### ISSUE TITLE
Upgrade "debug" dep to version 2.6.9 or greater

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1003]
As mentioned in gitter here: https://gitter.im/cypress-io/cypress?at=5a21f516ba39a53f1a0ccde4

https://nodesecurity.io/advisories/534

**Comment by brian-mann** [comment]
Sure, this is technically correct, but really Cypress is immune to most if not all security vulnerabilities because its locally run software - not a web server hosted in the cloud.

Something like this would be almost impossible to trigger unless the user of Cypress themselves caused this to happen.

**Comment by igniteeng000** [comment]
debug version is changed to 3.1.0. So you must close this issue.
