### ISSUE TITLE
Setup feature flags / toggles

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#1054]
## Development feature

Setup a way to implement features behind feature flags.

Probably add an object to `cypress.json` that would describe features (on/off) and value for "on" features.

```json
{
  "experimentalFeatures": {
    "featureA": false,
    "featureB": true,
    "featureC": "fast"
  }
}
```
So `featureA` is turned off, `featureB` is on, and `featureC` is on with value "fast"

**Comment by brian-mann** [comment]
`features` -> `experimentalFeatures` 

The name helps imply why these are off by default.

**Comment by jennifer-shehane** [comment]
I'm going to close this issue due to inactivity - we can always open a new issue if we intend to implement it in the future. For now, our users have access to pre-release versions of Cypress, but no feature flags are currently supported on the test runner. https://on.cypress.io/debugging#Hacking-on-Cypress

**Comment by Asalem1** [comment]
It would be a super cool feature to get in if this can be reopened and investigated? Our current workaround has been using window.set and/or window.store.dispatch to toggle feature flags in memory / in redux, but it's been pretty flakey. Any built in support would be greatly appreciated
