### ISSUE TITLE
Crash after allocation failure

### ISSUE THREAD

**Issue by jhartma** [cypress-io/cypress#1077]
- Operating System: Arch Linux
- Cypress Version: 1.2.0, but also all previous versions
- Browser Version: shipped Electron version

### Is this a Feature or Bug?
Bug

### Current behavior:
I have a quite extensive test suite running. On their own, the tests run just fine, but when I click on the "Run all tests" button in the electron window, Cypress crashes after a while. When running tests in the console, it works fine.

```bash
<--- Last few GCs --->

  272175 ms: Mark-sweep 1398.6 (1504.2) -> 1397.9 (1504.2) MB, 408.7 / 3.3 ms [allocation failure] [GC in old space requested].
  272755 ms: Mark-sweep 1397.9 (1504.2) -> 1397.9 (1489.2) MB, 579.9 / 35.7 ms [last resort gc].
  273252 ms: Mark-sweep 1397.9 (1489.2) -> 1397.5 (1489.2) MB, 496.1 / 33.5 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x149c585deba9 <a Window with map 0x8a3a160c709>
    1: StringReplaceGlobalRegExpWithFunction [native regexp.js:~448] [pc=0x154714707ecb](this=0x2ee831a2a489 <JS Global Object>,W=0x2bc4b839e749 <Very long string[1425151]>,C=0xeb37ade4db9 <JS RegExp>,aw=0x9e572c5521 <JS Function (SharedFunctionInfo 0x3e75501b2559)>)
    2: RegExpReplace [native regexp.js:~528] [pc=0x1547146cb455](this=0xeb37ade4db9 <JS RegExp>,D=0x2bc4b83...
```

### Desired behavior:
Should continue running tests

**Comment by brian-mann** [comment]
Closing this as a duplicate. This is a well known and documented aspect of Cypress. The GUI is not built to run all tests because of the way Cypress creates debuggability.

The CLI is the only place where you should be running all your tests and it opts for performance and longer runs as opposed to the GUI. The GUI is only there for test **writing** and iterations, whereas the CLI is there for **running** your tests to completion.

If you want all the details check out this issue - we have major changes coming to this (hopefully in Dec) which solve / address these issues.

- https://github.com/cypress-io/cypress/issues/681
- https://github.com/cypress-io/cypress/issues/990#issuecomment-348517774
- https://github.com/cypress-io/cypress/issues/416#issuecomment-337400871
