### ISSUE TITLE
timeout for "visit" https sites

### ISSUE THREAD

**Issue by maku** [cypress-io/cypress#1082]
- Operating System: win10
- Cypress Version: 1.3
- Browser Version: Chrome 63

### Is this a Feature or Bug?
Bug

### Current behavior:
browser executed by cypress shows that site is NOT secure (e.g. https://angular.io/)
(When opening the site in chrome myself the browser means that the site is secure....)
The result is that the loading of the page lasts a long time before I get  a timeout.

### Desired behavior:
Same "security" state for sites opened by cypress as when opened "manually"

**Comment by brian-mann** [comment]
The insecure / secure message is incidental and does not actually affect anything.

This is fundamental to the way Cypress works. It's a proxy layer that must alter the traffic coming in and out of the browser in order to do its automations. This is the only way to achieve this when testing `https` sites, but it does not affect the browser in any way (other than displaying that message).

"the loading of the page lasts a long time before I get a timeout" shouldn't have anything to do with this. However, Cypress is a proxy and it is shuttling the packets to the origin server and back into the browser - and there are a couple open issues related to it. 

In order for this to be actionable we'd need a much deeper analysis into what traffic is being slowed down and performance timings vs outside of the Cypress itself.

For more information you could read about this (we explain it in various places in our docs)

- https://docs.cypress.io/guides/guides/web-security.html#
- https://docs.cypress.io/guides/references/trade-offs.html#
- https://docs.cypress.io/guides/overview/key-differences.html#

**Comment by jennifer-shehane** [comment]
Closing as resolved - visiting https://www.angular.io is working in Cypress.
