### ISSUE TITLE
different env blocks

### ISSUE THREAD

**Issue by kemalbayar** [cypress-io/cypress#1114]
- Operating System:
- Cypress Version:
- Browser Version:

#### Test code:

in Cypress.json, It's not possible the following usage.

  "env": {
  
    "Access":"esdsdssad6d8sdf045dfge3sdf75a",
     "Access":"Abc"
 
} 

is it possible to define different "env" : { . } blocks  in order to use define variables with same name but different values in different blocks. So the variables with same name but has different values can be defined and used. (or it may be other way instead of defining different blocks)

**Comment by bahmutov** [comment]
This is impossible because JSON always overwrites the first property with the second one (same name). You can use this trick to have "comments" in JSON files

```json
{
  "Access": "a token used to access the resource",
  "Access": "Abc"
}
```

But it is impossible for Cypress to load this JSON and have multiple values of "Access". But you can work around this if you need different configuration settings, see how: https://docs.cypress.io/api/plugins/configuration-api.html#
