### ISSUE TITLE
Access cypress CLI from Global Mode

### ISSUE THREAD

**Issue by RandallKent** [cypress-io/cypress#1131]
Currently, when a user directly downloads Cypress and runs in Global Mode, they don't have access to run Cypress headlessly/via CLI.

This can create a bit of confusion when a user follows documentation on running Cypress headlessly or when setting up projects to record runs as the call to action points the user to run a command.

**Comment by Knaledge** [comment]
@brian-mann - what is the ETA on this, if any? I just ran into this (I believe) last night and it would be unfortunate to see global installation remain as seemingly dusty and underappreciated as it is.

**Comment by brian-mann** [comment]
@Knaledge what exactly would you like to do from global mode?

The biggest reason people were installing Cypress globally was because it was reinstall the large binary for each project. Now we cache the binary so it's not longer an issue.

I'm not sure how we could feasibly make CLI runs work when Cypress is already open - it kind of doesn't make sense. It needs to be run from the CLI in order to do that.

As long as you install this as a regular NPM module and run it from the CLI all should be good.

**Comment by jennifer-shehane** [comment]
We've since implemented a message preventing users from recording runs to the Dashboard from a direct download of Cypress and recommend they install Cypress as an npm dependency. 

![](https://user-images.githubusercontent.com/29389000/62674928-c9b51480-b9ce-11e9-94f2-3d8d1551cb6c.JPG)
