### ISSUE TITLE
Feature req: why is there not a global 'cypress start' and 'cypress stop' hook?

### ISSUE THREAD

**Issue by BasieP** [cypress-io/cypress#1146]
- Cypress Version: 1.4.1

I am aware of the 'before' and 'after' but they only work per block, and therefor per file.

Right now i have like 10 files in my 'integration' folder, each handling a specific part of my website.
I have to write 10 times a 'before' and 'after' hook, but i can make 2 function and just call them 10 times (a call in the before and after hooks of each file)

The goal i am trying to achieve is to host my webapplication (the one i want to test) before i start cypress, and then unhost it again when i stop cypress...

i don't want to host my application 10 times and stop it 10 times, i just want to host it once, and stop it once..

What are your thoughts on this?
is this even the way to go? or should i do the hosting outside of my cypress environment?
the problem with most npm package is that they only host a site, but then block the thread. running it in parallel is an option, but then i can never 'unhost' the site...

**Comment by BasieP** [comment]
right now i fixed it with the -k flag of the concurrently npm package..
this kills all 'other actions' if one exits.. so i start cypress together with my hosting. Then if cypress exits, the hosting gets killed..

see:
https://www.npmjs.com/package/concurrently

**Comment by brian-mann** [comment]
Starting and stopping a webserver from within Cypress is an antipattern that we've documented here and provided instructions on how to properly do it here as well:

- https://docs.cypress.io/guides/references/best-practices.html#Web-Servers
- https://docs.cypress.io/guides/guides/continuous-integration.html#Booting-Your-Server

As for repeating the same hooks 10 times - you don't have to do that - that's why `supportFile` exists. This file is served before any specs are run which enables you to put root level `before` and `after` hooks in one single file and it will apply to all specs. However keep in mind that `after` and `afterEach` hooks are also indicative of an anti pattern. If you're struggling to get something to "fit" into the Cypress model - it's likely because its like trying to fit a square peg in a round hole :-)

https://docs.cypress.io/guides/references/best-practices.html#Using-after-or-afterEach-hooks
