### ISSUE TITLE
blacklistHosts ignored from CLI?

### ISSUE THREAD

**Issue by combs** [cypress-io/cypress#1155]
- Operating System: OS X 10.12.6
- Cypress Version: 1.4.1 beta
- Browser Version: Chrome Version 63.0.3239.132 (Official Build) (64-bit)

### Is this a Feature or Bug?

Bug

### Current behavior:

I can't get blacklistHosts to work at all when invoking `cypress open`. Here are the things I've tried:

`export CYPRESS_blacklistHosts='adservice.google.com'; npx cypress open`
`npx cypress open --config blacklistHosts='adservice.google.com'`
`npx cypress open --config blacklistHosts="['adservice.google.com']"`

Yet blacklistHosts does not appear in the "Settings/Configuration" section. I also do not see the requests being intercepted.

### Desired behavior:

Works as described in documentation

### How to reproduce:

See above

#### Test code:

```js

```

**Comment by brian-mann** [comment]
I looked into this and found two bugs:

1. Passing `--blacklistHosts` via the `--config` option is not actually setting it.
2. When setting `blacklistHosts` in `cypress.json` it DOES get set, although it is **NOT** showing up in the resolved configuration area in the desktop app. However It is actually correctly 503'ing requests.

For now, hopefully you can set this in your `cypress.json`. We'll get both of these fixed - there must be something strange that `blacklistHosts` does that nothing else does because all of these configuration values run through the same logic.

**Comment by combs** [comment]
Thanks a lot for your help! I was wondering if my syntax was wrong, since I couldn't find any examples of passing arrays via cli in the docs. Glad it wasn't just me :)

**Comment by brian-mann** [comment]
Released in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).
