### ISSUE TITLE
Elements hidden using clip / clip-path css properties pass as visible

### ISSUE THREAD

**Issue by y2keeper** [cypress-io/cypress#1178]
### Current behavior:
Elements hidden using the CSS `clip` / `clip-path` properties pass visibility check.

### Desired behavior:
Visibility checks should fail as the element isn't visible.

### How to reproduce:
Hide any element using CSS `clip` / `clip-path` properties and define a test to check if it's visible. Test passes.

#### Test code:
```html
<div style="position: absolute;clip: rect(1px,1px,1px,1px);">
    <a href="#test">clip</a>
</div>

<div style="position: absolute;clip-path: polygon(0px 0px, 0px 0px, 0px 0px, 0px 0px);">
    <a href="#test">clip-path</a>
</div>
```

```js
describe('Clipped links', function () {
  it('should not be visible', function () {
    cy.visit('127.0.0.1')

    cy.get('a').should('be', 'vivible')
  })
})
```

### Additional Info (images, stack traces, etc)
While clip is deprecated clip-path is not. Unfortunately however clip is still used and supported so for the time being at least I think it should make visibility checks fail.

* Operating System: Windows 10 Enterprise
* Cypress Version: 1.4.1
* Browser Version: Chrome Version 63.0.3239.132

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-80) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Our calculations for visibility can be found here if anyone wants to contribute: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/dom/visibility.coffee

**Comment by jennifer-shehane** [comment]
The original test chainers were written incorrectly in the original comment, but nonetheless this is an error demonstrated below. You can clearly not see the elements on the page, but Cypress passes saying they are visible and fails when asserting they are not visible.

### index.html

```html
<!DOCTYPE html>
<html>
<head></head>
<body>
  <div style="position: absolute; clip: rect(1px, 1px, 1px, 1px);">
    <span id="clip">clip</span>
  </div>
  <div style="position: absolute; clip-path: polygon(0 0, 0 0, 0 0, 0 0);">
    <span id="clip-path">clip-path</span>
  </div>
</body>
</html>
```

### spec file

```js
it('should not be visible', function () {
  cy.visit('index.html')

  cy.get('#clip').should('be.visible')      // passes
  cy.get('#clip').should('not.be.visible')  // fails
})

it('should not be visible', function () {
  cy.visit('index.html')

  cy.get('#clip-path').should('be.visible')     // passes
  cy.get('#clip-path').should('not.be.visible') // fails
})
```

### `clip` DEPRECATED

>The `clip` CSS property defines what portion of an element is visible. The `clip` property applies only to absolutely positioned elements, that is elements with `position:absolute` or `position:fixed`.

### `clip-path`

>The `clip-path` CSS property creates a clipping region that sets what part of an element should be shown. Parts that are inside the region are shown, while those outside are hidden.

Honestly, I cannot guarantee that we will support testing of `clip`, as adding support for deprecated properties is not something we generally do - especially since just at a cursory glance, I think supporting this will take a good amount of effort to calculate correctly. 

I've added a failing test for clip-path to this PR: https://github.com/cypress-io/cypress/pull/4421

**Comment by jennifer-shehane** [comment]
This is still incorrectly failing in Cypress 4.9.0.

**Comment by panzarino** [comment]
After investigating this issue for quite a while, I recommend that we either de-prioritize it or close as won't fix. First, `clip-path` isn't a commonly used way to hide content, and if it is, it's most likely in place of a better practice anyways. This issue has been open for around a year and a half now, and has no upvotes (compared to other more-requested fixes, which all have at least a couple).

In addition, the fix is quite technical. For starters, there's no way to easily get the dimensions of the clipping. The process would have to entail [converting the clip-path to an svg](https://stackoverflow.com/questions/50838485/easiest-way-to-convert-polygon-clip-path-to-microsoft-edge-supported-clippath), for which there is currently no standard library, so we would have to parse the value ourselves and convert that into a svg element. Next, we would have to see if that svg actually overlaps the underlying content, which we could do through `checkIntersection` or `getIntersectionList`, but [neither are supported in Firefox](https://developer.mozilla.org/en-US/docs/Web/API/SVGSVGElement#Browser_compatibility).

A different potential solution would be assigning an on click handler, which would only be executed when the underlying element was actually clicked on. However, there is no guarantee of what part of the element would be exposed. For efficiency, we could test the center, then each of the corners, and then just each pixel linearly, but there is still the case that we might have to click on every single possible pixel. With that said, I can't see a solution like this that is efficient and flake free and this issue should be de-prioritized.

(Selenium does [visibility checking](https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/atoms/dom.js#L460) in a similar way to us, and does not handle `clip-path` at all, nor has any issues about it).

**Comment by vacas5** [comment]
using `clip-path` to visually hide elements but leave them available for screen readers is a commonly used paradigm in front end development. https://www.a11yproject.com/posts/2013-01-11-how-to-hide-content/

Is there any way to use a class like this in conjunction with Cypress visibility?

**Comment by panzarino** [comment]
@vacas5 You could potentially assert on the `clip-path` css property directly with `have.css` or assert that the element should `have.class`. As explained above, for technical reasons, there are no plans to incorporate checking for `clip-path` directly into the visibility assertion.

**Comment by mikkorantalainen** [comment]
As the most common use of these properties is to hide the whole element without removing it from the DOM for accessibility purposes, maybe support only two special cases:

- clip: rect() with 4 identical lengths as arguments. Though I think supporting only rect(0, 0, 0, 0) should be enough because any other way to clip everything only results in longer strings.
- clip-path: polygon() for whatever count of zero length pairs as arguments. (Note that you might need to support both polygon(0px 0px, 0px 0px, 0px px) and polygon(0 0, 0 0, 0 0, 0 0) here. Again, I think supporting only verbatim polygon(0 0, 0 0, 0 0) should be enough for all practical purposes.)

And simply document that for all other cases, the clip and clip-path properties will be ignored.

**Comment by danatemple** [comment]
I agree mith @mikkorantalainen , this technique is even documented on w3.org as a best practice to make invisible-but-accessible elements:

https://www.w3.org/WAI/WCAG21/Techniques/css/C7

I know its tricky but it's just another difficulty making things accessible if we can't test it.
