### ISSUE TITLE
Allow reusing cy.server() in several tests and hooks

### ISSUE THREAD

**Issue by Sumolari** [cypress-io/cypress#1183]
### Is this a Feature or Bug?

Feature.

### Current behavior:

`cy.server()` is reset after each test case (`it`) is run. This makes impossible things like this:

```
describe
-> before :: something that needs to wait for a XHR request
-> it :: several tests waiting for requests
```

We could do:

```
describe
-> before :: set up cy.server()
-> before :: something that needs to wait for a XHR request
-> it :: several tests waiting for requests
```

But the second test will fail as current server will have been reset (it's reset [here](https://github.com/cypress-io/cypress/blob/2b2b6d99a9f1bf232d9c7396b25390913d5f2b18/packages/driver/src/cy/commands/xhr.coffee#L233)).

We could do:

```
describe
-> before :: set up cy.server() for before hooks
-> before :: something that needs to wait for a XHR request
-> beforeEach :: set up cy.server() for tests
-> it :: several tests waiting for requests
```

But then we have to set up the server twice.

### Desired behavior:

Cypress should expose a way to tell `cy.server()` that we don't want to reset the server before each test or one way to tell that we want to preserve aliased routes.

**Comment by brian-mann** [comment]
Strongly related to this: https://github.com/cypress-io/cypress/issues/686

**Comment by akshayjai1** [comment]
Had a doubt, if someone could answer https://stackoverflow.com/questions/59781881/is-it-ok-to-call-cy-server-twice-in-same-test-in-cypress

**Comment by jennifer-shehane** [comment]
The features requested in this issue are now possible as part of `cy.route2()`. 

`cy.route2()` is currently experimental and requires being enabled by passing `"experimentalNetworkStubbing": true` through your Cypress configuration. This will eventually be merged in as part of our standard API. 

**Please see the `cy.route2()` docs for full details: https://on.cypress.io/route2**

If you encounter any issues or unexpected behavior while using `cy.route2()` we encourage you to [open a new issue](https://github.com/cypress-io/cypress/issues/new?assignees=&labels=&template=bug-report.md&title=) so that we can work out all the issues before public release. Thanks!
