### ISSUE TITLE
[QUESTION] How to use array of folders or expression on 'integrationFolder' property

### ISSUE THREAD

**Issue by angel-git** [cypress-io/cypress#1189]
If you have in your project your tests files splitted in different modules but Cypress configuration only accepts one folder where all tests are located, you can only run tests from 1 module at the time.

You could create in that folder a huge javascript that imports the rest of the files but that breaks the notion of modules.

Could be nice to have something like:

```
integrationFolder: ["moduleA/tests", "moduleB/test", ....]
```

Any advice?

Thanks!
PS: Sorry if this was already opened, i tried to search but couldn't find anything.

**Comment by jennifer-shehane** [comment]
I feel like this should be achievable when we enable to pass an argument as a glob for which specs you want to run (which is in progress at the moment) https://github.com/cypress-io/cypress/issues/681

**Comment by brian-mann** [comment]
That will enable you to run specs but really `integrationFolder` is the mounting point for listing out the specs and understanding the relationship of the pathing. We chose to go this route because of the nesting of `cypress/integration` and all of the other sibling folders. The idea is that e2e tests are not strictly coupled to source code and therefore belong in their own folder instead of next to the code (like unit tests are)

**Comment by jennifer-shehane** [comment]
Closing as delivered. Please see [--spec argument docs](https://on.cypress.io/command-line#cypress-run-spec-lt-spec-gt)

**Comment by aarondotsteele** [comment]
This does not solve the issue. Implementing like angel originally posted would be ideal:
integrationFolder: ["moduleA/tests", "moduleB/test", ....]
