### ISSUE TITLE
Option to disable auto-rerun

### ISSUE THREAD

**Issue by sarahgracesmith** [cypress-io/cypress#119]
Currently, the re-runs automatically every time the the test code changes. For some tests this is undesirable, particularly if test data is being created with every test run. Would be great to be able to disable this feature.

**Comment by brian-mann** [comment]
Fixed in [`0.15.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0152-04032016).

**Comment by brian-mann** [comment]
We discussed this at length as a team, and all agreed this is really the first configuration option which we should be a local option instead of inside the global `cypress.json`. 

Having specific localized options is a feature that's down the road so as a workaround we implemented this option like all other configuration options.

What I recommend is setting `watchForFileChanges` in your `cypress.json` but not checking that change into source control. That will essentially allow you to turn off file watching and not share this option with anyone else. It's not great, but it will work.

Down the road we're going to update the CLI tool and environment variables to automatically be able to override the configuration found in `cypress.json`. Currently they do not do this.

However we have to do a good bit of work to make that happen (and also make it easy to see and understand what has or hasn't been overridden in the GUI). 

Lastly because we package Cypress as a desktop application environment variables set in bash do not actually take effect, which is another reason we decided to keep this in `cypress.json` for the moment.

**Comment by brian-mann** [comment]
As of [`0.15.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0153-04102016) and `0.11.0` of the [Cypress CLI](https://github.com/cypress-io/cypress-cli) tool you can now pass `--config` overrides when using `cypress open`.

That would be a much easier way for changing just your configuration without having to fuss with making modifications to `cypress.json` and not checking in those changes to git.

Example you can now do:

````bash
cypress open --config watchForFileChanges=false
```

This option will persist onto any project you now open from inside of Cypress.

You can also use the `--config` flag on both `cypress run` and `cypress ci`
