### ISSUE TITLE
Can type definitions be more automatic for beginners?

### ISSUE THREAD

**Issue by NicholasBoll** [cypress-io/cypress#1236]
I've seen a lot of people ask how they can get type definitions for Cypress in JavaScript. As it is right now, this in not automatic. We spent a lot of time getting type definitions to "just work" for Cypress commands and various aspects of the Cypress API, but many people aren't getting that benefit. I've seen some people have success making a `tsconfig.json` file to force the TypeScript language service to work with Cypress type definitions. This definitely works better for VSCode. I've seen people give up trying to get it to work with WebStorm before just switching to VSCode.

I use the `tsconfig.json` approach since my projects are written in TypeScript and that config file already exists. I don't have much experience with VSCode or other editors writing JavaScript and how types are pulled in. For most libraries that have exports, type definitions should be pulled in with a `.d.ts` file next to the source sharing the same base name. Cypress defines globals so type definitions files need to be manually included. Maybe a solutions is for when Cypress lays down support files (config, folders, examples, etc), also lay down a `tsconfig.json` file? Anyone with experience with WebStorm or editors? Would that solution work?

- Operating System: N/A
- Cypress Version: 1.4.1
- Browser Version: N/A

### Is this a Feature or Bug?
Feature

**Comment by jennifer-shehane** [comment]
I think some documentation on the subject in our docs could also mitigate some of the issues for beginners.

I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to get the ball rolling here: https://github.com/cypress-io/cypress-documentation/issues/400. Our documentation is open source and contributions are welcome. 😄

**Comment by bahmutov** [comment]
I agree with you @NicholasBoll and was thinking along the same lines. I setup json schema `cypress.json` in VSCode once using https://docs.cypress.io/guides/references/configuration.html#IntelliSense and just enjoy it so much! I want the same experience for Cypress `cy.get ...` typing as well. I still have not found a reliable way to get IntelliSense in VSCode. Maybe this is because of globals, and if we allowed importing local NPM api it would work better.

**Comment by bahmutov** [comment]
Actually I found a perfect way to use our types @NicholasBoll 

Just add a comment to the JS spec file

```
/// <reference types="Cypress" />
```

Nothing else is necessary (neither typescript compiler, not `jsconfig.json`, nor `tsconfig.json`).

Example: spec file without anything. No IntelliSense

<img width="691" alt="spec" src="https://user-images.githubusercontent.com/2212006/35538205-076e4374-051b-11e8-9311-3d91e786f354.png">

Spec file with reference comment: full IntelliSense in VSCode

<img width="716" alt="spec-with-reference" src="https://user-images.githubusercontent.com/2212006/35538242-1b2cf6ee-051b-11e8-844b-ce13fedc7be3.png">

**Comment by bahmutov** [comment]
I could get IntelliSense to work in Atom (but it is much much worse) using TypeScript package and only in TS files

<img width="965" alt="atom" src="https://user-images.githubusercontent.com/2212006/35538692-c86cd2ce-051c-11e8-91e6-bbd357525db5.png">

So my personal workflow for now would be to add reference comment to spec JS files to enable IntelliSense.

**Comment by bahmutov** [comment]
Yes, I agree - and for JS spec files using reference might be the fastest way to get IntelliSense

**Comment by NicholasBoll** [comment]
So maybe having Cypress example code that uses the reference directive (`/// <reference types="cypress" />`) with some notes in the documentation would be enough to close this issue?

Creating a `tsconfig.json` is possible, but might have too many edge cases.

**Comment by brian-mann** [comment]
@jennifer-shehane can you look at this / reference this issue in your PR for a `Tooling` section in the docs? Thx

**Comment by jennifer-shehane** [comment]
As brian mentioned, I've opened a WIP pull request for a doc specific to TypeScript support. I would love input + content suggestions as I am fairly new to *using* TypeScript myself! https://github.com/cypress-io/cypress-documentation/pull/466

**Comment by NicholasBoll** [comment]
I think the triple-slash directive is a good quick solution to JS files. If the Cypress files are written in TypeScript, the developer should add a `tsconfig.json` in the Cypress folder with something like the following:

```ts
{
  "compilerOptions": {
	"strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"],
  },
  "include": [
    "**/*.ts"
  ]
}
```

The `"types"` vs `"includes"` will make sure there are no conflicts with type definitions included in the developer's app (like jQuery or chai). The `tsconfig.json` should be in the Cypress directory, not the base directory to reduce conflicts with the project's TypeScript config. I added a comment in the docs pull request and a comment in #1152. The TypeScript recipe should be updated for this as well.

**Comment by jennifer-shehane** [comment]
There are new docs explaining how to configure TypeScript support. We would love any feedback on whether our recommended setup solves the issues laid out in this issue. https://on.cypress.io/typescript-support

There is also a new issue open proposing more "native" support of TypeScript (less config) if anyone has suggestions they'd like to add there: https://github.com/cypress-io/cypress/issues/1859

I am closing this issue, but please feel free to comment here again with any feedback/confusion!

**Comment by greggb** [comment]
@jennifer-shehane I'm using js for my project, but have type checking turned on in VS code. Something that tripped me up was missing `allowJs: true` and `"**/*.js"` in `includes` within the `tsconfig.json` file in the cypress directory. 

Not sure how common this is, but may help anyone who is having issues with type errors in their `js` files.

**Comment by haf** [comment]
I'm also trying to get this set up; I've followed the guide as near as I could (but I did install cypress with yarn). I can start cypress and I can write tests, but I can't get typescript code competition to work, despite follow the docs and disabling any plugins I can imagine disrupt code completition. Here's what my workspace looks like:

<img width="1680" alt="screen shot 2018-09-23 at 14 06 57" src="https://user-images.githubusercontent.com/193115/45927854-44517e80-bf3a-11e8-8786-b3ceca8156f6.png">

<img width="1633" alt="screen shot 2018-09-23 at 14 07 39" src="https://user-images.githubusercontent.com/193115/45927856-49aec900-bf3a-11e8-8cc9-74ff3d6c0d2e.png">

I've tried with `tsconfig.json` in both project root (one below) and in `cypress/` folder, but to no avail. I've also `npm install -g typescript` to get the compiler, so that these command show their respective outputs https://code.visualstudio.com/docs/languages/typescript. Also, like you can see, I've added the triple-slash directive on top of the file.

**Comment by bahmutov** [comment]
Yes I was thinking the same: add to the docs notes how to restart ts server in vs code
