### ISSUE TITLE
Cypress proxy fails on a POST request with a large cookie value

### ISSUE THREAD

**Issue by megantiu** [cypress-io/cypress#127]
**Description**
When making a POST request with a large cookie, the request returns a 413 instead of proceeding successfully.

In my case, the app I'm testing is making a POST request independent of the the Cypress test, which is for the UI.

**Comment by brian-mann** [comment]
I started working on this issue and created a test around it, but cannot get it to fail.

Are you still having this problem as of `0.16.0`? If so we may need to get on screenhero again because I cannot recreate this problem. I'm using the cookie you sent me but cannot get the proxy to return `413`.

What was the url you were POSTing against?
