### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by dz902** [cypress-io/cypress#1303]
- Operating System: macOS Sierra
- Cypress Version: 1.4.2
- Browser Version: Chrome 64

### Is this a Feature or Bug?
Bug

### Current behavior:
Routing not working

### Desired behavior:
Routes correctly

#### Test code:

```
cy.server({ force404: true });

cy.fixture('000.xml').as('basicxml'); // using alias or not makes no difference
cy.route('GET', '/xml', '@basicxml');
cy.visit('/xml');
cy.wait('@basicxml'); // this was added, no effect

// tried raw XHR, no effect

var xhr = new XMLHttpRequest();
xhr.open('GET', '/xml', true);

xhr.onload = function () {
      // Request finished. Do processing here.
};

xhr.send(null);

// fetch was polyfilled and tested, no effect

fetch('/xml')
        .then(response => response.text())
        .then((xmlString) => {
              alert(xmlString); // shows an Cypress error document
              expect(xmlString).to.be.string; // does not even show up in console list
         });
```

### Additional Info (images, stack traces, etc)
![image](https://user-images.githubusercontent.com/2723003/36161185-0585967a-111e-11e8-8ad8-ddccb7333c20.png)

I followed examples on manual but this is not working...In browser console shows 404, which means routing is not in effect I guess.

![image](https://user-images.githubusercontent.com/2723003/36161247-2433a7c4-111e-11e8-99df-bc8e9a660967.png)

Not sure about why this happens, or am I doing something really stupid?

**Comment by brian-mann** [comment]
You're misunderstanding `cy.route`. This is for routing XHR's - not visits.

In your test code you are visiting `/xml`. The error is telling you the example problem - you didn't provide us a webserver, so we are assuming that you want Cypress to statically serve this file. We looked to try to serve this file but it was not found.

`cy.route` is for routing XHR's **coming from your application** which you have to `cy.visit` first. Creating an XHR inside of test code won't cause anything either - because Cypress is only bound to look at XHR's coming from your application, not your test code.

You need to visit a legitimate site or app first, and then when that site or app makes an XHR that matches the route it will send back the response.

**Comment by dz902** [comment]
Right...I was using Cypress as a unit test tool, that's the problem. Just found out #318, looking forward to it.

Thanks a lot!
