### ISSUE TITLE
Headless runner screenshots use the last width of interactive test runner

### ISSUE THREAD

**Issue by dallonf** [cypress-io/cypress#1309]
Mentioned and diagnosed in https://github.com/cypress-io/cypress/issues/181#issuecomment-365407977.

- Operating System: macOS 10.12.6
- Cypress Version: 1.4.2
- Browser Version: Google Chrome 64.0.3282.140

### Is this a Feature or Bug?

Unintuitive feature

### Current behavior:

The headless runner will have a test runner panel just as wide as the panel from the last time you used the interactive runner. This can result in a hilariously small view for the tested page itself:

![apps page -- shows keys not including af keys](https://user-images.githubusercontent.com/346300/36176772-5c95efe0-10d9-11e8-84cf-6d8cd798bbbb.png)

### Desired behavior:

I would say it should use a static but configurable width in headless mode (separate from its width in interactive mode). Another solution could be to cache the _percentage_ of the window's width instead of the actual pixels, so that it's always proportional.

### How to reproduce:

1. Open an interactive test runner
2. Size your window to take up your entire screen
3. Size the test runner sidebar to be comfortably large
4. Run the tests in headless mode (with `viewportWidth` set to the default of 1000)
5. Check the outputted video or screenshots

**Comment by brian-mann** [comment]
It depends on your operating system. We store it where the operating system is supposed to store application settings.

Open up cypress and goto File -> View App Data

Then goto `production/projects/{your_project}/state.json`

If you use Cypress in global mode then it would be: `production/state.json`

**Comment by braden-m** [comment]
Thanks, that's worked great! That was the one hurdle we had remaining with Cypress to setting up visual diffing in our workflow.

**Comment by brian-mann** [comment]
@braden-m do you mind explaining what your visual diffing workflow is?

We're looking at implementing this in Cypress now and it would be helpful to understand your process. What are you diffing? Where are you storing the masters? In source control? Where do you perform the visual diff checks? CI? What's the process for approving new ones?

**Comment by braden-m** [comment]
We take screenshots through headless Cypress during our usual E2E tests. Masters are stored in source control, though the process for updating/approving them is manual (i.e. copying the updated screenshots from `screenshots` into `screenshots-base`. A process of accepting/rejecting new screenshots on failure locally could be our next step). 

After Cypress has been run, visual diffing is done using `blink-diff` as a separate script on CI, with the output saved to `screenshots-diff` (saved as a Buildkite artifact).

We use `blink-diff` over, say, `pixelmatch`, for the ease of cropping images (since the test runner tab and URL will not be constant between our tests, we remove it).

**Comment by brian-mann** [comment]
Right. But when the screenshots fail - what do you do?

You go inspect the buildkite artifacts and then manually reconcile? You have to go see if its a legitimate failure?

And what if its a natural change? You copy the buildkite artifact and then update your master in source? And then rerun all the tests?

**Comment by brian-mann** [comment]
Since you're using a single environment as the source of your screenshots (linux / chrome) what do you do about taking screenshots locally?

What I mean is - if you **know** something is changing, there's no way to take the screenshot locally and update the masters because they won't match what CI outputs... in that case you just **wait** for them fail in order to generate them correctly and then update the masters in source?

**Comment by braden-m** [comment]
Though we're still in early stages of integrating with CI, it appears that running Cypress headlessly, both locally and on CI, produces the same screenshots (provided `reporterWidth` is cleared, since this could be changed locally).

Because of this, we can produce and update screenshots locally.

**Comment by brian-mann** [comment]
Are you taking screenshots locally in the same environment as CI?

What I mean is - there is no way linux (which has disabled GPU) renders pixels the same way that OSX does (or Windows for that matter).

Your environments would all have to be perfectly homogenous. Is this the case? Or are they different?

**Comment by brian-mann** [comment]
Or perhaps you have the blink-diff threshold set relatively high to account for those differences

**Comment by brian-mann** [comment]
Related to #2132

**Comment by rodoabad** [comment]
Any ETA on when we can have a fix for this?
