### ISSUE TITLE
Add Directory Argument to `Cypress open`

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#1316]
### Is this a Feature or Bug?
Feature

### Current behavior:
launching Cypress globally (after installing via `npm i -g cypress` and launching with `cypress open`) always takes you to the "select a folder" screen.
It would be nice to run `cypress open path/to/project-directory/` or `cypress open .` to launch the global install pointed to the current directory (similar to running `code .` to open a vscode instance in the current directory).

### How to reproduce:
* globally install cypress
* `cypress open .`
you are met with the 'select folder' screen
**desired**:  
cypress opens in the current directory (finds the tests in `./cypress/integrations`)

### Additional Info (images, stack traces, etc)
I understand this is not the recommended way to run cypress, but if you have a bunch of little projects it would be nice to have this feature

**Comment by brian-mann** [comment]
I believe this is already possible and supported with the `--project` argument.

Can you confirm and close if this meets your needs.

https://docs.cypress.io/guides/guides/command-line.html#cypress-open

I understand what you're saying about global mode basically looking at `cwd` and figuring out that if there is a `cypress.json` then automatically open "to that project".

But that would create a potentially very weird scenario - where the first time in a new project you do `cypress open` you'll see it in global mode (since there is no project yet) - and then the 2nd time you issue it, cypress would then just "open" to that project.

If we didn't do that either - and just always "opened" to the current `cwd`, then essentially there would be no global mode at all. That's why we require the `--project` flag - because without it, we can't even tell if you've opened it from the command line, or whether or not you've double clicked on the installed Application.

**Comment by Bkucera** [comment]
wow, can't believe I missed this. I only looked at `cypress --help` but not `cypress open --help`
