### ISSUE TITLE
WebSockets SSL issue

### ISSUE THREAD

**Issue by benhowdle89** [cypress-io/cypress#1325]
### Current behavior:
I know it says in the docs that Cypress supports WebSockets, but I have an issue I hope I can articulate clearly. We have a secure websocket server running, that we connect to via JavaScript on wss://[server]

I can open the client-side application in the browser, and it connects to the WebSocket fine. 

However, when I run my tests in Cypress, it errors in the console with `websocket opening handshake was canceled`. If I open a new tab (within the Chrome instance Cypress is controlling, and visit the URL of the WebSocket server itself, I see the WebSocket connect fine), I can then go back to the tab with the running tests and it's connected. My guess is that the browser session is using/hitting the correct SSL certs to authenticate with the WSS in the new tab, but because Cypress modifies the traffic between browser/server, I'm thinking it's changing something for the worse?

### Desired behavior:
The browser tab that Cypress runs the tests in to respect the same behaviour as opening a new tab and visiting the WSS directly.

- Operating System:
Linux
- Cypress Version:
1.4.2
- Browser
Chrome

**Comment by brian-mann** [comment]
Cypress definitely works on the `wss://` protocol - which is secure websockets. We have tests for this and you can visit random sites on the web that use this and it works.

With that said - it sounds like you are experiencing a real issue - it just may be different one than this. For us to investigate we'll **have** to have a reproducible repo, or a public URL or test code or something in order to see it on our end - else there's nothing we can do :-(

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
