### ISSUE TITLE
modifyObstructiveCode hangs on huge responses

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#1330]
Users with massive `.js` files (in the several megabytes) can cause the network proxy response stream to choke when scanning for obstructive code.

Need to look at improving the performance of the scanner.

For now users can turn off `modifyObstructiveCode` in their `cypress.json` file.

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/1331

**Comment by brian-mann** [comment]
Released in [`2.0.1`](https://docs.cypress.io/guides/references/changelog.html#2-0-1).

**Comment by marcsanchez1** [comment]
I'm seeing a similar bug to the one stated above if not the actual bug. When I turn off 'modifyObstructiveCode', I'm getting the following message, "Whoops, there is no test to run." When I turn it back on, it'll work fine. I have a scenario when my test is opening up to its own window and from what I've read, this is because of 'Window.top' and the only way to get around it is to disable modifyObstructiveCode since we can't remove 'window.top'. Are there any other solutions?
![Screen Shot 2019-09-17 at 4 02 01 PM](https://user-images.githubusercontent.com/13281106/65075329-b5b4e900-d964-11e9-8252-d8fa88a5c367.png)

Thank you

**Comment by jennifer-shehane** [comment]
@marcsanchez1 this is a really old specific case that was fixed in 2.0.1, so you're issue is likely very different - open a new issue with a reproducible example.
