### ISSUE TITLE
Trying to test Login via Auth0 causes error in Test

### ISSUE THREAD

**Issue by Stormdoodle** [cypress-io/cypress#1344]
- Operating System: windows 8
- Cypress Version: Beta version 1.4.1
- Browser Version: Chrome v63.0.3239.108 (64bit)

### Is this a Feature or Bug?
??

### Current behavior:
below is my current test. 
It accesses our internal application and clicks on the login button, at which point it tries to access Auth0 login to verify the login account, but the test errors as it is blocked from accessing a cross-origin frame.

### Desired behavior:
Ideally I would like to create a login test that will go through the Auth0 process and get me to the main page of our application

### How to reproduce:
//

#### Test code:
```js
describe('My Login Test', function (){
    it('Visit Risk App Landing Page', function (){
        cy.visit('http://localhost:3000/workflow')
        cy.get('button').click()
    })
})
```

### Additional Info (images, stack traces, etc)

Is there another way around this?  Would setting chromeWebSecurity to false solve this problem?

I found a page that suggested a Window.postMessage() may help with the issue - https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage However my coding experience is very limited and I don't understand how to implement it.

Any help that can be provided would be appreciated.

**Comment by Stormdoodle** [comment]
I have managed to change the chromeWebSecurity to False and this has solved my problem, partly.  I can now access Auth0 and login, but my application still doesn't load to continue testing.  Is this because I'm going from an 'external' site back to a local one?

**Comment by brian-mann** [comment]
Your issue has been brought up several times in here. In fact someone opened an issue basically asking for the same thing (except it's about Azure) instead of auth0 just a few hours ago.

You're all testing SSO - a 3rd party login system that handles that actual username/password and credentials which is configured to send back a token to your system upon successfully logging in.

In 100% of these cases, it is not necessary - nor is it a good idea to test 3rd party sites you don't control - even authentication systems. There are a lot of reasons that are too much to explain in this post, but with this said it is still absolutely possible to test the integration correctly and still get 100% confidence.  Please read my response to this issue: https://github.com/cypress-io/cypress/issues/1342#issuecomment-366747803

We (the Cypress team) are talking at a conference later this week and I am specifically giving a talk about "Best Practices" including how to login to your application when you're going through a 3rd party provider. It will illuminate how to do it properly. We'll integrate that content into the docs to hopefully help more people understand why it's more challenging, and how to approach testing it.

**Comment by Stormdoodle** [comment]
Thanks for the response.  I will look forward to reading about these best practices once they are published.

Further to my initial question.  Would I be able to use cy.request to get a response from Auth0 to allow me to login to my application?

**Comment by brian-mann** [comment]
Yes you can use `cy.request` to talk to any API programmatically.

**Comment by brian-mann** [comment]
Here's my talk I gave at AssertJS that answers many of your questions.

https://www.youtube.com/watch?v=5XQOK0v_YRE

**Comment by johnnyreilly** [comment]
Hey guys!

I was mulling this very problem this weekend.  I came up with a solution which seems solid.  I've blogged about it here:

https://blog.johnnyreilly.com/2018/07/cypress-and-auth0.html

I'm still very much a Cypress novice and so it's possible my advice here might not be 100% perfect.  Please do feel free to set me straight if there's any bad advice in my post.  Happy to improve it; I want to spread good advice, not bad.
