### ISSUE TITLE
Snapshot unavailable on example_spec.js on version 2.0.2 

### ISSUE THREAD

**Issue by perceboisElisa** [cypress-io/cypress#1355]
Hi,

I have updated cypress.io from version 1 (I don't know exactly the number of first version) to 2.0.2. However, when I run example_spec.js, the snapshot is missing for several kinds of commands. Is it correct ?
I don't have the remember on the previous version...
Thanks!

My Settings:
- Operating System: Mac High Sierra 10.13
- Cypress Version: 2.0.2
- Browser Version: chrome Version 64.0.3282.167

**Comment by jennifer-shehane** [comment]
Snapshots are only displayed for the last `numTestsKeptInMemory`. The default value for this is 50. So, the last 50 tests of the example will have snapshot data. 

We are working on splitting up the tests in the example (which has more than 50 tests), because it's more tests than you should really have in one spec without suffering from performance issues. 

We could probably explain this better in the error message:

<img width="1036" alt="screen shot 2018-02-20 at 3 45 36 pm" src="https://user-images.githubusercontent.com/1271364/36448292-2371b2b8-1655-11e8-81fd-ce210aa709fd.png">

**Comment by brian-mann** [comment]
See this issue for all the glorious details. https://github.com/cypress-io/cypress/issues/681
