### ISSUE TITLE
Propose: Providing the service for get cypress status's badge.

### ISSUE THREAD

**Issue by imcuttle** [cypress-io/cypress#1367]
I saw the related issue https://github.com/cypress-io/cypress-documentation/issues/71

But the badge is settled style, I want to get the status dynamically by `https://example.com/${projectId}.svg?...`

**Comment by jennifer-shehane** [comment]
This is something we proposed to provide from the [dashboard](https://dashboard.cypress.io), similar to other CI services, so that you can go into a project's setting and get a generated badge.

**Comment by ludmilanesvitiy** [comment]
@jennifer-shehane @bahmutov Hello team!
Do we have any possibility to create such badge now? Because will be very nice to include badge with the status of Cypress run to our page: https://valor-software.com/ngx-bootstrap/#/documentation#getting-started

**Comment by jennifer-shehane** [comment]
@trydionel Services issue ^

**Comment by skylock** [comment]
Any updates on this, please ?

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.
