### ISSUE TITLE
Test for cy.click() loads many links

### ISSUE THREAD

**Issue by Peggy1012** [cypress-io/cypress#1388]
- Operating System: WIn 10
- Cypress Version: 2.0.2.
- Browser Version: Chrome 63

### Is this a Feature or Bug?
Bug

### Current behavior:
`cy.get('a[href="/services/all/"]').first().click()` load many links

### Desired behavior:
`cy.get('a[href="/services/all/"]').first().click()` load one link

### Additional Info (images, stack traces, etc)

![url](https://user-images.githubusercontent.com/22873782/36786488-d2987c54-1c86-11e8-86da-f057ed73c99f.png)

**Comment by brian-mann** [comment]
Hello!

Thanks for opening an issue. Unfortunately it's not clear, and there's not enough information in this issue for us to investigate if and what the bug may be.

For instance - it's unclear what you mean by "load many links". The screenshot provided shows the URL changing several times, but its unclear what the expected and correct behavior would be.

For us to look into this, we'd have to have a reproducible repo and a clear understanding of what Cypress is supposed to be doing. It looks as if you're trying to log in, but I can't be sure that's what it is.

**Comment by brian-mann** [comment]
Hmmm I just noticed that this is your 2nd test. I am going to guess here the problem is that you are building up state between your tests - that you are logging in the first test, and then running the second test without logging in. 

Cypress will automatically clear sessions in between tests to prevent tests from building up state. There are API's to preserve cookies to prevent this - but it's an anti pattern.

Here's a couple links to the docs that explain all of this - and a much large issue that explains what we need to do better to communicate this.

- https://docs.cypress.io/guides/references/best-practices.html#Having-tests-rely-on-the-state-of-previous-tests
- https://docs.cypress.io/api/cypress-api/cookies.html#
- https://github.com/cypress-io/cypress/issues/686
