### ISSUE TITLE
Proposal: new command for communicating between tests and a plugin event

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#1406]
Create a new command, `cy.task()`, that will send a message that can be received by a plugin event, allowing the user to write arbitrary code to be executed in node and return the result.

The code in the plugin can return a value or return a promise that resolves a value. That will become the value yielded by the command.

It can also throw an error or reject the promise to fail the command.

Returning undefined from the 'task:requested' event in the plugins file will cause an error, to help prevent missing a task event and help debug instead of just failing for subtle reasons. A user will be able to return `null` if they explicitly don't want to return a value.

Example:

```javascript
// in spec.js
cy.task('createUser', { email: 'chris@cypress.io' }).then((user) => {
  // user is the object returned by the plugin
})
```

```javascript
// in plugins/index.js
module.exports = (on) => {
  on('task:requested', (event, arg) => {
    switch (event) {
      case 'createUser': {
        // arg === { email: 'chris@cypress..io' }
        // create user and return it
      }
     }
  })
}
```

**Comment by brian-mann** [comment]
Some additional thoughts...

When users start requiring their `lib` code directly from plugins (their own node code like models, db stuff, etc) we will likely run into transpilation issues since people want to use features that don't exist in node `8.x.x`.

We need to demonstrate how you would do this (like using a babel hook in `plugins/index.js`).

Also - we need to make it clear that because we're awesome we automatically watch the entire dependency tree from `plugins/index.js` which means that any file changes you make to your node files will **automatically** get reloaded on changes.

**Comment by brian-mann** [comment]
For docs: we need to explain the use case of this.

**Example:**
- You have three ways to communicate with the outside world (outside the browser)
- `cy.exec` to execute system command
- `cy.request` to make HTTP request
- `cy.task` to talk directly to node (in plugins) that enables you to require any of your own node code

This is useful for things like:

- resetting a database
- seeding a database
- creating records in a database
- querying the database
- storing state in node that you want persisted (since the driver make do full refreshes on visits)
- performing parallel tasks (like making multiple http requests outside of cypress)
- running an external process (like spinning up a webdriver instance of another browser like firefox, safari, or puppeteer)
