### ISSUE TITLE
Uncaught TypeError Received from application not loading page in Cypress

### ISSUE THREAD

**Issue by OhAye** [cypress-io/cypress#14169]
When trying to visit a Webpage the application returns an Uncaught TypeError message. If I run this webpage on a normal Chrome tab I can still view the page but in Cypress explorer, it doesn't load the page correctly. The page is open to the public and the error can be reproduced. I am on the latest version of Cypress and this is the first time I have tried to run this test. 

### Current behavior

![image](https://user-images.githubusercontent.com/16784358/102063865-7cc92580-3dee-11eb-90c5-ff862aac5596.png)

### Desired behavior

![image](https://user-images.githubusercontent.com/16784358/102063965-9cf8e480-3dee-11eb-8d77-4b2208e5c5e7.png)

### Test code to reproduce

  it('Complete Registration Form', () => {
cy.visit('https://signin.mygovscot.org/home/?entityId=https://signin.mygovscot.org/shibboleth&sp=register/CAS#')

  })

**Comment by jennifer-shehane** [comment]
Expanding the stack trace, you can see where this error if throwing in your application code. 

<img width="670" alt="Screen Shot 2020-12-14 at 5 10 13 PM" src="https://user-images.githubusercontent.com/1271364/102071736-495abb00-3e2f-11eb-8d74-f9866ab094e5.png">

Searching in the `frmUtils.js` file in the Source panel, we can find the `disableBackground` method. Within this method is this line calling into `window.parent.document`. Since Cypress run's your application in an iframe, searching the DOM of the `window.parent` will actually search the Cypress test runner itself, which is why this error is thrown later on. 

<img width="1376" alt="Screen Shot 2020-12-14 at 5 09 31 PM" src="https://user-images.githubusercontent.com/1271364/102071845-7313e200-3e2f-11eb-8bac-740313f70866.png">

We do have an option to rewrite some of the source so that it references the correct application window instead of the Cypress Test Runner. This is experimental and can be turned on using the `experimentalSourceRewriting: true` flag in your Cypress configuration. 

```js
{
  "experimentalSourceRewriting": true
}
```

This does indeed seem to fix the loading of the application in your case. 

<img width="1222" alt="Screen Shot 2020-12-14 at 5 15 55 PM" src="https://user-images.githubusercontent.com/1271364/102072273-0c42f880-3e30-11eb-9494-32ebc48b6fb8.png">

**Comment by OhAye** [comment]
Ah thank you so much, Jennifer you're a legend. I could see why it was failing I just couldn't see how to get Cypress to work around it.
