### ISSUE TITLE
This element is not visible because it has CSS property :opacity: 0

### ISSUE THREAD

**Issue by begli80** [cypress-io/cypress#14191]
Current behavior:
The visibility test which was successfully passing in the cypress version 5.6 on Electron 85 is failing after upgrading cypress to version 6.1
To make sure I downgraded back to 5.6 and it passed but failing in 6.1
![image](https://user-images.githubusercontent.com/39811047/102262244-6bf4de80-3ed8-11eb-9ba9-80218731388b.png)
Desired behavior:
Successful Assertion for the visible element

Versions
cypress@6.1.0
Electron 85
Windows 10 x64

**Comment by jennifer-shehane** [comment]
Please make sure to read our [Changelog](https://on.cypress.io/changelog), including the [Migration Guide](https://on.cypress.io/migration-guide#Opacity-visibility) when updating to a major version of Cypress, as there are intended breaking changes. 

Elements with an opacity of 0 are now considered not visible in 6.0+, because they are not visible to the eye. This is working as intended.

**Comment by begli80** [comment]
So how am I supposed to assert that element is visible ?

**Comment by begli80** [comment]
The element  is  visible to the eye but cypress fails it

**Comment by jennifer-shehane** [comment]
If the element or its parent element has `opacity: 0`, then the element should not be visible. If can however be interacted with.

If you can provide some HTML + CSS of an example where the element is visible and we are incorrectly saying it is invisible with opacity: 0, we'd be happy to look at that as a possible bug. Can you provide an example for us to run of this situation?

**Comment by begli80** [comment]
I have already provided the screenshot attached in the issue. There is an
elment and it is an agreement checkbox.I can see it on page but cypress
version 6.1 fails to assert it as visible.

**Comment by bahmutov** [comment]
You can step through the Cypress visibility code to see why Cypress considers that element invisible. Follow the example in this blog post https://glebbahmutov.com/blog/debug-visibility/

**Comment by begli80** [comment]
Here is an attachment from the page which is visible to the eye. So how come it is asserted as invisible by cypress?

![image](https://user-images.githubusercontent.com/39811047/102373718-20007300-3f86-11eb-97d4-48bd981942b4.png)

**Comment by bahmutov** [comment]
@begli80 you can either provide a fully reproducible example we can run, or debug the visibility check yourself using the instructions we have posted above. 

Yes, we see the checkbox and agree that this is a very frustrating issue, but there are way too many changes between Cypress v5.6 and v6.1 for us to say "this is why opacity is now different". 

When you click on the get command, does it find the right element in the DOM? Can you then check the visibility using our algorithm call? https://on.cypress.io/dom#Is-visible

**Comment by begli80** [comment]
I tried get command without assertion but still same issue

**Comment by gweaths** [comment]
How do we resolve this issue, as in how do we assert that we can see it via the naked eye, but cypress thinks it's hidden ? surely there must be a work around ?

**Comment by jennifer-shehane** [comment]
@gweaths We're unaware of any examples of elements that can be seen with the eye with opacity: 0 that Cypress is incorrectly labeling as not visible. Can you provide an example that we can test to see this? Because this would be a bug. HTML/CSS/JS would be great.

**Comment by twalpole** [comment]
@gweaths The `input` element actually isn't visible in the example you show because it has opacity 0 - instead you're using CSS to show a fake checkbox (for styling reason) which probably has the real invisible checkbox overlaid on top of it

**Comment by suncat18** [comment]
I am running into the same issue: I have a list to select from and it is not selecting since that element's opacity is set to 0.  Is there a way to make this interactable?  I tried invoke('show') but that is not doing anything.
![opacity](https://user-images.githubusercontent.com/26546371/176348744-2c803bb3-9bd1-4983-a029-2d5e28a6379f.jpg)

**Comment by cjp-engr** [comment]
I have a same problem here. Does anyone already fixed the issue?

**Comment by arpipat** [comment]
i have same issue, parent element have opacity 0 and hence unable to find or click child element. Can you please provide solution on this

**Comment by frankhovin** [comment]
It's really nice how the Cypress reps here just stop responding. They claim that the reported problem is not real, several people chime in saying they've also encountered it, and then they just stop responding.

**Comment by marktnoonan** [comment]
@frankhovin the issue was closed and marked wontfix 3 years ago, I don't think we have been seeing the occasional comments that popped up here since then. 

I believe this is correctly marked as wontfix and that @twalpole got it right with [this comment](https://github.com/cypress-io/cypress/issues/14191#issuecomment-812092543) already. I'll go into some more detail and hope that it helps.

From what I can tell, this issue is mostly affecting `input` elements that have `opacity: 0`. 

There are some common UI development patterns that deliberately render invisible `input` elements and then simulate the browser UI for a radio button or a checkbox with custom styles. This is usually done so that the user-facing control can have nice styling and animations, and it offers a level of visual control beyond what is possible with native browser form elements.

The `input` element itself is then just being used to store the state of the control (checked or not). But what the user sees and clicks on is a different element - often the associate `label`, but not always. This means a visibility check on the `input` is correctly failing, because that element is actually invisible.

Instead of asserting the visibility of the `input` itself, I would recommend asserting the visibility of the user-facing element that represents the checkbox or radio button for the user. Since that is the visible portion of the form, I also think it's a more correct thing to verify with your tests. If Cypress pretended the `input` was visible and passed the test, you would still not know if the user-facing custom form control was rendering, so it would be a false positive and your test would not catch a regression that actually broke things.

Side note: you can always trigger a `click` on the input directly if you like, since opacity [does not affect actionability checks,](https://docs.cypress.io/guides/core-concepts/interacting-with-elements) 
![Screenshot 2023-08-30 at 5 25 13 PM](https://github.com/cypress-io/cypress/assets/8340719/dda98281-b7a0-4e96-a163-279014186749)

All of that said, I'm happy to learn more if the above is not your issue. If there is a case where Cypress claims that an element has `opacity: 0` and the element does not actually have `opacity: 0`, that is a bug and I would ask for a reproduction in a new issue to address that bug, rather than reuse this closed one. 

So far it looks like folks are locating elements and asserting that are really hidden and the visibility check is working as expected.

**Comment by NityaQA** [comment]
same issue. Is there any work around for it. As I can see a check box in my webpage. But when I tried to assert it through Cypress, it is throwing element is not visible as opacity:0 . Is this issue fixed in cypress new versions?

**Comment by marktnoonan** [comment]
Hi @NityaQA without a reproducible example, my assumption is you are locating a hidden input element [as described here](https://github.com/cypress-io/cypress/issues/14191#issuecomment-1699891892). Have you tried any of the recommendations in that comment?

**Comment by nimishjain77** [comment]
If the `opacity: 0`,
You can use below code to check that.

> cy.get('[value=xyz]')
>       .should('have.css', 'opacity', '0')
>       .should('be.checked')
>       .and('have.value', 'xyz');

Here `xyz` is the value of the checkbox.
