### ISSUE TITLE
Terminate test execution if Cypress caught a specific exception  

### ISSUE THREAD

**Issue by omelnik** [cypress-io/cypress#14213]
When a setup logic for my tests fires an exception I expect from Cypress to stop the test execution.

### Current behavior
**Open Mode:** It works as expected. When the setup logic is failed a user isn't able to proceed with the test execution.
<img width="891" alt="Screen Shot 2020-12-16 at 6 06 54 PM" src="https://user-images.githubusercontent.com/32174556/102434881-85765300-3fca-11eb-877a-8f2ae9078105.png">

**Run Mode:** The Error Exception has been thrown, but Cypress wasn't stopped.   

### Desired behavior
I expect from Cypress to stop the test execution.

### Versions
Cypress: 5.5.0

**Comment by jennifer-shehane** [comment]
>When a setup logic for my tests fires an exception I expect from Cypress to stop the test execution.

Can you provide an example of the code throwing an exception? There are a lot of places this could be thrown, so we'd need an example to follow what you want to have happen here.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
