### ISSUE TITLE
cy.focused() not working after cypress version 3.4.1

### ISSUE THREAD

**Issue by Prashant-Kan** [cypress-io/cypress#14227]
cy.focused() not working after cypress version 3.4.1

Testing Steps

Have 5-6 Inputs of type text, checkbox and select (dropdown) and give unique data-id or id to each controls. 
now, click on any input using cypress code. 

in the second line excute `cy.focused().then($element) => { // do some stuff for $element});`

### Current behavior with version later than 3.4.1
Throwing error that focused failed as there are no elements where focus is set. 

### Desired behavior
It shouldn't throw any error. 

### Versions

all the version after 3.4.1

### Browsers

Chrome

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

What I tried:

`index.html`

```html
<html>
<body>
  <input id="testinput" />
  <input id="testinput2" type="checkbox"/>
</body>
</html>
```

`spec.js`

```js
it('focus tests', () => {
  cy.visit('index.html')
  cy.get('#testinput').click()
  cy.focused().then(($element) => { 
    // do some stuff for $element
  })
  cy.get('#testinput2').click()
  cy.focused().then(($element) => {
    // do some stuff for $element
  })
})
```

<img width="829" alt="Screen Shot 2020-12-21 at 6 16 05 PM" src="https://user-images.githubusercontent.com/1271364/102774054-9eab4500-43b8-11eb-86e4-2d9a58fc8e8c.png">
