### ISSUE TITLE
Opacity animations cause 'should.be.visible' to fail

### ISSUE THREAD

**Issue by actuallymentor** [cypress-io/cypress#14230]
### Current behavior

1. Click button
2. Element fades in
3. `.should( 'be.visible' )` fails during animation

### Desired behavior

The `.should( 'be.visible' )` should respect the timeouts that the other queries use so that animations involving opacities do not fail.

### Test code to reproduce

To busy sorry.

### Versions

`"cypress": "^6.1.0"`

**Comment by actuallymentor** [comment]
Update: Setting `animationDistanceThreshold` to `1` does not fix the issue.

**Comment by bahmutov** [comment]
Can you please provide a reproducible example or at least HTML + CSS and the video of the test showing what happens?

**Comment by jennifer-shehane** [comment]
@actuallymentor We have a lot of tests around opacity visibility and animating into opacity 0, so the situation you're seeing is likely specific to the circumstances of your app/test. Without a reproducible example, we'll have to close the issue.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by BorjaRafolsMartinez** [comment]
> 

Could you kindly point me to those? I've tried to find them without success. 

I'm having the same issue and would like to take a look at the relevant code.

Thanks in advance.

**Comment by BorjaRafolsMartinez** [comment]
> @actuallymentor We have a lot of tests around opacity visibility and animating into opacity 0, so the situation you're seeing is likely specific to the circumstances of your app/test. Without a reproducible example, we'll have to close the issue.

Could you kindly point me to those? I've tried to find them without success.

I'm having the same issue and would like to take a look at the relevant code.

Thanks in advance.
