### ISSUE TITLE
Browser doesn't connect on 6.x.x

### ISSUE THREAD

**Issue by marciusl** [cypress-io/cypress#14265]
Hello, I had version 4.x.x and 5.6.0 and everything worked on CircleCI. When upgraded to 6.x.x it fails.

Ran with:
`npm run web-server && cypress run --headless --browser chromium -c baseUrl=https://localhost:8000 && npx mochawesome-merge "cypress/results/*.json" > cypress/merged.json && npx marge cypress/merged.json --reportDir cypress/report`

### Current behavior
Didn't run, reason: `The browser never connected. Something is wrong. The tests cannot run. Aborting...`

### Desired behavior
To run

### Test code to reproduce
Code is not an issue here

### Versions
4.x.x, 5.6.0, 6.0.0 and 6.1.0
Chromium 76
CircleCI

**Comment by jennifer-shehane** [comment]
I'm not aware of anything specifically that would cause this error during update. 

You could try running Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode to see if there's something in the logs. 

Also make sure to check our [migration guide](https://docs.cypress.io/guides/references/migration-guide#Migrating-cy-route-to-cy-intercept) since you're updating a few major versions.

The chrome version is also a bit older, have you tried updating / or running in Electron to see what happens?

Essentially I would try to isolate my test suite down to see what exactly would cause this error.

**Comment by marciusl** [comment]
I had debug mode enabled but couldn't find something that I caught on my eye.

I did followed migration guide, made some changes according to every major version, on local everything is fine there.

Tried with Electron 87, worked.
