### ISSUE TITLE
experimentalSource Rewriting - Click stops working when having this config as true.

### ISSUE THREAD

**Issue by TheFreeRangeTester** [cypress-io/cypress#14268]
### Current behavior
The dropdown selector ('.k.dropdown-wrap > .k-input') is not working when having the "experimentalSourceRewriting" config as true.

When disabling this config, clicking the above locator works correctly. 

### Desired behavior

The elements can be clicked when having experimentalSourceRewriting as true.

### Test code to reproduce
I've tried this with Electron and Chrome, same result. the code involves a click action for the element (you can find the locator above). Given this is on my work machine and because of confidentiality, can't share much more. 

### Versions

I'm using Cypress 6.1.0, on a Windows 10 enterprise machine with Intel Core i5-6200U CPU @ 2.30GHz 2.40 GHz and 16 GB of Ram,

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Right now there isn't enough information to reproduce the problem on our end. We don't have a path to move forward with investigating without this.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
