### ISSUE TITLE
window:before:load event not firing

### ISSUE THREAD

**Issue by ianwalter** [cypress-io/cypress#1429]
- Operating System: macOS High Sierra 10.13.3 (17D102)
- Cypress Version: 2.1.0
- Browser Version: Chrome Version 64.0.3282.186 (Official Build) (64-bit)

### Is this a Feature or Bug?

Bug

### Current behavior:

`window:before:load` callback specified in plugins/index.js through `on` function does not get called.

### Desired behavior:

`window:before:load` callback specified in plugins/index.js through `on` function gets called before page load.

### How to reproduce:

Run `npm start` then `npm run cypress` to open Cypress. Run the example spec and see that console.log does not get called and that window has not been modified.

#### Test code:

https://github.com/ianwalter/cypresstest

**Comment by ianwalter** [comment]
Looks like this works in `support/index.js`:
```js
Cypress.on('window:before:load', window => {
  console.log('yooooo', window)
})
```

**Comment by brian-mann** [comment]
I'm not sure where you read that Cypress events are provided to you in plugins. 

They are two completely separate things. Plugins are for node code - to alter the way Cypress itself works outside of the browser.

Cypress events are for inside the browser because they're about things happening in real time to your application.

Plugin events are documented here in the plugins guide and in each various section: https://docs.cypress.io/guides/guides/plugins-guide.html#

Cypress events are documented here: https://docs.cypress.io/api/events/catalog-of-events.html#

One doesn't have anything to do with the other.
