### ISSUE TITLE
Webpack Compilation Error

### ISSUE THREAD

**Issue by henil9891** [cypress-io/cypress#14302]
```
Webpack Compilation Error
multi .
Module not found: Error: Can't resolve 'C:\Users\..\Documents\folder\Cypress' in 'C:\Users\..\Documents\folder\Cypress'
Looked for and couldn't find the file at the following paths:
[C:\Users\..\Documents\folder\Cypress]
[C:\Users\..\Documents\folder\Cypress.js]
[C:\Users\..\Documents\folder\Cypress.json]
[C:\Users\..\Documents\folder\Cypress.jsx]
[C:\Users\..\Documents\folder\Cypress.mjs]
[C:\Users\..\Documents\folder\Cypress.coffee]
[C:\Users\..\Documents\folder\Cypress\index.js]
[C:\Users\..\Documents\folder\Cypress\index.js.js]
[C:\Users\..\Documents\folder\Cypress\index.js.json]
[C:\Users\..\Documents\folder\Cypress\index.js.jsx]
[C:\Users\..\Documents\folder\Cypress\index.js.mjs]
[C:\Users\..\Documents\folder\Cypress\index.js.coffee]
[C:\Users\..\Documents\folder\Cypress\index]
[C:\Users\..\Documents\folder\Cypress\index.json]
[C:\Users\..\Documents\folder\Cypress\index.jsx]
[C:\Users\..\Documents\folder\Cypress\index.mjs]
[C:\Users\..\Documents\folder\Cypress\index.coffee]
```
This happens when a button click action is happening and is being redirected to another page i.e. for example 
xyz.com/products -> xyz.com/cart

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
