### ISSUE TITLE
Cypress hangs after Angular 11 upgrade 

### ISSUE THREAD

**Issue by stahloss** [cypress-io/cypress#14369]
### Current behavior
After migrating to Angular 11 in my nx workspace, Cypress hangs in default or headless mode. In watch mode it still runs tests.

### Desired behavior
Cypress doesn't hang in default or headless mode.

### Test code to reproduce
[This branch](https://github.com/D0rmouse/nx-cypress-cucumber-demo/tree/nx_upgrade_cypress) demonstrates the behavior. Just run `npm run e2e` or `npm run e2e -- --headless` to see Cypress hang. Updating to a more recent version does not resolve the issue.

### Versions

Cypress: 4.4.0, but 6.2.0 also hangs.
OS: Windows 10.0.19041 Build 19041

**Comment by jennifer-shehane** [comment]
@D0rmouse I do see the example given hanging when Cypress opens. Can you possibly narrow down the example use case? Simplifying it to a Cypress spec file, removing cucumber, etc? That would be helpful in narrowing down the issue and having a simple example for us to run.

**Comment by D0rmouse** [comment]
@jennifer-shehane, I have pushed the changes to the branch. Now .spec files are executed, instead of .feature files, which fixes the execution hang.
Seems that the `preprocessTypescript` function was the culprit, which uses the following webpack preprocessors:

```
const wp = require('@cypress/webpack-preprocessor');
const { getWebpackConfig } = require('@nrwl/cypress/plugins/preprocessor');
```

Seems it could be either a cypress or nrwl issue...
