### ISSUE TITLE
Jira application breaking when visited with cy.visit() command. 

### ISSUE THREAD

**Issue by denizoguz** [cypress-io/cypress#1436]
I want to use cypress to test Jira plugins. In order to do that, I should able to browse to Jira pages using cy.visit(). But Cypress can't load even a basic page of Jira. You can reproduce the problem easily by trying to visit any page of Jira.

#### Test code:

```js
cy.visit('https://jira.atlassian.com/secure/BrowseProjects.jspa?selectedCategory=all&selectedProjectType=all');
```

- Operating System: MacOS High Sierra
- Cypress Version: 2.1.0
- Browser Version: Chrome 64

### Is this a Feature or Bug?
This is a bug.

### Current behavior:
cypress gives 'Uncaught TypeError: Cannot read property 'fn' of undefined' error. Cypress telling that this is not a Cypress problem, this is an application problem. But this page loads without any problem if you try to visit url directly in the Chrome 64. Somehow behavior of the page is changing under Cypress.

### Desired behavior:
Requested page should be loaded without any error.

**Comment by brian-mann** [comment]
@jennifer-shehane did the legwork here and discovered the root cause.

It's this function right here:

https://gist.github.com/jennifer-shehane/75759abaa79883097ee4922e3c8f1998#file-unframed-js-L87

That function is returning a different `window` in Cypress than in Jira.

I'll have to dissect the logic to implement a workaround. Although its kind of a rabbit hole to fix 3rd party code - I don't see another option. Because Cypress iframes the application under test, it's possible code behaves slightly differently - in this case it returns the Cypress window - instead of the Jira window.

**Comment by brian-mann** [comment]
PR is here: https://github.com/cypress-io/cypress/pull/1437

This will go out in the next release.
