### ISSUE TITLE
Cypress cy.get(): graceful error handling, either .catch(err) or .then(error, resp)

### ISSUE THREAD

**Issue by jeff00seattle** [cypress-io/cypress#14377]
I would prefer in some cases to handle the error gracefully if `cy.get()` fails to find selector

```
cy.get(x)
  .then(resp => {
    // handle resp
    ***
  })
  .catch((err) => {
    // handle err
    ***
  });
```

or

```
cy.get(x)
  .then(err, resp) => {
    if (err) {
      // handle err
      ***
    }
    /// handle resp
  })
```

or at least support:

```
try {
  cy.get(x)
    .then(resp) => {
      /// handle resp
    })
} catch(err) {
 /// caught cy.get() failure
}
```

In some cases, I do not want a notification that cy.get() failed, if it did then I want to handle the error, not Cypress. For example:

**Code:**
```
cy.get(x)
  .click()
  .then(resp) => {
```

**Console:**
```
     CypressError: `cy.click()` failed because it requires a DOM element.

The subject received was:

  > `undefined`

The previous command that ran was:

  > `cy.get()`
```

**Code with Error Handling:**
```
cy.get(x)
  .catch(err) => {
    // do something else, handle error as I would prefer
  })
  .click()
  .then(resp) => {
```

**Comment by bahmutov** [comment]
The commands like `cy.get` are meant to retry the assertions that follow it, read our https://on.cypress.io/retry-ability guide. You can place pretty advanced rules into existing assertions or by writing your own using https://on.cypress.io/should with a callback function.

If the command fails to find elements that pass the assertions, then the command and the test fails, otherwise, the test becomes ambiguous and non-deterministic, something we strongly discourage in https://on.cypress.io/conditional-testing
