### ISSUE TITLE
`Cypress run` similar CLI usage as Mocha: --bail and --exit

### ISSUE THREAD

**Issue by jeff00seattle** [cypress-io/cypress#14376]
There is a npm module available [cypress-fail-fast](https://www.npmjs.com/package/cypress-fail-fast), which enables fail fast in Cypress, skipping the rest of tests on first failure.

Since Cypress has structured is integrations the same way as Mocha test suites, then why does not `Cypress run` have the same rules and behaviors (CLI usage) as Mocha: https://mochajs.org/

```
  --bail, -b                 Abort ("bail") after first test failure   [boolean]
  --check-leaks              Check for global variable leaks           [boolean]
  --exit                     Force Mocha to quit after tests complete  [boolean]
```

**Comment by bahmutov** [comment]
The case for Mocha is more limited than what Cypress is meant to solve. As the number of end-to-end tests increases, the time to run them gets longer and longer as well. After the tests run for about 5 minutes, it becomes necessary to split the set of spec files and run them in parallel to make the CI fast enough. Now you have a set of tests that run across multiple machines. 

If you stop a spec file due to a failed test like cypress-fail-fast does, do you bail on the rest of the specs that run on machine A? Do you stop all other CI machines running _other_ spec files? 

Since E2E tests exercise the entire application they are very closely related to a single source change, unlike the unit tests are. Thus changing a source line X in your application might affect seemingly unrelated tests in other spec files. The thing is, I believe the purpose of CI is to give you a complete picture of your web application.  By bailing out after the first failed test you lose the full picture. In fact, since the first failed test might be very non-obviously related to the source line X you might have _harder_ time finding the true source of the problem because the test that closely tests the source line X never runs.

Thus I understand why people might want to immediately stop running any tests on CI after the first test fails, but I believe this is a very bad trade-off.
