### ISSUE TITLE
cy.next() doesn't want to search by valid selector

### ISSUE THREAD

**Issue by sergeyblohin** [cypress-io/cypress#14388]
Hi, I use Cypress 6.2.0 (macOS, Chrome).
For example, open example.com and try to find `body > div > p:nth-child(3) > a` element.

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/61824066/103534147-64a16f00-4e9f-11eb-9a79-2b9ba55176f7.png">

I want use next code:

```javascript
/// <reference types="cypress" />

describe('example.com', () => {
  it('.next()', () => {

    cy
      .visit('https://example.com');

    /**
     * <p></p> <!-- .get('p').first() -->
     * <p>
     *   <a href="https://www.iana.org/domains/example"></a>
     * </p>
     */
    cy
      .get('p')
      .first()
      .next('p > a');

  });
});
```

But Cypress returns error: 

> Timed out retrying after 4000ms: Expected to find element: p > a, but never found it. Queried from element: <p>

But, if I use next code, then Cypress work correctly:

```javascript
cy
      .get('p')
      .first()
      .next('p')
      .find('a')
```

Why does cypress separate `.next('p').find('a')` and `.next ('p > a')`?

**Comment by jennifer-shehane** [comment]
The `.next()` command is looking for a **sibling** element that matches the query `p>a`. There is no sibling element matching that requirement since the sibling element is simply a `p` element. 

You may want to try asking questions related to the use of Cypress in our community in our [GitHub Discussions](https://github.com/cypress-io/cypress/discussions). As an open source project with a small maintainer team we have to focus our time on bugs and features in the product, which Issues are reserved for.
