### ISSUE TITLE
Test runner window when minimized affects test results

### ISSUE THREAD

**Issue by Cito** [cypress-io/cypress#14405]
This is a follow-up on #9604: When the test runner window is fully occluded, then this affects the test results.

The issue has been fixed in 6.2.1 and it is working for me now when the window is fully occluded.

However, #6904 also mentioned that the same effect can be seen when the test runner window is minimized. Unfortunately, this does not seem to be solved by the fix in 6.2.1.

If this cannot be fixed, then Cypress should show an error or pause when minimized, pointing out that the test runner window must be open at all times when tests are running.

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example of the issue? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

There are some known situations that will fail if the browser does not maintain focus documented here: https://github.com/cypress-io/cypress/issues/5023 Perhaps your issue is that - without a reproducible example we'll have to close the issue.

**Comment by Cito** [comment]
Sure. I thought #6904 already had an example but now I see it hasn't. Will try to create something.

**Comment by Cito** [comment]
Ok, a self-contained test is available at [Cito/cypress-14405](https://github.com/Cito/cypress-14405) now.

**Comment by Cito** [comment]
It doesn't seem to be the same issue as #5023. The test works even when the test runner is fully occluded and has no focus. It fails only when the test runner is minimized.

**Comment by jennifer-shehane** [comment]
😓 I can't reproduce this with the example. I'm in Chrome 87.0.4280.141 and immediately minimizing the browser - waiting 10+ seconds and the tests are all passed. 

- What's the visibility error? Can you paste it? 

<img width="839" alt="Screen Shot 2021-01-07 at 4 17 21 PM" src="https://user-images.githubusercontent.com/1271364/103877723-d7ab1f80-5103-11eb-8996-aadc738d278d.png">

**Comment by Cito** [comment]
Maybe try it a few times. However I can reliably reproduce this on machine. I'm using the exact same browser version, on Windows 10. I see the same as you when running the test with open browser, but when minimized, I see this:

![issue14405](https://user-images.githubusercontent.com/464599/103885773-ce5c8b80-50e0-11eb-92f8-0f7c0c6c23bb.png)

The dropdown should disappear after 500ms, but it seems it never does or it takes over 4s when the windows is minimized.

Don't maximize the browser too early. Give it 10 seconds (+ 4 more seconds for the timeout) to run completely through and fail before maximizing it again.

**Comment by jennifer-shehane** [comment]
Do you happen to have 2 monitors where it's minimized on one screen and then focusing on the other screen? 😅 I'm not sure why I can't reproduce. Maybe it weirdly works on Mac?

You know what's weird though is that the element shows up as hidden in the Command Log, but it still successfully clicks. But it shows this way regardless of being minimized.

![](http://g.recordit.co/gV6C3iF56f.gif)

**Comment by italodeandra** [comment]
Hi @jennifer-shehane,

I have this same problem of minimizing the Chrome window. I have some theories, but the problem is, we can't really debug it.

The Chrome window seems to not really render when minimized. I'll show you on a video:


https://user-images.githubusercontent.com/19225266/104012022-66c14180-51af-11eb-8fe1-46b5abfd8dec.mp4


https://user-images.githubusercontent.com/19225266/104012028-688b0500-51af-11eb-96a7-b0d6b05f3470.mp4

**Comment by Cito** [comment]
> Do you happen to have 2 monitors where it's minimized on one screen and then focusing on the other screen? I'm not sure why I can't reproduce. Maybe it weirdly works on Mac?

I could imagine this somewhat depends on the OS or window manager. I have been testing this with a single screen though and could reproduce it reliably on both Windows and Ubuntu.

**Comment by jennifer-shehane** [comment]
@italodeandra You're issue may also be more similar to https://github.com/cypress-io/cypress/issues/5023 since it's involving focus of the browser specifically.

**Comment by italodeandra** [comment]
I think both are similar to #5023. Because I figured out that the problem is the browser losing focus, if I click on anything on my second screen, the error is the same. Is there any solution for this? Or we just agree that when running tests we should always keep the Cypress window focused and never switch to another window/screen?

**Comment by Cito** [comment]
Tried this again with my example app. When I change the focus, the example test still passes. Even when I change focus to a window on a different virtual desktop, it still works. I can only make the test fail by minimizing the window. And I can reliably reproduce this, it's not flaky like #5023. So these may be different issues.

**Comment by jennifer-shehane** [comment]
Yah, I think @Cito issue only happens with minimized window which is why this new issue will remain open.

@italodeandra looks like duplicate of #5023. We do a bunch of things to try to make sure focus still works in these situations, but there's something we're not accounting for. Make sure to follow the other issue for any updates.

**Comment by Cito** [comment]
Checked again with the new Cypress 6.3.0 and Chrome 88. Unfortunately, the problem still exist.
