### ISSUE TITLE
FireFox 83 doesn't trigger mousedown, even with {force: true}

### ISSUE THREAD

**Issue by markchagers** [cypress-io/cypress#14429]
### Current behavior
In an Angular component, the line:
```js
.trigger('mousedown', { button: 1 }, { force: true })
```
works as intended in Chrome and Electron, but hangs in Firefox 83. with the following CypressError:

```
Timed out retrying after 4000ms: cy.trigger() failed because this element:

    <ptp-slider-handle _ngcontent-asj-c13="" _nghost-asj-c12="" ng-reflect-position="0" ng-reflect-parent-element="[object HTMLDivElement]" ng-reflect-used-class="">...</ptp-slider-handle>

is being covered by another element:

    <div _ngcontent-asj-c16="">...</div>
```

the element 'covering' my target element is a div enclosing the entire component generated by angular. The target element is actually enclosed inside this container element, I don't quite understand how this container can be seen as covering the elements inside it.

Interestingly, in my Angular project the issue occurred in FireFox and NOT in Chome or Electron, but in the minimal test case linked below, the issue also occurs in the other browsers.

If an element with higher z-index overlaps the center of the target element (where the mousedown event registers by default), the problem occurs. In the test case, the first target correctly gets the mousedown event, but the second one hangs with the error.

I seems like the `{ force: true }` option is ignored.

### Desired behavior

It should trigger a mousedown on the target element when I specify { force: true }

### Test code to reproduce
see: https://github.com/markchagers/cypress-test-tiny/tree/minimal-test-case

### Versions
6.2.1
I'm a new user of cypress, so I have no information on previous versions and whether the issue occurs there.

**Comment by jennifer-shehane** [comment]
What version of Chrome is this working in for you? I would assume it's the built in Electron 87. I'm seeing this same error in Chrome 87, Electron 87, and Firefox 81 with the example provided.

I updated the colors to make this a bit clearer. This div *is* covering the second element. Since we trigger events at the very center of the element, the first mousedown works since the center of the first element is not covered by the div with z-index: 100.  

`index.html`

```html
<html>
<body>
    <div class="target first" style="top: 70px; left: 0; background-color: blue; position: absolute; width: 100px; height: 100px;">this is first target</div>
    <div class="target second" style="top: 270px; left: 110px; background-color: red; position: absolute; width: 100px; height: 100px;">this is second target</div>
    <div class="cover" style="top: 20px; left: 60px; background-color: yellow; opacity: 0.3; position: absolute; width: 200px; height: 400px; z-index: 1000;">this covers the target</div>
</body>
</html>
```

```js
it('works', () => {
  cy.visit('index.html')
  cy.get('.target.first').should('be.ok')
    .trigger('mousedown', { which: 1 })

  cy.get('.target.second').should('be.ok')
    .trigger('mousedown', { which: 1 })
})
```

<img width="762" alt="Screen Shot 2021-01-07 at 2 52 28 PM" src="https://user-images.githubusercontent.com/1271364/103868931-fdcac280-50f7-11eb-8564-f0081e781168.png">

The `force: true` option is not working in your case because `.trigger()` accepts 2 arguments in this situation https://on.cypress.io/trigger#Syntax, the 2nd being all options. You need to pass `which` and `force` arguments in the same options argument. 

```js
it('works', () => {
  cy.visit('index.html')
  cy.get('.target.first').should('be.ok')
    .trigger('mousedown', { which: 1, force: true })

  cy.get('.target.second').should('be.ok')
    .trigger('mousedown', { which: 1, force: true })
})
```

It will pass with the force option

<img width="768" alt="Screen Shot 2021-01-07 at 2 55 00 PM" src="https://user-images.githubusercontent.com/1271364/103869174-5ac67880-50f8-11eb-8655-e03f5aee5782.png">

Please comment if there is a more specific example you can give where this is behaving unexpectedly and we can reopen. Just went off of the provided repo.

**Comment by markchagers** [comment]
Hi, thanks for your reply.

I can confirm that the fix you suggest fixes the issue for me as reported in the minimal example. You can close this issue AFAIC.

> What version of Chrome is this working in for you? I would assume it's the built in Electron 87. I'm seeing this same error in Chrome 87, Electron 87, and Firefox 81 with the example provided.

The example I provided is not working in any browser. The project where just FireFox had problems and Chrome and Electron were ok is too complex to share here. I still have an issue there that I am investigating and I will create a new issue if appropriate.

> I updated the colors to make this a bit clearer. This div _is_ covering the second element. Since we trigger events at the very center of the element, the first mousedown works since the center of the first element is not covered by the div with z-index: 100.

That was why I had set it up so, to show the difference between these two situations, but that the force: true option didn't seem to work.

> The `force: true` option is not working in your case because `.trigger()` accepts 2 arguments in this situation https://on.cypress.io/trigger#Syntax, the 2nd being all options. You need to pass `which` and `force` arguments in the same options argument.

Thanks, may I suggest adding a note to this page: https://docs.cypress.io/api/commands/trigger.html#Syntax to the effect that the trigger command accepts only a single options object? I had taken this code from a stack-overflow question, apparently it's an error made more often.
