### ISSUE TITLE
ขอคุณสมบัติ

### ISSUE THREAD

**Issue by prdarm** [cypress-io/cypress#14442]

**Comment by jennifer-shehane** [comment]
When opening a pull request, please fill out the [pull request template](https://github.com/cypress-io/cypress/blob/develop/PULL_REQUEST_TEMPLATE.md) provided - it requires necessary information we need to move forward with reviewing pull requests. 

If you can, please edit the initial comment of this PR filling out the pull request template including an explanation for why this PR is necessary. Otherwise, we will be closing this PR.
