### ISSUE TITLE
DOC clarification requested: I'm seeing different behavior with cy.intercept depending on which calling signature I use.

### ISSUE THREAD

**Issue by flamingbear** [cypress-io/cypress#14458]
### Current behavior

When I migrated from cy.route() to cy.intercept() I found some behavior I didn't expect depending on which form of cy.intercept I used.

 
I have an intercept call that works with a two param input (method, url):
```js
cy.intercept('GET', '/collections/active?limit=*').as('getActiveCollections');
```

But when I use a routeMatcher object, it does not work.
```js
cy.intercept({method:'GET', url:'/collections/active?limit=*'}).as('getActiveCollections');
```

I didn't see anything in the documentation that would show a difference between the two url params.

**So in putting this together, I see that my routeMatcher needs to include `matchUrlAgainstPath: true` and that will match**

```js
cy.intercept({method:'GET', url:'/collections/active?limit=*', matchUrlAgainstPath: true }).as('getActiveCollections');
```

### Desired behavior

I would hope that the need to include `matchUrlAgainstPath` is documented or that the behavior is consistent.  I would suggest the doc change, but I don't actually know if I've got this completely correct.

### Versions
6.2.1

Thanks
Matt

**Comment by jennifer-shehane** [comment]
In the first example, the `matchUrlAgainstPath` is automatically set to `true`. There's a note in the docs here:

>Note: passing a URL as a string or RegExp to cy.intercept() will automatically set `matchUrlAgainstPath` to `true`. This means that the supplied string or RegExp will be matched against the path if matching against the URL fails.
>https://on.cypress.io/intercept#Matching-URL

Essentially when you are passing the `url` argument, you are saying 'match against the url exactly' and since you provided a path, this will no longer intercept the url you're expecting. Passing `matchUrlAgainstPath` will make match your `url` arg against the `path`. So, your solution is the correct solution. 

In 6.2.0 we changed the behavior of passing a simple string to `cy.intercept()` (like `cy.intercept('GET', '/collections/active?limit=*')`) to match against the `url`, but if that failed match against the `path`. This is how `cy.route()` worked before. See https://github.com/cypress-io/cypress/issues/9379

I suppose there could be an example showing the use of `matchUrlAgainstPath: true` when passing a `url` property in the docs. Would that be helpful?

**Comment by flamingbear** [comment]
Thanks Jennifer, going back, it is clearly documented. I just didn't grok path v. url as clearly as I should have or just skipped right over that note.  Appreciate the feedback, feel free to close.
