### ISSUE TITLE
Intercept does not return locally cached data and times out

### ISSUE THREAD

**Issue by asithade** [cypress-io/cypress#14459]
### Current behavior
When trying to intercept a request, if the request is already cached locally the intercept method is unable to intercept the query. Workarounds for caching previously mentioned deleting various headers that determine whether the server returns cached data or not, do not work as it doesn't intercept the query at all. 

![Screen Shot 2021-01-07 at 5 07 28 PM](https://user-images.githubusercontent.com/3814354/103962136-0d073b80-510b-11eb-82d8-1618cd8ec30c.png)

If I disabled caching via the console's network tab, the query works every time and I'm able to wait for it to complete. 

### Desired behavior
If the data is cached locally, return the local response. If the intended behavior of Cypress is to mimic a user's experience, then we should not have to append query parameters to get a fresh set of data each time a query is presented. 

### Test code to reproduce
```Javascript
  it('successfully loads', () => {
    cy.visit('/');

    cy.intercept('GET', `${projectServicesAPI}/projects/search**`, (req) => {
      delete req.headers.Authorization;
    }).as('projects');

    // Ensure that the projects are loaded
    cy.wait('@projects').its('response').should('deep.include', {
      statusCode: 200
    });
  });
```

The response from the API sends the following cache control header:
```
cache-control: private, max-age=600
```

### Versions
Cypress Version: 6.2.1
Browser: Electron 87
OS: Mac

**Comment by jennifer-shehane** [comment]
@flotwig Is this issue related to this? https://github.com/cypress-io/cypress/issues/14277

**Comment by flotwig** [comment]
@jennifer-shehane that one seems to be for 304 responses, this issue seems to be about requests that are never sent at all, so different

> If the intended behavior of Cypress is to mimic a user's experience, then we should not have to append query parameters to get a fresh set of data each time a query is presented.

@asithade Well, it is mimicing the user's experience... your browser caches responses in the real world!

But in the real world, responses don't change like that :)

I am not sure how Cypress can easily solve this problem for users, since we are intercepting requests at the HTTP level.

My current favorite idea is Cypress clearing the browser's cache between each test, so that it acts closer to your expectations. There is probably not an easy way for Cypress to manage the browser's cache during the runtime of your test, since clearing cache mid-test could affect the outcome. What do you think?

In the mean time, you can use the workaround of disabling cache automatically before running tests:

```js
before(() => Cypress.automation(
  'remote:debugger:protocol', 
  { 
    command: 'Network.setCacheDisabled',
    params: { cacheDisabled: true }
  }
))
```

**Comment by rooby** [comment]
@flotwig Where does that workaround go?

I have tried adding to `  on('before:spec', (spec) => {` in plugins, and to `before()` and `beforeEach()` in my spec files and none of those seemed to have any effect.

I am testing using Electron via cypress open.

If I run my single spec it works but then if I click the re-run icon it fails due to this issue.

**Comment by rooby** [comment]
I seem to have got it working for me with this code:

```javascript
      Cypress.automation('remote:debugger:protocol', {
        command: 'Network.enable',
        params: {}
      });
      Cypress.automation('remote:debugger:protocol', {
        command: 'Network.setCacheDisabled',
        params: { cacheDisabled: true }
      });
```

The way I use it currently is I have a load page function that I call on beforeEach() of all my tests, which runs the above code, then intercepts some requests, loads the requested page and waits on the intercepted requests.

**Comment by flotwig** [comment]
It should work to use it in your support file, or on a per-spec-file basis. You can read more about `before` and `beforeEach`: https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Hooks

Closing since the workaround of disabling cache is all that can really be done.

**Comment by shwarcu** [comment]
@jennifer-shehane could we please revive this topic and think of a correct solution rather than workarounds?
