### ISSUE TITLE
Intercept - unable to modify request body before sending to destination

### ISSUE THREAD

**Issue by eddif** [cypress-io/cypress#14537]
### Current behavior

In the runner, I can see that the request has been stubbed and in the console I can see that the body has been modified by the stub, but in the actual request payload it still contains the unmodified value.

Stub
![image](https://user-images.githubusercontent.com/13355055/104482598-f41fdf80-557b-11eb-91cc-47bddd031f8e.png)

Payload
![image](https://user-images.githubusercontent.com/13355055/104482689-131e7180-557c-11eb-9392-284ab9055f8c.png)

### Desired behavior

Payload should contain the value as shown here:
![image](https://user-images.githubusercontent.com/13355055/104482917-60024800-557c-11eb-9cb0-81c7cc1e0837.png)

### Test code to reproduce

```
    it("/// Not Working ///: displays an error if a request is submitted with count < 0", () => {

        cy.intercept('POST', 'http://localhost:3002/count', (req) => {
            // set the request body to something different before it's sent to the destination
            req.body = '-1';
        }).as('count')

        cy.getByTestId(id.submit).click(); // invokes post request

        cy.wait('@count').then(xhr => {
            // this asserts correctly (as expected)
            expect(xhr.request.body).to.equal("-1")
        })

        cy.getByTestId(id.error).should('be.visible'); // should display if value < 0
    });
```

### Versions

Applies to 6.2.0 and 6.2.1

**Comment by bahmutov** [comment]
What Cypress version are you using?

**Comment by eddif** [comment]
@bahmutov tested against 6.2.0 and 6.2.1 (updated issue)

**Comment by bahmutov** [comment]
<img width="404" alt="Screen Shot 2021-01-13 at 12 21 49 PM" src="https://user-images.githubusercontent.com/2212006/104486553-eaa57000-5599-11eb-8e3a-8889b2c9cbce.png">

Why does it show 500 first for `/count`?

**Comment by eddif** [comment]
It is currently wired to return a 500 for all requests. This is to simulate a service being down.

Note: as shown in the last screen shot it currently works as expected in this state

FYI - code behind for the submit - is just doing a simple fetch
```
  const submit = () => {
    fetch("http://localhost:3002/count", {
      method: "POST",
      body: JSON.stringify(count),
    })
  };
```

**Comment by bahmutov** [comment]
Does the server see the correct changed value `-1`? Because the network intercept happens _outside_ the browser, the DevTools Network tab shows the value _before_ it is changed. Can you print the value on the server?

**Comment by eddif** [comment]
It's a React state change that occurs to set the -1 and does not rely on a server response. 
Pushed the code to https://github.com/eddif/counter-app. 
It is a React SPA. I was trying to simulate the behavior of the 'click me' button makes a POST request.

**Comment by bahmutov** [comment]
@eddif The counter app is a Hyperapp + Cypress v1?

**Comment by eddif** [comment]
> @eddif The counter app is a Hyperapp + Cypress v1?

Hmm... 🤔 the count-app is a create-react-app with Cypress v6.2.1

**Comment by bahmutov** [comment]
Ok, turns out I had local old `count-app` folder right next to your `counter-app` folder.

After checking your app, and adding JS to see the posted request on the server

```js
const express = require("express");
const cors = require("cors");
const app = express();
const bodyParser = require('body-parser');
const port = 3002;

app.use(cors());
app.use(bodyParser.text())

app.get("*", (req, res) => {
  res.status(500).send();
});

app.post("*", (req, res) => {
  console.log(req.method, req.url, req.body)
  res.status(500).send();
});

app.listen(port, () => {
  console.log(`Server listening at http://localhost:${port}`);
});
```

I honestly do NOT see the problem you are describing. The app's state has `count:0` in your test

```js
it.only("/// Not Working ///: displays an error if a request is submitted with count < 0", () => {

    const value = -1
    cy.intercept('POST', 'http://localhost:3002/count', (req) => {
        // set the request body to something different before it's sent to the destination
        req.body = value.toString();
    }).as('count')

    cy.getByTestId(id.submit).click();

    cy.wait('@count').then(xhr => {
        console.log('xhr: ' + xhr)
        expect(xhr.request.body).to.equal("-1")
    })

    cy.getByTestId(id.error).should('be.visible');
});
```

The browser _sends_ `count: 0` when making the request - that's what the app has.
<img width="1274" alt="Screen Shot 2021-01-16 at 11 57 30 AM" src="https://user-images.githubusercontent.com/2212006/104817864-19b61e80-57f2-11eb-8c32-fe7d86462bed.png">

The the Cypress proxy intercepts the request _outside the browser_, changes the body to `-1` and it continues to the server where it prints `-1`

<img width="814" alt="Screen Shot 2021-01-16 at 11 58 56 AM" src="https://user-images.githubusercontent.com/2212006/104817881-37838380-57f2-11eb-97d5-3c01f0986491.png">

Well, the request gets back tot he app, and what does it do? Nothing really. The frontend app does not handle errors from the `fetch` at all. The app stills thinks the `count=0` since why would it think otherwise? So it does not show anything different, and does not show the error message.

I will probably update our documentation to clarify this point that you see the original outgoing request in the Network tab, and it is changed later outside the browser.
