### ISSUE TITLE
Not able to get element and Timedout Error when the element is coming as visible(by removing display:none) style property.

### ISSUE THREAD

**Issue by senthiltr** [cypress-io/cypress#14629]
my detailed query is below:
In my application the drop down combobox tagged with ul elements under div. And this div elements are initially having display: none in the style property.
This display : none is removing when i click the other div element. I am clicking this div element in the middle after completing the previous fields. So in middle the element is attaching with the dom?. In this way, i am not able to get the visibility changed element. How to over come this issue?
If you post example for this scenario it would be more usefull.
i gone through below link and tried to change display; none to display : none !important.
https://glebbahmutov.com/blog/debug-visibility/
in my application manually i verified the display: none element is coming as visible or not.

**Comment by jennifer-shehane** [comment]
@senthiltr Can you provide a reproducible example. I got this much of what you're explaining, but then am confused at the part about 'attaching with the dom'.

`index.html`

```js
<html>
<body>
  <div id="button">Click me</div>
  <div id="combobox" style="display: none;">
    <ul>
      <li>Option 1</li>
      <li>Option 2</li>
      <li>Option 3</li>
    </ul>
  </div>
  <script>
    document.getElementById('button').onclick = () => {
      document.getElementById('combobox').style = 'display: block;'
    }
  </script>
</body>
</html>
```

`spec.js`

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('button').click()
})
```

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
