### ISSUE TITLE
Cypress 6.2.1 with docker : most of types and clicks are failling 

### ISSUE THREAD

**Issue by olimpiu-galea** [cypress-io/cypress#14624]
### Current behavior
I'm running cypress 6.2.1 through docker and 99% of tests are falling. The clicks are not made, {Enter} is not 'typed' at all. 

### Desired behavior
I revert my code to Cypress 5.4 ( without intercept ) and it's working as expected. So I believe the issues are with the new version on cypress, am I missing something ?
### Test code to reproduce

Any simple code, mine looks like 👍 
selectCustomer: ($customerName) => {

            
               cy.get(customerPage.selectCustomer)
                .type($customerName, { force: true })
                .then(el => {
                    cy.wait('@waitForCustomer').then((xhr) => expect(xhr.response.statusCode).to.be.eq(200))
                    cy.wrap(el).focus().type('{Enter}')
                })
        },
customerPage.selectCustomer("name)

### Versions
Cypress 6.2.1
Run through DOCKER

**Comment by bahmutov** [comment]
Can you provide a reproducible example please? Something we can run plus commands to run it?

**Comment by olimpiu-galea** [comment]
@bahmutov 
I sent you an email with the repo source code, I can't post here a runnable example, since this is a public thread.

**Comment by bahmutov** [comment]
I looked at the code and noticed that you mostly do not have any assertions. Thus the test quickly clicks and types, while the application struggles to catch up. For example when you type the customer name, the dropdown gets initialized. Then you pick the first customer like this

```js
CustomerPageObj.searchCustomer()
  .type($customerName, { force: true })
  .then(el => {
      cy.wait('@waitForCustomer').then((xhr) => expect(xhr.response.statusCode).to.be.eq(200))
      cy.wrap(el).type('{Enter}')
  })
```

Well, in Docker the server response might be slower so when you do `cy.wrap(el).type('{Enter}')` the drop down is still empty. 

You should: generate video. Why make your own debugging harder by disabling it?

Also read the blog post https://www.cypress.io/blog/2020/03/20/working-with-select-elements-and-select2-widgets-in-cypress/ where I show specifically select widget with fetched data. You want to make sure the widget shows the data before typing "Enter".

Please add more assertions to your tests, seems the test runner because it is fast runs faster than the app. Just assertion that the XHR happens is not enough - because the app needs time to render the UI after the XHR finishes.
