### ISSUE TITLE
XHR's displaying aborted

### ISSUE THREAD

**Issue by Elif5757** [cypress-io/cypress#14649]
XHRs are shown as 'aborted' in the Cypress test runner. Chrome dev tools Network tab shows successful XHRs and the angular app is working as designed, completing requests with no errors. 
I'm using cy.route2() for requests with mock payloads. 
I know that there are other similar issues but I can only read that it has been fixed. Then why does this happen to me?
What do i have to do?

Cypress Version: 6.2.1

![image](https://user-images.githubusercontent.com/62025022/105175978-ea225180-5b24-11eb-97e4-f3ee28d3a4d6.png)

**Comment by jennifer-shehane** [comment]
There's this issue involving aborted requests. https://github.com/cypress-io/cypress/issues/9549

We don't have any issues currently opened involving requests being aborted that are not actually aborted by the application itself. 

Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. Without this we can't move forward with investigating.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
