### ISSUE TITLE
Cypress fails and throws page load error while working with windows/Page alerts 

### ISSUE THREAD

**Issue by suchitrachavan** [cypress-io/cypress#14676]
Hi Team I am facing issues
When i click on a button
one unexpected popup (window,URL) opens up
then cypress fails

![image](https://user-images.githubusercontent.com/61357214/105383253-e8b55f80-5bde-11eb-8787-7f27083c8076.png)

Browser Electron
Cypress version 6.14.10

**Comment by bahmutov** [comment]
Can you please provide reproducible code example? Or the URL you are testing? Are there any errors in the DevTools console?

**Comment by suchitrachavan** [comment]
@bahmutov my code:
       cy.get('[data-cy=container-btnlink]').as('referalPagebtn')
        cy.get('@referalPagebtn').should('be.visible')
        .find('button')
        .contains('Share via SMS')
        .click()
after this a window pop up opens up and cypress freezes ... also i have not written any after each block

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end - we need the HTML to run the test code against in your example. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
