### ISSUE TITLE
Cypress 6.2.1 breaks retries with certain reporters.

### ISSUE THREAD

**Issue by smccarthy-godaddy** [cypress-io/cypress#14681]
### Current behavior

I use [mocha-elk-reporter](https://github.com/mpahuja/mocha-elk-reporter) and when I use Cypress 6.2.1, I see the test object in the reporter is :
```
{
  err: {
    ...
  },
  state: 'failed',
  timings: {
    ...
  },
  wallClockStartedAt: '2021-01-21T19:36:47.403Z',
  wallClockDuration: 15648
}
```

The reporter I use, requires title, fullTitle(), duration, err, context (sometimes undefined, but that's OK since its not a method). The code that uses those fields [here](https://github.com/mpahuja/mocha-elk-reporter/blob/master/index.js#L126-L130). I believe this is the commit that broke it https://github.com/cypress-io/cypress/pull/14381/files#diff-66fb525702fae53dc8b6f357091e89288ff078cf0e7411a286d852cb73e0fc2eR134

### Desired behavior

Instead of only choosing a few fields to use in the retry, can you exclude the ones that were causing the issue ? perhaps make it configurable somehow? Or at the very least, include duration, title, fullTitle(), and context ?

### Versions

Last working version of Cypress : 6.2.0
Version that broke it : 6.2.1
Pull Request that broke it : https://github.com/cypress-io/cypress/pull/14381/files

**Comment by Bkucera** [comment]
sure, thanks for giving an example. It should be simple to fix.

**Comment by Bkucera** [comment]
hi @smccarthy-godaddy. The `prevAttempts` property that mocha reporter is accessing is not standard mocha, so no mocha reporter compatible with the mocha spec should ever access `runnable.prevAttempts` unless it has been modified specifically to support Cypress retries. That's what appears to be the case with `mocha-elk-reporter`. This is not an issue in Cypress because the prevAttempts array should not duplicate data such as title/duration when it's the same as the runnable with the prevAttempts property. 

So mocha-elk-reporter needs to be modified to pull those props off of the main test runnable.

**Comment by smccarthy-godaddy** [comment]
Thanks @Bkucera  . I will post that to the mocha-elk-reporter issues list.
