### ISSUE TITLE
Cypress 6.3 does not enforce retries configuration

### ISSUE THREAD

**Issue by fgiroud** [cypress-io/cypress#14697]
### Current behavior
Hello, we are not sure if it's since 6.3, but the retries config is not enforced
It happens on both run and open mode
* open mode
* cypress dashboard

### Desired behavior

That the retries are configured according to cypress.json.
If there is an alternative configuration to set up it's okay too

### Test code to reproduce

in cypress.json (See the code in [this PR](https://github.com/OpenRefine/OpenRefine/pull/3510))
```js
{
	"integrationFolder": "./cypress/integration",
	"nodeVersion": "system",
	"numTestsKeptInMemory": 1,
	"retries": {
		"runMode": 2,
		"openMode": 1
	},
	"env": {
		"OPENREFINE_URL": "http://localhost:3333"
	}
}
```

[And see the matching run in cypress dashboard](https://dashboard.cypress.io/projects/s5du3k/runs/179/test-results/f4a6af89-c2a6-4d57-b3ff-d05b5b03bad1), there have been 3 retries

On Open mode (locally), tests are retried 2 times

### Versions

6.3

**Comment by jennifer-shehane** [comment]
This is expected behavior. When you define 'retries' that's the number of times *beyond* the 1st try to run the test. https://on.cypress.io/test-retries So:

- 1 initial run + 2 retries = 3 attempts
- 1 initial run + 1 retry = 2 attempts

We struggled a lot with this implementation, what to name the config to make sense. This is what we settled on. But I can understand, it's a bit confusing.
