### ISSUE TITLE
Execute describe() block only after before() hook has finished execution

### ISSUE THREAD

**Issue by rajneeshm49** [cypress-io/cypress#14773]
I have some code in describe block (not inside it() block) that depends on code in before() hook. The code in describe() block starts execution even before before() hook completes execution. Can I delay or start the execution of describe() context only after before() hook has finished execution in Cypress and code is ready to be used in describe() block.

**Comment by bahmutov** [comment]
1. Do you have `async` anywhere in the `before` block? Remove it
2. Can you paste your spec code?

**Comment by rajneeshm49** [comment]
No I do not have any async code in my spec file.

My example is quite large so Iam pasting something similar code that is quite similar to mine
describe("Array check", () => {
  const files = [];
  before(() => {
    files.push("a");
    files.push("b");
  });

  describe("Check files array", () => {
    files.forEach(ele => {
      it("tests each element", () => {
        expect(ele).to.be.equal("a");
      });
    });
  });
});

**Comment by bahmutov** [comment]
Gotcha. So the problem is that you are creating the tests on the fly. When the `describe` block is processed, there are not `it...` calls (since the `files = []` initially), and thus the `before` block does not run (since there are no tests to run it _before_) 

Since you want to create tests dynamically, it is not supported by default, you would need to create test definitions ahead of time (as a JSON for example) and then create them in the file. See our recipe https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/fundamentals__dynamic-tests for how to do this.
