### ISSUE TITLE
Cypress stops triggered scrolling

### ISSUE THREAD

**Issue by apalaqa** [cypress-io/cypress#14829]
### Current behavior
I have navbar and main view. Angular app emits event on clicking on section in navbar that triggers scroll to the section in the main view. When Cypress clicking on the section in navbar it scrolls a little and stops not reaching the section. I noticed that when Cypress clicking on the section and receiving a random XHR call the scrolling performs longer until XHR is not handled.
I tried to use different wait options but it doesn't work.

### Desired behavior
Scrolling should not be interupted.

### Versions
6.3

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
