### ISSUE TITLE
cypress adds __/ while using cy.visit()

### ISSUE THREAD

**Issue by sukheja-varun** [cypress-io/cypress#14897]
I am trying to use `cy.visit('https://web.telegram.org');` but instead it hits `https://web.telegram.org/__/`

<img width="676" alt="Screenshot 2021-02-04 at 12 27 09 AM" src="https://user-images.githubusercontent.com/21065146/106795137-9167b400-660e-11eb-88e8-c20dd68ebb7e.png">

**Comment by jennifer-shehane** [comment]
Can you try setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

**Comment by sukheja-varun** [comment]
already tried that but didn't work 😞

**Comment by panzarino** [comment]
Cypress issues a request to `https://web.telegram.org/__/` in order to load Cypress from that domain. It's not actually sending a request to that domain, it's really just requesting an internal Cypress document. You can read more about why we have to do that [here](https://on.cypress.io/web-security).

Looks like Telegram is using a service worker which is preventing Cypress from working properly (you can test by manually removing it and refreshing, which causes everything to work properly). This issue has been reported in #702, and there are a number of workarounds presented in that thread, so I'd suggest trying some of those out. (Closing this issue as duplicate)

If you're trying to automate Telegram, they do have some [official APIs](https://core.telegram.org/) that might work better than Cypress for that purpose.
