### ISSUE TITLE
False Failures in UX

### ISSUE THREAD

**Issue by CinkadeusBG** [cypress-io/cypress#14896]
There are only 13 tests in this suite and all 13 are passing yet the UX is stating that this one test if failing.  Re-running the suite may clear this up but every few runs this will happen again.  We're mid-way into an upgrade to Cypress 6 from 5.

![image](https://user-images.githubusercontent.com/59319282/106794255-2faf4600-661e-11eb-84ad-e82fbb8c9e0e.png)

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
