### ISSUE TITLE
xhr displaying as aborted but they are not

### ISSUE THREAD

**Issue by devjalpesh** [cypress-io/cypress#14898]
XHR displaying as aborted but they are not, all other XHRs look fine in the runner

![1](https://user-images.githubusercontent.com/78503900/106798080-7d11ce80-6683-11eb-8529-927973a7e9aa.png)

Cypress Ver 6.3.0

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
