### ISSUE TITLE
Retry instead of Fail/Pass on non-200 Status Codes

### ISSUE THREAD

**Issue by tizmagik** [cypress-io/cypress#1490]
### Is this a Feature or Bug?

Feature

### Current behavior:

[failOnStatusCode: false](https://docs.cypress.io/api/commands/visit.html#Arguments) will silently swallow errors and skip the test on a per `visit()` basis.

### Desired behavior:

While the current behavior is a valid use case, our use case is that non-200 status codes are sometimes expected (because of how the app is deployed for testing internally) and instead we would like the ability to _retry_ instead of swallow, skip and continue.

So maybe a `retryOnStatusCode: true` or something (or maybe instead of a Boolean it could take an Integer for number of retries).

cc, @ValerieThoma

**Comment by brian-mann** [comment]
Can you paste an image of exactly what you're receiving from your server? Do not turn off `failOnStatusCode` so that Cypress actually errors.

There is an existing open issue about retrying visits and requests when the server itself isn't accessible such as ECONNREFUSED.

However those errors are fundamentally different than say a `5xx` error coming from your server. If your server is responding with those statuses, it would be difficult to know when you actually *expect* those to occur vs when you want to retry.

To clarify - here's an example of an error which would **would** retry.

![screen shot 2018-03-25 at 11 13 48 am](https://user-images.githubusercontent.com/1268976/37876647-a0a75648-301d-11e8-9ac2-332450d9d2b2.png)

However if your server were to send a `5xx` error and send back HTML such as: "hey I'm overloaded, sorry, an error happened" that is a completely different beast and one where we could not automatically do the right thing without adding an extra option (as you suggested).

The goal here though would be to silently retry under the hood as the default so that you'd be insulated from momentary hiccups with the network, dns, server booting, etc.

**Comment by tizmagik** [comment]
It is a `502` and it's valid behavior from Cypress' perspective (we're investigating the root cause), but at this point it's more or less expected because of the way our internal test servers are provisioned. There will always be at least a 502 because they are fronted by an nginx proxy.

![image](https://user-images.githubusercontent.com/244704/37918506-367a2e30-30ef-11e8-8713-f6ba842781e0.png)

If this test were running against production, then it would be totally valid to fail on a `502`, but in this case, we expect a `502` and would rather a retry or two instead of failing.

Hope that helps @brian-mann !

**Comment by brian-mann** [comment]
I see... I think it's debatable whether we make `cy.visit` retry on status code errors. I can totally see us doing it for network related events (because these things naturally happen), but if you server **actually responds** its hard for me to imagine retrying is a good idea.

For instance, a visit is not idempotent and there could be side effects of retrying. A server may decide to respond appropriately and do things like set cookies if it wanted to. Retrying again would then potentially cause a different thing to happen on the next request...

I'm leaning towards creating natural retryability **only** for network errors. For application errors (such as the one you're experiencing) I believe the easiest thing is to handle them yourself by creating a recursive function. Something like this should work...

Disclaimer: I am writing this code right now, it may not work but hopefully in theory you should understand what it's doing.

```js
const is500Re = /^5/

const visitWhenStable = (url, options) => {
  function req () {
    return cy.request(url, { failOnStatusCode: false ))
    .then((resp) => {
      if (is500Re.test(resp.status)) {
        return req()      
      }
  
      return cy.visit(url, options)
    })
  }
  
  // kickoff
  return req()
}
```

**Comment by tizmagik** [comment]
Yes, that's fair and makes sense, thanks @brian-mann -- will give that a shot on our end and post back if there's any further issues. Right now we're planning on "overwriting" the `cy.visit()` command to transparently check for `200` first so that we don't have to change our test code much if at all.
