### ISSUE TITLE
Can not change header of type “host” within intercept

### ISSUE THREAD

**Issue by jalehn** [cypress-io/cypress#14920]
### I expect to change the headers within a cy.intercept() like this:

adding a new header works perfectly fine via intercept:
```JS
it('adds a new Header', () => {
    cy.intercept('/detect/what-http-headers-is-my-browser-sending', (req) => {
        req.headers['SomeHeader'] ='NewHeader';
    })
    cy.visit('https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending');
})
```
![NewH](https://user-images.githubusercontent.com/55732381/106888997-a95f3680-66e7-11eb-8b3f-39f439ccc193.PNG)

setting a existing header that is not host does also work:
```JS
it('overwrites existing header', () => {
   cy.intercept('/detect/what-http-headers-is-my-browser-sending', (req) => {
        req.headers['user-agent'] ='Overwrites user agents with this text';
    })
    cy.visit('https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending');
})
```
![OverwriteH](https://user-images.githubusercontent.com/55732381/106889418-4326e380-66e8-11eb-8417-36985f8d08a2.PNG)

Setting the host header does not work:
```JS
it('does not overwrite host header', () => {
    cy.intercept('/detect/what-http-headers-is-my-browser-sending', (req) => {
        req.headers['host'] ='Should set new host header';
    })
    cy.visit('https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending');
})
```
![No Overwrite](https://user-images.githubusercontent.com/55732381/106889997-0f988900-66e9-11eb-932b-7e23ba77857c.PNG)

Is this expected behavior?

**Comment by flotwig** [comment]
I think the problem here is that there are basically two sources of truth for the `Host` header here -

* `req.headers.host` - contains the host header sent by the browser
* `req.url` - contains the fully qualified URL (including host)

For your `host` change to stick, you need to change the URL. For example:

```js
it('does not overwrite host header', () => {
    const newHost = 'foo.com'
    cy.intercept('/detect/what-http-headers-is-my-browser-sending', (req) => {
        req.headers['host'] = newHost // can be skipped too, it will be set automatically
        const url = new URL(req.url)
        url.hostname = newHost
        req.url = url.toString()
    })
    cy.visit('https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending');
})
```

This still fails, because `whatismybrowser.com` uses `Host` to provide virtual hosting, so it will end up in a redirect loop. But basically to override `host`, you must override `url`.

---

Extremely wacky advanced use case: If you wanted to force a connection to a specific IP with a specific Host header, I believe you could set your URL's hostname to the desired IP address, and set the Host header to the desired domain, and it would work.

**Comment by flotwig** [comment]
Closing since there is nothing to do.

**Comment by jalehn** [comment]
thank you!

**Comment by gyh2016** [comment]
Hi @flotwig, thanks for explaining the two sources of the `Host` header(actually only one from req.url).

But in my test case, I really need to modify the `Host` header to a different host. For example:

```
cy.intercept({ url: "some_path" }, (req) => {
  req.headers["host"] = "bbb.com";
  req.url = "aaa.com";
  req.reply();

  // or use redirect
  // req.redirect("aaa.com", 302);
}).as("some_alias");
```

When visit aaa.com, it only works when the `Host` header is equal to "bbb.com".

`curl` can help me do that. It supports set `Host` header by `-H` parameter such as `curl "aaa.com" -H "host:bbb.com"`.

Does Cypress support to customize `Host` header by force like this?
