### ISSUE TITLE
Issue with test occurring only when run in Amplify CI

### ISSUE THREAD

**Issue by cwinters8** [cypress-io/cypress#14953]
Hello,

I have a somewhat interesting issue. I have a test that types input into a form and then checks for a DOM change after the form is saved. This runs fine locally, but one of the steps is failing when running the tests in Amplify CI. If you look at the video below, you'll see that about 0:20, the first letter is entered, then erased, then the rest of the text is entered. The test then fails because it can't find the matching text on the corresponding DOM element.

https://user-images.githubusercontent.com/40615752/107096085-8f008800-67cf-11eb-8354-5e7d53cb9409.mp4

Here is a gist with my spec: https://gist.github.com/cwinters8/948dab600446a1823ece19cc16db4fac
Line 129 is where the function is called where the issue seems to be happening. As you can see, I'm using this same function with several other element types and it works fine for those so I'm rather confused what's going on here.

Thanks for any assistance or clarification about what might be happening here.

**Comment by jennifer-shehane** [comment]
Looking at the video - it seems like:

- the 'submit' button is being clicked
- POST graphql request goes out
- test continues typing 'Q' into next input of refreshed DOM
- POST graphql responds with 200
- test continues typing 'uestion...' into input

My guess is that some action in the application happens when the POST returns 200 that is clearing the input or refreshing the DOM, which ends up splitting the typing up. This flakiness only occurs on a slower network which may happen on CI. 

I would write an assertion after clicking the 'submit' button, to verify that the POST responds 200 before continuing on to type into the next input (using `cy.intercept()` and `cy.wait()`. See if this helps the situation on CI.

We have some other suggestion you can follow on troubleshooting why tests are fail in CI but pass locally if this doesn't help with your issue: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

**Comment by cwinters8** [comment]
This makes a lot of sense. Thank you for the help!! I'm testing out cy.intercept() and cy.wait() and will attempt a CI run soon and get back to you on how things turn out.

**Comment by cwinters8** [comment]
Fixed! @jennifer-shehane thanks very much for the suggestion to use cy.intercept/cy.wait. That was key 😄
