### ISSUE TITLE
404 by getting the popper.js.map

### ISSUE THREAD

**Issue by ebors-sysnetcz** [cypress-io/cypress#14968]
Hi, 

in a new project following the tutorial sites (https://docs.cypress.io/guides/getting-started/writing-your-first-test.html) with this example:

![image](https://user-images.githubusercontent.com/49151505/107211836-60202700-6a06-11eb-8d71-68433e7e8262.png)

there is a 404 error by getting the popper.js.map file

![image](https://user-images.githubusercontent.com/49151505/107211914-7cbc5f00-6a06-11eb-82b2-5155b3103d4e.png)

Version:
Cypress package version: 6.4.0
Cypress binary version: 6.4.0
Electron version: 11.2.1
Bundled Node version:
12.18.3

Windows 10

**Comment by jennifer-shehane** [comment]
I only see this on first run of a test suite. It looks like this `popper.js` is a dependency of our `@cypress/react-tooltip`, but I see our tooltips are working in the Test Runner. I think this can be safely ignored since this is just s sourcemap file - seeing some other comments from this not loading for other packages

**Comment by webia1** [comment]
Thank you Jennifer for your endlessly patient and kind feedbacks for the time being; I've read a lot of them. Thank you for great Cypress. 

Since this is the only error/warning message in Chrome DevTools (yes, I confess, I'm a nerd), I would like to get rid of it, just for the sake of clarity. 

I'm sorry, I can't stop it, it just looks terrible to me, I can no longer sleep at night.: :cold_sweat:

<img width="460" alt="DevTools_failed_to_load_popper_js_map" src="https://user-images.githubusercontent.com/2741558/146150454-faa439b5-58ce-4323-92b9-54e253d1185f.png">

**Comment by Niemetz** [comment]
Hi @webia1 !!!
  Did you find a solution for this?
  In my case, it causes Test Runner to crash!!!
  Thanhs!

**Comment by saylestyler** [comment]
> Hi @webia1 !!! Did you find a solution for this? In my case, it causes Test Runner to crash!!! Thanhs!

I'm getting this as well when running tests that formerly passed... along with this: 

![image](https://user-images.githubusercontent.com/20520284/158441876-861ac355-60db-4035-9c80-fa7e172ada45.png)

I dont know if it's "causing" my tests to crash, but the stack trace has no error and there are no errors that have not been changed to `throw new Error('some message')` format

![image](https://user-images.githubusercontent.com/20520284/158441972-dc847e1e-8b4c-489a-8ed8-9739c12c31db.png)

**Comment by webia1** [comment]
sorry, I've seen it now, no, no solutions yet,..

**Comment by efraimpc** [comment]
hello, we are dealing with same issue as we started using cypress, unfortunately, this is causing the application to detect it and try to handle it into a 404 error page and making the test fail because of that.

**Comment by felipe-ff** [comment]
Same issue here, had to stop testing a modal because of that.

**Comment by tatianajiselle** [comment]
this was happening to me and crashing my tests suite.

I removed node_modules and reinstalled, suddenly it worked again ...

Im using node v.14.10.0 and cypress 12.9.0

**Comment by zhendalf** [comment]
Hey @jennifer-shehane. I see that you closed the issue, but it's not resolved. The popper.js.map warning is always the first one in the console, which is quite annoying. It's not crashing anything for me, but it's been there for as long as I've used Cypress.
<img width="692" alt="CleanShot 2023-04-18 at 08 51 19@2x" src="https://user-images.githubusercontent.com/5859177/232649443-b7be27a6-a109-4561-9911-ae888de0e2fa.png">

There should be a way to fix the problem, and I think that doing so would be better than ignoring it. Because people will keep [bringing](https://github.com/cypress-io/cypress/issues/23648) [it](https://github.com/cypress-io/cypress/issues/14968) [up](https://github.com/cypress-io/cypress/issues/14724).
