### ISSUE TITLE
Webpack Compilation Error when browserslist is present in project root

### ISSUE THREAD

**Issue by Viktor-Rus** [cypress-io/cypress#15014]
I get the error when trying to run tests through the Runner:

Error: Webpack Compilation Error
./cypress/integration/integration/examples/action.spec.js
Module build failed (from C:/Users/user/AppData/Local/Cypress/Cache/5.4.0/Cypress/resources/app/packages/server/node_modules/babel-loader/lib/index.js):
C:\Users\user\IdeaProjects\mtstv-smartweb\browserslist:1
This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
^

SyntaxError: Invalid or unexpected token

**This problem was not resolved in issue 8864**

Cypress package version: 6.4.0
Cypress binary version: 6.4.0
Electron version: 11.2.1
Bundled Node version: 12.18.3

**Comment by diald** [comment]
Bump. This is still a problem with vanilla installs of Angular 9 and Cypress.

**Comment by 7dev70** [comment]
I got excactly the same error message

the problem seems ubiquitous in various forms on the internet, but i could not find a solutions that worked.

ng --version:
  
Angular CLI: 9.1.12
Node: 10.20.0
OS: linux x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/service-worker           9.1.13
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Comment by michas84** [comment]
same here. any news?

**Comment by adrienharnay** [comment]
I found that this only happens because of a line in the root tsconfig.json of my project:
```
compilerOptions: {
  baseUrl: '.',
}
```

If I remove it, the problem is gone. Overriding it in `cypress/tsconfig.json` doesn't work.

**Comment by mikerandall** [comment]
Yup, same here. Removing the `baseUrl` from `compilerOptions` fixes it as @adrienharnay pointed out. But removing it isn't an option.

**Comment by adrienharnay** [comment]
Forgot to point out that renaming browserslist to .browserslistrc fixes the issue too, but isn't an option either.

**Comment by kevb10** [comment]
has anyone figured out a fix for this?

**Comment by Zenuka** [comment]
> Forgot to point out that renaming browserslist to .browserslistrc fixes the issue too, but isn't an option either.

That fixes the problem for me as well but why wouldn't that be an option? I see in the documentation that .brwoserlistrc file should be accepted: https://github.com/browserslist/browserslist#queries. Am I missing something?

**Comment by CoryDanielson** [comment]
I have this issue with a project root that contains a file named `.browserslistrc`
