### ISSUE TITLE
Cypress does not show tab contents inside pop up window

### ISSUE THREAD

**Issue by asankasira** [cypress-io/cypress#15071]
### Current behavior
  I am automating a web application using Cypress and I came across a popup window with sub tabs. While switching among subTabs, a random behavior could be observed  where subTab contents are not loaded. Please refer to attached screenshots
  

![image](https://user-images.githubusercontent.com/9448392/107755438-cbd8fb80-6d48-11eb-85a4-e459efeb9eee.png)

### When switching the popup window subTab using Cypress

![image](https://user-images.githubusercontent.com/9448392/107756059-a6002680-6d49-11eb-8eff-09ab130c13ef.png)

Please not that this occurs randomly, sometimes it works fine

### Desired behavior

Contents should be displayed as shown below and controllers should be accessible all the time. Tab switching work fine in other pages, This issue occurs randomly when tabs are present inside a popup window.

![image](https://user-images.githubusercontent.com/9448392/107756536-5a01b180-6d4a-11eb-8295-46776c37d935.png)

### Versions
    Cypress 6.3.0

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by asankasira** [comment]
Hi @jennifer-shehane,

Thanks for the reply, We have found the root cause for this behavior after some time, but forgot to update it. It was due to some pop-up content removal of code for the Vaadin combo boxes to reduce flakiness of some tests while executing GUI form related tests. We have found the root cause for this behavior after some time, but forgot to update it. It was due to **some pop-up content removal of code for the Vaadin combo boxes** to reduce flakiness of some tests while executing GUI form related tests.

`Cypress.$(this.cmbClassPopUpContent).remove();`

 It was working fine for all locations, being the only exception of this issue I reported where tab switching is required within a pop-up window. Strange thing is this occurred randomly as well.

I have fixed this to have a different mechanism rather than pop-up content removal for combo boxes caught up with this issue and it solved the problem completely. :)
