### ISSUE TITLE
can't modify request with cypress.intercept()

### ISSUE THREAD

**Issue by kfir-mm** [cypress-io/cypress#15139]
Hi,

recently upgraded Cypress from v4.5 to v6.5 
my hope was to use `cy.intercept()` in order to override some of the headers for one of my requests before sending them to the BE.

here is what i tried:
`
cy.intercept({
method:'POST',
path:'/my-request'},
req => {
req.headers.myToken = 'token-override'
})
`
i added some console logs to see that this indeed works and all seem fine.

however, when looking into the request, both in the network tab and when clicking on it in the cypress UI, i see that the token was not changed.

another thing i noticed, when printing the request to the console inside this callback, that the header name is all lower-case, while the real one is not. tried to modify it as well (`req.headers.mytoken = 'token-override'`), with similar results.

hope you can help

Thanks!

**Comment by bahmutov** [comment]
In https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__intercept we have a header spec that adds a request header and confirms the server receives it. Note that because the header is added _after_ the request has left the browser, the Network tab does not show it - it is added AFTER it. If you wait for the network request you should be able to see that header though.

The below screenshots are from a presentation https://slides.com/bahmutov/how-cy-intercept-works#/11 (click down arrow to see the column of slides)

<img width="922" alt="Screen Shot 2021-02-18 at 10 12 50 AM" src="https://user-images.githubusercontent.com/2212006/108377270-dd4f5700-71d1-11eb-9711-884cb817dcc7.png">

<img width="895" alt="Screen Shot 2021-02-18 at 10 13 08 AM" src="https://user-images.githubusercontent.com/2212006/108377309-e809ec00-71d1-11eb-9015-ec33eb10c605.png">

<img width="907" alt="Screen Shot 2021-02-18 at 10 13 25 AM" src="https://user-images.githubusercontent.com/2212006/108377352-f0fabd80-71d1-11eb-8cc7-0fccf19fec0c.png">

I will update our documentation to make it clearer

**Comment by kfir-mm** [comment]
Thank you very much for the prompt response!

so, basically, I can't verify in the FE that the header is indeed updated -
only in the BE.

**Comment by bahmutov** [comment]
Yes, you could wait and verify from the spec
