### ISSUE TITLE
Also run lifecycle hooks (before:run, after:run, before:spec, after:spec) in plugins while in interactive mode

### ISSUE THREAD

**Issue by yentheo** [cypress-io/cypress#15138]
### What would you like?

As described in the last comment of [issue 6665](https://github.com/cypress-io/cypress/issues/6665) the lifecycle hooks `before:run`, `after:run`, `before:spec` and `after:spec` in a plugin don't run while in interactive mode. 
I don't really get the reasoning behind this choice. Maybe this is hard to do technically. But I would like these events to be triggered when running in any mode. 

### Why is this needed?
The reason I would like to use these events is to subscribe and unsubscribe to some of my own events that get triggered by my system to do some integration tests. Another use case I would assume is to prep some data or clear some data that is managed by a plugin, so not to use the beforeEach and stuff of the tests themself but from the plugin.

**Comment by jennifer-shehane** [comment]
@yentheo Thanks for detailing the use case. Any more detail would be appreciated since feedback will help us understand how to implement it.

We're trying to be more thoughtful about just building features out because we can and listening to people to see if there is a use case for it first - and so far we hadn't had many people request the need for interactive mode. Plus it is slightly more complicated than run mode.

**Comment by yentheo** [comment]
Hey @jennifer-shehane I will try to describe our exact use case a bit better.
So at the front of our application we have a spa, which we want to test, this spa receives data from a server. Now we can feed this data that the server has, from some client. It looks something like this:

spa <--> server <--> data-source (some client that pushes data)

What I created in cypress is a plugin in which I can manipulate the data that is known by our server so I can check if our spa is showing the data we want to show. E.g. of how a test of ours looks like

1. I execute a task on our plugin that pushes some data to our server, like let's say some Employee information
2. I open up the website and check if the employee information is shown like I expect it

Something our application also does is sent events to the data source too. So when I click a button, that event is sent to the server and the server proxies it through to the data-source. Now in the case of our e2e tests, the data-source we're talking about is my plugin. What I want to do in my plugin is begin to subscribe on the possible events the server can send me and unsubscribe when my run or spec is done. E.g.

1. Spec starts, I subscribe to a "delete-employee" event in my plugin
2. I open the website
3. Click the "delete employee" button
4. I wait for the event to be triggered in my plugin
5. I unsubscribe to the event

I could just subscribe to the events in the startup of the plugin but I need to unsubscribe afaik because when running it with a watch, it keeps some stuff at run time and I don't have a hook to unsubscribe.

**Comment by KrekkieD** [comment]
I have the same use case as @yentheo. Initial run of the spec goes well because the hook feeds our server with mock data. A re-run then fails because the mock data was used up and no new mock data was fed because the hook did not run.

**Comment by jennifer-shehane** [comment]
There's an `experimentalInteractiveRunEvents` configuration available since Cypress 7.1.0. (Sorry I forgot to update the issue). This configuration allows listening to the `before:run`, `after:run`, `before:spec`, and `after:spec` events in the plugins file during interactive mode (during `cypress open`).

We'd love to hear any feedback on if this is working as expected, so that we can decide if the implementation should change and if we can merge this into the core product.

```json
{
  "experimentalInteractiveRunEvents": true
}
```

**Comment by KrekkieD** [comment]
Hi @jennifer-shehane, it works but apparently not for re-runs or when running multiple specs. I'm running v7.3.0

**Comment by jennifer-shehane** [comment]
@KrekkieD Yeah, the feature is experimental because we didn't have a lot of feedback from users on the feature request - and there are different situations that need to be accounted for with `cypress open` than `cypress run`. As you mentioned, 

- rerunning - do we rerun the `before:spec` events? Do we rerun the `before:run` events?
- rerunning - do we run the `after:spec` events when you click 'rerun'? What if there is cleanup in there that's needed before the spec runs again.
- Running 'all specs', which events do we run? What if you stop the run mid-way? 

Any details about the use case or code currently running would be helpful in us making these decisions.

**Comment by KrekkieD** [comment]
I guess it indeed depends on the type of actions you'd expect in the hooks 🤔 

perhaps additional hooks are required to cater to this ambiguity:
*  `before:spec:once` which runs only once, regardless of rerun
* `before:spec` runs every time a spec starts (run, rerun, running multiple specs)
*  `after:spec:once` which runs only once, regardless of rerun
* `after:spec` runs every time a spec ends (run, rerun, running multiple specs, spec stop, spec failure)

alternatively, perhaps a flag can be added to the `spec` argument in the hook that indicates what type of run we're looking at. This way it's up to the consumer to decide if the hook should be handled, and in which way. Something along the lines of:
```javascript
on('before:spec', spec => {
  switch (spec.runType) {
    case 'run': { ... }
    case 'rerun': { ... }
    case 'multiple': { ... }
  }
});
```

Either way would work for us.

**Comment by jennifer-shehane** [comment]
Having the `mode` be accessible is interesting. I thought this would already be available on the `config` object in the plugins file, but it's not. I think this should be available here.

**Comment by tvsbrent** [comment]
Just a bit more feedback on this feature for my use case.

I have several component libraries that I want to have do a static Storybook build prior to starting up Cypress. The individual tests will then load the static HTML file as part of running the tests. While I could put that build operation in my own tooling, it does simplify my tooling by allowing me to offload that to Cypress' startup.

So, for my use case, the current functionality of `before:run` is a perfect fit. About the only thing I would like is some way to communicate to the Cypress GUI what is going on. There may already be a way, I've not dug in too much to it.

**Comment by cameron** [comment]
I also find it surprising and disappointing that these events aren't run when triggering a re-run in the interactive mode (especially a year later). Honestly, it feels quite broken. The obvious thing, to me, is to treat any re-run, whether it's a single spec or all, as a non-interactive run, which should answer all the questions @jennifer-shehane posed above. I dislike any solution that makes the interactive case different from the non — this the last place I want to spend mental energy on extra complexity in my development process.
