### ISSUE TITLE
Error: Unknown option: .mode. Check out ...

### ISSUE THREAD

**Issue by ivanvorona** [cypress-io/cypress#15133]
Hi folks, i am trying to run cypress on my vuejs project. any `*spec.js` open attempts give me this error message:
```
Error: Webpack Compilation Error
./cypress/integration/examples/sample_spec.js
Module build failed (from C:/Users/ivan_/AppData/Local/Cypress/Cache/6.5.0/Cypress/resources/app/packages/server/node_modules/babel-loader/lib/index.js):
Error: Unknown option: .mode. Check out https://babeljs.io/docs/en/babel-core/#options for more information about options.
```

### Desired behavior
No error.

### Test code to reproduce
https://dev.azure.com/olympianguru/OLYMPIAN_GURU/_git/OG_MARKETPLACE

### Versions
Never worked for this project. first time tried.
![Capture](https://user-images.githubusercontent.com/18105506/108263551-6dd75a00-7134-11eb-852a-7f05bd0dc1b5.PNG)

**Comment by mccataldo** [comment]
@ivanvorona I found a similar issue with a comment including a possible solution. 
https://github.com/cypress-io/cypress/issues/6755#issuecomment-779198018
Give it a try and post an update here.

**Comment by mccataldo** [comment]
@ivanvorona you could also try removing the `.babelrc` file or compilation configs in `package.json` just to see if there's a difference.

**Comment by ivanvorona** [comment]
Hi @mccataldo  - i've removed this file: babel.config.js from my project and it fixed the issue. any idea what dependency & why it broke cypress?
will research if that config will have other impact on my project.

Thanks,
Ivan

**Comment by mccataldo** [comment]
@ivanvorona Not sure, yet. What happens if you put a new babel config in the `cypress` directory?

**Comment by JessicaSachs** [comment]
@ivanvorona I think Cypress may have an older version of babel-loader than what's supported in your application's version. In our latest 3.x release (private alpha) we rewrote this so that we do not bundle any user dependencies (babel, webpack, etc) to avoid these kinds of versioning issues.

We'll be releasing 3.x for public use on around March 15th. If you don't want to upgrade, you can pass in a webpack configuration in your plugins file where you remove the babel-loader for Cypress only.

You should probably keep your babel file when building your app for production.

I hope this helps. I'll update this issue when we release 3.x. I'm going to close this issue unless you have anything else to add.
