### ISSUE TITLE
cy.intercept / force404

### ISSUE THREAD

**Issue by ncjones** [cypress-io/cypress#15209]
Cypress should allow disabling forwarding of requests which are unmatched with cy.intercept.

This will prevent unwanted latency and make it easier to spot missing stubs. This used to be supported with cy.server(). 

Related to:

https://github.com/cypress-io/cypress/issues/9358#issuecomment-750231567
https://github.com/cypress-io/cypress/issues/9302

**Comment by ncjones** [comment]
One way could be to have a whitelist of valid origins for intercept forwarding.

**Comment by ncjones** [comment]
The workaround we are using is to add a utility which is invoked in every test _after_ all other stubs have been declared to block requests on origins our app uses for XHRs:

```
function force404() {
  cy.intercept('https://api.mydomain/**', { statusCode: 404, body: 'Cypress forced 404', });
  cy.intercept('https://auth.mydomain/**', { statusCode: 404, body: 'Cypress forced 404', });
}
```

Can optionally add this as a custom command in "cypress/support/commands.js":

```
Cypress.Commands.add('force404', force404);
```

**Comment by flotwig** [comment]
Yep, that works. Once #14543 is released in 7.0.0, that code can be moved to a `beforeEach`, since handler ordering is reversed to make doing stuff like this easier. I'll add this issue to the issues closed by #13543.

**Comment by CodingItWrong** [comment]
Would the above approach also work with a wildcard for domain names? Our enterprise app connects to a number of different first-party and third-party domains. I would love a way to ensure that _all_ outgoing HTTP requests are stubbed.

The reason is that isolating our app from external systems is a big value in our testing approach. If we are ever accidentally sending real HTTP requests, they may succeed for now, but fail for flaky reasons in the future. So an option to stub _all_ outgoing HTTP requests, instead of us having to remember to add any new domain names that need to be stubbed, will be a big benefit.

**Comment by flotwig** [comment]
Yup, you could create a fallback for ALL requests... but things like images, CSS, and scripts would be intercepted and return 404s, so you'd probably want to do more filtering than simply `cy.intercept('*')`.

**Comment by CodingItWrong** [comment]
Looking over the docs again, I see that the relevant difference is that `cy.route` only stubbed XHRs, whereas `cy.intercept` stubs XHRs, fetch, page loads, and resource loads. I think the desired behavior for my use case would be to stub only XHRs and fetches. Is there a way to do that with `cy.intercept` APIs?

**Comment by flotwig** [comment]
Not currently, no, and there's not a feature request open for it.
