### ISSUE TITLE
Cross origin error / Whoops there is no test to run

### ISSUE THREAD

**Issue by joszo** [cypress-io/cypress#15224]
### Current behavior

I found out that my UI login tests started to fail. Scenario is pretty simple:
   
```js
        cy.intercept('POST', '/api/auth').as('auth');
        cy.visit('')
        cy.get('#input_0').type('test');
        cy.get('#input_1').type('test123');
        cy.get('.md-raised').click();
        cy.wait('@auth').then(intercept => {
            console.log(intercept);
        });
        cy.get('button').click()
```

**My cypress.json:**

```json
{
    "baseUrl": "http://localhost",
    "chromeWebSecurity": true,
    "experimentalSourceRewriting": false,
    "modifyObstructiveCode": true
}
```

**The error I get:**

```
Cypress detected a cross origin error happened on page load:

  > Blocked a frame with origin "http://localhost" from accessing a cross-origin frame.

Before the page load, you were bound to the origin policy:

  > http://localhost
  
```
  

- When I will change `"chromeWebSecurity": false` then I have `Whoops, there is no test to run.`. 

- When I change  `"modifyObstructiveCode": false`, nothings happen.

- When I change `"experimentalSourceRewriting": false` then application load, but I cannot perform any action on UI, the time that we need to perfom first comment is also longer around 10-15 seconds before even cy.viisti will starts.

As I know, our frontend devolpers changed routing in angular from                 

`url: '/api/auth/signIn',` => `url: './api/auth/signIn'`

I will try to reproduce on earlier commits if the problem also occurs.

**EDIT:** We verified with earlier commits and it still doesn't work - strange issue. 

### Versions

cypress: 6.2.0 also checked on 6.4.0 and 6.5.0 6.0.0...
chrome: 88
checked on electron, firefox, chrome

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
