### ISSUE TITLE
Cy.intercept -> broken images

### ISSUE THREAD

**Issue by SlavikDMI** [cypress-io/cypress#15245]
### Current behavior
I tried intercept requests for images. All responses have status code 200. When request pass through intercept, images have bigger size, when test dont have intercept.

There is cy.intercept - http://joxi.ru/5mdKWZGI8gb14r 
There isnt cy.intercept - http://joxi.ru/RmzjglviMD1Gxm 

### Test code to reproduce
```js
  before(() => {
    cy.intercept( 'POST',Cypress.config('baseUrl') + '/assets/**', (req) => {
      req.reply((res) => {
        expect(res.statusCode).to.be.within(200,399)
        res.send()
        })
      })
    })
```

### Versions
6.5.0 - now, latest

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Some app code to run this intercept against to see this? HTML/JS?

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
