### ISSUE TITLE
cy.exec always exits with code 1 and no output

### ISSUE THREAD

**Issue by hnandiwada** [cypress-io/cypress#15296]
### Current behavior
I am new to Cypress trying to test a VSCode extension.
When I run `cy.exec('ls')`, the test runner exits with code 1, and empty strings for `stderr` and `stdout`. I've tried giving it an absolute path (`'/bin/ls'`), and also tried giving it gibberish ('`asdf`'), and I get the same result each time.

[Screenshot](https://imgur.com/a/7XT8FCA)

I'm running Cypress with `sudo` because it was breaking at the `--no-sandbox` flag as referenced in [this issue](https://github.com/cypress-io/cypress/issues/4624): `DEBUG=cypress:* sudo node_modules/.bin/cypress open`

### Desired behavior
I want Cypress to either run the command or give me sensible output telling me why it's failing.

### Versions
Cypress package version: 6.6.0
Cypress binary version: 6.6.0
Electron version: 11.2.3
Bundled Node version: 12.18.3

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
