### ISSUE TITLE
Page doesn't load as expected

### ISSUE THREAD

**Issue by maxplyassunov** [cypress-io/cypress#1530]
### Bug
I wanna test ad unit's using cypress. But when i open this url in cypress - https://www.tripsavvy.com/when-should-you-get-your-luggage-wrapped-4146609?kw=TEST4534121759 - ad unit's load broken

### Current behavior:
![screen shot 2018-04-03 at 9 54 18 am](https://user-images.githubusercontent.com/35612115/38255193-2a9e8a4e-3729-11e8-985d-d6a4084106a5.png)

### Desired behavior:
![screen shot 2018-04-03 at 9 54 48 am](https://user-images.githubusercontent.com/35612115/38255204-3115f876-3729-11e8-877a-5ba3e65f8172.png)

### How to reproduce:

Just open this url using cypress cy.visit("https://www.tripsavvy.com/when-should-you-get-your-luggage-wrapped-4146609?kw=TEST4534121759");

#### Test code:

```js
'use strict';

describe('FIU', () => {

  it('FIU', () => {
  	cy.visit("https://www.tripsavvy.com/when-should-you-get-your-luggage-wrapped-4146609?kw=TEST4534121759");
  });
});

```

### Additional Info (images, stack traces, etc)

I was trying to set "chromeWebSecurity": false , but it didn't help

Thank you!

- Operating System:
Mac Os Hight Sierra 10.13.3
- Cypress Version:
2.1.0
- Browser Version:
Chrome 65.0.3325.181, see same issue on Electron 59, and Canary 67

**Comment by Bkucera** [comment]
@maxim94plyasunov Testing the specific content of a 3rd party service is usually an anti-pattern, since this is something beyond the control of your application's code. I would would recommend simply **asserting that the request to the ad server was made** and nothing more than that. That way you are still ensuring that your app is functioning properly regardless if the ad provider's servers are up or down.

**Comment by maxim94plyasunov** [comment]
@Bkucera The issue is - it's not 3rd party content, this ad unit's were developed by our team also, it's just located on other server, and we need test to make sure that all elements load correctly, and don't break the page, we have the test's for the whole app already, and now we want to write a test, which checks that specific ad units interact correctly with our the page

**Comment by bahmutov** [comment]
Yeah, I don't understand what the add is doing - some of the markup for the top banner add is there, I see something loading, flashing black rectangle, then it disappears.

**Comment by jennifer-shehane** [comment]
^ @Bkucera has dug into this issue and narrowed down some of what's happening. He's still investigating.

**Comment by Bkucera** [comment]
@maxim94plyasunov It appears your ad is using "frame busting" to get access to the root document's page from the iframe and set the height/width of itself. By default Cypress blocks this from happening so the app can't mess up Cypress's Test Runner, which runs your app inside an iframe itself. There is an option to disable this by setting `modifyObstructiveCode=false` in cypress.json, but that still might not fix your problem.
I tried to display your webpage from an iframe in Chrome, and it didn't work, giving me this error

`
Refused to display 'https://www.tripsavvy.com/when-should-you-get-your-luggage-wrapped-4146609?kw=TEST4534121759' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.specless.io *.specless.tech http://*.seo.aws.about.com https://*.seo.aws.about.com www.tripsavvy.com *.qa.aws.tripsavvy.com atlas.tripsavvy.com atlas.local.tripsavvy.com".
`

**Comment by anuragipankaj** [comment]
i'am facing the same issue , and ADS are not showing up while running it through cypress ,any fixes yet?  modifyObstructiveCode=false and 'chromeWebSecurity": false are not working .

**Comment by pxlprfct** [comment]
I'm running into this exact issue aswell, the first page we load in is a log in form, so I can't even get around it :(
```
Refused to display 'https://prepiam.toronto.ca.ibm.com/idaas/oidc/endpoint/default/authorize?response_type=code&client_id=MDc2Yzg1ZDktNmVlYS00&redirect_uri=https%3A%2F%2Flocalhost%3A6443%2Fauth%2Foidc%2Freturn&scope=openid%20openid' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://wwwstage.ibm.com/".
```

Thanks everyone looking at it, you're all heroes <3

**Comment by songbo0212** [comment]
@pxlprfct I have the same issue, could you please share your security features? Which security features did you turn off?  Thanks a lot

**Comment by pxlprfct** [comment]
@songbo0212  Sorry for the late response here. I am using an express server, which usually uses [helmet](https://github.com/helmetjs/helmet) to protect it, so I just added a E2E run mode that doesn't - and that cleared the issue up for me.

**Comment by thaiching** [comment]
Hi @pxlprfct ,
  I'm facing the same issue as well where the ads are not loading on the page when Cypress test is run and I need to perform some tests on the adverts.

  Can you share in details how you fix the problem please? Thank you.

**Comment by aswine** [comment]
CypressError: Timed out after waiting ‘10000ms' for your remote page to load.
Your page did not fire its 'load' event within ‘10000ms'.
You can try increasing the 'pageLoadTimeout' value in 'cypress.json' to wait longer.
Browsers will not fire the 'load' event until all stylesheets and scripts are done downloading.
When this 'load' event occurs, Cypress will continue running commands.

This issue occurs in headless mode, in headed mode the same test case works perfectly. In the execution video, I can see that the website is loaded visibly but I am not sure is there something that prohibits cypress to find and interact with the html elements

**Comment by abhiskkk-mp** [comment]
Is there any update on the above issue, this is still an open issue and is causing serious problems.
