### ISSUE TITLE
Cypress does not load the page properly

### ISSUE THREAD

**Issue by ingriddbritok3** [cypress-io/cypress#15339]
### Current behavior
When Cypress clicks a button <Add new Customer> it goes to a new URL (the address displayed on the runner is correct), but the page stays loading (not all the elements are displayed on the page and the spinner remains spinning). This is how the page looks when Cypress is running, you can see the buttons are loaded, but the rest of the page is not.

<img width="887" alt="notLoading" src="https://user-images.githubusercontent.com/58943407/110108628-b6d21400-7dac-11eb-9cae-c1e08482cda5.png">

### Desired behavior
I want Cypress to click the button <Add new Customer>, go to the new URL, and loads all the elements from the page. So, the rest of the test won't fail because the elements are not loaded.

I used cy.visit('url'), but the page remains loading infinitely.

### Versions
Cypress 6.4.0
Electron 87
Chrome 88
Win 10

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
