### ISSUE TITLE
cy.should can be chained off of cy, refers to previous subject instead of failing

### ISSUE THREAD

**Issue by lenkva** [cypress-io/cypress#15352]
### Current behavior
When chaining `should()` off of `cy`, it creates an assertion on the last subject yielded by previous commands. 

### Desired behavior
According to the [documentation](https://docs.cypress.io/api/commands/should.html#Usage):

`cy.should('eq', '42')   // Errors, cannot be chained off 'cy'`

When executing such code, an Error should occur along the lines of:

```
Oops, it looks like you are trying to call a child command before running a parent command.

You wrote code that looks like this:

cy.should('eq', '42')

A child command must be chained after a parent because it operates on a previous subject.

For example - if we were issuing the child command click...

cy
  .get('button') // parent command must come first
  .click()       // then child command comes second
```

### Test code to reproduce
```js
describe('Context', function () {
    it('should not run', function () {
        cy.visit('https://example.cypress.io/')
        cy.get('body')
        cy.should('contain.text', 'Kitchen Sink')
    });
})
```

The test should fail to run, citing invalid chaining, but instead it runs and successfully asserts that `<body>` contains 'Kitchen Sink'.
### Versions

Tested in 6.5.0, 6.6.0, not yet tested in earlier versions.

Tested on both Win7 and Win10, on local machines, with Electron 87.

**Comment by jennifer-shehane** [comment]
We don't error when you do not follow the chaining recommendations, but you should always follow the chaining recommendations from the docs to avoid unintended consequences. There is no use case ever for `cy.should()` because it is a child command.

When we previously spoke about enforcing chaining, it didn't get a lot of requests from users: https://github.com/cypress-io/cypress/issues/508

I'll update the docs to be more accurate.

**Comment by lenkva** [comment]
Thanks for the quick response. I agree that there is no use case, I just wanted to see what happened. Testing the tester, if you will ;-) 

I saw the other issue in my preliminary search, but figured this was the opposite issue - things working without chaining when they shouldn't. 

In any case, thanks for clearing up my misunderstanding.

**Comment by jennifer-shehane** [comment]
Actually, this does usually error for other commands I'm now seeing. I'm not sure why it doesn't error for `.should()` and `.and()`, maybe because they are assertions?

<img width="557" alt="Screen Shot 2021-03-06 at 11 02 46 AM" src="https://user-images.githubusercontent.com/1271364/110212904-9917b400-7e6b-11eb-93b8-3feb76a8c243.png">

**Comment by elliott-king** [comment]
Note that this will raise the error correctly - if the previous command did not return a subject. For example

```javascript

          cy.get('i[data-original-title="Visitors"]').first().click();
          cy.wait(2000);
          cy.should("not.contain", `${stringToAvoid}`);
```

Will correctly throw the error described: 

```
CypressError: Oops, it looks like you are trying to call a child command before running a parent command.

You wrote code that looks like this:

``cy.should("not.contain")``

A child command must be chained after a parent because it operates on a previous subject.

For example - if we were issuing the child command `click`...
```

**Comment by BlueWinds** [comment]
This will be resolved by the changes in https://github.com/cypress-io/cypress/pull/25296 - .should() will error if it's used as a parent command, enforcing the recommendations of the documentation.

Going to close this; feel free to follow along or comment in that pull request or https://github.com/cypress-io/cypress/issues/25134, the issue it's associated with.
