### ISSUE TITLE
Cucumber feature compilation Error

### ISSUE THREAD

**Issue by manoj12419** [cypress-io/cypress#15371]
I am using cypress version : 6.5.0
Cypress-cucumber-processor version: 4.0.1

It was working fine but all of sudden it started showing error during compilation
```
**Error:** Webpack compilation Error

./cypress/integration/foldername/test.feature 1:13

Module parse failed: Unexpected tocken 1:13

You may need an appropriate loader to handle this file type, currently no loaders are configured to process the file . see https://webpack.js.org/concept#loader
```

Please let me know if any fix is available for this issue.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
