### ISSUE TITLE
Follow the `@cypress/vue` document to run program that is not working

### ISSUE THREAD

**Issue by uni-zheng** [cypress-io/cypress#15372]
### Current behavior

![image](https://user-images.githubusercontent.com/9986421/110461064-f335a500-8109-11eb-93f5-57fa721241ff.png)

### Test code to reproduce

```
$ vue create vue-cypress
# select default option

# when finished
$ cd vue-cypress
$ vue add cypress-experimental

# when finished
$ yarn run test:components
```

### Versions
`cypress: 6.6.0`
`@cypress/vue: 2.0.1`

**Comment by sig-rhys** [comment]
I also am having this issue. 

I changed the component path to :
`import Greetings from  '../../src/components/Greetings.vue'`

but now that has caused a new error:
`Error: Webpack Compilation Error
./src/components/Greetings.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|   <section>
|     <h1 data-testid="title">👋 Hello {{ name }}!</h1>
 @ ./tests/components/Greetings.spec.js 7:40-85`

**Comment by jennifer-shehane** [comment]
Where did you follow these instructions? Just want to clarify what you were following.

**Comment by LolliDepp** [comment]
Steps are at the top of the docs

[](https://github.com/cypress-io/cypress/tree/develop/npm/vue#vue-cli-installation)

I've been trying to update from `^1.1.0-alpha.2` to `2.1.1` but with no success.

After the update:
- `.tsx` components cannot be tested because when importing `.less` files I get a webpack error, apparently there's no `less-loader`.
- `.vue` components cannot be tested because nothing renders and I see the message in browser console "could not mount, template or render function could not be found"

I also tried the manual installation, but it also didn't work.
It's also worth noting that you have 2 different sections that explain how to do the setup, and they're saying two completely different things.

[](https://github.com/cypress-io/cypress/blob/develop/npm/vue/docs/manual-install.md)
[](https://github.com/cypress-io/cypress/tree/develop/npm/vue#bundling)


![image](https://user-images.githubusercontent.com/13365724/111482774-22609d80-872c-11eb-8a5b-1df58438e6d2.png)

![image](https://user-images.githubusercontent.com/13365724/111482992-4d4af180-872c-11eb-950b-f4d66c4a1c3e.png)

**Comment by LolliDepp** [comment]
Update:
I managed to get it working with version `2.1.1`, but I think by doing this I'm no longer using `webpack-dev-server` as I'm supposed to (I'm never using `@cypress/vue/dist/plugins/webpack`)
```
const path = require('path');
const mockEnv = require('mocked-env');
const webpack = require('@cypress/webpack-preprocessor');

const webpackConfigPath = path.resolve(
  process.cwd(),
  'node_modules',
  '@vue',
  'cli-service',
  'webpack.config.js',
);

const babelEnvName = 'development';
const restoreEnv = mockEnv({
  BABEL_ENV: babelEnvName,
  NODE_ENV: 'test',
});

// eslint-disable-next-line import/no-dynamic-require
const webpackOptions = require(webpackConfigPath);

const options = {
  webpackOptions,
  watchOptions: {},
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
module.exports = (on: any) => {
  on('file:preprocessor', webpack(options))
};
```

**Comment by uni-zheng** [comment]
@jennifer-shehane https://github.com/jessicasachs/vue-cli-plugin-cypress-experimental

**Comment by jennifer-shehane** [comment]
Please update to our latest version of Cypress and the @cypress/vue plugin. We've made a lot of changes to the product and the docs in our 7.0 release. Please open a new issue with the reproducible example using the new versions.
