### ISSUE TITLE
Can't install cypress/react

### ISSUE THREAD

**Issue by nilsmartel** [cypress-io/cypress#15448]
Installing `@cypress/react` even in a fresh npm project fails

### Current behavior
`npm i --save-dev @cypress/react` fails with this error message:
``` 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: cypress-tests@1.0.0
npm ERR! Found: webpack@5.25.0
npm ERR! node_modules/webpack
npm ERR!   peer webpack@">=2" from babel-loader@8.2.2
npm ERR!   node_modules/babel-loader
npm ERR!     peerOptional babel-loader@"^=8.x" from @cypress/react@4.16.4
npm ERR!     node_modules/@cypress/react
npm ERR!       dev @cypress/react@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional webpack@"^=3.x" from @cypress/react@4.16.4
npm ERR! node_modules/@cypress/react
npm ERR!   dev @cypress/react@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/nilsmartel/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nilsmartel/.npm/_logs/2021-03-12T09_19_37_930Z-debug.log
```

### Download method
 

- [x] npm 7.5.3

### Operating System

- [x] Linux
- [x] Mac
- [ ] Windows

**Comment by glomotion** [comment]
im getting a similar error: 
```
timpaul@Tims-Work-MBP imx-marketplace % npm i -D @cypress/react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: imx-marketplace@1.0.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!   peer react@"17.0.1" from react-dom@17.0.1
npm ERR!   node_modules/react-dom
npm ERR!     react-dom@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^=16.x" from @cypress/react@4.16.4
npm ERR! node_modules/@cypress/react
npm ERR!   dev @cypress/react@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/timpaul/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/timpaul/.npm/_logs/2021-03-19T00_10_22_166Z-debug.log
timpaul@Tims-Work-MBP imx-marketplace % 

```

**Comment by aronrodrigues** [comment]
It is a problem in the @cypress/webpack-preprocessor@5.6.0 that is not compatible with WebPack webpack@5.26.3

**Comment by glomotion** [comment]
Fwiw - it turns out that you can —force it - and everything works fine. :)

**Comment by eltoro** [comment]
I'm getting the web pack dependency error and I'm running Cypress 7.0.0. Trying to install it with vite-dev-server 1.2.0. I even tried with the webpack-dev-server. My app is React 17.0.1 with Vite 2.0.5.

**Comment by eltoro** [comment]
For anyone else with the same issue, I was using node 15. I downgraded to 14 LTS and the install worked.

**Comment by jennifer-shehane** [comment]
Any updates on what this issue is currently? Since @cypress/react has updated since this was opened.

**Comment by nilsmartel** [comment]
With the newest version of @cypress/react this error does not occur anymore

**Comment by glomotion** [comment]
@nilsmartel, so i'm not sure we can consider this issue fixed. 

As i understand it, the issue happens when using npm 7 to install `@cypress/react`, and this happens because npm 7 no longer has --legacy-peer-deps turned on by default. Please try installing `@cypress/react` using npm 7.x and you will see these errors.

`@cypress/react`'s current (`develop` branch) `package.json` specifies that `webpack 3.x` is a peer dependency. I think this is the root of the problem (at least for `@cypress/react`). 
https://github.com/cypress-io/cypress/blob/a12928496610743b8ac77a7fe17a8a2794f7e77a/npm/react/package.json#L108

I believe you are already telling ppl as part of ur docs, that component testing requires webpack 4 or 5 (https://docs.cypress.io/guides/component-testing/introduction#Prerequisites). Could I suggest the above peer-dep be changed to: 
```
"webpack": ">=3", // or even "webpack": ">=4"
```

It should be noted that various other packages (eg `@cyprss/webpack-preprocessor` & `@cypress/webpack-dev-server`) also specify things like: 
```
'webpack': '*'
```

I wonder, could you guys agree on a webpack support range (sounds like you already have, and it's 4.x - 5.x) - and fix these definitions across all the cypress npm component package.json's? 🙏
