### ISSUE TITLE
Cypress closes the Google browser print bullet box

### ISSUE THREAD

**Issue by guoyupeng01** [cypress-io/cypress#15446]
I am using cypress, trying to close the print popup of Google browser, I am using cy.realPress ('Escape'), but it doesn't work, is there any other way?

`
it('Close the print window', () =>{
        cy.realPress('Escape')
})
`
![image](https://user-images.githubusercontent.com/32129782/110904496-08961380-8344-11eb-902c-7307e041c498.png)

**Comment by guoyupeng01** [comment]
> I am using cypress, trying to close the print popup of Google browser, I am using cy.realPress ('Escape'), but it doesn't work, is there any other way?
> 
> it('Close the print window', () =>{
> cy.realPress('Escape')
> 
> ```
> })
> ```

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example of the test that is initiating the print dialog? Basically the print dialog should never open in Cypress, so I'd like to see how this is popping up to begin with. But no, there would not be a way currently to test a print dialog.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
