### ISSUE TITLE
Application field gets disabled after typing one character in cypress but test doesnot field

### ISSUE THREAD

**Issue by nupur2610** [cypress-io/cypress#15484]
If I provide a long value in provider name field. It gets disabled after typing one character(application code). But Cypress does not fail the test.

**Comment by nupur2610** [comment]
If I provide a long value in provider name field. It gets disabled after typing one character(application code). But Cypress does not fail the test.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
