### ISSUE TITLE
Cypress keeps waiting for XHR request infinity and doesn't kill the process when the test is failed.

### ISSUE THREAD

**Issue by viengiang** [cypress-io/cypress#15518]
### Current behavior

Hello Cypress Dev team, thanks for the awesome e2e testing framework.
I'm having an issue: Our server is slow for a few days (API response extremely slow), and when I run the test, Cypress will wait for the XHR request infinity and doesn't kill the process although the test is failed.

Here are the photos, sorry for the inconvenient cause I can't upload the photo directly:
https://ibb.co/XpQr193
https://ibb.co/nckh7ZS

### Desired behavior

Are Cypress will wait until every XHRs request are finished to do the next step? Or do we have any way to tell Cypress to stop when the test runs so long?

Thank you in advance.
### Versions
Cypress version: 6.7.1

**Comment by jennifer-shehane** [comment]
That shouldn't be the case - it trying to wait for all XHRs to finish before moving on if the test has failed. 

Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
