### ISSUE TITLE
Property 'validity' does not exist on type 'HTMLElement'

### ISSUE THREAD

**Issue by TheLogan** [cypress-io/cypress#15515]
### Current behavior
```js
cy.get('[type="email"]').then(($input) => {
  expect($input[0].validity.typeMismatch).to.eq(true);
})
```
$input has the type JQuery<HTMLElement>, validity then has a red underline and the error message: "Property 'validity' does not exist on type 'HTMLElement'. ts(2339)"

![image](https://user-images.githubusercontent.com/759433/111308558-1ce75280-865b-11eb-8693-1b9100fc5785.png)

### Desired behavior
I can see in the console that the shape of the validity object is something like this:

```
{
    valueMissing: boolean,
    typeMismatch: boolean,
    patternMismatch: boolean,
    tooLong: boolean,
    tooShort: boolean,
    rangeUnderflow: boolean
    rangeOverflow: boolean,
    stepMismatch: boolean,
    badInput: boolean,
    customError: boolean,
    valid: boolean
}
```
And the desired behaviour would be that the property was recognized.

### Test code to reproduce
```
cy.get('[type="email"]').then(($input) => {
  expect($input[0].validity.typeMismatch).to.eq(true);
})
```

### Versions
"cypress": "^6.6.0"

The bug is in no way critical as I can just add it manually to the object, but at least now you're aware of it. :)

**Comment by jennifer-shehane** [comment]
Yes, feel free to open a PR. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md).

**Comment by sainthkh** [comment]
First of all, thank you for spending time to write this issue. 

Unfortunately, it's not a bug. When TypeScript team designed the HTML type system, they put properties that every element has into `HTMLElement` interface. And they added element-specific properties to each Element interface. 

Because of that, `validity` property exists in `HTMLInputElement` but not in `HTMLDivElement`. 

In Cypress, we cannot statically guess the type of the returning element from `cy.get()` function. Because of that, it's `HTMLElement` by default. And it's a good default and it cannot be changed. 

But it doesn't mean the problem cannot be solved. Check the code below: 

```ts
it('t', () => {
  cy.get<HTMLInputElement>('[type="email"]').then(($input) => {
    expect($input[0].validity.typeMismatch).to.eq(true)
  })
})
```

By putting `<HTMLInputElement>` in the middle, you can return HTMLInputElement type from `cy.get()`. Then, it'll solve all the problems.
