### ISSUE TITLE
Cypress loads page twice on first visit, even if baseUrl is set

### ISSUE THREAD

**Issue by maximedupre** [cypress-io/cypress#15523]
### Current behavior
When calling `npx cypress open` and running the test for the first time (those two conditions are needed to reproduce), the page is loaded twice on the first `cy.visit`. I have added a `console.log` in my index.html and can clearly see that this one call of `cy.visit` makes the html load twice.

[This issue](https://github.com/cypress-io/cypress/issues/2542) suggests that this behaviour can be avoided by setting a `baseUrl` in the cypress.json, but that is not the case - there might be a regression bug. This is my cypress.json:

```
{
    "baseUrl": "http://localhost:3031",
    "screenshotOnRunFailure": true,
    "video": true
}
```

I don't have Chrome installed on my machine currently, so it's using Electron to run tests.

### Desired behavior
index.html should not be loaded twice on first call to `cy.visit`

### Versions

Using v6.7.1

**Comment by jennifer-shehane** [comment]
Do you have an example of the test code?

**Comment by maximedupre** [comment]
Thanks for the response.

Just the most minimal test code causes the problem:

```
describe('Navigation', () => {
    it('should only fetch the user once when visiting multiple pages that need the user', () => {
        cy.visit('/').then(() => console.log('cy.visit has resolved'));
    });
});
```

As you can see by the following screenshot, index.html is loaded twice after one call to `cy.visit`.

![Screen Shot 2021-03-17 at 9 23 43 AM](https://user-images.githubusercontent.com/5158181/111474568-95551e80-8702-11eb-8a80-20ffe3f557cd.png)

**Comment by yann-combarnous** [comment]
Same behavior for us

**Comment by todd-m-kemp** [comment]
This might be the same thing (or perhaps just related) that I reported back in January? https://github.com/cypress-io/cypress/issues/14538

**Comment by maximedupre** [comment]
I don't think so, since my use case doesn't involve changing domain during the test. Your behaviour might actually be the expected behaviour (don't quote me on this :D).

**Comment by maximedupre** [comment]
@jennifer-shehane :D

**Comment by svalluri-cais** [comment]
If anyone finds a workaround please kindly share. In my case I create users in my before hook and because of the reload, it is creating 2 sets of users and I am able to delete only one set of users in the tear down which is making a mess.

Any help or pointer will be greatly appreciated.

My baseUrl is also set in the config.

**Comment by svalluri-cais** [comment]
Adding baseUrl will resolve the problem. If your base url is inside env: { baseUrl : "blah blah"} this won't work. It has to be like baseUrl: "blah blah" inside cypress config file

**Comment by Troyc-boop** [comment]
I have the same problem. I added the baseUrl and it was ok but now I am running the tests against the app that is running on my local machine. I changed the baseUrl to go to the new site (which is now local) but now it loads the first visit() twice. The only thing that is changed is the baseUrl because now I build the app that I am testing locally.  Could that be the problem?

**Comment by Troyc-boop** [comment]
> I have the same problem. I added the baseUrl and it was ok but now I am running the tests against the app that is running on my local machine. I changed the baseUrl to go to the new site (which is now local) but now it loads the first visit() twice. The only thing that is changed is the baseUrl because now I build the app that I am testing locally. Could that be the problem?

I found the solution. The problem was that when I changed the URL I was still using HTTPS as it was before but there was no self-signed certificate or cypress couldn't find it (the app is running in docker) and that is the reason why it would start 2 times at the beginning of each spec file as when you use only cy.visit() withouth baseUrl. The reason for this is that cypress creates its one self-signed certificate and restarts again with the certificate. The solution was to use HTTP.
