### ISSUE TITLE
Frame-breaking CSP directive: "frame-ancestors 'none'" prevents loading page, despite disabling Chrome Web Security

### ISSUE THREAD

**Issue by davidcelis** [cypress-io/cypress#1555]
- Operating System: macOS 10.13.4
- Cypress Version: 2.1.0
- Browser Version: Chrome 65.0.3325.181

### Is this a Feature or Bug?

Bug

### Current behavior:

I'm using Cypress to run end-to-end tests on an application that allows users to configure a connection to a GitHub OAuth application. The interactions with GitHub are complex and involve needing to receive webhooks, so I want to test the actual connection as opposed to stubbing. I have managed to do this successfully with Bitbucket, but the authorization page on GitHub has a CSP rule that doesn't seem to get caught despite setting `"chromeWebSecurity": false` in my Cypress configuration. The interaction is as follows:

1. User creates an OAuth Application on GitHub
2. User takes the Client ID and Client Secret from that OAuth Application and enters them in my application to create a connection just for their use.
3. My application generates a callback URL for GitHub, which the user then enters in their GitHub OAuth application
4. User returns to my application and clicks a button to connect to the OAuth application. This hits a URL in my own application that sets up the OAuth dance, and then _redirects_ to GitHub's authorization page
5. When that _redirection_ occurs, Cypress suddenly replaces the contents of the URL bar with `data:,` and displays a blank page. Opening the web inspector shows this error in the console:

`Refused to display 'https://github.com/login/oauth/authorize?client_id=SCRUBBED&redirect_uri=SCRUBBED' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

### Desired behavior:

The above steps do not result in a blank page and the console error. Instead, the OAuth Authorization page is displayed and allows my test to click the "Authorize user" button and finish the OAuth dance

### How to reproduce:

I can reproduce this in a barebones Rails app and have pushed the code to GitHub. You'll need:

* Ruby 2.5 along with the `bundler` gem
* A GitHub username/password, probably one that is not of import. Make sure 2FA is not enabled.

Then, in one Terminal tab, set up and boot the application:

```
git clone https://github.com/davidcelis/cypress_framebusting.git
cd cypress_framebusting
bundle
bin/rails db:create db:migrate
bin/rails server
```

Then, in another tab, run the Cypress tests:

```
export CYPRESS_GITHUB_USERNAME=username
export CYPRESS_GITHUB_PASSWORD=password
yarn run cypress open
```

_NOTE: The tests are written in a way that you'll need to run the fifth test file between tries, so that it will delete the OAuth Application that gets created on GitHub as well as emptying the local application's database_

#### Test code:

https://github.com/davidcelis/cypress_framebusting/tree/master/cypress/integration/

### Additional Info (images, stack traces, etc)

Possibly related to #1497

**Comment by jennifer-shehane** [comment]
This error is displaying due to GitHub's Content Security Policy of not allowing it's view to be displayed within an iframe (which is where your application is rendered within Cypress). 

We do not have access to [the cross-origin frame used for GitHub's login](https://docs.cypress.io/guides/guides/web-security.html#Cross-Origin-Iframes). 

This is [one of the many reasons](https://docs.cypress.io/guides/references/best-practices.html#Visiting-external-sites) that we suggest you do not test a 3rd party application's behavior that is not under your control.

**Comment by brian-mann** [comment]
@jennifer-shehane is correct and I'll try to provide a bit more context...

This question has been asked on here many times, and the last time I answered it was here: https://github.com/cypress-io/cypress/issues/1380#issuecomment-368663427

The short of it is that using a bot to login will simply not work after you try it a few times (at least with Google). I haven't personally seen or tried doing it with Github, but my guess is that the same thing happens.

In order to test this you **must** use oAuth API's programmatically with `cy.request()`. Doing that would enable you to test the entire flow without involving the UI. Because its programmatic you would still be able to test things like webhooks from Github, etc.

https://docs.cypress.io/guides/references/best-practices.html#Visiting-external-sites

**Comment by davidcelis** [comment]
@jennifer-shehane @brian-mann Thanks for the quick response. I was under the impression that setting `"chromeWebSecurity": false` would get around CSP issues such as this one. My tests can otherwise visit GitHub and load its views into Cypress' iframe. All of GitHub's pages have CSP rules defined, but it's only this authorization page that seems to break…

**Comment by brian-mann** [comment]
It gets around the web security limitation that all browsers have (which is that cross origin iframes are not accessible) - but with CSP headers this will **still** prevent things from communicating.

By default Cypress automatically strips CSP headers but **only for the origin under test** which is defined by what you use with `cy.visit`.

Because you're being redirected to Github, the origin under test does not match, and therefore CSP headers are not stripped and thus it breaks.

We could/can strip all headers for all requests even if they aren't for origin, we just choose not to. We could (especially if `chromeWebSecurity` is disabled).

But really... even if we did all that, I wouldn't suggest this because Github itself will likely block you after it detects you are a bot. There is no real advantage testing **their UI** when you can already test everything programmatically.

**Comment by davidcelis** [comment]
@brian-mann Thanks a bunch for that explanation!

> By default Cypress automatically strips CSP headers but only for the origin under test which is defined by what you use with cy.visit.

That's the bit I was missing. This all makes sense, so if the Cypress team has no plans to strip all CSP headers when Chrome Web Security is disabled, I'm ok with this issue being closed.

**Comment by brian-mann** [comment]
Yeah so after looking at your code... you are doing pretty much exactly what it is that we describe as anti-pattern. I promise... none of this is necessary and you are making life so much more difficult for yourself.

https://github.com/davidcelis/cypress_framebusting/blob/master/cypress/integration/5_delete_github_oauth_app_spec.js#L6

You don't need to **ever** visit a 3rd party application and use their UI. Ever. You are literally testing **Github** itself and every single time they make an update, it will break. They will detect you are a bot, and prevent your scripts from working.

All you have to do is programmatically interact with their 3rd party API's with `cy.request` and you will instantly be done with all of the interaction with Github. They make it easy to create and authorize 3rd party applications without touching their UI.

**Comment by brian-mann** [comment]
Also - really suggest watching the Best Practices video we gave at a talk a couple months ago. Will highlight some things for you: https://docs.cypress.io/guides/references/best-practices.html#Organizing-Tests-Logging-In-Controlling-State

**Comment by brian-mann** [comment]
Overall, I get what you're trying to do. If you'd like, make some updates and post back here and we can give you feedback on your implementation.

It's been on our radar for a long time now to do a comprehensive guide / recipe / example showing how to properly handle oAuth logins for 3rd party providers.
