### ISSUE TITLE
Cypress : Firefox and Chrome generate different snapshot for same file  ?

### ISSUE THREAD

**Issue by Shivani1796** [cypress-io/cypress#15637]
Hey!!
I am been using cypress for a while and I saw when I am trying to generate a snapshot with chrome & firefox it is supposed to generate the same snapshot. _But in this case, the snapshot is not exactly the same (firefox)._ 

**Purpose:** Performing visual testing to verify both chrome & firefox should generate the same snapshot.

Is there any drawback of firefox while taking a snapshot?

**Comment by jennifer-shehane** [comment]
Not that we're aware of. 

Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
