### ISSUE TITLE
Timed out retrying after 4000ms: cy.type() failed because this element:

### ISSUE THREAD

**Issue by kamranshan777** [cypress-io/cypress#15653]
Would you please tell me how can I fix this problem? I have been stuck on this issue for more than 2 days.
![Screenshot 2021-03-25 at 4 28 31 PM](https://user-images.githubusercontent.com/12068812/112466312-8b2cc300-8d87-11eb-9b77-60e763b11ae7.png)

**Comment by jennifer-shehane** [comment]
In order for Cypress to type into an input, it must first click the input. Cypress cannot click on the input you are targeting because it has the style of `pointer-event: none`. You can see this `!important` style directly in the HTML of the error message. 

Pass `force: true` to type into the input or inspect the HTML to find the correct element you intended to type into.

**Comment by kamranshan777** [comment]
Thanks @jennifer-shehane
