### ISSUE TITLE
CustomElements delegating focus

### ISSUE THREAD

**Issue by brion-fuller** [cypress-io/cypress#15664]
Currently, customElements and redirect focus to a child element make the child element unelectable in Cypress.  This kind of thing is needed for handling form support and making sure focus is set on validation before submission of a form.  

### Current behavior
![image](https://user-images.githubusercontent.com/9418958/112544710-988c8200-8d74-11eb-8814-ad7262e1cc7f.png)

### Desired behavior
The underlying input should be focused and should be able to interact with the element.

### Test code to reproduce

Here is a repo of some sample code and cypress tests I would expect to work https://github.com/brion-fuller/cypress-focus-custom-elements

### Versions

Cypress: 6.8.0

Everything should be in the repo for reproducing.

**Comment by brion-fuller** [comment]
Understanding correctly this fireFocus event is there to help with time travel?  Is the blur event mainly to 'reset' the page for next command?

**Comment by shinijimmy3** [comment]
It looks like we have a similar problem, due cypress injected code is not possible to click inside input in cypress window ( not only by code, it is not possible with mouse too)
![chrome_JD3gORb9pM](https://user-images.githubusercontent.com/10617939/211531776-50ca4ac8-f566-4297-866c-2b48f07dc167.gif)

in code we are using force:true as a workaround, but it is really annoying to work with in cypress debug menu:
due to injected code messing with focus we:
- need use force:true   - not rly good pattern to follow
- can't really work in cypress debug window because we can't type to react inputs
- console log is full of errors 
![chrome_FYfs7RMGH8](https://user-images.githubusercontent.com/10617939/211532586-b4a21dff-5e2d-49d4-8b1a-52c67bc5172f.png)
- after some time and interacting with It in cypress open window test stuck and restart of cypress is needed
