### ISSUE TITLE
Cypress needs to be closed in order for changes to cypress.json to be used

### ISSUE THREAD

**Issue by symon-skelly** [cypress-io/cypress#15662]
### Current behavior
Open cypress application no longer uses any changes made to cypress.json while it is open, closing and re-opening cypress is required for cypress application to use the changes made.

### Desired behavior
Cypress application should use whatever current cypress env / cypress variables were last saved to cypress.json.

### Test code to reproduce

1. Open cypress.json
2. add the following to the file and save it
```
"viewportWidth": 1920,
"viewportHeight": 1080,
```
3. yarn run cypress open
4. change the viewportWidth to something other than 1920 and save the file again
5. Open Settings Tab and expand configuration / Run a spec file

Issue:

1. The new viewportWidth is not used, closing the cypress application and re-opening will use the new value

This happening with any configuration settings set in cypress.json, not just the viewportWidth, I'm just using this as an example.

### Versions
Cypress 6.6.0 Windows 10, Chrome 89
This was not occurring in Cypress 6.1.0.

**Comment by jennifer-shehane** [comment]
I am not able to recreate this behavior in 6.6.0. Changing the `cypress.json` file's values updates instantly in the Settings tab and also takes effect in the test when it is run - reflecting the new viewport width and height.

I'm not sure what could be causing this issue for you specifically.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
