### ISSUE TITLE
Feature: Access browser extensions API/storage/messaging

### ISSUE THREAD

**Issue by ejoubaud** [cypress-io/cypress#1567]
I use Cypress to test a browser extension (hat tip for #1078 btw) that stores its settings in the [extension local storage](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/local).

So I need to clear the extension local storage between each test, and possibly setup fixtures in there, but there doesn't seem to be any built-in way with Cypress.

Because it has a content script, I can hack a workaround with `window.postMessage(clearDbMessage, "*")`, catch it in the content script that relays it to the background tab (with `runtime.sendMessage`), that can then clear the DB (or setup fixtures). But it's less than ideal because 1. It's hard to make it unexploitable by the pages users will visit and 2. It's a lot of boilerplate testing-specific code to add to my codebase.

I realise browser extension testing must be a somewhat low-priority edge but it would be great to be able to access the local storage and background tab of an extension from Cypress.

**Comment by brian-mann** [comment]
Actually I think you have exactly what you already need because of the way Cypress is built.

Rather than put those `window.postMessage` inside of your app code - just use it directly from Cypress spec code! Because it all runs in the same loop there's really no difference between the two, other then the `window` frame they are bound to.

I'm not sure if your extension is listening only to the app `postMessage` or whether it's listening to `top` which is Cypress.

Try this..

```js
// cypress test code
cy
.foo()
.bar() // do your normal command stuff
.baz()
.then(() => {
  // now send messages to your extension
  window.postMessage('clearDbMessage, '*')
})
```

If for whatever reason your extension is only listening to the application under test, you could simply tap into it's `window` and do the same thing...

```js
// cypress test code
cy
.foo()
.bar() // do your normal command stuff
.window().invoke('postMessage', 'clearDbMessage', '*')
```

I'm confident you can get it working and control it directly from Cypress, no problem.

**Comment by brian-mann** [comment]
Because extension API's are partitioned away there are no API's that the browser exposes to access them **other** than existing in an extension. While it's technically possible for us to bridge that gap, it would be a large amount of work without a lot of upside IMO. I believe controlling it from the `contentWindow` gets you everything you need.

If after getting it to work I'd recommend abstracting this into something resuable for the general community with custom commands and an npm module for both sides (the spec code + the extension code) that you could require in.

**Comment by ejoubaud** [comment]
In case anyone has the same use-case (testing an extension with contentscript and local storage), here's the full workaround:

```javascript
// > cypress/integration/my_spec.js
beforeEach(() => window.postMessage({resetDb: true}, "*"))

// > contentscript.js
function isIntegrationTestWindow() {
  return window.location.href.match("/integration/");
}

function isIntegrationTestIFrame() {
  const f = window.frameElement;
  return f && f.className.match(/spec-iframe/);
}

function setupDbResetHook() {
  window.addEventListener("message", (event) => {
    if (event.source == window && event.data && event.data.resetDb) {
      browser.runtime.sendMessage(event.data).then(() => console.log("DB reset"));
    }
  });
}

// My content script is triggered on all URLs and all frames in the extension's manifest
// (for Cypress you need `all_frames` as Cypress holds the actual page under test in an iframe)
// Cypress opens 3 frames:
// 1. the top-level Cypress windows, 2. the Cypress iframe and 3. the app (under test) iframe
// I want nothing to happen in 1, the listener to reset the db to load in 2 and my contentscript to load in 3
if (isIntegrationTestWindow()) { // 1 or 2
  if (isIntegrationTestIFrame()) setupDbResetHook(); // 2 only
} else {
  ready(startExtension); // 3
};

// > background.js
browser.runtime.onMessage.addListener(function(message, sender, sendResponse) {
  if (message.resetDb) browser.storage.local.remove(mySettings).then(sendResponse);
  return true
})
```

That's a bunch of boilerplate and there's not much to prevent a site to send my users to a page with a path in an `<iframe class="spec-iframe" src=".../integration/..." />` that makes a `window.postMessage({resetDb: true}, "*")`.

**Comment by ejoubaud** [comment]
> would be a large amount of work without a lot of upside IMO
> If after getting it to work I'd recommend abstracting this into something resuable for the general community with custom commands and an npm module

Agreed, sounds like the best solution for now, tbh this was more about giving feedback on extension-testing issues and sharing my workaround than asking for an immediate built-in solution.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
