### ISSUE TITLE
Intercept data is empty for 304 status codes

### ISSUE THREAD

**Issue by nicholaschiang** [cypress-io/cypress#15680]
### Current behavior

When an intercepted route has a 304 status code (i.e. has been retrieved from the browser cache), the response data is empty:

```typescript
    cy.wait('@list-users').then((interception) => {
      console.log('Intercepted:', interception); 
      console.log('Intercepted request:', interception.request); 
      console.log('Intercepted response:', interception.response); 
      
      // This body object is an empty string for 304 status codes.
      console.log('Intercepted response data:', interception.response?.body); 
    });
```

The current workaround (proposed in #14277) is to delete the `if-none-match` header:

```typescript
  cy.intercept('GET', '/api/users*', (req) => {
    delete req.headers['if-none-match'];
  }).as('list-users');
```

On an even higher level, I don't believe that the `interception.response` should have a 304 status code at all. In the Cypress logs, there are only ever 200 status codes:

![cypress-intercept-bug](https://user-images.githubusercontent.com/20798889/112706505-dca98080-8e61-11eb-9a58-98829978d5a3.png)

You'll notice ☝️ that Cypress seems to log two of each request. One as an `(xhr)` request to `/api/users` with a 200 status code and the other as a `(req)` to `http://localhost:3000/api/users` (this second `(req)` is the one that is intercepted by Cypress).

I'm a little confused by this as well... Why are there two of each request? Which of those two requests is Cypress actually returning data for in `cy.wait()`?

### Desired behavior

The response body for requests with 304 status codes should be the same as the original 200 status code response body. The HTTP response exposed by `cy.wait()` should have the same data as the HTTP response that is used by our application.

Again, on a higher level, Cypress should only log a single request (with a 200 status code), instead of logging both an `(xhr)` and a `(req)` event for the same HTTP request.

### Test code to reproduce

The original repository is [`tutorbookapp/tutorbook`](https://github.com/tutorbookapp/tutorbook) (completely open-source).

The test in question is in [`cypress/tests/org/users/index.spec.ts`](https://github.com/tutorbookapp/tutorbook/blob/develop/cypress/tests/org/users/index.spec.ts) but the same issue is happening everywhere I use `cy.intercept()` in conjunction with `cy.wait()`.

### Versions

Cypress: 6.8.0
Browser: Electron
OS: Pop_OS! 20.04 (Ubuntu 20.04)

**Comment by nicholaschiang** [comment]
I found this: https://glebbahmutov.com/blog/cypress-intercept-problems/#cached-response

But I've still got questions about why Cypress isn't logging any requests with 304 status codes and why Cypress seems to be logging two of each request.

**Comment by flotwig** [comment]
The confusion about the logs is because currently, there are two types of network logs:

* logs for XMLHttpRequest object creation (xhr) - these come from the cy.route and cy.server implementation
* logs for matched cy.intercept request (req)

So an XHR that hits a cy.intercept will log both. This is suboptimal UX, there is an issue open to track consolidating the two logs into one: https://github.com/cypress-io/cypress/issues/14843

---

Because of the way XMLHttpRequests work, the `.status` property of a successful 200 response (cached and returned as the response to a 304 or not) will always be `200`. You can't get a `304` via the XHR API.

`cy.intercept` works on actual raw HTTP requests, not XMLHttpRequests, so it can get either a `200` response with a body or a `304` response with no body from the destination server.

There is no body with `304` responses, so that's why the response object is missing a body in your example.

We are working on improving the UI around this whole situation, it's still not as clear as it could be. Specific suggestions are welcome.

---

I think we can close this issue since this is known behavior. If there is a new bug with cy.intercept, feel free to open an issue.
