### ISSUE TITLE
Cypress 7.0 (Component Testing) 404s runtime files while using create-react-app with a homepage set

### ISSUE THREAD

**Issue by sscaff1** [cypress-io/cypress#15811]
### Current behavior

If you create a new CRA app and do the cypress setup and add a homepage to package.json, you will notice when you try to run your cypress tests your runtime files will 404. Here a repo that does all of the setup for you:

https://github.com/sscaff1/cypress-bug

To reproduce:
- clone
- npm i
- npm run cy:watch
- Open the Chrome dev tools and click on the App.spec.jsx. You will notice 2 files 404 because they are looking for those files in the directory specified by the package.json homepage.

Remove the homepage from the package.json and notice that the test now runs.

### Desired behavior

That the App.spec.jsx can run even with the homepage specified.

### Versions

This is a new bug with Cypress 7.0. This was not a bug in Cypress 6.8.

**Comment by lmiller1990** [comment]
Probably the same as https://github.com/cypress-io/cypress/issues/15824.

While we figure out the best way to approach this, you can work around by removing publicPath when initializing the devServer plugin:

```js
```

**Comment by lmiller1990** [comment]
This is fixed in https://github.com/cypress-io/cypress/pull/15839/files which has since been released. Please upgrade to the latest version of `@cypress/webpack-dev-server` and everything will work. I gave it a test in your repo and it worked. 

Let me know if this isn't the case or you find any other bugs. Thanks!
