### ISSUE TITLE
'include.text' doesn't match text when used with monaco editor

### ISSUE THREAD

**Issue by maclockard** [cypress-io/cypress#15863]
### Current behavior
Trying to assert that a monaco editor includes a substring fails even when the substring is present.

<img width="1509" alt="Screen Shot 2021-04-07 at 2 01 41 PM" src="https://user-images.githubusercontent.com/7308388/113933735-cc6e9b00-97a9-11eb-8cdb-a339058402b1.png">

Bizarrely enough, testing for a sub string without spaces works.

```js
    cy.get('.monaco-editor').should('include.text', 'Game') // passes
    cy.get('.monaco-editor').should('include.text', 'Game of Life') // fails
```

### Desired behavior
'include.text' should work for all valid substrings, even if there are spaces present.

### Test code to reproduce
https://github.com/maclockard/cypress-test-tiny

### Versions

cypress: 6.4.0
chrome: 89

**Comment by bahmutov** [comment]
Non-breaking space characters cause the problem here. I have recorded a short video https://youtu.be/6CxZuolWlYM explaining the problem and two solutions

- use https://on.cypress.io/contains command that handles non-breaking space character
```js
cy.contains('.monaco-editor', 'Game of Life')
```

- use Unicode character "\u00a0" where the non-breaking spaces are
```js
cy.get('.monaco-editor').should('include.text', 'Game\u00a0of\u00a0Life')
```

**Comment by maclockard** [comment]
Ah, gotcha, makes sense!
