### ISSUE TITLE
Open devtools inside the playground iframe with a simple button

### ISSUE THREAD

**Issue by edimitchel** [cypress-io/cypress#15873]
### What would you like?

_When I want to inspect the DOM, I have to use shortcut or click right + Inspect element._
Have some latency before the devtools is opened.

And because the playground is in an iframe, it could be very nice to integrate the dev tools directly inside the iframe, because we didn't want to inspect Cypress app, only the playground.
You can see with @antfu [Vite VS Code project](https://github.com/antfu/vscode-vite) to get some inspiration for devtool integration (which would be sadly only available for Chromium based browser)

<u>Summary:</u>

- Integrate the devtools inside the playground iframe
- Add a button to open dev tools (or inspect DOM element which open the devtools directly with the element inspected visible).

### Why is this needed?
For better inspection tools and a fully tools set during TDD tests writing (especially for Component Testing !)

**Comment by JessicaSachs** [comment]
I think this issue is multiple feature requests if I understand you correctly

1. Nicer in-cypress debug experience for the components, specifically the element explorer which is hard to use because the DOM for cypress pushes the components so far “down”

You’re suggesting that this could be solved by possibly targeting the iframe directly instead of cypress (technically this is possible, I’m not sure how easy it is)

2. Portability of cypress where the runner and driver can mount in user browsers (eg user’s chrome, without the parent cypress app.)

This is technically possible (and was a design goal of mine in November) but because we use the chrome developer protocol, if we don’t launch the process ourselves we cannot support many features.

There is a cheap middle ground if you just want to mount your components but not interact with them... and I’m happy to accept PRs for that, or look at any OSS tools you’d build on top.

—-
Can you tell me more about what you want out of a stand-alone browser? Would it be useful if it didn’t do the automation? What parts matter the most to you?

**Comment by edimitchel** [comment]
1. We could perhaps mount the devtools in the playground iframe and display it on demand. I just don't know if the devtools will be working as the native one.

2. What I need is not in a browser, but only inside the Cypress playground. But yes, outside cypress would be great. For example, add the possibility to pop-out the playground ?

**Comment by JessicaSachs** [comment]
Looking back through this issue. I'm going to put this screenshot here for future reference. Going to keep this open as a future enhancement.

![image](https://user-images.githubusercontent.com/2801156/129844144-7f6b6c00-3218-4379-94f3-94518ff7a8eb.png)

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
