### ISSUE TITLE
Component testing support things like vue-test-utils?

### ISSUE THREAD

**Issue by f3ltron** [cypress-io/cypress#15897]
### What would you like?

First that's really cool that you are supporting and working on component testing! The doc doesn't show it so. Can you add extra elements like store etc when mounting a component? How far you plan to go with that? Could be awesome to use on tool to rule them all :)

**Comment by lmiller1990** [comment]
Hello @f3ltron,

Component testing is with Cypress is certainly awesome, agreed. We will continue to update the docs and make component testing a more prominent feature as it matures!

The `@cypress/vue` `mount` function is actually using Vue Test Utils under the hood, so you can pass things like `localVue`, `store`, or whatever else you'd like.

There is some example tests [here for Vue 2 and Vuex](https://github.com/cypress-io/cypress/tree/develop/npm/vue/cypress/component/counter-vuex) and [here for Vue 3](https://github.com/cypress-io/cypress/tree/next/npm%2Fvue/npm/vue/cypress/component/counter-vuex). 

I also filmed a video showing you how to migrate a Vue 3 app from Vue Test Utils to Cypress, [see it here](https://www.youtube.com/watch?v=qZKEbfHY_t0&t=6s).

If you have any specific test you'd like help with, you can post it here and I will help you 💪  since we fully support the entire Vue Test Utils API, I will close this since there is technically no action to be taken.

Thanks for the support and trying out Cypress for component testing 💯

**Comment by f3ltron** [comment]
Thanks for the fast answer. And awesome job will give it a try defintely
