### ISSUE TITLE
Cypress.Screenshot.defaults option "capture" can't be processed by runner.

### ISSUE THREAD

**Issue by Seitar18** [cypress-io/cypress#15910]
### Current behavior
Cypress runner can't handle "capture" option value and always make screenshot of whole runner

### Desired behavior
Cypress should make correct screenshots, as set in "capture" option

### Test code to reproduce
I've tried below commands at top `support/index.js`
```js
Cypress.Screenshot.defaults({capture: "fullPage"});
Cypress.Screenshot.defaults({capture: "viewport"});
```
And the result was the same, btw `Cypress.Screenshot.defaults({scale: true});` or `Cypress.Screenshot.defaults({screenshotOnRunFailure: false});` affects the screenshot result.

### Versions
Tested both on Cypress 6.8.0 and Cypress 7.0.1 
OS: MacOS and Debian, both latest.
Browser: chrome 89, latest image from cypress docker base

**Comment by jennifer-shehane** [comment]
@Seitar18 Are these for screenshots taken via `cy.screenshot()` or for the screenshots taken when there is a test failure? Because the capture option doesn't currently affect the screenshots automatically taken during a test failure. See https://github.com/cypress-io/cypress/issues/5920. Please feel free to close this issue if that is the case.
