### ISSUE TITLE
[7.1.0] Vue Component testing - not working when trying to use with PWA plugin

### ISSUE THREAD

**Issue by xanxuz** [cypress-io/cypress#15968]
### Current behavior
The cypress test runner crash when using Vue with the [PWA plugin](https://cli.vuejs.org/core-plugins/pwa.html#vue-cli-plugin-pwa)

![image](https://user-images.githubusercontent.com/11968584/114630039-afddd180-9c87-11eb-9a2c-1dc0326c88ef.png)
![image](https://user-images.githubusercontent.com/11968584/114630089-ce43cd00-9c87-11eb-9f33-0f7bbb582bce.png)
![image](https://user-images.githubusercontent.com/11968584/114630117-da2f8f00-9c87-11eb-8a8d-580ed818b5b2.png)

### Desired behavior
To work with the PWA plugin added to a Vue project

### Test code to reproduce
Here is the project made with vue-cli that includes the pwa plugin already install and cypress ct that was being used to test and make the screenshots
https://github.com/xanxuz/vue-cypress-ct

### Versions
Cypress v7.1.0
Yarn v1.22.5
Node v15.14.0
Windows 10

**Comment by lmiller1990** [comment]
Hi!

The problem is the `htmlWebpackPluginBeforeHtmlProcessing` is deprecated in `html-webpack-plugin@4.x`. The lates version is 5.x - we support 4.x and 5.x as it stands. Vue CLI is still using `html-webpack-plugin@3.x`, and depends on those lifecycle hooks.

We are exploring a solution to let us support any version of `html-webpack-plugin`. Until then, the easiest way to get your project to work would just be to conditionally remove the plugin when used with Cypress. [Here's an example of how to do that](https://github.com/cypress-io/cypress/pull/15970). Example `cypress/plugins/index.js` file. The trick is you remove the plugin during testing, since you probably won't use a service working during development anyway.

```js
/// <reference types="cypress" />
const { startDevServer } = require('@cypress/webpack-dev-server')
const webpackConfig = require('@vue/cli-service/webpack.config')

/**
 * @type Cypress.PluginConfig
 */
module.exports = (on, config) => {
  on('dev-server:start', (options) => {

    // omit PWA Plugin during testing

    const modifiedWebpackConfig = {
      ...webpackConfig,
      plugins: (webpackConfig.plugins || []).filter((x) => {
        return x.constructor.name !== 'HtmlPwaPlugin'
      }),
    }

    return startDevServer({
      options,
      webpackConfig: modifiedWebpackConfig,
    })
  })

  return config
}
```

**Comment by lmiller1990** [comment]
Another alternative is to use the latest version of Vue cli (`@next`) it comes with `html-webpack-plugin@5` and `webpack@5` everything works as expected.

Upgrading your dependencies is always a good idea - if this is an option, definitely do this - you'll get a nice speed boost from all the webpack optimizations in v5.

**Comment by xanxuz** [comment]
> Another alternative is to use the latest version of Vue cli (`@next`) it comes with `html-webpack-plugin@5` and `webpack@5` everything works as expected. I am not sure it will be easy to support v3, v4 and v5 simultaneously, when v4 and v5 have been out and stable for some time.
> 
> Upgrading your dependencies is always a good idea - if this is an option, definitely do this - you'll get a nice speed boost from all the webpack optimizations in v5.

Thanks for the suggestion @lmiller1990, I didn't even know that vue-cli had a new version in progress, but for the moment I'll stick with my current version because the new one is still in alpha
