### ISSUE TITLE
Buttons are hidden when we run Cypress scripts against our application

### ISSUE THREAD

**Issue by kettlescott** [cypress-io/cypress#15974]
### Current behavior
    Buttons are hidden when we run Cypress scripts against our application

### Desired behavior
  Buttons should not be 
![bug](https://user-images.githubusercontent.com/6243985/114670093-00b3ff80-9d46-11eb-86dd-8b144690974f.png)
hidden when we run Cypress scripts against our application

### Versions
Cypress package version: 6.3.0
Cypress binary version: 6.3.0
Electron version: 11.2.0
Bundled Node version:
12.18.3

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
