### ISSUE TITLE
clearCookies() doesn't work for WordPress

### ISSUE THREAD

**Issue by mishautkin** [cypress-io/cypress#16007]
**Cypress doesn't clear Wordpress cookies between tests.**

**clearCookies()** function doesn't help as well.

This workaround helped:
```js
Cypress.Commands.add( "clearWPCookies", () => {
  cy.getCookies()
    .then(cookies => {
      cookies.forEach((cookie) => {
          if (cookie.name.substr(0, 10) === 'wordpress_') {
            cy.clearCookie(cookie.name);
          }
      });
    });
});
```

**Comment by bahmutov** [comment]
Please fill all information from our [new issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md). Without enough information we cannot investigate and solve the problem

```
<!-- Is this a question? Questions WILL BE CLOSED. Ask in our chat https://on.cypress.io/chat  -->

### Current behavior:

<!-- A description including screenshots, stack traces, DEBUG logs, etc -->

### Desired behavior:

<!-- A clear description of what you want to happen -->

### Test code to reproduce

<!-- If we cannot fully run the tests as provided the issue WILL BE CLOSED -->
<!-- Issues without a reproducible example WILL BE CLOSED -->

<!-- You can fork https://github.com/cypress-io/cypress-test-tiny repo, set up a failing test, then link to your fork -->

### Versions

<!-- Cypress, operating system, browser -->
```

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
