### ISSUE TITLE
[6.8.0] flaky cy.visit on docker - AssertionError: Timed out retrying after 90000ms: Expected to find element: `.navbar`, but never found it. at Context.eva

### ISSUE THREAD

**Issue by tkaczus** [cypress-io/cypress#16001]
### Current behavior
Hi, running tests on docker 
FROM cypress/browsers:node14.16.0-chrome89-ff86
- cypress@6.8.0 
- gets unstable on first command cy.visit , loads fully or not at all
![image](https://user-images.githubusercontent.com/11943052/114829427-5979ab80-9dcb-11eb-85bd-f40ad3387031.png)
 - locally it never happens

### Versions
cypress@6.8.0 
browsers:node14.16.0-chrome89-ff86

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
