### ISSUE TITLE
The video compression in headless mode has increased 3x from version 3.8.3 to 7.1.0

### ISSUE THREAD

**Issue by preetibellad** [cypress-io/cypress#16046]
### Current behavior
We have just migrated cypress version 3.8.3 to current 7.1.0. We have found that the video compression in headless mode has increased 3 times!!
The video compression time taken with cypress version 3.8.3
![image](https://user-images.githubusercontent.com/72126464/115111286-41f21c80-9f9d-11eb-9f3f-27e563c6c62c.png)

The video compression time taken with cypress version 7.1.0 for the same test without any changes in the test
![image](https://user-images.githubusercontent.com/72126464/115111330-841b5e00-9f9d-11eb-87cc-7412570db077.png)

This is happening for all the tests consistently which is not expected. Least the time taken should be same if not an improvement.

### Desired behavior
The time taken for video compression should be same if not an improvement.

### Test code to reproduce
N/A

### Versions
Comparison between cypress version 3.8.3 and current 7.1.0

**Comment by jennifer-shehane** [comment]
This is because the default headless browser window size has been increased to 1920x1080 pixels to capture High-definition videos and screenshots in version 7.0. 

There are some ways you can mitigate the increased video size if necessary:

- You can decrease the compression of the video: https://docs.cypress.io/guides/guides/screenshots-and-videos#Video-encoding
- You can delete the video if a certain condition is met (like all the tests pass). This will skip compression. https://docs.cypress.io/api/plugins/after-spec-api#Delete-the-recorded-video-if-the-spec-passed
- You can configure the browser window size to a smaller size for smaller videos: https://docs.cypress.io/api/plugins/browser-launch-api#Set-screen-size-when-running-headless
