### ISSUE TITLE
Vite/React fast spec switching throws an invariant error

### ISSUE THREAD

**Issue by elevatebart** [cypress-io/cypress#16070]
### Current behavior
When I open specs quickly successively without waiting for them to render, the runner hangs forever.
Furthermore, there is an error in the console saying 

```
Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

https://user-images.githubusercontent.com/5592465/115275327-42a6c200-a107-11eb-803e-359b2ee7e9e6.mov

### Desired behavior
No need to wait for specs to render to open a new one

### Test code to reproduce
https://github.com/elevatebart/cy-ds-test

yarn
yarn cy:open
click fast on changing specs until it fails
open console

### Versions

```
    "@cypress/react": "^5.3.3",
    "@cypress/vite-dev-server": "^1.2.2",
    "cypress": "^7.1.0",
    "cypress-real-events": "^1.3.0",
```

### Initial Investigation

The console error points at unmountComponentAtNode

https://github.com/cypress-io/cypress/blob/59d1d84d2cca18f8392af0e026ee3a3db607517b/npm/react/src/mount.ts#L149-L157

**Comment by agg23** [comment]
@elevatebart and I did a fairly in-depth investigation of this issue. There were several things we discovered:

- Unmount of a given test component is performed multiple times; once via the `test:before:run` event and once via `beforeEach`. I expect that we should only have the Cypress event variant (and we should avoid `beforeEach` entirely for any work)
- Unmount was not bound to the `react-dom` instance used for the `mount` command. This would result in calling `unmountComponentAtNode` against a different React instance than the one that owns a component, which would not properly unmount that component.
- **We're doing cleanup before we start the new test/spec.** Rather than cleaning up when we're switching to a new spec/test (while in the context of the old spec), we're waiting until we've loaded the new spec, which could carry a new `react-dom` instance and different settings. Essentially, we're looking for a `willUnloadSpec` and a `willUnloadTest` event, which does not appear to exist in Cypress currently.

I propose that we add these `willUnloadSpec` and `willUnloadTest` events to allow Cypress and its plugins to properly clean up before switching to a new test or spec context.

**Comment by lmiller1990** [comment]
Those hooks sound pretty useful @agg23, I wonder if there is already a similar event. I suspect @brian-mann has some ideas around this - is there a pre-existing event/pattern to to cleanup *after* a given test and/or spec?

**Comment by brian-mann** [comment]
You should **never** clean up after a test, only ever before the test. You always want the DOM to be usable and viewable and available **after** the test completes.

Do not use `beforeEach` as @agg23 suggested. Use the internal Cypress events `test:before:run`.

**Comment by brian-mann** [comment]
When you switch between specs, we should be blowing away the entire iframe + the spec code, which will halt JS execution. That'll forcibly dispose of anything running in there.
