### ISSUE TITLE
Cypress 1.4.1 or 2.1.0 crashes on Windows 10

### ISSUE THREAD

**Issue by trobbins1981** [cypress-io/cypress#1607]
### Current behavior: 

I launch cypress and I see my lists of tests.
I click on a test (it can be any test).  
A chrome window briefly opens then it closes again

### Desired behavior:

I would like for Cypress to work as designed, and start running my tests. 

### Steps to reproduce:

This issue appears to be intermittent.  It never happened while I was on Cypress 1.4.1.  Then, after upgrading to 2.1.0, it didn't happen at first, but then started to a week or so later.  I then downgraded to 1.4.1 and it continued to happen.  The next day, it started working again, but now today (a week later), it's crashing again.

### Versions  

Cypres 1.4.1 or 2.1.0
WIndows 10
Chrome 65

**Comment by trobbins1981** [comment]
I think I found a temporary solution for fixing it.  Last time this this happened, it started working after I had put my computer to sleep then brang it right back.  I figured it was a coincidence.  Well, just now, I put my computer to sleep and brought it back, and it's working again.

**Comment by Saibamen** [comment]
Please retest with latest Cypress. Also install lates windows updates and npm

**Comment by jennifer-shehane** [comment]
Please try unsetting the `NODE_OPTIONS` environment variable if you have this set - as this causes Cypress to crash. This is due to an Electron bug prior to version 2.0.3, where having `NODE_OPTIONS` set causes either a failure or arguments to be ignored. https://github.com/electron/electron/issues/12695#issuecomment-385826834

### To see all environment variables currently set

#### MacOS / Linux
```sh
printenv
```

#### Windows
```sh
SET
```

### To unset `NODE_OPTIONS` environment variable

#### MacOS / Linux
```sh
unset NODE_OPTIONS # this is not the same as export NODE_OPTIONS=
```

#### Windows
```sh
set NODE_OPTIONS=
```

We have open issues for this being fixed that you can follow here: 

- `NODE_OPTIONS` should not exit `0`: https://github.com/cypress-io/cypress/issues/1676 
- Electron update: https://github.com/cypress-io/cypress/issues/3568
- Version 4.0 Release: https://github.com/cypress-io/cypress/issues/2840
