### ISSUE TITLE
cy.go('back') navigates to a blank page

### ISSUE THREAD

**Issue by alineborak** [cypress-io/cypress#16084]
### Current behavior
<When I add the command cy.go('back'), the navigator goes back in the cypress chrome application itself, not the site that I intended to perfom the test>

### Desired behavior
<After user clicks to go to another screen, and then the cy.go('back') command is called in the tests, it should go back to the screen that it was previously>

### Test code to reproduce
```js
describe('User navigates back and forward on some pages', () => {
    it('User searches for a listing, selects advanced filter and clicks to go back to homepage', () => {
        cy.visit("/ford/fiesta?bmin=2019&srt=df-a", { timeout: 5000 });
        cy.get('[data-testid="advanced-link"]').click();
        cy.get("button[data-testid='button']").eq(2).click();
        cy.go('back');
        cy.location("pathname", { timeout: 5000 }).should("equal", "/ford/fiesta?bmin=2019&srt=df-a");
    });
});
```

### Versions
cypress": "^6.9.1"

**Comment by bahmutov** [comment]
Can you post a video or screenshots of what is happening? Does it do the visit then go to the new page, then go to the blank page?

**Comment by alineborak** [comment]
> Can you post a video or screenshots of what is happening? Does it do the visit then go to the new page, then go to the blank page?

Here's the video:
https://user-images.githubusercontent.com/36476341/115413455-7b24c980-a1f5-11eb-891d-ba23b5c6d4c9.mov

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
