### ISSUE TITLE
Desc name and it name appearing twice on cypress dashboard

### ISSUE THREAD

**Issue by neo-mahe** [cypress-io/cypress#16106]
When I run the suite without Page Object Model the desc name and it name doesn't appear twice on cypress dashboard. But when using Page Object Model these appear twice. Attached are the screenshots for both with and without POM for the same test scripts

### Versions
Cypress Version: 7.1.0, 7.0.0, 6.8.0, 6.5.0
<img width="960" alt="WithoutPOM" src="https://user-images.githubusercontent.com/26810188/115500703-7876b280-a28f-11eb-9a36-4726d1a2a796.png">
<img width="960" alt="WithPOM" src="https://user-images.githubusercontent.com/26810188/115500715-7b71a300-a28f-11eb-917d-8a95d89acdce.png">

**Comment by jennifer-shehane** [comment]
@neo-mahe Hey, could you please provide a code example of the Cypress tests with and without using the POM? That will help us understand your issue better. Thanks.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
