### ISSUE TITLE
LayerCI Integration

### ISSUE THREAD

**Issue by ColinChartier** [cypress-io/cypress#16101]
### What would you like?
Automatic detection of LayerCI environment variables

### Why is this needed?
Would help our cypress users! Discussed with @bahmutov 

Here is the environment reference: https://layerci.com/docs/layerfile-reference/build-env
Recommended key (to facilitate retrying): `$LAYERCI_JOB_ID retry #$RETRY_INDEX` (100 retry #1)

Thanks!

**Comment by jennifer-shehane** [comment]
This is our file we use to collect env vars from CI providers: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/ci_provider.js#L88:L88

And there's a file for testing: https://github.com/cypress-io/cypress/blob/develop/packages/server/test/unit/ci_provider_spec.js#L1:L1

Mostly we have a specific key to tell which CI is it, then collect as many useful env vars as possible (you can see other CI examples). Some stuff is available, some isn't. 

We'd be welcome to a PR for collecting these.

**Comment by bahmutov** [comment]
I have created a repo https://github.com/bahmutov/cypress-example-layerci to see what is happening

Some variables are missing from the Dashboard as expected

<img width="939" alt="Screen Shot 2021-04-27 at 10 18 46 AM" src="https://user-images.githubusercontent.com/2212006/116259549-e580c100-a743-11eb-98bb-ca3a4a89d6f2.png">

Printing the relevant environment variables using `npx @bahmutov/print-env GIT LAYERCI RETRY`

The first run:
```
GIT_COMMIT=6121106abc63bc1dd54ae25df752b100e566fd02
GIT_COMMIT_TITLE=use scope
GIT_TAG=6121106
LAYERCI=true
LAYERCI_BRANCH=main
LAYERCI_JOB_ID=12
LAYERCI_ORG_NAME=bahmutov
LAYERCI_PULL_REQUEST=
LAYERCI_REPO_NAME=cypress-example-layerci
LAYERCI_REPO_OWNER=bahmutov
LAYERCI_RUNNER_ID=main-layerfile
RETRY_INDEX=1
```

Retry

```
GIT_COMMIT=6121106abc63bc1dd54ae25df752b100e566fd02
GIT_COMMIT_TITLE=use scope
GIT_TAG=6121106
LAYERCI=true
LAYERCI_BRANCH=main
LAYERCI_JOB_ID=12
LAYERCI_ORG_NAME=bahmutov
LAYERCI_PULL_REQUEST=
LAYERCI_REPO_NAME=cypress-example-layerci
LAYERCI_REPO_OWNER=bahmutov
LAYERCI_RUNNER_ID=main-layerfile-3
RETRY_INDEX=3
```

By the way, this is how LayerCI shows the retries

<img width="868" alt="Screen Shot 2021-04-27 at 10 37 17 AM" src="https://user-images.githubusercontent.com/2212006/116260331-95562e80-a744-11eb-962f-6292f9a6f831.png">

A new branch has the following env variables

```
GIT_COMMIT=a67ceeda2c2e8e32fb233faebad47bfd712400e5
GIT_COMMIT_TITLE=add a comment
GIT_TAG=a67ceed
LAYERCI=true
LAYERCI_BRANCH=pr-example
LAYERCI_JOB_ID=13
LAYERCI_ORG_NAME=bahmutov
LAYERCI_PULL_REQUEST=
LAYERCI_REPO_NAME=cypress-example-layerci
LAYERCI_REPO_OWNER=bahmutov
LAYERCI_RUNNER_ID=main-layerfile-2
RETRY_INDEX=2
```

When opening a PR need to push a commit AFTER opening the PR (otherwise the branch build still applies) still no PR variable?

```
GIT_COMMIT=533bb4c6945b599081e948434160e71fa17b27a1
GIT_COMMIT_TITLE=print user
GIT_TAG=533bb4c
LAYERCI=true
LAYERCI_BRANCH=pr-example
LAYERCI_JOB_ID=14
LAYERCI_ORG_NAME=bahmutov
LAYERCI_PULL_REQUEST=
LAYERCI_REPO_NAME=cypress-example-layerci
LAYERCI_REPO_OWNER=bahmutov
LAYERCI_RUNNER_ID=main-layerfile
RETRY_INDEX=1
USER=root
USERNAME=root
```

added the SPLIT variable printing https://layerci.com/docs/tuning-performance/the-layerfile-cache#split
without `SPLIT N` command the variable is undefined

```
GIT_COMMIT=db1aabedfaac9b651854888f98f3e45d8816fd46
GIT_COMMIT_TITLE=print the SPLIT environment variable
GIT_TAG=db1aabe
LAYERCI=true
LAYERCI_BRANCH=pr-example
LAYERCI_JOB_ID=15
LAYERCI_ORG_NAME=bahmutov
LAYERCI_PULL_REQUEST=
LAYERCI_REPO_NAME=cypress-example-layerci
LAYERCI_REPO_OWNER=bahmutov
LAYERCI_RUNNER_ID=main-layerfile
RETRY_INDEX=1
USER=root
USERNAME=root
No environment variables found that start with SPLIT
```

**Comment by bahmutov** [comment]
Ran tests in parallel, pretty good experience!

```
RUN BACKGROUND npm start

# Create a unique link to share the app in this runner.
# Every time someone clicks the link, we'll wake up this staging server.
EXPOSE WEBSITE http://localhost:8888

SECRET ENV CYPRESS_RECORD_KEY

# execute the tests against the same machine (?) on N machines
SPLIT 2
RUN npx cypress run --record --parallel --ci-build-id $LAYERCI_JOB_ID-$RETRY_INDEX
```

<img width="1135" alt="Screen Shot 2021-04-27 at 10 52 27 AM" src="https://user-images.githubusercontent.com/2212006/116262702-c20b4580-a746-11eb-91bc-0fd665df85ab.png">

did the retry too, but interestingly, the "retry" only re-runs using a single machine. For example here 3 machines were used at first, then retry kicked off - using just one machine

<img width="837" alt="Screen Shot 2021-04-27 at 11 01 45 AM" src="https://user-images.githubusercontent.com/2212006/116264101-03502500-a748-11eb-86c0-2c3e8c8434b6.png">
