### ISSUE TITLE
Record CI performance to prevent regressions

### ISSUE THREAD

**Issue by agg23** [cypress-io/cypress#16110]
We have experienced several significant performance regressions as of late (#15779, #15853, and more) and were none the wiser until users reported it. We should be monitoring various performance metrics in CI so we can act on anomalies.

## First steps

I suggest that we start by identifying particular limited scenarios (in terms of Cypress tests and env setup) and relevant metrics to capture from each; CPU time, raw time, heap size, etc. These tests should be run on machines of varying sizes to record the performance impact across different setups.

Results from the performance metric runs should post a comment on the PR, the same way we do for Dashboard. These results won't indicate a clear pass/fail, but will show percentage change from the mean and a measure of variance.

**Comment by unlikelyzero** [comment]
@agg23 I would be interested to learn about your performance testing setup to compare notes. Maybe it could be something you could roll into a guide for others to use or even as feature of the cypress product, itself!

From what I've read, if the `--enable-precise-memory-info` flag is sent to chrome, you should be able access the JS Heap metrics with a few simple
```console.log(JSON.stringify(window.performance.memory, ['totalJSHeapSize', 'usedJSHeapSize', 'jsHeapSizeLimit']))```
commands.

Poking around at some of the available metrics, it looks like you may be able to expose most of this information with your use of https://github.com/cypress-io/cypress/blob/7a3ace5b47ec54de1d1a7f0a20a722004e6312e2/packages/server/package.json#L40

Instead of setting up the performance measurements on different devices, it may be simpler to use docker's [inbuilt resource constraints on cpu and memory](https://docs.docker.com/config/containers/resource_constraints/#configure-the-default-cfs-scheduler) . I don't know how this would look when running on circleci runners.

I'm currently researching ways to expose CPU Metrics from the CDP API. The closest I've come is https://www.sitespeed.io/documentation/sitespeed.io/cpu/ which uses https://github.com/aslushnikov/tracium under the hood

**Comment by agg23** [comment]
@unlikelyzero Yes, there's lots of information we can pull out of the Chrome debugger. Given that there may even be performance issues with that API, and in the interest of time, the performance bisection for #15853 was done entirely with `time`. While this is very rough, it should also be very consistent from an external perspective (as long as you can mostly control for context switching).

We were using Docker's `cpus` flag to control for cores, but I also wanted to test in a more real-world environment.

Sitespeed looks interesting. Thanks for the heads up.
