### ISSUE TITLE
redirect loop between urls

### ISSUE THREAD

**Issue by morphicsk** [cypress-io/cypress#16156]
### Current behavior
 run into a problem in cypress with some kind of redirect loop? I’m seeing it jump back and forth between test url and the oktapreview url after logging in

1) cy.visit to the test url  and also I have added "chromeWebSecurity": false in cypress.json

2) my tests were working fine in chrome 89 

3) chrome updated to 90 and I am seeing the  problem in cypress with some kind of redirect loop in chrome 90

cypress version is 6.8.0

workaround 

scripts work fine in electron browser ,firefox and edge

Any help on this ?

### Versions
cypress version is 6.8.0  
browser is chrome 90
mac os mojave

**Comment by jennifer-shehane** [comment]
Could you try updating to the newest version of Cypress? Cypress should at least exit from the redirect loop in these instances in 7.0+. 

Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
