### ISSUE TITLE
Function is called again with stale params

### ISSUE THREAD

**Issue by shauvik** [cypress-io/cypress#162]
We have a test with a util function in support.

```
function saveSegment(name, edit) { // edit=boolean
...
}
```
I noticed that there is an element on the page with classname, which is same as the function name. i.e., `.saveSegment`.

**ISSUE:**
From the test, we call this function multiple times.
```
saveSegment("foo")
saveSegment("bar", true)
```
However, the second invocation calls the functions with edit=false.

**TEMP FIX:**
Changing the name of the function seems to fix this issue but it is a bug in cypress that needs fixing.

**Comment by brian-mann** [comment]
This is a little known fact but unique elements with an `id` are actually accessible as globals on `window`.

http://www.2ality.com/2012/08/ids-are-global.html

Cypress doesn't affect this behavior. What you should do is namespace your functions so they are not globals.

```javscript
window.utils = {
  saveSegment: function(name, edit){  
   
  }
}

// call it
utils.saveSegment()
```

Another alternative is to add a build process around the cypress spec files so that you can use common js `require` or es6 `import` and not deal with globals at all.
