### ISSUE TITLE
Unable to visit the site when url is redirected to /#!/login instead of /login

### ISSUE THREAD

**Issue by Nastaran200** [cypress-io/cypress#16205]
### Current behavior
I am unable to use the cy.visit(URL) in my test. This app gets redirected to '/#!/login' to get to login page.  But attempt to run the test and it almost immediately right after trying the cy.visist() shows the 'Whoops, there is no test to run'

### Desired behavior
I should be able to access the login page similar to when it gets redirected to '/login'.

### Versions
I have tried it with different version including the current one I have 7.1.0

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
