### ISSUE TITLE
Test runner only shows the last screen

### ISSUE THREAD

**Issue by gregevari** [cypress-io/cypress#1623]
### Current behavior: 
Despite having many steps in the test, the only screen that is shown during a test run is the final screen in the test.

Mousing over the time travel segments shows only blank screens.

Inspecting the screen shows that the chrome has the elements, they are just not visible.

### Desired behavior:
I would think that we should be able to see all screens rendered as I do when I navigate through them when using the app

### Steps to reproduce:
Happens with all tests I've written with v2.1.0 (and previous versions)

```js

```

### Versions  
2.1.0, OSX High Sierra, Chrome 66.0.3359.117

**Comment by jennifer-shehane** [comment]
Hi @gregevari, this is definitely not the intended behavior. You are supposed to be able to 'time travel' to previous views. 

- Could you possibly share any screenshots? If not, could you share more what you mean by 'blank screens'?
- Does this happen in every website/tests you run? Like, does this happen when you run our example_spec files?

Our best chance at addressing the issue is to be able to reproduce it ourselves, and we haven't seen this issue before. So, as close as you can get us there, that'd be great.

**Comment by gregevari** [comment]
Thanks for the quick response! It doesn't seem to happen with the example_spec files, they're all ok. Here's a screencap of my test, its the same for all tests: 

![blank-running](https://user-images.githubusercontent.com/38128131/39102805-8ed58908-46d9-11e8-8176-1d56c21a6a54.gif)

The test we're running in the above goes to our home page, then to a followup then to a register page which it finally displays.  We're using react, its a project that uses create-react-app out of the box.

It feels a little like cypress is moving on before the screen is full rendered within chrome,

**Comment by gregevari** [comment]
I can't reproduce this outside our app, and it turns out that as I get further down the request chain the problem goes away so I'll close this though there is still something of an issue there.  Thanks for your help @jennifer-shehane!
