### ISSUE TITLE
Cypress was unable to save these commands to your spec file: ENOENT: no such file or directory, open ....

### ISSUE THREAD

**Issue by yuchristina** [cypress-io/cypress#16255]
### Current behavior
When I "Save Commands" using Cypress Studio, I get the following error:

>ENOENT: no such file or directory, open '[ABSOLUTE PATH TO THE FOLDER I AM RUNNING THE TEST]/[PACKAGE NAME from PACKAGE.JSON]/[RELATIVE PATH TO TEST FILE]
>
>Cypress was unable to save these commands to your spec file. Cypress Studio is still in beta and the team is working hard to resolve issues like this. To help us fix this issue more quickly, you can provide us with more information by clicking 'Learn more' below.Learn more

### Desired behavior
I expect the tests to be saved to the file for which I have ran Cypress Studio on to generate the commands.
 The path should not have the package name from the package.json file. Instead, it should be: 

'[ABSOLUTE PATH TO THE FOLDER I AM RUNNING THE TEST]/[RELATIVE PATH TO TEST FILE]'

For RELATIVE PATH TO TEST FILE, I had expected it to be derived from the `cypress.json` file from `testFiles` or integration Folder: 
```
  "testFiles": "../apps/**/*.cypress.ts",
  "ignoreTestFiles": "**/node_modules/**",
  "integrationFolder": "../apps/",
```

Curiously, when I click the "open in IDE" button on hover over the file path on the top left, it does open to the correct file path (not the '[ABSOLUTE PATH TO THE FOLDER I AM RUNNING THE TEST]/[PACKAGE NAME from PACKAGE.JSON]/[RELATIVE PATH TO TEST FILE]' version) in the Finder.
### Versions

7.2.0 (Latest Version)

**Comment by jennifer-shehane** [comment]
I don't think that we read the package name in from the package.json. We will interpret the name of the directory that the cypress.json is within as the 'root' of the project, so that may be what you're seeing there. 

Can you show the folder structure like below? I'm having some difficulty recreating and that would be helpful. 

```
📁 root
	- 📁 apps
		- 📄 spec.js
📄 cypress.json
📄 package.json
```

**Comment by yuchristina** [comment]
"We will interpret the name of the directory that the cypress.json is within as the 'root' of the project" --> that is consistent with what I am seeing. I am using a monorepo. 

root 
   - src
      - .cypress
          - cypress.json
          - package.json
      - apps
          - appA
             - package.json
             - appA.cypress.ts
          - appB
             - package.json
             - appB.cypress.ts
       - package.json

**Comment by yuchristina** [comment]
Hi @jennifer-shehane ,

I have figured out a temporary get around.

In plugins/index.ts, add:
`module.exports = (on, config) => {
  config.projectRoot = path.resolve("./../");
  return config;
};`

Looking at how `save command` locates the file to save to, it seems that the project root is by default resolved to where cypress.json resides.

**Comment by panzarino** [comment]
This actually turned out to be a pretty weird issue - our source map utils were not generating the correct path to the file. This issue was caused by the way [source-map](https://github.com/mozilla/source-map) returns a relative file path, it would truncate the `..`. This issue was actually not caused by the use of workspaces/reading the `package.json`, but rather due to having a path that was outside of the `projectRoot`. I've created #16533 with a fix.

(This issue doesn't just affect Studio, it also prevents the "open in IDE" button from working for specific hooks like `before each` and `test body`, and possibly also opening your IDE from an error stack trace)
