### ISSUE TITLE
Impossível abrir nova 'tab' na aplicação com Cypress

### ISSUE THREAD

**Issue by mariellems** [cypress-io/cypress#16256]
Estou tentando automatizar a aplicação do projeto em que trabalho com o  Cypress, é necessário clicar em um botão para direcionar para uma 'tab' dentro da aplicação, porém o Cypress não executa a ação de abrir esta tab.

Configurações:
cypress.json
`"chromeWebSecurity": false,`

spec.js
```
`it("Acessar Tabelas Auxiliares - Timesheet", () => {
        cy.get('a#menu-financeiro').click();`
```

![image](https://user-images.githubusercontent.com/39096226/116462947-789f2100-a840-11eb-86d3-f63a40d37c15.png)

Comportamento esperado:

![image](https://user-images.githubusercontent.com/39096226/116463015-8bb1f100-a840-11eb-9555-d2e0a229f57f.png)

Preciso que clique no elemento destacado na imagem e abra a tab, no exemplo da imagem: **Financeiro**.

Cypress versão 7.2.0

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by mariellems** [comment]
Olá @jennifer-shehane, esse projeto faz parte da empresa na qual trabalho, e não tem como acessar externamente, somente via VPN.
Mas basicamente meu código é:

`    cy.get("#username").type(Cypress.env('user_login'));
    cy.get('#password').type(Cypress.env('user_password'));
    cy.get("#submit").click();
`

spec.js:
`it("Acessar Tabelas Auxiliares - Timesheet", () => {
        cy.get('a#menu-financeiro').click();`

**Comment by jennifer-shehane** [comment]
@mariellems We won't really be able to help without a way to see the app code and a way to reproduce. Or if you can create a smaller reproduction of the problem. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
