### ISSUE TITLE
Samesite cookies: Redirection from auth service to the test portal fails on Chrome 90

### ISSUE THREAD

**Issue by MythilyM** [cypress-io/cypress#16329]
hi All, 
With the recent Chrome 90 upgrade, my Cypress tests started failing at redirection from auth service to the test portal.
I have tested the same by downgrading Chrome to 86 and it works all fine. This works fine in Electron too but the primary focus for us is Chrome.  
There is no change in our BED security settings that should be stopping Chrome. chromeWebSecurity is set to false already in Cypress.json. 

Suspecting that the /callback request when redirecting from auth service to the test portal is dropping cookies. 

Is there something Cyrpess needs to fix, to be compatible with latest Chrome? Please share thoughts or solutions if any? 

Thanks!

**Comment by MythilyM** [comment]
error from test
![image](https://user-images.githubusercontent.com/32950486/117087816-f65cb280-ad93-11eb-9a44-af54f1275063.png)

**Comment by jennifer-shehane** [comment]
@MythilyM We'd need some way to reproduce this in order to investigate what changed in Chrome 90 to affect your test. Can you provide a reproducible example?

**Comment by MythilyM** [comment]
@jennifer-shehane - thanks for the reply. 
Sorry, couldn't give you any details to reproduce considering the enterprise security.
However, with our devs help, found that the issue is introduced with the same site cookie updates from Chrome. 
More details in the post here - https://blog.heroku.com/chrome-changes-samesite-cookie

and fix in this post worked like charm. Redirection works well with this fix.   
https://dev.to/poponuts/overcoming-samesite-cookie-issue-in-cypress-when-running-on-chrome-or-edge-274m

**Comment by nicothyrael** [comment]
The issue is with your __cypress.initial cookie, it did not have:
secure: true
sameSite: 'strict'

options in it. Please fix this.

**Comment by flotwig** [comment]
@MythilyM @nicothyrael I have been unable to reproduce this issue from the information provided. Without a way to reproduce this issue, I can't make any changes. Could either of you share a way for me to reproduce this, possibly by forking https://github.com/cypress-io/cypress-test-tiny to create a reproducible example? Otherwise, the issue cannot be fixed.

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity and that there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment in this issue with a reproducible example and we will consider reopening the issue.
