### ISSUE TITLE
For some websites cypress runner hangs when running cy.visit for the second time in the same test spec

### ISSUE THREAD

**Issue by magdalenaslowinska** [cypress-io/cypress#16360]
### Current behavior
For some websites cypress runner hangs when running `cy.visit` for the second time within the same test session. It's totally frozen and it's not possible to click any button nor interact with page.

- It happens on every browser (Chrome, Edge, Electron, FF), in headless and non-headless mode.
- It happens every time - problem is reproducible on given [website](https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/requisitions).
- DEBUG logs does not show anything interesting.
- `cy.reload` or clicking "Run all tests" from test runner gives the same results

### Desired behavior
It should be possible to reload the page multiple times within one test session.

### Test code to reproduce
The first test passes, cypress get frozen when running `cy.visit` on the second test.
```js
describe('Test issue', () => {
    beforeEach(() => {
        cy.visit('https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/requisitions');
    });

    it('test 1', () => {
        cy.wait(3000);
    });

    it('test 2', () => {
        cy.wait(3000);
    });
});
```

### Versions

Currently on **7.2.0**. Downgraded to **6.7.0** - issue exists.

macOS 11.2.3

**Comment by EddieEldridge** [comment]
I'm having the same issue 

`describe('Create test form', () => {

    beforeEach(() => {
        cy.intercept(
            'GET',
            `${TEST_API}/smoke/example/example-route-1`,
            { fixture: 'example/created-from-route-1.json' }
        ).as('getExample');

        // Navigate to our mocked example route
        cy.visit('/example/example-route-1');

        // Wait for our mocked response
        cy.wait('@getExample');
    });

    it('"Create example 1" button renders succesfully', () => {

        cy.get('[data-cy=create-example-button]').contains('Add Example');
    });

    it('"Create example 2" button renders succesfully', () => {

        cy.get('[data-cy=create-example-button]').contains('Add Example');
    });
});
`

When I use this setup, the second test will always fail. It only happens with the second test. 

When the second test runs, instead of navigating to `/example/example-route-1` again it just notes that the page is loaded and my request isn't intercepted.

**Comment by jennifer-shehane** [comment]
@magdalenaslowinska Video of the behavior. I have to kill the Chrome browser process in order to exit. It's completely hanging. I'm not sure what the issue is.

![](http://g.recordit.co/HUnSriqZt4.gif)

I saw a couple of errors when trying to reload the test with experimentalSourceRewriting on. Unexpected String

<img width="523" alt="Screen Shot 2021-05-06 at 12 43 44 PM" src="https://user-images.githubusercontent.com/1271364/117342360-c501e680-ae68-11eb-9adb-e60fe2a7926a.png">

And https://requirejs.org/docs/errors.html#timeout

<img width="409" alt="Screen Shot 2021-05-06 at 12 42 44 PM" src="https://user-images.githubusercontent.com/1271364/117342268-a996db80-ae68-11eb-96ca-76de70cc13bf.png">


@EddieEldridge Your issue looks unrelated to the Cypress tests hanging that this original issue was opened for. Your is related to intercepting requests. Please open a new issue with a fully reproducible example we can run. The example you provided is not runnable by us.
