### ISSUE TITLE
Video upload takes a long time, extending action runs from 10 minutes to over 50 minutes

### ISSUE THREAD

**Issue by pgerlich** [cypress-io/cypress#16524]
We use http://dashboard.cypress.io/ for free right now. We have observed that the video recording feature seems to result in our tests taking an exceptionally long time to run, but this wasn't always the case.

When we first setup the dashboard, our tests took about 10 minutes to run. But after some weeks of running (we run probably 10k+ tests a month, which is well over the free tier limit) we started to notice that our test runs took anywhere from 20 minutes to 1 hour and 20 minutes to run. We use Github Actions with Github's workers to run our tests.

After disabling the video recording feature, with the following setting:
```
`videoUploadOnPasses: false`
```
we stopped experiencing this issue.

Again, this wasn't always an issue. Sometimes it is totally fine, but others it takes a really long time.

We were theorizing that we might be getting throttled when uploading videos, since we aren't paying anything for cypress dashboard after all. Could this be the case? If so, perhaps Cypress could just reject video uploads for test runs beyond the free tier limit?

-- This isn't a blocker or anything for us, we just wanted to inform you of the behavior. Love the product so far!

**Comment by jennifer-shehane** [comment]
>We were theorizing that we might be getting throttled when uploading videos, since we aren't paying anything for cypress dashboard after all. 

This is not the case. Cypress doesn't have a mechanism to throttle video uploads and there's' no difference in experience with how videos are uploaded with free versus paid accounts.

Parallelization of spec files would be disabled for free accounts going over the limit, so that could increase run time.

If you've reached your limit in the Dashboard also, then you can't view the recordings in the Dashboard, so there's not really a reason to pass the `--record` flag for subsequent runs - as this is just uploading the videos to the Dashboard runs that you can't see. (If you were to upgrade in the future though, you could see those recorded run's data.)

- What version of Cypress are you using? There was a change introduced in 7.0 concerning videos, so if the change in runtime seems connected to that, we can investigate further.

**Comment by bmpieretti** [comment]
I can add some further context here, initially we upgraded cypress from v6.8.0 to 7.1.0, and started seeing massive increases in timing to our CI pipelines for Cypress, as @pgerlich mentioned it went from ~14 mins to ~50-70mins, but would sometimes finish the CI pipeline in ~20mins. The actual tests time was usually around the 20 min mark, with something else having to account for the extra 30-50 mins.

We theorized this was likely due to one or both of the following reasons:
- Videos might be throttled when uploaded to cypress.io
- Video compression

I'm not sure which may have been the real problem, as I never took the time to sit with a stopwatch and time our CI output, and this extra timing wasn't happening locally likely due to not having the resource constraint that github action containers have. 

In the implemented fix, the only changes made were to set `videoUploadOnPasses: false`, and bumping the cypress version to v7.3.0, as I know the team had addressed some performance items  in v7.2.0. The version bump alone didn't seem to be enough here, as we were still seeing 50min builds after the bump.

Any insight into the real issue here given this? Since you mentioned uploads are never throttled, was there any changes to the default compression for videos that may have been responsible for the time, or could this be some other issue we weren't aware of?

**Comment by jennifer-shehane** [comment]
If you are running Cypress in a headless browser, the default screen size was increased in 7.0 to 1920x1080 which some have reported as increasing time with the video processing. 

Could you try reducing the screen size to the default size prior to 7.0 (1280x720) to see if the performance is related to the increase in screen size. [You need to follow the instructions here.](https://on.cypress.io/browser-launch-api#Set-screen-size-when-running-headless) (Note, this is **not** simply changing the `viewportHeight` and `viewportWidth`.)

**Comment by pgerlich** [comment]
We can try that, but the issue isn't consistent between runs and doesn't scale with the number of tests. If screen size was the issue, I would expect more tests to cause a linear increase in run time and consistent run times between builds.

We've actually seen a successful run take 15 minutes to run the tests and then 57 minutes for the cypress run job itself.

We're happy to provide any details on the above ^ or other runs if it might help you diagnose the issue.

**Comment by jennifer-shehane** [comment]
@pgerlich  Yes, any way to reproduce is optimal. You could also run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the set of logs here. I'm curious to see where exactly the time is being taken up. It shows a large amount of time during the compression, processing, upload? I think seeing the DEBUG logs could help us track down the extra unaccounted minutes.

**Comment by jennifer-shehane** [comment]
Hey @pgerlich, just following up to see if there's any new information so we can investigate the video processing timing.

**Comment by jennifer-shehane** [comment]
Closing as stale. Please comment if there is new information or open a new issues if you're experiencing something similar.
