### ISSUE TITLE
Cypress generates new Docker image with each run by default

### ISSUE THREAD

**Issue by dmitrizzle** [cypress-io/cypress#16523]
### Current behavior
When I run `docker run -v $POW:/e2e -w /e2e cypress/included:7.3.0 --config baseUrl=http://host.docker.internal:3000 --spec cypress/integration/my-test-name.spec.js` a new Docker container is spawned. 
<img width="1362" alt="Screen Shot 2021-05-14 at 9 20 59 AM" src="https://user-images.githubusercontent.com/8587882/118301527-095c3a80-b498-11eb-925d-ae7be342fc36.png">

### Desired behavior
I'd expect Cypress to just use one container or at least one container per configuration. Otherwise, a warning in console or note in docs would be helpful.

### Test code to reproduce
`docker run -v $POW:/e2e -w /e2e cypress/included:7.3.0 --config baseUrl=http://host.docker.internal:3000 --spec cypress/integration/my-test-name.spec.js` produces new Docker container on each run.

### Versions
I'm using macOS 10.14.6 and Docker Desktop 3.3.1 (Engine 20.10.5).

**Comment by bahmutov** [comment]
Hello @dmitrizzle 

Every time you run `docker run` you spawn a new container. That container then stops after the tests finish, but there is nothing Cypress can do about it - it is the Docker command `docker run ...` that controls this behavior.

If you are running a lot of tests again and again, you might start the container once using Bash as entrypoint, instead of default `cypress` command. Then you can execute `cypress run` while still in the same container multiple times.

```
$ docker run -it -v $PWD:/e2e -w /e2e --entrypoint=/bin/bash cypress/included:7.3.0
# we are inside the container
root@814ed01841fe:/e2e# cypress run
....
# run tests again
root@814ed01841fe:/e2e# cypress run
```

I will add a note to https://github.com/cypress-io/cypress-docker-images/tree/master/included to explain this.
