### ISSUE TITLE
Strange Output:  non_webpack_require lodash.js when using @rails/webpacker with cypress component tests

### ISSUE THREAD

**Issue by anark** [cypress-io/cypress#16559]
### Current behavior

If you try to use component tests in a project that uses @rails/webpacker your preview window will contain some strange output nested in with the component
```js
var _ = __non_webpack_require__("/Users/Development/cypress-comonent-test-webpacker-example/node_modules/lodash/lodash.js");module.exports = function (templateParams) { with(templateParams) {return (function(data) { var __t, __p = ''; __p += '\n\n \n \n \n \n \n \n \n
\n \n\n'; return __p })();}}
```
![Preview](https://github.com/anark/cypress-comonent-test-webpacker-example/raw/master/preview-image.png)

### Desired behavior

This output should not be there, just the component should be rendered.

### Test code to reproduce

https://github.com/anark/cypress-comonent-test-webpacker-example

### Versions
Cypress: 7.3.0
@cypress/react: 5.7.0
@rails/webpacker: 6.0.0-beta.7
webpack: 5.37.0
@cypress/webpack-dev-server: 1.3.0

**Comment by mattvague** [comment]
I'm using the same setup as @anark and I also have this issue. It took some serious digging but I think I've figured out what's going on and have a hacky workaround.

In short, @cypress/webpack-dev-server uses HTMLWebpackPlugin to bundle your component in an HTML file, which is then rendered in the cypress test runner. If no other loader is found to handle `.html` files, HTMLWebpackPlugin uses [it's own built in loader](https://github.com/jantimon/html-webpack-plugin/blob/main/lib/loader.js#L35-L39), which outputs the following string:

```js
...
return 'var _ = __non_webpack_require__(' + JSON.stringify(require.resolve('lodash')) + ');' +
    'module.exports = function (templateParams) { with(templateParams) {' +
      // Execute the lodash template
      'return (' + template.source + ')();' +
'}}';
```

This string is meant to be executed as Javascript, but for some reason in our case it is being injected verbatim into @cypress/webpack-dev-server's [index-template.html](https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/index-template.html) file and is then passed to the cypress test runner.

My hacky workaround was just to copy the vanilla loader from HTMLWebpackPlugin and replace the returned string with just the rendered component HTML in `template.source`:

```js
'use strict';
const _ = require('lodash');

module.exports = function (source) {
  // Get templating options
  const options = this.getOptions();
  const force = options.force || false;

  const allLoadersButThisOne = this.loaders.filter((loader) => loader.normal !== module.exports);

  // This loader shouldn't kick in if there is any other loader (unless it's explicitly enforced)
  if (allLoadersButThisOne.length > 0 && !force) {
    return source;
  }

  // Allow only one html-webpack-plugin loader to allow loader options in the webpack config
  const htmlWebpackPluginLoaders = this.loaders.filter((loader) => loader.normal === module.exports);
  const lastHtmlWebpackPluginLoader = htmlWebpackPluginLoaders[htmlWebpackPluginLoaders.length - 1];
  if (this.loaders[this.loaderIndex] !== lastHtmlWebpackPluginLoader) {
    return source;
  }

  // Skip .js files (unless it's explicitly enforced)
  if (/\.js$/.test(this.resourcePath) && !force) {
    return source;
  }

-  // The following part renders the template with lodash as a minimalistic loader
-  //
-  const template = _.template(source, { interpolate: /<%=([\s\S]+?)%>/g, variable: 'data', ...options });
-  // Use __non_webpack_require__ to enforce using the native nodejs require
-  // during template execution
-  return 'var _ = __non_webpack_require__(' + JSON.stringify(require.resolve('lodash')) + ');' +
-    'module.exports = function (templateParams) { with(templateParams) {' +
-      // Execute the lodash template
-      'return (' + template.source + ')();' +
-    '}}';
-};
+  return template.source
```

To enable the loader, I just added it like so to my custom webpack config in `cypress/plugins/index.ts`

```js
on('dev-server:start', (options) => {
    return startDevServer({
      options,
      webpackConfig: {
        ...webpackConfig,
        module: {
          ...webpackConfig.module,
          rules: [
            ...webpackConfig.module.rules,
            // Hacks on hacks on hacks to fix stupid issue with HTMLWebpackPlugins default loader
            {
              test: /\.html$/,
              use: [
                {
                  loader: path.resolve('cypress/plugins/loader.js')
                }
              ]
            }
          ]
        }
      }
    })
  })
```

As I say, it ain't pretty but at it's at least a temporary work around, and maybe will also help the nice Cypress folk 😄 here pinpoint what the real issue is.

## Versions

Cypress: 8.5.0
@cypress/react: 5.10.1
@rails/webpacker: 6.0.0-rc.1
webpack: 5.56.1
@cypress/webpack-dev-server: 1.6.0

**Comment by rockindahizzy** [comment]
Can you still reproduce this with the latest version of Cypress?

**Comment by lmiller1990** [comment]
This is 5 majors behind - if it's still an issue, please make a new one with the latest Rails and Cypress. 👍

**Comment by gotoAndBliss** [comment]
Cypress 12.3 and still reproducible ( via Webpacker now called Shakapacker )

**Comment by gastonmorixe** [comment]
Yes +1 we had this a few days ago, easily solvable but still happening

**Comment by lmiller1990** [comment]
If I update the minimal repo in the OP does is still occur?

We can re-open, would be great to have a current repro someone can clone and work off.

**Comment by andreycrane** [comment]
Hey guys! Issue is still actual. Is there any workaround about it? What should I do with own webpack config?
