### ISSUE TITLE
cy.visit() timeout ignored

### ISSUE THREAD

**Issue by mattcopas** [cypress-io/cypress#1657]
I require a longer timeout when visiting my project's site (as a docker image needs to boot up first).

I understand there are 2 ways to do this - either set pageLoadTimeout: 600000 in cypress.json or use cy.visit(url, {timeout: 600000})

I've tried both of these techniques but the test still times out and fails after a minute (default) - so it would seem these values are being ignored.

### Current behavior: 
The test times out and fails after a minute 

### Desired behavior:
The test should allow 10 minutes (600000 ms) before timing out, when trying to visit the website under test

### Steps to reproduce:

cy.visit(someUrlThatDoesntWork, {timeout: 600000}) // or set pageLoadTimeout in cypress.json
Test will timeout after 1 minute, not the expected 10 

```js

```

**Comment by jennifer-shehane** [comment]
Hi, I did some research into this issue and have come to a few conclusions:

1. The `timeout` option is not being ignored. You can verify this by setting the `timeout` to a lower value and see that it times out more quickly than the default `60000`ms.
2. The reason this is failing is because network connections that are not finished are eventually timed out by Cypress/the underlying operating system, which then causes the `cy.visit` to fail. This is something we can "kind of" tweak in Cypress - basically we can up the timeout for `ESOCKETTIMEOUT` but only up to the maximum the operating system allows.

**The better solution for your problem is not to start Cypress until you are sure your server has started before even running `cypress run`. You can try a utility like [`start-server-and-test`](https://docs.cypress.io/guides/guides/continuous-integration.html#Helpers) or [`wait-on`](https://github.com/jeffbski/wait-on) to achieve this.**
