### ISSUE TITLE
How to set environment JSON file in different folder 

### ISSUE THREAD

**Issue by swatantra15081986** [cypress-io/cypress#16639]
Please help me . Create one folder 'environment' under project folder and create 'production js'

Created app.js file under project and write :-

process.env.NODE_ENV = process.env.NODE_ENV || 'production'

So that I call in the test specs file.

var env_js = require ('../.. environment/wms/') + process.env.NODE_ENV

It is taking 'development.js' env by default.how can we switch to 'production.js'

**Comment by lmiller1990** [comment]
This doesn't seem to be a Cypress specific issue. Either way, I think your `require` statement is incorrect. How about:

```js
var env_js = require ('../.. environment/wms/' + process.env.NODE_ENV)
```

[Read more about Cypress environment variables here](https://docs.cypress.io/guides/guides/environment-variables).

**Comment by swatantra15081986** [comment]
I have read the document already. Actually there are two folder 'wms' and
'logistics', I want to add demo.js, staging.js,production.js file in wms
folder and then same to 'logistics' but env data are different . How can we
do it ?

**Comment by lmiller1990** [comment]
Can you explain a bit more about what you'd like to accomplish? For example "I want to dynamically set the `NODE_ENV` variable". I still don't fully understand your goal. 

Where is this code getting executed? Node.js (for example in `cypress/plugins/index.js`, or via `cy.task`, or in the browser when executing the tests? I assume it's in a Node.js context, since `process` does not exist in the browser.

**Comment by swatantra15081986** [comment]
Dear sir
Actually I have created one folder environment and two another folder DTDC
and WMS under it.
[image: image.png]


I want to import environment variables in integration fileby below command
:-


[image: image.png]

How can i set the environment.I have created app.js file and ewrite code:
const env1 = process.env.NODE_ENV || 'production' + '.js'


But it is not working.

Please help.

**Comment by lmiller1990** [comment]
Your images and not appearing correctly. 

If you'd like more help, you'll need to provide a minimal repository showing me exactly what you want to do. Please include instructions on how to run it, and post a link here.

I don't think this is an actual bug in Cypress. Happy to help, but I am going to close this issue since I don't think we need to make any changes to Cypress.

**Comment by swatantra15081986** [comment]
I am asking the way:
 We can easily set env variables if we create demo.json, production.json.
But I want to create one folder 'wms' under config and then want to create
demo.json, production.json under wms folder .
What the approach without hardcopy folder name 'wms'.

**Comment by lmiller1990** [comment]
Does this not work? https://github.com/cypress-io/cypress/issues/16639#issuecomment-846736267
