### ISSUE TITLE
Cypress do not save variable value for later use in the next test

### ISSUE THREAD

**Issue by yasinitskyi** [cypress-io/cypress#16646]
Cypress do not save a variable value for later use in the next test IF two tests, namely it(), are sharing different domains.

```
describe('test', function() {
  let str;
  it('take value from input', () => {
    cy.visit('/');
    cy.contains('Forms').click();
    cy.contains('Form Layouts').click();
    cy.contains('nb-card', 'Using the Grid').find('[data-cy="imputEmail1"]').type('someemil@email.com').invoke('val').then((value) => {
      this.str = value;
      cy.log(this.str); // someemil@email.com
    });
  });

  it('log value', () => {
    cy.visit('https://facebook.com') // just an example
    cy.get('[type="email"]').then((input) => {
      cy.log(this.str); //undefined
     });
  });
});
```

**Comment by bahmutov** [comment]
This is expected behavior, as the spec reloads completely when visiting a new domain. You can pass a value using either a cy.task or by saving it into a file

- recipe ["Visiting 2nd domain"](https://github.com/cypress-io/cypress-example-recipes#server-communication)
- recipe ["Pass value between specs"](https://github.com/cypress-io/cypress-example-recipes#server-communication)
-
