### ISSUE TITLE
cy.visit() performance degradation

### ISSUE THREAD

**Issue by milankonir** [cypress-io/cypress#16671]
### Current behavior

We're using Cypress to test large pages (several megs) and noticed severe performance degradation since upgrading to version `7.2.0`. It takes over 20 seconds to visit the page. Majority of time is spent on TTFB. We have also noticed considerable increase in memory usage.

The problem persists with versions `7.3.0` and `7.4.0`.

![image](https://user-images.githubusercontent.com/72383088/119464706-4d2a2c00-bd43-11eb-9ff3-cfb7f4cd4781.png)

Loading the same page outside of Cypress automation takes fraction (~3 seconds) as the long TTFB period is not present

![image](https://user-images.githubusercontent.com/72383088/119495518-c5ecb080-bd62-11eb-8d5c-70c298d2a3e8.png)

### Desired behavior

Loading the page via `cy.visit();` should take similar time (~3 seconds) as it does when visiting the page in browser and as it did prior to version `7.2.0`.

### Test code to reproduce

Fork with repro: https://github.com/milankonir/cypress-test-tiny

Screenshot from repro: 
![image](https://user-images.githubusercontent.com/72383088/119494984-32b37b00-bd62-11eb-966d-f54ae8e2249b.png)

### Versions

**Affected versions:** `7.2.0`, `7.3.0`, `7.4.0`
**Last working version:** `7.1.0`

**Comment by jennifer-shehane** [comment]
Yah, wow, I can reproduce this. Thanks for providing a reproducible example, this helps. 

The site load event fires 20 seconds slower in 7.2.0 than in 7.1.0. I tracked this down to being introduced in https://github.com/cypress-io/cypress/pull/16113, where we downgraded electron. I had to pass in `contextIsolation` to get this commit to run, so I guess it's also possible that the `contextIsolation` change it the root cause: https://github.com/cypress-io/cypress/commit/48fe3fb5b261e10b71ca89c41f754008be60e0fc It's weird because this issue isn't present in 7.0.1.

**Issue not present**: https://github.com/cypress-io/cypress/commit/d4e48858fb7b80fe2b926a88df7760173f005db7
**Issue present**: https://github.com/cypress-io/cypress/commit/7b55863b749d358dcfc1ed4cb4cea13ccea5a85e

### 7.1.0

<img width="1372" alt="5-secs-test" src="https://user-images.githubusercontent.com/1271364/119555101-12d08700-bd63-11eb-95c0-5dada8dceee6.png">


### 7.2.0
<img width="1387" alt="25-secs-test" src="https://user-images.githubusercontent.com/1271364/119559187-f71baf80-bd67-11eb-9e00-f6dbebbfd8ab.png">

**Comment by jennifer-shehane** [comment]
Reopening as we are reverting the previous PR to avoid possible performance implications for many users on low resources machines recording video. We'll continue investigating and hopefully move towards updating Electron to fix this issue.
