### ISSUE TITLE
Keep getting redirect error after disabling windows security and set redirectionLimit higher

### ISSUE THREAD

**Issue by avranil82** [cypress-io/cypress#16691]
### Current behavior
I am trying to submit more than 20 applications but I am receiving this error message, I increased limit to 200 in Cypress.Json file and disabled windows security but did not work.

"redirectionLimit": 200,
"chromeWebSecurity": false

**Error message coming in cypress:** The application redirected to more than 20 times. Please check if it's an intended behavior. If so, increase redirectionLimit value in configuration.

**Comment by jennifer-shehane** [comment]
@avranil82 Please provide an example test of what you're doing. Windows security shouldn't have anything to do with the redirectionLimit. 

The intent behind the redirectionLimit is that your test could get stuck in a loop forever if it redirected back and forth from the same url forever. 

I tested the `redirectionLimit` override and it does indeed work. So increasingg it to 200 should work.

**Comment by jennifer-shehane** [comment]
@sainthkh I noticed that there isn't actually a test that the 'redirectionLimit' configuration override does anything, so had to test this manually. Although this may be kind of difficult to test.

**Comment by avranil82** [comment]
@jennifer-shehane I am trying to submit 100 applications into the applications I am testing. Cypress is submitting until 20th and then I am getting that error message. Are you saying there is some security in place in the browser itself?

> @avranil82 Please provide an example test of what you're doing. Windows security shouldn't have anything to do with the redirectionLimit.
> 
> The intent behind the redirectionLimit is that your test could get stuck in a loop forever if it redirected back and forth from the same url forever.
> 
> I tested the `redirectionLimit` override and it does indeed work. So increasingg it to 200 should work.

**Comment by jlherren** [comment]
Hi, I experience the same error. It seems that the redirection counter is not properly reset on every new request, such that doing more than 20 identical POST requests in a row in the same test causes problems, even if they each only redirect once.

I have created a test case here: https://github.com/jlherren/cypress-test-tiny/tree/bug16691

I had to use an external server, since I didn't find a way to submit a good old form on `example.cypress.io`. The deployed `index.php` file is also committed.

Let me know if anything is missing for you to reproduce this.

**Comment by BlueWinds** [comment]
Thank you for the tiny-test, it demonstrates the issue very clearly.

Adding this to our list of bugs to take a look at.

**Comment by jennifer-shehane** [comment]
Original PR for redirectionLimit: https://github.com/cypress-io/cypress/pull/14643

**Comment by jlherren** [comment]
This is still an issue in Cypress 12.12.0. I have updated the reproduction repository: https://github.com/jlherren/cypress-test-tiny/tree/bug16691-2

**Comment by AtofStryker** [comment]
Hi @jlherren. I took a look at your reproduction repository but I am unable to reproduce the issue adding the configuration described in the issue. Is there something I am missing here?

https://github.com/cypress-io/cypress/assets/3980464/fcf59660-4f91-490f-8da3-c3f3cf20a4c0


https://github.com/cypress-io/cypress/assets/3980464/fec1e955-be5e-4e08-b0a6-8b5894a52908

**Comment by jlherren** [comment]
You seem to have added something to `cypress.config.js`. Did you increase the redirection limit? My understanding is that separate cypress commands, which cause separate form submissions, should not count towards the same limit.  The limit should be reset between cypress commands.

**Comment by AtofStryker** [comment]
> You seem to have added something to `cypress.config.js`. Did you increase the redirection limit? 

I increased the limit to `200` to see if the issue would persist and it seemed to resolve the problem as expected.

> My understanding is that separate cypress commands, which cause separate form submissions, should not count towards the same limit. The limit should be reset between cypress commands.

As far as I understand, the redirection limit is [global](https://docs.cypress.io/guides/references/configuration#Global) and applies to any redirect of the application itself. Is there a resource or something in our documentation that makes you believe otherwise?

**Comment by jlherren** [comment]
> As far as I understand, the redirection limit is [global](https://docs.cypress.io/guides/references/configuration#Global) and applies to any redirect of the application itself. Is there a resource or something in our documentation that makes you believe otherwise?

No, the documentation does not indicate otherwise, but then again it is only documented very briefly. The reason why this option was introduced in the first place, was to detect redirection loops (#14445 / #14643). The example I provided is clearly not a redirection loop, it redirects exactly once before responding with an HTML document. Every button click is exactly one single redirection. So this behavior definitely goes against what I would expect from a feature that prevents redirection loops. Further, it is arguably not very useful this way, because for an arbitrary long test, I will have to set this value to an arbitrary high value.

**Comment by AtofStryker** [comment]
@jlherren Ok that makes sense. It seems different from the original issue, so what I think is best is we close this issue, and open an issue about redirect limits applying to more than just redirect loops and we triage it as a feature. Would you be able to open that issue? How does that sound?
