### ISSUE TITLE
Video Recording has become super slow within Chrome

### ISSUE THREAD

**Issue by chasemgray** [cypress-io/cypress#16696]
### Current behavior
Our test runs within Chrome are very slow after upgrading from 6.6.0 to 6.7.0. We also had to update to a more recent version of Chrome due to something required in cypress that only newer Chrome has.
We have frames per second tracking within some of our tests which run in a canvas and after the upgrade we see a drop of 50-75% of the FPS that we used to have before the upgrade.
We've tried all the recent versions of Cypress and they all have the same issues.
We also tried adjusting the windowSize as suggested in some solutions but this didn't help.
For example, launchOptions.args.push('--window-size=1280,768');

We tested out electron and it doesn't have the same issue.

We finally completely disabled video recording and our FPS shot back up to even faster than before so it's definitely something around the video recording.

The drop in performance immediately following our 6.7.0 upgrade and continuing into our 7.2.0 upgrade:
![Screen Shot 2021-05-26 at 5 14 02 PM](https://user-images.githubusercontent.com/68772/119742812-cd38ba80-be45-11eb-8632-b5a43b3e29fa.png)

After disabling video recording within Cypress 7.2.0:
![Screen Shot 2021-05-26 at 5 07 09 PM](https://user-images.githubusercontent.com/68772/119742701-9b275880-be45-11eb-83cf-9d85c10dd91e.png)

### Desired behavior

Enabling recording should not have such a significant performance impact on our app. It becomes unusable with the latest cypress and causes constant flakes due to the slow framerate.

### Versions
Cypress 6.6.0 worked for us, anything from 6.7.0 to 7.2.0 has not helped.

**Comment by helenanull** [comment]
Having the same exact issue, last usable Cypress version is **6.6.0**, last attempt was to upgrade to **8.0.0** but still very slow (tests are taking twice as long if not more)
Browser Chrome and both headless and headed versions.
Even with video disabled, 6.6.0 is faster than newer versions

**Comment by jennifer-shehane** [comment]
Chrome 89+ introduced a change to the amount of frames captured when video recording, so that it does slow down Cypress performance when recording video. This is the only performance affecting thing that we have diagnosed so far. https://github.com/cypress-io/cypress/issues/16152

7.2.0 introduced an issue that could cause some sites to load slower than before (cy.visit taking longer to load). https://github.com/cypress-io/cypress/issues/16671

🙏 Please provide a reproducible example to show a test suite taking twice as long in 8.0.0 versus 6.6.0. We have spent a lot of hours tracking this down and testing suites in many different containers and OS's and have not come up with any other causes than the ones I listed.
