### ISSUE TITLE
Globally installed cypress not finding local project

### ISSUE THREAD

**Issue by nothingismagick** [cypress-io/cypress#1672]
### Current behavior: 
When: 
 - cypress has been installed globally
 - cypress tests and configs have been generated in the project folder
 - starting a cypress instance from within a project folder via CLI

It: 
 - can't find the project immediately

![screen shot 2018-05-03 at 12 03 06](https://user-images.githubusercontent.com/35242872/39570866-ff18810a-4ec9-11e8-9609-27da6cf47c2a.png)

### Desired behavior:

Expect:
 - cypress to search for configs / tests in its CWD (project folder)
 - offer these to the user instead of making them search through their filesystem

### Steps to reproduce:

Install globally with valid integration tests in a local project.

### Versions  
Cypress 2.1.0 - MacOS - quasar-cli (in development for test mode)

**Comment by brian-mann** [comment]
@nothingismagick @Bkucera says you will prove you wrong and finish caching the binary :-P

We know a lot of our users want this. We're doing the "simplest" thing first which is to cache Cypress versions globally and reuse them between all projects. 

After that you'll see us do things like caching `ffmpeg` between versions (to reduce the size of downloads) and then from there do the same thing with electron so that new versions of Cypress will only include the app files + node modules. Should reduce the `.zip` by like 80-90%. It takes time but we'll get there.

**Comment by nothingismagick** [comment]
I trust that @Bkucera is fully aware of how awesome it would be to have the binary cache'd outside the local scope of the project - and having a pathway for me to dynamically link an ffmpeg binary (that I have built and trust) would also offload some of the bulk of the package. Of course that would also need to be a different kind of (probably wrapped) install process, because yarn/npm aren't really that "interactive"...
