### ISSUE TITLE
Permanently deleting runs from Cypress Dashboard

### ISSUE THREAD

**Issue by moroshko** [cypress-io/cypress#16759]
It would be useful to be able to permanently delete certain runs due to sensitive information in the recorded video/screenshot.

I found #1839, but it looks like we just have the ability to archive a particular run, not to permanently delete it.

Any plans to add a "permanent delete"?

**Comment by jennifer-shehane** [comment]
The best place to express interest and see progress for Dashboard features is on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I'll' be closing this issue since this is related to our Dashboard and we want to make sure any feedback gets seen and addressed by the right team. 

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there.
