### ISSUE TITLE
should('have.length.above') suppresses other assertion messages

### ISSUE THREAD

**Issue by monkpit** [cypress-io/cypress#16783]
If I chain assertions after `.should('have.length.above')` then some of the assertions after it are not shown on the log.

Example:

```javascript
describe('Cypress', () => {
    it('can display all assertions after "have.length.above"', () => {
        cy.visit('https://developer.mozilla.org/en-US/');
        cy.get('.hero-content')
            .should('have.length.above', 0)
            .should('contain', 'Resources') // this command runs, but it is never logged unless it fails
            .should('contain', 'developers');  // this command is logged even when passing (expected behavior)
    })

    // example without browsing to a page
    it('can display all assertions after "have.length.above" without a webpage', () => {
        const array = [1, 2, 3];
        cy.wrap(array)
            .should('have.length.above', 1)
            .should('contain', 1)
            .and('contain', 2);
    })
})
```

![image](https://user-images.githubusercontent.com/5297293/120532988-e1306f00-c3a5-11eb-809b-8629b33e27f3.png)

Notice how there is only 1 message for the 2 `'contain'` assertions, it only shows the second one.

If we change the test and convert `'have.length.above', 0` to `'have.length', 1`, then both assertions are shown:

![image](https://user-images.githubusercontent.com/5297293/120533503-6451c500-c3a6-11eb-83cb-83d534496498.png)

In this image we can see both `Resources` and `developers` in the assertions.

### Versions

Tested on Cypress v6.9.1 and v7.4.0, with Chrome and Electron.

**Comment by jennifer-shehane** [comment]
Looks like maybe another example of this issue https://github.com/cypress-io/cypress/pull/16218, where some `.contains()` assertions followed by certain assertions don't show all `.contains()` logs. cc @sainthkh 

### Reproducible example

```js
it('can display all assertions after "have.length.above"', () => {
  cy.visit('index.html');
  cy.get('div')
    .should('have.length.above', 0)
    .should('contain', 'Testing') // this command runs, but it is never logged unless it fails
    .should('contain', 'Cypress') // this command is logged even when passing (expected behavior)
})
```

```html
<html>
<body>
  <div>
    <h1>Testing with Cypress.</h1>
  </div>
</body>
</html>
```

<img width="706" alt="Screen Shot 2021-06-02 at 2 55 29 PM" src="https://user-images.githubusercontent.com/1271364/120544044-9cf79b80-c3b2-11eb-80cf-e1cd1ba92b45.png">

**Comment by sainthkh** [comment]
#16218 and this issue seems similar, but it has different causes. The cause of #16218 is expected duplicated call of command. It's caused by unexpectedly merging log messages below:

https://github.com/cypress-io/cypress/blob/e0c385e0a2b5c0d343399280ab8b7e2aa2e12113/packages/driver/src/cy/assertions.js#L332-L344

Simply removing those code would solve the problem. But I'm trying to understand why the merge happens and how to solve that.

**Comment by sainthkh** [comment]
#16218 and this issue seems similar, but it has different causes. The cause of #16218 is expected duplicated call of command. It's caused by unexpectedly merging log messages below:

https://github.com/cypress-io/cypress/blob/e0c385e0a2b5c0d343399280ab8b7e2aa2e12113/packages/driver/src/cy/assertions.js#L332-L344

I guess there should be some discussion about this behavior. It's implemented because some assertions create 2 messages like `have.property`. As `have.property` cannot be chained like below, it wasn't a problem.

```js
cy.wrap({ a: 1, b: 2 })
.should('have.property', 'a', 1)
.should('have.property', 'b', 2)
```

(Is this intended behavior?)

The problem is that there are more commands that create 2 messages: `have.length.above` is one of them. 

When it's chained together with other assertions, there are more messages with fewer commands. Because of that, the last message is merged with the last command, that's why one `contain` message is gone above. 

I checked the code and it's hard to check which message belongs to which command. That's why we had to write code like below: 

https://github.com/cypress-io/cypress/blob/e0c385e0a2b5c0d343399280ab8b7e2aa2e12113/packages/driver/src/cy/assertions.js#L274-L285

And this issue proves that this code doesn't work. The simplest solution is to remove the merge. But I want to be sure if it's what the Cypress team wants.

**Comment by jennifer-shehane** [comment]
I can't remember why we were doing this exactly. There's likely some reason, where it was showing double identical logs when it shouldn't. Maybe play around with removing the merge and see how many tests fail when that's done?

**Comment by sainthkh** [comment]
It was added at https://github.com/cypress-io/cypress/commit/c56556db973f5702a0618ef371713ba7137c03fd.

I experimented by removing it and got this result:

![image](https://user-images.githubusercontent.com/8130013/121833107-8fbda380-cd06-11eb-8431-4b358ef40568.png)

It seems it's valid attempt. The solution might be more carefully merging messages.

**Comment by jennifer-shehane** [comment]
@sainthkh Yeah, I thought this was what this code was for. I remember when it used to log every single retry attempt in the runner, sometimes hundreds of them. 😆 Let's not do this, but maybe there's a way to be smarter about the merge via the message content rather than a count.
