### ISSUE TITLE
Duplicate var declarations between spec files

### ISSUE THREAD

**Issue by goldylucks** [cypress-io/cypress#16819]
### Current behavior
Declaring a var/function with the same name in two different spec files gives a TS error of "Duplicate function implementation", tho the tests of course pass

### Desired behavior
it shouldn't happen

### Test code to reproduce
create a cypress project with TS, create a var/function in two different files with the same name

### Versions
7.4.0

**Comment by jennifer-shehane** [comment]
@goldylucks How are you running the tests when you get this error?

**Comment by goldylucks** [comment]
The error is on my IDE (vscode)

The tests pass on both `$ cypress run` and `$ cypress open`

**Comment by goldylucks** [comment]
any updates on this? anything I can do on my end to make it easier for you guys to look into it?
maybe there's a way to workaround it in the meantime through the `tsconfig.json` ? (I've copied mine from the docs)

**Comment by jennifer-shehane** [comment]
Oh, sorry, I missed that this is a TypeScript error. I would recommend using `@ts-ignore` to get around this for now. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#suppress-errors-in-ts-files-using--ts-ignore-comments

**Comment by goldylucks** [comment]
well of course that's what I'm using :)
but this happens only in my cypress files, not in any of my other projects, so I'm only assuming it's a cypress related bug

**Comment by jennifer-shehane** [comment]
You'd be surprised by how many people don't know they can ignore TS errors. 😅 

I think this is not a Cypress specific issue. It's explained here: https://stackoverflow.com/a/41975448/5878476 

>So if your file doesn't have any sort of top-level import or export statements, then you'll occasionally see issues with global declarations interfering with each other. https://stackoverflow.com/a/41975448/5878476

Probably you don't see this in other files because they already have imports/exports.  You can get around it by adding `export {}` to the top of the file. 

`spec.ts`

```ts
function foo() {
  return 'bar'
}
```

`spec2.ts`

```ts
function foo() {
  return 'bar'
}
```

<img width="623" alt="Screen Shot 2021-06-15 at 12 54 49 PM" src="https://user-images.githubusercontent.com/1271364/122100532-e8f60780-cdd8-11eb-8830-0ef5ecd23ced.png">
