### ISSUE TITLE
Large File handling - Cypress.fixture(fileName, fileEncoding) - cannot create a string longer than

### ISSUE THREAD

**Issue by LoganWlv** [cypress-io/cypress#16823]
### Current behavior
`Cypress.fixture(fileName, fileEncoding)` breaks when loading a 500MB csv file.

![image](https://user-images.githubusercontent.com/22358070/121006756-90e45300-c791-11eb-90ea-23b9851b17a7.png)

### Desired behavior
Be able to load a ~500MB fixture. 

### Test code to reproduce

.js 

```javascript
import { Given, Then } from 'cypress-cucumber-preprocessor/steps'

Given('Load file {string} and {string}', (fileName, fileEncoding) => {
  cy.fixture(fileName, fileEncoding).then(v => console.log(v))
})

Then('File should be loaded', loadedFile => {
  return true;
})
```

.feature 

```gerkins
Feature: Test

  Scenario Outline: Load large file

    Given Load file '<file>' and '<encoding>'
    Then File should be loaded
    Examples:
      | file              | encoding |
      | tuto_DB_italy.csv | utf8     |
```

use any .csv file that size is at least 500MB

### Versions

dependencies: 

```json
"@testing-library/cypress": "^7.0.6",
"clipboardy": "^2.3.0",
"cypress": "^7.4.0",
"cypress-cucumber-preprocessor": "^4.1.0",
"cypress-file-upload": "^5.0.7"
```
OS: MacOs Catalina 10.15.7
Browser: Chrome 91

**Comment by LoganWlv** [comment]
It seems to happen in the server side. 

Extra logs: 

![image](https://user-images.githubusercontent.com/22358070/121027210-1292ab80-c7a7-11eb-8b35-a9255048af3f.png)

Here's what I get in the web socket: 

![image](https://user-images.githubusercontent.com/22358070/121027011-ed05a200-c7a6-11eb-9e16-ad29c3b81d2b.png)

**Comment by BlueWinds** [comment]
In Cypress 9.0.0, we added the `null` encoding, which helps significantly when dealing with large fixtures and files. This transfers the data as an ArrayBuffer rather than a base64 encoded string.
https://docs.cypress.io/api/commands/fixture#Arguments

Cypress still tends to encounter issues with files in the gigabyte range, but 500mb should now be doable. Going to close this issue as resolved, feel free to let us know if the above still isn't working for you.
