### ISSUE TITLE
the times parameter in cy.interceptor is not respected

### ISSUE THREAD

**Issue by A-ZC-Lau** [cypress-io/cypress#16821]
### Current behavior

When the `times` parameter is used in RouteMatcher, it doesn't respect the limit (i.e. using `times: 1` will still match more than once

![Screen Shot 2021-06-07 at 5 14 59 pm](https://user-images.githubusercontent.com/20273647/120975150-41634e80-c7b4-11eb-99ed-b95e2222ef4a.png)

### Desired behavior

It should only match up to the `times` specified.

### Test code to reproduce

```js
/// <reference types="Cypress" />
/* global cy */

before(() => {
	cy.visit("https://mocki.io/fake-json-api");
});

describe(
	"interceptor times test",
	function () {
		it(
			"should not intercept twice",
			function () {
				const routeMatcher = {
					method: "POST",
					times: 1,
					url: /graphql$/
				};
				cy.intercept(
					routeMatcher,
					(req) => {
						req.continue(res => {
							console.log("hello i am here");
							console.log(res);
						});
					}
				)
					.as("interceptor");
				cy.get("#success").should("not.be.visible");
				cy.get("#body").type("{ \"abc\": 123 }", { parseSpecialCharSequences: false });
				cy.get("#create").click();
				cy.get("#success").should("be.visible", { timeout: 10000 });

				cy.get("#body").clear().type("{ \"another\": 123 }", { parseSpecialCharSequences: false });
				cy.get("#create").click();
				cy.get("#success").should("not.be.visible");
				cy.get("#success").should("be.visible", { timeout: 10000 });
			});
	});
```

### Versions

7.4

**Comment by jennifer-shehane** [comment]
I can verify the issue described above. I modified the example slightly so that there is a failing test (that should be passing). 

The test should only mock the data the first time the request matches (because `times: 1` was passed), but it passes on 2 requests. 

```js
it('should not intercept twice', () => {
  cy.visit('https://mocki.io/fake-json-api')
  
  cy.intercept({
    method: 'POST',
    times: 1,
    url: /graphql$/
  },
    (req) => {
      req.continue(res => {
        res.body.data.createPublicStage.url = 'foobar'
      })
    }
  ).as('interceptor')

  cy.get('#success').should('not.be.visible')
  cy.get('#body').type('{ "abc": 123 }', { parseSpecialCharSequences: false })
  cy.get('#create').click() // submit form that will generate url
  // ✅ success msg contains mocked 'url' dats in 1st match
  cy.get('#success').should('contain', 'foobar') 

  cy.get('#body').clear().type('{ "another": 123 }', { parseSpecialCharSequences: false })
  cy.get('#create').click() // submit form that will generate url
  cy.get('#success').should('not.be.visible') // make sure the succes msg rerenders
  cy.get('#success').should('be.visible')
    // ❗️ success msg shouldn't contain mocked 'url' data in 2nd match
    .and('not.contain', 'foobar') 
})
```

<img width="1074" alt="Screen Shot 2021-06-15 at 11 19 26 AM" src="https://user-images.githubusercontent.com/1271364/122088817-bf82af00-cdcb-11eb-9852-8e0a7172e0ea.png">

**Comment by sainthkh** [comment]
I ran the example above and found out that `cy.intercept` intercepts once correctly. 

![Peek 2021-06-28 16-01](https://user-images.githubusercontent.com/8130013/123594070-34250700-d82a-11eb-8f76-29faff748273.gif)

The thing we need to check is why `foobar` is applied twice.

**Comment by jennifer-shehane** [comment]
@sainthkh I'm seeing the exact opposite behavior, in Cypress 7.6.0. 

![](http://g.recordit.co/XzDoB2A9w6.gif)

**Comment by sainthkh** [comment]
@jennifer-shehane It's because I didn't restart Cypress after modifying code. I fixed the problem and opened [the PR](https://github.com/cypress-io/cypress/pull/17138).

@A-ZC-Lau After fixing the `req.continue` behavior`, @jennifer-shehane's test is still failing. I guess it's because of the cache problem on mocki.io's side. 

I genereated the api urls with `{"abe":123}` and `{"another":123}`, but they were same. Is this intended behavior?
