### ISSUE TITLE
Option for using the exact domain when setting a Cookie

### ISSUE THREAD

**Issue by jerrykobes** [cypress-io/cypress#16856]
### What would you like?
An additional option within `SetCookieOptions` for `cy.setCookie(name, value, options)` that allows for setting an exact domain without a prepended period as described in https://github.com/cypress-io/cypress/issues/1896 .

### Why is this needed?
When setting a cookie for a particular name/domain, if a cookie without a prepended period already exists in the browser then a second cookie with the same name will be created. This results in the browser having two cookies with the same name when the web application only expects one.

**Comment by Spea** [comment]
@jennifer-shehane Is this something you consider adding? Can I somehow help with implementing this feature?

**Comment by Donaab** [comment]
Hi ... Is there any workaround that we can use until this is fixed?

**Comment by Askarov5** [comment]
Are there any updates on this? or a workaround? 
[Unable to set `HttpOnly` flag with javascript](https://stackoverflow.com/questions/14691654/set-a-cookie-to-httponly-via-javascript) blocked me from copying cookies.

**Comment by Kazathur92** [comment]
@Songyu-Wang hi there, you said document.cookie could be used as a workaround. would you mind giving an example of how to do that? I am having the same issue as everyone else with Cypress adding a "." in the beginning of my cookie domain. :(

**Comment by garyantoriano** [comment]
> 
Hi @Kazathur92, you can find more information about the document.cookie api at the following link: _https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie_
Basically if you use: **document.cookie = "cookieName=cookieValue"**, it will set a cookie with its name as 'cookieName' and its value as 'cookieValue', and the **domain name** will be the host portion of the current document location.
So the additional dot character will only be added if you explicity include the domain name, ie:
**document.cookie = "cookieName=cookieValue; domain=example.com"**
In my case I also had to set the **'path'** property as **'/'** to resolve my issues, otherwise it'll be the current path of the current document location.
