### ISSUE TITLE
Cypress Component Test Runner - Not all angular unit test specs are executed in Firefox in both open and run mode (open-ct & run-ct) and only first spec is executed and hangs on second spec

### ISSUE THREAD

**Issue by Sathish787** [cypress-io/cypress#16897]
Able to execute all angular unit test specs in Electron, Chrome and Edge successfully but with Firefox, after first spec executed successfully it hangs on second spec and on rest of specs.

From screenshot, you could see first spec had nine tests executed successfully but hangs on first test of second spec and further execution. Need to close browser. This happens in both open and run mode (open-ct and run-ct).

![Firefox-cypress unit](https://user-images.githubusercontent.com/22374311/121564522-86bc9180-c9e9-11eb-8005-d2182a2d9f53.jpg)

Angular unit test suite is not complex and it is very simple as below: 

```js
describe('Edit Save Button Component Tests', () => {
  const editSaveComponent = new EditSaveButtonComponentPage();
  let fixture: ComponentFixture<EditSaveButtonComponent>;

  beforeEach(() => {
    setConfig({ stylesheets: ['./cypress/support/styles/style.css'] });
    initEnv({
      imports: [
        EditSaveButtonModule,
        BrowserAnimationsModule,
        TranslateTestingModule.withTranslations('en', translation),
      ],
    });    
  });

  afterEach(() => {
    fixture.destroy();
  });

  it('Should display Cancel and Save button when value (Edit Mode) is true', () => {
    fixture = mount(EditSaveButtonComponent, { value: true });
    fixture.autoDetectChanges();
    editSaveComponent.cancelButton().should('be.visible');
    editSaveComponent.saveButton().should('be.visible');
  });
```

**Comment by LeJeanbono** [comment]
Hi @Sathish787, can you give us your Firefox version ?

**Comment by LeJeanbono** [comment]
Fine for me with `FF 89.0 (64 bits)`

**Comment by Sathish787** [comment]
I tried in both Firefox 88 and 89.0 (64 bits) and Cypress version 7.4.0 and 7.5.0.

But no luck.

**Comment by kod-raj** [comment]
@Sathish787  - Please let me also know if you come across any solution regarding firefox. Thank you

**Comment by JessicaSachs** [comment]
@Sathish787 we need a repo reproduction. Could you add one, please?

**Comment by ZachJW34** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Check out Cypress Angular CT testing, which is now officially supported in 10.4 of Cypress!

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
