### ISSUE TITLE
Updated value not getting reflected when updated inside the window().then() block

### ISSUE THREAD

**Issue by suniljaiswal01** [cypress-io/cypress#16918]
### Current behavior
variable Value updated inside an window().then() block does not reflect outside the block

### Desired behavior
Updated variable value should get reflected to the outside block

### Test code to reproduce
```js
describe('Varibale Update Test', () => {

    it('Window block test', () => {

        var tempval = "oldValue"
        cy.log("Before Window block:" + tempval)
        cy.window().then(window => {
            tempval = "newValue"
            cy.log('InSide Window Block:' + tempval)
        })
        cy.log("After Window block:" + tempval)
    })
})
```

Output:
![image](https://user-images.githubusercontent.com/45997477/121845631-5d5e7700-cd03-11eb-8d73-15a52e375610.png)

### Versions

Cypress Version: 7.4.0
Browser: Chrome/Firefox/Electron/Edge
Operating System: Windows 10

**Comment by jennifer-shehane** [comment]
The tempval in the last `cy.log()` is evaluated immediately in this situation, so it wouldn't reflect the new value. This is expected behavior. 

I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code).
