### ISSUE TITLE
cy.visit() failed trying to load on Vue App

### ISSUE THREAD

**Issue by Ruinevo** [cypress-io/cypress#16983]
I'm trying to run test in my vue-cli app
![image](https://user-images.githubusercontent.com/25858845/122415567-76845380-cfa1-11eb-8c96-3c9a05b6f348.png)

yarn add --dev cypress @cypress/vue @cypress/webpack-dev-server html-webpack-plugin@4

After this I change my cypress/plugins/index.js file with this code :

![image](https://user-images.githubusercontent.com/25858845/122415656-8a2fba00-cfa1-11eb-875b-29dd483f3877.png)

And yarn cypress open-ct

![image](https://user-images.githubusercontent.com/25858845/122416061-dd097180-cfa1-11eb-9045-8244a3ad5781.png)

but i am getting error

![image](https://user-images.githubusercontent.com/25858845/122415824-aaf80f80-cfa1-11eb-865e-db688c314919.png)

Download method
 yarn 1.22.10

Operating System
 Windows

Other
"cypress": "^7.5.0",
"@cypress/vue": "^2.2.3"
"@cypress/webpack-dev-server": "^1.3.1"

**Comment by elevatebart** [comment]
Hello @Runinevo

I did not see your issue here before now and I apologize for that.
In component testing `cy.visit()` will never work.

In principle, component testing is different from E2E in this:
Instead of going to test your component by asking you to load your own server, it creates a server for you and helps you load your components in it.

Instead of having this code for testing the `wizard` component:

```js
it('should look like a wizard', () => {
  cy.visit("http://localhost:3000/wizard.html")
})
```

... we would have this kind of test.

```js
import { mount } from "@cypress/vue"
import Wizard from "@components/Wizard.vue"

it('should look like a wizard', () => {
  mount(Wizard)
})
```

I hope this helps. If it does, please close the issue.

**Comment by elevatebart** [comment]
It would be nice of us too to improve the error message in `cy.visit()`
