### ISSUE TITLE
Request for a global beforeAll hook that loads the application only once before all the tests run

### ISSUE THREAD

**Issue by ajinkyashukla29dj** [cypress-io/cypress#17094]
### What would you like?
I would like to have a new global hook that is executed only once before all the tests run. This hook loads the application being tested only once. Each of the `.spec` that runs subsequently should not load the whole application from scratch.

### Why is this needed?
The application that I am testing has several `.spec` files. Each of the `.spec` file loads a different route of the SPA application in the `before` hook using the `cy.visit` command. The application makes a number of network calls to fetch the data. Every time a new `.spec` file gets executed while running `cy:run`, all the network calls are made again and that really increases the load on our backend systems causing it to throttle the requests. We can certainly scale up the back end system to handle the requests while testing but that that does not seem to be the way the application is used by the users. The application should only be loaded once before all the tests run and so the subsequent navigation in each of the `.spec` file does not make all the network requests to fetch data. There needs to be a global hook maybe in `support/index.js` where we can load the application only once before all the tests and not having to use `cy.visit` command in the `before` hook of the `.spec` file.  If we use `before` hook in `support/index`, it get executed before each of the `.spec` file runs. Mocha has a `beforeAll` hook but it seems that does not work in `support/index.js`. This can really speed up the testing process since each of the `.spec` will not load the application again. It will also decrease the load on the backend systems.

**Comment by jennifer-shehane** [comment]
This situation should be addressed with our new Sessions API which is in the final stages of work. https://github.com/cypress-io/cypress/issues/8301

**Comment by ajinkyashukla29dj** [comment]
Thanks for the update @jennifer-shehane

**Comment by jennifer-shehane** [comment]
So, thinking more through this, I actually dont' think this will solve the issue with the many requests + backend overloaded. Cypress will actually be enforcing a clean state before each test is run even more in the future, so this will likely mean you'd have to update the necessary load for the backend requests. 

I'm not totally understanding why this would result in throttling if you are visiting before each spec. Are you running in parallel so that all the specs requests for every spec go out at once? Seems like it would go at the same speed a user could if it's being visiting once per spec.

**Comment by ajinkyashukla29dj** [comment]
The application that is  being tested is somewhat SPA  and some of the requests that the client makes happen only once during the lifecycle of the application. The client then caches the response of these requests so that the it need not reissue these requests when the client or the user navigate to different parts of the application. Now, the approach that Cypress takes of enforcing a clean state as you mentioned before every `.spec` file is run, causes it to reissue these requests which would not happen if the user were to navigate the same route. So with the approach that Cypress tests it, the application really behaves like ten different users loading it than one user navigating to ten different routes of the application.

**Comment by jennifer-shehane** [comment]
>The client then caches the response of these requests so that the it need not reissue these requests when the client or the user navigate to different parts of the application.

@ajinkyashukla29dj How is this 'caching' occurring? Depending on the mechanism used for this, our sessions work may help.

**Comment by cowboy** [comment]
If you're retrieving and storing any once-during-the-lifecycle data in `localStorage` as part of the login process (or whenever it's missing from `localStorage`), then the new session API will be able to cache it so that it can be restored before each test runs. This approach is ideal, because it guarantees that no state from a previous test can possibly be left over at the start of each test, resulting in less flake, and thus higher confidence that tests do exactly what is expected.

If that once-during-the-lifecycle data is _not_ being stored in `localStorage`, whenever an already-logged-in user visits any route of the app, it will need to re-fetch that data—even though it hasn't changed—because it hasn't been cached on the client in a persistent way. This approach might work just fine when the entire user journey starts with logging in and ends with logging out, but in my experience, most app users don't explicitly log out, and many users bookmark pages, open pages in new tabs, or share page links with others, resulting in a user journey that doesn't begin with logging in. It's a good practice to consider those user journeys and build apps that cache once-during-the-lifecycle data in `localStorage`, thus reducing network requests, load on servers, and the load time of the app.

**Comment by cowboy** [comment]
And, just to be clear, please note that I'm not suggesting you store _all_ your app data inside `localStorage`. Just the once-during-the-lifecycle data, which is usually data like the user id, jwt, auth token, etc. Things that can be used to identify the user or their session that can _never_ change.

**Comment by ajinkyashukla29dj** [comment]
We use an Apollo client  that provides a in memory cache to store the query response. You can find more details here https://www.apollographql.com/docs/react/caching/cache-configuration/

**Comment by cowboy** [comment]
> We use an Apollo client that provides a in memory cache to store the query response. You can find more details here https://www.apollographql.com/docs/react/caching/cache-configuration/

If network requests or server load are a known issue, you may want to consider using something like [apollo-cache-persist](https://github.com/apollographql/apollo-cache-persist) to persist cached data, so that your app will make less network requests.

**Comment by cowboy** [comment]
Also, you could use the [`cy.intercept`](https://docs.cypress.io/api/commands/intercept) API to [mock GraphQL queries](https://docs.cypress.io/guides/testing-strategies/working-with-graphql) so that, instead of making a network request at the start of each test, you could just use a fixture.

**Comment by ajinkyashukla29dj** [comment]
I am going to try some of the approaches mentioned  here such as using the `apollo-cache-persist` or `sessions` api. Meanwhile if there is any plan from Cypress team to address similar issues at a low level, please keep me posted here. Thanks

**Comment by jennifer-shehane** [comment]
Thanks for taking the time to explain the feature you'd like. 

Our team has decided that adding this feature is not currently within our scope of feature work as we're moving towards implementing a Sessions API and enforcing state to not carry over from test to test. 

We will be closing this issue, but keeping it open for comments (which we do read). We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
