### ISSUE TITLE
[@cypress/react] window.location.replace() method call in a component breaks cypress-ct runner

### ISSUE THREAD

**Issue by denis-domanskii** [cypress-io/cypress#17117]
### Current behavior
When the React component under test use `window.location.replace()` method - all following cases in current and other describe/context blocks don't work. Seems that the href is not restored after the tests' end. 

### Desired behavior
The environment should be restored after the test ends. 

### Test code to reproduce
Please see the following repo: https://github.com/denis-domanskii/cypress-react-template . 
Run `yarn & yarn cypress open-ct` to run the example.

`App` component has a button, which calls `window.location.replace()` on click:
https://github.com/denis-domanskii/cypress-react-template/blob/master/src/App.tsx#L31

The component test mounts the component and clicks the button. Href assertion works well, but the following `it` block fails (see the screenshot):
https://github.com/denis-domanskii/cypress-react-template/blob/master/src/App.spec.tsx#L12

![image](https://user-images.githubusercontent.com/61494460/123405217-4563de80-d5b2-11eb-9853-39f6ba7a63f6.png)

### Versions
```
"@cypress/react": "^5.9.1,
"@cypress/webpack-dev-server": "^1.4.0",
"cypress": "^7.6.0",
```

**Comment by jennifer-shehane** [comment]
I can recreate this behavior from the given example.

**Comment by JessicaSachs** [comment]
You can't test multi-page navigation with component testing because the spec file is in the same iframe as your app code. If you navigate away from the page, you lose your spec file.

I don't think we'll add support for this because we can't intercept or prevent document.location from navigating. If you have other suggestions let me know.

But, your use case is valid and common... how do you actually test that your button is trying to navigate, without causing your tests to break? This is one of those cases where your best bet is to refactor your app a little bit to make it testable.

If you were using a router, you could use an abstract/in-memory/history router to check that your route changes were working without navigating the page. Putting a router or another mock-able layer in-between your component and `document.location` navigation will allow you to prevent your code from calling a **real**  navigation.

If you have ideas for how we can prevent document.location navigation, let me know. I'll leave this issue open for now.
