### ISSUE TITLE
I'm not able to pay with SEPA anymore

### ISSUE THREAD

**Issue by bsvenson** [cypress-io/cypress#17157]
Hi,

I used to have some automated tests that use the payment method SEPA(twikey).
We don't know exactly when but we notice yesterday that the tests were failing.
We're always getting this page 
![image](https://user-images.githubusercontent.com/45208517/123963289-9ad52c80-d9b2-11eb-9399-f15844dd29a8.png)

Manual tests I can proceed correctly to the payment.
Is it on cypress side or could be SEPA blocking automated tests?

Thank you in advance for your attention.

**Comment by jennifer-shehane** [comment]
@bsvenson I would suggest tracking down what changed between this test passing and the test now failing. It could be any number of reasons. Was it a Cypress update? Because if not then it's unlikely the cause is Cypress itself. 

Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by vdechef** [comment]
@BDQover this just saved my life !

I have an OIDC auth server running on _auth.mydomain.lan_, and making multiple redirections for login page. I did not understand why the cookies were not sent in the browser requests. It took me quite a while to detect that the cookies set by auth server where missing `SameSite` attribute. And thanks to your workaround, the cookies are now send to the server, and I am able to test my login page with Cypress.

```javascript
cy.intercept('**', { hostname: 'auth.mydomain.lan' }, req => {
    req.continue(resp => {
        const cookies = resp.headers['set-cookie']
        if (cookies && cookies.length) {
            const newkies = []
            for (const cookie of cookies) {
                newkies.push(`${cookie}; SameSite=None`)
            }
            resp.headers['set-cookie'] = newkies
        }
    })
})

cy.visit("/") // http://localhost:8080/
```

**Comment by jennifer-shehane** [comment]
Thanks for the report, and for the detailed diagnosis. You correctly identified this as a SameSite cookie issue. On the older Cypress version where this was filed, cross-site cookies sent with SameSite=Lax (or no SameSite, which defaults to Lax) weren’t carried across redirects the way a real top-level browser navigation would, so the payment provider’s session cookie went missing.

This was addressed by the cookie-handling rewrite in Cypress 12, which introduced a server-side cookie jar that tracks same-site context and applies SameSite=Lax cookies on cross-site navigations to match real browser behavior (see #19800, fixed). The manual Lax → None cy.intercept workaround should no longer be necessary.

Since this predates that work and there’s no reproduction on a current version, I’m going to close this out. 

If you’re still seeing missing cookies on the latest Cypress, particularly inside cy.origin, please open a new issue with a reproducible example. Thanks! 🙏
