### ISSUE TITLE
Cypress 7. Component tests. File limit reached error is shown on CI

### ISSUE THREAD

**Issue by pashidlos** [cypress-io/cypress#17173]
### Current behavior
Since we upgraded to version 7.4.0 from 6.2.1 this warning is shown
On some VMs it's even failing with error, I guess it's depending on some system configuration 
`Error: ENOSPC: System limit for number of file watchers reached, watch 'cypress/component'`
https://github.com/Visual-Regression-Tracker/frontend/runs/2961008538#step:4:191

seems like webpack 5 config  issue
should we even watch files during `run-ct`?

### Test code to reproduce
https://github.com/Visual-Regression-Tracker/frontend

### Versions
Cypress 7.4.0

**Comment by Asharma86** [comment]
@pashidlos, @jennifer-shehane , this is happening for my team as well and I commented on a closed issue so this comment is to connect both issues. 

https://github.com/cypress-io/cypress/issues/6960#issuecomment-884197117

cc: @adi518, @sterling, @ckxddd0324, @jakub-bao

**Comment by adi518** [comment]
I ended up downgrading and running it with the command above and it worked.

**Comment by andrico1234** [comment]
I'm having a similar issue, 

Even with `"watchForFileChanges": false,` set in the cypress.json, running `"yarn cypress run --record --ci-build-id #{Build.BuildNumber}# --group '#{Build.DefinitionName}#'"` in our CI pipeline throws the same warnings and errors that @pashidlos shared.

**Comment by Asharma86** [comment]
> I ended up downgrading and running it with the command above and it worked. Cypress clearly has a bug somewhere. I'd close this issue to avoid duplication though.

Thanks @adi518 for sharing the workaround - it worked for me. Hope Cypress can update us here once it is fixed. 

cc: @jennifer-shehane

**Comment by ckxddd0324** [comment]
> @pashidlos, @jennifer-shehane , this is happening for my team as well and I commented on a closed issue so this comment is to connect both issues.
> 
> [#6960 (comment)](https://github.com/cypress-io/cypress/issues/6960#issuecomment-884197117)
> 
> cc: @adi518, @sterling, @ckxddd0324, @jakub-bao

Thanks for tagging me this! Hope Cypress can solve this with a quick hot-fix

**Comment by elevatebart** [comment]
@adi518 
Thanks for the workaround, it seems to have saved a few headaches :D .

I am trying to get together that quick fix you guys are hoping for.
I need to get a minimum reproduction together.

Do you mind sharing (probably again) the command you are talking about?
Can you share (again too) what version you downgraded from (with issue) and back to (no issue)?

Thank you for your help!

**Comment by elevatebart** [comment]
Here is the lines in cypress that trigger a watcher (that I have found).

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/open_project.js#L273
https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/project-base.ts#L522
https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/project-base.ts#L475
https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/specs-store.ts#L66

I hope we can use it to track the faulty watcher and fix it.

**Comment by elevatebart** [comment]
One more thing I need for all of you here:

Can you share the contents of your pluginsFile and supportFile please?
That will help a lot. 

Thank you again

**Comment by lmiller1990** [comment]
I am looking into this issue. I tried various projects on both a beefy macOS running docker and a medicore linux desktop but had no luck reproducing it.

Seems to be a CI only problem - likely owning to a lack of resources, incurred by docker and/or generally under powered CI machines. I think there is no one issue here, but several over time.

[berviantoleo/react-multi-crop](https://github.com/berviantoleo/react-multi-crop) is one easy to reproduce use case, I'll start there. Seems something was introduced between 7.6.0 and 7.7.0 that pushed things over the edge.

Cypress 7.6.0 passes: https://github.com/lmiller1990/react-multi-crop/runs/3168029365?check_suite_focus=true#step:7:56
Cypress 7.7.0 fails: https://github.com/lmiller1990/react-multi-crop/runs/3168051830?check_suite_focus=true#step:7:56

Luckily 7.6.0 -> 7.7.0 is not that big a diff: https://github.com/cypress-io/cypress/compare/v7.6.0...v7.7.0

The original issue post is an upgrade from 6.2.1 -> 7.4.0, which is a huge surface area to investigate. Next steps there would be gradually upgrading each minor version and figuring out where that problem was introduced.

**Comment by lmiller1990** [comment]
Here are my findings. I used the [react-multi-crop](https://github.com/lmiller1990/react-multi-crop) from @berviantoleo ([see this comment](https://github.com/cypress-io/cypress/issues/6960#issuecomment-876329535)) to test and debug, since it consistently exhibits the file limit error on 7.7.0, but works fine on 7.6.0.

Firstly, I ran the same pipeline on both GH Actions and CircleCI - this problem only manifests on GH Actions, which in my experience, have less powerful machines than CircleCI. Is everyone experiencing this problem on **GH Actions**, or locally? If you are experiencing it locally, are you running in docker? I'm trying to narrow the problem down, I suspect it's a docker (or a docker-in-github-actions) problem. @pashidlos @ckxddd0324 @Asharma86 @andrico1234.

Anyway, I found that [this line is the problem](https://github.com/cypress-io/cypress/compare/v7.6.0...v7.7.0#diff-a062d0b0db7bfd6f4a0d1785e9d83ee00e169d21dbb2cdcf7107ed0fab857e6aR252), at least in the `react-multi-crop` example. Between 7.6.0 and 7.7.0, I removed a check which causes an additional spec watcher to start in E2E mode. Also, this watcher should not start in `cypress run`, only `cypress open`, [so I made a PR fixing that](https://github.com/cypress-io/cypress/pull/17494).

Seems this is a problem for @pashidlos in `7.4.0`, so likely this won't solve everyone's problems, but it's a good start.

I found around work-around might be useful. Ultimately, the problem is watching too many files. [Here's some more information i found regarding GH Actions, docker and watching files](https://github.community/t/increase-watchers-in-github-workflow-when-running-from-a-docker-image/16691). To watch less files with `chokidar` (which is what Cypress, and basically every other Node.js based tool uses) we can use the [`usePolling` option](https://github.com/paulmillr/chokidar#performance). It fixes the problem in the `react-multi-crop` example.

- Failing with Cypress 7.7.0, `CHOKIDAR_USEPOLLING: 0` (default is 0)
https://github.com/lmiller1990/react-multi-crop/runs/3168834559?check_suite_focus=true#step:7:56

- Passing with Cypress 7.7.0, `CHOKIDAR_USEPOLLING: 1`
https://github.com/lmiller1990/react-multi-crop/runs/3168920083?check_suite_focus=true#step:7:113

Here's how you can use the `CHOKIDAR_USEPOLLING: 1` option: https://github.com/lmiller1990/react-multi-crop/commit/9ad840a175ec58c3c127f552b52a9a94d051d64b

**Comment by pashidlos** [comment]
@lmiller1990 thanks for extensive description!

first time I discovered this issue with `7.4.0` running inside docker on internal company CI (TeamCity) and we were managed to solve that (I guess  as described [here](https://stackoverflow.com/questions/55763428/react-native-error-enospc-system-limit-for-number-of-file-watchers-reached))
so unfortunately I could not reproduce it anymore with `7.4.0`
those were the logs 
```
[10:15:06]Status: Downloaded newer image for cypress/included:7.4.0
[10:15:06]docker.io/cypress/included:7.4.0
[10:15:12]ℹ ｢wds｣: Project is running at http://localhost:34898/webpack-dev-server/
[10:15:12]ℹ ｢wds｣: webpack output is served from /__cypress/src
[10:15:12]ℹ ｢wds｣: Content not from webpack is served from /opt/buildAgent/work/4f81f6d47f6aa03/client
[10:15:13]Error: ENOSPC: System limit for number of file watchers reached, watch 'cypress/component/CreatePaymentPage.cy-spec.tsx'
[10:15:13]    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
[10:15:13]    at Object.watch (fs.js:1525:34)
[10:15:13]    at createFsWatchInstance (/root/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server-ct/node_modules/chokidar/lib/nodefs-handler.js:116:15)
[10:15:13]    at setFsWatchListener (/root/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server-ct/node_modules/chokidar/lib/nodefs-handler.js:163:15)
[10:15:13]    at NodeFsHandler._watchWithNodeFs (/root/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server-ct/node_modules/chokidar/lib/nodefs-handler.js:325:14)
[10:15:13]    at NodeFsHandler._handleFile (/root/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server-ct/node_modules/chokidar/lib/nodefs-handler.js:355:23)
[10:15:13]    at NodeFsHandler._addToNodeFs (/root/.cache/Cypress/7.4.0/Cypress/resources/app/packages/server-ct/node_modules/chokidar/lib/nodefs-handler.js:617:21)
[10:15:13] {
[10:15:13]  errno: -28,
[10:15:13]  syscall: 'watch',
[10:15:13]  code: 'ENOSPC',
[10:15:13]  path: 'cypress/component/CreatePaymentPage.cy-spec.tsx',
[10:15:13]  filename: 'cypress/component/CreatePaymentPage.cy-spec.tsx'
[10:15:13]}
```

the second time it was on `GH Actions` with `7.6.0`
and it's fixed with your workaround

**Comment by ckxddd0324** [comment]
@lmiller1990 Thanks for looking into this issue. I am not able to create this locally, only seeing this issue with Github action

**Comment by lmiller1990** [comment]
Please wait for the next release and see if that fixes your problem. In the meantime, you could try the `CHOKIDAR` work around. I'd say using the dashboard is not relevant here, I think the problem is related to the CI provider.

**Comment by berviantoleo** [comment]
I've upgraded to 8.1.0, seems good for now.

https://github.com/berviantoleo/react-multi-crop/runs/3207210368?check_suite_focus=true

**Comment by aomaryus** [comment]
Testing 8.1.0 now

**Comment by aomaryus** [comment]
Worked...

**Comment by lmiller1990** [comment]
Seems like this is fixed.

If it comes up again or in another context, please make a new issue! Thanks team.
