### ISSUE TITLE
Cypress is not executing the click command

### ISSUE THREAD

**Issue by talaamin** [cypress-io/cypress#17194]
**Bug description:**
When I click on "send" button for a form without filling any field, error messages should show. However, cypress is not executing the click command and is not showing the error messages.

**Steps to reproduce using cypress:**
- Go to https://www.seleniumeasy.com/test/input-form-demo.html
- Click on Send button.

**Expected result:**
Error messages for the mandatory fields should show.
**Actual result**
Error messages are not showing.

**Environment:**
Cypress version 7.6.0
Chrome version: [91]

(![cypress click](https://user-images.githubusercontent.com/76010372/124442187-266d0580-dd85-11eb-96be-7eaa111c54d8.PNG))

Note: Cypress shows the click command as passed, but it is not actually executed

**Comment by jennifer-shehane** [comment]
Looks like this is caused by the bootstrapValidator not being a function on the form. These resources don't seem to be loading beecause of this mixed content warning. 

I'm not sure why this is only happening in Cypress. These resources should be served over https though.

<img width="1470" alt="Screen Shot 2021-07-06 at 4 09 31 PM" src="https://user-images.githubusercontent.com/1271364/124667120-973f1b00-de74-11eb-83b8-e53a97a4c229.png">

**Comment by talaamin** [comment]
Any updates on this?
