### ISSUE TITLE
Cypress update from 6.5.0 -> 7.7.0 tests are slower by a lot

### ISSUE THREAD

**Issue by NikolasNelson** [cypress-io/cypress#17276]
### Current behavior
cypress version 6.5.0
tests run 25min 

updated cypress to version 7.7.0
same tests run 1h 44m 

just in Jenkins CI on local pc it's ok same as before.

when I switch video recording off it's much faster

### Desired behavior
Same time to run test as in version 6.5.0

### Versions
6.5.0
7.7.0

**Comment by jennifer-shehane** [comment]
There were some performance issues that were introduced in 7.0 that we intend to address in 8.0 (our next planned release).

If you're running Cypress in a headless browser, the default screen size was increased to 1920x1080 which could introduce extra time. We suggest reducing the screen size to the default size prior to 7.0 (1280x720) to help with performance in the meantime. [Instructions here.](https://on.cypress.io/browser-launch-api#Set-screen-size-when-running-headless) This will be fixed in 8.0.

There is also a much  higher performance hit when tests are run on low resourced machines (CPU/memory). This will happen normally, but the effect is greater with  the newer screen size increases. 

We recommend running your tests on a local, high resourced machine (like a Mac) and comparing the test runtime against the runtime in your CI machine. If CI  runtime is significantly slower, your machine in CI needs more resources to  run performantly and we suggest updating those. 

Closing as this is being addressed in other upcoming issues.
