### ISSUE TITLE
Corrupted video recording

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#17290]
### Current behavior

I had multiple encounter with generated video being corrupted, see screenshot: 

![image](https://user-images.githubusercontent.com/36670132/125345087-f2598d80-e30c-11eb-86fd-d18b2a6cd339.png)

Or being laggy (Sorry, cant provide a clip for that because the software I am working on is not open sourced)

### Desired behavior

have reasonable video generation success rate

### Test code to reproduce

This only happens once in a while, I cannot find a way to stably reproduce it. Maybe someone who experienced the same thing can comment here. 

We are using `xvfb-run --server-args="-screen 0 1440x900x24 -ac +extension RANDR"`
with config `"numTestsKeptInMemory": 1`
with `launchOptions.args.push('--window-size=1920,1080');`
on environment `aws linux 2 m5.2xlarge` and `docker 20.10.4`

### Cypress Version

7.3.0 (did not update to the newest because I went through changelog, only found #16648 is video related, but I dont think it has anything to do here)

**Comment by jennifer-shehane** [comment]
Generally we've found that when there are laggy/frozen videos, it is due to the machine not having enough resources (CPU/memory) to run Cypress and record video. 

You can log the memory and CPU usage of Cypress by following these instructions: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage This will help determine if Cypress is running out of resources and whether the machine requires more.

Larger video also requires more resources, so increasing the screensize means larger video = more resources required.

**Comment by Songyu-Wang** [comment]
@jennifer-shehane Thank you for your replies! Somehow I cant get the cypress debug to work, but I just used an `top` script and got the information. 
Yes, you are right, The CPU is working at around 200% which is probably the issue. 
Closing this now.
