### ISSUE TITLE
"this" context doesn't work as expected in one of my repos

### ISSUE THREAD

**Issue by jakubondracek** [cypress-io/cypress#17300]
### Current behavior

For one of my tests, I'd like to store some data in "this" context. I initialise my variable in beforeEach cycle and try to access it within "it" cycle. For some reason, in this particular repo, it doesn't work as I would expect (and as it works in my other repos). If I force the test to go through another cycle and then try to access "this.variable" in its callback, the functionality works again.

Steps to reproduce:
1. launch test spec from my repo
2. Observe that first test passes
2. observe that second test fails even though the "cy.log()" is in another cycle

### Desired behavior

Variable that is defined and stored in beforeEach cycle should be accessible in the it cycle.

### Test code to reproduce

https://github.com/jakubondracek/cypressThisContextBug

### Cypress Version

7.5.0

### Other

This also works without a problem in my other repo, that is using cypress 6.9.1

**Comment by bahmutov** [comment]
This happens because you overwrite `it` global function but fail to preserve the context by using `=>` instead of function syntax.

```js
const origIt = window.it
window.it = (title, func) => {
  origIt(title, func && (() => itCallback(func)))
}
window.it.only = (title, func) => {
  origIt.only(title, func && (() => itCallback(func)))
}
window.it.skip = (title, func) => {
  origIt.skip(title, func)
}
```

You should use the `function` syntax and be careful how you call the overwritten functions, similar to https://github.com/cypress-io/cypress-grep/blob/main/src/support.js#L44

**Comment by jakubondracek** [comment]
Hi Gleb and thanks for the answer.

I'm aware of difference between "() => {}" and "function() {}" usage and I do follow it in my example.

```javascript
describe('TC2: Unpublished content', () => {
  beforeEach(function () {
    this.testArray = ['value123']
  })
  it('This works', function () {
    cy.get('body').then(function () {
      cy.log(this.testArray)
    })
  })

  it("this doesn't work", function () {
    cy.log(this.testArray)
  })
})
```

This is an acutal test case from my other repo where this logic works flawlessly. "this.testName" array is defined within "cy.loginAndPrepareTestData()"

```javascript
describe('tasksSuite', () => {
  beforeEach(function () {
    cy.loginAndPrepareTestData()
  })

it('deleteATaskFromTasks', function () {
    const swaggerData = {
      method: 'GET',
      baseUrl: Cypress.env('url'),
      endpointParams: {
        tenant: Cypress.env('tenantId'),
        endpoint: 'task'
      }
    }
    cy.fixture(this.testName[1]).then((testData) => {
...
```

Also, the exact same logic from my first example works when tried in cypress-test-tiny with the same version. Is it possible that the problem is caused by some combination of other npm packages? I'm unsure how to debug further...

**Comment by bahmutov** [comment]
The problem is not in the test file itself but in the support file where you have overwritten the global it function incorrectly

**Comment by jakubondracek** [comment]
I have now realised what you meant with the first comment. Srry for being thick-headed and thanks for the resolve.

**Comment by ondracja** [comment]
Hi @MikeMcC399,

The issue I actually had was caused by globally overwritting a fucntion so there really wasn't any issue at all with using `this` to pass some values.

I'm not sure what your exact use case is but generally, I used `this` context to pass info from `beforeEach` hook into the test itself and then further into `afterEach` hook.

If you take a look at this example, you can see that I have stored an array in `this` and later accessed it in a different scope.
The only constraint that you have is to `NOT` use lambda functions as they don't share `this` context.

This code was tested on Cypress `9.5.4`

```javascript
describe('Testing this context', () => {
  beforeEach(function () {
    // initializing the array with some data
    this.testArray = ['value123']
    // this returns "['value123']"
    cy.log(this.testArray)
  })
  it('Accessing this', function () {
    // this returns "['value123']"
    cy.log(this.testArray)
  })
})
```

Hope this helps your automation! If not, feel free to reach out and we can discuss it further.

**Comment by MikeMcC399** [comment]
@ondracja 

Your reply is much appreciated! The issue I have is with` it.only` not working, so I think it would be best to post this in a separate discussion for clarity, rather than overloading and hijacking this closed issue. I'll let you know when I've done this, in case there is something you would like to add.

**Comment by MikeMcC399** [comment]
- I have described the problem in the discussion https://github.com/cypress-io/cypress/discussions/23280
