### ISSUE TITLE
Does Cypress has analogue to Selenium's WebElement.isDisplayed?

### ISSUE THREAD

**Issue by b-ponomarenko** [cypress-io/cypress#1737]
In many cases we need to check if element displayed (is visible in viewport). Selenium has method [isDisplayed](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/WebElement.html#isDisplayed--) method for it. Does Cypress has same method or API?

**Comment by chrisbreiding** [comment]
You can use `.should('be.visible')` to test if an element is visible. Note that it doesn't fail if the element is outside the viewport. It's really an assertion for whether the element is visible or could be visible to the user with scrolling. There's some [discussion about that here](https://github.com/cypress-io/cypress/issues/877).

**Comment by brian-mann** [comment]
In Cypress you have native access to everything. We don't need to create commands for everything because you have the entire power of JavaScript at your disposal.

The question could be rephrased: "in javascript how do you detect if an element is visible?". Whatever that answer is is the same for Cypress.

Internally we use quite a few helper methods we created when determining visibility. They are all attached to `Cypress.dom`.

You could try looking at that object and I believe the method you're looking for is in there.

**Comment by b-ponomarenko** [comment]
Thanks
