### ISSUE TITLE
parseSpecialCharSequences not working as intended

### ISSUE THREAD

**Issue by fbonds** [cypress-io/cypress#17393]
### Current behavior

The following code enters 'CVE-d{4}-d{4,7}' in the text field.  If it's truly not parsing the special character sequence, it should instead enter 'CVE-\d{4}-\d{4-7}' in the text field.  
    
```js    
        cy.get('#query')
            .type('CVE-\d{4}-\d{4,7}', {
                parseSpecialCharSequences: false,
              })
            .type('{enter}')
```

In order to get what I intend to happen, I have to escape the "\" by entering them twice

```js
        cy.get('#query')
            .type('CVE-\\d{4}-\\d{4,7}', {
                parseSpecialCharSequences: false,
              })
            .type('{enter}')
```

### Desired behavior

If special character parsing is off, I don't need to escape the "\" to have them type literally. 

### Test code to reproduce

```js
        cy.get('#query')
            .type('CVE-\d{4}-\d{4,7}', {
                parseSpecialCharSequences: false,
              })
            .type('{enter}')
```

### Cypress Version

7.4.0

**Comment by fbonds** [comment]
Apparently I have to escape them here too.  😳   

""s above should be "\\"s

**Comment by jennifer-shehane** [comment]
The `parseSpecialCharSequences` argument will type the `{` or `}` characters as literal instead of interpreting as Cypress special chars.

This other behavior with the `\` character seems very unexpected. I know that jQuery queries have to account for the escaped chars, but I don't see why that should affect our own type command. Likely some method we're running the text througgh is stripping it unknowingly.

**Comment by fbonds** [comment]
Thanks for the clarification. 

The name is a bit misleading as "special characters" generally refer to a greater set of characters than just curly brackets.  If this is intended for just those, perhaps **parseCurlyBrackets** would be clearer?

**Comment by Asac2142** [comment]
Any updates on this? 
I'm unable to find a workaround in order to make cypress type `$k_{el}\\degree$` with double backslah

**Comment by emilyrohrbough** [comment]
@Asac2142 No update. Would you be interesting in contributing a fix for this issue?

**Comment by TimVee** [comment]
[The backslash is an escape character in JavaScript string literals.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#escape_sequences) Just try `'\d'` in the browsers JavaScript console, the resulting string doesn't have the backslash because JavaScript doesn't recognize the `\d` as an escape sequence and interprets it as a literal `d`. 

Backslashes in JavaScript string literals have to be escaped themselves by a preceding backslash. If you want two backslashes, there has to be an extra back slash in front of both of them, so for a string with the contents of `\\`, your literal has to look like this: `'\\\\'`

This is just part of the language, so unless the cypress team wants to create a non-standard js parser, there isn't anything they can do to change the way these strings are interpreted.

**Comment by fbonds** [comment]
Reference https://github.com/cypress-io/cypress/issues/17393#issuecomment-1256214626
