### ISSUE TITLE
Cy.screenshot ignores viewport heights over 720px and widths over 1280px

### ISSUE THREAD

**Issue by JSumner1992** [cypress-io/cypress#17403]
### Current behavior

Since 8.0.0 the screenshots produced are capped at 1280px width and 720px height. This is causing failures in our tests due to doing image diffs which are now a different size compared to the baseline.

### Desired behavior

Cypress should respect the viewport when using screenshot and not cap the screenshot size.

### Test code to reproduce

https://github.com/JSumner1992/cypress-test-tiny

run the tests and inspect the saved images sizes

### Cypress Version

8.0.0

**Comment by jennifer-shehane** [comment]
This is expected behavior and a breaking change of 8.0 as specified in the [Changelog](https://on.cypress.io/changelog#8-0-0) and the [Migration Guide](https://on.cypress.io/migration-guide#Default-screen-size-during-headless) for 8.0. 

The `cy.viewport()` does not set the screen size of the machine. It only sets the viewport of the application for which you are testing.  

![gui-diagram dd71ece copy](https://user-images.githubusercontent.com/1271364/126333195-db1d0e4b-704d-4f18-a9f0-cd25a190118f.png)


If you want to override the screen size of the machine, you can do it by following [these instructions](https://on.cypress.io/browser-launch-api#Set-screen-size-when-running-headless).

**Comment by JSumner1992** [comment]
Oh my bad I thought the screen size was only for the video recordings, didn't realise it was used for the screenshots as well. Thanks for the help.
