### ISSUE TITLE
Unable to finish Installation- Cypress for Jira 

### ISSUE THREAD

**Issue by radhikashashikanth** [cypress-io/cypress#17449]
### Current behavior

![Capture](https://user-images.githubusercontent.com/66630529/126662568-0b8cf19a-79b5-4b43-991d-f5c65862dcda.PNG)
![image](https://user-images.githubusercontent.com/66630529/126662601-2e4e12d3-6283-473e-8cec-83067290830c.png)

When I install cypress for Jira--> click on finish installation--> Select the Organization you want to integrate with jira-->when I click on my Add jira button--> receiving error Oops. There was a problem talking to our servers 

### Cypress Version

7.0

### Package Manager

npm

### Operating system

Windows

### Other

![image](https://user-images.githubusercontent.com/66630529/126662997-796efe21-718e-426e-8d10-7322b9d94787.png)

**Comment by jennifer-shehane** [comment]
@radhikashashikanth Thanks for reaching out about this issue. I've forwarded this to our Dashboard team to investigate and will comment when I have any updates.

**Comment by jennifer-shehane** [comment]
Hey @radhikashashikanth, the integration with Jira is a paid feature, so the installation was unable to finish since the organization you're trying to install within is not subscribed to a paid plan. 

I understand that this error state should be clearer on why the installation can't continue and forwarded this feedback to our Dashboard team for consideration. 

If you'd like to compare the features available per paid plan versus free plans you can see those details on our pricing: https://cypress.io/pricing/ or reach out to support@cypress.io for any inquiries on our plans.

**Comment by radhikashashikanth** [comment]
![image](https://user-images.githubusercontent.com/66630529/126676290-ea827c7c-7e8e-407f-8365-03aa84c3fd64.png)

I am the only user of cypress, website shows my current plan as 0$ since it's below 3 users and less than 500 test results can you please explain what I'm missing here

**Comment by jennifer-shehane** [comment]
@radhikashashikanth Jira Interation is not a feature of a Free plan $0, which is your current plan. You would need to upgrade to one of our paid plans for Jira integration to Cypress to finish installing.

**Comment by radhikashashikanth** [comment]
Thank you

**Comment by radhikashashikanth** [comment]
Is there a free trail for cypress for Jira?

**Comment by jennifer-shehane** [comment]
@radhikashashikanth I would suggest reaching out to support@cypress.io to ask about any trial offerings. I'm not sure if this is available.

**Comment by radhikashashikanth** [comment]
Thank you so much
