### ISSUE TITLE
test:before:run event question

### ISSUE THREAD

**Issue by paulpruteanu** [cypress-io/cypress#1758]
is there any way to obtain the name of the test file when I'm inside `Cypress.on('test:before:run', (attributes, runnable) => {})`?
and more importantly, is there a way to dynamically skip/ unskip tests during `test:before:run` event?

**Comment by Bkucera** [comment]
Since Cypress is using `mocha`, you can see if this will log out the title of each test
```
afterEach(function(){
    console.log(this.currentTest.title)
})
```

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.

**Comment by craigryan** [comment]
Hi, I'm also interested in this. Can you please answer the question if it's possible to dynamically skip the current spec within test:before:run? Can't see anything obvious like a skip() call available from either params. How about via Cypress or cy? Thanks!

This seems like the only possible alternative since cypress-select-tests can't be used when I already have a file:preprocessor registered in plugins.
