### ISSUE TITLE
Improve Uncaught Errors

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#1761]
on `Uncaught Errors`
- if there is no `err.stack`, e.g syntax error,  construct a better error
- if there is a stack, cut out the cypress related lines

![image](https://user-images.githubusercontent.com/14625260/40452378-9e97a392-5eaf-11e8-9d45-9746c1da0c1f.png)

**Comment by mackelito** [comment]
Guess this is the same issue I have... causes tests to fail.

cypress_runner.js:65225 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.appendErrMsg (cypress_runner.js:65225)
    at Object.createUncaughtException (cypress_runner.js:58408)
    at Object.onUncaughtException (cypress_runner.js:61281)
    at onError (cypress_runner.js:60780)

**Comment by benjie** [comment]
I've just spent an hour getting to know Cypress intimately to track down the error I was getting. Spoiler: turns out the error was that electron doesn't currently support optional catch binding in `try` block:

```js
try {
  ...
} catch {
  ...
}
```

The error I was receiving was:

```
Uncaught SyntaxError: Unexpected token {

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
```

This doesn't contain anything useful for tracking down what is causing the error since there's `{`s everywhere!

After much exploration through the devtools I landed here:

![cypress-error](https://user-images.githubusercontent.com/129910/63419894-8494d780-c3fd-11e9-8927-af8f9751619a.png)

This gave me the information I needed - the file, line number and column number of the syntax error! From then it only took a few more seconds to track down the actual syntax incompatibility.

The issue here seems to be that the source, lineno and colno information are being explicitly dropped here:

https://github.com/cypress-io/cypress/blob/55b352a11d0a664517ae054c67432d98abc2389e/packages/driver/src/cy/errors.coffee#L29-L30


https://github.com/cypress-io/cypress/blob/55b352a11d0a664517ae054c67432d98abc2389e/packages/driver/src/cy/errors.coffee#L39-L44

Because the error (argument 5) exists, the other details are discarded, which leads to a less-than-optimal debugging experience.

As far as I can tell, there's no way for me to extract these details with any cypress hooks, for example by the time it hits the `uncaught:exception` hook these details have been dropped (I think?).

**Suggestion**: add `source`, `lineno` and `colno` to the error object and ensure they're in the error message.
