### ISSUE TITLE
Warning about deprecated sub-dep 'uuid' when installing cypress

### ISSUE THREAD

**Issue by dapinto8** [cypress-io/cypress#17622]
### Current behavior

`warning cypress > @cypress/request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.`

### Desired behavior:

No warning

### Cypress Version

8.2.0

### Package Manager

yarn

### Operating system

Linux

**Comment by JessicaSachs** [comment]
@flotwig we should move off of `@cypress/request` since it was [put into maintenance mode](https://github.com/request/request/issues/3142) and won't be accepting any fixes. Thoughts?

**Comment by flotwig** [comment]
@JessicaSachs I agree. We use the fork at https://github.com/cypress-io/request but it is limiting since there's no support for HTTP2, QUIC, retries, etc... It would improve our code base and make the proxy layer faster if we switched to a modern request lib that speaks HTTP/2/3.

Related issue on HTTP/2: https://github.com/cypress-io/cypress/issues/3708

We can avoid this deprecation issue today by upgrading the dep in `@cypress/request`.
