### ISSUE TITLE
Regression: clicking a request in the log no longer displays request/response body

### ISSUE THREAD

**Issue by JessefSpecialisterren** [cypress-io/cypress#17656]
### Current behavior

After updating to Cypress 8.2.0, request and/or response bodies are no longer displayed in the console when clicking on certain requests in the log. Example:

![image](https://user-images.githubusercontent.com/36038882/128722240-6208ff07-e9df-4187-a9da-9c202c6a4e2a.png)

The selected request has both a request body and a response body, but the information displayed in the console suggests that it has neither. Expanding the `XmlHttpRequest` object does show the response body, but not the request body. This is both misleading and inconvenient when examining requests.

Note that this issue does not seem to affect all requests, but those it does affect, it seems to affect consistently.

### Desired behavior

In Cypress 8.1.0, the request and response bodies are clearly shown in the console output:

![image](https://user-images.githubusercontent.com/36038882/128718828-c316d4f5-7245-4fe9-b25a-79733b439e87.png)

### Test code to reproduce

```js
it('', () => {
  cy.visit('http://automationpractice.com/index.php?controller=authentication&back=my-account')
  cy.get('#email_create').type('a@b{enter}')
})
```
When the test has finished, open the console and click the `POST 200 /index.php` request at the bottom of the runner log. Note that I do not own or control this website. It appears to be flaky sometimes; if that happens, please try again after a few minutes.

### Cypress Version

8.2.0

**Comment by Narretz** [comment]
@flotwig any news on this? With fetch, I don't see an option to print the response body at all at the moment (from the cypress ui)

**Comment by flotwig** [comment]
@Narretz Even after this fix, response bodies will only be available for XHRs and requests intercepted with `cy.intercept()`, to match parity with the previously existing functionality.

You are best off using the "Network" tab of the Developer Tools to inspect request/response bodies if your requests do not fit those 2 cases.

Due to how Cypress works, it's a bit of additional work to get the request/response bodies for all requests in the browser. Even with that work being done, there could be a negative performance impact that would have to be debugged. I'm not saying it's not possible or important to add what you're asking for, but just that it's a significant chunk of work to add and it's not part of this fix.

**Comment by Narretz** [comment]
Thanks @flotwig, I didn't realize fetch wasn't logged previously. Still a bit of a bummer that it is still special cased in some circumstances.
