### ISSUE TITLE
URL does not accept parameters

### ISSUE THREAD

**Issue by luisvargasmx** [cypress-io/cypress#17661]
### What would you like?

Trying to visit next web site: http://palig-producer-portal-qa.s3-website-us-east-1.amazonaws.com/new-business?role=superuser
Studio raises next error: Sorry, we could not load: http://palig-producer-portal-qa.s3-website-us-east-1.amazonaws.com/new-business?role=superuser
404 - Not Found (text(html)

And in the test execution window next error raises: Studio cannot add commands to a failing test.

I would like Studio to be able to receive URL with parameters.

### Why is this needed?

My website has different behavior depending on user roles received as URL parameters.
![image](https://user-images.githubusercontent.com/79924911/128772777-78851bcb-8697-45c4-8a97-50eac1748c9b.png)

### Other

Visiting this URL using Cypress Test runner works correctly: http://palig-producer-portal-qa.s3-website-us-east-1.amazonaws.com/new-business?role=superuser.
![image](https://user-images.githubusercontent.com/79924911/128772941-31bfab0e-21f7-4a3a-bd2f-fce6f9c0b4af.png)

**Comment by panzarino** [comment]
@luisvargasmx Does this url work with `cy.visit()`? Studio hooks into that directly and it should support url params properly.

**Comment by luisvargasmx** [comment]
@panzarino: Yes, this URL works with **cy.visit()**:

URL: http://palig-producer-portal-qa.s3-website-us-east-1.amazonaws.com/new-business?role=superuser

Image with evidence:
![image](https://user-images.githubusercontent.com/79924911/129223543-f7968ca3-d74d-43b7-8075-1e14df960a22.png)

**Comment by panzarino** [comment]
So on my end it doesn't work with Studio or with `cy.visit()`. This is because your server is returning a 404 which is registered as an error code. You can fix this by passing `failOnStatusCode: false` to `cy.visit` which it seems like you've been doing in your tests.

One way that we can fix this for Studio is by adding this option by default to visiting in Studio, but this can easily mask a true underlying problem so for most users this would not be beneficial.

Given the url I'm guessing that you're hosting your site on S3 and are pointing the error document to `index.html` so that the routing appears to work properly to the end user (although it still returns a 404). To fix this you can set up CloudFront in front of your bucket (which has many benefits such as enabling https). In CloudFront you can add a custom error page for a 404 error and have it return `index.html` with a 200 status code which should fix this issue (and speed up your load times!)
