### ISSUE TITLE
@cypress/vue component tests add ability to change props after component mount

### ISSUE THREAD

**Issue by freezer278** [cypress-io/cypress#17712]
### What would you like?

Add ability to set props after component is mounted like in vue-test-utils ([setProps method](https://vue-test-utils.vuejs.org/api/wrapper/#setprops))

### Why is this needed?

It would be great to add this ability because now it is impossible to test watchers of component props.

**Comment by JessicaSachs** [comment]
We wrap Vue Test Utils, so you have access to the `setProps` method, though we don't recommend using it.

@freezer278 You have two solutions:
1. You can use your component like you would in your app (Recommended)
2. You can just access the Vue Test Utils wrapper and call `setProps` (Cypress uses VTU under the hood) 

Internally at Cypress, we prefer doing the first option because it gives you interactivity with your component. In my example below, I'm able to manually click on a button to show/hide a modal via its props.

For Vue 3, I actually recommend a JSX syntax with the Composition API (even though we're working in Vue) because it makes the usage look more like you'll use it in the SFC. 

I find that when I want to `setProps` what I **really** want is to try different values in the component (like variants on a Button, etc). Making this input helpers to play around with the props of a component (like a `<select v-model="variant">....</select>`) will let me test out many variants manually while I'm developing.

If you do the version which uses the Vue Test Utils, you won't be able to play around with changing the component's props manually.

### Vue 3 + Composition API + JSX

```jsx
it('renders', () => {
  const show = ref(true)
  const close = () => show.value = false

  mount(() =>
    <div>
      <button onClick={ () => show.value = !show.value } data-testid="toggleButton">
        Toggle Modal
      </button>

      <Modal show={ show.value } onClose={ close }>
        <p data-testid="content">The content for the modal</p>
      </Modal>

    </div>)
    // v-if="true" inside of the modal should show the content
    .get('[data-testid=content]').should('be.visible')

    // The parent component should change show.value to be false
    .get('[data-testid=toggle-button]').click()

    // v-if="false" inside of the modal should not show the content
    .get('[data-testid=content]').should('not.exist')
})
```

### Using Vue Test Utils under the hood

```js
it('renders', () => {
  mount(HelloWorld, {
    // Vue 2 uses propsData, not props
    props: {
      msg: 'Hello World',
    },
  })
    // Cypress Alias
    // But if you don't do this, the VTU wrapper is still accessible via window.Cypress.vueWrapper
    .as('wrapper')

    // Initial value is rendered
    .get('[data-testid=message]')
    .should('have.text', 'Hello World')

    // Grab Vue Test Utils wrapper via Cypress Alias
    .get('@wrapper')

    // wrapper.setProps({ msg: 'Nice' })
    .invoke('setProps', { msg: 'Nice' })

    // New test value
    .get('[data-testid=message]')
    .should('have.text', 'Nice')
})
```

Hope this helps!

**Comment by jcupps** [comment]
FWIW `.as('wrapper')` doesn't seem to work for me as it appears to just return the window object. Here's the type definition:

```javascript
export declare const mount: (component: VueComponent, optionsOrProps?: MountOptionsArgument) => Cypress.Chainable<Cypress.AUTWindow>;
```

**Comment by mateutek** [comment]
> FWIW `.as('wrapper')` doesn't seem to work for me as it appears to just return the window object. Here's the type definition:
> 
> ```js
> export declare const mount: (component: VueComponent, optionsOrProps?: MountOptionsArgument) => Cypress.Chainable<Cypress.AUTWindow>;
> ```

I have the same problem, trying to find a way around this, but so far no results

**Comment by gregveres** [comment]
> 
> I find that when I want to `setProps` what I **really** want is to try different values in the component (like variants on a Button, etc). Making this input helpers to play around with the props of a component (like a `<select v-model="variant">....</select>`) will let me test out many variants manually while I'm developing.

That isn't the use case at all. I would say that for component testing, the reason you really want to have the props change is for a component that sits on the page and reacts to other parts of the system changing.

For instance, I have an announcement banner component that shows zero or more system announcements. When the announcement banner component is displayed, it is given an empty array of announcements from the store. The system then pokes the back end to get the current announcements. When that comes back, the prop of the announcement banner is changed because it was a ref. 
Similarily, when someone adds an announcement, the back end notifies the front end that a new announcement is available and the announcements are loaded in the store and the prop is changed again. 

We need to be able to test that the component properly handles these changes. To do that, the prop has to change mid test.

To help future people googling for this issue, here is a solution that works. It builds on the suggestion of creating a vue() custom command.
I have defined the vue() custom command as the following using typescript:
```
import { VueWrapper } from '@vue/test-utils';
import { ComponentPublicInstance } from 'vue';

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Cypress {
    interface Chainable {
      /**
       * Custom command to return the vue test utils wrapper.
       * @example cy.vue().then(wrapper => ())
       */
      vue(): Chainable<VueWrapper<ComponentPublicInstance>>;
    }
  }
}

export function registerVue() {
  Cypress.Commands.add('vue', () => {
    return cy.wrap(Cypress.vueWrapper);
  });
}
```
I put this in a file called /tests/cypress/support/commands/vue.ts and I import it in my /tests/cypress/support/component.ts

Then to change the props mid test, I do something like this:

```
  it('shows banner when array goes from empty to having one element', () => {
    // start the banner with an empty array
    cy.mount(AnnouncementBanner, {
      props: {
        list: [],
      },
    });

    // make sure that it doesn't render anything (the top level div of the banner has data-cy="banner"
    cy.dataCy('banner').should('not.exist');

   // use vue() to get the vue test utils wrapper
    cy.vue().then((wrapper) => {
      // set the props
      wrapper.setProps({ list: [announcements[0]] });
      // now test that the banner has responded properly
      cy.dataCy('banner').should('exist');
      cy.get('.announce-title').should('contain', announcements[0].title);
    });
  });
```

**Comment by joecacti** [comment]
> That isn't the use case at all. I would say that for component testing, the reason you really want to have the props change is for a component that sits on the page and reacts to other parts of the system changing.

This is the exact reason I finally found this issue.  I have a checkbox component I'm trying to test a model value prop watcher. This component is being used as a filter for items on a dashboard.  When a filter is applied using this checkbox a chip component gets added to the page and the user can click that chip to remove the filter.  

The checkbox is supposed to watch it's model-value for changes and when that component's given value (eg., id) is removed from the model-value which is an array of ids then that checkbox should uncheck.
