### ISSUE TITLE
Onload() function in Cypress

### ISSUE THREAD

**Issue by KARIM-QA** [cypress-io/cypress#17711]
### Current behavior

I'am making an end to end test , i want to use onload() function to load all the elements before execution but error found " Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise. 
how can i fixe this issue ?
Thanks a lot 

![cypress error](https://user-images.githubusercontent.com/85531300/129187019-4d123d57-f7a1-40ef-adfe-c4fabde6c3a5.png)

### Test code to reproduce

const loginpage = new loginPage();

cy.visit("/globalview/login",{ timeout: 50000, 

  onLoad: function(contentWindow){

   cy.log('globalview')
   loginpage.FillEmail("");
   loginpage.FillPassword("");
   loginpage.SubmitLogin();

   }
})

### Cypress Version

8.2.0

**Comment by JessicaSachs** [comment]
You're getting a failure because you can't call `cy` commands from within `onLoad`. Cypress automatically waits for your application to load **before** starting your tests, so using `onLoad` isn't necessary for most tests.

You'll want to use Cypress commands to wrap your Page Object Model. See [this article](https://www.cypress.io/blog/2019/01/03/stop-using-page-objects-and-start-using-app-actions/).

```js
// This causes the failure you're seeing
cy.visit('https://example.cypress.io/todo', {
  timeout: 50000,
  onLoad() {
    cy.log('hello world')
  }
})
```
