### ISSUE TITLE
cy.intercept not intercepting the request

### ISSUE THREAD

**Issue by Pixcell** [cypress-io/cypress#17729]
### Current behavior

The XHR request finishes with `Failed to fetch` even though the request is stubbed in beforeEach. (See screenshot, showing the routes being stubbed on the left, and the failed request in the network inspector)

![image](https://user-images.githubusercontent.com/4005291/129299431-ed51a8e7-da73-465f-ad5f-d9b77dc754ec.png)

***Notes***:

- This is  flaky, re-running the test suite might end in a success.
- The stubbed request is for a domain different than the app

### Desired behavior

Stubbed request should properly return the value they are given as a stub.

### Test code to reproduce

This is the relevant part of the setup.
I am well aware this is not a reproduction but there is no easy way to make a small reproduction.

Any pointers, tips, suggestion is more than welcome. I've been trying to solve this for a while now

````js
const iofogControllerInfo = {
  baseURL: 'http://localhost:51121',
  credentials: {
    username: '',
    password: ''
  }
}

const applications = [{
  name: 'Cypress application',
  id: 1,
  routes: [],
  microservices: [],
  isActivated: true
}]

const microservices = []

const GET_APP_MICROSERVICES = (name) => `/microservices?application=${encodeURIComponent(name)}`


beforeEach(() => {
    //  ... Bunch of other intercepts
    cy.intercept('GET', `${iofogControllerInfo.baseURL}${GET_APP_MICROSERVICES(applications[0].name)}`, { statusCode: 200, body: { microservices } }).as('getMicroservices')
})

````

### Cypress Version

7.9.0 ~ 8.2.0 (Tried them all)

**Comment by Surm4** [comment]
Got the same problem. I use `intercept` and `req.reply` to stub the response and it sometimes succeeds, sometimes not
test preview:
```
    it('edits the code', () => {
      cy.intercept('PATCH', `code/${codeId}`, req => {
        const body = JSON.parse(req.body)

        req.reply({
          ...body,
          id: codeId,
        })
      }).as('codeUpdated')

      cy.get('.monaco-editor').type('my new code')
      cy.get('.codeDialog').contains('Save').click()
      cy.wait('@codeUpdated')

      cy.get('.codeDialog').should('not.exist')
    })
```

**Comment by steve-taylor** [comment]
I was having the same problem before reading about how `cy.intercept` does route matching. You're both using the `url` matcher, which is the default. Read about different route matchers and how to use them here: https://docs.cypress.io/api/commands/intercept

In my case, I had to use the `pathname` matcher because query parameters in request URLs were preventing the match.

Here's an extract from the docs:



Option | Description
-- | --
auth | HTTP Basic Authentication (object with keys username and password)
headers | HTTP request headers (object)
hostname | HTTP request hostname
https | true: only secure (https://) requests, false: only insecure (http://) requests
method | HTTP request method (matches any method by default)
middleware | true: match route first and in defined order, false: match route in reverse order (default)
path | HTTP request path after the hostname, including query parameters
pathname | Like path, but without query parameters
port | HTTP request port(s) (number or Array)
query | Parsed query string (object)
times | Maximum number of times to match (number)
url | Full HTTP request URL

To use the `pathname` matcher, for example, it might look something like this:

```js
cy.intercept({ method: 'GET', pathname: '/api/v1/inbox' }, { fixture: 'inbox.json' })
```

which will match a request with the exact same `pathname`, with or without query parameters.

**Comment by biolds** [comment]
I'm seeing similar behavior on Cypress 8.3.1 (component testing) under Chromium 90.0. The same test of network request interception & stubbing works well when using Firefox 92.0.

**Comment by happycollision** [comment]
Actually, it sure seems to me that the docs are not describing actual behavior for url matching.

From https://docs.cypress.io/api/commands/intercept#Glob-Pattern-Matching-URLs

> Glob pattern matching provides the necessary flexibility:
> ```js
> cy.intercept('/users')
> // matches all of these:
> //   https://prod.cypress.io/users
> //   https://staging.cypress.io/users
> //   http://localhost/users
> 
> cy.intercept('/users?_limit=+(3|5)')
> // matches all of these:
> //   https://prod.cypress.io/users?_limit=3
> //   http://localhost/users?_limit=5
> ```

And the examples in the minimatch section just below show how you can test/debug matches:

> ```js
> // executed in the Test Runner browser console:
> Cypress.minimatch('http://localhost/users?_limit=3', '/users?_limit=+(3|5)')
> // true
> Cypress.minimatch('http://localhost/users?_limit=5', '/users?_limit=+(3|5)')
> // true
> Cypress.minimatch('http://localhost/users?_limit=7', '/users?_limit=+(3|5)')
> // false
> ```

However, if you actually run those in a test...
```js
it("matches things...", () => {
  console.log( Cypress.minimatch( "http://localhost/users?_limit=3", "/users?_limit=+(3|5)" ) )
  console.log( Cypress.minimatch( "http://localhost/users?_limit=5", "/users?_limit=+(3|5)" ) )
  console.log( Cypress.minimatch( "http://localhost/users?_limit=7", "/users?_limit=+(3|5)" ) )
})
```

Every single one is false.

**Comment by christo8989** [comment]
Mine fails because cypress isn't recognizing that the request has returned.

The first test succeeds but then other tests fail.

<img width="267" alt="image" src="https://user-images.githubusercontent.com/1092511/173220503-f92f202a-22ac-4ddd-8e26-6f42e7ac492a.png">
