### ISSUE TITLE
nuxt image module + cypress component testing sharp error

### ISSUE THREAD

**Issue by flozero** [cypress-io/cypress#17742]
### Current behavior

Hello ! I followed this tutorial. https://docs.cypress.io/guides/component-testing/framework-configuration#Nuxt

My current deps:
- @nuxt/image -> 0.5.0
- nuxt: 2.15.7 

When running cypress component testing. Got this first error.
![Screen Shot 2021-08-14 at 7 50 09 PM](https://user-images.githubusercontent.com/11556276/129462834-ce642355-49c9-4798-b5e2-1fe9e0b97356.png)

After install webpack-dev-server. I now have this error.

![Screen Shot 2021-08-14 at 7 51 41 PM](https://user-images.githubusercontent.com/11556276/129462851-10f06e44-58f8-417e-a98f-9f4684679187.png)

I will also post the error on cypress project and refer it here.

### Desired behavior

nuxt + nuxt image + cypress component testing should work

### Test code to reproduce

Following basic tutorial on cypress component testing.

"@cypress/vue": "^2.2.3"
"cypress": "^8.2.0",

### Cypress Version

8.2.0

### Other

Reference to the error:

https://github.com/nuxt/image/issues/387

**Comment by JessicaSachs** [comment]
(Originally responded here https://github.com/nuxt/image/issues/387... duplicating the response here)

I can't get the `sharp` error to happen. The specs compile correctly.

<img width="1376" alt="Screen Shot 2021-08-17 at 9 35 38 PM" src="https://user-images.githubusercontent.com/2801156/129822548-70b347be-5533-4c32-abc4-46bc7549a8a5.png">

RE the first failure: We assumed that Nuxt ships webpack-dev-server, but seemingly it doesn't, so we'll have to support however Nuxt launches its dev server.

I don't think the `sharp` error is a Cypress thing because it works on my machine. My node version is v14.17.0 and I'm on Big Sur. A stab-in-the-dark suggestion is to rm -rf your node_modules so that the native modules rebuild.

**Comment by lmiller1990** [comment]
Need a minimal repro - happy to reopen once we have more info.
