### ISSUE TITLE
Tests run slower when upgrading from Cypress version 6.9.0 to 8.2.0

### ISSUE THREAD

**Issue by Reemalashry** [cypress-io/cypress#17750]
### Current behavior

Tests take 17+ minutes when we upgraded to v8.2.0, they took 7 minutes with version 6.9.0 when I use Cypress run.
This happens when running on CI, with Electron 89 (headless) 

### Desired behavior

Tests should run equally fast with all Cypress versions.

### Test code to reproduce

I can't share the code, but it's a react app with 310 tests so far 😅 

### Cypress Version

8.2.0

### Other

I've tried setting `videoCompression` to 0 to reduce compression quality, and also I've tried disabling video recording altogether, both didn't work and tests are still slow.

**Comment by jennifer-shehane** [comment]
We'll be releasing 8.3.0 today with some performance improvements. So I'd recommend trying that version when it comes out. We've tracked down and fixed a lot of performance issues from 7.0-8.2 from lots of different sources. 

In order to track down the cause we'll need a reproducible example since there are so many variables invovled. Can you provide a more simplified test suite that we can run and compare the timings from 6.9 to 8.2. 

Does this only happen in CI? Do you know the CPU/memory available on your CI? Is the CPU maxing out? You can log the memory and CPU usage of Cypress by following these instructions: https://on.cypress.io/troubleshooting#Log-memory-and-CPU-usage This will help determine if Cypress is running out of resources and whether the machine requires more.

**Comment by Case09** [comment]
Same happens for us also, but it happened before 8.2.0 as well. I think it started after version 7. Yesterday i tried to switch from 6.6.0 to 8.3.0 but it took way too much time that our CI pipeline timed out. I've tried couple of things since:

- Ran cypress in docker container locally and got almost the same execution times as in our CI (in some cases one spec took 19 minutes in 8.3.0, while in v6.6.0 it was 1 minute)
- Checked memory and CPU usage, they were very similar in both 6.6.0 and 8.3.0. Memory was over 90% in both cases. CPU is also similar in both versions, average about 50%.
- Ran single test with `.only` that was way slower in 8.3.0 when running all specs. Got almost same execution times in 6.6.0 and 8.3.0 when running that one test

Some findings after this:

Running single test gives very similar times in both versions so it might not be about how test is written. The issue comes when multiple tests are ran in sequence, and i noticed that after one of them takes a long time, the ones afterwards also take a lot longer to finish.

We do use some custom commands that, amongst other things, wait for element to be available in the DOM (waiting for javascript to load) before executing the rest of the test, which might be connected to this, but seeing other people having this problem and the fact that when running that same test with `./only` i get normal execution times, i'm suspecting something else.

**Comment by ifilatov** [comment]
I've upgraded from 7.7.0 to 8.3.0 (I've ran with --headless in 7.7.0, so nothing changed), and the execution time for all the tests increased for 1.5-3 times (varies for different tests). My application under test is sending a lot of xhr requests, so maybe the fact they are all now rendered in the test log is what's causing the slowness. 
@jennifer-shehane  is it possible to turn off the rendering of all the fetches in test log (left part of the screen)? If so - I can try without them and check if it affects the execution time.

**Comment by GlebkaF** [comment]
I've upgraded from 8.0 to 8.5.0, and the execution time for all the tests increased for 1.5. From 8 to 12 minutes.

**Comment by glomotion** [comment]
just chiming in here. I'm noticing that `8.5.0` is sometimes really choking (lots of timeouts) when our GH actions are under load. 

Tests that run 100% reliably locally, fail 50% of the time in CI right now.  

😭

**Comment by itayod** [comment]
I upgraded from 6.** to 9.4.0 that slowed down my e2e by 70%ish :(
