### ISSUE TITLE
unable open the cypress Run it showing error with latest version that is 8.3.1

### ISSUE THREAD

**Issue by bisht4testing** [cypress-io/cypress#17928]
### Current behavior

unable open the cypress Run it showing error with the latest version that is 8.3.1

please find the below details

Run npx cypress open

```
Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command failed with exit code 2147483651: C:\Users\Singh Bhupal\AppData\Local\Cypress\Cache\8.3.1\Cypress\Cypress.exe --smoke-test --ping=647

----------

Platform: win32 (6.2.9200)
Cypress Version: 8.3.1
```

### Cypress Version

8.3.1

### Package Manager

npm

### Operating system

Windows

### Other

OS windows 8
cypress version 8.3.1
After installing the cypress while going to open the cypress Runner then it showing the below error.
```
It looks like this is your first time using Cypress: 8.3.1


Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command failed with exit code 2147483651: C:\Users\Singh Bhupal\AppData\Local\Cypress\Cache\8.3.1\Cypress\Cypress.exe --smoke-test --ping=522

----------

Platform: win32 (6.2.9200)
Cypress Version: 8.3.1
```

**Comment by samanthakirby** [comment]
I have the same issue. I had to roll back.

**Comment by jennifer-shehane** [comment]
The only thing I can think that could contribute to this is our Electron update, which was a minor update. 

Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by KuleschLars** [comment]
I had the same issue when I start cypress 8.5.0. So I have to roll back to 8.3.0
`It looks like this is your first time using Cypress: 8.5.0


Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command failed with exit code 2147483651: C:\Users\l8975\AppData\Local\Cypress\Cache\8.5.0\Cypress\Cypress.exe --smoke-test --ping=846

----------

Platform: win32 (10.0.19043)
Cypress Version: 8.5.0`

**Comment by ogomez-at-wiris** [comment]
Happens again, 10.1.0.
[trace.txt](https://github.com/cypress-io/cypress/files/8938277/trace.txt)
