### ISSUE TITLE
Buffer.copy is broken in cypress chrome and electron

### ISSUE THREAD

**Issue by factoidforrest** [cypress-io/cypress#17995]
### Current behavior

Buffer.copy copies zero bytes into the destination buffer, and returns `0`.  Works fine in standard chrome.  Absolutely no idea why this would happen in cypress and not in standard chrome.  Replecated on multiple machines.  

Buffer.copy was being called from within an iFrame, so that may be a necessary step to reproduce the issue.  

I probably sound insane but I swear to you, this really happens and is a real bug.

### Desired behavior

Copy bytes properly

### Test code to reproduce

```typescript
const req = https.request(requestConfig, (res) => {
      res.on('data', (chunk: Buffer) => {
        chunk.copy(responseBuffer) // Issue here
      });
      res.on('end', () => {
        resolve([res, responseBuffer]);
      });
    });
```

### Cypress Version

8.3.0

**Comment by sainthkh** [comment]
Sorry for the late reply. 

By default, the App Under Test is run in iframe environment and the test code is run outside of that iframe. It's hard to guess the cause of the problem because there is no reproducible example, it might be possible that the buffers are living in the different worlds. 

Maybe using [`cy.window()`](https://docs.cypress.io/api/commands/window) might solve the problem.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
