### ISSUE TITLE
Segment route not intercepted in headless mode

### ISSUE THREAD

**Issue by sangamkarthik** [cypress-io/cypress#18190]
### Current behavior

I am having an issue for one of my test where Cypress run is working for headed mode but it is not working for headless i.e., this is happening in my local as well as in CI

cypress run --browser chrome --headless --> Error
cypress run --browser chrome --headed --> Works fine
I reckon It is unable to intercept the route in headless mode and is timing out if i wait for the route 

Electron and chrome are behaving the same(i.e., issue on headless mode)
The test passes in Cypress open mode across all the Browsers

### Test code to reproduce
```js
    beforeEach(() => {
      cy.intercept(
        {
          method: 'POST',
          url: 'https://api.segment.io/v1/t*',
        },
        (req) => {
          catchEvent.push(req.body.event);
        }
      ).as('segment');
    });

cy.wait('@segment');
```

### Cypress Version

7.7.0

**Comment by sainthkh** [comment]
Sorry for the late reply.

I sent request with postman to `https://api.segment.io/v1/track`, but failed. It seems because I don't have valid authentication. It would be great if you could me a reproducible example. As we all know, reproducing bug on the developer's machine is the first step to debugging. 

I hope it works with 8.5.0.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
