### ISSUE TITLE
Error while working with Jest and Cypress

### ISSUE THREAD

**Issue by Algoritm211** [cypress-io/cypress#18305]
### Current behavior

Our team decided to use Jest and Cypress together to display our application’s test coverage and collect all tests in one place.
However, when we run the tests, we get the error:
```
The following error originated from your test code, not from Cypress.
  > Do not import @jest/globals outside of the Jest test environment
When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
Cypress could not associate this error to any specific test.
We dynamically generated a new test to display this failure.
```
Can you please tell us how to solve this problem, we are really stuck on this error
I also attach a screenshot of the error:

https://i.stack.imgur.com/MuqLJ.png

**Thanks a lot in advance for your help.**

### Desired behavior

Cypress works correctly with Jest

### Test code to reproduce

```typescript
import { getConsultationsByPsychologistId } from "../../src/api/consultation";
import { ConsultationType } from "../../src/pages/types";
import { loadConsultationsThunk } from "../../src/redux/consultations/action";
import { expect } from '@jest/globals';

jest.mock("../../src/api/consultation");
const result = [
  {
    id: "id",
    duration: 20,
    price: 20,
    psychologist_id: "psychologist_id",
    psychologist_name: "psychologist_name",
    psychologist_avatar: "avatar_url",
    user_id: "user_id",
    user_name: "user_name",
    videochat_url: "videochat_url",
  },
] as Array<ConsultationType>;

const getConsultationsByUserIdMock =
  getConsultationsByPsychologistId as jest.Mocked<
    typeof getConsultationsByPsychologistId
  >;

//@ts-ignore
getConsultationsByUserIdMock.mockReturnValue(Promise.resolve(result));

test("Load consultations", async () => {
  const thunk = loadConsultationsThunk("1tj3McTIjMdvbCQBCsIlgY88ksy2");

  const dispatchMock = jest.fn();

  await thunk(dispatchMock);

  expect(dispatchMock).toBeCalledTimes(1);
});
```

### Cypress Version

7.5.0

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Internally, Cypress is tightly coupled with `mocha`. When running test codes with Cypress, it meas that mocha is loaded. `@jest/globals` doesn't want to be used with other libraries like `mocha`. So, it throws the error, `Do not import @jest/globals outside of the Jest test environment`. 

What is the solution?

I'm not sure because I don't know the exact goal of your testing plan. 

* If it's running all test commands with a single command, it might need a script. 
* If it's seeing all the test coverage data in a single screen, maybe using `nyc` with Cypress might solve the problem because jest's code coverage and nyc both use istanbuljs.

**Comment by sainthkh** [comment]
Closing because of the inactivity.
