### ISSUE TITLE
Collect pull request information for each run

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#1844]
Collect and send PR to api when specs are run, so that a link to the PR can be shown in the Dashboard.

**Comment by bahmutov** [comment]
need to decide which variables to collect, since each CI does it differently
- Circle `CIRCLE_PR_NUMBER `, etc https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
- Travis `TRAVIS_PULL_REQUEST` (number if PR, "false" otherwise) https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

Need to update schema `TestRunner.Commit` to add this

**Comment by bahmutov** [comment]
The test runner can send the pull request number (if any). It seems all CIs have explicit pull request number, while CircleCI has pull request number in the url like `CIRCLE_PULL_REQUEST=https://github.com/cypress-io/cypress/pull/2114` which we will need to parse ourselves.
