### ISSUE TITLE
Cypress wont select dropdown (Only with force twice)

### ISSUE THREAD

**Issue by npostma** [cypress-io/cypress#18467]
### Current behavior

- I have a selectbox that is being loaded with AJAX.
- I wait for the repsonse with code 200
- Then i try to select a option based on the value in its value property 

Sometimes i am lucky and it selects the option. Mostly it doesn't

Calling `cy.get('.form-group:nth-child(2) .form-control').select('value')` once does not select the value. I see in the before / after a red dot on the correct selectbox but no value/selected change.
Calling `cy.get('.form-group:nth-child(2) .form-control').select('value')` twice gives me a `detached from DOM` error
Calling `cy.get('.form-group:nth-child(2) .form-control').select('value', {force: true})` twice gives works for me.

### Desired behavior

That calling  `cy.get('.form-group:nth-child(2) .form-control').select('value', {force: true})` twice is not needed and calling `cy.get('.form-group:nth-child(2) .form-control').select('value')` once is enough.

### Test code to reproduce

Load a form with a `<select>` and `<option>`s with ajax and try selecting the option after the ajax call is finished.

### Cypress Version

8.5.0

**Comment by sainthkh** [comment]
Sorry for the late reply.

It's hard to guess the real problem because there is no reproducible example here. 

I guess [`cy.wait`](https://docs.cypress.io/api/commands/wait) or [`cy.intercept`](https://docs.cypress.io/api/commands/intercept) would help solve the problem.

**Comment by BlueWinds** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

As sainthkt says, it'll be a lot easier for use to track down and attempt to fix if there's code we can easily run to see it happening ourselves. Reproducing the issue is the first step to fixing it, after all.

**Comment by npostma** [comment]
No, this is something that is happening in the system i'am trying to test. But cant reproduce it in a simple setup. I have an idea where the 'problem' lays (and probably not a cypress issue).

![image](https://user-images.githubusercontent.com/1578820/142166321-e03934fa-61a6-46b3-96a3-85deac23efc3.png)

Cypress waits unit the ajax request gives me a 200. But that is not the moment everything is ready. The JavaScript is being evaluated en doing things like animations and other DOM interactions and this needs (probably) a little bit more time than cypress is waiting for. Or there is some conflict. Because sometime i see that is selects the correct value and a split second later the selection is made undone.

**Comment by BlueWinds** [comment]
In that case all I can suggest is that you add an intermediate cypress command that will wait until you know the DOM is settled - `cy.get('select').should('have.class', 'data-ready')` or something, that cypress can wait on before you invoke your select command.

Since there doesn't seem be an issue that we can help you solve, or in cypress itself, I'm going to close this issue. For questions over the best way to solve problems or get help, you could try our [Community Chat](https://on.cypress.io/chat) or ask on [Stack Overflow](https://on.cypress.io/stack-overflow).
