### ISSUE TITLE
LocalStorage items gets deleted at second test execution

### ISSUE THREAD

**Issue by vpetrache** [cypress-io/cypress#18475]
### Current behavior

I have several tests that, in before, have several line of codes for clearing the local storage, making the login call to get token and user object, a cy.window() method to set 2 local storage items ngStorage-accessToken and ngStorage-user.

If I run this spec from Cypress Playground, in the first execution, both items are set in Local Storage.

On the second execution, both are set but after some time ngStorage-accessToken disappears.
I also tried removing the clear Local Storage function but without any success.

This also happens when running tests in CI in several specs.

The issue doesnt happen for tests in which there are other actions between clear storage and set storage items.

I tried with adding cy.wait() but it didnt worked when running multiple tests.

Thanks for the support
![scr](https://user-images.githubusercontent.com/9765495/137187087-3b9f4ee7-f0f7-41d2-9c43-2b729c85f45b.png)

### Desired behavior

I should have 2 items set in Local Storage.

### Test code to reproduce
```js
before(function () {
        cy.visit(`${Cypress.env('LEGACY_PLATFORM_APP_URL')}/dashboard`)
        window.localStorage.clear()
        window.sessionStorage.clear()

        expect(window.localStorage.getItem('ngStorage-user')).to.be.null
        expect(window.localStorage.getItem('ngStorage-accessToken')).to.be.null

        cy.fixture('testUsers').then(testusers => {
            testUsers = testusers

            cy.requestLogIn(
                testUsers.erm.emailAddress,
                Cypress.env('CYPRESS_USER_PASSWORD')
            ).then(loginResponse => {

                cy.window().then(win => {
                    win.localStorage.setItem('ngStorage-accessToken', loginResponse.body.token)
                    expect(win.localStorage.getItem('ngStorage-accessToken')).to.eq(
                        loginResponse.body.token
                    )
                })

                cy.window().then(win => {
                    win.localStorage.setItem('ngStorage-user', JSON.stringify(loginResponse.body.user))
                    expect(win.localStorage.getItem('ngStorage-user')).to.eq(
                        JSON.stringify(loginResponse.body.user)
                    )
                })

                cy.visit(`${Cypress.env('LEGACY_PLATFORM_APP_URL')}/expert-search`)
            })
        })
        cy.fixture('expertDetails').then(expertDetails => {
            expertData = expertDetails
        })
    })
```

### Cypress Version

8.6.0

**Comment by emilyrohrbough** [comment]
In Cypress today, we clear localStorage for the current domain before each test. This isn't clear or obvious because we persist the application under test so it's unintuitive that the user needs to re-apply the local storage values needed for their application.

In v12.0.0 (soon-to-be-released), we are introducing the concept of [Test Isolation](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Isolation) to prevent confusing cases like this. There will be two modes of test isolation, `on` and `off`, with `on` being the new default mode.  When test isolation is `on`, before each test, Cypress will:

- clear the page by visiting `about:blank`
- clear cookies
- clear local storage
- clear browser storage

This will prevent DOM and browser state bleed over between tests.

If it is desired to persist DOM and browser state between a set of tests, you will be able to turn test isolation off for the run or at the suite level.

Closing this issue as done and tagging for the v12.0.0 release.
