### ISSUE TITLE
Execution time increased drastically after upgrading from 8.3.0 to 8.6.0

### ISSUE THREAD

**Issue by dein0s** [cypress-io/cypress#18564]
### Current behavior

After upgrading cypress from `8.3.0` to `8.6.0`, execution time of our tests (same amount of tests/suits) increased by ~10 min (almost doubled the initial time to execute).
Current execution results (version `8.6.0`):
![image](https://user-images.githubusercontent.com/7908313/138057155-09fdd530-e555-4ed8-8092-d1152d5b2261.png)
![image](https://user-images.githubusercontent.com/7908313/138057180-f8eb7192-60e9-47c1-b446-6ca3d8ef5439.png)

### Desired behavior

We'd expect, that execution time stays the same or gets lower with cypress update, not increase almost two times.
Previous execution results (version `8.3.0`):
![image](https://user-images.githubusercontent.com/7908313/138057430-e2db6e94-9c86-4013-8f3e-c211de65728a.png)
![image](https://user-images.githubusercontent.com/7908313/138057539-550e58da-5c99-4939-be62-25cc3c618b1f.png)

### Test code to reproduce

`yarn upgrade cypress@8.6.0`

### Cypress Version

8.6.0

### Other

Currently had to revert back to 8.3.0, because otherwise builds time out (due to the 30m aws-amplify build timeout setting).

**Comment by szamanr** [comment]
i can confirm the issue is coming from electron. when i switch the browser to chrome via cypress.yml, the issue disappears.

the video playback issue that i mentioned in #18740 also doesn't happen on chrome.

**Comment by lszmit-nm** [comment]
We have observed the exact same problem moving from 8.3 to 8.6. Out test pipeline of 136 tests in 22 specs had its runtime escalate from ~30 minutes to over 2h (we're using Chrome, not Electron). Disabling video recording made a difference, but moving back to 8.3 had the most impact.

**Comment by petetnt** [comment]
More anecdotal evidence, with no code changes 8.7.0 performs 400% slower than 7.7.0 (which I updated to 8.7.0) and 8.5.0 (which I downgraded from 8.7.0). Running on GH Actions with multiple runs equaling around the same times from same setup (both on fresh cache and warmed cache).

![image](https://user-images.githubusercontent.com/7641760/140539856-dc1d7b11-4268-4b7a-ab21-eb5db9ab7b17.png)

**Comment by CamilleDrapier** [comment]
This slowness still seems to happen, for us, in the same proportion as described [here](https://github.com/cypress-io/cypress/issues/18564#issuecomment-949298434) in version 9.0.0

**Comment by AlexDaniel** [comment]
Same problem, downgrading to 8.5.0 helped a lot. Here are the timings:
| Cypress 8.5.0 | Cypress 8.7.0 |
|--------------------|--------------------|
| ![image](https://user-images.githubusercontent.com/5507503/141296354-d899e948-ff22-4f38-a385-8a12fe1e048f.png) | ![image](https://user-images.githubusercontent.com/5507503/141286421-e5ea0c4e-741a-4aae-b8d8-51dc5fd1c610.png) |

**Comment by szamanr** [comment]
is the team aware of this issue yet?

**Comment by helenaritson** [comment]
We are also experiencing the same issue - recent versions are much slower(both locally and in CI) and we are stuck on version **`6.6.0`** 
For us, biggest difference was upgrading to `7.6.0` where test execution time jumped from ~31 to ~105 sec:

![image](https://user-images.githubusercontent.com/77272748/141799085-67fcdf26-069f-4ac4-9e27-7c9272b58932.png)


Also, it seems that first test run is the fastest and when I re-run the same test again(from test runner) it gets slower and slower (with 6.6.0 it's the opposite, re-running the same test is usually faster)

List of similar issues:
- https://github.com/cypress-io/cypress/issues/18057
- https://github.com/codelab-ai/codelab.ai/issues/1172
- https://github.com/cypress-io/cypress/issues/17759
- https://github.com/cypress-io/cypress/issues/17750

**Comment by AlexDaniel** [comment]
For what it is worth, I have tried 7.5.0 for our project (instead of 8.5.0) and I see [no further performance improvement](https://github.com/cypress-io/cypress/issues/18564#issuecomment-966292917) (compared to downgrading to 8.5.0 from 8.7.0). So, no, it's not the case of [Wirth's law](https://en.wikipedia.org/wiki/Wirth%27s_law), and cypress is not getting slower the further we go, but there's clearly a performance regression in 8.6.0.

**Comment by BlueWinds** [comment]
> is the team aware of this issue yet?

Sorry for the lack of response so far - performance regressions are something we take fairly seriously, and it's been causing us pain internally as well, due to much of our automation becoming flaky due to increased runtimes.

While we haven't pulled this ticket in specifically, it seems like at least some of this may be related to changes in how electron handles failed requests while under test automation control - @mjhenkes may have more information on that subject.

**Comment by jiangao1** [comment]
@helenaritson Thanks for showing the graph. I'm also holding the upgrade and in 8.3.1 now. Like the graph showed, we see a sizable increase from 8.3.1 to 8.7.0, and we had to roll back the upgrade. I will wait to see further performance data for later versions, and wait.

**Comment by jennifer-shehane** [comment]
Can anyone provide a reproducible example that we can run to reproduce the performance issue?

**Comment by CommCody** [comment]
I have no sample (yet), but I have tested our code base with the following versions (8.4 8.7 9.0) with different browsers (Electron Chrome Firefox). While I could discern some relevant differences between versions and browsers (runtime is between 6 and 8 minutes), none are as big as running this same code base on the az Pipelines ubuntu image on the cypress/included docker image (~50 minutes).

Not testable with version 9:
https://github.com/cypress-io/cypress-docker-images/issues/555

I will try to distil a sample.

**Comment by jvavre** [comment]
I don't have exact comparison as others but noticed our CI runs going from 35mins in 6.x and 7.x to 50-55mins for 8.7.0 as for now with little to no changes in amount of TCs run.

**Comment by gguine-sweep** [comment]
hello, it's hard to get the time to create a reasonable reproduction example for something that global (demo stack, demo tests, benchmark). 
Would a comparable set of full cypress log with DEBUG: cypress:* for same code base, context, test help ?

**Comment by jmoses** [comment]
Is it possible the [real world app](https://github.com/cypress-io/cypress-realworld-app) can be used as a reproduction case?  I'm not sure if failing tests are a contributor (I _feel_ like they are, but have not checked) or if the RWA has any that currently fail.

**Comment by tuomoa** [comment]
Our experiments shows that cypress 8.5.0+ uses a lot more cpu. We tested in docker container limited to 4 cores and 8gb of memory:
```
Version   Execution Time
9.1.1:    2:22:24
9.2.0:    2:09:50
8.5.0:    1:22:07
```
However if we ran it without docker limiting cpu usage, it took like 900% of cpu (the processes in total) and 9.1.1/9.2.0 took around 1h 30min. So it seems to me that the cpu usage is doubled/tripled and that is causing the slowing down if you have limited cpu resources.

**Comment by MaaikeFox** [comment]
I have the same problem. I switched to using chrome browser on CI runs and this brought running times back to normal so that I can upgrade Cypress

**Comment by szamanr** [comment]
still experiencing this issue with v9.3.1:

our current setup is v8.7 + chrome

- 8.7 + chrome 97 + ubuntu 20.04 ~= 11 min
- 9.3 + chrome 97 + ubuntu 20.04 ~= 11 min
- 9.3 + electron 94 + ubuntu 20.04 ~= 26 min

**Comment by FelipeLahti** [comment]
Experiencing the same issue here upgrading cypress from 8.4 to 9.4.1
E2E testing went from 3min to 6min
Component tests from 7min to 13min.

**Comment by tkovs** [comment]
Experiencing the same issue here upgrading cypress from `5.6.0` to `7.1.0`. A complete run went from 30m to 1h.

**Comment by ChristianKlima** [comment]
The same in our solution. Time doubles with electron. With chrome the cypress is a fast as it was before. Is it possible to fix something to run electron again or is it recommended to use chrome only?

**Comment by ChristianKlima** [comment]
Switch to chrome was not an option. Now we have a problem with same major Chrome versions check. 
The Chrome browser is automatically updated on our test agents. Don't know why this is checked :(

 You passed the --parallel flag, but we do not parallelize tests across different environments.

This machine is sending different environment parameters than the first machine that started this parallel run.

The existing run is: 

In order to run in parallel mode each machine must send identical environment parameters such as:

- specs

- osName

- osVersion

- browserName

- browserVersion (major)

This machine sent the following parameters:

{

**Comment by csvan** [comment]
I understand it is not helpful, but I just want to echo that we are seeing the same degradation as described above on our (proprietary) suites, gradually getting worse from Cypress 7 to 9.7. Due to reports of even worse performance we are holding off migrating to 10 - unfortunately CI performance is almost unusable for us at this point.

My only observation is that this ONLY seems to affect CI/headless mode. Running `cypress open` still _feels_ very fast and snappy, but as soon as we hit CI everything grinds to a halt.

If there is anything we can do to help dissect this issue, please let me know. I am not sure where to start looking.

**Comment by BlueWinds** [comment]
> I understand it is not helpful, but I just want to echo that we are seeing the same degradation as described above on our (proprietary) suites, gradually getting worse from Cypress 7 to 9.7. Due to reports of even worse performance we are holding off migrating to 10 - unfortunately CI performance is almost unusable for us at this point.
> 
> My only observation is that this ONLY seems to affect CI/headless mode. Running `cypress open` still _feels_ very fast and snappy, but as soon as we hit CI everything grinds to a halt.
> 
> If there is anything we can do to help dissect this issue, please let me know. I am not sure where to start looking.

We got some changes out in 10.3.0 which might fix your issue - no promise it's the same problem, but we've had one company report a 2x speedup in 10.3.0 compared to 10.2.0.

**Comment by csvan** [comment]
@BlueWinds tested 9.7 vs 10.3.1 on one of our suites and saw an improvement of about 3 minutes (roughly 40% relative to average runtime under 9.x), awesome stuff!!

**Comment by BlueWinds** [comment]
We have some additional speedups in the pipeline. https://github.com/cypress-io/cypress/issues/22353#issuecomment-1189769920 is about component testing, but the currently top candidate applies to e2e testing as well, cutting off about 300ms from loading every spec.

There's also V8 snapshots, which are a bit further out (and unclear exactly how much time they'll save - some, but too early to quantify yet).

The currently work on Detached DOM (https://github.com/cypress-io/cypress/issues/7306) should bring some performance improvement as well, though not on the scale of the other two tickets mentioned.

**Comment by BlueWinds** [comment]
> We are also experiencing the same issue - recent versions are much slower(both locally and in CI) and we are stuck on version **`6.6.0`** First biggest time difference was upgrading to `7.7.0` where test execution time jumped from ~37 to ~81 sec:
> 
> ![image](https://user-images.githubusercontent.com/77272748/141811483-8fbf70c9-90f4-4b79-9043-8811ab9e3f8d.png)

That is a lovely benchmark and graphic, thank you for putting it together. If you could try the same under 10.3.1, it would be great to see how much further we still have to go to get back to the fast old days.

**Comment by Cellule** [comment]
Upgraded from 9.6.1 to 10.3.1 and test run time cut by about 3-4min, about 25% faster.
Amazing 🎉🎊

**Comment by bbartizek** [comment]
I saw that there were performance improvements mentioned in the changelog for 10.8.0, but running one of our existing test suites showed that this issue still is not resolved.  Over the last 3 months on 8.1.0, the average runtime for the suite is 11m 44s, but my test on 10.8.0 took 30m 20s.

**Comment by BlueWinds** [comment]
@bbartizek - If you could provide us with a specific test which runs slower on 10.x, I'd love to look into it more.

I certainly believe it's happening, but in order to look into it, I first need to be able to isolate a case and examine it. I don't have access to your tests quite, so it running slower isn't much help in figuring out what the problem is. It's also very hard to compare across a gap of multiple major versions and a huge amount of code change, even if we have a specific test which does run slower on newer versions.

I understand the frustration, but unless you can help track down the problem, I'm not sure what else we can do beyond continuing to look at performance and making incremental improvements (which we are). :woman_shrugging:

**Comment by AlexDaniel** [comment]
@BlueWinds have you tried running *any* test suite on 8.3.0 vs 8.6.0 (and then vs the latest version)? What are your timings?

**Comment by BlueWinds** [comment]
I'm saying 8.3 vs 8.6 was a long time ago, and we (like the majority of projects) don't usually tend to support old versions.

We would welcome help identifying exactly what is now slow and improving it. But "still slow" is not useful or productive.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. We won't be investigating issues for 8.x releases and recommend upgrading to a later version of Cypress.

**Comment by AlexDaniel** [comment]
Has anybody done any measurements to confirm that the latest releases don't have this issue?

**Comment by ghost** [comment]
> Has anybody done any measurements to confirm that the latest releases don't have this issue?

I know it's just a single datapoint, but we're currently running 226 tests in 38 specs averaging 4:00 minutes per run with 8-way parallelisation on 13.1. You can compare that to where [we were just a year ago](https://github.com/cypress-io/cypress/issues/18564#issuecomment-1144891223) (a world of pain, in short).
