### ISSUE TITLE
After cy.request() to retrieve a large file, the next test hangs indefinitely 

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#18671]
### Current behavior

![image](https://user-images.githubusercontent.com/36670132/139175470-95619cb2-52d4-431c-b3b9-4d4f9b893357.png)

After using `cy.request()` to retrieve a huge file. The next test hangs indefinitely (cannot start)

I could be completely wrong, but my educated guess is that holding the retrieved body of the file caused some memory issues

### Desired behavior

The following tests run as normal

### Test code to reproduce

Init project with `npx cypress open`

Test case is :
```javascript
describe("x", () => {
    it('x', () => {
        const link = "https://github.com/cypress-io/cypress/archive/refs/heads/develop.zip"
        cy.request(link).as('link')

        cy.get('@link').should((response) => {
            expect(response.status).to.eq(200)
        })
    })

    it('y', ()=>{
        cy.wrap(2).should('equal', 3)
    })
})
```

### Cypress Version

8.7.0

**Comment by mariecreel** [comment]
+1 to this issue with cypress 9.5.4. Running `cy.request` on a 15.0 MB image file causes the following tests to never start.

**Comment by spiltcoffee** [comment]
+1 still happening in Cypress 12.10.0, though we could download slightly larger files by requesting a different encoding from the service we were testing (base64 in this case).

**Comment by mike-plummer** [comment]
For folks running into this issue I will leave a couple thoughts:

## There is some browser-specific behavior at play

Chromium has some internal limits which impacts Chrome/Electron/etc. For instance, the example above fails in Chrome & Electron but succeeds in Firefox (latest versions as of today). We try to mitigate this whenever possible, but sometimes browsers just work differently.

## Do you really need to download a file this large?

A lot of the time you don't actually need to download the file but just want to verify a given service is "up". For this, you can specify that `cy.request` use the `HEAD` HTTP method which just reaches out to the given endpoint to get headers without actually downloading the payload.

```js
cy.request({
  url: link,
  method: 'HEAD'
}).should((response) => {
  expect(response.status).to.eq(200)
})
```

## If you're downloading the file for test data, could it be a Fixture instead?

Large blocks of test data should be stored as [Fixtures](https://docs.cypress.io/api/commands/fixture) when possible - they are more performant and minimize the bandwidth impact of your tests. Fixtures are much faster to load (since there's nothing moving over the wire), and can be *massive* (upwards of 1GB) if you [customize the content encoding](https://github.com/cypress-io/cypress/issues/16823#issuecomment-1043270016)

**Comment by ncreel** [comment]
Thanks for the response @mike-plummer, totally blanked on using the `HEAD` method in my use case but it would suffice.

**Comment by jennifer-shehane** [comment]
Closing this issue since it has workarounds suggested.
