### ISSUE TITLE
"Browser context management is not supported" error for electron browser on cy.window()

### ISSUE THREAD

**Issue by mannugndu** [cypress-io/cypress#18675]
### Current behavior

When i issue the command cy.window() and launch the tests in electron browser then i get this 
![image](https://user-images.githubusercontent.com/53671962/139203366-b8b1d8aa-26d4-43fe-8fa7-c3b4afadc00a.png)

### Launch the test in electron browser
cy.window().then(win=>{
console.log(win)
})

### Cypress Version

8

**Comment by nileshgulia1** [comment]
@mannugndu Did you find anything on this yet? Thanks!

**Comment by trainoasis** [comment]
Would also be interested in the solution. 

What worked for me was using Chrome, like `cypress run --browser chrome --config video=false --headed`

**Comment by mannugndu** [comment]
@nileshgulia I found out that electron does not support window context (at least for now)..
We need to use chrome browser for that..

**Comment by mbinic** [comment]
This probably got fixed in the meantime - with Cypress 12.1.0 running Electron 106 I could use `cy.window()` normally.

However, I got this when trying to set permissions using `Cypress.automation` like [here](https://gist.github.com/mbinic/e75a8910ec51a27a041f967e5b3a5345), but adding a `catch()` to it helped, because it seems with Electron the permissions are already there.
