### ISSUE TITLE
Stubbing node methods for electron apps not working

### ISSUE THREAD

**Issue by bdiz** [cypress-io/cypress#1873]
### Is this a Feature or Bug?

Feature. The FAQ says it'll work with a little extra code and I looked through the cypress specs you guys use for testing the cypress electron browser, but I did not see any stubbing node methods. ie fs methods etc. 

This may be a feature request for enhanced docs. Nobody in the chat responded to this question. I've asked three times on gitter now so I gave my best to not file a bug for this question.

I've found https://github.com/cypress-io/env-or-json-file/blob/ef205312ba73f2fd6404947005b1a401cb6dd305/src/env-or-json-file-spec.js#L43 which looks promising but I don't think these specs are ran using Cypress? Regardless I tried to copy what was done in this spec without success.

And the FAQ points to https://github.com/cypress-io/cypress/tree/develop/packages/desktop-gui/cypress/integration but I don't see any node methods being stubbed. Am I just missing it?

### Current behavior:

Stubbing like this doesn't work.
```js
const fs = require('fs');
it('does something', () => {
  cy.stub(fs, 'readFileSync').returns('file contents'); // Errors: fs does not have method 'readFileSync'
});
```
Nor does this work.
```js
const fs = require('fs');
it('does something', () => {
  fs.readFileSync = function() {
    return 'file contents';
  };
  cy.find('.btn-which-invokes-readFileSync')
    .click(); // Error: Empty fs object required in project different than empty fs object required here in test. readFileSync method not defined.
});
```
### Desired behavior:

To be able to stub node methods using first example above.

### Steps to reproduce:

See Current Behavior section.

### Versions

Cypress 2.1.0, Ubuntu

**Comment by chrisbreiding** [comment]
The issue you're encountering is that your app code and your test code are in separate files that end up having separate references to the `fs` module. So you can't stub `fs` from your test code just by requiring it. You have to expose `fs` globally from your app code in order to stub it in your test code.

You can see how we do it in the Desktop GUI by [exposing a global `App` object](https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/src/main.jsx#L20) in order to [stub the ipc](https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/cypress/integration/app_spec.coffee#L4). 

You could conditionally expose the global only when running in Cypress if you like.

```javascript
// app code
const fs = require('fs')

if (window.Cypress) {
  window.fs = fs
}

// ... more app code ...
```

```javascript
// test code
cy.window().its('fs').then((fs) => {
  cy.stub(fs, 'readFilesync')
})
```
