### ISSUE TITLE
Request in Headless mode not returning the same result as in Head mode

### ISSUE THREAD

**Issue by gpenafib** [cypress-io/cypress#1878]
### Is this a Feature or Bug?
Bug

### Current behavior:
Making a request in HEAD mode returns 200, while the exact same code, in HEADLESS returns 400
This is happening while importing a xlsx file. 

The import is made with function included in commands.js:
```js
Cypress.Commands.add('form_request', (method, url, formData) => {
    return new Cypress.Promise((resolve, reject) => {

        const xhr = new XMLHttpRequest();
        xhr.open(method, url);
        xhr.onload = () => {
            resolve(xhr);
        };
        xhr.onerror = () => {
            reject(xhr);
        };
        xhr.send(formData);
    })
})
```

### Desired behavior:
Obtaining the same result, either with HEAD or HEADLESS mode.

### Steps to reproduce:
1.- Use the method said just ago to import a file into a web with HEAD mode
2.- Do the exact same thing with HEADLESS mode.

```
### Versions
Cypress: 3.0.1
WIndows 7
Chrome - Headless

**Comment by jennifer-shehane** [comment]
- Do you mean it runs different between `cypress run` and `cypress open`?
- Or do you mean it runs different between `cypress run` and `cypress run --headed`?
- Are you using the browser flag when in run mode like `cypress run --browser chrome`?

The nomenclature is a bit confusing, I know. 😄

**Comment by brian-mann** [comment]
Sounds like you're running electron headlessly but chrome in headed mode. These are not going to be the same browser versions and thus their behavior differs.

There may not actually be anything wrong here depending on what you're trying to do. We'll need much more information - you describe "importing an xlsx file" but you're getting a `400` on the request - why? A 400 is something your server sends, so why is your server sending 400? What is the root cause of this problem? What is different about the requests?

Also - why are you using `new XMLHttpRequest` instead of using `cy.request` to make this request? Just curious.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
