### ISSUE TITLE
adding hover custom command throws an error

### ISSUE THREAD

**Issue by mysticdevx** [cypress-io/cypress#18887]
### Current behavior

Hi,
There was a custom hover method I have added in v8.3.1, however, with v.9.0.0 changes although there's no cypress built-in hover method, I am getting the below error message:
```
The following error originated from your test code, not from Cypress.

  > Cypress.Commands.add() is used to create new commands, but hover is an existing Cypress command.

Please use Cypress.Commands.overwrite() if you would like to overwrite an existing command.
```

### Desired behavior

It should work as in previous versions because there's no hover method in cypress as mentioned in https://docs.cypress.io/api/commands/hover 

### Test code to reproduce

Here is how I have added the hover method in previous versions (v8.3.1 and before)
```
Cypress.Commands.add("hover", { prevSubject: 'element'}, (subject, options) => { ... })
```

### Cypress Version

9.0.0

**Comment by CannyBangbang** [comment]
When I hit this I was thinking they finally added it but no...

**Comment by BlueWinds** [comment]
`cy.hover()` is in fact an existing command. https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/actions/hover.ts. If someone wanted to open a PR for the docs to clarify it, we'd definitely welcome the contribution. It's a bit misleading.

![image](https://user-images.githubusercontent.com/3003404/141536151-441dcc0a-b9e6-4879-9ed3-4a1699832f13.png)

Now I'll grant you it's a *useless* command, since all it does is throw an error - but it does exist. You can change your code to use 
```
Cypress.Commands.overwrite('hover', (originalFn, ...otherArgs) => {})
```
rather than

```
Cypress.Commands.add('hover', (...otherArgs) => {})
```
and it should resume working with no other changes.

**Comment by mysticdevx** [comment]
Thank you for the answer. I have created a PR for this issue in documentation.
https://github.com/cypress-io/cypress-documentation/pull/4208

**Comment by cowboy** [comment]
cypress-io/cypress-documentation#4208 has been merged, closing
