### ISSUE TITLE
Commands using `this` context can't be overwritten

### ISSUE THREAD

**Issue by slikts** [cypress-io/cypress#18892]
### Current behavior

Commands lose their original `this` context when overwritten.

### Desired behavior

It should be possible to overwrite commands that reference `this`.

### Test code to reproduce

Reproduction:
```js
Cypress.Commands.add('foo', function () {
  cy.log(this.test.title) // this works if not overwritten
})

Cypress.Commands.overwrite('foo', function (originalFn) {
  return originalFn() // throws error
})
```

### Cypress Version

9.0.0

### Other

The workaround for the reproduction would be to use `Cypress.currentTest.title`, but it can't be controlled for 3rd party code.

**Comment by BlueWinds** [comment]
Interesting. This seems fairly niche, but there's no particular reason we shouldn't support it - a one-line change to make the Cypress API work "as expected" seems worth it.

In my PR, I left it so that you'd have to
```
return originalFn.call(this)
```
rather than forcing it to be the case. 

Out of curiosity, what are you actually trying to do with this? Instrument an existing function with additional logging, if I had to guess?

**Comment by slikts** [comment]
I'm wrapping the Applitools Eyes commands to add additional features to them (hence the linked applitools/eyes.sdk.javascript1#710). The reason to overwrite instead of adding new commands is to make it a drop-in replacement of the original, so that you can change only the imports and it still works. Not sure how rare this use case is, but it's not something very exotic.
