### ISSUE TITLE
Not able to execute cypress scripts in any browser

### ISSUE THREAD

**Issue by sankarijayapal** [cypress-io/cypress#18936]
### Current behavior

![image](https://user-images.githubusercontent.com/92518148/142003002-972cfa2d-221a-4059-b20f-a11a923b5f43.png)

Forcepoint app is installed in my machine and due to that app , I was not able to execute cypress automation scripts in chrome or firefox browser. When we uninstall forcepoint app we are able to execute cypress scripts and due to company policy we can't uninstall them.

I was been asked to refer to below url and set the proxy accordingly

 https://docs.cypress.io/guides/references/proxy-configuration#Set-a-proxy-on-Windows

I tried setting environmental variable as HTTP_PROXY and value that been provided for me and still i am facing same issue.

### Test code to reproduce

![image](https://user-images.githubusercontent.com/92518148/142004159-e2688208-2460-4a17-b487-8cc09fd6e39d.png)

### Cypress Version

9.0.0

**Comment by BlueWinds** [comment]
We currently [have a regression](https://github.com/cypress-io/cypress/issues/18330) where HTTP_PROXY is not being respected for https requests. Can you please try setting HTTPS_PROXY as well, and see if that helps?

If you can open a specific known port in your firewall, you could also try setting the CYPRESS_REMOTE_DEBUGGING_PORT environment variable - this will allow you to specify a specific port which Cypress will use for CDP, rather than selecting one at random.
