### ISSUE TITLE
Unable to upload file.

### ISSUE THREAD

**Issue by javedansari278** [cypress-io/cypress#18951]
### Current behavior

![FileUpload issue](https://user-images.githubusercontent.com/58820949/142164651-8e3cb303-15fe-4ac6-b83b-9f367ff3420b.png)

### Desired behavior

File should get upload successfully using cypress-file-upload package.

### Test code to reproduce

describe('Test',()=>{

    it('Test1',()=>{

        const filepath1 = 'TIS/Trade/Authorize_TradeData.json'

        cy.visit('tradetickets?batchid=12415')

        cy.get('#files',{timeout:5000}).invoke('removeAttr','style').attachFile(filepath1)

       

    })

})

### Cypress Version

8.6.0

### Other

Step to execute.

1. Downloaded cypress-upload-file package through npm.
2. File which needs to be uploaded is in cypress/fixture folder.

 Note - for same application on some screens it's working fine but on some screens it's not.

**Comment by BlueWinds** [comment]
Unfortunately we can't provide support for the cypress-upload-file plugin here, since it's not something we maintain or have any say over. The maintainer of that plugin is quite active and helpful - I'd suggest opening an [issue on that repo](https://github.com/abramenal/cypress-file-upload/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) rather than here. :)
