### ISSUE TITLE
create-cypress-tests demo.gif is missing

### ISSUE THREAD

**Issue by basarat** [cypress-io/cypress#18971]
### Current behavior

# Issue 1: 
Its not present on https://www.npmjs.com/package/create-cypress-tests due to invalid link
The link needs to be changed here : https://github.com/cypress-io/cypress/blob/develop/npm/create-cypress-tests/README.md

I would do that but that brings me to

# Issue 2: 
The file `demo.gif` is 0bytes: https://github.com/cypress-io/cypress/blob/develop/npm/create-cypress-tests/demo.gif 🤷🏻‍♂️ 

Just thought I'd point it out :rose:

### Test code to reproduce

~ general doc issue ~ 

### Cypress Version

latest

**Comment by BlueWinds** [comment]
Looks like the gif got accidentally removed back in March, I've opened a PR to fix that. For the link though, I'm not completely sure what's the right approach - a relative path of "./demo.gif" appears correct and works in github (https://github.com/cypress-io/cypress/tree/issue-18971-demo-gif-broken/npm/create-cypress-tests), but npmjs.com appears to take that as a path relative to the repository, rather than the README.
