### ISSUE TITLE
Component tests in CI cause plugin file issues for e2e tests

### ISSUE THREAD

**Issue by muratkeremozcan** [cypress-io/cypress#18986]
### Current behavior

I am doing an external PoC on component testing, so that we can start incorporating component tests at our company.

We are using create React app, with instructions from the [Cypress blog post](https://www.cypress.io/blog/2021/04/06/cypress-component-testing-react/). 
Here is the [PR for adding component tests](https://github.com/muratkeremozcan/multi-stage-caching/pull/2).

Things are working well locally. Component testing in CI also works well.
However the plugin file setup [causes a regression with e2e tests on CI](https://github.com/muratkeremozcan/multi-stage-caching/runs/4255714007?check_suite_focus=true#step:5:40).

### Desired behavior

Component and e2e tests work together in CI just like they work locally.

### Test code to reproduce

```javascript
git clone https://github.com/muratkeremozcan/multi-stage-caching.git
cd multi-stage-caching
yarn

yarn server:test // headless e2e run
yarn cy:open-ct // component test runner 
yarn cy:run-ct // headless component tests

yar start // start the app
yarn cy:open // e2e test runner
yarn cy:run // headless e2d tests 

// All work fine locally.
// Make any change, i.e. comment or readme
// push, create a PR, observe CI
// Component tests will work well, e2e job will fail with a plugin file complaint
```

### Cypress Version

9.0.0

### Other

[Here is a video record of the issue](https://drive.google.com/file/d/16AzHte5BK54QJ59-Elqx5yrQdicOH-RD/view). I can invite anyone as a collaborator or you can fork the repo.

**Comment by jennifer-shehane** [comment]
What Node.js version are you running in?

This error is throwing here: https://github.com/cypress-io/cypress/blob/develop/npm/react/plugins/utils/get-transpile-folders.js#L5:L5

**Comment by muratkeremozcan** [comment]
Using 14.18.0.

Wrestled this a bit more. Your workaround works.

To reproduce the issue, use the commented out code instead. 

Just pushed this.
https://github.com/muratkeremozcan/multi-stage-caching/pull/2/commits/4e009b71083d73b1ffe2a90b4c7abb465bce3ff8

![image](https://user-images.githubusercontent.com/34237651/142498035-13cef290-50d2-4eac-921c-1a71d872a3e2.png)

**Comment by chrisbreiding** [comment]
It looks like `bahmutov/npm-install` [uses Node 12](https://github.com/bahmutov/npm-install/blob/37d870e488074d1a5810ffe9256ebdd81530ab72/action.yml#L6), and support for the nullish coalescing operator (??) was [added in Node 14](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#browser_compatibility). If you can run Node 14+ in your GitHub action, it should fix this.

That said, I think we should fix `@cypress/react` in one way or another. It looks like the intention is to [transpile the code to es5](https://github.com/cypress-io/cypress/blob/dc7503ebc9189d0976885a42378848fc3378cadf/npm/react/tsconfig.json#L4), but the [compiler options are overridden](https://github.com/cypress-io/cypress/blob/dc7503ebc9189d0976885a42378848fc3378cadf/npm/react/plugins/tsconfig.json#L3), so that isn't the case when it's published. If that's not the intent, the requirement for Node 14 or greater should be documented and enforced with a better error message.

**Comment by emilyrohrbough** [comment]
related: https://github.com/cypress-io/cypress/issues/19069

**Comment by lmiller1990** [comment]
`npm/react` is now shipped in the CLI - `import { mount } from 'cypress/react`'. You can also install from `@cypress/react` on npm. It's correctly transpiled now - no `??` operator.
