### ISSUE TITLE
Check select (multiple) has no values?

### ISSUE THREAD

**Issue by lugosium** [cypress-io/cypress#19029]
### Current behavior

`cy.get('select').should('have.value', []);` => `expected to have value [], but the value was []`

### Desired behavior

`cy.get('select').should('have.value', []);` => OK

### Test code to reproduce

have an empty multiple select

### Cypress Version

9.0.0

**Comment by chrisbreiding** [comment]
I could reproduce with the following:

index.html

```html
<select multiple>
	<option value="one">1</option>
	<option value="two">2</option>
</select>
```

spec.js

```js
cy.visit('index.html')
cy.get('select').should('have.value', [])
```

This is because it ends up being a strict equality check (`[] === []`) and it fails because the two arrays are different object references. But try a deep comparison:

```js
cy.get('select').invoke('val').should('deep.equal', [])
```

It fails with:

```
expected null to deeply equal []
```

`have.value` uses `.val()` under the hood, so there's some wonkiness with how Cypress wraps the element in jQuery. This demonstrates it:

```js
cy.get('select').then(($el) => {
  $el.val() // => null
  Cypress.$($el[0]).val() // => []
})
```

Both call `.val()` but return different results.

This is definitely a bug. There's 1 or 2 things that could be done to address it:

1. Fix the wonkiness with jQuery so that `.val()` always returns the same thing for an empty multiple select. I'm not sure if that should be `[]` or `null`. [Here's a relevant discussion I found](https://github.com/jquery/jquery/issues/2562) relating to it.
2. Optionally, change how `have.value` works so that if the value is an array, it does a deep comparison by default. 

@lugosium In the meantime, you could workaround this issue by using the following instead:

```js
cy.get('select').invoke('val').should('be.null')
```

**Comment by lugosium** [comment]
Thank you @chrisbreiding
