### ISSUE TITLE
querystring (introduced through URL) is obsolete

### ISSUE THREAD

**Issue by JJ** [cypress-io/cypress#19031]
### Current behavior

While installing cypress 9.0.0, a warning shows up indicating querystring is no longer used.

### Debug logs

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

### Cypress Version

9.0.0

### Package Manager

npm

### Operating system

Linux

### Other

This is the dependency tree:

```
└─┬ cypress@9.0.0
  └─┬ url@0.11.0
    └── querystring@0.2.0
```
url seems also in the brink of obsolescence, having been released 6 years ago.

**Comment by somalil** [comment]
I have the same problem. Solved only by installing cypress version 8.5.0 and below...

**Comment by JJ** [comment]
Will probably have to create yet another PR in `@cypress/request`...

**Comment by JanKanty** [comment]
Maybe we can change usage of `url` to `querystringify` since it's not depracated and does similar thing?

**Comment by dawidappnovation** [comment]
I have the same problem with next.js project

**Comment by RiZKiT** [comment]
Related issue: https://github.com/defunctzombie/node-url/issues/57

**Comment by plarner30** [comment]
This can break CI so would be good to have a fix soon

**Comment by plarner30** [comment]
@jennifer-shehane Realistically I think it's an issue external to Cypress so nothing more than that. But the details are:

When tests are run as part of our Appveyor build via a powershell build script the warnings are interpreted as breaking errors

The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

I changed the ErrorActionPreference and strictly they are warnings so it shouldn't be stopping probably but in any case would be helpful to get these warnings removed.
