### ISSUE TITLE
'Aw, Snap' error screen shown when test runs over 250 seconds (approx) intermittant

### ISSUE THREAD

**Issue by shaunswales** [cypress-io/cypress#1906]
### Current behavior:
Cypress when tests seem to run over 200 seconds you are sometimes presented with a screen showing the following:

'Aw, Snap! Something went wrong while displaying this webpage. Learn More / Reload'

Screenshot: 

![](https://content.screencast.com/users/shaunswales695/folders/FMG/media/3f2485f9-00b4-4032-99ee-97abe5c4da7c/06.08.2018-11.23.png)

### Desired behavior:
Shouldn't timeout.

### Steps to reproduce:
Runs tests around 300s plus using the Chrome browser.

### Versions
Version: 2.1.0 to 3.0.2

**Comment by shaunswales** [comment]
Just checked and this seems to be even more of an issue in 3.0.2

**Comment by shaunswales** [comment]
So just to give a bit more information so this can be looked into further...

The issue seems to be happening less back on 2.1.0, it increased in 3.0.1 and is happening more often in 3.0.2.

**Comment by meinhimmel** [comment]
@shaunswales have you found any workarounds for this yet? I'm running into this on 3.0.2 as well.

**Comment by AlexanderGranhof** [comment]
same issue, was able to reach ~2100 seconds at one point, but generally crashes around 200-300 seconds

**Comment by Prashant-Kan** [comment]
Same issue 
sometimes facing Aw snap and sometimes it crashes my application server to run further due to which it throws response timeout error.

**Comment by asubota** [comment]
+1 same story

**Comment by Prashant-Kan** [comment]
Hello, 

I have tried few solution and it is working for me at the moment but I am still in testing mode with different scenario.

In Cypress.json
{
    "requestTimeout" : 30000,
    "numTestsKeptInMemory": 0,
    "responseTimeout" : 50000,
    "pageLoadTimeout": 100000
}

This is what I have changed. 
Anyone who face the same issue try this one.

I got reference from [MySameQuestion](https://stackoverflow.com/questions/51630143/cypress-long-automation-script-crashes-the-chrome-browser-with-aw-snap-error/51635170#51635170)
and some quick research on default timeout values.

**Comment by carloscheddar** [comment]
Happening to me as well but only for `cypress open` `cypress run --browser chrome` doesn't have the same issue.

**Comment by Prashant-Kan** [comment]
Try adding 
{
"numTestsKeptInMemory": 0,
}
In your cypress.json. Browser will not crash. It will work.

**Comment by patpatx** [comment]
Happening to me as well.

As mentioned by @Prashant-Kan, changing `"numTestsKeptInMemory": 0,` does help prevent the `Aw, Snap` from appearing.  :+1: Thanks for that tip.

Do note that by setting `numTestsKeptInMemory` to 0, this itself disables the snapshot / limit the capability of Command Log feature.

Just wondering, as I notice Cypress runner saves the snapshot temporarily on the memory, isn't it possible to save it to a file (maybe an option) instead every x MB/test, so as to limit/lessen the possibility of `Aw snap memory problem`

**Comment by duncan-bayne** [comment]
We're experiencing this consistently with a long-running test that visits different SaaS systems.  It gets towards the end of the test, then crashes Chrome w/ the 'Aw, Snap' message.

* Cypress 3.1.0
* Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* macOS High Sierra 10.13.2

**Comment by duncan-bayne** [comment]
Some further updates:

1. The workaround proposed by @Prashant-Kan doesn't prevent the crash in our case.
2. The crash happens _every_ time, not intermittently.
3. If we reduce our test case to the minimal "browse to site, enter username and password, log in" then Chrome still crashes.  Happens on OSX and Windows.

I think this is a different bug, & will raise as a new issue.

**Comment by Prashant-Kan** [comment]
Hi, duncan-bayne:

I got reference from [MySameQuestion](https://stackoverflow.com/questions/51630143/cypress-long-automation-script-crashes-the-chrome-browser-with-aw-snap-error/51635170#51635170)
and some quick research on default timeout values.

Check the explanation in the above-mentioned link maybe you will get your solution.

**Comment by Boczarsky** [comment]
> 
> 
> Hello,
> 
> I have tried few solution and it is working for me at the moment but I am still in testing mode with different scenario.
> 
> In Cypress.json
> 
> ```json
> {
>     "requestTimeout" : 30000,
>     "numTestsKeptInMemory": 0,
>     "responseTimeout" : 50000,
>     "pageLoadTimeout": 100000
> }
> ```
> 
> This is what I have changed.
> Anyone who face the same issue try this one.
> 
> I got reference from [MySameQuestion](https://stackoverflow.com/questions/51630143/cypress-long-automation-script-crashes-the-chrome-browser-with-aw-snap-error/51635170#51635170)
> and some quick research on default timeout values.

It isn't work for me. Browser still crashes during long tests.

**Comment by Prashant-Kan** [comment]
@Boczarsky : Correct, Even it fails for me too (now) earlier it was getting passed. But, When my number of steps for the particular testcases increases which eventually increases the Memory, which results in browser crash.

if, Anyone else faces this issue and has the solution please do guide us.

**Comment by B3Kay** [comment]
This is a big issue at our department where we are doing big end to end testing as we can't do tests taking longer then 250s...

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Comment by azollai** [comment]
@jennifer-shehane the problem is still appearing in version 3.1.5. 
Reproduce it by running a spec file for more than 5 minutes.

**Comment by jennifer-shehane** [comment]
@azollai I've been unable to reproduce this using your suggestion. My example ran for 569 seconds. 

**We will need the issue narrowed down more - to specifically what to run to reproduce it.**

My test code:

```js
let times = 1000

for (let i = 0; i < times; i++) {
  it('.focus() - focus on a DOM element', () => {
    cy.visit('https://example.cypress.io/commands/actions')
    cy.get('.action-focus').focus()
      .should('have.class', 'focus')
      .prev().should('have.attr', 'style', 'color: orange;')
  })
}
```

![retries-ideas-updated](https://user-images.githubusercontent.com/1271364/53668326-91502400-3c41-11e9-807b-778de4b977ce.png)

**Comment by Saibamen** [comment]
@jennifer-shehane: This is Cypress 3.1.5 or unreleased Cypress 4? What is `Attempt 1` and `Attempt 2` buttons (labels?)?

**Comment by EduMotaControliD** [comment]
@jennifer-shehane: I have the same problem, I'm running only a inserts of users on a form, it work fine whether I set only litle numbers of users but if I increase that number like 30 or more the browser break. The browser also break when I try to run a bunch of tests, like 6 or more tests, which make others things. I'm running cypress in windows with git bash. 

**My cypress.json**
`
{
"animationDistanceThreshold": 5,
"baseUrl": "http://localhost:30445",
"blacklistHosts": null,
"chromeWebSecurity": true,
"defaultCommandTimeout": 4000,
"env": {},
"execTimeout": 60000,
"fileServerFolder": "",
"fixturesFolder": "cypress/fixtures",
"hosts": null,
"integrationFolder": "cypress/integration",
"modifyObstructiveCode": true,
"numTestsKeptInMemory": 0,
"pageLoadTimeout": 100000,
"pluginsFile": "cypress/plugins",
"port": null,
"reporter": "spec",
"reporterOptions": null,
"requestTimeout": 30000,
"responseTimeout": 50000,
"screenshotsFolder": "cypress/screenshots",
"supportFile": "cypress/support",
"taskTimeout": 60000,
"testFiles": "**/*.*",
"trashAssetsBeforeRuns": true,
"userAgent": null,
"video": true,
"videoCompression": 32,
"videoUploadOnPasses": true,
"videosFolder": "cypress/videos",
"viewportHeight": 660,
"viewportWidth": 1000,
"waitForAnimations": true,
"watchForFileChanges": true
}
`

**Version output**
`
$ npx cypress version                                                                                                                                                                                           Cypress package version: 3.1.5                                                                                                                                                                                  Cypress binary version: 3.1.5
--
`

**My set test**
`
it('Login', function ()
    {
        cy.visit('http://localhost:30445/#/login')
        cy.get('#usr').type('My_username')
        cy.get('#pwd').type('My_password')
        cy.get('#confirm').click()
    })

it('Set Users', function ()
    {
        cy.get('#listuser').click()
      
       for(var i =0; i < 300; i++)
       {
        cy.get('#addUser').click()
        cy.get('#name').type(`User Test ${i + 1}`)
        cy.get('#btnConfirm').click()
        }
})
`

**Comment by jennifer-shehane** [comment]
@Saibamen Whoops, this is the wrong screenshot. 😅 This is some work we are doing getting ready for test retries. https://github.com/cypress-io/cypress/issues/1313

**Comment by jennifer-shehane** [comment]
@EduMotaControliD Is there any way to provide some tests that break that we can run locally?

**Comment by Phillipe-Bojorquez** [comment]
This happens to me if I am running tests through the GUI and select run all specs.  I have 10 specs each one taking 1-3 minutes to run a piece.  I get 3/4ths done and get oh snap errors.  For me, it doesn't matter how long an individual test is running but a group of specs running over a certain time limit crashes my app.  I am uncertain how to share my tests since they concern private things my company would not like me to share.  Is there a way to spy on the error message for the GUI test runner that could help debug it?

my spec files have one describe block with a before each block and many it blocks underneath it. Our site does polling so during the tests there may be graphql queries being fired while i interact with the site.

**Comment by carloscheddar** [comment]
I found that having the dev tools open allows chrome to catch the `out-of-memory` error which causes the browser to pause(debugger state) instead of showing `aw snap`. If you wait a bit for memory to be available then you can click on the play button and the tests will continue. It's not ideal but at least I can finish testing the file.

**Comment by juristr** [comment]
Suffering the same issue. Apparently the `"numTestsKeptInMemory": 0,` solves it for me (at least for now)

**Comment by shaunswales** [comment]
Sorry I didn't realise this was still open, yes that is what I needed to implement.

The reason being within windows the application is a 32-bit application, with the tests kept in memory this meant that everything within the DOM for each action was stored. This eventually went over the memory limit for a 32-bit application.

**Comment by scharf** [comment]
# How to reproduce the problem

 To reproduce it, duplicate your tests many times and then run the suite. The more complex the pages are the less tests you need.

## The problem is: chrome runs out of memory (for the snapshots)

The problem is clearly that chrome runs out of memory. What you will see that the memory goes up to about 2.5Gb (on my mac) and then just before it fails the tests run slower and slower (this is typical for running out of memory: the garbage collector takes more and more time) until you see the `Aw, Snap!`

![image](https://user-images.githubusercontent.com/3731059/59566419-64911280-9060-11e9-915b-f80f4ed0cfdb.jpeg)

**Side note:** I wonder why only few people stumble over this problem. We have only 80 tests and that covers about 10% of our app (it fails at test 79). Either our pages are overly complicated or other teams don't run too many tests. This limitation is a real problem for us, because we cannot expand the number of tests.

## Why "numTestsKeptInMemory": 0,` is not a good solution

If I add `"numTestsKeptInMemory": 0,` to  `cypress.json`, it solves the problem but then I cannot dive into a failed test. I think it means, that keeping all snapshots for many tests on a complicated application takes too much memory.

# Proposals

## Quick solutions

- If I add something `"numTestsKeptInMemory": 10,` it keeps the last `10` tests. I would be much better to keep the last `10` *failed* tests. I am not interested in history of successful tests....

- Allow to run only some directories. At he moment you can either run a single test or all tests but I see no way to run the tests in a subdirectory

## Real solution

- If the app detects that the snapshot take too much memory, drop successful snapshots and add an indicator that the snapshot  has been dropped.
- The problem with `"numTestsKeptInMemory": 10,` (even if it keeps all failed snapshots) is that it is a global configuration. I think the user should be able to change it when a test is run and it should fall back to cleaning up memory automatically.

**Comment by CoryDanielson** [comment]
@scharf the memory leak and performance issues that you're experiencing are likely fixed with #4068 which is pending a release. The root cause was performance and memory leaks caused by external stylesheets.

**Comment by scharf** [comment]
@CoryDanielson is there a way to try the pending release (a kind of pre-release)?

**Comment by bahmutov** [comment]
@scharf there is a way to install pre-release version (when a commit has been merged into `develop` branch), it is complex though, see https://docs.cypress.io/guides/getting-started/installing-cypress.html#Install-pre-release-version

**Comment by scharf** [comment]
@CoryDanielson I installed the newest version (https://github.com/cypress-io/cypress-test-example-repos/commit/842608ef90bf4fdf49e36e035c0fccc618a5d836) and it was running 360 tests without problem (before it was failing after 80 tests or so).

**I can confirm that it is now much more scalable....**

**Comment by Domino987** [comment]
When can we expect that fix to be in the stable version?

**Comment by CoryDanielson** [comment]
It was released in 3.3.2

**Comment by Domino987** [comment]
I see because I still have that problem. I will look more into it. Thanks.

**Comment by chaoyangnz** [comment]
in my case, I installed a plugin `cypress-log-to-output` which causes the crashing. So disable your plugins as much as possible. Then isolate the issue.
Sometimes, a plugin is not well tested and add the unpredictable possibilities

**Comment by flotwig** [comment]
@chaoyangnz can you open an issue on the `cypress-log-to-output` repo detailing the crash it caused? https://github.com/flotwig/cypress-log-to-output I would like to fix that if possible, wasn't aware of it til just now.

FYI - make sure you're on version 1.0.7 of the plugin if you're using Cypress >= 3.5.0, there was a breaking change.

**Comment by chaoyangnz** [comment]
@flotwig thanks for your fast response. Actually I am not quite sure that is caused by the plugin. But I tried a lot of option, the final rescue is when I disabled the plugin, then everything is working.

I will isolate the issue, and add more details in your repo. thanks

**Comment by jnis77diver** [comment]
So, I experienced the "Aw Snap" issue when I added the following to my module.exports in plugins/index.js and tried to run cypress with `npx cypress open`. It would cause Chrome to crash immediately with the "Aw Snap" message.

```
  on("before:browser:launch", (browser, launchOptions) => {
    if (browser.family === "chromium") {
      launchOptions.args.push("--enable-logging", "--v=1");
      return launchOptions;
    }
  });
};
```

Removing it made Cypress open normally again.

**Comment by dudziakm** [comment]
for me, a good solution was to turn off video recording and compressing (`"video": false`, in `cypress.json`).
Of course, this is not a perfect solution :(

**Comment by DRiewaldt** [comment]
After updating to 5.0.0 I am getting this constantly while writing a new test.  I'm using the Test Runner to run the test as I write it to iterate, and sometimes it will just randomly go to Aw, Snap.  This doesn't appear to be linked to any single IT block, and there is only this one test running.

It might can pass all IT blocks, and then just aw, snap.  I might run it once, no issue, then run it again without anything changing and it Aw, Snaps.

I found the memory is climbing with every run, and it's not lowering the memory in any way.  Could this be a memory leak?

My past tests that never had this issue are now also having this occur, again it appears random. If I close the test runner and open it again, it might still crash right away or it might work.  At this point i'm at a 30-40% success rate that the test runs without an aw, snap.

Unfortunately, I can't give code to our site.  Also, with the Test Runner crashing constantly, I can't find any specific IT block that might be causing it either, or I'd paste that test code in.

Are others seeing an increase in these Aw, Snap errors?  I'm now running 5.2.0 and it's still having the same issues.

**Comment by kristiehowboutdat** [comment]
After updating to 5.2.0 from 4.5.0, we are experiencing this issue consistently. Running a single test triggers `Aw, snap` in Chrome 83. I can run more tests in Firefox 77 before it hits the `Aw, snap`. We did not hit this in 4.5.0

**Comment by engmagdy87** [comment]
I'm facing the `Aw, snap` with `cypress/included:5.4.0` and 
```
"numTestsKeptInMemory": 0,
  "video": false,
```

**Comment by richtera** [comment]
I am still seeing this with Chrome 101 and Cypress 
Cypress package version: 9.6.0
Cypress binary version: 9.6.0
Electron version: 15.5.1
Bundled Node version: 16.5.0
It seems to work fine using Elektron 94, but both Chromium and Chrom are causing Aw, Snap during running long tests.
On the Mac I am seeing it usually work the first time, but when running with --watch test script changes will cause it to try and run the scripts again and then fails with Aw, Snap. When running on Windows, WSL, X11 it seems to happen all the time. With numTestsKeptInMemory=0 it does go through, but it's pretty useless since I can see failures and successed, but there is no way to see what actually failed.

**Comment by richtera** [comment]
Argh even Elektron is not 100% reliably and shows an empty screen unless I manually execute one test script at a time using --watch

**Comment by b-pmcg** [comment]
> > Try adding
> > ```json
> > {
> > "numTestsKeptInMemory": 0,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In your `cypress.json`. Browser will not crash. It will work.
> 
> I found this issue in Chrome 95 with Cypress 8.7
> 
> I suggest anyone else to use this solution.

This solution doesn't work if you want to review and debug failing tests in the browser

**Comment by richtera** [comment]
@b-pmcg using numTestsKeptInMemory is unfortunately not a useful solution because if you're running with --watch then you need to keep the snapshots which cause the problems to see anything (especially because 0 won't even keep the currently failing set of snapshots in memory.) I have not actually seen the error when not running with --watch in which case snapshots are also not required, but then without video and combing through those videos it's difficult to develop test scripts. I think there needs to be a better solution or a way to save and restore snapshots from disk. Another thing that might be good is to be able to run several tests (not all) but be able to select a few, run them and see the results. Basically I have about 40 tests which will fail if I run them all, but if I run one at a time I will be there about 1/2 hour. It would be nice to be able to run 20 and then run another 20 without needing to change the code to skip some and not others. Then I can easily exclude the tests that take up too much memory and run them at the end separately.

**Comment by burkedavid** [comment]
Getting this regularly will long test run in Chrome locally. all the below set

  "numTestsKeptInMemory": 0,
  "video": false,
  "defaultCommandTimeout": 10000,

**Comment by laerteneto** [comment]
Getting this as well with 

"numTestsKeptInMemory": 10,
"video": true,
"defaultCommandTimeout": 15000,

**Comment by ezrag26** [comment]
Still happening on 10.3.0. I can't get through more than 5 minutes of tests before Chrome runs out of memory.

**Comment by navdeepdevrepublic** [comment]
> Still happening on 10.3.0. I can't get through more than 5 minutes of tests before Chrome runs out of memory.

I have raised this new issue for the same context https://github.com/cypress-io/cypress/issues/23131

**Comment by kolorfilm** [comment]
same problem with the lastest cypress version :-(

**Comment by Prashant-Kan** [comment]
Same problem since cypress v8.3
I think this requires urgent look 
because its getting worse when we have to use numTestsKeptInMemory:0 every time

**Comment by anilpujaraofficial** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/65593381/184064383-0c8f8406-4d4f-48dc-9ead-930fa5bd400a.png)

**Comment by SinghPramender** [comment]
Same problem is happening in the version 9.7.0 and unable to run my test cases in headed mode. Need to fix this issues.
![image](https://user-images.githubusercontent.com/54567831/185851857-a71e71ff-5098-422f-ac20-1876ff8df76a.png)

**Comment by navdeepdevrepublic** [comment]
#23193 #23131 Tickets for same issue

**Comment by chughes87** [comment]
My team was struggling with this issue recently. We found that using Chrome 94 (instead of 104) resolved the issue for us.

**Comment by theTestingApproach** [comment]
Got this issue today with cypress 9.5.2..I have 16 specs and it crashed in the 10th one. This happened when using the cypress GUI..If any other details is needed pls let me know.

**Comment by howard-zhang** [comment]
Got this issue with Cypress 8.4.1 and the runner crashed with out of memory error after running a couple of tests out of 12 total tests.

**Comment by mehran75** [comment]
Same issue

**Comment by JohnSmithyy** [comment]
Same issue and I tried all the solutions users posted above.

**Comment by CoryDanielson** [comment]
There appears to be a bug with Chrome 104 that has reduced memory limits for a tab (possibly). One of the comments even mentions Cypress crashing in 104, but not 103
- https://support.google.com/chrome/thread/174889666/increasing-the-memory-limit-on-chrome-v104?hl=en

You may also benefit from running garbage collection between tests, if you aren't already. For cypress 10+ users, the changes recommended here are different because of the Cypress changes to the plugins file.
- https://github.com/cypress-io/cypress/issues/8525#issuecomment-715353672

**Comment by JohnSmithyy** [comment]
> There appears to be a bug with Chrome 104 that has reduced memory limits for a tab (possibly). One of the comments even mentions Cypress crashing in 104, but not 103
> 
> * https://support.google.com/chrome/thread/174889666/increasing-the-memory-limit-on-chrome-v104?hl=en
> 
> You may also benefit from running garbage collection between tests, if you aren't already. For cypress 10+ users, the changes recommended here are different because of the Cypress changes to the plugins file.
> 
> * [Reduce Memory Usage with window.gc() #8525 (comment)](https://github.com/cypress-io/cypress/issues/8525#issuecomment-715353672)

Enabling garbage collection between tests have not worked either unfortunately.

**Comment by DomyNithanth** [comment]
@JohnSmithyy 
I was getting this Out of memory 'Aw, Snap' issue for the past two weeks starting from **10th Aug 2022** to be exact. Current Cypress version : 10.3.0.
After that, used the `numTestsKeptInMemory: 0` in config and it did work for a while, but after few days the issue was observed again frequently. 

On further observation it was observed that, chrome version used was 104 from **10th Aug 2022**.
This observation validates the above comment

**Comment by scorpyto** [comment]
Today the issue still persists. Latest version of Cypress - v12.9.0, latest version of Chrome - v111. Running tests for more than 5 mins causes the "Aw snap" error. Please, you need to find a stable solution for cypress open. It is not suitable for a big project when people are relying on automation tests...

**Comment by burkedavid** [comment]
> Today the issue still persists. Latest version of Cypress - v12.9.0, latest version of Chrome - v111. Running tests for more than 5 mins causes the "Aw snap" error. Please, you need to find a stable solution for cypress open. It is not suitable for a big project when people are relying on automation tests...

@scorpyto maybe try   experimentalMemoryManagement: true in cypress.config.js ?

**Comment by scorpyto** [comment]
> @scorpyto maybe try experimentalMemoryManagement: true in cypress.config.js ?

already Implemented :/

**Comment by nagash77** [comment]
Hi @scorpyto Can you please open a new issue for your specific use case with a reproducible example?  We will be happy to look at that.

**Comment by scorpyto** [comment]
> Hi @scorpyto Can you please open a new issue for your specific use case with a reproducible example? We will be happy to look at that.

`  "experimentalMemoryManagement": true` didn't help but 
`  "numTestsKeptInMemory ": 0` seems to work fine at the moment (35 mins tests). Will try later with more tests.
My mistake was that it was set to: 
 `  "numTestsKeptInMemory ": true`

**Comment by aream-tebra** [comment]
Same problem.  Adding numTestsKeptInMemory=0 in cypress.config.js fixed it (default is 50).  Full instructions & example here:
https://docs.cypress.io/guides/references/configuration

**Comment by Xiomycm15** [comment]
Hi I am also facing this problem. I added   "numTestsKeptInMemory ": 0 in the **cypres.config.js**  this way and now happily working: 
```js
const { defineConfig } = require("cypress");
const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = defineConfig({
  numTestsKeptInMemory: 0,
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
      on('file:preprocessor', cucumber())
    },
    specPattern: "cypress/e2e/Features/*.feature",
  },
});
```
