### ISSUE TITLE
Streaming compilation failed. Falling back to ArrayBuffer instantiation.  TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

### ISSUE THREAD

**Issue by joshpzero** [cypress-io/cypress#19081]
### Current behavior

When testing a Blazor Application with Cypress version 9 and above the following error occurs when the application is run in the Cypress Browser. The latest working fix is in 8.7.0

`Streaming compilation failed. Falling back to ArrayBuffer instantiation.  TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.`

This causes error in rendering the application as we expect. 

### Test code to reproduce

This is unrelated to test code, I have reproduced this with no test code apart from authorisation.

### Cypress Version

9.0.0, 9.1.0

**Comment by chrisbreiding** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment in this issue with a reproducible example and we will consider reopening the issue.
