### ISSUE TITLE
Indeterminate checkbox state doesn't get changed via uncheck({ force: true })

### ISSUE THREAD

**Issue by sturmery** [cypress-io/cypress#19098]
### Current behavior

Cypress does not uncheck checkboxes that have indeterminate state.

### Desired behavior

Cypress should detect that it's an indeterminate checkbox, then click on it twice to uncheck.

### Test code to reproduce

```js
cy.get("input[aria-label='Toggle Select All Columns']")
  .uncheck({ force: true })
```

### Cypress Version

9.1.0.1027187

### Other

https://css-tricks.com/indeterminate-checkboxes/

**Comment by chrisbreiding** [comment]
I reproduced this with the following code:

index.html

```html
<input type="checkbox" />
```

spec.js

```js
it('unchecks indeterminate checkbox', () => {
  cy.visit('/index.html')
  cy
  .get('input[type=checkbox]')
  .invoke('prop', 'indeterminate', true)
  .uncheck()
  .should('not.be.checked')
})
```

After which the checkbox still appears indeterminate. It's worth noting that this is only a visual issue. The above test passes, because the state of the checkbox is correctly changed to unchecked.

I think Cypress could handle this though. On uncheck, we could ensure the `indeterminate` prop is switched to `false`. This will be a pretty low priority to fix, but we would welcome a PR for it.

**Comment by anthonygedeon** [comment]
I'll like to tackle this if no one else is working on this issue currently.

**Comment by kshastri** [comment]
I would like to work on this issue, if someone else is not working on this?
