### ISSUE TITLE
.npmrc is ignored during npm i, cypress download failes

### ISSUE THREAD

**Issue by TimoPot** [cypress-io/cypress#19227]
### Current behavior

![image](https://user-images.githubusercontent.com/2789625/144558660-9318afac-93a4-4675-95d9-b166e4fc080b.png)

npm i tries to download binary while it shouldn't because of CYPRESS_INSTALL_BINARY=0 in .npmrc (see below)

http_proxy=http://....                                                               (adress to company proxy)
https_proxy=http://....                                                               (adress to company proxy) 
no_proxy=.local,localhost,127.0.0.1
noproxy=.local,localhost,127.0.0.1
progress=true
registry=https://nexus.ontwikkel.local/                                 (adress to company nexus)
fetch-retry-mintimeout=60000
timeout=60000
CYPRESS_INSTALL_BINARY=0

.npmrc is ignored, or CYPRESS_INSTALL_BINARY=0 is ignored 
when using:
node 16.13.0 
npm 8.1.0

The download is skipped when using:
node 12.18.0
npm 6.14.11

### Cypress Version

^8.7.0

### Package Manager

npm

### Operating system

Mac

**Comment by d-henn** [comment]
I am also experiencing this issue. The `.npmrc` seems to be ignored even though in the code it looks like it _"should"_ grab the correct value from the config when ran through `npm` according to [cypress/cli/lib/tasks/install.js#L243](https://github.com/cypress-io/cypress/blob/v9.1.1/cli/lib/tasks/install.js#L243). Just want to point out this happens for _all_ `npm_config_*` settings not just `CYPRESS_INSTALL_BINARY`.

Tried on several versions of **cypress** with no luck:

- `9.1.1`
- `9.1.0`
- `8.x.x`
- `7.x.x`

**Comment by d-henn** [comment]
Also facing this same issue. According to [/cli/lib/utils.js#L459-L491](https://github.com/cypress-io/cypress/blob/v9.1.1/cli/lib/util.js#L459-L491) in conjunction with something like [/cli/lib/tasks/install.js#L243-L264](https://github.com/cypress-io/cypress/blob/v9.1.1/cli/lib/tasks/install.js#L243-L264), it looks as though it should be taking what's a part of the `.npmrc` but just isn't.

## Replication

I want to preface saying I tried running this on several versions of `cypress` not just `9.1.1`:

- `9.1.1` & `9.1.0`
- `8.7.0` & `8.6.0`
- `7.7.0`
 
The samples below are ran going after `9.1.1`.

### Versions

| tech | version |
| ---- | -----|
| npm | `8.1.0` |
| node | `v17.0.1` |
| cypress | `9.1.1` | 
| operating system | `macOS 11.0 Big Sur` & `Ubuntu 20.04` & `Windows 10` |

### Sample `.npmrc`
Tried using `.npmrc` with both _lower_ and _upper_ case with no luck. Below is a sample:

```text
# Example .npmrc
CYPRESS_INSTALL_BINARY=https://example.com
cypress_install_binary=https://example.com
```

### Sample `package.json`

```json5
{
  "name": "cypress-example",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo test"
  },
  "devDependencies": {
    "cypress": "^9.1.1" // <-- after successfully installing manually (not a part of the test)
  }
}
```
### Commands

With the configured `.npmrc` and the first command below, I don't see any calls using the `CYPRESS_INSTALL_BINARY` config. In fact it should fail because I am pointing at a non-existent location (not expected behavior).

<details>
<summary>First command: <code>DEBUG=cypress:* npm i --save-dev cypress@9.1.1</code></summary>                

```shell
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 163 packages, and audited 164 packages in 37s

24 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
</details>

So the `.npmrc` config did not work, the next thing I tried to be sure I had it correct was passing the `env` variable to the command. Received an expected output for this one. 

<details>
<summary>Second command: <code>DEBUG=cypress:* CYPRESS_INSTALL_BINARY=https://ex.com npm i --save-dev cypress@9.1.1</code></summary>                

```diff
 verbose node v17.0.1
 verbose npm  v8.1.0
 error code 1
 error path xxxxx
 error command failed
 error command sh -c node index.js --exec install
 error ⚠ Warning: Forcing a binary version different than the default.
 error
 error   The CLI expected to install version: 9.1.1
 error
 error   Instead we will install version: https://ex.com
 error
 error   These versions may not work properly together.
 error
 error Installing Cypress (version: https://ex.com)
 error
 error [STARTED] Task without title.
 error The Cypress App could not be downloaded.
 error
 error Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
 error
 error Otherwise, please check network connectivity and try again:
 error
 error ----------
 error
 error URL: https://ex.com
 error Error: connect ECONNREFUSED 52..23.:
 error
 error ----------
 error
 error Platform: linux-x64 (Ubuntu - 20.04)
 error Cypress Version: 9.1.1
 error  cypress:cli installing Cypress from NPM
 error  cypress:cli installing with options {}
 error  cypress:cli version in package.json is 9.1.1
+ error  cypress:cli Using CYPRESS_INSTALL_BINARY from environment variable
+ error  cypress:cli Using CYPRESS_INSTALL_BINARY from environment variable
+ error  cypress:cli using environment variable CYPRESS_INSTALL_BINARY "https://ex.com"
 error  cypress:cli Reading binary package.json from: xxxxx
 error  cypress:cli looking for versionSpecifier { dir: 'xxxxx' }
 error  cypress:cli looking for versionSpecifier { dir: 'xxxxx' }
 error  cypress:cli looking for versionSpecifier { dir: 'xxxxx' }
 error  cypress:cli looking for versionSpecifier { dir: 'xxxxx' }
 error  cypress:cli looking for versionSpecifier { dir: 'xxxxx' }
 error  cypress:cli looking for versionSpecifier { dir: 'xxxxx' }
 error  cypress:cli looking for versionSpecifier { dir: 'xxxxx' }
 error  cypress:cli looking for versionSpecifier { dir: 'xxxxx' }
 error  cypress:cli looking for versionSpecifier { dir: 'xxxxx' }
 error  cypress:cli reached FS root with no versionSpecifier found
 error  cypress:cli finished looking for versionSpecifier { versionSpecifier: undefined }
 error  cypress:cli installed version is null version needed is https://ex.com
 error  cypress:cli no binary installed under cli version
 error  cypress:cli checking local file xxxxx/https:/ex.com cwd xxxxx
 error  cypress:cli preparing to download and unzip version  https://ex.com to path xxxxx
 error  cypress:cli version is already an url https://ex.com
 error  cypress:cli needed Cypress version: https://ex.com
 error  cypress:cli source url https://ex.com
 error  cypress:cli downloading cypress.zip to "/tmp/cypress-.zip"
 error  cypress:cli Downloading package {
 error   url: 'https://ex.com',
 error   proxy: null,
 error   downloadDestination: '/tmp/cypress-.zip'
 error }
 error  cypress:cli version is already an url https://ex.com
 error  cypress:cli URL: https://ex.com
 error Error: connect ECONNREFUSED xxxxxx
 error [FAILED] The Cypress App could not be downloaded.
 error [FAILED]
 error [FAILED] Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
 error [FAILED]
 error [FAILED] Otherwise, please check network connectivity and try again:
 error [FAILED]
 error [FAILED] ----------
 error [FAILED]
 error [FAILED] URL: https://ex.com
 error [FAILED] Error: connect ECONNREFUSED xxxxx
 error [FAILED]
 error [FAILED] ----------
 error [FAILED]
 error [FAILED] Platform: linux-x64 (Ubuntu - 20.04)
 error [FAILED] Cypress Version: 9.1.1
 verbose exit 1
```
</details>

### Conclusion

Based on reading through several threads here and going over the official https://cypress.io documentation, I thought the first command would operate in the same manner the second command did. But unfortunately did not get the expected results.

It's highly possible I am way off base here and read incorrectly how this process is supposed to work 😄 , if so please let me know!

Thank you for all you do, love this product and can't wait to start using it in a more complex manner!

**Comment by Jeppeer** [comment]
Any progress on this? I am facing the same issue.
