### ISSUE TITLE
Reading a binary fixture get it's content changed

### ISSUE THREAD

**Issue by andrealmieda** [cypress-io/cypress#19344]
### Current behavior

In the process of updating from `cypress@8` to `cypress@9`, It was noticed that intercepting a binary file had changed, making the intercepted file to be corrupted (not in the expected format).

Here's a screenshot of the update and the files diffing
![Screenshot 2021-12-13 at 11 19 09](https://user-images.githubusercontent.com/4404448/145812445-da6e3bd2-984a-45a7-8e7d-442808f161fc.png)

### Desired behavior

When reading a binary fixture the content of it shouldn't be changed when serving it (via `cy.intercept`)

### Test code to reproduce

https://github.com/andrealmieda/react-cypress-boilerplate

I created a small test to download the intercepted binary file and then manually check it on the terminal 

### Cypress Version

9.1.1

**Comment by emilyrohrbough** [comment]
@andrealmieda Thank you for creating this issue and providing a reproducible example of the behavior you are seeing. Using your example project, I was able to re-create the issue you are seeing.

It seems this issue caused by the same regression causing #19330. The details of the regressions can found on https://github.com/cypress-io/cypress/issues/19330#issuecomment-991316383. A slight change will be needed in Cypress to maintain the previous functionality.
