### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by AugustoSandim** [cypress-io/cypress#1935]
### Current behavior:
<img width="1008" alt="screen shot 2018-06-12 at 16 07 34" src="https://user-images.githubusercontent.com/4098679/41315173-1e4afe58-6e65-11e8-8faf-a9de44e067ed.png">

### Desired behavior:

Gives me a confirmation prompt on click button.

### Steps to reproduce:

<img width="346" alt="screen shot 2018-06-12 at 17 23 34" src="https://user-images.githubusercontent.com/4098679/41315273-6353ef50-6e65-11e8-821f-3feb56bfe778.png">

### Versions

Cypress: 3.0.1
OS: macOS High Sierra
Chrome: v66

**Comment by jennifer-shehane** [comment]
If your application is using a `window.confirm()`, you'll want to handle that event programmatically in your tests. [See the docs for listening to this.](https://on.cypress.io/catalog-of-events#Window-Confirm)

As for the Uncaught error, we will need a reproducible example - with tests to run in order to track down why that is happening.

**Comment by AugustoSandim** [comment]
@jennifer-shehane Thanks, it's working now.

**Comment by mpacary** [comment]
Got exact same "Cypress logging" error on a project using Quasar framework (which uses VueJS) ; happens only when using `$this.router.push(...route...)` in a `mounted()` method of a component.

Seems like [the fix is pretty simple & already done for future version Cypress 4](https://github.com/cypress-io/cypress/pull/2880/files#diff-cd9e5c273c28d1b98e0e50633e67e594).

➡️ Dirty workaround for Cypress 3.x:
* For a Windows installation, open file **C:\Users\<username>\AppData\Local\Cypress\Cache\<cypress-version>\Cypress\resources\app\packages\runner\dist\cypress_runner.js** (warning, heavy file 6MB, an editor like [Sublime Text 3](https://www.sublimetext.com/3) can handle it)
* Find the line containing exactly: `testId: state("runnable").id` and change it to `testId: state("runnable") ? state("runnable").id : null`
* Save & close the file

Any chance that this could be addressed in future 3.x versions too?
Is there any info about release date of 4.x?

**Comment by jennifer-shehane** [comment]
@mpacary Interestingly enough, I just recently fixed this error while running across it while working in Cypress's in `develop`. The code was updated to check that state("runnable") is defined before getting it's id prop here: https://github.com/cypress-io/cypress/pull/3927

This PR is pending release in version 3.3.0

Yeah, I wish this had been pulled in from Version 4, but it likely wasn't because there were no existing issues open for this error that we found. I'm not sure exactly why you're getting the error in this situation, it should easily happen. Do you not see any subsequent errors after fixing this line of code in your example?

**Comment by mpacary** [comment]
@jennifer-shehane Thanks for replying & adding the fix to upcoming version 3.3.0 👍 

> Do you not see any subsequent errors after fixing this line of code in your example?
I've used Cypress quite intensively after fixing the issue ; no subsequent errors appeared.
