### ISSUE TITLE
Screenshot pixel mismatch from the second run via Cypress Runner

### ISSUE THREAD

**Issue by happyali** [cypress-io/cypress#19354]
### Current behavior

I have a simple test to take screenshots of multiple elements on the page
And store them in one project folder

When I rerun the test via Cypress Runner then either of the image comparison will fail with error message in cypress console:
"Image was 0.637741756499683% different from saved snapshot with 1372 different pixels." or similar.
but when I inspect the failed image capture, I see only the rendering change in image which is slightly up or down with respect to the image reference.

### Test code to reproduce

<img width="952" alt="minor_diff" src="https://user-images.githubusercontent.com/21300342/145928479-88a3a1e1-e9dc-4e9d-a699-699f5f83c2f0.png">

### Cypress Version

9.1.1

### Other

I have used this to setup https://github.com/jaredpalmer/cypress-image-snapshot

Below is from my package json:
 "dependencies": {
    "cypress-image-snapshot": "^4.0.1",
    "cypress-match-screenshot": "^1.1.0",
    "cypress-xpath": "^1.6.2",
  },
  "license": "ISC",
  "devDependencies": {
    "cypress": "^9.1.1",
    "mocha": "^9.1.3"
  }
}

**Comment by sainthkh** [comment]
Sorry for the late reply. 

It seems that this issue is more related with `cypress-image-snapshot` project rather than this one.

**Comment by Zazador** [comment]
@happyali  - Out of curiosity, did you begin seeing this behavior in Chrome 97?

**Comment by happyali-qa** [comment]
yes, Version 97.0.4692.71

**Comment by Zazador** [comment]
@happyali-qa - we're seeing very similar behavior in our tests after going to Chrome 97. Were you able to pinpoint a fix? Even when we update baselines, the next run fails.

**Comment by evantd** [comment]
Just in case it's not entirely clear from the above, the snapshots change a little bit each time we run them, so it's not a matter of updating them once in order to move to Chrome 97. If we switch to Chrome 97, update the snapshots, and run the tests again, there are more diffs. So it seems like the font rendering is in some way non-deterministic.

I think we only saw it with bold text (`font-weight: 700`), using Noto Sans fetched from Google via https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap but not all bold text seemed to be affected. There was some that never seemed to show the problem, and some that did, but I was not able to figure out what differentiated them. There was a list where the last items in the list seemed to be consistent, while earlier items in the list were inconsistent.

Chrome 96->97 includes a lot of font-related changes. We've tried using `font-synthesis: none`, `text-rendering: geometricPrecision`, and `--disable-features=COLRV1Fonts`. We were already running with `--font-render-hinting=none`, but we also tried dropping it. For now, we've worked around it by sticking with Chrome 96, but that's not going to be a good option for long. We could potentially try `--disable-font-subpixel-positioning` and/or `--enable-font-antialiasing`, though I'm not sure if anything changed with those from Chrome 96->97.

**Comment by evantd** [comment]
It looks like `--disable-font-antialiasing` takes care of *most* of the issue, though we also had to *stop* using `--font-render-hinting=none`.  We're still seeing problems specifically in bits of text that have a copyright symbol. I'm guessing it might have something to do with the browser falling back to a different font in order to fill in a missing glyph, and then how it combines the fonts might be non-deterministic? I saw the same issue in bits of text that had emoji (special region indicator flags), which were displayed as tofu, and yet even the tofu showed rendering differences from one run to another. Installing an Emoji font on the system (Noto Emoji on CentOS 7) resolved that issue, leaving only the copyright one.

**Comment by evantd** [comment]
`--font-render-hinting=full` (the default) gave the best results for me. All the others had more trouble with inconsistent snapshots. That is, when I updated snapshots and then immediately re-ran the tests, `--font-render-hinting=full` resulted in the fewest failures.

**Comment by maslo88** [comment]
@evantd @sainthkh @happyali it has been a while since this issue was updated, did you make any progress or find any solution please? thx

**Comment by evantd** [comment]
Not really, though we did manage to make the problem smaller and work around what remained. With the setup from my last comment, we only had trouble where we used the copyright symbol, so we ended up swapping them out for a simple C before the snapshot and them swapping the normal content back after the snapshot.

**Comment by hongdeyuan** [comment]
> Not really, though we did manage to make the problem smaller and work around what remained. With the setup from my last comment, we only had trouble where we used the copyright symbol, so we ended up swapping them out for a simple C before the snapshot and them swapping the normal content back after the snapshot.

@evantd 
Hey, I also encountered the same problem. Is there a better solution?

**Comment by SunStupic** [comment]
@hongdeyuan Hi, did you find any workaround for this issue?
