### ISSUE TITLE
cy.screenshot scrolls background when modal displayed  

### ISSUE THREAD

**Issue by brett-burman** [cypress-io/cypress#19438]
### Current behavior

main page has "overflow-y: hidden;" which stops the background page scrolling when a modal is displayed which seems to be ignored when cy.screenshot is called resulting in the below screenshot where the top of the modal is captured multiple times.

![image](https://user-images.githubusercontent.com/76097494/146902544-94b9ee62-117e-4358-97e2-6a9b8e254f30.png)

### Desired behavior

When cy.screenshot is called the "overflow-y: hidden;" setting should be recognised and only the modal scrolled as per functionality when manually navigating the page allowing the full modal to captured in a screenshot.

![image](https://user-images.githubusercontent.com/76097494/146903965-e31ca222-2500-421c-81ef-b25371b059d3.png)

### Test code to reproduce

customer data required to get to the page which can not be shared 

### Cypress Version

9.1.1

### Other

currently testing on latest chrome

**Comment by happycollision** [comment]
You may be able to get something _more_ usable—though still not _exactly_ what you've described—by targeting the modal directly for the screenshot, then adding some padding.

Something like this
```js
cy.get("#modal).screenshot({padding: 10})
```

Should yield something like this

<img width="337" alt="CleanShot 2021-12-21 at 15 05 14@2x" src="https://user-images.githubusercontent.com/3663628/146991130-06723a46-d6d8-4db0-8f4b-1c29b6a43adc.png">

(Assuming for argument's sake that `#modal` also encompasses the close button that floats above the main content area of the modal)

**Comment by brettburman-code** [comment]
@happycollision

Thanks for your reply, I had tried that and still get the same problem unfortunately, it attempts to take a full page screenshot 
as the modal is long but cy.screenshot still scrolls the background page rather than the modal


![Modal Issue -- Test](https://user-images.githubusercontent.com/76097494/147075707-0a6ea14e-cb8a-46f0-8446-31ec9d3964e1.png)

**Comment by sainthkh** [comment]
Confirmed with the code below:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
  <title>Document</title>
</head>
<body>
<div style="height: 1500px;background: blue">
  <!-- Button trigger modal -->
  <button type="button" id="modal-button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Launch demo modal
  </button>
  <h1>Hello World</h1>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div style="height: 1300px;">Body</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
</body>
</html>
```

```js
it('t', () => {
  cy.visit('fixtures/a.html')
  cy.get('#modal-button').click()
  cy.wait(700) // delay for modal to open
  cy.screenshot()
})
```

**Comment by EPGDigital-MW** [comment]
I've worked around this issue with bootstrap modals longer than the viewport. Bootstrap modals limit the height to viewport, which is where the issue is, and the modal doesn't scroll down the page.

The code gets the modal element, then checks the height of the content, if bigger than viewport, it adjusts the css position and height of the modal. I then capture the screenshot and clip to the size of the modal.

In my use case I only want a viewport screenshot to capture, I have a loop of modal item ids that I pass into the code to capture the screenshots

```javascript
// get the bootstrap .modal (item is the id)
cy.get('#' + item).then(($el) => {
    let modalHeight = $el.find('.modal-content').height();

    // viewport is 1600x1200 high
    if (modalHeight > VIEWPORT_HEIGHT - 100) {
        // change default modal properties, so it can scroll down the page, allows height to grow
        cy.get('#' + item).invoke('css', 'position', 'absolute');
        cy.get('#' + item).invoke('css', 'height', 'initial');

        // capture viewport, but clip back to size wanted with some extra padding
        cy.screenshot('modals/-' + item, { clip: { x: 0, y: 0, width: VIEWPORT_WIDTH, height: (modalHeight + 100) }});
    } else {
        // just capture viewport
        cy.screenshot('modals/' + item, { capture: 'viewport' });
    }
});
```

**Comment by Charles-Gerber** [comment]
### Another workaround - increase browser window's size

I have another workaround: increase viewport and browser window's size.
You can't do one withouth the other, otherwise cypress will still scroll => BUG happens.

#### 1 Do the screenshot using the "viewport" mode
#### 2 set the viewport to a big vertical size like 

`cy.viewport(1080, 1820)`

#### 3 increase browser's window size (4K)
The idea is to have a browser window big enough to print your viewport during screenshot without any scroll needed.

```
  e2e: {
    setupNodeEvents (on, config) {

      // We increase cypress browser window size to avoid the screenshot bug on the sidePanel
      // (only when running headlessly)
      // this will produce higher resolution images and videos
      // https://on.cypress.io/browser-launch-api
      on('before:browser:launch', (browser = {}, launchOptions) => {
        console.log(
          'launching browser %s is headless? %s',
          browser.name,
          browser.isHeadless
        )

        // the browser width and height we want to get
        // our screenshots and videos will be of that resolution
        const width = 2160
        const height = 3840

        console.log('setting the browser window size to %d x %d', width, height)

        if (browser.name === 'chrome' && browser.isHeadless) {
          launchOptions.args.push(`--window-size=${width},${height}`)

          // force screen to be non-retina and just use our given resolution
          launchOptions.args.push('--force-device-scale-factor=1')
        }

        if (browser.name === 'electron' && browser.isHeadless) {
          // might not work on CI for some reason
          launchOptions.preferences.width = width
          launchOptions.preferences.height = height
        }

        if (browser.name === 'firefox' && browser.isHeadless) {
          launchOptions.args.push(`--width=${width}`)
          launchOptions.args.push(`--height=${height}`)
        }

        // IMPORTANT: return the updated browser launch options
        return launchOptions
      })
    },
```

Here are some links to help you in that task:
https://www.cypress.io/blog/2021/03/01/generate-high-resolution-videos-and-screenshots/
https://docs.cypress.io/guides/references/migration-guide#Plugin-Event-beforebrowserlaunch

**Comment by nagash77** [comment]
I am going to close this issue as it is quite old at this point.  If folks are seeing this behavior in current versions of Cypress please open a new ticket with a reproducible example and we will be happy to investigate.

**Comment by IdleThought** [comment]
I am bothered by the fact this issue existed, a contributor was able to verify the issue existed, others found workaround because they also ran into the issue, and then it was simply closed because it was "old". As of right now using Cypress 13.6.3 I can verify this issue still occurs exactly as the original author described....

**Comment by jennifer-shehane** [comment]
@IdleThought We can reopen. It's hard to tell sometimes over time if an issue was resolved or not with little activity.

**Comment by evilaliv3** [comment]
Up to date we encounter this as well within the GlobaLeaks project 

<img width="1920" height="1719" alt="Image" src="https://github.com/user-attachments/assets/c6ac201c-471b-40c4-ba6f-035010df34c8" />
