### ISSUE TITLE
I have error with script in cypress

### ISSUE THREAD

**Issue by Peggy1012** [cypress-io/cypress#1945]
### Current behavior:

I have script and run in tests - I become error Uncaught TypeError: window.changeCti is not a function at <anonymous>:1:8, but in browser run script without problem. 
![ashampoo_snap_ctvrtek 14 cervna 2018_13h47m41s_003_](https://user-images.githubusercontent.com/22873782/41410592-37c280a6-6fda-11e8-8146-d968a46fd9e6.png)
![ashampoo_snap_ctvrtek 14 cervna 2018_13h49m11s_004_](https://user-images.githubusercontent.com/22873782/41410593-37e4f514-6fda-11e8-9d0e-275cbc26a238.png)

Cypress 3.0.1, Win 10

**Comment by jennifer-shehane** [comment]
This may be due to us attempting to get around framebusting. Could you try setting `modifyObstructiveCode: false` in your configuration and let me know if that error goes away? https://on.cypress.io/configuration#modifyObstructiveCode

**Comment by Peggy1012** [comment]
@jennifer-shehane This fix don't repair my issue.

**Comment by Peggy1012** [comment]
I have tests with 
cy.visit('/service/cti');
 cy.window().then((win) => {      cy.win.changeCti({'event':'Ringing','from':'777711101','to':'210','line':'210','uniqueid':'1478610236.1426','direction':'incoming'})
          })  

but, when I get DevTools after crash, DevTools have title without '/service/cti'

**Comment by jennifer-shehane** [comment]
The `win` here is the `window` yielded from `cy.window()`. You do not need to chain `win` off of `cy` after this. I believe that is why you are having this error, because `cy.win.changeCTI` is definitely not a function. Try the code below.

```js
cy.visit('/service/cti');
cy.window().then((win) => {
 win.changeCti({'event':'Ringing','from':'777711101','to':'210','line':'210','uniqueid':'1478610236.1426','direction':'incoming'})
})  
```

**Comment by Peggy1012** [comment]
When I use this code, become error win.changeCti is not function.
In devtools I can  use window.changeCti({"event":"Ringing","from":"575750981","to":"210","line":"210","uniqueid":"1478610236.1426","direction":"incoming"})

**Comment by brian-mann** [comment]
@Peggy1012 up above you showed a screenshot trying to use `window.changeCti` in your dev tools console.

This won't work because you need to change the page context in the console to be that of your app first. By default it is set to `top`, which is the Cypress frame (which doesn't know anything about your app). 

If you change the context to your app then you can use the console in the same way.

Cypress has native access to your window so I don't see any reason why `win.changeCti` wouldn't be a function. It makes me think that your JS must be loaded asynchronously and by the time you call `win.changeCti` it has not been loaded yet.

The problem is that you're using a `cy.then` which is only ever invoked once and will fail. If you use one of our other commands it will automatically retry.

```js
cy.visit('/service/cti')
cy.window().invoke('changeCti', { ... })
```

This will automatically retry the `.invoke` until that function is callable on the `<window>` subject. https://docs.cypress.io/api/commands/invoke.html

**Comment by Peggy1012** [comment]
@brian-mann ,  @jennifer-shehane  Thanks, very much. This code works.
