### ISSUE TITLE
@cypress/vue conflict with jest

### ISSUE THREAD

**Issue by estebanaragonc** [cypress-io/cypress#19472]
### Current behavior

When installing @cypress/vue to start component testing, the unit test based in Jest started to fail.

![image](https://user-images.githubusercontent.com/55291655/147260890-bea599ef-4bef-4acf-8779-3e5c7ab16c6c.png)

My tsconfig.json

```
{
...
"exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
...
}
```

my cypress/tsconfig.json

```
{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress", "@testing-library/cypress"]
  },
  "include": ["./**/*.ts"]  
}
```

### Desired behavior

![image](https://user-images.githubusercontent.com/55291655/147260764-5f963b8f-5aba-422e-98ad-51cc843f9daf.png)

### Test code to reproduce

There is not testcode to run.

### Cypress Version

"@cypress/vue": "^2.2.3", "cypress": "^9.1.1",

### Other

it seems that the expect on cypress overwrites the expect of jest.

Already tried:

- https://stackoverflow.com/questions/58999086/cypress-causing-type-errors-in-jest-assertions
- https://github.com/cypress-io/cypress-and-jest-typescript-example
- workaround of adding import { expect } from '@jest/globals';

**Comment by xiaoxiangmoe** [comment]
see also https://github.com/cypress-io/cypress/issues/2773

**Comment by xiaoxiangmoe** [comment]
Please not close it

**Comment by mike-plummer** [comment]
@xiaoxiangmoe This issue is quite old and references a version of Cypress from almost two years ago. If you are able to provide a reproduction case demonstrating this is still an issue using the latest versions of Cypress and Jest please open a new issue with an updated description, logs, and link to your reproduction.

Based on what information was provided in the original writeup I suspect that the given project was attempting to use a single `tsconfig.json` that pulled in Cypress *and* Jest which ended up polluting the global namespace as they overwrote each other. The solution would be to craft a `tsconfig.json` that pulls in only the libraries needed for each and use it for each run target
