### ISSUE TITLE
cy.run --headed --no-exit. Exits the browser after each spec.

### ISSUE THREAD

**Issue by scarsam** [cypress-io/cypress#19485]
### Current behavior

Trying out Cypress run with the headed and no exit option, but after each test, it still exits the test runner.

### Desired behavior

With the `--headed --no-exit` flag I expect the test runner to not close

### Test code to reproduce

I tried this with a fresh cypress installation. And ran the `run` command with one of the example specs included when you install Cypress.

`npx cypress run --headed --no-exit --spec "cypress/integration/1-getting-started/todo.spec.js"`

### Cypress Version

9.2.0

**Comment by ScriptyChris** [comment]
I have the same issue, though for me it happens without `--spec` param provided.

**Comment by ScriptyChris** [comment]
I noticed that the problem does not occur on version 9.1.1. @scarsam could you try to downgrade your Cypress and check if older version will also work for you?

**Comment by ejdaly** [comment]
v9.1.1 works for me also (v9.2.0 not working)

This also broken as a result: https://github.com/cypress-io/cypress/issues/4044

**Comment by mjhenkes** [comment]
This was introduced by #18896. By adding 'exit' to the [default config](https://github.com/cypress-io/cypress/blob/develop/packages/config/lib/options.ts#L144-L148) we elevated the exit key from being in the root options object (`options.exit`) to being nested in the config object (`options.config.exit`), preventing us from reading it in [run.js](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/modes/run.js#L1611). A fix could would be reading from reading the 'exit' option from `config.exit` instead of `options.exit` in the above file.

We also added defaults for [keystrokeDelay](https://github.com/cypress-io/cypress/blob/develop/packages/config/lib/options.ts#L207-L211) and [isInteractive](https://github.com/cypress-io/cypress/blob/develop/packages/config/lib/options.ts#L424-L428). We should confirm they are still being read correctly as well.

**Comment by scarsam** [comment]
Thanks, @ScriptyChris and @ejdaly. Downgrading to `9.1.1` works for me now.
