### ISSUE TITLE
Running cypress on angular2 quickstart

### ISSUE THREAD

**Issue by shauvik** [cypress-io/cypress#195]
I'm trying to write a simple cypress test against the angular2 quickstart but it doesn't seem to be working although the page loads correctly.

Here is the app: https://github.com/angular/quickstart

And this is the test:
```
cy.visit("http://localhost:3000/index.html", {timeout: 8000})
cy.get("h1").should("have.value", "My First Angular 2 App");
```

It fails with error:
```
CypressError: Timed out retrying: expected '<h1>' to have value 'My First Angular 2 App', but the value was ''
```

**Comment by brian-mann** [comment]
Whether you're testing Angular 1, 2, or anything else, Cypress doesn't care about it. As long as HTML is generated by the framework and is inserted into the DOM it'll work like everything else. :-)

The problem is that `<h1>` do not have `value`. Only `<input>` and `<option>` and `<textarea>` have value.

You're looking for 
```javascript 
cy.get("h1").should("contain", "My First Angular 2 App")
```
or more succinctly 

```javascript
cy.contains("My First Angular 2 App")
```

**Comment by brian-mann** [comment]
@jdhines can you provide a reproducible repo? What version of Cypress are you using? There were some issues with the proxy choking due to nonperformant regexp a few versions ago but have been fixed. Please open a new issue so we can investigate.

**Comment by jdhines** [comment]
Opened #1608
