### ISSUE TITLE
Cypress 9.x.x cannot read CYPRESS_env environment variable on Windows

### ISSUE THREAD

**Issue by zubinix** [cypress-io/cypress#19508]
### Current behavior

Windows environment variables not read correctly if CYPRESS_env is present as an environment variable. This was working with Cypress version 8.x.x

### Desired behavior

Windows environment variables should be readable by test scripts and cypress ui tool configuration.

### Test code to reproduce

In an CMD shell on Windows

set CYPRESS_env=uat

### Cypress Version

9.x.x

**Comment by pbadenski** [comment]
I'm having the same problem with CYPRESS_ENV on Mac with Cypress 9.5.0. Other CYPRESS_* environment variables work fine.

**Comment by pbadenski** [comment]
Any updates on this?

**Comment by will-banked** [comment]
+1 to this not working on Mac. Was using 8.7.0 and CYPRESS_ENV was read absolutely fine, but upgraded to 9.6.0 and CYPRESS_ENV now returns undefined. Am temporarily changing to use CYPRESS_ENVIRONMENT to store the environment we're in so that I can play around with the new cy.origin() stuff, but would like to move back.
