### ISSUE TITLE
Spy on response (without modifying) never works

### ISSUE THREAD

**Issue by z0d14c** [cypress-io/cypress#1954]
### Current behavior:

I want to spy on the response of a request that gets created when I click on a button so that I can capture the ID of the created object. Somewhat similar to the needs of those expressed in this closed issue: https://github.com/cypress-io/cypress/issues/937

I for the life of me cannot get this to work. I basically have a very minimal example:
```js
      //inside of it() block

      cy.server() 

      cy.route('POST', '/someurl/').as('createRequest')

      cy.get('#submit-button')
        .click()

      cy.wait('@createRequest').then(function(xhr){
        console.log('da thing happened ', xhr)
      })
```

It always ends up "Timed out retrying... 5000ms"
### Desired behavior:
I want to get inside the callback block that would allow me to capture the xhr response information.

### Steps to reproduce:

I didn't fork the repo because I think it is a simple case; if it passes in tiny-cypress-repo but not my application, then it seems like cypress is not scaling to real applications for this use case.

### Versions

Cypress 2.1.0

**Comment by z0d14c** [comment]
I also tried several different variations for the URL matcher, including regex.

I feel there may be some gap in the cypress engine where if a request has already fired and you wait for it, it never catches it? but I can't wait for it before I fire off the request.

**Comment by brian-mann** [comment]
You need to provide screenshots because the Cypress Command Log will show you everything you need to see in order to understand what's happening. With that we can quickly tell you what you're doing.

Screenshots of dev tools would also be helpful. I promise that the network stubbing works as documented, its used by thousands of different projects.

Using `cy.wait()` is built to work for requests that have already gone out - thats why it's deterministic. Cypress internally increments the number of times it's seen a request match a `cy.wait()`. This is the first time you're waiting on it, so it will wait for the 1st request to match it. Had it already gone out, it would have resolved instantly. 

You can look at our kitchen sink or our recipes for more examples, I promise, they all work.

**Comment by z0d14c** [comment]
Ok, thanks @brian-mann I appreciate the reassurance, will take a closer look at your documents and update/close this appropriately

**Comment by z0d14c** [comment]
Ok so I'm pretty confused 
<img width="631" alt="screen shot 2018-06-15 at 8 00 33 pm" src="https://user-images.githubusercontent.com/5269809/41495204-dae329c8-70d6-11e8-935f-2feacf37ba46.png">
I altered this (using dev tools) not to reveal any company-specific information, but I can assure you that the call described in the screenshot occurs and is visible in the networks tab. No clue why it never seems to detect it. :(

**Comment by z0d14c** [comment]
For the record, I follow examples exactly as described in https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/integration/examples/network_requests.spec.js

**Comment by z0d14c** [comment]
I'm sad this doesn't work for me but I don't want to clutter up issues, because I haven't actually reproduced in the kitchen sink repo, etc... but maybe someone else with more time to track down the cause of this issue will pop up eventually.

**Comment by brian-mann** [comment]
Are you running the actual kitchensink or like... translating this into your own app calls? Are you using `window.fetch`? Can you send a screenshot of your Network Log. I'm sure it's going to say `fetch` instead of `XHR`.

**Comment by blueshirts** [comment]
Based on the comment above it seems like the following document is probably relevant.

https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__window-fetch
