### ISSUE TITLE
Adding external libraries not work

### ISSUE THREAD

**Issue by kutlaykural** [cypress-io/cypress#1963]
### Current behavior:
After adding new libraries it says:
Uncaught TypeError: Cannot read property 'prototype' of undefined

### Desired behavior:
Use external library functions properly
### Steps to reproduce:

npm install Cypress --save-dev
npm install excel --save-dev
npm install babel-cli --save-dev
npm install babel-preset-env --save-dev
npm install mocha --save-dev;

in test file in integration insert code below:
var parseExcel = require('excel/commonjs/excelParser').default;

### Versions

Mac
electron 59

**Comment by EirikBirkeland** [comment]
I was able to reproduce this.

@kutlaykural Cypress is running in the browser and so does not have native Node.js access. The above error seems to be caused by `fs.ReadStream` being undefined:
```
  var fs$ReadStream = fs.ReadStream
  ReadStream.prototype = Object.create(fs$ReadStream.prototype)
  ReadStream.prototype.open = ReadStream$open
```

I suggest looking into `cy.task`:
https://docs.cypress.io/api/commands/task.html#
As well as `cy.exec`:
https://docs.cypress.io/api/commands/exec.html#

These commands can help you execute Nodejs code and then return the results to the browser.

**Comment by brian-mann** [comment]
@kutlaykural, @EirikBirkeland is correct - you cannot require node specific libraries into browser code, but you can use `cy.exec`, `cy.request`, or the new and best `cy.task` for interopt with the background `node` process. This will enable you to do anything you'd like.
