### ISSUE TITLE
cannot start task onAfterScreenshot

### ISSUE THREAD

**Issue by assafey** [cypress-io/cypress#1966]
I am trying to call a nodejs task from screenshot's `onAfterScreenshot` callback.
The task is matching current screenshot with the previous base one.
What is the proper way to do it with `Cypress.Screenshot.defaults` or `Cypress.Commands.overwrite('screenshot', ()=>{})` ?

### Current behavior:
```
Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise. The command that returned the promise was: cy.screenshot() The cy command you invoked inside the promise was: cy.task()
```

### Desired behavior:
task should run

### Steps to reproduce:

```js
Cypress.Screenshot.defaults({
    capture: "fullPage",
    scale: false,
    onAfterScreenshot ($el, props) {
        cy.task('matchScreenshot', props);
    }
});
```

and call `cy.screenshot(imageName)` in test.

### Versions

Cypress:    3.0.1
Browser:    Electron 59 (headless)

**Comment by brian-mann** [comment]
There are a number of ways to do this - you could likely store state somewhere and iterate through the screenshot props and then call `cy.task` on them.

The way you're doing it currently definitely won't work because `cy.task()` is async. Also based on the error you're getting it does not appear that you've pasted in everything you're doing in your project - so it's harder to go off of how you're actually doing all this.

The better solution IMO is to expose a plugin/hook event called: `after:screenshot` that you could use inside of `plugins/index.js` to automatically diff the screenshot, without needing to touch anything inside of your spec code. We'd need to create that event but it's in my notes to do it.

Anyway you can probably do something like this...

```js
// in a support file somewhere
let screenshots = []

Cypress.Screenshot.defaults({
  onAfterScreenshot ($el, props) {
    screenshots.push(props)
  }
})

afterEach(() => {
  if (screenshots.length) {
    const items = screenshots.slice(0)
    
    // reset them again
    screenshots = []

    items.forEach((item) => {
      cy.task('matchScreenshot', item)
    })
  }
})
```

That will run tasks for each screenshot captured in each test. You might need to do something special to handle the case when a test fails and we auto-capture a screenshot. I think we yield some property like: `failed: true` or something so you know to skip those.

**Comment by chrisbreiding** [comment]
We implemented and released the [`after:screenshot` plugin event](https://docs.cypress.io/api/plugins/after-screenshot-api.html) in [3.0.2](https://docs.cypress.io/guides/references/changelog.html#3-0-2), which you should be able to use for this purpose. You can return a promise from it that will be awaited before `cy.screenshot()` resolves, and if you throw an error or reject the promise, it will fail the test.
