### ISSUE TITLE
Cannot install locally

### ISSUE THREAD

**Issue by devjared1** [cypress-io/cypress#19675]
### Current behavior

Trying to run `npm install cypress --save-dev` but the install keeps getting stuck at `reify:rxjs: timing reifyNode:node_modules/cypress` and just hangs there. Node version: 16.13.1.<br><br>
![image](https://user-images.githubusercontent.com/71391311/149174084-5f33facf-5da3-4cf4-aa42-a3012e12685a.png)

### Cypress Version

9.2.1

### Package Manager

npm

### Operating system

Windows

**Comment by tomaszwojciechowski** [comment]
What was reason of this issue or it's solution?

To authors of Cypress: If it was because (as for Cypress 9.5.1) problem with downloading Cypress in next step, it may be clearer, for user, to mark that reify:rxjs has been downloaded, and progress of downloading Cypress itself stucks on 0%?

**Comment by Poojitha-Chandra** [comment]
@devjared1 I am facing the same issue, can u let me know how the issue is resolved for you?

**Comment by Mustafa-Sahin-1915** [comment]
you need to downgrade npm version

**Comment by Mustafa-Sahin-1915** [comment]
npm install -g npm@6

**Comment by DmitriyIvanko** [comment]
Have the save issue (not fixed yet)

**Comment by ghost** [comment]
Just ran into the same issue & downgrading helped -> npm install -g npm@6

thx @Mustafa-Sahin-1915

**Comment by saradhiii** [comment]
thanks @Mustafa-Sahin-1915 your suggestion has worked for me thanks a lot

**Comment by ThiroshMadhusha** [comment]
### Hello Guys... I am facing the same issue. but now I have **Resolved it**. 

![Screenshot_6](https://github.com/cypress-io/cypress/assets/79472177/7ba639f2-5d3e-4341-a123-ad409e21fa0c)

## Here are the Steps.

1. Create a Folder like "cypress-automation" Do not create only the "cypress" word. because it conflicts some time while installing.
2. Open a new Terminal in the Same Created "cypress-automation" Folder path
3. In the terminal Type the below Command and press Enter.

>  `npm init -y`

4. After creating the package.json file Run the below Command and press Enter.

> `npm install cypress --save-dev`

5. It is Correctly Install Cypress.
6. No need to downgrade your npm version. Check your Node Version.

> `node -v`

![Screenshot_7](https://github.com/cypress-io/cypress/assets/79472177/d4e3cd2c-c4a7-4ee8-9faa-dd0421737d4d)

7. Go and check the Cypress document to which version you need to do the Cypress installation. 

> [https://docs.cypress.io/guides/getting-started/installing-cypress](url)


![Screenshot_4](https://github.com/cypress-io/cypress/assets/79472177/46643564-e72b-4c65-a9ab-32c92b33545a)

8. Install compatibility Node.js Package which is recommended in Cypress installation document Page.

> [https://nodejs.org/en/download](url)


**_---Happy Testing---_**

**Comment by ThiroshMadhusha** [comment]
> ### Current behavior
> Trying to run `npm install cypress --save-dev` but the install keeps getting stuck at `reify:rxjs: timing reifyNode:node_modules/cypress` and just hangs there. Node version: 16.13.1. ![image](https://user-images.githubusercontent.com/71391311/149174084-5f33facf-5da3-4cf4-aa42-a3012e12685a.png)
> 
> ### Debug logs
> _No response_
> 
> ### Cypress Version
> 9.2.1
> 
> ### Package Manager
> npm
> 
> ### Operating system
> Windows
> 
> ### Other
> _No response_

https://github.com/cypress-io/cypress/issues/19675#issuecomment-1837018407

**Comment by ThiroshMadhusha** [comment]
### Hello Guys... I am facing the same issue. but now I have **Resolved it**. 

![Screenshot_6](https://github.com/cypress-io/cypress/assets/79472177/7ba639f2-5d3e-4341-a123-ad409e21fa0c)

## Here are the Steps.

1. Create a Folder like "cypress-automation" Do not create only the "cypress" word. because it conflicts some time while installing.
2. Open a new Terminal in the Same Created "cypress-automation" Folder path
3. In the terminal Type the below Command and press Enter.

>  `npm init -y`

4. After creating the package.json file Run the below Command and press Enter.

> `npm install cypress --save-dev`

5. It is Correctly Install Cypress.
6. No need to downgrade your npm version. Check your Node Version.

> `node -v`

![Screenshot_7](https://github.com/cypress-io/cypress/assets/79472177/d4e3cd2c-c4a7-4ee8-9faa-dd0421737d4d)

7. Go and check the Cypress document to which version you need to do the Cypress installation. 

> [https://docs.cypress.io/guides/getting-started/installing-cypress](url)


![Screenshot_4](https://github.com/cypress-io/cypress/assets/79472177/46643564-e72b-4c65-a9ab-32c92b33545a)

8. Install compatibility Node.js Package which is recommended in Cypress installation document Page.

> [https://nodejs.org/en/download](url)

9. Open Cypress

> `npx cypress open`

![Screenshot_8](https://github.com/cypress-io/cypress/assets/79472177/c6c81c18-b2d4-4bdd-ada8-fbc0046a249e)


**_---Happy Testing---_**

**Comment by melsyvolfram** [comment]
I have the same issue. My Node version is correct (18x as in documentation: https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs).  
But cypress installed only after downgrading: npm install -g npm@6
