### ISSUE TITLE
General App Setup

### ISSUE THREAD

**Issue by averboe** [cypress-io/cypress#1967]
### Current behavior:
We have an initial localization (using [i18-react](https://github.com/alexdrel/i18n-react)) setup once our app loads:

```js
import { defaultLanguage, setLanguage } from "../../src/i18n";

setLanguage(defaultLanguage);
```

i18n.js file:

```js
import T from 'i18n-react';


let currentLang = '';
export const defaultLanguage = 'en';


const languages = {
  'en': require('../locale/en.json')
};


/**
 * @param {string} lang Language
 */
export function setLanguage(lang) {
  if (!(lang in languages)) {
    lang = defaultLanguage;
  }
  currentLang = lang;
  T.setTexts(Object.assign({}, languages[defaultLanguage], languages[lang]));
}
```

We run this once when our app loads, and we thought of placing this under `support/index.js`. Not sure if that's the proper spot. In any case, our string comparison fails when we try to use the `T.translate` function. It turns out our `T` object in our spec files is now a different `T` object than the one we used to setLanguage on, which makes it impossible for us to test for strings. 
Our current workaround is to place the `setLanguage` function at the top of each spec file, but we obviously want to stop doing that.

What are we doing wrong? Is there a better place to have this function run?

### Desired behavior:
`T` object is the same singleton shared across the entire test cycle, just like in the real application.

### Steps to reproduce:
I guess you can just install the `i18n-react` package and use the code above. Then you can see that `T.translate(STRING_KEY)` never finds its translation since the `this.texts` property in `T` is always null since the `T` object is a different one.

### Versions
Cypress 3.0.1.
Mac OS High Sierra 10.13.4

**Comment by Bkucera** [comment]
Can you show how you are using `T` in your specs? Are you importing `T`?

**Comment by averboe** [comment]
@Bkucera yes, sure
import looks like that:
```
import T from 'i18n-react';
setLanguage(defaultLanguage);
```
usage in test
```
cy.get(<element>).contains(T.translate(`TOAST_EDIT_TEMPLATE`))
```

**Comment by brian-mann** [comment]
`support/index.js` is served in a separate `<script>` tag and is not automatically bundled into your actual spec files - therefore it's not directly accessible unless you made it a global variable in order to access it via your specs.

The easier thing to do is create like a `support/utils.js` file that you do directly require/import into your spec files - and in there import the react `i18n` and expose the `T`. function.

```js
// cypress/integration/spec.js

const utils = require('../support/utils')
```

That way they will be shared and directly accessible in each spec file. You should hide all of this implementation in the `utils.js` file and just export a function like `T` or `translate` which does both the default `getting / setting`.

My other idea is that you could also expose this directly from the application itself (but you'll have to make it a global) and that way you can automatically tap into whatever language your app code is already using.

This is more complicated since it involves needing to first get access to the `window` which you'll only have after a `cy.visit()` but it would also work. I'd say start with the first option, it is straightforward.

**Comment by averboe** [comment]
Yeah, it works. Thanks a lot!
The only issue is that you should import/require it in every single spec file.
