### ISSUE TITLE
@cypress/vite-dev-server sourcemap is not correct

### ISSUE THREAD

**Issue by dream2023** [cypress-io/cypress#19688]
### Current behavior

![企业微信截图_40ad1b35-ab7d-4cfd-82c5-5f4ce312a7e2](https://user-images.githubusercontent.com/19297757/149260637-88179f0c-33b2-4386-817e-6b62b3df5bf4.png)

### Test code to reproduce

clone this project, then write `debugger` on `src/App.tsx`

https://github.com/lmiller1990/cypress-react-vite-demo

### Cypress Version

7.5.0 & 9.2.1

**Comment by tnrich** [comment]
Just to add some anecdotal evidence that source maps are broken for other people, here is the SAME debugger getting hit in both windows. The right side is running just in a normal chrome browser, the left is running inside a cypress test. The left side is completely bungled, even pointing to the wrong file entirely:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2730609/170530625-2a239f0c-440a-4712-9c81-b7d771e946e1.png">


Makes debugging tests a nightmare..

**Comment by tnrich** [comment]
Also an interesting thing to note, the same source maps seem to work fine in Electron so it seems like it is due to some weird interactions with Cypress and Chrome:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2730609/170583420-74061e9d-97b6-4de3-9380-b9d0e6332ad0.png">
