### ISSUE TITLE
9.3.1 Fails Typescript check

### ISSUE THREAD

**Issue by emilgoldsmith** [cypress-io/cypress#19759]
### Current behavior

![Screenshot from 2022-01-19 15-11-58](https://user-images.githubusercontent.com/18149242/150147567-19a3a6d9-03bf-43ba-a8da-f6f90177f5d5.png)

My CI is giving me these issues and I verified it locally. It seems to be an internal Cypress issue and not anything to do with my custom types or am I wrong?

### Desired behavior

Typescript compiling

### Test code to reproduce

I will admit I haven't gone as far as doing that myself but I believe any fresh repo should fail a typescript check

### Cypress Version

9.3.1

**Comment by sainthkh** [comment]
I tried it with a fresh repo. Instructions below:

1. `npm init -y`
2. `npm i typescript cypress`
3. Create file 

```ts
/// <reference types="cypress" />

cy.stub()
```

4. `npx tsc a.ts`

I failed to reproduce it. Can you provide a reproducible code example?

**Comment by skvale** [comment]
I can reproduce this with 1 additional step

```
+ npm i @sinonjs/fake-timers@7.1.2
```

It works if you get `@sinonjs/fake-timers@8` though

**Comment by sainthkh** [comment]
I researched on the topic. And the only solution is to upgrade `@sinonjs/fake-timers` to 8+.

Internally, Cypress uses sinon 7, 8 and 9. As there are some definitions that we need, I had to update the `@types/sinon` to `9.0.9`. (Unfortunately, there is no `@types/sinon@8.x`.)

That's why I had to update @sinonjs/fake-timers to 8.

If the upgrade causes any problem, please let me know. Maybe I'll find other ways.

**Comment by emilgoldsmith** [comment]
Ahh that was it! Thanks @sainthkh, I hadn't thought about / noticed that I have fake-timers installed myself for a use-case, and that was still the old version, upgrade it solved my issues :). Closing the issue.
