### ISSUE TITLE
Adding new test file results in "No tests found"

### ISSUE THREAD

**Issue by nirtz89** [cypress-io/cypress#19822]
### Current behavior

After installing the default cypress component testing repo and adding a new component and a new test to it results in "No tests found"

### Desired behavior

It should find the tests

### Test code to reproduce

Start by installing react with cypress here: https://www.cypress.io/blog/2021/04/06/cypress-component-testing-react/  
Now add a new component, for example, Button.tsx  
  
```
import React from 'react';

const Button = ({text}: any) => {
  return <button>{text}</button>;
};

export default Button;
```
  
  
Now add a test to it:  
  
```
import React from 'react';
import { mount } from '@cypress/react';
import Button from './Button';

it('renders button', () => {
  mount(<Button text="text"/>);
  cy.get('button').contains('text');
});
```  
  
The result is:  
![image](https://user-images.githubusercontent.com/14985235/150585414-1601cdfb-ab13-41fa-b2d1-69ca3e33ef50.png)

### Cypress Version

9.3.1

**Comment by tbiethman** [comment]
@nirtz89 thank you for the report. I can reproduce this using the linked guide. Any new file created does not have its specs detected, even if the contents exactly match that of the working App.test.tsx, and this persists after restart.

**Comment by chrisrhymes** [comment]
I am having the same problem. I have also tried `npx cypress cache clear` and `npx cypress install` (installing cypress 9.3.1) and the problem still persists.

**Comment by paul-moers** [comment]
- `npx create-next-app nextjs-cypress-ct`
- `cd nextjs-cypress-ct`
- `yarn && yarn dev`

Visiting `http://localhost:3000/` shows the `Welcome to Next.js!` demo page.

Then follow the steps from https://docs.cypress.io/guides/component-testing/framework-configuration#Next-js-Webpack-4. Though a modified version as I believe these instructions are outdated, or at least that mentions `the latest version of Next.js, which uses Webpack 4`, while that is now webpack 5 as can be read on https://nextjs.org/docs/messages/webpack5, with furthermore `In Next.js 12 webpack 4 support was removed`.

- So instead of 
  `yarn add -D cypress @cypress/webpack-dev-server @cypress/react html-webpack-plugin@4 webpack@4 webpack-dev-server@3`
  do
  `yarn add -D cypress @cypress/webpack-dev-server @cypress/react html-webpack-plugin@5 webpack@5 webpack-dev-server@3`
- Add `cypress/plugins/index.js`:
  ```
  const injectDevServer = require('@cypress/react/plugins/next')

  module.exports = (on, config) => {
    injectDevServer(on, config)

    return config
  }
  ```
- Add `cypress.json`, with testFiles modified to `"**/*spec.{js,jsx}"`:
  ```
  {
    "testFiles": "**/*spec.{js,jsx}",
    "componentFolder": "cypress/pages"
  }
- Add `cypress/pages/welcome.spec.js`:
  ```
  import React from 'react'
  import { mount } from '@cypress/react'
  import IndexPage from '../../pages/index'

  it('Renders page component', () => {
    mount(<IndexPage />)
    cy.contains('Welcome to Next.js')
  })
  ```
- `npx cypress open-ct`.

Chrome shows, and clicking the test executes it succesfully.

- Copy the test as ``cypress/pages/welcome-copy.spec.js`.

Tests shows in Chrome, but clicking it shows `No tests found.`.

These things don't work:
- Click to `Run All Tests` / type `r`.
- Retry, `npx cypress open-ct`.
- Retry with cache clear and reinstall, `npx cypress cache clear && yarn add -D cypress &&  npx cypress open-ct`.
- Restart app, `yarn dev` (= `next dev`).
- Restart app after cache clean, `yarn cache clean && yarn && yarn dev`.
- Try all above steps to do clean setup but without specific versions:
  `yarn add -D cypress @cypress/webpack-dev-server @cypress/react html-webpack-plugin webpack webpack-dev-server`
  But then when chrome opens and clicking a test it keeps showing `Your tests are loading...`.

Only after I think downgrading/upgrading any or all of `cypress @cypress/webpack-dev-server @cypress/react html-webpack-plugin webpack webpack-dev-server` it seems to catch up.

Using 
```
  "dependencies": {
    "next": "12.0.10",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "@cypress/react": "^5.12.1",
    "@cypress/webpack-dev-server": "^1.8.0",
    "cypress": "^9.4.1",
    "eslint": "8.8.0",
    "eslint-config-next": "12.0.10",
    "html-webpack-plugin": "5",
    "webpack": "5",
    "webpack-dev-server": "3"
  }
```

Using `node v17.3.1`, `yarn 1.22.17` on `macOS Monterey 12.1`.

**Comment by paul-moers** [comment]
I think this is related to #19423.

**Comment by paul-moers** [comment]
Thank you @chrisrhymes, that indeed seems to do the trick!

**Comment by SaraOmar54** [comment]
I faced the same problem and I found out that my node.js is old. and after downloading node.js 18.17.1 Cypress worked perfectly.

**Comment by prudhvi-sdet** [comment]
'm also facing same issue using node v16.14.0 and I tried to run rm -r .next/cache but no luck
rm: .next/cache: No such file or directory

**Comment by AlonMiz** [comment]
running into the same issue. sometimes i cant run any tests using the UI interface. all tests show the same error "No tests found". very annoying.
sometimes installing a different cypress version helps, but sometimes that doesn't help as well

**Comment by mindlessroman** [comment]
I see this too, though it may be a version problem (Version 14.4.1 (14.4.1.2925072), which is what the repo I'm working in currently uses). Running the cypress tests in the command line, the tests are detected and run. Trying to run the same test files in the UI, undetected tests. Strange that it's detectable in one place and not the other.
