### ISSUE TITLE
How should I use AWS Amplify instead of cy.request on the beforeEach in order to authenticate users?

### ISSUE THREAD

**Issue by josoroma** [cypress-io/cypress#1982]
Hi!

How should I use aws amplify on the beforeEach in order to authenticate users? I am asking this because I am going to need the token to make other AWS requests later.

```js
import Amplify, { Auth } from 'aws-amplify';
import aws_exports from './aws-exports.js';
Amplify.configure(aws_exports);

describe('ZTT - CDS', function () {
  context('Querying', function () {
    beforeEach(function () {
      //
    })


    it('It should...', function () {
      Auth.signIn('test@test.com', 'EasyToGuess$333')
        .then(user => {
          console.log('===> user', user);

          let session = Auth.currentSession();

          console.log('===> session', session);
        })
        .catch(err => console.log('===> err', err));
    })
  })
})
```

**Comment by brian-mann** [comment]
You need to return `Auth.signIn` because it's a promise and the test must be returned a promise to know to await the results of it.

Is `aws-amplify` a node only lib? Are you having issues with this? You've posted this issue but haven't specified what the actual problem is... ?

If `aws-amplify` is a `node` only lib you can simply use `cy.task` to talk to the background node process and implement it there... something like `cy.task('login', user, pass)` and then do the same stuff you need to do in `node` and that's it. Tasks are already promise aware so you just need to return the promise and be done with it.

If the promise rejects the command will automatically fail, etc. Same for succeeding.

**Comment by josoroma** [comment]
AWS Amplify is a JS SDK which simplifies the Authentication process with AWS Cognito.

https://aws.github.io/aws-amplify/media/authentication_guide.html

**Comment by brian-mann** [comment]
@josoroma yeah I see it is a browser lib. So no need to use `cy.task`. It should "just work". Is there a problem, you still didn't specify whether or not there actually was one.

**Comment by josoroma** [comment]
@brian-mann nope, there is no problem anymore, and thanks for your quick response.

**Comment by artivilla** [comment]
If we have 2fa and email verification, is there a way to bypass that for a single user in the cognito user pool?

**Comment by christopherfrance** [comment]
You can verify a user from the command line: 

```
cy.exec(`aws cognito-idp admin-confirm-sign-up \
  --region us-east-1 \
  --user-pool-id ${config.cognito.USER_POOL_ID} \
  --username ${userEmail}`)
    console.log(`Confirmed ${userEmail}`)
```

Not sure about handling 2fa.
