### ISSUE TITLE
bi-directional WebSocket support and/or message queue/pools

### ISSUE THREAD

**Issue by StephenOTT** [cypress-io/cypress#199]
Would be great to have the ability to watch a bi-directional web socket to process messages from the back-end as they are received.

Use Case:

User preforms a action through the front-end which actions several back-end events.  It would be great if we could monitor that these different events did occur (there is an endless amount of different events and combinations of events).

What would be great if there was a simple message pool/queue or a way to "monitor" a bi-direcitonal websocket and capturing the messages received from the back-end.

We would then write tests to check if those events are being executed by looking at the socket/pool/queue and seeing if the events were received after X user actions.

**Comment by flotwig** [comment]
Agree that this would be good to have, and with the introduction of request events on `cy.intercept` in 7.0.0, I think we have a good API precedent for adding websocket mocking. 

For now, I'm going to close this issue and fold it into #2492 since that one has a bit more support, but covers the same ground as this.
