### ISSUE TITLE
(uncaught exception) ReferenceError: SharedArrayBuffer is not defined in Electron Browser after Update to 8.6.0

### ISSUE THREAD

**Issue by Im-a-Train** [cypress-io/cypress#19912]
### Current behavior

After the Update from 8.5.0 to 8.6.0 I get the following error while starting my app in the Electron browser:

`Uncaught (in promise) ReferenceError: SharedArrayBuffer is not defined`

The problem might be the new Electron version, but until now I was not able to find the root cause.
An other Cypress user reported a similar problem on Stackoverflow:
https://stackoverflow.com/questions/70794396/sharedarraybuffer-not-defined-when-using-cypress/70863376#70863376

### Desired behavior

The app should start normally without the SharedArrayBuffer error.

### Test code to reproduce

Here ist a simple Code Repo to reproduce the error:
https://github.com/unlocomqx/cypress-ffmpeg

Switch the Cypress version to 8.5.0 and start the test with the Electron browser. -> It should work fine
Switch the Cypress version to 8.6.0 or higher and start the test with the Electron browser. -> The SharedArrayBuffer error occurs.

### Cypress Version

8.6.0 and higher

**Comment by unlocomqx** [comment]
I'm not 100% on this but `SharedArrayBuffer` requires strict origin isolation (These [two headers](https://developer.chrome.com/blog/enabling-shared-array-buffer/#cross-origin-isolation) need to be set)

It could be that `SharedArrayBuffer` is not defined because these headers are not present on the toplevel cypress page.

The reason it works on `electron@13.2.0` is probably because this strict origin isolation requirement is a recent security fix which was introduced after `13.2.0`

**Comment by Im-a-Train** [comment]
@unlocomqx Thx for the fast response.
As you can see in the example:
https://github.com/unlocomqx/cypress-ffmpeg/blob/main/vite.config.js#L6
these headers are set.
And also in the test, you can see the Response Headers are set:
![COOP and COEP Headers](https://user-images.githubusercontent.com/42909317/151524839-97782e74-02a4-43e6-9cc2-1ef80b0ebb6b.png)

In the normal Chrome browser the error does not occur, and the network traffic is exactly the same.
It looks like the browser (Chrome & Electron) in the Cypress context ignores these headers?

**Comment by unlocomqx** [comment]
I'm the one who posted this issue on stackoverflow 👋 

What I mean is not the app request, but the cypress top level request

![CleanShot 2022-01-28 at 12 38 35@2x](https://user-images.githubusercontent.com/793712/151540805-f5039084-5baf-4f45-8ce7-184ea8f6b527.png)

**Comment by Im-a-Train** [comment]
I see, probably we should add the two headers in the Cypress Server:
https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/server-base.ts#L253-L264

Like this:

`    app.use((req, res, next) => {
      setProxiedUrl(req)

      res.setHeader("Cross-Origin-Opener-Policy", "same-origin")
      res.setHeader("Cross-Origin-Embedder-Policy", "require-corp")

      // useful for tests
      if (this._middleware) {
        this._middleware(req, res)
      }

      // always continue on

      return next()
    })`

But im no very familiar with the code of Cypress, just an idea...

**Comment by Im-a-Train** [comment]
@unlocomqx 
I tested it locally by setting the headers in serve-base.ts as mentioned above in the following file:
"C:\Users\{USERNAME}\AppData\Local\Cypress\Cache\8.6.0\Cypress\resources\app\packages\server\lib\server-base.js"
And the result was as expected.
If the top level request returns the COEP and the COOP headers, it works:
![COEP and COOP Set](https://user-images.githubusercontent.com/42909317/151790110-ac32273a-2191-411a-b3e4-c0cb960be551.png)

@tbiethman, @jennifer-shehane or who else is able to fix this. Could you please fix this. Thanks.

**Comment by jpierson-at-riis** [comment]
I'm seeing the same error behavior in both an attempt to upgrade to either `v9.5.2` or `v8.7.0`. It looks like `v7.7.0` works fine for me as well.

Based on the conversation I'm guessing [these described changes from 8.6.0](https://docs.cypress.io/guides/references/changelog#8-6-0) may be at the heart of the issue?

> Dependency Updates:
> * Upgraded the Chromium browser version used during cypress run and when selecting Electron browser in cypress open from 91.0.4472.164 to 93.0.4577.58.
> * Upgraded electron from 13.2.0 to 14.1.0. Addressed in [#18318](https://github.com/cypress-io/cypress/issues/18318) and [#18384](https://github.com/cypress-io/cypress/issues/18384).

I'm going to try `v8.5.0` specifically next to see if I can our project as updated as possible without being blocked by this regression. We typically use Electron exclusively due to issues running with Chrome and other installed browsers which are locked down due to strict corporate policies which appear to break the integration with most of the browsers and Cypress as well as tools like Lighthouse.

**Comment by Im-a-Train** [comment]
@jpierson-at-riis yes, you are guessing right.
We are still stuck at `v8.5.0` too, because of the same reasons as you.
I opened a Pull Request. I hope to overcome this problem soon. :)

**Comment by chabb** [comment]
We have the same issue, and it's blocking all our tests

**Comment by 6sixtyfour4** [comment]
Dear Cypress team
We encounter the same situation in our projects. It's getting more and more painful to be stuck with an old Cypress version (8.5.0). We kindly ask you to give this issue a higher priority since the solution is already mentioned in the comments above. 
Thank you!

**Comment by Im-a-Train** [comment]
I've got an update on this.
As a workaround, we use the Chrome Browser, and start it with this argument: `--enable-features=SharedArrayBuffer`.
(For more information how to launch browsers with argument in Cypress see: https://docs.cypress.io/api/plugins/browser-launch-api#Modify-browser-launch-arguments)

This allows us to go catch up to the newest Cypress version.

Anyway, for Electron the problem is still present. I didn't found any way to tell Electron to enable SharedArrayBuffers.
Except by adding the required CORS headers to the Cypress Server, as mentioned: https://github.com/cypress-io/cypress/issues/19912#issuecomment-1024276051

**Comment by sedghi** [comment]
@Im-a-Train Is it possible for you to share your cypress.config.ts?

**Comment by akesling** [comment]
Any update on this?  I'm evaluating Cypress expressly for Web Worker e2e tests *for `SharedArrayBuffer` functionality* and not being able to control the "root" page cross origin restriction headers makes it so that `crossOriginIsolated` is always false.

To emphasize the state I'm seeing: the iFrame receives the appropriate headers, ***but the root Cypress context outside the iFrame does not***.  AFAICT, the embedding context *must* have these headers set for `SharedArrayBuffer` to be available.

**Comment by jpierson-at-riis** [comment]
@cypress-app-bot , please reopen this is still an issue. Tested on Cypress 13.7.3.
