### ISSUE TITLE
Override of XHRs send function only applies once

### ISSUE THREAD

**Issue by Simonerus** [cypress-io/cypress#19932]
### Current behavior

A header set in `XMLHttpRequest.prototype.send` is only applied in first testcase.

### Desired behavior

The header added by the app applies in all testcases.

### Test code to reproduce

Example app:
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Test App</title>
  <script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
</head>
<body>
  <script>
    const xhrSend = XMLHttpRequest.prototype.send;
    XMLHttpRequest.prototype.send = function(tmp) {
      if (!this.headers || !this.headers.test) {
        this.setRequestHeader('test', 'IS_SET');
      }
      xhrSend.apply(this, tmp);
    }
      </script>
      <button class="doAJAX" onclick="jQuery.ajax('/data/test')">Load next row</button>
</body>
</html>

```

Example Test :

```
describe('Run landingpage tests', () => {

    before(function () {
        cy.visit('http://localhost:4200');
    });
    context('Spam-click', () => {
        it('Click button once', () => {
            cy.intercept('/data/test').as("request1");
            cy.get('.doAJAX').should('exist');
            cy.get('.doAJAX').click();
            cy.wait('@request1')
                .its('request.headers')
                .should('have.property', 'test', 'IS_SET');
        });
        it('Click button again', () => {
            cy.intercept('/data/test').as('request2');
            cy.get('.doAJAX').should('exist');
            cy.get('.doAJAX').click();
            cy.wait('@request2')
                .its('request.headers')
                .should('have.property', 'test', 'IS_SET');
        });
    });
});
```

### Cypress Version

9.3.1

**Comment by tbiethman** [comment]
It's not that your headers aren't being applied; your entire `send` implementation is being overwritten. We [override the XMLHttpRequest prototype](https://github.com/cypress-io/cypress/blob/e66734d514e12655accab1dd6d047958583ea3d1/packages/driver/src/cypress/server.ts#L400) as well.

Your first test works because your script executes _after_ ours; the `xhrSend` value you capture ends up being [our override](https://github.com/cypress-io/cypress/blob/e66734d514e12655accab1dd6d047958583ea3d1/packages/driver/src/cypress/server.ts#L606). However, when your next spec starts, we [restore](https://github.com/cypress-io/cypress/blob/e66734d514e12655accab1dd6d047958583ea3d1/packages/driver/src/cypress/server.ts#L397) the prototype with the values that we previously captured, which do not include yours (as your script hadn't executed yet). And since you only visit the page once with a `before`, your script never re-executes.

I'm going to label this as a bug needing more investigation. If nothing else, we need better documentation around this behavior. There are a number of ways to work around this in the meantime; revisiting the page for each test might be the easiest.

**Comment by qa-joerg** [comment]
Hi. Any news on this? The workaround you have proposed is not useful in my mind. The tests should have the possibility to divide them into test steps. Otherwise, the individual tests will become very confusing.

**Comment by qa-joerg** [comment]
Any news on this?

**Comment by tausif29** [comment]
Any update on this? Please share a workaround for this
