### ISSUE TITLE
Bug: Data attributes not used as given during assertion

### ISSUE THREAD

**Issue by HybridEyeGrillage** [cypress-io/cypress#19944]
### Current behavior

Browser: Chrome 97
NodeJS Version: v16.13.2
OS: Windows 10 Pro 20h2 (19042.1466)

Running a test using data attribute `data-cy`, assertions do not use the same context and fail. When using `cy.get("[data-cy=name]").should("exists")`, this passes as expected, but the element context being checked is different from what was given. 

`[data-toggle=collapse]` becomes `<button.navbar-toggle.collapsed>`

When using `cy.get("[data-cy=name]").should("be.visible")`, the test fails, even if the element is visible. 
When using `cy.get("[data-cy=name]").should("not.be.visible")`, it passes, but that's not the truth of the page.

![image](https://user-images.githubusercontent.com/5670441/151515500-6e41148f-37c9-4dc4-a1a9-99a3550c9a8f.png)

### Desired behavior

In this situation, Cypress should...

- Use the data attribute as it is given during an assertion.
- the .should("be.visible") should find the data attribute element that is clearly visible on the page

### Test code to reproduce

https://github.com/HybridEyeGrillage/cypress-test-tiny

### Cypress Version

9.3.1

### Other

This was also seen in #2130, but the OP had never found a solution.

**Comment by tbiethman** [comment]
@HybridEyeGrillage Thanks for reaching out, I ran your reproduction. When you say:

> [data-toggle=collapse] becomes <button.navbar-toggle.collapsed>

That button _is_ the element with the data-toggle attribute on it. The selectors should be equivalent, as far as this page is concerned. I don't see any other elements with a data-toggle value of 'collapse'.

> When using cy.get("[data-cy=name]").should("be.visible"), the test fails, even if the element is visible.
When using cy.get("[data-cy=name]").should("not.be.visible"), it passes, but that's not the truth of the page.

I'm a little confused here, because the button isn't visible. At the defined window size, the button is explicitly hidden. So your assertions are behaving like I'd expect; the button is on the DOM (exists), but is hidden (not.visible).

**Comment by HybridEyeGrillage** [comment]
Sorry, it seems I hit the wrong element in my haste to get someone to shed some light on the issue I am facing. 
And after taking another look with fresh eyes, it's seems more likely that I had misinterpreted the error. 
Upon changing element to an anchor in the tiny-test, it went as I'd expected. This most likely means that there is something else going on in the proprietary app or maybe one of the custom functions that were made.
Excuses for the time wasted, I should have realized that sooner. 😞 I'll close this bug.

**Comment by tbiethman** [comment]
@HybridEyeGrillage No worries! Good luck with your investigation :+1:
