### ISSUE TITLE
Timed out retrying after 5000ms: cy.wait() timed out waiting 5000ms for the 1st request to the route:

### ISSUE THREAD

**Issue by asmakhalfallah2018** [cypress-io/cypress#19975]
### Current behavior

I'm trying to reproduce the documentation example of intercept and then wait alias of intercept but it's giving this error 

CypressError
Timed out retrying after 5000ms: cy.wait() timed out waiting 5000ms for the 1st request to the route: getSettings. No request ever occurred.Learn more

### Test code to reproduce

```
      describe('settings', () => {
        it('should settings ', () => {
         cy.intercept('http://example.com/settings').as('getSettings')
         cy.wait('@getSettings')     
        })
     })
```

### Cypress Version

^9.3.1

**Comment by JakubLog** [comment]
I have the same problem...

`it("Should redirect to '/school-admin' if School Admin is authenticated", () => {
    cy.intercept('POST', `${Cypress.env('API_URL')}/auth/local`).as('login');
    cy.visit('/');
    cy.findByPlaceholderText(/login/i).type('test_admin');
    cy.findByPlaceholderText(/hasło/i).type('*********');
    cy.findByText(/zaloguj/i).click();
    cy.wait('@login').then(() => {
      cy.url().should('include', '/school-admin');
    });
  });`

Locally works perfect, but when GH actions starting work - this test it's failing.

**Comment by Lux589** [comment]
I have the same problem. I am trying to add additional authentication headers to all requests so that I can bypass cloudflare 2FA page using cloudflare [access service token](https://developers.cloudflare.com/cloudflare-one/identity/service-auth/service-tokens). 

This works great on my local but on GH action all tests fail because of this error. 

This is how I got it to work on my local. 
on the index.js file I add the headers to all requests from to the site using cy.intercept
`beforeEach(() => {
		cy.intercept(baseUrl, (req) => {
      req.headers['CF-Access-Client-Id'] = Cypress.env('CF_ACCESS_CLIENT_ID');
      req.headers['CF-Access-Client-Secret'] = Cypress.env('CF_ACCESS_CLIENT_SECRET');
    }).as('cloudfareAccessService')
  })`
  
  Having just the above code works on my local and I can bypass the cloudflare 2FA screen. 
  To check the responses I'm getting while trying to debug why this is not working on GH actions I used a cy.wait to get the response and that is when I get the error mentioned in this issue. 
  
  `cy.wait('@cloudfareAccessService').its('response.headers')
      .then((headers) => {
        cy.log(headers['set-cookie']);
      })`

**Comment by BlueWinds** [comment]
I'm going to respond to each comment here separately, since I'm not sure you're all talking about the same thing. :)

@asmakhalfallah2018 - Your provided test could *should* fail. You're registering an intercept, then waiting to see if anything calls it. Nothing ever does. This makes sense, your sample code doesn't include visiting a page, making a request, or anything like that.

@JakubLog - Something is probably different between your local environment and CI. You could try enabling video recording on your test, or taking some screenshots at various stages, to see if that provides any additional information. https://docs.cypress.io/guides/guides/screenshots-and-videos

@Lux589 - Probably the same thing, something is going on differently locally and in GH actions. Same suggestion as for Jakub - try recording a video of the test running in CI, which will show you the command log and might provide hints as to what's going on.

**Comment by dadamsGS** [comment]
idk if this is related at all, but I cannot seem to get intercepts to re-write the request headers. 

My very simple code is:
```
describe('TODO api testing', () => {

  it('fetches price sheets - GET', () => {
    // add a header to an outgoing request
    cy.intercept('**/price-sheets', (req) => {
      debugger
      req.headers['x-custom-header'] = 'added by cy.intercept'
      req.headers['authorization'] = `Bearer ${Cypress.env('API_IDTOKEN')}`
    })

    cy.request('/price-sheets')
  });
});
```

The request is returned as unauthorized.


Ideally I would like to intercept and then make a request to a baseUrl that is different from what I have in `cypress.json`:
```
cy.intercept('https://someotherdomain/price-sheets', (req) => {
      debugger
      req.headers['x-custom-header'] = 'added by cy.intercept'
      req.headers['authorization'] = `Bearer ${Cypress.env('API_IDTOKEN')}`
    })
```
but that does not work, either.

**Comment by dadamsGS** [comment]
For my purposes I missed the one line of text in the documentation that states intercepts work only for requests made by the browser. Which means I need another tool for API testing. 

Cool.

**Comment by sainthkh** [comment]
Closing because of the inactivity.

**Comment by TifeDada** [comment]
"Timed out retrying after 5000ms: cy.wait() timed out waiting 5000ms for the 4th request to the route: currentUserRequest. No request ever occurred." 
I'm getting this error after I upgraded to Cypress 10 from Cypress 7 and it was working properly before the upgrade. Anyone else experienced this and knows how to fix it?

**Comment by tafhyseni** [comment]
Ran into the same problem. Turns out the default request timeout for the request to leave the browser is 5000ms. As it is stated in the docs:

> The duration is configured by the [requestTimeout](https://docs.cypress.io/guides/references/configuration#Timeouts) option - which has a default of 5000 ms.

I fixed it by simply overwriting that, example:


```
cy.intercept('https://httpbin.org/post*').as('fetchData')

cy.wait(20000) // default request Timeout will be overwritten by this value
cy.wait('@fetchData')
```

**Comment by Moe793** [comment]
Following worked for me:

```
describe('settings', () => {
        it('should settings ', () => {
         cy.intercept('http://example.com/settings', (req) => {
            delete req.headers['if-modified-since'];
            delete req.headers['if-none-match'];
            delete req.headers['proxy-connection'];).as('getSettings')
         cy.wait('@getSettings')     
        })
     })
})
```

**Comment by andreeajurj** [comment]
Everybody has the same problem and nobody has a clue from where it comes, nice. We don't even know to listen

**Comment by kblestarge** [comment]
This issue should not be closed. 
Like many of you, I am experiencing this issue after upgrading from Cypress 7 to Cypress 10+ (I'm on `12.11.0`). This wasn't a problem before. I'm not sure if there's something wrong in my Cypress tests/config or if the newer version of Cypress just has a race-condition type of bug.
The most frustrating part is that the errors aren't reproducible on my local machine --they only happen intermittently on my CI pipeline in GitHub actions 😞.

**Comment by eliliam** [comment]
Why was this issue closed again? This is still very much an issue that many users here are facing. Please reopen this and help us find the solution to this.

**Comment by nagash77** [comment]
@eliliam In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by korel-san** [comment]
I have the same issue on my environment

**Comment by ameya-jain** [comment]
I have been facing the issue. In my particular case my code looks like this. I have two subsequent calls to the same endpoint. I am intercepting the endpoint in my test but was having the same behavior as everyone else. Removing the first call seemed to resolve the test and the test is working fine after removing the first call (or any one call I guess) . I am not sure what this means and why this was an issue.
```
useEffect(() => {
    wretch("path_to_endpoint")...
}, [])

useEffect(() => {
    wretch("path_to_endpoint")...
}, [])
```

**Comment by jennifer-shehane** [comment]
Hi everyone, I realize this error is still appearing for many people. The cause of this could be extremely varied however and there is not a singular root cause. Please open a new issue with a reproducible example if you believe there is a bug within Cypress causing this error to be shown so that we can investigate properly.
