### ISSUE TITLE
Login page is having SSO feature which on giving the URL gets redirected to a new URL for login. cypress.visit is not redirecting me to that URL and the URL is created on the fly so don't know the end URL.

### ISSUE THREAD

**Issue by anchoubey** [cypress-io/cypress#20031]
### What would you like?

I am able to load my login page using window.open but not via cy.visit. 

Please help me in loading the URL.

**Comment by flotwig** [comment]
Hi @anchoubey, issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
