### ISSUE TITLE
"\~" interpreted as "\x7e" in cy.request()

### ISSUE THREAD

**Issue by baviereteam** [cypress-io/cypress#20088]
### Current behavior

Hi,

I'm currently working on a test that downloads a file and compares it with a fixture.
After investigating a failure, I noticed that cy.request seems to fail encoding / decoding the tilde character when it follows a backwards slash - the tilde is replaced by "x7e" in the content.
This seems to happen "randomly" - ie. not all \~ are victim of that behavior. I have the feeling that only the first one in the file is affected. For example, with [two-tildes.txt](https://github.com/cypress-io/cypress/files/8035209/two-tildes.txt), only the first tilde appears as "x7e". The second one appears correctly.

Maybe this has to do with #19083 and linked issues? It is, however, not fixed in 9.4.1.

### Desired behavior

The tilde should appear as a tilde.

### Test code to reproduce

Putting the attached file [tilde.txt](https://github.com/cypress-io/cypress/files/8024914/tilde.txt) on a webserver:
* Opening that file in the browser shows the tilde correctly.
* Downloading the file with `cy.request()` and asserting on the content or writing it to a file shows that the tilde is encoded.

```
describe('Various tests', () => {
	it('Downloads file', () => {
		cy.request({
			url: 'http://localhost/tilde.txt',
			encoding: 'binary'
		}).then(response => {
			cy.writeFile('cypress/documents/tilde-request.txt', response.body, 'binary');
			cy.wrap(response.body).should('eq', 'This character: "\~" is called a tilde.');
		})
	})
})
```

Running this spec gives the following output:

>   1) Various tests
       Downloads file:
      Timed out retrying after 30000ms
      + expected - actual
      -'This character: "\\x7e" is called a tilde.'
      +'This character: "~" is called a tilde.'
      at Context.eval (http://localhost:27243/__cypress/tests?p=cypress\integration\various.js:106:30)

### Cypress Version

8.0.0, 9.0.0, 9.4.1

### Other

Thanks for helping!

**Comment by BlueWinds** [comment]
This is because the `binary` encoding... is not actually binary. It is an alias for `latin1', [same as in node](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings).

For working with binary data in cypress, we instead suggest using the `null` encoding, which will probably behave more like you expect:

```
describe('Various tests', () => {
	it('Downloads file', () => {
		cy.request({
			url: 'http://localhost/tilde.txt',
			encoding: null
		}).then(response => {
      console.log(Cypress.Buffer.from(response.body).toString())
			cy.writeFile('cypress/documents/tilde-request.txt', Cypress.Buffer.from(response.body), null);
			cy.wrap(Cypress.Buffer.from(response.body).toString()).should('eq', 'This character: "\\~" is called a tilde.');
		})
	})
})
```

Note how it now has "\~" in the string - it's dealing with the data straight off the disk.

With that said, it would be good for consistency's sake if `cy.request` returned a Cypress.Buffer for `null` encoding, same as `cy.readFile()` and `cy.fixture()` - but at the moment it returns an ArrayBuffer, which you can either work with directly or turn into a Cypress.Buffer as is convenient.

**Comment by yhaiovyi-tripactions** [comment]
@BlueWinds I'm having exactly the same problem with `cy.reply` used with an endpoint returning `{"regexp":"\\~$"}`, it's replaced with `\\\x7e` and that one fails on the frontend.
