### ISSUE TITLE
Fail Cypress builds when video fails to encode

### ISSUE THREAD

**Issue by BlueWinds** [cypress-io/cypress#20081]
### What would you like?

Currently, we have no good way of telling when video fails to encode in our tests. We have an ongoing issue where video always fails in Firefox, and our builds are still green; If video were to begin failing in chrome (eg, on very short tests, intermittently, or in other ways not covered by our specific video-encoding tests), we wouldn't get any notification.

We should consider either making our tests in circleci fail if they don't produce video, or setting up some other sort of alerting around video encoding.

**Comment by flotwig** [comment]
If all my tests passed, but video failed, I wouldn't necessarily want my CI job to fail, since the video is irrelevant. 

I guess the only reason it is this way is that Cypress's video recording is flaky, so failing jobs every time video recording flakes would be an issue. If the video recording wasn't flaky, it would probably be less of an issue to fail on video recording errors.

**Comment by rockhold** [comment]
Discussing in backlog review, it seems that this likely needs some product direction before anyone picks it up. Adding a comment here for visibility.

**Comment by BlueWinds** [comment]
Going to close this as not planned, it's a rather old internal issue, and those never age well.
