### ISSUE TITLE
Session gets cleared

### ISSUE THREAD

**Issue by varunrayen** [cypress-io/cypress#2015]
### Current behavior:

In my web app, i'm testing the login and navigating to the profile page using a dropdown menu. The login works and I am able to click the dropdown menu. As soon the menu is clicked, It logs out from my session and redirects to the log in page. How can I prevent this?

### Desired behavior:

It should keep the session and navigate to the profile page.

Using Cypress 3.0.1

**Comment by chrisbreiding** [comment]
Can you post your test code? We'll need that at a minimum to help determine what the issue is.

**Comment by varunrayen** [comment]
```
it("can login using an account", () => {
    cy.get('input[name=username]').type('testuser', {force: true})
    cy.get('input[name=password]').type('password.', {force: true})
    cy.get('button#submit').click({force: true})
    cy.get('#modal-acknowledged')
    .click()
  })

  it("should log in the user", () => {
    cy.contains('testuser')
  })

  it("should go to profile page", () => {
    cy.contains('Investment').click()
  })
```

Above is the example code,
-  it logs in using the username and password
- checks for username `testuser`
- when it tried to click on the `investment`, it logs out and goes back to login page.

**Comment by chrisbreiding** [comment]
Any given test (code in an `it` block) is run independently and browser state (cookies, local storage, etc) is cleared between them, so you start with a clean slate and won't have state built up between tests. I'd recommend putting the code in your first test ("can login using an account"), into a `beforeEach` so it runs before each test.

```
describe('logging in', () => {
  beforeEach(() => {
    cy.get('input[name=username]').type('testuser', {force: true})
    cy.get('input[name=password]').type('password.', {force: true})
    cy.get('button#submit').click({force: true})
    cy.get('#modal-acknowledged')
    .click()
  })

  it("should log in the user", () => {
    cy.contains('testuser')
  })

  it("should go to profile page", () => {
    cy.contains('Investment').click()
  })
```

There are also strategies to log in without going through the UI for subsequent tests to speed them up. Here's an [example with an HTML form](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__html-web-forms/cypress/integration/logging-in-html-web-form-spec.js#L81) and an [example using XHR](https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/logging-in__xhr-web-forms/cypress/integration/logging-in-xhr-web-form-spec.js#L140).

**Comment by brian-mann** [comment]
Also here please read our best practices (all of them are good) but this one in particular calls out this antipattern.

https://docs.cypress.io/guides/references/best-practices.html#Having-tests-rely-on-the-state-of-previous-tests

**Comment by varunrayen** [comment]
The issue I face is, I am trying to test a flow right from logging in until making a investment. The steps included are 
- Log in as a user
- Select a campaign for investment
- Choose an amount to invest
- Agreed to certain terms & conditions
- Fill up the payment form 
- Investment is made

In this case, I doubt that I cannot use login in a `beforeEach` hook because it would break the flow. How could this be tested? Any suggestions?

**Comment by brian-mann** [comment]
@varunrayen what you're asking about is extremely common - I would say that virtually all web applications are doing the same kind of testing, you can swap out any of the words and everyone has to effectively do something like this.

You can simply make that one giant test if you're interested in testing that flow e2e - that's it, it's not any more complicated than that.

However, because we build stateful applications on the web, strict flows such as this do not model how users behave, or the choice / pattern trees that make up behavior.

If you tried to model all of the potential back/forward/refresh/cancel choices between all of those movements you wouldn't get a straight line - you would likely get a "bush" of different paths.

Because of this, it's typically much more effective to test each step **in isolation** away from the others. All together they make up a flow, but by breaking them down and providing the entry point / state for each one independently from one another, you more comprehensively cover every situation in a highly performant, controlled manner.

With that said, do whatever works for you. A single test focusing on this flow is fine if that works for you. Using the `beforeEach` model is perfectly adequate to model this. A flow as you're describing does not involve breaking down the pieces and therefore you would use a single test to test this flow.
