### ISSUE TITLE
When using CDN download links in commit messages, support relative build numbers

### ISSUE THREAD

**Issue by JessicaSachs** [cypress-io/cypress#20160]
## Summary

As we do internal manual testing using the CDN download links within each commit, it's difficult to report what version of Cypress we're running. We need a dropdown (maybe in the launchpad, maybe in the server – somewhere) that reports what version we're running.

## Acceptance Criteria

1. Should be able to determine what internal build a user is on.
2. Ideally this build contains either a date or other sequential numbering.

**Comment by jennifer-shehane** [comment]
Can we distribute the prerelease binary in a way that is unique so that users will not need to clear their cache. We've had MANY instances of internal testing where someone finds a 'bug', reports it, and it turns out they just didn't clear their cache. This also isn't very clearly documented that clearing the cache is absolutely necessary. This would accelerate the review process of the 10.0 release.

**Comment by flotwig** [comment]
I'd love it if we could have something straightforward, like `branchName-1`, `branchName-2`, `branchName-3`, be the names of the builds.

Unfortunately, outside of building some standalone service that keeps track of our monotonically increasing build number, I don't think there is a good way to do this with Circle.

Circle has [`CIRCLE_BUILD_NUM`](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables) which does monotonically increase, but it increments for every single job run as part of a workflow. So it will change for each OS we build on, it will change on each retry, and it will skip ~100 or so numbers every build because of the number of jobs we run.

[Feature request here for Circle to support monotonically increasing build #'s in the way we want.](https://circleci.canny.io/cloud-feature-requests/p/add-a-build-number-for-workflow-runs-shared-by-all-jobs-in-a-workflow)

---

The solution in #20296 bakes the commit SHA, the commit branch, and the commit timestamp into the CLI itself. It also adds output to `cypress info`, `cypress install`, and `cypress version` that each displays this info to some level of detail.

The existing changes should meet the requirements of the OP, so I'll close this issue If we do want to add this to the `launchpad`/`app` UI at some point, it should not be too much of a lift.
