### ISSUE TITLE
Cypress disconnects my web application under test If I put all the commands methods in multiple it blocks under single describe

### ISSUE THREAD

**Issue by shagupta92042** [cypress-io/cypress#20182]
### Current behavior

It is disconnecting my web application server and UI remains interactive if I put all the commands methods in multiple it methods where as if I put all the commands in a single it methods then it works absolutely fine.

### Desired behavior

It should not disconnect my web app under test as I am not giving any xpath or selector to disconnect my server yet it disconnects my web app at any step.

### Test code to reproduce

**If I run below code using multiple it methods inside a single describe then any of the it method gets failed at any step and it disconnects my web application server itself and does not allow me to reconnect :**
```
describe('Limit Order Tc' ,{tags: ['@shashank']}, () =>{
   before(() => {
      cy.visit('http://localhost:8088/')
   })

it('login to UI', () =>{
  cy.login(tests[1].client_id , tests[1].userName)
})
it('select Dashboard', () =>{
  cy.selectDashboard()
  cy.wait(30000)
})
it('placeOrder',()=>{
  cy.placeOrder()
 })
it('orderWidget', () =>{
  cy.orderValidation()
 
  })
it('editAndLoadWatchlist', () =>{
  cy.editAndLoadWatchlist()
  cy.wait(10000);
})
});
```
**Below code is working fine if I merge all the methods in a single it block.**
```
describe('Limit Order Tc' ,{tags: ['@shashank']}, () =>{
  
  before(() => {
   cy.visit('http://localhost:8088/')
  })

it('login to UI', () =>{
  cy.login(tests[1].client_id , tests[1].userName)
  cy.selectDashboard()
  cy.wait(45000)
  cy.editAndLoadWatchlist()
  cy.wait(1000);
  cy.placeOrder()

  })
```

### Cypress Version

Cypress package version: 9.1.1 Cypress binary version: 9.1.1

### Other

Cypress package version: 9.1.1
Cypress binary version: 9.1.1
Electron version: 15.2.0
Bundled Node version:
16.5.0

**Comment by BlueWinds** [comment]
It's a lot easier to read code pasted into github if you enclose it in triple ticks, like so:

```
code
```

I've gone ahead and edited some into your comment.

This doesn't look like a bug to me. Each individual `it` is a *separate test* - Cypress clears everything between tests, so that each can be run separately.

`describe` blocks are used to *group tests*, while `it` is used to *group commands into a single test.* If you want the commands to run in sequence in the same environment, then you want them in same test!
