### ISSUE TITLE
Do not have Write Access of root folder when installing cypress using docker image cypress/base:16.13.2

### ISSUE THREAD

**Issue by Techevan** [cypress-io/cypress#20286]
### Current behavior

I'm trying to use docker image **cypress/base:16.13.2** and install cypress inside my node project, however getting following errors:

cdp_cypress_test_container | npm ERR! code 1
cdp_cypress_test_container | npm ERR! path /opt/****/node_modules/cypress
cdp_cypress_test_container | npm ERR! command failed
cdp_cypress_test_container | npm ERR! command sh -c node index.js --exec install
cdp_cypress_test_container | npm ERR! Cypress cannot write to the cache directory due to file permissions
cdp_cypress_test_container | npm ERR!
cdp_cypress_test_container | npm ERR! See discussion and possible solutions at
cdp_cypress_test_container | npm ERR! https://github.com/cypress-io/cypress/issues/1281
cdp_cypress_test_container | npm ERR!
cdp_cypress_test_container | npm ERR! ----------
cdp_cypress_test_container | npm ERR!
cdp_cypress_test_container | npm ERR! Failed to access /root/.cache/Cypress:
cdp_cypress_test_container | npm ERR!
cdp_cypress_test_container | npm ERR! EACCES: permission denied, mkdir '/root/.cache/Cypress'
cdp_cypress_test_container | npm ERR!
cdp_cypress_test_container | npm ERR! ----------
cdp_cypress_test_container | npm ERR!
cdp_cypress_test_container | npm ERR! Platform: linux-x64 (Debian - 10.11)
cdp_cypress_test_container | npm ERR! Cypress Version: 9.5.0
cdp_cypress_test_container |
cdp_cypress_test_container | npm ERR! A complete log of this run can be found in:
cdp_cypress_test_container | npm ERR!     /root/.npm/_logs/2022-02-21T07_21_09_524Z-debug.log

It seems cypress trying to write files to root directory (/root/.cache/Cypress, not project root) but doesn't get write access. **Checked issue #1281 but doesn't work if setting ENV. CYPRESS_CACHE_FOLDER during docker image building.**

**It works fine for docker image cypress/base:latest. (npm version = 6)**

The reason I would use version newer is to use npm > 7. The issue can also be reproduced when using cypress/base:latest and do upgrade npm during docker image building process.

### Test code to reproduce

**Dockerfile**:

FROM cypress/base:16.13.2
 
COPY ./artifact /opt/artifact
 
RUN mv /opt/artifact/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh && \
    chmod 777 /usr/local/bin/docker-entrypoint.sh && \
    ln -s /usr/local/bin/docker-entrypoint.sh /docker-entrypoint.sh && \
    echo "done"
 
ENTRYPOINT ["/docker-entrypoint.sh"]

### Cypress Version

9.5.0

**Comment by dc-wc-2017** [comment]
I ran into the same issue. I tried setting up CYPRESS_CACHE_FOLDER according to https://docs.cypress.io/guides/getting-started/installing-cypress#Binary-cache but no luck.

My npm version is 8.5.1

**Comment by codepunkt** [comment]
Same here, doesn't work with latest NPM.

**Comment by irangarcia** [comment]
Same. I had to downgrade my npm version

**Comment by DeividVeloso** [comment]
Same here

**Comment by pszabop** [comment]
It appears Cypress is modifying contents of the home directory when installing from npm, rather than installing everything under the current directory (e.g. in `node_modules/`).

I had the same thing happen with user as `node` in a docker container.   It would install stuff on /home/node, instead of /home/node/app/ which was the mounted directory.  Then that stuff went away when the container exited.

It is not desirable for npm packages to install things in the current user's home directory.

This also breaks many dev setups for using docker and mounting a directory that contains the package.json, and running `npm install` inside the container.

This docker file with the following line in package.json will reproduce the problem easily.

```
FROM cypress/base:14

WORKDIR /home/node/app

RUN npm install -g @aws-amplify/cli

CMD [ "/bin/bash" ]
```
```
    "cypress": "^9.7.0",
```

**Comment by timothylombrana** [comment]
Same here:

Image: `cypress/browsers:node16.13.2-chrome100-ff98`
Error: EACCES: permission denied, open '/github/home/.cache/Cypress/10.3.1/binary_state.json'
----------
Platform: linux-x64 (Debian - 10.11)
Cypress Version: 10.3.1

**Comment by alecmestroni** [comment]
Same error, some news?
Image: [cypress/browsers:node16.14.2-slim-chrome100-ff99-edge](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/node16.14.2-slim-chrome100-ff99-edge)

**Comment by Seth10001** [comment]
Setting this environment variable worked for me:

```
ENV CYPRESS_CACHE_FOLDER /app/.cache
```

**Comment by aromeronavia** [comment]
Having this same issue. Setting the ENV variable in the previous comment didn't work T.T

**Comment by QABob3** [comment]
> Setting this environment variable worked for me:
> 
> ```
> ENV CYPRESS_CACHE_FOLDER /app/.cache
> ```

I tried this from /Users/usr as well as from the cypress project got the same error: 
ENV: CYPRESS_CACHE_FOLDER: No such file or directory

**Comment by mike-plummer** [comment]
@QABob3 Did you add that to your Dockerfile? The syntax of the error message and your reference to running it "from a directory" makes me think you were running it as a terminal command, maybe?

If anyone is still experiencing this issue after properly setting the `CYPRESS_CACHE_DIR` environment variable please post a reproducible example (full Dockerfile, ideally in a `git` repo we can clone and run locally). You can also take a look at [`cypress/factory`](https://hub.docker.com/r/cypress/factory) which allows you to build a much more customized Docker base image that already has Cypress installed by the `build` stage (rather than at runtime).
