### ISSUE TITLE
Edge 100 - Viewport size in headless mode

### ISSUE THREAD

**Issue by EtienneBruines** [cypress-io/cypress#20288]
### Current behavior

On Microsoft Edge 100 (on Linux), while running Cypress in headless mode, the viewport is incorrect.

Note that this is not 1366x660 (which is defined): 
![Navigating without authentication -- should be able to load the login-page successfully (failed)](https://user-images.githubusercontent.com/3962174/154944283-6c709493-0291-4afc-a22b-9eed5a0ae3f4.png)

Especially annoying if the spec depends on the viewport size, otherwise you'll run into:

```
This element `<img#auth-template--logo.logo>` is not visible because its 
content is being clipped by one of its parent elements, which has a CSS 
property of overflow: `hidden`, `scroll` or `auto`
```

### Desired behavior

The viewport should be the size as defined in my configuration.

### Test code to reproduce

Any spec. 

Can reproduce both on my local dev machine as well as on GitLab CI.

### Cypress Version

9.5.0 and 9.4.1 (and possibly older)

### Other

The issue does not occur on Google Chrome 100, nor on Firefox. Microsoft Edge 99 also seems happy.

Headed mode with Microsoft Edge 100 is also fine - headless is the issue.

**Comment by stephen-spar** [comment]
Also experiencing this issue - running tests using Edge 100 in headless mode via AWS CodePipeline/CodeBuild is resulting in the same tiny viewport as OP and is causing all of my tests for Edge to fail (also due to same `not visible` issue as OP). 

Using the latest official docker image [from here](https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node14.10.1-edge88) to run the tests (which is odd, as the repo explicitly states the image should be installing edge v88, but the Dockerfile commands don't enforce that - anyways that's a separate issue that should be logged in the other repo I guess).

**Comment by EtienneBruines** [comment]
Seems to work again in the latest Edge 100 minor release.
