### ISSUE TITLE
Add support for {home} and {end} special character sequences

### ISSUE THREAD

**Issue by kyleoliveiro** [cypress-io/cypress#2033]
### Current behavior:

`cy.type('{home}')` and `cy.type('{end}')` are not supported:

```
CypressError: Special character sequence: '{home}' is not recognized. Available sequences are: {selectall}, {del}, {backspace}, {esc}, {{}, {enter}, {leftarrow}, {uparrow}, {rightarrow}, {downarrow}, {alt}, {option}, {ctrl}, {control}, {meta}, {command}, {cmd}, {shift}
```

```
CypressError: Special character sequence: '{end}' is not recognized. Available sequences are: {selectall}, {del}, {backspace}, {esc}, {{}, {enter}, {leftarrow}, {uparrow}, {rightarrow}, {downarrow}, {alt}, {option}, {ctrl}, {control}, {meta}, {command}, {cmd}, {shift}
```

### Desired behavior:

Support the `{home}` and `{end}` special character sequences.

### Versions

Cypress 3.0.1

**Comment by jennifer-shehane** [comment]
Great suggestion. The code for special characters can be found here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cypress/keyboard.coffee#L11

As a workaround, you should be able to create a custom command for these by triggerering the keyboard events after knowing the keyCode like this:

```js
Cypress.Commands.add('homeKey', {prevSubject: 'element'} (subject, opts) => {
  cy.wrap(subject).trigger('keydown', {
      keyCode: 36,
      which: 36,
      shiftKey: shiftKey,
      ctrlKey: ctrlKey
  });

  return subject
});

Cypress.Commands.add('endKey', {prevSubject: 'element'} (subject, opts) => {
  cy.wrap(subject).trigger('keydown', {
      keyCode: 35,
      which: 35,
      shiftKey: opts.shiftKey,
      ctrlKey: opts.ctrlKey
  });

  return subject
});
```

**Comment by brian-mann** [comment]
That'll fire a single event but it won't move the cursor or perform the default action and we're missing stuff like `keypress` and `keyup`.

**Comment by kyleoliveiro** [comment]
Also consider adding support for {pgup} and {pgdown}.

**Comment by brian-mann** [comment]
@Bkucera 	can you comment on this issue since it's being addressed in your native events PR / keyboard enhancements. Tag it or mark as duplicate / explain what we're doing in the upcoming release, etc.

**Comment by Bkucera** [comment]
as @brian-mann mentioned, [Native Events](#311) will allow all of these "special" keys including `pageup`, `pagedown`, `home`, `end`, etc. Using native events, two things are enabled:

1) events fired (`keydown` for example) will be `trusted` (have property `isTrusted:true` and allow privledged apis such as `document.execCommand('copy')` in the event handlers)

2) event can perform its `default action` (for example, `pagedown` would scroll the page`)

Currently, we only support a subset of these special keys because `default actions` are complex to fulfill.

In the PR for adding `{home}` and `{end}` keys [#3071] the `default action` is fulfilled only for the case where the focused element is a text editable- using a [non-standard browser API](https://developer.mozilla.org/en-US/docs/Web/API/Selection/modify) which is not in IE11. That being said I'm happy with that strategy if users rely on the default action of `home/end` in their tests.

@kyleoliveiro do you need the default action performed or are you using `e.preventDefault()` in your event handler?

**Comment by Ajith456** [comment]
Hi Jennifer-Shehane, I'm new for Cypress.io and I'm not able to write test case for check the length of password please help me. and i need sample projects also and i waiting for your replay.


thank u

**Comment by skorunka** [comment]
This is a very usefull feature to add! Thanks.

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by skorunka** [comment]
Great job! Thanks.
