### ISSUE TITLE
webpack-dev-server always compiles all spec files

### ISSUE THREAD

**Issue by BlueWinds** [cypress-io/cypress#20359]
### Current behavior

Webpack-dev-server currently compiles all spec files even when only a single one is needed, resulting in slow compilation of even simple component tests when an application is large.

### Desired behavior

When we only need one spec file, we should only compile that one file (and its dependencies).

### Test code to reproduce

With https://github.com/cypress-io/cypress-realworld-app/tree/10.0.0: 

```sh
$ npx cypress run --ct --spec src/components/AlertBar.cy.tsx
```

![image](https://user-images.githubusercontent.com/3003404/155610141-5d061db0-27f2-44be-98b9-514e84cfe147.png)

Notice how even though only AlertBar.cy.tsx is needed, there are chunks for spec-0, spec-1, spec-2, etc - one for each component test in the repo. The dependency graph is therefore extremely large. The same thing happens in open mode - opening a single spec results in the entire application being compiled.

### Cypress Version

9.5.0

### Other

In `npm/webpack-dev-server/src/makeWebpackConfig.ts`, we pass a list of every spec file in the repository into `CypressCTOptionsPlugin`. We should instead consider passing in only the support file initially, and in the plugin listening for server events requesting specific additional files. We can then compile them on-demand, rather than all up-front.

**Comment by JessicaSachs** [comment]
> We should instead consider passing in only the support file initially, and in the plugin listening for server events requesting specific additional files. We can then compile them on-demand, rather than all up-front.

Architecturally, please let the dev-servers subscribe and behave to the events as they'd like to. The implementations are so different that something very performant for one implementation can be detrimental to the other.

---

**On performance...**

When it comes to the performance of the webpack-dev-server and vite dev servers, a good approximation of what you can expect can be found by looking at similar tools to ours, like Storybook. For Storybook (which is usually Webpack), **a minimum 30s or 2.5 minute compile time is very normal**.

> We follow a similar architecture and so we have the same problems.
> What I’m planning to change is:
> For `dev-server:start`, Cypress will pass in an empty list of specs. This will result in immediate compilation of the support file and our own CT entrypoint, which should be relatively quick.
> When the runner wants to execute a file, it emits dev-server:specs:changed, passing in only the spec file it wants to execute. It will wait for dev-server:compile:success before attempting to load in.

This was the previous behavior.

It felt “slow” to use when you were developing in Open Mode.

**When you're in open mode** and you're adding additional dependencies and importing more components, your app needs to do significant compilation (10-15s between reloads) whenever you add more files. This is because Babel needs to recompile everything and generate new vendor chunks, etc, based on if any new files were added to the dependency tree. 

By loading all specs at first, the recompile time when working in CT and the spec switching time was instant.

It made the app feel much better for sessions lasting more than the **first run of the first spec.**

**When you’re in run mode**, you know you’re going to run all of the specs passed into `dev-server:start`, so allowing Webpack to optimize the chunks as it sees fit is the most efficient way to do it.
Any performance tuning we do needs to be done against a large codebase like RWA by using the webpack performance profiler.

The two biggest performance gains you’ll have are:
* turning off source maps by setting devtool: false
* Optimizing babel (this is usually what [your webpack profiler](https://webpack.js.org/plugins/profiling-plugin/) will tell you). This is usually done via a file-system babel-cache directory. Probably similar to what you’re mentioning.

**Now… Webpack and Vite have significantly different dependency scanning algorithms and phases.**

Vite already only compiles what’s fetched over the network, but we give it ALL of the files that are going to be loaded before the browser makes any requests so that it’s able to precompile certain CJS/large dependencies.

The points at which the build is expensive differs as well. For Vite, the most expensive part is discovering new dependencies (e.g. a “watch” adding a new file to the compilation) because it means that all optimized 3rd party chunks need to be invalidated and recompiled.

I’d ask that any changes you make for webpack dev server, you make when both performance profiling and using the app. The time between rebuilds is a huge concern. Please also keep changes scoped to the specific dev-server unless it makes sense for all of them.

Each dev-server has its own performance tuning tips and tricks.

Certain dev-servers will have their own internal module cache (Vite). For the Cypress webpack dev server, you should approach it just like any app’s devserver that you’re trying to optimize.

For the Cypress Vite Dev Server, please hold off on changes. I’m in the middle of rewriting it to make use of the hooks the Vite team has given us in order to avoid refreshing the page and adding many seconds to the build.
