### ISSUE TITLE
Cypress 3 complains about covered elements that make no sense

### ISSUE THREAD

**Issue by aldarund** [cypress-io/cypress#2037]
### Current behavior:

In 2.1.0 tests work fine. In 3.0(1) cypress test fails because cypress think that elements covered, but that just dont make any sense. For example:
```
CypressError: Timed out retrying: cy.click() failed because this element:
<a href="/auth/signup" class="v-btn v-btn--block v-btn--router primary white--text">...</a>
is being covered by another element:
<html lang="en" data-n-head="lang">...</html>
```
Or like this
```
CypressError: Timed out retrying: cy.click() failed because this element:
<button type="button" primary="" data-cy="signup" class="v-btn v-btn--block primary">...</button>
is being covered by another element:
<i data-cy="invalid-check" aria-hidden="true" class="v-icon grey--text text--lighten-1 mdi mdi-close-circle-outline"></i>
```

### Desired behavior:

No errors with hovered elements like in 2.1

### Versions

Windows 10, Chrome 68

**Comment by jennifer-shehane** [comment]
The first error message definitely looks unusual.

Could you provide an example of some html / tests that throw this error? We won't be able to investigate this issue without a reproducible example. If it is private code, try recreating the css/html just to reproduce the error.

**Comment by aldarund** [comment]
@jennifer-shehane https://beta.tenantreport.net - here is url
test that produce first error
```
  it('Go to signup', () => {
    cy.contains('a', 'Try It Now').click()
    cy.contains('button', 'Sign up')
  })
```
test that produce second error
```

  it('Visits signup page', () => {
    cy.visit('/auth/signup/')
  })

  it('Fill signup page', () => {
    cy.visit('/auth/signup/')
    cy.get('input[name=landlordType]')
      .click({ force: true })
      .then(() => {
        cy.contains('estate agent').click()
      })
```

Both code work fine in 2.1.0

**Comment by jennifer-shehane** [comment]
I am not experiencing this on my Mac in Chrome 67 or Canary 69. Will have to check in Windows/Chrome 68.

<img width="381" alt="screen shot 2018-06-26 at 5 14 48 pm" src="https://user-images.githubusercontent.com/1271364/41939644-75b73ecc-7964-11e8-8421-07f9f692c37e.png">

Are you running these tests in 'interactive mode' or by running it using `cypress run`?

**Comment by aldarund** [comment]
@jennifer-shehane cypress open.  Here screenshot when i run agains that url : https://i.imgur.com/4s8aT95.png

**Comment by aldarund** [comment]
@jennifer-shehane tried cypress run. This two test works fine with cypress run. But another bug -> https://github.com/cypress-io/cypress/issues/2044

**Comment by aldarund** [comment]
3.0.2 still have same problem

**Comment by Vitao18** [comment]
I'm also having the same issue. Many of my tests broke when upgrading from version 2.x to 3.0.2
Errors are all very similar to each other:

`CypressError: Timed out retrying: cy.click() failed because this element is not visible:

<button tabindex="0" class="jss104 jss89" type="button" id="new-ticket-button">...</button>

This element '<button#new-ticket-button.jss104.jss89>' is not visible because it has CSS property: 'position: fixed' and its being covered by another element:

undefined

Fix this problem, or use {force: true} to disable error checking.`

`CypressError: Timed out retrying: cy.type() failed because this element is not visible:

<input aria-invalid="false" aria-required="true" class="jss29" name="user" required="" type="text" value="">

This element '<input.jss29>' is not visible because it has CSS property: 'position: fixed' and its being covered by another element:

<label class="jss16 jss11 jss12 jss15" data-shrink="false">...</label>

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
`

**Comment by brian-mann** [comment]
We're aware of some issues regarding visibility that need refactoring. However in order to prioritize these issues we must have a reproducible repo.

Simply pasting the error is not enough. We have hundreds of tests around clicking and visibility, and need specific scenario's in which the algorithms aren't working.

Per your comment @Vitao18 we have no idea if this should even be happening or not. Is the element really being covered? Have you tried `{ force: true }`? Was this happening on `2.x.x`? Have you tried `3.0.1`? Does this happen in `cypress open` vs `cypress run`? Can you paste an animated gif? Can you send us your test code.

**Comment by Vitao18** [comment]
> Per your comment @Vitao18 we have no idea if this should even be happening or not. Is the element really being covered? Have you tried { force: true }? Was this happening on 2.x.x? Have you tried 3.0.1? Does this happen in cypress open vs cypress run? Can you paste an animated gif? Can you send us your test code.

My tests where passing in version 2.x.x.
They break when upgrading to version 3.0.1 or 3.0.2
It happens in cypress run but not in cypress open. I'll try to make a reproducible example and paste it here

**Comment by aldarund** [comment]
@jennifer-shehane any luck replicating issue?

**Comment by larkintuckerllc** [comment]
FYI... I just installed Cypress 3.0.2 (and then reverted back to 3.0.1) and going through the tutorial, I get the same "cover" error message on the following test in both cases.

```
describe('My First Test', function() {
  it('clicks the link "type"', function() {
    cy.visit('https://example.cypress.io')

    cy.contains('type').click()
  })
})
```

Finally started over with version 2.1.0 and it was successful.  Something is odd here.

**Comment by aldarund** [comment]
@larkintuckerllc what os are u using and what version of chrome?

**Comment by larkintuckerllc** [comment]
Ok... Here is some more info...

OS: macOS High Sierra, Version: 10.13.5
Browser: Version 68.0.3440.59 (Official Build) beta (64-bit)

Shows up in Cypress as "Chrome 68".  Here is the screenshot of the error:

note: I happen to know that I have not taken MacOS updates for a bit (will try that next).

![screen shot 2018-07-17 at 3 11 07 pm](https://user-images.githubusercontent.com/4379100/42840195-054ee47a-89d4-11e8-8301-633b40b10495.png)

**Comment by larkintuckerllc** [comment]
A bit more information... Upgraded OS to MacOS 10.13.6 (no change).

BUT... Downgraded my browser to: Chrome Version 67.0.3396.99 (Official Build) (64-bit)

And the test was successful.

**Comment by larkintuckerllc** [comment]
![screen shot 2018-07-17 at 3 38 50 pm](https://user-images.githubusercontent.com/4379100/42841372-d5e182ca-89d7-11e8-9338-b570e80c61ac.png)

**Comment by aldarund** [comment]
Version 68.0.3440.68 (Official Build) beta (64-bit) - still not working :(

**Comment by gregtillbrook** [comment]
Im also experiencing the errors 'is being covered by another element <html lang="em"...'

Im on `macOS Sierra 10.12.4` and using chrome `Version 68.0.3440.75 (Official Build) (64-bit)` (was also seeing the error with chrome 67)

**Comment by albertored** [comment]
Same here on `Ubuntu 16.04` and `Google Chrome 68.0.3440.75`. Downgrading to `Google Chrome 67.0.3396.79` solves the issue.

**Comment by kapalkat** [comment]
I have the exact same thing after my Chrome updated to 68 version. Previously it was ok with 67 and Cypress 3.0.2.
What I did as a workaround: I switched on test runner to Electron 59 and it works fine now!
Worry about my production tests as it is also using Chrome...headlessly though so maybe it's gonna work. Will check that and update my post here.

**Comment by jennifer-shehane** [comment]
Now having this fail in our own Cypress project on Chrome version 68.0.3440.75. This error is not happening in Canary 70...which makes me feel like this is a Chrome error. Trying to track this down in their issue.

**Comment by aldarund** [comment]
Well, if it's chrome error why it work fine in Cypress 2?
Also it certainly before build 59. At the moment I created issue there was either build 34 or 43 at that time.

**Comment by aepplerplangrid** [comment]
Running into this same issue

**Comment by jennifer-shehane** [comment]
Alright, I've narrowed down the issue. We recently added the `--disable-blink-features=RootLayerScrolling` flag to Cypress on browser launch to fix [this issue](https://github.com/cypress-io/cypress/issues/1620). 

It appears that this flag is now causing the issue within this thread, where the registered click positions of elements are shifted, so that the area Cypress calculates to click at, is not the coordinate that Chrome is listening at due to a bug. I have not tracked down the bug in Chromium yet because their bugs list is insanely long. 

Hopefully removing this flag does not cause the AUT to shake again. I am not seeing this behavior anyway.

**The Workaround Today**

Within your `cypress/plugins/index.js` file, we will want to remove the `--disable-blink-features=RootLayerScrolling` flag from the flag arguments being sent to chrome before launch.

```js
module.exports = (on) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {

      args = args.filter((arg) => {
        return arg !== '--disable-blink-features=RootLayerScrolling'
      })

      return args
    }
  })
}
```

**Cypress Fix**

We will remove this flag in our next release of Cypress after tracking down the exact Chromium issues and ensuring the AUT shaking bug does not return.

**Comment by brian-mann** [comment]
We are going to remove `--disable-blink-features=RootLayerScrolling` for Chrome versions higher than 68

**Comment by brian-mann** [comment]
The AUT shaking was primarily affecting versions 66 and 67, so it seems safe to remove although it is still an open bug on Chromium's bug tracker

**Comment by kkor** [comment]
I was trying out Cypress for the first time the day before yesterday, and I could run the "Writing Your First Test" tutorial.
Yesterday Chrome installed the new update (Version 68.0.3440.75 (Official Build) (64-bit), on MacOS Sierra 10.13.6), but was still pending for a browser restart on the 67 version when the simple_spec.js started failing. After a restart & computer restart it still was failing and downgrading Chrome seems to be a hassle (if even possible).

As kapalkat said running with other browsers fixes the issue:
cypress run --spec 'cypress/integration//simple_spec.js' --headed --no-exit --browser canary
cypress run --spec 'cypress/integration//simple_spec.js' --headed --no-exit --browser electron

But this is not a good first impression D:

**Comment by pawelgalazka** [comment]
Can confirm, had the same issue. @jennifer-shehane your work around helped

**Comment by gramie** [comment]
I was getting this error this morning, whereas it was working perfectly yesterday (and I made no changes). I'm using the local version of Cypress on OSX, and when my computer woke up this morning there was an error message about not being able to contact the server or something.

Closing Cypress.app and restarting it solved the problem.

**Comment by egucciar** [comment]
I'm still having this problem, what is the proposed fix? Do i need to C/P those LOCs above? Just upgraded to 3.1 in attempt to have this solved to no avail

**Comment by jennifer-shehane** [comment]
@egucciar Ensure that you **remove** the following code below from your `plugins/index.js` file (as you may have added this as a workaround previously for https://github.com/cypress-io/cypress/issues/1620)

```js
module.exports = (on) => {
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--disable-blink-features=RootLayerScrolling')
      return args
    }
  })
}
```

**Comment by caroleco** [comment]
Hello there, I'm having the same problem.

Chrome: 68.0.3440.106
Cypress: 5.0.3

**Comment by LeKoArts** [comment]
@jennifer-shehane Still getting this error and https://github.com/cypress-io/cypress/issues/2037#issuecomment-407898194 doesn't help either. Should I open an issue?

**Comment by konekoya** [comment]
Ran into the exact same issue. Upgrading to 3.1.0 fixed the issue for me. Thank you!

**Comment by jennifer-shehane** [comment]
@LeKoArts What version of Cypress are you using?

**Comment by LeKoArts** [comment]
@jennifer-shehane I'm using `cypress@^3.1.0` and the only way my tests are passing right now is by using `.click({ force: true })` which is a real bummer.

**Comment by jennifer-shehane** [comment]
@LeKoArts Could you include some of the errors you are getting / screenshots? Also include what version of Chrome you are using to test?

**Comment by LeKoArts** [comment]
@jennifer-shehane I'm using Chrome 68 if you meant that:

![image](https://user-images.githubusercontent.com/16143594/44814896-4c89f880-abde-11e8-97a4-814fb1eee422.png)

![18_08_8t64470e](https://user-images.githubusercontent.com/16143594/44815196-2153d900-abdf-11e8-9c38-c9cf9a3e6af2.gif)

As you see the element is clearly visible

**Comment by jennifer-shehane** [comment]
@LeKoArts This is an issue related to Cypress calculations used for visibility - where it thinks the element has height/width of 0 at the time of clicking. We need to improve our calculations on this.  

Have you tried using `.click({force: true})`? This will bypass our visibility check. 

See this issue: https://github.com/cypress-io/cypress/issues/2000

This is unrelated to the bug in this issue - which was effectively shifting the coordinates of every DOM element in the application.

**Comment by nikhiletc** [comment]
I am still facing this issue, 
`.click({force: true})`  it doesn't work for me, i am using chrome 69.0.3497.81
any updates ?

**Comment by akapitoha** [comment]
Cypress 3.1.0
Chrome 69.0.3497.100

Attaching a screenshot with my failure (though assert for "Unverified" label works fine)
```
cy.contains(mail_address).should('be.visible')
cy.contains('Unverified').should('be.visible')
```
![2018-09-24 17 06 38](https://user-images.githubusercontent.com/3147449/45957215-2f015080-c01d-11e8-976c-38807e9f7332.png)

**Comment by JamboBuenna** [comment]
Any updates, still seeing this?

**Comment by jennifer-shehane** [comment]
This was a very bizarre issue concerning some Chrome flags in versions over 67 that inadvertently shifted the DOM so that it would cover elements. I am locking this conversation due to many comments about other visibility issues with assumptions that it is related to this use case.

We are aware of many other visibility issues and suggest you search the other issues tagged as such or open a new issue giving a reproducible example. [Existing Visibility Issues](https://github.com/cypress-io/cypress/issues?q=is%3Aopen+is%3Aissue+label%3A%22topic%3A+visibility%22)
