### ISSUE TITLE
Test runner left panel disappears after the salesforce application is open

### ISSUE THREAD

**Issue by scrattescrat** [cypress-io/cypress#20460]
### Current behavior

After log in to the application the test runner **left log panel disappears** after salesforce application is open and execution stops without any error report. Application stays open and execution stops
The message "Chrome is being controlled by automated test software" still exists, but there is no Test Runner left pane.

### Desired behavior

Able to automate the salesforce application using Cypress

### Test code to reproduce

```js
cy.visit('https://testsalesforce-as--testsalesforcefc.lightning.force.com/')
cy.get('#username').type('my_username')
cy.get('#password').type('my_password')
cy.get('#Login').click()
```

### Cypress Version

9.4.1

### Other

The following workaround is no longer supported:
```js
    var URL = "https://testsalesforce-as--testsalesforcefc.lightning.force.com/?un=my_username&pw=my_password"
    cy.request(URL)
    .then(() => {
       cy.visit(URL)        
    }) 
```
    
Salesforce has disabled this feature in it's latest release
https://help.salesforce.com/s/articleView?id=000363298&type=1

**Comment by davidmunechika** [comment]
I tried using your test code to reproduce but wasn't able to reproduce your issue. I am unable to load that URL in the browser or in Cypress.

<img width="1195" alt="Screenshot 2022-03-04 at 10 27 17 AM" src="https://user-images.githubusercontent.com/27690333/156791773-28a99590-806f-4cfc-9ac3-71bd9c303d13.png">

Unfortunately we will have to close this issue if there is not enough information for us to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment in this issue with a reproducible example and we will consider reopening the issue.
