### ISSUE TITLE
Not able to install github integration on cypress dashboard

### ISSUE THREAD

**Issue by apoorv1316** [cypress-io/cypress#20634]
### Current behavior

It just shows the loader for few seconds then nothing happens.  Please see the loom video for ref. https://www.loom.com/share/0897492ad2c04a9a90bac0cf30e0efc4

### Desired behavior

It should install GitHub app successfully.

### Test code to reproduce

No test code it has nothing to do with tests I guess.

### Cypress Version

9.5.1

**Comment by conversaShawn** [comment]
@apoorv1316 It is possible this is related to a [current GitHub outage](https://www.githubstatus.com/). 

If the issue persists after the issue has been resolved, please @ me.

**Comment by apoorv1316** [comment]
@conversaShawn the issue still persists.

**Comment by conversaShawn** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
