### ISSUE TITLE
Cypress should have a warning when in a Read Only FS not error

### ISSUE THREAD

**Issue by Toxicable** [cypress-io/cypress#2064]
### Current behavior:
Cypress will throw when run in a read only FS.
In my case im running it under Bazel which only allows reading from it's processes unless specific files are stated to be written.

>The error was:
Error: EROFS: read-only file system, mkdir '/home/fabian/.config/Cypress/cy/production/projects'

### Desired behavior:
This error should be caught and handled as a warning that features like project seed, screenshots, video recording will be disabled when being unsed in a Read Only File system.

### Versions
```
Cypress:  3.0.1 
Browser:  Electron 59 (headless) 
Node: 8.11.2
OS: linux x64
```

related: https://github.com/cypress-io/cypress/issues/1281

**Comment by brian-mann** [comment]
How do you install node_modules?

**Comment by Toxicable** [comment]
@brian-mann That's handled by the yarn bazel rules, which is irreverent to this issue.

**Comment by luyishan9118** [comment]
I have the same issue 3 years later.

**Comment by chojnicki** [comment]
4 years, and nothing changed :(

@Toxicable maybe you found solution for this? ;)

In my case for component testing I'm using Cypress inside official docker container. I cannot install it directly inside Node container because it's based on Alpine linux which Cypress does not support. I just mounted my JS project as volume and it works great. But since Cypress in docker runs as root, I want to be sure that it will not mess up my project with any root files, like videos or screenthods. I do not want it to seed anything. Cypress should test my project and simply live it alone, without creating anything... To be sure I mounted volume as read only, but Cypress is not happy about that. Why @brian-mann ? If Cypress is not going to put anything in my project (cypress was initiated, videos/screenshots are disabled) then why it requires access to my source root?
