### ISSUE TITLE
Cypress Runner Fails when Running against Salesforce Org after Login

### ISSUE THREAD

**Issue by DerekWWestAwesomeDeveloper** [cypress-io/cypress#20713]
### Current behavior

Try and open up any Salesforceorg using cypress (make sure you have a salesforce org set up).
Use the instructions [on this link ](https://www.salesforce.com/form/sem/sales-cloud-free-trial-form/?gclid=CjwKCAjwxOCRBhA8EiwA0X8hiz4I-Wm9rsdLl1T2ih23DFo_G7pIcdCp-TnjZyPobV94kz2E69R-UxoCzHwQAvD_BwE&d=70130000000sn94&nc=7010M0000022Bpg&DCMP=KNC-Google&ef_id=CjwKCAjwxOCRBhA8EiwA0X8hiz4I-Wm9rsdLl1T2ih23DFo_G7pIcdCp-TnjZyPobV94kz2E69R-UxoCzHwQAvD_BwE:G:s&s_kwcid=AL!4604!3!372937807370!e!!g!!salesforce%20trial&gclsrc=aw.ds)to set one up if you dont already have one.

Make sure that you have a username and password to log into the page ...

1) Set up your cypress config to point to the base url
I have mine setup something like this:
```json
{
    "baseUrl": "https://test.salesforce.com/",
    "env": {
    },
    "experimentalSourceRewriting" : true,
    "experimentalStudio": true,
    "experimentalSessionSupport" : true,
    "chromeWebSecurity" : false,
    "pageLoadTimeout": 120000,
    "viewportWidth": 1000,
    "viewportHeight": 660    
}
````
2) Setup a spec to try and log into your org.  Something like this:
```js
describe('Trying to Connect to the Dev Genesis Sandbox', () => {
    it('try to get to the Salesforce test site', ()=> {
        cy.loginToSalesforceDev(Cypress.env().testUsers.businessRequestor.user,Cypress.env().testUsers.businessRequestor.secret)
    })
    
})
```
Immediately you'll notice that while it does log in, the salesforce page takes over entirely
Any further tests you attempt to run will absolutely not run.  

### Desired behavior

I would like for the cypress runner to continue to execute so that I can finish testing the rest of my application.

### Test code to reproduce

```js
describe('Trying to Connect to the Dev Sandbox', () => {
    it('try to get to the Salesforce test site', ()=> {
        
//I set up the user and secret in an environment specific config file, feel free to just drop the user and pass in there...
cy.loginToSalesforceDev(Cypress.env().testUsers.businessRequestor.user,Cypress.env().testUsers.businessRequestor.secret)
    })
    
})
```

### Cypress Version

9.5.1

**Comment by emilyrohrbough** [comment]
@DerekWWestAwesomeDeveloper 
We suggest programmatically authenticating your user when running tests. Typically, logging in a user within your app by authenticating via a third-party provider requires visiting login pages hosted on a different domain. Since each Cypress test is limited to visiting domains of the same origin, we can subvert visiting and testing third-party login pages by programmatically interacting with the third-party authentication API to login a user. We don't have API's specifically for authenticating with SalesForce, however we have docs for authenticating with [0Auth](https://docs.cypress.io/guides/testing-strategies/auth0-authentication), [Amazon Cognito](https://docs.cypress.io/guides/testing-strategies/amazon-cognito-authentication), [Okta](https://docs.cypress.io/guides/testing-strategies/okta-authentication), and [Google](https://docs.cypress.io/guides/testing-strategies/google-authentication) you can reference to determine the best approach for your application.

**Comment by DerekWWestAwesomeDeveloper** [comment]
Thanks Emily.  Do you have an example of programmatically logging in my user or can I find that info in the OAuth documentation that you gave me?\

**Comment by emilyrohrbough** [comment]
Please reference the workaround listed here https://github.com/cypress-io/cypress/issues/2367#issuecomment-487972147

**Comment by ShashidharSM** [comment]
@emilyrohrbough Emily, I have followed the workaround in [#2367 and ](https://github.com/cypress-io/cypress/issues/2367#issuecomment-487972147) and got it to work, too. However, the issue reported here still persists - The test-runner/debugger pane on the left disappears after logging in. I suspect this is because of Salesforce Lightning components. 

Please see https://github.com/cypress-io/cypress/issues/22453 for more info.
