### ISSUE TITLE
cy.intercept() not overriding existing alias properly

### ISSUE THREAD

**Issue by sanjayupasi** [cypress-io/cypress#20728]
### Current behavior

In the following test case, **_firstRoute_** is not getting overridden by **_secondRoute_**, i.e cypress should wait for **_secondRoute_** .

Following is the reference screenshot for using cy.intercept()

<img width="1792" alt="Screenshot 2022-03-22 at 7 16 33 PM" src="https://user-images.githubusercontent.com/57387252/159496230-c89b3747-d613-4784-9229-214e6b931725.png">

### Desired behavior

In the following test case, **_firstRoute_** has to be overridden by **_secondRoute_**, i.e cypress should wait for **_secondRoute_** .

Following is the reference screenshot for using cy.route()

<img width="1792" alt="Screenshot 2022-03-22 at 7 17 30 PM" src="https://user-images.githubusercontent.com/57387252/159496608-38e7997d-85ac-42b2-9d70-c740c9180dd8.png">

### Test code to reproduce
```js
describe('cy.intercept', () => {
  it('> cy.route overidding', () => {
    cy.intercept('POST', '**/analytics/3.0/results').as('firstRoute')
    cy.intercept('POST', '**/analytics/3.0/results').as('secondRoute')
    cy.visit('/signup')
    cy.wait('@secondRoute')
    cy.contains('button', 'Teacher').should('be.visible')
  })
})

baseUrl: https://www.khanacademy.org/
```
### Cypress Version

9.5.0, 9.0.0, 7.2.0, 7.0.0

**Comment by missgeeky** [comment]
I was stuck in the same scenario and the below change worked.

describe('cy.intercept', () => {
  it('> cy.route overidding', () => {
    cy.intercept('POST', '**/analytics/3.0/results').as('firstRoute')
    cy.visit('/signup')
    **cy.wait(['@firstRoute', '@firstRoute'])**
    cy.contains('button', 'Teacher').should('be.visible')
  })
})

**Comment by sainthkh** [comment]
Sorry for the late reply. 

Actually, Cypress did wait for `@secondRoute`. 

![Peek 2022-03-28 15-42](https://user-images.githubusercontent.com/8130013/160340979-3c3b0220-6a9a-4cd3-ae4b-a68604fe73d4.gif)

When there are multiple routes to match, Cypress shows them as a number. You can check them out by hovering over it.

**Comment by sanjayupasi** [comment]
We are awaiting response...!!!
@sainthkh @jennifer-shehane @bahmutov

**Comment by sainthkh** [comment]
I also read #9302. And the goal of the issue is to define a new way of behavior for the same route when `cy.intercept()` is called multiple times for the route. It has nothing to do with aliases. 

----

In the case of this issue, the same route is intercepted multiple times with the different aliases. 

"alias" means:

> used to indicate that a named person is also known or more familiar under another specified name.

It's an another name of something. 

The route has 2 aliases: `firstRoute` and `secondRoute`. 

So, not failing when waiting for `firstRoute` is not a bug. 

----

And I personally think this behavior is more intuitive to the new users because we don't usually think making a new alias deprecates the old one. 

----

What we need now is to check if there are cases when deprecating/removing old aliases is unavoidable. 

Maybe, `clearIntercept` [in this comment](https://github.com/cypress-io/cypress/issues/9302#issuecomment-793125450) might solve your problem.

**Comment by flotwig** [comment]
As @sainthkh notes, this is working as intended. You can use the `{ times: 1 }` parameter if you really only want to match once; otherwise, `cy.intercept()` will continue matching infinitely.
