### ISSUE TITLE
Cypress is reporting no specs found, but the spec definitely exists

### ISSUE THREAD

**Issue by mikeerickson** [cypress-io/cypress#20734]
### Current behavior

When I run the following command, cypress states the spec can't be found.

```
npx cypress run -C ../sc-automation/config/cypress.uat.json --spec "../sc-automation/cypress/integration/apis/partner-leads/external-single-partner-lead.spec.ts"
```

Cypress eventually shows the following

```
Can't run because no spec files were found.

We searched for specs matching this glob pattern:

  > /Users/<user>/Documents/clients/abc.com/sc-automation/cypress/integration/apis/partner-leads/external-single-partner-lead.spec.ts
```

### Desired behavior

I would expect cypress to run the defined spec as it surely exists

```
~/Documents/clients/abc.com/sc-automation/cypress/integration/tickets master*
❯ pwd
/Users/<user>/Documents/clients/abc.com/sc-automation/cypress/integration/tickets
```

See here, I am in the directory, and listing files show the spec in question

```
~/Documents/clients/abc.com/sc-automation/cypress/integration/apis/partner-leads master*
❯ ls -la          
total 40
drwxr-xr-x  4 user  staff    128 Mar 20 12:56 .
drwxr-xr-x  6 user  staff    192 Dec 20 17:14 ..
-rw-r--r--  1 user  staff  15476 Mar 20 12:56 external-single-partner-lead.spec.ts
```

### Test code to reproduce

n/a

### Cypress Version

9.5

**Comment by mikeerickson** [comment]
@emilyrohrbough Thank you for the quick response, first off, would you please edit to replace client to replace ***.com with abc.com.  I meant to obfuscate all *.com with abc.com in original message

**Comment by mikeerickson** [comment]
OK, so I have also edited the op to reference `abc.com` consistently, now we can work to resolving my issue after this edit has been made in your initial response

**Comment by mikeerickson** [comment]
For easier communication, here is what I am running

```
❯ npx cypress run -C ../sc-automation/config/cypress.uat.json --spec "/Users/mikee/Documents/clients/abc.com/sc-automation/cypress/integration/apis/partner-leads/external-single-partner-lead.spec.ts"
Can't run because no spec files were found.

We searched for specs matching this glob pattern:

  > /Users/mikee/Documents/clients/abc.com/sc-automation/cypress/integration/apis/partner-leads/external-single-partner-lead.spec.ts
  ```
  
  And again, here is proof that the spec does exist
  
  ```
  ~/Documents/clients/abc.com/sc-automation/cypress/integration/apis/partner-leads master*
❯ ls -la                                   
total 40
drwxr-xr-x  4 mikee  staff    128 Mar 20 12:56 .
drwxr-xr-x  6 mikee  staff    192 Dec 20 17:14 ..
-rw-r--r--  1 mikee  staff  15476 Mar 20 12:56 external-single-partner-lead.spec.ts
```

**Comment by mikeerickson** [comment]
@emilyrohrbough OK, I am *positive* this spec exists (see screenshot)

I have copied the path from VSCode which is represented by second line

![CleanShot 2022-03-22 at 12 40 50](https://user-images.githubusercontent.com/183153/159562578-f28663d3-db02-47ff-9558-2f75b95b4df7.png)

_Note: I have obfuscated `<user>` and `abc.com` in this screenshot and other ticket comments_

**Comment by mikeerickson** [comment]
@emilyrohrbough Hey, just checking in to see if you need more information or have an idea of why this is not working.

**Comment by miblafi** [comment]
Hello @mikeerickson , 

Not sure if you fixed it already but I had a similar issue and I fixed it by adding --config integrationFolder=<path to spec.js>

**Comment by hamzafarooq333** [comment]
If you want to run a specific folder under the integration folder, we need to change the default behavior of cypress in the cypres.config.json file.

By default the cypress does support the execution of the test if the project structure is be like:

- cypress/integration/examples/abc.js

now if we want to run the newly created folder under the integration folder then alter the property into the cypres.config.json file.

- specPattern: 'cypress/integration/**/*.js'

Now cypress will accept all newly created folders under which there will be different specs files.

To run the whole new folder from terminal give command:

node_modules/.bin/cypress run --spec cypress/integration/<new folder name>/* --headed

**Comment by jessicamartinezojedabarcelona** [comment]
I need your help

**I have a problem I have tried the spec Pattern like this:

"test": "cypress run --headless --spec cypress/e2e/test/*.spec.js",
"test": "cypress run --headless --spec cypress/e2e/test/**/*",
"test": "cypress run --headless --spec cypress/e2e/test/*",

The repository is Bitbuket and the server is Bamboo.
and in all I get the error:**

build 06-Jul-2022 12:59:50 [INFO] Cypress 10.0.2 is installed in C:\WINDOWS\system32\config\systemprofile\AppData\Local\Cypress\Cache\10.0.2
build 06-Jul-2022 12:59:50 [INFO]
build 06-Jul-2022 12:59:50 [INFO] added 309 packages from 248 contributors and audited 309 packages in 31,514 s
build 06-Jul-2022 12:59:50 [INFO]
build 06-Jul-2022 12:59:50 [INFO] 39 packages are seeking funding
build 06-Jul-2022 12:59:50 [INFO] run `npm fund` for more details
build 06-Jul-2022 12:59:50 [INFO]
Build 06-Jul-2022 12:59:50 [INFO] found 1 moderate severity vulnerability
build 06-Jul-2022 12:59:50 [INFO] run `npm audit fix` to fix them, or `npm audit` to get more details
build 06-Jul-2022 12:59:50 [INFO]
build 06-Jul-2022 12:59:50 [INFO] --- frontend-maven-plugin:1.12.0:npm (npm cypress run) @ test-automation ---
build 06-Jul-2022 12:59:50 [INFO] npm does not inherit proxy settings from Maven
build 06-Jul-2022 12:59:50 [INFO] Running 'npm run test' in E:\appl\bambooagent\xml-data\build-dir\KIRA-KATM-JOB1\test-automation\src\main
compilation 06-Jul-2022 12:59:51 [INFO]
build 06-Jul-2022 12:59:51 [INFO] > kira_end_to_end_test@1.0.0 test E:\appl\bambooagent\xml-data\build-dir\KIRA-KATM-JOB1\test-automation\src\main
build 06-Jul-2022 12:59:51 [INFO] > cypress run --headless --spec cypress/e2e/test/**/*
compilation 06-Jul-2022 12:59:51 [INFO]
build 06-Jul-2022 12:59:53 [INFO]
build 06-Jul-2022 13:00:08 [INFO] Cannot run because no spec files were found.
compilation 06-Jul-2022 13:00:08 [INFO]
build 06-Jul-2022 13:00:08 [INFO] We are looking for specifications that match this global pattern:
compilation 06-Jul-2022 13:00:08 [INFO]
build 06-Jul-2022 13:00:08 [INFO] > E:\appl\bambooagent\xml-data\build-dir\KIRA-KATM-JOB1\test-automation\src\main\cypress\e2e\test\ **\*
build 06-Jul-2022 13:00:08 [INFO] npm ERROR! code ELIFECYCLO
build 06-Jul-2022 13:00:08 [INFO] npm ERROR! mistake 1
build 06-Jul-2022 13:00:08 [INFO] npm ERROR! test kira_end_to_end_test@1.0.0: `cypress run --headless --spec cypress/e2e/test/**/*`
build 06-Jul-2022 13:00:08 [INFO] npm ERROR! Exit state 1
build 06-Jul-2022 13:00:08 [INFO] npm ERROR!
build 06-Jul-2022 13:00:08 [INFO] npm ERROR! Error in test script kira_end_to_end_test@1.0.0.
build 06-Jul-2022 13:00:08 [INFO] npm ERROR! This is probably not a problem with npm. There is likely an additional log output above.
compilation 06-Jul-2022 13:00:08 [INFO]
build 06-Jul-2022 13:00:08 [INFO] npm ERROR! A full log of this run can be found at:
build 06-Jul-2022 13:00:08 [INFO] npm ERROR! C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\_logs\2022-07-06T11_00_08_673Z-debug.log
compilation 06-Jul-2022 13:00:08 [INFO] ------------------------------------ ------------------------------------
build 06-Jul-2022 13:00:08 [INFO] BUILD ERROR
compilation 06-Jul-2022 13:00:08 [INFO] ------------------------------------ ------------------------------------
compilation 06-Jul-2022 13:00:08 [INFO] Total time: 01:57 min
compilation 06-Jul-2022 13:00:08 [INFO] Finished on: 2022-07-06T13:00:08+02:00
compilation 06-Jul-2022 13:00:08 [INFO] ------------------------------------ ------------------------------------
build 06-Jul-2022 13:00:08 [ERROR] Failed to run target com.github.eirslett:frontend-maven-plugin:1.12.0:npm (npm cypress run) in project test automation: Failed to run task : 'npm run test' failed. org.apache.commons.exec.ExecuteException: Process terminated with error: 1 (Exit Value: 1) -> [Help 1]
build 06-Jul-2022 13:00:08 [ERROR]
build 06-Jul-2022 13:00:08 [ERROR] To see the full stack trace of errors, run Maven again with the -e switch.
build 06-Jul-2022 13:00:08 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
build 06-Jul-2022 13:00:08 [ERROR]
build 06-Jul-2022 13:00:08 [BUG] For more information about the bugs and possible solutions, please read the following articles:
build 06-Jul-2022 13:00:08 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
simple 06-Jul-2022 13:00:08 Task failed from return code of [E:\appl\apache-maven-3.5.4\bin\mvn.cmd --batch-mode -Djava.io.tmpdir= C:\WINDOWS\system32\config\systemprofile\AppData\Local\Temp\KIRA-KATM-JOB1 clean install -gs maven

**Comment by lalitkushwaha1410** [comment]
Me also getting the same issue on teamcity server as mentioned by https://github.com/cypress-io/cypress/issues/20734#issuecomment-1176121653

**Comment by michaelpward** [comment]
Same issue here.

I have 27 spec files all in the same directory (`/cypress/e2e`). The 2 newest spec files were added today. Cypress does not "see" them whether I attempt to run all of specs or if I attempt to run either of the 2 newly created specs - but it "sees" all 25 of the specs created in the past.

Permissions on all files is the same.

My 2 new specs do not appear in the list of specs when I run `yarn cypress:open`.
My 2 new specs are not run when I use `yarn cypress:run`.

Confused thus far... 😕

**Comment by michaelpward** [comment]
Following up to my prior comment:

I've just updated my config such that I have added 

```
e2e {
    specPattern: 'cypress/e2e/*.cy.js',
}
```
...and the issue persists. When I run `yarn cypress:open` only 25 of the 27 spec files appear in the list, and the 2 missing specs are the ones I created today.

**Comment by lalitkushwaha1410** [comment]
Hi @michaelpward , May I know which cypress version you are using ??
 Please try with latest cypress version - 10.8.0 or 10.7.0 . 
![image](https://user-images.githubusercontent.com/45065608/190328841-129826fd-0aa6-44c9-8f86-4d4ac65d942f.png)

I also faced this issue a couple of days ago .At that time I was using cypress - 10.4.0 . It got resolved when I  upgraded the cypress version to latest .
Let me know if this solution resolves your issue .

**Comment by michaelpward** [comment]
I upgraded from 10.7 to 10.8 today.

**Comment by rahul-adpushup** [comment]
> I upgraded from 10.7 to 10.8 today.

Is this working for you?

**Comment by lalitkushwaha1410** [comment]
@michaelpward  
are you able to see all the 27 specs in the cypress test runner ?
also try with command "npx cypress run" .

**Comment by michaelpward** [comment]
No, only 25 show up in the test runner. 

I'll try npx.

**Comment by lalitkushwaha1410** [comment]
> No, only 25 show up in the test runner.
> 
> I'll try npx.

Please try with below spec pattern and also check the project settings in the cypress test runner .
![image](https://user-images.githubusercontent.com/45065608/190380327-84ea91f4-5ca8-4b84-82af-16ad639ad05e.png)

**Comment by lalitkushwaha1410** [comment]
> No, only 25 show up in the test runner.
> 
> I'll try npx.

Try with putting this specPattern and also verify the same in the project settings in cypress test runner. 
![image](https://user-images.githubusercontent.com/45065608/190381319-33928d69-b955-483d-a5dd-27f009df9ae1.png)

**Comment by michaelpward** [comment]
`<humbling>`
Thank you for your help. I found the problem. The 2 spec files that were not being "seen" were both missing `.cy.` in their names.

For example, I changed `account-profile.js` to `account-profile.cy.js` and now the spec is seen.
`</humbling>`

**Comment by UmamaheshMaxwell** [comment]
if somebody is wondering about why no tests showing up in dashboard when you have files with test.js extension and not test.cy.js extension, this is what you need to add in cypress.config.json file 

specPattern: ```cypress/e2e/**/*.{js,jsx,ts,tsx}```

**Comment by jquintozamora** [comment]
I managed to resolve this issue by specifying both: `specPattern` + `spec`. Being `specPattern` more general and `spec` more specific.

`cypress run --e2e --config baseUrl='http://localhost:3000',specPattern='cypress/integration/**/**.cy.ts' --browser electron --headless --spec=cypress/integration/group1/**.cy.ts`

Hope it helps others.

**Comment by amrsa1** [comment]
im facing the same issue, all paths are correct
![Screenshot 2022-12-23 at 17 48 06](https://user-images.githubusercontent.com/32042806/209372019-a2039e06-ad57-4a3c-be84-245c90ffaa5f.png)


![Screenshot 2022-12-23 at 17 49 58](https://user-images.githubusercontent.com/32042806/209372347-5b5aa543-7850-452c-a05c-1c918a2a3826.png)


```
await cypress.run({
      specPattern: `./cypress/integration/**/**.spec.js`,
      spec: `./cypress/integration/**/${name}`,
})
```

**Comment by vvega** [comment]
I spent an embarrassing amount of time swirling around on this, but in my case it looks like the `specPattern` config value did not like leading `./`, so I changed my spec pattern from:

`specPattern: './**/*.cy.(ts|tsx)'`

to 

`specPattern: '**/*.cy.(ts|tsx)'`

Maybe it will help someone having the same issue.

**Comment by TheDeadWeatcher** [comment]
In my case this video help me :) 

https://docs.cypress.io/guides/references/migration-guide

before cypress v10  - "spec": "npx cypress run --spec 'cypress/e2e/homePage.js"  // npm run spec 
after cypress v10 -"spec": "npx cypress run --e2e 'cypress/e2e/homePage.cy.js" // npm run spec 

take care !

**Comment by TheDeadWeatcher** [comment]
![screen VC studio](https://user-images.githubusercontent.com/121101613/221036842-960612ac-1f79-42a6-90fa-8045e3f6ecb3.png)

**Comment by arndbeissner** [comment]
> I spent an embarrassing amount of time swirling around on this, but in my case it looks like the `specPattern` config value did not like leading `./`, so I changed my spec pattern from:
> 
> `specPattern: './**/*.cy.(ts|tsx)'`
> 
> to
> 
> `specPattern: '**/*.cy.(ts|tsx)'`
> 
> Maybe it will help someone having the same issue.

It did, so thanks! In our project it turns out that './cypress/..whatever' in the specPattern isn't the same as 'cypress/..whatever' - on Windows. In the debug log it will evaluate to the correct Windows path but the spec files will not be found. Without the ./ prefix they are found. On MacOS, both versions work (cypress 12.6.0 both cases)

**Comment by yassarikhan786** [comment]
Not sure if this will help anyone, but I'm using `v12.3.0` of cypress on a react app and my folder structure is as follows:

"cypress/component/**/*.cy.tsx"

Where ** is the component folder and I have each component I'm testing in its own folder. 

Running

```
npx cypress run --component
```

runs the tests in `headless` mode in the terminal. I'm using VS Code.

I should add that this command also works flawlessly in an Azure DevOps pipeline.

**Comment by farvour** [comment]
> I managed to resolve this issue by specifying both: `specPattern` + `spec`. Being `specPattern` more general and `spec` more specific.
> 
> `cypress run --e2e --config baseUrl='http://localhost:3000',specPattern='cypress/integration/**/**.cy.ts' --browser electron --headless --spec=cypress/integration/group1/**.cy.ts`
> 
> Hope it helps others.

This seemed to be my problem as well. We define a `cypress.config.ts` file in our repository in the working directory and set `specPattern` in the `e2e` section. However, when trying to use a different directory match on the `spec` flag, it doesn't work. I had to override the config via the GitHub Action:

Example of the config file snip that was in the repository:

```
import { defineConfig } from 'cypress';

export default defineConfig({
  e2e: {
    baseUrl: 'http://localhost:3000',
    specPattern: 'cypress/e2e/**/*.cy.{ts,tsx}',
  },
});
```

```
# Override the specs to test.
config: specPattern=cypress/e2e_v2/pipelines.cy.ts
```

**Comment by darlenya** [comment]
I have tried all of the above , but it does not work for me.
Maybe my case is soemthing special. The tests are in a required module.

I got the following error message:
Can't run because no spec files were found.
We searched for specs matching this glob pattern:
/Users/userName/Documents/.../my-current-module/node_modules/@myOrg/some-other-module/dist/src/run.cy.js

The file exists. When I copy the strig and do an ls -la on it, it shows me the expected file.


I am using cypress version 12.17.4

in the cypress.config I have added the specPattern under the e2e section:
specPattern: "node_modules/@myOrg/some-other-module/dist/src/**/*.cy.{js,jsx,ts,tsx}"



I am starting the test with an API call like:

cypress
      .run({
        spec: specFile,
        headed: false,
        env: {
          some variables
        },
        e2e: {
          baseUrl: myBaseUrl,
          specPattern: "node_modules/@myOrg/some-other-module/dist/src/**/*.cy.{js,jsx,ts,tsx}"
          ...
    }
      })

where 'specFile' is pointing to the file with a full path as shown above.
In the run call I have addded the spec pattern also.

Yes this looks a little bit wiered but in my case it is right. This is exected as a service 
wich gets the tests commands as a json file. And the test is generic and executes these json files.

**Comment by tomdglenn91** [comment]
Suffering the same problem. Absolutely nothing out of the ordinary in my config:

```
component: {
    devServer: {
      bundler: 'webpack',
      framework: 'react',
    },
  },
```

Results in:

```
Can't run because no spec files were found.

We searched for specs matching this glob pattern:

  > /Users/<user>/code/projects/<monorepo>/apps/<app-name>/e2e/**/*.cy.jsx
```
The file is right here.
![Screenshot 2023-09-28 at 17 12 20](https://github.com/cypress-io/cypress/assets/31797732/cd75cb4f-9532-4b50-9fe4-aff92b2cf6e5)

Granted my project is both in a nested folder (e2e/cypress, rather than cypress), and this is also part of an nx monorepo, which may be messing with some things, but clearly its SEARCHING in the right place. Do the files have to be served inside the dev server?

**Comment by jennifer-shehane** [comment]
Closing as the original issue has been addressed by updating the filenames so that they are included in the specPattern glob that it is marching against. 

There are some good tips in the comments here that we suggest users try.

**Comment by murraydailymaverick** [comment]
haha - I had a 'excludeSpecPattern' which was doing what it should in config. removed and all works - hope this helps someone :-)
