### ISSUE TITLE
"cypress install" stuck in a never ending loop and could not install cypress | Cypress package version: 9.5.2 Cypress binary version: not installed

### ISSUE THREAD

**Issue by shagupta92042** [cypress-io/cypress#20736]
### Current behavior

I was getting below error while installing cypress 

**Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration**

So I did setup http proxy using set HTTP_PROXY=http://my-company-proxy.com and ran below steps

**1.**
**C:\Users\shashank.gupta>npm install cypress --save-dev**

added 165 packages, and audited 166 packages in 27s

27 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**2.**
**C:\Users\shashank.gupta>npx cypress -v**
Cypress package version: 9.5.2
Cypress binary version: not installed
Electron version: not found
Bundled Node version: not found

**3.
C:\Users\shashank.gupta>npx cypress run**
No version of Cypress is installed in: C:\Users\shashank.gupta\AppData\Local\Cypress\Cache\9.5.2\Cypress

Please reinstall Cypress by running: cypress install

----------

Cypress executable not found at: C:\Users\shashank.gupta\AppData\Local\Cypress\Cache\9.5.2\Cypress\Cypress.exe

----------

Platform: win32-x64 (10.0.19042)
Cypress Version: 9.5.2

Now the below step stuck for hours and it is not able to install the cypress on my system.

**4.
C:\Users\shashank.gupta>npx cypress install**
Installing Cypress (version: 9.5.2)

**5.
C:\Users\shashank.gupta>npm list cypress**
shashank.gupta@ C:\Users\shashank.gupta
`-- cypress@9.5.2

### Test code to reproduce

NA

### Cypress Version

9.5.2

**Comment by AurelienKun** [comment]
I have actually an issue with npm to install cypress with npm (`npm install --save-dev cypress@9.5.2`). The process stop while downloading the archive (in my case it's always at 37% for the 9.5.2). I checked with my admin network and it does not seem to be related to our network. 
If i download with the browser same thing : the download is stopped before the whole archive is downloaded.
Something might be wrong on Cypress' backend eventually ?

**Comment by jottes** [comment]
I also have this problem when i try to run npm install. And exactly the same problem as @AurelienKun wrote when i try to download cypress via browser. The download stucks.

**Comment by ToddRB** [comment]
I have the exact same issue @AurelienKun 
My downloads keep stopping at 37% on my CI agents.  Are my agents being throttled somehow? 
I am able to download successfully on other machines. 

Even if  try to download the zip via the browser.
https://cdn.cypress.io/desktop/9.5.1/win32-x64/cypress.zip
![image](https://user-images.githubusercontent.com/5262597/163042755-78c6bb7d-31fa-4a51-81d0-cbd2fc870094.png)

**Comment by domenHren27** [comment]
This happens because for some reason Cypress installation doesn't get through as it should. 

I was able to solve this issue by downloading  https://download.cypress.io/desktop/{cypress version} and after that extracting the content of Cypress zip to the
C:\Users\{user}\AppData\Local\Cypress\Cache\{cypress version}.  _If the folder does not exist just create it._

Be careful that the cypress version matches the cypress version that you installed via npm. 

After that, I was able to run cypress without any problems.

**Comment by galfimihaly** [comment]
> This happens because for some reason Cypress installation doesn't get through as it should.
> 
> I was able to solve this issue by downloading [https://download.cypress.io/desktop/{cypress](https://download.cypress.io/desktop/%7Bcypress) version} and after that extracting the content of Cypress zip to the C:\Users{user}\AppData\Local\Cypress\Cache{cypress version}. _If the folder does not exist just create it._
> 
> Be careful that the cypress version matches the cypress version that you installed via npm.
> 
> After that, I was able to run cypress without any problems.

It's ok, but this is a workaround.
I would like to know why not run postinstall automatically after npm installation (`npm install --save-dev cypress`), which downloads and installs the binary.
Also, what happens when I start the binary installation with `npx cypress install` and I only get the information on terminal that the installation is in progress:

> Installing Cypress (version: 12.7.0)

and the process gets stuck, no more message on terminal:

> Downloading Cypress
> Unzipping Cypress
> Finishing Installation

So I want to see what happens, e. g. try to download binary zip from url or any other steps, because I don't know what is the problem and I don't resolve it.

**Comment by PRAVEENKUMAR782** [comment]
any one found any solution to above  issues ,@cypress team ?

**Comment by MikeMcC399** [comment]
@PRAVEENKUMAR782 

> any one found any solution to above issues ,@cypress team ?

In many cases similar installation issues are caused by network issues. You may be able to get more information if you use some debugging commands:

```bash
npm install cypress@latest --save-dev --ignore-scripts
npx cypress cache clear
export DEBUG=cypress:*
npx cypress install
```

Unless you are using Cypress 9.5.2, as the original issue described, you may want to open a new installation issue if you continue to have a problem and need assistance.

You can also tap into the Cypress community know-how via [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)
(click on button).

**Comment by RobertDiebels** [comment]
I ran into this myself today/yesterday and after I debugged the issue I found the cause in my particular case. Here's my contextual information and the cause.

*Versions*
Cypress: 12.5.1
NodeJS: 16.15.1
Platform: Windows 10

*Context*
Our client runs in an airgapped setup, with an internal CA and a Proxy.
In our .npmrc we'd added:

```
registry= example.com
cypress_install_binary=example.com/version/cypress.zip
strict_ssl=true
cafile=example.com/ca.cert
http_proxy=proxy.example.com:8080
https_proxy=proxy.example.com:8080
```
*Cause*

The cause of the issue was due to both `HTTP_PROXY ` and `HTTPS_PROXY` pointing to the same proxy address.
As a result the `tunnel-agent` package errs, this bubbles through `@cypress/request` up to `cli/lib/tasks/download.js`  https://github.com/cypress-io/cypress/blob/50933faac48820d9e35dce1bb217d757f484deaf/cli/lib/tasks/download.js#L303.
However, tunnel-agent tags the error with a 'ECONNRESET' code causing cypress to ignore the error completely and just hang forever.

The full error was as follows: 
`Error: write EPROTO 8768:error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

However, I can imagine that other people are running into similar issues due to ECONNRESET errors being filtered out and ignored. Personally I don't quite understand why this error is being filtered to begin with, since it causes the application to hang without providing any feedback.

Hence I would suggest that this particular filter gets removed or a library is introduced that tags this particular error with the proper code ( EPROTO ).

EDIT: Forgot to tag: @PRAVEENKUMAR782 @MikeMcC399
