### ISSUE TITLE
Hover over Command Log  and switching back breaks App UI layout

### ISSUE THREAD

**Issue by romankhomitskyi** [cypress-io/cypress#20840]
### Current behavior

When I Hover over command log to debug my app, and then move my mouse back to App view port, App UI layout is broken

https://user-images.githubusercontent.com/57874507/160780170-f8f1354b-9447-4e42-95f6-cb238a080e3a.mp4

### Desired behavior

App UI  layout should not break and displays as it is

### Test code to reproduce

none

### Cypress Version

9.5.0

**Comment by romankhomitskyi** [comment]
> @romankhomitskyi can you provide a reproducible example? This indeed appears to be odd behavior but we cannot look into it without more information. Can you share the test used and the command hovered as well as styles your application is using that is then breaking?

@emilyrohrbough I spotted that style Grid is removed from an element
I will try find an example

**Comment by nemonemi** [comment]
I started experiencing this as well, a couple of weeks ago.
Basically, as soon as I hover in the sidebar over the executed steps, to debug the problem, the UI of the application gets messed up, and I have also noticed that it is because the styles get messed up.

Here you can see the comparison of the healthy and unhealthy container styles:
![image](https://user-images.githubusercontent.com/77624664/162764376-ba63b8a6-ffc9-4c32-92de-a9cd2c5c9da1.png)
![image](https://user-images.githubusercontent.com/77624664/162764474-cc3e4e13-d654-4922-b24e-54c2c002e1b0.png)

And here you can see the difference in rendered style for healthy and unhealthy child elements:
![image](https://user-images.githubusercontent.com/77624664/162764574-c0d04647-64e2-480b-a779-2042cdce5fd5.png)
![image](https://user-images.githubusercontent.com/77624664/162764613-d03f8827-c69e-41cf-b86f-d035552af514.png)

**Comment by nemonemi** [comment]
It would be great if this could be moved forward. It is impeding our progress in debugging failing tests.

**Comment by max-nextcloud** [comment]
I'm seeing something similar but for me it looks more like the styles would not be applied at all.

- Browser: Chromium
- Testing: [nextcloud text](https://github.com/nextcloud/text) current master - but happens for a while.
- Cypress current (11.2.0) but also happens for a while.
- Also happens with other nextcloud apps.


**Screenshots**

<details>
<summary>
After the test test everything is still good:
</summary>

![Bildschirmfoto vom 2022-11-29 12-14-31](https://user-images.githubusercontent.com/97337118/204515043-79272ffb-623c-4fc3-8601-53f6633bb189.png)

</details>

<details>
<summary>
Hovering over the test step:
</summary>

![Bildschirmfoto vom 2022-11-29 12-14-47](https://user-images.githubusercontent.com/97337118/204515046-96f0b219-0221-4a01-898d-fff89ea3f228.png)

</details>

<details>
<summary>
After hovering even the current state is broken:
</summary>

![Bildschirmfoto vom 2022-11-29 12-14-54](https://user-images.githubusercontent.com/97337118/204515050-9d596083-d625-498a-9a21-4836aace73e4.png)

</details>

also reported to text here: https://github.com/nextcloud/text/issues/3499

**Comment by max-nextcloud** [comment]
I thought i was seeing the same issue but actually we're affected by https://github.com/cypress-io/cypress/issues/16066.

However that issue also has a bunch of info around the grid problem.
Turns out that that's an issue in Chromium that should have been fixed wihttps://bugs.chromium.org/p/chromium/issues/detail?id=1303968 which should be fixed in chromium101.th the release of chrome 101:
https://bugs.chromium.org/p/chromium/issues/detail?id=1303968 .
