### ISSUE TITLE
Could not login to a web application(with open auth 2.0)

### ISSUE THREAD

**Issue by kutlaykural** [cypress-io/cypress#2085]
### Current behavior:
To login with google open auth i tried this:

```js
 cy.request({
        method: 'POST',
        url: login_url,
        json: true,
        body : {
          password: _password,
          username:_username,
        }
      }).then((resp) => {
        cy.visit(profile_url);
      })
```
After request, response returns with status code 200 and response body like this:

<img width="586" alt="screen shot 2018-07-02 at 17 59 01" src="https://user-images.githubusercontent.com/38225108/42171430-ee74a658-7e21-11e8-8a98-d526c309bb2b.png">
 
But  the code cy.visit(profile_url) returns back to login page like not authenticated. 
Should i save access code to anywhere? Or what i miss?

### Desired behavior:

 the code cy.visit(profile_url) opens to profile page properly

### Versions

Mac, electron 59

**Comment by brian-mann** [comment]
This is completely specific to your application works. You just do the thing that you application would have otherwise done had it gone through the google oauth API.

For instance, does it get set as a cookie? If so, set it as a cookie. Does it get set to local storage? If so set it to local storage.

Maybe that access token actually makes its way back to your server and then your server sends you a cookie. If so, just make a new cy.request() to your server with that value. 

Essentially you just need to complete the loop / contract between your app and google. There's nothing else I can tell you, you have all the tools within Cypress to do it.

If you're still unsure - just login with your regular browser and make sure that you preserve all the network requests. You could then see exactly what gets passed and what you're missing. You've already done the hard part though, so you're almost there.

You can check out some of our recipes here which utilize some of the same methods:

- https://docs.cypress.io/examples/examples/recipes.html (The logging in recipes)
- https://docs.cypress.io/guides/references/best-practices.html#Organizing-Tests-Logging-In-Controlling-State (watch this video)

**Comment by kutlaykural** [comment]
Thank you for detailed explanation and quick answer @brian-mann 
Now i am trying to set cookie but it gives an error like this:

<img width="280" alt="screen shot 2018-07-03 at 00 26 18" src="https://user-images.githubusercontent.com/38225108/42187177-d041e200-7e57-11e8-91e8-37a3818a9801.png">

Here is my code:
```js
cy.visit(profile_url, {
          onBeforeLoad: (contentWindow) => {
            cy.setCookie('OauthAccessToken',resp.body.payload.data.access_token)
          }
        })
```

Thanks,

**Comment by brian-mann** [comment]
You can't set a cookie in an `onBeforeLoad` header because its async.

Just set the cookie ahead of time before you call `cy.visit()`

**Comment by kutlaykural** [comment]
I tried the code below, i see it set cookie successfully but then it crash suddenly.
```js
cy.clearCookie('OauthAccessToken')
cy.setCookie('OauthAccessToken',resp.body.payload.data.access_token)
cy.wait(10000)
cy.visit(profile_url)
```

<img width="595" alt="screen shot 2018-07-03 at 08 23 50" src="https://user-images.githubusercontent.com/38225108/42200096-7adbf100-7e9a-11e8-8c3f-0f76f4c6ad73.png">

Cypress existed without giving any error. And i see error log on terminal

<img width="517" alt="screen shot 2018-07-03 at 08 26 35" src="https://user-images.githubusercontent.com/38225108/42200236-f12c9ee0-7e9a-11e8-877c-9e7fc42996f8.png">

**Comment by kutlaykural** [comment]
And also at first login attempt google oauth receive all request to same login page. Which includes 2 steps login process. The first one is validating entered e-mail. And second one is verifying e-mail and password matches. 
At the google oauth API's there is no way explained skipping this page with a HTTP request or any other way. 
Is there any solution about it? Can you share a specific example?

Thank you for all your interest,

**Comment by kutlaykural** [comment]
@brian-mann
What do you think about using puppeteer to automate
https://github.com/google/google-auth-library-nodejs/blob/master/examples/puppeteer/oauth2-test.js
