### ISSUE TITLE
Google Maps/Mapbox added layers is not clickable

### ISSUE THREAD

**Issue by BenK93** [cypress-io/cypress#20865]
#### Expected Behavior:  
Being able to click in the middle of the screen and trigger the `mouseclick`  
#### Actual Behavior:  
Cypress is clicking on the middle of the screen **BUT** not on my added entities(circles/rectangles), it seems like my entities are not even there when Cypress is clicking, but on the other hand you can see them when running the test with `npx cypress open` (will attach images for more details)

- Cypress: ^9.5.0
- @angular/google-maps: ^13.3.0

On the UI 2 things are happening:  
1. Adding my own elements to the google maps
2. Adding to those elements eventListener `click`.  
**Manually everything behaves perfectly fine!**

[![enter image description here][1]][1]
#### Angular code adding my entities + click eventListener:

    addDataLayer(dataLayer: google.maps.Data): void {
        dataLayer.addGeoJson(this.entitiesService.entities) // works perfectly fine
    });

    addDataLayerListeners(dataLayer: google.maps.Data): void {
        dataLayer.addListener('click', (event) => {
           my-function() // is working fine when i click on the UI manually
        })
    });

### The steps of my test (examples)

    it('my clicking tests example 1' , () => {
        cy.createMyEntity()✅
        cy.get('body').click(400,400,{force:true})❌
     })
     it('my clicking tests example 2' , () => {
        cy.createMyEntity()✅
        cy.get('canvas').first()
         .trigger('pointerdown', {force: true, which: 1, button: 0, bubbles: false})
         .trigger('pointerup',{force: true,which: 1, button: 0, bubbles: false})❌
     })
     it('my clicking tests example 3' , () => {
        cy.createMyEntity()✅
        cy.get('canvas').first()
         .trigger('pointerdown', {force: true, which: 1, button: 0})
         .trigger('pointerup',{force: true,which: 1, button: 0})❌
     })
     it('my clicking tests example 4' , () => {
        cy.createMyEntity()✅
        cy.get('canvas').first()
         .trigger('mouseover', {force: true, which: 1, button: 0})
         .trigger('mousedown', {force: true, which: 1, button: 0})
         .trigger('mouseup',{force: true,which: 1, button: 0})❌
     })
## Examle of Cypress running
[![enter image description here][2]][2]
## And when I pin one of the test lines this is happenning
like there is no entity on the map 🙇🏽‍♂️
[![enter image description here][3]][3]

## How google render my entities inside the DOM:
[![enter image description here][4]][4]

#### Questions
 1. is there a way to make it behave as it does manually?
 2. Am I doing anything wrong?

  [1]: https://i.stack.imgur.com/IP9Fp.png
  [2]: https://i.stack.imgur.com/XL3Sa.jpg
  [3]: https://i.stack.imgur.com/ood4E.jpg
  [4]: https://i.stack.imgur.com/2Jz46.png

### There are 2 types of maps I use in my project:
- Mapbox
- Google-maps

Both are canvas elements rendered to the DOM, and I'm adding extra layers to those maps.  
But when I click them with Cypress it is like those layers are never been there in the first place 🥴

It will be really helpful first to understand the difference between a manual click `VS` Cypress click.  
Second, a functionality that will make the Canvas element click behave as it should manually

**Comment by marktnoonan** [comment]
Hi @BenK93, thanks for this detailed report. I'm still a bit confused though - the examples of failing tests in your screenshot don't match the ❌s in your test code that you shared, so it's not totally clear.

In a general sense, clicking on canvas elements in Cypress works. There could be a few things at play and I have some questions to figure out whether you've hit a Cypress bug or a "maps are a pain to test" situation (which I have sympathy for).

The main question is, are you describing the following expected behavior on the app:

1. Click the middle of the map
2. This causes an entity to appear
3. Now click on the newly-added `[data-cy="entity-index"]`

And in real life that works but Cypress fails on the `cy.get('[data-cy="entity-index"]')`? Which might indicate the initial click on the map didn't trigger the entity correctly, except it did because you see it in open mode, you just can't interact with the new entity?

That's at least what the screenshots seem to suggest - the pointer events stuff on the ` cy.get('canvas').first()` looks like it is passing and we fail on the `get`. 

So I would be wondering - is the first canvas of (the 9 canvas elements matched) definitely the right thing to click? Is it it being clicked at the right time? I see you have some big waits in there which I guess are an attempt to let things settle before the click. Does that canvas definitely have the data-cy attribute you are looking for?

The best thing would be a reproduction where we can see this kind of test not working and actually debug it.  You might be able to create this reproduction.

Our click event is fired using [`dispatchEvent`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) and you can check out the code here: https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/actions/click.ts and https://github.com/cypress-io/cypress/blob/marktnoonan/axe/packages/driver/src/cy/mouse.ts (though, those are relatively complex to read through since mouse events come in many varieties.

**Comment by AtofStryker** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
