### ISSUE TITLE
On Cypress crash, prompt users to run with debug logs

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#2087]
If Cypress crashes, and no debug logs are set, prompt users to run with debug logs and open an issue

**Comment by nhc** [comment]
How would I get cypress to crash to test this? Can you give any direction I would be willing to help.

**Comment by kblcuk** [comment]
@nhc I guess one example would be wepback build crashing. This was very frustrating experience, but in the end I found out that providing `cypress:webpack` flag to cypress makes it to print webpack debug logs (and then fixing broken file is a matter of seconds).

Perhaps we could add that to [error message that shows when webpack build fails](
https://github.com/cypress-io/cypress/blob/55b352a11d0a664517ae054c67432d98abc2389e/packages/runner/src/errors/error-messages.js)? I'm not entirely sure if that's the right place, since the actual debug logging happens on https://github.com/cypress-io/cypress-webpack-preprocessor, might there be some other places where this error is published?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
