### ISSUE TITLE
If any test case fails, cypress automatically stops test execution in headless mode, not completing remain test execution

### ISSUE THREAD

**Issue by KrupalVaghasiya** [cypress-io/cypress#20955]
### Current behavior

When I run the `npm run cy:run` command, If any test case fails, cypress automatically stops test execution in headless mode, not completing remain test execution.

### Desired behavior

It should finish all tests when I run the cypress test in headless mode.

### Test code to reproduce

1. Clone `https://github.com/KrupalVaghasiya/orderFlow.git`
2. Open the cloned folder in `vs code`
3. Run `npm install`
4. Run `npm run cy:run` command
5. wait for the failing test and once the test is failed it will stop execution.

### Cypress Version

9.5.0

### Other

I am facing this issue from the last one month. before I am using the old cypress version so I think it was fixed into the newer version. so I have updated my cypress but still facing this issue.

**Comment by davidmunechika** [comment]
<img width="1067" alt="Screenshot 2022-04-07 at 4 26 05 PM" src="https://user-images.githubusercontent.com/27690333/162745163-0f77df18-1f70-4cec-bb6a-ead0da5e42a6.png">

I am unable to recreate the issue you are describing. It appears the remaining test execution is completing after the failed test occurs. Maybe I am misunderstanding the issue, but is this not the expected behavior?

**Comment by KrupalVaghasiya** [comment]
@davidmunechika Now it's working fine but sometime it will stop test execution.

**Comment by davidmunechika** [comment]
Unfortunately we will have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment in this issue with steps to reproduce the issue and I'll be happy to reopen the issue. Thanks!

**Comment by KrupalVaghasiya** [comment]
@davidmunechika Please clone this repo and run test `npm run cy:run`. 5th test is failed and then it will stop execution and not generate reports.

**Comment by davidmunechika** [comment]
I have cloned the repo and run these tests multiple times and have not encountered this issue. The execution completes for all of the tests each time. Unfortunately, I don't have enough information to reproduce this issue at this time.

**Comment by T-e-j-k-u-m-a-r** [comment]
Hello, I'm facing this issue when executed cypress all spec files in jenkins. 
Issue is when there are 1 files(spec1.ts, spec2.ts & spec3.ts) inside a folder lets say: Login,
If the spec1.ts failed then it will not pick the very next test case. Instead it will go for next folder which is in my case HomePage. 

Why is that?

**Comment by tobiasgrossmann** [comment]
I would like to have the described behavior as feature: "If any test case fails, cypress automatically stops test execution in headless mode". 
Is there any parameter to configure the behavior?
