### ISSUE TITLE
Can't upgrade to v3.0.2: "Error: unable to verify the first certificate"

### ISSUE THREAD

**Issue by 4z5lz** [cypress-io/cypress#2097]
### Current behavior:

Can't upgrade to v3.0.2

### Desired behavior:

Want to upgrade to v3.0.2 :)

### Steps to reproduce:

`npm install --save-dev cypress@3.0.2`

Receive:
```
> node index.js --exec install

 ×  Downloading Cypress
   → Cypress Version: 3.0.2
    Unzipping Cypress
    Finishing Installation
The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/3.0.2?platform=win32&arch=x64
Error: unable to verify the first certificate
----------

Platform: win32 (6.1.7601)
Cypress Version: 3.0.2
- @types/minimatch@3.0.1 node_modules\cypress\node_modules\@types\minimatch
- assert-plus@0.2.0 node_modules\cypress\node_modules\assert-plus
- aws-sign2@0.6.0 node_modules\cypress\node_modules\aws-sign2
- cachedir@1.2.0 node_modules\cypress\node_modules\cachedir
- form-data@2.1.4 node_modules\cypress\node_modules\form-data
- har-schema@1.0.5 node_modules\cypress\node_modules\har-schema
- http-signature@1.1.1 node_modules\cypress\node_modules\http-signature
- json-stable-stringify@1.0.1 node_modules\cypress\node_modules\json-stable-stringify
- ajv@4.11.8 node_modules\cypress\node_modules\ajv
- har-validator@4.2.1 node_modules\cypress\node_modules\har-validator
- performance-now@0.2.0 node_modules\cypress\node_modules\performance-now
- hoek@2.16.3 node_modules\hoek
- boom@2.10.1 node_modules\boom
- cryptiles@2.0.5 node_modules\cryptiles
- sntp@1.0.9 node_modules\sntp
- hawk@3.1.3 node_modules\hawk
- stringstream@0.0.6 node_modules\stringstream
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'D:\git\project\node_modules\log-symbols\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\git\project\node_modules\listr\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'D:\git\project\node_modules\request\package.json'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "cypress@3.0.2"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! cypress@3.0.2 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@3.0.2 postinstall script 'node index.js --exec install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cypress package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js --exec install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cypress
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cypress
npm ERR! There is likely additional logging output above.
```

### Versions

Windows 7 64b
node: v6.9.0
npm: v3.10.8
current Cypress: v3.0.1

**Comment by brian-mann** [comment]
Are you behind any kind of proxy or firewall?

This is an SSL Cert error from node, but our certs are just fine and we've had a great many downloads today already ;-)

Maybe just try again? Or change your node version perhaps? Do you know of any kind of system settings that may muck with your network configuration? Have you had any issues downloading Cypress before?

**Comment by 4z5lz** [comment]
Yes, I'm behind the corporate firewall, but I not had any issue with installation of Cypress 3.0.1 before.

**Comment by cLupus** [comment]
I have the same error.
While I've tried setting `NODE_EXTRA_CA_CERTS` to the bundled corporate certificate bundle (which includes Mozilla's), and setting an alias for `node` to `node --use-openssl-ca`.
Neither of which worked out.

**Comment by brian-mann** [comment]
You likely just need to set `HTTP_PROXY=whatever npm install` or set it up in your `.npmrc` file.

Read this comment here for workarounds when installing Cypress: https://github.com/cypress-io/cypress/issues/1469

I looked at our documentation and expected this to be there but was surprised not to find it. You likely just need to set `HTTP_PROXY` or `HTTPS_PROXY` environment variables when doing the `npm install`.

**Comment by cLupus** [comment]
**PS**: For my part, `HTTP(S)?_PROXY` is set (exported).
I've managed to work around the issue on my work computer, however, such a workaround is not really an option in our CI/CD pipeline.
The said environment variable have also been set (globally) in our CI/CD pipeline, but we still get the certificate error.

**Comment by jennifer-shehane** [comment]
We made a lot of improvements to proxy support recently. Can you try updating to 3.3.1 and update this issue if it is fixed/not fixed please? Thanks.

**Comment by mafalarz** [comment]
Unfortunately still not working. 
 
```
×  Downloading Cypress
   → Cypress Version: 3.3.1
    Unzipping Cypress
    Finishing Installation
The Cypress App could not be downloaded.

Please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/3.3.1?platform=win32&arch=x64
Error: unable to verify the first certificate
```

**Comment by mafalarz** [comment]
I was able to resolve the situation by following the instructions on [Proxy Configuration](https://docs.cypress.io/guides/references/proxy-configuration.html#Set-a-proxy-on-Linux-or-macOS)

Specifically I had to set HTTP_PROXY=http://my-company-proxy.com before I did my npm install

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.

**Comment by visjag** [comment]
Hi,
I am getting following issue, while installing cypress 3.8.3

> cypress@3.8.3 postinstall C:\dev\cy_npm\node_modules\cypress
> node index.js --exec install

Installing Cypress (version: 3.8.3)

 ×  Downloading Cypress
   → Cypress Version: 3.8.3
    Unzipping Cypress
    Finishing Installation
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/3.8.3?platform=win32&arch=x64
Error: unable to verify the first certificate

----------

Platform: win32 (10.0.17763)
Cypress Version: 3.8.3
npm WARN rollback Rolling back chalk@1.1.3 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\dev\cy_npm\node_modules\listr-verbose-renderer\node_modules'
npm WARN enoent ENOENT: no such file or directory, open 'C:\dev\cy_npm\package.json'
npm WARN cy_npm No description
npm WARN cy_npm No repository field.
npm WARN cy_npm No README data
npm WARN cy_npm No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress@3.8.3 postinstall: `node index.js --exec install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cypress@3.8.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     2020-01-30T15_49_54_548Z-debug.log

I have already set my environment variale
ie HTTP_PROXY, HTTPS_PROXY and NO_PROXY

As well as I tried with http=<proxy> run cypress. but it didn't work

Please can you guide

**Comment by shankarnarayanb** [comment]
@visjag  try using 

`export NODE_TLS_REJECT_UNAUTHORIZED=0 
`
