### ISSUE TITLE
contenteditable="plaintext-only" not respected in Chrome

### ISSUE THREAD

**Issue by wobo-bledebur** [cypress-io/cypress#21005]
### Current behavior

Given this element:
```html
<div id="test" contenteditable="plaintext-only"></div>
```
And this action:
```js
cy.get('#test').type('FOO{enter}BAR')
```
The content of the element will be `FOO<div>BAR</div>`, which is the expected behavior when `contenteditable="true"` but not when `contenteditable="plaintext-only"`.

<img width="1440" alt="Screen Shot 2022-04-08 at 1 59 44 PM" src="https://user-images.githubusercontent.com/89813303/162498008-5890173a-d8f7-47aa-aca7-34db1ae02e70.png">

### Desired behavior

Given this action:
```js
cy.get('#test').type('FOO{enter}BAR')
```
`div#test` should have the following innerHTML content:
```
FOO
BAR
```

### Test code to reproduce

[Forked repo with failing test case](https://github.com/wobo-bledebur/cypress-test-tiny/commit/30ff7ca98e6ecc0f1c9de051de54265506f3a270).

Note that if you manually type "FOO", "\<Enter\>", "BAR" in the same Chrome window that the automated test had been running, you will get the expected behavior.

### Cypress Version

9.5.3

### Other

Technically, `content-editable="plaintext-only"` is considered experimental. But it is widely supported, is used by many existing libraries, and is often the only viable option for allowing multi-line plain text editing for cases when using a `<textarea>` is not viable due to design requirements. So I wanted to appeal to you to possibly add support. Thank you!

**Comment by davidmunechika** [comment]
Thanks for providing an example repo- I was able to recreate the issue as you described

<img width="434" alt="Screenshot 2022-04-11 at 9 20 16 AM" src="https://user-images.githubusercontent.com/27690333/162748170-3723c668-f2fe-4dcc-a925-bf297d753cb7.png">

**Comment by marktnoonan** [comment]
Just a quick note, @viniciuspietscher and I happened to take a look at this last night and we think we see what's up.

The cause is likely this [line](https://github.com/cypress-io/cypress/blob/af472b6419ecb2aec1abdb09df99b2fa5f56e033/packages/driver/src/dom/selection.ts#L86): 

```js
$elements.callNativeMethod(doc, 'execCommand', 'insertText', nativeUI, text)
```

This is how characters are added into a `contenteditable` element through `cy.type()`, but the way `execCommand` handles this seems to be to briefly turn on `document.designMode`, which makes _everything_ act like regular `contenteditable` and presumably that overrides the intended behavior of the experimental `plaintext-only` value. 

I don't have a particular way forward to suggest, but wanted to share what we learned looking through the code so it can help the next person, or possibly this will help you create your own workaround for the time being.
