### ISSUE TITLE
Can't install Cypress

### ISSUE THREAD

**Issue by dteneva** [cypress-io/cypress#21013]
### Current behavior

E:\CODING\CypressAutomation>npm install cypress --save-dev

up to date, audited 165 packages in 1s

27 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

E:\CODING\CypressAutomation>

After that, I am trying with:

E:\CODING\CypressAutomation>cypress run
and I get an error message: The code execution can not proceed because ffmpeg.dll was not found. Reinstalling the programm may fix this problem.

So, every time when i try to reinstall the program it is the same.,,

Before to do this so, I created a package.json and added to the variables on the windows following a tutorial.
No I do not have a file called Cypress.json when I open a Visual Studion Code.

### Cypress Version

9

### Package Manager

npm

### Operating system

Windows

**Comment by geromegrignon** [comment]
Hi,

By googling the error, it sounds directly related to Windows itself (and not Cypress):
There are some blog posts provided in [top search results](https://www.google.com/search?q=The+code+execution+can+not+proceed+because+ffmpeg.dll+was+not+found.&rlz=1C5CHFA_enFR908FR908&sxsrf=APq-WBs0jKGUHc4GSUts7yGUXC2pvfXKBg:1649627507832&source=lnt&tbs=qdr:y&sa=X&ved=2ahUKEwjmvPasvYr3AhVsyoUKHSBeCOQQpwV6BAgBEB4&biw=1440&bih=764&dpr=2).

**Comment by davidmunechika** [comment]
Closing this issue because it appears to be a problem with Windows rather than Cypress. I will be happy to reopen it if you continue to experience Cypress-related problems with installation.

**Comment by Sanjusakithyan** [comment]
same issue happened with mine, could you please help

**Comment by geromegrignon** [comment]
Hi @Sanjusakithyan, please relate to previous link. That's purely a Windows issue, occuring with Cypress but nothing the library can help with.
