### ISSUE TITLE
Cypress is not redirecting to next page 

### ISSUE THREAD

**Issue by WKOW** [cypress-io/cypress#21102]
### Current behavior

No car page is displayed 
![image](https://user-images.githubusercontent.com/17624309/163583398-56067013-25f8-49a5-ac16-71b1d77a59f1.png)

GET /trade-in-vehicle 302 143.808 ms - 126

### Desired behavior

Display next trade in page 

![image](https://user-images.githubusercontent.com/17624309/163583533-32bebea9-bb5a-44ea-a0fe-5bdbc43659e6.png)

### Test code to reproduce

```js
describe('Sales App HappyPath', () => {
  it('Choose Audi A8', () => {
    cy.visit('https://qa.devstorefront.co.uk/start?vehicle_id=4')
  })
  it('Accept Cookies Policy', () => {
    cy.get('#impliedsubmit').click().debug()
     })
  it('Click Continue Button', () => {
    cy.get('.btn').scrollIntoView().should('be.visible').click().debug()
  })
})
```

### Cypress Version

9.5.3

### Other

All works as expected when I try to run it on browserstack locally or manually using chrome 
It fails only in cypress chrome

**Comment by davidmunechika** [comment]
Thanks for opening an issue! I notice when I navigate directly to the https://qa.devstorefront.co.uk/trade-in-vehicle page in a web browser, I am redirected to the /no-vehicle page. The /trade-in-vehicle page only shows up correctly if I go through the start page and click continue. 

This makes me think this behavior in your test is somewhat related to sessions/cookies state not being persisted between tests. Cypress automatically clears all cookies before each test to prevent state from building up. Since you have separated these commands into separate tests, the state is not being correctly persisted between tests which is why you are being redirected to the /no-vehicle page. When I moved these commands into the same test, I was correctly able to see the /trade-in-vehicle page.

<img width="1612" alt="Screenshot 2022-04-16 at 10 04 53 PM" src="https://user-images.githubusercontent.com/27690333/163697155-23fac9b3-466f-4ee6-b70a-61ba46abcdf1.png">

My suggestion would be to either combine these commands into a single test so that the state doesn't get reset between them or look into `Cypress.Cookies` here: https://docs.cypress.io/api/cypress-api/cookies#Syntax

In this particular situation, I think you might also be able to simply add your `cy.visit()` command to a beforeEach block so that it gets run before each test so the state is correct if you'd prefer to keep the tests separate, but seeing as each test is only a single command, I would recommend combining the commands into a single integration test. I hope this helps!
