### ISSUE TITLE
Window: popstate event

### ISSUE THREAD

**Issue by npsantini** [cypress-io/cypress#21128]
### What would you like?

It would be incredibly useful if there were [Window:popstate](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event) events available in Cypress.

### Why is this needed?

In my testing I need to know when the history/popstate has changed because when that event occurs new content is loaded and needs to be tested.

**Comment by davidmunechika** [comment]
Are you not able to use `cy.window()` in this instance? Since Cypress is just javascript - you should have native access to everything without needing to create special commands in order to interact with native JS API's.

For instance... if you wanted to invoke pushState...

```js
cy.window().then((win) => {
  win.history.pushState(...)
})

// or

cy.window().its('history').invoke('pushState', ...)
```

Maybe I am misunderstanding your use case, but feel free to look at this past issue for more information: https://github.com/cypress-io/cypress/issues/128
