### ISSUE TITLE
Cypress Open Crashing Chrome with "Aw Snap" after upgrade to Chrome 100

### ISSUE THREAD

**Issue by dwaynegreen** [cypress-io/cypress#21135]
### Current behavior

When running Cypress Open with multiple tests, Chrome 100 is more likely to crash with an "Aw, Snap" error message than previous versions of Chrome:
![image](https://user-images.githubusercontent.com/6467250/164047803-61bd9a6a-33ed-48ee-840a-c19206f8192f.png)

I was able to determine that Chrome 100 is more likely to crash by using a Chromium version from https://chromium.cypress.io/. I was then able to run the standard Cypress Tests examples with Chrome 99.0.4844.0 by specifying "npx cypress open --browser "pathToChromiumVersion\chrome.exe" 

Here is three screenshots from running cypress open showing memory footprint with Chrome 99 using the Cypress Examples:
![image](https://user-images.githubusercontent.com/6467250/164048827-48c0c078-78e0-4379-8073-efe464ce4930.png)
![image](https://user-images.githubusercontent.com/6467250/164048841-a127a368-6ece-4848-9d21-7ae2d59e44c0.png)
![image](https://user-images.githubusercontent.com/6467250/164048857-883b4a45-1d07-4c7d-a911-71d32863b8c6.png)

Here is three screenshots from running cypress open showing memory footprint with Chrome 100 using the Cypress Examples:
![image](https://user-images.githubusercontent.com/6467250/164048969-8b3f74b2-7f4a-46e6-bd66-46c4101c50f3.png)
![image](https://user-images.githubusercontent.com/6467250/164048986-2d41b889-b23b-458f-b818-57c53caa0368.png)
![image](https://user-images.githubusercontent.com/6467250/164049002-989ab2b1-dc2a-4e1e-b662-4cdbfa71c00b.png)

### Desired behavior

I believe that Cypress should be able to keep a similar memory footprint between Chrome 99 and Chrome 100 or provide a better way to garbage collect between tests.
I have looked at using numTestsKeptInMemory (https://docs.cypress.io/guides/references/configuration#Options) but we only have 14 tests in our build verification suite.

I would also like to have the numTestsKeptInMemory configurable to only keep tests that have failed in memory instead of the last X tests.

### Test code to reproduce

Using Cypress Version 9.5.4 (as well as other versions), Cypress Examples that are installed with cypress on npm install -D cypress

### Cypress Version

9.5.4

**Comment by rockhold** [comment]
@davidmunechika, did you have a chance to reproduce this against the 10.0-release branch? Just curious if it'll still be an issue before long.

**Comment by BlueWinds** [comment]
@rockhold - I've confirmed this for both 9.x and 10.x. Chrome/Chromium 100/101 with Cypress seems to use more memory than previous versions.

I did a bit of searching around Chromium bugs, and the best I've found is https://bugs.chromium.org/p/chromium/issues/detail?id=1309201#c9, which seems to indicate that the Chrome team is aware of some ongoing memory issues introduced around Chrome 100 and not yet resolved in 101; I don't know enough of the internals to make complete sense of this conversation.

With that said, I suspect that this in a Chromium regression, which Cypress will be powerless to resolve. :( Perhaps 102 or 103 will contain more solutions.

**Comment by BlueWinds** [comment]
The issue they mention related to `extensions::Event::DeepCopy` in particular seems like a likely culprit - Cypress is deeply bound up with browser events, and we create a ton of event for our internal use, far more than most "real sites" ever would. If there's a memory leak there, Cypress is perfectly positioned to pound it repeatedly.

**Comment by brian-mann** [comment]
If that's the case then maybe we shouldn't update the embedded Chromium in Electron to v100 yet...

@BlueWinds can you check our perf charts and see if there's anything egregious in there

**Comment by mjhenkes** [comment]
@brian-mann, we have already updated chromium in electron to v100 https://github.com/cypress-io/cypress/pull/21418

**Comment by extracker-ppetrov** [comment]
I can still reproduce this on Cypress 10.0.3. My "tests kept in memory" setting is set to 2. 
It crashes if I run more than 2 tests in a single run. 
If the test kept in memory is set to 0, it is all good.

**Comment by tbiethman** [comment]
@extracker-ppetrov as of Cypress 10.4.0, the Electron browser bundled with Cypress is using Chromium 102. I'm curious if you're still experiencing these crashes with that version (or with the latest stable Chrome version 104)?

**Comment by JessefSpecialisterren** [comment]
@tbiethman I'm not extracker-ppetrov, but our team has also been facing lots of Aw Snap crashes lately, and I've been investigating the issue. Some results running a specific memory-hungry test file with Cypress 10.4.0 on Windows 10:

**Chrome 104:** consistent Aw Snap during the third test. Memory usage of Chrome is around 3gb right before the crash, my system has >5gb of available RAM at that point. It is unclear why Chrome doesn't just use more RAM instead of crashing
**Electron 102:** completes the test file without issue. The interesting thing: memory usage is very similar to Chrome 104, but Electron seems to have no trouble using more than 3gb of RAM. I've seen Electron run without crashing with over 5gb of memory usage, while the largest footprint I've seen with Chrome 104 was 3.3gb (and then it crashed)
**Chromium 99:** completes the test file without issue. The memory footprint has some interesting properties: the usage right after garbage collection doesn't differ that much between the 3 browsers, but Chromium 99's peak memory usage is significantly lower. Chromium 99 stayed below 2.6gb of memory usage during the entire test file, whereas Electron 102 peaked above 4gb and Chrome 104 crashed at around 3gb

Note: I have also experimented with `--expose-gc` and found that periodic forced garbage collection would delay the crash with Chrome 104, but I still couldn't complete the entire test file. Once memory usage starts approaching 3gb, Chrome 104 gets very likely to crash on my system, garbage collection or no

Note 2: I wondered if Chromium 99 would crash when memory usage got around 3gb, so I ran the same test file twice without closing the browser between runs and saw a peak memory usage of just over 4gb without issues

**Comment by succinct** [comment]
@tbiethman I'm also experiencing crashes with Cypress 10.4.0 and Chrome 104.0.5112.79, although my error code is SIGTRAP rather than a memory error.

**Comment by hodbby** [comment]
I use Cypress 10.3.0
Chrome  v104
Electron v100
**Both browsers crash as mentioned above.**
Only 3 weels ago they were fine

Any idea?

**Comment by extracker-ppetrov** [comment]
@tbiethman I am still experiencing this. I am currently with Cypress 10.6.0 and Chrome 104.
At this point even if my "tests kept in memory" is set to 0, I am seeing the issue, when my tests fail and rerun multiple times. 
I would suggest you try with a test suite that has multiple test cases in it and make them all fail. 
Also something else I noticed is that regardless what I set for "retries", a failing test is always being retried 4 times.

**Comment by cliedeman** [comment]
I am also experience this issue. 

In my case this was on a working install that hasn't been touched in months

```
cypress/browsers:node12.8.1-chrome80-ff72
```

<img width="527" alt="image" src="https://user-images.githubusercontent.com/3578740/186227970-a9a6644b-4842-46dd-a710-48884b3df54f.png">

Is there any other external change this could be caused by?

**Comment by emreSmrt** [comment]
I am getting the same error very often and it is becoming unbearable 

cypress v10.6.0
chrome v104
electron v102

**Comment by tusharbmc** [comment]
Hi There, Any update on this issue? We are also facing the same issue for lengthy E2E tests which takes around 8-9 mins to execute. I am afraid if Cypress can withstand our complete suite of +1500 E2E tests which we are planning to migrate from Protractor.

Suggestions are welcomed, how to increase Chrome/Cypress memory so that it will not crash. Shall we go headless? will it fix the problem?

**Comment by ComeOnGroupAutomationTeam** [comment]
Same here, we put a lot of effort to migrate to Version 10, and now it seems like we'll put another effort to revert back to version 9.

**Comment by tusharbmc** [comment]
Hi @ComeOnGroupAutomationTeam , does that mean Cypress V9 doesn't have this problem even with lengthy tests of duration more than 10 mins?

**Comment by emilyrohrbough** [comment]
Chrome itself has had quite a few bugs logged around issues with crashing due to running out of memory, so some of the issue is out of Cypress' control. Please see #23391. It seems Chrome 106 should see improvements.

That being said, we understand your frustrations. I am going to do some profiling of Cypress and try to see what we can do on our side to reduce hitting this limit. 

**Our First steps:**
- I am aware of a memory leak introduced in 10.0 that I am actively working on fix. 
- I am going to look at destroying our source mapping instances when we tear down Cypress between new spec selections in open mode and in navigation events with `cy.visit()` to a new domain

**Feedback would be appreciated:** 
In addition to altering many tests are kept in memory with `numTestsKeptInMemory` (default is 50), we know the reporter does impacts the overall performance and large specs will have degraded performance as the run executes due to the number of elements rendered on the dom (). We should really virtualize the reporter, however in the short-term, can you try using `NO_COMMAND_LOG=1` (https://docs.cypress.io/guides/references/troubleshooting#Disable-the-Command-Log) to see if reduces/prevents the crashes you are seeing and let us know?

**Comment by tusharbmc** [comment]
Thanks @emilyrohrbough for your suggestions, surely most of the time numTestsKeptInMemory alteration is not working for us, I will try out NO_COMMAND_LOG along with it and let you know if that helps. I had went through the #23391 you shared; however, I felt like those are the possibilities they talked about and not a confirm fix. What if chrome 106 improvement doesn't fix 'aw snap' error.

I really appreciate your efforts on Cypress profiling and looking forward to it.

**Comment by extracker-ppetrov** [comment]
Running the tests headless is not reproducing the issues for me. It only reproduces when using the Runner.

**Comment by extracker-ppetrov** [comment]
Using Electron as a browser and running the tests headless is not reproducing the issue for me. 
It reproduces only when using the Runner. More often when using Chrome and less often when using Electron.

**Comment by Fewwy** [comment]
"cypress": "^9.6.1" - have the same issue using Chrome.

**Comment by AnushaAshokReddy** [comment]
@jennifer-shehane , 

Is there a final solution on this issue? We are facing same issue for longer test cases even after doing the following settings in cypress.json file 

"requestTimeout" : 30000,
  "numTestsKeptInMemory": 0,
  "responseTimeout" : 50000,
  "pageLoadTimeout": 100000,

Could you please post the solution here since there are lot many tickets open on the same issue? 

Thank you :)

**Comment by extracker-ppetrov** [comment]
I am able to reproduce this on Edge and Electron too, for longer test suites that hold multiple test cases, it(}. 
The issue reproduces mostly when test cases are failing within the spec test suit and are being rerun. 
Lets say you have 7 test cases in the spec file, if two fail and are rerun 3 times each, the issue reproduces. Setting the numTestsKeptInMemory to something different than 0 is reducing the time to reproduce it.

**Comment by emilyrohrbough** [comment]
@extracker-ppetrov Thanks for the details. How many tests on average are in your spec? How many commands on average per test? Are you using Cypress out of the box are are you also using a plugin/preprocessor as well?

**Comment by extracker-ppetrov** [comment]
I would say 8 to 10 tests. My longest test has about 150 lines, but I am using page object model and two layers of encapsulation, so lets say may be 200-250 commands for that one. But that is a rare case. This spec always reproduces the issue when one of the 11 tests inside fails. 
Mostly I would say my tests have about 50 -60 commands and there are 8 to 10 tests in each spec. 
Our tests are in TypeScript.  
I do not have a preprocessor in my configuration. I am using Cypress out of the box in that aspect.

**Comment by extracker-ppetrov** [comment]
Here is also a crash output from a headless run. I am not running this in Docker. I am simply using the Terminal in VS Code. I am getting this error for chromium crashing, when I run my tests headless with Electron.  
───────────────────────────────────────────────────────────────────────────────
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- There is a memory leak in Cypress (unlikely but possible)
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed

**Comment by Jaroslav004** [comment]
I think I had previously version 8 something on my PC with 8GB RAM and around 16 tests when my browser went "Aw snap" on approximately every fourth attempt to run all the tests. I thought that the PC's memory wasn't big enough so I got a new PC with much faster CPU and twice the original RAM and guess what...my tests are now failing on every single attempt. The only difference was that I intalled cypress 10 something instead of version 8 on new PC. It is so bad now that often I'm not even able to run one single (longer) test that ran just fine on version 8.

**Comment by extracker-ppetrov** [comment]
10.8.0 made things worse. I can hardly run 5-6 tests headless before cypress crashes. I had to revert to 10.7.0.

**Comment by tusharbmc** [comment]
> Chrome itself has had quite a few bugs logged around issues with crashing due to running out of memory, so some of the issue is out of Cypress' control. Please see #23391. It seems Chrome 106 should see improvements.
> 
> That being said, we understand your frustrations. I am going to do some profiling of Cypress and try to see what we can do on our side to reduce hitting this limit.
> 
> **Our First steps:**
> 
> * I am aware of a memory leak introduced in 10.0 that I am actively working on fix.
> * I am going to look at destroying our source mapping instances when we tear down Cypress between new spec selections in open mode and in navigation events with `cy.visit()` to a new domain
> 
> **Feedback would be appreciated:** In addition to altering many tests are kept in memory with `numTestsKeptInMemory` (default is 50), we know the reporter does impacts the overall performance and large specs will have degraded performance as the run executes due to the number of elements rendered on the dom. We should really virtualize the reporter, however in the short-term, can you try using `CYPRESS_NO_COMMAND_LOG=1` (https://docs.cypress.io/guides/references/troubleshooting#Disable-the-Command-Log) to see if reduces/prevents the crashes you are seeing and let us know?

Hi @emilyrohrbough,

I have updated Chrome 106 and Cypress 10.8, still facing the same issue. Cypress needs some performance improvement to get rid of aw snap error.

Cypress: 10.8, Chrome: 106, already using, numTestsKeptInMemory: 0,
Command: npx cypress run NO_COMMAND_LOG=1 --browser chrome --headed --spec **/regression/* --config baseUrl=<Application URL>

I am sorry, could not share the code/repo its organization proprietary.

If we are looking at Cypress as a replacement of Protractor, it needs to be robust and reliable. We are not in need of enhanced debug mode or jazzy reports, Cypress should first at least execute our e2e tests which are quite lengthy, some tests take around 20 mins.

I hope Cypress profiling is going well, you and your team will nail down this issue soon.

Thank you!

**Comment by vasanthiraman** [comment]
Cypress browser is crashing frequently during the execution, it becomes a blank screen suddenly and we need to close the browser window and start the execution again. It is being a major issue since we face it very frequently, especially after the upgrade to 10.6. previously we were using version 9.5 we faced that crash very rarely only when the execution time exceeds 6 or 7 mins. but in the upgraded version we face it even after 3 mins.

We use Electron V102. Please let us know if there is any solution for this issue.

**Comment by dwaynegreen** [comment]
> Chrome itself has had quite a few bugs logged around issues with crashing due to running out of memory, so some of the issue is out of Cypress' control. Please see #23391. It seems Chrome 106 should see improvements.
> 
> That being said, we understand your frustrations. I am going to do some profiling of Cypress and try to see what we can do on our side to reduce hitting this limit.
> 
> **Our First steps:**
> 
> * I am aware of a memory leak introduced in 10.0 that I am actively working on fix.
> * I am going to look at destroying our source mapping instances when we tear down Cypress between new spec selections in open mode and in navigation events with `cy.visit()` to a new domain
> 
> **Feedback would be appreciated:** In addition to altering many tests are kept in memory with `numTestsKeptInMemory` (default is 50), we know the reporter does impacts the overall performance and large specs will have degraded performance as the run executes due to the number of elements rendered on the dom. We should really virtualize the reporter, however in the short-term, can you try using `CYPRESS_NO_COMMAND_LOG=1` (https://docs.cypress.io/guides/references/troubleshooting#Disable-the-Command-Log) to see if reduces/prevents the crashes you are seeing and let us know?

I ran our tests that go through headed chrome 106 using the CYPRESS_NO_COMMAND_LOG=1. We have 13 tests, some of which visit one page, and the rest go through an E2E flow of approximately 5 - 10 pages. The "Aw Snap" crash in chrome still occurs when running all of the tests through the runner. I'm currently running Cypress version 9.6.1.

**Comment by dwjohnston** [comment]
Has anyone been able to create a minimal repro of this? 

I've been attempting to here: https://github.com/dwjohnston/cypress-performance-issue but have been unsuccessful.


Strategies so far: 

- Long running test (100x click a button that waits 3 seconds and shows some text, assert for existence of the text) 
- Fill the dom with new items (300x fill out a textfield and submit form, which will add the text as a div, assert for existence of text).

**Comment by Jaroslav004** [comment]
I've been having problems with Ow snap messages on one of my projects as I mentioned in earlier post where my tests keep crashing even if I run only one of them at the time but now I've ran tests on my older projects that I haven't used for a while, updated version of Cypress to the latest one and set numTestsKeptInMemory: 50 and it all ran just fine without failing despite having 14 fairly long tests in one script. So that makes me think that the issue is maybe somewhere else...that it is affected by certain commands or logic...I will try to single out some troublemakers...

**Comment by tusharbmc** [comment]
> I've been having problems with Ow snap messages on one of my projects as I mentioned in earlier post where my tests keep crashing even if I run only one of them at the time but now I've ran tests on my older projects that I haven't used for a while, updated version of Cypress to the latest one and set numTestsKeptInMemory: 50 and it all ran just fine without failing despite having 14 fairly long tests in one script. So that makes me think that the issue is maybe somewhere else...that it is affected by certain commands or logic...I will try to single out some troublemakers...

Thanks @Jaroslav004, after long time reading a positive post! Could you please share Cypress, Chrome version and machine configuration where your run the tests? Is it a parallel run?

**Comment by extracker-ppetrov** [comment]
10.7.0 is still the most stable version for me for now. It is crashing too when a test fails and has to retry 2-3 times, but still at least the tests that pass are not being interrupted by crashes.  
10.10.0 crashed even in headless mode.

**Comment by danielvianna** [comment]
Crashing here too all the time running locally with cypress open, please no new features until the basics are stabilized

**Comment by ddukic** [comment]
I have the same problem, it fails on longer tests especially if I keep running more tests in the same Cypress gui.
To debug the issue I added this in my `setupNodeEvents()` function

```
            on('before:browser:launch', (browser = {}, launchOptions) => {
                if(browser.name === 'chrome') {
                    launchOptions.args.push('--enable-logging', '--v=1')
                }
                return launchOptions;
            })
```
I'm using Ubuntu v22 and my Chrome logs are on this location:

`~/.config/Cypress/cy/production/browsers/chrome-stable/interactive/chrome_debug.log`

At the moment of the Chrome crash I see this message:

`ERROR:v8_initializer.cc(730)] V8 process OOM (Oilpan: Unprotecting memory.).`

**Comment by Jaroslav004** [comment]
> > I've been having problems with Ow snap messages on one of my projects as I mentioned in earlier post where my tests keep crashing even if I run only one of them at the time but now I've ran tests on my older projects that I haven't used for a while, updated version of Cypress to the latest one and set numTestsKeptInMemory: 50 and it all ran just fine without failing despite having 14 fairly long tests in one script. So that makes me think that the issue is maybe somewhere else...that it is affected by certain commands or logic...I will try to single out some troublemakers...
> 
> Thanks @Jaroslav004, after long time reading a positive post! Could you please share Cypress, Chrome version and machine configuration where your run the tests? Is it a parallel run?

I've tested it on Cypress 10.4.0 (although I've since upgraded it to newer version but it did not help. I'm experiencing problems only when I run it in UI. I use a laptop with Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz and 16GB RAM and Windows 11. 
The script that I mentioned earlier that ran without failing contained originally no loops. Later on when I added a few for loops to my code it started occassionally failing so there might be some hint to what it causes...

**Comment by extracker-ppetrov** [comment]
Here is a video, with dev tools open so you can see the memory spike once a test fails: 
https://www.loom.com/share/922e1a78c4a24abe8c5c68d08af861a3

**Comment by extracker-ppetrov** [comment]
Here is a video so you can see the spike in memory once a test fails and how it crashes the runner afterwards:
https://www.loom.com/share/0f4c387b11964f57a4c4ddf90ec5547e
The test suite has 21 test in it. It crashes at usually between the 5th and the 7th. 
What I noticed by separating the test in separate suites is that the memory consumption raises super fast when doing assertions and when entering values in the txt fields.

**Comment by richardszanyi-kasa** [comment]
@dwjohnston 
We've been seeing these errors with a lot of `cy.get()` on a page. (For example a table with many values)
Try to play around `.each()` and `.get()` functions for reproduction.

**Comment by DobQA** [comment]
I'm using Mac Ventura
Cypress 11.2 and latest Chrome 108.
Issue still exists, happens at random times.
I often need to re-run the test.

**Comment by hodbby** [comment]
Crashes also here on every run
Chrome- 107.0.5304.121 (Official Build) (64-bit)
Firefox- 107.0 (64-bit)

When run on local machine 127.0.0.1, it crashes every ~10th run

**Comment by magarwal19** [comment]
I am also facing the same issue when executing my suite. It does have some long running E2E tests
Mac: 13.0.1
Chrome: 107

Have observed same issue while executing it using linux machine

**Comment by blaszlo-well** [comment]
I also have this issue with long running tests.

MacOS version: 13.0.1
Chrome version: 107

It works flawlessly in headless mode for me.

**Comment by JesseZomer** [comment]
I also have this issue, but it also happens after all the tests are done and I'm just hovering over the steps and looking at the screenshots

**Comment by viriatis** [comment]
In my case that I using on jenkins ( CI ): 
I create a custom image of cypress/included:11.2.0 with a replaced base image: "cypress/browsers:node16.16.0-chrome107-ff107" . And all crashes on chrome with long runs stopped.

```

FROM cypress/browsers:node16.16.0-chrome107-ff107

(...)
```

If you want to do a quick test, just pull this image:

[Custom docker image 1050475/cypress/11.2.0-node16.16.0-chrome107-ff107](https://hub.docker.com/layers/1050475/cypress/11.2.0-node16.16.0-chrome107-ff107/images/sha256-b7e6a6a001b5788a739df059f455122d26482725a32c1f5d93822f2b475f3417?context=repo)

More info:
https://github.com/cypress-io/cypress-docker-images/tree/master/included
https://github.com/cypress-io/cypress-docker-images/tree/master/browsers

**Comment by vitaliy4us** [comment]
Right now I am executing 3 (three) tests only. Only one the same function in each test. The function has 150 lines of code. 100% tests fails due to out of memory error. Cypress 12.5.1, numTestsKeptInMemory: 5, Windows 10 professional, 16.0 GB memory. Chrome v112. The tests are executing on local machine in Cypress runner. Memory volume used by Chrome when crashing is 5GB.

**Comment by Livven** [comment]
Seeing this very reproducibly on certain tests with Cypress 12.9.0, both Chrome 112 and Electron 106. Firefox works flawlessly though 🦊

**Comment by EmreCihanbeyoglu** [comment]
Any update, improvement?

**Comment by DobQA** [comment]
This happens to me on latest version of Cypress - its not a machine resource issue, running latest Chrome 64GB Ram and latest Intel chip. I notice its todo perhaps with the site being tested, site using Angular Framework, happens at certain points.

**Comment by nagash77** [comment]
Have folks tried using the config flag `experimentalMemoryManagement` [link to docs](https://docs.cypress.io/guides/references/experiments#Configuration) which was added in [12.4.0](https://docs.cypress.io/guides/references/changelog#12-4-0)?  I would try setting that to true and seeing if that helps with your specific use case.  One note - if you are running a large single test this change will likely not improve performance for you and breaking your large test into smaller tests may be beneficial.

**Comment by nagash77** [comment]
It's been a couple of weeks and I have not heard back from folks.  I am going to close this issue.  If you are still encountering this issue after turning on that config flag, please open a new issue and we will be happy to investigate.  Please note this issue in your comment.

**Comment by brandonLyonMM** [comment]
@nagash77 you said that if we are running a large single test this change will likely not improve performance for us and breaking a large test into smaller tests may be beneficial. Since that was true for me, I did not reply. I was trying to run a large single test. Unfortunately breaking the test into smaller tests is not an option for me in this case.

**Comment by nagash77** [comment]
@brandonLyonMM please open a new issue with your specific use case and we will be happy to investigate.  Please mention this ticket in your issue.

**Comment by nathan5x** [comment]
I'm running into a similar issue where a single test does many things, and it is hard to break the flow. 
@brandonLyonMM - Did you open a new issue?

**Comment by brandonLyonMM** [comment]
> I'm running into a similar issue where a single test does many things, and it is hard to break the flow. @brandonLyonMM - Did you open a new issue?

No I did not

**Comment by extracker-ppetrov** [comment]
I am still facing the same issue after 12.4.0.
The way I started writing my tests is by grouping steps from one test in separate It()s.  
Each spec file is a single test for me and the steps inside are broken in separate It() This way I can control the crashes.

**Comment by andreynav** [comment]
>I am still facing the same issue after 12.4.0.
The way I started writing my tests is by grouping steps from one test in separate It()s.
Each spec file is a single test for me and the steps inside are broken in separate It() This way I can control the crashes.

Agree!
I faced the same crashes if I run API test in cycle

```
it('GET request to each region should have status 200', () => {
    cy.get<RegionsT>('@regionsData').then((regionsData) => {
      regionsData.regions.forEach((item) => {
        cy.api(`https://restcountries.com/v3.1/region/${item.region}`).then((response) => {
          expect(response.status).eq(200)
        })
      })
    })
  })
```
  
  There are only 5 regions and almost in 50% of runs browser is crashes!
  
  If I separate this test to 6 tests 

  ```
it('GET request to a region should have status 200', () => {
    cy.api(`https://restcountries.com/v3.1/region/Africa`).then((response) => {
      expect(response.status).eq(200)
    })
  })
```
tests pass OK

@nagash77 please take a look at this crashes! People still have the problems!

**Comment by mike-plummer** [comment]
@andreynav Unfortunately your reproduction is incomplete so I am unable to review it to identify what your issue is - the shape of the `@regionsData` alias could have *major* impacts on how many service calls actually get made here. In addition, in your example you don't actually need to call a `GET` on that endpoint since you're just asserting that the endpoint returns a 200 - you could instead use a `HEAD` request which has *massive* memory and performance improvements.

If you have a complete reproduction that you believe demonstrates a legitimate memory issue in Cypress I invite you to open a new issue so we can investigate

**Comment by extracker-ppetrov** [comment]
@mike-plummer 
We all have valid tests that fail with the chrome browser blowing up with 'out of memory' If you create a long enough E2E test that deals with UI elements only, and monitor the chrome browser in DevTools, you will see that the memory consumption grows with insane rates. 

https://www.loom.com/share/0f4c387b11964f57a4c4ddf90ec5547e

Once the memory consumption reaches 6-7GB, the browser crashes. Same with Electron, same with Edge. 

I do not see a valid reason to close this ticket, when all these people are still facing the same issue.

**Comment by mike-plummer** [comment]
@extracker-ppetrov I've reopened as requested - can you provide a reproduction case that demonstrates the issue while following Cypress' existing recommendations around reducing memory use? These recommendations primarily revolve around the fact that Chromium renderer processes are restricted to ~4GB of JS memory heap.

There are many things you can do to reduce the risk of exhausting memory:
1. Split very long tests into smaller tests
2. Avoid asserting against complex objects or very long strings - can you instead assert against a subset or more targeted item?
3. Use `experimentalMemoryManagement` - this cleans up memory *between* tests, so it helps after splitting large tests up. If running in `open` mode the `numTestsKeptInMemory` flag and [disabling the command log](https://docs.cypress.io/guides/references/troubleshooting#Disable-the-Command-Log) also help
4. Reduce unnecessary aliases
5. Avoid intercepting/requesting very large datasets (can you use a fixture instead? Can you do a `HEAD` instead of `GET` request?)
6. Ensure you aren't introducing memory leaks by persisting cross-test state in your specs (for example, global or shared variables)
7. Enable `testIsolation` to reduce risk of application-side memory leaks
8. Disable video recording
...and many more

**Comment by nagash77** [comment]
@extracker-ppetrov are you able to provide a reproducible example using [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny)?

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by ngomezph** [comment]
Tests done: 
deleted TaskA from ContentItemA - shows as deleted in db - **Passed**
- ContentItemA - shows not deleted in db - **Passed**
deleted ContentItemB - shows deleted in db - **Passed**
deleted TaskB from CampaignA - shows as deleted in db - **Passed**
- CampaignA - shows not deleted in db- **Passed**
deleted CampaignB - shows deleted in db - **Passed**

**Comment by LouisGinger** [comment]
Happens all the time even with tests kept in memory set to 0. This is actually making cypress unusable at present and needs fixing.

**Comment by juliancastroorozco** [comment]
Cypress crashing so much that makes it unusable, sadly my company is looking to move away from cypress because of this, wish you the best

**Comment by jennifer-shehane** [comment]
@juliancastroorozco @LouisGinger Please comment or open a new issue detailing what is happening and providing a reproducible example of that issue. We can't assist without having a way to reproduce this ourselves. We run 1000s of tests every minute in Cypress, so it must be something specific to your application, test suite, environment, browser, etc - there's lots of factors for us to track down.

**Comment by silvio-romero-intelex** [comment]
Getting the same issue after upgrading to latest version of chrome
![image](https://github.com/cypress-io/cypress/assets/147631483/4cdc9f36-2702-44c8-867d-1d85db96da71)
![image](https://github.com/cypress-io/cypress/assets/147631483/c71f3157-bc72-4cfb-bd5a-2177115d442c)
![image](https://github.com/cypress-io/cypress/assets/147631483/ed702ee7-c42e-4f86-bead-475e2c744190)
