### ISSUE TITLE
Cypress Dashboard - Can no longer add other repos from my Organization's GitHub project

### ISSUE THREAD

**Issue by cmaloney7** [cypress-io/cypress#21168]
### Current behavior

We can no longer add other repos from GItHub projects.  Redirects to a 404 in GItHub page.  This prevents any Cypress Dashboard integration with new repos.

### Desired behavior

Should be able to add new repos from my company's GitHub project in the Cypress Dashboard

### Test code to reproduce

1. Navigate to the Cypress Dashboard
2. Open the page to your company's organization
3. Click the "Integrations" link in the left menu
4. Under "Installed Integrations", CLICK the "Configure" button for "GitHub"
5. Under "Active Installations", CLICK the "Manage" button for your GitHub Organization.  A web page dialog opens and redirects to GitHub

The web dialog contains a GitHub 404 page
![image](https://user-images.githubusercontent.com/10427376/164510826-0d485dee-c258-4b94-af1e-d44bdedf4d2c.png)

### Cypress Version

9.5.3

**Comment by conversaShawn** [comment]
@cmaloney7 @coltdorsey Are you still experiencing this issue?

**Comment by conversaShawn** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
