### ISSUE TITLE
Specific test fails and hangs on CircleCI

### ISSUE THREAD

**Issue by goldylucks** [cypress-io/cypress#21189]
### Current behavior

we have a specific test that passes locally, passes on codeship, but fails on cypress circleCI on docker, (almost) every time.
Rest of the tests work fine on circleCI.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/6963212/165115174-4e39b43e-c332-4033-ad18-e008184fe7b2.png">

### Desired behavior

should pass on docker like it passes locally and on codeship, but even if it fails it should not hang

### Test code to reproduce

I don't know how to reproduce this.

### Cypress Version

9.5.1

### Other

Log of running cypress with `DEBUG=cypress*

**Comment by jennifer-shehane** [comment]
@goldylucks The logs you posted are printing out possible sensitive information in the form of env vars that are being printed. I suggest you rotate all keys that were exposed in this document. I've removed the log file from the original comment and deleted the revision history of the comment.

- Can you provide a reproducible example of the issue? 
- Did this just start happening recently? 
- What changes were made since this was passing and is now not passing?

**Comment by goldylucks** [comment]
_Can you provide a reproducible example of the issue?_. 
- Not really , I don't know what's causing this nor how to reproduce w/o replicating our entire angular app.

_Did this just start happening recently?_
- We just switched to circleCI and it started happening. It doesn't happen on codeship nor locally on linux or mac

I couldn't make sense of the logs.
Could you?

And yes we rotated the keys anyway, thanks :)
