### ISSUE TITLE
.should(callbackFn) is not retried in an after hook if the previous test function failed

### ISSUE THREAD

**Issue by ApostolosBenisis** [cypress-io/cypress#21198]
### Current behavior

When the `.should(callbackFn)` chained after a `cy.wrap()` is placed in an `afterEach()` hook, the  `callbackFn` is not retried if the previous test function (`it()`) has failed.
This causes the after hook to fail, even if all assertions would eventually pass, and all further tests are stopped.

### Desired behavior

The `callbackFn` should be repeatedly retried until all assertions pass, or a timeout occurs, independently of the status of the previous test function. 

### Test code to reproduce

```
describe('.should(callbackFn) is not retried in an after hook if the previous test function failed', () => {
    afterEach("hook should always succeed after 1 second", () => {
        const start = Date.now();
        cy.wrap(null).should(() => {
            expect(Date.now() - start).to.gte(1000);
        });
    })

    it('should succeed after 2 seconds', () => {
        const start = Date.now();
        cy.wrap(null).should(() => {
            expect(Date.now() - start).to.gte(2000);
        });
    });

    it('should fail', () => {
        expect(false).to.be.true;
    });
});
```

### Cypress Version

9.5.1

**Comment by sainthkh** [comment]
I"ve checked about this behavior and learned that it's intended. Check the comment below: 

https://github.com/cypress-io/cypress/blob/a47b45fc83b1bc750660ffcf9f30db7de6cd484c/packages/driver/src/cy/retries.ts#L104-L119

The case above is No 2, (when we have an error).

And this is a good behavior because having an error can cause false positive on the retry results. 

----

And [Mocha hooks doc](https://mochajs.org/#hooks) says that `afterEach()` is created to clean up the setup, not to test something:

> Mocha provides the hooks before(), after(), beforeEach(), and afterEach(). These should be used to set up preconditions and clean up after your tests.

So, it is not a good convention to use `should` inside `afterEach()`.

It is recommended to make a function about the repeated assertions and call it inside `it` functions like below:

```js
describe('recommended', () => {
    const lastAssert = () => {
        const start = Date.now();
        cy.wrap(null).should(() => {
            expect(Date.now() - start).to.gte(1000);
        });
    }

    it('should fail', () => {
        expect(false).to.be.true;

        lastAssert();
    });
});
```

**Comment by sainthkh** [comment]
Closing because of the inactivity.
