### ISSUE TITLE
cy.origin doesn't support custom commands

### ISSUE THREAD

**Issue by KrzGruszcz** [cypress-io/cypress#21264]
### Current behavior

Can't run custom command inside cy.origin callback function. `cy.<custom_command_name> is not a function` error is thrown:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/86097671/165945925-6a420823-10fa-4b90-87f7-1b24487b0e2a.png">

How to reproduce:
```js
Cypress.Commands.add(
  'getLinkByText',
  (text) => {
    cy.contains('a', text)
  },
);

it('origin example', () => {
  cy.visit('/')
  cy.getLinkByText('Start a free trial')  // works here

  cy.origin(
    'https://www.google.com/',
    () => {
      cy.visit('')
      cy.getLinkByText('Sign in')
    }
  )
})
```

The issue is also reproducible if custom command is implemented in `support` directory.

### Desired behavior

I'm not sure if it's some limitation for cy.origin not to support custom commands, but it should be. 

### Test code to reproduce

https://github.com/KrzGruszcz/cypress-origin-issue

### Cypress Version

9.6.0

**Comment by mjhenkes** [comment]
This is a current limitation of `cy.origin` and is being tracked in https://github.com/cypress-io/cypress/issues/19974. Require will be supported before `cy.origin` becomes generally available.

The Cypress instance defined in the `cy.origin` block is a wholly separate instance from one defined on the initial origin and the instances can only communicate using serialized strings via `postMessage`. Due to this limitation custom commands cannot be shared at this time.

The current workaround is to redefine the custom command within the cy.origin block, but this to limits you to only using cy provided commands and no third party code.

```javascript

Cypress.Commands.add(
  'getLinkByText',
  (text) => {
    cy.contains('a', text)
  },
);

before(() => {
  cy.origin('https://www.google.com/', () => {
    Cypress.Commands.add(
      'getLinkByText',
      (text) => {
        cy.contains('a', text)
      },
    );
  })
})

it('origin example', () => {
  cy.visit('/')
  cy.getLinkByText('Start a free trial')  // works here

  cy.origin(
    'https://www.google.com/',
    () => {
      cy.visit('')
      cy.getLinkByText('Sign in')
    }
  )
})
```
