### ISSUE TITLE
cy.screenshot() return Type is always Chainable<null> even though yields previous element when chained

### ISSUE THREAD

**Issue by bvandercar-vt** [cypress-io/cypress#21277]
### Current behavior

Incorrect typing: `cy.screenshot()` indicates that the return type is always `Chainable<null>` even though when chained from an element (i.e. `cy.get('input').screenshot('the input')`) it yields the chained subject. This is inconsistent with functionality, and inconsistent with the `cy.screenshot()` documentation that claims it yields the passed subject.

### Desired behavior

Have correct type for cy.screenshot() when chained

### Test code to reproduce

cy.get('input').screenshot('the input').then((inputElement)=>{
    cy.wrap(inputElement)  // typescript indicates inputElement is null even though it is not.
})

### Cypress Version

9.6.0

**Comment by davidmunechika** [comment]
Thanks for opening an issue! I was able to reproduce using your example code.

<img width="511" alt="Screenshot 2022-05-03 at 8 45 29 AM" src="https://user-images.githubusercontent.com/27690333/166455274-305ce7b7-5dc1-413a-8b59-fb77ca5523bf.png">

According to our docs, it does appear `cy.screenshot()` should yield the same subject it was given from the previous command. The current behavior seems to be inconsistent with this.

**Comment by paazmaya** [comment]
... but it still relevant

**Comment by nagash77** [comment]
@paazmaya are you seeing this behavior on the latest version of Cypress?

**Comment by paazmaya** [comment]
@nagash77 yes, while upgrading to the latest Cypress over here https://github.com/Visual-Regression-Tracker/agent-cypress/pull/238.

Specifically at https://github.com/Visual-Regression-Tracker/agent-cypress/blob/update-dependencies-like-its-mid-july-2023/lib/utils.ts#L91 where the `.screenshot()` method was chained with `.then()` to run the `cy.task()`, but it will complain in editor due to types, and in the current form of the code, calling `cy.task()` inside the `onAfterScreenshot` callback is showing up in error logs as a failure...
