### ISSUE TITLE
Custom commands not working inside cy.origin callback

### ISSUE THREAD

**Issue by emilio-notable** [cypress-io/cypress#21326]
### Current behavior

We are testing the new `cy.origin` command to use multiple domains in the same test. But when we want to use a custom command (ie: one that was defined with `Cypress.Commands.add('customCommand', customCommandFunction);`) in the second domain, it throws the error `cy.customDomain` is not a function

### Desired behavior

be able to use custom commands in multi-domain tests

### Test code to reproduce

```
Cypress.Commands.add('customCommand', () => { visit('') });
```

and then in the test:

```
    cy.origin('second_domain.com', () => {
      cy.customCommand();
    });
```

### Cypress Version

9.6.0

### Other

Using `experimentalSessionAndOrigin = true`

**Comment by mjhenkes** [comment]
@emilio-notable , You're correct, custom cypress command are currently not reachable in `cy.origin`. Since any communication between origins must be sent via post message we aren't able to pass functions between origins. We have a couple of workarounds for this, one of which is still in development.

You can define custom commands for an origin in a before block and it will persist in the origin for the entire spec run. You could even define the before block in your support file to make it available for all specs.
``` javascript
before(() => {
  cy.origin('myOrigin', () => {
    Cypress.Commands.add('myCommand', () => {
      cy.log('Hi mom!')
    })
  })
})

it('calls my custom command', () => {
  cy.origin('myOrigin', () => {
    cy.myCommand()
  })
})
```
We're working on a require feature that will let you require files that can be shared between origins, follow that here:
https://github.com/cypress-io/cypress/issues/19974.
