### ISSUE TITLE
Feature: natural language query functions for links and form elements

### ISSUE THREAD

**Issue by searls** [cypress-io/cypress#2138]
I'd like to see Cypress add natural language query functions for links and standard form elements.

One of the nicest things about the [capybara](https://github.com/teamcapybara/capybara) API is that it has a few tricks that make selecting links and form elements (the element types an integration test will interact with most frequently) queryable with the same natural language text that users will see. 

Here are a few examples from Capybara:

* `click_link('Link Text')`, `click_button('Button Text')`, `click_on('a link or a button')`
* `fill_in('First Name', with: 'John')`
* `check('A Checkbox')`, `uncheck('A Checkbox')`

And so on. None of these matchers are particularly challenging to implement, but they can dramatically improve the UX of a browser automation API, especially to people in non-typical developer roles. Additionally, selecting on text can improve the durability of a test suite against subsequent implementation changes, since you're coupling to text users can see and not markup.

This style has been found to have a few benefits over the years:

* The intent of the test is more apparent, especially in cases where the markup is obtuse or unclear (and where making the markup cleaner is outside the control of the tester)
* The test is less likely to break due to implementation changes that are unimportant to the user. If the label of a form element changes, however, that's almost always meaningful to _somebody_, since it's visible to the users. This has the effect of decreasing the occurrence of false negatives (tests that fail but for which nothing is broken)
* It encourages better a11y, in particular for form elements, which sadly still often fail to have proper `for` & `id` attribute matching. If the test can select a form element correctly based on given label text, so can a screen reader

**Comment by ngauthier** [comment]
Yes! I would love this. Here's a typescript example from the project I'm working on now that uses Enzyme. I built this really crappy version (almost called it Crappybara):

```typescript
export default function wrapy(node: any): Wrapy {
  return new Wrapy(node);
}

export class Wrapy {
  public node;
  constructor(node) {
    this.node = node;
  }

  public clickLink = (text) => {
    const links = this.linksWithText(text);
    if (links.length === 0) {
      throw new Error(`wrapy: Could not find link with text "${text}"`);
    }
    if (links.length > 1) {
      throw new Error(`wrapy: More than one link with text "${text}"\n` + links.map((l) => l.debug()).join("\n"));
    }
    links.simulate("click", new Event("click"));
  }

  public linksWithText = (text) => {
    return this.node.findWhere((n) => {
      if (n && n.length > 0 && n.type() === "a") {
        return n.text().indexOf(text) > -1;
      }
    });
  }
}
```

This allows you to write a test like:

```typescript
test("tabs", (done) => {
  withData((wrapper) => {
    expect(wrapper.state("selected")).toBe(Selected.Statistics);
    wrapy(wrapper).clickLink("Markets");
    expect(wrapper.state("selected")).toBe(Selected.Markets);
    wrapy(wrapper).clickLink("Charts");
    expect(wrapper.state("selected")).toBe(Selected.PriceChart);
    wrapy(wrapper).clickLink("Historical Data");
    expect(wrapper.state("selected")).toBe(Selected.History);
  }, done);
});
```

**Comment by brian-mann** [comment]
I think many of these API's are analogous to ours. We try to be be low enough to enable you to add abstractions on top of our API's, but simple enough that you can get by without doing anything special.

Here's some examples...

```
click_link('Link Text'), click_button('Button Text'), click_on('a link or a button')
fill_in('First Name', with: 'John')
check('A Checkbox'), uncheck('A Checkbox')
```

```js
cy.contains('a', 'Link Text').click()
cy.contains('button', 'Button Text').click()

// cy.contains prefers links or buttons over deeper elements
cy.contains('a link or a button').click()

cy.get('[data-cy="First Name"]').type('John') // agreed this could be improved
cy.contains('A Checkbox').check() // <-- we should allow applying `cy.check()` to a label if its connected to the checkbox
```

It would be fairly trivial to add a custom command (or just a regular ol' JS function) to abstract checking or unchecking across labels today.

We wrote a [best practice on selecting elements](https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements) which talks about adding attributes like `data-cy` or `data-test` and then selecting by that.

We could then give you a simple shortcut to select them.

```html
<input data-cy="First Name" />
```

```js
cy.get('[data-cy="First Name]"') // long and obtuse

cy.get('=First Name') // something like this where we automatically search those special attribute fields

cy.get('~=First') // Or even things like enabling the word to be a substring
```

A big part of what makes Cypress unique and special amongst any other testing tool is that it has native access to everything in your application.

That gives us the ability to create chaining mechanisms enabling you to go outside the boundaries of conventional API's.

For instance, you can drop directly into your own application code to do things like mutate state, fire events, or even wrap other elements you have a native reference to.

Although we haven't done it yet - creating things like framework specific selectors would be trivial and then enable you to select them by component name.

Today - you could just query into the DOM and then traverse those nodes manually (or create a custom command or function that does it)

```js
cy.document().then((doc) => {
  // traverse this thing manually
  const el = doc.go.get.me.react.component('<Form />')

  cy.wrap(el).find('button').click() // all possible to do today
})
```

Because of this power we've opted to go with composability of commands that do one thing really well. Anyone who wants to create abstractions that bundle up a sequence of commands can already do so in whatever way they choose.

```js
const clickLink = (text) => {
  return cy.contains('a', text).click()
})

clickLink('Link Text') // not anymore complicated than this
```

It's likely possible that in less than a single day's work, you could create direct 1:1 translations of every single capybara API, and then bundle them up as a bunch of functions and distribute them through a shareable NPM module.

All of that is possible because of the natural composability of the API. You could do that for any API you choose to model after.

Always happy to discuss more and totally understand the use case.

**Comment by ngauthier** [comment]
Thanks for the really thorough and thoughtful response! I think framework specific stuff should be in a separate module for sure, I was supplying my code purely as an example.

Regarding capybara features, I agree with Justin that cypress is missing is a user-oriented way to interact with input elements and links. I would find this incredibly useful because my team works with functional css, meaning we don't have semantic classes on our elements. Instead, being able to perform every possible user interaction using only information visible to a user is the end goal for us. Adding in test specific css classes and binding to that, and not what a user sees, it counter to the goal of acceptance testing. Relying on semantic css classes for your markup and styling in your tests prevents you from refactoring that markup and css while passing an acceptance test.

An additional benefit is that this forces a bare minimum of accessibility because links need meaningful text and inputs need meaningful labels. Writing a clear test helps you build a usable app!

Another benefit is that you can write a complete test without writing any code. Often a barrier to TDD is not knowing what your code will look like until you've tried a few things, and without knowing your code's interface (or desired interface) you can't write a test. If your API is always "stuff a person does" then you can always write a test first without knowing what your markup and css will need to be (or having the test enforce a particular markup or css).

Regarding assertions, this is an area in capybara that is constantly misused because the asynchronicity of it is hard to get right. So honestly, I'd prefer that feature set didn't make it into cypress.

**Comment by searls** [comment]
Thanks a lot for discussing this, Brian. I appreciate the composability of the API's `get`/`contains` functions. I think I started with an issue because I wanted to hear your thoughts on the topic before investing time in a separate package/module/plugin.

Your point about the chaining API is well taken. I think there may be an 80% rule here, where a simple `clickLink` or `fillIn` command is fine in most simple cases, FWIW. I think it's okay if we agree to disagree on the merits of selecting user-visible text; every approach to UI testing comes with its own trade-offs. 💚

**Comment by brian-mann** [comment]
@ngauthier I understand that you're not exposing an easy way to target elements - but that's where the `data-cy` or `data-test` or `data-testid` attributes come in. You just add those to the critical elements you specifically want to target. This insulates you from those ever changing or being coupled to the CSS styling of an element. That's why its suggested as a best practice.

The framework specific stuff would absolutely be in a separate module. The point I'm making is that it can be done today without introducing anything new into the core Cypress API's.

@searls sure thing. Worth mentioning is that our day to day interaction with a significant number of users gives us the ability to see how Cypress scales and applies to lots and lots of organizations and configurations. Of course this is still fairly biased, but the idea is that we get to see how it applies from day 1 all the way through adoption throughout many different teams at different companies. 

The ideal model or "sweet spot" that we're shooting for are developers themselves writing the tests as they build the application. Because of that, we're somewhat biased against creating abstractions for splitting up the development and testing efforts. These days the philosophy primarily "shift-left" whereby the person writing the code is also directly responsible for testing. Don't get me wrong, we have **many** QA engineers or other configurations using Cypress today. Cypress is designed to be broadly applied and flexible enough for many scenarios and situations, but we don't try to hide from the opinion that it's a developer-centric tool that tries to fit into your day to day development processes.

With all that said, for the last few months we have been considering some significant API changes. After you design and use something for years you start to see patterns that arise where users fall into the same problems over and over again. So don't be surprised if we end up making some big changes.

**Comment by searls** [comment]
Okay, I just published [cypress-capybara](https://github.com/testdouble/cypress-capybara#cypress-capybara), which implements the three most relevant and useful Capybara finder methods for the purposes outlined in the opening issue.

I scanned the rest of the Capybara DSL but didn't see anything else that'd provide much value that isn't (a) already implemented in Cypress's built-in API, or (b) wouldn't undercut the chaining API in the way @brian-mann  described earlier.

Would love if you'd add this to your docs! 💚

**Comment by patcon** [comment]
For anyone reading along after, I just want to acknowledge that the philosophy espoused in the Cypress docs (using `data-testid` etc) is not the only philosophy, and some tools seem to have an opposite one. e.g., [`testing-library`](https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change) maintained by kentcdodds, used for react components
https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change
