### ISSUE TITLE
Cypress ci 0.17.2 inside Docker container exits without running the tests

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#214]
In our CI containers, upgraded cypress to 0.17.2 but the ci command just ends without any output or errors.
```
$ cypress verify
Cypress application is valid and should be okay to run: /root/.cypress/Cypress
$ echo Starting tests at $(date)
Starting tests at Wed Sep 7 21:18:05 UTC 2016
$ cypress ci --spec cypress/integration/$CI_BUILD_NAME.js
Running after script...
$ echo Finished tests at $(date)
Finished tests at Wed Sep 7 21:18:06 UTC 2016
```

**Comment by brian-mann** [comment]
There is a new dependency in electron. If you invoke the binary directly like ~/.cypress/Cypress/Cypress you'll see the missing dependency. I think it's called like libxss or something. This was brought up in gitter earlier as well.

**Comment by brian-mann** [comment]
Okay I looked it up and its likely: `libXss.so.1`

You should see this error when invoking the binary directly:

```bash
/.cypress/Cypress/Cypress: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```

If you `apt-get install` this it should work fine again.

**Comment by brian-mann** [comment]
The reason why it doesn't output anything when running through the CLI is that we ignore `stderr`. Chromium is an amazingly noisy process that writes out hundreds of lines to `stderr` and if we didn't ignore that, your CI output would be completely garbled.

Unfortunately when you attempt to invoke a GUI program that's missing a dependency that output is **also** over `stderr`. And because it's ignored it appears to just "hang".  We have not figured out a way to know ahead of time if Cypress is missing dependencies.

We could try to do some string matching but different flavors of linux show different kinds of errors on missing dependencies so it's tough.
