### ISSUE TITLE
experimentalSessionAndOrigin cannot be changed by Cypress.config()

### ISSUE THREAD

**Issue by mmitchell3590** [cypress-io/cypress#21403]
### Current behavior

We just upgraded to 9.6.0 and are using `experimentalSessionAndOrigin` which replaces our current usage of `experimentalSessionSupport`.

We have test code that sets this feature to true for a specific test file:
`Cypress.config('experimentalSessionAndOrigin', true);`

This is not working and we are seeing an error --> Error: CypressError: `Cypress.config()` cannot mutate option `experimentalSessionAndOrigin` because it is a read-only property.

This worked previously with `experimentalSessionSupport`.

### Desired behavior

We should be able to change `experimentalSessionAndOrigin` with `Cypress.config()`

### Test code to reproduce

`Cypress.config('experimentalSessionAndOrigin', true);`

### Cypress Version

9.6.0

**Comment by mjhenkes** [comment]
@mmitchell3590, This was an intentional change on our part, allowing `experimentalSessionSupport` to be set per test would allow the tests to get into an indeterminate state. `experimentalSessionSupport` enables test isolation along with the `cy.session` command. Test isolation visits 'about:blank' between each test, enabling the feature after the test has already started would skip this step, putting the test run into a weird state. We discussed this and determined to provide the intended experience for the feature flag we should disallow enabling it per test. Sorry for any inconvenience this has caused. As we are planning to enable test isolation in 11.0 and would be interested in understanding any difficulties you experience trying to upgrade.

**Comment by gbannerman** [comment]
[The docs for config](https://docs.cypress.io/guides/references/configuration#Test-Configuration) specifically say that `experimentalSessionAndOrigin` is writeable and can be changed via per test configuration. So maybe these need updating?

![image](https://user-images.githubusercontent.com/16233190/178497695-7e2df8a2-d397-413e-bc4b-e31d4fe78db5.png)

**Comment by marcoscannabrava** [comment]
I believe it should also be updated here although I don't really see the reason not to be able to override it at the spec-level. That would be useful to my use-case.

![image](https://user-images.githubusercontent.com/54267712/193956992-0ec105fb-6b8d-4cfe-88f9-b5930cced8bd.png)

![image](https://user-images.githubusercontent.com/54267712/193957096-b91298a4-fa4a-40ba-bb9b-ecac613c9246.png)

**Comment by chaitanyak-bidgely** [comment]
Hi @mjhenkes ,

The issue mentioned by @mmitchell3590 [mmitchell3590] seems still seen with latest Cypress version. 11.2.0

I tried enabling experimentalSessionAndOrigin at Suite level and still getting the same error -> The experimentalSessionAndOrigin configuration can never be overridden because it is a read-only configuration option.

Is there any other way to handle it as my other testSuites don't need this property set to True
