### ISSUE TITLE
Visit being able to ignore specific animations

### ISSUE THREAD

**Issue by FlyingHelix** [cypress-io/cypress#21420]
### What would you like?

I'd like to be able, to either tell one single visit command to ignore all animations without affecting other ones, or to ignore animations of specific elements (maybe through a selector string like with get).

### Why is this needed?

The site i want to test has some decorative elements that are animated in the background, so visit keeps loading and loading and eventually times out, as the animation never stops.
Disabling waitForAnimations is, as far as i know, only possible for everything at once and not single commands. I tried with Cypress.env("waitForAnimations", "true") after the visit i do not want to wait for, but it seems to affect the whole test run, even commands before the call and even with the then() command. 
It would be perfect if you could disable waitForAnimations for specific classes, ids and such, maybe even with wildcards.

**Comment by mjhenkes** [comment]
I'm not sure that this is something we could offer. You may need to add logic in an on load block for the visit to disable or remove animations yourself before the page is completely loaded

Check out the [window before load event]https://docs.cypress.io/api/events/catalog-of-events#Window-Before-Load example. You may want to use the `window:load` event instead of the `window:before:load` event, but you'll have to try it out to be sure. In that block you can disable or remove animations yourself.
