### ISSUE TITLE
Is it possible to make beforeEach keep running if it fails because of `cy.url()`?

### ISSUE THREAD

**Issue by achelonmm** [cypress-io/cypress#2144]
### Current behavior:

When `beforeEach` fails in one test it stops the execution of all the tests after that.

### Desired behavior:

Is it possible to add an option to make the run keep going even if `beforeEach` fails once?
In my case I'm using `beforeEach` to log in into my application, but sometimes from clicking the "Log in" button until the page has loaded a lot of time passes and the `beforeEach` fails.

However, it's not like the application is failing, it's just taking a long time to load the page.

This is my code:
```js
beforeEach(function () {
        cy.visit('')

        cy.url()
            .should('contain','login')

        cy.get('#btnLoginOauth')
            .click()

        cy.get("#Username")
            .type("rcarter",{force:true})

        cy.get("#Password")
            .type("pass",{force:true})

        cy.get("#btnLogin")
            .click({timeout:10000})

        cy.url()
            .should('include', '/app/list')
    }))
```

My problem is that `cy.get("#btnLogin").click({timeout:10000})` takes a long time to load the page, and then `cy.url().should('include','/app/list')` fails because even if sometimes the page has loaded, it is still reading the old url and not the new one. I will give an example:
![error2](https://user-images.githubusercontent.com/41155189/42690992-a6a840ae-86a6-11e8-86c8-3b053c1db85e.png)

This sometimes fails even if the page has loaded because the `cy.url()` is reading the old url and not the new page one.

Because of this I have two questions:
1) As I asked before, is it possible to add an option to beforeEach so it keeps running the tests even if it has failed once?
2) Is there a way to make `cy.url()` read the new page and not the old one?

**Comment by jennifer-shehane** [comment]
> My problem is that `cy.get("#btnLogin").click({timeout:10000})` takes a long time to load the page

Cypress waits for the `load` event to fire on any page transition before continuing, and you can increase the `timeout` of this [globally](https://on.cypress.io/configuration#Timeouts) as `pageLoadTimeout`.

1. I think this *may* technically be possible by listening to Cypress [`fail` event](https://on.cypress.io/catalog-of-events#Catching-Test-Failures), but I'm not sure how you would isolate it to only catch failures in this `beforeEach` - and it is [strongly discouraged](https://on.cypress.io/catalog-of-events#Cypress-Events). 
2. I would recommend applying some more guards to your application, to ensure this page transition is happening how you expect before checking the url. What is actually happening in your application in between hitting the Login Button and the page transitioning? Are there cookies that need to be set? Requests that need to go out first? I would write assertions to check that those things are happening *after* you click the login button - then check that the `url` is correct. For example, this is one of our tests on login (in coffeescript):

```coffee
it "logs in", ->
  cy.visit("/#/login", {
    onLoad: (win) ->
      @loginWithPopup = cy.stub(win.Auth0.prototype, "loginWithPopup")
  })
  cy.contains("Log In with GitHub").click()
    .then ->
      expect(@loginWithPopup).to.be.called
      expect(@loginWithPopup.args[0][0].connection).to.eq("github")
  cy.hash().should("eq", "#/projects/runs")
```

We don't just click the button then check the url changes, we also make sure the right calls to our third party login are being called *first* - this will get us closer to where we want to be, instead of waiting around for an arbitrary amount of time for the hash to change. 

Let me know if this answers your questions.

**Comment by jennifer-shehane** [comment]
@achelonmm Did this help resolved your issue?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
