### ISSUE TITLE
cypress click not working on MFE which is federated into monolith

### ISSUE THREAD

**Issue by country-bumpkin-software** [cypress-io/cypress#21464]
### Current behavior

I work for an organisation and Im rolling out Cypress. One team is having an awful developer experience in getting Cypress to work with a trivial webpage.  This is jeopardising the roll out of this framework. 

When the web page is loaded it some of the web component containers  are part of a third party component ([HeadlessUI RadioGroup](https://headlessui.dev/react/radio-group)) (not sure if this is relevant).

The test is just clicking on one of these containers but literally noting happens.  In the cypress test runner you can see the click takes place butt he onClick event doesn't seem to be triggered.  We have tried every solution on stack overflow we can find but it doesn't seem to work.  We are using cypress 9.2.1 

This issue is with Chrome version 101, with Electron 94 the click does work sometime 30% of the time but it is just not reliable enough. With chrome is doesn't work 100% of the time

### Desired behavior

This line doesn't work and we need it to work:

cy.contains('Starter').click()

### Test code to reproduce

```
beforeEach('log in and go to plan page', function() {
    cy.clearCookies();
    cy.clearLocalStorage();
    cy.visit('https://login')
    cy.logIn()
    cy.getDataTestId('Route')
      .contains('Upgrade')
      .click({ force: true })
    cy.wait(25000)
    // cy.getDataTestId('SelectPlanStepTitle').should('have.text', 'Pick your plan')
  })

  it('user has access to payment methods to upgrade to Starter',  () => {
    
    cy.contains('Starter').click()
    cy.contains('Sign up for Starter').click()
    cy.contains('Your subscription')

  })
```

### Cypress Version

9.2.1

### Other

Html look something like this:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/85832271/168277867-6395faba-b419-400e-ad17-1f608dbb85ed.png">

**Comment by country-bumpkin-software** [comment]
Weird thing is if I installed the following library: https://testing-library.com/docs/cypress-testing-library/intro/
and use cy.findByText('Starter').click() it works!

Is there something weird going on here?

**Comment by BlueWinds** [comment]
Hm, If you can provide a reproducible example, I can take a closer look, but otherwise not sure how to help you troubleshoot this. You say in the app you can see it's clicking on the correct DOM element - that would have been my first suggestion, to verify that was that element.

You could also try [`cy.trigger()`](https://docs.cypress.io/api/commands/trigger), to trigger the onClick directly - this isn't a great solution, but it could help troubleshoot the problem, if it's related to `cy.click()` or something more application focused. You could also try registering a click handler on that element directly in the test - again not as a solution, but to help pinpoint the problem. Debug logs in the browser might also provide some hints. https://docs.cypress.io/guides/references/troubleshooting#Debug-logs-in-the-browser

**Comment by country-bumpkin-software** [comment]
Ah thanks for your input, it turns out that the third party component ([HeadlessUI RadioGroup](https://headlessui.dev/react/radio-group)) requires you to click on the radio group container and then click on the item you want to select? It that some sort of issue with cypress that it can't handle that? I mean when an end use click on the item in the radio group it is just selected without having to click once on the radio group container and then on the item you need?

**Comment by BlueWinds** [comment]
Hm, I'm not seeing that same behavior - it seems to work with HeadlessUI RadioGroup for me. Created this tiny little test:

```
  it('passes', () => {
    cy.visit('https://headlessui.dev/examples/react-radio-group-hero')
    cy.contains('Enterprise').click()
    cy.contains('Business').click()
  })
```

You can see that it flips between active elements just fine. Needing to use `{force: true}` on your `click()`s is a sign that there's probably something else going on - that shouldn't be necessary in most cases, and the error you're getting without using `force` might provide a hint what's going wrong.

**Comment by country-bumpkin-software** [comment]
Apparently the documentation said that the RadioGroup has to be in focus before an item can be selected do you think that has anything to do with it.

**Comment by BlueWinds** [comment]
I doubt it. Click events bubble, and cause focus, and the RadioGroup definitely does work in isolation, as show by the sample test I posted a moment ago using HeadlessUI's component demo.

My best guess is still that either your selector isn't quite right - selecting a parent element rather than the child that RadioGroup is expecting to get a click on, or something else is going on specific to your app.

Try getting the elements by text rather than TestID (as I did in my test), and consider whatever error you get if you remove `{force: true}` are the only troubleshooting tips I can offer. :woman_shrugging:

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by country-bumpkin-software** [comment]
feel free to try to reproduce this issue on the public facing website
