### ISSUE TITLE
@cypress/schematic: Run configuration does not work anymore without baseUrl

### ISSUE THREAD

**Issue by Kirdock** [cypress-io/cypress#21555]
### Current behavior

After upgrading from `1.6.0` to `1.7.0` all tests stopped working because `cy.visit('/')` is trying to access a file instead of a URL. Now the `baseUrl` has to be defined additionally in order to run the tests.

### Desired behavior

Cypress takes the host and the port of the `devServerTarget`. The host and the port should be defined once and not twice. There should be a reference instead.

## Current workaround:
Add `baseUrl: http://localhost:{myPort}` to the `cypress-run` and `cypress-open` options in `angular.json` or to `cypress.json`

### Test code to reproduce

angular.json:
```json
...
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            ...
          },
          "configurations": {
            "test": {
              ...
            }
          },
          "defaultConfiguration": ""
        },
        "serve-test": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "myProject:build:test",
            "port": 5000
          },
        },
        "cypress-open": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "myProject:serve-test",
            "watch": true,
            "headless": false,
            "browser": "chrome"
          },
          "configurations": {
            "production": {
              "devServerTarget": "myProject:serve-test"
            }
          }
        }
...
```

### Cypress Version

9.6.1

### Other

Angular core: `12.2.16`
cli, @angular-devkit/build-angular: `12.2.17`

**Comment by ZachJW34** [comment]
I was able to reproduce this.

Given a fresh angular workspace, the cypress schematic will work out of the box:
![Screen Shot 2022-05-24 at 2 23 22 PM](https://user-images.githubusercontent.com/25158820/170115975-baf70acc-7c21-4c0f-899d-bed9408ad4fb.png)

Adding an explicit port in angular.json for the serve.development configuration I get (expected since the baseUrl from the cypress config is overriding):
![Screen Shot 2022-05-24 at 2 25 25 PM](https://user-images.githubusercontent.com/25158820/170116288-c7a345de-045e-4a04-b0d4-2b970d888c6c.png)

Removing the `baseUrl` from the `cypress.json` gets me:
![Screen Shot 2022-05-24 at 2 26 30 PM](https://user-images.githubusercontent.com/25158820/170116470-50812b7d-c3b9-4282-b783-6d1d9354ff8f.png)

The third scenario is what it looks like you are seeing. I would expect the baseUrl returned from the angular dev-server to be used if there is no baseUrl configured which would respect the port specified.

I'm going to shuttle this issue to the team responsible for this package. Thanks for opening the issue @Kirdock

**Comment by admah** [comment]
I think is a regression introduced with #21415. I'm investigating what the root cause is.

**Comment by emilyrohrbough** [comment]
This was releases as `@cypress/schematic v2.0.2` on Aug 9ths.
