### ISSUE TITLE
Tests are displaying duplicate in edge , electron and chrome browser  

### ISSUE THREAD

**Issue by Basanthkumar** [cypress-io/cypress#21582]
### Current behavior

My project module build inside iframes and when i opened tests first time in any of like chrome , edge or electron working fine but second time tests are showing duplicate , where actual tests will pass and duplicated will get fail. 

### Desired behavior

Tests should display only one time

### Test code to reproduce

Can not provide code due to security restrictions 

### Cypress Version

9.5.1

**Comment by mjhenkes** [comment]
@Basanthkumar, could you use our https://github.com/cypress-io/cypress-test-tiny repo to create a re-createable example for us to debug?

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
