### ISSUE TITLE
ffmpeg doesn't always run at low priority

### ISSUE THREAD

**Issue by rrauenza** [cypress-io/cypress#21585]
### Current behavior

During capture, it looks like ffmpeg runs at low priority:

`0 S gitlab-+  91530  90804 66  99  19 - 517602 unix_s 09:41 ?       00:11:41 /opt/gitlab-runner/NCiG8AGt/0/.../cypress/.cache/Cypress/9.2.0/Cypress/resources/app/node_modules/@ffmpeg-installer/linux-x64/ffmpeg -f image2pipe -use_wallclock_as_timestamps 1 -i pipe:0 -y -vcodec libx264 -filter:v crop='floor(in_w/2)*2:floor(in_h/2)*2' -preset ultrafast /opt/gitlab-runner/NCiG8AGt/0/.../foo.spec.ts.mp4`

I think it is this code:

```
const startCapturing = () => {
    return new Bluebird((resolve) => {
      const cmd = ffmpeg({
        source: pt,
        priority: 20,
      })
      .videoCodec('libx264')
      .outputOptions('-preset ultrafast')
      .on('start', (command) => {
        debug('capture started %o', { command })

        return resolve({
          cmd,
          startedVideoCapture: new Date,
        })

```

But there seems to be another phase -- where I can see up to 600% cpu utilization (affecting other cicd jobs) that is not niced.  

It must be a second pass compressing, because that's when the -crf option is passed.

I think priority: 20 needs to be added here:

```
 return new Bluebird((resolve, reject) => {
    debug('processing video from %s to %s video compression %o',
      name, cname, videoCompression)

    const command = ffmpeg()
```

### Desired behavior

I'd like ffmpeg to always be niced since it is so cpu intensive.

Even better, an option like videoCompression to make this configurable?   And/or a thread limit passed to the command.

### Test code to reproduce

any code will work as long as videos are made.

### Cypress Version

cypress@^9.2.0:

### Other

I can make a PR for priority passed to ffmpeg.

If we want a user configurable option, then that would require more discussion.

**Comment by rrauenza** [comment]
Note:  There is one risk that the dev team should consider, which is that this could make cypress sessions take longer on cicd systems with multiple jobs, because the final ffmpeg will be deprioritized.  

I will argue that this is better than causing other jobs to timeout due to lack of CPU.

**Comment by rrauenza** [comment]
![image](https://user-images.githubusercontent.com/1376251/169610167-80eab71a-9f64-45af-81f7-b837d0aac619.png)

**Comment by BlueWinds** [comment]
Cypress runs ffmpeg in two stages: capture and process. The capture phase runs at low priority, single threaded, as light of a process as we can make it, so that it doesn't interfere with the running test. The processing phase, in contrast, is designed to use the entire available power of the machine to complete as quickly as possible, and not drag out your tests any more than necessary.

Using all available CPU is by design, to complete as quickly as possible. In CI, you usually run inside a docker container, so there are no other processes in that container contending for resources. I'd expect docker's CPU management to handle contention between containers, rather than nicing the ffmpeg process inside of them?

**Comment by Songyu-Wang** [comment]
I would like to +1 configurable ffmpeg or as least make it not resource greedy because the currently approach creates a spike pattern on cpu usage. I am gonna make an assumption here that "most people install cypress AND their product in the same VM" since it is architecturally easy to implement and probably can satisfy most of the use case. 

1. If people install everything in the same docker container, such as 
```
In one docker container: 
  run frontend in background
  run backend in background
  run worker(s) in background
  ...
  run cypress
```   
Then having cypress consistently spikes to 100% cpu usage could impact other background applications. Therefore create either flakes or unexplained errors (unless you are very knowledgeable in multiple domains)

2. If people are running "docker in docker" or equivalents

Then @BlueWinds is right, we can config the cpu limits. However, it is a pain in the xxx to identify the cpu usage per container and make educated guess on how to allocate resources for each container. In addition, any feature's performance change could force us to re-configure the allocation. If you are working with micro services, good luck!


So to simplify the issue and reduce the headache, a likely solution is to just use a better VM to keep the cpu usage under 100% which is not optimized because like 20% of the resources are wasted because  ffmpeg is not running. 


I appreciate the consideration to make the test suite finish as fast as possible, but financially speak, I would be happier to take a few seconds/minutes hit than double our base VM cost... (Or just not post-process the video at all, which is what I am doing. We are thinking about manually mass post-process the videos directly use ffmpeg at the end of the whole test suite, but it is not looked into yet)

**Comment by BlueWinds** [comment]
@Songyu-Wang - Makes sense, thanks for the input. I'm running the automated tests and will look at merging @rrauenza 's PR implementing this once they pass. :+1:

**Comment by rrauenza** [comment]
FWIW, I have solved this with cgroups and gitlab runner.  

I posted it here, but it's being voted for closure.  🙄 

https://stackoverflow.com/questions/72332642/how-can-i-assign-cgroup-resource-limits-per-gitlab-runner-job-to-ensure-fair-sha

```
#!/bin/sh
set -x
set -e
echo CGROUP Before:
cat /proc/self/cgroup
scope=$(grep 1:name=systemd: /proc/self/cgroup | grep -o -E 'session-\S+.scope')
systemctl set-property --runtime $scope CPUShares=1000 BlockIOWeight=500
echo CGROUP After:
cat /proc/self/cgroup
```
