### ISSUE TITLE
Tests hang when afterEach promise does not resolve with Retires enabled

### ISSUE THREAD

**Issue by taylorjellsworth** [cypress-io/cypress#21619]
### Current behavior

I recently noticed that our e2e tests periodically fail the first run and then randomly hang on the retry run.  After outputting cypress logs via `DEBUG='cypress:*'` I found the following:
- The `test:after:run` event never gets fired when the test hang on the retry run, The `test:after:run` event is supposed to happen after the `afterEach` and `after` Mocha hooks run 
- We get an `onMocha hook` output, which means that the `afterEach` hook has started
- We never receive an `onMocha hook end` output.  This signifies the `afterEach` hook has never finished.  So the `afterEach` hook is hanging for some reason
![Screen Shot 2022-05-10 at 10 14 06 AM](https://user-images.githubusercontent.com/47367288/170109249-df0f6406-93be-4414-836f-90bd7c42b22f.png)

It appears to me that the tests are hanging when retries are enabled and the afterEach promise does not resolve

### Desired behavior

During the first retry, Cypress should reach timeout and fail.  The test should not hang.

### Test code to reproduce

I am unable to share test code/logs due to proprietary rights.  However, I was able to reproduce a similar error where the test hangs on first retry when the done() callback is never invoked.

**In cypress.json**
```  
"retries": {
    "runMode": 1,
    "openMode": 1
 }
```

**Test Case**
```
describe('Cypress Tests Hang', () => {
  it('Cypress Tests Hang', () => {
    cy.visit('https://www.google.com');
  });

  afterEach(run => {
    cy.log('In afterEach');
  });
});
```

You'll see that the first run fails, and the retry run will end up hanging

<img width="550" alt="Screen Shot 2022-05-24 at 2 51 46 PM" src="https://user-images.githubusercontent.com/47367288/170110890-59e30884-d172-4528-ae5f-ab30bb900b02.png">

### Cypress Version

9.7.0

**Comment by ZachJW34** [comment]
I was able to reproduce this with latest Cypress (9.7.0). Like you are suggesting @taylorjellsworth, there seems to be something going wrong with how we are processing the `fail` event for hooks that timeout. I think a timeout of the hook should act the same as an error occurring within the hook.

Here is a snapshot of the `fail` function executing when throwing an error in an `afterEach`
![Screen Shot 2022-05-25 at 5 41 30 PM](https://user-images.githubusercontent.com/25158820/170381662-a86e6243-ee80-4db9-a729-9d657f4a7878.png)

With the timeout, the breakpoint is never reached
![Screen Shot 2022-05-25 at 5 42 20 PM](https://user-images.githubusercontent.com/25158820/170381699-d27ed680-f7a6-4e9e-adfc-dd304370c717.png)

Thanks for posting the issue, we'll add this bug to our backlog.

**Comment by taylorjellsworth** [comment]
@ZachJW34 Thanks for investigating!  I agree, I think a timeout of the hook should act the same as an error occurring within the hook.

If it's possible, can this bug be prioritized?  This is currently impacting our test suites, and if it gets stuck in the backlog we'd be forced to move off of Cypress (even though we really don't want to!)

**Comment by taylorjellsworth** [comment]
I was wondering if there are any updates on this?

**Comment by taylorjellsworth** [comment]
Hi @jennifer-shehane !  This is still causing us issues, I was wondering if anyone has started looking into it yet?

**Comment by ivanspasov99** [comment]
Facing the same issue. When using cy.request().then() on `before` or when there are more than 2 `it` cypress stucks.

It strange because if I put the logic inside one `it` it works if that helps somehow.

**Comment by flotwig** [comment]
Similar issue here: #18502

**Comment by taylorjellsworth** [comment]
@flotwig I was wondering if there's any estimate on when this will get looked at?  We are still running into this issue.

**Comment by taylorjellsworth** [comment]
@flotwig @mjhenkes @jennifer-shehane @mschile bump.  We are close to moving off of Cypress if this is not addressed

**Comment by Regaddi** [comment]
I'd like to add that not being able to use retries also increases costs.
In our app there is always some network flakiness to expect, so tests can sporadically fail without a corresponding change to the application.
We currently have a test suite of 120 Cypress tests.
Every time a test fails due to some flakiness that could otherwise be covered with the retries option, we'd have to re-run the tests, which typically adds $0,72 to our bill for Cypress plus CI costs. (I know this isn't a super fair comparison, but I'd prefer knowing that a test passed in a second run than not re-running the test at all).
While I understand that fixing this issue is not necessarily in the interest of the Cypress team (because it drives revenue) it's certainly annoying enough to start considering alternatives (echo-ing @taylorjellsworth).

**Comment by tgdevereux** [comment]
Just to add to this, we appear to be hitting a similar issue, however it appears to happen regardless of retries being set.
And we’re repro-ing it when we hit a separate file download issue, possibly related to https://github.com/cypress-io/cypress/issues/1551

Basically, we have a test that downloads a file, and then hits a pageLoadTimeout, perhaps due to  https://github.com/cypress-io/cypress/issues/1551
But if I have an afterEach block after this test (which just clicks a back button on the page), the test doesn’t throw the pageLoadTimeout error, and the test just hangs indefinitely. The tests are written in Typescript, running against a React UI.

Repro’d with:
Cypress version: 10.11.0
OS: macOS Big Sur (v11.7)
Browser version: Chrome 105.0.5195.125

**Comment by taylorjellsworth** [comment]
fyi - we have moved off of Cypress completely and onto Playwright due to this issue.  We would have loved to continue to use Cypress, but the lack of communication (even after asking for updates many times) on this issue was the driving force.  We could not wait around forever.  Hopefully this issue gets resolved at some point for those who are still dealing with it.

**Comment by mikhail-g** [comment]
I faced the same issue, it would be really nice having it fixed. Now we cannot use afterEach when having retries, it's very inconvenient

**Comment by ptrcortes** [comment]
I'm also experiencing this issue with Cypress 12. Would love a fix.

**Comment by sbfrancies-onyx** [comment]
I am experiencing this in `cypress 13.11.0`, my tests can hang indefinitely both locally and in an Azure Devops Pipeline when there are failures with retries enabled (we are using the [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/628#issuecomment-943656687) which uses `afterEach`). The same behaviour does not appear to occur when retries are not enabled.
