### ISSUE TITLE
Cypress with the ContextMenu not work - React Contextify 

### ISSUE THREAD

**Issue by jcsouz10** [cypress-io/cypress#2164]
### Current behavior: 

```jsx
<ContextMenu id={`menu-${this.props.candidate.id}`} animation={animation.fade} theme={theme.light}>
<Item className="testinhoImg"onClick={this.handleMenuDelete}>
  <div style={{ width: '50px', marginLeft: '0.5em', marginRight: '0.5em' }}>
    <img src={ViewSrc} alt="View" />
  </div>
  <span onClick={this.handleMenuDelete} className="testinhoImg ibm-plex-sans-serif-regular ibm-textcolor-blue-60"> View </span>
</Item>
```

### Desired behavior:
Hello guys, i'm using a library called React Contexty, and it has a `_menu_` that is inside of the `Contextify` and is called of `ContextMenu`, when i do request for it to click in the `Item` of the `ContextMenu`, it click but the action not happens.

### Steps to reproduce:
     
```js  
cy.get("input[name=input--searchForm-pierAdmin]")
  .type("Jean")

cy.get("button[data-test=button--searchForm-pierAdmin]").click()

cy.get("img[data-test=img--menu-candidate]")
.click({force:true}) 

cy.get(".testinhoImg").click({force:true})
```

### Versions

cypress 3.0.2 - windows 10 - chrome

**Comment by henrykuzmick** [comment]
Same issue

**Comment by henrykuzmick** [comment]
A workaround until fixed:
```
cy.document().then(doc =>
    doc.querySelector('selector').click()
);
```

**Comment by jennifer-shehane** [comment]
Can anyone provide a way to reproduce this - with a repo we can run to get this error?

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
