### ISSUE TITLE
cy.readfile and cy.fixture return null when using Cypress.Promise.all

### ISSUE THREAD

**Issue by Im-a-Train** [cypress-io/cypress#21655]
### Current behavior

I had some problems while creating a generic intercept function.
My approach was to concat an array of multiple fixture files and use them to mock a backend request:

```ts
export const simulateMetadata = (simulatedDocuments: Array<mockDocs>) => {
    let simulatedDocs = [];
    let promises: Array<Chainable> = [];
    simulatedDocuments.forEach(doc => {
        promises = [
            cy.fixture(doc).then((data: string) => {
                simulatedDocs = [...simulatedDocs, ...data];
            }),
            ...promises
        ];
    });
    return Cypress.Promise.all(promises).then(() => {
        cy.log('Mock ' + simulatedDocs.length + ' Documents');
        cy.intercept('someMockUrl', simulatedDocs);
    });
};
```
So I stored all promises I got from the cy.fixture calls in an Array. With the Cypress.Promise.all, I wait until all files are in my `simulatedDocs` array, so I can use this array to intercept the backend request of my application.
(`mockDocs ` is an enum so i don't have to type the full filepath while calling the simulateMetadata function)

While calling this fuction like this: `simulateMetadata([mockDocs.FILE1, mockDocs.FILE2, mockDocs.FILE3])` at the beginning of my test, I had some strange behavior.: My simulatedDocs array was always empty.

After some research and debugging I figured out, when I place my function call after any other cy.XY call, it worked as expected.
After some more research and debugging, I could reduce my code to reproduce the error to this:
```ts
describe(fixtureFirst', ()=>{
    it('readfile',()=>{
        cy.fixture('blup').then(blup=>cy.log(blup)) // this logs null too
        Cypress.Promise.all([]).then(() => {
            cy.log("lol")
        })
    });
})
```

I guess the problem is located anywhere in the `Cypress.Promise.all`, because without this the cy.fixture works as expected.
And as you see in the code above, I do not even wait for the fixture promise, I wait only for an empty array to complete. Somewhere might be a hidden side effect in `Cypress.Promise.all`.

### Desired behavior

If some one could fix this or if some one could make a remark about this behavior in the cypress documentation of the cy.readfile and cy.fixture section , this would be great.
At the moment I can live with this workaround:
```ts
describe(fixtureNotFirst', ()=>{
    it('readfile',()=>{
        cy.wait(1);
        cy.fixture('blup').then(blup=>cy.log(blup)) // this logs the blub content
        Cypress.Promise.all([]).then(() => {
            cy.log("lol")
        })
    });
})
```
or in my concret test script:
```ts
    it('upload and remove mail with attachment', () => {
        cy.wait(1);
        simulateMetadata([mockDocs.MAIL_WITH_ATTACHMENT])
        ...
```

### Test code to reproduce

```ts
describe('readFileFirst', ()=>{
    it('readfile',()=>{
        cy.readFile('fixtures/blup.json').then(blub=> cy.log(blub)); // this logs null
        Cypress.Promise.all([]).then(() => {
            cy.log("lol")
        })
    });
})
describe(fixtureFirst', ()=>{
    it('readfile',()=>{
        cy.fixture('blup').then(blup=>cy.log(blup)) // this logs null too
        Cypress.Promise.all([]).then(() => {
            cy.log("lol")
        })
    });
})
describe('readFileNotFirst', ()=>{
    it('readfile',()=>{
        cy.wait(1);
        cy.readFile('fixtures/blup.json').then(blub=> cy.log(blub)); // this logs the blub content
        Cypress.Promise.all([]).then(() => {
            cy.log("lol")
        })
    });
})
describe(fixtureNotFirst', ()=>{
    it('readfile',()=>{
        cy.wait(1);
        cy.fixture('blup').then(blup=>cy.log(blup)) // this logs the blub content
        Cypress.Promise.all([]).then(() => {
            cy.log("lol")
        })
    });
})
```

You can use any file with any contend. My `blub.json` contains `{"say": " blub"}`

### Cypress Version

9.5.3

**Comment by flotwig** [comment]
@Im-a-Train `cy` `Chainable`s are not `Promise`s, so I'm not surprised you're seeing strange behavior here: https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#The-Cypress-Command-Queue

There is a highly desired feature request to make `Chainables` `Promises`: https://github.com/cypress-io/cypress/issues/1417

The main functional difference between a regular `Promise` and a `Chainable` is that the chainables are designed to run in order (in the "command queue") to encourage deterministic test writing. Each chainable will run in the order it was called after the previous chainable finishes running.

`Cypress.Promise.all` is just `Bluebird.all`, so it shouldn't have any special behavior. I suspect that if you insert your `Promise.all()` promise into the command chain using [`cy.wrap()`](https://on.cypress.io/wrap), it will work as you expect, since the promise will be awaited before any commands are run:

```js
cy.wrap(Promise.all(...))
```

Let me know if this is helpful. I know this experience is confusing. You could possibly simplify your implementation by moving the fixture-combining logic to a [`cy.task()`](https://on.cypress.io/task).
