### ISSUE TITLE
"fullPage" Screenshot inconsistent / wrong stitching

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#2175]
### Current behavior:

This screenshot compares 2 images taken from 2 runs on the same environment. They are both full page. there was no other changes between runs.

![image](https://user-images.githubusercontent.com/2848185/42945056-5b896092-8b35-11e8-9e9d-06cf4be689a3.png)

### Desired behavior:

It would be better if the `fullPage` could always be captured like the below screenshot. However, from one `run` to the next, it can be *inconsistent*, sometimes looking good, sometimes looking not so good. At least it should be consistent, if not perfect, so that we are not at risk for false negatives when diffing.

### Steps to reproduce:

compare full page screenshots from one run to the next and observe their inconsistency.

### Versions

 cypress 3.0.2, circleCI linux

Note: A nice feature would be to have better control over the "viewport" size of the headless test runner so that we could take longer/wider screenshots, rather than relying on a algorithm that cannot perfectly replicate with accuracy what users see.

**Comment by maple-leaf** [comment]
I can confirm this issue exists and happens very often. It seems like the algorithm that hide others and use helper pixels doesn't works well.
I don't know this would be possible, but can we run spec on cypress and take screenshot on puppeteer with headless chrome?

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
