### ISSUE TITLE
Dashboard cases sum incorrect

### ISSUE THREAD

**Issue by chaitanyajoy** [cypress-io/cypress#21875]
### Current behavior

The sum of passed, failed, pending, and skipped cases **is not equal** to the total number of cases

### Desired behavior

The sum of passed, failed, pending, and skipped cases **should be equal** to the total number of cases

<img width="769" alt="Screenshot 2022-05-30 at 4 36 30 PM" src="https://user-images.githubusercontent.com/53746340/170980298-e06c60ef-c011-4f74-8e46-248277be9652.png">

### Test code to reproduce
Go to cypress dashboard
checkout the case summary card

### Cypress Version

8.4.1

**Comment by conversaShawn** [comment]
@chaitanyajoy Happy to investigate. Can you confirm the tests add up once the run is completed? Is it possible to provide a link to the run?

**Comment by conversaShawn** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
