### ISSUE TITLE
Not Reseting Map and Array object variable after every run

### ISSUE THREAD

**Issue by varshanharshank** [cypress-io/cypress#21987]
### Current behavior

Running the test cases using cucumber BDD style. Map and Array object variable are holding the previous test values and it is not resetting during second and subsequent test

    Scenario Outline: Login functionality
        Given hit the inventory url
        When enter login information "<userName>" and "<password>"
        Then verify user successfully logged to the application
        Examples:
            | userName | password |
            | user1    | welcome1 |
            | user2    | welcome2 |
            | user3    | welcome3 |

In the above scenario, 
1. I am storing the userName and password in Map object as global variable (key as userName and value as password)
2. I am storing userName in Array Object as global variable

Created the Map and array Object as below

**export const userMap = new Map<string, string>()
export let userArray: string[] = []**

**Note**: created the Map and array object globally for retrieve this value from other function

In the first run ,map and array size is showing as 1. 
In second run map and array size is showing as 2 
third run map and array size is showing as 3. 

It means, After every run, Map and array object is not clearing automatically. Instead it is retaining the old values

### Desired behavior

After storing value and verifying the Map size (every run it should show Map size is 1)
After storing value and verifying the Array size (every run it should show Map size is 1)

### Test code to reproduce

I am unable to provide the test code here.

### Cypress Version

9.7

**Comment by KittyGiraudel** [comment]
Considering you’re using global variables, that seems okay to me that they don’t get automatically reset for you? If you want to reset them, you can do so in the `beforeEach` hook, can’t you?

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
