### ISSUE TITLE
Only the first Set-Cookie in response header is handled

### ISSUE THREAD

**Issue by Far3t** [cypress-io/cypress#2213]
### Current behavior:

I have a login request in my app setting multiple cookies with Set-Cookie in response header, and when using cypress, I can see that there is only one which has been set.

`Set-Cookie: remember_token=5b56f2475e4fd43e29af88f5|d306269868c30bd9c05dff29c40f80a316ba9f3b89a2411eec828acd7727ee20f33343855a4bf9d6057566d3caeffc450d609e92959bcd13ed51dae61083c924; Expires=Fri, 26-Jul-2019 11:56:48 GMT; Path=/
Set-Cookie: session=7214d946e7d432a2_5b5990f8.Z070v-xcY5DkeZtO9hpIqMUtZiM; Domain=.***.com; HttpOnly; Path=/`

And getCookies will tell us:
`[{domain: "localhost", expiry: 1564142368.196979, httpOnly: false, name: "remember_token", path: "/", secure: false, value: "5b56f2475e4fd43e29af88f5|e6fd9605b6972dfc04c4d72a3f2053aa9629973154580f181f048cc123eb203d35f364d1e0d67130a868f2e10adefe9fe69ed845e9cd48f81a1fec129834b370"}]
`

### Desired behavior:

Handle multiple Set-Cookie in response header

### Steps to reproduce:

Having a response setting multiple cookies, and check whith cypress the cookies after that request

### Versions

OS: Debian 9.4
Cypress: 3.0.2

**Comment by aepplerplangrid** [comment]
I'm having this issue as well, making a request and two cookies are set in the response but when made via cypress only 1 cookie is set

**Comment by d0n0tdisturb** [comment]
same issue, I have 2 cookies in response but only the first one is set by cypress

**Comment by rbpaul2** [comment]
same issue

**Comment by jennifer-shehane** [comment]
Can anyone provide a reproducible example we can run to see this behavior?

**Comment by Far3t** [comment]
Well, I made a small test with an Express server sending 2 cookies, it was working with Cypress v3.1.2
I decided to test it into my big app and it is working now.
I didn't touch anything on the management of the cookies in my app and everything runs fine now with Cypress 3.1.2.

Maybe, others stil have errors?

**Comment by jennifer-shehane** [comment]
@Far3t We did include some cookie fixes into Cypress recently. 

@rbpaul2, @d0n0tdisturb, @aepplerplangrid can any of you confirm this is now working in Cypress version >3.1.2?

**Comment by Jeevan-Kishore** [comment]
@jennifer-shehane 

As of version 3.2.0, the issue seems to remains the same.

To add bits to the above, 

Our server responds with multiple `Set-Cookie` headers, the first one seems to get picked up by cypress and the other ignored.

We are sort of blocked on this as we are unable to automate our login systems,

I've attached a of screenshot of the same,

<img width="752" alt="Screenshot 2019-04-02 at 8 42 42 PM" src="https://user-images.githubusercontent.com/19756463/55414156-4438d800-5588-11e9-9b0d-2f82f8278ea5.png">

on the applications tab,

<img width="661" alt="Screenshot 2019-04-02 at 8 50 56 PM" src="https://user-images.githubusercontent.com/19756463/55414589-08524280-5589-11e9-808d-d503b70cc96f.png">


Hope this helps investigate.

**Comment by jennifer-shehane** [comment]
Closing as resolved. Please comment if you are still having this issue and we will consider reopening.
