### ISSUE TITLE
Cypress 10 keeps logging me out of my company network VPN

### ISSUE THREAD

**Issue by shahbazqa** [cypress-io/cypress#22148]
### Current behavior

Hi, 

I just recently upgraded to Cypress Version 10, and am noticing every time I run 1 or 2 tests, my internet and VPN disconnects. There seems to be some new proxy that Cypress 10 is creating which is making my VPN disconnect and then i have to restart the whole computer then it works again. But in this my tests are unable to run and I am at a road block. Is Cypress 10 creating a new proxy?  

### Desired behavior

It should run smoothly and VPN and intenet should still work if tests are executed within the Cypress Test runner. 

### Test code to reproduce

![image](https://user-images.githubusercontent.com/64419960/172244779-2d371aee-bd62-4527-af46-edf5bc757499.png)

### Cypress Version

10.03

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
