### ISSUE TITLE
Unable to use the Chrome Extension Properly

### ISSUE THREAD

**Issue by zqy1001** [cypress-io/cypress#22170]
### Current behavior

On Chrome Version 102.0.5005.63 (Official Build) (64-bit)

My organisation has added GUID caljajdfkjjjdehjdoimjkkakekklcck to allow Cypress Chrome extension. 
In VS code terminal execute "cypress open" then popup the UI, select "Chrome 102" as the browser then run tests. 
A chrome instance be fired but leave it blank not running any tests on it
![cypress blank page](https://user-images.githubusercontent.com/32744150/172434942-24c3599d-c50e-4d66-93aa-a576b4ad1603.JPG)
.

### Cypress Version

9.7

### Package Manager

npm

### Operating system

Windows

**Comment by AtofStryker** [comment]
Hey @zqy1001. I am guessing your chrome instance is corporate controlled? Do you have this issue with other browsers? Our guess is that something is likely blocking the extension similar to #8750 and #6889. Is this a new issue or were you able to run chrome with Cypress in the past?

**Comment by zqy1001** [comment]
Hi @AtofStryker , thanks for your quick response. 
Yes my Chrome instance is corporate controlled. I was able to run the tests on Chrome till few months back then the company implemented new restriction to Chrome extension then it stop working,
I have asked the admin added GUID caljajdfkjjjdehjdoimjkkakekklcck to allow cypress extension but it doesn't work.

Meanwhile I have no issue on other browsers (Electron, Firefox). This only happen when on Chrome.

Thanks

**Comment by zqy1001** [comment]
![CypressExtensionBlocked](https://user-images.githubusercontent.com/32744150/172623290-8d016150-a24d-40d8-b06e-7afcd434177e.JPG)

**Comment by zqy1001** [comment]
This is how my company admin set the registry for allowing Cypress extension. Is this the right way to do so?
![RegistryKey-GUID](https://user-images.githubusercontent.com/32744150/172637850-316dc11c-5b19-487e-a4c0-fdfb7184143d.png)

**Comment by AtofStryker** [comment]
Hey @zqy1001. My guess is the extension allowlist isn't configured correctly and it might be difficult to nail that down. Is there a way your company would allow for you to use a version of chrome that is not corporate controlled?  Otherwise and unfortunately, without some type of reproducible code on my end, I think we would have to possibly close the issue to prevent going down a rabbit hole.

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
