### ISSUE TITLE
Clicking on the download button leads to an infinitely long loading time ("Pdf is loading..)

### ISSUE THREAD

**Issue by tuimai** [cypress-io/cypress#22183]
### Current behavior

Normally, when you click the button in the form, a PDF is downloaded without having to confirm this. When I want to test in Cypress whether the PDF is being downloaded, clicking the button leads to an infinitely long loading time (On the button is wriiten: "PDF is loading..."), but the PDF is never downloaded and the Cypress test also does not fail.

Why isn't the PDF downloaded with Cypress?

### Test code to reproduce

    it('download file',  () => {
        cy.get('Download-button').click();

<button _ngcontent-serverapp-c67="" type="button" class="btn download-pdf color-white ng-star-inserted">
<span _ngcontent-serverapp-c67=""> PDF herunterladen </span></button>

### Cypress Version

ex. 9.6.0

**Comment by marktnoonan** [comment]
Please provide some more information about this issue so that we can confirm if this is an issue in Cypress itself or something to do with your application.

Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
