### ISSUE TITLE
After Continue, the Migration Helper keep eternal loading

### ISSUE THREAD

**Issue by ronycandeli** [cypress-io/cypress#22204]
### Current behavior

![image](https://user-images.githubusercontent.com/542746/172705573-2689d6ce-e277-453c-aa56-0a3276cfc8a7.png)
After Continue the Migration Helper keep eternal loading

### Desired behavior

I want use, but keep loading on Migration Helper

### Test code to reproduce

plugins/index.js
```
module.exports = (on, config) => {
  require('@cypress/code-coverage/task')(on, config)
 
  return config
}
```

support/index.js
```
require('cypress-plugin-tab')
   
import './commands'
 

import '@cypress/code-coverage/support'


Cypress.on("uncaught:exception", err => !err.message.includes("ResizeObserver"));
```

### Cypress Version

10.0.3

### Other

$ npx cypress version
Cypress package version: 10.0.3
Cypress binary version: 10.0.3
Electron version: 18.0.4
Bundled Node version:
16.13.2

**Comment by lmiller1990** [comment]
Can you share your `package.json`? I wonder if upgrading to the latest [code coverage](https://www.npmjs.com/package/@cypress/code-coverage) would help -- the latest was 12 days ago, which has some tweaks for Cypress 10.

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
