### ISSUE TITLE
After Update of "Apple M1 Pro" OS to version 12.4 cypress started not to run!!! and i see error in terminal => spawn Unknown system error -86

### ISSUE THREAD

**Issue by mhersim** [cypress-io/cypress#22200]
### Current behavior

After Update of "Apple M1 Pro" OS to version 12.4 cypress started not to run!!!
bash-3.2$ npx cypress open --config-file cypress.env.json
It looks like this is your first time using Cypress: 9.7.0

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command failed with Unknown system error -86: /Users/user/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=162
spawn Unknown system error -86

----------

Platform: darwin-x64 (21.5.0)
Cypress Version: 9.7.0

### Desired behavior

Opens cypress

### Test code to reproduce

no test code

### Cypress Version

9.7.0

**Comment by rachelruderman** [comment]
Hi @mhersim, thanks for reporting this issue! I consulted with the team and the response is
> I believe this is the error you get when you try to run an x64 program on arm64 without Rosetta. For some users it prompts to install Rosetta, for others it just fails, no idea why. They can try to install Rosetta and see if it goes away

Here's a support article on [how to install Rosetta](https://support.apple.com/en-us/HT211861). Please let me know if this helps 🙂

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
