### ISSUE TITLE
Test Isolation

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#22230]
Updated to reflect latest design decisions: 
There will be two modes of test isolation, `on` and `off`, with `on` being the new default mode.  When test isolation is `on`, before each test, Cypress will:

- clear the page by visiting `about:blank`
- clear cookies
- clear local storage
- clear browser storage

When test isolation is `off`, Cypress will not clear the browser context or the page.

**Comment by mjhenkes** [comment]
We need to break this issue up into smaller issues before we assign it out.

**Comment by emilyrohrbough** [comment]
Here's the work I have identified.



## Driver code that handles resets before a test runs:
Identified `test:before:run`and `test:before:run:async` hooks. these are currently set per-command / throughout the code and there is not a singular place where these are all called at once due to triggering when a event is heard.
  - runner:test:before:run
    - calls cy.reset which caches the window, document, autIframe, specWindow and activeSessions before resetting state and re-applying the cache. Queue is reset & cleared. Time is reset. test config overrides are removed. All listeners are removed. 
    - sets mocha timeout for runnable
    - 
  - test:before:run (happens first)
    - agents - resets spy & stub & children count and restores sinon global sandbox
    - clock - calls reset which uninstalls `@sinonjs/fake-timers` (prev issue to ensure is fine- https://github.com/cypress-io/cypress/issues/2850)
    - net stubbing - routes / aliasedRequest thought I think the runner.ts / cy.ts wipes cypress state and clears this for us already
    - proxy-logging - ends all logs for proxyRequests that had not received a response then reset unloggedPreRequests, proxyRequests and unmatchedXhrLogs
    - 	local_storage

  - test:before:run:async (happens first)
    - cookies - tied to sessions flag - clears cookies
    - sessions v- tied to sessions flag (obv) - this is the blank page between tests
  
  - any side effects on plugins leveraging these? Likely no today. Opt in to ignore later

## Buckets of work

EDIT: 6/23/2022 Updated to reflect issues related to the work break down.

1. add root-/describe-level configuration option to enable/disable about:blank page reload between tests #22279 
  - Work: add `testIsolation` configuration option 
    - attributes: `canUpdateDuringTestTime=false`, `specificTestingType=e2e`
    - desire is to have `testIsolation=true` Will need to release as `false` (unless `experimentalSessionAndOrigin=true`) and be a breaking change to move to `true`.
    - OR alternative is to strip out configuration option unless `experimentalSessionAndOrigin=true` then use `true` by default or honor the defined value.
  - Result: provide parity with current test resets between tests when `experimentalSessionAndOrigin=false`
  - describe-level config option - do not allow setting at the test-level
    - update testConfigOverrides to maintain if test override is a test or describe level override
    - update resolvedOptions in npm/config/options to indicate if it's attributes have both `canUpdateDuringTestTime` and `runnableType` === 'suite'. The (mocha) runnable types are suite & test.
    - expand testTime error message to include information on the test-level supported
      - error will be thrown from npm/packages/cypress/src/cypress.ts (prox line 222) within configure() where this.config is set
    - add `testIsolation` configuration option - `canUpdateDuringTestTime=true`, `specificTestingType=e2e`
      - desire is to have `testIsolation=true` Will need to release as `false` (unless `experimentalSessionAndOrigin=true`) and be a breaking change to move to `true`.
      - alternative is to strip out configuration option unless `experimentalSessionAndOrigin=true` then use `true` by default or honor the defined value.
     changed needed to manage if configuration option is allowed at it-level and throw error if not.

2. UI icon to determine if testIsolation was on/off https://github.com/cypress-io/cypress/issues/22482

3. aliases are reset between each test and are not recommended to be set in before hooks. (see docs) so persisting alisas set in before's changes the current recommendation/behavior in Cypress. Need to determine if we truly want to take this work on and will need to cross-reference how this might impact or be impacted by the detached dom work Blue is working on. https://github.com/cypress-io/cypress/issues/22484

4. persist clock state https://github.com/cypress-io/cypress/issues/22485

5. persist intercepts state (routes and intercept) https://github.com/cypress-io/cypress/issues/22486

**Comment by emilyrohrbough** [comment]
@nagash77 we also need to consider resetting `cy.viewport()`.

**Comment by emilyrohrbough** [comment]
#24206 will close this issue with recent discussions on how test isolation is defined.

There will be two modes of test isolation, `on` and `off`, with `on` being the new default mode.  When test isolation is `on`, before each test, Cypress will:

- clear the page by visiting `about:blank`
- clear cookies
- clear local storage
- clear browser storage

When test isolation is `off`, Cypress will not clear the browser context or the page.

**Comment by emilyrohrbough** [comment]
Issues fixed by test isolation:
- https://github.com/cypress-io/cypress/issues/413
- https://github.com/cypress-io/cypress/issues/461
- https://github.com/cypress-io/cypress/issues/1083
- https://github.com/cypress-io/cypress/issues/5510
- https://github.com/cypress-io/cypress/issues/15247
- https://github.com/cypress-io/cypress/issues/16935
- https://github.com/cypress-io/cypress/issues/17174
- https://github.com/cypress-io/cypress/issues/17585
- https://github.com/cypress-io/cypress/issues/18874
- https://github.com/cypress-io/cypress/issues/18475

**Comment by piotrpalek** [comment]
Are there plans to clear `cy.intercept` calls between tests? I'm using Cypress mostly for component testing, and it'd be desirable if I can set different interceptors per test instead of them "leaking over" to the next, and being hard to override

**Comment by emilyrohrbough** [comment]
@piotrpalek EDIT:  I just ran a more verbose example set per https://github.com/cypress-io/cypress/issues/20397, and it does not seem that Test Isolation does not completely resolves the intercept bleed-over. I ran this snippet:
```js
for(let i = 0; i < 1000; i++) {
    it('can wait on a single request using "alias.request"', function () {
        cy.intercept('/foo*')
        .as('foo.bar')
        .then(() => {
        Cypress.$.get('/foo')
        })
        .wait('@foo.bar.request')
    })

    it('can timeout waiting on a single request using "alias.request"', function (done) {
        cy.on('fail', (err) => {
            expect(err.message).to.contain('No request ever occurred.')
            done()
        })

        cy.intercept('/foo*')
        .as('foo.bar')
        .wait('@foo.bar.request', { timeout: 100 })
    })
}
```
Which produced 2000 tests cases. And there were 15 failures (about 0.75% fail rate) . Leaving https://github.com/cypress-io/cypress/issues/20397 open as unresolved. We can have further conversations there.

**Comment by emilyrohrbough** [comment]
The work related to Test Isolation has been completed. This will be released with Cypress 12.
