### ISSUE TITLE
Changed precedence of config loading in Cypress 10

### ISSUE THREAD

**Issue by aommm** [cypress-io/cypress#22245]
### Current behavior

Hi!

In Cypress 10, `CYPRESS_baseUrl=x` takes precedence over `--config baseUrl=x` when loading configuration.

```
> CYPRESS_baseUrl=http://fail.com npx cypress run --config baseUrl=http://google.com
# test runs with http://fail.com
```

### Desired behavior

This is the behaviour in Cypress 9:
```
> CYPRESS_baseUrl=http://fail.com npx cypress run --config baseUrl=http://google.com
# test runs with http://google.com
```

### Test code to reproduce

https://github.com/aommm/cypress-bug-2
To prep the repo:
```
cd cypress9
npm install
cd ../cypress10
npm install
cd ..
```
Working in Cypress 9 ✅ :
```
./cypress9-works.sh
```
Failing in Cypress 10 ❌ :
```
./cypress10-fails.sh
```

### Cypress Version

10.0.3

### Other

Is this change intended? By default I would say "less change = good" 🙂 
I couldn't spot it in the changelog but I might have missed it.

**Comment by lmiller1990** [comment]
Hi! If it's not in the change log, I'd say it's unintended. We did change some config options like `testFiles` -> `specPattern`, but the loading precedence should be the same. We should fix this, sounds like a bug.

**Comment by rachelruderman** [comment]
Test code to repro is in the issue description, ready to route 🙂

**Comment by marktnoonan** [comment]
Let's test #22261 again when this loading precedence issue is addressed, I think it's a duplicate of the same general issue, but referring to the passing `specPattern` instead of `baseUrl`.

**Comment by lmiller1990** [comment]
Also: https://github.com/cypress-io/cypress/issues/22430 (same core issue around precedence).

**Comment by lmiller1990** [comment]
For ref, resolved order of config here: https://docs.cypress.io/guides/references/configuration#Resolved-Configuration

**Comment by fs-jake** [comment]
Hi there, we are running into a bug with this after Cypress v10 as well. We have a custom `url-config.js` file that is used to dynamically set the base URL for various environments. We were importing this file into our `commands.js` file and using the dynamic URL variable in one of our custom commands. Prior to Cypress v10, the variable was getting read in correctly. However, after Cypress v10, the variable is not getting the correct value I'm assuming due to a change in precedence.
