### ISSUE TITLE
Intercept Rout Matcher doesn't work properly

### ISSUE THREAD

**Issue by elshafey** [cypress-io/cypress#22277]
### Current behavior

- the targeted url has the following uri `/api/employer/unread-suggested-apps?sort=-createdAt&include=employerUser,talentApplication.talentUser,talentApplication.lookupOpportunityFolder,talentApplication.applicationScore,talentApplication.opportunity.createdBy,talentApplication.opportunity.company,talentApplication.opportunity.opportunityWorkTypes.workType,talentApplication.opportunity.opportunityFolderSetup.lookupOpportunityFolder&page[offset]=0&page[limit]=40`

using the following code:
`cy.intercept(
            {
                url: "/api/employer/unread-suggested-apps"
            }
        ).as('api')`

no urls are matched 

### Desired behavior

the url should be matched

### Test code to reproduce

```
cy.intercept(
{
    url: "/api/employer/unread-suggested-apps"
}
).as('api')

cy.visit('url-that-load-the-page')
```

### Cypress Version

10.0.3

**Comment by rachelruderman** [comment]
Hi @elshafey , thanks for reaching out! In the [cy.intercept documentation](https://docs.cypress.io/api/commands/intercept#Matching-url), you'll see you can use exact, glob, or pattern matching for the `url` property. 

The way you have it set up, `url: "/api/employer/unread-suggested-apps"` is looking for an exact match. 

Try updating to `url: "/api/employer/unread-suggested-apps?**` so that it's using a glob pattern. This way, it will match any URL that starts with `/api/employer/unread-suggested-apps?`. Please let me know if this helps 😃

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
