### ISSUE TITLE
snapshot are not getting generated in nonheaded mode of mocha report

### ISSUE THREAD

**Issue by M-Jyothi** [cypress-io/cypress#22274]
### Current behavior

I am seeing that the snapshots are not getting generated when I run the cypress in non headed mode

### Test code to reproduce

 i,e without mentioning as  headed only if we mention as headed is the snapshot generated for failed test cases other wise not kindly help

### Cypress Version

9.6

**Comment by AtofStryker** [comment]
Hey @M-Jyothi. Thank you for opening an issue. This is actually expected behavior as we do not take snapshots in [headless mode](https://github.com/cypress-io/cypress/blob/v9.6.0/packages/driver/src/cypress/log.ts#L339). Could you provide what you are trying to accomplish that requires snapshots in headless mode?

**Comment by M-Jyothi** [comment]
Hey thankyou so much for your reply , I was in progress of establishing cicd for cypress automations and saw that we are not able to get reports when we tried headless mode of invoking spec file . thank you for your clarifications
