### ISSUE TITLE
Add new testIsolation configuration option

### ISSUE THREAD

**Issue by vergjor** [cypress-io/cypress#22279]
### What would you like?

What I would suggest to be improved is when we are using the `cy.session()` command or to be more specific `experimentalSessionAndOrigin=true`, currently the state between the tests within one cy/spec file is cleaned and we need to reset everything, but when we do not use this flag the state is kept and we can link together some tests. 
It would be great to be able to keep the state as we do without the flag and not set the page url to `_blank_`

### Why is this needed?

This would save a lot of execution time for tests where we do need to stay on the same page, or depend on some setup from the previous test where instead of logging in, setting everything up again, we can just continue where we left off (like we do when `experimentalSessionAndOrigin` is false)

**Comment by jnsrnhld** [comment]
Totally agree on this. I have to test a long chain of forms and with the new session behavior I have to slam all assertions and actions into one huge test or the setup effort for each test gets huge. 

I suggest, for example, to add a flag to the spec context that enables to stay on the current page instead of starting with a blank page for each test. So the new behavior can be kept, but the old can still be enabled via a flag.

**Comment by vergjor** [comment]
> Totally agree on this. I have to test a long chain of forms and with the new session behavior I have to slam all assertions and actions into one huge test or the setup effort for each test gets huge.
> 
> I suggest, for example, to add a flag to the spec context that enables to stay on the current page instead of starting with a blank page for each test. So the new behavior can be kept, but the old can still be enabled via a flag.

I agree, plus when we use cy.session() and we add a validation for the session like in my case by trying to open a specific page that is only accessible if the user is logged in, then I would have to use:

```ts
    validate() {
      cy.visit('/');
      cy.location('pathname', { timeout: 30000 }).should('equals', '/home');
    },
```

and this is the only way I can validate the login for our application. Then after the session we need to again use cy.visit() to navigate to the home page which is again extra time to re-load everything instead of just continuing from the validation or login state.. removing the blank page part would be amazing

**Comment by emilyrohrbough** [comment]
Test isolation is writing tests such that tests to no rely on the test before it. Clearing the page and setting the url to `about:blank` is one mechanism Cypress used to ensure test isolation.  This behavior allows each test to have a clean slate without app state leaking, whether initially or unexpectedly, into the next test.

In general, we recommend writing tests that do no rely on each other, but with this said, we recognized there are use-cases where clearing the app's current state is undesirable.

The request to add a new configuration option to opt-out of test isolation when `experimentalSessionAndOrigin=tru` has been taken into consideration. There are plans to add a new configuration optional which will give you the flexibility to turn this behavior off.

@vergjor Can you create a separate issue to discuss your request to remove the clear page after the session validation is ran? We need evaluate it independently since it alters the existing behaviors of the `cy.session()` command.

**Comment by vergjor** [comment]
> Test isolation is writing tests such that tests to no rely on the test before it. Clearing the page and setting the url to `about:blank` is one mechanism Cypress used to ensure test isolation. This behavior allows each test to have a clean slate without app state leaking, whether initially or unexpectedly, into the next test.
> 
> In general, we recommend writing tests that do no rely on each other, but with this said, we recognized there are use-cases where clearing the app's current state is undesirable.
> 
> The request to add a new configuration option to opt-out of test isolation when `experimentalSessionAndOrigin=true` has been taken into consideration. There are plans to add a new configuration optional which will give you the flexibility to turn this behavior off.
> 
> @vergjor Can you create a separate issue to discuss your request to remove the clear page after the session validation is ran? We need evaluate it independently since it alters the existing behaviors of the `cy.session()` command.

I do agree that we should strive to have an isolation between test cases, but yeah I would also say that having that optional configuration would be a massive advantage for some of the special cases where we would want to have depended cases.

@emilyrohrbough thank you for the suggestion and feedback! I created the new issue: https://github.com/cypress-io/cypress/issues/22368
