### ISSUE TITLE
I really miss full path in spec names in cy run report

### ISSUE THREAD

**Issue by Threnos** [cypress-io/cypress#22304]
### What would you like?

To have option to enable full path with spec name (e.g. AP/admin/customers/informationBar.ts) like it used to be before version 10, insted of just spec name (informationBar.cy.ts). Setting in cypress.config.ts would be ideal.

### Why is this needed?

I have large number of specs with identical names which are scattered over dozens of folders. Now cy run report is almost useless to me - I cannot tell whether AP/admin/customers/informationBar.ts failed or was it Vendor/responseRepresentative/informationBar.cy.ts

**Comment by jennifer-shehane** [comment]
@Threnos Which 'run report' are you referring to? Are you talking about the running during `cypress open`? The output during `cypress run`? A custom reporter you've set up? Where are you seeing this specfile name being different exactly?

**Comment by Threnos** [comment]
When you have 100+ specs you eventually come to this method of organizing tests. Otherwise, you end up with ridiculously long spec names.

**Comment by gvocale** [comment]
+1 for old way displaying full path

**Comment by Doomsby** [comment]
An option for displaying the full path would be very helpful for us as well.

**Comment by lmiller1990** [comment]
This seems like a pretty nice feature. Just posting to let others know opinions posted here don't go into a void, we look, assess, and act on them - it just takes a bit of time, since any change should be carefully considered (this one was, too, but evidently it may not have been considered enough). 

My personal use case: when a spec fails, I copy the path and paste to `cmd + p` in VS Code to go there. It's a bit more tricky now - all my specs are uniqely named, so it's not a problem in my specific use case, but this workflow wouldn't work on some code bases where everything is names `index.spec.js`, etc.

**Comment by Narretz** [comment]
I would also like to see the old behavior. I assume the full path is problematic when you have very deeply nested tests., but I would guess the nesting is usually no that deep. What would be cool: an easier way to customize the output of cypress run in general, especially the big result table.

**Comment by melibe23** [comment]
Oh, boy, I thought it was me! This is a feature of V10? Did someone find a way to customise this and have the full path back? I have more than 100 scripts and I organise them in type of tests (seo, ga, functional, visual), i have no idea what has been ran if I dont see the folder. 

+1 to bring this back or be able to customize it. I will add this to the list of reasons not to migrate to version 10.

**Comment by lmiller1990** [comment]
I agree we should do this, the full spec path definitely gives more context and is more useful - I will raise this internally.

**Comment by Narretz** [comment]
thanks @lmiller1990! I drafted a PR a while ago: https://github.com/cypress-io/cypress/pull/22930

It needs a bit more than these two changes, though

**Comment by lmiller1990** [comment]
One of the main challenges of this PR will be updating literally thousands of snapshots, eg: https://github.com/cypress-io/cypress/blob/develop/system-tests/__snapshots__/base_url_spec.js#L116 (not a big deal, just will take a while - running the entire suite locally to update the snapshots takes an very long time).

I think the reason this changed is as follows (for context and for whomever is going to work on this):

- In Cypress 9, you might have `cypress/integration/foo.spec.js`. `integrationFolder` is `cypress/integration`.
- Videos/screenshots would go to `cypress/videos/foo.spec.js.mp4`. Basically `spec.replace(integrationFolder, videosFolder)`.
- When Cypress 10 merged `integrationFolder` and `testFiles` into a single `specPattern`, this changed. Since we wanted artefacts to stay in the same place, we implemented something to "remove" the common root path, which would be `cypress/integrationFolder` - akin to removing `integrationFolder`. You are then left with `foo.spec.js`. This is called the `baseName` of the spec in the code base. The recording then goes to `cypress/videos/<spec>.mp4`.

The side effect is the `baseName` is also used for the CLI output. You correctly identified this and made the change: https://github.com/cypress-io/cypress/pull/22930/files#diff-58fd4a8e28c13b52b19c42346eade66ed1de5a8b139541dff4e94fef42c3c701L1336.

I am not sure if this will have any side effects, I'll find out - maybe your PR is all we need.

**Comment by Narretz** [comment]
Thanks for the write-up @lmiller1990!

If we do only the change in the PR, the spec names will look like this:

`cypress/integration/reports/barChartReport/card_spec.ts`

assuming your specPattern is e.g. `cypress/integration/**/*_spec.ts`

Which is a bit noisy, because the common root of the paths isn't interesting. I think we should identify the common root of all specs and strip it from the spec names. Something like this already happens in run.js in a different context.

**Comment by lmiller1990** [comment]
Ok so we have a property called `relativeToCommonRoot`. Given

- `nested-1/nested-2/nested-3/foo.js`
- `nested-1/nested-2/nested-3/spec.js`
- `nested-1/nested-2/nested-3/nested-4/spec.js`

`relativeToCommonRoot` is 

- `foo.js`
- `spec.js`
- `nested-4/spec.js`

Because `nested-1/nested-2/nested-3` is the common root. I think this is what we want.

## Before

```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  cypress/e2e/nested-1/nested-2/neste      XX:XX        1        1        -        -        - │
  │    d-3/spec.cy.js                                                                              │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  cypress/e2e/nested-1/nested-2/neste      XX:XX        1        1        -        -        - │
  │    d-3/stdout_specfile.cy.js                                                                   │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  cypress/e2e/nested-1/nested-2/neste      XX:XX        1        1        -        -        - │
  │    d-3/stdout_specfile_display_spec_wi                                                         │
  │    th_a_really_long_name_that_never_ha                                                         │
  │    s_a_line_break_or_new_line.cy.js                                                            │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  cypress/e2e/nested-1/nested-2/neste      XX:XX        1        1        -        -        - │
  │    d-3/nested-4/spec.cy.js                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        XX:XX        4        4        -        -        -  

```

## After

```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  spec.cy.js                               XX:XX        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  stdout_specfile.cy.js                    XX:XX        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  stdout_specfile_display_spec_with_a      XX:XX        1        1        -        -        - │
  │    _really_long_name_that_never_has_a_                                                         │
  │    line_break_or_new_line.cy.js                                                                │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  nested-4/spec.cy.js                      XX:XX        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        XX:XX        4        4        -        -        -  
```

**Comment by lmiller1990** [comment]
See: https://github.com/cypress-io/cypress/pull/23794

**Comment by lmiller1990** [comment]
#23794 is up for review.
