### ISSUE TITLE
Add a way to disable proxy

### ISSUE THREAD

**Issue by gajus** [cypress-io/cypress#22319]
### What would you like?

According to https://www.cypress.io/blog/2019/05/22/how-we-improved-network-speed-by-300-in-cypress-3-3-0/, Cypress proxies all requests in order to:

* injects a global window.Cypress object that can be used by the application under test to determine if it is running inside of Cypress.
* removes [framebusting](https://en.wikipedia.org/wiki/Framekiller) JavaScript so that Cypress can properly run the applicatin under test within an iframe.
* replaces absolute references to window.top and window.parent to the correct frame reference (since window.top points to Cypress's window instead of the application's window).

However, this comes at a _major_ performance cost.

I would heavily prefer if Cypress did not proxy any requests, but instead provided a way to inject the necessary logic into the main application, e.g. as an NPM package.

### Why is this needed?

This would drastically improve performance and reliability of Cypress tests.

**Comment by csvan** [comment]
I can't overstate what a _massive_ improvement this would be, and I would be more than willing to help work on it. The performance penalty becomes even more pronounced in apps with a large number of chunks and other initial requests. 

Like @gajus suggests it seems _unlikely_ that this cannot be handled inside the runtime environment itself rather than having an entire proxy layer between the browser and network.

**Comment by gajus** [comment]
We are done with Cypress. Letting someone else advocate for this.

**Comment by csvan** [comment]
Sad to hear that @gajus, may I know what you opted for instead? There has been some internal pressure here to move to Playwright (primarily for performance reasons) but we are lobbying hard to stay with Cypress ourselves.

**Comment by gajus** [comment]
Yeah, no, moving away from Cypress to Playwright, while very painful, was the best decision we ever made.
