### ISSUE TITLE
cy.origin doesn't set appropriate url when trying to write items to the local storage

### ISSUE THREAD

**Issue by rnovosad** [cypress-io/cypress#22311]
### Current behavior

Using `accounts.google.com` as the origin in `cy.origin` for a test removes the subdomain from it and leaves only `google.com`

### Desired behavior

`cy.origin` should set an appropriate origin containing both domain and subdomain

### Test code to reproduce

```js
it("base origin is incorrect (@dev)", () => {
  cy.origin("accounts.google.com", () => {
    cy.log(window.origin)
    expect(window.origin).eq("accounts.google.com")
  })
})
```

### Cypress Version

10.1.0

**Comment by mjhenkes** [comment]
@rnovosad, when you're accessing `window` in the test, you're accessing the `window` for the cypress test runner attached to the origin. We only have one per origin which is why it doesn't include the subdomain. If you want to access the `window` of the AUT you can access it through the `cy.window` command.
 
```javascript
  it('base origin is technically correct (@dev)', () => {
    cy.origin('docs.cypress.io', () => {
      expect(window.origin).eq('https://cypress.io')
      cy.visit('https://docs.cypress.io/guides/overview/why-cypress')
      cy.window().then((win) => {
        expect(win.origin).eq('https://docs.cypress.io')
      })
    })
  })
```
What is your usecase with local storage? Are you able to set local storage on the AUT directly? I _think_ local storage is available on the same origin. IE, if local storage is set on cypress.io it's accessible in docs.cypress.io.

**Comment by rnovosad** [comment]
hey @mjhenkes 
seems like I was not using this feature properly.
thank you for a great explanation. it helped a lot. closing the ticket
