### ISSUE TITLE
Cypress cannot find node by text containing BOM

### ISSUE THREAD

**Issue by knpwrs** [cypress-io/cypress#22324]
### Current behavior

Consider a dom node with the following text:

```
\ufefftesting\ufeff\ufeff and stuff
```

The following code does not find anything:

```ts
cy.contains('\ufefftesting\ufeff\ufeff and stuff')
```

Neither does the following code:

```ts
cy.contains('testing and stuff')
```

The following code _does_ work, however:

```ts
cy.get('#target')
  .should((div) => {
    const text = div.text()
    // cy.contains() does not appear to be able to find elements with \ufeff, so we assert manually
    expect(text).to.eq('\ufefftesting\ufeff\ufeff and stuff')
  })
```

### Desired behavior

`cy.contains` should be able to find dom nodes containing BOM (`\ufeff`)

### Test code to reproduce

Repo: https://github.com/knpwrs/cypress-bom-bug

Run `npm test` and observe.

### Cypress Version

10.1.0

**Comment by rachelruderman** [comment]
Hi @knpwrs , thank you for putting together the repro, that's very helpful and much appreciated 😸 

I just wanted to clarify something.. you mentioned
> The following code does not find anything:
`cy.contains('\ufefftesting\ufeff\ufeff and stuff')`
Neither does the following code:
`cy.contains('testing and stuff')`

However when I repro'd, `cy.contains('testing and stuff')` DID succeed. Can you confirm? Thanks!

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
