### ISSUE TITLE
Empty `--spec` parameter error message is misleading for Cypress developers

### ISSUE THREAD

**Issue by sainthkh** [cypress-io/cypress#22328]
### Current behavior

When you don't pass anything after `--spec` like `yarn workspace @packages/launchpad cypress:run:e2e --spec`, it shows the error message like below:

```
No version of Cypress is installed in: /home/sainthkh/.cache/Cypress/0.0.0-development/Cypress

Please reinstall Cypress by running: cypress install

----------

Cypress executable not found at: /home/sainthkh/.cache/Cypress/0.0.0-development/Cypress/Cypress

----------

Platform: linux-x64 (Ubuntu - 20.04)
Cypress Version: 0.0.0-development
```

Cypress is actually installed (or cached in CI). The `--spec` is empty. But the message is really misleading. 

### Desired behavior

Maybe, the message should be changed to `No spec files provided. They should be provided after `--spec` argument`. 

### Test code to reproduce

In our project root, `yarn workspace @packages/launchpad cypress:run:e2e --spec`

### Cypress Version

10.1.0

**Comment by marktnoonan** [comment]
What's happening here seems to be a quirk of how we ensure that in the Cypress repo, we run in dev mode. [This script](https://github.com/cypress-io/cypress/blob/4626f7481c9904fec484aa167a02e0197a3095c4/scripts/cypress.js#L14-L17) runs when `@packages/launchpad cypress:run:e2e` is run.

The issue is not with the `--spec` flag as such. In a regular project the message is fine. `npx cypress run --spec` leads to this:

```
error: option '-s, --spec <spec>' argument missing
```

But within the cypress repo, that last flag ends up _receiving `--dev` as the argument_. I didn't look too closely, but something in the timing of when we push it seems to be an issue. 

Swallowing the `--dev` flag means it no longer prevents the attempt to verify the Cypress binary for the version `0.0.0-development`. There's nothing in the cache to verify at that path, since we aren't working with a binary that was installed, we are working with whatever the current code is in the branch being developed. So Cypress complains, correctly, that you don't have anything at that path. The same thing happens if you leave `--browser` at the end, for example, or any flag that needs an argument. 

This definitely could be better, I'll route this to the team to improve at some point so that it works as expected when developing Cypress, just as is does when using a regular build. But at least for users of Cypress in other projects, this all seems to be working as expected.

**Comment by sainthkh** [comment]
@marktnoonan I added "for Cypress Developers" for clarity.
