### ISSUE TITLE
screenshot() omits specName in `cypress open`

### ISSUE THREAD

**Issue by joergplewe** [cypress-io/cypress#22339]
### Current behavior

When taking a `screenshot("name")`, the image is expected to be in directory `{screenshotsFolder}/{adjustedSpecPath}/{name}.png`

Using `cypress run` this works fine (as in v9).
Using `cypress open`, the `{adjustedSpecPath}` is omitted.

Additionally, the `after:screenshot` event won't contain a `specName`.

### Desired behavior

* `cypress run` and `cypress open` should show the same behaviour.
* `after:screenshot` event should provide a `specName` 

### Test code to reproduce

Repo to reproduce: https://github.com/joergplewe/cypress_screenshot_bug

### Cypress Version

10.1.0

**Comment by joergplewe** [comment]
I verified it happening on Windows(10) and MacOS(12.3).
I also checked that it doesn't happen in Cypress v9.

**Comment by joergplewe** [comment]
May I ask, what is the further process? Will it get fixed? When?

Just for my planning, for we have to wait for that before updating to v10. 

Thanks alot.

**Comment by joergplewe** [comment]
Ping. Will that get fixed?

**Comment by HeneryHawk** [comment]
Hi @rachelruderman 

what is the status on this issue.
I use the plugin `cypress-visual-regression` to test canvas elements which compares screenshots of the elements. The plugin searches the screenshots within `{screenshotsFolder}/{adjustedSpecPath}/{name}.png`, but this fails via `cypress open` due to this issue.

Is there a timeline when this issue is fixed?

**Cypress version:** 10.10.0

Regards

**Comment by rachelruderman** [comment]
Hi @HeneryHawk and @joergplewe, I'm sorry you're experiencing failures due to this bug 😞 Currently this issue is not slated to be worked on by the internal Cypress team. However if this becomes a larger issue for the community we can definitely re-evaluate and escalate. While the Cypress team does not have the bandwidth to address every issue, we always welcome and encourage contributions from the community.

**Comment by gonzocer** [comment]
HI All ,

i was able to do a work around if the intention is to add the screen shot to mochaAwesome.

in the index file you need only to do

_Cypress.on("test:after:run", (test, runnable) => {
    if (test.state === "failed") {
        const screenshot = `assets/${test.title.replaceAll(" ","")}(failed).png`;
        addContext({test}, screenshot)
    }
});_

and the config file you need to rename the file 

 _on('after:screenshot',` (details) => {
        const newPath = path.resolve(`cypress/reports/mochareports/assets/${details.path.split('--')[1].replaceAll(" ", "")}`)
        fs.renameSync(details.path, newPath)
        fs.rmdirSync(path.resolve(`cypress/reports/mochareports/assets/${details.specName}`))
        return { path: newPath }
   })_

this workaround is also solving the issue with the nested folders that is causing the screenshots be broken in the report.

![image](https://user-images.githubusercontent.com/87035593/216755868-f87b0e5c-d0cb-4c47-ad11-98bde2dbe963.png)
