### ISSUE TITLE
before:spec broken?

### ISSUE THREAD

**Issue by ciprianene** [cypress-io/cypress#22360]
### Current behavior

When trying to run a "before:spec" function, nothing happens.

### Test code to reproduce

setupNodeEvents(on, config) {
      on("before:spec", (spec) => {
        console.log("Running before spec: ", { spec });
});
}

(//experimentalInteractiveRunEvents is set to true.)

the log will return empty values for the spec object.

Also logged what's returned by before:run and the spec shows as an empty array.

### Cypress Version

10.1.0

**Comment by rachelruderman** [comment]
Hi @ciprianene , thank you for reporting! I put together [this repo](https://github.com/rachelruderman/investigate-issue-22360) to reproduce your issue. It looks like you found a buggo! 🐛 

<img width="1594" alt="Screen Shot 2022-06-17 at 3 53 09 PM" src="https://user-images.githubusercontent.com/26726429/174392848-9fe9f7d3-0c23-4f30-ad43-6f2024a7377e.png">

**Observed behavior:**
1. `npx cypress open`
2. Click "E2E" -> "Start E2E testing in Chrome"
3. Log appears in terminal with empty string for `name`, `relative`, `absolute` properties. User sees spec list in GUI
4. Run a spec. Log does not appear again despite starting, stopping, or switching specs.

**Expected behavior:**
Log should appear when a spec file is selected, and the values of `spec` should all be populated

**Documentation**
https://docs.cypress.io/api/plugins/before-spec-api#Syntax

**Comment by ShadowLNC** [comment]
Just to add my team's use case here - we are trying to load in some data during test loading (we wrapped Mocha's `it` call with additional data of files to be loaded - `cy.*` is not available until inside the `it` block) and we're passing it to the test via the Cypress config, similar to #22614.

Right now we're loading in all possible required files since we can't get the specific spec during interactive mode, which we anticipate will become a performance bottleneck as our test suite grows (approx 10-15sec per 1000 data files according to my testing).

**Comment by BlueWinds** [comment]
Interesting that this appears to be in open mode only. Investigating now.

```
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  // setupNodeEvents can be defined in either
  // the e2e or component configuration
  experimentalInteractiveRunEvents: true,
  e2e: {
    setupNodeEvents(on, config) {
      on('before:spec', (spec) => {
        console.log(`This is the before:spec event`)
        console.log(spec)
      })

      on('before:run', (info) => {
        console.log(`This is the before:run event`)
        console.log('experimentalInteractiveRunEvents', info.config.experimentalInteractiveRunEvents)
        console.log(info.specs)
      })
    }
  }
})
```

![image](https://user-images.githubusercontent.com/3003404/180032702-a48f4947-97bb-4fbc-b6e1-fb35e163d0a1.png)

This is quite different from run mode, where all information is properly available:

![image](https://user-images.githubusercontent.com/3003404/180031891-c72cf977-df40-42b2-819c-bd57cef1cd13.png)

**Comment by BlueWinds** [comment]
So I'm at a bit of a standstill here. Our docs say that the plugin's before:spec can return a promise which will be awaited. However, my current approach was to tap into mocha events - runner:start and runner:end - and mocha events are synchronous. You can't delay execution based on them.

So my options are...

1. Start over from scratch finding a different approach, taking another 2-3 days on this issue.
2. Make run and open mode behave differently and use two different code paths - in run mode Cypress will wait on your promises, in open mode you cannot. This is literally the worst, having multiple code paths for the same functionality.
3. Breaking change, Make the cypress events match the mocha events (you cannot return promises, they are informational not hooks to adjust Cypress' flow)
4. Make a bigger comment about what I've learned here, unassign myself, go back to working on detached DOM.
