### ISSUE TITLE
Cypress.config('baseUrl', 'someUrl.com') after v10 upgrade

### ISSUE THREAD

**Issue by jasoncarty** [cypress-io/cypress#22374]
### Current behavior

After upgrading to Cypress version 10.1.0 the following is resulting in a Typescript linting error:

```
Cypress.config('baseUrl', 'http://localhost:1234')
// Argument of type '"baseUrl"' is not assignable to parameter of type 'keyof TestConfigOverrides'.ts(2345)
```

### Desired behavior

This error is not shown

### Test code to reproduce

```
Cypress.config('baseUrl', 'http://localhost:1234')
// Argument of type '"baseUrl"' is not assignable to parameter of type 'keyof TestConfigOverrides'.ts(2345)
```

### Cypress Version

10.1.0

**Comment by devhid** [comment]
Also running into the same issue.

**Comment by rmanai** [comment]
I have the same error and t tried to create an extended config file to define specific baseurl but not working (cypress v10.1.0) 

please any solution ?

**Comment by lmiller1990** [comment]
Related (and possibly dup): https://github.com/cypress-io/cypress/issues/22072

As noted. since 10.0 `baseUrl` is now nested inside of `e2e`:

![image](https://user-images.githubusercontent.com/19196536/174920916-025661ce-5277-4c42-93ed-43bfc86a4cf7.png)

Which is why the types are complaining. As noted (https://github.com/cypress-io/cypress/issues/22072#issuecomment-1149914697), we **should** support this, but **only** for e2e testing - not component. We don't know the testingType in the spec, though, so I think we will just need to make the type allowed, and have a runtime error if you try to set `baseUrl` when using component testing.

I tested it out and `Cypress.config('baseUrl', 'http://...')` does work - it's just a typing error. I had a look and I think it's because we do `Omit` on `baseUrl` here: https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts#L3054. I am thinking it's not as simple as just removing that, since we don't want `baseUrl` to be valid inside of `cypess.config.js` > `component` property. I think we want a new interface that is specifically for the `Cypress.config(...)` type.

We will look to fix this one soon - in the meantime, I hate to say it but `ts-ignore` is the only alternative until this fix lands.
