### ISSUE TITLE
When I install @cypress/webpack-dev-server 2.0.0, my Project intall error

### ISSUE THREAD

**Issue by Dante-dan** [cypress-io/cypress#22398]
### Current behavior

When I install `@cypress/webpack-dev-server 2.0.0` in my mono repo produce by Lerna, sub packages install `html-webpack-plugin` throw some Warn.

- yarn: 1.22.18
- lerna: 4.0.0

install warn:

```bash
warning Pattern ["html-webpack-plugin@^5.5.0"] is trying to unpack in the same destination "/Users/taptap/Library/Caches/Yarn/v6/npm-html-webpack-plugin-5-5.5.0-c3911936f57681c1f9f4d8b68c158cd9dfe52f50-integrity/node_modules/html-webpack-plugin-5" as pattern ["html-webpack-plugin-5@npm:html-webpack-plugin@^5"]. This could result in non-deterministic behavior, skipping.
```

and then, I build my package by `yarn build`.  It throw some error:

``` bash
Error: Cannot find module 'html-webpack-plugin'
```

So, i guess the `html-webpack-plugin` have the same destination `html-webpack-plugin-5`.

https://github.com/cypress-io/cypress/blob/1e42ba3c330456d50545511ac1ff799165f7f1f2/npm/webpack-dev-server/package.json#L23

I think the `@cypress/webpack-dev-server` should not rename packages by this way.  It will effect the host project.
 

### Desired behavior

I think the `@cypress/webpack-dev-server` should not rename packages by this way.  It will effect the host project.

### Test code to reproduce

above

### Cypress Version

10.1.0

**Comment by lmiller1990** [comment]
Hi! Interesting, I haven't seen this problem, but all my projects are still on Lerna 3. I will try to reproduce. 

As an aside, you might not need to install `@cypress/webpack-dev-server` anymore. As of v10, we ship it with our binary, so you don't need to install it manually. For example I can do this:

```sh
ls /home/lachlan/.cache/Cypress/10.2.0/Cypress/resources/app/node_modules/ | grep html-webpack
html-webpack-plugin-4
html-webpack-plugin-5
```

Which is where Cypress installs on linux (same idea, different location on other OSes. You can see we ship our own `html-webpack-plugin` here, so the version (hopefully) should not conflict with your local one.

Unless you are looking to configure the dev-server yourself, you might not even to install this package. You can configure it like [this now](https://docs.cypress.io/guides/component-testing/component-framework-configuration#React):

```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  component: {
    devServer: {
      framework: 'create-react-app',
      bundler: 'webpack',
    },
  },
})
```
And we handle the dev-server stuff for you. Would this be an option, or are you looking to do something more customized?

**Comment by lmiller1990** [comment]
I am having trouble reproduction this. Are you able to provide a minimal reproduction with a step-by-step one what to run? I tried to replicate your instructions but no luck - here's my repository: https://github.com/lmiller1990/cypress-issue-22398.

Can look to solve this, but if the alternative (use new configuration, do not install `@cypress/webpack-dev-server` works for you, we might not even need to.

**Comment by Dante-dan** [comment]
Thanks for your answer.

I already remove the `@cypress/webpack-dev-server`, it works for me. And I create [mini repo  to reproduction this](https://github.com/Dante-dan/cypress-issue-22398).  

I think that it will be caused by npm register.

**Comment by lmiller1990** [comment]
Thanks for the reproduction. Just to clarify, everything is okay now?

I'll still look into it, but if my suggestion has unblocked you, that's great to hear.

**Comment by Dante-dan** [comment]
yep, everything is okay

**Comment by wingy3181** [comment]
@lmiller1990 just FYI i faced the same issue when using NX with storybook + cypress component testing (which i just migrated to since NX 14.5 supports component testing)

Found it to be the same root cause as above where there are two copies for each version of html-webpack-plugin within node_modules which are suffixed with the version (See screenshots below)

### BEFORE (working)
![image](https://user-images.githubusercontent.com/1212576/181668615-df0769f7-9ca4-4a27-a881-1e91574aa340.png)

### AFTER (not-working)
![image](https://user-images.githubusercontent.com/1212576/181668658-c2163b0d-5c00-492f-8422-b2be63ff5177.png)

And then storybook fails as it tries to resolve it without the suffix internally......

The hacky workaround I have for now is to just copy the `./node_modules/html-webpack-plugin-4` to `./node_modules/html-webpack-plugin` as a postinstall script

Not sure if there are any other suggestions but that's what i need to do in the short term...

just FYI the dependency tree I have at the moment is (i would have thought having it as a direct dependency instead of transitively would have helped but it does not)

```
my-app
- html-webpack-plugin@^5
- @cypress/webpack-dev-server 2.0.0 
  - html-webpack-plugin-4
  - html-webpack-plugin-5
```

**Comment by lmiller1990** [comment]
@wingy3181 we are working on eliminating the `html-webpack-plugin` entirely - you can follow some progress [in this draft PR](https://github.com/cypress-io/cypress/pull/22736). Once that is done, this should be a non issue.

For now, [see this issue](https://github.com/cypress-io/cypress/issues/22577) - it has the same problem and a few fixes/work-arounds.
