### ISSUE TITLE
Cypress doesn't set cookies on 3xx redirects when they are cleared by the intermediary redirect

### ISSUE THREAD

**Issue by shauvik** [cypress-io/cypress#224]
In our tests, we do `cy.visit("localhost:8080/logout")`, which resets 2 named cookies and 303 redirects to `"localhost:8080/"`. The cookie sets are not happening correctly with cypress.

Here is an example request from Chrome which correctly sets the cookies.
![image](https://cloud.githubusercontent.com/assets/141353/18446105/be7b6c00-78ee-11e6-9cca-67755038a34a.png)

**Comment by brian-mann** [comment]
I'm able to replicate. This will be fixed soon.

**Comment by ianrose14** [comment]
Hi @brian-mann any update on the expected time of this fix?  I believe that this is blocking our company from upgrading to the 0.17.x branch which is a real pain since I'd like to pull in some of the new 0.17 features like custom mocha reporters.

**Comment by brian-mann** [comment]
The problem here is that when cookies are cleared from the `jar` due to an intermediary redirect that these cookies which were "cleared" do not get properly set on the current browsing session and are therefore "lost".

Cookies which are updated or created during an intermediate redirect *are* correctly handled, so this is only for cookies which were purged in between.

**Comment by brian-mann** [comment]
Fixed in [`0.17.9`](https://github.com/cypress-io/cypress/wiki/Changelog#0179-10132016).
