### ISSUE TITLE
Chrome error code 5/ blank screen on electron browser while running the tests

### ISSUE THREAD

**Issue by amad0005** [cypress-io/cypress#22409]
### Current behavior

During test case executions, the browser runs blank and fails test case executions.

**Browser: (its showing the same issue with other old versions as well)
- Chrome 102 -> Return error code 5
- Electron version: 94 -> shows blank screen

**Reproduction steps:
There are no proper reproduction steps for this failure.

**Possible causes:
1. When the RAM is running high. Initially, the above-mentioned behavior was observed when my machine was running low on memory (for e.g. approx 12 - 13GB of RAM consumption out of 16GB). I updated my macOS to the latest and that brings some optimizations to overall machine performance hence consuming less RAM in other applications. But now the issue is occurring even when the mac is running with 7GB of RAM.

2. When the test case execution time exceeds 200 - 300 seconds. This is less likely to cause an issue because the tests ran fine several times E2E with over 300seconds of total execution time.

<img width="1038" alt="error code 5" src="https://user-images.githubusercontent.com/107306452/174702972-d9fb5407-6bc1-4cba-a9c7-75ec3d378765.png">

The problem can occur at any time with all of the previous execution logs (in timeline being lost). 

Please suggest any proper way around for this. 

### Desired behavior

1. Tests should execute completely. 
2. If there is a memory issue then Cypress should detect it as a safe side before actually starting the test executions.

### Test code to reproduce

This is achievable with any automated test. Systems performance is more important here.

### Cypress Version

9.5.0

### Other

Machine specs:
Macbook M1 chipset with 16GB RAM

**Comment by emilyrohrbough** [comment]
@amad0005 Can you provided verbose debug logs by running with `DEBUG=cypress*`?

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity. Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
