### ISSUE TITLE
type is not working without force

### ISSUE THREAD

**Issue by xtawfeeq7k** [cypress-io/cypress#22446]
### Current behavior

![image](https://user-images.githubusercontent.com/87164562/175014614-700c0a75-04ac-47f8-9242-22f325e96c86.png)

https://user-images.githubusercontent.com/87164562/175014528-e87be9ee-aa3b-4f6b-941f-d494ae38dd6c.mp4

I had to add `{force:true}` in all the tests to run successfully

![image](https://user-images.githubusercontent.com/87164562/175014938-1dbd3aab-9956-407d-a4b4-469bf611fcc1.png)

### Desired behavior

In his situation cypress should run with no need to add `{force:true}` everywhere

### Test code to reproduce

```js
/// <reference types="cypress" />
import user from "../../user";

describe('Analytics Weights page', () => {
  const email: string = user.email;
  const pass: string = user.password;

  const weightTitle = [
    'Analyticity',
    'Code Style',
    'Language understanding',
    'Composure',
    'Resourcefulness',
    '10X-Factor',
  ];

  let beforeClick;
  let afterDecreaseClick;
  let afterIncreaseClick;

  it('Logging in and checking weights', () => {
    cy.visit('http://localhost:3000/login');

    cy.get('[data-testid="input-email-login"]').type(email,{force:true});

    cy.get('[data-testid="input-password-login"]').type(pass,{force:true});

    cy.get('[data-testid="login-btn"]').click({force:true});
    });
});
```

### Cypress Version

cypress 10

**Comment by tbiethman** [comment]
@xtawfeeq7k Thanks for the report. Your video is interesting, the jittery scrolling in there stands out. Cypress has logic to detect whether an element is actionable prior to interacting with it, and I assume the persistent scroll jitter is preventing us from determining that we've reached an interactive state.

I wonder if you see any difference by calling [`focus()`](https://docs.cypress.io/api/commands/focus) directly on the input first?

```js
cy.get('[data-testid="input-email-login"]').focus().type(email);
```

If that doesn't make a difference, maybe try using [`scrollIntoView()`](https://docs.cypress.io/api/commands/scrollintoview) instead of `focus()` and seeing what effect that has?

Does the application under test have any custom scroll handlers or CSS that may be impacting this?

**Comment by distancerunner** [comment]
I ran in to a same behaviour and type only worked properly with focus() or force added: 
```    cy.get('[formcontrolname="company"]')
      .should('be.visible').focus()
      .type('Citycouncil')
```
```    cy.get('[formcontrolname="company"]')
      .should('be.visible')
      .type('Citycouncil',{force:true})
```
