### ISSUE TITLE
BlockHosts Not Working In V10+

### ISSUE THREAD

**Issue by jst1102** [cypress-io/cypress#22478]
### Current behavior

We are still getting xhr's from hosts in the blockHosts

### Desired behavior

BlockHosts should block hosts / not be in xhr sections of tests

### Test code to reproduce

const { defineConfig } = require("cypress");

module.exports = defineConfig({
  viewportWidth: 1920,
  viewportHeight: 1080,
  blockHosts: [
    "*.google-analytics.com",
    "*.googletagmanager.com",
    "*.doubleclicknet.net",
  ]
}

### Cypress Version

10.2

### Other

![chrome_FDkksmlPvH](https://user-images.githubusercontent.com/17620110/175306059-73eb9406-40f9-464f-adb6-62b91887fa45.png)
![Code_MLTqLEfJtI](https://user-images.githubusercontent.com/17620110/175307479-be312383-a40d-4acd-97cc-af9638088cee.png)

**Comment by gustavobmichel** [comment]
I am having a similar behaviour when running on Cypress 10.2 on Windows. As per the docs I can't find the header `x-cypress-matched-blacklisted-host` on my response header. This setting was working fine on Cypress 9+.

**Comment by devhid** [comment]
`blockHosts` option also not working for me.

But @jst1102, I see in your screenshots that you blocked `*.doubleclicknet.net`, but your actual request is from the domain, `doubleclick.net`. Was this just a typo and it still doesn't work?

**Comment by AurelienKun** [comment]
We tried to migrate to the new v10.2 but this issue has a big impact on our CI building time. We had to rollback to v9.7.0.

**Comment by tbiethman** [comment]
@jst1102 @devhid @AurelienKun thank you for the report and the comments. I tried to reproduce this and failed to do so, which indicates to me that there's a difference in our dev environments. Can you provide me with:

* the platform (macOS/windows/linux) where you're seeing this issue
* the version of node being used

**Comment by devhid** [comment]
> @jst1102 @devhid @AurelienKun thank you for the report and the comments. I tried to reproduce this and failed to do so, which indicates to me that there's a difference in our dev environments. Can you provide me with:
> 
> * the platform (macOS/windows/linux) where you're seeing this issue
> * the version of node being used

Hi @tbiethman,

Platform: MacOS Monterey v12.3

Node Version
```
❯ node --version     
v16.14.2
```

NPM Version
```
❯ npm --version      
8.10.0
```

**Comment by tbiethman** [comment]
@devhid thanks for thorough set of data. Turns out our environments match, so something else must be going on here.

I noticed that your blockedHost value for `iaudienc.com` doesn't include a subdomain wildcard, but the requests are being made from the subdomain `s.iaudienc.com/...`. So a couple questions:

* Have you tried using a subdomain wildcard (`*iaudienc.com`) for that entry?
* Do you see the other blocked hosts you specify (doubleclick/google-analytics) succeed, or do those seem to be getting blocked?
* Are you migrating from a previous version of Cypress to 10.1.0 where the config you posted was working?

**Comment by devhid** [comment]
Hi @tbiethman, I was able to figure it out and it is now working for me.

You were right about needing the wildcard. When I used `*iaudienc.com`, the host is correctly blocked.

The issue was that my changes for `blockHosts` when I originally tried the wildcard didn't take place until I completely closed the Test Runner and restarted it. Usually, whenever I make changes in any file including the config, I can just save it and it's reflected in the Test Runner (and the test automatically re-runs again).

Is this behavior expected?

**Comment by gustavobmichel** [comment]
I figured out what my issue was. I am using different config files for different environments and they don't inherit from the main `cypress.config.js` so I have to copy all settings into it. Hope that helps someone.

**Comment by jst1102** [comment]
> `blockHosts` option also not working for me.
> 
> But @jst1102, I see in your screenshots that you blocked `*.doubleclicknet.net`, but your actual request is from the domain, `doubleclick.net`. Was this just a typo and it still doesn't work?

Reading over this thread, I've now got it working. As the others indicated, they just had to update their URLs. Specifically, I know I tried just doubleclicknet.net, which didn't work. Doing as purposed and doing *doubleclicknet.net, and adding * in front of the others blocked as desired! Thank you all for the great assistance.

**Comment by jst1102** [comment]
Seems we are all set! Great work and communication all!
