### ISSUE TITLE
ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 

### ISSUE THREAD

**Issue by Ilonas1** [cypress-io/cypress#22509]
### Current behavior

describe('My first simple testy with cypress' () => {
    it('True should be true', () => {
        expect(true).to.equal(false)
    })
})

### Desired behavior

ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 

### Test code to reproduce

ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 

### Cypress Version

9.7.0

**Comment by emilyrohrbough** [comment]
Hi @llonas1 This issue has been logged a few different times at various points. This should not impact Cypress running, rather it is a warning logged by Chromium due to your system setup. It seems like can occur when hardware acceleration is enabled. One suggest that has worked for some can be found [here](https://github.com/cypress-io/cypress/issues/18947#issuecomment-991901414). This appears to be a [chromium issue](https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled) as others are reporting it outside of cypress.

Some of the proposed solutions are passing in args when launching browsers. If you wish to try them with cypress follow this [guide](https://docs.cypress.io/api/plugins/browser-launch-api#Modify-browser-launch-arguments-preferences-and-extensions) to modify the args passed when starting browsers.
