### ISSUE TITLE
Cypress will not open on my Mac

### ISSUE THREAD

**Issue by Nazmin1982** [cypress-io/cypress#22522]
### Current behavior

I get this message 
```
Nazminaras-MBP: Cypress_Automation-main-2 nazminaraali$ npm install cypress -- save-dev

added 1 package, and audited 256 packages in 1s

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Nazminaras-MBP:Cypress_Automation-main-2 nazminaraali$ npm i

up to date, audited 256 packages in 755ms

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Nazminaras-MBP:Cypress_Automation-main-2 nazminaraali$ npx cypress open
Cypress cannot run because this binary file does not have executable permissions here:

/Users/nazminaraali/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/MacOS/Cypress

Reasons this may happen:

- node was installed as 'root' or with 'sudo'
- the cypress npm package as 'root' or with 'sudo'

Please check that you have the appropriate user permissions.

You can also try clearing the cache with 'cypress cache clear' and reinstalling.

----------

Platform: darwin-x64 (19.6.0)
Cypress Version: 9.7.0
```

### Cypress Version

9.7

### Package Manager

npm

### Operating system

Mac

**Comment by Benedict-Lojewski** [comment]
run this command

`chmod 755 /Users/nazminaraali/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/MacOS/Cypress`

You should be able to install after that.

**Comment by Nazmin1982** [comment]
Thank you for the reply, now I get this error

Cypress failed to start.

This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies

Please refer to the error below for more details.

----------

Command was killed with SIGKILL (Forced termination): /Users/nazminaraali/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/MacOS/Cypress --no-sandbox --smoke-test --ping=533

**Comment by emilyrohrbough** [comment]
@Nazmin1982 Can you run with `DEBUG=cypress*`?

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity. Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
