### ISSUE TITLE
.crx files?

### ISSUE THREAD

**Issue by GrayVi02** [cypress-io/cypress#22534]
### Current behavior

Hello, I package software for my organization. Recently members of one of our organizational units have been unable to use the cypress.io .crx chrome extension due to some workstation hardening policies we put in place recently. Our process now is to package these types of extensions and deploy to each user individually. 

I have been unable to find much information about the .crx extension you all offer, let alone the .crx files so that I can package them. Are the .crx file, settings file, and other necessary items for the chrome extension packaging available for download anywhere? 

Thanks. 

### Cypress Version

9.7 or Latest version

### Package Manager

npm

### Operating system

Windows

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity. Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by GrayVi02** [comment]
Hi Victoria and Emily,

We are running it from cypress itself but not any third party extension. I am not even seeing the extension shows atm.
***@***.***
***@***.***


Before Victoria guide me on the register key change  the erro was like tihis
***@***.***
***@***.***

Thanks & Regards,
Yueh

From: Gray, Victoria (RIS-ATL) ***@***.***>
Sent: 28 June 2022 14:00
To: cypress-io/cypress ***@***.***>; cypress-io/cypress ***@***.***>; Zeng, Qianyue (RIS-SUT) ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [cypress-io/cypress] .crx files? (Issue #22534)

@Zeng, Qianyue ***@***.***> Can you provide Emily with more information on the Chrome extension your team uses?

Thanks,
Victoria Gray
Desktop Engineer
Infrastructure & Operations Group
LexisNexis Risk Solutions Group
***@***.******@***.***>

LexisNexis Risk Solutions | ICIS | Cirium | Proagrica | XpertHR | EG | Nextens
