### ISSUE TITLE
Cookies not set correctly by cypress

### ISSUE THREAD

**Issue by abin53** [cypress-io/cypress#22554]
### Current behavior

https://github.com/cypress-io/cypress/discussions/21509#discussioncomment-3009357

### Desired behavior

Cookies must be set correctly

### Test code to reproduce

Issue explained in https://github.com/cypress-io/cypress/discussions/21509#discussioncomment-3009357

### Cypress Version

7.1.0

**Comment by chrisbreiding** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Please provide a reproducible example with test code. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

You're also using a relatively old version of Cypress. Is it possible to reproduce this issue in the latest version of Cypress (10.3.0)?

**Comment by abin53** [comment]
![IMG_20220705_184823~2](https://user-images.githubusercontent.com/13628586/177339543-4487cb7c-0a88-4cc6-b9d9-5c6cb37447db.jpg)

This screenshot suggest there are 3 cookies. Two XSRF-TOKEN with path as '/' and httpOnly as 'false' and also one other cookie JSESSIONID with path /scv' and httpOnly as true

**Comment by abin53** [comment]
![IMG_20220705_184830~2](https://user-images.githubusercontent.com/13628586/177339639-622a0992-054b-4e87-9cab-7250cdd3ae0d.jpg)

This screenshot of the same request it can be seen that only one cookie is considered which is XSRF-TOKEN but with path '/scv' and httpOnly as true which is not the right attributes. They are attributes of JSESSIONID cookie which is not even set

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
