### ISSUE TITLE
Wrong path when execute cy.exec

### ISSUE THREAD

**Issue by PhmNgocNghia** [cypress-io/cypress#2257]
This seem to be environment problem. I have already looked for help on gitter but people seem not experience my problem so i decided to create a bug report. Just look at the path, usr is definitely from linux path. I already install git-bash. Cypress is so cool maybe i need to switch from windows 7 to linux just for using cypress.

### Current behavior:
```
CypressError: cy.exec('cat cypress.json') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 127

Stderr:
/c/Program: Files\Git\usr\bin\bash.exe: No such file or directory
```
### Desired behavior:
Cy.exec execute command from docs

### Steps to reproduce:
- Install cypress with npm install --save dev
- Run example from docs
```
cy.exec('npm run build').then((result) => {
  // yields the 'result' object
  // {
  //   code: 0,
  //   stdout: "Files successfully built",
  //   stderr: ""
  // }
})
```

### Versions
- version 3.0.3
- Windows 7 64 bit

**Comment by jennifer-shehane** [comment]
Hi @PhmNgocNghia, thanks for asking. This is unfortunately an issue with the docs - as this command will simply not work on Windows. The docs should be updated to the example below since `cat` is not an available command on Windows. 

```
    if (Cypress.platform === 'win32') {
      cy.exec('print cypress.json')
        .its('stderr').should('be.empty')
    } else {
      cy.exec('cat cypress.json')
        .its('stderr').should('be.empty')
```

I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document updating the exec doc here: https://github.com/cypress-io/cypress-documentation/issues/808. Our documentation is open source and contributions are welcome. 😄

**Comment by wasiqkhan786** [comment]
can we use cy.exec as alternative of evaluate from protractor?
