### ISSUE TITLE
Cypress CI hangs on async tests sometimes

### ISSUE THREAD

**Issue by shauvik** [cypress-io/cypress#226]
There is some race condition that causes `cypress ci` to hang on async tests i.e., when we pass a done callback as a second parameter. https://mochajs.org/#asynchronous-code 

There is no good way to debug this at the moment as the test doesn't fail and the mocha output is stuck at the previous test.

**Comment by brian-mann** [comment]
Anytime you issue a cypress command in a test forces mocha into async mode, so I doubt that has anything to do with it.

The real problem here is that we cannot easily "see" into why `electron` hung. Is it a problem with Chromium, a problem with system drivers / dependencies? It is a problem in Cypress? We don't know.

But the solution for this is a few things - we're going to be adding automatic video recording whenever running headlessly, and the ability to use `cy.record` for recording specific periods of time.

We're also gong to give you the ability to run other real browsers with `cypress run` so if there are specific problems with `electron` they can be easily bypassed even when running in CI mode.

I'm confident when we can determine the root cause it'll be easily fixable.
