### ISSUE TITLE
Sidebar scrollbar is really hard to use

### ISSUE THREAD

**Issue by kaiyoma** [cypress-io/cypress#22608]
### Current behavior

Currently, you have to be a sniper to grab the scrollbar for scrolling. See the screencast:

https://user-images.githubusercontent.com/10719780/176554494-6fe9dc71-a5e3-428a-8d91-cbdb509b6c88.mp4

Only the very left of the scrollbar is usable for scrolling. The rest gets hijacked by east-west resizing.

### Desired behavior

Scrolling should work normally.

### Test code to reproduce

Run any test in Cypress 10.3.0. I'm running Windows 10.

### Cypress Version

10.3.0

**Comment by lmiller1990** [comment]
Thanks for the report. That looks really annoying. If you'd like to try and fix this problem, we'd be happy to accept a PR! Otherwise, someone from Cypress can take a look.

If you do decide to take a look, you should be able to clone the repo, `yarn`, `cd packages/app` and `yarn dev` should get you started.

**Comment by emilyrohrbough** [comment]
@kaiyoma It looks like there is an existing contributor PR to fix this behavior! #22473
