### ISSUE TITLE
Showing a window pop-up while running commands in the headless (CLI) mode.

### ISSUE THREAD

**Issue by SinghPramender** [cypress-io/cypress#22616]
### Current behavior

As we know, cypress does not support other window or tab testing. I am testing a button on which a new window opens. But when i run the code in the command lines using "npx cypress run", a window pop-up and then disappear. But this should not be happened in the headless mode.

### Desired behavior

Pop-up window should not show in the screen.

### Test code to reproduce
```js
Cypress.Commands.add('changePassword', () => {
    cy.get(commonObjects.profileSection).should('be.visible');
    cy.get(commonObjects.profileSection).click();
    cy.xpath(commonObjects.profileListContainerXpath).within(() => {
        cy.get(commonObjects.profileMenuItems).contains(' Change Password ').should('be.visible');
        cy.get(commonObjects.profileMenuItems).contains(' Change Password ').click();
    });
});
```

### Cypress Version

9.7.0

**Comment by emilyrohrbough** [comment]
@SinghPramender Can you provide additional information like browser, os as well as a reproducible example using https://github.com/cypress-io/cypress-test-tiny?

**Comment by emilyrohrbough** [comment]
Are you referencing the face Cypress is [auto-accepting an alert](https://cypress-documentation-h2l08ulip-cypress-io.vercel.app/api/events/catalog-of-events#Window-Alert)?

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity. Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by AzeemChaudary** [comment]
I had  cypress-cucumber-preprocessor in my cypress project . when I have uninstalled  it and executed some tests in headless mode. I am getting a white blank popup which is not interactable we cant click on it. I am getting this even after installing cypress-cucumber-preprocessor again 



![download](https://github.com/user-attachments/assets/dc5b9d00-3714-4b32-84a1-a22e913c9205)



Here is the screenshot

**Comment by neminovno** [comment]
Happens while `cypress run --spec aaa.cy.ts --browser chrome` is running, there is white box visible. I guess it is chrome window related, because box size can be changed with window-size argument:
```
on('before:browser:launch', (browser, launchOptions) => {
  if (browser.name === 'chrome' && browser.isHeadless) {
    launchOptions.args.push('--window-size=1800,900');
    return launchOptions;
  }
});
```
Nothing new was installed, just updated Cypress recently.

Cypress: 13.14.2
Browser: Chrome 129 (headless)
Node Version: v20.11.0 (C:\Program Files\nodejs\node.exe)

**Comment by gkielwasser** [comment]
@jennifer-shehane Could you please re-open the issue? It seems to still be occurring.

There is a white window which seems a bit different of the browser one we see with `--headed`.

using default or explicit headless argument
`cypress run --browser chrome --headless`
`cypress run --browser chrome`

Os: Windows 10
Cypress: 15.15.0
Browser Chrome 129
Node: v18.20.2

It is related to chrome browser as running `cypress run --browser firefox` won't show any window.

**Comment by neminovno** [comment]
It is Chrome 129 issue: 
https://stackoverflow.com/questions/78996364/chrome-129-headless-shows-blank-window
