### ISSUE TITLE
`@cypress/vue@4.0.0` bundle is broken: `@vue/test-utils` is not externalized

### ISSUE THREAD

**Issue by 0x009922** [cypress-io/cypress#22611]
### Current behavior

Currently `@cypress/vue` (v4) has a dependency:

```json
{
  "dependencies": {
    "@vue/test-utils": "2.0.0-rc.19"
  }
}
```

But if you explore actual `dist/cypress-vue.*.js` files, you will see that Vue Test Utils is not imported, but bundled. The only external import is `vue`.

### Desired behavior

`@cypress/vue` should import `@vue/test-utils`, not bundle it.

### Test code to reproduce

Bundle bug, not test code.

### Cypress Version

10

### Other

It is a huge problem because our tests rely heavily on setting global Vue Test Utils configuration to achieve global components registration per spec file. (https://test-utils.vuejs.org/api/#config-global)

For example, we do that trick:

```ts
import { config } from '@vue/test-utils'
import { mount } from '@cypress/vue'

before(() => {
  config.global.components = { SRadio, SRadioGroup }
})

after(() => {
  config.global.components = {}
})

it('just mounts', () => {
  cy.mount({ template: `<SRadioGroup />` })
})
```

Now it doesn't make any effect because `mount()` from `@cypress/vue` does not import `@vue/test-utils`, i.e. it is broken.

BTW, Cypress 10 is awesome!

**Comment by lmiller1990** [comment]
Hi! Good point. If we import it, though, it's an additional peer dependency, which isn't really ideal.

We've got two options:

1. try to import it, then defer to bundled version.
2. bundle it and re-export it

I think 2 is the best option - this way, you just need to update to the latest `cypress` version, and you'll get all the updates for free. `cypress/vue` is generally running against the latest stable test utils version.

This would mean you'd do

```js
import { config, mount } from 'cypress/vue'
```

Also, if you are on Cypress 10, you don't even need to install `@cypress/vue` - we bundle it with Cypress, so just import it from `cypress/vue`. The goal is, instead of installing lots of different libraries, you just need to install and update Cypress, and we deal with the rest!

What do you think? Open to the first option too, but I think less peer dependencies is generally better for the end user, since you don't have to mess around with updating everything, just one dependency (cypress).

**Comment by JessicaSachs** [comment]
One of the issues to consider with either solution is that `config` is a Vue 3-only concept. When we document the solution, this is only gonna be applicable to Vue 3.

@Akryum what do you need from the exports object that you cannot set when invoking mount itself? The before/after syntax in the initial code example of this issue is useful, but it's entirely possible to just pass in `global.components` from within mount in a custom command.

**Comment by lmiller1990** [comment]
I am working on this, it should be done soon.

**Comment by lmiller1990** [comment]
The PR is about to merge, and last minute feedback on the API would be great!

**Comment by Akryum** [comment]
Looking good
