### ISSUE TITLE
Cypress test on sauce labs

### ISSUE THREAD

**Issue by anchalkumra** [cypress-io/cypress#22679]
### Current behavior

My application is secured with 2 factor authentication (ping authentication). When running the test on sauce , browser authentication window appears.  I am unable to bypass the login neither able to fetch the current url so that i can pass username and password and proceed with the test. Its a big block to run cypress test for such applications where the cross origin happens.
 Running 2 factor authentication url on sauce using cypress.
![image](https://user-images.githubusercontent.com/60463423/177317265-3729e534-0bf6-46e8-8892-0002ebda2a4f.png)

I am using cypress 9.7.0 as sauce labs dont support cypress versions other than below
![image](https://user-images.githubusercontent.com/60463423/177317463-a8b3b424-d420-4ef3-8a68-1d0f02c283fe.png)

If incase , cy.origin is not used, upon clicking the signing button , the authenticaiton pop-up is displayed and page keeps loading. On adding cy.origin , page still keeps loading but the cy.origin command is unbale to perform any action.

### Desired behavior

When a user is trying to login , the browser authentication pop-up thats displayed, cypress should be capable to read that page or able to add username and password or click signin or cancel button.

### Test code to reproduce

cy.visit ('/')
cy.origin("https://authgateway1-dev.entiam.xxxxxxxxxcom/", ()=>{
        //cy.contains('Sign In').click()
        cy.get("input[type='username']").type('username')
        cy.get("button[type='Cancel']").click()
    })

### Cypress Version

9.7.0

**Comment by chrisbreiding** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by anchalkumra** [comment]
Hi Chris , My application uses ping fed server for user authentication and follow single sign on standards. When running it on sauce , the authentication pops-up (screenshot share above) , the url changes when a login button is clicked.

cypress is unable to type username/password/hit cancel button on the pop-up nor able to fetch the current url too which can be used to pass username and password. 

Its basically the multi origin and per the examples shared on cypress doc , those are not working for a scenario like this.

**Comment by anchalkumra** [comment]
It happens only while spinning the application on Sauce Labs. Locally , it uses ldap authentication , such pop-up doesn't come.

I couldn't proceed ahead to test the application behavior on sauce due to this blocker.

**Comment by chrisbreiding** [comment]
Are you able to run your tests locally using the same authentication method as on sauce and encounter the same issue? It would be easier to debug if it's reprocible locally.

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by anchalkumra** [comment]
Hi . This scenario is reproducible in incognito mode on local . However , when i am using below code to run electron in incognito mode , it gives me web pack error.
Below is the code as suggested in plugins/index.js file 

        module.exports = (on, config) => {
        on('before:browser:launch', (browser = {}, launchOptions) => {
           if (browser.family === 'chromium' && browser.name !== 'electron') {
               launchOptions.args.push("--incognito");                
               return launchOptions
           }
  
          if (browser.name === 'electron') {                
              launchOptions.preferences.incognito = true               
              return launchOptions
          }
      })    
      }

The error received is as below
![image](https://user-images.githubusercontent.com/60463423/180991403-4f9e07d0-06f0-4fe8-9274-8b19969e4e0a.png)

This is my npm test script:
"test": "npx cypress run --headed --spec 'cypress/integration/features/xxxx/xxx_deployment.feature'  --reporter mocha-allure-reporter ",
