### ISSUE TITLE
 Exception error after opening app url under test - Cannot read properties of null (reading 'contentWindow')

### ISSUE THREAD

**Issue by oharpat** [cypress-io/cypress#22685]
### Current behavior

On running script that opens URL (https) from app running locally on port 8080 and attempting to click on a login button the following exception occurred in console and script fails.
The page does however opens as can be seen in the Cypress test runner. It looks as though Cypress can not select the window contentsl. See error below.

![image](https://user-images.githubusercontent.com/39906075/177349921-043c0993-54e6-4614-a4a6-0fcc301449b9.png)

Event:      uncaught exception
Caught by:  "error" handler
Error:      TypeError: Cannot read properties of null (reading 'contentWindow')

The following is detailed in the output of Cypress IDE
![image](https://user-images.githubusercontent.com/39906075/177349681-a64ace78-54a8-467e-9d85-8227b7c07ccb.png)

### Desired behavior

Test URL should open in browser and page elements should be clickable in browser.

### Test code to reproduce

To be added

### Cypress Version

10.3.0

### Other

This was working without issue before V10 migration in V9.6.1

**Comment by sean-schaefer** [comment]
I also ran into this same error during a migration to Cypress 10, and tracked it down to an incompatible version of [cypress-terminal-report](https://github.com/archfz/cypress-terminal-report). I was using version 3.x.x which doesn't appear to work with Cypress 10, so I had to upgrade to [v4.x.x](https://github.com/archfz/cypress-terminal-report/commit/1b59b3a5df128c82565f51be1936ff282cea018e).

**Comment by BlueWinds** [comment]
@oharpat - Have you tried sean's suggestion?

If that didn't fix it, then right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
