### ISSUE TITLE
Graphql Request Handle

### ISSUE THREAD

**Issue by sharozraees802** [cypress-io/cypress#22697]
### Current behavior

im use a graphql request there my component sends many requests on server cypress not handle and cypress crash the web browser

### Desired behavior

im use a graphql request there my component sends many requests on server cypress not handle and cypress crash the web browser

### Test code to reproduce

im use a graphql request there my component sends many requests on server cypress not handle and cypress crash the web browser

### Cypress Version

10.3.0

**Comment by sharozraees802** [comment]
Please Resolve This Issue

**Comment by chrisbreiding** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by mjhenkes** [comment]
Closing absent a reliable reproduction
