### ISSUE TITLE
Chaining is broken for `should`

### ISSUE THREAD

**Issue by fjodor-rybakov** [cypress-io/cypress#22692]
### Current behavior

The following code gave an error

```typescript
cy.visit('https://docs.cypress.io/guides/overview/why-cypress#What-you-ll-learn')
      .get('div.main-content-header h1')
      .should('not.have.attr', 'readonly')
      .and('not.have.attr', 'data-is-invoking');
```

![image](https://user-images.githubusercontent.com/23727801/177542840-1216d42f-c26c-452b-81b3-be29cf3629c3.png)
![image](https://user-images.githubusercontent.com/23727801/177543590-8dbc0d07-644c-4423-a6ee-767ae2df0da6.png)

### Desired behavior

* Prev subject should pass to `and` chain
* Second check attr should not throw error

### Test code to reproduce

```typescript
cy.visit('https://docs.cypress.io/guides/overview/why-cypress#What-you-ll-learn')
      .get('div.main-content-header h1')
      .should('not.have.attr', 'readonly')
      .and('not.have.attr', 'data-is-invoking');
```

### Cypress Version

10.0.3

**Comment by JessefSpecialisterren** [comment]
I'm just a fellow Cypress user, but AFAIK this is expected behavior. Quoting from https://docs.cypress.io/api/commands/should#Yields: "some chainers change the subject." And below that on the same page (under heading https://docs.cypress.io/api/commands/should#Subjects):
> **How do I know which assertions change the subject and which keep it the same?**
> The chainers that come from [Chai](https://docs.cypress.io/guides/references/bundled-libraries#Chai) or [Chai-jQuery](https://docs.cypress.io/guides/references/bundled-libraries#Chai-jQuery) will always document what they return.

`attr` is a Chai-jQuery assertion and is [documented to return the value of the attribute](https://github.com/chaijs/chai-jquery#attrname-value) (although the wording of that documentation could be a little clearer 😇). If you want to check for the absence of multiple attributes using a single `get`, I'd recommend using `should` with a callback function (https://docs.cypress.io/api/commands/should#Function).

**Comment by fjodor-rybakov** [comment]
> I'm just a fellow Cypress user, but AFAIK this is expected behavior. Quoting from https://docs.cypress.io/api/commands/should#Yields: "some chainers change the subject." And below that on the same page (under heading https://docs.cypress.io/api/commands/should#Subjects):
> 
> > **How do I know which assertions change the subject and which keep it the same?**
> > The chainers that come from [Chai](https://docs.cypress.io/guides/references/bundled-libraries#Chai) or [Chai-jQuery](https://docs.cypress.io/guides/references/bundled-libraries#Chai-jQuery) will always document what they return.
> 
> `attr` is a Chai-jQuery assertion and is [documented to return the value of the attribute](https://github.com/chaijs/chai-jquery#attrname-value) (although the wording of that documentation could be a little clearer 😇). If you want to check for the absence of multiple attributes using a single `get`, I'd recommend using `should` with a callback function (https://docs.cypress.io/api/commands/should#Function).

Thanks! You cleared things up for me
