### ISSUE TITLE
Cypress v9.5.1 to v10.3.0 migration wizard keeps looping on load your project/find browsers installed on system

### ISSUE THREAD

**Issue by GBL87** [cypress-io/cypress#22700]
### Current behavior

Hi,

After reviving a project I started earlier this year I decided to also go with the latest version of Cypress.
The version which I was using at the time was v9.5.1 and I followed the migration wizard with success until a certain point.

I was able to clear all the action points in this screen:
![image](https://user-images.githubusercontent.com/17334300/177630655-3996606e-86f5-4db6-af4a-f8985448bae7.png)

But when I click on the "Continue" button, I get stuck in a looping loading project/search for installed browsers on my system:
![image](https://user-images.githubusercontent.com/17334300/177630772-9bba5bd0-878d-4d7a-969b-fdb4c9b5788d.png)

I can verify that my project ran successfully under version v9.5.1.
Is this a known issue? And if so, is there a way to solve this?

Many thanks in advance,

Gwen

### Debug logs

added "DEBUG=cypress:*" env var, but nothing really came out of the logs except the periodic system metrics per service ...

### Cypress Version

10.3.0

### Package Manager

npm

### Operating system

Mac

**Comment by astone123** [comment]
Hey @GBL87, a couple of questions:

1. Do you have any other projects on your system that you can run e2e tests with? If not, maybe try setting up a simple project to run e2e tests. This might give us an idea of whether it's an issue with this specific project or a system/browsers issue.
2. Are you able to provide those three configuration files that are listed in the wizard? Looking at the configuration might reveal some more info about what is happening.

Thanks!

**Comment by marktnoonan** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
