### ISSUE TITLE
Issue with selector playground input field not allowing input when a React Material UI dialog is showing

### ISSUE THREAD

**Issue by pjamessteven** [cypress-io/cypress#22714]
### Current behavior

I have a problem where the selector playground text input won't allow me to manually input a selector when a Material UI (v4) dialog is showing. I originally had this problem with version 9.5.0 but it also happens with the latest version; 10.3.0. 

### Desired behavior

I should be able to use the selector playground text input to manually input a selector regardless of the content of the iframe containing the app I'm testing. 

### Test code to reproduce

I don't have the time to do this sorry, the repo I'm working on is private. 

### Cypress Version

10.3.0

**Comment by astone123** [comment]
@pjamessteven are you able to reproduce this issue with a simple webpage outside of your private repo? It would help us figure out what's going on if we had a way to reproduce. 

Also, could you be a little more specific about how you're using the selector playground API? Thanks!

**Comment by marktnoonan** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
