### ISSUE TITLE
Cypress 10.3.0 Gives 'Worker terminated due to reaching memory limit: JS heap out of memory'

### ISSUE THREAD

**Issue by taydin-git** [cypress-io/cypress#22734]
### Current behavior

I upgraded cypress from 8.3.0 to 10.3.0, it keeps crashing and gives heap out of memory even though I increased the memory. I guess, it is due to high CPU usage. It is giving the following error message all the time.

**Worker terminated due to reaching memory limit: JS heap out of memory
Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory
    at new NodeError (node:internal/errors:371:5)
    at Worker.[kOnExit] (node:internal/worker:277:26)
    at Worker.<computed>.onexit (node:internal/worker:199:20)

The Test Runner unexpectedly exited via a exit event with signal SIGABRT

Please search Cypress documentation for possible solutions:

https://on.cypress.io

Check if there is a GitHub issue describing this crash:

https://github.com/cypress-io/cypress/issues

Consider opening a new issue.

----------

Platform: darwin-x64 (21.4.0)
Cypress Version: 10.3.0**

### Desired behavior

Cypress shouldn't crash and let my tests run

### Test code to reproduce

I can't provide any repo but I can tell, it is not a big app to test.

### Cypress Version

10.3.0

**Comment by chrisbreiding** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by mjhenkes** [comment]
Closing absent a reliable reproduction.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
