### ISSUE TITLE
The test will be blocked at the spinner appearance

### ISSUE THREAD

**Issue by ammannai** [cypress-io/cypress#22759]
### Current behavior

Currently, when loading tests and by redirecting to another screen (due to an action or a web service call) , cypress doesn't load the next screen, will get stuck at the spinner and the target screen gets greyed out.
Note: the spec passes correctly in _-- watch_ mode and fails in _-- headless_ mode.

### Desired behavior

In this situation , cypress should load the screen correctly as reproduced in the application manually , spinner appears when loading the screen and disappears after page successful load.

### Test code to reproduce

Use case to reproduce : 
By invoking the save action on an Edit screen containing a form, a redirection to a view screen will be executed after loading the spinner.

### Cypress Version

5.3.0

**Comment by chrisbreiding** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
