### ISSUE TITLE
Performance measurement and optimizations of ObstructiveCode RegEx

### ISSUE THREAD

**Issue by nagash77** [cypress-io/cypress#22766]
Per our conversation with Brian, the performance of the RegEx is "10/10 importance".  We need to do benchmarking and optimizations around performance.  Results to be shared with team and Brian/Peter.

**Comment by AtofStryker** [comment]
Initially, when assessing the regex performance of the added transformations, the rewriting performed about twice as slow as seen [here](https://github.com/cypress-io/cypress/pull/22568#discussion_r911378293) and was consistent with other benchmarks taken locally. After some work on the regex by @mschile and myself, we were able to only increasing the performance burden by about 10% instead of 100% by eliminating lookbacks/lookaheads and combining regex to only analyze added expressions when the feature flag is turned on. 
![](https://user-images.githubusercontent.com/3980464/179087671-0822ff36-d85f-45e7-96e9-dfa001484cf7.png)

If we stick with this approach, I believe the performance impact will be minimal
