### ISSUE TITLE
Commands are not scrolled into view on long test runs

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#228]
Commands are being cut off when there is a long test run instead of being scrolled into view.

![vlcsnap-2016-09-20-00h09m22s864](https://cloud.githubusercontent.com/assets/1268976/18657276/8e3d7122-7ec6-11e6-8e45-f97ebead63a7.png)

I've also included a video and you'll see everything starting from `0:32` will be cut off.

[headless.zip](https://github.com/cypress-io/cypress/files/481616/headless.zip)

**Comment by chrisbreiding** [comment]
I believe the issue is that as tests expand and collapse rapidly, there's a chance the command element's position gets reported "wrong" when queried, so it ends up cut off. To combat that, I've added a padding, so that the active test or command will always be slightly above the bottom instead of right at the bottom.

**Comment by brian-mann** [comment]
Fixed in [`0.17.5`](https://github.com/cypress-io/cypress/wiki/Changelog#0175-10022016).
