### ISSUE TITLE
Run cypress-io/github-action@v2 internal/fs/utils.js:269     throw err;     ^ Error: ENOENT: no such file or directory, open '/runner/_work/wms-mobile/wms-mobile/cypress/package-lock.json'

### ISSUE THREAD

**Issue by tpatro** [cypress-io/cypress#22806]
### Current behavior

github action doesn't find package-lock.json even though its present

### Test code to reproduce

<img width="563" alt="image" src="https://user-images.githubusercontent.com/81240914/179210843-e953246a-1c55-4118-8ad0-ca6655f42d48.png">

### Cypress Version

6.8.0

**Comment by tpatro** [comment]
This package-lock.json is installed inside cypress because the npm install command is run inside cypress directory.
Here is the structure
<img width="585" alt="image" src="https://user-images.githubusercontent.com/81240914/180183690-619c9360-8de8-4f60-9903-d0c5f9b91b18.png">

**Comment by marktnoonan** [comment]
Thanks @tpatro, we have some documentation around using `package.json` in a subfolder: https://github.com/cypress-io/github-action#subfolders, which points to the need to use this package: https://github.com/bahmutov/cypress-gh-action-subfolders.

I'm not too familiar with github actions but does this seem like it would unblock you? Or you've tried these things and they didn't work? If none of that documentation helps, we'll move this issue to that github-actions repo, since it doesn't seem to be a problem with the Cypress app itself.

**Comment by marktnoonan** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
