### ISSUE TITLE
Input type="datetime-local" type() does not work Sometimes correctly

### ISSUE THREAD

**Issue by Koyirov** [cypress-io/cypress#22805]
### Current behavior

I try to enter the date to input type="datetime-local" by type() function with the format 'YYYY-MM-DDTHH:mm' (for example: 2022-07-15T12:45), but "Sometimes" Cypress doesn't type at all, I don't see any change in the date on user interface. I don't understand exact reason why "Sometimes" doesn't work and "Sometimes" works. Language is set to German.

### Desired behavior

It should be entered the date correctly and always correctly.

### Test code to reproduce

cy.get('input[name="startDate"][type="datetime-local"]').type("2022-07-15T12:00");

### Cypress Version

9.6.1

**Comment by chrisbreiding** [comment]
Can you please provide the following information?

- OS and OS version
- Browser and browser version

**Comment by Koyirov** [comment]
> Can you please provide the following information?
> 
> * OS and OS version
> * Browser and browser version

OS: Windows 10 Pro and  21H2
Browser: Chrome and 103.0.5060.134

**Comment by mjhenkes** [comment]
@Koyirov, Sorry, I should have asked for this sooner, but could you put together a repo demonstrating the problem? Generally I start with the https://github.com/cypress-io/cypress-test-tiny template to get a simple example up and running.

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
