### ISSUE TITLE
Sometimes inputs appear to be incorrectly marked as disabled for typing

### ISSUE THREAD

**Issue by emmanuelonah** [cypress-io/cypress#22872]
> I'm seeing something similar after upgrading from 7.7.0 to 8.5.0. I've even added an assertion as shown below in the hopes to tease out the issue but the assertion passes and then the next line complains about the error mentioned in the original post.
> 
> ```js
> cy.get("[name=zip]").should("not.be.disabled").type(zip);
> ```
> 
> ![image](https://user-images.githubusercontent.com/77620925/158619233-638cdfc1-b602-4f59-a958-59ce2b62c39c.png)
> 
> In my case I was able to get these cases working instead by forcing focus.
> 
> ```js
> cy.get("[name=zip]").focus().should("not.be.disabled").type(zip).focus().blur();
> ```
> 
> Also BTW, [this post on a separate issue](https://github.com/cypress-io/cypress/issues/5827#issuecomment-1036084927) seems to be highlighting the experience I've repeated and demonstrated above as well.
> 
> Based on what I'm seeing right now I'll be sticking back onto 7.7.0 until this gets resolved or until I have time to help dig further into the root cause or help to arrive at a solution.

Me too after upgrading to **9.3.1**, it started happening.

Meanwhile, @jennifer-shehane mentioned [here](https://github.com/cypress-io/cypress/issues/5827) that the reason for such behaviors is because the cypress tries to perform an action on a DOM Node before the actual node/element-node is mounted/rendered into the DOM. But then my fear is; that if we decide to do a synchronous cy.wait, that will be very unstable since we don't know the time frame. 

My other solution was to chain the **then**  method to the element before performing an action on it, the reason for thinking that way is that; it will only perform the action when the element is resolved since cypress says every query is promisified [here](https://docs.cypress.io/api/commands/then). But then this still doesn't work. Right now I don't know what to do.

```
cy.get(selectorHere).then(node=>{
//now use it safely, but unfortunately this still doesn't work
})
```

_Originally posted by @emmanuelonah in https://github.com/cypress-io/cypress/issues/5830#issuecomment-1190538811_

**Comment by marktnoonan** [comment]
@emmanuelonah I agree this should be investigated, seems a few people are seeing it, and in various situations. Did you try the workaround mentioned [here](https://github.com/cypress-io/cypress/issues/5830#issuecomment-570638375) with `.blur()`? 

Can you share a reproducible example with me where this is happening and we can debug from there? Cloning https://github.com/cypress-io/cypress-test-tiny and adding your code to that would be great.

Right now it's difficult to help you since I don't know the code, sequence of things happening in the test, and the specific DOM where this is occurring. This is not to say what you're seeing isn't happening, I just need more info to recreate this.

**Comment by marktnoonan** [comment]
@emmanuelonah Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided.
