### ISSUE TITLE
cypress not opening in chrome 

### ISSUE THREAD

**Issue by SaajidNawwar** [cypress-io/cypress#22907]
### Current behavior

I followed the documentation on the official cypress site and installed cypress. Next after typing 'npx cypress open', the IDE opened. But when I choose chrome to run the E2E testing, a blank window appears and the terminal shows an error 'Passthrough is not supported, GL is disabled, ANGLE is '. I tried some other solutions such as enabling webgl on chrome but still it didn't work. Can I please know the reason for this error?
![Screenshot (850)](https://user-images.githubusercontent.com/68622804/180634469-a58d1d40-b82e-453f-8241-edaef4d60add.png)
![Screenshot 2022-07-24 112855](https://user-images.githubusercontent.com/68622804/180634498-4b4bac21-c138-4ca7-81ca-01a2d80825f0.png)

### Cypress Version

10.3.1

### Package Manager

npm

### Operating system

Windows

**Comment by tbiethman** [comment]
@SaajidNawwar thanks for the report. Could you run Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the entire set of logs here?

Can you also confirm the version of Chrome you have installed?

**Comment by tbiethman** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
