### ISSUE TITLE
watchForFileChanges flag doesn't work.

### ISSUE THREAD

**Issue by sajjadqa** [cypress-io/cypress#22908]
### Current behavior

Hi, 

I'm appending some text from a test into a JSon file. But when I run that test case then after completion of test Cypress reloads and start running that test again. It keeps running that test untill I stop it manually. I've turned off the flag of watchForFileChanges in cypress.config file. Don't know is it intended behavior or broken functionality of this configuration.

### Desired behavior

I think when we have turned off this watchForFileChanges flag then it should not rerun the test. Other than that this config is  working fine for other test cases. Don't know how to share the code with you so you can replicate this issue. 

### Test code to reproduce

Last command that runs in my test before rerun the test:

this.writeToJson(id)

in writeToJson file:
cy.writeFile(filename, raw_data)

<img width="213" alt="image" src="https://user-images.githubusercontent.com/42992227/180645731-e25e5135-77bb-49fa-8348-91740adc459c.png">

### Cypress Version

10.3.1

**Comment by tbiethman** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
