### ISSUE TITLE
Cypress run: --spec argument cannot be single quoted

### ISSUE THREAD

**Issue by SecondFlight** [cypress-io/cypress#2298]
### Current behavior:

An error occurs when a filepath for `--spec` is surrounded by quotes.

### Desired behavior:

I should be able to use quoted filepaths as per the docs.

### Steps to reproduce:

1) Use `cypress run --spec '(some spec)'` to start a test run, making sure to wrap `(some spec)` in quotes.

### Versions

Cypress 3.0.3
Windows 10

----

The following example is in the docs for using the `--spec` flag:

`cypress run --spec 'cypress/integration/examples/actions.spec.js'`

I have tried something similar, and it doesn't work. Here's the command and the resulting output:

`node_modules\.bin\cypress run --spec 'C:\(...)\SomeTest.js'`

This produces the following error:

> Can't run because no spec files were found.
>
> We searched for any files matching this glob pattern:
>
> `'C:\(...)\SomeTest.js'`

However, when I remove the quotes, it works:

`node_modules\.bin\cypress run --spec C:\(...)\SomeTest.js`

```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.0.3                                                                              │
  │ Browser:    Electron 59 (headless)                                                             │
  │ Specs:      1 found (SomeTest.js)                                                              │
  │ Searched:   ..\(...)\SomeTest.js                                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by brian-mann** [comment]
It can be quoted - it's just that its only **required** when using a glob pattern with the `*`.

I think in Windows it handles quotes differently which is why its failing. As it stands, using quotes in linux/osx regardless of the whether or not there is a glob always works.

In thats the case we could probably update the CLI to strip the quotes if you're on windows and not using a glob pattern.

**Comment by Saibamen** [comment]
Working:
`npm run cypress -- run --spec "cypress/integration/test/test.spec.js"`
and
`npm run cypress -- run --spec cypress/integration/test/test.spec.js`

Single quote `'` is converted into `"'cypress/integration/test/test.spec.js'"`

**Comment by flotwig** [comment]
The Windows shell will automatically remove double-quotes from path arguments, which is why this is happening:

![image](https://user-images.githubusercontent.com/1151760/53670438-be540500-3c48-11e9-956a-10c913e51eff.png)

As you can see, both `.config` and `".config"` are recognized as valid files, while `'.config'` is not.

We can probably trim single-quotes from the `--spec` argument as part of #3375 for convenience. For now, as a workaround, please use double-quotes for your spec filenames.

**Comment by Saibamen** [comment]
In my answer please see `--` before `run`

https://stackoverflow.com/questions/43046885/what-does-do-when-running-an-npm-command
