### ISSUE TITLE
cypress.env.json file not being found.

### ISSUE THREAD

**Issue by Zia-ullah** [cypress-io/cypress#23003]
### Current behavior

Hi,
I am Ziaullah, and I am working on Cypress 10.3.1 version.

I am working to use a cypress.env.json file and also able to get the values both form the cypress.env.json file as well as from cypress.config.js under env: in my test script using the test runner.
However when I try to rung the spec from command line and specify the file using --config-file option then getting as

Could not find a Cypress configuration file.
We looked but did not find a cypress.env.json file in this folder: D:\cyauto

I have also moved the cypress.env.json file under cypress folder but still received the same error.
Even I have tried the following combinations but non of them worked.

npx cypress run --config-file cypress.env.json  -b "edge" --headed  --spec "cypress\e2e\1-A\AdminNopCommerce.cy.js"
npx cypress run --config-file "cypress.env.json"  -b "edge" --headed  --spec "cypress\e2e\1-A\AdminNopCommerce.cy.js"
npx cypress run -C cypress.env.json  -b "edge" --headed  --spec "cypress\e2e\1-A\AdminNopCommerce.cy.js"
npx cypress run --config-file "cypress\cypress.env.json"  -b "edge" --headed  --spec "cypress\e2e\1-A\AdminNopCommerce.cy.js"

error and file contents image attached.
Thanks
Ziaullah

![CypressCommandLine](https://user-images.githubusercontent.com/53328142/181644892-49f44fa5-3b6a-490a-b26b-7022da9ff59c.png)

### Test code to reproduce

 npx cypress run --config-file cypress.env.json  -b "edge" --headed  --spec "cypress\e2e\1-A\AdminNopCommerce.cy.js"   

cypress.env.json
{
     "fsb":"q",
    "ouid": "admin",
    "opwd": "admin123",
    "viewportWidth":1360,
    "viewportHeight":800,
    "port":5555
}

### Cypress Version

10.3.1

**Comment by AtofStryker** [comment]
Hi @Zia-ullah. Thank you for opening an issue. I think there is some confusion here as `cypress.env.json` is not a config file, but rather a file that just contains environment variables. What happens if you run the following?

```
npx cypress run -b "edge" --headed --spec "cypress\e2e\1-A\AdminNopCommerce.cy.js"
```

Both `cypress.config.js` and `cypress.env.json` should be in the root directory of your project. Are the environment variables found?

On another note, we usually do not recommend checking in [cypress.env.json](https://docs.cypress.io/guides/guides/environment-variables#Option-2-cypress-env-json) into your project as it could contain sensitive environment variables.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
