### ISSUE TITLE
`CYPRESS_DOWNLOAD_PATH_TEMPLATE` set in `.npmrc` is not picked up by `npx cypress install`

### ISSUE THREAD

**Issue by rkrisztian** [cypress-io/cypress#23013]
### Current behavior

Added this to `.npmrc`:

```
CYPRESS_DOWNLOAD_PATH_TEMPLATE=https://my.corporate.site/desktop/\${platform}-\${arch}/cypress.zip
cypress_download_path_template=https://my.corporate.site/desktop/\${platform}-\${arch}/cypress.zip
```

=> `npx cypress install` still uses the default binary URL to download from.

### Desired behavior

If I put `CYPRESS_DOWNLOAD_PATH_TEMPLATE` in  `.npmrc`, Cypress should use it, similarly to the `package.json` way (see the workaround I showed).

Note: during `npm ci` it should be read too, but it isn't.

### Test code to reproduce

This code is rather for debugging than reproducing the bug. I added it to  `node_modules/cypress/lib/util.js` to see why it doesn't work:

```javascript
	  console.log(`${varName}=${process.env[varName]}`);
	  console.log(`${configVarName}=${process.env[configVarName]}`);
	  console.log(`${packageConfigVarName}=${process.env[packageConfigVarName]}`);
	  console.log(`${varName.toLowerCase()}=${process.env[varName.toLowerCase()]}`);
	  console.log(`${configVarName.toLowerCase()}=${process.env[configVarName.toLowerCase()]}`);
	  console.log(`${packageConfigVarName.toLowerCase()}=${process.env[packageConfigVarName.toLowerCase()]}`);
```

Result is:

```none
CYPRESS_DOWNLOAD_PATH_TEMPLATE=undefined
npm_config_CYPRESS_DOWNLOAD_PATH_TEMPLATE=undefined
npm_package_config_CYPRESS_DOWNLOAD_PATH_TEMPLATE=undefined
cypress_download_path_template=undefined
npm_config_cypress_download_path_template=https://my.corporate.site/desktop/${platform}-${arch}/cypress.zip
npm_package_config_cypress_download_path_template=undefined
```

=> NPM has `npm_config_cypress_download_path_template` as an environment variable, but Cypress checks `npm_config_CYPRESS_DOWNLOAD_PATH_TEMPLATE`.

### Cypress Version

9.7.0

### Other

Node version: v16.15.1
NPM version: 8.11.0

Current workaround: if I put the following into `package.json`, it works:

```javascript
{
	"config": {
		"CYPRESS_DOWNLOAD_PATH_TEMPLATE": "https://my.corporate.site/desktop/${platform}-${arch}/cypress.zip"
	}
}
```

But during `npm ci`, this variable is still not read.

**Comment by mjhenkes** [comment]
I put together a simple repo recreating this: https://github.com/mjhenkes/issue-23013-CYPRESS_DOWNLOAD_PATH_TEMPLATE

This issues appears to be that we pass the upper case `CYPRESS_DOWNLOAD_PATH_TEMPLATE` into util.getEnv, but the variable in the npm config is always set to lower case `npm_config_cypress_download_path_template: 'https://my.corporate.site/desktop/${platform}-${arch}/cypress.zip',`.

We have to be sensibly handling this elsewhere because i know that other env variables work from npm config.

Easy fix regardless.

**Comment by theothirteen** [comment]
@mjhenkes Is anyone working on this issue?

**Comment by emilyrohrbough** [comment]
@theothirteen No one is actively work on this. Please feel free to pick this up! Just let us know 😄

**Comment by NiharPhansalkar** [comment]
@emilyrohrbough Hello, can I try to work on this issue?

**Comment by York77** [comment]
@mjhenkes @emilyrohrbough just tried to reproduce and I found this issue was already fixed by this change: 
https://github.com/cypress-io/cypress/blob/74253149cf727451e8e13269219185675d1e7c6b/cli/lib/util.js#L537C32-L537C45  (#24664)

Tested with following env/config, and the binary can be downloaded and unzipped successfully.

Cypress version: 12.17.2
Node version:16.16.0
npm version: 8.11.0

in .npmrc, CYPRESS_DOWNLOAD_PATH_TEMPLATE=https://download.cypress.io/desktop/\${platform}-\${arch}/cypress.zip 

But I found that the "npx cypress install -f" will stuck there without any info show in console if the download path is invalid. For example, if I put CYPRESS_DOWNLOAD_PATH_TEMPLATE=https://somewrongdomain.com/desktop/\${platform}-\${arch}/cypress.zip, it will stuck without giving out any further error info.
