### ISSUE TITLE
Facing client socket gets disconnected issue before performing cy.visit() in jenkins

### ISSUE THREAD

**Issue by pragadeeshkv** [cypress-io/cypress#23079]
### Current behavior

I'm facing the same issue while integrating Cypress with Jenkins in my client network..

CypressError: "cy.visit() failed trying to load:

https://application url/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

o Error: & connection to the upstream proxy could not be established Client network socket disconnected before
secure TLS connection was established

### Debug logs

npm config set https-proxy=http://url/
npm config set proxy=http://url/
npm config set http-proxy=http://url/
npm config set no_proxy localhost, ...,...,..net
set HTTP_PROXY=http://url/
set HTTPS PROXY=http://url/
export NO PROXY=localhost, ...,...,..net
export NODE_TLS_REJECT_UNAUTHORIZED=0

### Cypress Version

8.7.0

### Package Manager

npm

### Operating system

Linux

**Comment by pragadeeshkv** [comment]
@flotwig Can you help me out on this

**Comment by rockindahizzy** [comment]
Hey @pragadeeshkv,

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by pragadeeshkv** [comment]
Couldn't able to resolve
