### ISSUE TITLE
noExit flag in module mode is ignored, and cypress exits

### ISSUE THREAD

**Issue by cdaringe** [cypress-io/cypress#2310]
### Current behavior:

per https://docs.cypress.io/guides/guides/module-api.html#Options, i can set `noExit`
```js
  await cypress.run({
    noExit: true, //! !process.env.CYPRESS_NO_EXIT,
    headed: !!process.env.CYPRESS_HEADED,
    record: !!process.env.CYPRESS_RECORD,
    config: {
      baseUrl
    },
    specs: t.context.uiTestFilenames
  })
```

cypress launched, but closes on complete.

### Desired behavior:

cypress stays open

### Steps to reproduce:

see above.

### Versions

 cypress 3.0.3
osx, electron

**Comment by brian-mann** [comment]
The flag actually comes from `miminist` and it's actually called `exit`, not `noExit`.

`--no-exit` is short for `{ exit: false }`. Any boolean based flag can be turned off this way.

To write it in the module API do this...

```js
cypress.run({ exit: false })
```

**Comment by cdaringe** [comment]
Cool thx!  The table probably could use a patch too reflect that

**Comment by runarb** [comment]
Docs are still not updated https://docs.cypress.io/guides/guides/module-api.html#cypress-run

**Comment by jennifer-shehane** [comment]
Hey everyone, our documentation is open source and contributions are welcome. 😄 Thanks to @ben-turner for opening a PR to change the docs https://github.com/cypress-io/cypress-documentation/pull/2012

**Comment by sirbarrence** [comment]
The type definitions on https://github.com/cypress-io/cypress/blob/a64b72a5da5b4031765c721817733b971dd760eb/cli/types/cypress-npm-api.d.ts#L69 still say the option is called `noExit`, which does nothing. In a typescript project, when I use `exit: false`, I have to tell the compiler to ignore it in order to make the program compile.

Should this issue be reopened to address the incorrect type def or should it be a new issue?

**Comment by brian-mann** [comment]
New issue for the types plz.
