### ISSUE TITLE
cy.screenshot() not respecting viewport width > 1280

### ISSUE THREAD

**Issue by sharmarahul** [cypress-io/cypress#2313]
### Current behavior:

I am using `cy.screenshot()` at element level and it takes screenshots at 1280 width and no greater. Even when `viewportWidth` is set to `1440` which is the preset value for `macbook-15` it doesn't take screenshot for this width. This seems to be the issue whether the config is read through `cypress.json` or command line flags. Also, when built in preset is used as `cy.viewport('macbook-15')` it doesn't respect this at the time of screenshot. During the test run when I manually drag the browser window and make it bigger, the screenshot seems to work as expected.

Note: This is not in headless(read the issue around headless xvfb limitations) but in headed Chrome.

### Desired behavior:

`cy.screenshot()` should respect configured viewport size.

### Steps to reproduce:

Run any responsive site and take screenshot as preset `macbook-15` viewport configuration. The output screenshot is not the right size.

### Versions

Cypress version: 3.0.3
OS: Mac OSX
Browser: Chrome

**Comment by chrisbreiding** [comment]
It's not possible to take a screenshot that's larger than the browser width. We scale the viewport of the app under test when tests are running so it fits within the browser and tests run consistently, but we do not scale the viewport for screenshots because it would result in inconsistent screenshots. 

Is there a problem with manually resizing the browser to be large enough?

**Comment by sharmarahul** [comment]
Well manually resizing the browser works but for automated tests that's a pain. I have just checked that Cypress browser API docs say there is a way to pass in flags at the time of browser launch. Chrome has flags for browser size. Is this the only way to resize the browser or does cypress support it in another way?

**Comment by chrisbreiding** [comment]
Yes, there isn't an API for setting browser size, so browser flags are currently the only way you could potentially do it.

**Comment by sharmarahul** [comment]
@chrisbreiding The issue with browser flags is that Cypress doesn't support Chrome headless so the flags don't work with that. So, the only option remains is to use Electron which doesn't support the chrome `--window-size` flag. Is there a way Cypress supports resizing Electron browser?

**Comment by chrisbreiding** [comment]
For Electron, instead of an array of flags, you can return an object from the `before:browser:launch` event that will be used to instantiate the Electron browser window. Those options are [documented here](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions).

```javascript
// plugins file

module.exports = (on) => {

  on('before:browser:launch', (browser) => {
    if (browser.name === 'electron') {
      return {
        width: 1440,
        height: 960,
      }
    }
  })

}
```

I see that we're missing this from our [Browser Launching doc](https://docs.cypress.io/api/plugins/browser-launch-api.html), so I [created an issue](https://github.com/cypress-io/cypress-documentation/issues/866) to make sure we add it.

**Comment by jennifer-shehane** [comment]
Closing this issue as resolved. @sharmarahul please comment if these suggested flags did not resolved your issue.
