### ISSUE TITLE
Unable to map an element. The message "it is being covered by another element" is shown 

### ISSUE THREAD

**Issue by osoriosara98** [cypress-io/cypress#23180]
### Current behavior

I'm unable to map a button that has multiple elements in it. 
![image](https://user-images.githubusercontent.com/102264353/183315598-9999425b-6a41-42d1-8c0f-c4e4f2aac2a8.png)

### Desired behavior

To be able to click on that button 

### Test code to reproduce

cy.xpath('//*[@id="cmpsMain"]/cmps-auth-login/div/div[4]/div/div/div[2]/form/div[4]/div[2]/button').click() // everytime you have gaps within a class you need to use dots 
        cy.wait(20000) 
        cy.get(".coaching-button.row").eq(0).click() 
 

### Cypress Version

10.3.0

**Comment by AtofStryker** [comment]
Hi @osoriosara98. Thank you for opening an issue. From what I can see, this is expected behavior. The element you are trying to interact with is covered by another element. To force interaction, you could run:

```
cy.get(".coaching-button.row", { force: true }).eq(0).click()
```
If this does not solve your issue, would you be able to provide a reproduction? Also, we would highly recommend reading our guide on [selecting elements](https://docs.cypress.io/guides/references/best-practices#Selecting-Elements) if you can to avoid brittle xpath selectors where possible!

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
