### ISSUE TITLE
Cypress side bar disappears and the test is "paused" after automatic redirection

### ISSUE THREAD

**Issue by leobaLMK** [cypress-io/cypress#23208]
### Current behavior

When you go to a page with "cy.visit" and this one has an automatic redirection to another page with a different url base, the side bar on the left of Cypress disappears and the test pauses indefinitely.

Nothing more happens while the test still has steps to perform on the page as you can see on the screenshot. 

![image](https://user-images.githubusercontent.com/110894699/183626056-0946ff5c-c285-418d-8788-e6e00a94436a.png)

This problem also appears on another test where after an automatic redirection from one page to another, the side bar disappears and the test is "paused" without displaying anything in error.

### Desired behavior

Be able to continue the test steps (e.g. filling in input elements) on the page generated by the automatic redirection.

### Test code to reproduce

I am not able to send you the code since it contains confidential data.

To reproduce you have to make a "cy.visit" on a page which has an automatic redirection as of its appearance towards another page with a different base url.

### Cypress Version

10.4.0

### Other

I have chromeWebSecurity: false in my config file

**Comment by marktnoonan** [comment]
Just a note, @tbiethman and I were looking at a kind of similar issue yesterday: https://github.com/cypress-io/cypress/issues/17367

In looking at logs it led me to https://github.com/cypress-io/cypress/issues/14175, which seemed possibly antivirus related, and Sophos has recently patched https://support.sophos.com/support/s/article/KB-000044041?language=en_US

It's not clear that this is definitely related, but the end state is the same, the Cy browser ends up showing the application in `top` instead of in its own iframe, so it might be worth considering together.

**Comment by AtofStryker** [comment]
Hi @leobaLMK. Thank you for opening an issue. Is it possible to make a quick reproduction example for us to run on our end and get the same results. This almost looks like frame busting @marktnoonan, but I'm not entirely sure. @leobaLMK have you tried using the `experimentalModifyObstructiveThirdPartyCode` flag and seeing if the issue persists?

**Comment by andreas-soroko** [comment]
Hello, 

we investigated exactly the same problem. Unfortunately, I can not provide a reproduction example.
We set our `baseUrl` to our Frontend application which makes an redirect ( `oidc` ) to our backend to the login page.

Is there anything that we can provide? Logs what ever?
