### ISSUE TITLE
Next.js CT apps have "Component Testing Mismatched Dependencies" warning for deps it doesn't need.

### ISSUE THREAD

**Issue by ZachJW34** [cypress-io/cypress#23216]
### Current behavior

When booting up a Next.js app for CT testing, a warning for `Component Testing Mismatched Dependencies` is displayed on the "Open Browser" page. This warning says that the application is missing "webpack", but Next.js applications don't require webpack since Next bundles it internally.

![Screen Shot 2022-08-09 at 10 28 34 AM](https://user-images.githubusercontent.com/25158820/183699351-91c8b5d6-f726-45b6-8b34-f85ad36c7b0c.png)

### Desired behavior

The warning should not show when launching Next.js Component Testing

### Test code to reproduce

1. `npx create-next-app my-next-app && cd my-next-app`
2. `npm i -D cypress`
3. `npx cypress open`
4. Walk through CT setup, "Choose a browser" page will show misleading warning.

### Cypress Version

10.4.0

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23216?planning-poker) with ZenHub @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by marktnoonan** [comment]
Looks like a pretty small change. But I'm not totally sure at a glance where `getBundlerDependency` is being called when the `nextjs` `dependencies` function doesn't actually call it, and already ignores the `bundler` argument. Which would have been my naive assumption about the change needed here.

**Comment by mike-plummer** [comment]
My guess is this is the line giving the error: `ProjectConfigManager.ts` -`const result = await isDependencyInstalled(bundler, this.options.projectRoot)` - it treats the bundler as a required dependency even if it isn't listed in the dependencies. Would need to rework the wizard deps logic to remove this condition and then ensure other frameworks have their bundler listed as a dependency

**Comment by JasonFairchild** [comment]
Just wanted to add that I have experienced this. I thought it might be a bug, so this is reassuring to find. But to be clear, if I'm using nextjs with 'latest' version, then I shouldn't expect to see any mismatched dependency warning, right? I can also confirm that I've run into no problems so far, but I've only written a few component tests, so not super in depth yet from that perspective.

I also happened to notice that the warning can stack up multiple times. Maybe because I was modifying configuration that would cause the CT runner experience to restart to some degree and add another warning? Small thing, but maybe you want to think about improving it as well:
![image](https://user-images.githubusercontent.com/56280950/184440222-71a04cd0-51f2-4041-b9aa-05b8ee7315ca.png)

**Comment by lmiller1990** [comment]
@JasonFairchild I think you are right in suggesting the mismatched bug was introduced in https://github.com/cypress-io/cypress/issues/23216#issuecomment-1213493767 - that's where we added the dependencies check feature, but missed the edge case of Next.js and the inline webpack they ship.

Also the stacking errors looks bad, that's definitely a separate bug we should address.

**Comment by lmiller1990** [comment]
Okay, fixed the duplicate warnings :facepalm: https://github.com/cypress-io/cypress/pull/23339

We will look into Next.js warnings separately and track progress in this issue.
