### ISSUE TITLE
Unable to update CSV file data from each it block

### ISSUE THREAD

**Issue by ChethanCP37** [cypress-io/cypress#23223]
### Current behavior

CSV file is updated in first it block and same file data is consumed by other it blocks

### Desired behavior

New data is shared in each it block to update csv file and same should be accepted to update CSV file

### Test code to reproduce

I don't have it in git 

### Cypress Version

10

**Comment by rockindahizzy** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
