### ISSUE TITLE
When config files are created during onboarding, keep them collapsed

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#23260]
During onboarding, when config files are created, keep them collapsed on the "Configuration Files" screens. If they have warnings (changes required, etc.), then start with them open.

<img width="625" alt="Screen Shot 2022-08-10 at 4 55 42 PM" src="https://user-images.githubusercontent.com/7063516/184018379-906985d4-be3a-4a15-b48c-ced29a1287ee.png">

**Comment by brian-mann** [comment]
I agree that all fields could be collapsed by default (except for conflicts as you suggested) with the exception of config. 

Config should always be open because this is a one time operation and it’s important the user understand and see how their setup was translated into the lens of how that’s expressed through config. The goal here is to help orient, train, and teach the user what goes where to help them understand what’s available to them in order to further customize the config. 

For instance the e2e and component functions are how you write plugins that can’t be autogenerated by us - it’s code the user has to write. There’s no UI pattern for doing this and we can’t lead you automatically to the things you’re trying to accomplish. Therefore it’s important to introduce the surface area that they will use in the future.

**Comment by brian-mann** [comment]
Although I'm not convinced the config accordion should be collapsed by default, I'm okay with collapsing it by default and we'll keep an eye out for confusion from users.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23260?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
Is there any case were we need changes/warnings except for `cypress.config.js`? This should only happen when setting up E2E or CT in a project that has already got 1 testing type, and when we update the `cypress.config.js`, something goes wrong.

I don't know of any cases where this would happen off the top of my head, so what is the deliverable here? I was going to suggest "open `cypress.config.js` by default", but it looks like this isn't something we are doing based on the above comment from @brian-mann?

**Comment by pstakoun** [comment]
We should not be adding any warnings, etc outside of existing patterns. The use case is simply to reduce the amount of information the user is shown on this "config success" screen, so showing them the files created rather than all of their contents as well. @lmiller1990 @rockindahizzy maybe I'm not understanding the scope here - are these cases where the change is not as simple as: collapse file contents by default if and only if it is in the success state (green with checkmark)?

**Comment by rockindahizzy** [comment]
@pstakoun, that clears it up for me 👍
