### ISSUE TITLE
Blank pages while clicking through steps in passed Cypress tests

### ISSUE THREAD

**Issue by tragsdale7** [cypress-io/cypress#23267]
### Current behavior

I run cypress tests and they pass. I then expand the tests to display the steps. Notice that some of them have an "eye" icon to the right with a slash. Hovering my mouse over I receive "This element is not visible" message. The UI for these steps is white and completely blank.

![image](https://user-images.githubusercontent.com/39227317/184054595-4e8037bb-ee37-497f-9fb9-eaa2c03bac63.png)
![image](https://user-images.githubusercontent.com/39227317/184054650-36eda750-98cc-4a75-aa92-b0c274f659f2.png)

### Desired behavior

I watched the cypress tutorials on youtube and the instructor did not get any of these element is not visible messages. I am using the exact same code as them. It appears the UI should highlight, for example, the button that was clicked. Or, if I get on the get step, it should highlight the element that was retrieved.

### Test code to reproduce

describe("home page", () => {
  beforeEach(() => {
    cy.visit("http://localhost:3000")
    cy.clearLocalStorage();
  })

  context("Hero section", () => {
    it("the h1 contains the correct text", () => {
      cy.getByData("hero-heading").contains(
        "Testing Next.js Applications with Cypress"
      )
    })

    it("the features on the homepage are correct", () => {
      cy.get("dt").eq(0).contains("4 Courses")
      cy.get("dt").eq(1).contains("25+ Lessons")
      cy.get("dt").eq(2).contains("Free and Open Source")
    })
  })

  context("Courses section", () => {
    it("Course Testing Your First Next.js Application", () => {
      cy.getByData('course-0')
        .find('a')
        .eq(3)
        .click()
      cy.location('pathname').should('eq', '/testing-your-first-application')
    })

    it("Testing Foundations", () => {
      cy.getByData('course-1')
        .find('a')
        .eq(3)
        .click()
      cy.location('pathname').should('eq', '/testing-foundations')
    })

    it("Cypress Fundamentals", () => {
      cy.getByData('course-2')
        .find('a')
        .eq(3)
        .click()
      cy.location('pathname').should('eq', '/cypress-fundamentals')
    })
  })
})

**command.ts file**
/// <reference types="cypress" />

Cypress.Commands.add('getByData', (selector) => {
  return cy.get(`[data-test=${selector}]`);
});

### Cypress Version

10.4.0

**Comment by rockindahizzy** [comment]
Hi @tragsdale7, is it possible to share the repo, or the tutorials that you are following?

**Comment by tragsdale7** [comment]
Hey @rockindahizzy 

https://github.com/tragsdale7/cypress-project.git

I'm new to github. Let me know if this^ has what you need

I've been following the lessons recently posted by the Cypress io youtube channel:
https://www.youtube.com/watch?v=x0QuiEJUf6s
https://www.youtube.com/watch?v=Q1rHmOYyGDo

**Comment by mike-plummer** [comment]
@tragsdale7 This is a common issue with Single Page Applications like NextJS which inherently load their resources (javascript, css, etc) asynchronously (client-side rendering). When Cypress visits a page (`cy.visit`) it waits for the page load event to fire which, in this case, happens before the SPA is finished with its client-side rendering. This tells Cypress to start the test before the app is really "ready" - the DOM elements exist and Cypress is able to find them by parsing the page's markup, but the styling hasn't been loaded/parsed so it *appears* that there's nothing on the page.

You can verify this is the case by making a simple adjustment to your test:

```
cy.getByData('course-0').should('be.visible')
        .find('a')
        .eq(3)
        .click()
```

The `should('be.visible')` assertion will have Cypress wait until the element is rendered to the screen (likely just a few tens of milliseconds) before proceeding. Note that your test is perfectly valid as-is - the DOM content is there and is structured correctly, but screenshots and videos of your tests will be misleading.

A common tactic for addressing this more holistically is to add logic to a `beforeEach` hook to ensure a known element is visible so that all tests are delayed until the SPA is really "ready".

Hope this helps!

**Comment by tragsdale7** [comment]
@mike-plummer This makes a lot of sense. Thanks for the insight!
