### ISSUE TITLE
Index.js doesn't support import statement

### ISSUE THREAD

**Issue by Srutherford2407** [cypress-io/cypress#23290]
### Current behavior

I am having an issue with @faker-js/faker within the index.js file. The index.js does not allow for the import { faker } from '@faker-js/faker'; statement (even though importing it this way does create the correct references). When imported as const faker = require("@faker-js/faker"); is does not create the correct references to faker and thus the data is not created. Here is my index.js for reference.

I have tired a series of different option but I am unable to get faker to via the `const faker = require("@faker-js/faker");` within the index.js. I also tired to remove that completely from the index.js and create a module.export of my faker data but then cypress fails on start-up with a module error.

### Test code to reproduce

```
const faker = require("@faker-js/faker");

//For Cucumber Integration
const createEsbuildPlugin =
  require("@badeball/cypress-cucumber-preprocessor/esbuild").createEsbuildPlugin;

const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");

const nodePolyfills =
  require("@esbuild-plugins/node-modules-polyfill").NodeModulesPolyfillPlugin;

const addCucumberPreprocessorPlugin =
  require("@badeball/cypress-cucumber-preprocessor").addCucumberPreprocessorPlugin;
  
module.exports = async (on, config) => {
  const firstName = faker.name.firstName();
  const lastName = faker.name.lastName();
  await addCucumberPreprocessorPlugin(on, config); // to allow json to be produced
  // To use esBuild for the bundler when preprocessing
  on(
    "file:preprocessor",
    createBundler({
      plugins: [nodePolyfills(), createEsbuildPlugin(config)],
    })
  );
  on("task", {
    freshUser() {
      user = {
        id: null,
        loyalty_id: faker.random.alphaNumeric(10),
        email: firstName + "." + lastName + "@gmail.com",
        password: faker.internet.password(20, false, /^[a-zA-Z0-9!@#%]+$/),
        phone_number: faker.phone.phoneNumber("##########"),
        preferred_store_id: "7909108e-0b44-4182-9124-ba3180f24212",
        birth_day_of_month: faker.datatype.number({ min: 1, max: 31 }),
        birth_month: faker.datatype.number({ min: 1, max: 12 }),
        address: faker.address.streetAddress(true),
        city: faker.address.city(),
        postal_code: faker.address.zipCode("#####"),
        state: faker.address.state(),
      };
      return user;
    },
  });
  return config;
};

```

### Cypress Version

10.4

### Node version

16.3

### Operating System

Windows 10

**Comment by AtofStryker** [comment]
Hey @Srutherford2407 . Thank you for opening an issue. In this case, what is `index.js`? Is it a plugins file? It's a bit unclear from the example provided.

By default, `index.js` will not support `import` statements unless the package is an ES Module or is a Typescript file. Otherwise, the default is commonjs, which should only allow `require` statements. This [article](https://flaviocopes.com/es-modules/) gives a good introduction.

Either way, your problem should be solvable, via commonjs:

```
const { faker } = require("@faker-js/faker");
```

I threw together a quick [repository](https://github.com/AtofStryker/cypress-issue-23290) that showcases this, which you can invoke the files via `node index.js` (For CommonJS) or `node index.mjs` (for ES Module).

I am going to close this issue out, but if this continues to be an issue for us, please let us know and happy testing!
