### ISSUE TITLE
Cannot use html-webpack-plugin with @cypress/webpack-dev-server and Yarn 1.x

### ISSUE THREAD

**Issue by sudocovik** [cypress-io/cypress#23334]
### Current behavior

When using Cypress `webpack-dev-server` with `html-webpack-plugin` as a project dependency or a dependency of another dependency `Yarn` complains that `html-webpack-plugin` is trying to use the same destination folder as `html-webpack-plugin` specified in cypress' `webpack-dev-server`.
The warning message is:

`Pattern ["html-webpack-plugin@^5.5.0"] is trying to unpack in the same destination "/home/node/.cache/yarn/v6/npm-html-webpack-plugin-5-5.5.0-c3911936f57681c1f9f4d8b68c158cd9dfe52f50-integrity/node_modules/html-webpack-plugin-5" as pattern ["html-webpack-plugin-5@npm:html-webpack-plugin@^5"]. This could result in non-deterministic behavior, skipping.`

After `yarn` completes the `html-webpack-plugin` is missing from `node_modules` (as warning says).

### Desired behavior

`html-webpack-plugin` should be resolved and installed correctly.

### Test code to reproduce

Please see [Covik/cypress-dev-server-yarn-issue](https://github.com/Covik/cypress-dev-server-yarn-issue).

### Cypress Version

10.4.0

### Node version

18.7.0 and version bundled with Cypress 10.4.0

### Operating System

Linux 5.19

### Other

After digging a bit this a problem with Yarn version 1 and has been resolved in Yarn version 2.
My understanding is Cypress does not play well with Yarn 2 ATM so I crossed this solution.
Even though this is not Cypress' problem per se it could be resolved with a couple of changes in `package.json`.

The 'problematic' lines in `package.json` are:
```
"html-webpack-plugin-4": "npm:html-webpack-plugin@^4",
"html-webpack-plugin-5": "npm:html-webpack-plugin@^5",
```
When `yarn` resolves these dependencies it downloads `hwp` (`html-webpack-plugin`) version 5 into `node_modules/html-webpack-plugin-5` and version 4 into `html-webpack-plugin-4`.
However, before these folder are created there is a temporary download folder in `~/.cache/yarn` which uses package name, resolved version and some kind of hash.
So, when yarn downloads the `hwp` specified in project's `package.json` it resolves the same name, same version and hash and tries to download it in the same folder.
Because this folder is not empty and contains files from Cypress' `hwp-5` it complains about non-deterministic behavior and skips installing the module - even though they are completely the same.
I would assume if you specified different version (ie. lock `hwp` in your project to 5.3.0) there would be no problems.

I didn't dug deeper in how yarn works, but executing `yarn add -D html-webpack-plugin` after initial `yarn install` seems to add the package correctly without warnings - but this is weird workaround and requires extra steps in CI.

My proposed solution is to add `hwp` v4 and v5 as a single dependency:
```
"html-webpack-plugin": "^4.0 || ^5.0"
```
This approach always resolves to `node_modules/html-webpack-plugin` and a bonus is you don't download `hwp` v4 if you are not using it (and vice versa).
This is my naive approach, I'm not sure if this is going to break something else in Cypress project.

Extra: I'm not sure I understand why these are listed as dependencies and not peerDependencies.
If I'm adding Cypress `webpack-dev-server` I mostly likely have `webpack` installed and there is a good chance I have `html-webpack-plugin` too.

**Comment by lmiller1990** [comment]
Hi! This is a known issue, see:

- https://github.com/cypress-io/cypress/issues/22577
- https://github.com/cypress-io/cypress/issues/22398#issuecomment-1198926457

We are working on eliminating the `html-webpack-plugin` dependency entirely - you can follow some progress [in this draft PR](https://github.com/cypress-io/cypress/pull/22736). Once that is done, this should be a non issue.

**Comment by ZachJW34** [comment]
Since we were adding new support for `Angular CT`, I put the html-webpack-plugin replacement work on the backburner. @Covik have you tried removing the `@cypress/webpack-dev-server` dependency? As of Cypress 10.0, having this dependency installed is no longer a requirement (unless you are doing something custom) since we ship the dependency with the Cypress binary. Though what you have pointed out is a valid issue (and is why I have WIP trying to remove it), you should be able to remove the problem by removing the dependency.

**Comment by Covik** [comment]
Thanks @lmiller1990, I managed to workaround the issue in the same way you proposed.

@ZachJW34 My framework (Quasar Vue) dynamically generates webpack config (and exports it through JS function) so I must use `@cypress/webpack-dev-server`.
I've seen your PR about removing the `html-webpack-plugin` and I understand you have other priorities but could my proposed solution be a temporary fix until you completely ditch the dependency? Right know, library & framework authors requiring `@cypress/webpack-dev-server` have to keep using Cypress 9 or tell users to add `resolutions` to their package.json (I could be wrong, maybe dependencies can add `resolutions` too?).

**Comment by ZachJW34** [comment]
@Covik could you post your Cypress config? You can specify a webpack configuration inside the config without using the custom dev-server, something like:

```js
const myCustomWebpackFunction = require('./my-custom-webpack-function')

module.exports = {
  component: {
    devServer: {
      framework: 'vue',
      bundler: 'webpack',
      webpackConfig: myCustomWebpackFunction(...)
    }
  }
}
```

The dev-server will also look for a `webpack.config.js` in the project root that it will use if it exists.

The reason we have them as `dependencies` and not `peerDependencies` is because we include `@cypress/webpack-dev-server` in the Cypress binary and need those dependencies installed. If we only published it as an npm package then we would utilize `peerDependencies`.

If you can't utilize the suggestions above, then we can prioritize the `html-webpack-plugin` replacement work but I'd like to see if the options we provide for the default CT configuration can suit your use-case before looking further.

**Comment by Covik** [comment]
@ZachJW34 I have to use the function signature version because the function for getting webpack config returns a Promise.
At the moment I cannot use the top-level await in my project, Cypress does not manually await the promise if I just call the function without await nor does `defineConfig()` accept (async) function as it's only parameter.

My proposed solution was to include `html-webpack-plugin` like this:
```
"html-webpack-plugin": "^4.0 || ^5.0"
```
but I assume you need both of these in main Cypress binary?
Either way, if you need it Cypress binary couldn't you add them as `peerDependencies` and then include those as `dependencies` in package.json of the binary? My assumption here is that this file does exist?

**Comment by ZachJW34** [comment]
@Covik it's possible to move the dependencies around but I would like them to be encapsulated to the `@cypress/webpack-dev-server`. Would it help to have the `webpackConfig` property allow a promise i.e. `webpackConfig: {} | Promise<{}>`?

**Comment by lmiller1990** [comment]
We have an issue for making that a promise: https://github.com/cypress-io/cypress/issues/23302

Some similar discussion here: https://github.com/cypress-io/cypress/issues/22390

**Comment by IlCallo** [comment]
@ZachJW34 hey there, Callo from Quasar core team here
Seems like both us and Covik are working on supporting Cypress 10 separately and hitting the same bumps.
Last problem we hit last week is the html plugin one.

Another solution to this problem would be to re-export `@cypress/webpack-dev-server`/`@cypress/vite-dev-server` types from Cypress, since we cannot use it into TS projects otherwise unless we add them as dependencies, and this cause the aforementioned html-plugin error

**Comment by lmiller1990** [comment]
Which types do you want to export? Some of them might be available via the `Cypress` object: https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts#L3063-L3064.

**Comment by IlCallo** [comment]
We don't need a particular type, the problem arise when importing the whole package, since there doesn't seem to be an ambient file declaring the types for that package

![image](https://user-images.githubusercontent.com/10036108/185102878-5bc1c927-3289-4886-80ef-d2fd5a8598f9.png)

Unless there's another way to import those `devServer` symbols directly from `cypress` package, eg 
```ts
import { devServer } from 'cypress/webpack-dev-server';
```

Note that in this case `webpack-dev-server` is a subdirectory, not part of a scoped package name.
I haven't found any docs about this kind of import syntax, so I guess it doesn't exist.

I also tried to explore the downloaded `cypress` package folder to locate where exactly `@cypress/webpack-dev-server` bundled dep is stored, but I couldn't find it, so it's unclear to me what do you mean by "bundled within Cypress package"

Let me know if it's not clear, I'll try to rephrase

**Comment by Covik** [comment]
@ZachJW34 

> it's possible to move the dependencies around but I would like them to be encapsulated to the @cypress/webpack-dev-server.

I must say it feels weird that dependencies required by a package A are defined in a package B

> Would it help to have the webpackConfig property allow a promise i.e. webpackConfig: {} | Promise<{}>?

Yes, if you follow the https://github.com/cypress-io/cypress/issues/22390 and as @IlCallo already pointed in a reply here, everything that works for Quasar team wil work for me.

---

As @IlCallo already pointed out, is it possible to make a `@cypress/webpack-dev-server` bundled with main `cypress` package, with all the dependencies transpiled?
For instance, `@cypress/react` is bundled in `cypress` and published as a standalone package.
If you open [@cypress/react on NPM](https://www.npmjs.com/package/@cypress/react) it clearly suggest you should import from the main `cypress` package, import from the scoped package is for advanced use cases.

If I open `node_modules/cypress/react` in my project, there is only `dist`, `package.json`, `README.md`, `CHANGELOG.md`.
I think bundling the `@cypress/webpack-dev-server` in the same way would solve all of the issues plus if any future user having a more complex project (in terms of bundler configuration), like Quasar, cannot easily add Cypress to their project, they can fallback to manually importing webpack/vite dev server and configure it themselves without downloading extra packages or encounter issues with `html-webpack-plugin`.

**Comment by lmiller1990** [comment]
Hmm I am not sure we want to bundle all those deps: https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/package.json#L20-L28

We probably don't want to bundle `webpack-dev-server` or `fs-extra` in the cli package. I think we can actually solve this, though:

| name | strategy |
| ---- | ---- |
| find-up | tiny transpile |
| fs-extra | can we just us `fs` from Node? |
| html-webpack-plugin-4 | Replace with lightweight alternative https://github.com/cypress-io/cypress/pull/22736 |
| html-webpack-plugin-5 |  Replace with lightweight alternative https://github.com/cypress-io/cypress/pull/22736 |
| local-pkg | tiny, transpile |
| speed-measure-webpack-plugin | this is for benchmarks, should be a devDependency |
| tslib | Should this be a devDevdenency? |
| webpack-dev-server | peerDep, reasonable to ask people to install this |
| webpack-merge | Small, can probably transpile |

It seems like `html-webpack-plugin` is the main problem, though - once we complete https://github.com/cypress-io/cypress/pull/22736 we could inline that with `@cypress/webpack-dev-server` (no need for `html-webpack-plugin` as a dep anymore). This would also make `cypress/webpack-dev-server` small enough to potentially ship in the CLI, too.

What does everyone think of this?

I think making webpackConfig an async function is pretty straight forward, we should also solve that, it's a quick win. Tracking that here: https://github.com/cypress-io/cypress/issues/23302. I'm busy with other Cypress work for this week + next week, but if I can sneak in some time I might try get this one... otherwise I can post some tips if an outside contributor is motivated and has some bandwidth?

**Comment by IlCallo** [comment]
I think that's a good plan, I expecially hope in https://github.com/cypress-io/cypress/issues/23302 since it looks simpler to implement than creating your own replacement for `html-webpack-plugin`

**Comment by lmiller1990** [comment]
I am working on something in this area: https://github.com/cypress-io/cypress/pull/23605

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23334?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
@baus a little hard to estimate - what's the deliverable? Is it to get https://github.com/cypress-io/cypress/pull/22736 completed?

**Comment by warrensplayer** [comment]
@lmiller1990 @baus I am also not sure which of the many options mentioned here is the desired direction for a solution.  Estimating based on the same assumption as @lmiller1990 that it is to complete #22736

**Comment by lmiller1990** [comment]
I think it's actually okay for issues to be a bit ambiguous, it's just important to keep in mind you need to do some exploration and decision making, so include that wiggle-room in your estimates. "We cannot do this" or "I think we should something else based on my learnings" is also a valid outcome.

**Comment by rockindahizzy** [comment]
Just to add my $0.02, I think prescribing a solution to a problem is not ideal as it takes away a lot of the exciting factors from a development perspective. On the other hand, we are trying to be proactive and accurate when it comes to communicating our ability to deliver, so we should make efforts to be clear during planning when an issue has potential for scope creep, the potential to not be completed in the time estimated, and possibly extending over multiple sprints.

For this issue in particular, we discussed that the combination of #22736 and #23302 would resolve this issue.

**Comment by marktnoonan** [comment]
it seems like https://github.com/cypress-io/cypress/pull/22736 and https://github.com/cypress-io/cypress/issues/23302 are both in progress so I'm inclined to dial in the estimate based on those and not put one on this issue.

**Comment by cellog** [comment]
just a quick note to say that we have 3 repositories. 2 of them have been successfully upgraded to both Storybook 6.5.15 and Cypress 12. One is stuck on Cypress 9, with Storybook 6.5.15. I can't see any configuration difference between the two of note, but this bug is holding the upgrade back.

**Comment by cellog** [comment]
I worked around it with a crazy hack. I added this to my `postinstall` script in `package.json` (other things stripped):

```
    "postinstall": "cp -r node_modules/html-webpack-plugin node_modules/html-webpack-plugin-5",
```

**Comment by krzysztof-hellostudio** [comment]
for anyone interested in "neater" solution use package alising in yarn:  "html-webpack-plugin": "npm:html-webpack-plugin@4.5.0"
