### ISSUE TITLE
Running Cypress in WSL2 caused "gpu_memory_buffer_support_x11.cc(44)]" ERROR

### ISSUE THREAD

**Issue by JasmineLaiHua** [cypress-io/cypress#23343]
### Current behavior

Hi All,

I have installed Cypress in my WSL2 system and all dependencies ( https://docs.cypress.io/guides/continuous-integration/introduction#Ubuntu-Debian).
But when I run this command node_modules/.bin/cypress open it throws out an ERROR

> [13857:0815/161856.512323:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

### Cypress Version

^10.4.0

### Node version

v16.15.0

### Package Manager

npm

### Package Manager Version

8.5.5

### Operating system

Linux

### Operating System Version

20.4

**Comment by ryan-silicon-digital** [comment]
Hi I am having the same issue. the exact error message I receive is: 
'[2899:0817/180152.338924:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.'

Debug logs
No response

Cypress Version
10.6.0

Node version
v14.17.0

Package Manager
npm

Package Manager Version
6.14.13

Operating system
Linux Ubuntu

Operating System Version
20.04

Other
No response

**Comment by rachelruderman** [comment]
Hi @JasmineLaiHua and @ryan-silicon-digital ! I've seen this error as well, I mentioned it in https://github.com/cypress-io/cypress/issues/23326. Out of curiosity, what impact does this have on your tests? Is it a non-failing error? Do your tests hang when you see it?

**Comment by 3pns** [comment]
I am having the same problem on CI using cypress docker image cypress/included:10.6.0 
Everything was woking before I upgraded from cypress 8
It works on my Mac OS M1 but not on CI

Debug logs ( from CI )
```
Proxy Settings: none detected
Environment Variables:
CYPRESS_CACHE_FOLDER: /root/.cache/Cypress
Application Data: /root/.config/cypress/cy/development
Browser Profiles: /root/.config/cypress/cy/development/browsers
Binary Caches: /root/.cache/Cypress
Cypress Version: 10.6.0 (stable)
System Platform: linux (Debian - 11.3)
System Memory: 8.37 GB free 5.75 GB
$ CYPRESS_BASE_URL=http://web_app:3500/ cypress run --headless --spec "cypress/e2e/all.cy.js"
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[776:0818/055649.635682:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

Cypress Version
10.6.0

Node version
v16.14.2

Package Manager
yarn

Package Manager Version
yarn@3.1.0

Operating system
Debian GNU/Linux 11 (bullseye) ( cypress/included:10.6.0 docker image )

Operating System Version
20.04

Other
Gitlab-CI script :

```
  script:
    - cd apps/myapp
    - yarn # cypress 10 ts error fix  https://github.com/cypress-io/cypress-docker-images/issues/688
    - cypress verify
    - cypress info
    - CYPRESS_BASE_URL=http://web_app:3500 cypress run --headless --spec "cypress/e2e/all.cy.js"
```

**Comment by ryan-silicon-digital** [comment]
Hi @rachelruderman. The error is occurring for me when following the [getting started](https://docs.cypress.io/guides/getting-started/installing-cypress) guide. at the [opening the app](https://docs.cypress.io/guides/getting-started/opening-the-app#What-you-ll-learn) step, running the command ```npx cypress open```

**Comment by rachelruderman** [comment]
> When I look at the video artifacts for each tests it shows the page loading then crashing with the error "Application error: a client-side exception has occured (see the browser console for more information )".

Hi @3pns , thank you for the detailed info, it's much appreciated!! `dri3 extension not supported` shows up in the node logs, would you mind sending your browser logs as well? I'm interested in knowing what exactly your client-side exception in the browser console is 🙏

**Comment by JasmineLaiHua** [comment]
> Hi @JasmineLaiHua and @ryan-silicon-digital ! I've seen this error as well, I mentioned it in #23326. Out of curiosity, what impact does this have on your tests? Is it a non-failing error? Do your tests hang when you see it?

Hi @rachelruderman , the same with @ryan-silicon-digital . The error happens when running the command `npm cypress open`

**Comment by rachelruderman** [comment]
Hi @JasmineLaiHua, can you clarify what you see in the GUI? I.e. does it fail to load, hang on a particular screen, etc?

**Comment by lmiller1990** [comment]
I wonder if we can do something similar to https://github.com/cypress-io/cypress/pull/20939

**Comment by lmiller1990** [comment]
I think the root issue is actually different - I always see this message on CI, eg: https://github.com/lmiller1990/rhythm/runs/8197426389?check_suite_focus=true#step:9:74 but the tests run just fine.

We need more information to debug this. The original issue references WSL - this guide was useful for me to run with WSL: https://nickymeuleman.netlify.app/blog/gui-on-wsl2-cypress

Happy to reopen if we have more info, but for now I don't see anything actionable on our end.

**Comment by erik-itland** [comment]
@rachelruderman you ask above:

> Hi @JasmineLaiHua, can you clarify what you see in the GUI? I.e. does it fail to load, hang on a particular screen, etc?

As Jasmine hasn't answered I'll do:

The GUI doesn't show up. 

When we come to the "Opening the App" step it just stops after displaying the message:

"[8995:0922/151902.580168:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported."

Let me repeat it from a business perspective: your prospective customers come to page 2 in the documentation and then they can't follow the instructions any longer.

Based on the 100/10/1 rule about 100 customers reading something / 10 customers pressing like / 1 customer caring to write roughly around 500 prospective customers have been stopped by the problem above.

Personally I guess the common thing for everyone in this thread is we are trying from WSL2.

If this is the problem then the workaround to truly fix it for everyone might be big, but I'd still recommend that you at least detect this issue and display a better error message, ideally with pointers to workarounds.

As for me I'll try to run it in a pure Windows install (for now, until I have time to remove the Windows infection and can run on pure Linux again like I prefer ; )

**Comment by nagash77** [comment]
@erik-itland At this point we don't plan to offer official support for WSL. Can you help us understand why you want to use WSL vs our windows binary? That might help us make a better case to internal product managers as to why as a company we should invest more resources in this type of use case. I am going to close this issue for the time being while we await your response.

**Comment by erik-itland** [comment]
The reason I use WSL is because for people like me who knows Linux, Windows is nightmarishly slow.

Even trivial things that returns instantaneously in Linux - like git status - takes several hundred milliseconds. For processes with multiple commands stringed together (builds) the effect is of course bigger. In my world that is often the difference between flow and not flow.

Interestingly enough, I get close to the same performance in WSL or even in an ordinary VM running on top of Windows 🤯 so as long as I work on Windows I work in WSL where possible. 

Personally I value cypress enough that I'll just live with this limitation for now. I'll probably just check out the code on the Windows machine as well and update it there every time I need to run the tests, meaning it wont be done as often but it will be done. Maybe I can even find a way to run the cypress process from the "Windows side".

But for anyone who is new to cypress, it will just look like it is broken or they did something wrong.

So, as someone who likes cypress I recommend adding a something in the docs and in the CLI output for now so those who are new to it won't get the wrong impression. 

Edit, some pointers that might actually allow it to work, based on search on Kagi and browsing the results:
- https://shouv.medium.com/how-to-run-cypress-on-wsl2-989b83795fb6
- https://stackoverflow.com/questions/69621197/running-cypress-on-wsl
- https://superuser.com/questions/1580610/how-to-run-gui-apps-with-windows-subsystem-for-linux

**Comment by nagash77** [comment]
@erik-itland thank you for your thoughtful reply!  I will be sure to pass this along to our product team so they can better understand our users and this specific use case.

**Comment by hanna-becker** [comment]
In case it helps anyone: For me this issue appeared after updating the WSL2 (I am using cypress v10.10.0). I emptied the Cypress cache and reinstalled the binary. This didn't help. I then removed cypress from my local repo's packages, deleted the Cypress folder under ~/.cache, and reinstalled it. This fixed it!

**Comment by jgentes** [comment]
To add to what @erik-itland said, the reason developers use WSL is that it separates their development environment from their host OS. It's the same reason everyone uses Docker to containerize their apps.

Rather than installing all of the various programming dependencies directly into your daily work environment, you can isolate them by using a WSL instance. This works wonderfully for everything other than apps that attempt to launch a UI.

As he said, there should be a clear error pointing people to a solution like https://sourceforge.net/projects/vcxsrv/ which will generally solve the problem.

Thanks, Cypress is a great tool!

**Comment by erik-itland** [comment]
@nagash77 I hopefully have some good news for many of those who have been affected by this problem,

The most recent version of WSL, at least WSL2[1] now supports x forwarding to Windows 10 by default.

Updating was really simple: 
- For good measure I made sure my WSL distro was up to date (i.e. in my case running `sudo apt update` followed by `sudo apt upgrade` 
- shut down the WSL environment (`wsl --shutdown`) from Powershell in Windows
- I then ran `wsl --update` from powershell from Powershell in Windows

Next time I ran `npx cypress open` it just worked! The cypress window showed up, clearly coming from the Linux environment since it has different window decorations (borders, minimize and maximize buttons etc).

By default only the electron browser was available, but Firefox was easily installed using `sudo apt install firefox`, Chromium was a bit harder since Ubuntu insists it should be installed using snap, and snap isn't available at least on my Ubuntu WSL (and I don't want to add it either). Anyways, my experice is, if it works in Firefox, well above 99% of the time it works everywhere else too, on the contrary Chrome, like IE before it allows a lot of sloppyness. If anyone still wants or needs a Chromium instance on their Ubuntu WSL, I used this recipe:  https://askubuntu.com/a/1206153 (note that in step 5 it says you need double newlines, but at least when I pasted it I got only single ones so I added extra newlines myself.)

[1]: I don't use WSL1 anymore so I cannot say either way

**Comment by jaredr-branscum** [comment]
Hi, wanted to leave a note that I'm also experiencing this issue as well with WSL 2 and the above suggested solutions of running sudo updates & wsl --update, and deleting the cache & reinstalling binary did not work for me.

Using Windows 11
Node 14.15.5
NPM 6.14.11

Seeing this error message: "[<number:number/number>:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported."
internal/modules/cjs/loader.js:638
    throw err;

GUI doesn't show up for me as well

Also, followed instructions on this page: https://nickymeuleman.netlify.app/blog/gui-on-wsl2-cypress

**Comment by erik-itland** [comment]
> Hi, wanted to leave a note that I'm also experiencing this issue as well with WSL 2 and the above suggested solutions of running sudo updates & wsl --update, and deleting the cache & reinstalling binary did not work for me.
> 
> Using Windows 11 Node 14.15.5 NPM 6.14.11

I see you use Windows 11 and I thought Windows 11 WSL should have fixed X forwarding even earlier.

Of the top of my head: Have you at any point configured X server manually?

Also, if you run `wsl --version`, what versions does it report?

(FTR: I am just another user, hoping to give you some pointers for further troubleshooting.)
