### ISSUE TITLE
`scroll-behavior: smooth` breaks scroll in Cypress 10+

### ISSUE THREAD

**Issue by pegak** [cypress-io/cypress#23355]
### Current behavior

We have `scroll-behavior: smooth` in our website. Cypress does not scroll when it is enabled.

### Desired behavior

Scroll to anchor.

### Test code to reproduce

https://github.com/pegak/nauc-me-it/blob/add-cypress-e2e/cypress/e2e/menu.cy.ts

This test is does not scroll to element. It scrolls only and only if we remove `smooth scroll`.

### Cypress Version

10.4.0

### Node version

18.7.0

### Operating System

Windows 11

### Other

This issue was reported and resolved as mentioned here: https://github.com/cypress-io/cypress/issues/3200

**Comment by raphzandrade** [comment]
Had the same issue trying to run tests that checked the behavior of some anchor buttons this week. Also using version `10.4.0`.

**Comment by rachelruderman** [comment]
Hi @pegak ! I'm sorry to hear you're having issues, thank you for putting this issue together. I wasn't able to run your source code due to build errors (`NEXT_PUBLIC_CLERK_FRONTEND_API` environment variable was required) however [I was able to put together a reproduction](https://github.com/rachelruderman/issue-23355) and confirm the behavior you're seeing.

I observed that the first click works as expected with `scroll-behavior: smooth`, but all subsequent clicks do not. I was able to reproduce both on your website and with some generic HTML.

Congrats on finding a bug and thank you again for reporting! 🐛
