### ISSUE TITLE
Flaky test: CypressError: `cy.task('__internal_scaffoldProject')`

### ISSUE THREAD

**Issue by rachelruderman** [cypress-io/cypress#23452]
### Link to dashboard or CircleCI failure

Failures with timeouts:
- https://app.circleci.com/pipelines/github/cypress-io/cypress/42187/workflows/1c55c4fe-45fc-4bde-af4c-cf01a8734c9b/jobs/1750692/tests#failed-test-0
- https://app.circleci.com/pipelines/github/cypress-io/cypress/42396/workflows/0d2b9f29-2e73-4600-8264-72e23db048ab/jobs/1761435

Failures with EEXIST: file already exists (originally noted in issue https://github.com/cypress-io/cypress/issues/23417):
- https://dashboard.cypress.io/projects/ypt4pf/runs/38107/test-results/a69afa29-37b1-453f-9dbc-dd6f84c9f8a5?utm_source=github&isFlaky=%5B%7B%22value%22%3Atrue%2C%22label%22%3A%22Flaky%22%7D%5D
- https://dashboard.cypress.io/projects/ypt4pf/runs/38193/test-results/ddd23eed-07a0-4a77-9630-51a29ffd2581
### Link to failing test in GitHub

Failures with ENOENT: no such file or directory:
- app.circleci.com/pipelines/github/cypress-io/cypress/41309/workflows/91b07182-06e5-4d6c-88aa-8861ac4c660f/jobs/1710135

Source code for `scaffoldProject`: https://github.com/cypress-io/cypress/blob/develop/packages/frontend-shared/cypress/e2e/support/e2eSupport.ts#L183

### Analysis

We've seen this timeout a number of times in `cy.task('__internal_scaffoldProject')`:
<img width="1172" alt="Screen Shot 2022-08-18 at 10 58 47 PM" src="https://user-images.githubusercontent.com/26726429/185553000-487268b1-7092-48ea-97fb-42e86bb256d5.png">

### Cypress Version

10.5.0

**Comment by rockindahizzy** [comment]
The install failure that seems to cause the timeout

```bash
    angular-cli-unconfigured
📦 Found package.json for project angular-cli-unconfigured.
📦 Creating a new node_modules cache dir at \tmp\cy-system-tests-node-modules\angular-cli-unconfigured\node_modules
📦 node_modules symlink created at C:\Users\circleci\AppData\Local\Temp\cy-projects\angular-cli-unconfigured\node_modules
C:\Users\circleci\AppData\Local\Temp\cy-projects\angular-cli-unconfigured\yarn.lock
📦 Writing yarn.lock with fixed relative paths to temp dir
📦 Running "yarn install --prefer-offline --ignore-scripts --frozen-lockfile --update-checksums --cache-folder=C:\Users\circleci/.yarn" in C:\Users\circleci\AppData\Local\Temp\cy-projects\angular-cli-unconfigured
warning ..\..\..\..\..\package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
(node:3892) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
[3/4] Linking dependencies...
Remove failed for C:\Users\circleci\AppData\Local\Temp\cy-projects\angular-cli-unconfigured due to EBUSY. Skipping on Windows.
📦 Found package.json for project angular-cli-unconfigured.
⚠ An error occurred while installing the node_modules for angular-cli-unconfigured.
[Error: EEXIST: file already exists, symlink 'C:\tmp\cy-system-tests-node-modules\angular-cli-unconfigured\node_modules' -> 'C:\Users\circleci\AppData\Local\Temp\cy-projects\angular-cli-unconfigured\node_modules'

] {
  errno: -4075,
  code: 'EEXIST',
  syscall: 'symlink',
  path: 'C:\\tmp\\cy-system-tests-node-modules\\angular-cli-unconfigured\\node_modules',
  dest: 'C:\\Users\\circleci\\AppData\\Local\\Temp\\cy-projects\\angular-cli-unconfigured\\node_modules'
}
[1/4] Resolving packages...
[2/4] Fetching packages...
(node:9336) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
📦 Copying yarn.lock and fixing relative paths for angular-cli-unconfigured
[3/4] Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile 'C:\\Users\\circleci\\AppData\\Local\\Yarn\\Cache\\v6\\npm-resolve-1.22.0-5e0b8c67c15df57a89bdbabe603a002f21731198-integrity\\node_modules\\resolve\\test\\precedence\\aaa.js' -> 'C:\\Users\\circleci\\cypress\\system-tests\\projects\\angular-cli-unconfigured\\node_modules\\@angular\\cli\\node_modules\\resolve\\test\\precedence\\aaa.js'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\circleci\\cypress\\system-tests\\projects\\angular-cli-unconfigured\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
📦 Found package.json for project angular-cli-unconfigured.
⚠ An error occurred while installing the node_modules for angular-cli-unconfigured.
[Error: EEXIST: file already exists, symlink 'C:\tmp\cy-system-tests-node-modules\angular-cli-unconfigured\node_modules' -> 'C:\Users\circleci\AppData\Local\Temp\cy-projects\angular-cli-unconfigured\node_modules'

] {
  errno: -4075,
  code: 'EEXIST',
  syscall: 'symlink',
  path: 'C:\\tmp\\cy-system-tests-node-modules\\angular-cli-unconfigured\\node_modules',
  dest: 'C:\\Users\\circleci\\AppData\\Local\\Temp\\cy-projects\\angular-cli-unconfigured\\node_modules'
}
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
      1) scaffolds component testing for Angular
```

**Comment by rachelruderman** [comment]
FYI I added another link to the "Link to dashboard or CircleCI failure" section --  I'll continue adding examples of this failure as I come across them

**Comment by astone123** [comment]
I've identified a few issues that are related to this flake. I'll outline my progress here and then move this back into the backlog for now to re-investigate at a later time so that we can move onto more pressing issues.

## Windows EBUSY

Sometimes when we clean up a project, Windows gives us an `EBUSY` error indicating that we're trying to delete something that is locked by some other process. Currently, if we get this error, we just skip deleting the project.

This **sometimes** causes an error when creating a symlink for the project's `node_modules/` which causes the dependency install to fail like this

```bash
⚠ An error occurred while installing the node_modules for create-react-app-unconfigured.
[Error: EEXIST: file already exists, symlink 'C:\tmp\cy-system-tests-node-modules\create-react-app-unconfigured\node_modules' -> 'C:\Users\circleci\AppData\Local\Temp\cy-projects\create-react-app-unconfigured\node_modules'

] {
  errno: -4075,
  code: 'EEXIST',
  syscall: 'symlink',
  path: 'C:\\tmp\\cy-system-tests-node-modules\\create-react-app-unconfigured\\node_modules',
  dest: 'C:\\Users\\circleci\\AppData\\Local\\Temp\\cy-projects\\create-react-app-unconfigured\\node_modules'
}
```

It looks like we get the EBUSY error because there is an "install" process hanging around from the previous project set up which is writing to the directory that we're trying to delete in the next setup. No idea why this only happens on Windows.

For instance, I can reproduce EBUSY on my Windows machine by removing the try/catch block from the `safeRemove` function in fixtures and running the `ct-framework-errors.cy.ts` test. Once the first test calls `cy.visitApp`, the origin changes which causes the browser to refresh.

Once this happens, `scaffoldProject` kicks off again (because the spec is re-running now that the browser has refreshed), and EBUSY gets thrown because the process from before the origin switch is still running.

### Potential solutions (needs investigation)
- Find and kill processes that were spawned by the `scaffoldProject` task before clean up is called
- Prevent an origin switch from occurring by setting `baseUrl` to the same origin that we go to with `cy.visitApp` (I tried this on [this branch](https://github.com/cypress-io/cypress/compare/scaffold-project-flake-2) and it caused a bunch of other failures and didn't seem to actually resolve the flake issue)

## Linux ENOTEMPTY
```bash
ENOTEMPTY: directory not empty, rmdir '/tmp/cy-projects/next-12.1.6'
```

I'm having trouble figuring out where this is getting thrown. I thought it was in the same place as the Windows issue (`safeRemove` in `fixtures.ts`), but according to the [fs-extra docs](https://github.com/jprichardson/node-fs-extra/blob/master/docs/remove-sync.md), the directory doesn't have to be empty because it uses `rimraf` under the hood, so this must be getting thrown somewhere else that I can't see.

I can't find the error in the CI logs. Supposedly this error was thrown during one of the attempts of the `next.cy.ts` tests in [this log](https://circleci.com/api/v1.1/project/github/cypress-io/cypress/1876832/output/114/0?file=true&allocation-id=63497c42a82ab20f8b9219d9-0-build%2F49772620) but I can't find it anywhere in the output to see the stack trace. I also haven't been able to reproduce this one locally on Mac
