### ISSUE TITLE
Spike: Run All Specs Reimplementation

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#23471]
We're doing this spike to learn:
- The level of effort to add in a 'run all specs' button just like in 9.x
- The level of effort to pull @lmiller1990's plugin into core and polish up the UI
- The level of effort to do a full multi-spec mode implementation (eliminate the hacks and trade-offs of the old 'run all specs')

There is no implementation implied by doing this spike. The outcome may be that we do none of the above.

**Comment by lmiller1990** [comment]
# 1. level of effort to add in a 'run all specs' button just like in 9.x

Here's the main differences we'll need to consider

- Port the exact implementation from Cypress 9. The code is all there and the core test runner isn't really any different. This is likely the "easier" part of this project.-
- We support Component Testing now. Do we need the same behavior for Component Testing? One point of different is Component Testing works with Vite and Webpack, and uses a dev server. I'm not sure how much complexity this adds, but it's complexity we will need to consider.
- Where does the button go? Does it go on the first page you see (the "specs" page) or on the "runner" page?
- How can I choose multiple specs? We need checkboxes. Where do those go?
- What if I want to run a different set of specs? One of the main problems with Run All Specs is memory usage. In Cypress 9, when you choose a new combination of specs to run, we re-launch the browser, which releases all the memory. In Cypress 10, you only open the browser once. Need to consider the workflow here, and complexity and of memory consumption issues (not everyone has a beefy work station). 

All in all, this would involve:

1. product (how does the feature work) 
2. designer (how does the checkboxes look) 
3. engineering (consider technical complexity, implement feature, add tests (old run all specs never had any proper tests around it)
4. ongoing support (9.x run all specs was buggy, we dropped it since it led to confusion and support overhead)

# 2. level of effort to pull your plugin into core and polish up the UI

For reference [this is the plugin](https://github.com/lmiller1990/cypress-explorer). For this to be something more than a weekend experiment (current state) we would need to:
- spend 1-2 days on [known issues](https://github.com/lmiller1990/cypress-explorer#known-issues), mainly respecting the user's `specPattern` and fixing various bugs around file extensions and windows compat (unknown if there are issues).
- make it look nice (I'm not a designer but it's a form with some check boxes, I don't think this is more than a day).

# 3. level of effort to do a full multi-spec mode implementation (eliminate the hacks and trade-offs of the old 'run all specs')

My understanding is there's quite a bit that needs to happen under the hood. See "Changes Necessary" here: https://github.com/cypress-io/cypress/discussions/21628. It looks like it's a project that would need a full quarter of work to really flesh out - including at least
- one full time technical lead (each of the points outlined in the discussion will likely need a tech brief)
- ... who will work closely with Brian and some more veteran App team engineers with historical context/deep knowledge of the runner/driver/server
- and a secondary senior engineer to implement all those things

As an aside, (3) sounds like a very fun project - high visibility and big impact. I have no doubt a lot of technical leads/senior engineers will want in. (1) and (2) sounds like a something users will enjoy short term but we will likely come to regret unless (3) is already in the pipeline (a hack/temporarily fix is fine, in my eyes, if we have a real solution in the works - it's the classic "prototype becomes the production build" situation, like the original "run all specs").

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23471?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by mirobo** [comment]
> * How can I choose multiple specs? We need checkboxes. Where do those go?

Just to give you a heads up.. I don't think "we" need checkboxes on the UI. I think filtering with text input was a brilliant and easy to use solution for everybody.. that's why people want it back :D

**Comment by lmiller1990** [comment]
Good point, maybe we are over complicating this.

**Comment by lmiller1990** [comment]
I'm going to collect various things related to Run All Specs as we look to revive this. One of the complexities is around huge snapshots and how much memory they consume. There's a small discussion about it [here](https://github.com/cypress-io/cypress/pull/23665#discussion_r968898824) where we talk about using MutationObserver to minimize the amount and size of snapshots we need to persist.
