### ISSUE TITLE
Technical brief for Create from React Component

### ISSUE THREAD

**Issue by baus** [cypress-io/cypress#23525]
Write a technical brief for scaffold a React CT spec by clicking on a source file containing a React Component.

There's some good ideas here: https://github.com/cypress-io/cypress/issues/23525#issuecomment-1229693899. Make sure you consider that design needs to be done too; the brief should have enough useful information that a designer can start working on designs, too.

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23525?planning-poker) with ZenHub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
This is a bit more tricky than Vue, since you need to consider **what is a React component**. Luckily, we can make some assumptions. Here's the complexity I foresee:

## What is a React Component?

React components **must start with a capital letter**` Example:

```js
// React component
const App = () => <div>App</div>

// React component
function App () {
  return <div>App</div>
}

// Not a React component
const app = () => <div>not okay</div>
```

If you try to use a lower case letter, React will error.

Obviously this is not really perfect - for example this **is** valid:

```js
const Foo = () => <div>foo</div>

export const foo = () => <Foo />
```

This makes it pretty tricky. You can get a decent amount of the way there by using babel to parse the AST and grabbing any functions starting with a capital letter, or ones that returns JSX perhaps, but it's (probably) not practical to do this on an entire code base - AST parsing is not very fast.

They can also be in any file - `js`, `tsx`, etc. I think we discussed this and settled on "just show all the files in the code base that match common extensions". Not ideal, but the best we can reasonable do?

## Knowing Which Component to Generate for?

This is a tricky one, too. Eg:

```ts
// MyList.jsx
export function MyList (props: { items: string[] }) {
  return (
    <ul>
      {items.map(item => <Item>{item}</Item>
    </ul>
  )
)

export function Item (props) {
  return <li>{children}</li>
}
```

Do we generate a test for `MyList` or `Item`? The filename is a hint - *probably* `MyList`, but maybe not? Either way we **need** to parse the file to get the correct name, see if it's a named or default export, etc

## Potential Improvement?

I think the Create From Modal needs an additional step.

**Comment by astone123** [comment]
Should we go through a design/product phase for this? I agree that we will most likely want to create an additional step to the create from component flow. One unanswered question here is:

How should we handle modules with multiple components (new step with checklist, create multiple tests, etc)?

Because of this I'm not sure that I'd say this ticket is ready to work. In addition I think we might want to make this an epic and create smaller issues.

**Comment by marktnoonan** [comment]
> Should we go through a design/product phase for this?

Would agree. I love the diagrams and wireframes @lmiller1990 has created.

**Comment by lmiller1990** [comment]
Cool idea from @JessicaSachs, we should consider eventually if we can use an open source snippet standard for our cod gen like https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets for VS Code, might be useful.

**Comment by lmiller1990** [comment]
Note: I have updated this ticket to just be concerned with **writing** the tech brief. Previous estimates were for the entire feature.

Epic: https://github.com/cypress-io/cypress/issues/24008

**Comment by lmiller1990** [comment]
I updated the original tech brief by Mike here https://github.com/cypress-io/tech-briefs/pull/53

Please review!
