### ISSUE TITLE
[Improvement] Include an option when typing to set the input text as confidential and show * instead of characters in the test logs

### ISSUE THREAD

**Issue by vergjor** [cypress-io/cypress#23561]
### What would you like?

I've been using Cypress for over a year now and one thing I would like to see as an addition would be to have like an option in the cy.type() command where we could set something like:

`cy.get(elementSelector).type('s4mpl3Pa$$w0rd', { sensitive: true });`

which would type in the correct text in the HTML element, but in the test logs we would only see ******

I would also suggest including something similar in the `cy.session()` command since we also pass sensitive information there as well and we could easily see it in the logs.

### Why is this needed?

I think that this would be extremely useful, especially when we want to be able to include detailed logs in test pipelines and we don't want everyone that has access to those logs to be able to see the credentials that were used.

**Comment by vergjor** [comment]
> There is an option that could work for you, it's `log` and you can set it to `false`
> 
> ```
> 
> cy.get(elementSelector).type(password, { log: false })
> 
> ```
> 
> I don't know if it's available in `session` but this helps with your main request.

Our logs are turned off during the test execution on the pipeline in general, but when we see the logs of the failed tests in the console we can still see the data that was used. It would still be great to be able to specify sensitive data and not display that data anywhere.

**Comment by emilyrohrbough** [comment]
@vergjor, @nickAdlard is correct that you should use 
```js
cy.get(elementSelector).type(password, { log: false })
````
to hide logs if you are concerned about sensitive data.

You can follow #17642 for `cy.session()` in regards to providing a `log: false` option. I will note, at this type, Cypress expects `log:false` to be set explicitly set for each command that should be hidden. When using `cy.session` I do not recommend using sensitive data as the unique identified since it is logged.
