### ISSUE TITLE
contains() targets element with pointer-events: none and fails to click

### ISSUE THREAD

**Issue by ionuthorgos** [cypress-io/cypress#23586]
### Current behavior

I want to create a dynamic function for a date picker and to do the checkin after a number of days.  Let's say I want after 60 days to do the checkin.

Here you can find the website (it's only for me to learn cypress)
https://www.vola.ro/

An error is displayed:
imed out retrying after 60050ms: cy.click() failed because this element:

<div ng-bind="::day.day">28</div>

has CSS pointer-events: none, inherited from this element:

### Test code to reproduce

selectFromDatePickerAnotherSolution(checkinDay, checkoutDay) {
    const monthTranslate = {
      january: "ianuarie",
      february: "februarie",
      march: "martie",
      april: "aprilie",
      may: "mai",
      june: "iunie",
      july: "iulie",
      august: "august",
      september: "septembrie",
      october: "octombrie",
      november: "noiembrie",
      december: "decembrie"
    };
    const dayjs = require('dayjs')
    // Numarul of day that I want to select
    let checkin = dayjs().add(checkinDay, 'day').format("DD")
    // The Name of the Month
    let validateMonth = dayjs().add(checkinDay, 'day').format("MMMM").toLowerCase()
    let verifyCheckinMonth = monthTranslate[validateMonth]
    let a;
    
    cy.get('.ith-calendar__month-name strong').eq(0).then((element) => {
      let futureMonthIndex = dayjs().add(checkinDay, 'day').format("M").toLowerCase()
      let currentMonthIndex = dayjs().format("M")
      let monthDifferenceIndex = futureMonthIndex - currentMonthIndex

      for(let i=1; i <= monthDifferenceIndex; i++){
        cy.get('button[class="ith-calendar__next-month"]').click();
      }
      cy.get('.ith-calendar__month-name').eq(0).contains(verifyCheckinMonth)
    });
    cy.get('.ith-calendar__table').eq(0).find('td').find('.ith-calendar__button').contains('div', checkin).click()
  }

### Cypress Version

Cypress package version: 10.4.0 Cypress binary version: 10.4.0 Electron version: 19.0.8 Bundled Node version: 16.14.2

### Node version

v16.15.1

### Operating System

Version 12.5.1

**Comment by mike-plummer** [comment]
Hi @ionuthorgos , thanks for opening an issue. This appears to be a question on how to use Cypress rather than a bug report or feature request. We recommend questions relating to how to use Cypress be asked in our [Discord server](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io/), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

The example code you attached is incomplete so I am unable to reproduce your issue or give you much guidance, but the error message indicates that you're attempting to click an element that the website treats as non-clickable (using the `pointer-events` CSS rule). This indicates you're either selecting the wrong DOM element (maybe a parent or child of the item you really want), or you're attempting to interact with an element before it thinks it should be interactive (not waiting for a popup to fully open, for example). I would recommend revisiting your selectors to ensure you're acting on the item you should be, and ensuring the browser state in the test runner reflects an appropriately interactive state for each test step. If all else fails you could also try passing the [`force` option to your `click` command](https://docs.cypress.io/api/commands/click#Usage) to skip the actionability checks, but this is generally an anti-pattern.

**Comment by ionuthorgos** [comment]
Ok, I understand. Thank you for your time and quick response. I will do some research through the documentation.
