### ISSUE TITLE
'Aw, Snap' error when logging in to Peoplesoft Campus

### ISSUE THREAD

**Issue by duncan-bayne** [cypress-io/cypress#2364]
### Current behavior:

Cypress is crashing with an 'Aw, Snap' error when loading Peoplesoft Campus.

<img width="924" alt="screen shot 2018-08-17 at 16 19 27" src="https://user-images.githubusercontent.com/65949/44250864-95829a00-a239-11e8-9335-6b96fa6a0056.png">

### Desired behavior:

The test should pass.

### Steps to reproduce:

```js
context('crashing test', () => {
  it('crashes', () => {
    cy.visit('https://campus.example.org/psp/cs92uat1/?cmd=login')
    cy.get('input#userid').type('REDACTED')
    cy.get('input#pwd').type('REDACTED')
    cy.get('input.ps-button').click()
  })
})
```
After successfully logging in and briefly displaying the Campus homepage, the browser crashes with the dreaded 'Aw, Snap' error:

### Versions

* Cypress 3.1.0
* Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* macOS High Sierra 10.13.2

**Comment by jordan-jarolim** [comment]
Have similar problem here. This happens on cy.visit() mehod.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
