### ISSUE TITLE
Cypress crashed during test execution

### ISSUE THREAD

**Issue by sparrafw** [cypress-io/cypress#23672]
### Current behavior

Currently I'm executing the following test:

    it('Verify login', () => {
        cy.visit(URL)
        cy.get('#email').type(userEmail)
        cy.get('#password').type(userPassword)
        cy.get('.login').click()
        cy.url().should('contain', '/main')
    })

Testing the code with a dummy page like: https://www.saucedemo.com/ it's working and test are passing

However when I tried to execute the same code with my application the login is performed successfully but it crashed on:
cy.url().should('contain', '/main')

I already tried my application from a live environment and locally and it's working
Also, if I open a new window on the browser opened by cypress and perform the login it's also working properly
So it's only crashing when cypress it's driving the execution

I tried using windows 10, macOS
Node 10, 14 and 16
Cypress 8,9 and 10.7.0

It's crashing on all the browsers with different error with the exception of firefox:

For chrome and chromium the error is:
```
We detected that the Chromium Renderer process just crashed.
[1] 
[1] This is the equivalent to seeing the 'sad face' when Chrome dies.
[1] 
[1] This can happen for a number of different reasons:
[1] 
[1] - You wrote an endless loop and you must fix your own code
[1] - There is a memory leak in Cypress (unlikely but possible)
[1] - You are running Docker (there is an easy fix for this: see link below)
[1] - You are running lots of tests on a memory intense application
[1] - You are running in a memory starved VM environment
[1] - There are problems with your GPU / GPU drivers
```
![Screen Shot 2022-09-02 at 8 58 47 AM](https://user-images.githubusercontent.com/112132765/188165438-fdb802c8-9485-4060-a4f4-3d24e3e27ee4.png)

For electron:
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#FailureMessage Object: Electron Framework  v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 16184648

I Also tried using docker but the result it's the same

### Test code to reproduce

None

### Cypress Version

10.0.7

### Node version

16

### Operating System

macOS 12.5.1

**Comment by sharozraees802** [comment]
"numTestsKeptInMemory": 0,
add this on cypress.json or cypress.config.js

**Comment by sparrafw** [comment]
@sharozraees802, just added and validated the new config value was picked up correctly, but the issue is still the same

**Comment by chrisbreiding** [comment]
I'm sorry you're encountering this issue.

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. If you can create a self-contained example repo using https://github.com/cypress-io/cypress-test-tiny as a template, that would be very helpful.
