### ISSUE TITLE
Fix flake test: "experimentalStudio is not a valid config for component testing"

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#23743]
### Current behavior

Fails sometimes on CI, sometimes linux, usually windows. I think it is a detached DOM related issue (maybe).

### Desired behavior

Does not fail.

### Test code to reproduce

This is an example: https://app.circleci.com/pipelines/github/cypress-io/cypress/43088/workflows/d2b0ef06-de0a-4040-bd99-b40c726ff83e/jobs/1796860

Just run it a few times locally - it should fail eventually, even on linux/Mac.

### Cypress Version

10.7

### Node version

16.16

### Operating System

linux, mac,windows

**Comment by rachelruderman** [comment]
When this issue is fixed, please unskip the skipped test. You can find the skipped flaky test by searching the code for this GitHub issue 🙂

**Comment by astone123** [comment]
Starting to look into this. The issue appears to be that the configuration that we are writing into the project isn't getting picked up in time (sometimes). 

When the test fails, it's because the config file inside of `experimentalSingleTabRunMode` project is being used rather than the one that we write in with `writeFileInProject`, so there's no config error on the page.
