### ISSUE TITLE
uncaught:exception breaks the Gitlab pipeline

### ISSUE THREAD

**Issue by nemonemi** [cypress-io/cypress#23741]
### Current behavior

When running locally, I can see the exception being thrown and am informed by Cypress about it, however, the tests continue running.

When running it on the pipeline, the output shown gets cut off, and no information is displayed as to why the pipeline failed.
![image](https://user-images.githubusercontent.com/77624664/189294558-61b9bf4d-5afb-413d-a981-7fe0314a5266.png)

Here it is stated that only the tests will fail (nothing else is mentioned).
https://docs.cypress.io/guides/references/error-messages#Uncaught-exceptions-from-your-application

After I've added `cy.on('uncaught:exception', () => false);` to my test, the pipeline run fine, but this should have nothing to do with the pipeline passing or not in my oppinion.

### Desired behavior

The pipeline should continue running, and the reported failed and passed tests should be displayed correctly so that the debugging information can be useful.

### Test code to reproduce

Don't have it as of this time.

### Cypress Version

10.7.0

### Node version

16.14.0

### Operating System

Ubuntu 20.04.5

**Comment by lmiller1990** [comment]
To clarify: this sounds like a feature request, not a bug report? An uncaught exception is considered to be a failure, as you noted in the docs. The run should continue, just the test in question will be considered a fail.

It sounds like your run is terminated immediately after the uncaught exception, instead of continuing to run? If it's unique to GitLab pipelines, can you try to provide a minimal example (ideally, if you are using Docker or something, the associated Dockerfile, too?)

Here's my attempt at minimal example: https://github.com/lmiller1990/cypress-test-tiny/compare/master...lmiller1990:cypress-test-tiny:issue-23741?expand=1

- 2x tests 
- 1 with uncaught error
- 1 that passes

When I run this, I get 1/2 passes, and the run continues until all specs have executed.

**Comment by lmiller1990** [comment]
Trying to reproduce on GitLab CI: https://gitlab.com/xenetics/cypress-example-kitchensink

**Comment by nemonemi** [comment]
I see... Hmm... my application uses NX, and I am not sure how, but it might be the one introducing this issue.

**Comment by lmiller1990** [comment]
Can you please try to provide a minimal reproduction? I'll be able to assist more  don't I know the exact environment or toolchain you are using.

**Comment by nemonemi** [comment]
Yes, I will try to do so in the following days.

**Comment by ZachJW34** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
