### ISSUE TITLE
Spike: Support Next Server Side Props

### ISSUE THREAD

**Issue by baus** [cypress-io/cypress#23761]
Support Testing of Next's Server Side Props: https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/23761?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
Context: there are two scenarios in which `getServerSideProps` runs.

- When you request this page directly, getServerSideProps runs at request time, and this page will be pre-rendered with the returned props
- When you request this page on client-side page transitions through [next/link](https://nextjs.org/docs/api-reference/next/link) or [next/router](https://nextjs.org/docs/api-reference/next/router), Next.js sends an API request to the server, which runs getServerSideProps

I personally think second one, routing, is outside the scope of CT - we cannot change the route for the AUT iframe, since that is pointing to the dev server, if you navigate away, your test will be blown away. Even if this was not the case, components using routing normally expect to be rendering in a full App with the full router, and you end up with a big mess if you render them without the full router. "Testing routers" is a problem across all frameworks and libs, people generally stub/mock it out. I think routing is an E2E concern.

The first one is more relevant and interesting -  I can see a world where people want to test components rendering on the server. @mike-plummer probably has some more concrete examples from his experience developing Next.js.

I think the best way to do this would be as close to real Next - possible start a little server and render there, and shuttle the HTML across and hydrate it. I think we'd need an additional API. We may need a `cypress/next` mounting adapter, which would internally be something like:

```js
import { mount } from 'cypress/react'

function mountNext (comp) {
  return mount(comp, {
    ssr: true
  })
}
```

To tell the component it needs to do the SSR rendering. If we are smart, we can get ahead and potentially set ourselves up to support the new React Server Components: https://reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components.html and possibly develop a pattern for Nuxt SSR, too.

**Comment by lmiller1990** [comment]
Related? https://github.com/cypress-io/cypress/issues/22350

I think the main deliverable here should be a spike and tech brief. It's not even clear the best way to support this. Thoughts?

I'd expect to spend the best part of a week on this investigation + brief.

**Comment by lmiller1990** [comment]
I thought about it more. Let's consider all the different things Next.js does, and what I'd recommend.

## Pages

Ref: https://nextjs.org/docs/basic-features/pages

How it works: you put your pages in `pages`, for example `pages/hello.js`. When a user visits `https://example.com/hello`, they get `hello.js`. Next will run some server side things (more on this later) and send back some HTML. `pages` is effectively the root of your Next.js app, and the file structure is your router.

Testing: Your testing a server and router. I'd recommend writing E2E tests to cover each of these. I'd personally group them based on pages, eg `pages/hello.cy.js` etc.

## Data Fetching

Ref: https://nextjs.org/docs/basic-features/data-fetching/overview

How it works: Next.js has several APIs for fetching data. Those are:

1. [getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props)
2. [getStaticPaths](https://nextjs.org/docs/basic-features/data-fetching/get-static-paths)
3. [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching/get-static-props)

How they work: 

- can only be exported from a page. You can’t export it from non-page files
- only runs on server-side and never runs on the browser

I don't think pages are a good candidate for Component Tests. Sure, a page is technically React component, but so is `<App />` - but it's obviously impractical to mount your entire App in Component Testing. Component Tests are served via a dev server, so you can't navigate to different routes. Pages often expect to receive route-specific data, like `params.id`, `query`, etc.

I'd recommend an E2E test for pages. I think `getServerSideProps` is outside the scope of CT.

`getStaticPaths` and `getStaticProps` are used for static rendering of entire pages. This is definitely outside the scope of component testing.

## Build In Components

Next.js has some built in components.

- next/image
- next/link
- next/head
- next/script

- `next/head`: #22350 notes `next/head` doesn't do what you might expect - it appears to require server side APIs. `<Head>` injects things into `<head>` which sounds like an E2E/page level concern to me.
- `next/link` navigates somewhere - again, navigation sounds like an integration/e2e level concern.
- I don't know about `next/image` or `next/script` yet.

## Cypress and Next.js

[They mention Cypress in their docs](https://nextjs.org/docs/testing#cypress), but only E2E. I'd recommend updating the docs to include some information about Component Testing. We could add an example to support this in their example: https://github.com/vercel/next.js/tree/canary/examples/with-cypress. I don't know how they manage or maintain docs, we should find out. I created an issue to see what the Next.js team thinks: https://github.com/vercel/next.js/issues/40781

## Other Notes

What is more interesting and compelling is [React Server Components](https://github.com/josephsavona/rfcs/blob/server-components/text/0000-server-components.md). React and Next are working on this together (noted in FAQ) and this will be something we should consider in the future. [Next.js docs](https://nextjs.org/docs/advanced-features/react-18/server-components). These, unlike Next.js pages, are not directly coupled to a router. They *do* need a server, though. More exploration is needed.

**Comment by EandrewJones** [comment]
I know this is closed but there's another aspect of the relationship between components and pages that adds a wrinkle to the E2E/Component distinction in NextJS.

You note:
> I don't think pages are a good candidate for Component Tests. Sure, a page is technically React component, but so is <App /> - but it's obviously impractical to mount your entire App in Component Testing. Component Tests are served via a dev server, so you can't navigate to different routes. Pages often expect to receive route-specific data, like params.id, query, etc.
>
> I'd recommend an E2E test for pages. I think getServerSideProps is outside the scope of CT.

In theory, there's a clean separation of components and pages, but in some cases components' dependency trees extend all the way back to `pageProps`. Is it great practice to have this coupling, no. But it's more common in NextJS than you'd think. Let me give you an example.

# Example Case
I use Lingui for translations across my website. The locale is detected on page load,  translations are fetched, passed to pages and page props and access by components all over the website.
```ts
export const getServerSideProps: GetServerSideProps = async context => {
    const { Auth } = withSSRContext(context)
    try {
        const { attributes } = await Auth.currentAuthenticatedUser()
        // fetch translations
        const translation = await loadTranslation(
            context.locale ? context.locale : 'en',
            process.env.NODE_ENV === 'production'
        )
        return {
            props: {
                translation,
                sub: attributes.sub,
            },
        }
    } catch (err) {
        console.log('Redirecting')
        return {
            redirect: {
                destination: `/login?from=/home`,
                permanent: false,
            },
        }
    }
}
```
Translations also need to detect changes in the locale in the URL, hence depend on the router. Therefore, the `<App>` is wrapped with:
```ts
const AppSetup = ({ translation, children }: Props) => {
    const [queryClient] = useState(() => new QueryClient())

    // Detecting locale (language) for translations
    const router = useRouter()
    const locale = router.locale || router.defaultLocale
    const firstRender = useRef(true)

    // on page compile
    if (translation && firstRender.current && locale) {
        // load the translations for the locale
        i18n.load(locale, translation)
        i18n.activate(locale)

        // render only once
        firstRender.current = false
    }

    // on dynamic changes
    useEffect(() => {
        if (translation && locale) {
            i18n.load(locale, translation)
            i18n.activate(locale)
        }
    }, [locale, translation])

    return (
        <QueryClientProvider client={queryClient}>
            <Provider store={store}>
                <I18nProvider i18n={i18n}>
                    <Layout>{children}</Layout>
                </I18nProvider>
            </Provider>
        </QueryClientProvider>
    )
}

export default AppSetup
```
# Ideas

Any component with translations, then, has to have access to pageProps to even mount for testing. But as you note, it's very inefficient to mount your entire App context for component tests. Almost any solution I can think of either doesn't work in CT (mounting page and aliasing pageProps before component tests) or moves us closer to E2E and introduces unwanted technical debt. For example, in **`cypress/support/components.ts** add:

```ts
...
beforeEach(() => {
    cy.fixture('path/to/translations/fixture').as('translations')
})
```
#### in **`cypress/support/commands.tsx`** write custom mount:

```ts
Cypress.Commands.add('mount', (component: React.ReactNode, options = {}) => {
    const { translation, ...mountOptions } = options

    const wrappedComponent = (
        <AppSetup translation={translation}>
            <>{component}</>
        </AppSetup>
    )
    return mount(wrappedComponent, mountOptions)
})
```

and finally in the test, you'd have access to the fixture which could be passed to the mount options:

```ts
describe('<ComponentToTest/>', () => {
    it('mounts', function () {
        cy.mount(<ComponentToTest />,
        {
            translation: this.translation,
        })
    })
})
```

# Challenges
This solution, which I'm hesitant to even test, just doesn't scale. You'd could write individual translation fixtures for each component and load before each mount or you'd have to maintain an ever growing translation fixture. And that's just for a single page prop. There are other page props accessed at the component level for which creating fixtures wouldn't work. 

Though this is a specific example, I think it highlights the blurred lines between CT and E2E in next. Until there's a clear protocol for disambiguating and solving these issues, I don't see how how to do CT in Next for anything but very simple utility components.

**Comment by lmiller1990** [comment]
@EandrewJones great comment... I have been running into a similar issue (not with Next.js, but testing components that have a server dependency). `cy.intercept` is pretty nice, but I agree it introduces a lot of boilerplate and doesn't scale very well. 

I also found a similar problem testing components using GraphQL with `useQuery`. I don't really want to stub the API call, but I also don't want to add more layers just to the purpose of testing my component.

This is also going to become more of a pressing issue for testing projects using things like Remix, where there is a significant server dependency. The Remix ["Data Loader"](https://remix.run/docs/en/v1/guides/data-loading) is almost a direct parallel to `getServerSideProps`.

I think we need to bridge this gap somehow. I don't have a good solution now, but working backwards from where I want to be:

1. I've got a component that depends on <some server side thing>
2. I write my test, I want to have some way to have a short lived server (or something like that) that starts and ends with my test lifecycle. 

Basically:
- I want to write an integration test
- I want to use a dev server (faster) 
- I want to have fine grained control without spinning up/tearing down a real server, database, etc. 
- I also don't want to stub the universe, I want everything relevant to my test in my `cy.mount` function.
- I want to run it with the **component testing** running, I like the speed and fact it's so easy to configure.
_____
Below is just my ideas, thinking out loud. I have no idea how much sense these make, if it's practical, etc. Brainstorming, basically. If you have any input that would be very useful! 

Consider this Remix example (using Remix since the code is more concise)

```js
export const loader: LoaderFunction = async () => {
  return someJsonEndpoint()
};

export default function Products() {
  const products = useLoaderData();
  return (
    <div>
      <h1>Products</h1>
      {products.map((product) => (
        <div key={product.id}>{product.name}</div>
      ))}
    </div>
  );
}
```

I do not want an E2E test for some tiny widget on my website. `cy.intercept` is an okay solution, but I think we need to explore other options, too.

```js
it('does something with SSR', () => {
  cy.mount(Products, {
    loader: [{ id: 1, name: 'Great product' }]
  })
})
```

In the background, it might 

1. notice there is a `loader` key
2. create a short lived server? mock server? Something else?
7. run test
8. teardown whatever happened in step 2

Exploring your Next.js example, there are actually quite a few dependencies:

```js
const { attributes } = await Auth.currentAuthenticatedUser()
// fetch translations
const translation = await loadTranslation(
  context.locale ? context.locale : 'en',
  process.env.NODE_ENV === 'production'
)
```

1. Auth (which uses `withSSRContext`, which looks like it hits some AWS service)
2. `loadTranslation` - assume this hits some endpoint
3. context - this needs to get provided somehow
4. process.env - obvious server side variable

I don't want to write roughly 8-10 E2E tests for this, though - it's expensive and time consuming. I think using CT with a dev server is a good fit, but we definitely don't have the tools for this, yet. It sits in this weird place between CT and E2E - an integration test.

Again, thinking out loud...

```js
it('is the integration testing dream API', () => {
  cy.mount(Products, {
    getServerSideProps: (req, res) => {
      // do something
      req.whatever = 'foo'
      return { req, res }
    },
    hooks: {
      // how would this work? I want to have control over this in my tests.
      // Do we want to hit a real AWS service during development? 
      // Probaby not, it costs money. Auth is always a real E2E test.
      withSSRContext: { user: { locale: 'en-US' } } 
    },
    // Can we manipulate the Next.js context somehow? That'd be nice.
    context: {
      locale: 'en-US'
    },
    // Just dreamed this up, no real idea if this even makes sense
    server: {
      process: {
        env: { NODE_ENV: 'production' }
      }
    }
  })
})
```
