### ISSUE TITLE
Cypress component tests not loading assets with Angular

### ISSUE THREAD

**Issue by lydemann** [cypress-io/cypress#23797]
### Current behavior

It will not load assets:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/9210691/189891649-444b5a5f-6949-478a-85ae-b359e87edd94.png">

Even though the dev server is copying the assets:
<img width="603" alt="Screenshot 2022-09-13 at 13 40 07" src="https://user-images.githubusercontent.com/9210691/189891833-d6873b04-03dd-46f2-a3a9-e5260e160d2e.png">

### Desired behavior

It should load assets from eg.:

http://localhost:8080/assets

### Test code to reproduce

<img width="644" alt="image" src="https://user-images.githubusercontent.com/9210691/189895231-5e3a4c29-f5c0-4e50-9c2d-4efc11012225.png">

https://github.com/lydemann/cypress-assets-bug

### Cypress Version

10.7.0

### Node version

16.14.2

### Operating System

12.3.1

### Other

Assets are not loaded, eg. the image in the repo

**Comment by ZachJW34** [comment]
@lydemann thanks for posting, I can verify that the assets aren't loading properly. I was able to implement a quick hack and get assets to load by editing the `cypress/support/component-index.html` with the following:

```html
<head>
	...
	<base href="/__cypress/src/" />
</head>
```

Could you give this a try and see if it works? Your image shows that it's failing to load `assets/env.js` rather than a traditional asset (like a `.png`) so might be more to explore unless I'm misunderstanding.

This is definitely something we should be handling on our side but I'm curious if the hack works for you.

**Comment by lydemann** [comment]
> @lydemann thanks for posting, I can verify that the assets aren't loading properly. I was able to implement a quick hack and get assets to load by editing the `cypress/support/component-index.html` with the following:
> 
> ```
> <head>
> 	...
> 	<base href="/__cypress/src/" />
> </head>
> ```
> 
> Could you give this a try and see if it works? Your image shows that it's failing to load `assets/env.js` rather than a traditional asset (like a `.png`) so might be more to explore unless I'm misunderstanding.
> 
> This is definitely something we should be handling on our side but I'm curious if the hack works for you.

Yes, that does work like that, but should probably also work as domain:port/assets/*

Thanks for looking into it.

**Comment by lydemann** [comment]
Any updates?

**Comment by inigoiparragirre** [comment]
Same problem here. I wanted to add MSW using mockServiceWorker.js in assets, and it doesn't load it.
