### ISSUE TITLE
ERR_FAILED (-2) when loading new window Electron 102 (headless) via CLI

### ISSUE THREAD

**Issue by MvRiele** [cypress-io/cypress#23835]
### Current behavior

Test uses `cy.window().then(win => { cy.spy(win, 'open').as('windowOpen'); });` and `cy.waitUntil(() => cy.get('@windowOpen').should('be.called'));` to check if opening a window is triggered. 

When running in CLI Electron 102 (headless) an error is given:

`ERR_FAILED (-2) loading 'https://www.testcode.com/?title=test'
Error: ERR_FAILED (-2) loading 'https://www.testcode.com/?title=test'
    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)
    at EventEmitter.emit (node:events:526:28)
    at EventEmitter.emit (node:domain:475:12)`

When i run in chrome, there is no error and the test runs fine

### Desired behavior

No error given

### Test code to reproduce

Test uses `cy.window().then(win => { cy.spy(win, 'open').as('windowOpen'); });` and `cy.waitUntil(() => cy.get('@windowOpen').should('be.called'));` to check if opening a window is triggered. 

### Cypress Version

10.8.0

### Node version

6.14.13

### Operating System

windows 11 PRO

**Comment by ZachJW34** [comment]
We recommend stubbing `window.open` rather than spying on it as we don't support running Cypress commands inside another window (popup or new tab), see [comment](https://github.com/cypress-io/cypress/issues/4468#issuecomment-502542288). So you can replace the `cy.spy` with `cy.stub` and you should be able to verify that the stub was called.

That said, Cypress should not be crashing when you call this function and we should print a nice error message in the UI in this case. I was able to reproduce this error with the code snippets you provided. Thanks for the issue @MvRiele, let me know if the workaround works for you.

**Comment by DavesPlanet** [comment]
we are experiencing this same error with electron (apparently not chrome) on a simple
```
cy.get("#foo").click();
cy.url().should('includ','http://bar');
```
when the thing being clicked causes a pop-up window to download a pdf

**Comment by StephanGuingor** [comment]
I'll leave this here, we are also experiencing this issue. By using `cy.stub` instead of `cy.spy` worked fine. 
Although this should be marked as a bug, as it should not crash, it happend on _Electron (headless) 106_

An example on how you can test the window by stubbing:

```
const stub = cy.stub().as('open')
cy.on('window:before:load', (win) => {
            cy.stub(win, 'open').callsFake(stub)
})
```

And then to verify it got called  `cy.get("@open").should("be.called")`

**Comment by flotwig** [comment]
This is seemingly a duplicate of #18547, closing

**Comment by benfenglee** [comment]
Damn it, I showed up, and I don't know how to fix it, okay

> Error: ERR_FAILED (-2) loading 'http://localhost:8090/'
>     at rejectAndCleanup (node:electron/js2c/browser_init:2:84559)
>     at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:84946)
>     at WebContents.emit (node:events:526:35) {
>   errno: -2,
>   code: 'ERR_FAILED',
>   url: 'http://localhost:8090/'
> }

**Comment by bravewasp** [comment]
@benfenglee and everyone else coming here from google.

We had a similar issue, cypress simply crashed on startup with a similar message. It seems like cypress has problems when the computer is set to enery saving mode (Windows 11). 

Perhaps the startup takes to long an cypress decides to kill the electron process.

**Comment by ArtemAvramenko** [comment]
In my application, I create a window at the very beginning, and to have it already loaded, I open 'about:blank' in it:

```ts
const window = new BrowserWindow({
    show: false,
    paintWhenInitiallyHidden: false,
    webPreferences: {
        nodeIntegration: false,
        devTools: false,
        javascript: false,
        spellcheck: false,
        webgl: false
    }
});
await window.loadURL('about:blank');
```

And even in this simplest scenario, an error occurs, albeit extremely rare:
```
Error: ERR_FAILED (-2) loading 'about:blank'
at rejectAndCleanup (node:electron/js2c/browser_init:2:85498)
at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:2:85885)
at EventEmitter.emit (node:events:513:28)
```

I'm using v26.6.0 on Windows

It seems to be related to PC speed, because it reproduces for some users during OS booting, when the application is in startup folder, and when CPU and HDD are busy with simultaneous launching of other applications.

**Comment by billyang1222** [comment]
Any updates ？
