### ISSUE TITLE
Backend data not fetched while Frontend automation suite runs

### ISSUE THREAD

**Issue by saurabh021986** [cypress-io/cypress#23863]
### Current behavior

I am accessing my application under test via corporate proxy and trying to assert the presence of data on UI which is returned by some backend APIs. Issue is that during test run these APIs do not return data, resulting in data not present in UI at the time of assertion and the suite failing ultimately. Strangely, when i copy the API curl from the browser console and hit it via postman the data appears everytime. No issue at all while executing the same manually via browser. Any leads would be very helpful as this is blocking our adoption of cypress for E2E UI test automation.

### Desired behavior

APIs of the application should return data everytime.

### Test code to reproduce
```
   cy.visit('myurl')
    cy.get('div').contains('Search Customer').should('exist')
    cy.get('div').contains('Customer Number').click()
    cy.get('[data-value="2"]').click()
    cy.get('.MuiFormControl-root > .MuiInputBase-root > .MuiInputBase-input').type('12345678')
    cy.get('.jss44').click()
    cy.wait(5000)
    cy.get('div').contains('Authentication').should('exist')
```
### Cypress Version

10.1

### Node version

v16.15.0

### Operating System

macOS v11.5

**Comment by mjhenkes** [comment]
Hi @saurabh021986, I suspect you may be running into a cookie issue. If you inspect while running the test are the api calls hanging or failing. If they're failing you should check to see if the same cookies are being sent down on the request as are sent down when you execute the request outside of cypress.

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
