### ISSUE TITLE
It would be great to support typing of "{tab}"

### ISSUE THREAD

**Issue by mP1** [cypress-io/cypress#23864]
### What would you like?

Many special keys may be typed onto a focused element such as `{enter}`.

The big missing feature is the ability to type TABs, `{tab}` is not mentioned in the documentation or supported at runtime.

https://docs.cypress.io/api/commands/type

I believe it would be helpful to mention this omission as Im sure many during their travels must be wondering how or why they cant type `{tab}`.

### Why is this needed?

My app like many supports tabbing around the UI, and i would like to write some tests to verify tabbing does whats expected.

Im using the cypress-tab plugin (/cypress/support/e2e) but it doesnt always work, it sometimes gets stuck and doesnt advance the focus but thats another story. My dream would be to support something like this in the product.

```
import './commands'

// Alternatively you can use CommonJS syntax:
// require('./commands')
require('cypress-plugin-tab')
```

**Comment by nagash77** [comment]
Hi @mP1 , I believe this request is already captured in https://github.com/cypress-io/cypress/issues/299.  I am going to close this issue since we are tracking this feature in the linked issue.  You might want to checkout [this repo](https://github.com/dmtrKovalenko/cypress-real-events) which may provide what you need in the interim.
