### ISSUE TITLE
Certificate not valid on https://download.cypress.io/

### ISSUE THREAD

**Issue by ivanminovi** [cypress-io/cypress#23927]
### Current behavior

Hi Cypress team

I have issues installing the cypress via terminal, it gets blocked by our company's client connector, and seems like the issue is the certificate, it would be nice if you give it a check from your side, thank you! 

![Screen Shot 2022-09-21 at 4 57 16 PM](https://user-images.githubusercontent.com/1906466/191630147-94d48c2c-5568-457d-ad0c-41dee7b0adea.png)

### Cypress Version

10.6.0

### Node version

v14.15.4

### Package Manager

npm

### Package Manager Version

8.19.1

### Operating system

Mac

### Operating System Version

12.3.1

**Comment by JesusLopezCh** [comment]
+1

**Comment by colebrumley** [comment]
Hello, thanks for reporting this issue. Could you please share the specific TLS error you're seeing? I'm not able to duplicate this using OpenSSL (command I used: `openssl s_client -connect download.cypress.io:443 -showcerts -verify_return_error -verify_hostname download.cypress.io`) or via a browser.

**Comment by ivanminovi** [comment]
Sure ...basically I have cypress on my package.json as a devDependency and I ran `npm install `

![Screen Shot 2022-09-22 at 12 59 51 PM](https://user-images.githubusercontent.com/1906466/191839715-e3f9c743-a450-420b-bdd5-aab67d8f87ee.png)

And it shows: `Unable to get local issuer certificate`

Here're different version tries:

![cypress issue](https://user-images.githubusercontent.com/1906466/191843919-e2cdc8bd-e976-46e9-b546-b213be2700fb.png)
<img width="1206" alt="Screen Shot 2022-09-22 at 1 31 10 PM" src="https://user-images.githubusercontent.com/1906466/191845235-36742e51-8a59-4129-a86d-e667bc42171b.png">

**Comment by colebrumley** [comment]
Hi again! This looks like a configuration issue with the firewall. Does your company use a proxy server? If so you'll need  to follow the proxy configuration instructions [here](https://on.cypress.io/proxy-configuration). Occasionally this error is also caused by misconfigured client certificates for the internal firewall.

Usually when we see [these](https://github.com/cypress-io/cypress/issues/1352) [kinds](https://github.com/cypress-io/cypress/issues/17238) of [issues](https://github.com/cypress-io/cypress/issues/18616) it's related to a corporate firewall/TLS inspection service. Unfortunately, since this error is nearly always happening before the traffic leaves your network, there's little in the way of troubleshooting we can do on our end other than verifying that the certificate is valid. We're using a Cloudflare-managed TLS certificate which checks out from my end, so I don't think that's the problem. 

Several of the linked issues above include workarounds that have helped others if the proxy configuration documentation does not help.

**Comment by ivanminovi** [comment]
Thanks very much!, we will check the different links (since we don't have any proxy configuration), hopefully one of them help us, we'll let you know the results

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by sahapina** [comment]
@colebrumley
Hello, I have the same problem [reported issue](https://github.com/cypress-io/cypress/issues/23927#issue-1381644497).
I don't know how can fix it. The generated certificate is valid and the issuer is cypressproxyCA.
I need help resolving a security issue in the Cypress browser. When I try to submit a form (usually an action button called POST or PUT endpoints), it is not working. The website appears to be secure without any coding issues. I have manually added the certificate, but the problem persists. Can you assist me in resolving this issue?
I attempted different methods, but none of them resolved the issue.

Cypress Version
12.17.3

Operating system
Windows

![image](https://github.com/cypress-io/cypress/assets/77250050/a2f3f089-58d2-4ab3-8e49-c36901a30b1a)

![image](https://github.com/cypress-io/cypress/assets/77250050/9c76aee4-909e-4115-bbde-2e5a17fd13a6)

![image](https://github.com/cypress-io/cypress/assets/77250050/b8c8e0b6-4e6b-4ae7-a854-9f145bb40c4e)
