### ISSUE TITLE
Getting (uncaught exception)TypeError: Cannot read properties of undefined (reading 'guided tours') while launching ServiceNow url 

### ISSUE THREAD

**Issue by shalinirakesh** [cypress-io/cypress#24010]
I am getting the below error while launching service now url.Please find the screenshot attached:
I have tried the below workarounds but nothing worked.
1. I am using cypress version 10.4.0 currently.I have tried older version like 9.5.0 and 8.5.0 and i am getting the same error in older versions too.
2. Added the below code to e2e.js file.
Cypress.on('uncaught:exception', (err, runnable) => {
    return false
}) 
**Browser used**:Electron and chromium
**cypress version**:10.4.0,9.5.0,8.5.0

**Error Message:**
(uncaught exception) TypeError: Cannot read properties of undefined (reading 'guided tours')

**Comment by nagash77** [comment]
@shalinirakesh I am going to close this issue since it does not follow our issue template.  Your screenshot also does not show in this issue.  Please create an issue from the issues tab in the [cypress github repo page](https://github.com/cypress-io/cypress) and select the bug option and include the fields.
