### ISSUE TITLE
[Dashboard] integrate with ReportPortal.io

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [cypress-io/cypress#2406]
Dashboard (reporting) functionality looks like a ReportPortal many many years ago.
https://github.com/reportportal/reportportal

It follows the same concept to collect data on runtime.
Leverage ML to analyze new fails, based on historical data of previous fails.
Already have tons of functionality and can be re-used for dashboard part in Cypress.
and it's open sourced.
http://reporportal.io 

What do you think guys?

**Comment by Kondasamy** [comment]
I second @DzmitryHumianiuk

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.
