### ISSUE TITLE
[cy.intercept] `times` not working?

### ISSUE THREAD

**Issue by Rc85** [cypress-io/cypress#24081]
### Current behavior

My app authenticates user every 30 seconds and if there is a logged in user, the response status 200, otherwise, it's 204. After my app makes the first call to authenticate, it returns 200, meaning the intercept worked. However, subsequent calls seem to be hitting my server, as it is returning 204. I added a routeMatcher with times in it but the authentication is still hitting my server.

### Desired behavior

Using times in routeMatcher should return the same response until the # of times is reached.

### Test code to reproduce

```
cy.intercept(
      '/api/merchant/auth?application=merchant',
      { times: 100 },
      { statusCode: 200, body: activeUser }
    );
```

### Cypress Version

10.9.0

### Node version

16.15.0

### Operating System

Windows 10 64bit

**Comment by mjhenkes** [comment]
@Rc85, does your route change at all after the first request so that the matcher no longer matches? Keep in mind that intercepts are bound to it blocks and if you want to intercept across it block you have to specify it in a before each.

I put together a simple example of intercept working after the first request here.
https://github.com/mjhenkes/intercept-test

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
