### ISSUE TITLE
zombie process that take a whole cpu core

### ISSUE THREAD

**Issue by Reaster0** [cypress-io/cypress#24130]
### Current behavior

i'm running cypress as module api in my nestJS backend, it work without a flaw,
but when i run more than two tests at the same time, a process will spawn doing nothing beside taking 100% of one core of my cpu
beside the name of the zombie process is always the same, so right now i need to kill the process myself with a cron or an exec
![image](https://user-images.githubusercontent.com/73885131/194072340-66ac492a-c025-462d-b0be-7bbb133f0254.png)

### Desired behavior

that when multiples cypress tests are run at the same time, this process will not spawn

### Test code to reproduce
```
return cypress.run({
			spec: `./cypress/e2e/${name}.cy.js`,
			screeshot: true,
			quiet: true,
			browser: 'chrome',
			config: {
				video: true,
			},
			
		})
```
### Cypress Version

10.4.0

### Node version

18.9.0

### Operating System

Ubuntu 22.04 x64

**Comment by Reaster0** [comment]
maybe it has to do with this warning that i get everytime i run a cypress test (i run my nestJS in a docker)
ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

**Comment by warrensplayer** [comment]
There are several issues reported that report the same "dri3 extension not supported" error: https://github.com/cypress-io/cypress/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+%22dri3+extension+not+supported%22. 

Trying to see if there is any correlation.

**Comment by warrensplayer** [comment]
@Reaster0 Are you able to provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/)

**Comment by warrensplayer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
