### ISSUE TITLE
No possibility to drag and drop to the top of the window when cypress scrolls down for the element

### ISSUE THREAD

**Issue by kapalkat** [cypress-io/cypress#2418]
### Current behavior:
Not able to drag and drop an element to the top of the document when window is scrollable and the element is at the very bottom.

### Desired behavior:
There should be some possibility to make this scenario working.

### Steps to reproduce:
1. I have a list of interactive elements. The list is quite long and the window is changed to scrollable to navigate through all those elements.
2. I want to get the element which is in the very bottom, drag it, scroll up and drop it to the top of the list.
Manually it looks like below:
<img width="1273" alt="draganddropmanual" src="https://user-images.githubusercontent.com/26725074/44877398-2595fa00-aca4-11e8-9055-3168ce7014ca.png">

Cypress behaviour:
a. cy.get() --> scrolls down to get the element
b. When I now try to drag and drop up, it's not possible as I am already at the top of the page:
![draganddropcypress](https://user-images.githubusercontent.com/26725074/44877513-81608300-aca4-11e8-835f-ae765c0d59bc.png)
c. There is no way to scroll up the window when dragging the element!

### Versions
Cypress 3.1.0
MacOS
Chrome

**Comment by kapalkat** [comment]
Hey, could you send some information regarding this? Maybe there is some workaround which I don't know about?

**Comment by kapalkat** [comment]
According to this: https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Scrolling, you always scroll into elements view when action is applied on it, so my question is how the hack I should scroll it back now holding the element to move it up?

I have already tried this:
        cy.get('tr > .dest-width > div.pull-right.drag-element:eq(3)',)
          .trigger('mousedown', { which: 1, force: true })
          .trigger('mousemove', { clientY: NEW_POSITION_Y, force: true })
          .trigger('mouseup', { force: true })
and this:
        cy.get('tr > .dest-width > div.pull-right.drag-element:eq(3)')
          .trigger('mousedown', { which: 1 })
          .then(() => {
            cy.scrollTo('top')
          })
          .trigger('mousemove', { clientY: NEW_POSITION_Y })
          .trigger('mouseup', { force: true })
and this:
        cy.get('tr > .dest-width > div.pull-right.drag-element:eq(3)')
          .trigger('mousedown', { which: 1 })
          .then(() => {
            cy.wrap($tbody).scrollTo('top')
          })
          .trigger('mousemove', { clientY: NEW_POSITION_Y })
          .trigger('mouseup', { force: true })
But none of this works. I can't move the elmenet up as it's Y coordinate is around 0.

**Comment by kapalkat** [comment]
Hey, team any updates regarding this? I haven't found any workaround so far.

**Comment by jennifer-shehane** [comment]
No updates have been made to this issue. We do have some work coming on being able to change the scroll behavior, but...I'm not sure that would help this scenario. https://github.com/cypress-io/cypress/issues/871

**Comment by Sakshi3110** [comment]
@jennifer-shehane 
I am facing some similar issue, **I want to scroll down the page so that lazy loaded ads appear when they come into view.**
I want to scroll down the page by scrolling down AUT and then come at the center of the page. I added following in my code :
	```
cy.window().scrollTo('0', '100%');
			cy.wait(3000);
			cy.scrollTo('0', '50%');
			cy.wait(3000);
```
This works perfectly when I am viewing the cypress tests window. As soon as I minimize the window and not looking into the tests, scrollTo do not work. When Cypress TestRunner/AUT is minimized, scrolling fails. I even tried - cy.scrollTo('bottom') , this also fails when window is minimized. Fails means, I remain at top of the page only and do not get any errors.

**Comment by Sakshi3110** [comment]
@jennifer-shehane 
I am facing some similar issue, **I want to scroll down the page so that lazy loaded ads appear when they come into view.**
I want to scroll down the page by scrolling down AUT and then come at the center of the page. I added following in my code :
`cy.window().scrollTo('0', '100%');
			cy.wait(3000);
			cy.scrollTo('0', '50%');
			cy.wait(3000);`

This works perfectly when I am viewing the cypress tests window. As soon as I minimize the window and not looking into the tests, scrollTo do not work. When Cypress TestRunner/AUT is minimized, scrolling fails. I even tried - cy.scrollTo('bottom') , this also fails when window is minimized. Fails means, I remain at top of the page only and do not get any errors.

**Comment by Szymon-dziewonski** [comment]
Im also looking into how to in my case drag scrollbar, and I can't do it
 
Cypress version `12.12.0`

**Comment by nagash77** [comment]
@Szymon-dziewonski have you had a chance to check out our [community chat](https://discord.gg/cypress)? It can be helpful for debugging or answering questions on how to use Cypress. If you have a reproducible example to share please do and we can investigate.

**Comment by Szymon-dziewonski** [comment]
@nagash77 Thank you for swift reply, will try to work a bit with it and if no result I will contact community chat, at the end I will probably create reproduction. Sorry, I possibly wrote comment too fast :)

**Comment by nagash77** [comment]
@Szymon-dziewonski , thank you for the reply.  I am going to close this issue for the time being.  If/When you create a reproduction comment back here on this ticket and we can reopen and investigate.
