### ISSUE TITLE
Screenshots not working for WebGL-based map in Firefox

### ISSUE THREAD

**Issue by ludazhao** [cypress-io/cypress#24200]
### Current behavior

Currently cy.screenshot() returns a blank screenshot for our page with a MapboxGL-based map in Firefox (version 91.7.0esr). Loading the page renders the map normally and the map shows up normally on the uploaded video recording as well, only when we take a screenshot does it show a blank map. The screenshot seems to work fine with the built-in Electron browser, only on Firefox does it break.

With Firefox:
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/4770594/195108449-44cdc4ca-300a-48ae-ae65-132b75429d50.png">

With Electron:
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/4770594/195109932-aae7b110-9554-479a-b6a8-844a3409842d.png">

### Desired behavior

Cypress should take a screenshot with the map loaded

### Test code to reproduce

```
//wait for map to load
cy.screenshot();
```

### Cypress Version

9.5.2

### Node version

v14.17.1

### Operating System

Debian GNU/Linux

**Comment by warrensplayer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Also, I see you are using Cypress version 9.5.2.  Are you able to update to the latest version of Cypress to see if you still experience this issue.  The latest version is 10.10.0

**Comment by warrensplayer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
