### ISSUE TITLE
Automatic proxy rewrites of `window.top` expressions break app already including an iframe

### ISSUE THREAD

**Issue by rene-leanix** [cypress-io/cypress#24237]
### Current behavior

The Cypress proxy [rewrites expressions with `window.top`](https://github.com/cypress-io/cypress/blob/688b7ea33e8243a76fc1b3bd7f5ef7f2bfba07f9/packages/proxy/lib/http/util/regex-rewriter.ts#L36-L38) in any JS file loaded during a Cypress test to ensure that the tested app does not realise it's being executed in Cypress' iframe. A problem occurs if the tested app itself already includes an iframe with JS code, that behaves differently when executed in an iframe rather that in the top-level window.

### Desired behavior

Ideally, the iframe-related rewrites should only happen for code that has been requested by the top-level window of the tested app and not for code within iframes within that app.

If that's not possible, Cypress should allow for a way to disable the iframe-related rewrites or possibly all rewrites (see #22319).

### Test code to reproduce

Serving an app containing an iframe loading the following script will demonstrate that the rewrite also happens with the iframe:

```js
alert(window.top === window.self)
```

### Cypress Version

10.10.0

### Node version

v16.16.0

### Operating System

macOS 12.6

### Other

Our current workaround is to replace `window.top` with `window.self.top` in our code, which isn't replaced right now and hopefully won't be replaced in the future either until this bug is fixed or the rewrite can be turned off.

I understand why that the rewrite is necessary for the majority of apps containing `window.top`-checks and that there is no good alternative (since `window.top` cannot be overwritten or redefined). But this is such a surprising and difficult-to-find "feature" of Cypress, that it should actually be pointed out to the user when this rewrite happens! How about adding a note in the Cypress window that code was rewritten?

Please don't just close this issue as a duplicate of #136...

**Comment by AtofStryker** [comment]
Hi @rene-leanix . Thank you for opening an issue. I think you hit the nail on the head here in saying

> Ideally, the iframe-related rewrites should only happen for code that has been requested by the top-level window of the tested app and not for code within iframes within that app.

This is something we have considered in the past. However, it is pretty difficult to do correctly, since we likely want to rewrite certain top referencing code within iframes to actually point to the application under test iframe. 

The good news is this "feature" is configurable and it's called [modifyObstructiveCode](https://docs.cypress.io/guides/references/configuration#modifyObstructiveCode). It is turned on by default, but can be disabled by setting the option to false. Would you be able to give this a try?

In the future, we are likely adding further changes to [modifyObstructiveCode](https://docs.cypress.io/guides/references/configuration#modifyObstructiveCode) with what is currently [experimentalModifyObstructiveThirdPartyCode](https://docs.cypress.io/guides/references/experiments#Configuration) which adds further rewrites and extends this rewriting out to third party html and javascript files to prevent frame busting which is common with authentication providers, including stripping SRI on links and scripts (this will likely be a separate option in the future to not conflate security concerns). However, if none of this concerns you, this can always be opted out 😃 .

**Comment by rene-leanix** [comment]
Thanks for your quick response, @AtofStryker! I completely missed the `modifyObstructiveCode` config option, even though I even checked your code on this. This does the trick!

Just to reiterate the obvious: framebusting is not the only reason why code may contain checks like `window.self === window.top`. In the code we've included via an iframe this check was included to differentiate between embed/iframe mode and standalone mode, both of which are supported by the code.

So the following comment on [modifyObstructiveCode](https://docs.cypress.io/guides/references/configuration#modifyObstructiveCode) could potentially mislead developers to think that it's never wrong to enable `modifyObstructiveCode`:

> These techniques prevent Cypress from working, and they can be safely removed without altering any of your application's behavior.

I'm just mentioning this in case your team would consider clarifying your documentation on this feature, but it's certainly a rare edge case!

Thanks again for your help!
