### ISSUE TITLE
Cypress keeps freezing

### ISSUE THREAD

**Issue by fabianhijlkema** [cypress-io/cypress#24270]
### Current behavior

While trying to check out Cypress with the most basic setup possible, it keeps freezing or erroring out most of the time. While running it with `npx cypress open` or `npx cypress run`. The Cypress application in that case will be unresponsive according to Activity Monitor. It's just plain unusable like this.

Cypress versions tried 10.10.0, 10.9.0, 10.8.0

<img width="1683" alt="Screenshot 2022-10-15 at 22 26 03" src="https://user-images.githubusercontent.com/2919995/196007463-28e8f983-f35e-496f-a57f-01ad7e286950.png">

### Test code to reproduce

Spec (tried with other urls as well):
```
describe('empty spec', () => {
  it('passes', () => {
    cy.visit('https://example.cypress.io')
  })
})
```

cypress.config.js
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
  },
});
```

Other files are just an empty index.js file and Cypress as the only dependency. 

### Cypress Version

10.10.0

### Node version

18.11.0

### Operating System

MacOS 12.2.1

**Comment by nagash77** [comment]
@fabianhijlkema can you confirm it is a typo in your node version?  I assume you mean 18.19.2

**Comment by fabianhijlkema** [comment]
Sorry, that was NPM version. Node version 18.11.0.

**Comment by warrensplayer** [comment]
@fabianhijlkema Are you able to send a screen recording of what is happening?

**Comment by amehta265** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
