### ISSUE TITLE
Spike into relaxing strict same-origin requirement for cy.origin

### ISSUE THREAD

**Issue by mjhenkes** [cypress-io/cypress#24274]
Spike into relaxing the strict same-origin requirement for cy.origin to instead allow super-domain same origin for sites that allow.

We should be able to support spec bridges with super-domains connecting to AUT's declared with sub domains using document.domain if possible. We must also support spec bridges declared with sub domains specifically.

The outcome of this spike should be logged tasks to complete this work, no tasks if the work is unfeasible, or a PR if the work can be completed within the spike.

**Comment by AtofStryker** [comment]
Going to try and gather my thoughts here. I created a revert of the [same-origin-spec-bridges commit](https://github.com/cypress-io/cypress/compare/spike/super-domain-origin-spec-bridges?expand=1) to give this a test to see how the two compare against each other.

Below are some bulletpoints discovered with some differences, from what I believe to be least important to most important

### devtools

##### same-origin
![same-devtools](https://user-images.githubusercontent.com/3980464/199080530-5ba2ee32-7820-40da-affe-8ab9491837e9.png)

##### super-origin
In the case of super origin, the user may/may not get an extra cookie jar tab. This likely isn't a huge deal, especially due to the unlikely nature that cookies are actually visible here, but might lead to confusion as to why it exists in the first place

![super-devtools](https://user-images.githubusercontent.com/3980464/199080581-3e450bc0-ec1f-48e5-b6dc-5967721bbd58.png)

### Metadata Request Headers

##### same-origin
Main differences here between `same-origin` vs `same-site` spec bridges is the omission of the `Origin` Metadata header, as well as the more obvious `Sec-Fetch-Site` header. 

![same-set-cookie-request-headers](https://user-images.githubusercontent.com/3980464/199092102-a46b7566-740e-47f5-978c-6c74871e5424.png)

##### super-origin
![super-set-cookie-request-headers](https://user-images.githubusercontent.com/3980464/199092125-2778e1b3-0da5-43f1-a036-420e2c0a055d.png)


### Relative URLs

##### same-origin
The nice thing here is that `window.origin` and other window properties will be in close parity as whatever the AUT is on when the origin block is invoked, and because of that certain inferences can be made, including relative requests to the expected AUT

![relative-url-same](https://user-images.githubusercontent.com/3980464/199082422-e1402190-1ebc-4fdd-93d4-2cfa0f080e00.png)

##### super-origin
In this case, to make requests to the AUT in the case of a present sub domain, the user is going to have to specify the whole domain here. I am not sure how common this is, but I think it could be a bit of a pain when trying to debug this as the request will likely either fail or just time out depending on the server setup.

![relative-url-super](https://user-images.githubusercontent.com/3980464/199081705-4725390b-3ee7-4e61-b36c-bc088badf9f2.png)

![super-relative-url](https://user-images.githubusercontent.com/3980464/199080671-726dc96e-a423-4dbe-8686-8afb84948de1.png)

### Inferred Cookie Context
One thing that I am struggling to wrap my head around is how we would know how to correctly apply cookies in the super-origin spec bridge to users making requests from `cy.origin`. If a user is planning on visiting `app.foobar.com`, but the spec bridge is created for `foobar.com`, and simulated cookies are set on `app.foobar.com`, do requests from the spec bridge need to attach `app.foobar.com` cookies or are they omitted? How can we tell if a request came from a spec bridge? Likely not a common use case, but we do get these things by default in the current state with `same-origin` spec bridges. 

### Number of spec bridges
With super origin spec bridges, the user would be able to interact with multiple cross origin sub domains with a single spec bridge, lessening the number of spec bridges needed in this use case.

### Possible inconsistencies with exceptions
As we know, `*.google.com` in Google Chrome requires strict origin matches for spec bridges. However, if we only create a strict origin spec bridge for google sub domains, it makes our behavior within the origin block inconsistent from what we have seen above. This also becomes inconsistent when the visited domain lacks a subdomain and the spec bridge is an exact origin match in this case, leading to relative urls in this case only. 


### Messaging

##### implied nature of `cy.origin`
As the name implies, `cy.origin` takes a string argument of `origin`. I would expect my serialized function to execute in this origin context and not the super domain context.

##### Error messaging
When we moved to `same-origin` spec bridges, a lot of our error messaging became clearer around expected visited origin vs actual. In other words, with super domains you might get an error message like this:
```
The command was expected to run against origin `http://foobar.com:3500` but the application is at origin `http://barbaz.com:3500`.
```

When, in fact, your application might actually be at `http://www.barbaz.com:3500` as it's origin. Tying into the first point of implied nature, we are blending the idea of `super-domain` with `origin`, which I think confuses users as to what an origin actually is. Since `origin` is defined definitely to the webdev community, I don't think mixing these terms externally to users is a good idea. We would introduce to users the idea of `super-domain` origins, but this I don't think is exactly discoverable, even if we contain it inside our documentation 

## Possible future issues

### Iframes
Obviously a lot of unknowns with this one, but it is a real possibility in the future when we implement iframe support that we will have multiple iframes that are cross origin to top but are relatively same origin to themselves. In this case, we likely need an additional layer of specificity to interact with the correct iframe in which cypress is injected to, which likely means another `cy.iframe/origin` like block per iframe interacted with. I think this extension in the future is likely easier with the spec bridge iframe being that of same origin than that of same site since we likely need to create multiple spec bridge frames anyway in order to interact with the correct iframe, and we can get all the benefits of same origin with the spec iframe. This belief also would extend down to implied cookie domain from the spec iframe with the cookie api, as we can infer the domain directly from the spec bridge iframe

### simulating the spec iframe
Since we plan to allow sub domain visits without reloading, we will need a way in the future to simulate cookies within the spec iframe as it can be `same site / cross origin` to the AUT . This is much easier to do with just the spec iframe, as there is only always one and we can simulate this context correctly, as opposed to trying to figure out the one to many relationship in which a request came from

## My recommendation

I think we should keep `cy.origin` spec bridges same origin, but gate creation of them to the primary with our superdomain rules in mind (ie you can only create if cross site/ cross origin or same site / cross origin if top is a google domain and prompt error messaging). I think this is much clearer to end users and will help avoid some weird caveats that users have run into in the past. I also think it might avoid a maintenance nightmare. For instance:

#### Scenario A 
* `cy.visit` establishes top origin
* `cy.visit` to same site / cross origin
* user does NOT need to specify a `cy.origin` except in the case top is `*.google.com` and is running in chrome (same origin also keeps this consistent from within the origin block. We likely want to force in all browsers). If the user specifies a `cy.origin` block outside of this case, throw an error that guides the user to just `cy.visit` and continue to write commands

#### Scenario B 
* `cy.visit` establishes top origin
* `cy.visit` to cross site / cross origin
* User needs to specify an origin block. If they don't, throw an error that guides the user to do this (we do this today)

#### Scenario C 
* `cy.visit` establishes top origin with `www.google.com`
* `cy.visit` to same site / cross origin with `accounts.google.com`
* If the user is in chrome, the user needs to specify a cy.origin block to interact with the frame. Throw an error if not provided to point user in the right direction

**Comment by AtofStryker** [comment]
Also need to discuss scenario D, if a user's navigation is `same-site / cross origin` in CI/local, but on local/CI their navigation is `cross-site / cross-origin`. How do we make this experience seamless? 

see #24373
