### ISSUE TITLE
Adding how to perform code coverage in cypress directories in the documentation 

### ISSUE THREAD

**Issue by regulas1** [cypress-io/cypress#24283]
### What would you like?

Since Cypress uses mocha having the code coverage helps the contributors know what unit tests are missing.

One way of performing this is adding nyc to the dependencies but I think that would be a significant feature request which I can raise another time. 

However if we add the nyc package globally in the local machine and add the generated nyc report files in .gitignore, this way we can know what code is not covered and write where unit tests are missing.

I would like to contribute by Adding the replication steps to get the test coverage locally and raise a pull request for it.

Additionally a chore ticket can be raised based on the code coverage to add more unit tests.

### Why is this needed?

Improvements in the code quality and reduces any major breaking changes 
![image](https://user-images.githubusercontent.com/66300767/196320330-420f6737-b3f4-45db-8bf5-b143218ca3a5.png)

![image](https://user-images.githubusercontent.com/66300767/196320485-69657989-3492-4e2b-8b0f-b55aebd4b9b7.png)

### Other

There are mutliple new contributors asking for this as well based on the discussions

**Comment by mschile** [comment]
Hi @regulas1, thanks for opening this request. Have you taken a look at our existing [code coverage plugin](https://github.com/cypress-io/code-coverage) and [docmentation](https://docs.cypress.io/guides/tooling/code-coverage#What-you-ll-learn)?

**Comment by regulas1** [comment]
@mschile  apologies for not writing the request correctly. My question is that can we check the code coverage within cypress package ?

For instance finding the code coverage in https://github.com/cypress-io/cypress/tree/develop/cli within cypress, that is my proposed use case. 

As a new contributor i want to start with unit tests to get used to the system

**Comment by nagash77** [comment]
Hello @regulas1 Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [Discord server](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io/), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
