### ISSUE TITLE
Wrong detect of framework & bundler when run cypress open

### ISSUE THREAD

**Issue by irenetang1993** [cypress-io/cypress#24319]
### Current behavior

Q1: I am using React & vite. when I run `npx cypress open`, it detect framework is React, which is right. and detect bundler is Webpack, which should be vite.

This is package.json
```
{
  "name": "my-awesome-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "@vitejs/plugin-react": "^2.1.0",
    "cypress": "^10.8.0",
    "typescript": "^4.6.4",
    "vite": "^3.1.0"
  }
}
```

This is vite.config.ts
```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()]
})
```

Q2: When I run `npx cypress open --component`, it doesn't detect framework & bundler.
<img width="675" alt="image" src="https://user-images.githubusercontent.com/17581661/196876562-6f209d39-9d6a-4fd0-b93a-f9c1fb794627.png">
<img width="682" alt="image" src="https://user-images.githubusercontent.com/17581661/196876681-1a7af1c2-7989-446e-8b3e-e218705d966a.png">

### Desired behavior

It should detect the right framework & bundler.

### Test code to reproduce

https://github.com/cypress-io/cypress-component-testing-apps/tree/main/react-vite-ts

### Cypress Version

10.8.0

### Node version

v14.18.3

### Operating System

macOS 10.15.7

**Comment by amehta265** [comment]
@irenetang1993 Thank you for opening this issue.

I have been able to create a very basic `react-vite-ts` application with the same dependencies provided in your `package.json` screenshot. On my end, when running `npx cypress open` Cypress was able to detect both the framework and bundler correctly.

![Image](https://user-images.githubusercontent.com/65267668/198690921-c72aff90-9d4b-4868-8b67-4f319f2497a3.png)

With regards to Q2, we are aware of this problem and are hoping to get to solving it pretty soon. This is the related issue: https://github.com/cypress-io/cypress/issues/22777

For now, We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward as I have been unable to replicate the unrecognizable bundler when running `npx cypress open` on my end.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
