### ISSUE TITLE
[Question] What's the best/recommended way to handle login before each test with setting (Redux) state

### ISSUE THREAD

**Issue by MichaelDeBoey** [cypress-io/cypress#2435]
Hi all!

At my company we're making a SaaS app in React + Redux, which is only available for logged in users (like most SaaS apps).

Of course I've already read [the recommendations about logging in](https://docs.cypress.io/guides/getting-started/testing-your-app.html#Logging-In).
The only problem we face, is that we're setting (Redux) state after the request happened, so the proposed `cy.request()` won't help.

Is there any recommendation for stuff like this?

We tried executing our custom `cy.login()` command inside the `test:before:run` event hook (which does a manual login, but will only run once due to the hook), but we couldn't get this to work unfortunately. 😕

Hopefully somebody can help us with  this. 🙂

Thanks in advance for putting your time into our question! 🙂

Kind regards,

Michaël

**Comment by brian-mann** [comment]
Read this best practice: https://docs.cypress.io/guides/references/best-practices.html#Organizing-Tests-Logging-In-Controlling-State

It has a link to a video that will answer your question - although it sounds like you just need to use a `beforeEach`. Modifying the redux state is easy - you could login via a `cy.request` and set the `localStorage` or whatever it is that your state looks for when knowing whether its logged in.

After the app loads you can access the state directly through `cy.window()` and then modify it at will.

**Comment by euZebe** [comment]
@brian-mann you say that "Modifying the redux state is easy", but I am not sure to understand how one could initialize redux state with a different fixture for each test case, since Redux only allows to set the state during `createStore()` call (or by dispatching an action which would reset the whole store, but I don't think this is an option).
The example in the video you redirect to just shows a token stored in the localStorage, which is slightly different from redux store.

What I did so far is allowing tests to access redux store as follows:
```javascript
const store = createStore(reducers, initialState); // business code
if (window.Cypress) {
  window.__store__ = store; // so that I can easily dispatch actions in cypress tests
}
```
I can't use any fixture here. Any other suggestion ? Something like
```javascript
cy.fixture('myInitialState.json').then(initialState => {
  cy.window().invoke('__store__.getState').then(state => {
    Object.entries(state).forEach(([key, value]) => state[key] = initialState[key])
  });
});
```
(I can't imagine uglier solution ;-) )
