### ISSUE TITLE
cy.origin throws Uncaught error & breaks in v10.9.0+

### ISSUE THREAD

**Issue by Hawxy** [cypress-io/cypress#24373]
### Current behavior

Our application redirects on load to an Auth0 login page and signs in the user. We updated from v10.7.0 to v10.10.0 and immediately ran into failing origin usage with the below stacktrace:

```
Uncaught Error: on only accepts instances of Function
    at ../driver/node_modules/eventemitter2/lib/eventemitter2.js.EventEmitter._on (xml.js:30:2)
    at ../driver/node_modules/eventemitter2/lib/eventemitter2.js.EventEmitter.on (xml.js:30:2)
    at attachToWindow (xml.js:30:2)
    at SpecBridgeCommunicator.<anonymous> (xml.js:30:2)
    at SpecBridgeCommunicator.emit (xml.js:30:2)
    at SpecBridgeCommunicator.onMessage (xml.js:30:2)
    at xml.js:30:2
```

![image](https://user-images.githubusercontent.com/975824/197680169-698606c2-7299-4467-acf9-5104a800afba.png)

This error appears to stop the login from working properly, as it fails to find the password field despite it being readily available on the DOM:

![image](https://user-images.githubusercontent.com/975824/197683492-17f19c61-8d58-4592-a2c9-6e35a9f0f355.png)
![image](https://user-images.githubusercontent.com/975824/197683630-b83bd7c5-78ed-46bf-b2de-2efae14e5bbd.png)

### Desired behavior

`cy.origin` works successfully.

### Test code to reproduce

I'm working on a reproduction, but I've discovered that the login works fine whilst running on localhost and only breaks when pointed at our cloud environment. The code being used is very simple & worked on previous versions:

```ts
      cy.origin(Cypress.env('AUTH0_DOMAIN'), { args }, ({ email, password }) => {
        cy.get('#username').type(email);
        cy.get('button')
          .contains(/^Continue$/)
          .click();
        cy.get('#password').type(password);
        cy.get('button').contains('Continue').click();      
      });
```

There's also another user running this problem here: https://github.com/cypress-io/cypress/issues/21201#issuecomment-1277427102

### Cypress Version

10.10.0

### Node version

v16.17.0

### Operating System

Windows 11 22H2

**Comment by Narretz** [comment]
I'm also having the  exact same problem. It still worked in Cypress 10.8. We should try to isolate the exact version where this happens, i.e. if it starts in 10.9 or 10.10

**Comment by mschile** [comment]
@Hawxy, @Narretz, do either of you have a reproduction I could look at and debug?

**Comment by Narretz** [comment]
@mschile That's a bit difficult because the error is caused only with auth0 as it looks right now. Does the Cypress team have an auth0 setup we could use for a repro?

**Comment by Hawxy** [comment]
@Narretz Are you also using a custom auth0 domain for logins? I've been testing this and it appears to be the cause. Using the auth0.com domain works fine.

**Comment by Hawxy** [comment]
@mschile I've been able to reproduce this against auth0's lab environment which uses a custom domain. Updating to 10.11.0 fixed the error being thrown (maybe it's being caught internally?) but the origin is still not working:

https://github.com/Hawxy/auth0-cypress-reproduction

`npm i` & `npx cypress open`.

**Comment by Narretz** [comment]
@Hawxy yes, I'm also using a custom domain.

Cool that you've created a repo. My setup looks much the same, but without cy.session. Is it necessary for the failure to occur?

**Comment by Hawxy** [comment]
> Is it necessary for the failure to occur?

No, it's not. The issue is specifically with `cy.origin` it seems.

**Comment by mschile** [comment]
@Hawxy, thanks a lot for taking the time to create a reproduction! I'm hoping to get some time today to take a look at it.

**Comment by AtofStryker** [comment]
Hi @Hawxy and @Narretz. @mschile and I spent some time investigating today and saw the code worked in `10.9.0` and `10.10.0`, but stopped working in `10.11.0`. The behavior in `10.11.0` is actually the correct behavior, but the error message isn't helpful. I'll try to explain.

Cypress allows users to use `cy.visit` without `experimentalSessionAndOrigin` to urls that are otherwise the same, but the [subdomains are different](https://docs.cypress.io/guides/guides/web-security#Limitations). So in this case, the `cy.origin` block isn't needed since `https://config.auth0lab.com` is a subdomain/same-site to `https://manage.auth0lab.com`. However, right now we do not provide a great error message around this, and we plan to make this experience better with #24169 to error with `cy.origin` being called for `same-origin` and `same-site/subdomain` invocations to help guide users in the right directions. That way if you run into this in the future, you will get a useful error message as opposed to the `cy.origin` block timing out and the failure being a mystery.

What I think happened in `10.9.0` and `10.10.0` is one of the events we use to execute the `cy.origin` serialized function was still getting sent when it shouldn't, leading to an edge case and likely triggering the `Uncaught Error: on only accepts instances of Function`.

I've opened two PRS against the reproduction repo to show [login within the same-site/different subdomain](https://github.com/Hawxy/auth0-cypress-reproduction/pull/1) as well as if the sites are in fact [cross-site/cross-origin](https://github.com/Hawxy/auth0-cypress-reproduction/pull/2). Both should be able to interact with the form 😄 

I did want to ask the following to make sure your issue is actually resolved: **Is the `baseUrl` for your actual project `https://manage.auth0lab.com`? If not, what is your actual `baseUrl`?** If the `baseUrl` is actually different, this could be a different problem entirely.

**Comment by Hawxy** [comment]
Thanks for the investigation, I've tested it and that was the issue. It also explains why it would work fine when running on localhost but not against our cloud environment running on a subdomain. I've updated our implementation with a check to only use `origin` when running against localhost and we appear to be back in business.

**Comment by AtofStryker** [comment]
@Hawxy glad to know that resolved your issue! If you run into any other trouble please let us know and hopefully some of the messaging changes we make in the near future help avoid this type of stuff from coming up 🙂

**Comment by Narretz** [comment]
@AtofStryker thanks for the update, that makes a lot of sense. Is there a ticket for that message improvement? If not, I have the feeling this will be forgotten ...

**Comment by mjhenkes** [comment]
@Narretz, the ticket is https://github.com/cypress-io/cypress/issues/24169. I'm currently working on it and it likely will be in the release next week.

**Comment by Narretz** [comment]
That's great to hear @mjhenkes!
