### ISSUE TITLE
cypress API not working from .Net --> {"status":"failed","failures":1,"message":"Could not find Cypress test run results"}

### ISSUE THREAD

**Issue by arunvenkat1911** [cypress-io/cypress#24436]
### Current behavior

Hi Team,

We are trying to run the cypress test from .NET using NodeService. 
When we are running the same test from node js command prompt, we are getting the proper response.

Below is the code.. 

```
const cypress = require('cypress')

 cypress
   .run({
     // the path is relative to the current working directory
     spec: './cypress/e2e/Test1.cy.js',
   })
    .then(testResults => {
     console.log("---resultJSON---");
     console.log(testResults);     
   })
    .catch((err) => {
     console.error(err)
   })
```
I am running like this on cmd: 
node [FilePath] 
And I am the proper response.

When I try to convert this for .NET like this. 
```
const cypress = require('cypress')

module.exports = async (callback, strSpecFilePath) => {
    const objResults = await cypress
        .run({
            reporter: 'junit',
            browser: 'chrome',
            spec: strSpecFilePath,
            record: false
        })
    callback(null, objResults);
};
```
And when I am running this from .NET nodeservice.InvokeAsync. 
I am getting this response 
```
{"status":"failed","failures":1,"message":"Could not find Cypress test run results"}
```
Please help us to solve the issue.

Arun.

### Test code to reproduce
```
const cypress = require('cypress')

module.exports = async (callback, strSpecFilePath) => {
    const objResults = await cypress
        .run({
            reporter: 'junit',
            browser: 'chrome',
            spec: strSpecFilePath,
            record: false
        })
    callback(null, objResults);
};
```
### Cypress Version

10.11.0

### Node version

v16.17.0

### Operating System

windows

**Comment by nagash77** [comment]
Hello @arunvenkat1911 .  Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [Discord server](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io/), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by riaadh** [comment]
any news in this error? thanks

**Comment by eranshahar** [comment]
Happens to me also, any news?
