### ISSUE TITLE
Tailwind hidden class but change on group-hover

### ISSUE THREAD

**Issue by hilmanski** [cypress-io/cypress#24431]
### Current behavior

I have a child element that has a [group-hover](https://tailwindcss.com/docs/hover-focus-and-other-states) class.
Which basically, it detect if the parent is hovered, then the child should change the value based on what we put.

In this child element, my manual class is "hidden" , but change /overwritten when the parent is on hover.

But in cypress, it always detect this tailwind hidden class
```
This element `<div>` is not visible because its parent `<div.hidden.group-hover:flex.absolute.w-11/12.bottom-20.left-0.right-0.mx-auto.p-2.bg-white.border.rounded-xl.shadow-sm.space-x-2>` has CSS property: `display: none`
```

### Desired behavior

If the value display is overwritten then we should be able to perform action such as click on this element

### Test code to reproduce

Element
```
 <div
            id={`wrapper-pdf-page-1`}
            className="relative group">
  ...
<div data-cy='removeBtn' className="hidden group-hover:flex">
             REMOVE
</div>

</div>
```

Test
```
 // hover on a page
    it('should hover on a page', () => {
        cy.get('#wrapper-pdf-page-1').trigger('onmouseover')
        cy.get('#wrapper-pdf-page-1').trigger('mouseenter')
        cy.get('[data-cy="removeBtn"]').first().click()

        // check '#wrapper-pdf-page-1' removed
        cy.get('#wrapper-pdf-page-1').should('not.exist')
    })
```

### Cypress Version

^10.11.0

### Node version

16

### Operating System

macoS

**Comment by amehta265** [comment]
@hilmanski Thank you for opening this issue.
Unfortunately, the information you have provided is not sufficient enough to reproduce this issue on my end. I do not know what your parent element `wrapper-pdf-page1` is and therefore I am unable to assert a trigger on the parent element which would then render the child element as explained in the issue.

Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by hilmanski** [comment]
> @hilmanski Thank you for opening this issue. Unfortunately, the information you have provided is not sufficient enough to reproduce this issue on my end. I do not know what your parent element `wrapper-pdf-page1` is and therefore I am unable to assert a trigger on the parent element which would then render the child element as explained in the issue.
> 
> Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.
> 
> Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Hi sorry for missing the proper reproducable test. I just add the parent div for this case

**Comment by amehta265** [comment]
@hilmanski Thank you for updating the test!

Unfortunately I still do not have enough information to accurately reproduce this issue. I do not know what your tailwind configurations and classes look like and therefore I cannot accurately mimic the `group-hover` styles on your elements. Secondly, I do not have the logic behind "...if the parent is hovered, then the child should change the value based on what we put." Having this information is important so that I can test the desired behavior on my localhost and see if the value of the child component changes on my side, after which I can look into the behavior on Cypress.

Providing a a [Short, Self Contained, Correct, Example](http://sscce.org/) reproducible example perhaps in the form of a repository would be much more helpful in debugging this issue.

**Comment by hilmanski** [comment]
Hi @amehta265 
I think the tailwind configuration not necessary in this case. It's all in tailwind. 
A group and group-hover is a default behavior on tailwind https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state

**Comment by marktnoonan** [comment]
Hi, I'm curious about this line:

`cy.get('#wrapper-pdf-page-1').trigger('onmouseover')`

Shouldn't that be `trigger('mouseover')`?

I think the testing strategy here will depend on how tailwind implements the group hover, if it's a CSS-only solution depending on `:hover` CSS state, triggering the JS mouse events may not create the actual hover state that Tailwind is looking for. If that's the source of the problem, common workaround is `cy.realHover` using https://github.com/dmtrKovalenko/cypress-real-events.

**Comment by hilmanski** [comment]
thanks @marktnoonan 
will explore your answer
