### ISSUE TITLE
Conclude Smart Prompt A/B tests

### ISSUE THREAD

**Issue by pstakoun** [cypress-io/cypress#24472]
Remove A/B testing from Smart Prompts and replace with permanent versions that use the content from the following cohorts:
Specs Login Banner: B
Specs Create Organization Banner: A
Specs Create Project Banner: B

There should be no `utm_content` sent on the "viewed" event or any subsequent events (e.g. login, org create, project create). Whereas now we set the content to "A"/"B", we should leave it empty/null/not send it, so as to not be confusing in analytics data. We will have to start sending these again if/when we do additional A/B tests.

There will be additional A/B tests run on the content and/or styles of the banners in the future.

**Technical Solution Proposal**
* Update `SpecsListBanners` to indicate the campaign is over and the winning options have been chosen
  * Add a comment next to `bannerCohortOptions` that explains the campaign, refer to this issue if desired
  * Add a field to `bannerCohortOptions` to indicate which option was the "winner"
  * Update `getCohortForBanner` to always return the selected option for each banner and to skip the call to `cohortBuilder.getCohort`
* Update the values and/or logic to make sure that `TrackedBanner` does not send `utm_content` in the call or sends a blank value - (E.g. set `cohort` value to empty string)
* Update appropriate tests

**Comment by baus** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/24472?planning-poker) with Zenhub @amehta265 @astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
Can someone with more knowledge on ACI elaborate a little more on the technical requirements? I am not entirely sure how to weigh this one.

**Comment by marktnoonan** [comment]
There's a short way to do it, which is to make the content the same for [contentA and contentB variants in en-US.json](https://github.com/cypress-io/cypress/blob/develop/packages/frontend-shared/src/locales/en-US.json#L200-L201).  That would leave the cohort infrastructure around these banners intact for future experiments, and would need minimal testing changes.

The drawback with this is that it leaves the code doing this (now pointless) branching and cohort business where each cohort actually ends up seeing the same content. Which could be confusing when you come to this part of the code with fresh eyes.

@pstakoun could you give some guidance if `Remove A/B testing from Smart Prompts` really means "remove" in the sense that we'd remove the actual idea of them being aware of cohorts, stop tracking what banners have been seen, etc. Or do we want to keep everything the same, anticipating future experiments, and just match the content for all cohorts for the time being. 

You may have already planned out the process of ending the experiment with @warrensplayer. I'd say the minimal content change + test updates is about a single day task, fully removing is more like a few days to a week, depends on how much of the cohort setup we want to keep for the future, since we need to keep it tested somewhere - if it's not actively being used by the app it's dead code. 

We might want to split this up in to two steps so that we can start showing the better set of content right away, even if full removal takes a bit longer.

**Comment by pstakoun** [comment]
@lmiller1990 @marktnoonan I do intend to run additional A/B tests or either the content and/or the styles of the banners. I think I would prefer if `utm_content` was not being sent if there was not an actual A/B test running, since that would probably be confusing in the analytics. I'll update the issue to clarify.

**Comment by warrensplayer** [comment]
@astone123 @lmiller1990 @marktnoonan @mike-plummer @rockindahizzy @ZachJW34 I have updated the issue description with a proposed technical solution.  I am not sure how to remove the Planning Poker estimates to start over, so please just update your estimates if needed after you review my proposal.  I would like to consider this for the next sprint.
