### ISSUE TITLE
 Webpack compilation error 

### ISSUE THREAD

**Issue by annaswan0001** [cypress-io/cypress#24486]
### Current behavior

Writing e2e tests with cypress 9.7.0 (with CRA 17), it's been fine for a half a year. I has been not creating new tests for 1 month. But few days ago only wrote command cypress open  and now I have this Error: Webpack Compilation Error - Unexpected сharacter.
![WP compilation error](https://user-images.githubusercontent.com/42541919/199240585-66be6d78-3bfa-4095-aceb-505034c9dab8.png)

I have create-react-app webpack config, not ejecting. Everything works find in app.
So I decided to add webpack preprocessor and I fixed  this error,   but  receive several new errors
          `const findWebpack = require('find-webpack');
          const webpackPreprocessor = require('@cypress/webpack-preprocessor');
          
          /**
           * @type {Cypress.PluginConfig}
           */
          module.exports = on => {
            // find the Webpack config used by react-scripts
            const webpackOptions = findWebpack.getWebpackOptions();
          
            if (!webpackOptions) {
              throw new Error('Could not find Webpack in this project 😢');
            }
          
            // if we just pass webpackOptions to the preprocessor
            // it won't work - because react-scripts by default
            // includes plugins that split specs into chunks, etc.
            // https://github.com/cypress-io/cypress-webpack-preprocessor/issues/31
          
            // solution 1
            // blunt: delete entire optimization object
            // delete webpackOptions.optimization
          
            // solution 2
            // use a module that carefully removes only plugins
            // that we found to be breaking the bundling
            // https://github.com/bahmutov/find-webpack
            const cleanOptions = {
              reactScripts: true,
            };
          
            findWebpack.cleanForCypress(cleanOptions, webpackOptions);
          
            const options = {
              webpackOptions,
              watchOptions: {},
            };
          
            on('file:preprocessor', webpackPreprocessor(options));
          };`

Now I have new error that I cant resolve. Can you help me? And why did it happen after half a year working correctly?
![New WP error](https://user-images.githubusercontent.com/42541919/199241570-7255c2a6-5959-4e5f-8782-6124a30810a7.png)

### Desired behavior

Working without Webpack Compilation Error

### Test code to reproduce

All tests are invalid but was working correctly earlier

### Cypress Version

9.7.0

### Node version

v12.22

### Operating System

10.14.5

**Comment by amehta265** [comment]
@annaswan0001 Thank you for opening this issue.
Based on the screenshot and `webpack config` it looks like the correct loaders may not have been configured to handle certain file extensions in your `webpack config` file. Based on your first screenshot you may need to declared `css-loaders` and `style-loaders` in your `webpack config` to handle the `.css` files.

Have you tried upgrading to to cypress 10? This may resolve your issue. All you have to run is `npm install cypress@latest --save-dev`. Once you run cypress (`npx cypress open`) a migration guide on the desktop app will be able to automatically migrate and scaffold all your current tests and config files so that they are compatible with thenew cypress version.

If you have not tried upgrading to cypress 10, may i ask what are the limiting factors that have prevented you from upgrading to Cypress 10?

It would also be more helpful if you could provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide. Having access to your `webpack config file` as well as your `cypress config` file would also be super helpful

**Comment by amehta265** [comment]
Unfortunately we have to close this issue due to inactivity and a lack of a reproducible example. 
Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
