### ISSUE TITLE
When opening project in Cypress (manual dl) on OS Sierra, error writing to file due to translocation

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#245]
If Cypress is manually downloaded on OS Sierra, translocation error occurs on writing to files on `open:project`. 

**For Reference:** 
- http://lapcatsoftware.com/articles/app-translocation.html
- http://weblog.rogueamoeba.com/2016/06/29/sierra-and-gatekeeper-path-randomization/

**Example Screenshot**
![screen-shot-2016-09-26-at-10 59 39-am EROFS: read-only file system, open ](https://cloud.githubusercontent.com/assets/1271364/18841853/1dd03df0-83e1-11e6-85ed-edb5db84f5e1.png)

**Comment by brian-mann** [comment]
**Current Workaround**

You need to install Cypress from the CLI and it will work because we invoke the binary directly.

```bash
npm install cypress-cli
cypress install
```

**Thoughts**
- we may need to switch to packaging OSX in a `.dmg` but that is a lot of work
- we could look into not writing files relatively to where Cypress is installed (but this may still cause updating from within Cypress not to work)
- we may need to account for being translocated and provide an error modal to the user indicating the steps to take to resolve this

**Comment by brian-mann** [comment]
Fixed in [`0.19.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0192-04162017).
