### ISSUE TITLE
setupNodeEvents does not trigger for components in cypress.config.js

### ISSUE THREAD

**Issue by MohanVallivedu** [cypress-io/cypress#24513]
### Current behavior

Hello team,
It seems that the setupNodeEvents, especially on('file:preprocessor') event is not getting triggered for component testing. It is working for e2e tests (when I run a test, I can see the event is triggered and I can print the filePath) but not for the component tests

My cypress.config.js:
```
const browserify = require('@cypress/browserify-preprocessor');
const preprocessor = browserify(browserify.defaultOptions);

module.exports = defineConfig({
  e2e: {
        devServer: {
            bundler: 'webpack',
            webpackConfig,
        },
        setupNodeEvents(on, config) {
            on('file:preprocessor', (file) => {
                console.log('e2e event ', file);   //  I can get this output when I run e2e tests
                const report = eslint.lintFiles([file.filePath]);

                // Run browserify preprocessor
                return preprocessor(file);
            });
            return config;
        },
        baseUrl: 'http://localhost:3014',
       specPattern: 'cypress/e2e/*.cy.js',
  },
  component: {
          devServer: {
              bundler: 'webpack',
              webpackConfig,
          },
          setupNodeEvents(on, config) {
              on('file:preprocessor', (file) => {
                  console.log('Component event ', file);    // Cant get this output in console
                  const report = eslint.lintFiles([file.filePath]);

                  // Run browserify preprocessor
                  return preprocessor(file);
              });
             return config;
          },
         specPattern: 'cypress/tests/**/*.cy.js',
   }
})
```

I expect to see the file object in my console, which is not happening for component tests. My end goal is to run eslint on the file and run preprocessor on it. 
I have updated my cypress version from 6.9 to 10.11 and did all the changes. I was trying to replicate the same behavior we used in 6.9 version (running eslint and returning preprocessor call). Am I missing something?

### Test code to reproduce

Code example provided above

### Cypress Version

10.11.0

### Node version

v14.17.3

### Operating System

Windows 10 Pro OS build: 19044.2130

**Comment by lmiller1990** [comment]
Component Testing serves all the files via your dev server (Vite/webpack). I don't think they run through the file:preprocessor lifecycle hook.

In your example you do:

```js
const report = eslint.lintFiles([file.filePath]);
```

But you don't actually do anything with `report`. In your real code base, what happens next? Do you write that to a file somewhere? Or do you want the linting to show up in the runner when you tests executes?

I am not sure if this is documented anywhere, but you can probably hook into the dev-server events in the same fashion, see here for an example: https://github.com/cypress-io/cypress/blob/f2bce02f5dcab7a73a2a1b8e102518d706a29c25/packages/server/lib/plugins/dev-server.js#L11-L17. Depending on the event, you can grab all the spec files, or just the one that changed.

**Comment by MohanVallivedu** [comment]
Oh, we do some reporting internally, calling a method something like this with cypress version 6.9.1
```
on('file:preprocessor', (file) => {
     const report = eslint.lintFiles([file.filePath]);

     // Send report to logging method
     logging(file.filePath, report);
     return preprocessor(file);
});
```
I've tried dev-server:spec:changed as well and cypress threw error as it's not supported
It seems all other events in cypress documentation [link](https://docs.cypress.io/api/plugins/writing-a-plugin#List-of-events) only supports for e2e? Is there something I could replicate similar to our code from 6.9.1?

**Comment by lmiller1990** [comment]
Ah I see, I didn't realize we guarded against certain events:

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/plugins/child/validate_event.js#L26-L37

We do expose `dev-server:start`. What about adding `dev-server:specs:changed`,` dev-server:compile:success` to that list?

**Comment by MohanVallivedu** [comment]
I'm wondering if this event before:spec would be useful for my scenario. I would expect a file object to return every time I run a spec file (ex: flexbox.cy.js), so that I can run eslint on it (as shown in previous comment)?

**Comment by lmiller1990** [comment]
Good idea. The argument you get in the callback is a spec with lots of useful information:

```js
{
  id: 'U3BlYzovaG9tZS9sYWNobGFuL2NvZGUvd29yay9jeXByZXNzL3BhY2thZ2VzL2xhdW5jaHBhZC9zcmMvY29tcG9uZW50cy9jb2RlL0ZpbGVSb3cuY3kudHN4',
  name: 'FileRow.cy.tsx',
  specType: 'component',
  absolute: '/home/lachlan/code/work/cypress/packages/launchpad/src/components/code/FileRow.cy.tsx',
  baseName: 'FileRow.cy.tsx',
  fileName: 'FileRow',
  specFileExtension: '.cy.tsx',
  fileExtension: '.tsx',
  relative: 'src/components/code/FileRow.cy.tsx'
}
```

On caveat is the `before:run` event is still experimental. You can read more [here](https://docs.cypress.io/guides/references/experiments#Configuration). I enabled it with `experimentalInteractiveRunEvents: true`. It works for both CT and E2E testing types.

We might want to change the issue title? `setupNodeEvents` does work in component testing, but `file:preprocessor` does not. 

Does this solve your issue? Can you use the experimental flag for your purpose? If so, we should definitely capture this feedback and use case -- it will help move the feature from experimental to part of the stable API.

**Comment by MohanVallivedu** [comment]
Oh, I see. When I add the experimentalInteractiveRunEvents option to the component, before:spec event works. But it seems I cannot use before:spec as well, because browserify preprocessor expects a file object parameter something like this (Printed from e2e file:preprocessor event)
```
EventEmitter {
  _events: [Object: null prototype] {
    rerun: [Function (anonymous)],
    close: [Function (anonymous)]
  },
  _eventsCount: 2,
  _maxListeners: undefined,
  filePath: '/root/project/cypress/e2e/application.spec.js',
  outputPath: '../bundles/cypress/e2e/application.spec.js',
  shouldWatch: true,
  [Symbol(kCapture)]: false
}
```

And yes sure, we can update the title. I think it would be beneficial to have file:preprocessor event for components as well

**Comment by lmiller1990** [comment]
It looks like the properties from `file:preprocessor` and `before:spec` are pretty similar. Are you looking for something specific, like a particular property that isn't available? Do you need an `EventEmitter`, or just the `outputPath` or `filePath`? In your example you do `const report = eslint.lintFiles([file.filePath]);` - so could you perhaps do:

```js
setupNodeEvents (on, config) {
  on("before:spec", spec => {
    eslint.lintFiles([spec.absolute])
  })
}
```


The main difference with the End to End and Component Testing is that in End to End, `file:preprocessor` actually writes a file to disc (which is then served via HTTP request). Component Testing does **not** - it's all in memory, and we serve it via a dev-server. That's why there's not 1:1 `file:prepreprocessor` for Component Testing.

I don't think we can have a `file:preprocessor` for Component Testing, since no file is written to disc (which is how the preprocessors in Cypress work, it takes X and applies Y transform, resulting in Z file written to disc), but I do think we can accomplish the something similar here. Please let me know if I'm misunderstanding something.

**Comment by MohanVallivedu** [comment]
Sorry, I should have been clear. eslint is working when I send spec.relative
But the preprocessor method expects the file object to have filePath, outputPath, shouldWatch which are not available for before:spec object.
@cypress/browserify-preprocessor version 3.0.2 expects we send the file object with those attributes, and that is the reason my e2e is working good, because file:preprocessor event returned object contains those attributes

```
const browserify = require('@cypress/browserify-preprocessor');
const preprocessor = browserify(browserify.defaultOptions);
on('before:spec', (spec) => {
    // Working
     const report = eslint.lintFiles(spec.relative);

     //  Run preprocessor on each file
     // Does NOT work, throws error "The "path" argument must be of type string. Received Undefined"
     return preprocessor(spec);
});
```
As you can see, https://docs.cypress.io/api/plugins/preprocessors-api#Examples, all preprocessor packages here are using file:preprocessor event and shows examples for only e2e

**Comment by lmiller1990** [comment]
Right, now I see your snippet, it makes more sense. So you want to do this workflow:

1. Hit save in IDE
2. Event runs
3. Get file
4. Apply processing
5. Send **processed file** to the browser?

So the goal is **lint your files** as part of the workflow? But the `preprocessor` won't actually write the linted source files to your project, but to a temp directory. Sorry if I'm completely missing something here - I'm still not able to grok the overall goal.

Now that I understand the goal better (I think), I don't think `before:spec` is going to work, even if you reformat the `spec` argument to have the expected properties. [`before:spec`](https://docs.cypress.io/api/plugins/before-spec-api#Log-the-relative-spec-path-to-stdout-before-the-spec-is-run) doesn't do anything with the returned value, by the looks of things. It's mainly useful for side effects (like linting the files, like you are doing).

Because of the dev-server architecture Component Testing uses, everything happens in memory using the respective bundler (webpack or Vite). If you want to hook into the bundler lifecycle, I think you'd need to use a plugin for the bundler (eg, [`eslint-plugin-vite`](https://www.npmjs.com/package/vite-plugin-eslint)). I suspect this is not practical or really want you want, though.

If you can clarify the exact goal here, I might be able to suggest an approach that will work.

**Comment by MohanVallivedu** [comment]
Sorry, I think I misunderstood our use case. We were doing the same process as you mentioned like from 2 years. Run file, run eslint on it, report if any errors, return preprocessor transpiled file. And at some point, we've updated our codebase(with webpack and plugins stuff), so we no longer need it now, and I misunderstood it.
Thank you for your responses :)

**Comment by lmiller1990** [comment]
Sounds like everything is okay -- any action needed here, or can we close?

Good discussion, I think this will be useful for other people learning about the Cypress events, etc.

**Comment by MohanVallivedu** [comment]
Yes, we can close it. it's a good discussion. Thank you!
