### ISSUE TITLE
Component Test only works once in UI mode if component routes to other page

### ISSUE THREAD

**Issue by manuelkroiss** [cypress-io/cypress#24577]
### Current behavior

We are testing an Angular component (`npx cypress open`) that contains a button where a click should lead the router to route to a specific link.

The test works fine asserting `cy.url().should('include', 'http://localhost:8080/__/#/settings');` running the first time. But trying to run the test again (without reloading the page) does not work and this test (and also all other tests) initialization run forever.

### Desired behavior

Test should work again on reload.

Note: Everything works fine running cypress with `npx cypress run --component`

### Test code to reproduce

````
// mount the component (using `RouterTestingModule`)

cy.get('<link-button>').click({ force: true });

cy.url().should('include', 'https://localhost:8080/__/#/settings');
````

### Cypress Version

10.11.0

### Node version

16.13.2

### Operating System

Windows 10 Enterprise 20H2

### Debug Logs

```shell
no logs available
```

**Comment by lmiller1990** [comment]
Hi!

The reason this happens is you navigate away from the dev-server URL. Unlike E2E where there is two iframes ("spec" frame for the test, "app" frame for the webpage), Component Testing only has one - which points to a dev server.

I haven't got a one size fits all solution, but in general, here's some of the things I've done around routing:

1) avoid testing routing in CT - it's kind of an End to End concern, since you need to navigate to different pages
2) use a memory router - I'm not sure if your framework supports this, I know React and Vue have memory/hash/history modes
3) rework your component and/or test to not need to navigate

If you can share you exact test/component, happy to make some recommendations.
