### ISSUE TITLE
no issue, you can close the ticket, sorry

### ISSUE THREAD

**Issue by mandriao84** [cypress-io/cypress#2461]
so issue, you can close the ticket, sorry

**Comment by jennifer-shehane** [comment]
Sure! For the future, you can always close an issue that you opened. It's a little hidden because it's the button at the bottom under making a comment - says "Close issue"

<img width="787" alt="screen shot 2018-09-12 at 10 21 15 am" src="https://user-images.githubusercontent.com/1271364/45431807-66174f80-b676-11e8-9d6a-1d9026c47fdb.png">
