### ISSUE TITLE
video compression taking longer in webkit

### ISSUE THREAD

**Issue by mschile** [cypress-io/cypress#24621]
After removing the `experimentalSessionAndOrigin` flag, the following test started to fail:

https://github.com/cypress-io/cypress/blob/d7e148f8cde4f74300bec3a3e2fa55ed3139d6fd/system-tests/test/video_compression_spec.js#L74

We need to investigate the cause and remove the TODO.

**Comment by flotwig** [comment]
Possibly relevant: We have to pass extra options to ffmpeg to remove duplicated frames because we get a ridiculously high framerate from WebKit: https://github.com/cypress-io/cypress/blob/e7b52b4c0abec46ff9434d25d8e685f15f5a3cf5/packages/server/lib/browsers/webkit-automation.ts#L151-L157

If this isn't working for some reason, maybe the ffmpeg option passing is broken. Or maybe we can pass an option to WebKit to decrease the framerate.
