### ISSUE TITLE
Inspect shows different URLs for each category of the dashboard box while website uses only one

### ISSUE THREAD

**Issue by arsasota** [cypress-io/cypress#24676]
### Current behavior

I apologize in advance for the bad explanation. 

I am working with cypress on a project. On the website there is a box with 4 clickable lines. When clicking each line, the page remains the same as the material is all located in one. It only scrolls up and down. However, when I inspect I see that each line has a specific URL, which is formed from the base URL of the page + some additional words specific to each step in the end. 

When clicking the links and checking the URL on top of the search bar, it does not change. And when I use cypress to analyse the functionality of each line and their URLs, cypress does not accept the different URLs for each line, but only accepts the base URL. 

### Desired behavior

I would like to be able to call the specific URLs using cypress in order to test them. I do not know how to do it

### Test code to reproduce

a

### Cypress Version

10.10.0

### Node version

v10.10.0

### Operating System

Windows 11 Pro

**Comment by nagash77** [comment]
Hi @arsasota , I am sorry to hear you are having issues getting started with Cypress.  Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [Cypress Discord](https://discord.gg/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io/), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
