### ISSUE TITLE
GET 404 error for loading images

### ISSUE THREAD

**Issue by reynolkb** [cypress-io/cypress#24686]
### Current behavior

Currently I'm getting a 404 error when trying to do component testing. I'm testing a basic React/TypeScript/Next.js app with a parent and child component.

The image shows up fine with e2e testing, just not component testing. For component testing, it only shows the alt text and not the actual image.

I tried using the `Image` component from next as well as the basic html `img` and both didn't work. I also tried using a `.png` vs `.svg` both which didn't work.

All I want is for the image to show up in the cypress component test.

![Screenshot 2022-11-14 at 10 30 34 PM](https://user-images.githubusercontent.com/57142369/201844719-ccc1bbcf-6712-4808-896f-265fa9569018.png)

### Desired behavior

I want the image to actually show instead of the alt text.

### Test code to reproduce

https://github.com/reynolkb/with-cypress-app

### Cypress Version

11.0.1

### Node version

16.15.0

### Operating System

13.0.1

### Debug Logs

`GET /_next/image?url=%2Fstatic%2Fgroup.png&w=32&q=75 404 18.102 ms - -`

**Comment by mike-plummer** [comment]
Hi @reynolkb , thanks for opening an issue and sorry it took us a while to get back to you. Unfortunately this is one of those things that Next.js does that is kinda-sorta outside the scope of the component itself which is why it doesn't work out of the box at the moment. Next helpfully wants to optimize images for you so it tries to use a special "_next/image" endpoint to get images optimized for the requested size, but this endpoint isn't available unless we spin up your full Next app (like an E2E test would) thus you get a 404 during component tests. At the moment there are a couple workarounds:

1. Serve images from the `public` directory and refer to it via string path using an `img` element.
This isn't ideal since the `Image` component has a lot of helpful props and behaviors on it above the basic HTML `img`

```
/public
  group.png
```
```
<img src="/group.png" ... />
```

2. Use the `unoptimized` prop on `Image`
This bypasses the Image optimization logic and just uses the source image. This is slightly better than `img` but still not great since one of the awesome features of Next is the image optimization, especially for mobile devices
```
<Image .... unoptimized />
```

3. Dynamically apply the `unoptimized` prop in Component Tests
With some JS trickery you can add some custom logic to dynamically "fix" usages of `Image` only when running in component tests. This allows your production code to be structured the way you want (with a few caveats, see below) but allow it to run in component tests.

`cypress/support/next-image-handler.js`
```
import * as ImageComponent from 'next/image'

// Grab unaltered Image component from Next
const WrappedImageComponent = ImageComponent.default

// Change the default export of `Image` so that our Component Tests use this version
// This allows us to change the behavior within component testing without altering
// our actual component logic
Object.defineProperty(ImageComponent, 'default', {
  configurable: true,
  // Anytime a component tries to render an `Image` we output it with the provided props
  // but also tack on the special `unoptimized` prop to bypass Next's image optimization
  value: props => <WrappedImageComponent {...props} unoptimized />,
});

export {}
```
`cypress/support/component.ts`
```
import './next-image-handler.js'
...
```

_Credit to the fine folks over at Storybook for the basis of the handler code above._
**Caveats**
Use of `unoptimized` to get images working in component tests relies on images being in `/public` and referred to as string src paths - Next also helpfully tries to serve non-public content via another endpoint that isn't available without spinning up the full app.

We are actively looking at how to improve our Next.js support out of the box and this is one of the things on our radar. There are a lot of custom behaviors that the full Next application provides that can manifest as "broken" component tests (this issue, statically imported images, `Head` mutation, etc) and we want to support as many as we can and provide alternate testing strategies for those that can't be handled in component tests.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by belwalshubham** [comment]
hey @mike-plummer @marktnoonan  @rockindahizzy  @JJ @reynolkb  I  get the  404 error when I run Cypress in github.

in package. json I have this code.
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt build && nuxt preview"
  },
  ```
and In YML file 
``` steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: install npm
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true
 ```
If instead of using npm run dev, I run npm run preview, it works fine and Cypress runs successfully, but it does not generate a code coverage report. A code coverage report can only be generated when I use npm run dev, but it gives a 404 error.

**Comment by nagash77** [comment]
Hi @belwalshubham , Can you please open a new issue specific to your problem with a reproducible example?  Be sure to include steps on how to recreate the behaviors you are seeing. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
