### ISSUE TITLE
Cypress chrome window irresponsive after the test case is failed

### ISSUE THREAD

**Issue by mohanbabu-zumen** [cypress-io/cypress#24701]
### Current behavior

Once the test case getting failed, the cypress chrome window is irresponsive.
Unable to do anything manually.

### Desired behavior

It should not be irresponsive. 

### Test code to reproduce

1. Run the test case in the cypress chrome window.
2. Once the test case is getting failed, do anything manually in the cypress chrome window.

Note: "It's occurred randomly"

### Cypress Version

10.10.0

### Node version

16.17.0

### Operating System

Windows 11

**Comment by nagash77** [comment]
Hello @mohanbabu-zumen .  I am sorry to hear you are having issues running Cypress.  Unfortunately with the information provided we do not have enough to investigate further.  If you can provide a reproducible example please do so and we can re-open this issue.  This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
