### ISSUE TITLE
Cypress browser crashed frequently

### ISSUE THREAD

**Issue by mohanbabu-zumen** [cypress-io/cypress#24702]
### Current behavior

When we run the long scripts, the cypress chrome window getting crashed and returns "Aw. Snap!"

Not only chrome, but All the browsers are also crashed when we run the long script

### Desired behavior

Cypress browser shouldn't be crashed in any case.

### Test code to reproduce

1. Run the long script in any cypress browser (Chrome, Firefox, Edge)
2. Browser will be crashed within 7 minutes

### Cypress Version

10.10.0

### Node version

16.17.0

### Operating System

Windows 11

**Comment by nagash77** [comment]
Hello @mohanbabu-zumen .  Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
