### ISSUE TITLE
Improve Test My Web App in Dark Mode

### ISSUE THREAD

**Issue by jingliancui** [cypress-io/cypress#24717]
### What would you like?

https://www.cypress.io/blog/2019/12/13/test-your-web-app-in-dark-mode/

As above blog post.
The cypress app's browser(chrome) show the page with dark/light mode correctly.
But test result throw exception. And I search this error 
`(uncaught exception)TypeError: window.matchMedia(...).addEventListener is not a function`
And know that this api is deprecated. refer https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener

![image](https://user-images.githubusercontent.com/16309962/202456458-2fedaa6d-8ef1-490f-93aa-9214edf482b5.png)

`launchOptions.preferences.darkTheme = false`  Doesn't work that I refer that [post](https://docs.cypress.io/api/plugins/browser-launch-api#Start-fullscreen).

So want to know any workaround about this?

### Why is this needed?

As the blog post you wrote.

**Comment by marktnoonan** [comment]
Hi @jingliancui could you share your actual test code that produces this error. The following works for me:

```js
    it('dark mode works', () => {
        cy.visit('https://gzecent.com/', {
            onBeforeLoad(win) {
                cy.stub(win, "matchMedia")
                  .withArgs("(prefers-color-scheme: dark)")
                  .returns({
                    matches: true,
                    addEventListener: () => {}
                  })
              },
        })
    })
 ```
 
You need to stub `addEventListener` because even though it is deprecated, the website is using it, so this line throws an error when the `matchMedia` response stub doesn't include it.
 
<img width="642" alt="Screen Shot 2022-11-18 at 10 31 58 AM" src="https://user-images.githubusercontent.com/8340719/202741631-4c55f47b-23d4-4667-b178-fd4d43232cf6.png">

**Comment by jingliancui** [comment]
Ah! You are right, and I think because I didn't know `return()` method of `stub()`. So I thought it occur because of the deprecated stuff.
Thanks so much. @marktnoonan
