### ISSUE TITLE
No projects, no branches, pr closed. But Cypress tests keep running. 

### ISSUE THREAD

**Issue by yeonjaee** [cypress-io/cypress#24728]
### Current behavior

I found the cancel run button because I wanted to cancel the run during the test by integrating cypress io and github action, but I couldn't find it.

So I just deleted the project and the branch.

But It says, "Tests are running."

How can I stop these?

![스크린샷, 2022-11-18 10-45-19](https://user-images.githubusercontent.com/96452659/202599269-2802b664-27a2-4547-b0d4-97c8028e0000.png)

### Test code to reproduce

no code sorry. using yml

### Cypress Version

10.11.0

### Node version

v14.16.0

### Operating System

ubuntu 20.04.5

**Comment by nagash77** [comment]
Hi @yeonjaee , Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://on.cypress.io/chat). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io/), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.  Or perhaps [GitHub](https://support.github.com/) would be able to assist.
