### ISSUE TITLE
Configure dashboard during cypress open

### ISSUE THREAD

**Issue by tommy-anderson** [cypress-io/cypress#24721]
### What would you like?

I'd like to be able to use the, `latest runs` and `average duration` columns in the Cypress 11 UI during `cypress open` with a dashboard different from Cypress Dashboard.

**Comment by nagash77** [comment]
Hi @tommy-anderson can you elaborate on your use case and why you are requesting this feature?

**Comment by tommy-anderson** [comment]
Hey there, so I've been using sorry-cypress to host my own on-premise dashboard and want to be able to view analytics from that dashboard instead of the Cypress Dashboard during `cypress open`.

More specifically I'm interested in the `latest runs` and `average duration` fields 

<img width="349" alt="Screenshot 2022-11-18 at 1 52 17 PM" src="https://user-images.githubusercontent.com/11273582/202699247-ab82af41-14ca-4671-80e3-46221e66cc53.png">

**Comment by brian-mann** [comment]
Hi @tommy-anderson - we're racking our brains trying to understand your question. To be clear, our Dashboard service already provides this data to the test runner. 

Based on what you're saying, it seems like a competitor to our service (not built by us) has not yet built the functionality to provide that data. If that's the case I'm not sure what we could do on our end since we're not responsible for serving data from our competitors.

**Comment by tommy-anderson** [comment]
hey Brian, closing this. 
My bad, I misunderstood what was going on.
