### ISSUE TITLE
Cannot access component variables

### ISSUE THREAD

**Issue by devjared1** [cypress-io/cypress#24735]
### Current behavior

Using Cypress 9.7.0, after adding the Vuetify plugin to our Vue3/Vite app, I am not able to access component variables or methods in a component test. 

### Desired behavior

Before adding the Vuetify plugin, I was able to access component variables and methods.

### Test code to reproduce
Here is my `cypress\index.js` file:
```
import { VApp } from 'vuetify/lib/components/VApp/index.mjs';
import { h } from 'vue';
import { mount } from '@cypress/vue';

Cypress.Commands.add("mount", (component, props, args) => {
  return mount(
    { render: () => h(VApp, {}, [h(component, props)]) },
    { ...args }
  );
});
```
TestNavbar.vue file:
```
<template>
  <v-app-bar density="compact" data-cy="navbar">
    <v-app-bar-nav-icon color="grey-lighten-2" data-cy="drawer-btn" />
    <v-app-bar-title class="pl-0">
      <span data-cy="title">Test Title</span>
    </v-app-bar-title>
  </v-app-bar>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const testFoo = ref('');
</script>

<style scoped lang="sass">
</style>
```
TestNavbar.cy.js file
```
import TestNavbar from './TestNavbar.vue';
import vuetify from '../plugins/vuetify';

describe('Navbar component tests', () => {
  it.only('Default view', () => {
    cy.mount(TestNavbar, {}, {
      global: {
        plugins: [vuetify]
      }
    })
      .then(() => {
        cy.get('[data-cy="navbar"]').should('be.visible');
        cy.get('[data-cy="drawer-btn"]').should('be.visible');
        cy.get('[data-cy="title"]').should('be.visible').then((span) => {
          expect(span.text()).to.eq('Test Title');
        });
        // before Vuetify plugin
        console.log(Cypress.vueWrapper.vm.testFoo);
        // after Vuetify plugin, get the nested TestNavbar component
        console.log(Cypress.vueWrapper.getComponent(TestNavbar).vm.testFoo);
      });
  });
});
```
Before we added the Vuetify plugin, I was able to access component variables after mounting with `Cypress.vueWrapper.vm.variableName`. Now, since we have to wrap components with the `VApp` component in tests, `Cypress.vueWrapper.vm` is tied to the `VApp` component. I thought that doing `Cypress.vueWrapper.getComponent(TestNavbar).vm.variableName` would give me access but it is `undefined`.<br><br>
Does anyone have any suggestions on anything else to try? Thanks in advance!

### Cypress Version

9.7.0

### Node version

16.18.0

### Operating System

Windows10

**Comment by marktnoonan** [comment]
Hi @devjared1, there are a couple of things to think about here. Since you are still on Cypress 9 and the alpha version of CT, this article I wrote might be helpful: https://css-tricks.com/testing-vue-components-with-cypress/#aa-adding-attributes-required-by-vuetify - it avoids the `v-app` wrapper by modifying the surrounding DOM in the mount command.

It's based on this reference repo: https://github.com/elevatebart/cy-ct-vuetify. This doesn't set plugins in the mount command, and it's possibly too simple an example compared to what you are doing.

There are some other directions around working with Vuetify here: https://docs.cypress.io/guides/component-testing/vue/examples#Replicating-the-expected-Component-Hierarchy - that uses a slightly different way of setting up the plugin.

There have been several small but potentially important changes in Cypress Component Testing between the alpha you are using, the beta that came with v10, and the now full release in v11. So I would be curious if it's possible to upgrade your project and see what the experience is in the latest.
