### ISSUE TITLE
Alias commands (`.as`) set within a `within` callback, are not accessible outside of it.  

### ISSUE THREAD

**Issue by dwjohnston** [cypress-io/cypress#24747]
### Current behavior

If trying to set an alias value within a `within` callback, but then accessing it outside of that callback, the value is shown as undefined. 

eg: 

Does not work 
```javascript 
        cy.get("#some-container").within(function() {
            cy.get("#some-text").invoke('text').as("foo")
        }); 


        cy.get("#enter-text").type(this.foo) // this.foo is undefined 
```

This is fine: 

```javascript 
        cy.get("#some-text").invoke('text').as("foo")
        cy.get("#enter-text").type(this.foo)
```

### Desired behavior

We need some mechanism for: 

- Doing selection behaviour within a `within()` block 
    -  This is often because you may have multiple rows, panels etc, with similar content, and you need to find the button within that one particular row. 
- Being able to access DOM elements directly, to retrieve a name, id etc. 
- Being able to use that name, id from outside of the container. 

### Test code to reproduce

```html
<div>
    <div id="some-container" style="border: 1px solid red;">
        <div id="some-text">foobar</div>
    </div>
    <label>enter text here: <input type="text" id="enter-text"></label>
</div>
```

Some example tests: 

```
describe("alian within test", () => {
    it("This does not work", function()  {

        cy.visit('http://localhost:3000');

        cy.findByRole("link", {
            name: "Input"
        }).click();


        cy.get("#some-container").within(function() {
            cy.get("#some-text").invoke('text').as("foo")
        }); 


        cy.get("#enter-text").type(this.foo)
    }); 

    it("This does", function()  {

        cy.visit('http://localhost:3000');

        cy.findByRole("link", {
            name: "Input"
        }).click();


        cy.get("#some-text").invoke('text').as("foo")
        cy.get("#enter-text").type(this.foo)
    }); 

    it("This won't work, as the input is not within the #some-container ", function()  {

        cy.visit('http://localhost:3000');

        cy.findByRole("link", {
            name: "Input"
        }).click();


        cy.get("#some-container").within(function() {
            cy.get("#some-text").invoke('text').as("foo"); 
            cy.get("#enter-text").type(this.foo)

        }); 


    }); 
})

```

See this commit: with example running https://github.com/dwjohnston/cypress-performance-issue/commit/59d2b0e573d4c00b0767d2299142a887d0dfeb9f

### Cypress Version

11.1.0

### Node version

14.20.1

### Operating System

macOS 12.5.1

**Comment by mike-plummer** [comment]
Hi @dwjohnston , thanks for opening an issue!  I think your described use case is supported, it may just need some syntax updates in your spec. If you use the `cy.get(@...)` API for accessing an existing alias you can work with the aliased value using `.then`, even for aliases created inside a `within` block. I adjusted the last block of your "Does not work" example above and it seems to work as expected:

```
cy.get('@foo').then((fooValue) => {
  // Instead of `this.foo`, retrieve using a `get` and utilize with `then`
  cy.get("#enter-text").type(fooValue)
})

```

Can you confirm this works for you?

**Comment by rafalnawrocki** [comment]
After upgrade from Cypress 10 to 12 I had similar issue with aliasing within within() block. Solution proposed by @mike-plummer was not working also, it was result of that:
![Screenshot 2022-12-08 at 09 51 10](https://user-images.githubusercontent.com/30791609/206404087-44bd3660-4b2e-4209-97bf-d78d8a88fdb5.jpg)

I workaround that with cy.wrap() inside the within() block, something like below:

```
        cy.get(user_table_row).first().within(() => {
            cy.get(user_row_name).invoke('text').then(($text) => {
                cy.wrap($text).as('user_name')
            })
        })
```

And then it is accessible later by `cy.get(@user_name)` call.

**Comment by BlueWinds** [comment]
This is actually expected behavior, and has nothing to do with `.within()` - it has to do with how Cypress executes commands. [This guide](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Commands-Are-Asynchronous) explains in detail, but basically this test:

```
cy.get("#some-container").within(function() {
  cy.get("#some-text").invoke('text').as("foo")
}); 
cy.get("#enter-text").type(this.foo)
```

is executed like so:
1. Add `cy.get("#some-container")` to the command queue.
2. Add `.within(callback)` to the command queue.
3. Add `cy.get("#enter-text")` to the command queue.
4. Add `.type(this.foo)` to the command queue. But `this.foo` is undefined - we haven't executed any commands yet! We haven't even entered the .within() block - only added it to the queue. So you're adding `.type(undefined)` to the command queue.
5. Now that the test function has returned, we begin executing commands.

Even a simpler case:
```
cy.wrap('string').as('str')
cy.log(this.str)
```

executes like so:
1. cy.wrap('string') is added to the command queue.
2. .as('str') is added to the command queue.
3. cy.log(this.str) -> cy.log(undefined) is added to the command queue.
4. The test function returns, and commands begin to execute.

If you want execution to wait until previous commands are finished - and your alias is put on `this` - you need to put your code in a `.then()` block.

```
cy.get("#some-container").within(function() {
  cy.get("#some-text").invoke('text').as("foo")
});

cy.then(() => {
  cy.get("#enter-text").type(this.foo);
})
```
passes as expected. I'm not sure how your "this does" example is working - it fails for me locally for the exact same reason.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
