### ISSUE TITLE
Gitlab CI Job does not end properly when `cypress run` contains a specific page that was visited

### ISSUE THREAD

**Issue by tomoyachen** [cypress-io/cypress#24788]
### Current behavior

When running the `cypress run` command on Gitlab CI, there is a probability that after a specific page is visited in a test case, the CI job does not end after running all the cases.

I tested different pages of my test subjects individually, and a specific page causes this problem, while all other pages end normally.

The page with the problem has a Service Worker, so I tried to block the Service worker but it still didn't work.

*Tested Cypress v10.11.0 v11.2.0 

### Test code to reproduce

I think it only has to do with the pages visited

cypress.config.js
```
{
  "baseUrl": "https://leetcode.cn"
}
```

health-check.cy.js 
```
describe('Health Check v2', () => {

  it('Health Check - Home Page', () => {
    cy.visit('/')
  })
})
```

Gitlab CI Job Screenshot
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/42526054/203492496-751673bf-f048-41f9-be13-1dca49861aa0.png">

### Cypress Version

10.11.0

### Node version

v16.18.0

### Operating System

Using Docker executor with image cypress/browsers:node16.18.0-chrome107-ff106-edge

**Comment by BlueWinds** [comment]
Hm. I'm not seeing a hang locally, so it must be something CI specific. I assume it works locally for you as well, and only fails in CI? Some things to try out:
1. Try with different browsers. Does it hang with chrome, electron and firefox? If all or only some of them, that helps narrow down the problem.
2. Try turning video recording off. Cypress can be very resource hungry, especially with video recording on. Turning it off could help figure out if it's a memory usage issue.

**Comment by me4502** [comment]
I believe we're experiencing the same problem as this post, since 10.11.0. I've done some investigation and I have a theory that it's caused by some sockets being kept around / hanging due to writes occurring after Cypress has started to shut down. I've attached some cleaned up logs, https://gist.github.com/me4502/e7436e484899ad835c879b64a8c49298. The specific test that triggered these logs ends by reloading the page, so my theory is that the service worker initialisation is causing writes to occur even beyond the point that the tab is closed, and Cypress isn't able to correctly handle this during shutdown.

There seems to be a lot of network traffic happening, despite the tab being closed. This might relate to service workers, as also mentioned in the opening post of the issue. Comparing with a successful run, it seems no further shutdown steps occurred after these post-tab-close writes. The application this occurred against only supports Chromium-based browsers, so I can't confirm whether it occurs in others.

Another thing I've noticed is that the `other` category in the process profiler that spams at the end until the CI task times out appears to have new PIDs every time, but this might be a background task and a red herring.

**Comment by BlueWinds** [comment]
Service workers do cause a variety of issues in Cypress for sure - it's not something well supported. None of these are exactly what either of you are describing, just providing to show the sorts of issues other people run into.

https://github.com/cypress-io/cypress/issues/16192
https://github.com/cypress-io/cypress/issues/16742

Good digging, @me4502.

**Comment by AtofStryker** [comment]
Out of curiosity, has anyone tried running headfully in CI and able to reproduce the issue?

**Comment by me4502** [comment]
I've been able to reproduce this issue running in headed mode on CI. We have one pipeline that runs headfully, while the rest run headless. Both are impacted, although it does feel like the headful one hit the issue _more_

**Comment by mschile** [comment]
Are you able to [disable service workers](https://glebbahmutov.com/blog/cypress-tips-and-tricks/#disable-serviceworker) to see if Cypress exits properly?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
