### ISSUE TITLE
Integrating Cypress with Bamboo without Docker Containers

### ISSUE THREAD

**Issue by sakhrNab** [cypress-io/cypress#24869]
### What would you like?

Hi, 

We are building a project currently and we're using Bamboo for CI. I know that we can integrate Cypress to Bamboo using the documentation in the Cypress webpage, however, only using Docker Containers. Since we're not allowed to use Dockers in THE current project, is there a way to make this integration possible without Docker Containers?

**Comment by nagash77** [comment]
Hi @sakhrNab , I'm sorry you are are having difficulties.  Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://discord.gg/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io/), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
