### ISSUE TITLE
Spying on a function doesn't work when using d3 and parcel

### ISSUE THREAD

**Issue by lkaratun** [cypress-io/cypress#2490]
### Current behavior:
I have a visualization project with d3, I'm also using parcel as the build step. It is impossible to test that a callback is triggered when a circle (part of a plot) is clicked. I.e., the test fails as if the callback was never called, even though it (or at least the version of it transformed by parcel) clearly was called.
The problem persists only when trying to test the app which uses both d3 and parcel.  
Thanks in advance for looking into it!

### Desired behavior:
The test passes (function call is registered by the spy)

### Steps to reproduce:

1. Clone the branch: https://github.com/lkaratun/cypress-test-tiny/tree/d3_parcel
2. `npm i` , etc.
3. `parcel index.html`
4. Open Cypress and run spec.js

### Versions
Windows 8.1, Chrome 69, Cypress 3.1.0

**Comment by chrisbreiding** [comment]
The issue is that you're stubbing `window.callback`, but [the `on("click")` code is calling a local reference to `callback`](https://github.com/lkaratun/cypress-test-tiny/blob/7c670ccea2d08ee314a71f676cb42a1b3c5ebf9a/app.js#L7). Stubbing only replaces the method on `window` and not the local function. For the stubbing to work, the `on("click")` code would need to call `window.callback`.

```javascript
function callback() {
  console.log("Hi from the callback!");
}
window.callback = callback;

window.onload = function init() {
  d3.selectAll("circle").on("click", () => window.callback()); // <= changed `callback()` to `window.callback()`
};
```

**Comment by lkaratun** [comment]
Thanks Chris! Your change does make the test pass.
I was wondering if there is a way to spy on a function without attaching it to the window object? (since attaching it like I did requires me to re-write all the function calls to use `window.`)

**Comment by chrisbreiding** [comment]
There isn't really. The `window` object is the only way to get access to the context in which your app is running. 

The core issue is that you're blending e2e testing with unit testing - triggering an action in an e2e way but making an assertion like it's a unit test. 

It will be less cumbersome if you can accomplish your test in one way or the other. With the e2e route, you'll still trigger the action the same way, but make an assertion based on the action changing something in the DOM or triggering a network request. Or you can go the unit test route, where you import the unit of code in question and potentially stub out a dependency linked to that callback, not needing to go through `window` because you should be able to stub the dependency directly.

I can't say for sure whether either of those will work since I only have the 'repro' code to go on, which of course isn't your actual app.

**Comment by lkaratun** [comment]
Hi @chrisbreiding,
You're probably right, I think I'll stick with E2E tests with Cypress and do unit tests with Jest.
Thanks again for your help! I think it's safe to close the issue.
