### ISSUE TITLE
Uncaught DOMException: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes.

### ISSUE THREAD

**Issue by Binayad** [cypress-io/cypress#24934]
Can someone help me regarding the redirect issue inside the iframe in cypress?

I have a form inside an iframe where I can insert text on the input field and in the next step, I click on the next button and it should respond to the next page but redirect is not performing on the cypress chrome browser.

I tried via cypress studio also but the button will be clicked and an alert will show but the redirect will not be performed.

The console will throw this message:
Uncaught DOMException: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes.

**Comment by nagash77** [comment]
Hi @Binayad !  Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://discord.gg/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io/), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
