### ISSUE TITLE
Problem with cy.visit on my website Cypress.io

### ISSUE THREAD

**Issue by raval1986** [cypress-io/cypress#2496]
Version 1.22.2

I cant visit my testing website.
If I try open another site is no problem.
I know that my problem for You should be very easy but please for help.

I try this:
```js
describe ('My first cypress test', () => {
    it ('Navigate to ea site', () => {
            cy.wait(500)
            cy.request('http://www.sport.pl' )
            cy.visit('http://www.sport.pl' )
            cy.wait(500)

            beforeEach(function () {
                cy.visit('http://www.sport.pl' )
            })
    })
})
```

I try only with visit but still have this community:
```
CypressError: cy.visit() failed trying to load:

http://www.sport.pl/

The content-type of the response we received from your web server was:

  > null

This was considered a failure because responses must have content-type: 'text/html'

However, you can likely use cy.request() instead of cy.visit().

cy.request() will automatically get and set cookies and enable you to parse responses.

```

I am a manual tester how are train to be automatic, but I dont have experience. Please friend for help me.

Thank You

**Comment by jennifer-shehane** [comment]
Cypress often takes the route of being more opinionated than other testing tools. Part of what we're trying to do is catch errors in your application that you may not find otherwise. We do not take a strategy of guessing the MIME type as some browsers do, so what you are experiencing is the intended behavior. There are many reasons for this that you can read here: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Configuring_server_MIME_types

We suggest you do not send a `null` MIME type from your server as, according to the HTTP specification, browsers have *no way of knowing* how you intend for them to display and process your content.

**Comment by raval1986** [comment]
If another user, can be try make this test and find something info to help, I will be happy.
I am working in company and in must try use
