### ISSUE TITLE
Allow setting baseUrl from cypress.env.json

### ISSUE THREAD

**Issue by raineroviir** [cypress-io/cypress#2499]
Right now Cypress only respects the baseUrl setting when it is defined in cypress.json but I think it should respect it also from cypress.env.json.

More info on baseUrl:
https://docs.cypress.io/guides/references/best-practices.html#Web-Servers

**Comment by brian-mann** [comment]
This has been asked before about a year ago and there was a long discussion about it.

https://github.com/cypress-io/cypress/issues/909

In short, it makes no sense because `cypress.env.json` is about environment variables, not configuration. It would just end up acting like `cypress2.json`, and all the overrides regarding `cypress.json` can instead be programmatically altered which is all around much better because you are likely just trying to do things like swap out multiple dev vs staging vs prod environments.

You can already do that in the most clean / effective manner using the [Configuration API](docs.cypress.io/api/plugins/configuration-api.html) - and then you can organize things in whatever way you'd like.

**Comment by raineroviir** [comment]
Got it, thanks!  The URL you posted must have gotten messed up, here is what I believe you were trying to link to [docs.cypress.io/api/plugins/configuration-api.html](url)
