### ISSUE TITLE
Enable dashboard login with email and password

### ISSUE THREAD

**Issue by dcastil** [cypress-io/cypress#2501]
### Current behavior:

I can login only with my GitHub account which is linked to my private email address.

![screen shot 2018-09-21 at 11 07 32](https://user-images.githubusercontent.com/31006608/45871827-aec5bb80-bd8e-11e8-85ad-4f6edf342078.png)

This leads to all of the organization members having their own GitHub account with their private email addresses linked to Cypress.

<img width="808" alt="screen shot 2018-09-21 at 11 03 14" src="https://user-images.githubusercontent.com/31006608/45872170-a02bd400-bd8f-11e8-9793-c07f7f850a02.png">

### Desired behavior:

We would like to be able to link the company email addresses to Cypress with user accounts independent from GitHub for several reasons:

- Private email accounts generally shouldn't be exposed to the company.
- Currently someone with access to a private email account of one of our employees could get access to the Cypress dashboard of our company, which is a security issue as we don't have any control over private email accounts.
- Employees who leave the company still have access to the Cypress dashboard until we revoke access manually.

### Versions

https://dashboard.cypress.io on 21.09.2018

**Comment by jennifer-shehane** [comment]
cc @cypress-io/services

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.

**Comment by jennifer-shehane** [comment]
Signup via email and password is now available in the Dashboard. You can create a new account using email at https://dashboard.cypress.io/signup
