### ISSUE TITLE
Drag and Drop using DataTransfer stopped working after upgrading to cypress 11

### ISSUE THREAD

**Issue by BioJibinJ** [cypress-io/cypress#25115]
### Current behavior

Hi, 
I did an upgrade from v9 to v11 using the [Cypress's Migration to 10.0 guide](https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-10-0).  For the most part the migration went fine,  but  I am noticing that several of my existing tests are failing after the migration; these tests use DataTransfer to create a drag-and-drop event.   

I can confirm that the test code (see in the code to reproduce section) works in v9.5.4, and were not modified during migration

Here is a screen recording of the test working in v9 
https://user-images.githubusercontent.com/88059252/207146680-6d947d09-34f6-4cf9-aa1b-ead2b52c2911.mp4

here is the screen recording of the test NOT working in v 11
https://user-images.githubusercontent.com/88059252/207146737-a2313c3a-d30f-4fe4-82f9-e7ff35640448.mp4

### Desired behavior

the drag and drop behaviour in the test occurs by creating a new DataTransfer which works in v9, but doesn't in v11+.  Looking for some guidance on how to get it working again, or an alternative solution.   

### Test code to reproduce

       // some code to get to a page with draggable file and folder
       
        cy.get('[data-testid="my-draggable-file"]').as('file');
        cy.get('[data-testid="my-folder"]').as('folder');

        const dataTransfer = new DataTransfer();

        // Start the dragging of the file
        const drag = cy.get('@file').trigger('dragstart', {
            dataTransfer,
            force: true,
        });

        // Move datatransfer onto to the folder
        cy.get('@folder')
            .trigger('dragenter', { dataTransfer, force: true })
            .trigger('dragover', { dataTransfer, force: true });

        // Drop file onto to the folder
        cy.get('@folder').then(($fElem) => {
            const boundingRect = $fElem[0].getBoundingClientRect();
            const vector = {
                x: boundingRect.x,
                y: boundingRect.y,
            };

            drag.trigger('drop', {
                dataTransfer,
                force: true,
                clientX: vector.x,
                clientY: vector.y,
            });
        });

### Cypress Version

11.0

### Node version

16.18.1

### Operating System

MacOS 12.5.1

### Other

I tried the [recommended community plugin ](https://github.com/4teamwork/cypress-drag-drop), but that also uses DataTransfer behind the scenes, so got stuck in the same way

Tests are running in Chrome v108

**Comment by mike-plummer** [comment]
Hi @BioJibinJ , thanks for reaching out and sorry to hear you're having issues. I've put together a [minimal reproduction case](https://github.com/mike-plummer/cypress-issue-25115-repro) demonstrating Drag and Drop in Cypress that works for me using Cypress 12.1.0 and Chrome 108. I tried to maintain as much of your example structure as possible so that it's easy for you to associate with your codebase, but feel free to ask any questions.

I believe the main issue in your example above is how you're attempting to store a yielded subject to a local variable then use it later. [This is a major code smell in Cypress.](https://docs.cypress.io/guides/core-concepts/variables-and-aliases#Return-Values)
```
const drag = cy.get('@file').trigger(
```
This is tempting to do but will often cause issues if you expect a yielded subject to be usable later in a spec after executing other Cypress commands - you're implicitly breaking out of Cypress' [asynchronous Command Queue](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Subject-Management). Typically you should use an alias or a `then` block to perform this sort of action. The fact that this test used to work was likely a fluke of execution order in earlier versions of Cypress rather than a true change in behavior/support.

**Comment by BioJibinJ** [comment]
Hey @mike-plummer, thank you walking me through what I was doing wrong, and taking the time to setup a code reproduction that I can work off.   Thanks to your guidance, drag and drop is working for me.
