### ISSUE TITLE
.contains() regression when first param is attribute with v12

### ISSUE THREAD

**Issue by Develliot** [cypress-io/cypress#25143]
### Current behavior

Similar to regression mentioned with  issue #25025
.contains() before v12 used to work with something like 

```
 cy.contains(
      '[role="dialog"]',
      "This is the body text of the Milestone."
    ).should("be.visible");
```

now it only works if you use an element you can't use attributes

```
 cy.contains(
      "div",
      "This is the body text of the Milestone."
    ).should("be.visible");
 ```

    

### Desired behavior

contains can find an element with attribute in first param

```
 cy.contains(
      '[role="dialog"]',
      "This is the body text of the Milestone."
    ).should("be.visible");
```

### Test code to reproduce

```
 cy.contains(
      '[role="dialog"]',
      "This is the body text of the Milestone."
    ).should("be.visible");
```
```
<div role="dialog">
  <span>
    This is the body text of the Milestone.
  </span>
</div>
```

### Cypress Version

12

### Node version

14

### Operating System

macOS

**Comment by BlueWinds** [comment]
Also, it's worth trying out Cypress 12.2.0 - we have had a couple of regressions with .contains fixed in the last couple of patch releases. 12.0.1 definitely had some issues. I'm not able to reproduce in 12.2.0. My test:

```
it.only('attribute', () => {
  cy.visit('http://example.cypress.io')
  // One subject
  cy.contains('[role="button"]', 'Commands').should('exist')
  
  // Many subjects, filtered by text
  cy.contains('[id]', 'Utilities').should('exist')
})
```

Can you provide an example where you're seeing the failure, using a public site? It seems like there may be something else going on in your case - or it's a regression we've already fixed in one of the recent patches.

**Comment by Develliot** [comment]
this look like this is working now with 12.2.0. Thank you :D
