### ISSUE TITLE
Avoid creating cookie prepended with dot ('.')

### ISSUE THREAD

**Issue by olivierboudet** [cypress-io/cypress#25174]
### Current behavior

First, i have to tell that I am testing a company internal SSO implementation (based on Keycloak). I saw this comment (https://github.com/cypress-io/cypress/issues/1342#issuecomment-366747803) on another issue which tells to test SSO with `cy.request` to simulate the authentication flow. In our case, we precisely want to test the flow, involving usage of multiple cookies with different domains, all set by Keycloak, not by `cy.setCookie()`.

Current behavior: 

When user is authenticated, Keycloak sets some cookies but cypress duplicates them with domain prefixed by a dot.
In the cypress console, we can see cookies set by cypress: 
```
[
   
    {
        "name": "KEYCLOAK_IDENTITY",
        "value": "",
        "path": "/auth/realms/myrealm/",
        "domain": ".keycloak.local",
        "secure": false,
        "httpOnly": true,
        "sameSite": "lax"
    },
]
```

Keycloak set this one in the server response: 

```
 {
        "name": "KEYCLOAK_IDENTITY",
        "value": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxNzA2N2ZhNS03NjQ2LTRmNjUtOTBkZi1jYWE5NjJmZThjODcifQ.eyJleHAiOjE3MzE1NzU5NDQsImlhdCI6MTY3MTA5NTk0NCwianRpIjoiYmYyNGRhMDItZmU4MS00OWQ3LTk1MzgtMjU0NDk5NDQ5ZmFi......",
        "path": "/auth/realms/myrealm/",
        "domain": "keycloak.local",
        "secure": true,
        "httpOnly": true,
        "hostOnly": true,
        "sameSite": "no_restriction"
    },
```

### Desired behavior

Cypress should allow to disable the automatic creation of new cookies prefixed by a dot.
At least, the value should not be empty.

### Test code to reproduce

Too difficult to provide here, it needs a full setup of Keycloak with multiple applications to test SSO.

This issue is already detailed in other issues : 
- https://github.com/cypress-io/cypress/issues/1896
- https://github.com/cypress-io/cypress/issues/1342
- https://github.com/cypress-io/cypress/issues/16856

We have found a workaround which is to manually remove all cookies automatically set by Cypress, which is a very dirty hack: 
```
When("user register", () => {
  cy.clickJsConsoleLogin();
  cy.registerRandomUser();
  cy.activateEmail();
  cy.clearCookie('KEYCLOAK_IDENTITY', {domain: Cypress.env('keycloakUrl').replace('https://', '.')})
});
```

### Cypress Version

12.1.0

### Node version

14.18.0

### Operating System

Ubuntu 20.04

**Comment by verheyenkoen** [comment]
Similar issue with a go-based-backend. The cypress intervention (likely by using `document.cookie = '...'`) causes a second cookie with dot-prefix to be present which is also sent back-and-forth to the server and the server cannot deal with it, causing behavior you don't get without Cypress.

**Comment by AtofStryker** [comment]
Hi @olivierboudet . Thank you for opening an issue. Would you or @verheyenkoen be able to help provide me with a repro? I have an old reproduction repository I used for #22282 but that is only using `cy.origin()`. Would you be able to do something similar to this [repro](https://github.com/AtofStryker/cypress-issue-22282) but taylor it to `cy.request()`?

**Comment by AtofStryker** [comment]
I have been able to reproduce this. Is this what you are seeing?

![](https://user-images.githubusercontent.com/3980464/207923292-20616d24-57ff-47d7-9a14-415ec69dacfe.png)

**Comment by verheyenkoen** [comment]
@AtofStryker Yes, the cookies are duplicated with one of the domains being dot-prefixed. Not sure but could have to do with the `httpOnly` attribute being true for these cookies. Anyway, they are sent back to the sever with roundtrip and that is in some use cases causing problems.

This means you don't need a reproduction repo anymore?

**Comment by olivierboudet** [comment]
In my case, I observe a similar thing but the value of new cookies are empty : 

![image](https://user-images.githubusercontent.com/857205/207954322-f5c1b9aa-ec06-469a-a983-b37f9eb9c167.png)

I think it would not be an issue if the value was not empty.

**Comment by AtofStryker** [comment]
@verheyenkoen If the screenshot is the identical issue I don't think we need an additional reproduction, but can use the #22282 reproduction with Cypress 12.

@olivierboudet however it sounds like your issue might be slightly different. A reproduction would likely be useful here, but if not We can likely go off the salesforce reproduction I have

**Comment by Bertg** [comment]
I've seen similar issues on our solution. This is a Rack (ruby) based application. 

So far we have only observed this in tests which use multiple domains. We actually have a test failure there, where a cookie does not get stored, even though present in the cookie headers. (We have had no time to file a decent bug report on this yet.)

I think both issues may be related to the changes introduced in Cypress 12. If I understand correctly quite some work was done to make cross-domain tests work better.

**Comment by olivierboudet** [comment]
> I think both issues may be related to the changes introduced in Cypress 12. If I understand correctly quite some work was done to make cross-domain tests work better.

Yes, we saw the issue just after upgraded to cypress 12 (from cypress 10)

**Comment by Bertg** [comment]
May also be related to #25205

**Comment by verheyenkoen** [comment]
@AtofStryker Looks like the same issue indeed.

In our case it were new tests so can't say if this "bug" is new to Cypress 12 but our test case is also touching multiple subdomains.

**Comment by AtofStryker** [comment]
We did significant cookie work for Cypress 12, including introducing new cookie commands and behaviors. My guess is this is an unintended side effect of those changes. Hopefully we can investigate soon!

**Comment by wulfovitch** [comment]
We have the same problem since updating to Cypress 12. 
Cookies are created twice, one of them with a prefixed dot (".").
We are currently using the workaround mentioned above when interaction with cookies is needed:

`cy.clearCookie('NAME_OF_THE_CORRESPONDING_COOKIE', { domain: "." + baseUrl });`

I hope this bug will be resolved soon. This workaround is far from ideal.

**Comment by szymon-niedrygas** [comment]
The same behavior for us. 
We tried to use `cy.clearCookies({domain: .ourDomain.com})` but it doesn't work. 
It's a huge discomfort for us so we're looking forward to a resolution.

**Comment by wulfovitch** [comment]
Clearing all cookies does not work for us either. You need to specify which cookie to delete and do at the same step as your app under test will delete the corresponding cookie without the dot ".".

**Comment by valscion** [comment]
I've written a reproduction case here: https://github.com/valscion/cypress-cookie-issue-reproduction

The branch with Cypress v11.2.0 is passing:

* https://github.com/valscion/cypress-cookie-issue-reproduction/pull/1

while the `main` branch with Cypress v12.3.0 is erroring out because the spec asserts that only one cookie is set but there are two.

In that reproduction repository, we can see that we have two cookies being set with Cypress v12 where as v11.2 didn't set them. What's strange about the v12 behavior is that I needed to add a small timeout before reading `document.cookie` to see that there are more than one cookie being set. On page load there was only one cookie present but I wasn't able to figure out if that cookie was the one with the dot prefix or without it.

## Cypress v12.3.0

<img width="1280" alt="cypress-12 3 0-cookies" src="https://user-images.githubusercontent.com/482561/210774218-84cab56f-b5d8-4fb5-9aeb-2f484e34b7ba.png">

## Cypress v11.2.0

<img width="1280" alt="cypress-11 2 0-no-double-cookie" src="https://user-images.githubusercontent.com/482561/210774427-9e5bcbe8-7d35-47f6-afb1-bda131cff397.png">

## Manual steps

<img width="1228" alt="manual-steps" src="https://user-images.githubusercontent.com/482561/210774468-f364a342-c003-47b2-8cce-8a46f2b91eff.png">

**Comment by Bertg** [comment]
@valscion Great effort, well done!

**Comment by valscion** [comment]
Regarding this section from the comment by @verheyenkoen in https://github.com/cypress-io/cypress/issues/25174#issuecomment-1353592877:

> Not sure but could have to do with the `httpOnly` attribute being true for these cookies.

I was able to get the same broken behavior both with `httpOnly` and without it. The test I wrote just has to avoid using `httpOnly` as the assertions are done based on what `document.cookie` has on JS side.

<img width="1280" alt="cypress-cookie-issue-reproduction" src="https://user-images.githubusercontent.com/482561/210792480-42bdb109-9990-4143-b095-64f18153d6b5.png">

* https://github.com/valscion/cypress-cookie-issue-reproduction/pull/3

**Comment by valscion** [comment]
More on our context — we're upgrading from Cypress v11.2.0 to v12 and now we have a test where a message that should be shown using Ruby on Rails' [Flash messages functionality](https://www.rubyguides.com/2019/11/rails-flash-messages/) that in our case works with special cookies.

However, with v12, we spot that there exists two cookies in the Cypress test, where now the one with the dot prefix is being used and the flash message is not being rendered as the application would render when not ran with Cypress:

<img width="1312" alt="venuu" src="https://user-images.githubusercontent.com/482561/210795111-9a9dfb93-f9de-4425-929e-c4a56f6fe001.png">

This causes our test to fail because the UI isn't showing the "Reply sent!" message as we'd expect to happen.

<img width="410" alt="venuu" src="https://user-images.githubusercontent.com/482561/210795295-a8fbc342-dfb6-4fea-a35d-6068b06d0052.png">

Right now this is blocking us from upgrading to Cypress v12 as I can't think of a workaround for this situation.

**Comment by valscion** [comment]
Is there anything I could do to help with this issue? This is blocking us from upgrading to Cypress 12.x right now.

**Comment by AtofStryker** [comment]
Hi @valscion. We are planning to start looking at this issue next sprint (in around 2ish weeks). If you want to get started early though, you might be able to debug some of the cookie code. My guess is it may not be the [CDP Automation](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/cdp_automation.ts) code as if I remember correctly this also happens in Firefox. I wonder if parsing the cookies on server has a different domain and sets them twice. These are all guesses as I haven't had time to look into the code in depth, but they might be great places to start!

**Comment by valscion** [comment]
Cool, thanks for the pointers! Let's see if I can figure out any extra details ☺️

**Comment by leonid-sviderskii-mtl** [comment]
I'd like to add a couple of cents too:
The issue happens with the `csrf` token cookie so whenever cypress needs to reload the page / navigate to another page, the API requests do fail due to `csrf token mismatch` error. 

In my case, I have to delete both cookies before any move, as otherwise, I still have the mismatch issue.

**Comment by valscion** [comment]
> if I remember correctly this also happens in Firefox.

Yes I was able to verify with my reproduction repository that this also happens with Firefox:

* https://github.com/valscion/cypress-cookie-issue-reproduction/pull/4

I updated the Cypress v11.2.0 baseline test to also run with Firefox and that also passes with Firefox:

* https://github.com/valscion/cypress-cookie-issue-reproduction/pull/1

**Comment by valscion** [comment]
It looks like the issue is indeed somewhere in the CDP Automation code. These parts seem suspicious to me:

https://github.com/cypress-io/cypress/blob/c2e7b60f541e01bb1e7f54f8582c458f619f9690/packages/server/lib/browsers/cdp_automation.ts#L49-L58

Called in many places, one of them being here:

https://github.com/cypress-io/cypress/blob/c2e7b60f541e01bb1e7f54f8582c458f619f9690/packages/server/lib/browsers/cdp_automation.ts#L60-L69


---

I tried to follow the code path on how we'd end up in those places but I didn't get that far. I also didn't have time today to figure out how I could try changing some code inside Cypress CDP Automation parts and then check if they'd fix my issue.

I described my journey here as well as added logs of things that seems to be suspicious to me: https://gist.github.com/valscion/d4f0bf080598d42603f807fba87b8b3a

**Comment by pionl** [comment]
Hi, we have same issues with Laravel and `XSRF-TOKEN`. Deleting cookies did work for some test cases but still on some `visits` the session is restored and I cant delete it. Thank you :)

**Comment by AtofStryker** [comment]
OK so I had some time to actually dig into this today and figure out what is going on. From what I can see, this is what is causing these duplicate cookies to show up with a prepended dot in the domain. But first, its probably good to document this cookie workflow for what is/supposed to happen in Cypress 12:

* With the release of Cypress 12, Cypress stores certain cross-origin cookies in a server side cookie jar because the browser may not have permission to set these cookies due to Cypress running in an iframe. These cookies would otherwise be same origin, but in this case are not due to `window.top` and the Application under test being cross-origin. These cookies are added in the proxy layer of Cypress in the [response-middleware](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/util/cookies.ts#L240)
* When these [simulated cookies](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/response-middleware.ts#L387) are added, they are [sent down](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/response-middleware.ts#L479) to the client to what we call a "cross-origin spec bridge" to sync cookie values that should be there into `document.cookie` and other resources. It's important to note that with Cypress 12, `fullCrossOrigin` injection might be used on a cross-origin html request, even if you aren't leveraging `cy.origin()`.
* When these cookies [make it to the "spec-bridge"](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cross-origin/events/cookies.ts#L17
), cookies are patched and then synced through the [automation client](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cross-origin/events/cookies.ts#L36
) with the subsequent middleware being [released](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/response-middleware.ts#L475).
* These simulated cookies, assuming they aren't added to the browser previously, make it up to the [automation client](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/automation/automation.ts#L114) to be [preprocessed](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/automation/cookies.ts#L168) before being sent to the appropriate automation client.
* These cookies are then sent to the appropriate automation client (in this case CDP for chromium) to go through a [similar process](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/cdp_automation.ts#L291). If the cookie is not considered a host only cookie, the dot is prepended onto the domain name [here](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/cdp_automation.ts#L112) (which is the suspicion @valscion pointed out here). The return value from this process is ultimately setting cookies these cookies via [CDP](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/cdp_automation.ts#L293).

This is a pretty complex workflow that takes a bit to put together, but it's not entirely necessary to understanding the problem. So what is actually happening?

From what I can see,  some of the cookies we are setting in the server side cookie jar are actually cookies that requests have the ability to set in the browser, either through `SameSite=None`  attributes or top level redirects that allow `SameSite=Lax` cookie setting. These cookies are getting set in the server side cookie jar, **AND** the browser. When the duplicated cookies set in the jar make it through the automation client, the hostOnly prepended dot is applied, which is really just a side effect of this incorrect behavior. If you are able to run the cypress dev environment locally, if you comment out [this line](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/util/cookies.ts#L240) the duplicate cookies should dissappear. 

This explains why the regression appeared in v12, and is happening for those who do not even use `cy.origin()`.

I am still thinking of solutions, but one way we might be able to fix this is to be a bit smarter about what cookies we set in the serverside cookie jar, filtering out any values we know will actually be set by the browser to avoid any type of duplication or side effects. I don't think this solution is super involved and is something we can unit test fairly easily,

**Comment by valscion** [comment]
Wow thanks for the explanation @AtofStryker, this functionality is quite interesting indeed!

Let me know if you need help with verifying some fixes or change ideas and I can take them for a spin also in our actual application and not just the reproduction repository.



> If you are able to run the cypress dev environment locally, if you comment out [this line](https://github.com/cypress-io/cypress/blob/develop/packages/proxy/lib/http/util/cookies.ts#L240) the duplicate cookies should dissappear.

Would it be useful if I test this out myself?

**Comment by AtofStryker** [comment]
> Would it be useful if I test this out myself?

@valscion I would say so just to confirm the duplicate cookie issues resolve. Others can also feel free to try it!

**Comment by AtofStryker** [comment]
Seems to be related to #25205

**Comment by AtofStryker** [comment]
Anyone willing to try [this binary](https://github.com/cypress-io/cypress/commit/86a8cd83792a046146bb43d869f8812dd0fc800c) to see if it resolves the prepended dot issues?

**Comment by leonid-sviderskii-mtl** [comment]
@AtofStryker I'll try although I'm not 100% sure my issues is exactly as described but seems to be pretty similar

**Comment by leonid-sviderskii-mtl** [comment]
I tested the `darwin-x64` version on macOS with Chrome v110.

I removed the code block with the `csrf` cookie removal and I confirm that the test fails on `12.3` but passes on `12.6` and I see only one cookie set for the domain without `.` So for me, it's a success :tada:

**Comment by AtofStryker** [comment]
This should be making it in today or tomorrow with 12.6.1. Hang tight!

**Comment by valscion** [comment]
> Anyone willing to try [this binary](https://github.com/cypress-io/cypress/commit/86a8cd83792a046146bb43d869f8812dd0fc800c) to see if it resolves the prepended dot issues?

I also verified that this binary did fix my reproduction repository locally: https://github.com/valscion/cypress-cookie-issue-reproduction

**Comment by ankorstore-haddowg** [comment]
> This should be making it in today or tomorrow with 12.6.1. Hang tight!

Any update on this patch? Just upgraded from v10 only to be scuppered by this issue.

**Comment by AtofStryker** [comment]
@ankorstore-haddowg Our patch release was delayed with an unknown ETA. My best guess at the moment is we will be releasing this week, if not worse case a week from today.
