### ISSUE TITLE
Component testing for angular is not using the custom webpack configuration during the build

### ISSUE THREAD

**Issue by martin-mueller-solutions** [cypress-io/cypress#25175]
### Current behavior

Hi, I added the cypress component testing to an existing angular project (in NX workspace). in this project we use a custom webpack configuration to add a yaml-loader.

Unfortunately, the custom webpack configuration is not used, when the build for the component testing is started. This means that the loader is not working and I am getting a lot of error messages, because of the missing loader.

### Desired behavior

The component testing should use the builder which is configured within the angular.json, including the custom webpack configuration, if one exists.

### Test code to reproduce

I created a minimal setup to reproduce this issue here: https://github.com/magile-de/cypress-component-test-not-using-custom-webpack-config

Step 1: run the angular application with `ng serve`. It does not show any errors, since the yaml-loader is properly added. on localhost:4200 you can see the content of the yaml file.

Step 2: run the component test with `npx cypress open`. Component Testing -> Start.
Step 3: run the `app.cy.ts` to see an empty object where the yaml content should be. additionally check the error message in the console, that the yaml-loader is not added.

### Cypress Version

12.1.0

### Node version

v16.16.0

### Operating System

MacOS 13.1

### Debug Logs

```shell
ERROR in ./src/app/test.yaml 2:6
Module parse failed: Unexpected character ' ' (2:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
> ---  # yaml document beginning
| # comment syntax
|
```

**Comment by mike-plummer** [comment]
Hi @magile-de , thanks for opening up this feature request! Currently Angular component testing uses the base utilities out of `@angular-devkit/build-angular` to construct a Webpack config - since your config relies on using a custom builder it is unfortunately not being executed. I think supporting custom builders would be useful so I'll get this passed along to the team to look into.

At the moment you can work around this by appending your Webpack customizations via the Cypress config. There is an optional `webpackConfig` field under `component.devServer` which accepts an object or no-arg function that returns a partial Webpack config that will be merged on top of the auto-generated config. Unfortunately this would mean your existing `webpack.custom.js` file would need to adjust a bit since it relies on the base config being passed in and mutated, but it should be possible to restructure into a "standard" and "testing" config function without too much duplication.

_webpack.custom.js_
```
export const Customizations = {
  module: {
    rules: [{
      test: /\.yaml$/,
    use: [
      {
        loader: "yaml-loader"
      }]
    }]
  }
}
```

_cypress.config.js_
```
import { Customizations } from './webpack.custom'
...
component: {
    specPattern: "**/*.cy.ts",
    devServer: {
      bundler: 'webpack',
      framework: 'angular',
      webpackConfig: Customizations,
    }
}
```

Let me know if you have trouble getting this to work - I made the adjustments outlined above to your reproduction case and got the YAML to load as expected so hopefully this fixes the issue in your baseline.

**Comment by martin-mueller-solutions** [comment]
Hey @mike-plummer thank you so much for your response... that works. 

So I was just reading the documentation wrong. It expects an object to merge, not a path to a custom file, that works on the existing config, as the angular-builder does.

Thanks again for your help!

It would be nice to support custom webpack configurations at some point in the future. I will close this, since my issue is fixed 👍
