### ISSUE TITLE
Bootstrap modal and backdrop issue

### ISSUE THREAD

**Issue by lugosium** [cypress-io/cypress#25202]
### Current behavior

Having this bootstrap modal displayed, when clicking "Close", modal is hidden, but backdrop is always here (Working on Chrome or Safari).

Currently I do this to avoid the issue:

`cy.get('.modal-backdrop.fade.show').then((element) => element.remove());`

### Desired behavior

Backdrop should be auto removed as in my Chrome browser.

### Test code to reproduce

Modal:

```
<div class="modal fade" id="modal-id"
                data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
                aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5">Header</h1>
                  </div>
                  <div class="modal-body">Body</div>
                  <div class="modal-footer text-center">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">
                        Close
                    </button>
                  </div>
                </div>
              </div>
            </div>
```

In cypress:

`cy.get('#modal-id').contains('Close').click();`

### Cypress Version

12.1.0

### Node version

v16.18.1

### Operating System

macOS 13.0.1

**Comment by mike-plummer** [comment]
Hi @lugosium , thanks for reaching out. What you have described is not a bug in Cypress but rather an issue with how Bootstrap chooses to manage transitions. When the modal "opens" Bootstrap adds/removes classes and attributes in a way that allows Cypress to "see" it as interactive before Bootstrap has registered its own click handlers. Since Cypress is able to see and execute interactions very quickly it's able to produce behavior that would never be visible to a user (closing a modal just milliseconds after it opens) but is, in fact, a loophole in the code. This has been reported a few times before - [this issue](https://github.com/cypress-io/cypress/issues/3175) has a good description of the problem and links to a [really good blog post](https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/).

The simplest way to work around this is to add a [`cy.wait`](https://docs.cypress.io/api/commands/wait) call to force the test to delay some time after seeing the modal open before trying to click the close button.

```
cy.contains('Open Modal').click()
cy.wait(500)
cy.get('#modal-id').contains('button', 'Close').click()
```

This is a bit of an anti-pattern since fixed delays will probably make your test slower than it could be and can result in flake. The referenced blog post has a bit on using [`cypress-pipe`](https://github.com/NicholasBoll/cypress-pipe) to just try the `click` over and over again instead - this would be a bit better but some devs don't like that pattern.

A more reliable/performant way of handling this might be to add some logic to ensure Cypress "knows" when Bootstrap is actually ready for interactivity. In reviewing the [Bootstrap docs](https://getbootstrap.com/docs/5.2/components/modal/#events) there are a couple event listeners that Bootstrap provides that fire once all transitions are complete on show/hide - we can use these to add a data attribute and use that for querying so that Cypress will automatically wait for that attribute to be present rather than using the standard "visible" checks.

_index.html_
```
<script>
// Add a `data-cy="modal"` attribute when the modal is finished transitioning open
document.getElementById('modal-id').addEventListener('shown.bs.modal', (evt) => {
    evt.target.setAttribute('data-cy', 'modal')
})
// Remove the `data-cy` attribute when the modal is finished transitioning closed
document.getElementById('modal-id').addEventListener('hidden.bs.modal', (evt) => {
    evt.target.removeAttribute('data-cy')
})
</script>
```

_spec file_
```
// Query using the data attribute - Cypress won't "see" it until Bootstrap has told our event listener that it's done with setup
cy.get('[data-cy="modal"]').contains('button', 'Close').click()
```

**Comment by lugosium** [comment]
Hello @mike-plummer,

I took the second option and add an attribute when the modal is ready for interaction. 
It's working great.

Thank you a lot for the great explanation and the solution. 👍
