### ISSUE TITLE
EACCES: permission denied to Chrome Preferences

### ISSUE THREAD

**Issue by will-weiss** [cypress-io/cypress#25231]
### Current behavior

When trying to run component or end-to-end tests using either cypress version 11.2.0 or 12.1.0, I encounter an error 

`EACCES: permission denied, open '/Users/willweiss/Library/Application Support/Cypress/cy/production/browsers/chrome-stable/interactive/Default/Preferences'`

Running with `sudo` works

<img width="1799" alt="image" src="https://user-images.githubusercontent.com/6589960/208710734-81121502-b234-46a2-a06c-8fe6c25bd152.png">

### Desired behavior

Not require `sudo` to run locally.

### Test code to reproduce

.

### Cypress Version

12.1.0

### Node version

v16.17.0

### Operating System

macOS 13.0

**Comment by lmiller1990** [comment]
I updated to Ventura. I used iTerm to open Cypress 12. I didn't get an error, but I did get

<img width="394" alt="image" src="https://user-images.githubusercontent.com/19196536/209053406-8eb12b14-3723-48e1-b067-1f53b1961cfc.png">

Everything still seems function just fine, though.


I also turned **off** full disk access for Terminal.app to try and reproduce it, but it still worked fine:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/19196536/209053542-23098398-c448-496a-8b77-9a9695f267c8.png">

I still got a warning:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/19196536/209053851-0ebf13a8-891d-4f33-8392-a7c53cb26d37.png">


Can you poke around in your permissions @will-weiss? I think MacOS 13 changed something, I am not sure what, but I'm guessing it's related to permissions. Can definitely change something in Cypress if we need to, but it's not clear 1) what the issue is or 2) if we can do anything about it on our end.

**Comment by mschaefer-gresham** [comment]
@will-weiss did you figure this out? I had the same issue. I deleted the Cypress folder under Application Support and managed to get past the initial Cypress screen. Chrome opens and shows the specs, but then hangs when I try to run one. 

Curious if you figured anything out that might help.

**Comment by astone123** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
