### ISSUE TITLE
After upgrading from version "9.5.1" to "12.2.0" the logout doesn't work with the SSO 

### ISSUE THREAD

**Issue by sondoos** [cypress-io/cypress#25247]
### Current behavior

After upgrading from version "9.5.1" to "12.2.0" the logout doesn't work, I think it's an issue with the SSO as Cypress stores the user token 
it doesn't give an error but the logout not happening when 

### Test code to reproduce

Confidential 

### Cypress Version

12.2.0

### Node version

8.1.2

### Operating System

windos

**Comment by emilyrohrbough** [comment]
@sondoos Please provide more information about your test setup and the test code you are experiencing this issue on. I understand your code is confidential, but without high level details it we cannot investigate this issue at all. Ideally if you can provide a simple, reproducible example that you can share, that'd be the best.

**Comment by Bertg** [comment]
Possibly related to #25174, as session mgmt is often done through cookies.

**Comment by chrisbreiding** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment here with a reproducible example and we will re-open this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
