### ISSUE TITLE
Custom Command is not a function

### ISSUE THREAD

**Issue by yurakhomitsky** [cypress-io/cypress#25348]
### Current behavior

I was following along with the installation instructions from [cypress/schematic](https://www.npmjs.com/package/@cypress/schematic) for "ng new" project

Then I decided to add a custom command however cypress throws the error: "cy.login is not a function" 

- To add a custom command I wrote the following code in the `commands.ts` file
`Cypress.Commands.add("login", () => { cy.log('login...') })`

- Added it to the namespace
`declare namespace Cypress {
  interface Chainable<Subject = any> {
		login(): any;
  }
}`

- Uncommented this line `import './commands';` in the `e2e.ts` file
- Used `cy.login()` in the `spec.cy.ts` file 

<img width="557" alt="image" src="https://user-images.githubusercontent.com/54478076/210402514-640bb7a0-21e9-4bc1-8e9f-c799644ef8cc.png">

### Desired behavior

Cypress should not throw the error "cy.login is not a function" 

### Test code to reproduce

https://github.com/yurakhomitsky/cypress-angular-schematic-issue

### Cypress Version

12.2.0

### Node version

16.15.0

### Operating System

macOS 13.0.1

**Comment by astone123** [comment]
@yurakhomitsky thanks for the example project. I see in your Cypress configuration that you have `supportFile: false` for `e2e`

```js
  e2e: {
    baseUrl: 'http://localhost:4200',
    supportFile: false
  }
```
Setting this option to `false` means that `cypress/support/e2e.ts` will not be executed when you launch e2e testing. Because of this, `commands.ts` is never imported, and your custom commands are never registered.

If you remove `supportFile: false`, you should be able to call your custom commands successfully.

**Comment by astone123** [comment]
I'm going to route this to the tools team to see if we should remove `supportFile: false` from the Cypress configuration that we generate with `cypress-schematic` to avoid confusion.

**Comment by Amit-P** [comment]
I don't have "supportFile: false" in my e2e but still my custom commands are not working.

**Comment by mike-plummer** [comment]
Hi @Amit-P , sorry you're having trouble. This issue has been closed for some time. If you're experiencing an issue that you believe is a Cypress bug I would recommend you open a new issue and provide all the requested information including a reproducible example (ideally a `git` repository we can clone and run ourselves) and Debug Logs.

Since this sort of issue is usually a configuration or setup issue (rather than a bug in Cypress) you may want to reach out on [Discord](https://on.cypress.io/discord) for help.

**Comment by vecernik** [comment]
having supportFile correctly set, custom commands don't work in 12.17.4 anymore.

**Comment by nagash77** [comment]
@vecernik please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.

**Comment by yuritoledo** [comment]
@vecernik dang! Same here. Did you fix it?

**Comment by vecernik** [comment]
@yuritoledo Only downgrading back to 12.17.3 helped to get custom commands working.

**Comment by Gbuomprisco** [comment]
> 

The solution is described here: https://github.com/cypress-io/cypress/issues/27641

**Comment by vecernik** [comment]
"sideEffects": [ "libs/shared/src/e2e/*.ts" ]
in package.json fixed the issue. Btw it's just a plain import (not extra function), it works now even with v13.

**Comment by ptakpatryk** [comment]
Workaround above works in my case I had "sideEffects" set to `false` in the package.json. Removing the whole line helped as well.
