### ISSUE TITLE
Cypress cloud videos not working

### ISSUE THREAD

**Issue by SS-SamiAhonen** [cypress-io/cypress#25367]
### Current behavior

Hi, We are developing e2e test with cypress dashboard cloud. We noticed that with Electron 106 browser the result videos are not working at all with this browser. Initial loading screen goes thru, but after that SUT browser and application is not visible or some cases is visible, but not rolling. Instead with chrome and firefox browsers videos are working well. Does anyone have ideas to solve this problem with electron 106 browser. 

Screen captures are working instead well with this browser also.

### Test code to reproduce

-

### Cypress Version

11.0.1

### Node version

v18.11.0

### Operating System

Github ubuntu-latest

**Comment by astone123** [comment]
@SS-SamiAhonen I wasn't able to reproduce this on my own. Is there a reproduction of this issue that you could share with me? Thanks

**Comment by SS-SamiAhonen** [comment]
I have a only a one video. Tests go thru but video lacking some reason much. With another browsers this works well.

**Comment by astone123** [comment]
@SS-SamiAhonen are you able to share the video here, or share anything else about your setup? If you run the test locally with video does it record correctly? 

If you give us the run ID that the video is associated with, we might be able to have the Cloud support team take a look. Thanks

**Comment by ZachJW34** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
