### ISSUE TITLE
Data from cy.invoke() stored in alias is removed on page navigation

### ISSUE THREAD

**Issue by filiphric** [cypress-io/cypress#25388]
### Current behavior

When I take a text from page using `cy.invoke('text')` and save it to alias, it disappears on page navigation, see following code:
```js
cy.visit('/')

cy.get('[data-cy=board-item]')
    .invoke('text')
    .as('boardName')

// navigates to "/board/1" on same origin
 cy.get('[data-cy=board-item]')
    .click()
    
   cy.get('@boardName')
    .then((boardName) => {
      console.log(boardName) // undefined
    })
```

strangely enough, when I use `cy.go('back')` and then try to retrieve data from alias, it’s there. seems to be a regression, works in v11.0.0

### Test code to reproduce

https://github.com/filiphric/invoke-bug

### Cypress Version

12.3.0

### Node version

v16

### Operating System

macos

**Comment by emilyrohrbough** [comment]
@filiphric Assuming the text is undefined on `"/board/1"` it sounds like it's working correctly because the query chain (in this case, `cy.get('[data-cy=board-item]').invoke('text')`) will re-execute when the alias is referenced.

This issue was logged a few weeks ago https://github.com/cypress-io/cypress/issues/25173 and we are moving forward with allowing users to explicitly determine if an alias should be a static value or not. See https://github.com/cypress-io/cypress/pull/25251.

**Comment by filiphric** [comment]
oh, sorry for duplicate then. I was suspicious that something with v12 changed this behavior. I was looking at [this part of docs](https://docs.cypress.io/guides/core-concepts/variables-and-aliases#Sharing-Context), and thought that there may be some update if something changed, so I got confused. It might be a nice addition once the #25251 is done
