### ISSUE TITLE
Not signed binary files in package for Windows

### ISSUE THREAD

**Issue by gemiusz** [cypress-io/cypress#2543]
### Is this a Feature or Bug?
Security improvement.

### Current behavior:
Windows binary files aren't signed by your certificate - easier for malware to "be Cypress".
In some organisations only signed exe files can be allowed to use.

### Desired behavior:
Signed binary files in package for Windows.

### Steps to reproduce:
None :)

### Versions
Cypress 3.1.0
Windows 10

**Comment by Saibamen** [comment]
Any update?

**Comment by jennifer-shehane** [comment]
No work has been done on this issue

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by minijus** [comment]
@jennifer-shehane would it be possible to reopen this issue?

Our organisation is exactly such as described:

> In some organisations only signed exe files can be allowed to use.

Please let me know if there is any help needed with requirements gathering. The release process does not seem to be open sourced, so it will not be possible to contribute with actual change, I guess.

**Comment by jennifer-shehane** [comment]
@minijus We would be open to accepting PRs for this if it's not too heavy of a lift by our team to finish. I remember the signing of the Mac binary was not a simple task, it ended up taking months, but maybe it will be easier since we already set that up. We would need the process automated in a similar way.

**Comment by minijus** [comment]
Just did a quick verification of passing needed data to `electron-builder` as per [Code Signing](https://www.electron.build/code-signing) documentation.

It seems that setting `WIN_CSC_LINK` and `WIN_CSC_KEY_PASSWORD` is enough to produce signed binaries.
After running `yarn binary-build` in local workspace with env variables mentioned above:
![image](https://user-images.githubusercontent.com/3633549/118326410-9f7e7800-b50d-11eb-8ef3-f1dd5c2ec5be.png)

In order to continue Cypress should acquire Code Signing certificate, add it to CI system and 🥳.

**Comment by jennifer-shehane** [comment]
The error when attempting to run `cypress open` in this situation where orgs only allow signed exe to be used shows like below:

```
Cypress failed to start

...

Command failed with UNKNOWN
spawn UNKNOWN
```

![119539765-462c0980-bd95-11eb-906c-c980ad71175e](https://user-images.githubusercontent.com/1271364/119553002-c7b57480-bd60-11eb-9956-fcdca4a8c7ac.png)
