### ISSUE TITLE
Component test does not reset zustand store between tests

### ISSUE THREAD

**Issue by blessanm86** [cypress-io/cypress#25441]
### Current behavior

Currently tests that render components that use a zustand store do not reset the store when the test is finished.
Due to this, tests interfere with each other. 

Currently to get around the issue, I  created a dummy component and render that into the test. The dummy component resets the store on button click.

Here is an example of zustand + react component.

```
import { create } from 'zustand'

const useBearStore = create((set) => ({
  bears: 0,
  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
  removeAllBears: () => set({ bears: 0 }),
}))

function BearCounter() {
  const bears = useBearStore((state) => state.bears)
  return <h1>{bears} around here ...</h1>
}
```

### Desired behavior

Cypress should drop whatever is in memory so that tests can run in isolation.

### Test code to reproduce

https://github.com/blessanm86/cypress-zustand-bug

### Cypress Version

12.1.0

### Node version

16.16.0

### Operating System

Mac 12.6.2

**Comment by astone123** [comment]
@blessanm86 thanks for the repo. This is expected behavior as Cypress won't clear this kind of state in between tests. We do [clear some browser state](https://docs.cypress.io/guides/core-concepts/test-isolation#Test-Isolation-in-Component-Testing) between tests but not application state. You'll have to manage the store state yourself to run the tests in isolation.

One way that you can do this is by adding a `reset` function to your store to restore it to its initial state (this is recommended in the [Zustand documentation](https://github.com/pmndrs/zustand/blob/main/docs/guides/how-to-reset-state.md)), then export the store so that it can be imported into the test file:

```js
// App.js
const initialState = { bears: 0 }

export const useBearStore = create((set) => ({
    ...initialState,
    increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
    removeAllBears: () => set({ bears: 0 }),
    reset: () => set(initialState)
}))
```
then in the test, you can reset the store's state between each test by using a `beforeEach` hook:

```js
// App.cy.js
import { useBearStore } from './App';

describe('LoginForm', () => {
    beforeEach(() => {
        useBearStore.getState().reset()
    })
    ...
});
```

Alternatively, you could handle this by calling `reset` when the component is mounted with a `useEffect` hook:

```js
// App.js
useEffect(() => {
  useBearStore.getState().reset()
}, []);
```

This way when Cypress mounts the component in the second test, the store state is reset.

**Comment by Armadillidiid** [comment]
@astone123 This doesn't scale well when you have multiple slices. A better approach would be this:

```ts
import useStore from "@/store";

const initialStoreState = useStore.getState();

afterEach(() => {
  // Reset store state
  useStore.setState(initialStoreState, true);
});

describe("Test", () => {
  // tests
})
```
