### ISSUE TITLE
net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by manoharaataleait** [cypress-io/cypress#25451]
### Current behavior

When Try to run the script unable to load the script with getting "net::ERR_EMPTY_RESPONSE" post.
![image](https://user-images.githubusercontent.com/111444103/212299365-2bc81195-8f1e-428e-9fcd-cdbb746249e6.png)

### Test code to reproduce

Post call needs Response.

### Cypress Version

9.7.1

### Node version

1.3.0

### Operating System

Windows

**Comment by nagash77** [comment]
Hi @manhoraatalea , Im sorry to hear you are having issues running Cypress.  I see you are on an older version of Cypress.  Are you seeing this behavior on the latest version?

Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by manoharaataleait** [comment]
I'm not using latest version I'm using 9.7.0

**Comment by nagash77** [comment]
Hi @manhoraatalea , can you try reproducing in the latest version of Cypress?  This will help us narrow down potential causes of the problem.  We also will need you to provide a reproducible example for our engineers to be able to look into this any further.  I am closing this issue until a reproducible example can be provided.
