### ISSUE TITLE
Cypress always open the old login page of google accounts when using chrome headless

### ISSUE THREAD

**Issue by idanElitzur** [cypress-io/cypress#25536]
### Current behavior

Cypress always open the old login page of google accounts when using chrome headless and open the new one when using opened chrome by the GUI runner.

I can't mapped the old login page to handle this "a/b test" because i can reached him by the browser.
I'm sure this use case is to make the automation harder over there.
Also there is two-factory stage when trying to login by the GUI runner in the first time.
Can you please assist to deal with these use cases?
I can't login by Google in my tests and it's a really blocker for me.

This use case is not available for testing since Cypress v9 ~

### Test code to reproduce

```js
/// <reference types="./../../../testilize/node_modules/cypress" />

import * as loc from "./locators/google-login";
export const email = Cypress.env("gmail_user");
export const password = Cypress.env("gmail_password");
export let button = loc.submitButton;
export const args = { loc, email, password };

export function googleLogin(
  button: string,
  appEndpoint: string,
  landingLoc: string
) {
  cy.session(
    args,
    () => {
      cy.visit("/login");
      cy.get(button)
        .should("be.visible")
        .click()
        .then(() => {
          cy.intercept(Cypress.config("baseUrl") + "/**").as("redirect");
          cy.origin(
            "accounts.google.com",
            { args },
            ({ loc, email, password }) => {
              Cypress.on(
                "uncaught:exception",
                (err) =>
                  !err.message.includes("ResizeObserver loop limit exceeded")
              );
              cy.get(loc.username)
                .should("be.visible")
                .type(email)
                .and("contain.value", email);
              cy.get(loc.submitButton)
                .eq(3)
                .should("be.enabled")
                .click({ force: true });
              cy.get(loc.password)
                .should("be.visible", { timeout: 45000 })
                .type(password);
              cy.get(loc.submitButton)
                .eq(1)
                .should("be.enabled")
                .click({ force: true });
              cy.wait("@redirect", { timeout: 20000 });
            }
          );
        });
      cy.get(landingLoc).should("be.visible");
    },
    {
      validate() {
        cy.visit(appEndpoint);
      },
    }
  );
}

```

### Cypress Version

12.3.0

### Node version

14.18.1

### Operating System

MacOS 13.0.1 (22A400)

**Comment by nagash77** [comment]
Hi @idanElitzur , Unfortunately we cannot control wether google requires 2factor for an account or not.  Most auth providers that are not controlled by the application under test can potentially face such challenges.  Those auth providers often put measures in place to prevent automated logins to prevent misuse by bots.  I would suggest you reference our [documentation on the topic](https://docs.cypress.io/guides/references/best-practices#When-logging-in).

**Comment by idanElitzur** [comment]
I see,
Do you have any alternative working solution for login by google account?
It's a major part of my tested application and i know that other automation tools are manage to deal with this use case.

**Comment by AtofStryker** [comment]
@idanElitzur I know the exact problem you are describing for the headless issues. Are you able to run chrome headfully in run mode?  You could do something like `cypress run your_test_file.spec.js --headed --browser chrome`. 

For two factor, there isn't too much we can do to handle on our side, especially in CI, but if you are running locally, you might be able to leverage a OTP tool like [this](https://github.com/pipobscure/otp) or if you use a password manager like 1password you may be able to leverage their [connector](https://www.npmjs.com/package/@1password/connect) to fetch an OTP. We **don't** recommend this because it does violate the TOS for Google and other media providers and may result in your account being suspended, but if you are blocked completely from running your tests, this may be an option.

I believe you have mentioned this in the past, but you have tried [programmatic login](https://docs.cypress.io/guides/end-to-end-testing/google-authentication), correct?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
