### ISSUE TITLE
Issue in Overwrite Customized command

### ISSUE THREAD

**Issue by Amara292** [cypress-io/cypress#25535]
### Current behavior
```js
Cypress.Commands.overwrite('contains', (originalFn, subject, filter:any,text:any,options={}) => {
    
    //dertermine if filter argument was passed
    if(typeof text==='object'){

        options = text
        text = filter
        filter=undefined
    
    }
    options.matchCase=false
return originalFn(subject,filter,text,options)
})

```

### Desired behavior

Options also should accept  as Arguments  but getting 
below Error

//Iam Unable to take options Argumant
(parameter) options: Parameters<Cypress.ChainableMethods<any>[T]>[3]
Expected 2-3 arguments, but got 4.

### Test code to reproduce
```js
describe('Custom Commands', () => {
    it('handling Links', () => {
        cy.visit('https://demo.nopcommerce.com/');
        //cy.get(':nth-child(2) > .product-item > .details > .product-title > a').click()   
        //cy.get('h1').should('have.text','Apple MacBook Pro 13-inch')

       // Using Customcommand
       cy.clickLink('APPLE MACBOOK PROS 13-inch')
       cy.get('h1').should('have.text','Apple MacBook Pro 13-inch')
    })
})
```
### Cypress Version

 "12.2.0",

### Node version

16.16.0

### Operating System

windows

### Debug Logs

```shell
no
```

### Other

no

**Comment by ZachJW34** [comment]
I see you are overwriting `contains` but I do not see a `cy.contains` usage. Can you post a usage of the overwritten command, or better yet provide a simple reproduction? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by warrensplayer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by Amara292** [comment]
Hi,

 Thanks for the Update.I m Unable to take parameter for option Kindly check
it please .Its not about contains method.

Thanks and Regards,
Amaravani
