### ISSUE TITLE
What is the problem: Test seems to crash with "You seem to have gotten lost"?

### ISSUE THREAD

**Issue by mib122** [cypress-io/cypress#25578]
### Current behavior

I am using cypress for e2e testing. I have a nextJs App -> I start the test with loading the page and logging in. Then I have a loading spinner showing up until all the resources loaded. Right after that I get a short sight on the page, and then running into the error page "You seem to have gotten lost". Without any error or without any warning. 

### Desired behavior

Cypress should tell me why this is happening. I can't find out where the problem should be because there is no error message anywhere. Logging into the page in a normal browser works as expected without any error or crashes.

### Test code to reproduce
```js
    doLoginAsAdmin() {
        this.inputUsername.type(`${Cypress.env('username')}`, {force: true});
        this.inputPassword.type(`${Cypress.env('password')}`, {force: true});
        this.loginSubmit.click();
        //now the page does the login and loads all resources. The test is doing nothing else.
    }

    get inputUsername() {
        return cy.get('[data-cy="login-username"]');
    }

    get inputPassword() {
        return cy.get('[data-cy="login-password"]');
    }

    get loginSubmit() {
        return cy.get('[data-cy="login-submit"]');
    }
```
### Cypress Version

12.4.0.

### Node version

v16.8.0 and v18.12.0

### Operating System

macOS 12.4

**Comment by ZachJW34** [comment]
I'm assuming the "You seem to have gotten lost" is a 404 route within your NextJs application. There could be many things causing this redirect, and not necessarily a problem due to Cypress (could be application code or a misconfigured redirect).

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by abrilmaestre** [comment]
@mib122 Were you able to solve it? I've had the same problem for weeks but no one responded to my posts.

**Comment by warrensplayer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.
Please comment with a reproducible example and we can reopen. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by joydeep100** [comment]
We are also facing the same problem @warrensplayer @jennifer-shehane .Was able to repo using cypress 12.4 / 12.9. On Mac latest / windows 10. In run / open modes across almost all browsers.

I am attaching a debug logs with masked url's. please check this and let me know if this helps.

So basically what is happening is when we click on a link, we are running into this issue. While if we navigate to the same url it is fine. weird thing is there are a bunch of links on the UI and issue seems to pertain to only a particular link.

Pls let me know if you would like me to attach the element attributes / properties.

[debug.log](https://github.com/cypress-io/cypress/files/11119008/debug.log)

**Comment by nagash77** [comment]
Thank you @joydeep100 for providing those logs.  Can you also share your reproduction steps?

**Comment by joydeep100** [comment]
Hi @nagash77 ,  we have trying to click on the highlighted link (Service Admin) as per the below screen shot then we run into this issue.
note that, this happens only with this link. Other links (like Manage Groups or Users) work as expected.

![image](https://user-images.githubusercontent.com/45758076/230311540-96b51a1d-550c-4030-a731-3d9a321511ba.png)

here is the html of that element.

<a href="/provision/ui/serviceadmin/commPlans/commPlans.html" target="" class="x-tree-node-text  " data-awt="mainMenu-link-admin-serviceAdmin" data-qtip="Service Admin">Service Admin</a>

**html**
![image](https://user-images.githubusercontent.com/45758076/230312190-e3c12d4f-24a8-494a-8c40-474eb5a29457.png)

**properties**
![image](https://user-images.githubusercontent.com/45758076/230312495-5183fdf0-e877-4d42-98e9-b00046ff9f79.png)
![image](https://user-images.githubusercontent.com/45758076/230312694-943412a6-86e2-401a-ad7c-c6618817070e.png)

ps. if you are expecting if we can share a recipe to spin up the UI app, that wont be feasible for us.

**Comment by mib122** [comment]
[This](https://github.com/cypress-io/cypress/issues/16905#issuecomment-882113807) was the solution for me, because we were using ExtJs.

**Comment by jordanpowell88** [comment]
@mib122 I'm glad you found a solution. Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by joydeep100** [comment]
@mib122 

Yes we too are using ExtJs. What worked instead was adding the same piece of code in the spec file itself.

    Cypress.on('window:load', win => {
        if (win.Ext) 
            win.Ext.History.useTopWindow = false;
    });

**Comment by istvan-csaki-md** [comment]
Hello, 
I've solved the issue by editing the attribute of the element from target="_top" to '_parent' in cypress:
cy.get(selector)
      .invoke('attr', 'target', '_parent')
      .click();
