### ISSUE TITLE
Ability to add tag to run to display in 'Runs' list in Dashboard UI

### ISSUE THREAD

**Issue by ArieLevs** [cypress-io/cypress#2561]
### Current behavior:

Dashboard UI does not show environment

![screen shot 2018-10-04 at 9 15 42](https://user-images.githubusercontent.com/34907201/46456050-2f84ae80-c7b6-11e8-9d12-42fb585552af.png)

### Desired behavior:

Hi,
Is there an option to add environment to the dashboard UI?
So for example if we run sanity tests (or any e2e) for the same project on different environments we have no way to know where did the test ran.

for example screen shot above, test num 100 can run on production, text 101 can run on qa etc...
It would be great to see the env straight on dashboard without entering the test and figuring out where it ran.

### Versions

cypress: v3.1.0
os: CentOS 7.3.1611
browser: Electron 59.0.3071.115

**Comment by jennifer-shehane** [comment]
Hey @ArieLevs check out our new [Grouping feature](https://on.cypress.io/parallelization#Grouping-test-runs). We've found it helpful in our own tests to specify env the tests ran within, so `--group staging` and `--group dev`, etc. This will have all the tests displayed in the same run with labels associating each group. 

Let me know if this helps with what you're looking for.

**Comment by jennifer-shehane** [comment]
We haven't had this feature request before, so there hasn't been any previous discussion on this. 

The list of runs would need to display any/all groups within each run.

**Comment by LiranBri** [comment]
+1

**Comment by lirantal** [comment]
Hi @jennifer-shehane, this feature will be valuable for us as we normally run cypress tests in multiple environments (development CI, alpha, and production) and need to easily distinguish this from the birds-eye view instead of the actual test run.

**Comment by avnersorek** [comment]
Even just simple tagging/labeling of tests runs, that can be passed in to the CLI and displayed in the Dashboard UI, would be great.

**Comment by amrwahdan3** [comment]
i concur with adding tagging of test runs in the birds eye view (/runs). displaying the value here from the --group flag would be awesome.

the Message displays there but in our case it isnt very helpful b/c the Message seems to be the comments from whatever the last commit was to that branch (we are running through azure)

**Comment by bahmutov** [comment]
I think as step 1 that might be enough is to display the group name(s) in the run list. Right now we do not show `--group` name in the list of runs, one can kind of guess that there are 2 groups in the middle run in the image below, but you cannot be sure.

<img width="989" alt="Screen Shot 2019-08-07 at 3 52 30 PM" src="https://user-images.githubusercontent.com/2212006/62653520-bdc44680-b92b-11e9-965f-ef4e5b7ef91d.png">

Only by opening the run details and collapsing the individual specs one can see the group names

<img width="1006" alt="Screen Shot 2019-08-07 at 3 53 42 PM" src="https://user-images.githubusercontent.com/2212006/62653569-cf0d5300-b92b-11e9-8316-0d262d3d1061.png">

## Proposal:

If the run has 1 group, show the group name in the list of runs. If there are multiple groups, concatenate and show their name, but put a text limit.

Something like this (I have replaced time ago column with group name column)

<img width="989" alt="Screen Shot 2019-08-07 at 3 52 30 PM" src="https://user-images.githubusercontent.com/2212006/62653875-902bcd00-b92c-11e9-8651-59bdfcf32b3f.png">

This could be done quickly, since we already have this data in the database, plus the Test Runner has the `--group` flag feature.

**Comment by jennifer-shehane** [comment]
Our plan moving forward is to support 'tags' that can be passed into `cypress run` via a `--tags` flag.

We would then display those tags in the 'Runs' UI of the Dashboard, allowing filtering by tag. 

Some examples of how we think this may be used - also examples with `--group` flag, to distinguish how you may use groups and tags together.

```
cypress run --tags develop
cypress run --tags staging
cypress run --tags production
```

```
cypress run --tags nightly
cypress run --tags hourly
```

```
cypress run --group desktop --tags staging
cypress run --group mobile --tags staging
```

```
cypress run --group web-es --tags production
cypress run --group web-en --tags production
```

```
cypress run --group desktop-uk --tags develop, nightly
cypress run --group desktop-de --tags develop, nightly
```

**Very rough concept of Runs list**

<img width="1346" alt="Screen Shot 2019-09-09 at 1 19 20 PM copy" src="https://user-images.githubusercontent.com/1271364/64552797-03e34000-d306-11e9-93c3-7347badda945.png">


## Test Runner tasks:

- [ ] Capture `--tags` from CLI
- [ ] Capture `tags` from Module API

## Dashboard tasks:

- [ ] Display 'tag' per run
- [ ] Allow filtering by 'run'
- [ ] Display all tags used per project. Allow setting tag 'colors.

## Docs tasks:

- [ ] Document `--tags` flag.
- [ ] Document `tags' in Module API
- [ ] Document why you would want to use tags (where??)
- [ ] Document tags in the Dashboard 'runs'

**Comment by ZoroQualityAutomata** [comment]
> Document why you would want to use tags (where??) 

As for where to document this, perhaps alongside the docs on the `--group` and `--parallel` flags, because `--tags` is another way to organize and group tests together by type.
