### ISSUE TITLE
Tests being skipped in CI?

### ISSUE THREAD

**Issue by SimonasB88** [cypress-io/cypress#25621]
### Current behavior

Upgraded the Cypress to the 12.4.1 Github Actions https://github.com/marketplace/actions/cypress-io and the tests started to skip, but the outcome is green and successful. Launching on local machine MacOS M1 Ventura 13.1 `npx cypress run` works ok, tests do not skip.

Don't know, maybe anyone got something like that recently?

![image](https://user-images.githubusercontent.com/29095235/215465119-79f33969-4750-4369-a0ff-7976f35bf1e7.png)
![image](https://user-images.githubusercontent.com/29095235/215465293-47cef5ef-a9cf-4710-94bd-6c5053b9f3c3.png)

### Desired behavior

Cypress should not skip the tests.

### Test code to reproduce

https://github.com/mollie/PrestaShop1.7/actions/runs/4043288521/jobs/6952031023

### Cypress Version

12.4.1

### Node version

v16.16.0

### Operating System

Linux on Github Actions

**Comment by ZachJW34** [comment]
Looks like the issue comes from the code itself. I took a look at the job and the branch associated with it and I found:

```js
afterEach(function () {
    if (this.currentTest.state === "failed") {
      Cypress.runner.stop();
    }
  });
```

Your test did not pass the first time and attempts to retry:

```
PS1784 Module initial configuration setup
    (Attempt 1 of 2) 01 Connecting test API successsfully
```

Your afterEach then catches the first failure and causes Cypress to terminate. Not sure what the desired behavior should be with your tests but invoking `Cypress.runner.stop();` will cause the behavior you are seeing. 

To my knowledge, there is no way to abort Cypress and have it report a failure. You could tweak your code to have all subsequent tests fail:

```js
let failEarly = false;

beforeEach(() => {
  if (failEarly) throw new Error("Failing Early due to an API problem")
});

afterEach(function () {
  if (this.currentTest.state === "failed") failEarly = true
});
```

**Comment by SimonasB88** [comment]
@ZachJW34 hey man, yea, I left some issues here, but thank you very much for your help! Used the tweak you provided, analyzed the tweak, and it works good now in CI. So glad about this supportive workflow 👍

**Comment by ZachJW34** [comment]
Glad I could help out 😄
