### ISSUE TITLE
Monaco Issues with Cypress

### ISSUE THREAD

**Issue by cx-ruben-sequeira** [cypress-io/cypress#25685]
### Current behavior

these command sometimes works , sometimes not with monaco editor.
its is very random... 
```js
  cy.get('.monaco-editor textarea:last').siblings();
    cy.wait(2000);
    cy.get('.monaco-editor textarea:last').click();
    cy.wait(2000);
    cy.get('.monaco-editor textarea:last').type(Cypress.platform == 'darwin' ? '{command}a' : '{ctrl}a');
    cy.wait(2000);
    cy.get('.monaco-editor textarea:last').clear();

```
what i can do to garante that will work always?

### Test code to reproduce

These command sometimes works , sometimes not with monaco editor.
its is very random... 
```js
  cy.get('.monaco-editor textarea:last').siblings();
    cy.wait(2000);
    cy.get('.monaco-editor textarea:last').click();
    cy.wait(2000);
    cy.get('.monaco-editor textarea:last').type(Cypress.platform == 'darwin' ? '{command}a' : '{ctrl}a');
    cy.wait(2000);
    cy.get('.monaco-editor textarea:last').clear();
```

what i can do to guarantee that will work always?

### Cypress Version

9.7.0

### Node version

v12.13.0

### Operating System

MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports) 11.6.1

**Comment by warrensplayer** [comment]
@rubensequeiracx Can you please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by warrensplayer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.
Please comment with a reproducible example and we can reopen. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
