### ISSUE TITLE
Cypress test fails when there is no response form server for an invalid api/url

### ISSUE THREAD

**Issue by anchalbhanwala** [cypress-io/cypress#25751]
### Current behavior

I am running the test to validate the invalid urls , and there is a url which returns no response . How cypress can be utilize to validate that scenario . As suggested in cypress docs , to use failonStatusCode : false in the request and add alias to store the response , the test is failing in this scenario. Looking for a workaround.

### Test code to reproduce

I am fetching the links that needs to be validated from fixture file.
Here's the code
```
 cy.request({
                  method: 'GET',
                  url:data[index].link,
                  timeout: 5000,
                  failOnStatusCode: false,
                 }).as('anchal')
                 
                cy.get('@anchal').its('status')
                 .should('equal', 202)
                }}
```
![image](https://user-images.githubusercontent.com/85665536/217758815-7464dd38-3720-4cd4-a8e4-47075b12ab00.png)

### Cypress Version

9.7.1

### Node version

v16.14.2

### Operating System

windows 10

**Comment by nagash77** [comment]
Hi @anchalbhanwala , Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://discord.gg/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io/), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
