### ISSUE TITLE
The new Cypress Cloud Debug tab may show the failures from main/master as opposed to the current branch

### ISSUE THREAD

**Issue by muratkeremozcan** [cypress-io/cypress#25783]
### Current behavior

Have a repo.
Have Cypress Cloud setup, recording tests.
Have a deployment as well as local testing; we test localhost on PRs, we test a dev deployment on merge.
main branch runs on dev deployment.
Have a test fail on main, you may have to push to main with an intentional failure.

Create a new branch and open Cypress; we see the failure(s) in the Debug tab that occured on the main branch.

### Desired behavior

On a branch we should only see failures in the Debug tab from the branch we are on, granted a CI run occured

### Test code to reproduce

repo:
https://github.com/muratkeremozcan/appsyncmasterclass-frontend
cy cloud dev failure (notice the tag dev-e2e-tests) 
https://cloud.cypress.io/projects/r8t63u/runs/24/overview

(Let me know your github handle and I can give Cypress devs full access as collaborators)

Prerequisite: A failure has to happen on main; you may have to push to main with an intentional failing test. (At this minute it is so but may change on this repository, so if you need help reproducing that, let me know).

```
git clone https://github.com/muratkeremozcan/appsyncmasterclass-frontend.git
cd appsyncmasterclass-frontend
yarn 
yarn cy:open-local # server the app & launches e2e
# or open component tests
yarn cy:open-ct
```

### Cypress Version

12.5.1

### Node version

v16.13.0

### Operating System

probably any, I have Mac

### Other

This issue consistently occurs on our internal repo. I believe the key is to have tests that execute against different deployments; local, dev, stage etc. 

Here is a screen shot from the sample repo.
The local branch is `CyDebugIssueRepro`. It has not been pushed at this minute.
The failure it's showing is the one on main from a day ago.

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/34237651/218460314-eedbc3f8-da78-4268-851e-78908424c6b8.png">

**Comment by muratkeremozcan** [comment]
It appears that using `ref: ${{ github.event.pull_request.head.sha }}` as an option to actions/checkout can work around the issue https://github.com/muratkeremozcan/appsyncmasterclass-frontend/blob/main/.github/workflows/PR.yml#L21

**Comment by warrensplayer** [comment]
@muratkeremozcan and I have been troubleshooting this with his Github repo above.  As be mentions above, the issue stems from using the default for the Github action `actions/checkout` (https://github.com/actions/checkout).  His solution is to use this option: [Checkout pull request HEAD commit instead of merge commit](https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit). Without this change, the action would checkout the merge commit that Github creates for each PR. This commit does not exist in a developer's local environment, so the Cypress App is not able to match up any runs recorded to Cypress Cloud against those PR merge commits. 

He has tested out this change in the Github repo above and is waiting for PRs to be reviewed against the internal repo at his company.

**Comment by marktnoonan** [comment]
@muratkeremozcan let me know if you have had any success with the option described above. Assume that solves your issue, this might be something we need to document for others.

**Comment by marktnoonan** [comment]
Closing this for now, @muratkeremozcan we can re-open when you have an update.
