### ISSUE TITLE
Improve startup performance

### ISSUE THREAD

**Issue by lilaconlee** [cypress-io/cypress#2579]
It takes several seconds for Cypress to startup and open browser at beginning of tests. 

Decrease this startup time. 👍

**Comment by sebinsua** [comment]
See also: https://github.com/cypress-io/cypress/issues/3692

**Comment by indrajitbnikam** [comment]
Any Progress on this issue? I'm really stuck for a long time and I really want to use cypress.

**Comment by jennifer-shehane** [comment]
There has been no work done on this issue.

**Comment by indrajitbnikam** [comment]
@jennifer-shehane When can I expect this issue to be worked on? where can I see the progress?

**Comment by mpulipati** [comment]
Any update on this issue. It's taking 45 secs for Cypress to startup and open browser at beginning of tests.

**Comment by jennifer-shehane** [comment]
@mpulipati Typically opening Cypress will take a few seconds. 45 seconds or anything more than around 10 seconds to open is *not typical* and generally is due to some other Cypress plugin or file watching process taking up this length of time. 

If you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode, this should give some idea of where the time is being spent before Cypress can start up. 

You could also try removing plugins or preprocessors one at a time to see what is taking up this amount of time.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close this issue until we can confirm this is still an issue. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
