### ISSUE TITLE
Unable to upload file on cypress 12.5.1 , electron browser 110

### ISSUE THREAD

**Issue by Basanthjm** [cypress-io/cypress#25842]
### Current behavior
```js
 const fixturepath = 'AUtomation_Budget_Full.xlsx'
cy.get('[data-cy="chooseFile"]').attachFile(fixturepath,{force:true})
```

My application : `<button _ngcontent-hsy-c343="" type="button" data-cy="chooseFile" class="btn sm-font lh-2 btn-primary br-25 mt-10 uploadfile">Choose File</button>`

```js
{
  "name": "cypressautomation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@4tw/cypress-drag-drop": "^2.2.3",
    "cypress": "^12.5.1",
    "cypress-file-upload": "^5.0.8",
    "cypress-iframe": "^1.0.1",
    "node-xlsx": "^0.21.0"
  },
  "dependencies": {
    "cypress-xpath": "^2.0.1"
  }
}
```

### Test code to reproduce

 const fixturepath = 'AUtomation_Budget_Full.xlsx'
cy.get('[data-cy="chooseFile"]').attachFile(fixturepath,{force:true})

My application : <button _ngcontent-hsy-c343="" type="button" data-cy="chooseFile" class="btn sm-font lh-2 btn-primary br-25 mt-10 uploadfile">Choose File</button>

### Cypress Version

12.5.1

### Node version

18.13

### Operating System

Windows 10

**Comment by marktnoonan** [comment]
Hi @Basanthjm and thank you for the report. This seems like an issue that belongs in the [external cypress-file-upload repository](https://www.npmjs.com/package/cypress-file-upload) since `attachFile` is not a Cypress command.

You might be able to uninstall this package now and try the built in [Cypress `selectFile` command](https://docs.cypress.io/api/commands/selectfile) that was added last year to enable file uploading without the need for a third-party package.

**Comment by marktnoonan** [comment]
@Basanthjm I'm going to close this issue for now due to inactivity, please reply if you think there is an underlying bug in Cypress related to uploading files and we can investigate more.
