### ISSUE TITLE
xvfb should not be used when running in headless mode

### ISSUE THREAD

**Issue by John-H-Smith** [cypress-io/cypress#25874]
### Current behavior

As alredy in https://github.com/cypress-io/cypress/issues/16505, while running cypress in headless mode xvfb has to be installed too.
Should be fixed since version 8.0.0, but on my version 12.5.1 it's not working.

### Desired behavior

`cypress run` should not need xvfb to execute

### Test code to reproduce

- Install cypress on a machine without xvfb
- Execute `cypress run`

### Cypress Version

12.5.1

### Node version

v16.16.0

### Operating System

Linux Debian 11.3 (Without GUI)

**Comment by flotwig** [comment]
@John-H-Smith Xvfb is still required for Cypress to run headlessly, because Cypress uses Electron, which requires a display server even when running headlessly.

I think you are intending to use `ELECTRON_RUN_AS_NODE` to force Cypress to skip using Electron - in that case, you can launch Cypress without Xvfb, but you will be unable to use the `electron` browser to run tests. Please see the docs for more info: https://docs.cypress.io/guides/continuous-integration/introduction#Running-headless-tests-without-Xvfb

Please let me know if this solves your issue.
