### ISSUE TITLE
can't navigate to a specific address

### ISSUE THREAD

**Issue by T-Auto-1** [cypress-io/cypress#25896]
### Current behavior

I believe this is a bug in Cypress: https://github.com/cypress-io/cypress/discussions/25850

### Test code to reproduce

See link provided.

### Cypress Version

12.5.1

### Node version

v19.4.0

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hi @T-Auto-1 , I'm sorry to hear you are having issues using Cypress.  Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by nagash77** [comment]
I'm closing this issue as a duplicate the issue linked by the end user.  If a new reproducible example is provided we can reopen and investigate.
