### ISSUE TITLE
Not able to download cypress

### ISSUE THREAD

**Issue by mini30** [cypress-io/cypress#25892]
### Current behavior

Getting error 
I am currently trying to download cypress in vs code using command npm install cypress --save-dev in Visual Studio Code.
 
Below is the error I am getting which is not letting me move forward .
 
PS C:\Users\AX587UQ\CypressAutomation> npm install cypress --save-dev
npm ERR! code 1
npm ERR! path C:\Users\AX587UQ\CypressAutomation\node_modules\cypress
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node index.js --exec install
npm ERR! Installing Cypress (version: 12.6.0)
npm ERR! 
npm ERR! [STARTED] Task without title.
npm ERR! The Cypress App could not be downloaded.
npm ERR! 
npm ERR! Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: [https://on.cypress.io/proxy-configuration](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fon.cypress.io%2Fproxy-configuration&data=05%7C01%7CMinakshi.Singhal%40in.ey.com%7C05a535a8d4264afc71a708db13f8c30f%7C5b973f9977df4bebb27daa0c70b8482c%7C0%7C0%7C638125731406707119%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=STqe0SsLap%2BEkzDfDaW2NyMtffKB2GCMPGivVYzMfLA%3D&reserved=0)
npm ERR!
npm ERR! Otherwise, please check network connectivity and try again:
npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! URL: [https://download.cypress.io/desktop/12.6.0?platform=win32&arch=x64](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdownload.cypress.io%2Fdesktop%2F12.6.0%3Fplatform%3Dwin32%26arch%3Dx64&data=05%7C01%7CMinakshi.Singhal%40in.ey.com%7C05a535a8d4264afc71a708db13f8c30f%7C5b973f9977df4bebb27daa0c70b8482c%7C0%7C0%7C638125731406707119%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gzHl%2FeHA%2BpfqOou8UhBfS6mBi6RlL3awbCPBv0QxQxY%3D&reserved=0)
npm ERR! Error: unable to get local issuer certificate
npm ERR!
npm ERR! ----------
npm ERR!
npm ERR! Platform: win32-x64 (10.0.19044)
npm ERR! Cypress Version: 12.6.0
npm ERR! [FAILED] The Cypress App could not be downloaded.

### Cypress Version

12.6

### Node version

v18.12.1

### Package Manager

npm

### Package Manager Version

1.0.0

### Operating system

Windows

### Operating System Version

10.0

**Comment by nagash77** [comment]
Hi @mini30 , I'm sorry to hear you are having issues using Cypress.  I cannot replicate the issue you are seeing and am not seeing other reports of our downloads being broken.  What happens when you navigate directly to https://download.cypress.io/desktop/12.6.0?platform=win32&arch=x64 from the machine you are seeing the problem on?

**Comment by mini30** [comment]
I am able to download zip from here

**Comment by marktnoonan** [comment]
I'm curious about this error: 

```
npm ERR! Error: unable to get local issuer certificate
```

There seem to be some [workarounds](https://stackoverflow.com/questions/36494336/npm-install-error-unable-to-get-local-issuer-certificate) you could try, I'm not sure if any apply to your exact setup. I don't think I've seen that in general when Cypress fails to install.

**Comment by mike-plummer** [comment]
This sort of error may indicate you have a MITM SSL proxy on your network (common on corporate systems). 

There are [instructions here](https://docs.cypress.io/guides/references/advanced-installation#Using-a-custom-certificate-authority-CA) for adding an appropriate truststore to enable secure SSL communication using that certificate, or as a quick workaround you can toggle the [`strict-ssl` setting](https://docs.npmjs.com/cli/v9/using-npm/config#strict-ssl) and/or using the [`NODE_TLS_REJECT_UNAUTHORIZED`](https://nodejs.org/api/cli.html#node_tls_reject_unauthorizedvalue) environment variable (but both of these have serious security shortcomings and I cannot recommend doing either).

Your best best may be to contact your security department for instructions on configuring your system's Node/NPM to respect the corporate SSL infrastructure (assuming that is the cause). You can also download the Cypress zip file using your browser and then use the [`CYPRESS_INSTALL_BINARY` environment variable](https://docs.cypress.io/guides/references/advanced-installation#Install-binary) to have Cypress install from that file rather than attempting to download directly.

Hopefully these suggestions help you with your issue. If you believe there is an issue outside of your local environment that we can further assist with please comment and we can re-open this issue.
