### ISSUE TITLE
setCookie creates cookie in prepended '.' in domain Cypress 12.7.0

### ISSUE THREAD

**Issue by tommy0831** [cypress-io/cypress#25953]
### Current behavior

This [issue](https://github.com/cypress-io/cypress/issues/25174) was supposed to be fixed with Cypress 12.7.0.  But, looks like it is still happening.

`
    cy.visit('https://www.google.com')
    cy.setCookie('myCookie', '1', {
      domain: 'google.com'
    });
`
<img width="1791" alt="cookieIssue" src="https://user-images.githubusercontent.com/98181057/221385752-43d73877-94dd-4e6a-9cfe-ae2aa08d69ee.png">

### Desired behavior

No dot prepended 

### Test code to reproduce

`
    cy.visit('https://www.google.com')
    cy.setCookie('myCookie', '1', {
      domain: 'google.com'
    });
`

### Cypress Version

12.7.0

### Node version

v14.20.1

### Operating System

macOS 12.5

**Comment by AtofStryker** [comment]
Hey @tommy0831 . Thank you for opening an issue. So the goal of #25174 was not necessarily to eliminate the prepended dot domain as a whole, but to prevent duplicated cookies that were being created with a prepended dot domain. 

The main reason the prepended dot domain exists within Cypress is to ensure cookie compatibility within cypress if the user is to navigate to a subdomain. For example: `www.foobar.com` to `apps.foobar.com`

Cookies set through `cy.origin`, as they are not the main site under test, should not fall under this rule and should have domains set as expected.

If you need to set a `hostOnly` cookie, which is a cookie with the domain not containing a prepended dot, you can now use the `hostOnly` option with the [`setCookie`](https://docs.cypress.io/api/commands/setcookie#Arguments) API as of [`12.7`](https://docs.cypress.io/guides/references/changelog#12-7-0)!

```js
describe('cookie spec', () => {
  it('sets an httpOnly cookie on www.google.com', () => {
    cy.visit('https://www.google.com')
    cy.setCookie('myCookie', '1', { domain: 'www.google.com', hostOnly: true });
  })
})
```

![](https://user-images.githubusercontent.com/3980464/221892083-7cfac3b4-b465-429d-8bab-c11aac75e217.png)

You can leverage the following code, but you will not see it on `www.google.com` cookies in devtools since `google.com` cookie domains do not apply to `www.google.com`:

```js
cy.setCookie('myCookie', '1', { domain: 'google.com', hostOnly: true });
```

I am going to close this, but if you are still running into problems don't hesitate to let us know!
