### ISSUE TITLE
window:confirm does not auto accept when spawned from iframe

### ISSUE THREAD

**Issue by markentingh** [cypress-io/cypress#25955]
### Current behavior

I have a confirm dialog that appears in my application and Cypress never presses the OK button. The confirm dialog just sits there. I've tried adding this code to the top of my spec to make sure I wasn't imagining things

```
beforeEach(() => {
      cy.on('window:confirm', () => true);
  });
```

**To be fair, this confirm dialog was executed within an iframe on the page i am testing, so this may be an issue with Cypress auto accepting confirm dialogs that were spawned by an iframe.**

I ran the latest version of Cypress by executing command `npx cypress open` and choosing E2E & Chrome to run my tests.
I'm using Google Chrome 110.0.5481.105 on Windows 10 x64

### Desired behavior

Cypress should autoselect the OK button for the confirm dialog

### Test code to reproduce

i dont have time to write this

### Cypress Version

12.6.0

### Node version

19.6.1

### Operating System

Windows 10

**Comment by mike-plummer** [comment]
Hi @markentingh , thanks for opening an issue. This has been [reported previously](https://github.com/cypress-io/cypress/issues/6781) and is a result of Cypress not injecting itself into child iframes of the application under test (there is an [open proposal](https://github.com/cypress-io/cypress/issues/136) for this capability). This means that `window.alert` and `window.confirm` calls are not caught by the Cypress stubs since they execute against the `iframe`'s context (not the Application Under Test's `window`. There are a couple workarounds I can propose:

1. In your `iframe` code, use `window.parent.confirm` to explicitly utilize the `confirm` method from the parent window (which would be the Cypress-managed window). Just `confirm` or `window.top.confirm` will bypass the Cypress AUT window, side-stepping our stubs.
2. There is a [recipe for handling child iframe alert/confirm here](https://github.com/cypress-io/cypress-example-recipes/issues/410), but it is a couple years old so there may have been updates to APIs.

Hopefully one of these approaches helps you work around your issue.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by markentingh** [comment]
Thank you for this information. I will use the workaround for now, and hopefully your team will come to a consensus on the matter of iframe handling. Godspeed.
