### ISSUE TITLE
Stubbed requests sometimes slip through as the real ones

### ISSUE THREAD

**Issue by sergeyKhristenko** [cypress-io/cypress#25989]
### Current behavior

Requests that should be stubbed/mocked sometimes slip through as the real ones.

I submitted a bug ticket a while ago - https://github.com/cypress-io/cypress/issues/7478
Looks like the described behaviour didn't change since then. It looks like that the website is continuing to load and there is a gap between end of the previous `it` and `beforeEach` of the next one, so real requests can slip through.

It's one of the biggest sources of flakiness in our test suite since we're mocking all the backend to test frontend in isolation. But these unhandled requests give 401 and screwing everything after.

<img width="950" alt="image" src="https://user-images.githubusercontent.com/18219232/222204986-c6044bf2-608f-4e0e-8688-fa132286f6fc.png">

### Desired behavior

I would like to have the ability to mock all requests

### Test code to reproduce
```js
describe('Test', function () {
  before(function () {
    cy.visit('https://www.theguardian.com/international');
  });

  beforeEach(function () {
    cy.intercept('GET', '**/weatherapi/forecast/**', {}).as(
      'weatherapiforecast'
    );
  });

  for (let i = 0; i < 10; i++) {
    it('load page', function () {
      // reload the page
      cy.get('.inline-the-guardian-logo')
        .should('exist')
        .click({ force: true });
    });
    it('dummy 1', function () {
      // split page loading to multiple `it`s so "weatherapiforecast" request can occur in 'beforeEach'
      cy.wait('@weatherapiforecast'); // this fail sometimes because the request already happened in "beforeEach"
      cy.wait(500);
    });
    it('dummy 2', function () {
      cy.wait(500);
    });
  }
});
```
### Cypress Version

12.3.0

### Node version

14.17.0

### Operating System

macOS/Linux

**Comment by mike-plummer** [comment]
Hi @sergeyKhristenko , as @jennifer-shehane [pointed out on your previous issue](https://github.com/cypress-io/cypress/issues/7478#issuecomment-635912237) there are some fundamental issues with how you're structuring your tests that cause them to be non-deterministic. Is there a particular reason you need to do your `cy.visit` only once in a `before` block? This can be tempting to do for performance reasons, but is often quite troublesome due to state leaking. There is also no guarantee of test execution order - the runner usually orders them in a predictable manner, but you should design your tests in a way that allows them to be reordered, run in parallel, or a subset of them to be run independently.

I would recommend restructuring your test to migrate your `cy.visit` into the `beforeEach` block. That avoids relying on previous tests for state and ensures stubs and intercepts are generated for each test in isolation. This way you get a fresh Cypress context for each test and your tests can be run independently of one another:

```js
beforeEach(() => {
  // Some broken JS on this page, adding this to allow tests to execute
  cy.on('uncaught:exception', (e) => {
    return false
  })

  // Default Cypress testIsolation loads blank page between tests
  // so our intercept won't get triggered from residual state from previous tests
  cy.intercept('GET', '**/weatherapi/forecast/**', {}).as(
    'weatherapiforecast'
  );
    
  // To speed things up you can add intercepts for third-party
  // JS/CSS assets (Amazon, Google, Ads, etc) so repeated visits
  // don't load unnecessary content
    
  // Load the desired page before each test
  cy.visit('https://www.theguardian.com/international');
});

test('independent test 1', () => {
  // Triggered only by the page load done for this test
  cy.wait('@weatherapiforecast');
});

test('independent test 2', () => {
  // Triggered only by the page load done for this test
  cy.wait('@weatherapiforecast');
});
```

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
