### ISSUE TITLE
Unable to launch Microsoft teams app even after adding the following extension "Ignore-X-Frame-Headers"

### ISSUE THREAD

**Issue by Srikanth07482** [cypress-io/cypress#25995]
### Current behavior

Teams app does not get launched withing an Iframe, so I  added the https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe to the cypress test. Still teams app does not load

### Desired behavior

Teams app should load.

### Test code to reproduce

Test file - 
describe('Microsoft Teams automation', () => {
  it('Logs in and navigates to a channel', () => {
    cy.visit('https://teams.microsoft.com/');

    cy.get('input[type=email]').type('your-email-address');
    cy.get('input[type=password]').type('your-password');
    cy.get('button[type=submit]').click();

  });
});

**cypress.config.js** file - 
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {

    chromeWebSecurity: false,

    setupNodeEvents(on, config) {
      on('before:browser:launch', (browser, launchOptions) => {
        // supply the absolute path to an unpacked extension's folder
        // NOTE: extensions cannot be loaded in headless Chrome
        launchOptions.extensions.push('/Users/srikanthkrishnan/Downloads/Ignore-X-Frame-headers')

        return launchOptions
      })
    },
  },
});

### Cypress Version

12.5.1

### Node version

v18.13.0

### Operating System

macOS 12.5

**Comment by mike-plummer** [comment]
Hi @Srikanth07482 , it appears you already opened a [similar issue regarding MSFT Teams in Cypress](https://github.com/cypress-io/cypress/issues/25883). Information around troubleshooting and what solutions you've tried would be more appropriate to be added to that discussion rather than opening a new issue. I'm closing this as a duplicate and will reply in that issue with some ideas
