### ISSUE TITLE
@cypress/grep doesn't work with multiple grepTags, only runs test with first tag

### ISSUE THREAD

**Issue by GeorgeXCV** [cypress-io/cypress#25994]
### Current behavior

I run a command like:
`cypress run --config excludeSpecPattern=*/*/**/users.cy.ts --env grepTags=@defi @login version=development`

Only tests with the first tag will run, the second tag is ignored.

### Desired behavior

I want to run any tests that have either of those tags.

### Test code to reproduce

`cypress run --config excludeSpecPattern=*/*/**/users.cy.ts --env grepTags=@defi @login version=development`

### Cypress Version

12.6.0

### Node version

16.16.0

### Operating System

13.2.1 (22D68)

### Other

I have tried using quotes, commas and semi-colons and the result is always the same.

**Comment by mike-plummer** [comment]
Hi @GeorgeXCV . I am unable to reproduce your issue, so I suspect it is due to bad CLI syntax in your command. Syntax varies depending on what shell you're using, but on`zsh` I can adapt your command to the following - note the addition of shell-compliant quotes and the comma for setting multiple `env` entries

`cypress run --config excludeSpecPattern="**/users.cy.ts" --env grepTags="@defi @login",version=development`

In my local testing this:
- Appropriately excludes `**/users.cy.ts`
- Sets both the `grepTags` and `version` env vars
- Any tests tagged with `@defi` OR `@login` are run

If fixing your CLI syntax doesn't address the issue I'd be happy to dig in a bit further. A true reproduction repo would be very helpful in that case.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
