### ISSUE TITLE
A loss of chainable cypress context, while changing a viewports' width

### ISSUE THREAD

**Issue by AlexeyKhen** [cypress-io/cypress#26008]
### Current behavior

Cypress loses it's chainable context wherever  i change viewport size in "beforeEach" hook, when testing React App.
![Screenshot from 2023-03-03 13-09-49](https://user-images.githubusercontent.com/67691338/222654821-9387f291-1403-451c-b636-29edf3e990dc.png)

My app is listening to changes in the viewport's width and based on it, replaces the state in the window's history.  At the beginning of each test, I am setting the viewport width at some value, then at the end of each test, cypress changes the viewport's width back to its default value, those changes probably trigger the app to replace the state in the window's history between tests, finally, it leads to error.

### Desired behavior

Cypress should not lose it's context 

### Test code to reproduce

Here is a link on repo: https://github.com/AlexeyKhen/cypress-bug

This error came with cypress 12.5.1 version.
To reproduce the error, build the app and run it in a preview mode.
Then execute cypress' run command .

### Cypress Version

12.5.1

### Node version

v18.12.1

### Operating System

Ubuntu 20.04.5 LTS

### Other

it somehow is related to libs: @floating-ui/react and downshift, without them the bug cannot be reproduced

**Comment by mike-plummer** [comment]
Hi @AlexeyKhen , thanks for opening an issue and thanks so much for putting together a very nice reproduction! I've taken a look at it and I suspect the issue is an error from within your `App` component that just isn't being reported very well. I managed to grab this failure screenshot showing that there is a logical loop on your `ResizeObserver` which, when hit, kills the test while it happens to be doing some unrelated setup. The error is reported as a problem with the aliasing (`as`), but the real problem came out of the ResizeObserver.

![Image](https://user-images.githubusercontent.com/11482842/223235316-45600073-fd4a-47b5-91a2-14d93686133a.png)

My best guess is that the hole in your logic is here - when `containerRef` is getting unmounted you bail out of updating the `container` state variable. Since that never changes you don't re-execute your `useEffect` with the `ResizeObserver` so the cleanup `disconnect` isn't called when expected.

```ts
const containerRef = useCallback((node: HTMLDivElement | null) => {
        if (node !== null) setContainer(node);
    }, []);
```

My React is a little bit rusty but I took a stab at fixing this to validate my guess - I *think* it's still doing the same thing and I can't reproduce the failure with these changes. Main changes are around memoizing `getToggleButtonProps`, using `createRef` for the container reference so you don't have the intermediate `container` state variable, and adding some missing hook dependencies.

```ts
import {useFloating, offset, autoUpdate} from "@floating-ui/react";
import {useSelect} from "downshift";

import {useEffect, createRef, useMemo, useState} from "react";

const MIN_EXPANDED_WIDTH = 1100;

export const Menu = () => {
    const {reference} = useFloating<HTMLButtonElement>({
        placement: "top",
        open: false,
        whileElementsMounted: autoUpdate,
        middleware: [offset(10)],
    });

    const { getToggleButtonProps } = useSelect({
        selectedItem: null,
        items: [],
    });

    const buttonProps = useMemo(() => {
        return getToggleButtonProps({
            ref: reference,
            onClick: () => {},
        })
    }, [reference])

    return (
        <button {...buttonProps}>
            Menu button
        </button>
    );
};


export const getEntryWidth = (entry: any) => {
    return (
        (entry.contentRect.width ||
            entry?.contentBoxSize?.[0]?.inlineSize ||
            entry?.borderBoxSize?.[0]?.inlineSize) ??
        0
    );
};

export const getEntryHeight = (entry: any) => {
    return (
        (entry.contentRect.height ||
            entry?.contentBoxSize?.[0]?.blockSize ||
            entry?.borderBoxSize?.[0]?.blockSize) ??
        0
    );
};

export const useResizeObserver = () => {
    const [dimensions, setDimensions] = useState({
        width: 0,
        height: 0,
    });

    const containerRef = createRef<HTMLDivElement>();

    useEffect(() => {
        if (!containerRef.current) return;

        const elementObserver = new window.ResizeObserver((entries) => {
            const entry = entries[0];

            if (entry) {
                setDimensions({
                    width: getEntryWidth(entry),
                    height: getEntryHeight(entry),
                });
            }
        });
        elementObserver.observe(containerRef.current);

        return () => elementObserver.disconnect();
    }, [containerRef.current]);

    return {
        containerRef,
        dimensions,
    };
};

const MainContainer = ({width}: {
    width: number;
}) => {
    useEffect(() => {
        if (width !== 0 && width <= MIN_EXPANDED_WIDTH) {
            window.history.replaceState(
                null,
                "",
                "/some#eyJjYW1lcmFJZHMiOlsiZTk3OTk4ZDUtOGU3My00MTQ2LTlhYzYtYTE",
            );
        }
    }, [width]);

    return (
        <div>
            <button data-cy="button-backward">Backward button</button>
            <Menu/>
        </div>
    );
};


function App() {
    const {containerRef, dimensions} = useResizeObserver();

    return (
        <>
            <div ref={containerRef}>
                <MainContainer width={dimensions.width}/>
            </div>
        </>
    );
}

export default App
```

In case those changes are actually invalid (sorry if they are 😬 ) I did find a potential workaround - use test configuration to set the viewport size rather than `cy.viewport`. I wasn't able to reproduce the issue if you have Cypress create the viewport at the desired size initially rather than doing a resize later with `cy.viewport`:

```js
context("context bug, use test config", { viewportWidth: DESKTOP_SIZE[0], viewportHeight: DESKTOP_SIZE[1]}, () => {
        beforeEach(() => {
            cy.visit(`/`);
        });
...
```

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
