### ISSUE TITLE
Could not type colon(:) on a div  even though parseSpecialCharSequences is set to false

### ISSUE THREAD

**Issue by gowthamieb** [cypress-io/cypress#26022]
### Current behavior

cy.type colon on a div with contenteditable="true" doesnt work even though parseSpecialCharSequences is set to false

### Desired behavior

I have tried the below and it doesnt work. The same works as expected for input type and not for div even though contenteditable is set to true.
```js
cy.get('div .test')
.type('100::20', {
parseSpecialCharSequences: false,
})
```
### Test code to reproduce
```js
cy.get('div .test')
.type('100::20', {
parseSpecialCharSequences: false,
})
```
### Cypress Version

12.4.0

### Node version

v16.13.0

### Operating System

macOS 11.7.1

**Comment by mike-plummer** [comment]
Hi @gowthamieb , sorry to hear you're having trouble. I took a quick look at this and cannot reproduce your issue. The following setup works as expected for me on Cypress 12.4.0 & 12.7.0 (latest).

`/index.html`
```html
<html>
    <head></head>
    <body>
        <div contenteditable></div>    
    </body>
</html>
```
`/cypress/e2e/spec.cy.js`
```js
describe('contenteditable verification', () => {
  it('types into div and asserts expected test', () => {
    cy.visit('index.html')
    cy.get('div').type('100::20')
    cy.get('div').should('contain', '100::20')
  })
})
```

![Screenshot 2023-03-06 at 8 53 42 AM](https://user-images.githubusercontent.com/11482842/223145747-1d516f94-04ae-4faf-b2d7-4959319d1361.png)

Can you share a reproduction case showing the failure? Is it possible the `div` isn't actionable at the time you're trying to type (not visible or encased within a `disabled` element)? An easy way to verify is to use the `force` option on `cy.type` to ignore actionability

**Note:** `parseSpecialCharacters` would have no effect here - that option is to allow typing strings which otherwise would be interpreted as our special "keystroke" patterns like `{enter}`, but colon (`:`) isn't part of those patterns

**Comment by gowthamieb** [comment]
Hi Mike
Thanks for your inputs. I have made sure the div is actionable and have also enabled the force option. I see the colons are being truncated by the cy.type command. It only types 10020 and the colons are missing.

<img width="1528" alt="image" src="https://user-images.githubusercontent.com/76729727/223179695-f7978e2a-aaf8-4732-921d-48817f8992b7.png">

**Comment by mike-plummer** [comment]
@gowthamieb Your screenshot indicates you have an action listener of some sort causing certain key events to be swallowed (perhaps doing a `e.preventDefault` on the div or a parent element)? My example above works as expected for a `div` without any custom listener logic, but if I add a `onKeyDown` listener that stops events for `:` then I get the same output you screenshotted:

```js
<div
    contenteditable="true"
    autocomplete="off"
    autocapitalize="off"
    autocorrect="off"
    aria-required="true"
    onKeyDown="if (event.key === ':') { event.preventDefault() }"
></div>
```

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
