### ISSUE TITLE
Cannot submit support ticket via Contact Us form

### ISSUE THREAD

**Issue by nlathammeh** [cypress-io/cypress#26053]
### Current behavior

I fill my name, email, and support category (Other). Type my text in the form and click submit. The form is not submitted due to a reCAPTCHA error. 

### Desired behavior

I am able to submit a support ticket

### Test code to reproduce

Dear Cypress Professional,

We have encountered an issue with creating reusable functions which can be executed sequentially within a spec file. 

I tried to attach psuedo code, but was unable to submit it via this form. I will attempt to describe the code pieces here. We have two functions, f1 and f2. f1 is called first in a test and contains cy.gets, but no clicking is done. f2, which is called right after f1, contains a cy.get.click at the beginning. 

We see in our code that f2 is called shortly after f1, sometimes before f1 has finished executing. We know this because of the click action which only takes place in f2. We managed to reproduce this by placing a large delay using cy.wait within f1, which lead to f2 always being executed before f1 is finished. 

The desired behaviour is that f2 only gets executed after f1 has succesfully completed. 

We searched through the Cypress documentation and found that Cypress has an asynchronous nature and that this is most likely the cause of this issue. However, we have not been able to find a way to achieve the desired outcome. 

We look forward to hearing back from you and your thoughts on how we may resolve this.

Kind regards,

Natasha

Psuedo Code: 

```
it("example test", () => {
  cy.get("...");
  // .. other built-in calls
  f1();
  f2();
}


function f1() {
    cy.get('...').type();
    // .. other built-in calls
}

function f2() {
    cy.get('...').click();
    // .. other built-in calls
}
```

### Cypress Version

0

### Node version

0

### Operating System

Windows

**Comment by mike-plummer** [comment]
Hi @nlathammeh , I'm sorry you had issues with the form - I'll pass that along to ensure it's working as expected.

Regarding your issue, you are correct that [Cypress commands are asynchronous in nature](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Commands-Are-Asynchronous). In your example, the functions `f1` and `f2` will execute almost instantly. The `cy.*` commands they reference will get queued up to execute asynchronously and will execute in the order they were encountered in the test. This can be problematic if you're [mixing Cypress commands with other logic](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Mixing-Async-and-Sync-code) (like calling other javascript functions or attempting to directly interact with the DOM) since it will attempt to execute synchronously. I assume this sort of interaction is what you're describing in your `// .. other built-in calls` comments above.

You can ensure that logic executes only after a cypress command is complete by using a chained [`cy.then`](https://docs.cypress.io/api/commands/then) or [`cy.should`](https://docs.cypress.io/api/commands/should#Function). This ensures your other logic will wait until after the command is complete, which takes into account Cypress' auto-waiting and auto-retry abilities.

```js
it("example test", () => {
  cy.get("...");
  f1();
  f2();
}


function f1() {
    cy.get('...').type()
      .then(() => {
        // .. other built-in calls
      })
}

function f2() {
    cy.get('...').click()
      .then(() => {
        // .. other built-in calls
      })
}
```

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
