### ISSUE TITLE
Page loads for only one run

### ISSUE THREAD

**Issue by jarniKusters** [cypress-io/cypress#26065]
### Current behavior

The page loads, but when you run it again the page does not load anymore

I tried deleting the appdata, and that works for only one run, so i have to constantly delete the appdata

Does anyone have a idee what the problem can be, and a solution?
![image](https://user-images.githubusercontent.com/118997235/224047575-1ac34771-6dfc-49eb-94ea-fcc453359b09.png)

### Desired behavior

Load the page and start testing.

### Test code to reproduce

no code for reproduce

### Cypress Version

11.1.0 and latest

### Node version

latest

### Operating System

windows 11

**Comment by mike-plummer** [comment]
Hi @jarniKusters , sorry to hear you're having trouble. We will need more information in order to help you diagnose the issue you're encountering - a reproducible example is the best way for us to identify and assist with your issue, but if one cannot be provided then we would need the [Debug logs](https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs) from your test run as well as any browser console output generated during the test.

In addition to providing this information I would suggest the following as initial troubleshooting steps:
* Cypress v12 introduced [Test Isolation](https://docs.cypress.io/guides/core-concepts/test-isolation) which should automatically clear all local/session storage & cookies between tests. Can you confirm you aren't trying to manually adjust these areas (I see a `localStorageSnapshot` activity in your screenshot)?
* Is this specific to Chrome, or does it occur for other browsers as well?
* I see you've built a reusable `loginWithUser` command - you may want to review the new [`cy.session` command](https://docs.cypress.io/api/commands/session) introduced in Cypress 12 which allows you to save & restore a session across multiple tests.

**Comment by jarniKusters** [comment]
testisolation: false, because the storage does not need to be reset, otherwise i am not authorised

**Comment by mike-plummer** [comment]
@jarniKusters I'm not sure I understand - you mentioned above you're explicitly clearing App Data from the browser to get runs to work, but you've disabled the feature in Cypress (12+) that does that for you automatically. Your problem seems to be caused by local browser state leaking between tests (cookies, localStorage, etc) - can you try running your tests with `testIsolation` enabled and see if that makes a difference?

**Comment by jarniKusters** [comment]
Sorry for the delayed answer, i have tried to run te test with isolation on true, but it does not change the behavior, and still does not want to load the page more than once.

**Comment by jarniKusters** [comment]
I have found a workaround, i have made a script that deletes the app data everytime i open cypress, and added experimentalSourceRewriting to cypress.config.ts, because i found out it always stopped working when i added a file while cypress was open.
