### ISSUE TITLE
Cypress compile error in web pack 5.

### ISSUE THREAD

**Issue by kidogb** [cypress-io/cypress#26085]
### Current behavior

When I try to use fs in Cypress with Web pack 5. I'm facing an error:```
 Web pack compilation error: Module not found: Can'
t resolve 'fs' in ...
```
I try to do add fallback in webpack.config.js, but still not work. 

### Debug logs

_No response_

### Cypress Version

6.5

### Node version

14.21.0

### Package Manager

npm

### Package Manager Version

6.14

### Operating system

Mac

### Operating System Version

Ventura 13.1

### Other

_No response_

**Comment by mike-plummer** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by lmiller1990** [comment]
Worth noting you cannot use a Node.js module like `fs` when bundling for the browser - in webpack 4 it would automatically polyfill them out (basically "stub" it out), but webpack 5 dropped the auto polyfill feature. Here's a gist describing how to replicate it in webpack 5: https://gist.github.com/ef4/d2cf5672a93cf241fd47c020b9b3066a

If you can provide some code we can run, I can give you more specific guidance.
