### ISSUE TITLE
Cypress adds cypress files to the Angular app during component testing

### ISSUE THREAD

**Issue by CMadden8** [cypress-io/cypress#26088]
### Current behavior

The issue is more obvious when trying to use the [cypress-cucumber-preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor), but it also appears to happen even without such packages. I'm still clear what is going on - but for some reason, Cypress insists on Cypress files being added to Angular app's tsconfig files array, even though that doesn't appear to make any sense.

### Desired behavior

Cypress should not insist on adding Cypress files to the Angular app's tsconfig during component testing.

### Test code to reproduce

The simplest way to test this is to create a basic Angular app that contains the same setup from this [working React example](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples/ct-react-ts). 

The packages to install are: ts-loader, @badeball/cypress-cucumber-preprocessor, @cypress/webpack-dev-server and cypress.

Then copy the code from the cypress.config.ts file in the example above. Changing only the framework to 'angular' and changing the 'tsx' to 'ts'.

Now add a basic test called 'app.ts' to the component folder that tests the boilerplate Angular app component.

It will fail with the below error:

```
ERROR in ./cypress/component/app.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: C:\[omitted paths]cypress\component\app.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```
 
Now add the app.ts file to the tsconfig.app.json:

```
  "files": [
    "src/main.ts",
    "cypress/component/app.ts"
  ],
```

The test will now load and execute correctly.

It appears to be a bug in Cypress itself, rather than the plugin, as the plugin is not, as far as I can tell, modifying anything to do with how Cypress compiles the Angular app during component testing. And as mentioned, it is adding Cypress files to the compilation even without the plugin modifications.

Is there even any workaround to this where I can add the files the Cypress files it wants only for the Cypress component testing? Not ideal, but I think anything is better than nothing.

Just to note, the React app doesn't have the same problem. So it only affects Angular.

I have also posted this on the cucumber git issues section, but as mentioned, I don't think they will be able to solve this as the bug doesn't appear to be on their end.

### Cypress Version

12.7.0

### Node version

16.14.2

### Operating System

Windows

**Comment by mike-plummer** [comment]
@CMadden8 Without a ready reproduction case it appears that this is intended behavior based on how you have `tsconfig.json` and `ts-loader` configured. The `ts-loader` instance you're adding to support Cucumber inherits the `files` array from your `tsconfig`, and that array excludes the Cypress test you're trying to run from the Typescript compilation.  This causes `ts-loader` to fail to prepare the necessary files. Since the test is itself written in Typescript it must get processed by Typescript in order for the test to run. The example you reference uses an almost-blank `tsconfig` which will result in no `files` field and a default value of `**` being applied for the `include` property - this results in Typescript handling any TS files within the project, including the Cypress test, transparently.

I suspect you need to update your `tsconfig` to either use a glob pattern to pick up all project TS files, or a more targeted `files`-based approach depending on your project use case.

**Comment by CMadden8** [comment]
@mike-plummer I've added the full reproduction to [this repo](https://github.com/CMadden8/cypress-angular-test).

While your suggested solution does work, that's not ideal as these modifications to `tsconfig.app.json` will also include the Cypress files when compiling the 'real' Angular app that is built. 

Is there any way to configure Cypress to use its own dedicated `tsconfig.json` file for compiling the app during component testing? This would have the configuration you suggested, but it wouldn't contaminate the `tsconfig.app.json`. Ideally, the app's tsconfig would not be altered to include Cypress files that it doesn't need to function, and could introduce conflicts and other side effects.

**Comment by mike-plummer** [comment]
@CMadden8 Cypress itself will respect a `tsconfig.json` within the `/cypress` directory which itself can extend your project's `tsconfig` as a base - we have a [Typescript section in our docs](https://docs.cypress.io/guides/tooling/typescript-support) that has some more info on customizing your TS setup for Cypress.

However, that will likely not resolve your issue since your `ts-loader` instance will likely pick up the root-level config file depending on how you have your project directories structured. You may need to point it to the config file you want it to use (note - I haven't run this, so you may need to tweak it a bit):

```
{
  test: /\.tsx?$/,
  exclude: [/node_modules/],
  use: [
    {
      loader: "ts-loader",
      options: {
        context: __dirname,
        configFile: require.resolve('./cypress/tsconfig.json')
      }
    },
  ],
},
```

**Comment by CMadden8** [comment]
@mike-plummer that solution should ordinarily work, but the `tsconfig.app.json` file is still being referenced by Cypress during compilation and appears to give priority to this, even though it acknowledges correctly resolving the cypress tsconfig - my guess is because of the direct reference to it in `angular.json`: 

`"tsConfig": "tsconfig.app.json" `

I think you can close this ticket, as I don't see any straightforward to this issue - it's at least clear why the problem occurs.
