### ISSUE TITLE
Fixture doesn't contain mimetype when loaded twice

### ISSUE THREAD

**Issue by royk** [cypress-io/cypress#26095]
### Current behavior

When loading a file using fixture, in the first test the file is loaded with a mimetype. In the second test, the mimetype is empty.

### Desired behavior

Fixture should be loaded with mimetype every time.

### Test code to reproduce

https://github.com/royk/cypress-test-tiny-1

### Cypress Version

12.7.0

### Node version

v16.18.0

### Operating System

Windows 10.0.22621

**Comment by lmiller1990** [comment]
I confirmed this in indeed the case - that's very strange, the second uploaded file type is `''`, instead of `audio/wave`. I tried creating a different fixture named `kicks2.wav` and it works - this seems to only happen when selecting the _same_ fixture.

**Comment by BartRamharter** [comment]
Hi Lachlan,
We just discovered the same bug. We want to use the same PDF as input in different input[type='file'] fields in our tests so put the cy.fixture in the beforeEach() hook but then only the first test succeeds (even if that test uses the pdf to upload in several input fields). From the second test on, the uploads fail because of the missing file mime type.
We also expirimented in putting the cy.fixture() call near the code that uses the .selectFile but then it will fail after the first upload input field even in the same test.
Extra remark: we also noticed when the bug happens that the filename of the fixture is also empty, not just the mimetype. Our front-end shows the reported filename of the uploaded file and this is also blank after the second cy.fixture call for the same PDF.
BTW: for people impacted by this issue: simply not using cy.fixture() but using the actual file path at .selectFile(file), will do the trick of getting to run the tests successfully. Downside is this will read the same file over and over again, but at least it will get the tests to run as they should.

**Comment by lmiller1990** [comment]
> BTW: for people impacted by this issue: simply not using cy.fixture() but using the actual file path at .selectFile(file), will do the trick of getting to run the tests successfully.

Woah, nice find. This is very useful for when someone tries to debug and patch this. I am not sure I've got the bandwidth to do it now, but a PR would be very welcome if anyone wants to take a look. I wonder if `cy.fixture` is doing some caching that `selectFile` doesn't do that somehow leads to this bug.
