### ISSUE TITLE
cy.session() randomly 'fails' in 12.6.0

### ISSUE THREAD

**Issue by ryan-mulrooney** [cypress-io/cypress#26147]
### Current behavior

Our Cypress suite is rather large, and we have a lot of tests within the same spec that rely on actions from previous tests in the same spec.

I just upgraded from cypress 9.x.x to 12.6.0 and had to replace the old PreserveCookies function with cy.session() and {testIsolation:false}. I have things running usually ok, except randomly sometimes the session is lost inbetween tests in the same spec and the test is logged out of the application. This is consistent in a couple of specs, but also happens randomly in others. I never had this problem in cypress 9.x.x when using PreserveCookies to keep me logged into the app. 

I have retries set to 3, and usually when it retries the same spec, it passes. I've noticed this in our CI env, and all when running it locally using the Cypress Test Runner GUI.

Any ideas what is causing this?

### Desired behavior

It to remain logged in for tests in the same spec.

### Test code to reproduce

This is the login code I have wrapped in cy.session() in the beforeEach() block. When a user is logged into the app, navigating to /members/login redirects them to the root of the app (it doesn't log them out, nor clear the csrf token). Clearly the cookies are occasionally being wiped occasionally before the test is due to run.

```js
const loginByCSRF = ({ email, password }) => {
  cy.request('/members/login')

    .its('body')
    .then(body => {
      const csrfToken = getCsrfToken(body)
      cy.request({
        method: 'POST',
        url: 'members/process/login',
        failOnStatusCode: false, // don't fail so we can make assertions
        form: true, // we are submitting a regular form body
        body: {
          email,
          password,
          authToken: csrfToken, // insert this as part of form body
        },
      }).then(response => {
        expect(response.status).to.eq(200)
        //Parse the response body in spite of using an expect() line
        //which will print the entire response body in the logs
        const $html = Cypress.$(response.body)
        expect($html[3].innerHTML).to.include('Dashboard')
      })
    })
}
```

### Cypress Version

12.6.0

### Node version

16.14.0 (but I see it everywhere the tests are run)

### Operating System

macos 12.4

**Comment by lmiller1990** [comment]
Hi! That sounds frustrating - nothing worse than a failure than a "sometimes" failure... someone else just reported a similar issue around sessions (maybe) on 12.6: https://github.com/cypress-io/cypress/issues/26140. There isn't any in the changelog for that release around sessions, though: https://docs.cypress.io/guides/references/changelog#12-6-0

> Our Cypress suite is rather large, and we have a lot of tests within the same spec that rely on actions from previous tests in the same spec.

This is definitely not ideal, but I'm guessing changing things to not rely on previous test state is impractical due to the size of your test suite?

Are you able to share a snippet where it always happens? That might reveal something.

I'll see if I can point this issue to someone who's worked on the sessions feature deeply, they might have some instinct on what's going on.

**Comment by lmiller1990** [comment]
Happy to reopen once we've got more information to continue debugging. Until then, I'll close this, since I don't see any actionable work in Cypress relating to this issue.
