### ISSUE TITLE
Update to Vite 4.2

### ISSUE THREAD

**Issue by lmiller1990** [cypress-io/cypress#26161]
Vite 4.2 is out, but it breaks our development workflow. It's not clear why.

- [Internal thread](https://cypressio.slack.com/archives/C011BAPC614/p1679345453813889)

Reproduce:

```
# Update to vite 4.2.x in the monorepo
cd packages/app
DEBUG=vite* yarn vite build --watch
ls dist # see assets dir and index.html
# modify a file like App.vue
# rebuild never finishes, assets and index.html ARE cleaned up and deleted
```

It hangs on i18n - if you remove that plugin, it hangs on something else. It's not clear if Vite 4.2 broke some plugins. I tried making a minimal reproduction but I was not able to.

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/26161?planning-poker) with Zenhub @astone123 @jordanpowell88 @marktnoonan @mike-plummer @warrensplayer

**Comment by mike-plummer** [comment]
The Vite 4.2 hang on rebuild is caused by the `useMarkdown` composable. The act of doing `import MarkdownIt from 'markdown-it'` causes the hang - commenting out that line (and associated code) allows the rebuild to proceed, but just having the bare import present is enough to hang the rebuild. (don't even have to **_use_** the import)

I'm going to work on putting together a base repro of`vite@4.2.1` + `markdown-it@13.0.1` to validate whether it's a real issue between those two so I can get some bugs filed, or if there's some other magic going on in our baseline causing the issue. In any case, not going to get this wrapped up by end of sprint

**Update:** Created a [minimal reproduction](https://github.com/mike-plummer/vite-markdown-it-repro), appears to be a legit weirdness either in Vite or `markdown-it`

**Update 2:** Reproduction above is fixed by upgrading to `vite@4.3.0-beta.4`. Going to pause this issue pending Vite 4.3 release and try again

**Comment by mike-plummer** [comment]
Vite 4.2.x exhibited a strange hang on rebuild due to issues within the `markdown-it` library we use in the `useMarkdown` hook. I wasn't able to find a good workaround outside forcing a dynamic import of the library on every hook invocation, so we waited for Vite 4.3.0 instead which fixed the hang

**Comment by lmiller1990** [comment]
I synced with @mike-plummer, looks like 4.3 also is problematic. Let me know when you think we should give up updating for now, I'll make another ticket to capture the time spent on this and move this one back to the backlog.

**Comment by mike-plummer** [comment]
Current status is that 4.3 (and associated plugin updates) work, but there is an issue with the binary build (likely caused by a change to esbuild under the covers) as well as a significant number of percy snapshot changes due to slight (1-2px) differences in several icons

**Comment by lmiller1990** [comment]
I wonder if we can just do `nohoist` on `esbuild`. It's only used for development, so having two binaries installed probably isn't the worst thing in the world. Doing anything around v8 snapshots and packherd is uncharted territory for most of us, and I think updating the esbuild version used there is probably not worth it.

**Comment by lmiller1990** [comment]
This is done, we just need to rebase. We will hold off on merging since there is some associated risk. We will merge post release.

I am going to close the issue for the sake of tracking sprint points.
