### ISSUE TITLE
Cannot Run Cypress via Firefox with Older Versions

### ISSUE THREAD

**Issue by ekremaltan** [cypress-io/cypress#26212]
### Current behavior

When I try to run cypress with Firefox browser v109 I receive a pop-up error stating that "You've launched an older version of Firefox" and on the description it's stating as "Using an older version of Firefox can corrupt bookmarks and browsing history already saved to an existing Firefox profile. To protect your information, create a new profile for this installation of Firefox. Down below there are 2 buttons : Quit or Create New Profile. If I click on Quit button, Firefox doesn't open at all. If I click on Create a new profile button, it opens an empty tab in which I cannot run my test.

https://user-images.githubusercontent.com/25629959/227491284-d49673ff-9fdb-4c2c-9cdf-56bc2d53c7bd.mov

### Desired behavior

I should be able to open my test suites in older version of Firefox

### Test code to reproduce

- Install an older version of Firefox browser on your computer
- Turn off automatically update feature of Firefox
- Run your cypress and choose Firefox browser to open e2e
- See that you will receive an error message pop-up and it will block you to open your e2e tests

### Cypress Version

12.3.0

### Node version

16.19.0

### Operating System

macOs 13.1

**Comment by AtofStryker** [comment]
Hi @ekremaltan. Thank you for opening your first issue with Cypress! I have run into this a few times when needed to test older versions of firefox on macOS, and it usually becomes an issue when you have had a later version installed and are trying to downgrade. I am currently not running into this running Firefox v108 (time of writing Firefox is on version v111), but this due to me not upgrading. If I were to upgrade to v111, and then downgrade back down to v108 on macOS, I would more than likely experience this issue. 

A lot of this has to do with the profile data, specifically on MacOS, which you mentioned in the post. I have run into this outside Cypress as well, so I am not entirely convinced this is a Cypress unique issue, rather a Firefox on macOS  issue.

##### Possible workarounds
Is running Cypress on Linux an option? Installing older Firefox [tar](https://download-installer.cdn.mozilla.net/pub/firefox/releases/) packages works quite well and does not run into this issue. I have not tried on Windows. 

If that isn't an option, you may be able to use VMWare with an Ubuntu ISO image or dockerize the solution locally and connect to the docker display using XServer (or XQuartz for mac). The first option would likely be a lot easier 😅 .

I know this is a bit of a pain, but are any of these options for you?

**Comment by mschile** [comment]
@ekremaltan, you can probably just delete your Cypress firefox profile. Run `npx cypress info` and you can see the path to the browser's profile. Just delete the folder and a new profile will get created.

**Comment by emilyrohrbough** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
