### ISSUE TITLE
Importing a fixture file that is overwritten in a test causes the test runner to loop indefinitely

### ISSUE THREAD

**Issue by githubaja** [cypress-io/cypress#26249]
### Current behavior

I have written a short command in command.js file
```js
Cypress.Commands.add("generateApplicant", () => {
const faker = require("faker");

cy.writeFile("cypress/fixtures/applicant.json", {
firstName: ${faker.name.firstName()},
lastName: ${faker.name.lastName()},
});
});
```
I can successfully invoke my command inside a test file and the applicant.json file will be created in my fixtures folder.
The problem occurs if I try to import said fixture file and then during the test change it. I'm not saying it's best practice, but unexpected behaviour does occur. Test code is below:
```js
/// <reference types="cypress" />
import applicant from "../../fixtures/applicant.json";
describe("Neverending loop", () => {
  before(() => {
    cy.generateApplicant();
  });
  it.only("My test", function(){
    cy.log("Hi");
  });
});

```
If you run the test using `npx cypress open` and clicking on the script - it will loop over and over again generating a new applicant.json every time. Comment (or remove) the import statement - looping will stop and the spec file will complete as expected in a single run.

### Desired behavior

Cypress test runner shouldn't loop endlessly. I can manage the data in the file but the test suite cannot run if there is an import statement and fixture file generation in the same spec file.

### Test code to reproduce

command.js
```js
Cypress.Commands.add("generateApplicant", () => {
const faker = require("faker");

cy.writeFile("cypress/fixtures/applicant.json", {
firstName: ${faker.name.firstName()},
lastName: ${faker.name.lastName()},
});
});
```

spec file:

```js
/// <reference types="cypress" />
import applicant from "../../fixtures/applicant.json";
describe("Neverending loop", () => {
  before(() => {
    cy.generateApplicant();
  });
  it.only("My test", function(){
    cy.log("Hi");
  });
});
```

### Cypress Version

12.8.1

### Node version

18.12.0

### Operating System

Windows 11

### Other

Issue is reproducible in both Chrome and Electron browsers that come in Cypress 12.8.1

**Comment by emilyrohrbough** [comment]
@githubaja What you are describe where the test will endlessly restart __does__ sound like correct behavior given how you are importing this fixture.

Because your custom command is writing a new `applicant.json` file each time the spec is loaded and executed and because you are directly importing this file into your spec, hot-reloading is triggering the spec refresh to run against the latest changes.

I would recommend considering one of the following options that work best for you:

1. remove the import and use the [`cy.fixture()`](https://docs.cypress.io/api/commands/fixture) command. Depending on how you want to use this data in your test, it might be less intuitive. For example:
```js
// import applicant from "../fixtures/applicant.json";
describe("no loop", () => {
  before(() => {
    cy.generateApplicant()
  })

  it("My test", function(){
    cy.fixture('applicant.json')
    .then((applicant) => {
      cy.log(`Hi, ${applicant.firstName}`)
    })
  })
})
```
2. keep the import, but move the fixture generation to either a [`before:run`](https://docs.cypress.io/api/plugins/before-run-api) or [`before:spec`](https://docs.cypress.io/api/plugins/before-spec-api) node event callback. Note: there are a few known issues with the `experimentalInteractiveRunEvents` experiment and I recommend writing sync callbacks.

**Comment by emilyrohrbough** [comment]
Closing since this behavior is correct.
