### ISSUE TITLE
cy.orign fails to switch to auth0  window

### ISSUE THREAD

**Issue by cjmacharia** [cypress-io/cypress#26382]
### Current behavior

When using cy.origin, cypress fails to point  to the new auth0 origin when its a new window

<img width="721" alt="Screenshot 2023-03-31 at 15 54 05" src="https://user-images.githubusercontent.com/29351276/229125571-753a89b5-1e50-4959-9727-a9aa4da30d5a.png">

### Desired behavior

cy.origin should point to the popup window 

### Test code to reproduce

```
it('should successfully login a customer', () => {
    cy.visit('https://app.test.nala.ninja');
    authPage.clickLoginWithEmail();
    cy.origin('https://nala-test.eu.auth0.com', () => {
      cy.get('#username').type('test@test.com');
      cy.get('input[type="password"]').type('testpassword', { log: false });
      cy.get('input[type="submit"]').click();
    });
      });
```

### Cypress Version

12.9.0

### Node version

v19.7.0

### Operating System

macos Venturi 13.2.1

### Debug Logs

```shell
Timed out retrying after 10000ms: 
The command was expected to run against origin https://nala-test.eu.auth0.com 
but the application is at origin https://app.test.nala.ninja.

This commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.

Using cy.origin() to wrap the commands run on https://app.test.nala.ninja will likely fix this issue.

cy.origin('https://app.test.nala.ninja', () => {

  <commands targeting https://app.test.nala.ninja go here>

})

https://on.cypress.io/cy-visit-succeeded-but-commands-fail
```

### Other

I am thinking this is an auth0 window that is outside cypress.. how do I handle this

**Comment by nagash77** [comment]
Hi @cjmacharia , Unfortunately at this time that is a [limitation of cy.origin](https://docs.cypress.io/api/commands/origin#Other-limitations). 

Although not ideal, you could try adding a check in your site that detects if Cypress is running and do a redirect rather than a popup while being visited via Cypress.

Something like:
```js
return window.Cypress ? redirect() : popup()
```

I would also encourage you to check out our [community chat](https://discord.gg/cypress).  Someone there might have some other ideas as a workaround.
