### ISSUE TITLE
Cypress skips tests that are no marked for skipped

### ISSUE THREAD

**Issue by BetullCakir** [cypress-io/cypress#26403]
### Current behavior

Tests are skipping before running in CI/CD environment. Doesn't give any warning.  I was using version 8.3.1, when I had problems, I upgraded to 10.8.0. However, the problem isn't solved. 

### Desired behavior

What should I do so that the tests aren't skipped?

### Test code to reproduce

Can't add image from project privacy

### Cypress Version

10.8.0

### Node version

v18.14.0

### Operating System

windows

**Comment by MikeMcC399** [comment]
@BetullCakir 

You haven't really given enough information to be able to help you. If your project is confidential and you can't copy exact log files then you would need to show a generic example of what you are doing, like what is in your Cypress test spec, what output you are seeing and what you expect to see.

You can also chat in the Discord community if you need to ask questions. See https://discord.gg/cMjUZg7.

**Comment by nagash77** [comment]
Hi @BetullCakir as Mike mentioned, we will need a reproducible example in order to investigate this further.  I see you upgraded to version 10.8.0 and saw the same problems.  Can you please try upgrading to the latest version of Cypress and see if the problem continues.

I am going to close this issue for the time being.  Please comment back with a reproducible example in the latest version of Cypress and we can reopen for investigation.
