### ISSUE TITLE
Cypress programatic Auth0 authentication not working 

### ISSUE THREAD

**Issue by robto09** [cypress-io/cypress#26420]
### Current behavior

The issue that I am having, is that the application's session is not set.  So the auth0 login form is always shown. It should not happen because I am bypassing the form.

### Desired behavior

In this situation cypress should omit the auth0 login form and access directly to the app or endpoint required, making use of already obtained token. 

### Test code to reproduce

Programatic auth0 login
[https://docs.cypress.io/guides/end-to-end-testing/auth0-authentication#Programmatic-Login](url)

### Cypress Version

12.8.1

### Node version

v18.6.0

### Operating System

macOS 12.5.1

**Comment by nagash77** [comment]
@robto09 Can you explain further what you think is wrong and why and what updates you think need to be made to the documentation?

**Comment by robto09** [comment]
As I mention programatic code is not bypassing the login form due it still appear. So I imagine there is something that needs to be added or modified in current code posted in the documentation. Idea is that everything works due documentation is the main source of true.

**Comment by robto09** [comment]
> @robto09 Can you explain further what you think is wrong and why and what updates you think need to be made to the documentation?

As I mention programatic code is not bypassing the login form due it still appear. So I imagine there is something that needs to be added or modified in current code posted in the documentation. Idea is that everything works due documentation is the main source of true.

**Comment by emilyrohrbough** [comment]
@robto09 You linked to our guide, are you using the code directly from the example and this is not working in the cypress-real-world-app or have you used this guide to modify it to fit your projects needs and it is not working?

**Comment by mjhenkes** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
