### ISSUE TITLE
Accept timezone in test specific environment variable

### ISSUE THREAD

**Issue by nabaisu** [cypress-io/cypress#26435]
### What would you like?

I'd like to know if it's possible to change the timezone environment variable in a single test as [it's in the docs](https://docs.cypress.io/guides/guides/environment-variables#Option-5-Test-Configuration), like this:

```js
// change environment variable for single suite of tests
describe(
  'timezone test',
  {
    env: {
      TZ: 'America/New_York',
    },
  },
  () => {
    it('displays correct timezone', () => {
      console.log({
        cypressEnv: Cypress.env('TZ'), // America/New_York
        browserTZ: Intl.DateTimeFormat().resolvedOptions().timeZone, // Europe/London but should be America/New_York
      });
    })
  }
)
```

### Why is this needed?

To be able to have a specifc timezone for a specific test

**Comment by nagash77** [comment]
Hi @nabaisu Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://discord.gg/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io/), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
