### ISSUE TITLE
Automatic updates of dependencies

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#2644]
### Current behavior:

Dependencies logging security vulnerabilities on install.

### Desired behavior:

No security warnings, but more specifically setting up [Renovate Bot](https://renovatebot.com/gh/marketplace/renovate) to automatically check for dependency updates. 

Can we specifically set it up to prioritize security updates?

I know this is a big issue since this is a monorepo, but I feel that renovate is well vetted now from our other projects and allows for configuration of [monorepo set ups](https://renovatebot.com/docs/presets-monorepo/)

**Other projects config:**
[cypress-documentation renovate.json](https://github.com/cypress-io/cypress-documentation/blob/develop/renovate.json)
[json-schemas](https://github.com/cypress-io/json-schemas/blob/master/renovate.json)
[cypress-dashboard](https://github.com/cypress-io/cypress-dashboard/blob/develop/renovate.json)
[cypress-api](https://github.com/cypress-io/cypress-api/blob/develop/renovate.json)

### Steps to reproduce:

`npm install cypress --save`

### Versions

3.1.0

### Proposed renovate.json file

```json
{
  "extends": [
    "config:base"
  ],
  "automerge": true,
  "commitMessage": "{{semanticPrefix}}Update {{depName}} to {{newVersion}} 🌟",
  "prTitle": "{{semanticPrefix}}{{#if isPin}}Pin{{else}}Update{{/if}} dependency {{depName}} to version {{#if isRange}}{{newVersion}}{{else}}{{#if isMajor}}{{newVersionMajor}}.x{{else}}{{newVersion}}{{/if}}{{/if}} 🌟",
  "major": {
    "automerge": false
  },
  "minor": {
    "automerge": false
  },
  "prHourlyLimit": 1,
  "updateNotScheduled": false,
  "timezone": "America/New_York",
  "schedule": [
    "after 10pm and before 5am on every weekday",
    "every weekend"
  ]
}
```

Will need a PR opened to https://github.com/renovatebot/presets/tree/master/packages/renovate-config-monorepo with:

```json
{
  "packageNames": [
    "coffee",
    "desktop-gui",
    "driver",
    "electron",
    "example",
    "extension",
    "https-proxy",
    "launcher",
    "reporter",
    "root",
    "runner",
    "server",
    "socket",
    "static",
    "ts",
  ]
}
```

**Comment by bahmutov** [comment]
Made an example project that uses Renovate with a "manual" monorepo (top level package.json plus `packages` folder with subfolders) here https://github.com/bahmutov/test-renovate-monorepo/pulls

it seems to just work. Renovate has found all our `package.json` files and upgraded out of date dependencies. It even grouped all `lodash` upgrades among `packages/*` folders into a single PR and has labeled it `SECURITY` because it was a security update

<img width="796" alt="screen shot 2018-12-26 at 2 11 50 pm" src="https://user-images.githubusercontent.com/2212006/50454900-7ba84080-0918-11e9-8ede-6ad93dabefa6.png">
