### ISSUE TITLE
Selector Playground Tooltips can be covered by other page elements

### ISSUE THREAD

**Issue by calvinballing** [cypress-io/cypress#2645]
### Current behavior:

The tooltips for the Selector Playground do not appear on top of all page elements.
The `z-index` of Selector Playground tooltips varies.  I have seen `100`, and `2147483647`.

### Desired behavior:

The tooltips for the Selector Playground appear on top of all page elements (as much as possible).

### Steps to reproduce:

`cy.visit('https://www.walkme.com/technology/');`

0) Wait for the test to finish running.
1) Click on the blue question mark at the bottom of the page,
2) Open the selector playground
3) Click the button that shows the cursor inside of a box (if the button is not already blue) to turn on the display of tooltips
4) Hover over the magnifying glass

![image](https://user-images.githubusercontent.com/5534029/47386422-a12b8a80-d6da-11e8-8079-0efdb9a54e1e.png)

I initially thought this was just based on the `z-index` of the element, but it appears that under some conditions, the tooltip still appears correctly on top of elements with high `z-index` due to additional factors affecting the stacking.

### Versions

Cypress 3.1
Chrome
Windows

To set the `z-index` of the react tooltip, use `className` (see https://www.npmjs.com/package/react-tooltip for more details)

**Comment by calvinballing** [comment]
![image](https://user-images.githubusercontent.com/5534029/47385906-54937f80-d6d9-11e8-9675-22c618785767.png)

**Comment by jennifer-shehane** [comment]
This example is no longer reproducible from the test code provided (no blue question mark at bottom of page). 

This may have been fixed already as part of https://github.com/cypress-io/cypress/pull/3668

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by jhays-nhaschools** [comment]
@jennifer-shehane 

Yes, WalkMe has updated their website since I posted those repro steps. Instead, try this:

1) Run `it('test', () => { cy.visit('https://www.alayacare.com/') });`
2) Wait for the test to finish
3) Open the selector playground
4) Click the button that shows the cursor inside of a box (if the button is not already blue) to turn on the display of tooltips
5) Hover over the disclaimer in the footer "AlayaCare's website stores cookies..."

Actual:
The hovertext is partially covered by the footer. 

Expected:
The hovertext appears above all page content.

Alternately, hover over the "Accept" button, and you will be unable to see the hovertext at all.

![image](https://user-images.githubusercontent.com/43037440/56771632-2de7fb80-6785-11e9-9a2f-3dba7d7b8c7e.png)

**Comment by jennifer-shehane** [comment]
@jhays-nhaschools Thanks so much for following up with an example! I can see the tooltip being partially covered in version 3.2.0 and also in the upcoming pre-release of 3.3.0. 

**3.3.0**
<img width="1002" alt="Screen Shot 2019-04-26 at 12 57 39 PM" src="https://user-images.githubusercontent.com/1271364/56787579-fcbe0880-6822-11e9-9c5a-ad6ff8ec66c7.png">


We'll reopen this issue.
