### ISSUE TITLE
Unexpected token when using experimentalSourceRewriting

### ISSUE THREAD

**Issue by matheobrise** [cypress-io/cypress#26499]
### Current behavior

Hi,
I try to connect to the Recruitee site but I get the following error :

```    
cy.visit('https://app.recruitee.com/login')
cy.get('input[id="admin_email"]').focus().type(emailRecruitee)
cy.get('input[id="admin_password"]').focus().type(`${passwordRecruitee}{enter}`, { log: true })

```
<img width="595" alt="Screenshot 2023-04-14 at 10 14 36" src="https://user-images.githubusercontent.com/49375251/231985743-32b61df7-4d36-4bc9-8a91-c314fa41f885.png">

I thought I saw that this could be solved with ```experimentalSourceRewriting: true``` but now I have this error : 

<img width="417" alt="Screenshot 2023-04-14 at 10 21 50" src="https://user-images.githubusercontent.com/49375251/231987372-f94f3a9f-c828-4751-96c1-72eff78f2256.png">

### Desired behavior

To connect, the url https://app.recruitee.com/login redirects us to https://auth.recruitee.com/?redirect=https%3A%2F%2Fapp.recruitee.com%2Flogin. Once the username and password are entered, we as redirected to the url https://app.recruitee.com/login and that's where we get the errors instead of connecting.

### Test code to reproduce

As you don't have a recruited account, you can't test everything but in the following repo you can still see the last error I get.
The repo : https://github.com/matheobrise/cypress-test-tiny/tree/issue

### Cypress Version

12.9.0

### Node version

v19.5.0

### Operating System

13.3.1

**Comment by jordanpowell88** [comment]
@matheobrise Thank you for providing a reproducible link. I am getting the same error but the error throws regardless if you use the `experimentalSourceRewriting` experimental flag or not.

I believe this is happening because the request to get an auth token returns a 401 and therefore subsequent requests by your app don't have the token it expects. 

![401 Token Request Screenshot](https://user-images.githubusercontent.com/3605268/232805203-50baeec5-848e-4289-bb57-f50d918795fd.png)


I recommend using [cy.origin](https://docs.cypress.io/api/commands/origin) or following one of our authentication guides as a starting point (example: https://docs.cypress.io/guides/end-to-end-testing/auth0-authentication)

**Comment by matheobrise** [comment]
Hi, thanks for your answer but when I try with cy.origin :
```      
    cy.visit('https://google.com')
    cy.intercept('https://auth.recruitee.com/oauth/token').as('login')
    cy.visit('https://app.recruitee.com/login')
    Login on Auth0.
    cy.origin(
      'auth.recruitee.com',
      { args: { username, password } },
      ({ username, password }) => {
        cy.get('input[id="admin_email"]').focus().type(username)
        cy.get('input[id="admin_password"]').focus().type(password, { log: false })
        cy.get('button[type=submit]').focus().click()
      }
    )
    // // Ensure Auth0 has redirected us back to the RWA.
    cy.url().should('equal', 'https://app.recruitee.com/login')
```

When i visit 'https://app.recruitee.com/login' the oauth request failed (expected i think because i am not yet connected?) but the second time when i enter my username and password, the request is good.
<img width="614" alt="Screenshot 2023-04-19 at 09 15 02" src="https://user-images.githubusercontent.com/49375251/232996825-259ce741-9b01-4c11-84fc-5f1352505eaf.png">
But i still have this error after :
<img width="622" alt="Screenshot 2023-04-19 at 09 19 00" src="https://user-images.githubusercontent.com/49375251/232998155-c025afc1-20d2-485a-b03a-05f710d7b9e1.png">

It's because I don't use cy.origin well?

**Comment by jordanpowell88** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://discord.gg/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io/), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

> It's because I don't use cy.origin well?

I recommend looking through the resources below and feel free to ask any further questions in our Discord.

- https://docs.cypress.io/guides/end-to-end-testing/auth0-authentication

**Comment by iepoch** [comment]
Not sure why close this. There is a bug in the experimentalSourceRewriting when redirection happens immediately.  

Cypress recommends setting experimentalSourceRewriting=true in the cypress.json settings file. This instructs Cypress to also rewrite the integrity tag. However, this logic does not get executed when the browser location changes via the window.location.href property. Because of this issue we can not log completely into the site. Using the Cy.origin may route you to the login but after login and the redirect the location and the property never get set again This was using ADB2C or OAuth for login and redirection.  This causes issues with other customers out there who may use this type of logic in doing a redirect of the login. 

Please reopen this to fix an issue with the experimental and using ADB2C or some other Authorization setup like it.

**Comment by jennifer-shehane** [comment]
@iepoch Could you provide a reproducible example that shows this error when experimentalSourceRewriting and the success situation when it is off? I think we're missing that bit of info.

**Comment by iepoch** [comment]
@jennifer-shehane there are some sensitive information that I will have to remove in order to show this and I don't have a way to to create this setup of ADB2C the way the current company has it implemented. But here is what happens.
This is the ADB2C Microsoft SPA Signin where we redirect the users to a sign in page using Azure ADB2C once they click signin they are redirected to the actual site. But because it's a different origin the redirection assumes its different domain when its not. Here is the reproduceable error message.
![image](https://github.com/cypress-io/cypress/assets/7504929/cfe21e21-460d-4d2e-abbc-96a488d2b3ce)


Seems this issue has been around since 2018 but also using the experimentalSourceRewriting isn't working either :
https://github.com/cypress-io/cypress/issues/2393

Cypress Settings
Cypress recommends setting experimentalSourceRewriting=true in the cypress.json settings file. This instructs Cypress to also rewrite the integrity tag. However, this logic does not get executed when the browser location changes via the window.location.href property. So while updating this setting works in some cases, it does not work when logging in to the your login page



Using the Mutation Observer
Before Cypress loads a page, some JavaScript code can be added to the requested page that monitors when the script tags are added to the DOM and executes logic during a failure. However, this code does not get executed when the window.location.href is changed.  When changing from the Spa/signin to the logged in site page.  Heres what that looks like.

![image](https://github.com/cypress-io/cypress/assets/7504929/7756cb8a-3b12-45ae-acbe-9de381a80d0d)


To make this successfully work we added a before each to our main file before all test that needed to login with the following:
![image](https://github.com/cypress-io/cypress/assets/7504929/1e15c823-2e59-4fed-b26a-264f35ac2eaa)

Also note using cy.origin doesn't work either in this instance as the cy.origin routes your but the page is inadvertently just blank.  with no error message.
