### ISSUE TITLE
different login process when use chrome

### ISSUE THREAD

**Issue by wafiqualtrics** [cypress-io/cypress#26532]
### Current behavior

I am getting different login process when I use **Chrome** ( it is working as expected when i use electron).
Current login  process is : 
Visit the URL  >  a Sign In button is showing . 
Click on Sign In button > a child window is opening to enter user name and password. 
Enter user name and password in the child window and click log in  > nothing happen. 

### Desired behavior

Visit URL
Login page to enter the user name and password. 
Enter user name and password and click on login 
User landed in the main homepage. 

### Test code to reproduce
```js
/// <reference types="cypress" />


describe('example to-do app', () => {
    it('login with valid credentials', function() { 

        cy.visit('https://URL')
        
    })
})
```
### Cypress Version

12.10.0

### Node version

18.12.1

### Operating System

MAC ventura 13.3.1 (22E261)

**Comment by nagash77** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by wafiqualtrics** [comment]
Just added useragent = 'cypress' in my cypress config and the issue solved.
Thank you
