### ISSUE TITLE
Cypress crashes when running "npx cypress open" ERROR "Network service crashed, restarting service" 

### ISSUE THREAD

**Issue by PeaceGusenga** [cypress-io/cypress#26543]
### Current behavior

When I run "npx cypress open",  in the background the Cypress Window opens blank and closes down.
In the VSCode Terminal it shows the below error:

![CypressError](https://user-images.githubusercontent.com/37972802/233121395-3e8bf538-9b37-4b5a-9605-1f642a3fe39a.png)

Any help on what I could do to fix this issue ?

### Cypress Version

12.10.0

### Node version

v16.16.0

### Package Manager

npm

### Package Manager Version

8.11.0

### Operating system

Mac

### Operating System Version

10.13.6

**Comment by nagash77** [comment]
Hello @PeaceGusenga , Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

You can also try looking into your [Debug Logs](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) for more information.

Lastly I would encourage you to check out our [Discord server](https://discord.gg/cypress) for additional troubleshooting tips from the community.

**Comment by PeaceGusenga** [comment]
reinstalled Cypress v10.3.0 - issue resolved

**Comment by t-ashraf** [comment]
This issue keeps happening again and again and again. Cypress works and then fails again with the same error next time I start it.

**Comment by jennifer-shehane** [comment]
@t-ashraf It'd be nice if you could provide a reproducible exampe in a new issue so we can track it down.

**Comment by t-ashraf** [comment]
@jennifer-shehane - Sorry, my comment wasn't very helpful. I use a laptop configured by my employer and some setting or custom software running in the background is interfering with Cypress. Cypress worked fine on my old Windows 10 laptop and works fine on my Apple Mac Mini (M2).
At the same time, this is how I've managed to get it working:

1. Use:
`npx cypress open -b electron`
2. Next time I need to open Cypress, I use:
`npx cypress open -b chrome`
3. Repeat step 1

I, essentially, swap between electron and chrome and that seems to work just fine. Hope this helps someone in future.
