### ISSUE TITLE
Cypress Chromium Renderer process just crashed in google cloud docker run

### ISSUE THREAD

**Issue by tgreen7** [cypress-io/cypress#26558]
### Current behavior

Seeing this error in a docker run.

We are using `"cypress/included:12.9.0"` in the config.

> We detected that the Chromium Renderer process just crashed.
> 
> This is the equivalent to seeing the 'sad face' when Chrome dies.
> 
> This can happen for a number of different reasons:
> 
> - You wrote an endless loop and you must fix your own code
> - You are running Docker (there is an easy fix for this: see link below)
> - You are running lots of tests on a memory intense application.
>     - Try enabling experimentalMemoryManagement in your config file.
>     - Try lowering numTestsKeptInMemory in your config file.
> - You are running in a memory starved VM environment.
>     - Try enabling experimentalMemoryManagement in your config file.
>     - Try lowering numTestsKeptInMemory in your config file.
> - There are problems with your GPU / GPU drivers
> - There are browser bugs in Chromium

I have added `experimentalMemoryManagement: true,` and `numTestsKeptInMemory: 1,` (even though we are using cypress.run not cypress.open).

I also added `ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'` from this issue https://github.com/cypress-io/cypress/issues/25357.

But every time the chromium renderer crashes and then the rest of the tests in that run fail. I am not sure what else to do for debugging and solving this.

### Desired behavior

Not have the browser crash.

### Test code to reproduce

I am not sure how to reproduce this easily. We have 1800 tests that are getting run using cypress/included:12.9.0

### Cypress Version

12.9.0

### Node version

16.13.0

### Operating System

ubuntu linux

**Comment by nagash77** [comment]
@tgreen7 without a reproducible example we won't be able to debug very much.  I would suggest trying a few things:

1.  try reproducing this on a smaller number of tests
2. what are the specs of the machine you are running the container on?  Can you try running on a more powerful machine to see if it has any effect?
3. What happens when you run your test suite not in a docker container?

Hopefully this can help narrow down a few variables but ultimately we will need to work towards a reproducible example if we are going to be able to help solve this issue.

Probably also worth you checking out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by nagash77** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
