### ISSUE TITLE
In Cypress component testing, exposed values in a `script setup` component are not accessible on the component instance (AKA `wrapper.vm`)

### ISSUE THREAD

**Issue by segevfiner** [cypress-io/cypress#26575]
### Current behavior

In Cypress component testing, exposed values in a `script setup` component are not accessible on the component instance (AKA `wrapper.vm`).

This is available when using `@vue/test-utils` directly in vitest.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/24731903/234073940-993d9a2d-4024-41c4-8bde-107056a6fa81.png">

### Desired behavior

Exposed values from a `script setup` component are accessible.

P.S. The type returned inside `Chainable` by `mount` is not easily accessible as it is defined inline, which makes it hard to use via an alias (`as`/`get`). It might be nice to turn it into an exported interface for ease of use?

### Test code to reproduce

https://github.com/segevfiner/cypress-test-utils-expose-issue

### Cypress Version

12.10.0

### Node version

v16.20.0

### Operating System

macOS 13.3.1

### Debug Logs
[cypress-debug.log](https://github.com/cypress-io/cypress/files/11313165/cypress-debug.log)

### Other

The same kind of test works in `vitest`.

**Comment by warrensplayer** [comment]
@segevfiner This appears to be due to the older version of `@vue/test-utils` that is used in the Cypress vue mount adaptor.  

@lmiller1990 Can you confirm my hypothesis?  The `@vue/test-utils` dependency has not been updated in 7 months or so.  Is that easy to update without causing a breaking change?

**Comment by lmiller1990** [comment]
Sure, we should be able to bump to https://github.com/vuejs/test-utils/releases/tag/v2.3.2 without breaking.

v2.4.0 has https://github.com/vuejs/test-utils/pull/2026 which may permanent fix this need to constantly update types, but it might be a breaking change, so I'm not sure if we can adopt it yet.

Edit... I tried dropping in Test Utils v2.3.2, I'm getting a bunch of typing errors that are very difficult to understand. I am wondering if we should just make `mount` take `any` as the type, since this is proving quite disruptive to users, at least until we've got a more maintainable solution.

**Comment by lmiller1990** [comment]
Actually, I got the types to work. I see the value but I cannot access it:

![image](https://user-images.githubusercontent.com/19196536/235391485-a394013b-3501-43f4-a2e3-4dd9ddff105a.png)

I think this is related to how we use a Proxy in cypress/vue, to wrap *anothter* proxy in Test Utils... eg [here](https://github.com/vuejs/test-utils/blob/4e4660ea7b9ad41f66a5bff38fff00e53f58ba7c/src/vueWrapper.ts#L23).

Oddly enough, `Reflect.has(component, 'hello')` is `true`, but `Reflect.get(component, 'hello')` is undefined.

**Comment by lmiller1990** [comment]
Fixed in https://github.com/cypress-io/cypress/pull/26633

```
defineExpose({
  hello: 'world'
})
``` 

Will never work. See [docs](https://vuejs.org/api/sfc-script-setup.html#defineexpose). `defineExpose` is only for variables declared - like `const`, `let` etc. I think this will solve your issue, though, of accessed bindings that are in `defineExpose`.
