### ISSUE TITLE
Object wrong in cypress

### ISSUE THREAD

**Issue by luckylimanman** [cypress-io/cypress#26589]
### Current behavior

I write a object named [test_object], and change a key's value, but cypress didn't handle it correctly. 
```
var test_object = {
            'A': '1',
            'B': '2'
        }
```
1. the key of object become lower case
2. the value confused
<img width="643" alt="Screenshot 2023-04-26 at 15 45 05" src="https://user-images.githubusercontent.com/43720807/234505723-c2dcc6eb-a5cb-4bad-b6b1-e5a5a28104da.png">

### Desired behavior

<img width="710" alt="Screenshot 2023-04-26 at 15 46 27" src="https://user-images.githubusercontent.com/43720807/234505935-061214be-6508-42b1-8de8-4b81f2587e37.png">

### Test code to reproduce
```
describe("test", () => {
    var phases = {}
    it('test', () => {
        var test_object = {
            'A': '1',
            'B': '2'
        }
        cy.log(test_object)
        console.log(test_object)
        test_object['A'] = '11'
        cy.log(test_object)
        console.log(test_object)
    })
})
```

### Cypress Version

10.0.0

### Node version

v18.13.0

### Operating System

macOS 13.0.1 (22A400)

### Other

The issue also occurs in the cypress latest version.

**Comment by mschile** [comment]
Hi @luckylimanman 👋, it appears you are [mixing async and sync](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress#Mixing-Async-and-Sync-code) code in your test. You can rewrite your test as follows:

```js
describe("test", () => {
  it('test', () => {
    var test_object = {
      'A': '1',
      'B': '2',
    }
    cy.log(test_object).then(() => {
      test_object['A'] = '11'
    })
    cy.log(test_object)
  })
})
```

The object key displays in lower case due to some formatting but should display correctly in the console when you click the log.

<img width="1218" alt="Screenshot 2023-04-26 at 3 26 06 PM" src="https://user-images.githubusercontent.com/2002044/234707696-ac1711dc-d8b3-47ab-9732-b9ba162c0632.png">
