### ISSUE TITLE
Checking the existence or non-existence of an element and managing both exceptions.

### ISSUE THREAD

**Issue by alessandrostassano** [cypress-io/cypress#26635]
### What would you like?

In this method:
The promise checks for the specific existence of an element, if it exists it returns true otherwise false.
```js
checkFirstCookieButton () {
  return new Cypress.Promise ((resolve) => {
    cy.get('.popup-home > .modal-dialog > .modal-content').then ($ body => {
      const dis = $ body.find ('[style ="padding-right: 20px; background-color: #E4E4E4;"] > span > .fa')
      if (dis.length) {
          resolve (true)
      } else {
          resolve (false)
      }
  })
  })
}
```
The goal of this method is to return a promise to use in this next method:
if it's true then click the button to close the cookie, if it's false then no.
```js
closeCookie() {
    this.checkFirstCookieButton().then(($value) => {
      if ($value) {
        cy.get('[style="padding-right: 20px; background-color: #E4E4E4;"] > span > .fa').click()
        cy.xpath(e_HomePageElements.DeleteButton).click()
      }
      else {
        cy.log("there's no cookie")
      }
    })
  }
```
This workaround is correct? Unfortunately, in the case where the element DOES NOT exist it doesn't work, so I can't manage the situation when I access my site, and sometimes there's a cookie and sometimes there isn't. I need to be able to handle this situation.
Is there a way to check that an element exists and possibly manage the case when it doesn't exist without breaking the test?

### Why is this needed?

 I can't manage the situation when I access my site, and sometimes there's a cookie and sometimes there isn't. I need to be able to handle this situation.

**Comment by nagash77** [comment]
Hi @alessandrostassano , Issues in the repo are reserved for feature requests and bugs since this appears to be neither.  If you have questions about using Cypress check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

If you have a specific feature request please comment back here or edit the description to specify specifically what feature is missing and why you would like to see it.
