### ISSUE TITLE
New test not listed under specs

### ISSUE THREAD

**Issue by Codanag** [cypress-io/cypress#26708]
### Current behavior

After installing cypress V12.12.0, and updating cypress.config.js with specPattern. the new added specs are not listed under specs

![image](https://github.com/cypress-io/cypress/assets/100539606/556a6bb9-1ba7-4e70-9b82-20d0b7156d41)

This is the cypress config file:
``
```
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    supportFile: false,
    specPattern: "cypress/e2e/**/*.cy.{js,jsx,ts,tsx}",
  },
});
```
This is the folder path:

![image](https://github.com/cypress-io/cypress/assets/100539606/52c473ba-48dd-473c-85b6-a84778be5bb5)

### Desired behavior

When adding new tests, they are listed under specs

### Test code to reproduce

N/A

### Cypress Version

12.12.0

### Node version

v18.16.0

### Operating System

Windows 11

**Comment by MikeMcC399** [comment]
@Codanag 

I couldn't see any issue on the example https://github.com/cypress-io/cypress-example-kitchensink repository using Cypress 12.12.0 on Windows 11:

![image](https://github.com/cypress-io/cypress/assets/66998419/80d563b5-b4e9-4123-8b34-9dd4d9dc99cb)

You might like to try cloning this example repository and starting from there.

You don't need to explicitly define `specPattern: "cypress/e2e/**/*.cy.{js,jsx,ts,tsx}",` since this is the default `e2e` value (see https://docs.cypress.io/guides/references/configuration#e2e).

**Comment by Codanag** [comment]
Thank you @MikeMcC399, cloning the repository worked. now I'm seeing all the specs
