### ISSUE TITLE
Cypress.Commands.add needs option to force retry on that command

### ISSUE THREAD

**Issue by SDESkowronski** [cypress-io/cypress#2670]
I've created a custom Cypress command that contains no calls to any other cypress cy.commands. Essentially it does this (simplified example):

`    var elements = Cypress.$(selector)
    expect(elements[0].innerHTML).to.equal(expectedValue)
`
But this does not retry as I expected it to. ALSO your document [https://docs.cypress.io/api/cypress-api/custom-commands.html#Retryability](https://docs.cypress.io/api/cypress-api/custom-commands.html#Retryability) says "WIP" so it is not clear what Cypress does or does not support.

**Comment by jennifer-shehane** [comment]
Hey @SDESkowronski, sorry, that WIP is meant to mean that the documentation was WIP, but I see how that is confusing. There was meant to be a section that explains how to have a custom command retry, but that has not been documented.

I suggest reading through the [Intro to Cypress](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html) doc. Most of the retry-ability is going to be dependent on using the cy commands directly or chaining off of a cy command like `.should()`, instead of `expect` or `Cypress` commands.

**Comment by egucciar** [comment]
@jennifer-shehane

Assuming the developers in question are already well acclamated to native cypress commands and their retryability how do you suggest we were custom commands in a way that they are then retried ? Either standalone or in a chain?

**Comment by lukeapage** [comment]
@jennifer-shehane it seems a few people are lost how to make custom commands that can retry - I've read through the intro to cypress, I've created a command that does
```
cy.window()
   .then((win) => return win.x());
```
but the command is never re-executed to get the new value..

**Comment by tnrich** [comment]
@jennifer-shehane  @bahmutov why not add a way to rerun chains of cy commands back up the stack? This is far and away the largest source of flake in our tests: elements being rerendered and detached from the dom and the commands not being smart enough to rerun. 

Here is a very simplified version of what I'm suggesting:

Say you want to click a button that is next to a label with text: 

```html
<div>I'm a label</div>
<button>Ok</button>
```

And I want to get the button based on the label text: 
```js
cy.contains("I'm a label").siblings().find("button").click({retryChain: true})
```

Maybe the button hasn't rendered by the time the label shows up, or maybe it has been re-rendered and detached from the dom. Why not add an option to retry the whole chain leading up to the click? Can you explain to me why that is technically impossible? Because if it is possible I think we should do it! 

Thank you!

**Comment by tiago-ctw** [comment]
The docs say the reason is mainly because those commands can have side effects in the application. But we should at least have the option to retry if we want. We're also having flaky tests mainly due to rerenders and detached from dom issues. One simple case is testing if a tooltip shows on mouseover by using click or trigger, and since they don't retry, the tooltip sometimes appears and then disappears right away on rerender, and the test fails.

**Comment by FreyaDingDing** [comment]
just a silly question... cy.verifyUpcomingAssertions() is this a default method offered by Cypress? I could find it from official website. If not, which library does it belong to? Thanks.

**Comment by dwelle** [comment]
Yes, it's official, but undocumented.

**Comment by FreyaDingDing** [comment]
Thank you, David.

Regards,
Freya

**Comment by jennifer-shehane** [comment]
@tnrich You're describing what's requested in this issue: https://github.com/cypress-io/cypress/issues/3561 I'd suggest commenting in that thread if you'd like that feature.

**Comment by mirobo** [comment]
I've talked to @bahmutov about my similar case and explained why I want a custom chai assertion wrapped in a custom command (in short: far superior IntelliSense guidance). I'm still in disbelief that my simple solution seems to work just fine... and I would be happy to get some feedback..

The scenario is a table whose table row is updated after a delay and Cypress needs to retry the custom command (which contains the assertion).

Here's the repo: https://github.com/mirobo/cypress-fiddle

And a copy of the relevant code:

`
Cypress.Commands.add('verifyText2', { type: 'assertion', prevSubject: ['element'] }, (subject, expected) => {
  return Cypress.Promise.try(() => subject).then((trimmedText) => {
    expect(trimmedText).to.have.textTrimmed(expected);
  });
});

chai.use((chai, _utils) => {
  chai.Assertion.addMethod('textTrimmed', function (expected) {
    // eslint-disable-next-line no-underscore-dangle
    const $element = this._obj;
    new chai.Assertion($element).to.exist; // NOSONAR
    const actual = getElementValueOrText($element)
      .replace(/\u00A0/g, ' ') // replace non-breaking space
      .replace(/\u200B/g, '') // replace zero width space
      .replace(/\s/g, ' ') // replace new lines, tabs with normal space
      .trim();
    let isEqual;
    if (expected instanceof RegExp) {
      isEqual = !!actual.match(expected);
    } else {
      isEqual = actual === `${expected}`;
    }

    const actualTextEscaped = escape(actual);
    const explanation = `but the TRIMMED text was #{act}. Actual text escaped: '${actualTextEscaped}'`;
    console.log(actualTextEscaped, explanation);
    this.assert(
      isEqual,
      `expected #{this} to have text #{exp}, ${explanation}`,
      `expected #{this} not to have text #{exp}, ${explanation}`,
      expected,
      actual,
      true
    );
  });
});

function getElementValueOrText(element) {
  if (typeof element === 'string') {
    return element;
  }
  return element.prop('tagName') === 'INPUT' ? `${element.val()}` : element.text();
}
`

**Comment by emilyrohrbough** [comment]
Starting in Cypress 12, Cypress comes with its own API for creating [custom queries](https://docs.cypress.io/api/cypress-api/custom-queries).

Queries are a type of command, used for querying the state of your application. They are different from other commands in that they follow three important rules:

1. Queries are synchronous. They do not return or await promises.
2. Queries are retriable. Once you return the inner function, Cypress takes control, handling retries on your behalf.
3. Queries are idempotent. Once you return the inner function, Cypress will invoke it repeatedly. Invoking the inner function multiple times must not change the state of your application.

Please leverage this API to write retriable, custom commands.
