### ISSUE TITLE
Cypress cy.task converts different objects to null or undefined

### ISSUE THREAD

**Issue by alexsch01** [cypress-io/cypress#26715]
### Current behavior

Running:  spec.cy.js                                                                      (1 of 1)

  
```
null
undefined
undefined

[ null ]
[ null ]
[ null ]
```

### Desired behavior

Running:  spec.cy.js                                                                      (1 of 1)

  
```
NaN
[Function (anonymous)]
undefined

[ NaN ]
[ [Function (anonymous)] ]
[ undefined ]
```

### Test code to reproduce

**[cypress/e2e/spec.cy.js]**

```
describe('', () => {
	it('', () => {
		cy.task('log', NaN)
		cy.task('log', function () {})
		cy.task('log', undefined)

		cy.task('log', '')

		cy.task('log', [NaN])
		cy.task('log', [function () {}])
		cy.task('log', [undefined])
	})
})
```

**[cypress.config.js]**

```
const { defineConfig } = require("cypress");
module.exports = defineConfig({
	e2e: {
		setupNodeEvents(on, config) {
			on('task', {
				log(msg) {
					console.log(msg)
					return null
				},
			})
		},
		supportFile: false,
		video: false,
	},
});
```

### Cypress Version

12.12.0

### Node version

v18.16.0

### Operating System

Windows 10 21H2

**Comment by warrensplayer** [comment]
@alexsch01 Can you provide a simple production to make sure we are testing the exact same thing that you are?  Thanks!

**Comment by alexsch01** [comment]
@warrensplayer Does this give different results on your setup?

I updated the issue above with better formatting

**Comment by mike-plummer** [comment]
Hi @alexsch01 - just to confirm, have you reviewed the [docs for `cy.task`](https://docs.cypress.io/api/commands/task#Arguments)? There is some info there that may shed light on the behavior you're seeing:

> An argument to send along with the event. This can be any value that can be serialized by [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify). Unserializable types such as functions, regular expressions, or symbols will be omitted to null.

Since `cy.task` runs in a separate process from the test runner we have to be able to transmit any "arg" values over the wire which requires them to be serializable. Functions and symbols (such as `NaN`) are not serializable, thus are squashed to `null`. Unfortunately, the ability to serialize these items is a limitation of JavaScript

**Comment by alexsch01** [comment]
Ah ok, so this is intended.
