### ISSUE TITLE
cy.readFile / cy.writeFile

### ISSUE THREAD

**Issue by mandriao84** [cypress-io/cypress#2672]
Hello,

Right now the `cy.fixture` function get data from `/cypress/fixtures` by default but it's possible to change it in the `cypress.json`

But the `cy.readFile` and `cy.writeFile` get data from `/` and I dont find a way to set the get data path by default.

Any help please.

Regards.

**Comment by chrisbreiding** [comment]
The fixtures folder is configurable because you save fixture files in there, so `cy.fixture()` uses it as a convenience. With `cy.readFile()` and `cy.writeFile()`, you can read or write any arbitrary file, so there isn't an associated folder where you would necessarily keep all files you use with those commands. The current working directory (cwd) is set to the root of your project because it arguably makes the most sense. 

Can you describe why you want/need to change the current working directory for `cy.readFile()` and `cy.writeFile()`?

**Comment by mandriao84** [comment]
The path I use in localhost are not the same than the path use by my company.
So the idea is just to write the name of the files and not the {path+name}, that way I can push my script without changing anything in it.

**Comment by chrisbreiding** [comment]
I created [a proposal to address this](https://github.com/cypress-io/cypress/issues/2673). Unfortunately, this will be a pretty low priority. As a workaround in the meantime, could you perhaps utilize [cy.task()](https://docs.cypress.io/api/commands/task.html) to get the base path for your files based on the environment the tests are running in? Then you could do something like:

```javascript
cy.task('get:files:base:path').then((basePath) => {
  cy.readFile(`${basePath}/${name}`)
})
```

I'm not sure what the 'get:base:files:path' implementation would look like in the plugins file, but I imagine you can come up with something.

**Comment by mandriao84** [comment]
Thank you
