### ISSUE TITLE
Cypress not click a button 

### ISSUE THREAD

**Issue by MmaounSuboh** [cypress-io/cypress#26809]
### Current behavior

When I click to generate a link, the link generated in new button, but the button is not clickable in the cypress dashboard, even though it is clickable and works fine in the browser 

### Test code to reproduce

       controls.click("#form\\:j_id_x")
        controls.waitFor(1000);
        //cy.get('h3 > a').rightclick({force: true});
        cy.get('h3 > a').click({ force: true });

### Cypress Version

12.12.0

### Node version

18.15.0

### Operating System

Windows 10

### Debug Logs

```shell
No logs
```

### Other

<img width="531" alt="Screenshot_14" src="https://github.com/cypress-io/cypress/assets/134078803/9d1bcb97-479f-484f-bddf-af02aab798cd">

**Comment by nagash77** [comment]
Hi @MmaounSuboh can you please provide a reproducible example using [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny)?  The test code you provided will not be able to be run by an engineer to reproduce this problem.

**Comment by MmaounSuboh** [comment]
@nagash77 Sorry for that, But I can't upload the website since it is secure on Out Company. 
But the use is, the button clickable and redirect to the page in browser, not on the cypress.

**Comment by nagash77** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
