### ISSUE TITLE
session (Laravel) destroyed come back from other domain

### ISSUE THREAD

**Issue by mzee19** [cypress-io/cypress#26862]
### Current behavior

session destroyed after disabling chromeWebSecurity on the same test case in Cypress. When come back from another domain then return to the login page instead of the dashboard page.

### Test code to reproduce

 [Error report](https://github.com/cypress-io/cypress/assets/72722281/7cd558ae-ac5a-4c85-8a6e-5c83838f1143)

### Cypress Version

12.12.0

### Node version

v14.18.0

### Operating System

ubuntu 20.22

**Comment by nagash77** [comment]
Hi @mzee19 Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by mzee19** [comment]
Hey @nagash77
I will login from one domain (https://demo.bankconnect.dev/login) and then switch to another domain (https://demo-company.bankconnect.dev/) after some action performs then does not come back for the first domain as an authenticated person, it works as an unauthenticated person and return to the login page.

## First Domain ##
Cypress.Commands.add("login", () => {
    cy.session([connectionFixture.email], () => {
        cy.visit(cy.config().baseURL + 'login');

        cy.get('#email')
            .type(connectionFixture.email)
            .should('have.value', connectionFixture.email)
        cy.get('#password')
            .type(connectionFixture.password)
            .should('have.value', connectionFixture.password)
        cy.get('input[name="remember"]')
            .check()
        cy.contains('Log in').click()
        cy.url()
            .should('include', 'dashboard')
    })
})


## Switching to the other domain ##
cy.contains('Add connection via UI').click()

## back to first domain##
cy.contains('Done').click()


But redirect to login page instead dashboard page

**Comment by AtofStryker** [comment]
Hi @mzee19. Thank you for providing some reproduction steps above. Would you be able to package this, along with fixtures needed to log in, into a reproduction repository you can link here so we can reproduce on our end and investigate?

**Comment by mschile** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by mzee19** [comment]
@AtofStryker here is the [link](https://demo.bankconnect.dev/login)

**Comment by AtofStryker** [comment]
@mzee19 are you able to provide some type of login credentials in place of the fixtures?
