### ISSUE TITLE
Cypress is Not Responding

### ISSUE THREAD

**Issue by ahmedsuhailrts1** [cypress-io/cypress#26888]
### Current behavior

Once I Open Cypress testrunner and run the test , When I retry to run the test the page keeps on loading and there is a message that Cypress is not responding. I have tried all the things to resolve my issue even i have reset my computer but the issues remains same

### Desired behavior

cypress should respond always why it keeps on loading

### Test code to reproduce

I an not share it with you

### Cypress Version

12.13.0

### Node version

20.20

### Operating System

Windows 10

### Debug Logs

```shell
no
```

### Other

no

**Comment by nagash77** [comment]
Hi @hassam936 , Right now there doesn't seem to be enough information to reproduce the problem on our end. I am going to close this issue until you can provide a reproducible example. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.
