### ISSUE TITLE
Add .vscode to git for project specific tasks, debuggers, settings, and terminals

### ISSUE THREAD

**Issue by brian-mann** [cypress-io/cypress#2689]
Adds:

- `.vscode/launch.json` for debugging
- `.vscode/settings.json` for project specific settings
- `.vscode/tasks.json` for tasks specific to decaffeinating files, or AST codeshifting
- `.vscode/terminals.json` for plugin specific ways of launching terminals with the correct `cwd` for nested `packages`

**Comment by brian-mann** [comment]
It's possible, but the VSCode team checks this into source control - and we're not adding anything that's not specific to our actual project there.

https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control

**Comment by jennifer-shehane** [comment]
I also do not agree with having this committed to code. Especially since this is open source and many contributors may have their own vscode settings that they could easily accidentally commit or overwrite with ours. 

I believe we should have some internal documentation regarding our development practices - and add things like VSCode settings there. On top of that, not all of our dev team even uses VSCode. I've especially seen this need with new hires - having to go over general rules
