### ISSUE TITLE
Client side validation via JavaScript?

### ISSUE THREAD

**Issue by chrisssi2** [cypress-io/cypress#26927]
### Current behavior

I have a field with the ID `name` where the value `1` is not allowed. If a not allowed value is entered my App insert per JavaScript the text 'This value is not valid' in `form`-element when the cursor left the `name`-field. 

I would like to test this.

I have tried this code:

    cy.get('#name').clear().type('1')
    cy.get('#street').trigger('click')
    cy.get('#street').focus().then(() => {
      cy.get('#form').should('contain.text', 'This value is not valid')
    })

Sometimes the test works, sometimes not. In the app itself, the validation works without any problems.

Is this a bug or what do I need to do to make sure the code tests valid?

### Desired behavior

Test shoud success.

### Test code to reproduce

See describtion.

### Cypress Version

Cypress Version: 12.8.1 (stable) 

### Node version

16.16.0

### Operating System

System Platform: linux (Ubuntu - 22.04)

**Comment by nagash77** [comment]
Hi @chrisssi2 Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by chrisssi2** [comment]
I found the issue. 
I need to use `blur()`

`cy.get('#name').clear().type('1').blur()`
