### ISSUE TITLE
cy.stub: stubbed method is never called, the original method is called in the test

### ISSUE THREAD

**Issue by axelle-bch2** [cypress-io/cypress#26946]
### Current behavior

Hello! 
I'm doing E2E testing of a NextJS app. I'm using `cypress.stub` to try and stub a hook.

Although I'm stubbing the method, it seems the original hook is always called in the test, instead of the stubbed method.

I've been stuck on this issues for a while now and I'm running out of ideas 🤯

I have browsed Github / StackOverflow and the like, and found solutions saying it's an environment issues and suggested updating the instance of the hook in the window object.
It seems these solutions were fine for a create-react-app application, but they didn't work in the case of my NextJS app.

![352358786_554317990233965_7428452438912099865_n](https://github.com/cypress-io/cypress/assets/124666721/e5582188-468e-4ef2-b491-fbdf33516cb6)
![352092125_796246468494338_868413066348826263_n](https://github.com/cypress-io/cypress/assets/124666721/949c44e5-124f-40f2-8738-320752e7e542)
![352225284_6096944213752376_443473213903394856_n](https://github.com/cypress-io/cypress/assets/124666721/6632022c-ccc2-4f24-9981-536c6aef3af9)
![352225381_3574278346183080_5921437847033323057_n](https://github.com/cypress-io/cypress/assets/124666721/29febc6a-3ee2-4dae-b658-fdf9b87cb4e6)

### Desired behavior

I'm expecting cypress to call the stubbed method and not the original one

### Test code to reproduce

I have created a basic reproductible example here : [https://github.com/axelle-bch/cypress-stub](https://github.com/axelle-bch/cypress-stub)

### Cypress Version

12.13.0

### Node version

18.14.0

### Operating System

macOS Ventura 13.0

**Comment by AgoraRich** [comment]
I have this issue as well. I've tried to stub a local module function import and it still calls the original. Pretty frustrating as its blocked progress on testing.

**Comment by mike-plummer** [comment]
Hi @axelle-bch , sorry you're having trouble with stubbing. This is a bit of a mind-bender, but in this case you're actually dealing with two different instances of your `useSimpleHook` function. The version used by your component is bundled up by your React application's bundler (Webpack or Vite, most likely), and you're then importing a second version into your spec file which is the one that you're attempting to stub. Tricky! Due to how web app bundlers work it's often difficult to stub/spy on this sort of logic unless there's some sort of global state accessor involved (e.g., a function that gets registered onto `window`, for example).

The best solution for this is likely to use Cypress' built-in [Component Testing solution](https://docs.cypress.io/guides/component-testing/overview). This is designed to load just your React (or Vue, Angular, etc) component and its dependencies directly rather than visiting a webpage (no server necessary!), and this is done in a way that allows you to stub/spy most dependencies since the spec is run within the bundler context. This way you can write E2E tests to address integration-level concerns and leave component logic to the more fine-grained Component Tests.

If you want to continue using E2E testing you would need a way to access the exact function instance used by the code you're testing (which is quite difficult since every React component instance could end up with its own hook instance 🤯 ). You could have it register itself to a known static location (`window.myHookInstance`, for example), or load the hook [dynamically](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) and use `[cy.intercept`](https://docs.cypress.io/api/commands/intercept) to provide a custom implementation (which could be quite complex to get working).

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
