### ISSUE TITLE
Ionic Angular Components not rendering during component testing

### ISSUE THREAD

**Issue by ilsehaydee22** [cypress-io/cypress#26975]
### Current behavior

1.Create a new ionic angular basic project
2. install cypress 12.14.0 
3. Create basic component test
4. Run the test
5. Component does not render when doing mount 
6. 
![image](https://github.com/cypress-io/cypress/assets/135156367/6f62cb80-6442-4c16-9484-62cddd1727ee)
![image](https://github.com/cypress-io/cypress/assets/135156367/83a5a18e-b9ba-4008-b750-698aefa3e417)

### Desired behavior

Component ListComponent should render as expected

### Test code to reproduce

Here is my failing code with the test and components. Please run the test "list-component.cy.ts" which is the one where I have the code that I mentioned earlier.
[component-test.zip](https://github.com/cypress-io/cypress/files/11692667/component-test.zip)

### Cypress Version

v12.14.0

### Node version

v18.16.0

### Operating System

Windows 10

I've looked into another issue very similar to mine https://github.com/cypress-io/cypress/issues/24226
Where someone mentions that there isn't official Cypress support for ionic apps, I'm aware of that.
The main reason of why I wanted to create this issue was to ask if cypress planned on giving official support to ionic apps since this is the current behaviour I've encountered and I don't see how I could render normally the components. We are trying to implement component testing on the company where I work, but we've been encountering different issues such as, and components don't render correctly by passing the component directly like: cy.mount(ExampleComponent). You have to pass in the html in order to render the component,
This is the only workaround I've found so far thanks to the other issue where they mention this: 
![image](https://github.com/cypress-io/cypress/assets/135156367/83bd610f-34fa-4592-8a0c-933da796c782)

_No response_

**Comment by mike-plummer** [comment]
Hi @ilsehaydee22 , thanks for reaching out. At the moment we do not have plans to add direct Ionic support - there are just too many frameworks out there for our small team to maintain. The good news is that we have recently added support for [Third Party framework definitions](https://docs.cypress.io/guides/component-testing/third-party-definitions) so that open source contributors can build a plugin to support pretty much any component framework under the sun. A quick look at npmjs shows one Cypress Ionic plugin but it doesn't use this API and isn't widely used - you could build one out yourself (or see if the Ionic team is interested) using the pattern you described.

If building out a plugin is too much work right now you could also look at defining a [custom `mount` command](https://docs.cypress.io/guides/component-testing/angular/examples#Custom-Mount-Commands) that takes the component reference and element name and builds out the mount pattern from above automatically so you don't have to copy-paste it throughout your tests.

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
