### ISSUE TITLE
Flaky test: 

### ISSUE THREAD

**Issue by bhanuprakash026** [cypress-io/cypress#27003]
### Link to Cypress Cloud or CircleCI failure

Timed out retrying after 5000ms: cy.wait() timed out waiting 5000ms for the 1st request to the route: Create-API. No request ever occurred. I wrote the commands below like this. Can any one reply me to overcome this error

### Link to failing test in GitHub
```js
cy.get('[data-testid="DoubleclicktoeditAPI"]').should('contain', data.apiStudio.apiStudioName);

  cy.get('[data-testid="saveBtn"]').then(($createAPI) => {
    if($createAPI.length === 1 && $createAPI.is(':visible')){
      cy.wrap($createAPI).should('be.visible').and('contain', 'Create API').click({force:true})
      cy.log("Create API button is triggered")
    } else {
      cy.log('Create API button is not triggered')
    }
  }) 
  cy.intercept('POST', '**/push?**').as('Create-API');
  cy.wait('@Create-API');
})
```
### Analysis

I am waiting for your reply 

### Cypress Version

10.11.0

**Comment by nagash77** [comment]
HI @bhanuprakash026 In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

I would also suggest you try upgrading to the latest version of Cypress to see if that fixes your problem.  [Cypress community chat](https://discord.gg/cypress) can be helpful for debugging or answering questions on how to use Cypress as well.

**Comment by haipinggong** [comment]
@bhanuprakash026 , can you try to move your cy.intercept() to be before you click the button? You need to set up the intercept before the request is fired so that Cypress can catch it.

cy.get('[data-testid="DoubleclicktoeditAPI"]').should('contain', data.apiStudio.apiStudioName);

  cy.get('[data-testid="saveBtn"]').then(($createAPI) => {

    if($createAPI.length === 1 && $createAPI.is(':visible')){
      cy.intercept('POST', '**/push?**').as('Create-API');
      cy.wrap($createAPI).should('be.visible').and('contain', 'Create API').click({force:true})
      cy.log("Create API button is triggered")
      cy.wait('@Create-API');
    } else {
      cy.log('Create API button is not triggered')
    }
  }) 

 
})

**Comment by bhanuprakash026** [comment]
It's working now

**Comment by nagash77** [comment]
I'm glad everything is working now.  I am going to close this issue at this point.

**Comment by bhanuprakash026** [comment]
But if API fails I want to fail the test case, is it possible?

**Comment by nagash77** [comment]
I'm not exactly sure what your exact use case is based on your comment but check out our [community chat](https://discord.gg/cypress), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by haipinggong** [comment]
> But if API fails I want to fail the test case, is it possible?
> […](#)

@bhanuprakash026 , you can read through this doc: 
https://docs.cypress.io/guides/guides/network-requests#Assertions

It depends on what you want to check.
Just give you an example, if you want to assert that the API response status code must be 200, then write something like:
 cy.wait(‘@Create-API’).its(‘response.statusCode’).should(‘eq’, 200)
