### ISSUE TITLE
expecting test to fail but it got pass

### ISSUE THREAD

**Issue by HanisNMahadi** [cypress-io/cypress#27028]
### Current behavior

failed to locate the element. supposedly test will fail. but it passed.
![Screenshot 2023-06-14 123904](https://github.com/cypress-io/cypress/assets/132340781/88795e67-e5e9-4d69-aa69-5dae40eabc03)

### Desired behavior

expecting cypress to show fail to locate element .... error message.   

### Test code to reproduce

_.js_
```js
searchUserbyUserName(){
        cy.get("[placeholder='Search User 1']").click().type("CypressSearch");
        cy.wait(1000);
        cy.get("div[class='css-1dbjc4n r-1awozwy r-18u37iz'] div[class='css-901oao css-cens5h']").contains("CypressSearch")
    }
```
_.cy.js_
```js
 it.only("CP-UM-107 - Search user by username", {"retries": 3}, ()=>{
    um.searchUserbyUserName();
  });
```
![image](https://github.com/cypress-io/cypress/assets/132340781/fd3aa63b-e839-4ef4-bf0d-0467de5389e5)

### Cypress Version

12.9.0

### Node version

18.16.0

### Operating System

windows 11

**Comment by nagash77** [comment]
@HanisNMahadi Right now there doesn't seem to be enough information to reproduce the problem on our end. Unless we receive a reliable reproduction, we'll eventually have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by HanisNMahadi** [comment]
you can try replicate it by changing any of your element locator to the invalid one. then run cypress. you will see your test will passes even your element is invalid.

**Comment by nagash77** [comment]
Hi @HanisNMahadi I am not seeing the same behavior on my end.  Can you please provide a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) that demonstrates the problem with step by step instructions that reproduces this behavior?  We will need that in order to investigate further.

**Comment by HanisNMahadi** [comment]
issue solve. there is someone push code to prevent cypress from failing the test to the project. thank you!
