### ISSUE TITLE
npm_config_loglevel env variable is silencing too much (--silent)

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#2705]
## Bug 
introduced by #817 

**Current**:
`npm_config_loglevel` is able to silent the stdout from `cypress version`, `cypress cache list`, cypress downloading message, etc 

**Desired**:
presence of `npm_config_loglevel` should not silence important messages such as the downloading message, and output from `cypress version` and `cypress cache list`, etc

**Comment by isolationism** [comment]
I respectfully disagree. 

Disrespect for this key property means a flood of literally _millions_ of lines of useless logfile output in a container deploy scenario:

```
[20:22:06]  Unzipping Cypress        99% 1s [title changed]
[20:22:06]  Unzipping Cypress        99% 1s [title changed]
[20:22:06]  Unzipping Cypress        99% 1s [title changed]
[20:22:06]  Unzipping Cypress        99% 1s [title changed]
... forever ...
```
I would paste the entire buffer, but I don't think the megabytes of data are valuable — do you?

In fact, you might rightfully surmise that it goes a long way toward _obscuring actually useful log information_ by spamming log files with worthless garbage data, obliterating terminal scrollback buffers, and so on.

If you want to `WARN` people about a large/potentially long download, fine — you get _one line_. The current implementation is a massive waste of resources with no benefit whatsoever. Don't ram it down users' throats.

To wit: Nobody is silencing output because they are waiting on baited breath for how long the process is going to take.

**Comment by Bkucera** [comment]
@isolationism I understand your frustration, the idea here is to print the 6 lines of output when the log level is set to silent. We already try to do this in CI and when no tty, but clearly there are bugs there. and I'm not sure why we haven't fixed the 1000's of lines of output when we detect a tty, I believe there is a PR for it

**Comment by bahmutov** [comment]
I am fine with download progress messages, but I think we are silencing important  stuff that user _is_ asking for: like `cypress --version`
