### ISSUE TITLE
Does browser reset command work for Blazor Server app? 

### ISSUE THREAD

**Issue by GitHVictor** [cypress-io/cypress#27076]
### Current behavior

I am trying to automate test in Cypress for an application developed in Blazor Server. The app is designed to display a message to the user "You have unsaved changes. Please save your changes before exiting" when the user navigates somewhere else but forgot to the save button. 

The problem is that when a test fails and the changes are not saved, all the other tests fail because the app keeps displaying that same message until the cancel button is clicked. 

My question is whether or not clear localstorage works for Blazor Server. I have been trying to use  different commands to clear the browser, including testIsolation to no avail. When I open a new instance of the application in incoginoto mode, the save changes message is not displayed, 

Do you have any suggestion?

### Test code to reproduce

NA

### Cypress Version

12.9.0

### Node version

16.15.0

### Operating System

Windows

**Comment by mike-plummer** [comment]
Hi @GitHVictor , sorry that you're having issues with test isolation. By default (provided [Test Isolation](https://docs.cypress.io/guides/core-concepts/test-isolation#Test-Isolation-Enabled) is enabled), Cypress attempts to clear all cookies, local & session storage, the JavaScript VM, and DOM between tests. These are all browser-side and should be server-agnostic. However, various server frameworks can store state away in unique locations (and against tertiary domains) so it's possible there's a loophole. I'm not at all familiar with Blazor so I would start with a couple questions:

1. Do you know how the message is controlled? Does it use local storage, cookie, etc? If yes, are they against the domain-under-test or a third-party domain (like Microsoft, Google, etc)?
2. Have you tried logging the result of [`cy.getAllCookies()`](https://docs.cypress.io/api/commands/getallcookies), [`cy.getAllLocalStorage()`](https://docs.cypress.io/api/commands/getalllocalstorage), and [`cy.getAllSessionStorage()`](https://docs.cypress.io/api/commands/getallsessionstorage) to see if there's anything that sticks out? These all only cover domains *the test has interacted with* which is why my question about third-party domains above is important
3. Is there a public instance I could test against or other reproducible example I could pull down?
4. You're not super out of date and I don't believe there have been any significant fixes around test isolation recently, but you could try upgrading to a newer version of Cypress to see if you get different results

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
