### ISSUE TITLE
Can Cypress support running in a self-developed browser?

### ISSUE THREAD

**Issue by nizar787** [cypress-io/cypress#27125]
### What would you like?

I would like to test some web pages running in the self-developed browser. Is that supported in Cypress?

I've looked through what browsers Cypress supports: https://docs.cypress.io/guides/guides/launching-browsers#WebKit-Experimental

### Why is this needed?

our web product does not run in Chrome or other browser

**Comment by mike-plummer** [comment]
@nizar787 Depends on what you mean by "self developed". Cypress has built-in integrations to support Chromium-based browsers and Firefox (plus experimental Webkit). If your browser is built atop one of those and complies with the same APIs & protocols then it's a possibility. For a from-the-ground-up unique browser (not built atop Chromium, etc) you would likely need to develop a driver integration so that Cypress knows how to communicate and control it.

Since this is a question about Cypress use rather than a bug report I'm going to close this issue. Questions around using Cypress are better directed to our [community on Discord](https://on.cypress.io/discord) where you can find others who have tackled similar issues or are interested in collaborating with you to find a solution.
