### ISSUE TITLE
cy.contains() is not working as expected

### ISSUE THREAD

**Issue by sreenarayan** [cypress-io/cypress#27147]
### Current behavior

It is not fetching the element even it is visible on UI
![image](https://github.com/cypress-io/cypress/assets/52318279/9366c4d6-85c2-4318-961f-7aeb2bf551f0)

### Desired behavior

In dropdown it is showing the expected element, still it is not clicking it

### Test code to reproduce

it("Verify Filter Dropdown - SelectAll/UnSelectAll/Clear/Invalid filter", () => {
    cy.get(FILTERWIDGET.filterCounty).click();//country
    cy.contains("United States").click({ force: true });
    cy.get(FILTERWIDGET.filterState).click(); //state
    cy.contains("California").click({ force: true });
    cy.get(".sb-dropdown--header-title",{ timeout: 10000 }).eq(2).click() //county
    // cy.wait(5000);
    .contains("Almeda", { timeout: 10000 }).click({ force: true });
});
       

### Cypress Version

12.11.0

### Node version

16.17.0

### Operating System

Windows 10

**Comment by mike-plummer** [comment]
Hi @sreenarayan , thanks for reaching out. Right now there isn't enough information for us to identify exactly what the issue is. We would ask for a reproducible example that we can run ourselves - the code you included is incomplete so we can't run it.

From your screenshot it appears you're attempting to select an item from a dropdown menu using [`cy.contains`](https://docs.cypress.io/api/commands/contains) - you may want to review the [`cy.select`](https://docs.cypress.io/api/commands/select) API to see if that is a better fit for your scenario. Dropdown menus are often coded differently, so it's impossible to say for certain which API would be expected to work in your app.

Finally, it appears you may have a typo in your test. California does not have an "Almeda" county, but there is an "Alameda" - are you just missing the "a"?

**Comment by mike-plummer** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
