### ISSUE TITLE
Allowing setting Chrome bandwidth and latency setting

### ISSUE THREAD

**Issue by mitar** [cypress-io/cypress#2716]
### Current behavior:

Currently, during CI, the client-side connects to local server-side and this makes all API calls very fast. But in production, users are not so close to the server and I would prefer if I could test a more realistic scenario where there is a bandwidth and latency limits.

### Desired behavior:

In Chrome, in web development tool, you can configure the speed and latency override for all HTTP requests. I think it would be great if one could control this from tests in Cypress (or for all tests, or just for some). So that I could also test if on a very slow links behavior is as expected (for example, to test that loading UI element appears and so on).

### Versions

Cypress: 3.1.1
OS: Linux Ubuntu 18.04

**Comment by jennifer-shehane** [comment]
The features requested in this issue are now possible as part of `cy.route2()`. 

`cy.route2()` is currently experimental and requires being enabled by passing `"experimentalNetworkStubbing": true` through your Cypress configuration. This will eventually be merged in as part of our standard API. 

**Please see the `cy.route2()` docs for full details: https://on.cypress.io/route2**

If you encounter any issues or unexpected behavior while using `cy.route2()` we encourage you to [open a new issue](https://github.com/cypress-io/cypress/issues/new?assignees=&labels=&template=bug-report.md&title=) so that we can work out all the issues before public release. Thanks!
