### ISSUE TITLE
Cypress is crashing on the startup after selecting E2E testing in the version 12.17.0

### ISSUE THREAD

**Issue by DmIvanchenko** [cypress-io/cypress#27246]
### Current behavior

After selecting the E2E testing in the Cypress menu, the following error occurs (Performed on Macbook M1 Pro):

(intermediate value)(intermediate value)(intermediate value) is not iterable
TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at v.h (<embedded>:4344:35655)
The Test Runner unexpectedly exited via a exit event with signal SIGABRT

### Test code to reproduce

npx cypress open

### Cypress Version

12.17.0

### Node version

v9.2.0

### Operating System

macOS 13.3.1 (a)

**Comment by nagash77** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please provide a reproducible example of the issue you're encountering. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

Forking [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny) makes sharing a reproducible example easier to share and easier for our engineers to replicate your issues. This method also keeps the reproduction as simple as possible, which helps us eliminate potential causes and noise from the investigation.

**Comment by steveworkman** [comment]
I was able to reproduce it myself and it appears to be fixed in 12.17.1 (https://github.com/cypress-io/cypress/issues/27228) - do an upgrade and you should be fine
