### ISSUE TITLE
Cypress .type() ignores selectionStart (caret position of input) and custom-mask logic

### ISSUE THREAD

**Issue by MaksimSkachko** [cypress-io/cypress#27279]
### Current behavior

During the typing text Cypress doesn't re-read or maybe ignore selectionStart (caret position of input) and ignores custom-mask logic
![cypress](https://github.com/cypress-io/cypress/assets/77272404/e6bb0394-71c5-4ea4-aedd-4144e49ccb1f)

https://github.com/cypress-io/cypress/assets/77272404/67c46636-6ffb-4e1c-bbd3-fec3044af60c

### Desired behavior

Cypress must detect changing selectionStart and doesn't refresh it in this case like it works in browser natively

**_Note:_** it does not reproduce manually
Example:

https://github.com/cypress-io/cypress/assets/77272404/b744fc8c-4bc2-495b-83cc-a02fb2215739

### Test code to reproduce

```
  it("checkControlWithMask", () => {
    cy.visit("https://yegorich555.github.io/web-ui-pack/control/text", { failOnStatusCode: false });
    cy.get('[name="ipaddr"] input').clear().type("123456", {
      delay: 1000,
    });
  });
```

### Cypress Version

12.17.1

### Node version

v18.16.1

### Operating System

Windows 11

### Other

It works as expected with [cypress-real-events](https://github.com/dmtrKovalenko/cypress-real-events) - cy.realType()

**Comment by nagash77** [comment]
Hi @MaksimSkachko that is strange behavior indeed!  I will forward this on to an engineer to investigate.

**Comment by lmiller1990** [comment]
I think it's due to some weird interaction where Cypress events are JS based, which is conflicting with some custom logic you've got in your mask component.

I've seen similar issues before, and the fix was to use https://github.com/dmtrKovalenko/cypress-real-events. It works for your test, too, I tried it out:

```js
it("checkControlWithMask", () => {
  cy.visit("https://yegorich555.github.io/web-ui-pack/control/text", { failOnStatusCode: false });
  cy.get('[name="ipaddr"] input').clear().realType("123456", {
    delay: 1000,
  });
});
```

Note the `realType()` - not `type()`.

This is due to the limitations of JS based type events, which have some differences to real user based input events. I'd recommend using the `cypress-real-events` library, I don't think we can fix this in Cypress core.
