### ISSUE TITLE
failOnStatusCode not working for visit with 404

### ISSUE THREAD

**Issue by tranan89** [cypress-io/cypress#27277]
### Current behavior

failOnStatusCode option is ignored

<img width="747" alt="image" src="https://github.com/cypress-io/cypress/assets/8797144/9ad09b1e-fcf3-4320-bb42-3fd2eba6cf8f">

### Desired behavior

failOnStatusCode works so that cypress doesn't fail the visit with expected 404

### Test code to reproduce

cy.visit(`${this.setup.unitUri}/foo`, { failOnStatusCode: false })

### Cypress Version

12.11.0

### Node version

16.20.0

### Operating System

macOS 13.4.1

**Comment by tranan89** [comment]
Why is there still no progress on this issue? It has been 1,5 month now...

**Comment by tranan89** [comment]
@cacieprins Still waiting for help with this...

**Comment by constantinsuiu** [comment]
I have the same issue but with 401.. The first test passes, but then rest of them fail due to a 401 in network call. The website works regardless of this 401, so not sure why cypress is not ignoring it. 

My code
`  beforeEach(() => {
    cy.visit('', {failOnStatusCode: false});
    loginPage.login(validUser.username, constants.password);
    cy.get(inventoryPage.title).should('have.text', 'Products');
  });`

<img width="1728" alt="Screenshot 2023-11-24 at 12 44 38" src="https://github.com/cypress-io/cypress/assets/6248780/1d9c3e1e-8a43-4d55-bc6b-36f0b8b28001">
