### ISSUE TITLE
Cypress Runner hangs when executing same tests using cy.origin() twice consecutively.

### ISSUE THREAD

**Issue by n1lebg** [cypress-io/cypress#27349]
### Current behavior

Hello, I am currently writing a few tests which test a menu dropdown with options which when clicked open a new tab from another domain which is different from my localhost:30305 app (the system under test). When I open the Cypress runner and run the tests for the first time everything works as expected - the external domain is opened and the checks there are passing successfully. When I run the same tests for a second time using the same Cypress Runner session the tests cannot switch correctly to the new tab using cy.origin() and the tests hang and never complete. Also the Runner stops responding and I need to terminate the Cypress runner app from the terminal in VS Code directly.

I have a video on that but I do not know where to upload it. (Please advise me).

Note: This happens when I run the tests using the Cypress runner or in headless mode.

### Desired behavior

The runner should not hang and the tests should be executed successfully.

### Test code to reproduce

```js
cy.visit('/'); // This visits localhost:30305 when the app under tests is started as a service
cy.get('.more-menu') // this opens the menu that contains the dropdown options with the links
cy.get('.menu.transition.right.visible.hidden').contains(option).invoke('removeAttr', 'target', '_self').click(); // this clicks on the desired menu option and opens the link in the same tab

cy.origin("https://forums.chaos.com/forum/chaos-cosmos", () => {
				cy.url().should('include', 'https://forums.chaos.com/forum/chaos-cosmos');
			});` //this executes the cross-origin check successfully but the first time when I run the tests only
```

### Cypress Version

12.9.0

### Node version

14.17.0

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hi @n1lebg Unfortunately at this point in time Cypress [does not support testing in multiple tabs](https://docs.cypress.io/guides/references/trade-offs#Multiple-tabs).  The linked document does give some strategies about working around this current limitation.  Perhaps you can share more about how a first run succeeds but a second run has multiple tabs while the first one did not.

I would also suggest you check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by 0xshubhs** [comment]
The issue you're encountering with your Cypress tests hanging and not completing when switching to a new tab from a different domain can be quite challenging to diagnose without being able to directly see the execution flow and interactions in your environment. However, I can provide some general guidance on possible causes and steps you can take to troubleshoot and resolve the issue:

1. **Video Upload:** You can upload the video to platforms like YouTube, Vimeo, or Google Drive, and then share the link here so that I can review it for further insights.

2. **Version Updates:** First and foremost, consider updating both Cypress and Node.js to the latest versions. Cypress frequently releases updates that include bug fixes and improvements. 

3. **Browser Behavior:** Opening new tabs and switching between them can sometimes lead to unexpected behavior in Cypress. It's possible that the hanging issue could be due to browser behavior when dealing with multiple tabs.

4. **Debugging:** In order to narrow down the issue, consider adding `console.log` statements at different points in your test code to track the flow of execution and identify where exactly the hang occurs. This can help you pinpoint if it's a specific action causing the issue.

5. **`cy.wait` and `cy.get` Combination:** Sometimes, using a `cy.wait` after clicking on a link that opens in a new tab can help Cypress to better track the window/tab switch. For example:

```javascript
cy.get('.menu.transition.right.visible.hidden')
  .contains(option)
  .invoke('removeAttr', 'target', '_self')
  .click();

cy.wait(1000); // Wait for a brief moment before performing the cross-origin check
cy.origin("https://forums.chaos.com/forum/chaos-cosmos", () => {
  cy.url().should('include', 'https://forums.chaos.com/forum/chaos-cosmos');
});
```

6. **Window Handle Management:** Cypress provides the ability to handle multiple windows or tabs. After clicking on the link that opens in a new tab, you can use `cy.window()` and `cy.get()` to interact with elements in the new tab.

```javascript
cy.get('.menu.transition.right.visible.hidden')
  .contains(option)
  .invoke('removeAttr', 'target', '_self')
  .click();

cy.window({ timeout: 10000 }).should('have.property', 'location').and('include', 'https://forums.chaos.com');
```

7. **Timeouts:** Adjusting timeouts can sometimes help with cases where tabs/windows take longer to load. You can use `cy.window({ timeout: ... })` or set a longer timeout using `Cypress.config('defaultCommandTimeout', ...)`.

8. **Isolate the Issue:** Try running the tests with only the relevant portion of the code related to opening the new tab and cross-origin checks. Isolating the problem can help you identify whether the issue is specific to this interaction.

9. **Environment and Network:** Ensure that the systems involved (your local environment and the external domain) are properly configured and have a stable network connection.

10. **Update Cypress Commands:** Make sure you're using the latest syntax and recommended approaches for Cypress commands. Sometimes older syntax might not work as expected in the latest versions of Cypress.

11. **Consult Cypress Documentation:** The Cypress documentation is an excellent resource for troubleshooting issues. You might find specific guidance related to browser interactions and handling multiple tabs/windows.

If you're still experiencing issues after trying these steps, sharing the video or a more detailed code snippet related to the interaction and tab switching could help to provide more targeted assistance.
