### ISSUE TITLE
Cypress Dashboard Displays same image on all tests. 

### ISSUE THREAD

**Issue by HappyMan0001** [cypress-io/cypress#27364]
### Current behavior

1. Run a testrun using 4 VMs via Cypress Dashboard. 
2. After test run is done review test results. 
3. Out of 20 tests, click the 1st test image, 2nd test image, 3rd test image, but the after that the test images are the same as the 3rd test image. 
4. Please note this happens randomly. 
Issue: test images are the same, not different as per test.  

### Desired behavior

User should be able to see images as per tests since the test are different. Not the same image. 

### Test code to reproduce

none

### Cypress Version

11. 1

### Node version

18.13

### Operating System

Windows 10 Enterprise

### Debug Logs

```shell
none
```

### Other

no

**Comment by nagash77** [comment]
Hi @HappyMan0001 In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by HappyMan0001** [comment]
It's pretty basic, the 1st run the before()/beforeEach() block runs, login, set up. But if the 1st run fails, the 2nd run the test will skip over the before()/beforeEach() block (which my test needs) and start the 2nd run on the it() block.
Here is a video from Cypress Cloud, keep an eye on the 2nd run. 
[Cypress Cloud Video](https://cloud.cypress.io/projects/65kjif/runs/38/test-results/49d67654-e6c4-40ef-a230-83f42a50f03c/video?utm_source=Dashboard&utm_medium=Share+URL&utm_campaign=Video)

**Comment by jennifer-shehane** [comment]
Hey @HappyMan0001, I reviewed the video. Typically this happens because there are not enough resources on your machine to handle running Cypress and recording video, so the resources recording the video lock up and your video freezes. 

I would recommend trying v13 of Cypress, where video is turned off and you can review [Test Replay](https://docs.cypress.io/guides/cloud/test-replay) within Cypress to see what happens and not rely on the video.

**Comment by jennifer-shehane** [comment]
Closing as stale. If you're encountering a similar issue, please open a new issue.
