### ISSUE TITLE
install Cypress via pnpm

### ISSUE THREAD

**Issue by inblossoms** [cypress-io/cypress#27419]
### What would you like?

Whether to consider supporting the pnpm install mode. Just as npm and yarn installation are supported.

### Why is this needed?

This is' ridiculous' because of my personal habits (using pnpm), going to install through pnpm to find the entire installation process takes a lot of time, and component test cases are still missing in the final project. When I tried to solve the problem by using 'npx cypress install --force', I circumvented the problem by using npm while reading the document.

**Comment by MikeMcC399** [comment]
@inblossoms 

The Cypress team will need to answer the question about the official support of `pnpm` which you are asking for. Possibly this is just a question of adding it to the documentation.

In my experience Cypress works with `pnpm` and to see Cypress being installed with `pnpm` you can execute the following:

```bash
git clone https://github.com/cypress-io/github-action
cd github-action/examples/basic-pnpm
npm install pnpm@latest -g
pnpm install --frozen-lockfile
pnpm run test 
```

Since you were having issues using `pnpm` with Cypress you might like to contact the Cypress technical community on Discord to get help:

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord)
(click on button)

Also, the template for [Cypress installation issues](https://github.com/cypress-io/cypress/issues/new?assignees=&labels=topic%3A+installation&projects=&template=3-install-issue.yml) includes `pnpm` in the choice list for "Package Manager".

![image](https://github.com/cypress-io/cypress/assets/66998419/05560a41-12ed-4980-9788-165230bb5643)

**Comment by inblossoms** [comment]
@MikeMcC399

Thanks for helping！
