### ISSUE TITLE
While testing my Input fields I am getting the error "Element is covered with another element"  It's look silly.

### ISSUE THREAD

**Issue by tanbin0001** [cypress-io/cypress#27479]
### Current behavior

 
![Screenshot_4](https://github.com/cypress-io/cypress/assets/88830167/aa7321bd-95de-4f4e-8215-3425e7558575)

### Desired behavior

Cypress should allow me to select that input field without any errors.

### Test code to reproduce

I am working on my comanies project It is confidencial.

### Cypress Version

12.17.3

### Node version

16.16.0

### Operating System

Windows 10

**Comment by nagash77** [comment]
Hi @tanbin0001 Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please open a new issue with a reproducible example and link to this issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
