### ISSUE TITLE
Cypress Folder Not Appearing in VS Code

### ISSUE THREAD

**Issue by Lavisha-Chhatwani** [cypress-io/cypress#27563]
### Current behavior

After installing the cypress on my project in VS Code the Cypress folder is not appearing in the side bar of VS  Code. Even after running the cypress it is still not appearing. Kindly guide me  in this issue.
![image](https://github.com/cypress-io/cypress/assets/142401482/294e7ab5-25b9-42c5-9514-db717c7ee929)

### Cypress Version

cypress@12.17.4

### Node version

v18.16.0

### Package Manager

npm

### Package Manager Version

9.5.1

### Operating system

Linux

### Operating System Version

22H2

### Other

After installing the cypress a message popped up on VS Code terminal after installing saying 2 moderate security vulnerabilities found.

**Comment by MikeMcC399** [comment]
@Lavisha-Chhatwani 

- It looks like you did not complete the set up of Cypress. I suggest that you follow the instructions on https://docs.cypress.io/guides/getting-started/opening-the-app to configure Cypress.

- It is also advisable to take some training before attempting to use Cypress otherwise you will be quickly lost. You can find some introductory materials on https://learn.cypress.io/.

- The security vulnerabilities are described in issue https://github.com/cypress-io/cypress/issues/27535.
