### ISSUE TITLE
cy.get() does not accept a DOM element

### ISSUE THREAD

**Issue by alexkrolick** [cypress-io/cypress#2759]
### Current behavior:

`cy.get()` accepts string selectors but not actual DOM node references

### Desired behavior:

`cy.get` seems to be based on jQuery, which accepts a DOM element and returns it wrapped: https://codepen.io/alexkrolick/pen/dQprqX?editors=0011

It may not be idiomatic for some reason but it seems like if a valid reference has been obtained, it should be usable.

### Versions

3.1.1

**Comment by chrisbreiding** [comment]
`cy.get()` only accepts a selector string, so that it can re-query for that selector as part of retrying the command chain. While it is related to jQuery, it does not mimic its signature exactly or all of its features. You can use [cy.wrap()](https://docs.cypress.io/api/commands/wrap.html) to wrap a DOM element reference instead.
