### ISSUE TITLE
Not able to achieve drag and drop using dataTranser 

### ISSUE THREAD

**Issue by cshekharc** [cypress-io/cypress#27649]
### Current behavior

Not able to drag and drop the element with dataTransfer
this is snippet i am using
 
const dataTransfer = new DataTransfer;
       **cy.get('#playlist-49').trigger('dragstart', { dataTransfer });
       cy.get('#dtmf-1').trigger('drop', { dataTransfer });**

Also tried with another option 

 **cy.get('#playlist-49').trigger('dragstart', { dataTransfer: { setData: () => {} } });
 cy.get("[id='dtmf-1']").trigger('drop', { dataTransfer: { getData: () => 'playlist-77**' } });

### Test code to reproduce

const dataTransfer = new DataTransfer;
       **cy.get('#playlist-49').trigger('dragstart', { dataTransfer });
       cy.get('#dtmf-1').trigger('drop', { dataTransfer });**

Also tried with another option 

 **cy.get('#playlist-49').trigger('dragstart', { dataTransfer: { setData: () => {} } });
 cy.get("[id='dtmf-1']").trigger('drop', { dataTransfer: { getData: () => 'playlist-77**' } });

### Cypress Version

^12.3

### Node version

^18

### Operating System

Linux

**Comment by nagash77** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://discord.gg/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
