### ISSUE TITLE
AuthGuard in Angular causes issue for Component Test

### ISSUE THREAD

**Issue by muhamedkarajic** [cypress-io/cypress#27733]
### Current behavior

I have the issue that we have a AuthGuard which we use at a lot of places which ultimatly causes the issue for cypress component tests. So far I haven't found a solution there, what I can say is that I have even tried to just return always true from the AuthGuard but that didn't work.

We are using those 2 libraries for auth
"@azure/msal-angular": "^3.0.1",
"@azure/msal-browser": "^3.0.1"

If any information is needed just let me know.

### Test code to reproduce

Its not a test so this isn't something I have.

### Cypress Version

12.16.0

### Node version

18.16.0

### Operating System

macOS 12.6.6

**Comment by nagash77** [comment]
Hi @muhamedkarajic Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. We also will nto be able to replicate your environment that uses AuthGuard.

My best advice would be to check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
