### ISSUE TITLE
Exclude @types from dependencies and move to devDependencies

### ISSUE THREAD

**Issue by tomitrescak** [cypress-io/cypress#2776]
Hi thanks for the wonderful package. I was wondering whether it would be possible to move @types from dependencies to devDependencies. All the @types/chai definitions are interfering with jest definitions. Also, it's not a great practice to include these in dependencies. Thanks!

**Comment by bahmutov** [comment]
Unfortunately, no, these dependencies have to be installed with Cypress, which itself is installed as a dev dependency (but these types are production dependencies for Cypress types). While I plan to create a nice example that shows how to separate jest types from Cypress types via separate tsconfig.json, we still need to include them.

**Comment by benwiley4000** [comment]
Could this be prioritized? My workaround solution (nothing else has worked) is to add this to my package.json scripts:

```json
    "postinstall": "rm -rf node_modules/cypress/types"
```

**Comment by jennifer-shehane** [comment]
@benwiley4000 We've been working on improving conflicts found in types in our past several releases. This issue is outdated. Try updating to our latest version, if you're still experiencing an issue - open a new issue. There is an existing types conflict issue here: https://github.com/cypress-io/cypress/issues/7435
