### ISSUE TITLE
After test fails, "default blank page" is displayed instead of last DOM

### ISSUE THREAD

**Issue by QuentinFarizon** [cypress-io/cypress#27820]
### Current behavior

After a test fails, "default blank page" is displayed

![Screenshot from 2023-09-15 14-47-22](https://github.com/cypress-io/cypress/assets/33634848/ee35d108-a659-4833-a433-7984f94ba3a0)

Also, when I hover on previous steps, there is no CSS applied, so I can't debug anything :

![Screenshot from 2023-09-15 14-54-13](https://github.com/cypress-io/cypress/assets/33634848/afe0a2c8-df67-457d-8e5b-43a85f132743)

### Desired behavior

A few Cypress versions back (I don't remember when), that displayed the last webpage with full DOM.

### Test code to reproduce

- 

### Cypress Version

13.2.0

### Node version

16.15.1

### Operating System

Ubuntu 20

**Comment by nagash77** [comment]
In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by rdwentmp** [comment]
I'm also able to face this issue since upgrade Cypress to 13.x.x+ versions
<img width="1042" alt="image" src="https://github.com/cypress-io/cypress/assets/33515840/83c9789b-bf50-445a-b178-453aff72be35">
I'm using settings:
    testIsolation: false,
but still some tests failing with this default blank page on CI
