### ISSUE TITLE
Cypress is opening cypress within cypress test runner

### ISSUE THREAD

**Issue by PipulPant** [cypress-io/cypress#27828]
### Current behavior

The test runner is opening a new cypress test runner within

### Desired behavior

The test execution should take place instead of displaying the test runner within the test runner

### Test code to reproduce

Opening the cypress version 13.2.0

### Cypress Version

13.2.0

### Node version

18.15.0

### Operating System

macOS13.5.2

**Comment by nagash77** [comment]
In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
