### ISSUE TITLE
UI mode | TypeError: suite.tests is not iterable

### ISSUE THREAD

**Issue by 403-html** [cypress-io/cypress#27871]
### Current behavior

We get error when we run test suite. All was working for quite a long time so not sure when it stopped working. We changed to new Cypress version few days ago.

After small debug session we have found out it does only occur on `ui mode` when running tests, as tests passes without issue on `run mode`. When we run test, and for example some test fails, then runner picks next... during this we get error like below. Test passes, and it's stuck on the next one.

Error
```
cypress_runner.js:161752  Uncaught TypeError: suite.tests is not iterable
    at findTestInSuite (cypress_runner.js:161752:28)
    at suiteHasTest (cypress_runner.js:161776:10)
    at Runner.<anonymous> (cypress_runner.js:162352:12)
    at Runner.emit (cypress_runner.js:146202:5)
    at next (cypress_runner.js:155477:10)
    at cypress_runner.js:155529:5
    at timeslice (cypress_runner.js:145764:27)
```

### Desired behavior

Tests are seen properly and itarable.

### Test code to reproduce

Can't do, simple cases doesn't work, tried to make reproductive case. Can't share codebase.

Only I can say that tests are nested properly and all brackets are open/closed in hierarchy.

### Cypress Version

13.2.0

### Node version

v18.11.0

### Operating System

macOS 13.5.1

**Comment by nagash77** [comment]
Hi @403-html In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
