### ISSUE TITLE
Cypress keeps crashing after every test

### ISSUE THREAD

**Issue by TrumeterCloudMax** [cypress-io/cypress#27897]
### Current behavior

I open cypress, open the chrome/edge browser and run a test, then I try and change to another page of the UI and it doesn't work. When I go back onto cypress it says (Not Responding). I have to close it and reopen it to run another test. This happens every time.

### Desired behavior

not crash

### Test code to reproduce

I'm unsure how to reproduce this

### Cypress Version

13.2.0

### Node version

v20.7.0

### Operating System

Microsoft Windows [Version 10.0.19045.3324]

**Comment by nagash77** [comment]
Hi @TrumeterCloudMax , can you create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny)?  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.  It would also help to include debug logs from your Cypress run.

**Comment by TrumeterCloudMax** [comment]
I don't even need to add any code to the repo when I fork it, I simply run one of the examples and it works then freezes

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by RamAvni** [comment]
So annoying! It just crashes randomly after simple tests...
