### ISSUE TITLE
'Warning: We failed capturing this video' error when tests are very short duration (2 secs or less) or skipped

### ISSUE THREAD

**Issue by ryanthemanuel** [cypress-io/cypress#27898]
### Current behavior

When video is enabled and all tests on a spec are skipped, we get the following error in standard output:

```
Warning: We failed capturing this video.

This error will not affect or change the exit code.

TimeoutError: operation timed out
    at afterTimeout (/Users/ryanm/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/Users/ryanm/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
```

### Desired behavior

In 12, we actually captured a video with no real information in this scenario but it didn't fail.

### Test code to reproduce

Any project really will work for this. Video needs to be enabled and a spec needs to have all tests skipped.

### Cypress Version

13.2.0

### Node version

v18.15.0

### Operating System

macOS 13.4.1

**Comment by karthivijay** [comment]
Facing the same issue with cypress 12.5.1. The video recording works fine with chrome but not with Firefox

**Comment by PvtSec** [comment]
# Its a 2 year old issue, and still not fixed
## [Video functionality is not working on Firefox 93 and above](https://github.com/cypress-io/cypress/issues/18415)

**Comment by jennifer-shehane** [comment]
@karthivijay Please see the [Firefox issue](https://github.com/cypress-io/cypress/issues/18415). This issue is only tracking the error on all browsers when all tests are skipped in a spec.

**Comment by pavel-blagodov** [comment]
I'm observing the same issue with electron and exactly same cypress version

**Comment by jennifer-shehane** [comment]
Just adding some insight here after some investigation. This can also be recreated by running a very short test as well as a spec where all tests are skipped (0 duration). 

```js
it("test", () => {
  expect(true).to.be.true
});
```

In this case, there are less frames being written to the video as shown below (only 1 frame written).

![Screen Shot 2023-12-07 at 5 32 44 PM (1)](https://github.com/cypress-io/cypress/assets/1271364/d62bffea-05d2-42da-9d5c-3d30ccee751c)

Compared to a run without this error shown (3 frames written)

![Screen Shot 2023-12-07 at 5 40 37 PM (1)](https://github.com/cypress-io/cypress/assets/1271364/4c92bb64-24fc-493a-9519-bf19879ca3a1)

When there are less than 2 frames written, these lines of code run: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/video_capture.ts#L135-L136 I would expect this would give a 3 sec timeout where more frames would be written then we can move on, but something isn't working at this point and causing the capture error. 

This error is occuring more often in v13 with `--record` as opposed to on v12 or without `--record` because we made a change in v13 to automatically hide the Runner UI when recording to the Cloud (`--no-runner-ui`) in order to speed up test runs. This does indeed speed up the test run! And it makes the tests that were previously not seeing this error now see this error because they're running so quickly. 

Unfortunately hitting this capture error seems to take time in itself, so we have seen an increase in runtime when this error state is hit, which could cause tests to run slower. I saw this as a few seconds testing locally, but had seen this on another user's run as taking more than 30 seconds.
