### ISSUE TITLE
Ability to Rerun only failing specs of previous execution

### ISSUE THREAD

**Issue by SwardCoder** [cypress-io/cypress#27905]
### What would you like?

Providing the Ability of Rerun to only Failing test cases of Previous Execution will help us a 
as doing it manually will be time time-consuming process as we need to collect names/paths of failing specs and we should be able to run them manually by using --spec command

at least if this facility is provided in paid subscriptions it will be more useful in saving infrastructure costs to run test cases

We have a situation to run 500 specs and it takes around 4 hrs to complete when using 6 VMs in Archestrization finally if we find any failing test cases (which are not flaky test failures) for example 50
then we will ask Developers to fix them and then instead of spending 4 hours again we will run only these 50 instead, 

if Cypress provides this facility by saving the details of failing specs in Memory and upon second execution if it prompts do you want to run only failures of the previous run and if it Executes it helps us 

Maybe it's not in the scope of Cypress Cloud but yes it can send some output kind of thing to CI/CD surely this kind of feature will help us

**Comment by ryanpei** [comment]
@SwardCoder which CI are you using?

Also, please look into [Spec Prioritization](https://docs.cypress.io/guides/cloud/smart-orchestration/spec-prioritization) and [Auto Cancellation](https://docs.cypress.io/guides/cloud/smart-orchestration/run-cancellation). Used together, they ensure that, on the next run, the failed specs will run first and then, depending on your Auto Cancellation threshold, the run stops after X failures. This way, you can ensure that you're only going to see the whole test suite run again once the failures are fixed. And you do want to make sure no other tests were failed because of the "fix", so it's recommended to re-run everything at the end anyway.
