### ISSUE TITLE
AppData folder is not updated with latest feature files from my Cypress Project

### ISSUE THREAD

**Issue by bheemaanilconvex** [cypress-io/cypress#27925]
### Current behavior

Keep getting below error, after following this https://docs.cypress.io/guides/references/troubleshooting#To-clear-App-Data
```
Error: ENOENT: no such file or directory, stat '~/Library/Application Support/Cypress/cy/production/projects/TCOE-32cd53e2f73cb94c71290e24d040df1f/bundles/cypress/test/inRisk/features/package-declaration-insurance.feature
```

Using Cypress 13.2.0

did all possible options
```
rm -rf node_modules
npm cache clean --force
rm package-lock.json
```
restarted  the machines

Still getting above error

a

### Test code to reproduce

Delete the appData folder from cypress, how to restore 

Keep getting below error, after following this https://docs.cypress.io/guides/references/troubleshooting#To-clear-App-Data
```
Error: ENOENT: no such file or directory, stat '~/Library/Application Support/Cypress/cy/production/projects/TCOE-32cd53e2f73cb94c71290e24d040df1f/bundles/cypress/test/inRisk/features/package-declaration-insurance.feature
```

Using Cypress 13.2.0

did all possible options
```
rm -rf node_modules
npm cache clean --force
rm package-lock.json
```
restarted  the machines

### Cypress Version

13.3.0

### Node version

v20.5.0

### Operating System

Mac os 13.6

**Comment by jennifer-shehane** [comment]
I'm not aware of where this message would be coming from. It looks like you may be using a cucumber plugin, so maybe it's trying to read this feature file?

**Comment by erick9025** [comment]
Were you able to solve it? i am having the exact same issue and still not able to fix it

**Comment by juan-belmonte** [comment]
I faced that error yesterday when upgrading the old `gherkin` NPM dependency to `@cucumber/gherkin` among other required updates.
I found that an error was thrown when pre-processing the `.feature` files, preventing the generation of build artifacts in the application data folder. Once I solved the error, the files were built and everything went back to normal.

In my case, [I had to downgrade](https://github.com/bahmutov/cypress-esbuild-preprocessor?tab=readme-ov-file#esbuild-version-support) `@bahmutov/cypress-esbuild-preprocessor` to `<2.2.0` because there was a conflict with nested dependencies resulting in this error: evanw/esbuild/issues/2841
