### ISSUE TITLE
after:run - results lost results.status (v13.2) 

### ISSUE THREAD

**Issue by DevYimo** [cypress-io/cypress#27926]
### Current behavior

With new v13 after:run results lost its status property (results.status === 'finished')
 - is it intentional? I could not find any reason/issue why it was silently removed

Maybe it is not bug?

Thank you :)

### Desired behavior

results should have 'status' or smth equivalent?

### Test code to reproduce

1. Run any test
2. in config - on('after:run', results)
3. results had? property 'status'
4. There is nothing like 'status' property

### Cypress Version

13.2

### Node version

18.12.0

### Operating System

Ubuntu

**Comment by jennifer-shehane** [comment]
@DevYimo Can you explain what you were using the results.status = finished property for? 

We worked in 13.0 to normalize results, and this property did not seem necessary because at the point that this is run it would always be finished - there are results or there aren't results. It seemed like a redundant check.

**Comment by DevYimo** [comment]
I just ensured with it, that process is "finished", that's all. 
So if it is guaranteed, when there are results, it's finished. I'm ok with that :)
