### ISSUE TITLE
Works in Electron but hangs when using Chrome and Firefox

### ISSUE THREAD

**Issue by danielcamargo** [cypress-io/cypress#27939]
### Description

I've created a very simple e2e test for the login page. The issue is that the test only works in Electron.

### URL of Issue(s)

http://localhost:8080

### Steps to replicate

![nuxeo-cypress](https://github.com/cypress-io/cypress-documentation/assets/4071288/90dbf5d9-1b3e-41b5-b240-63f2481c82ed)

### Browser

Chrome 117, Electron 114

### Device

- [ ] PC
- [X] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

```js
// cypress/e2e/spec.cy.js
describe('template spec', () => {
    it('passes', () => {
        cy.visit('http://localhost:8080');
        cy.get('.idItem > a').click();
        cy.get('#username').type('Administrator');
        cy.get('#password').type('Nuxeo20!9'); // silly password for my local env only
        cy.get('#login_button').click();
    })
})
```

Terminal Logs for **Chrome 117**

```
GET /__cypress/iframes/cypress%2Fe2e%2Fspec.cy.js?browserFamily=chromium 200 1.276 ms - -
GET /__cypress/tests?p=cypress/e2e/spec.cy.js 200 1.159 ms - -
GET /__cypress/tests?p=cypress/support/e2e.js 200 1.816 ms - -
GET / 200 2.975 ms - -
GET /nuxeo 302 2.817 ms - 58
GET /nuxeo/ 302 8.332 ms - 106
GET /nuxeo/ui/ 401 4.286 ms - -
GET /nuxeo/login.jsp?requestedUrl=ui%2F 200 18.871 ms - -
POST /nuxeo/startup 302 147.118 ms - 106
GET /nuxeo/ui/ 200 7.299 ms - -
GET /nuxeo/ui/config.jsp 200 97.572 ms - -
GET /nuxeo/json/cmis 200 13.198 ms - -
POST /nuxeo/api/v1/automation/login 200 3.081 ms - -
GET /nuxeo/api/v1/user/Administrator 200 12.654 ms - -
GET /nuxeo/ui/sw.js?ts=1695750496935 304 514.260 ms - -
GET /nuxeo/ui/workbox/workbox-sw.js 304 506.556 ms - -
GET /nuxeo/ui/sw.js?ts=1695750496935 304 512.514 ms - -
GET /nuxeo/ui/workbox/workbox-sw.js 304 507.320 ms - -
```

Terminal Logs for **Electron 114**

```
GET /__cypress/iframes/cypress%2Fe2e%2Fspec.cy.js?browserFamily=chromium 200 0.973 ms - -
GET /__cypress/tests?p=cypress/e2e/spec.cy.js 200 0.933 ms - -
GET /__cypress/tests?p=cypress/support/e2e.js 200 1.944 ms - -
GET / 200 2.175 ms - -
GET /nuxeo 302 3.065 ms - 58
GET /nuxeo/ 302 6.713 ms - 106
GET /nuxeo/ui/ 401 6.641 ms - -
GET /nuxeo/login.jsp?requestedUrl=ui%2F 200 5.644 ms - -
POST /nuxeo/startup 302 26.366 ms - 106
GET /nuxeo/ui/ 200 12.532 ms - -
GET /nuxeo/ui/config.jsp 200 129.543 ms - -
HEAD /nuxeo/ui/themes/default/theme.html 200 4.471 ms - -
GET /nuxeo/json/cmis 200 54.580 ms - -
POST /nuxeo/api/v1/automation/login 200 4.310 ms - -
GET /nuxeo/api/v1/user/Administrator 200 189.781 ms - -
POST /nuxeo/api/v1/automation/NuxeoDrive.GetRoots 200 7.677 ms - -
GET /nuxeo/api/v1/task?currentPageIndex=0&pageSize=1&userId=Administrator 200 45.092 ms - -
POST /nuxeo/api/v1/automation/User.GetUserWorkspace 200 109.918 ms - -
GET /nuxeo/ui/sw.js?ts=1695750496935 304 505.312 ms - -
GET /nuxeo/api/v1/path/default-domain/MasterData/Notifications/Notification 200 73.951 ms - -
GET /nuxeo/api/v1/search/pp/gvl_pp/execute?currentPageIndex=0&pageSize=40 200 26.750 ms - -
GET /nuxeo/api/v1/search/pp/stockSearch_pp/execute?currentPageIndex=0&pageSize=40 200 30.499 ms - -
GET /nuxeo/api/v1/search/saved?pageProvider=gvl_pp 200 63.946 ms - -
GET /nuxeo/api/v1/search/saved?pageProvider=stockSearch_pp 200 61.803 ms - -
GET /nuxeo/api/v1/search/pp/scriptureReference_pp/execute?currentPageIndex=0&pageSize=40 200 10.283 ms - -
GET /nuxeo/api/v1/search/saved?pageProvider=productionAssetsSearch_pp 200 85.922 ms - -
GET /nuxeo/api/v1/token?application=Nuxeo%20Drive 200 21.839 ms - -
GET /nuxeo/api/v1/search/saved?pageProvider=scriptureReference_pp 200 39.501 ms - -
GET /nuxeo/api/v1/search/pp/productionAssetsSearch_pp/execute?currentPageIndex=0&pageSize=40 200 196.928 ms - -
GET /nuxeo/api/v1/task?currentPageIndex=0&offset=0&pageSize=16&userId=Administrator 200 74.969 ms - -
GET /nuxeo/ui/workbox/workbox-sw.js 304 508.175 ms - -
POST /nuxeo/api/v1/automation/Favorite.Fetch 200 125.947 ms - -
GET /nuxeo/api/v1/search/pp/domain_documents/execute?currentPageIndex=0&offset=0&pageSize=16&queryParams=%2F 200 139.121 ms - -
GET /nuxeo/api/v1/path/ 200 11.965 ms - -
GET /nuxeo/api/v1/search/pp/default_content_collection/execute?currentPageIndex=0&offset=0&pageSize=16&queryParams=bef63beb-7509-4767-bf91-7ed54e5b6283 200 22.250 ms - -
GET /nuxeo/api/v1/search/pp/nxql_search/execute?currentPageIndex=0&pageSize=20&queryParams=SELECT%20*%20FROM%20Document%20WHERE%20ecm%3AparentId%20%3D%20%2700000000-0000-0000-0000-000000000000%27%20AND%20ecm%3AmixinType%20%3D%20%27Folderish%27%20AND%20ecm%3AmixinType%20!%3D%20%27HiddenInNavigation%27%20AND%20ecm%3AisVersion%20%3D%200%20AND%20ecm%3AisTrashed%20%3D%200 200 50.276 ms - -
GET /es2020/userflow.js?ts=1695750496935 200 615.142 ms - -
GET /es2020/flow-condition-types.95a68e08.js?ts=1695750496935 200 538.300 ms - -
GET /es2020/z-index.3189a525.js?ts=1695750496935 200 558.728 ms - -
GET /es2020/index.7d3437e2.js?ts=1695750496935 200 554.882 ms - -
GET /es2020/ResourceCenterApp.87f1ec4b.js?ts=1695750496935 200 569.189 ms - -
GET /es2020/BubbleToolbar.a0340e00.js?ts=1695750496935 200 570.212 ms - -
GET /es2020/ui.9c8f1fd3.js?ts=1695750496935 200 584.371 ms - -
GET /es2020/stylesheets.f23f55c3.js?ts=1695750496935 200 544.305 ms - -
GET /es2020/logomark.9bde6266.js?ts=1695750496935 200 560.344 ms - -
GET /es2020/ChecklistUI.c151c139.js?ts=1695750496935 200 565.134 ms - -
GET /es2020/Trigger.cc553eba.js?ts=1695750496935 200 556.815 ms - -
GET /es2020/LauncherApp.52884b06.js?ts=1695750496935 200 565.169 ms - -
GET /es2020/FlowChrome.7a810f94.js?ts=1695750496935 200 564.828 ms - -
GET /es2020/flow-host.f1352f71.css 200 34.154 ms - -
GET /es2020/bubble-frame.aaec9943.css 200 32.552 ms - -
GET /es2020/iframe-reset.3b2212c0.css 200 35.288 ms - -
GET /nuxeo/ui/sw.js?ts=1695750496935 304 514.421 ms - -
GET /nuxeo/ui/workbox/workbox-sw.js 304 512.067 ms - -
```

**Comment by AdrianBesleaga** [comment]
I can still reproduce this bug in the last version of Cypress. Nuxeo UI is based on Polymer, it's strange that it works fine in Electron but fails with Chrome

**Comment by AdrianBesleaga** [comment]
```js  
e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
      on('before:browser:launch', (browser = {}, launchOptions) => {
        if (browser.family === 'chromium' && browser.name !== 'electron') {
          // Disables the use of the automation extension
          launchOptions.args.push('--disable-blink-features=AutomationControlled');
```

The bug is not related to Cypress, can be reproduced with Selenium too. I fixed it by adding this parameter --disable-blink-features=AutomationControlled

**Comment by jennifer-shehane** [comment]
@AdrianBesleaga Could you provide a way to reproduce the original issue? I'd love to get a fix in with a test that verifies this flag fixes it.

**Comment by jennifer-shehane** [comment]
### The Problem

I had an example provided via email and am able to demonstrate a simple example of a websites behavior being different in Electron vs Chrome/Firefox if the website has logic that changes it's behavior based on the value of the `navigator.webdriver` value (which this website did as shown in the screenshot). 

![Screenshot 2024-04-30 at 9 38 33 AM](https://github.com/cypress-io/cypress/assets/1271364/69c0be37-5ef7-4807-95f7-7a62f36c1304)

`index.html`
```html
<html>
<body>
  <h1 id="content"></h1>
  <script>
    console.log(navigator.webdriver);
    var text = document.createTextNode(`navigator.webdriver is ${!!navigator.webdriver}`);
    document.getElementById("content").append(text);
  </script>
</body>
</html>
```

`test.cy.js`
```js
it('visit', () => {
  cy.visit('index.html')
  cy.get('#content').should('have.text', 'navigator.webdriver is false')
})
```

The example above, when not within Cypress in a regular browser displays as shown below. The `navigator.webdriver` value is `false`.

![Screenshot 2024-04-30 at 9 56 55 AM](https://github.com/cypress-io/cypress/assets/1271364/6efd11aa-7037-4dba-a5e9-0fc79495d684)


The example above will fail in Chrome/Firefox within Cypress, but pass in Electron within Cypress. 

Electron
![Screenshot 2024-04-30 at 9 57 35 AM](https://github.com/cypress-io/cypress/assets/1271364/b23d5a5f-5ad9-4767-8fc9-24c03eb901f1)

Chrome
![Screenshot 2024-04-30 at 9 55 11 AM](https://github.com/cypress-io/cypress/assets/1271364/56180666-605c-44fb-966e-c6404745ea20)

### Workaround

**There is no known workaround for this in Firefox.** I don't think they allow this at all based on [this thread](https://github.com/mozilla/geckodriver/issues/1680). 

If we pass the `--disable-blink-features=AutomationControlled` through Chrome's launch args, the example will pass within Chrome. 

```js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    setupNodeEvents(on, config) {
      on('before:browser:launch', (browser = {}, launchOptions) => {
        if (browser.family === 'chromium' && browser.name !== 'electron') {
          // Disables the use of the automation extension
        }
        return launchOptions
      })
  }
  }
});
```

### Why?

Chrome has logic to determine whether to set the [`navigator.webdriver`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver) value to `true`. Basically they set it when the browser is automated. [webdriver w3c docs](https://w3c.github.io/webdriver/#interface).

They check some specific flags to determine this [here](https://source.chromium.org/chromium/chromium/src/+/main:content/child/runtime_features.cc;l=466?q=tent%2Fchild%2Fruntime_features.cc&ss=chromium%2Fchromium%2Fsrc). If you pass:
- `--headless` (we pass that [here](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/chrome.ts#L431) unless explicitly turned off during `cypress run`)
- `--enable-automation` (we pass that [here](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/chrome.ts#L83))
- `--remote-debugging-pipe` (we do not set this)
- If `--remote-debugging-port` is set to `0`. We [set this to a specific port](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/chrome.ts#L445), so this should be affecting things (unless it somehow is on port 0 which some sets?)

Firefox checks for the `marionette.enabled` preference or `--marionette` flag according to [MDN docs.](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver) 

Maybe [some interesting ways](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/inspector-protocol/emulation/set-automation-override.js;l=5?q=navigator.webdriver&ss=chromium%2Fchromium%2Fsrc&start=11) Chrome enables/disables it for reference. 

### What should we do?

I think the worst part of this behavior is that Cypress runs differently in different browsers. Since there is no workaround for Firefox and the w3c defines that when a browser is automated that it must have the `navigator.webdriver` value as `true`, I'm inclined to think that we should also correctly have `navigator.webdriver` as `true` in Electron. 

But, this means sites that want to prevent automated bots from running on them just won't work in Cypress. That's what they coded the site to do though. I think they'd have to set that logic differently if they actually do want it to run within Cypress. 

```
if (window.Cypress) {
  // don't add the logic to act differently with `navigator.webdriver`
} else {
  // do add the logic to act differently with `navigator.webdriver` as `true`
}
```
