### ISSUE TITLE
Move CircleCI Gen2 resources to MacStadium Intel Mac Mini

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#28033]
### What would you like?

[CircleCI's announcement](https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718?mkt_tok=NDg1LVpNSC02MjYAAAGNzIE9JKs7lQUAbEHjfO1sLpj412zKrQp01dqd7m-QODPrCuvuik1z9SgHLQqqAfn2tcr9NuhoepbNGp_U4NvxkdfJysL_15ZncE_OW-OfErkjAQ)

>We will also be deprecating our Dedicated Hosts at this time. In January 2024, we will deprecate our Gen2 resources, ending our support for all Intel-based macOS resources. Jobs still calling these resource classes after this will fail with an Invalid resource class error.

31 January 2024
- Gen2 (macos.x86.medium.gen2)
- Xcode 15.1 is the last supported version for Gen2

We will be porting over our Gen2 CircleCI jobs to a MacStadium Mac Mini provisioned machine. This decision has to do with the need to build the binary on `darwinx64`. Building a composite binary doubles the size of the macOS binary so we are unable to build both on M1. CircleCI will only offer M1 macOS resources and we already leverage an M1 Macstadium runner for our binary process, which makes this path likely the one of least resistance and most effective.

### Why is this needed?

Our runs will fail starting 28 June 2024 if we don't update these.

**Comment by emilyrohrbough** [comment]
@jennifer-shehane CircleCi has an updated their statement that the sunsetting of Intel resources is now June 28, 2024.

**Comment by emilyrohrbough** [comment]
@AtofStryker's prev work on upgrading: https://github.com/cypress-io/cypress/pull/27319

Evaluation: https://docs.google.com/document/d/1YHDs7Y4aI7WAbHrnUWnF89fhWdwHRuUNlRPPpPza1-M/edit?usp=sharing

**Comment by AtofStryker** [comment]
It looks like the [workaround](https://support.circleci.com/hc/en-us/articles/19334402064027-Troubleshooting-slow-uploads-to-S3-for-jobs-using-an-m1-macOS-resource-class) that circle provided in October does work for the extremely slow S3 uploads using their m1 macOS images (due to the virtualization framework used under the hood). I was able to add in the updates and get a [passing build](https://app.circleci.com/pipelines/github/cypress-io/cypress/59094), so it at least means moving `darwin-arm64` off the macstadium box and onto hosted circle runners is technically unblocked. Here is the [branch](https://github.com/cypress-io/cypress/compare/chore/circle_ci_m1?expand=1) (also updates the s3 client).

We would still need to figure out what to do with the intel based jobs to build the intel binary, but this at least might give us options.

**Comment by AtofStryker** [comment]
This issue has pivoted from migrated our M1 resources to Circle CI hosted runners to migrating our Intel Circle CI hosted runner jobs to MacStadium due to the sunsetting of Intel based Mac resources by Circle CI.
