### ISSUE TITLE
Support mocking of iframe document response

### ISSUE THREAD

**Issue by olofd** [cypress-io/cypress#2818]
With ```cy.route``` it seems like document responses (GET-document requests) can not be mocked/replaced with fixture.

The use case is for having an foreign iframe embedded on our site and wanting to test our interaction with that iframe. But I can not reliably run the foreign iframe document in our tests.

It would be nice if (at least for relative paths, aka own domain) these responses could me mocked in cypress. If that's already possible with  ```cy.route```, please let me know.

**Comment by chrisbreiding** [comment]
Currently, `cy.route` can only mock XHR requests, but we [plan to add broader support for mocking any type of request in the future](https://github.com/cypress-io/cypress/issues/687).

**Comment by jennifer-shehane** [comment]
The features requested in this issue are now possible as part of `cy.route2()`. 

`cy.route2()` is currently experimental and requires being enabled by passing `"experimentalNetworkStubbing": true` through your Cypress configuration. This will eventually be merged in as part of our standard API. 

**Please see the `cy.route2()` docs for full details: https://on.cypress.io/route2**

If you encounter any issues or unexpected behavior while using `cy.route2()` we encourage you to [open a new issue](https://github.com/cypress-io/cypress/issues/new?assignees=&labels=&template=bug-report.md&title=) so that we can work out all the issues before public release. Thanks!
