### ISSUE TITLE
Launchpad opening when running in e2e mode

### ISSUE THREAD

**Issue by Wulfheart** [cypress-io/cypress#28313]
### Current behavior

Some posts (e.g. [here](https://github.com/cypress-io/cypress/issues/22152#issuecomment-1149498178) and [here](https://www.linkedin.com/pulse/why-i-use-cypress-automated-testing-julia-casciato/)) suggest that when running `npx cypress open --e2e --browser chrome` it does not open the [launchpad](https://docs.cypress.io/guides/getting-started/opening-the-app) (that electron window). However, for me it opens the launchpad AND the browser. 

### Desired behavior

I would like to just open the browser, not that launchpad.

### Test code to reproduce

`npx cypress open --e2e --browser chrome`

### Cypress Version

13.5.0

### Node version

18.5.0 (bundled), 18.6.0 (OS)

### Operating System

Pop!_OS 22.04 LTS

### Debug Logs

```shell
https://gist.github.com/Wulfheart/80d743585cae06d6c017b503b6aa31cf
```

### Other

Pop!_OS 22.04 LTS 64 bit
Gnome 42.9 - X11

**Comment by jennifer-shehane** [comment]
@Wulfheart There's no current way to skip launching the launchpad from launching entirely. It handles a lot of the logic in the background and also needs to be there to display errors in the case of failures. (If your config becomes invalid, for example - it will show a display here since the browser has to relaunch).

**Comment by Wulfheart** [comment]
Unfortunate. Thanks for the response.
