### ISSUE TITLE
cy.get(selector).clear().type('some text') does not fully clear the text in input field

### ISSUE THREAD

**Issue by ismailamranimr** [cypress-io/cypress#28375]
### Current behavior

cy.get('#fsp-name').clear().type('random text');
If the text already has value lets say 'xyza' and I perform above command I get something similar to 'random textxyza'

I also tried this workaround proposed in this discussion https://github.com/cypress-io/cypress/issues/4937 but it doesn't work

This causes a lot of flakiness in our project, can we figure out for a solution to this issue.

### Desired behavior

Input field should be cleared properly

### Test code to reproduce

(app code and test code)

### Cypress Version

13.5.1

### Node version

18.18.2

### Operating System

Ubuntu 22.04.3

**Comment by Crustum7** [comment]
Hello @ismailamranimr! I've looked in to this a bit and found that "non-query" commands should not be chained according to https://docs.cypress.io/guides/core-concepts/retry-ability#Only-queries-are-retried. You should therefore split the chain into separate statements in general. The suggestion is quite difficult to fix because the clear command depends on how fast the page is loaded. What seems to work is waiting before doing anything like so:
```javascript
// This might be set to different numbers depending on the current environment
// CI pipelines might get more time for example
cy.wait(1000)
cy.get('#fsp-name').as('elem')
cy.get('@elem').clear()
cy.get('@elem').should('be.empty')
cy.get('@elem').type('random text')
cy.get('@elem').should('have.value', 'random text')
```
Otherwise you could make some sort of solution similar to https://www.cypress.io/blog/2018/02/05/when-can-the-test-start but using logic specific to your application to find when the page has been loaded.
