### ISSUE TITLE
Running lighthouse in Cypress stops working after upgrade to v. 13.5.0

### ISSUE THREAD

**Issue by basiaBB** [cypress-io/cypress#28430]
### Current behavior

**Cypress-audit/lighthouse version:** 1.4.2

After upgrading Cypress to version 13.5.0 when lighthouse opens new tab there is an issue that `Cannot GET /xyz`. In console I can see 404 for it. For version 13.4.0 it works properly.

### Desired behavior

Cypress Lighthouse properly open app in the new tab and run performance audit.

### Test code to reproduce

cy.lighthouse(thresholds, options, config)

### Cypress Version

13.5.0

### Node version

18.16.0

### Operating System

macOS 14.1.1

**Comment by jennifer-shehane** [comment]
@basiaBB What are you running that defines the cy.lighthouse command?

My guess is that it's related to our changes to how tabs work and preventing traffic from other tabs, since that's another case of lighthouse we saw stop working. More context here: https://github.com/cypress-io/cypress/discussions/28337

You might find utility in using the cypress/puppeteer plugin to accomplish something similar: https://github.com/cypress-io/cypress/tree/develop/npm/puppeteer

**Comment by basiaBB** [comment]
@jennifer-shehane I am using `@cypress-audit/lighthouse/commands` for that.

**Comment by basiaBB** [comment]
Hi @jennifer-shehane, any update here? Do you need any more information?

**Comment by jennifer-shehane** [comment]
The cypress-audit plugin will need to update their side to appropriately run Lighthouse tests given the recent changes to Cypress with traffic across tabs: explained here: https://github.com/cypress-io/cypress/discussions/28337#discussioncomment-7634516

**Comment by jennifer-shehane** [comment]
We made some changes in our more recent version of Cypress, 13.6.5, to back out of some of this behavior, so I'm kind of curious if this is now working again.
