### ISSUE TITLE
Chrome v120 - Cypress run -  baseUrl - http issue

### ISSUE THREAD

**Issue by JohnnyTheBoy** [cypress-io/cypress#28480]
### Current behavior

After Chrome updated to v120, cypress run is not working correctly. 
Base URL contains HTTP and after cypress run, chrome forces it to HTTPS for some reason. 
Even If I set chromeWebSecurity to false and experimentalModifyObstructiveThirdPartyCode to true, it doesn't work. 
Everything worked well with previous version of Chrome.

Cypress verison 13.6.1
Node version: 20.10.0
Chrome verison: 120.0.6099.71

### Desired behavior

http should not be overridden with https by chrome

### Test code to reproduce

I'll try to add some soon

### Cypress Version

13.6.1

### Node version

v20.10.0

### Operating System

Windows 11

**Comment by Ollisteka** [comment]
Getting the same behaviour on Windows 10, with chrome 119 and cypress `10.10.0`

**Comment by jennifer-shehane** [comment]
@JohnnyTheBoy This is Chrome's default behavior now. See Chrome's blog post on HTTPS by default. https://blog.chromium.org/2023/08/towards-https-by-default.html

There is a situation in Cypress where this could cause an infinite loop. See this issue if you're encountering it: https://github.com/cypress-io/cypress/issues/25891

If your website offers https, I would suggest visting the https URL instead of the http URL.

Outside of the issue above, I'd like to understand how this behavior is disruptive to your tests and what Cypress has under its control in this regard. Please describe if this is an issue outside of the change in Chrome's behavior.

**Comment by jennifer-shehane** [comment]
Closing since there's nothing we can do in this case.
