### ISSUE TITLE
Default blank page issue

### ISSUE THREAD

**Issue by rdwentmp** [cypress-io/cypress#28510]
### Current behavior

During Cypress run the application page disappear and appear default blank page, after that test scenario fail with visibility of inputs. The issue occur randomly on different test scenarios, possibly some memory leak. 
The Default blank page errors start to occur after upgrade Cypress version from 11.2.0 to 13.0.0

![image](https://github.com/cypress-io/cypress/assets/33515840/00f06479-867c-40a9-92f1-693ead9d7855)

<img width="1672" alt="image" src="https://github.com/cypress-io/cypress/assets/33515840/743d404b-4fcd-49ca-8048-0a70918d8b51">

### Desired behavior

Cypress behave stable without clearing cache with appearing Default blank page

### Test code to reproduce

The issue occur randomly on different test scenarios, possibly some memory leak

### Cypress Version

13.0.0

### Node version

v14.21.3

### Operating System

linux, macbook

### Debug Logs

```shell
{
  "specName": "cypress%2Fe2e%2Factivities-tab%2Fadd-assumptions-additional-activity.spec.ts",
  "title": "Owner should add assumption for added equipment",
  "suiteName": "Add assumptions for additional activity",
  "testName": "add-assumptions-additional-activity Add assumptions for additional activity Owner should add assumption for added equipment",
  "testError": "Timed out retrying after 20000ms: Expected to find element: `[formcontrolname=assumptions]`, but never found it.",
  "testCommands": [
    "get [formcontrolname=assumptions]",
    "log \n            ⚠️ Could not find any coverage information in your application\n            by looking at the window coverage object.\n            Did you forget to instrument your application?\n            See [code-coverage#instrument-your-application](https://github.com/cypress-io/code-coverage#instrument-your-application)\n           `[@cypress/code-coverage]`"
  ]
}
```

**Comment by jennifer-shehane** [comment]
@rdwentmp The introduction of clearing state between tests with the default blank page was intentional in 12.0. Please refer to the changelog and migration guide to understand the changes necessary to upgrade: https://docs.cypress.io/guides/references/changelog#12-0-0

**Comment by rdwentmp** [comment]
@jennifer-shehane I forgot to mention that I already set up migration guide  and had to set up testIsolation: false, without that every test occur with default blank page, but still after done everything right the default blank page still occur.
Why the issue is already closed?

**Comment by rdwentmp** [comment]
Is there any chance to consider this behaviour as a bug?

**Comment by AdamDSherman** [comment]
Just posting a solution I found for this after scratching my head for a day:

I had retries (in cypress.config.js) set to 1 for my test suite:
```
  retries: {
    runMode: 1,
    openMode: 0
  },
```
and my last test step happened to fail for normal reasons. 

As far as I understand, Cypress was running my last test step and it would fail. Cypress would then attempt to re-run the test step **BUT** also continue onto the next test spec file, opening the blank page to clear the cache (as @jennifer-shehane mentioned it does above). So, the test step was re-running again but failing as it was unable to query the blank page."

Changing the retries to 0 (` runMode: 0,`) solved the issue for me, though I no longer have test reruns obviously.

@eugenet8k discusses issue here https://github.com/cypress-io/cypress/issues/28527#issuecomment-2570037962

I'm using 13.14.1 but this appears to have been fixed in later versions: https://github.com/cypress-io/cypress/pull/30864
