### ISSUE TITLE
Run specs in parallel offline

### ISSUE THREAD

**Issue by jpike88** [cypress-io/cypress#2856]
I run our tests in a totally isolated environment, cut off from the internet. I need a way to parallelise my tests in this way.

Suggestions?

**Comment by amirrustam** [comment]
Our current Parallelization feature does not function offline as the Dashboard service handles optimal load balancing of spec files across available compute resources. 

There is no good suggestion here, but you could spread your spec files via CI configuration (hard-code) to specific machines. For example:
- **Machine 1** is assigned *a.spec.js, b.spec.js, c.spec.js* in your CI config.
- **Machine 2** is assigned *d.spec.js, e.spec.js, f.spec.js* in your CI config.

> You can use the [`--spec` flag ](https://docs.cypress.io/guides/guides/command-line.html#cypress-run-spec-lt-spec-gt) to specify spec files.

You would essentially be executing multiple *unassociated* Cypress runs.
With that said, **this is not a recommendation, and it is not efficient or optimal**. It also assumes that:
- You have multiple spec files
- Tests do not depend on each other

I'm assuming you run off-the-grid due to security concerns. If so, we would like learn about your concerns, so please do share if possible. Maybe we can remedy some of those concerns.

**Comment by bahmutov** [comment]
Or you can use a little helper to generate your CI config file based on specs to have 1 CI job per spec file and let your CI (if it allows) load balance them. This utility for example writes a GitLab test file https://github.com/kensho/multi-cypress but you could do the same for other CIs
