### ISSUE TITLE
Using contenteditable and click, caret always move to the end of text

### ISSUE THREAD

**Issue by Jiongzhi** [cypress-io/cypress#2857]
### Current behavior:
![cypressbug](https://user-images.githubusercontent.com/16207345/49213166-990fea80-f3fe-11e8-8a04-49cd16e9efc4.gif)

### Desired behavior:
caret move to the correct position

### Steps to reproduce:
**a simple page**
```html
<body>
    <div id="test" contenteditable="true" style="height:200px; width: 200px; border: 1px solid black; white-space: pre">
        1111111111
        2222222222
        3333333333
    </div>
</body>
```
**cypress code:**
```js
    cy.wait(2000);
    cy.get('#test').click(60, 45)
```

it seems like  that function `$selection.moveSelectionToEnd(el)`  is always called when click a contenteditable element
[cypress/packages/driver/src/cy/commands/actions/click.coffee ](url)

### Versions
Operating System: windows10
Cypress Version: 3.1.2
Browser Version: Chrome 70.0.3538.110

**Comment by Bkucera** [comment]
@Jiongzhi yes, in all text-editables we move the cursor the end on `click`. This is to standardize the behaviors of all text-editable fields (input, textarea, contenteditable).

This makes more sense if you think about a `click` without specified coords, because the user behavior is undefined. However we have not implemented the cursor moving to arbitrary positions.

You can still use `{uparrow}`, `{downarrow}`, `{leftarrow}`, and `{rightarrow}` to position the cursor, or you can move to the beginning with `cy.get('#text').focus()`

**Comment by Tohaker** [comment]
Is there any chance this behaviour can be toggled? I need to test a touchscreen kiosk application that doesn't have a keyboard, so the only use case for my text boxes are people tapping the box to move the caret. I'd rather not implement keydown events just for the purposes of testing.

**Comment by Bkucera** [comment]
@Tohaker currently, you'll have to just use `.focus()` on the contenteditable or textarea. I would welcome an issue to give an option to `cy.click()` with `cursorPosition: 'start'` or something.

**Comment by Wilt** [comment]
@kuceb Thanks for mentioning `{moveToStart}` here, that is a very elegant solution. You mentioned it isn't documented, but I actually found it is [here at the `type` command under Arguments](https://docs.cypress.io/api/commands/type#Arguments).
