### ISSUE TITLE
Clicking nested element in disabled button invokes button's onclick handler

### ISSUE THREAD

**Issue by nils4cosee** [cypress-io/cypress#28788]
### Current behavior

When "clicking" a nested element of a disabled button, the onclick-handler of this button is run (in Chrome or Firefox, not in Electron)

```html
<body>
    <button disabled onclick="document.querySelector('div').innerText = 'Button clicked'">
        <span>Click me</span>
    </button>
    <div>

    </div>
</body>
</html>
```

Test: 

```javascript
it("does not invoke the onclick handler of a disabled parent button", () => {
    cy.visit("index.html")
    cy.contains("span", "Click me").click()
    cy.contains("Button clicked").should('not.exist')
})
```

![image](https://github.com/cypress-io/cypress/assets/54022132/af3a3209-02d9-491b-80c3-9ce71b91b459)

### Desired behavior

The behavior of 

```js
cy.contains("span", "Click me").click()
```

should be the same as 

```js
cy.contains("button", "Click me").click()
```

it only runs the onclick-handler if the button is not disabled and also waits for the button to be not disabled anymore.

### Test code to reproduce

See my repo with the code https://github.com/nils4cosee/cypress-click-span-in-disabled-button

### Cypress Version

13.6.1

### Node version

18.15.0

### Operating System

macOS 13.6

### Debug Logs

```shell
Output of 


DEBUG=cypress:* npm run cypress:run -- --browser chrome --headless >debug.log 2>&1
```

is too long, according to GitHub. Please tell me if you really need it
```


### Other

_No response_

**Comment by jennifer-shehane** [comment]
@nils4cosee Thank you for the clear reproducible example. This is surely a bug. We're open to a pull request to fix this. This bug is in the cypress/packages/driver package within this repo. 

I feel like the logic may be in the `mouse.ts` logic? https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/mouse.ts 

cy.click logic is defined here: https://github.com/cypress-io/cypress/blob/a11y-fixes-1/packages/driver/src/cy/commands/actions/click.ts#L259

A test case would be added here to test this new behavior.: https://github.com/cypress-io/cypress/blob/a11y-fixes-1/packages/driver/cypress/e2e/commands/actions/click.cy.js

**Comment by TheoAnastasiadis** [comment]
Apparently, disabled elements on Chrome do not prevent their children from firing `"click"` events. [see this codepen](https://codepen.io/teo_anastasiadis/pen/PoLOmmE).

Maybe it is because according to the HTML spec, ["actually disabled"](https://html.spec.whatwg.org/multipage/semantics-other.html#disabled-elements) elements can only ever be buttons, inputs, selects, textareas, options etc. ie. elements that **must not** have interactive content descendants. 

My idea would be to check if the mouse down or mouse up elements have an "actually disabled" parent, and skip the click command if they do. Will open a PR shortly.
