### ISSUE TITLE
cy.request: RequestBody type not aligned with RFC (e.g. boolean)

### ISSUE THREAD

**Issue by PeterRistMHP** [cypress-io/cypress#28789]
### Current behavior

I've stumbled on this problem while trying to send only a boolean in a `PUT` request. 

Currently the type for `RequestBody` is typed as `type RequestBody = string | object` [1].  However this doesn't align with the current RFC 8259 for allowed values in JSON [2]. 

[1] https://github.com/cypress-io/cypress/blob/develop/cli/types/cypress.d.ts#L10
[2] https://datatracker.ietf.org/doc/html/rfc8259#section-3

### Desired behavior

All values defined in the RFC should be accepted as valid values for the `body` in a `cy.request()`. 

### Test code to reproduce

`cy.request({
    method: "PUT",
    url: ANY_URL_HERE,
    body: true
})`

### Cypress Version

v13.16.1

### Node version

v20.10.0

### Operating System

macOS 14.2

**Comment by jennifer-shehane** [comment]
@PeterRistMHP That's fun. We'd be open to a pull request to fix the types.

**Comment by PeterRistMHP** [comment]
Hi @jennifer-shehane,

I'm afraid it's not only a type issue. I've changed the type, but sending the request with `body: true` crashes cypress with the following stacktrace: 

```
The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (true)
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (true)
    at new NodeError (node:internal/errors:399:5)
    at write_ (node:_http_outgoing:884:11)
    at ClientRequest.write (node:_http_outgoing:849:15)
    at ee.write (<embedded>:2050:109573)
    at e (<embedded>:2050:96908)
    at Immediate.<anonymous> (<embedded>:2050:97414)
    at process.processImmediate (node:internal/timers:476:21)
The Test Runner unexpectedly exited via a exit event with signal SIGABRT
```

I haven't found the source of this exception yet.

**Comment by TheoAnastasiadis** [comment]
This is a problem with the _@cypress/request-promise_ library. Indeed the JSON spec allows for boolean and null value literals so you should be able to use this as `cy.request('POST', 'https://example.com', true)`.

My idea for a fix would be to 
- change the [driver](https://github.com/cypress-io/cypress/tree/develop/packages/driver) so that it sets `json = true` in these cases.
- change the [server](https://github.com/cypress-io/cypress/tree/develop/packages/server) to convert boolean and null value literals to string as specified in [RFC 8259](https://datatracker.ietf.org/doc/html/rfc8259#section-3).
- fix the types of RequestOptions.

I can open a PR on this 😀
