### ISSUE TITLE
Cypress won't recognize cypress.config.ts Config file and won't load it. 

### ISSUE THREAD

**Issue by asoov** [cypress-io/cypress#28802]
### Current behavior

I install Cypress with the current version and add Typescript as is described in the documents here:  https://docs.cypress.io/guides/tooling/typescript-support

I'm using a cypress.config.ts and try to start the project with "cypress open". No matter what I do Cypress won't recognize my config file showing this error (TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\cypress-test-issue\cypress.config.ts): 
<img width="771" alt="image" src="https://github.com/cypress-io/cypress/assets/50890539/35afd067-ef06-4c0c-9f58-f9208c794022">

Cypress should recognize I'm using ESM because I use "type": "modules" in my package.json. However Cypress apparently doesn't use ts-node to load my config file at all.  

 

### Desired behavior

It should work and open Cypress. 

### Test code to reproduce

https://github.com/asoov/cypress-ts-support-issue 

### Cypress Version

13.6.3

### Node version

v18.18.2

### Operating System

Windows 11

**Comment by jennifer-shehane** [comment]
@asoov Since you have type: module, you'll need to have module.exports in the config. 

```js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  defaultCommandTimeout: 16000,
  retries: {
    runMode: 3,
    openMode: 0,
  },
  e2e: {
    baseUrl: "https://google.com",
  },
  chromeWebSecurity: false,
  video: false,
});
```

**Comment by asoov** [comment]
Hey Jennifer! This is really confusing as the docs are stating the following: 

> If your project is an ESM package (short for [ECMAScript Module](https://nodejs.org/api/esm.html#modules-ecmascript-modules)), Cypress attempts to apply the [ts-node/esm](https://github.com/TypeStrong/ts-node?tab=readme-ov-file#esm) Node.js loader to resolve the Cypress configuration and plugins. ESM is determined by Cypress if you have the type: "module" key-value pair present inside your project's package.json.

This indicates that when I use `"type": "module"` in my package.json I can use ESM syntax in my cypress.config.ts which I apparently can't. No matter what "type" setting I use I have to use CJS module.exports syntax in my Cypress config, is that correct?

**Comment by lp1641** [comment]
Case 1. Local packgage.json with type - commonjs. Works fine. Probably we should use this option.
![Image](https://github.com/user-attachments/assets/53a4a274-a455-49a1-8d0f-16a6189f0499)

Case 2. Local package.json with type - module. Error because of import/export syntax inside cypress.config.ts
![Image](https://github.com/user-attachments/assets/777ab3b3-7ea3-40cf-ad39-2d9a2a5ef65a)

Case 3. Project root package.json has type - module but I removed local package.json now. Error because it can't recognize .ts files.
![Image](https://github.com/user-attachments/assets/16cdba4d-3192-489f-a417-805ea290d6f5)
