### ISSUE TITLE
Cypress App - Typescript project blink on first test executions

### ISSUE THREAD

**Issue by schirrel** [cypress-io/cypress#28858]
### Current behavior

When running a TS project `yarn open` the very first test to execute the page refresh after the test start.
Other followed executions wont cause this. Only the first after the `yarn open`

See the video:

https://github.com/cypress-io/cypress/assets/6757777/db93956b-b943-4e59-82ff-c4c81fdb6ebe

If the video do no load, open the [link](https://github.com/cypress-io/cypress/assets/6757777/db93956b-b943-4e59-82ff-c4c81fdb6ebe).

### Desired behavior

When starting an app with typescript files it do not blinks of refresh after start

### Test code to reproduce

https://stackblitz.com/edit/typescript-lle8mt?file=cypress%2Fsupport%2Fcommands.ts

### Cypress Version

 13.6.2

### Node version

18.15.0

### Operating System

MacOS 14.1.1

### Debug Logs

```shell
https://gist.github.com/schirrel/0bcd30766d7fedbb682255b5a0e71fa8
```

**Comment by jbrp2** [comment]
@brian-mann up for this stopper on our pipeline

**Comment by jennifer-shehane** [comment]
@schirrel This is due to Cypress refreshing the top URL to the same base URL that you visited. We don't know ahead of time which URL will be visited, so we refresh to that URL when the visit is reached. You can avoid this refresh by setting the URL you intend to visit in your `baseUrl` of your Cypress config.

**Comment by schirrel** [comment]
Thanks a lot @jennifer-shehane 🙏🏻
