### ISSUE TITLE
Add support for webpack-dev-server v5

### ISSUE THREAD

**Issue by vdineva** [cypress-io/cypress#28924]
### What would you like?

Please add support for `webpack-dev-server@5`

### Other

`webpack-dev-server` have released a new major version - v5 and Cypress does not work with it:

![Screenshot 2024-02-12 at 12 53 04](https://github.com/cypress-io/cypress/assets/791418/8b950e1b-8f91-446e-aacd-f0ad628b12f8)

**Comment by MikeMcC399** [comment]
[webpack-dev-server v5.0.0](https://github.com/webpack/webpack-dev-server/releases/tag/v5.0.0) was released on Feb 12, 2024.

See [migration guide for webpack-dev-server@5.0.0.](https://github.com/webpack/webpack-dev-server/blob/master/migration-v5.md) including breaking changes.

**Comment by MichaelSemchenko** [comment]
Is there any update on this? v13.7.2, still an issue.

**Comment by MikeMcC399** [comment]
@vdineva 

- This issue seems to have been duplicated in issue<br>https://github.com/cypress-io/cypress/issues/29305
- The issue says it was resolved by PR<br>https://github.com/cypress-io/cypress/pull/29306
- Released in<br>Cypress [13.8.0](https://on.cypress.io/changelog#13-8-0)

Maybe you'd like to cross-check if this works for you?

**Comment by vadimpopa** [comment]
Works. Thanks @MikeMcC399 for the update.

**Comment by vdineva** [comment]
Verified this has been fixed in Cypress v13.8.0.
Closing this issue
