### ISSUE TITLE
Write permissions required on `resources/app/node_modules/@cypress/core-extension/dist/background.js`

### ISSUE THREAD

**Issue by orangecms** [cypress-io/cypress#290]
It seems a bit odd to me that Cypress would always rewrite the port in `HOST` (l14) when I open a project. That means I have to allow a regular user to write to that file if I want to install it globally. I came across this when creating a package for AUR: https://aur.archlinux.org/packages/cypress

This is the package build file:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cypress#n23

**Comment by brian-mann** [comment]
Due to the way that chrome extensions work there is no concept for a URL, so there's no other way for us to dynamically modify the javascript to point it to the cypress host server. Or at least - I couldn't think of another one.

However, what we can likely do is prevent rewriting this inside of `node_modules` and instead move it to the `app data` area of the OS that we write everything else to.

**Comment by orangecms** [comment]
I see, that solution makes sense. Thanks for the quick reply already! :)

**Comment by brian-mann** [comment]
Fixed in [`0.19.2`](https://github.com/cypress-io/cypress/wiki/Changelog#0192-04162017).
