### ISSUE TITLE
Is the test order within one file (one describe block) guaranteed?

### ISSUE THREAD

**Issue by Nasicus** [cypress-io/cypress#2901]
So this may not even be a Cypress specific thing but since I'm using Cypress I still think it's bes to ask here.

I'ts a very simply question:

_Is the test order within one file (one describe block) guaranteed?_

Why do I ask that?

We have quite a lot of database dependent tests.
Because of this we often have to seed our database data within tests.

Now let's assume I have the following tests:

```js
describe('My database tests', () => {
  // this is only done once for all tests in this block
  before(() => {
    seedUsersInDatabase();
  });

  it('Get users', () => {
    // expect 10 users
   });

  it('Remove users', () => {
    // expect 5 users removed
   });
});
```
Maybe you already see why the question poppep up.

If it's guaranteed that the tests within a `describe` block are always executed in the same order, I can seed the database with `before`. However if the order is not guaranteed I'd need to change it to `beforeEach`.

I personally assumed the order is guaranteed and therefore wrote only the `before`. The main reason for this is by the way: _Performance_! Seeding a database sometimes takes quite the time (even if it's just 100ms, it sums up if you have a lot of tests).

**Comment by jennifer-shehane** [comment]
The tests will run in order, although [we don't recommend you rely on the state of a previous test for your next test](https://on.cypress.io/best-practices#Having-tests-rely-on-the-state-of-previous-tests). Also, if one test fails (say your second test), all of the tests following may be affected or you may get false positives / negatives due to the state not being changed in that failed tests.

In the future, we recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Issues in our GitHub repo are reserved for potential bugs or feature requests.
