### ISSUE TITLE
Cloud should have a tab under tests run that contains information about response time duration of each endpoint used in the test suite

### ISSUE THREAD

**Issue by bixelbg** [cypress-io/cypress#29043]
### What would you like?

When I run my tests and navigate to the run report where Overview to have another tab that contains information about each and every endpoint used in the automation, ordered by number of uses, including the information about min response time, max response time, average resp time, the top 95%, 80% and 60% of fastest requests
![image](https://github.com/cypress-io/cypress/assets/82289070/17546e69-f7d4-4ab9-b245-fa879cfb0413)

### Why is this needed?

- Given the fact that most tests retest the same functionality, based on the response times we can really easy identify problems with system's optimization.
- We can always use checks in our tests like
```js
expect(response.duration).to.be.lessThan(200);
```
But that can introduce test flakiness for small laggs

For example running stress tests and viewing the response time in Grafana is highly helpful to find issues where certain endpoint lag for any reason:
![image](https://github.com/cypress-io/cypress/assets/82289070/6f9e7a05-53b1-4fab-bce1-6e8d3f06a75b)

### Other

@conversayShawn I'm tagging you to review this feature request

**Comment by jennifer-shehane** [comment]
@bixelbg Thanks for the feedback. I've forwarded this input to our product team. We have had some discussions around the possibility of exposing information around performance in relation to the application under test. Nothing has been decided at this point for that.

I'll close this issue here since this repo is used to track issues with the open source product and not the Cloud.
