### ISSUE TITLE
cy.log will print & instead of &amp;

### ISSUE THREAD

**Issue by awls99** [cypress-io/cypress#29115]
### Current behavior

While logging a string that contains the html entity `&amp;` the displayed log will be `&` which can be confusing.
![Screenshot 2024-03-12 at 14 17 02](https://github.com/cypress-io/cypress/assets/831346/1aee686e-aa7b-43f7-beaf-c06ddaf6c31c)

### Desired behavior

When `&amp;` is logged, `&amp;` should show on the logs

### Test code to reproduce

https://github.com/awls99/Ampersand-type-bug/blob/master/cypress/e2e/spec.cy.js

### Cypress Version

13.6.6

### Node version

18.18.2

### Operating System

macOS 13.2 (22D49)

### Other

I don't know if this happens with other html entities, likely it does, imho the logs should log _exactly_ what's told to log.

**Comment by jennifer-shehane** [comment]
We use markdown-it to interpret markdown formatting of messages in the Command Log, like `cy.log()`. https://github.com/cypress-io/cypress/blob/develop/packages/reporter/src/commands/command.tsx

I'm not sure this was the best decision in hindsight, but it'd be a breaking change to change it. The assertions were recently updated to not do formatting since it was comparing these absolute values that you needed to see. I can see how cy.log() messages could possibly be excluded from the markdown formatting also.
