### ISSUE TITLE
Change baseUrl during test (set to null) in order to visit local file instead of URL

### ISSUE THREAD

**Issue by dhmoon91** [cypress-io/cypress#2918]
### Current behavior:
We are currently implementing email confirmation test. 
We currently download the email file -> parse out the html content of it -> save it locally in fixture/. 

In order for `cypress.visit('path-to-local-file.html')` to load up the downloaded content, we need to change the `baseUrl` that was set in `cypress.json` to be empty. 

`Cypress.config('baseUrl', ' `');` doesn't switch `baseUrl` and keeps appending the path to local file to the original `baseUrl`, eg:  https://demo.test.com/fixtures/email-content.html

Also tried to follow https://docs.cypress.io/api/plugins/configuration-api.html#Usage but it also fails to switch out `baseUrl`. 

I couldn't find any workaround. 

One method I tried was NOT setting `baseUrl` in `cypress.json` and specify the main domain everywhere except for visiting local html file. But this also fails because we have a `before` hook that generates unique string for email and if you change the domain on `cy.visit()`, the `before` hook runs and the email file name won't match.

### Desired behavior:

`Cypress.config('baseUrl', ' ');` should switch baseUrl to none. 

### Steps to reproduce: (app code and test code)

Posting it as pseudo-code. Will fill in more details if needed.

**cypress.json**
```json
{
    "baseUrl": "https://demo.testing.com",
    "userAgent": "testing"
}
```

**test spec file**
```js
 var emailFileName;

    before(function () {
        cy.log('ran');
        cy.task('generateGuid').then(function ($guid) {
            guid = $guid;
            emailFileName = 'tester' + guid + '@test.com';
            cy.log(emailText);
        });
    });

it('Register user', function () {

        cy.visit('/login'); //-> yields https://demo.testing.com/login
        // Fill up registration info then click 'Register' button

        cy.wait(5000);
        cy.get(sendConfirmEmailButton).click({ force: true });

        // wait for 30s to verify email body
        cy.wait(20000);
        cy.downloadEmailHtml(emailFileName, 'confirmAccount');
    });

it('Visit email user', function () {
        // Change baseurl
        Cypress.config('baseUrl', ' ');
        // TODO visit/load the confirm account html file
        cy.visit(`cypress/fixtures/confirmAccount_${emailFileName}@test.com.html`);
        cy.get('#templateBody')
            .contains('Click the button below to confirm your account');
    });
```

### Versions

Cypress: 3.1.3
OS: Mac- mojave

**Comment by dhmoon91** [comment]
I kinda went all over the place but really, I just need to set the baseUrl to empty or null to load up the local html content file and I thought the Cypress.configure('baseUrl', '') would support this behaviour.

**Comment by jennifer-shehane** [comment]
Hey @dhmoon91, have you tried setting the baseUrl back to its default value of `null`? We believe this functionality should work.

```
Cypress.config('baseUrl', null)
cy.visit(`cypress/fixtures/confirmAccount_${emailFileName}@test.com.html`)
```

**Comment by dhmoon91** [comment]
Hi @jennifer-shehane . 

Thanks for the qucik reply .

I just tried setting it null and Cypress seems to append localhost + random port infront of the ``cypress/fixtures/confirmAccount_${emailFileName}@test.com.html``. 

For me, cypress tries to visit`http://localhost:60465/cypress/fixtures/confirmAccount_${emailFileName}@test.com.html` 
and fails.

This might be related to https://github.com/cypress-io/cypress/issues/382?

**Comment by you1anna** [comment]
Any updates on this issue? It is undesirable behaviour:

```
Cypress.Commands.add("loginToRm", (email, password) => {
    Cypress.config('baseUrl', null)
    cy.visit(Cypress.env('rmBaseUrl'))
        .get(RM_EMAIL_FIELD).type(email)
        .get(RM_PASSWORD_FIELD).type(password)
        .get(RM_LOGIN_BUTTON).click()
        .url().should('contain', '/admin/Home')
});
```
The above will redirect to baseUrl in Cypress.config instead of remaining at rmBaseUrl. The alternative is to never set baseUrl in the main config, against best practise.

An update on a fix or workaround would be greatly appreciated.

**Comment by pmn4** [comment]
I am experiencing something similar:
I have several applications on subdomains which redirect to a relative path (client-side) once an authentication request succeeds (that is, the user should stay on the subdomain once they authenticate). I am testing all applications in a single suite, so I set baseUrl as `"baseUrl": "domain.com"` in `cypress.json` since "domain.com" is the superdomain for all applications.

I have tried setting `Cypress.config("baseUrl", "stage.domain.com")` and  `Cypress.config("baseUrl", null)`, but in either case, the page redirects to `www.domain.com/home` instead of `stage.domain.com/home`

![image](https://user-images.githubusercontent.com/1158287/59944060-d935c980-9431-11e9-8366-e5a005811922.png)

The yellow arrow shows that my baseUrl is "domain.com"
The blue arrow points to my application's subdomain
The red arrow shows where an AJAX authentication attempt succeeds and the user is redirected using `window.location.redirect("/home")`. This translates to "www.domain.com/home" _(our server configuration points all naked domain requests to www.)_

unsetting baseUrl in my config works for the first subdomain that is visited, but subsequent subdomains do not (as latter subdomains do not descend from the first).

**Comment by mbatesR** [comment]
@jennifer-shehane Can you elaborate on why the baseURL reassignment during a test isn't applying? I have ran into cases as well where I needed to change the base URL mid-test to set key:value pairs in local storage and wasn't able to.

**Comment by zhammer** [comment]
may not work for everyone, but since i'm using cypress to test a python web application that serves up everything in a `static/` directory, i've done this:

```js
      const html = /* my html */;
      cy.writeFile("static/tempfile.html", html);
      cy.visit("static/tempfile.html");
    });
```

**Comment by jennifer-shehane** [comment]
@mbatesR Cypress changes the parent domain to match the `baseUrl`, in order to avoid issues with navigating on a website that does not match the parent domain. The Cypress product is just not coded to handle changing the `baseUrl` mid test.

**Comment by mihaic195** [comment]
@jennifer-shehane I think the inability to change the `baseUrl` mid test is a problem in our case.

Currently I am facing an issue where I do a login using API requests with `cy.request`. Login is happening on Auth0. This is needed to retrieve some JWTs from Auth0 and setting necessary cookies in the browser. This is needed for cross-domain authentication (SSO). Everything ok until here.

After setting the necessary cookies, I navigate to the page which I want to test using `cy.visit`. Doing any sort of interaction on that page causes the browser to reload and breaks the tests.
Possibly the exact same situation: https://github.com/cypress-io/cypress/issues/2542
I did not set any `baseUrl` because of the following:

We have pre-production environments where subdomains are dynamic and also certain parts of the application redirect to other subdomains. 

For example `x.subdomain1.domain.com` can redirect to `x.subdomain2.domain.com`, where `subdomain1` and `subdomain2` can be seen as bounded contexts of the application, while `x` is a github branch identifier.

I think a fix for this is to at least allow for some sort of wildcard in the `baseUrl` or regex?

A workaround can be to actually do the login during the test, click on login -> enter user/pass -> click login etc. But it is actually something that we want to avoid in the first place, as it causes tests to run for a longer time and it shouldn't be part of the actual test IMHO.

What do you suggest in this case?

**Comment by jennifer-shehane** [comment]
@mihaic195 I'm not completely sure of the circumstance you're describing.

>Doing any sort of interaction on that page causes the browser to reload and breaks the tests.

I have an example below where the cookies set before and after visit are both set.  It's likely more complicated than my example, so I'd like to understand. Can you provide an example of how the tests are failing due to the browser reload?

```js
it('setting cookies when no baseUrl', () => {
  cy.setCookie('foo', 'bar')

  cy.visit('https://example.cypress.io')
  
  cy.setCookie('baz', 'fizz')
  cy.getCookies().then((cookies) => {
    expect(cookies[1]).to.have.property('name', 'foo')
    expect(cookies[2]).to.have.property('name', 'baz')
  })
})
```

**Comment by mihaic195** [comment]
@jennifer-shehane I'll try to explain below.

Basically the tests are failing exactly how you see in the video of https://github.com/cypress-io/cypress/issues/2542

Steps:
1. Create a custom cypress login command, which creates a `cy.request` on an Auth0 link and sets the appropriate cookies in the browser (access_token, id_token, expires_at).
2. Visit the protected resource of our application using `cy.visit`, which requires the cookies to be set with the right values, otherwise you wouldn't be able to access the resource.
3. After arriving on the page, I do a `cy.contains('Share').click()` which is supposed to open a modal and do some actions on that modal. 
4. Upon clicking on the button from step 3, the modal briefly opens and then the browser refreshes, which brings us back to step 2 and then since the modal is not open anymore, it cannot continue with the remaining code of the test. It would need to do `cy.contains('Share').click()` again to re-open the modal.

Normally I should be able to set `baseUrl` to `x.subdomain1.domain.com` and it should work (based on the answers from https://github.com/cypress-io/cypress/issues/2542), but even by setting the `baseUrl`, the browser is still refreshed so maybe I am missing something.
Basically I am doing a `cy.request` to an Auth0 domain and a `cy.visit` to our application.

In any case, our test suite contains tests which are also part of other subdomains, such as `x.subdomain2.domain.com`, which brings us back to the problem of the current issue, so the `baseUrl` will not be correct for other tests, that's why I thought having a wildcard/regex as a `baseUrl` would be beneficial.

If I login using the test itself, the flow would be something like: 
1. Click on Login button
2. Be redirected to Auth0 URL
3. Type the user/pass
4. Submit form
5. Be redirected to the protected resource of our application

This flow works fine. This case doesn't include any `cy.request` and `cy.visit`. But as I said, I feel that this part should not be part of the contxt of the test itself from a business logic point of view, but also because it increases the time spent during the test, that's why I even created a custom login command to begin with.

Was it clear enough?
Thanks.

**Comment by andrei22b** [comment]
@mihaic195 I have the same issue as you.I am creating an account and and when the reload happens i have an error with the email already exist because it creates with the same one. I hope i can get a workaround.

**Comment by mihaic195** [comment]
Probably the explanation with `x.subdomain.domain.com` was a bit too deep and confusing.
The basic principle is SSO: https://auth0.com/docs/sso/current

How can that work if you can't change the `baseUrl`? But I think this is a different problem than the refresh thing.

@andrei22b Please let me know if you find a workaround. For now I just left the login as it is - cypress navigates to login - completes form - submits form.

**Comment by andrei22b** [comment]
@mihaic195 i will let u know if i find something

**Comment by andrei22b** [comment]
@mihaic195 this 'hack' worked for me:
![image](https://user-images.githubusercontent.com/20188368/79341114-f513da00-7f33-11ea-9365-ed9e2ffa1a56.png)

In my case visiting before any action the desired url helped me to not rerun the commands due to reload of the browser. Hope it helps you too !

**Comment by stuartbrussell-intuit** [comment]
I'm curious why we need to deal with the baseUrl at all when going to a local file? If you get a url beginning with ".", assume it is a file and don't prepend the baseUrl. It seems like this issue is more about changing the baseUrl midstream, and less about visiting a file (even though the title and some of the discussion are about visiting a file).

**Comment by stuartbrussell-intuit** [comment]
@jennifer-shehane Is it possible to re-open https://github.com/cypress-io/cypress/issues/4450 as a single-subject issue? The point is that opening a file should not require any consideration of the baseUrl, whether it is set or not. Most of the discussion here is about changing the baseUrl, which is really not relevant to opening a file. In other words, the title of this issue could be shortened to "allow a script to change the baseUrl while running" and it would match the discussion. Thanks in advance. It is good to see prompt activity in the project. :)

**Comment by willcoliveira** [comment]
Any updates on that? Probably it won't be reopen. I'm facing the same issue with latest version :(

**Comment by jennifer-shehane** [comment]
You can now change the `baseUrl` using [test/suite configuration](https://on.cypress.io/writing-and-organizing-tests#Test-Configuration) in order to set to null to visit a local file.

`cypress.json`

```js
{
  "baseUrl": "https://example.cypress.io"
}
```

`spec.js`

```js
it('visits base url', () => {
  cy.visit('/')
  cy.contains('h1', 'Kitchen Sink')
})

it('visits local file', { baseUrl: null }, () => {
  cy.visit('index.html')
  cy.contains('local file')
})
```

**Comment by zhammer** [comment]
@jennifer-shehane are `describe, context, it, specify` the only places to override the baseUrl? is it possible to do this manually? (my use case is that i'm using cypress-cucumber-preprocessor, so i'm not ever actually calling those funcs directly.)

**Comment by jennifer-shehane** [comment]
@zhammer Not currently, which is why this issue is still open. Just wanted to offer a possible solution for some that could use test / suite config.

**Comment by zhammer** [comment]
Got it, thanks! And thanks for posting helpful updates on issues all over the cypress github :)
