### ISSUE TITLE
Cypress using "--headed --no-exit" only runs one spec file

### ISSUE THREAD

**Issue by ouchsaray** [cypress-io/cypress#2919]
### Current behavior:
I have multiple spec files to check my website, when I run them without the options `--headed --no-exit` they work well, but if I add to my script `--headed --no-exit` then only runs the first spec file. 

### Desired behavior:
Using `--headed --no-exit` should run all the specs files inside the integration folder. 

### Steps to reproduce: (app code and test code)
Add `--headed --no-exit` to your script, e.g :

`"test:automation:local": "node_modules/.bin/cypress run --env configFile=local --headed --no-exit"`

### Versions
Cypress: 3.1.2 & 3.1.3

**Comment by jennifer-shehane** [comment]
Hey @ouchsaray, what is your intention behind passing the `--no-exit` flag?

This is not clearly stated in the docs, but the `--no-exit` flag will prevent Cypress from exiting (closing the test runner), so this will not exit on the first available opportunity to 'exit'. Since Cypress closes the test runner in between each spec file that is run, this means that the Test Runner would not close after the first spec of any set of specs is run. 

I will update the docs to reflect this current behavior.

**Comment by ouchsaray** [comment]
Hi Jennifer,

I use `--no-exit` when I am writing my test to keep the Cypress UI open (if I need the inspector to find an element, etc...), but today I was doing a demo to my colleagues and I realise that it only runs the first spec file not all of them, and what I was expecting  was to run all the spec and keep Cypress open at the end... it is the same than run `cypress run --headed` or open it manually, but reading your comment I was confused about `--no-exit` usage. 

Cheers! :)
