### ISSUE TITLE
Support custom timeouts for `its`

### ISSUE THREAD

**Issue by hdavidzhu** [cypress-io/cypress#2941]
### Current behavior:

```javascript
> cy.window().its('Something')

CypressError: Timed out retrying: cy.its() errored because the property: 'Something' does not exist on your subject.
```

### Desired behavior:

```javascript
> cy.window().its('Something', {timeout: 10000})
```

`Something` may take longer than the default timeout to load on a `window`, and I'm not exactly sure how I can customize the duration. Thoughts? Workarounds?

### Versions

```
CI: Unknown
OS: Linux Ubuntu - 14.04
Browser: Electron 59.0.3071.115
Cypress: v3.1.3
```

**Comment by jennifer-shehane** [comment]
The documentation for `cy.its()` says:

>.its() will automatically retry itself until the property exists on the subject.
>.its() will automatically retry itself until assertions you've chained all pass.
- https://on.cypress.io/its#Assertions

Passing the `timeout` option is the way to increase the time waiting for the property to exist on the window. 

How long does it generally take for the property to exist on the window? Is there another assertion you can do before this to get it closer to being there? Like..waiting for the page to load?

**Comment by hdavidzhu** [comment]
Thanks for the quick response!

I think in my situation, the window can sometimes load quite a bit before my object gets attached. Is there something I can insert between `window()` and `its()`? The window loading default timeout seems to be working fine.

**Comment by jennifer-shehane** [comment]
I think using the `timeout` is fine, unless you have something else you want to assert about in the window instead of just waiting for the object to exist.

**Comment by knagarajan1984** [comment]
I have a similar issue. The property in the window loads up as null after which it takes few seconds (20 secs) for the property to get updated to not null property. But the below line of code fails due to
".its() will automatically retry until the subject's property is not null or undefined."

cy.window({ timeout: 20000}).its('myproperty.Hash').should('not.equal', null).and('equal', '1234')

Is there anyway to get around this. I dont have anything else to wait on or assert about.

**Comment by hdavidzhu** [comment]
Sidenote: I think my original issue was resolved by https://github.com/cypress-io/cypress/issues/3837 🎉
