### ISSUE TITLE
Uncommitted change to packages/graphql/schemas/schema.graphql after PR #29420

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress#29656]
### Current behavior

- PR https://github.com/cypress-io/cypress/pull/29420 leaves change to autogenerated [packages/graphql/schemas/schema.graphql](https://github.com/cypress-io/cypress/blob/develop/packages/graphql/schemas/schema.graphql) uncommitted.

### Desired behavior

Running `yarn` after a PR has been merged (and in general in the `develop` branch) should not produce any differences.

### Test code to reproduce

Ubuntu `22.04.4` LTS, Node.js `18.17.1`, Yarn `1.22.22`

```shell
git clone https://github.com/cypress-io/cypress
cd cypress
git checkout ceb11a355a4e60f9833412cb03d56756b0dc4800 # commit before PR 29420
git clean -xfd
yarn
git status
```

`git status` shows:

```text
HEAD detached at ceb11a355a
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   yarn.lock
```

- (The above uncommitted change is related to issue https://github.com/cypress-io/cypress/issues/29653.)

- Now advance to commit from PR https://github.com/cypress-io/cypress/pull/29420

```shell
git checkout ec1d7994dddc4e3fe0f85d62ba49ad18f703ec51 # commit for PR 29420
yarn
git status
git diff
```

`git status` shows:
```text
HEAD detached at ec1d7994dd
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   packages/graphql/schemas/schema.graphql
	modified:   yarn.lock
```

`git diff packages/graphql/schemas/schema.graphql` shows:

```text
$ git diff packages/graphql/schemas/schema.graphql
diff --git a/packages/graphql/schemas/schema.graphql b/packages/graphql/schemas/schema.graphql
index 658f055c06..88a8155c28 100644
--- a/packages/graphql/schemas/schema.graphql
+++ b/packages/graphql/schemas/schema.graphql
@@ -1236,6 +1236,8 @@ enum ErrorTypeEnum {
   PORT_IN_USE_LONG
   PORT_IN_USE_SHORT
   PROJECT_ID_AND_KEY_BUT_MISSING_RECORD_OPTION
+  PROXY_ENCOUNTERED_INVALID_HEADER_NAME
+  PROXY_ENCOUNTERED_INVALID_HEADER_VALUE
   RECORDING_FROM_FORK_PR
   RECORD_KEY_MISSING
   RECORD_PARAMS_WITHOUT_RECORDING
```

### Cypress Version

`13.11.0` ec1d7994dddc4e3fe0f85d62ba49ad18f703ec51

### Node version

`v18.17.1` LTS

### Operating System

Ubuntu `22.04.4` LTS

### Debug Logs

See above

### Other

FYI @BernardoSousa03

**Comment by MikeMcC399** [comment]
- PR https://github.com/cypress-io/cypress/pull/29657 submitted to resolve this issue

**Comment by BernardoSousa03** [comment]
@MikeMcC399 Oh, thank you so much for this observation. I did not notice this file was changed due to autogeneration and since i didn't manually change it i didn't add it to the PR. I must have cleaned up some files before sending the PR.

By any chance do you know why isn't this file added to the `.gitignore` file since its autogenerated? I've read some different opinions on why you should or should not add autogenerated files and i was wondering if it has anything to do with the package.

Also it might be useful to update the file error-handling.md in `cypress/guides`. The `#### Editing or Adding New Errors and Updating Snapshots`  section specifically says to commit the files changed in the `__snapshot-html__`. Maybe tell the developer to add this file to the commit? Or give some sort of heads up to autogenerated files in this section of the code?

@jennifer-shehane what do you think about this sugestion?

**Comment by MikeMcC399** [comment]
@BernardoSousa03 

Based on the fact that [packages/graphql/schemas/schema.graphql](https://github.com/cypress-io/cypress/blob/develop/packages/graphql/schemas/schema.graphql) is already committed to the repo means that it needs updating if it gets changed. I'm not familiar with `graphql` so I can't contribute to what is best practice.

In general though when you build Cypress from source using `yarn` (install) there shouldn't be anything left over. And if there is, then it needs investigation.
