### ISSUE TITLE
Cypress is unable to solve alias

### ISSUE THREAD

**Issue by edudelta** [cypress-io/cypress#3005]
### Current behavior:

Cypress stuck in a step to solve alias stored in **beforeEach**. I'd waited for 400 sec by one result.

### Desired behavior:

Cypress should raise timeout or solve alias.

### Steps to reproduce: (app code and test code)

```javascript
function stuck() {
    return cy.get('@example').then((example) => {
        true
    })
}

describe('does not work', function () {

    beforeEach(function () {
        cy.wrap('neverTouch').as('example')
    })

    it('just a stuck example', function () {
        cy.log('Never writen', stuck())
    })

})
```

### Versions

Cypress 3.1.4
Windows 10
Chrome 71

**Comment by edudelta** [comment]
Hi again!
Thanks for clarify. As mentioned, I was waiting for a timeout or else instead freezes testing. 
Firstly, I'm trying to avoid too many then() calls because turns coding too horizontal. (I got 5 then and now refactoring.) and I face this situation that was quickly simplified. Yes, I think is a bug. This situation has occurred before in CI.
Second by some security/law reasons I changed to clear the situation of the issue instead sharing (ignorable) code.
Lastly, that issue is another one and it was closed. all notes related are there. Sorry by the delay.
Again, by security issues CHAT is not acceptable in all networks.
Thanks a lot for your help.

**Comment by dwelle** [comment]
Thanks for clarify. As mentioned, I was waiting for a timeout or else instead freezes testing.

> Firstly, I'm trying to avoid too many then() calls because turns coding too horizontal.

In cypress you don't usually need `then` callbacks if you structure your commands correctly, but if you end up needing them you can always do something like this:

```
.then(() => {
    return someAsyncCall();
}).then(() => {
    return anotherAsyncCall();
});
```

thus there won't be any callback hell issue.

> Yes, I think is a bug.

On second thought, there indeed seems some bug (or at least very weird behavior I don't understand), but the main point still stands --- you'd never encounter this "bug" if you didn't do stuff you shouldn't. Again, read that article I sent you.

Anyway, this is what's happening:

1. `cy.log(...args )` allows `...args` to be a Promise whose resolution value it logs:

    ```
    cy.log( Promise.resolve(42) ); // logs 42
    ```
2. when you issue any `cy` command, it returns a promise-like `$Chainer` object
3. you pass result of `stuck()` function as 2nd arg to `cy.log()` command
4. your `cy.log` command things the 2nd arg is a promise because the `$Chainer` has callable `.then` method
5. it then waits on the 2nd arg to resolve
6. (**conjecture**) the `cy.get()` doesn't resolve for some reason, even though it technically should/could, and `cy.log` doesn't timeout (which it [technically shouldn't](https://docs.cypress.io/api/commands/log.html#Timeouts), but in practice it does in other circumstances).

/cc [@jennifer-shehane](https://github.com/jennifer-shehane)  --- what's happening here, exactly?

```
cy.log(new Promise(() => {})); // times out in 4s

// incorrect code below, but to make a point

cy.log( cy.wrap(42) ); // times out in 4s
cy.log( cy.wrap(42).then(() => {}) ); // never times out
```

Also, despite passing `cy` commands as args to other cy commands being incorrect, why does cypress care in this example:

```
cy.log( cy.wrap(42) );
//  \       \_ command1
//   \_ command2
```

1. `command1` is enqueued
2. `command2` is enqueued
3. `command1` is dequeued
4. `command1` is resolved
5. `command2` is dequeued
6. `command2` awaits its 1st arg, which should already be resolved
    - is the problem here that the 1st arg is not a promise, but a `$Chainer`, and `cy.log` refuses to touch it? But why doesn't it time out if we chain extra noop `.then()` on the `cy.wrap(42)`?
