### ISSUE TITLE
Enforce valid describe() callback (valid-describe-callback)

### ISSUE THREAD

**Issue by julianCast** [cypress-io/cypress#30092]
### Current behavior

According to Cypress doc https://docs.cypress.io/guides/guides/test-retries#Test-Suites we can pass a object as second parameter to Describe, for example to use `retries`.

According to jest we shouldn't https://github.com/jest-community/eslint-plugin-jest/blob/v28.6.0/docs/rules/valid-describe-callback.md

### Desired behavior

Not getting a ESlint error from eslint-plugin-jest

### Test code to reproduce

```js
describe(
  "Test1",
  {
    retries: {
      runMode: 2,
      openMode: 1,
    },
  },
  () => {})
```

### Cypress Version

13.13.2

### Node version

20

### Operating System

macOS

**Comment by jennifer-shehane** [comment]
@julianCast Have you looked at trying https://github.com/cypress-io/eslint-plugin-cypress ?

**Comment by julianCast** [comment]
> @julianCast Have you looked at trying [cypress-io/eslint-plugin-cypress](https://github.com/cypress-io/eslint-plugin-cypress) ?

Oh sorry, that's the place for this issue.Thanks

**Comment by MikeMcC399** [comment]
@julianCast 

- There appears to be some misunderstanding. @jennifer-shehane was suggesting that you try linting your Cypress tests with the Cypress linter instead of the Jest linter.

- The repo https://github.com/cypress-io/eslint-plugin-cypress and your new issue https://github.com/cypress-io/eslint-plugin-cypress/issues/220 can't address issues using https://github.com/jest-community/eslint-plugin-jest. It is only for issues using https://github.com/cypress-io/eslint-plugin-cypress.

**Comment by julianCast** [comment]
Oh! That's a good point, I will try with `eslint-plugin-cypress`, thank you
