### ISSUE TITLE
Support Angular 19 Component Testing

### ISSUE THREAD

**Issue by AtofStryker** [cypress-io/cypress#30175]
### What would you like?

Angular 19 is scheduled to release the week of November 19th, 2024 ([see schedule](https://angular.dev/reference/releases)). Cypress should support this version for component testing when v19 is released

### Why is this needed?

Cypress should stay up to date with framework releases to allow users to have a smooth transition experience to Angular 19

**Comment by marklagendijk** [comment]
@AtofStryker since Angular 19 released yesterday: what is the status of this issue?

I got my Component Tests working with Angular 19 after resolving the following issues:
- Install `@angular-devkit/build-angular@19` and `@angular-devkit/core@19`. I think one of the Angular upgrade scripts removed these dependencies.
- Replace usages of the [ng-mocks](https://github.com/help-me-mom/ng-mocks) library with custom mocking code. https://github.com/help-me-mom/ng-mocks/issues/10503 https://github.com/help-me-mom/ng-mocks/issues/10487.

**Comment by AtofStryker** [comment]
> @AtofStryker since Angular 19 released yesterday: what is the status of this issue?
> 
> I got my Component Tests working with Angular 19 after resolving the following issues:
> 
> * Install `@angular-devkit/build-angular@19` and `@angular-devkit/core@19`. I think one of the Angular upgrade scripts removed these dependencies.
> * Replace usages of the [ng-mocks](https://github.com/help-me-mom/ng-mocks) library with custom mocking code. [Feature Request: Support for Angular 19 help-me-mom/ng-mocks#10503](https://github.com/help-me-mom/ng-mocks/issues/10503) [No updates until Jan 2025 help-me-mom/ng-mocks#10487](https://github.com/help-me-mom/ng-mocks/issues/10487).

@marklagendijk This is slated to go out with Cypress 14, which is likely going to release late 2024 / very early 2025. I will be starting implementation on this in a few days.

**Comment by AtofStryker** [comment]
currently blocked by https://github.com/angular/angular/issues/58862

**Comment by AtofStryker** [comment]
no longer blocked. https://github.com/angular/angular/issues/58862 outlines expected behavior of the test module
