### ISSUE TITLE
High timeout causes cypress retry-ability interval to increase drastically

### ISSUE THREAD

**Issue by ogdans3** [cypress-io/cypress#30209]
### What would you like?

Either keep the retry interval the same, make it configurable, or some sort of back-off. We would prefer it to be consistent or configurable.

### Why is this needed?

We have timeout set to 3 minutes in order to improve flakyness, we have a somewhat slow system 😛 

    defaultCommandTimeout: 180000,
    requestTimeout: 180000,
    pageLoadTimeout: 180000,
    responseTimeout: 180000,
    execTimeout: 180000,
    taskTimeout: 180000,

This seems to cause the cypress retry-ability to be extremely slow or rare. It seems that the interval between retrys for commands is dependent on the total timeout.

**Comment by jennifer-shehane** [comment]
>This seems to cause the cypress retry-ability to be extremely slow or rare. It seems that the interval between retrys for commands is dependent on the total timeout.

I don't really understand what you're describing here. Could you provide a code example that we can run to see the issue?

If you're using the standard retry behavior, where a Cypress test retries on a failure. There will always be a 3 minute wait for the test to actually fail (likely due to the `defaultCommandTimeout` being reached) before the next retry will run. The test has to fail the condition first. The test is doing exactly what you've told it to do.

**Comment by ogdans3** [comment]
After some more investigation it seems that the retry mechanism works as it should, we are simply querying too much which makes it appear slow. We are going to do a light rewrite of our step definitions to speed up the process.
