### ISSUE TITLE
Using KafkaJS in Cypress doesn't work, while works in Mocha itself

### ISSUE THREAD

**Issue by tomaszwojciechowski** [cypress-io/cypress#30404]
### Current behavior

Test being run as Mocha's one works- event is being produced in Kafka, while running same test in Cypress results in error.

### Desired behavior

I want to use KafkaJS inside Cypress test to produce and consume events in Kafka.

### Test code to reproduce

Fork: https://github.com/tomaszwojciechowski/cypress-test-tiny

### Cypress Version

13.15.0

### Node version

22.9.0

### Operating System

Ubuntu 24.10

**Comment by cacieprins** [comment]
Hi @tomaszwojciechowski , because Cypress runs its tests in the browser and `kafka-js` requires a `node.js` environment, you'll have to do some extra legwork to produce and consume kafka messages from a Cypress test. The [`cy.task` API](https://docs.cypress.io/api/commands/task) will be useful for implementing this.
