### ISSUE TITLE
Dashboard add comments

### ISSUE THREAD

**Issue by neutcomp** [cypress-io/cypress#3061]
### Current behavior:

There is no way of adding some comments to a failing test in the Cypress Dashboard

### Desired behavior:

I want to add some comments to a failing test. This so other testers know that I am looking at this failing test. This saves testers time in communication.

### Versions

3.1.4, Windows, Chrome

**Comment by GrzegorzKaczan** [comment]
Or at least to have a button marking this test (or whole run) as `being taken care of` by a user. Similar to how claiming failed build works for Jenkins: https://wiki.jenkins.io/display/JENKINS/Claim+plugin

**Comment by jennifer-shehane** [comment]
cc @cypress-io/services

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.
