### ISSUE TITLE
On-premise Dashboard

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3095]
## Problem

You organization would like to use [Cypress Dashboard](https://on.cypress.io/dashboard-service) but cannot send test results (names, timings, test bodies, screenshots, videos) to an external service.

## Proposal

Allow running Dashboard as a paid on prem solution. 

## Timeline

Far in the future. Requires bringing all our services into containers for deployment, rethinking charging and billing, support.

## Feedback

Is very welcome

## Related issues

- #3063

**Comment by fr0** [comment]
Other companies do this (e.g. [GitHub Enterprise](https://enterprise.github.com/home), [npm Enterprise](https://npme.npmjs.com/docs/)). You might take a look at their solutions for implementation ideas.

**Comment by JPHamlett1993** [comment]
Super interested in this

**Comment by jetrii** [comment]
Huge +1 on this. Cypress is currently unusable by companies that work with highly confidential data.

**Comment by faiz121** [comment]
Interested in this

**Comment by cbrunnkvist** [comment]
Absolutely essential for some enterprise settings.

**Comment by jennifer-shehane** [comment]
You can express interest in this feature and see it's progress on our Roadmap from our Dashboard's new product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard/c/32-on-premise-installation

**Comment by azaeng04** [comment]
> You can express interest in this feature and see it's progress on our Roadmap from our Dashboard's new product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard/c/32-on-premise-installation

This link takes me to a blank screen with the following error in Googles Console

![2019-10-24_16h30_19](https://user-images.githubusercontent.com/13921692/67495690-943dd000-f67b-11e9-802f-8984ef54c3c3.png)

**Comment by azaeng04** [comment]
What is the status on this?
This would be a BIG plus for our current testing environment.
We would really like to execute our tests in parallel.

**Comment by jennifer-shehane** [comment]
## Progress and Comments

This has not been released as of October 24, 2019.

You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard **Look for a card called 'On-premise installation'.**

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for the Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.
