### ISSUE TITLE
(new feature request) Config need to stop the script from failing when after each failed

### ISSUE THREAD

**Issue by VSathyamoorthy** [cypress-io/cypress#3110]
Config need to stop the script from failing when after each failed 

### Is this a new feature/bug?

New feature request

### Current behavior:

When the afterhook each failed after a time out error but the test has run successfully, still the test is considered as failed. 

In my case,  logout function is in the aftereach hook and when I run a test suite, one test fails due to the afftereach hook is timedout for every 2-3 runs

### Logout function

Cypress.Commands.add('logOut', () => {
    cy.visit('/')
    cy.visit('/home/logoff',{timeout:120000})

### Timeout error log

![image](https://user-images.githubusercontent.com/45643198/50937919-06b53900-14ca-11e9-9d8a-d4c23ebf992e.png)

### Desired behavior:

A configuration needed to make the test pass when aftereach hook is failed

### Versions

OS: Windows 10
Browser: Electron 59.0.3071.115
Cypress: 3.1.3

**Comment by bahmutov** [comment]
I believe this would be a very bad practice. The failing `afterEach` hook is telling you that either
- your server is flaky
- Cypress is flaky

If it is reason 1 then it is super important to fix the server code, otherwise, the user session is incorrectly handled. If it is reason 2 then we need to fix it in Cypress because it for sure will affect other requests, causing intermittent failures inside the main test bodies, not just in `afterEach` hooks.

We built Cypress with a goal to make tests useful, and each failure being a big red light that something is broken and should not be ignored. 

But do not despair, we are working on test retries that do what you need - prevent flake. Track issue #1313 to find how it is going
