### ISSUE TITLE
cy.fixture('foo.json') as text instead of object

### ISSUE THREAD

**Issue by fr0** [cypress-io/cypress#3138]
### Current behavior:

I have a fixture file that contains JSON data to be sent to the server to put the back-end in a specific state. It is sent as JSON text.
When using `cy.fixture()` or `cy.readFile()`, someone's parsing that JSON text and handing me an object.
Normally this is good, but in my case since I am just going to turn around and send the JSON text to the server, it seems like an unnecessary step to have to call `JSON.stringify`; why can't cypress just hand me the raw text?

### Desired behavior:

Add some option to `cy.fixture` that lets me force it to be text, even if the file extension is `.json`.

### Versions

3.1.4

**Comment by pablogiroud** [comment]
Maybe this will help you:
eg:

```cy.get('textarea').type(JSON.stringify(this.data))```

**Comment by jennifer-shehane** [comment]
Adding this feature is not something we see as within our scope of feature work since there is a pretty simple existing workaround by calling `JSON.stringify()` on the encoded JSON data, so we will be closing this issue. We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
