### ISSUE TITLE
Console.log of element with error

### ISSUE THREAD

**Issue by MathRobin** [cypress-io/cypress#314]
Hi !

Maybe I can suggest you something. I need more info in console too. In browser. When an assertion failed, concerning an element, it could be great to console.log it.

For example, I would like to know if all the images in my page has src attribute and if this attribute starts for each one by "https://". If one not, the cypress.each will say me it has failed. But on which one? I have to edit my test, console.log each element and find myself. Not really useful (juste for this part, cypress itself is very useful)

```js
    it('it should contain images in HTTPS with alt attribute', function () {
        cy
            .get('img')
            .each(function ($el) {
                // HTTPS
               expect($el.attr('src').substr(0, 5)).to.equal('https');
                // Alt
               expect($el.attr('alt').length).to.be.above(0);
            });
    });
```

If it failed, I don't know on which element.

**Comment by brian-mann** [comment]
The problem is that Cypress has no idea you are making an assertion about an element - because you're not. You are making an assertion about a `String` and a `Number`.

That's why you cannot tell which element is failing because you're simply comparing strings and numbers.

If you were to rewrite your assertion to actually be about the element you would already have the tools in Cypress to see which one was failing.

```javscript
it('it should contain images in HTTPS with alt attribute', function () {
        cy
            .get('img')
            .each(function ($el) {
               // assertion which starts on the $el
               // and then changes to the return value of attr("src")
               expect($el).to.have.attr("src").and.match(/^https/)

               // assertion which starts on the $el 
               expect($el).to.have.attr("alt")
            });
    });
```

Now in Cypress when you hover over the assertions about actual element you will see Cypress not only highlight the element on the page, but also when you click on the assertion you will see `console.log` information about the element in question.

**Comment by MathRobin** [comment]
How great !!! Will test it asap !!!

Thanks for your help !
