### ISSUE TITLE
Support for Early Hints (103 response code)

### ISSUE THREAD

**Issue by yanshiyason** [cypress-io/cypress#3189]
### Current behavior:

`cy.visit` crashes when accessing a page which uses Early Hints.

```js
// this line
cy.visit('https://my-app-staging.herokuapp.com/')
```

![image](https://user-images.githubusercontent.com/11358371/51582551-cf09b080-1f0f-11e9-9d31-7953706a441b.png)

Here is after adding the `failOnStatusCode: false` option.

![image](https://user-images.githubusercontent.com/11358371/51582710-97e7cf00-1f10-11e9-890d-a7f36ea86b40.png)

Here is a curl dump of the headers:

```bash
$ curl -i https://my-app-staging.herokuapp.com
HTTP/1.1 103 Early Hints
Server: Cowboy
Date: Wed, 23 Jan 2019 03:56:55 GMT
Connection: close
Link: <https://my-app-staging.herokuapp.com/assets/pages/teaser/application-75954bd9d7c1a87e0b297e6dd5d945d89555bb9af1be333d16a1aed75de349e9.css>; rel=preload; as=style
Via: 1.1 vegur

HTTP/1.1 103 Early Hints
Link: <https://my-app-staging.herokuapp.com/assets/pages/static/application-031d85232775d0f90de513495c11a5c867f975bcb49ab6b8afee3eaae5d1b065.js>; rel=preload; as=script

HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
Content-Type: text/html; charset=utf-8
ETag: W/"a0bd88dbe0de1e5905fafbe7d9319921"
Cache-Control: max-age=0, private, must-revalidate
Set-Cookie: _my-app_session=...; path=/; secure; HttpOnly
X-Request-Id: 29b23d23-de72-411a-88be-b71f53c2f8b7
X-Runtime: 0.011638
Strict-Transport-Security: max-age=31536000; includeSubDomains
Connection: close
Content-Length: 23509

<!DOCTYPE html>
... actual HTML below ...

```

### Desired behavior:

I want cypress to support Early Hints.

### Steps to reproduce: (app code and test code)

https://github.com/yanshiyason/cypress-early-hints-support-feature-request

### Versions

OS: macOS mojave 10.14.2
Chrome: 71
Cypress: Version 3.1.4 (3.1.4)

**Comment by jennifer-shehane** [comment]
Related issue involving content-type https://github.com/cypress-io/cypress/issues/3101 going out in 3.1.5 This error should only display `null` if the `Content-Type` is indeed `null` or the `Content-Type` header is missing or invalid, which seems to be the case when the response is 103 - it has no `Content-Type` header.

Early Hints are [still in the 'Experimental' stage](https://tools.ietf.org/html/rfc8297)

Chromium released tracking of HTTP/2 status code [in 69.0.3453.0](https://chromium.googlesource.com/chromium/src.git/+/d611ebfba50d215d4257ee89b4ef890a016d31b2) to more fully assess implementing support for Early Hints, so it [doesn't look fully supported yet even in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=671310&q=103%20Early%20Hints). 

[Firefox support for Early Hints.](https://bugzilla.mozilla.org/show_bug.cgi?id=1407355)

This will likely be of lower priority to us since even Chromium hasn't fully supported Early Hints.

**Comment by mitar** [comment]
Some background: https://chromium.googlesource.com/chromium/src/+/master/docs/early-hints.md

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not planned currently.

**Comment by mitar** [comment]
Please do not. This is vert important since Chrome disabled HTTP2 push and suggest everyone to use Early Hints:
* https://developer.chrome.com/docs/web-platform/early-hints
* https://developer.chrome.com/blog/removing-push
