### ISSUE TITLE
Disable file watching when running tests headlessly

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#329]
I'm getting an `ENOSPC` error when running my tests headlessly using `cypress ci`. This is generally due to the system reaching it's limit on how many files can be watched. 

Cypress should not be watching any files while running headlessly. 

**Screenshot of Failure**
![screen shot 2016-12-06 at 2 20 06 pm](https://cloud.githubusercontent.com/assets/1271364/20940051/4df4aff0-bbbf-11e6-8c17-226f4a204a45.png)

**Comment by shauvik** [comment]
Fyi, this is currently blocking us because the workaround for increasing the watch limit isn't allowed inside docker (Read only file system for sysctl). `docker build` simply doesn't allow this and with `docker run`, requires `--privileged` option which is undesirable.

[1] http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by brian-mann** [comment]
We'll get a patch out for this asap.

**Comment by brian-mann** [comment]
We will have `0.18.1` tomorrow (Friday) with this fix in it.

**Comment by brian-mann** [comment]
Fixed in [`0.18.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0181-12112016).
