### ISSUE TITLE
Inconsistent behavior in before hooks where Cypress cannot find page element

### ISSUE THREAD

**Issue by Dan195** [cypress-io/cypress#3320]
### Current behavior:

Given a test suite that's run utilizing "Run all specs" button and tested in a Chrome browser, occasionally on a `before` hook, it will not find the elements on the page. This will happen randomly on tests using a `before` hook, but never when running tests individually. 

A recent example of where this happened
```js
before(() => {
    cy.viewport('iphone-6');
    cy.visit(Routes.BaseUrl);
    cy.get('input[name=email]').type(Accounts.Email);
    cy.get('input[name=password]')
      .type(Accounts.Pw)
      .type('{enter}');
});
```

with error
```
CypressError: Timed out retrying: Expected to find element: 'input[name=email]', but never found it.

Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: 'TC31: Ensure correct items ...'
```

### Desired behavior:

The test should consistently get through the `before()` phase or consistently fail the before phase both when testing individually and when testing as a test suite with "Run all specs" button. 

### Steps to reproduce: (app code and test code)

This issue occurs in a relatively large sized test suite that receives many XHR requests upon each page loading.

### Versions

Currently happening in 3.1.5, but happened in previous versions as well.

**Comment by jennifer-shehane** [comment]
Most often in cases of flaky tests, we see that there is not enough assertions surrounding the actions or XHR requests/responses necessary before moving on to the next assertion. So if there is any variation in the speed of the XHR requests response in interactive mode versus run mode, then there will start to be failures in one over the other - or flaky tests. 

So, for example if you had a test to check that when you click a 'Save' button that the users page refreshes with the correct content, you may write a test like so:

```js
cy.get('.name-input').type('Jennifer')
cy.get('form').contains('Save').click()
cy.get('#user- name).should('contain', 'Jennifer')
```

Each command by default will wait 4 seconds to meet it's requirements, but if the POST for the form request *sometimes* takes longer to respond than it takes for the "cy.get('#user- name).should('contain', 'Jennifer')" to run, then it will fail sometimes. Because of this, we recommend asserting on as many required steps as possible - this also helps later to isolate where the exact failure is when debugging on an actual bug. 

So, the example above would be less flaky written like this:

```js
cy.server()
cy.route('POST', 'users/*').as('updateUser')
cy.route('GET', 'users').as('getUsers')

cy.get('.name-input').type('Jennifer')
cy.get('form').contains('Save').click()
cy.wait('@updateUser').then((xhr) => {
expect(xhr.requestBody).to.have.property('name', 'Jennifer')
}
cy.url('contains', 'users/123')
cy.wait('@getUsers')
cy.get('#user- name).should('contain', 'Jennifer') 
```

Now when the last line runs, we don't have to worry about the POST or that the POST sent the right information, that the url changed and the GET's or whatever requests needed to respond - we know it's in the right state to find the content here.

Closing as this is not an issue with Cypress.

**Comment by Dan195** [comment]
If the error is thrown at the first line, then I am struggling to see how the additional assertions in the second example would help. For the error I am receiving, if converted to the second example, it would still fail as cy.get('.name-input').type('Jennifer') as it would never reach the extra assertions.
