### ISSUE TITLE
Assert element NEVER exists ?

### ISSUE THREAD

**Issue by tnrich** [cypress-io/cypress#3355]
I'm trying to assert that an element doesn't exist on the page. 

Normally I'd just do `cy.get(myEl).should("not.exist")` 

In this case however I'm looking for a toast message that leaves the page rather quickly. 

```js
cy.get(myToast).should("not.exist")
```

doesn't work in this case because the test passes either before the toast is on the page, or the toast leaves the page too quickly. 

I want to assert that it NEVER shows up, even if very briefly but am struggling to figure out how to make that assertion.. any ideas?

Thanks!

Here's the actual code in my test just to give a more concrete example: 

```js
it(`should be able to edit a sequence and re-open it from the library without having the sequence re-save
  `, () => {
    cy.upsert(['sequence', 'id name sequence'], {
      name: 'thomas',
      sequenceFragments: [
        { index: 0, fragment: 'tagagtagagtagagtagagtagagtagag' }
      ]
    }).then(([{ id }]) => {
      cy.visit(`/sequences/${id}`);
    });
//edit the sequence
    cy.get('.veStatusBar').contains(`Length: 30`);
    cy.get('.veRowView')
      .focus()
      .type('g', { force: true });
    cy.get(`[id="sequenceInputBubble"] input`).type('gatgagagag{enter}');
    cy.contains('Sequence Inserted Successfully')
      .closest('.bp3-toast')
      .find('.bp3-icon-cross')
      .click();
    cy.contains('Sequence Saving...')
      .closest('.bp3-toast')
      .find('.bp3-icon-cross')
      .click();
    cy.contains('Sequence Saved')
      .closest('.bp3-toast')
      .find('.bp3-icon-cross')
      .click();
//open the library
    cy.contains('.header-link-text', 'Molecules').click();
    cy.contains('.bp3-menu-item', 'DNA Sequences').click();
    cy.get(`[data-copy-text="thomas"]`).dblclick();
//open the sequence again and assert that the sequence doesn't try to re-save
    cy.contains('Sequence Saved').should("not.be.visible") // I want this to fail if the "Sequence Saved" toast ever pops up. Currently it passes even when the "Sequence Saved" toast does pop up
  });
```

**Comment by bahmutov** [comment]
Can you spy on JavaScript method that opens the modal? It would be a lot more reliable than "catching" flash of the popup in the DOM

**Comment by jennifer-shehane** [comment]
This is tricky to test. I think that reviewing our doc on [conditional testing](https://on.cypress.io/conditional-testing) may help you think of some strategies for testing this situation though. 

I will be closing this since issues in our GitHub repo are reserved for potential bugs or feature requests.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of you [paid plans](https://www.cypress.io/pricing) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options.
