### ISSUE TITLE
Cypress can’t type the string ‘hasOwnProperty’ inside any field 

### ISSUE THREAD

**Issue by reno1979** [cypress-io/cypress#3423]
### Current behavior:
When testing out forms with the Big List Of Naughty strings, cypress itself fails to type the string ‘hasOwnProperty’ 

### Desired behavior:
Cypress Should be able to type all strings 

### Steps to reproduce: (app code and test code)

```js
cy.get(‘input’).type(‘hasOwnProperty’); 
cy.get(‘textarea’).type(‘hasOwnProperty’);
```

Nothing happens, workaround: 

```js
cy.get(‘input’).type(‘h’).type(‘asOwnProperty’); 
```

### Versions
Chrome v68
Cypress v3.1.0

**Comment by reno1979** [comment]
Same with these values 

toLocaleString
toString
valueOf 

The JavaScript object prototype functions ....

**Comment by jennifer-shehane** [comment]
Yes, lol, this is happening.

![](https://media.giphy.com/media/457NTDOuMmDfO/giphy.gif)

**Comment by clarmso** [comment]
It is a fun bug lol. The bug is on isSpecialChar and isModifier called from typeChars in packages/driver/src/cypress/keyboard.coffee.

Please note the following behaviour of the Javascript dictionary behaviour:

> modifiers = {alt: false, ctrl: false}
{alt: false, ctrl: false}
> modifiers["alt"]
false
> modifiers["hello"]
undefined
> modifiers["toString"]
ƒ toString() { [native code] }

The last one is not ok.

![whid](https://user-images.githubusercontent.com/1740517/55677703-9c3e4a00-58ba-11e9-941e-34d0372ca328.gif)

Let me see what I can do there.

**Comment by jennifer-shehane** [comment]
@clarmso Let us know if you need any help contributing. Feel free to open a WIP (work in progress) PR that we can help with.
