### ISSUE TITLE
Using assertion outside the test context leads to nasty crash without good message

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#345]
If I use "expect" outside a `describe` block, Cypress 0.18.1 fails to parse the file and shows "no tests found message". It is very unclear to the user why the tests do not start.

It could also related to the "cy.log" command I have added by using #342 
I could not reliably recreate the crash in the self-contained example, but this is the principle

```js
function foo(name) {
  expect(name).to.be.a('string')
}
describe('foo', () => {
  it('works', () => {
    foo('foo')
  })
})
```
Trying to run this breaks Cypress with message "No tests found in your file:" and the following error stack and object arguments (this shows that this is the "expect" assertion crashing)

<img width="699" alt="screen shot 2016-12-14 at 12 09 35 pm" src="https://cloud.githubusercontent.com/assets/2212006/21192371/556b3348-c1f6-11e6-91c9-a46e08dfd03b.png">

<img width="780" alt="screen shot 2016-12-14 at 12 09 53 pm" src="https://cloud.githubusercontent.com/assets/2212006/21192418/7c25f27a-c1f6-11e6-9002-d05fa1a67d9d.png">

**Comment by bahmutov** [comment]
Even a "simple" exception is not caught in the spec.js file, causing confusion. For example
```js
// example_spec.js
throw new Error('nope')
describe('Kitchen Sink', function(){ ...
```
shows 

![screen shot 2017-06-02 at 11 38 30 am](https://cloud.githubusercontent.com/assets/2212006/26733762/d6091218-4789-11e7-8a8e-440b12df2781.png)

At least should advise the user to open dev tools? Or open dev tools automatically...

**Comment by bahmutov** [comment]
Also, it seems this error is linked to https://docs.cypress.io/docs/errors#section-no-tests-found-in-your-file while it is more appropriate to link to https://docs.cypress.io/docs/errors#section-we-found-an-error-preparing-your-test-file

**Comment by brian-mann** [comment]
This is simply an uncaught global exception (which we are not correctly catching). We'll catch errors obviously from within a test but not outside of it.

There's a difference between parse errors and runtime errors. Runtime errors simply lead Cypress to not find any valid tests (since the code bails early) - whereas parse / bundle errors are caught prior to sending down the spec files and can be displayed.

The solution here is simple - catch global uncaught spec errors so we can notify the user there's something wrong with their code.

We already catch global uncaught errors from the application under test, so that same code can be repurposed to catch spec errors.

**Comment by bahmutov** [comment]
agree this is the best long term solution. Double points because it solves problem a new user might have (which are higher priority in my mind)

**Comment by brian-mann** [comment]
The code for this is done, but this has yet to be released. We'll update the issue and reference the changelog when it's released.
