### ISSUE TITLE
Assertion inside test fails, but test doesn't fail

### ISSUE THREAD

**Issue by Atticus29** [cypress-io/cypress#3497]
### Current behavior:
An assertion after a `cy.wait()` fails, but test passes.

### Desired behavior:
Test fails.

### Steps to reproduce: (app code and test code)

This test should work as a standalone.

```js
describe('Standalone temporary test for github issue', function() {
  it('navigates to known bottle nosed dolphin encounter page and re-runs matching, waits ten minutes, and then checks the output of the iaResults from the taskId of the known bottle nosed dolphin encounter github issue version', function(){
    cy.request({
      method: 'POST',
      url: 'https://www.flukebook.org/LoginUser',
      form: true,
      body: {
        username:'tempuser',
        password:'tempuser'
      }
    })
    .then((resp)=>{
      expect(resp.status).to.eq(200);
      cy.log(resp.requestHeaders.cookie);
    });
    cy.visit('https://www.flukebook.org/welcome.jsp');
    cy.url().should('match',/welcome/);
       cy.visit('https://www.flukebook.org/encounters/encounter.jsp?number=5f555acb-1a4a-4753-8313-75464a9b1894');
       cy.get('div[class=image-enhancer-menu]').click();
       cy.get('div[class=menu-item]').contains('start another matching job').click({force: true});
       cy.get('p[id=activeTaskId]', {force: true}).invoke('text').then((theText)=>{
         let bottleNoseTaskId = theText;
         cy.log(bottleNoseTaskId);
         cy.visit('https://www.flukebook.org/iaResults.jsp?taskId=' + bottleNoseTaskId);
         cy.contains('waiting for results').should('exist');
         cy.get('span[class="annot-info-num"]', {force: true}).should('not.exist');
         cy.get('span[class="img-info-type"]', {force: true}).should('not.exist');
         cy.wait(480000);
         cy.visit('https://www.flukebook.org/iaResults.jsp?taskId=' + bottleNoseTaskId);
         cy.get('span[class="annot-info-num"]', {force: true}).should('exist');
         cy.get('span[class="img-info-type"]', {force: true}).should('exist');
         //TODO test passing despite assertion failing!! WTH
       });
   });
});
```

### Versions

Cypress package version: 3.1.3
Cypress binary version: 3.1.3
Google Chrome Version 72.0.3626.96 (Official Build) (64-bit)
MacOS Mojave Version 10.14.3 (18D109)

**Comment by jennifer-shehane** [comment]
Hey @Atticus29, when running this, my test actually passed - and when failing, properly failed. So, I've got a few more questions. 

- Is this failing during `cypress open` or `cypress run`?
- You're selecting Chrome 72 to run it in?

I also see that during the test run, a new tab is opened within the browser. I can guess that this may be causing some issues since the tab with the currently running test would no longer be in focus.

As a side note: Is this page supposed to eventually show results after 'waiting for results'? If so, I would probably rewrite this test to not have a static wait time, but write something like: 

```js
cy.contains('.waiting', 'waiting for results', {timeout: 480000}).should('not.be.visible')
```

**Comment by Atticus29** [comment]
Hi, @jennifer-shehane ! 
I was using cypress open. Should I be using cypress run?

Right now, I'm just testing this stuff from my local machine (eventually, this will be kicked off in circleCI). So, Re: Chrome 72 - that's the current version of my browser (should I be using something different? Is Cypress secretly using something else?)

I've been reading on the cypress site that static waits are not best practice; your suggestion I'm sure will come in handy! Thank you for that!

**Comment by Atticus29** [comment]
@jennifer-shehane if you shorten the cy.wait() to cy.wait(60000), do you then get a failed assertion but a passing test? For that matter, is there any cy.wait() duration that passes the test but fails the assertion?

**Comment by jennifer-shehane** [comment]
Hmm, no @Atticus29, my test always accurately passes or fails even with different wait times. 😢 	

`cypress open` and Chrome 72 should be fine, I just wanted to make sure I was as close as possible to replicating the issue as you have it.

**Comment by Atticus29** [comment]
Hi, Jennifer et al.!
I managed to reproduce my issues as a video. While on a public bus (I was
alone on the bus at list initially; I'm not a monster). Perhaps it will
clarify the issue on my end? I apologize about the sound quality; a
lavalier mic on a bus is not ideal, apparently.
https://youtu.be/LsCm1_5UTB4

Many thanks again,
Mark

**Comment by jennifer-shehane** [comment]
Ok, this reminds me of this similar issue, that we did not get any more info back on: https://github.com/cypress-io/cypress/issues/2720

We've discussed the possibility of why this may happen. From what I remember, Cypress may initially find the element of `cy.get()`, then the element disappears (is removed from the DOM) so that the second part of the assertion fails and retroactively updates that line to be red, but the test still passes. This is just a theory though - that there's some sort of timing situation with how the assertions are run basically. 

One other thing that stands out to me is the fact that you are calling `cy.visit()` with the same url that you are currently navigated to. There was an issue previous to Cypress 3.1.5 that would cause some strange behavior when doing this. https://github.com/cypress-io/cypress/issues/1311 Can you try updating to version 3.1.5 and see if this is resolved?

**Comment by Atticus29** [comment]
Hi, @jennifer-shehane ! I can confirm that the update to version 3.1.5 worked (cypress version says 3.1.5) and the assertion still fails and the test still passes. Thanks for your continued help with this.

**Comment by Atticus29** [comment]
FYI I also get the same unexpected behavior even if I remove that cy.visit() line.

**Comment by Atticus29** [comment]
What other info. can I provide? Anything actionable on my part?

**Comment by MarekJavurek** [comment]
@jennifer-shehane FYI I have similar issue:
![image](https://user-images.githubusercontent.com/405034/53762495-8b1fa900-3ec8-11e9-87c3-1740872ff352.png)
Seems like #2413 looks pretty similar... Thanks for reply.

**Comment by MarekJavurek** [comment]
@jennifer-shehane (sorry for formating - github markdown cant hadle it...)

**more information:**

**support files (commands.js)**

` /* eslint-disable no-undef */

// https://github.com/scottschafer/cypressautomocker
import registerAutoMockCommands from "cypressautomocker-contenttype-fix/include-in-tests";
registerAutoMockCommands();

Cypress.Commands.add("getTestElement", selector => {
  return cy.get(`[data-testid="${selector}"]`);
});

Cypress.Commands.add("loginGui", (user, password) => {
  cy.visit("/login");

  cy.get("#username")
    .type(user)
    .should("have.value", user);

  cy.get("#password")
    .type(password)
    .should("have.value", password)
    .type("{enter}");

  cy.location().should(loc => {
    expect(loc.pathname).to.eq("/");
  });
});

Cypress.Commands.add("login", (user, password) => {
  // as admin
  cy.visit("/");

  cy.window()
    .its("__store__")
    .then(store => {
      store.dispatch({
        status: "success",
        validated: true,
        usernameError: "",
        passwordError: "",
        type: "LOGIN",
        username: user,
        bearer:
          "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFkbWluIiwic3ViIjoiNWJjMDYxYTJiMzFlYzlhM2ZjMjM3OWIwIiwiVG9rZW5UeXBlIjoiQWNjZXNzIiwiUmVmcmVzaFRva2VuSWQiOiI1YzdkODk2ZmZiNzRiZDE0ZmNhMTg1NmUiLCJ1cF92IjpbIjEiLCIxIl0sInR6IjoiQW1lcmljYS9WYW5jb3V2ZXIiLCJ1Y3JzX3YiOiIxIiwidWNyc19jIjoiMSIsInVkZXZfdiI6IjEiLCJ1ZGV2X2MiOiIxIiwidXRsZF92IjoiMSIsInV0bGRfYyI6IjEiLCJ1aW5zdHJfdiI6IjEiLCJ1cHdkX2MiOiIxIiwidXBfYyI6IjEiLCJ1ZnVuX3YiOiIxIiwidWZ1bl9jIjoiMSIsInVudGZfdiI6IjEiLCJ1bnRmX2MiOiIxIiwiY192IjoiMSIsImNfYyI6IjEiLCJjX2NyIjoiMSIsImNfbW5nIjoiMSIsInVmbmRfdiI6IjEiLCJjZm5kX3YiOiIxIiwiY2Nvbl92IjoiMSIsInVjb25fdiI6IjEiLCJjY29uX2MiOiIxIiwidWNvbl9jIjoiMSIsImN0bGRfdiI6IjEiLCJjdGxkX2MiOiIxIiwiY2Rvc192IjoiMSIsImNkb3NfYyI6IjEiLCJjc3NfdiI6IjEiLCJjc3NfYyI6IjEiLCJjaW5zX3YiOiIxIiwiY2luc19jIjoiMSIsImNyZXBfdiI6IjEiLCJleHAiOjE1NTE3OTI2MzIsImlhdCI6MTU1MTc4OTAzMiwiaXNzIjoibG9jYWwuY29yZS5uZHRjbG91ZC5uZXQiLCJhdWQiOiJsb2NhbC5jb3JlLm5kdGNsb3VkLm5ldCJ9.MLFfnNfjoi_1Dx1VGVj_n9UipHSDBtnCdTKsYJLSBxVuwx1dTlTnw-LEDKQiGOqyeADutgoCFUv91tAFLPX-TQ",
        bearerExpiration: "2222-03-04T21:24:15.5963653+00:00",
        refresh:
          "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImFkbWluIiwic3ViIjoiNWJjMDYxYTJiMzFlYzlhM2ZjMjM3OWIwIiwiVG9rZW5UeXBlIjoiUmVmcmVzaCIsIlJlZnJlc2hUb2tlbklkIjoiNWM3ZDg5NmZmYjc0YmQxNGZjYTE4NTZlIiwiZXhwIjoxNTU2OTE1MDU1LCJpYXQiOjE1NTE3MzEwNTUsImlzcyI6ImxvY2FsLmNvcmUubmR0Y2xvdWQubmV0IiwiYXVkIjoibG9jYWwuY29yZS5uZHRjbG91ZC5uZXQifQ.NiEVmfUrGt4oZ6gYO26IYczrflqjBfXRrD6B8zvmLwV-Ln3KDIWukv9cMjRSxNtYY75x7WjIQ3It1pFTlmHo2A",
        refreshExpiration: "2222-05-03T20:24:15.5964479+00:00",
        userSubmitLoginForm: true
      });
    });

  cy.fixture("profile_admin.json").as("profile");
  cy.get("@profile").then(profile => {
    window.localStorage.setItem("profile", JSON.stringify(profile));
  });

  cy.visit("/");
});

Cypress.Commands.add("tableFilterAllPages", () => {
  cy.get("#select-").click();
  cy.get("[role=listbox] li")
    .last()
    .click();
});

Cypress.Commands.add("tableVerifiCount", (rows = null) => {
  cy.tableFilterAllPages();

  cy.get("[class*=MuiTableBody-root-] tr")
    .its("length")
    .then(size => {
      cy.get("[class*=Pagination-rowsLabel-]").should("contain", "of " + size); // "1-3 of 3" or "0 of 0"
      if (rows) {
        cy.get("[class*=MuiTableBody-root-] tr").should($tr => {
          expect($tr).to.have.length(rows);
        });
      }
    });
});

Cypress.Commands.add("goHome", () => {
  cy.getTestElement("Home")
    .eq(1)
    .click();
});

Cypress.on("fail", (err, runnable) => {
  // this helps debugging
  // debugger;
});`

**support files (index.js)**

`import "./commands";

beforeEach(function() {
  // cy.log("users.json loaded");
  cy.fixture("users.json").as("users");
});`

**plugin files (index.js)**

`// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
}`

**cypress.json**

`{
  "video": false,
  "viewportHeight": 660,
  "viewportWidth": 1300,
  "defaultCommandTimeout": 10000,
  "baseUrl": "http://localhost:3000",
  "automocker": {
    "record": true,
    "playback": true
  },
  "testVars": {
    "testMessage": "<b>Test</b> \n\n form message: ĂăĄąĆćČčĎďĐđĘęĚěĹĺĽľŁłŃńŇňŐőŔŕŘřŚśŞşŠšŢţŤťŮůŰűŹźŻżŽžˇ˘˙˛˝ŒœŠšŸŽžƒˆ˜–—‘’‚“”„†‡•…‰‹›€™",
    "apiDelay": 10000,
    "companyIds": [
      { "id": "5c766b8052f072fae8180b10", "instrumentsCount": 3 },
      { "id": "5c766b8252f072fae8180baa", "instrumentsCount": 196 }
    ],
    "manufacturerIds": [
      { "id": "5c766b9952f072fae81811d1" },
      { "id": "5c766b9852f072fae81811be" }
    ]
  }
}`

**Comment by jennifer-shehane** [comment]
@Atticus29 Are you listening to the `Cypress.on("fail"...` event anywhere? In your support / plugin files even?

**Comment by Atticus29** [comment]
@jennifer-shehane yes I am! Interesting!

**Comment by jennifer-shehane** [comment]
If you listen to `Cypress.on("fail"...` and do not later `throw` the error, then the test will display as passing even though it failed, since you did not propogate the error onwards. See [this documentation](https://on.cypress.io/catalog-of-events#Debug-the-moment-a-test-fails) on how to have the test fail.
