### ISSUE TITLE
Alias names fail if they include dots

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#3512]
Cypress 3.1.5

This alias works fine

```js
cy.spy(obj, 'foo').as('foo')
cy.get('@foo')
```

This crashes and burns during `cy.get`

```js
cy.spy(obj, 'foo').as('obj.foo')
cy.get('@obj.foo')
```

<img width="655" alt="screen shot 2019-02-16 at 10 44 23 am" src="https://user-images.githubusercontent.com/2212006/52901927-e3239380-31d7-11e9-9d95-2dffaa773a61.png">

Nice touch: the Command Log shows that spy is actually working, it is just `cy.get` that fails

**Comment by jennifer-shehane** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/4248, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by 6220119** [comment]
Hi @jennifer-shehane , we've come across this issue when trying to wait for an alias-containing-dot of `CyHttpMessages.IncomingHttpRequest` in the latest version (6.2.1) of Cypress. 

Our code looks something like this:
```
  cy.intercept('POST', REQUEST_END_POINT, (req) => {
      req.alias = 'alias-with-dot:image.jpg'
      req.reply(aStaticResponse)
    })
  }

  // trigger the request to be intercepted
  // ...

  cy.wait('@alias-with-dot:image.jpg') // ERROR: Fail to wait for the alias
```

Is this a limitation by design? As it seems to conflict with a feature mentioned in https://github.com/cypress-io/cypress-documentation/issues/1573 (`cy.get("@getList.all")`)

**Comment by jennifer-shehane** [comment]
I don't believe this is by design. The dot in the alias works outside of it being defined in this `req.alias`, so I think it's just an oversight with `cy.intercept()` there. I've opened a new issue here: https://github.com/cypress-io/cypress/issues/14444 if you'd like to comment in there.
