### ISSUE TITLE
Inject an assertion after the request but before the response

### ISSUE THREAD

**Issue by arcdev1** [cypress-io/cypress#3514]
### Current behavior:

It is very common to have the UI display some kind of spinner or loading message while awaiting a response from an API call. Unfortunately, there is currently no way to "pause" a network request so that we can perform assertions before the response is received. The only option is to use a time delay which is flakey and an anti-pattern.

### Desired behavior:

To test this in a non-flaky way, it would be nice to be able to inject an assertion after the event that triggers the request but before the response is received. Something like:

```js
cy.route({
  onBeforeResponse: req => cy.get('[data-test-id=spinner]').should('be.visible') 
 ...
})
```

This would make the state much more deterministic as we would know that the request has been issued but that the response has not yet returned.

It's probably not possible to actually pause a request after it has been issued, but it should be possible to prevent the request from happening until some other event has taken place. For example, this could be implemented internally by wrapping the onBeforeResponse callback in a promise and delaying the request until onBeforeResponse is resolved. That way code like the following would be possible:

```js

cy.route({
  onBeforeResponse: req => cy.get('[data-test-id=spinner]').should('be.visible') 
 ...
}).as('apiCall')
cy.get('#button-that-triggers-apiCall').click()
cy.wait('@apiCall')
cy.get('[data-test-id=spinner]').should('not.be.visible') 
```

### Versions

Cypress: 3.1.5
macOS: Mojave 10.14.2
Chrome: Version 72.0.3626.109 (Official Build) (64-bit)

ref: #687

**Comment by jennifer-shehane** [comment]
Hey @arcdev1, thanks for opening the feature request, this sounds like a good idea. 

As you mentioned, the current workaround is to pass a `delay` to the `cy.route()` like so:

```js
it "shows a loader", ->
  cy.route({
    url: /runs[^\/]/
    response: @runs
    delay: 5000
  }).as("getRuns")
  cy.visit("/#/projects/#{@project.id}")
  cy.get(".loader")
```

**Comment by RyanClementsHax** [comment]
Hello!

Since the deprecation of `route()` in version `6.0.0`, the workaround for this has changed. I figured I would share my solution. I welcome any feedback.

```js
it('displays a loading spinner when loading the resource', () => {
  let resolveReq
  cy.intercept('GET', '/resource', req => {
    return new Cypress.Promise(resolve => {
      resolveReq = resolve
    }).then(req.reply)
  }).as('getResource')
  cy.visit('/')
  cy.get('#spinner')
    .should('be.visible')
    .then(() => resolveReq())
  cy.wait('@getResource')
    .its('response.statusCode')
    .should('eq', 200)
})
```

P.S. Cypress is awsome! I'm having a great time.

**Comment by flotwig** [comment]
This is supported with `cy.intercept()`:

```ts
cy.intercept('/something', (req) => {
  expect(req).to.be.something
  req.continue()
}
```

Closing as supported.

**Comment by joshribakoff-sm** [comment]
@flotwig It doesn't work. Note the OP is asking for `cy.get().should()` and you posted an example that doesn't use that API.

```ts
cy.intercept('/something', (req) => {
     cy.get('[data-testid="skeleton"]').should('exist');
  req.continue()
}
```

All this does is immediately send the request, instead of pausing it like asked. Additionally, the `cy.get()` prints it matched 0 elements, and the `.should()` is effectively ignored.

Could we re-open this? One of the selling points of Cypress is "time travel debugging", but it is painstakingly difficult to do something simple as the OP explained :)

What we're trying to do is wait for a loading indicator prior to sending a mock data to the app. Otherwise, the app can load too fast and Cypress tries to find the loading indicator after the app already loaded.


If I add `delay: 1000` to a mocked request, one of my suites constantly flakes... it seems like if I have tests in the suite that do not await the loading state, the tests run faster than the mock requests are sent, and tests randomly fail and just show a "loading state".

Seems like it's literally impossible to deterministically test a sufficiently complex application w/ Cypress these days. The only workaround I can think of is to bypass `cy.intercept()` completely, and instead use the `window` object to inject a mock service into my application from Cypress... which sort of defeats the point of using Cypress.

The workaround that did work for me and is more in the spirit of the OP's request than the arbitrary delays is https://blog.dai.codes/cypress-loading-state-tests/
