### ISSUE TITLE
Cypress crashes when visiting url

### ISSUE THREAD

**Issue by pipsk** [cypress-io/cypress#352]
`cy.visit('http://www.apple.com/shop/buy-iphone/iphone-7/5.5-inch-display-128gb-black#01,20,31,41,60')`

always crashes cypress. First it redirects to some wrong subset of url and then whole cypress quits

chrome 55 / canary 57 - macOS 10.12.3

**Comment by cezarlz** [comment]
Same happens here: `Uncaught Error: [object Object]`

**Comment by brian-mann** [comment]
@cezarlz Just to clarify - your issue doesn't have anything to do with this one.

This issue is happening because `www.apple.com` has employed a security strategy whereby they detect that their site has been `iframed` and they cause a `window.location.href` change to the `top` frame, which causes Cypress to then change its URL. Once the Cypress URL changes it crashes because its no longer a valid URL and internally we never expect this to happen and internal lookups fail due to `EISDIR: illegal operation on a directory, open`.

What Apple does defeats the point of Cypress, but it doesn't matter. Unless you are an apple engineer working on this page (in which case you could disable this `iframe` check) it shouldn't affect anything. Cypress isn't a solution for navigating throughout the random internet or pages you don't control. It's a tool to test *your* website or web application.

When **you** control your site, you can simply disable these security safeguards the same way you disable lots of things when you're testing (to make it easier to test after all). 

I will keep this issue open as this is a "Known Issue" that Cypress will likely always have. 

It is actually possible for us to detect that this is happening or potentially deploy strategies to combat it. This would involve parsing JS on the fly (using esprima), finding the call site of these functions and then removing them. Its likely to be an expensive operation and complex to find all the various ways you can modify `window.location`. But still, theoretically possible to do.

Another option is to give users `rewrite` rules whereby they can specify requests to rewrite ahead of time.

**Comment by jennifer-shehane** [comment]
This should have been fixed in Cypress [version 2.0.0](https://docs.cypress.io/guides/references/changelog.html#2-0-0)
