### ISSUE TITLE
Offline timeline report

### ISSUE THREAD

**Issue by eric-stanley** [cypress-io/cypress#3543]
### Current behavior:
Once the execution is complete, the user can view the timeline report for the current run, but there is no option for exporting the timeline report for future reference. Would be a good feature if timeline reports can be exported. That way the user does not have to create a cypress account in order to view the timeline report

### Desired behavior:
Option for exporting the report from the current run would be helpful (or) another option would be saving the files locally, so that it can be retrieved from a localhost port

### Versions
3.1.5

**Comment by jennifer-shehane** [comment]
Hey @eric-stanley, I want to make sure we understand your request. By 'timeline report', do you mean the Timeline view from the Dashboard - like pictured below?

![](https://docs.cypress.io/img/guides/parallelization/timeline-view-small.befee192.png)

**Comment by eric-stanley** [comment]
Yes ma'am. Thats correct.

**Comment by jennifer-shehane** [comment]
cc @trydionel

**Comment by jennifer-shehane** [comment]
cc @cypress-io/services

**Comment by trydionel** [comment]
Hi @eric-stanley,

Thanks for opening this issue. We were just discussing some revisions to the timeline view, so we can definitely add data exporting to the list! Can you answer a couple of follow-up questions for me?

* What sort of data format are you looking to export? Do you need the "raw" data? Or the rendered visualization?
* Can you share a little more about the use case you have for this export? I'm particularly curious to know more about the users that could make use of this data, but wouldn't have a Cypress account otherwise.

**Comment by eric-stanley** [comment]
Hi @trydionel,

Question # 1: The rendered visualization. More like an option to export results to a local folder with the index.html file and the necessary components in the same folder, so that the same visualization works offline (or) setting a flag during runtime/config with the export path, so that all results are recorded in the specified path for future reference (More like all runs view in the cypress dashboard)

Question # 2: 
Use case # 1: Export timeline report
Pre-requisite: Execution of the current run is complete
   Step 1: User selects the export option in the timeline report
   Step 2: User provides export path and saves the report
   Step 3: Exported report should be saved to a folder with the given name
   Step 4: User opens the index.html file in the folder and the timeline report should be opened (all links in the report should be relative and data for the report can be from .xml or .json for third party use)

Use case # 2: Save timeline reports
Pre-requisite: None
   Step 1: User executes tests with 'save results' option enabled (or added config to save results) in a defined path
   Step 2: Once the execution is complete, the user should be able to view the timeline report with history of previous runs with links as relative paths (all links in the report should be relative and data for the report can be from .xml or .json for third party use)

Let me know if you need more details or if anything is not clear. Happy to explain!

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.
