### ISSUE TITLE
cy.visit a page with a dash doesn't work

### ISSUE THREAD

**Issue by haikyuu** [cypress-io/cypress#3554]
### Current behavior:

![image](https://user-images.githubusercontent.com/8558836/53169887-d8ee0480-35de-11e9-97c1-a30aa7f83ef6.png)

### Desired behavior:

Should visit the page properly

### Steps to reproduce: (app code and test code)

https://github.com/haikyuu/cypress-test-tiny

`cy.visit('http://harley-davidson.com')` doesn't work for instance
### Versions

cypress: 3.1.5
OS: macOS
browser: Chrome 72

**Comment by jennifer-shehane** [comment]
Hey @haikyuu, 

1. The shown screenshot does indeed result in a 404 because the url `http://remote-ok.com/` responds with a 404 status. Cypress fails on any status code other than `2xx` and `3xx` by default, you can ignore this logic by setting [`failOnStatusCode` to `false`](https://on.cypress.io/visit#Arguments) ie: `cy.visit('http://remote-ok.com', { failOnStatusCode: false })` 

<img width="1151" alt="screen shot 2019-02-21 at 9 36 01 pm" src="https://user-images.githubusercontent.com/1271364/53178767-e4fab600-3620-11e9-92fa-46ed35c9f61a.png">

2. The visit to `http://harley-davidson.com` is failing due to an uncaught exception being thrown on the website upon visiting. Cypress is a bit opinionated when it comes to failing when there are issues with the website itself. You can prevent Cypress from failing by adding the following code:

```js
Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false
})


describe('', () => {
  it('Healthcheck ', () => {
    cy.visit('http://harley-davidson.com')
  })
})
```

<img width="1151" alt="screen shot 2019-02-21 at 9 32 56 pm" src="https://user-images.githubusercontent.com/1271364/53178927-2be8ab80-3621-11e9-91cd-4e29d42eee79.png">
