### ISSUE TITLE
Fix pre-push hook

### ISSUE THREAD

**Issue by Saibamen** [cypress-io/cypress#3560]
I don't know it runs correctly on Linux, but on Windows I can't push commits without `--no-verify` param

![obraz](https://user-images.githubusercontent.com/905878/53119191-c9bb7800-3546-11e9-8cce-ac6dbc7662e9.png)

https://github.com/cypress-io/cypress/blob/develop/package.json#L41

**Comment by flotwig** [comment]
Could be an issue in [bahmutov/stop-only](/bahmutov/stop-only). IIRC, it uses `grep` to find all the `.only`'s, so maybe there's some command-line difference between `grep` on Windows and other systems.

**Comment by bahmutov** [comment]
Maybe skip local pre-commit hook with “-n” option?

**Comment by Saibamen** [comment]
@bahmutov: only `--no-verify` works

**Comment by bahmutov** [comment]
Oh right ! You want to skip pre-push hook

**Comment by w0wka91** [comment]
This gets actually quite annoying for someone who is developing on Windows. You're able to skip the hook with `--no-verify` but then you're not able to benefit from all of the lint features!

I already looked into the stop-only source code but I wasn't able to fix it properly. Maybe another option would be to use https://github.com/levibuzolic/eslint-plugin-no-only-tests instead of stop-only?!

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
