### ISSUE TITLE
Running Cypress with different OSX users on the same machine

### ISSUE THREAD

**Issue by Nateu** [cypress-io/cypress#358]
I've multiple users on my MacBook and although I won't be running cypress simultaneously I'd like to run it with different users logged in.
Starting the Cypress applications works fine. But when I try to open a project with the user that didn't install the application it gives an error:

<img width="803" alt="screen shot 2016-12-22 at 17 28 56" src="https://cloud.githubusercontent.com/assets/4865667/21432495/28908fa4-c86c-11e6-97fd-cf0bc32ca041.png">

My guess it's a filesystem permission issue where the owner is user A and not user B who actually tries to open the project.

For now I'm working with a second application (manual download and renamed) which works fine so far. :)

**Comment by Bkucera** [comment]
With CLI binary cache, released in [`3.0.0`](https://docs.cypress.io/guides/references/changelog.html#3-0-0), I suspect this won't be as much of an issue, since the Cypress binary will be installed to a global cache directory with `npm install cypress`. 
You can modify permission/ownership of the cache folder or change the location of the cache folder to a shared location with `export CYPRESS_CACHE_FOLDER="/home/some/shared/location` if you want.
I believe you can set permissoins with `chmod 777 /path/to/cypress/cache/folder`
