### ISSUE TITLE
electron won't run test in headless/test runner

### ISSUE THREAD

**Issue by nikhilesh009** [cypress-io/cypress#3615]
I am trying to run a simple test in cypress 
```js
describe('Booking', function() {
  beforeEach(function() {
    cy.myLogin();
  });

  it('Booking verification', () => {
    cy.visit('http://testexmapleurl.com');
  });
});
```
when i execute in chrome it works fine but when i run in electron it doesn't work at all 

getting error message 

<img width="585" alt="screenshot 2019-02-28 at 16 01 12" src="https://user-images.githubusercontent.com/40767850/53575644-43201f80-3b72-11e9-8356-0249bd6aadaa.png">

there is no issue with the token, it same test work using chrome
it happened when running in Jenkins too,

is it possible to chrome headless i have tried to work around whatever suggestion was in github 
but nothing helped.

**Comment by jennifer-shehane** [comment]
Hey @nikhilesh009, I would suggest running this test locally and choosing Electron from the dropdown to run the test within. 

<img width="224" alt="screen shot 2019-02-28 at 11 23 09 am" src="https://user-images.githubusercontent.com/1271364/53581271-43f18b00-3b4b-11e9-8d18-42168c6933ac.png">

From within here, open the devtools and see where this error is originating from. It may be due to it running on an older Chromium version. 

Alternatively, I'd suggest turning off listening for uncaught exceptions as described in the error message: https://on.cypress.io/uncaught-exception-from-application

**Comment by nikhilesh009** [comment]
I have tried locally too, it doesn't work. but work for chrome 
https://on.cypress.io/uncaught-exception-from-application , i have tried that too but it doesn't show any error.but  even don't run the test

![image](https://user-images.githubusercontent.com/40767850/53582794-7cf82280-3b80-11e9-9ef2-cdc0e9553858.png)

**Comment by jennifer-shehane** [comment]
@nikhilesh009 I'm a little unclear. Are you saying that the error does throw when running locally on Electron? Did you open the dev tools when this error is thrown? Can I see a screenshot of that?

Besides that, this will be quite difficult to debug without a reproducible way to run this on our side.

**Comment by nikhilesh009** [comment]
it throws error locally and headless too, 
I fixed my problem, i am using chrome headless and locally, but spent a whole day to figure it out why the electron is not working, couldn't find any solution  
![image](https://user-images.githubusercontent.com/40767850/53663979-7e504a80-3c67-11e9-83c5-d66152bbf204.png)

**Comment by jennifer-shehane** [comment]
Yeah, I would try clicking through the stack trace. We won't be able to help any more without a reproducible example.

**Comment by nikhilesh009** [comment]
I understand that, i will try to find reproducible example and get back to you,but good thing is that I can run chrome I. Jenkins :smile: I'm happy with that
