### ISSUE TITLE
Parallelization on Mac

### ISSUE THREAD

**Issue by tbell511** [cypress-io/cypress#3676]
It is possible to utilize parallel tests outside a CI? I just want to run them on my computer for simplicity.

Thanks!

**Comment by jennifer-shehane** [comment]
Hey @tbell511, Yes - you can run `cypress run` multiple times within separate terminal windows. In order to associate each terminal window to the same 'run', you will want to pass in the [same `--ci-build-id` flag](https://on.cypress.ioparallelization#Linking-CI-machines-for-parallelization-or-grouping) for each instance. This can be any ID you make up. Normally this would be automatically generated when run in CI. 

**However**, you will quickly run into performance limitations since running multiple instances of Cypress - all running Chrome testing your application - will use up a *lot* of CPU. It may be good to run 2 terminal windows or playing around with some experimentation with parallel settings, but all of the tests will begin to slow down significantly after that. 

It's best to run in isolated CI environments with enough CPU to handle each run.

Just to note, for the future, issues in our GitHub repo are reserved for potential bugs or feature requests.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of you [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options.

**Comment by tbell511** [comment]
@jennifer-shehane Thanks for the response! Yes, I waited long as possible before posting here :) I exhausted all other options, including the chat, but never could get a response.  I know you and the team are very busy so thanks for taking the time to answer!
