### ISSUE TITLE
cy.visit uncaught error: [object Object] in some domains

### ISSUE THREAD

**Issue by cezarlz** [cypress-io/cypress#368]
In some URLs, using the `visit` method I receive a error from cypress terminal. The URL hasn't errors in its console.

![image](https://cloud.githubusercontent.com/assets/954889/21693942/0ab5d530-d36a-11e6-924d-8af685bc45d2.png)

Text version:

```
➜  cypress-test cypress run

Started video recording: /Users/cezar/Web/cypress-test/cypress/videos/pqw4g.mp4

  (Tests Starting)


  General Tests
    1) body should be visible


  0 passing (3s)
  1 failing

  1) General Tests body should be visible:
     Uncaught Error: [object Object]
      at createErrFromMsg (http://rabbitmq.magicbox/__cypress/static/js/cypress.js:1520:18)
      at $Cypress.Cy.$Cy.onUncaughtException (http://rabbitmq.magicbox/__cypress/static/js/cypress.js:1527:17)
      at $Cypress.window.$Cypress.$Cypress.onUncaughtException (http://rabbitmq.magicbox/__cypress/static/js/cypress.js:94:44)




  (Tests Finished)

  - Tests:           1
  - Passes:          0
  - Failures:        1
  - Pending:         0
  - Duration:        3 seconds
  - Screenshots:     1
  - Video Recorded:  true
  - Cypress Version: 0.18.4


  (Screenshots)

  - /Users/cezar/Web/cypress-test/cypress/screenshots/General Tests -- body should be visible.png (2560x1440)


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  /Users/cezar/Web/cypress-test/cypress/videos/pqw4g.mp4 (2 seconds)


  (All Done)
```

Page Console:

![image](https://cloud.githubusercontent.com/assets/954889/21693997/4b55ce42-d36a-11e6-97ba-b1db3862960f.png)

**Comment by cezarlz** [comment]
Hi @brian-mann!

We saved our HTML and put on CodePen the files and assets. The public URL is: http://s.codepen.io/CezarLuiz0/debug/GrJpKj/GnMnbnvYWWbM

The cypress test that I'm using: 
```js
describe('test', () => {
  context('test', () => {
    it('test', () => {
      cy.visit('http://s.codepen.io/CezarLuiz0/debug/GrJpKj/GnMnbnvYWWbM');
    });
  });
});
```

Take a look, the cypress is very simple.

I ran the test from CodePen again and the same error is happening. 

![image](https://cloud.githubusercontent.com/assets/954889/21718177/d5e06922-d3fc-11e6-8d50-3dc22b4ff352.png)

The full code you can view here: https://gist.github.com/cristopher-rodrigues/9574276344f1b27c45effa9e36cb07fc

**Comment by brian-mann** [comment]
Okay I spent some time debugging this.

This doesn't appear to be a bug in Cypress - rather it is a bug in your library code. Your lib code is incorrectly invoking `window.onerror` - which is what Cypress is bound to for uncaught exceptions.

It is calling it with an invalid argument signature. It's passing an `Event` instance and then a regular object literal as the 2nd argument. This does not match what is `onerror` should be invoked with: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

When Cypress attempts to stringify the arguments you send it - it is unable to, which is why you get `[object Object]`. I don't think we can account for this situation because it really makes no sense. The second argument should be a `source` string, and the first argument needs to be an `error` instance. 

However, what I'm describing is really just a display issue, it has nothing to do with **why** your application is calling `onerror` to begin with. If you run Cypress in the GUI you can put a breakpoint where the oncaught exception happens and dig through the stack trace - you will find your application throwing it. Because you've provided minified code I can't really tell what's going on.

Cypress is simply notifying you that `onerror` was invoked, the real root cause is somewhere in your application. Invoking `onerror` incorrectly is really the 2nd problem.

**Comment by brian-mann** [comment]
Per your screenshot of your dev tools console, it appears sammy is throwing the error due to it receiving a 404 on some XHR request.

**Comment by brian-mann** [comment]
Related to https://github.com/cypress-io/cypress/issues/254 with the ability to turn off uncaught error handling.
