### ISSUE TITLE
Uncaught AssertionError: Env not set,  aborting run

### ISSUE THREAD

**Issue by chirag-autodesk** [cypress-io/cypress#3710]
Everytime i try to run my cypress test i am getting this error:

```
Uncaught AssertionError: Env not set,  aborting run

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
Check your console for the stack trace or click this message to see where it originated from.
```

**Comment by jennifer-shehane** [comment]
Hey @chirag-autodesk, it seems that something from within your application has an uncaught exception - is you believe that this is not the case and that this is an issue with Cypress, you will need to provide the app and test code to reproduce it, otherwise we will unfortunately have to close this issue. Thanks!

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
