### ISSUE TITLE
visit() does not send user agent header as specified 

### ISSUE THREAD

**Issue by Songyu-Wang** [cypress-io/cypress#3719]
### Current behavior:

With the new feature in 3.2.0 that enables setting headers for `visit()`, "user agent" header is not correctly passed to server side 

### Desired behavior:

user agent header can be passed to server side as specified 

### Steps to reproduce: (app code and test code)
Using the following code: 
```js
cy.visit({
      url: '/',
      headers: {
        'User-Agent': 'bad browser',
        'hello': 'hi'
      }
    })
```
And observe server side receives something like this:
![image](https://user-images.githubusercontent.com/36670132/54451060-2d346200-470f-11e9-8a8f-9ebb22da85f1.png)

As shown above, header "hello" is correctly passed, therefore the header setting is recognized by cypress. However, header "User-Agent" is still my real browser which is the error  

### Versions

cypress 3.2.0

**Comment by flotwig** [comment]
It's probably because the UA header gets clobbered in two places in `request.coffee`:

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/request.coffee#L267  
https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/request.coffee#L328

From a first glance, it looks like this is just Cypress trying to pass along the UA of the browser with the request. It'd probably be safe to change these lines to have ` and !headers["user-agent"]` or similar to allow UA to be overridden.

Need to make sure we're normalizing headers to be lowercase before that can happen.

**Comment by jennifer-shehane** [comment]
You can set the `userAgent` as a configuration value in your `cypress.json` file - https://on.cypress.io/configuration#Browser

There's some explanation on why we implemented it this way here: https://github.com/cypress-io/cypress/issues/364

headers lowercase issue: https://github.com/cypress-io/cypress/issues/2879

**Comment by jennifer-shehane** [comment]
After further discussion - we should probably also at least handle warning the user when passing a User-Agent header that there is another way to implement this (if not change the implementation to work altogether), so we reopened.
