### ISSUE TITLE
Cannot recognize superdomain with multiple levels subdomain

### ISSUE THREAD

**Issue by yangliurea** [cypress-io/cypress#380]
Our url is xxx.xxx.xxx.com.au, before each test case, all the cookies under xxx.com.au should be clean, but they are always there, I tried using cy.clearCookies, but didn't work.

**Comment by brian-mann** [comment]
I've investigated this, and the problem is fairly simple but the solution will take a bit of work.

Basically we need to be as intelligent as the browser itself when parsing apart the domain into `tld`. The problem is that `tld` list is always changing, and browsers are constantly having to keep in sync with the latest lists, which we will also have to replicate.

So to do this "right" we're going to have to move logic out of the driver and make async calls to the backend to parse it correctly.

This will require some internal API changes since we synchronously parse URL's all over the place in the driver.

**Comment by brian-mann** [comment]
Released in [`1.4.2`](http://localhost:2222/guides/references/changelog.html#1-4-2).
