### ISSUE TITLE
Cannot test Magento 2 with caching enabled

### ISSUE THREAD

**Issue by paul-gene** [cypress-io/cypress#3813]
I am trying to setup some tests for a fresh Magento 2 installation (with sample data).

However, with all the caches enabled, when I add a product to the cart, I get a Magento error stating "Invalid Form Key".

If I disable the full page caching, the test works, but obviously, page loads take much longer.

Has anyone encountered this before, or does anyone have insight on testing Magento with Cypress, with caching enabled?

**Comment by jennifer-shehane** [comment]
Hey @paul-gene, if you believe this is a bug on Cypress side, we'll need the code to reproduce the issue. Otherwise, issues in our GitHub repo are reserved for potential bugs or feature requests.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Alternatively, signing up for any of you [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options.

**Comment by paul-gene** [comment]
I believe it is an issue with Cypress.

To reproduce, you will need a fresh installation of Magento, with caching enabled, something of a big ask just to test this.

**Comment by princefishthrower** [comment]
@paul-gene - I'm running into the same issues, though for the customer signup form. For me, even after disabling full page caching, i.e. issuing:

`php bin/magento cache:disable full_page`

the error is still coming. Did you ever run into this or do you have some pointers?

**Comment by melvinio** [comment]
@paul-gene , I've got a small workaround by adding a random number at the end of the url. like my example below. hope this helps for you.

const randomNumber = () => Cypress._.random(0, 10000);
cy.visit('https://www.mywebshop.com/productpage'  + '?' + randomNumber())

it's result is then like this: https://www.mywebshop.com/productpage?1353 etc, (uncached page).

Good luck!
