### ISSUE TITLE
How to select visible element?

### ISSUE THREAD

**Issue by paul-gene** [cypress-io/cypress#3819]
My page contains 3 copies of a button element, either of which may become visible and clickable (the other 2 stay hidden and disabled)

How can I get just the visible button?

**Comment by jennifer-shehane** [comment]
You should be able to use the [`:visible` selector](https://api.jquery.com/visible-selector/). `cy.get('button:visible')`.

In the future, issues in our GitHub repo are reserved for potential bugs or feature requests.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of you [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options.

**Comment by paul-gene** [comment]
I tried using that selector, and it doesn't work. Hence opening the issue.

If you want people to use your community chat, please link it via the README, for visibility.

FYI these kinds of questions are also easily avoided if your documentation was any good.

The section about assertions in particular is very poor and provides pretty much zero useful information.

EG your docs state assertions can be used with either `expect` or `should` - however, no `expect command exists in your documentation, only `should`.

The docs then go on to use `expect` in the examples - this makes no sense because of the issue mentioned above.

So, using `should` for an `exist` assertion, maybe it would be `should().to.exist` (replacing `expect` with `should`, because again, `expect` is not in the command list)

BUT its not that, it's `should('exist')`.

**Comment by jennifer-shehane** [comment]
We'll need the html you are testing against in order to narrow down why `cy.get('button:visible')` is not working. Can you provide an example of the html you are testing?

Our community chat is the very first thing linked in our issue template when opening an issue. We don't have the resources to answer every question about how to use Cypress unfortunately, which is why we rely on our amazing community.
```
<!-- Is this a question? Don't open an issue. Ask in our chat https://gitter.im/cypress-io/cypress-->
```

Sorry to hear the documentation has not been helpful for you. `expect` assertions come from mocha and `.should()` are a construct of cypress to make chaining assertions easier. I'd recommend reviewing [this section](https://on.cypress.io/introduction-to-cypress#Writing-Assertions) for a more thorough explanation of the difference between the two - and also reading the [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) in general before getting started.

Our [docs](https://github.com/cypress-io/cypress-documentation) are open source also, so contributions are welcome when it is not clear. Thanks for the feedback.

**Comment by AmazingJaze** [comment]
@jennifer-shehane , unless I am mistaken, the selector `:visible` that you suggested, doesn't work if an element has opacity 0 or visibility hidden, right? That's how jQuery's `:hidden` selector works but what I'd really like to see is a way to select only the elements within a collection that adhere to [Cypress' definition of visibility ](https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Visibility)

On a page where I have 3  
```HTML 
<span class="sortingIndicator-asc"> 
```
elements, and 2 of which have css style ` visibility:hidden` I want a way to select and assert that  
```javascript
cy.get(.sortingIndicator-asc)..should("have.length, 1")
```

**Comment by AmazingJaze** [comment]
updated code snippet for correctness.

**Comment by nikitahl** [comment]
@AmazingJaze that assertion didn't work for me, however, this one did, I'm using own selector:
```
  cy.get('.vce-button--style-basic')
    .should('be.visible')
    .its('length')
    .should('be.eq', 1)
```

**Comment by jennifer-shehane** [comment]
@AmazingJaze To use Cypress' internal definition of visibility you can use `Cypress.dom.isVisible($el)` documented here: https://on.cypress.io/dom#Is-visible

```js
cy.get('img').then(($el) => {
  Cypress.dom.isVisible($el) // true
})
```

**Comment by sorayaM** [comment]
Is there a way to tell cypress from which of all the found elements to focus on? like say the cy.get() and all the following nesting of specifications still throws you at least 5 essentially identical elements... can you tell cypress to focus on the nth incidence?

**Comment by cyrus-eh** [comment]
@sorayaM You can **chain** `.first()` or `.eq()` to select an element. 
Ex: `cy.get("[data-cy=box]").eq(0)`  will select the first non-unique element.

**Comment by sorayaM** [comment]
@cyrus-eh thanks a lot!

**Comment by simonwebdev000000001** [comment]
another case, i have a list of children, like ul > li, there are over 20 li, and not all of them available on the view, so when loading all li cy.get("ul li") cypress focusing to the middle of the ul, and my cy.get("ul li").eq(0) throwing an error `Timed out retrying: cy.click() failed because this element is not visible:`

**Comment by JessefSpecialisterren** [comment]
@AmazingJaze [wrote](https://github.com/cypress-io/cypress/issues/3819#issuecomment-517406645):
> unless I am mistaken, the selector `:visible` that you suggested, doesn't work if an element has opacity 0 or visibility hidden, right? That's how jQuery's `:hidden` selector works but what I'd really like to see is a way to select only the elements within a collection that adhere to [Cypress' definition of visibility ](https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Visibility)

Turns out [Cypress overwrites the visible/hidden logic of the included jQuery with its own](https://github.com/cypress-io/cypress/blob/1ac7c49d4eb2c86df492bce18ed216d5e65b3617/packages/driver/src/config/jquery.js). As a consequence, `cy.get(':visible')` and `.should('be.visible')` and their `hidden` counterparts all follow [Cypress' definition of visibility ](https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Visibility). I've opened https://github.com/cypress-io/cypress-documentation/issues/3243 to update the documentation with this information.

@AmazingJaze not sure if you're still active, but it's worth a try: could you perhaps edit your comment to include (a link to) this information? This issue is the first hit on google for `cypress get visible elements`, so you might save some people time and confusion 😊

**Comment by bubooon** [comment]
> @AmazingJaze To use Cypress' internal definition of visibility you can use `Cypress.dom.isVisible($el)` documented here: https://on.cypress.io/dom#Is-visible
> 
> ```js
> cy.get('img').then(($el) => {
>   Cypress.dom.isVisible($el) // true
> })
> ```

It looks like if we can see only part of the element then it will return false, am I right?

**Comment by talyh** [comment]
Assuming Cypress's definition of visibility are sufficient for you, filtering the `get` result based on visibility will select the element(s) visible. (If there's more than one result, you may need to chain further filters/functions to specialize the result until you get to the single element you want to interact with).

```javascript
   cy.get('your-selector-that-matches-both-visible-and-hidden-elements').filter(':visible')
```

**Comment by andrewbien** [comment]
> Assuming Cypress's definition of visibility are sufficient for you, filtering the `get` result based on visibility will select the element(s) visible. (If there's more than one result, you may need to chain further filters/functions to specialize the result until you get to the single element you want to interact with).
> 
> ```js
>    cy.get('your-selector-that-matches-both-visible-and-hidden-elements').filter(':visible')
> ```

Thank you @talyh, It worked for me 💯

**Comment by bahmutov** [comment]
I have added an example of filtering by visibility to https://glebbahmutov.com/cypress-examples/6.5.0/commands/traversal.html#visible-elements

```html
<ul class="visible-items">
  <li>first</li>
  <li style="display:none">second</li>
  <li style="display:none">third</li>
  <li>fourth</li>
</ul>
```

```js
cy.get('.visible-items li')
  .should('have.length', 4) // all LI items
  .filter(':visible')
  .should('have.length', 2) // only 2 visible LI items
```

**Comment by haroldo-ok** [comment]
This is the code that worked for me:

```javascript
getVisibleElement (selector, filter) {
  if (isString(selector)) {
    selector = cy.get(selector)
  }

  const predicate = isString(filter) ? $el => $el.matches(filter) : filter

  return selector.filter((index, $el) => {
    return predicate($el) && Cypress.dom.isVisible($el)
  }).first()
}
```

**Comment by cjcrandall** [comment]
@bahmutov what would be the functional difference between these two examples?

1. `cy.get('.visible-items li:visible').click();`
2. `cy.get('.visible-items li).filter(':visible').click();`

From problems that we're having and seeing other peoples' struggles in this thread and [others](https://stackoverflow.com/questions/54574494/how-do-i-get-cypress-just-to-process-the-visible-element), there seems to be a difference in behavior that I can't wrap my head around.

**Comment by bahmutov** [comment]
I prefer the first variant that uses a single command rather than splitting them into two commands (see the https://on.cypress.io/retry-ability for the reasoning)

**Comment by godfreyyeung** [comment]
Leaving this note in case it helps anyone: from my testing it seems that instead of asserting the length of visible elements, you can assert the entire array of elements is visible.
So instead of this (which wasn't working for me)
```
 cy.get('tbody:visible').should('have.length', 10);
```
I used
```
cy.get('tbody').should('be.visible');
```
If any one of the multiple `tbody` is not visible (`display: none`, etc), then the assertion correctly fails. 

Of course, it also works for the opposite.
```
cy.get('tbody').should('not.be.visible');
```
If any one tbody is visible, the assertion correclty fails.

**Comment by gregor-veal** [comment]
It’s all here https://maven-failsafe-pluginenr.github.io/chesney64/

**Comment by gregor-veal** [comment]
It’s all here https://maven-failsafe-pluginenr.github.io/chesney64/
