### ISSUE TITLE
Cypress 3.2.0 under Manjaro Linux fails with libnode.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by marinakuranda** [cypress-io/cypress#3878]
Hello friends, thank you for Cypress, I'm experiencing an issue with the latest update.

Any advice on fixing this?

### Current behavior:

```
> @ open /.../tests/
> cypress open

It looks like this is your first time using Cypress: 3.2.0

 ✖  Verifying Cypress can run /home/username/.cache/Cypress/3.2.0/Cypress
   → Cypress Version: 3.2.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.
----------

/home/username/.cache/Cypress/3.2.0/Cypress/Cypress: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory
----------

Platform: linux (Ubuntu Linux - )
Cypress Version: 3.2.0
```

### Desired behavior:

Cypress should open the UI.

### Steps to reproduce: (app code and test code)

- Install Cypress under Manjaro Linux.
- Run the open command.

### Versions

Cypress v3.2.0

```
   Static hostname: name
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: ...
           Boot ID: ...
  Operating System: Manjaro Linux
            Kernel: Linux 4.19.13-1-MANJARO
      Architecture: x86-64
```

**Comment by jennifer-shehane** [comment]
I'm seeing this same error pop up in some of Electron's issue threads, but didn't find a solution (although libnode is not used in Electron 4+)

@Bkucera @flotwig ideas?

**Comment by flotwig** [comment]
That's kind of a strange error, since we bundle `libnode.so` with Cypress when we publish the binary. I have some ideas to gather more information.

@marinakuranda Can you check some things? Do you have `libnode.so` in `/home/username/.cache/Cypress/3.2.0/Cypress`? If not, you might want to try deleting `/home/username/.cache/Cypress/3.2.0` and reinstalling. Perhaps the unzipping got interrupted.

If you do indeed have `/home/username/.cache/Cypress/3.2.0/Cypress/libnode.so`, can you run `ldd` to check that the correct `libnode.so` is being linked to? 

You should be able to do this:

```
ldd /home/username/.cache/Cypress/3.2.0/Cypress/Cypress | grep libnode
```

And receive this:

```
	libnode.so => /home/username/.cache/Cypress/3.2.0/Cypress/libnode.so (0x00007f7800ddd000)
```

If not, something is wrong.

**Comment by marinakuranda** [comment]
Thank you very much! Deleting cache and reinstalling Cypress helped!
