### ISSUE TITLE
Cypress unit test for a component which depends an event from out side of the component

### ISSUE THREAD

**Issue by vijeeshvofox** [cypress-io/cypress#3893]
I have a component which contains drop down. The values on the drop down is filled based on the `click` event of the page tab. The page tab is outside of this component. So we have the source code to emit the event from page tab to the component

`this.$router.app.$emit('RefreshCategories', 'blog');`

on the component we listen an event using below source code

```js
public mounted() {
  this.$router.app.$on('RefreshCategories', (data: any) => {
    this.GetCategories(data);
  });
}
```

The method `GetCategories(data)` fills data to the dropdown on the component. I am using vue js and Cypress. This is working correctly on my browser. I want to do unit test for this component using cypress.

Is it possible to do unit test for this component? Because this component depends an event from out side of this component.

Can we trigger the `emit` event from cypress during test?

**Comment by jennifer-shehane** [comment]
@vijeeshvofox Please look into the `vue-unit-tests` plugin: https://github.com/bahmutov/cypress-vue-unit-test

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of you [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options.
