### ISSUE TITLE
Can't chain negative `cy.should()` with a `.find()`

### ISSUE THREAD

**Issue by Kocal** [cypress-io/cypress#3917]
Hi :)

I'm having an issue while trying to using `.find()` after a negative assertion on an attribute.

### Current behavior:

![Sélection_517](https://user-images.githubusercontent.com/2103975/55782699-277f3180-5aad-11e9-8051-9bd2e87fc4a7.png)

### Desired behavior:

Using `cy.get('...').should('not.have.attr')` should yield the current element, like `cy.get('...').should('have.attr')` does.

![Sélection_516](https://user-images.githubusercontent.com/2103975/55782682-1d5d3300-5aad-11e9-9a71-fb3f7a8f56dd.png)

### Steps to reproduce: (app code and test code)

I've created [a repo](https://github.com/Kocal/cypress-issue-should-not-have-attr) that reproduce the issue.

You fill wind everything here https://github.com/Kocal/cypress-issue-should-not-have-attr/commit/9947ed8d67ffe9877d275787d1b167f8544535e5

### Versions

- Cypress: 3.1.5 and 3.2.0
- OS: Debian 9.8 (Stretch)
- Browser: Electron 59, the one packaged with Cypress

---

Thanks! :)

**Comment by Kocal** [comment]
Well, in fact I don't know if it's really a bug or a requested feature, because the [docs](https://docs.cypress.io/api/commands/should.html#Yields) says:

> In most cases, `.should()` yields the same subject it was given from the previous command.

> However, some chainers change the subject.

:man_shrugging:

**Comment by jennifer-shehane** [comment]
Yeah, I think the difference is the use of 3 arguments versus 2 arguments. 

```
 // works
.should('have.attr', 'data-sorted', 'desc') 
```

```
 // doesn't work
.should('not.have.attr', 'data-sorted') 
```

This second example changes the subject to the 'data-sorted' attribute, because you can usually further chain. 

```
 // works
.should('have.attr', 'data-sorted').and.match('/desc/)
```

I think the fact that the first example with 3 arguments is a bit weird that it returns the DOM element, but this comes directly from [Chai jQuery's implementation](https://github.com/chaijs/chai-jquery#assertions). 

We will not be changing this implementation at this time, so will close this issue. We may reconsider reopening depending on the amount of feedback wanting this feature in the future.
