### ISSUE TITLE
Passing parameters to cypress using cli

### ISSUE THREAD

**Issue by krishvv** [cypress-io/cypress#3919]
Hi,

Is There a way we can pass command line arguments to a cypress script in order to make it truly scalable . 

To explain in detail , We have a script `a.j`s That selects some values from list boxes(As of now these values are hardcode) . If there is a way we can parametrize these values , then the same script can be used to select multiple values

**Comment by jennifer-shehane** [comment]
Can you provide some of the code examples you've already tried? I'm not sure at what level of the test you are at that you want control over.

**Comment by krishvv** [comment]
@jennifer-shehane . Thanks for the reply . 
Code snippet
---
it('.select() - select an option in a <select> element', () => {
        cy.get('#cbLegalName').select('Graphics Driver - 64 Bit')
        cy.get('#cbReleaseLevel').select('100')
        cy.get('#cbReleaseVersion').select('(32-bit & 64-bit)')
        cy.get('#cbBuildVersion').select('(64 bit)')
    })
---------
I wanted to know if these values in cy.get() above can be passed as parameters so that the same script can be used for multiple use cases .

**Comment by must-git-good** [comment]
krishvv,

I'm pretty sure you can already achieve what you want here through the use of environment variables (which you can specify in the command line).  While your use case is slightly different, see https://docs.cypress.io/api/plugins/configuration-api.html#Usage for a general example.  

We, for example, load up a bunch of different configurations depending on our environment. You can extend this beyond just route/visit. The note at the end of the page is especially important to remember...it's just js, so you can make things as programmatically variable as you'd like.

So, loosely, in your case, you might have a cypress/config/  folder which contains (in .js or json, depending on your setup) a legalname.js, releaselevel.js, (etc).  Which config context is invoked here is called (from the example above) from the cli when you open Cypress.

Then within that file you define variable that are different for each setup.  So your code becomes:

it('.select() - select an option in a element', () => {
cy.get(  ${Cypress.config('releaseVersion')}  ).select( ${Cypress.config('graphicsDriverOptions')} ) 
 })

Of course that's just a general abstraction after a brief glance at what you need. But it should give an idea of how to accomplish what you want. It's probably not the only solution, but it's the one that seems to be the easiest 'fit' for your situation.  Hope it helps.

**Comment by krishvv** [comment]
@must-git-good. Thank you

**Comment by Harshit2318** [comment]
@must-git-good . I have a question regarding the explanation provided by you.
Assume i have a config file called a.js with the following elements
{"abc":"def",
"hello":"world"}
How would i assign it to

**Comment by must-git-good** [comment]
@Harshit2318 

Yeah, it won't work 'as is'. The config reference is assuming you've preloaded the config/just-an-example.js file into the Cypress configuration (as/before it loads).  The link above that ends in 'Usage' will walk you through that process better than I can. But the basic principle is to use your CLI to 'point' Cypress to which of the config files to load into its initial configuration (using your plugins/index.js file). Those values are then accessible using the Cypress.config() values any time you need them.  Note that if you're using .js instead of .json, you can 'also' export those values for when you need them directly, you can do things like provide programmatic values to them, etc. It's more flexible, but takes more initial setup than just dropping in .json files with normal config options.

I'd start with copying the guide above verbatim, then add complexity/abstraction as needed from there.

**Comment by krishvv** [comment]
@must-git-good . We followed all the steps needed to configure the variables . 
In the statement below
cy.get( ${Cypress.config('releaseVersion')} ).select( ${Cypress.config('graphicsDriverOptions')} )
we get a syntax error which says the following
**Unexpected token, expected ","** . This error is thrown right at the beginning of **"{"** above.

Is the syntax right? Or is there another way to access the same?

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of you [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options.
