### ISSUE TITLE
Option to force browser cache not being cleared before each test

### ISSUE THREAD

**Issue by achelonmm** [cypress-io/cypress#3925]
### Current behavior:

Currently, Cypress clears the browser cache before each test is run.

### Desired behavior:

I wonder if it could be possible to, somehow, make Cypress not clear the cache before each test is run. 
In our app we have a page that loads a 40Mb file when it loads and stores it on the cache. By clearing the cache before each test it's kind of a suicide to automate this section, so I would like to cancel the cache clear somehow.

### Versions

Cypress 3.2.0
Electron 59
Windows 10

**Comment by Lakitna** [comment]
The devs did this very purposefully and I don't think they want anyone to disable it because it will make it possible for tests to depend on each other.

Maybe the better question to ask here is if you really need that 40Mb file to be that big. Any user will run into the exact same issue regarding the load time. Some simple compression might make life better for everyone.

**Comment by must-git-good** [comment]
I'll second the vote to not change this behavior. I'm afraid it would be adopted too widely and lead to much flakier tests.  

I don't know your use case, OP, for a 40mb file...but depending on your use (and how much quicker you need things to be), you could almost certainly either stub some of your file interactions (if there's only a few/manageable), or you could probably just pre-load the test file locally instead of getting it over the network (which is still not super-fast, but much quicker, probably).

**Comment by jennifer-shehane** [comment]
This request would fall under our Life Cycle Events proposal here: https://github.com/cypress-io/cypress/issues/686 Closing as a duplicate.
