### ISSUE TITLE
Add link to download old versions of Chromium inside Cypress

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#3977]
Add a link to https://chromium.cypress.io inside the TR to help people download old versions

on-link: https://on.cypress.io/chromium-downloads

**Comment by jennifer-shehane** [comment]
Is this something that user's request? Or is this just an internal need? I'm not sure why user's want to do this unless they are developing within Cypress - in which case I would make the argument to only make this feature available within development.

**Comment by brian-mann** [comment]
Because Chrome auto-upgrades your browser which can all of a sudden break things. Users are then helpless, so this is the easiest way to tell users how to download a specific version of Chromium (so they can carry on happily).

Additionally - it will be helpful for support to direct users to download specific versions in the case where they say: "It was working, but now it's not". It can help rule out a major browser version change.

**Comment by jennifer-shehane** [comment]
Yes, I can see this as a great debugging tool. But in terms of "carry on happily" - wouldn't they *want* to see the errors on a new Chrome version? It means things have changed in chrome.
