### ISSUE TITLE
Not able to upload a png file in cypress

### ISSUE THREAD

**Issue by chirag-jogogo** [cypress-io/cypress#3990]
I am trying to upload a png file using cypress and this is that i have tried so far

```
Cypress.Commands.add('upload_file', (fileName, selector) => {
  return cy.get(selector).then(subject => {
    return cy.fixture(fileName, 'base64')
      .then(Cypress.Blob.base64StringToBlob)
      .then(blob => {
        const el = subject[0]
        const testFile = new File([blob], fileName, { type: 'image/png' })
        const dataTransfer = new DataTransfer()
        dataTransfer.items.add(testFile)
        el.files = dataTransfer.files
        return subject;
      })
  })
})
```

calling this in my test as below:

`cy.upload_file("logo.png", ".jss378");`

Have also tried different locators but no luck

it does not give any error but also it does not upload anything. note that the selector(.jss378) is dynamic so i want to use something that is not dynamic

Here is my HTML code

<img width="448" alt="Screen Shot 2019-04-17 at 2 52 15 PM" src="https://user-images.githubusercontent.com/49250072/56313388-7fa6db00-6120-11e9-82bf-dc0b12141210.png">

I am not getting any error but it not uploading anything

**Comment by must-git-good** [comment]
FWIW, I've had good file upload experience using the cypress-file-upload plugin.

Maybe that will be an easier/sufficient solution for you!

**Comment by chirag-jogogo** [comment]
@must-git-good , any documentation or example on that?

**Comment by must-git-good** [comment]
Sure, should have made that a link for you. 

On the plugins page:
https://docs.cypress.io/plugins/index.html#content

You'll find a link to:
https://github.com/abramenal/cypress-file-upload

The documentation there is pretty good. But for general reference, this one is even easier to setup than many other plugins (because you're basically just importing a pre-built custom command).

If those files don't get you moving in the right direction, let me know. I can share how it 'worked' for us in more detail (but I expect they've got you covered).

**Comment by chirag-jogogo** [comment]
@must-git-good - thank you, it worked

**Comment by imbilal1** [comment]
it('Uploading png image', () => {
        cy.fixture('testPicture.png').then(fileContent => {
            cy.get('input[type="file"]').upload({
                fileContent: fileContent.toString(),
                fileName: 'testPicture.png',
                mimeType: 'image/png'
            });
        });
    });

Use cypress file upload package: https://www.npmjs.com/package/cypress-file-upload
**Note**: testPicture.png must be in fixture folder of cypress
