### ISSUE TITLE
How to select table inside table?

### ISSUE THREAD

**Issue by mv7789** [cypress-io/cypress#4014]

**Comment by mv7789** [comment]
I have one master table with all data and second table inside that table with View links.
I want to select the row inside master table and then click on the view link associated to that row but as this view link is inside the second table I am not able to do it.
![image](https://user-images.githubusercontent.com/41212104/56526630-5c55a480-6501-11e9-9a1a-69bafe0a663d.png)

**Comment by mv7789** [comment]
first div- cm table wrapper is the entire table consist on other table div-table scroller-wrapper which contains only td = view but that is not part of entire row of the first table. 
![image](https://user-images.githubusercontent.com/41212104/56526850-a9d21180-6501-11e9-817d-48f34e5608db.png)

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. Since this is a question, I will be closing this issue.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of you [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options.
