### ISSUE TITLE
Question: Cypress test runner visiting /__/

### ISSUE THREAD

**Issue by elaich** [cypress-io/cypress#4027]
When cypress runs a spec, first it goes to this URL `/__/` I'm not sure why but I think that's how cypress finds the spec file it's about to run. I noticed that if I set a `baseUrl` then cypress will query `{baseUrl}/__/` first and then start running the test if `baseUrl` is not set then cypress runs on a random port like `http://localhost:32885/__/`. 

My question is how can I override the host where cypress runs? The host that comes before `/__/`, I don't want it to be my application `baseUrl` because I already have a `/__/` route on my application.

**Comment by jennifer-shehane** [comment]
Interesting. What happens when you put your application as the `baseUrl`? Does it just completely navigate to `{baseUrl}/__/` which ends up being your application? 

What happens when the `baseUrl` is not set and it runs on a random port? Do the tests run fine then?

You can set a [`port`](https://on.cypress.io/configuration#Global) so that cypress does not run on a random port. 

Otherwise, I'm not aware of the ability to set this entire host to *anything*. What would you set is as if you could set it?

@brian-mann @chrisbreiding thoughts?
