### ISSUE TITLE
Launch Cypress with Chrome "Incognito" using --incognito flag

### ISSUE THREAD

**Issue by beauholland** [cypress-io/cypress#4037]
### Current behavior:

Launch Cypress with Chrome "Incognito" results in: "Whoops can't run your tests"

![Incognito](https://raw.githubusercontent.com/beauholland/cypress-incognito/master/incognito.png?raw=true "Incognito")
### Desired behavior:

Able to launch Cypress with Chrome "Incognito"

### Steps to reproduce: (app code and test code)

Clone repo to test: (https://github.com/beauholland/cypress-incognito)

### Versions

Cypress 3.2.0
Node 10.14.1
Chrome 73.0.3683.103
Windows 10 V1803 build 17134.706

**Comment by jennifer-shehane** [comment]
Can verify, this is what happens when `--incognito` flag is passed. This is because all extensions are disabled when launched in incognito. Cypress itself uses an extension to run within the browser - and this unfortunately is the slightly unhelpful message that displays when the extension is not present.

Can I ask what functionality of `--incognito` it is that you are wanting to verify during testing? 

Cypress launches within its own profile and also that isolates a few things for testing purposes, so it would probably be more feasible to mimic the behavior you are wanting from incognito within Cypress than to actually launch incognito mode outright.

**Comment by beauholland** [comment]
Thanks @jennifer-shehane - got it, will try alternative approaches to find the real problem.

Trying Incognito mode in chrome to fix an intermittent issue with Auth0 "Request header or cookie too large" problem after tests run too frequently. Hitting it with a sledgehammer I know - will spend the time and find the fix.

Thanks again.

**Comment by ChaseBig** [comment]
@jennifer-shehane  I am having the same issue. Our webapp uses a library called `localForage` and it stores the state in the browser even after chrome is closed and a new cypress test instance is opened. I have the following set to run before each test: 
```
beforeEach(() => {
    cy.clearLocalStorage()
    **cy.clearCookies()
``` 
... but this is not clearing the `localForage` `indexedDb` cache. In order to run our test on the same test-user scenario account, I need to run in incognito mode OR somehow disable `indexedDb` in a configuration somewhere. Ideally we'd be able to run in incognito mode, but I understand this isn't exactly possible given the fact that Cypress uses a chrome plugin to run.

**Comment by jennifer-shehane** [comment]
@ChaseBig There is an open issue for clearing `indexedDb` here with some workarounds: https://github.com/cypress-io/cypress/issues/1208

**Comment by T-e-j-k-u-m-a-r** [comment]
Any comment on the how to execute the scripts in chrome incognito mode? Is there some settings that can be added into cypress.json file to handle it?

**Comment by anchalkumra** [comment]
Hi , Any update on this ? I am facing the same issue when trying to run the chrome incognito mode.

**Comment by AnshitaBhasin** [comment]
Try this https://youtu.be/28-axK6SxgU..
