### ISSUE TITLE
[Bug] When connecting to a remote machine by IP, running tests with electron results in a blank white screen with no errors

### ISSUE THREAD

**Issue by lrtanner** [cypress-io/cypress#4040]
### Current behavior:

Running cypress tests against a valid system's IP results in a blank screen with no errors

(targeting the same machine's hostname works fine)

### Desired behavior:

There should be a clear error that the connection is not valid

### Reproduction steps

- put IP of machine under test into `cypress.json`
- run `cypress open`
- run test from UI
	![](https://i.imgur.com/1P9wroU.png)
- blank electron window comes up with no errors in console, cypress, or electron.
	![](https://i.imgur.com/pFnSDKl.png)

### Versions

Operating system - CentOS Linux release 7.2.1511 (Core) 
Cypress - 3.1.5
Cypress environment - Electron 59

**Comment by jennifer-shehane** [comment]
Hey @lrtanner, just to clarify, you are setting the IP address within the `baseUrl` of `cypress.json` and then within your test file calling `cy.visit('/')? 

What is the resolved url in the test runner? `IP address + ??`

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can you provide a way to reproduce this?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by GonzaSSH** [comment]
Hello @jennifer-shehane,

I can also reproduce this issue when visiting the link to confirm the email after signup. It is only reproducible with Electron. 
Basically, this test checks what happens when a user tries to confirm the email after clearing the cookies. 
Unfortunately, Electron crashes when visiting the link. I attached a zip file with a video inside for you to see. Thank you in advance!

~~~javascript
describe('Email confirmation redirection', function () {
 beforeEach(function () {
    cy.pause()
    // create an unconfirmed user
    cy.login('voter').as('emailUser')
    cy.visit('/')
    // Opens the avatar menu
    cy.get('[data-test="navbar-account-menu"]').click()
    cy.get('div[data-test="account-menu"]').within(() => {
      // Clicks on Verifizieren sie ihre E-Mail-Adresse, um alle Funktionen von Civey zu nutzen!
      cy.contains(
        'Verifizieren Sie Ihre E-Mail-Adresse, um alle Funktionen von Civey zu nutzen!'
      ).click({ force: true })
    })
  })
  it('Anonymous user: should redirect to the onboarding', function () {
    cy.clearCookies()
    cy.task('readLastMail', {
      sentTo: this.emailUser.email,
      subject: 'Bitte bestätigen Sie Ihre E-Mail-Adresse jetzt!'
    })
      // links to mandrill and redirects to civey.com
      .then(mail => cy.request({ url: mail.html.links[0].href, followRedirect: false }))
      .then(response => {
        expect(response.headers.location).to.include('/confirm-email')

        // The cy.visit() below currently crashes the browser electron 61
        var confirmEmail = new URL(response.headers.location).pathname
        cy.visit(confirmEmail)
      })
    // Checks for the welcome card to be there
    cy.get('[aria-label="user-onboarding"]')
  })
})
~~~

[electron_creashes.mov.zip](https://github.com/cypress-io/cypress/files/3467920/electron_creashes.mov.zip)
