### ISSUE TITLE
Question : Is it possible to check if a downloading has happened ?

### ISSUE THREAD

**Issue by clferrarin** [cypress-io/cypress#4074]
Hi, 
Need informations about one question.
Is it possible to check in back-end if the downloading has happenend ?
Example : When i click on button it starts a downloading and i need to know if it happened 
Is cypress allowing this ? Or do you know how to check in javaScript or with an other framework ?
Thanks

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of you [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options.
