### ISSUE TITLE
Add ability to use .should (without callback) without retry

### ISSUE THREAD

**Issue by testerez** [cypress-io/cypress#4085]
### Current behavior:

`.should` is always retrying the previous command which can be undesired in some scenarios. For example when calling an api to check that an action on the app did change the data, we usually do something like:
```js
// ...
.request(...)
.its('body')
.should('deep.equal', expectedResult)
```

in this example, if the assertion fails then Cypress will retry the `its` until it times out. Which is useless since `.its('body')` will always return the same value.
### Desired behavior:

I'm not sure what's the best way to optimize this use case. My current workaround is to replace `.should` with:
```js
.then(body => expect(body).to.deep.equal(expectedResult))
```
Ideally, Cypress would be smart enough to avoid retries in this situation. If that is not possible, then maybe adding a `.assert` with same api as `.should` but without retry?

### Versions

cypress@3.2.0

**Comment by jennifer-shehane** [comment]
Hey @testerez, thanks for the detailed issue. 

`.should()` will always retry any chained assertions. The `body` in this case *could* technically mutate in this situation. `.its()` really has no way of knowing that the `body` here won't mutate essentially. 

Currently `.then()` is the equivalent of `.should()` in this case, in that it won't retry. Of course, `.then()` *only* accepts a callback so is a bit of a pain that you can't just pass the string assertions. 

I think introducing a command called `.assert` in this case may introduce some confusion, since that is already a word used for non-implicit assertions in Cypress. 

We'll be closing this for now since the alternative of not retrying is possible with Cypress today, but we'll consider reopening this issue if enough support from others gathers for this feature.

**Comment by testerez** [comment]
Ok, I get your point. Maybe another solution could be to add a `{retryable: false}` option on `its` command...
Either way, I can live with the `.then` workaround.
