### ISSUE TITLE
Cypress setup not running on my other machines.

### ISSUE THREAD

**Issue by nitingupta220** [cypress-io/cypress#4088]
I wrote some tests with Cypress on my 1st dev machine and it runs successfully with some failures and success.

But when I want to ran all the testsin my other dev machine it doesn't run. Whenever I tried to run it via : - `.node-modules/.bin/cypress open`. 

Every time I got this error in the console: - `Refused to load the script 'http://localhost:35729/livereload.js?snipver=1' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.`

Can anyone help me in this issue? @brian-mann @jennifer-shehane

**Comment by jennifer-shehane** [comment]
Hey @nitingupta220, do you have the same version of Chrome installed on both machines? What version of Chrome are you running this within?

**Comment by nitingupta220** [comment]
Hey @jennifer-shehane I have Chrome version 74 and my other two machine versions are 69 and 73.

The problem is Cypress tests are running normally in Linux, but creating problem in MacOs.

But if I run the tests headlessly via Electron browser it runs.

I don't know what is happening.

Please help.

**Comment by nitingupta220** [comment]
@jennifer-shehane can you please help?

**Comment by jennifer-shehane** [comment]
Another related issue to Content Security Policy: https://github.com/cypress-io/cypress/issues/1030

Also weirdly sounding related issue with live-reload and CSP (only causing problems in mac, not linux) https://forum.ionicframework.com/t/solution-for-livereload-problems-with-new-csp-rules/25449/14

I wonder if you could also make sure to set the `baseUrl` configuration in your project, so that Cypress loads directly to your domain. 

We run the application under test in an iframe, and I think your livereload doesn't like that essentially. - if you do want to make some changes to the livereload script while working under Cypress see this [FAQ](https://docs.cypress.io/faq/questions/using-cypress-faq.html#Is-there-any-way-to-detect-if-my-app-is-running-under-Cypress).

**Comment by jennifer-shehane** [comment]
@nitingupta220 	Any update on setting the baseUrl?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
