### ISSUE TITLE
Cancelled XHR Stubbed Request still has loading indicator next to it

### ISSUE THREAD

**Issue by nartc** [cypress-io/cypress#4130]
### Current behavior:
![image](https://user-images.githubusercontent.com/25516557/57200197-5a063800-6f4e-11e9-90df-fb6b5475fb87.png)

### Desired behavior:
Cancelled request (by navigating away) should not have the loading indicator next to it,

### Versions

Cypress 3.2.0
Chrome on MacOS X

**Comment by jennifer-shehane** [comment]
Hey @nartc, can you see the cancelled state of the XHR within the network panel of the devTools? 

Can you provide any test code we can run to reproduce this state exactly?

**Comment by nartc** [comment]
hi @jennifer-shehane , I can see the cancelled state of the XHR in the Network tab. 

I noticed this behavior in a very specific OAuth Redirect environment but I'll see if I could come up with a reproducible repository :) 

Thanks for checking in.

**Comment by nartc** [comment]
https://github.com/nartc/cypress-cancelled-xhr 

Above is the reproducible repo (it is Angular). Steps are as follow:
1. Start server `npm start`
2. Start Cypress `npm run cypress-open`
3. Run the test.

Synopsis: On start, the app will redirect from `/` to `/posts` which will then render `PostsComponent` and will call JSON Placeholder's `posts` endpoint. To simulate some delay, I add 1s delay to the Http request. In the test, I `visit` the home route `/` then wait for 999ms then navigate to `/todos` route (which then renders `TodosComponent` and will call JSON Placeholder `todos` endpoint). 

After the test has been finished, you can see the XHR Request for `/posts` still has a loading indicator next to it. Network tab shows the request has been cancelled due to navigating away.

Thanks

**Comment by jennifer-shehane** [comment]
Thanks so much for providing this example. I do see the issue - that the loading indicator remains after the XHR request has been cancelled.

I thought this may be related to this change made in Chrome 71 - which we have already fixed and is pending release in version 3.3.0, since I tracked down this 'cancel' display to the 'window:onload' event - https://github.com/cypress-io/cypress/issues/3973

So I ran your repo through `develop`, which is our pre-3.3.0 release branch and it is indeed fixed already 🎉 

The code for this is done in https://github.com/cypress-io/cypress/pull/3974, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
