### ISSUE TITLE
Problem with subdomain? SecurityError: Blocked a frame with origin from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by vwohlwend** [cypress-io/cypress#4142]
Hello fellow people of cypress, I hope you can help me with the following issue, and I hope I don't bother you with my problem. I read several related issues, but I just can not fix my problem. 

### Current behavior:
Tests for opening pages will fail, if requested URL is a subdomain. Even though the test fails, the website opens up for me. 
![cypress](https://user-images.githubusercontent.com/30195504/57232425-d9623d00-701c-11e9-8bd9-cbd9bbd24db2.png)
 I want to open "contacts.google.com", and it kinda works, but the test has problems as you can see on the left side. 
When I open up google.com (no subdomain), it works perfectly fine. 
![cypress2](https://user-images.githubusercontent.com/30195504/57232608-3c53d400-701d-11e9-94a1-388454af32a9.png)

### Desired behavior:
A successful test of opening a subdomain page, especially contacts.google.com.

### Steps to reproduce: (app code and test code)
Testfile / app_spec.js in integration folder:
```javascript
describe("Start", () => { 
    it("Open Page", () => { 
        cy.visit("contacts.google.com"); 
    });    
});
```
Cypress.json in main folder (because [Cypress documentary told me so](https://docs.cypress.io/guides/guides/web-security.html#Disabling-Web-Security)):
```javascript
{
"chromeWebSecurity": false
}
```
Part of index.js, which I added like [in this issue](https://github.com/cypress-io/cypress/issues/1951):
```javascript
module.exports = (on, config) => {
  // Manually added code down below:
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--disable-site-isolation-trials');

      return args
    }
  })
}
```
Also I changed by baseURL from "null" to "https://google.com", but it doesn't make any difference, the issue remains the same.

### Versions
Cypress: 3.2.0
OS: Windows 10 64bit
Browser: Chrome 74

Thanks for everyone in advance, that will try to help me.

**Comment by jennifer-shehane** [comment]
The application on the VISIT command does several reroutes, which ends up going to the `accounts.google.com` subdomain. Since you set the `baseUrl` to just `https://google.com`, the google page is throwing an error saying that that domain is blocked from access the `accounts.google.com` subdomain. 

**Set your `baseUrl` to `accounts.google.com`**

Please note that we strongly discourage testing the behavior of sites that are not under your control for several reasons: https://on.cypress.io/best-practices#Visiting-external-sites

**Comment by felquis** [comment]
Sorry to bring this issue back to live @jennifer-shehane, in my case I doesn't load different domains, I click a menu link that is going to reload the page to a new one, might use the same domain/path but different query parameters.

<img width="420" alt="Screen Shot 2020-01-24 at 15 15 58" src="https://user-images.githubusercontent.com/736728/73093020-72dbc280-3ebc-11ea-837b-928b02bcb11d.png">
<img width="439" alt="Screen Shot 2020-01-24 at 15 09 57" src="https://user-images.githubusercontent.com/736728/73092548-9a7e5b00-3ebb-11ea-9e82-b249d8f8928c.png">

Should I use `chromeWebSecurity: false` in this case? This error started to happen when I switched the server approach from react-scripts server, to `serve ./build`

Also I did check `on.cypress.io/cross-origin-violation` but it is different I think, may you give me some light?

**Comment by bahmutov** [comment]
@felquis can you please open a separate issue describing your problem AND having a public small reproduction that shows the problem. Like remove everything extra and just have a single test with the part of the source code that shows us the problem. Otherwise, we have nothing to go by really to fix the problem.

**Comment by felquis** [comment]
I started working on a reproducible repo, but it didn't reproduce the issue.
Whenever I can simulate it I'll open an issue.

Thank you.
