### ISSUE TITLE
Aw, Snap when inspecting

### ISSUE THREAD

**Issue by IsidroGH** [cypress-io/cypress#4185]
### Current behavior:

I always get a Chrome Aw Snap error when I move the mouse over the DevTools.

### Desired behavior:

Chrome doesn't crash.

### Steps to reproduce: 

Spec:
```js
describe('My First Test', function() {
  it('finds the content "type"', function() {
    cy.visit('https://example.cypress.io')
    cy.contains('type')
  })
})
```

Click on CONTAINS type:

![Screen Shot 2019-05-13 at 21 16 35](https://user-images.githubusercontent.com/3267885/57647880-6a5c8980-75c4-11e9-88ba-066588973d62.png)

Move the mouse over the DevTools area and I always get an Aw Snap in 1 or 2 seconds.

![Screen Shot 2019-05-13 at 21 17 54](https://user-images.githubusercontent.com/3267885/57647961-9a0b9180-75c4-11e9-9099-e7c9a90e4be4.png)

### Versions

Cypress 3.2.0
MacOS 10.13.6 
Chrome 74.0.3729.131

**Comment by jennifer-shehane** [comment]
I can recreate this. This crash happens specifically when you have pinned the snapshot, then hover over the DOM element shown as the **Yielded** property of the console props.

Manually inspecting the DOM element in question shows in the DOM tree as the following:

<img width="528" alt="Screen Shot 2019-05-14 at 12 54 57 PM" src="https://user-images.githubusercontent.com/1271364/57675301-953bf180-7647-11e9-87cb-7a88be87f8d5.png">

I've confirmed that this behavior **does occur** in the following browsers:
- Chrome Version 74.0.3729.131

I've confirmed that this behavior **does not occur** in the following browsers:
- Electron 59
- Chrome Version 72.0.3605.0
- Chrome Version 73.0.3683.0
- Chrome Version 75.0.3770.0
- Chrome Version 76.0.3793.0

So, this leads me to believe that this is a bug that was introduced sometime in between Chrome [73.0.3683.0 & 74.0.3729.131](https://chromium.googlesource.com/chromium/src/+log/73.0.3683.0..74.0.3729.0?pretty=fuller&n=10000) and fixed sometime in between [74.0.3729.131 and 75.0.3770.0](https://chromium.googlesource.com/chromium/src/+log/74.0.3729.0..75.0.3770.0?pretty=fuller&n=10000)

I tried to find a related commit or bug from Chromium, but wasn't able to find one in the time I spent - as the changelogs are quite extensive. Should probably narrow down the versions more between the failures, but essentially this appears to be a Chrome issue and not an issue with Cypress.

**Comment by ameego** [comment]
Hi @jennifer-shehane,

I am facing the same issue (Chrome eventually displays the Aw Snap Error) but for different scenario. From what I could read from other people facing the Aw Snap Error page, it somehow seems to be related to the amount of time the test runs for. In my case, I have a simple test involving login, browsing to a given page, executing the asset and login out of the application, executing for three viewports. The test run for around 130 seconds before the browser eventually displays the Snap page. I can reproduce this every single time.

I took the liberty to reply here because this occurs even with the latest version of Chromium (76.0.3794.0) as well as Electron browser. I thought this may be of interest considering your last reply.

I'm working on a reduced test case, I'll create a separate issue if I manage to replicate this outside of the application I'm working on.

**Comment by jennifer-shehane** [comment]
Yes, this issue is covering the specific case where the 'Aw, snap' happens on inspection in devtools. 

Other issues about 'Aw, snap' message can be found here: https://github.com/cypress-io/cypress/labels/topic%3A%20aw%20snap%20%3Aslightly_frowning_face%3A
