### ISSUE TITLE
Not able to click/Select Options Thro' Cypress

### ISSUE THREAD

**Issue by rahil23** [cypress-io/cypress#4237]
### Select Statement is not working , getting CypressError: Timed out retrying: Expected to find element: 'timeentry_lov1', but never found it.

I Want to select Options form Below HTML Code.`timeentry_lov1` is Select Name which is 2nd element in Page with same Name. Also checked that there is no Frame present in Page.
But Is there any Frame Concept like selnium in Cypress? If not then can anyone Help me to work with Select attribute.

### PFB HTML Code
![image](https://user-images.githubusercontent.com/15339271/57970038-fa6e4a80-7999-11e9-819c-9e3cd7f2bdef.png)

### PFB the below Select Statement which I have used

```js
cy.get('timeentry_lov1',{timeout : 60000}).eq(1).select('NB-860').debug();
cy.get('timeentry_lov1').eq(1).select('NB-860-Test Automation');
cy.select('timeentry_lov1',{timeout : 7000}).eq(1).should('have.value','NB-860');
cy.find('timeentry_lov1').get('select').select('NB-860');
```

**Comment by jennifer-shehane** [comment]
The selector should be `cy.get('[name="timeentry_lov1"])` - please use equivalent jQuery selectors to find elements. You can find documentation on this in jQuery's docs. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of you [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our premium support options.
