### ISSUE TITLE
Returning undefined after cy.window returns window instead

### ISSUE THREAD

**Issue by Floriferous** [cypress-io/cypress#4249]
I'm noticing inconsistent behavior when adding a custom command chained off of `cy.window()`.

Here are 2 different custom commands:

```js
Cypress.Commands.add('getUndefined', () => {
  return cy.window().then((window) => {
    if (!window.unknown) {
      return undefined
    }

    return 'working'
  })
})

Cypress.Commands.add('getNull', () => {
  return cy.window().then((window) => {
    if (!window.unknown) {
      return null
    }

    return 'working'
  })
})
```

However, when you run both of these, the first one returns the actual window object, whereas the other correctly returns `null`.

Here's a reproduction: https://github.com/Floriferous/cypress-example-kitchensink

Just run tests to see it.

**Comment by jennifer-shehane** [comment]
Thanks for providing a reproducible example. I can confirm this is happening from your repo code provided on version 3.3.0 of Cypress. 

The unexpected behavior you are seeing is independent from the custom command definitions and actually only pertains to the return value expected from the `.then()` command. 

What you are seeing is the documented behavior of the `.then()` command as can be seen in the [Yields section](https://on.cypress.io/then#Yields)

>`.then()` is modeled identically to the way Promises work in JavaScript. Whatever is returned from the callback function becomes the new subject and will flow into the next command (with the exception of `undefined`).
>
>When `undefined` is returned by the callback function, the subject will not be modified and will instead carry over to the next command.
>
>Just like Promises, you can return any compatible “thenable” (anything that has a `.then()` interface) and Cypress will wait for that to resolve before continuing forward through the chain of commands.

Since you are returning `undefined` from the `.then()`, it just passes through the original subject, which was `window`.

After understanding the intended behavior, if you can provide a valid use case for wanting to return `undefined` here instead - feel free to comment wanting this behavior changed.

**Comment by Floriferous** [comment]
My bad, didn't search long enough!

My use case is that we're working with `Meteor` apps, and getting the meteor object from the window is crucial to be able to interact with the backend (including other functionalities). However, on initial load, the `Meteor` object is not yet loaded, leading to unexpected behavior, because it returns undefined!

And more importantly, since returning this object from the `window` in a custom command behaves the way it does, sometimes the issue flies under the radar, as you can call a function off the `window` object, instead of our desired `Meteor` object.

In general I'd prefer that these magic patterns don't exist, as the UX for developers isn't easy to find out. It's like force-touch on iOS, it's hard to discover, sometimes it leads users to do unwanted things, and in general it's never used, even by those who know it's there!
