### ISSUE TITLE
Project is deleted without warning

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#426]
When I go to project settings in the dashboard and click "Delete project", the project is deleted without confirmation. Bam and it's gone!
For convenience I like to have a confirmation modal.

(When you delete a GH project, there is even an extra security measure: input the project name. Idea?)

**Comment by brian-mann** [comment]
It is only deleted without prompt if there were no recorded runs.

If there were recorded runs we display that and make you confirm it.

Here's a screenshot: https://docs.cypress.io/docs/projects#section-deleting-a-project

**Comment by bahmutov** [comment]
we should always prompt - the org might have users / projects / billing info / integrations setup.

**Comment by jennifer-shehane** [comment]
I've created an issue for both deleting orgs and projects to prompt regardless of current state: https://github.com/cypress-io/cypress-dashboard/issues/549

**Comment by brian-mann** [comment]
Ohh this is a good point. Gleb - you **must** handle the "safe delete" cleanup on all objects associated to a project - which means integrations.

The code for this is really clean - it runs on a cron job. We initially safe destroy the project, and then eventually the cron will cleanup all of the other associated objects. Just make sure you don't delete anything - always safe destroy associated objects.

The safe destroy takes the row -> converts it into JSON, and then inserts it into the `deletions` table. This is good because its impossible to accidentally query for deleted rows - but gives us the ability to restore if necessary.

**Comment by bahmutov** [comment]
That's good observation, but also API should reject requests to delete org if there is active subscriptions- dashboard should say "unsubscribe first".

**Comment by jennifer-shehane** [comment]
Currently, I was able to implement the confirmation dialog on DELETE of organization. Showing a confirmation dialog for deleting a project ended up being slightly more complex, so is branched into another open issue for now.

**Comment by jennifer-shehane** [comment]
@trydionel 	Services issue ^

**Comment by jennifer-shehane** [comment]
cc @cypress-io/services

**Comment by jennifer-shehane** [comment]
The best place to express interest and see progress for Dashboard features is on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard and we want to make sure any feedback gets seen and addressed by the right team. 

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thanks!
