### ISSUE TITLE
Cannot test XMLHttpRequests with URLs ending with ".html"

### ISSUE THREAD

**Issue by ddx32** [cypress-io/cypress#4266]
### Current behavior:

While checking for outgoing XMLHttpRequests, `cypress.route()` doesn't see requests whose URLs end with ".html", so the `wait()` command times out and is unable to run assertions on the request.

This is an example request that Cypress ignores:

```js
var req = new XMLHttpRequest();
req.open('GET', 'http://example.com/failing.html');
req.send();
```

Example failing test:

```js
cy.server()
cy.route('http://example.com/*').as('request')
cy.visit('failing.html') // page containing the code above
cy.wait('@request').then(xhr => {  // Promise is never resolved, the timer runs out
  expect(xhr.url).to.equal('http://example.com/failing.html')
})
```

### Desired behavior:

Cypress should be able to work with any valid URL requested via XMLHttpRequest so assertions can be run against it.

### Steps to reproduce:

The problem is reproduced in [this repo](https://github.com/ddx32/cypress-test-tiny), which contains a simple page with examples of passing and failing tests.

### Versions

The issue has been occuring in versions 3.2.0 and 3.3.0 in both Electron and Chrome on macOS 10.14.4

**Comment by jennifer-shehane** [comment]
By default, some resources are whitelisted from ever being logged or stubbed (jsx, html, and css files). This is mostly to prevent noise in the Command Log and to prevent confusion between urls matching XHR requests that are non-static resources versus static resources.

You can, however, [change this whitelisting behavior](https://on.cypress.io/server#Change-the-default-whitelisting) so that your html resources will be waited upon properly.
