### ISSUE TITLE
Screenshot tiling - fullScreen

### ISSUE THREAD

**Issue by pburkindine** [cypress-io/cypress#4277]
### Current behavior:

Sporadically, full-screen screenshots will tile the first viewport's worth of content rather than capturing the full image.  Content does not include fixed or sticky elements.  App is Angular 7.  For some tests this is 4 times out of 5, for others 1/10.

### Desired behavior:

Full-screen screenshots should consistently capture the entire page.

### Steps to reproduce: (app code and test code)

I have not been able to identify a set of conditions that consistently reproduces the issue.

### Versions

Cypress 3.2 & 3.3, OSX High Sierra, happens more with `cypress run` and electron 61 but also frequently with `cypress open` and Chrome 73 or electron 61

**Comment by pburkindine** [comment]
I can confirm, for what it's worth, that the issue persists despite setting `position: absolute` on the Angular CDK overlay (when present) as described in the cypress docs.

```
cy.get('body').then($body => {
    const overlayContainer = $body.find('.cdk-overlay-container').first();

    if (overlayContainer) {
      cy.log('Setting CDK overlay position:absolute for screenshot');
      overlayContainer.css('position', 'absolute');
    }

    cy.matchImageSnapshot().then(() => {
      if (overlayContainer) {
        cy.log('Reverting CDK overlay position:fixed');
        overlayContainer.css('position', 'fixed');
      }
    });
  });
```

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

I'd like to isolate this outside of being a problem with the cypress-image-snapshot plugin, as they do some things to the snapshot afterward. 

Also, I'd need some code to run that shows this. Can you provide the HTML to run this against?

Please comment in this issue with a reproducible example and we will consider reopening the issue.
