### ISSUE TITLE
Route with slash isn't resolved correctly

### ISSUE THREAD

**Issue by viraxslot** [cypress-io/cypress#4284]
### Versions
Cypress 3.3.0, Windows 10

### Current behavior:
I want to catch XHR request and I've added to my test:
```javascript
beforeEach(function () {
	cy.server();
	cy.route('POST', '*search*').as('apiSearch');
});
it('test', function() {
	...
	cy.wait('@apiSearch');
	...
});
```
Everything works fine:
![image](https://user-images.githubusercontent.com/20737672/58212156-9aa7d480-7cf6-11e9-99e8-584f99a80727.png)
![image](https://user-images.githubusercontent.com/20737672/58212210-c5922880-7cf6-11e9-9176-6f1d8c7e5a8f.png)

If change route path like this
```javascript
beforeEach(function () {
	cy.server();
	cy.route('POST', '*flights/search*').as('apiSearch');
});
```
Cypress can't find it:
![image](https://user-images.githubusercontent.com/20737672/58212347-21f54800-7cf7-11e9-9888-443e71154196.png)
![image](https://user-images.githubusercontent.com/20737672/58212372-36394500-7cf7-11e9-9792-07903b015ef8.png)

### Desired behavior:
Cypress should understand slash in route path.

**Comment by jennifer-shehane** [comment]
Honestly, I'm not sure why the first one is matching, probably due to minimatchs default options, which can be changed here: https://docs.cypress.io/api/utilities/minimatch.html#Syntax. 

Please try an online glob tester or minimatch before opening a PR. 🙏  These should match 

- `**/flights/search`
- `**/search`

**Comment by viraxslot** [comment]
@jennifer-shehane thanks, I'll try.
