### ISSUE TITLE
document.referrer is set on cy.visit(...)

### ISSUE THREAD

**Issue by JustTB** [cypress-io/cypress#4295]
### Current behavior:

`document.referrer` is set to cypress test url when I use `cy.visit(...)`

### Desired behavior:

`document.referrer` is an empty string

### Steps to reproduce: (app code and test code)

```js
cy.visit('https://your.test.dom/')
```
jscode on the page:

```
console.log(document.referrer)
```

### Versions

3.3.1 cypress (chromium 73 and electron 61)
Kubuntu 18.04

**Comment by jennifer-shehane** [comment]
Can confirm. The left side is visiting the url in normal Chrome, the right side is visiting the url within Cypress.

![Screen Shot 2019-05-24 at 11 03 10 AM](https://user-images.githubusercontent.com/1271364/58302936-a0dfa300-7e13-11e9-8bbe-a4aa43227f26.png)

This is due to Cypress rendering the application under test within an iframe. 

This property is `readonly`, but it does look as if Cypress can override what it returns like so:

```js
Object.defineProperty(document, 'referrer', { get () { return ''; } })
```

I don't think there should be any instances during `cy.visit()` where this shouldn't return an empty string, even in the case of 3xx redirects, this will be maintained by the browser appropriately. 

I would also likely only make this change from Cypress if the `modifyObstructiveCode` is `true`.

**Workaround Today**

You could detect if you application is running from within Cypress and set the `referrer` to an empty string in this case. 

```js
if (window.Cypress) {
  // we are running in Cypress
  Object.defineProperty(document, 'referrer', { get () { return ''; } })
}
```

**Comment by malshalabi** [comment]
Hey @jennifer-shehane, will you guys fix this soon?! I am facing the exact same case right now

**Comment by klarzynskik** [comment]
Hey @jennifer-shehane, I'd like to work on that one. Is that okay?
