### ISSUE TITLE
Add a way to clear selection with `cy.select()`

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4318]
This Stack Overflow question points out that `cy.select()` can't clear a selection, and apparently, neither can commands like `cy.clear()`: https://stackoverflow.com/questions/56340978/how-do-i-clear-a-select-input-using-cypress

Things that should work, but don't:

* `cy.select([])` should cause no elements to be selected
* `cy.clear()` with a `<select>` subject should cause no elements to be selected

Also, maybe `cy.select()` or `cy.select(undefined)` should also clear the selection.

**Comment by kylerob** [comment]
@jennifer-shehane I'm willing to work on this for Hacktoberfest. What should be the acceptable inputs to clear using the select command? @flotwig I like how clean `cy.select()` is, but I think `cy.select([])` or `cy.select(null/undefined)` conveys more meaning to readers. Also I'm not sure how much `cy.clear()` makes sense with selects because according to the docs "`.clear()` is just an alias for `.type({selectall}{backspace})`." Taking that action on a dropdown selects the first option (via selectall), and then backspace is a noop. We could look at expanding the scope of clear to make it more than an alias, but starting with changes to select may be good enough.

**Comment by flotwig** [comment]
Hey @kylerob, thanks for looking at this. To answer your questions:

`cy.select([])` and `cy.select(null/undefined)` should both clear the input field - since `cy.select` can accept an array of choices, `cy.select([])` semantically means "nothing selected". So I'd expect both to work.

Re: `cy.clear` - you can probably update cy.clear to check the command subject, and if the command subject is a `<select>`, chain `.select([])` on to it; otherwise, do the default behavior (`.type({selectall}{backspace})`)

cc @Bkucera

**Comment by Bkucera** [comment]
I don't think "clear" makes sense here since a user cannot clear a `select`, only set it to its default value.

However, the PR would simply be to accept `cy.get(...).select('')` and set the value to empty string.

The spec file to edit is here: https://github.com/cypress-io/cypress/blob/issue-2957/packages/driver/test/cypress/integration/commands/actions/select_spec.coffee

you would need to add a test for setting a value to empty string, and edit the select command file: https://github.com/cypress-io/cypress/blob/issue-2957/packages/driver/src/cy/commands/actions/select.coffee

**Comment by kylerob** [comment]
@flotwig, @Bkucera Thanks for the pointers, I'm starting on it now.

**Comment by florenceshelley** [comment]
Hi, is this issue still open and available for grabs?

**Comment by signalp** [comment]
> Hi, is this issue still open and available for grabs?

Still returning "cy.select() failed because it could not find a single <option> with value or text matching: ``" for me on select multiple (trying .select([]), .select(null), .clear(), all fail)
