### ISSUE TITLE
Cypress' cy.wait() does not wait on redirect

### ISSUE THREAD

**Issue by dhmoon91** [cypress-io/cypress#4357]
### Current behavior:

I'm writing a test to cover our registration flow. 

On creating an account, user gets redirected to a `/registration` page where I then try to validate that a `send confirmation email` button exists. 

We have bunch of `GET` requests made on redirect on registration page, which causes a complete load of 'registration' page pretty long (I would say 5-7s?).

Of course, this caused the test became really 'flaky', so I decided to wait for those api routes to be resolved before proceeding to next commands, but it seems like the commands are getting executed and timing out before `cy.wait` gets resolved.

Custom command, wait for api: 

```js
Cypress.Commands.add('waitForApiResponse', function (url) {
    cy.server();
    cy.route('GET', '**/internal**/**').as('internalApi');
    cy.wait('@internalApi');
});
```

Actual test: 

```js
cy.get(vendorRegSelectors.vendorRegCreateButton).click();
cy.waitForApiResponse();

cy.location('pathname').should('eq', '/registration');
cy.get(vendorRegSelectors.sendConfirmEmailButton)
  .invoke('width')
  .should('be.gt', 0);
```

Screenshot on Cypress:
![Screen_Shot_2019-05-31_at_1_07_19_PM](https://user-images.githubusercontent.com/6810688/58727680-fcc99f00-83b2-11e9-9f6e-8f0edcd95da6.png)

### Desired behavior:

Next commands of `cy.wait()` should not be executed until `cy.wait()` resolves successfully.

Now, I know that we can't wait FOREVER to grab requests that are being made within the app...

Would there really be a no other solution instead of increasing `timeout`?

### Versions

Cypress: 3.3.1
Browser: Chrome 74

**Comment by jennifer-shehane** [comment]
You will want to define your `cy.route()` before the action that will cause the request to go out, since `cy.route()` is really saying 'listen for this upcoming route'. So you probably want 

```js
cy.server()
cy.route('GET', '**/internal**/**').as('internalApi');
cy.get(vendorRegSelectors.vendorRegCreateButton).click();
cy.wait('@internalApi');
```

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).
