### ISSUE TITLE
Problem Cross Origin Iframes

### ISSUE THREAD

**Issue by gabrielfign** [cypress-io/cypress#4369]
I'm not getting access to a URL. Can someone help me? I have problem Cross Origin Iframes. As soon as I added "chromeWebSecurity": false, the test stopped crashing, but the URL still does not open.
![image](https://user-images.githubusercontent.com/18723149/58814807-caab7d80-85fc-11e9-9090-e1b41f858f24.png)

**Comment by jennifer-shehane** [comment]
In version 3.3.1 of Cypress, I get this error when running your tests: `Refused to display 'https://idcs-f14931f3c8584f3a9d118b3215b6309e.identity.oraclecloud.com/oauth2/v1/authorize?response_type=code&redirect_uri=https%3A%2F%2Fmobicare.auth0.com%2Flogin%2Fcallback&scope=openid%20profile&state=XzKDj0mSqRhZalOeFnuuVH8WSGVVAAHH&client_id=703f784c921549f594b7da456d34b091' in a frame because it set 'X-Frame-Options' to 'deny'.`

Closing this issue as a duplicate of https://github.com/cypress-io/cypress/issues/3459
