### ISSUE TITLE
cy.visit() occasionally loads blank page

### ISSUE THREAD

**Issue by nitzel** [cypress-io/cypress#4383]
### Is this a Feature or Bug?
A bug (either in Cypress, the browser or in our App)

### Current behaviour:
Browser occasionally loads an empty/blank page and starts testing against it - but can't find the expected elements.

This can happen to any spec. Often specs afterwards will run fine again.

1. Cypress navigates to `/` but the website shows as a blank page in the recorded video/screenshots
2. Test gets an authentication token and reloads the website with the token configured
2. Page still blank, cypress tests against the empty page and can't find the expected elements, e.g. `CypressError: Timed out retrying: Expected to find element: 'input[name=password]', but never found it.`

The code for the tests is roughly the following:
```typescript
// test*.ts
beforeEach(() => {
  cy.visit(`/`); // not logged in
  // get auth token via API, set it on local storage and visit site again
  cy.visit(`/`); // logged in
  cy.get('#root'); // fails
});

// other.ts
it('general\\signin.ts', () => {
  cy.visit(`/}`); // not logged in
  cy.get('input[name=password]') // fails
    .type(password);
}
```

```
     Spec                                                Tests  Passing  Failing  Pending  Skipped
 ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
 │ √ test1.ts                                  00:13        2        2        -        -        - │
 ├────────────────────────────────────────────────────────────────────────────────────────────────┤
 │ √ test2.ts                                  00:22        4        4        -        -        - │
 ├────────────────────────────────────────────────────────────────────────────────────────────────┤
 │ √ test3.ts                                  00:11        2        2        -        -        - │
 ├────────────────────────────────────────────────────────────────────────────────────────────────┤
 │ √ test4.ts                                  00:06        1        1        -        -        - │
 ├────────────────────────────────────────────────────────────────────────────────────────────────┤
 │ √ test5.ts                                  00:06        1        1        -        -        - │
 ├────────────────────────────────────────────────────────────────────────────────────────────────┤
 │ √ test6.ts                                  00:06        1        1        -        -        - │
 ├────────────────────────────────────────────────────────────────────────────────────────────────┤
 │ × other.ts                                  01:52      108      100        8        -        - │
 ├────────────────────────────────────────────────────────────────────────────────────────────────┤
 │ × test7.ts                                  00:20        2        -        1        -        1 │
 ├────────────────────────────────────────────────────────────────────────────────────────────────┤
 │ √ test8.ts                                  00:05        1        1        -        -        - │
 ├────────────────────────────────────────────────────────────────────────────────────────────────┤
 │ √ test9.ts                                  00:05        1        1        -        -        - │
 └────────────────────────────────────────────────────────────────────────────────────────────────┘
   2 of 10 failed (20%)                        03:31      123      113        9        -        1
```

![similar screenshot from https://github.com/cypress-io/cypress/issues/2938#issuecomment-451428083](https://user-images.githubusercontent.com/42965216/50899585-ca72d180-1412-11e9-974e-d9b33c77f907.png) Screenshot is from [here](https://github.com/cypress-io/cypress/issues/2938#issuecomment-451428083) but very similar to what I see.

### Desired behavior:
Browser always loads and displays the the website when navigating to `/`.

### What I've tried
- Run with electron (headless and headed) and with chrome (all fail)
- Increase the timeout for `cy.get` to `15` seconds (still fails)
- Navigating to `/v=<number>` instead of `/` to avoid any caching ( still fails)
- Run with `npx cypress open` and then `Run all specs` (this works / has not failed yet)
- Running similar tests against google.com and [random react app from the web](https://ahfarmer.github.io/calculator/) which passed so it seams this issue is not related to the testing environment but the combination of my website and Cypress CI.

### Versions
|||
|-|-|
|Cypress|3.3.1|
|OS| Windows 10 and Windows Server 2016|
|Browsers| Electron (headed/headless), Chrome|
|Website| React based, makes use of websockets to load data|
|Webserver| runs on the same machine as cypress|

---

To me it looks like the website is not quite compatible with Cypress CI's testing behaviour - is there a list of pitfalls to know about when writing testable websites?
Has anyone else had similar problems and found the problem or maybe a workaround?

Can I turn on some logging to get more insight into what may be going wrong? Configuring `$env:DEBUG` didn't produce helpful output for me, nor do the `cypress/logs`. Maybe extracting the `console.log` from the browser

The only post I found related to this (occasionally .visit() doesn't load the page, only happening in CI) was [here](https://github.com/cypress-io/cypress/issues/2938#issuecomment-451428083).

**Comment by flotwig** [comment]
@nitzel If you set $env:DEBUG to `cypress:*`, it will capture all the logs from Cypress which will be helpful to debug the problem: https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs 

Share them here and hopefully we can figure it out.

**Comment by nitzel** [comment]
Thank you, here they are: https://gist.github.com/nitzel/ae7928c9558df6a209d7a511cc046ae2
I've stripped away our website's console.log messages and all tests except for the 8th and 9th (the 9th one failed) to shorten the massive log.

**Comment by aviaweinstein** [comment]
We seem to be having a similar issue. A few weeks ago we had a feature branch unexpectedly start failing some tests. All the test failures were happening immediately after `cy.visit('/a_specific_url')` of one specific url. The failures seem to have the same behavior that nitzel describes above. Screenshot attached. Basically the test thinks it successfully visited a url but the page itself is blank and the url appears as just localhost. A few bizarre things: 
- These fails only happen on circleci and not locally
- These fails do only happen in this feature branch and not others although the code that this test checks was not touched in this branch. 
- The fails consistently happen every time we rerun the tests.
- This behavior is consistent across different test files that use the same url in the visit command.
- We attempted to fix by upgrading to cypress 3.3.1 and that seemed to fix the errors for a few days. When we went to merge the feature branch into our dev branch, it started failing again. We upgraded to 3.3.2 and it is still failing.
- A day or so after this test bug was discovered, we had a second developer working on a separate feature branch start seeing similar failing behaviors except only when visiting a different url than the first developer, say `cy.visit('/a_different_url')`.

![Property dashboard  overview page -- With all data -- displays dashboard cards with data (failed)](https://user-images.githubusercontent.com/7773346/60452804-412fa100-9be4-11e9-8b23-2b935d70871d.png)

**Comment by heinzhang** [comment]
We have similar issue. As @aviaweinstein mentioned we changed it back to Cypress 3.1.5 fixed it. 

Our website is react based. There are two xhrs sent after long time with Cypress 3.4.0 (over 2 minutes) 
I change the 'pageLoadTimeout' in cypress.json to 3 minutes seems fix the issue. 

The xhrs below are sent after around 2 mins. 
![image](https://user-images.githubusercontent.com/4383141/61906063-0c301900-af1a-11e9-8de1-cd1a476d2516.png)

But with Cypress 3.1.5 even 'pageLoadTimeout' is 10 seconds would load the two xhr instantly. 
![image](https://user-images.githubusercontent.com/4383141/61906241-6e891980-af1a-11e9-8b23-dbf1725df5c8.png)

I cannot tell the differences from the console output. If you need more information I am happy to provide.

**Comment by sikanhe** [comment]
Just ran into this, I believe Cypress is not letting page sending out ajax/xhr/api requests when visit() is happening. This also only happens on Circie CI headless. Not locally

**Comment by jennifer-shehane** [comment]
Thanks everyone for the detailed information!

If this behavior can be narrowed down to only happening beginning in 3.2.0 then it definitely sounds like a bug. 

@sikanhe @nitzel Does downgrading to Cypress 3.1.5 fix the issue for you?

Looking at the changelog for 3.2.0 it isn't immediately apparent what code could have affected this, although there is a long list of dep updates, so I'll start looking through those.

This is going to be a lot harder for us to even test a fix against though without a reproducible example to run against, so anyone that can provide that would be appreciated.

**Comment by single-stop-neil** [comment]
This looks very similar to the issues I am experiencing on Travis CI (Ubuntu 16.0.4) with Electron 61. 

I have tried running the tests in both headless and headed mode on Travis. The failures are sporadic. The tests pass every time on my laptop (OS X v10.14.6). When I run the tests on my laptop I typically use the GUI and set the browser to Chrome. However, I've also tried Electron in the GUI as well as headless Electron via the terminal. Everything passes on my laptop 

I've attached some sample screenshots from recordings:
![image](https://user-images.githubusercontent.com/52251882/64741878-27ee7f00-d4c8-11e9-9a00-3a6c45fff13b.png)
![image](https://user-images.githubusercontent.com/52251882/64741883-2cb33300-d4c8-11e9-965d-215e429c4304.png)

**Comment by jennifer-shehane** [comment]
Unfortunately we will have to close this issue if there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please everyone try the most current version of Cypress and comment in this issue with a reproducible example 🙏

**Comment by nicholassiu** [comment]
Hello so I have recently run into this issue as well. It runs perfectly fine in the GUI but when I run it headless, it consistently fails every time due to a blank white page. 
I am running:
- Cypress 3.8.2
- macOS 10.14.6

Below is a gif of the headless run and the code:
![botpromo js](https://user-images.githubusercontent.com/55104681/72278744-88620a00-35e9-11ea-9f7e-6f0f7258d13a.gif)

`describe('Visit URL', () => {
    it('Visit page', () => {
      cy.visit('https://dev-us.insightbot.io/smoke-test-landing-184926')
      cy.getByText('Chat On The Web')
    })
  })`

**Comment by danlourenco** [comment]
Same here.  This is very much still an issue on Cypress 3.8.2

**Comment by yuki-93** [comment]
It looks like I have the same issue as @nicholassiu 
I have that loops an it to test some functionally several times, but after first run, I get the blank page. Even the Cypress-Sidebar is gone.

**Comment by bahmutov** [comment]
@nicholassiu the url is not loading `https://dev-us.insightbot.io/smoke-test-landing-184926`

**Comment by rockthis13** [comment]
Yes, I have the same problem, after few times, I get just blank page
![image](https://user-images.githubusercontent.com/59865468/73077999-f3ed8680-3ec9-11ea-84f7-6de59f6d1b29.png)

**Comment by deane187** [comment]
My Test did not have this issue when running in circleCi  until I updated from cypress 3.8.2 -> 3.8.3. When I rerun the test all is well. Unfortunately I am not able to reproduce this issue as it happens sporadically.

App being tested is built in vue.

**Comment by Rose-Lutz** [comment]
I have the same problem, for many days now... What is weird is that this behaviour is not systematic (even though really frequent).

@jennifer-shehane : as you're on the subject (I saw you answers in this ticket and in all those related to blank pages ), I noticed some points that could maybe clarify or give some clues to understand : 

1- it seems that only my tests where I log in through the API are concerned
My tests where I don't have to log in are always ok.
To log in, I use a stub that connects directly through our api, without having to log through the interface.
I thus wrote the same test but where the logging is done through our connection interface : this test is always successfull (no blank page).

2- the bug came suddenly
All my tests (including the ones connecting through the api) were always launched successfully before the 28 january 2020, whatever the number of times I launched them (successively or not).

Could the bug come from cypress?
I had the version 3.6.0 of cypress installed, and everything was ok. I didn't understand why it could have changed so suddenly, but decided anyways to install the latest version (3.8.3), just in case. But the bug was (is) still there.

Could the bug come from our app under test?
We have spend a lot of time looking for changes we could have done that could explain this regression, but nothing came out.
Furthermore, sometimes the tests still pass, without blank screen.

Thus, I ask me now : Could the bug come from Chromium???
Yet, today, in cypress documentation on "launching browsers", I read that "the Chrome browser is evergreen - meaning it will automatically update itself, sometimes causing a breaking change in your automated tests." ( https://docs.cypress.io/guides/guides/launching-browsers.html#Browsers )

Given that Chromium seems to be the unique element that updates automatically, could it be possible that this blank page error comes from it ?

3- I found a way to get around this bug, but it's not sustainable (still randomly successful)
When I launch a successfull test (with no need of login) before a test that cames into error (where there is an api login step), it many times is successfull.
It is better than a total and systematic blank page, but it doesn't work each time, which still is a lot frustrating...

If anybody has an idea of why this bug has appeared and above all how to fix it, please let me know : I am stuck and my automation POC is threatened :s 

Thanks !

**Comment by Rose-Lutz** [comment]
@jennifer-shehane : A colleague of mine has found a solution to this blank page issue.

Actually, I have defined a baseUrl in my cypress.json file.
My tests thus contained a relative path in their cy.visit(). For example, I have tests with `cy.visit('/search')`.

We really don't know why, but now, to be successful, the test must have a dot before the slash.
In my former example, by typing `cy.visit('**./**search')` everything is ok now.

I don't know if this is a solution for everybody, but I hope it could help at least those who use a baseUrl, like us.

**Comment by hannahmclarke** [comment]
We've been seeing this issue for a while now. It happens intermittently when running tests on CircleCI and we found it was only reproduceable locally when running tests headlessly (passed everytime in the UI). 
I found a brief workaround in adding a short wait `cy.wait(100)` that seemed to work for a while, but after upgrading from 3.8.1 to 3.8.3 this came back. I increased the wait slightly and this prevents these tests from timing out everytime, but they do still keep happening intermittently. 
@Rose-Lutz I tried your fix (we do use a baseUrl) but that didn't solve it.

**Comment by Jacek-fstack** [comment]
Happens for my team locally as well... blacklisting GA and google fonts didn't help.
Any ideas how we could approach debugging this?
I can't create an issue, because there's no reliable way to reproduce it, only shows up every ~100 tests.

**Comment by ashwini4444** [comment]
Can anyone find solution of this issue?
i am getting blank page while using cy.visit(). My Cypress version is 4.0.2

**Comment by jennifer-shehane** [comment]
@nicholassiu I cannot get the url you provided to load in a normal browser outside of Cypress. It results in a blank page with many errors in the DevTools Console. This is not related to Cypress

Yet again, I am back to stating that we will have to close this issue as there is not enough information to reproduce the problem. This does not mean that the issue is not happening - it just means that we do not have a path to move forward.

We really, really want to help fix this issue - but we can't without a single way given to reproduce it.

**Comment by Jacek-fstack** [comment]
@jennifer-shehane I get it, but what can we provide to help?
I obviously can't give you access to my app code, because of compliance issues and other things, and on the other hand our 100++ tests would be useless in that case? 
I'd be happy to provide logs, debug extract and whatever we may provide. I just have no idea what may be helpful in this case.

**Comment by Jacek-fstack** [comment]
I'd love at least have an option to retry the cy.visit() after ~15 seconds if it failed. But I don't have an option to handle this error with cypress either.

**Comment by danitt** [comment]
> I'd love at least have an option to retry the cy.visit() after ~15 seconds if it failed. But I don't have an option to handle this error with cypress either.

@Jacek-fstack have you tried this plugin?
https://github.com/Bkucera/cypress-plugin-retries

this one may also be worth investigating
https://github.com/NoriSte/cypress-wait-until

we had similar issues a long while ago, and iirc we used some combination of those to get around it

**Comment by Jacek-fstack** [comment]
@danitt I looked at that, but it doesn't seem like I can isolate retries just for one command [the cy.visit(). 
Or am I mistaken and it is possible?

**Comment by danitt** [comment]
> @danitt I looked at that, but it doesn't seem like I can isolate retries just for one command [the cy.visit().
> Or am I mistaken and it is possible?

@Jacek-fstack no idea, if it were me I'd just apply it globally so you can at least move forward; probably have some other flakes that would benefit from retries anyway ¯\_(ツ)_/¯

**Comment by Jacek-fstack** [comment]
Understood, thank you for the reply :)

**Comment by Jacek-fstack** [comment]
Update for anyone interestd, I managed to 'get around' the issue, by forking the cypres-retries plugin and changing the code a bit, line 123 in the support.js file in that plugin to
```
      if(err.toString().includes("Your page did not fire its 'load' event within")) {
```
HOWEVER the bug is still a pain, it retries sometimes 2 times, because the cy.visit was not triggered.

@jennifer-shehane 
Is there a chance that cypress could expose the cy.visit() command, as a jQuery WITHOUT validation, so I could make my own assertion and not having to repeat the whole tests in case the page does not load?

**Comment by Jacek-fstack** [comment]
For the future:
It seems like the new update fixed that issue for us... AND tests are WAY faster than before.
Good job, cypress team.

**Comment by jmredfern** [comment]
I've been seeing the same issue with sporadic blank pages with Cypress 4.3.0, switching to Chrome instead of Electron seems to have fixed it! 🤞 
```
cypress run --browser chrome --headless
```

**Comment by shaunswales** [comment]
I'm also experiencing this issue with version 4.5.0 and get a white page after logging into my application.

**Comment by Gaurav98990** [comment]
Same issue with version 3.8.3 and upgraded to 4.5.0 white page after running 2-3 steps 
![20200517_002521](https://user-images.githubusercontent.com/52884861/82125237-26075900-97d7-11ea-9b8b-761c5e80c8af.jpg)

**Comment by Gaurav98990** [comment]
> Same issue with version 3.8.3 and upgraded to 4.5.0 white page after running 2-3 steps
> ![20200517_002521](https://user-images.githubusercontent.com/52884861/82125237-26075900-97d7-11ea-9b8b-761c5e80c8af.jpg)
> 
> Why cypress has so many bugs?

Any update on this ?

**Comment by MaciekBaron** [comment]
I am not sure if this is related, but when I try to do visual regression, I get a blank screen unless I perform some other action:

    cy.visit('/');
    cy.matchImageSnapshot('home');

The above creates a blank snapshot (just a white PNG file).

    cy.visit('/');
    cy.get('h1').contains('Home');
    cy.matchImageSnapshot('home');

The above produces a correct snapshot of the page.

**Comment by shunsuke1watanabe** [comment]
I have come across a similar issue.

Cypress suddenly stopped working this afternoon.

Devtools console says it can't find bundle.js.

```
GET https://myappsite.com/assets/b447b79ff50f19679aaa-bundle.js net::ERR_ABORTED 404 (Not Found)

/#/login:1 Refused to apply style from 'https://myappsite.com/assets/b447b79ff50f19679aaa-main.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
I found that this `bundle.js` doesn't exist on the server anymore, when I use Chrome it can show the page properly.

Does anyone have any workarounds?

I have spend whole afternoon to solve this and no dice.
I'm at my wit's end.

**Comment by wujekbogdan** [comment]
I've been experiencing the same issue. I found that it's somehow related to Service Workers. Disabling service workers solves the issue, but I would rather call it a workaround than a solution.

If, after disabling Service Workers, in your app, the problem is still occurring then go to Dev Tools and unregister all awaiting workers and re-rung the tests.

**Comment by cansudiez** [comment]
Hi, are there any updates on this issue?

**Comment by hg13190** [comment]
> 

Facing the same, sometimes cypress is bizarre, the way loops run in cypress is atrocious

**Comment by hg13190** [comment]
> > Same issue with version 3.8.3 and upgraded to 4.5.0 white page after running 2-3 steps
> > ![20200517_002521](https://user-images.githubusercontent.com/52884861/82125237-26075900-97d7-11ea-9b8b-761c5e80c8af.jpg)
> > Why cypress has so many bugs?
> 
> Any update on this ?

Facing the same, sometimes cypress is bizarre, the way loops run in cypress is atrocious

**Comment by Hypenate** [comment]
We're facing the same issue when testing Storybook, sometimes it works and sometimes it does not.
It's showing some flakey behavior.

![Toolbar Stories -- With some elements aligned to the right -- should display two elements on the left and two on the right (failed)](https://user-images.githubusercontent.com/7478681/151943274-1ff9887a-c2e2-4b18-887a-374052edecd7.png)

**Comment by ajsamra** [comment]
Facing the same issue with cypress 7.0.1. Tests will randomly fail with this error - behavior is inconsistent. The same test will pass in one test run and fail in the next

```
CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route:...
```

**Comment by jogelin** [comment]
Same issue here with the latest Cypress 9.4.1. We are using the Nx stack with Angular + Storybook and often times we have a white page on app testing and on Storybook too.

By using selectors, we had some expectations on the DOM to exist and it is there! We tried step by step to access the DOM and each time we add a level of a selector, we see that the page is not white anymore but displaying the element we selected. Still, the test is failing because the rest of the page isn't loaded.

Just the page isn't displayed/mounted so our requests are not triggered. Still no idea why

We are using Electron

**Comment by nileshbrahme** [comment]
Facing the same issue with cypress 9.5.1. Blank is showing up, please provide some solution
![cypress_blank_page_issue](https://user-images.githubusercontent.com/62586796/157859692-cee1343e-292d-4eb1-9b03-bbdedaa704c9.jpg)
.

**Comment by wujekbogdan** [comment]
Sometimes changing the browser to Firefox helps.

**Comment by anitaejoseph** [comment]
I am also getting the same issue of blank page with cypress 9.5. I have upgraded to 9.5.2 version, still getting blank page after logging to my website.

**Comment by gedeal** [comment]
I have a "solution" in my tests,  It seems that the IT steps loose the URL
Remove all the IT steps :
describe('Registrer Native', () => {
  // it("Verify1", () => {
   : a
  // })
 
  // it("Verify2", () => { 
   : b
  // })
  
})

Now I have a structure like (only one IT step):
describe('Registrer Native', () => {
  it('Whole test- Without IT parts', () => {
  
: a
: b
: c
  })
})

It is not an optimal solution as I now have a long test , without intermediaries IT tests

**Comment by dario-digregorio** [comment]
Still having this issue in Cypress 10.2.0

But I found (kinda) a workaround by adding a retry to my tests. 
https://docs.cypress.io/guides/guides/test-retries#Configure-Test-Retries

It still fails occasionally but at least less...

**Comment by alexmitylite** [comment]
Hey everybody. I'm getting this same issue with Cypress 13.2.0 😢. I'm currently going through the Cypress test course and I'm experiencing this issue with the "cypress-realworld-testing-course-app" repo.

Page is fine when it first loads:

![image](https://github.com/cypress-io/cypress/assets/81777857/c65e7984-8ea3-4b18-bdfb-4e038a8d18e9)

But when I hover over one of the steps, the page goes blank:

![image](https://github.com/cypress-io/cypress/assets/81777857/d09a4fc7-6266-4bcc-8633-471ab77fee82)

I'm on a Lenovo P14s Thinkpad running Windows 11.

**Comment by nagash77** [comment]
Hi @alexsch01 I would encourage you to check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

If that does not help you, and you think this is a bug in Cypress please open a new issue.

**Comment by alexsch01** [comment]
> Hi @alexsch01 I would encourage you to check out the Cypress Discord Community [![Discord chat](https://camo.githubusercontent.com/2a85a51f7a1b7a1f35aca577da0eedf98d445a1036907adab5d74c49cf91bd5b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636861742d6f6e253230446973636f72642d627269676874677265656e)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.
> 
> If that does not help you, and you think this is a bug in Cypress please open a new issue.

?? I don't remember being part of this thread

**Comment by alexmitylite** [comment]
Hey @alexsch01 , it looks like @nagash77 was trying to tag me and he accidently tagged you instead. @nagash77 , thanks for the tip to checkout the Discord community, just joined that.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue. Please open a new issue with a specific reproducible example of the behavior that's happening.  We've made a LOT of updates since this was originally opened and there could be a LOT of contributing factors that would cause a page under test to appear blank or partially blank. In order to best address the issues, we plz ask for a reproducible example. 🙏🏻
