### ISSUE TITLE
Warn when ProxyMode/ExtensionWhiteList registry setting is detected

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4391]
Cypress fails in strange ways if a ProxyMode policy is set on the user's computer, because it can break Cypress's proxy when running tests in Chrome.

We should:

* warn the user on the command line when Cypress is launched if we detect this setting
* maybe also warn the user if they try to launch Chrome with this setting enabled - could have chrome greyed out, or add a small :warning: sign or something with a tooltip explaining this problem - also don't set Chrome as the default browser

Relevant issues: #1253 and #4263

----

Should also detect ExtensionWhiteList/other problematic extension settings. 

Relevant issues: #1239, #2494

**Comment by wojciechsabaj** [comment]
@flotwig I fully agree with your decision. The best solution (from user's and UI/UX's point of view) will be adding a small ⚠️ sign before the browser's name. You should also introduce a balloon tip (when ⚠️ is hovered) saying what the problem is, like this:

"We detected ProxyMode key in your registry. Cypress's proxy cannot work properly with Chrome. To fix this issue, please [visit this page | remove the following keys | any other kind of advice that you can give to help people find out what's happening]

You can put a link to one of your pages describing the situation and possible solutions. I think that it is not so good to just tell people "hey, just remove those keys", as some people may have no rights to perform such actions, however, this will be the most straightforward solution.

Hope this helps :) Keep doing a great job with Cypress!
