### ISSUE TITLE
.select() on value not on label

### ISSUE THREAD

**Issue by ChrLei** [cypress-io/cypress#441]
Hi there, I encounter a problem with `cy.select('label')` when using a dropdown list where all the values of the options are the same.

```html
<select>
  <option value="foo">label 1</option>
  <option value="foo">label 2</option>
  <option value="foo">label 3</option>
<select>
```

In the test we use `cy.select(‘label 1’)` which results in an error because of Cypress doing something with the value instead of the text. Probably because it uses the underlying value to select an option, even when you select on the labels.

**Comment by brian-mann** [comment]
Fixed in [`0.19.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0191-03092017).

**Comment by ChrLei** [comment]
Sweet!

**Comment by damianocastro** [comment]
I don't think this case is fixed in all cases. I tried this example and always selects the first one when a valid text is selected. The html and test.js are both in the zip. My version is 0.19.4.

[select.html.zip](https://github.com/cypress-io/cypress/files/1125944/select.html.zip)

**Comment by chrisbreiding** [comment]
Thanks for the repro, @damianocastro. It looks like the fix for this is incomplete and needs a bit more work. 

Currently, when all the options have the same value, we set the 'selected' prop on the `<option>`(s) that match. I believe we also need to set the `selectedIndex` and maybe the `selectedOptions` props on the `<select>` itself.

**Comment by chrisbreiding** [comment]
Moving the continued work on this issue to https://github.com/cypress-io/cypress/issues/554.
