### ISSUE TITLE
"Browser was not launched through Cypress" after 3.3.0 upgrade

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#4410]
After installing 3.3.0 I get the Whoops' window ('This browser was not launched through Cypress'), trying to run Chrome 74.
The Cypress add-in *is* loaded in to Chrome. The add-in is shown as version 0.0.0
The tests run fine under Electron 61.

Back to Cypress 3.2.0 and Chrome 74 runs again without problems.

_Originally posted by @petermouton in https://github.com/cypress-io/cypress/issues/4260#issuecomment-494693673_

---

Cypress 3.3.1

![Cypress_Chrome_error](https://user-images.githubusercontent.com/48205462/59035814-609a0f00-886e-11e9-80e7-fec3a4aec4ee.PNG)

_Originally posted by @PetMou in https://github.com/cypress-io/cypress/issues/4260#issuecomment-499488347_

**Comment by flotwig** [comment]
@petermouton @PetMou It looks like Chrome is being launched with an incorrect path to the spec, which is causing this error. Can you share the full `DEBUG` logs, from the time to when you launch Cypress to when you launch Chrome and experience this error? Instructions for debug logs are here: https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs

**Comment by PetMou** [comment]
Thanks Zach. I added the debug log
[cypress_debug_4410.log](https://github.com/cypress-io/cypress/files/3275448/cypress_debug_4410.log)

**Comment by PetMou** [comment]
Parallel to issue #4260, I tried several options. Extra information:
- We run in a Windows 10 environment
- I now have more cypress installations next to eachother on the same disk. 3.3.1 to try options, 3.2.0 for the daily jobs. Testlife must go on...
- command **cypress open --browser chrome** will open the project correcly, whereas **cypress open --browser "C:\<path>\chrome.exe"** displays a message that cypress can't find a browser at that location. Which is strange, because the path is correct, and chrome does start, using this path.
- To start 3.3.1 I have to use a command file because I need to set **NO_PROXY=undefined** beforehand to avoid cypress saying it can't start the server
- I have installed cypress from within IntellIJ

Hope this gives some extra clues.

**Comment by flotwig** [comment]
Hey @PetMou, I was able to reproduce your issue, can you try something for me? Run with `NO_PROXY=undefined,localhost`.

The core problem is that requests for Cypress's internal server on `localhost` are going through your proxy, which will be fixed with #4358 (should be out in 3.3.2).

**Comment by PetMou** [comment]
Wow. That did the trick!
Thank you! 

Check, one more happy customer! :))

**Comment by munna73** [comment]
I am having this issue in Cypress 4.10.0. I am using my work computer.Works fine on electron 80 but  when I select chrome it gives error The browser was not launched through cypress , tests can not run

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

@munna73 If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
