### ISSUE TITLE
can't open cypress 3.3.1 on windows it just stuck at "Opening Cypress..."

### ISSUE THREAD

**Issue by Nagimagi** [cypress-io/cypress#4442]
npm: v4.2.6
node: 3.5.2
cypress: 3.3.1

It is successfully installed using bash on windows 10.
I tried it on multiple win10s but they all resulted the same.

after i have used `node_modules/.bin/cypress open `
the Cyress is verified, but it just stuck at "Opening Cypress..."
there aren't any further move after that. I had no choice but to ^C.

What should I do? 
Should i just download the Cypress.exe？
I wonder if there are any docs for supporting windows version CI ? cuz I am not very familiar of the dependencies on windows if there should be any.

**Comment by jennifer-shehane** [comment]
Could you run `cypress open` in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the logs here?

**Comment by slappinlappin** [comment]
Hello, not sure if this is related or helpful but I recently tried updating to 3.3.1 and got this message:


 ×  Verifying Cypress can run C:\Users\MyLocalPath\AppData\Local\Cypress\Cache\3.3.1\Cypress
   → Cypress Version: 3.3.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

Command failed: C:\Users\MyLocalPath\AppData\Local\Cypress\Cache\3.3.1\Cypress\Cypress.exe --smoke-test --ping=876

----------

Platform: win32 (10.0.17763)
Cypress Version: 3.3.1


I tried a variety of different things, including following the docs cited, but wasn't able to open Cypress because of this. I have rolled back to 3.3.0 in the meantime.

**Comment by SUSANO-O** [comment]
hello good day there are examples of how to use window other than cypress documents.

**Comment by jennifer-shehane** [comment]
In order to direct better focus on the overall problem that is being described in several issues - we opened one issue to track this behavior https://github.com/cypress-io/cypress/issues/4624 Please add any information about how we can reproduce this bug there. 🙏
