### ISSUE TITLE
Configure trashAssetsBeforeRuns to be true after X number of runs

### ISSUE THREAD

**Issue by Murkantilism** [cypress-io/cypress#4445]
### Current behavior:

When `trashAssetsBeforeRuns` is true, Cypress deletes assets before running. When it is false, it doesn't.

Right now, after a cypress test failure in our CI system a developer has to "race" to grab the video file before the next run destroys it. If the developer is busy, away, napping, eating, whatever and they return to find their test run failed, they have no footage to review if another run had been executed after their previous run.

### Desired behavior:

A way to configure Cypress to wait to `trashAssetsBeforeRuns` until X number of runs have been completed. 

Would be ideal if Cypress waited to `trashAssetsBeforeRuns` until 5 videos are already present, for example. Then it trashes the oldest one and proceeds with the next run. This way there's a quasi-archive of the last 4 runs as the 6th run begins to execute.

Simplest way to implement is probably just to count the number of MP4 files present in `videosFolder` and compare against date times to pick one to trash.

**Comment by jennifer-shehane** [comment]
Hey @Murkantilism, you can always access the video of previous runs from within the Dashboard if you [set up your project to record](https://docs.cypress.io/guides/core-concepts/dashboard-service.html#Setup).

Aside from this suggestion, we think this issue is more specific to your internal process setup than a feature that Cypress will out of the box support.  

You can turn off `trashAssetsBeforeRun` and set up some code in your CI system to trash the videos folder every x runs - or access the video afterwards to have it moved somewhere else using our [Module API](https://on.cypress.io/module-api#cypress-run).

**Comment by Murkantilism** [comment]
Thanks @jennifer-shehane! Didn't realize the Dashboard could also be setup with CI runs =)
