### ISSUE TITLE
Opacity is not considered for visibility checks

### ISSUE THREAD

**Issue by FredyC** [cypress-io/cypress#4474]
### Current behavior:
![image](https://user-images.githubusercontent.com/1096340/59603964-0e2cde00-910b-11e9-899a-92457e3d0b81.png)

### Desired behavior:
When opacity === 0, the element should be considered as not visible to avoid evaluating the next command sooner than expected and causing flakiness.

### Steps to reproduce: (app code and test code)
I think the issue is pretty clear from the image, but I can provide reproduction later if you consider it necessary.

### Versions
cypress@3.3.1
Electron 61
Windows 10 x64

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-78) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Nice. Thanks for opening this issue. Was going to do this myself. 

I am currently working on visibility fixes - one of which was implementing this change for opacity. We had initially decided not to consider elements with opacity 0 as 'not visible', because they are still interact-able, but we're going to be pulling this all out into a broader issue so that there can be different checks for 'can be seen', 'can be seen in viewpor', and 'can be interacted with'

Read more here: https://github.com/cypress-io/cypress/issues/1242

Some of our previous reasoning: https://github.com/cypress-io/cypress/issues/677

I actually have already written the code for the opacity check (commented out in this PR https://github.com/cypress-io/cypress/pull/4421) - as this would be implemented as part of the 'can be seen' code, but I think due to the change, this would have to go into a major code version update as it would be breaking our users current expectations.

## Workaround Today

Make sure that `0` is a string in your assertion, not a number - as all css properties evaluate to strings.

```js
cy.get('div').should('have.css', 'opacity', '0')
```

**Comment by ali-rival** [comment]
How would you suggest conditionally checking if an element `opacity: 1` or `opacity: 0`? I'm thinking along the lines of: 

```if ($button.is(':visible')){
  $button.click();
}```

but my buttons are considered visible because they are hidden only by opacity.

**Comment by mvriel** [comment]
> We had initially decided not to consider elements with opacity 0 as 'not visible', because they are still interact-able

I have actually worked on a piece of code that also set the `pointer-events` to `none`; effectively making it non-interactable. This was done to have an invisible element fade in using CSS transitions. (display: none will kill the fade)

**Comment by diegovincent** [comment]
@jennifer-shehane I think that the fact that `opacity: 0` is considered visible due to the interactivity, is a fairly good argument, as long as two things are taken into account:

1. The user can modify this behaviour with some option argument, ie, just like we have `timeout`, we could have `opacity-is-visible` (bad name, but good for the example).
2. This is properly documented in [the visibility section of the interaction guide](https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Visibility), which is not done nowadays, it does not even mention it.

What do you think?

**Comment by jennifer-shehane** [comment]
This fix requires a breaking change, so is targeted for our next breaking change release. You can follow along with progress on this release here: https://github.com/cypress-io/cypress/pull/8437
