### ISSUE TITLE
Can't use Custom Commands

### ISSUE THREAD

**Issue by Thanh96** [cypress-io/cypress#4537]
### Current behavior:
![Screenshot 2019-06-21 12 06 52](https://user-images.githubusercontent.com/29529118/59899051-7803fb00-941d-11e9-949d-87911abcac39.png)

![Screenshot 2019-06-21 12 06 40](https://user-images.githubusercontent.com/29529118/59898957-28bdca80-941d-11e9-8b09-c56258798ba6.png)

i can't use this custom commands.
### Desired behavior:

No error should be found

### Versions
3.3.1

**Comment by jennifer-shehane** [comment]
Types do not exist for custom commands since you defined the custom command yourself, you will have to add the Types as described here. https://on.cypress.io/typescript-support#Types-for-custom-commands

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

Also, check out our [community chat](https://on.cypress.io/chat), it can help with debugging or asking questions about how to use Cypress.
