### ISSUE TITLE
Testing A Form in Cypress

### ISSUE THREAD

**Issue by Karrar-Naqvi** [cypress-io/cypress#4550]
I have to automate an app completely which involves many pages like add agency, add new user etc now in these pages i have to fill many input fields

I want to get the values of these input elements and save them in a constant (One constant for each input field) As i have to test these input fields from many aspects in many tests like if an iput is accepting alphabets for phonenmbr field or if the required fields are showing any error if not filled or if they are accepting the characters beyond their fixed limit or for other type of validations

So is there any way in cypress that i store element values in constant like (const username = cy.get('.username') in any file (using fixture) or by using command.js

and then use them in various tests like (username.type('Jhon')

Kindly help me in this regard with best practices or guide me towards useful links in this regard

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our [premium support options](https://www.cypress.io/support/).
