### ISSUE TITLE
Misleading documentation (cy.exec stderr)

### ISSUE THREAD

**Issue by MikeSquall** [cypress-io/cypress#4573]
I tried to run this [example](https://docs.cypress.io/api/commands/exec.html#Choose-to-not-fail-on-non-zero-exit-and-assert-on-code-and-stderr) from documentation but it didn't work as described.

cy.exec(...).its('stderr').should(...) doesn't work with its('code').should(...)

### Current behavior:

```js
it('Run `man bear pig` throws an error', () => {
    cy
      .exec('man bear pig', { failOnNonZeroExit: false })
      .its('code').should('eq', 16)
      .its('stderr').should('contain', 'No manual entry for bear');
  });
```

![Result](https://i.ibb.co/xYgJ7cT/cy-fail.png)

Actually, it works only if I do expectation only on one (code or stderr).
Only `stderr`:
![Result](https://i.ibb.co/mzMBwq3/cy-ok1.png)

Only `code`:
![Result](https://i.ibb.co/BBHTDL7/cy-ok2.png)

### Desired behavior:

I wish I could use both of them simultaneously.

### Steps to reproduce: (app code and test code)

Writing this in a test and run it 
```js
it('Run `man bear pig` throws an error', () => {
    cy
      .exec('man bear pig', { failOnNonZeroExit: false })
      .its('code').should('eq', 16)
      .its('stderr').should('contain', 'No manual entry for bear');
  });
```

### Versions

| Cypress | operating system | browser |
|-------------|------------------------|-----------------|
| 3.3.1      |  Ubuntu 18.04      | Chrome 75 |

**Comment by jennifer-shehane** [comment]
This is due to how [chaining works in Cypress](https://on.cypress.io/introduction-to-cypress#Chains-of-Commands). 

- `cy.exec()` yields  yields an object with the properties: code, stdout and stderr. https://on.cypress.io/exec#Yields
- `.its()` yields the value of the property. https://on.cypress.io/its#Yields
- `.should()` here yields the subject it was given https://on.cypress.io/should#Yields

The first `its()` is chained off of `exec()` so it it passed the object, but the second `its()` is chained off of the other `its().should()` chain, so it's only being passed the `code`. 

You can test what is yielded by chaining a `.then()` off of any command and by using `console.log` or `debugger`. 

```js
it('Run `man bear pig` throws an error', () => {
    cy
      .exec('man bear pig', { failOnNonZeroExit: false }).then((ret) => {
      	console.log(ret)
      })
      .its('code').should('eq', 16).then((ret) => {
        console.log(ret)
      })                             
      .its('stderr').should('contain', 'No manual entry for bear').then((ret) => {
        console.log(ret)
      })
  });
```

What you likely want to write:

```js
it('Run `man bear pig` does not throw an error', () => {
    cy
      .exec('man bear pig', { failOnNonZeroExit: false }).then((obj) => {
      	expect(obj.code).to.eq(16)
        expect(obj.stderr).to.contain('No manual entry for bear')
      })
});
```

So yes, our example is completely wrong. I created a new issue in our [docs](https://github.com/cypress-io/cypress-documentation) to document fix this example here: https://github.com/cypress-io/cypress-documentation/issues/1815. Our documentation is open source and contributions are welcome. 😄

**Comment by MikeSquall** [comment]
Thank you
