### ISSUE TITLE
Cypress won't open Chrome 75 inside test runner

### ISSUE THREAD

**Issue by nchaudry** [cypress-io/cypress#4578]
### Current behavior:
After clicking a test to run in Cypress window, A blank google chrome tab is launched (no 404) and nothing happens.  The same test works using Electron 61, and was working a few days ago under Chrome 74.

![cy1](https://user-images.githubusercontent.com/26577562/60212935-6f9e2c80-9830-11e9-85fd-9f133dd2fdd3.PNG)
![cy2](https://user-images.githubusercontent.com/26577562/60213002-93fa0900-9830-11e9-84e8-45fe6b8d8356.PNG)
### Desired behavior:
Clicking a test in the Cypress window while Chrome 75 is selected should launch the test runner using Chrome 75

### Steps to reproduce: (app code and test code)
Open cypress using npx cypress open
Have Chrome 75 selected as test browser
Click a test to run
ISSUE:  A blank chrome tab opens up outside of the test runner
Was not solved with https://github.com/cypress-io/cypress/issues/1872#issuecomment-450807452

### Versions
Cypress 3.2.0
Cypress 3.3.1
Windows 10
Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by flotwig** [comment]
@nchaudry Thanks for reporting this. Can you share [debug logs](https://docs.cypress.io/guides/guides/debugging.html#Print-DEBUG-logs) from when you encounter the issue?

Also, can you visit and share the contents of `chrome://policy` from inside of Chrome?

**Comment by nchaudry** [comment]
@flotwig Thanks for the quick response.  Here is an attachment of the policy:

![Policy](https://user-images.githubusercontent.com/26577562/60214637-dec95000-9833-11e9-9dd6-59d14c7d4074.PNG)

As for the debug, I tried what the docs said, in my bash I set `set DEBUG=cypress:*`

And ran `npx cypress open`

In the blank google tab I launched, I got this message in the console:

`Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'sha256-EVjR8L4xuo0c7UNzAtLmKQoojKIjdHqYIqdanwmukFQ=' 'sha256-RuPNBCRDlU14rTJUWeNxqVMJBitEXwTmJPzLoMt7fEs=' 'sha256-YC9EJRgaR9dYl+dijW/U6uoFrb5FDreTpYwoTgNGfbc=' 'sha256-Wz4hra5DkiuVk7RuGJIGygK6BFeiHSwqDiFv7AUpjBk=' 'sha256-YnJ0Kv9P96X4+MCJu8d0U/UVQ1+JYkdPlVQ3Exh9shA=' 'sha256-V6HgSA4/YCmSdnKcHQ/7Ko62+rlF1n+TO0COkMK7SM0=' 'sha256-f3V2UCsvKFjtCioV+F2FiGILz9glItZ2PRmSfHGGhBQ='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
`

I'm not too familiar with debugging, I hope this helps, otherwise I may need a little more hand holding on the debugging portion

**Comment by flotwig** [comment]
@nchaudry Thanks for providing this. 

I noticed two things about your issue:

1. Your Chrome doesn't open up to the page that Cypress is telling it to open to
2. Your Chrome doesn't have the Cypress Chrome extension installed (should happen automatically)

Normally this is caused by bad policy settings that prevent Cypress from installing its extension; however, I see that you don't have any policy that would block that.

I'm thinking that the `ExtensionInstallForcelist` may be the issue here. I think that "Websense Endpoint" extension is blocking Cypress from working properly.

Could you try to follow the instructions in this guide and remove that extension in your `ExtensionInstallForcelist`, then try re-launching?

See #1253 for more history on these types of issues.

**Comment by nchaudry** [comment]
🤦‍♂ This indeed was the issue.  On my first installation of cypress I had to uninstall the forcepoint webpoint.  It was fine until chrome updated to 75, and forcepoint somehow reinstalled itself as well.  Thanks for your help and sorry for the inconvenience.
