### ISSUE TITLE
Feature Request: Allow alias for record keys to aid in managing multiple keys

### ISSUE THREAD

**Issue by rdooh** [cypress-io/cypress#458]
Current use cases in mind include having reserved keys for CI and other automated tasks, while also having general use keys for teams to run/record/share for subsets of total tests.  Being able to provide an alias for each key would help keep them straight.

**Comment by jennifer-shehane** [comment]
@trydionel 	Dashboard suggestion

**Comment by jennifer-shehane** [comment]
cc @cypress-io/services

**Comment by jennifer-shehane** [comment]
The best place to express interest and see progress for Dashboard features is on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard and we want to make sure any feedback gets seen and addressed by the right team. 

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thanks!
