### ISSUE TITLE
Test cases are not working with electron browser

### ISSUE THREAD

**Issue by ssamaji** [cypress-io/cypress#4590]
# Current behavior: 

I am getting blank page when i run my tests in electron.(no data on UI). any idea why i am getting this exception when i use electron `VM136 main.5424510dff4c3766dd34.js:5 user beacon call failed Error: Session expired. Please login again.`

![image](https://user-images.githubusercontent.com/26387897/60291919-a3b14480-9939-11e9-9644-0bd776a9b69b.png)

### Desired behavior: 

working fine with chrome, chromium and canary

![image](https://user-images.githubusercontent.com/26387897/60291784-5339e700-9939-11e9-8780-81ee3f9ba068.png)

### Steps to reproduce: (app code and test code)

[referralHistory.log](https://github.com/cypress-io/cypress/files/3336215/referralHistory.log)

[indexFile.txt](https://github.com/cypress-io/cypress/files/3336246/indexFile.txt)
[ReferralHistoryTestCase (1).txt](https://github.com/cypress-io/cypress/files/3336257/ReferralHistoryTestCase.1.txt)
[commands.txt](https://github.com/cypress-io/cypress/files/3336248/commands.txt)

### Versions
Version 3.3.0 
Electron 61
macOS

**Comment by jennifer-shehane** [comment]
When running in Electron, your tests are running against Chromium version 61. If you are using technologies in your application that were only supported in later Chrome versions, you may see some errors from your application when running outside. 

The error that you should look into is the first error in the console in the screenshot, the one about a Syntax Error that states "This error is originating from your application code" - I'd check to see where that is originating from, because that is breaking in Chromium 61. 

We are in the process of updating Electron here: https://github.com/cypress-io/cypress/issues/4270

**Comment by ssamaji** [comment]
@jennifer-shehane Thank you for a quick reply. any ETA when you are releasing v4.0 ?

**Comment by jennifer-shehane** [comment]
No ETA. There is work being done to the upgrade everyday. Make sure to watch the issue for any updates. Closing in favor of https://github.com/cypress-io/cypress/issues/4270

**Comment by jennifer-shehane** [comment]
Electron has been upgraded to 7.1.10 as of Cypress 3.8.3 and should be resolved.
