### ISSUE TITLE
Waiting for selector in cypress

### ISSUE THREAD

**Issue by MadHatter122312** [cypress-io/cypress#4592]
I am refactoring my ui tests from Puppeteer to Cypress, and while reading the documentation I was not able to find a way to wait for an element to appear on the page.

For example, there does not seem to be a method such as waitFor(#someId), such as in Puppeteer.

Does Cypress support something similar?

**Comment by bahmutov** [comment]
Pretty much every command in Cypress has it - check out this doc https://on.cypress.io/retry-ability

**Comment by MadHatter122312** [comment]
> Pretty much every command in Cypress has it - check out this doc https://on.cypress.io/retry-ability
> […](#)
> Sent from my iPhone
> On Jun 27, 2019, at 16:38, ID ***@***.***> wrote: I am refactoring my ui tests from Puppeteer to Cypress, and while reading the documentation I was not able to find a way to wait for an element to appear on the page. For example, there does not seem to be a method such as waitFor(#someId), such as in Puppeteer. Does Cypress support something similar? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Hmmm, perhaps I am not being clear about my use case.

Use case:  I want to be able to have the test await until a specific element is loaded on the page.  I am not testing XHR requests, I simple want to verify that an element has been loaded by selector, and then proceed to the next.

**Comment by bahmutov** [comment]
Sure, so here is the `cy.get` which will retry until the element is in the dom 

https://docs.cypress.io/api/commands/get.html#Assertions

you can change the passing condition by attaching assertions. For example, retry getting an element until it is visible

```js
cy.get('.my-class').should('be.visible')
```

or wait until there are 10 elements in the list

```js
cy.get('li').should('have.length', 10)
```

Perhaps reading https://docs.cypress.io/guides/getting-started/writing-your-first-test.html guide will answer all these questions

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our [premium support options](https://www.cypress.io/support/).
