### ISSUE TITLE
cy.writeFile does not work with variable values

### ISSUE THREAD

**Issue by Ceesiebird** [cypress-io/cypress#4596]
### Current behavior:

When using `cy.writeFile` using a variable as the value to write to file, it hangs indefinitely during execution.

### Desired behavior:

using `cy.writeFile` using a variable as the value to write to file should work just like writing a string to file works currently and write the variables value to a file.

### Steps to reproduce: (app code and test code)
run the following in a Cypress test.

```js
    var token = cy.get('#app > div > div.box > p') // use a valid text box locator here.
    
    cy.writeFile('C:\yourpathhere\token.txt',token)
```

### Versions

Cypress Version 3.3.2
Chrome 75 and Electron 61
OS Windows 10 pro v17763

**Comment by jennifer-shehane** [comment]
This is a bit tricky because your variable is actually pointing to a reference of Cypress, not what is yielded from the Cypress command. See https://on.cypress.io/variables-and-aliases for a more in depth explanation on why using variables in this way with Cypress promises is not advised. 

So, depending on what you want to do, you can do one of the following:

```js
it('writes the selector into the file', function () {
  cy.visit('https://example.cypress.io')

  let token = 'cy.get("h1")'

  cy.writeFile('cypress/fixtures/dom1.txt', token)
})

it('it should be possible to fill a form field', function () {
  cy.visit('https://example.cypress.io')
  cy.get('h1').then(($h1) => {
    cy.writeFile('cypress/fixtures/dom2.txt', $h1)
  })
})
```

dom1.txt - just our string.

```
cy.get("h1")
```

dom2.txt - the jQuery selector object

```
{
  "0": {},
  "selector": "h1",
  "context": {
    "location": {
      "href": "https://example.cypress.io/",
      "ancestorOrigins": {
        "0": "https://example.cypress.io"
      },
      "origin": "https://example.cypress.io",
      "protocol": "https:",
      "host": "example.cypress.io",
      "hostname": "example.cypress.io",
      "port": "",
      "pathname": "/",
      "search": "",
      "hash": ""
    },
    "jQuery112005046871802612689": 1
  },
  "length": 1
}
```


Likely you want to do something else with the $h1, but I don't know what the end goal is for you, so I'd suggest playing around with it. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).
