### ISSUE TITLE
Cypress fails to run on Jenkins 'FATAL:v8_initializer.cc(247)] Couldn't mmap v8 natives data file, status code is 1'

### ISSUE THREAD

**Issue by kkliuiev** [cypress-io/cypress#4615]
### Current behavior:
I've installed Cypress on my Jenkins on AWS EC2. Observed no issues during installation. Also I've installed all the dependencies by:
`sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2`
and chromium and chrome. When I do:
`npx cypress run --browser chrome` or `npx cypress run --browser chromium`
I receive the next:
```
[?25l[02:34:25]  Verifying Cypress can run /var/lib/jenkins/.cache/Cypress/3.3.2/Cypress [started]
[02:34:25]  Verifying Cypress can run /var/lib/jenkins/.cache/Cypress/3.3.2/Cypress [failed]
[?25hCypress failed to start.
This is usually caused by a missing library or dependency.
The error below should indicate which dependency is missing.
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies installed.
[24577:0630/023425.217984:FATAL:v8_initializer.cc(247)] Couldn't mmap v8 natives data file, status code is 1
```
### Desired behavior:
Being able to run Cypress on Jenkins on EC2

### Versions

Platform: linux (Ubuntu Linux - 18.04)
Cypress Version: 3.3.2

**Comment by jennifer-shehane** [comment]
What version of Chrome/Chromium do you have installed? How did you install the Chrome browsers?

**Comment by kkliuiev** [comment]
@jennifer-shehane Hi! I've got Google Chrome 75.0.3770.100 running on Ubuntu 18.04.2 LTS

**Comment by kkliuiev** [comment]
@jennifer-shehane Sorry, is there any info on issue I've reported?

**Comment by TolikChirkov** [comment]
https://www.bbc.com/news/world
BBC World - World - BBC News

**Comment by TolikChirkov** [comment]
https://genius.com/amp/Ariana-grande-thank-u-next-lyrics
Ariana Grande – ​thank u, next Lyrics | Genius Lyrics

**Comment by TolikChirkov** [comment]
https://jdk.java.net/13/
JDK 13 Early-Access Builds - Java (JDK) - Java.net

**Comment by maryhipp** [comment]
We are also getting this error running on Jenkins in parallel containers that have image `cypress/browsers:node8.15.1-chrome73`

```
[?25l[17:41:24]  Verifying Cypress can run /root/.cache/Cypress/3.3.2/Cypress [started]
[17:41:24]  Verifying Cypress can run /root/.cache/Cypress/3.3.2/Cypress [failed]
[?25hCypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

[89:0716/174124.381907:FATAL:v8_initializer.cc(247)] Couldn't mmap v8 natives data file, status code is 1

----------

Platform: linux (Debian - 9.8)
Cypress Version: 3.3.2
```

**Comment by kkliuiev** [comment]
I'm running that on EC2 native Ubuntu, not from docker just from Ubuntu. What I have to do?

**Comment by MY729** [comment]
When running cypress run on Jenkins, the following questions are prompted, what should I do?
-----------------------------------------------------------------------------
It looks like this is your first time using Cypress: 4.6.0

[?25l[19:42:16]  Verifying Cypress can run /root/.cache/Cypress/4.6.0/Cypress [started]
[19:42:16]  Verifying Cypress can run /root/.cache/Cypress/4.6.0/Cypress [failed]
[?25hCypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

/root/.cache/Cypress/4.6.0/Cypress/Cypress: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory

----------

Platform: linux (Centos - 7.2.1511)
Cypress Version: 4.6.0

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
