### ISSUE TITLE
Drop down list does not appears

### ISSUE THREAD

**Issue by mohamedyoussefmaaref** [cypress-io/cypress#4617]
Hello,

I have a dropdonw list with `<span>` and i can't select any item on it. 
I tried this code but it doesn't work.

```js
cy.get('#menu-item-1550')
	.should('be.hidden')
	.invoke('show')
	//.should('be.visible')
	.click( { force: true })
```

 also i tried this one by selecting the head list but also doesn't work.

```js
cy.get('.vc_col-sm-8 > .vc_column-inner > .wpb_wrapper > .main-menu-wrapper > .header-sticky > .nav-container > .horizontal-menu > #primary > .menu_holder > .menu_inner > #main_ul-primary > .first > [href="http://influencefurniture.mobelite.fr/collections/"] > .link_content')
	.trigger('mouseup')
	.get('#menu-item-1550')
	.invoke('show')
	.click( { force: true })
```

**Comment by jennifer-shehane** [comment]
In order to help with this - we'd have to see the exact HTML with its CSS that you are testing against.

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our [premium support options](https://www.cypress.io/support/).
