### ISSUE TITLE
Erroneous parallel flag on a run that was completed over 24 hours ago error.

### ISSUE THREAD

**Issue by skjnldsv** [cypress-io/cypress#4627]
Ref https://twitter.com/skjnldsv/status/1145223216316715008

### Current behavior:

![Capture d’écran_2019-07-01_16-41-32](https://user-images.githubusercontent.com/14975046/60445240-1ca4ea80-9c1f-11e9-90cc-2d41b55d819e.png)
https://cloud.drone.io/nextcloud/viewer/231/2/5

Pull request: https://github.com/nextcloud/viewer/pull/156

After restart, it stared and completed properly.

### Desired behavior:

No errors, test starts.

### Steps to reproduce: (app code and test code)

1. Dependabot opened an issue with a package.json update.
2. Cypress rejected the build stating the job was 24h+ old, but it was just created.

### Versions

Cypress (version: 3.3.1)

**Comment by bahmutov** [comment]
@skjnldsv in the dashboard for the existing run it shows the CI build id - can you paste it here, please? This is the build id it thinks has already been used. Might be grabbing a wrong environment variable on Drone.io to link the builds together

**Comment by bahmutov** [comment]
and another thing @skjnldsv - we extract the following environment variables on Drone to link builds together and distinguish old builds from new ones: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/util/ci_provider.js#L179

Can you install one more NPM dependency and run it before the tests in each container, please? It is https://github.com/bahmutov/print-env and the way you would use it is

```
npm i -g @bahmutov/print-env
print-env DRONE
```

This will print all env variables that start with `DRONE` - there should not be any sensitive information there. But we would like to see these variables from successful run and from a failed run, ok?

**Comment by skjnldsv** [comment]
> skjnldsv in the dashboard for the existing run it shows the CI build id

Well, it's not even starting, so I've got nothing on the dashboard :/

Though this one is now failing, but first one passed:
https://cloud.drone.io/nextcloud/viewer/251/2/5
https://dashboard.cypress.io/#/projects/xysa6x/runs/342
ci build id: `drone-241`



> This will print all env variables that start with `DRONE` - there should not be any sensitive information there. But we would like to see these variables from successful run and from a failed run, ok?

Sure, but then If I rebase, it will probably, pass, right?
I can add it for future runs though :)

**Comment by skjnldsv** [comment]
Ah, well, lucky us!
The test print-env pr failed similarely ;)
First run though, so it does not appear in the dashboard

https://cloud.drone.io/nextcloud/viewer/253/2/3
https://github.com/nextcloud/viewer/pull/161
``` sh



+ print-env DRONE
89 | DRONE=true
90 | DRONE_BRANCH=master
91 | DRONE_BUILD_ACTION=sync
92 | DRONE_BUILD_CREATED=1562077415
93 | DRONE_BUILD_EVENT=pull_request
94 | DRONE_BUILD_FINISHED=1562077421
95 | DRONE_BUILD_LINK=https://cloud.drone.io/nextcloud/viewer/253
96 | DRONE_BUILD_NUMBER=253
97 | DRONE_BUILD_STARTED=1562077415
98 | DRONE_BUILD_STATUS=success
99 | DRONE_COMMIT=c24d7dbbac88e637111d19516ac4f0f400386147
100 | DRONE_COMMIT_AFTER=c24d7dbbac88e637111d19516ac4f0f400386147
101 | DRONE_COMMIT_AUTHOR=skjnldsv
102 | DRONE_COMMIT_AUTHOR_AVATAR=https://avatars0.githubusercontent.com/u/14975046?v=4
103 | DRONE_COMMIT_AUTHOR_EMAIL=
104 | DRONE_COMMIT_AUTHOR_NAME=
105 | DRONE_COMMIT_BEFORE=
106 | DRONE_COMMIT_BRANCH=master
107 | DRONE_COMMIT_LINK=https://github.com/nextcloud/viewer/pull/161.diff
108 | DRONE_COMMIT_MESSAGE=Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>
109 | DRONE_COMMIT_REF=refs/pull/161/head
110 | DRONE_COMMIT_SHA=c24d7dbbac88e637111d19516ac4f0f400386147
111 | DRONE_DEPLOY_TO=
112 | DRONE_GIT_HTTP_URL=https://github.com/nextcloud/viewer.git
113 | DRONE_GIT_SSH_URL=git@github.com:nextcloud/viewer.git
114 | DRONE_JOB_FINISHED=1562077421
115 | DRONE_JOB_STARTED=1562077415
116 | DRONE_JOB_STATUS=success
117 | DRONE_MACHINE=8df7bf6c9c01
118 | DRONE_PULL_REQUEST=161
119 | DRONE_REMOTE_URL=https://github.com/nextcloud/viewer.git
120 | DRONE_REPO=nextcloud/viewer
121 | DRONE_REPO_BRANCH=master
122 | DRONE_REPO_LINK=https://github.com/nextcloud/viewer
123 | DRONE_REPO_NAME=viewer
124 | DRONE_REPO_NAMESPACE=nextcloud
125 | DRONE_REPO_OWNER=nextcloud
126 | DRONE_REPO_PRIVATE=false
127 | DRONE_REPO_SCM=
128 | DRONE_REPO_VISIBILITY=public
129 | DRONE_RUNNER_HOST=8df7bf6c9c01
130 | DRONE_RUNNER_HOSTNAME=8df7bf6c9c01
131 | DRONE_RUNNER_PLATFORM=linux/amd64
132 | DRONE_SOURCE_BRANCH=debug/tests/print-env-drone
133 | DRONE_STAGE_ARCH=amd64
134 | DRONE_STAGE_DEPENDS_ON=
135 | DRONE_STAGE_FINISHED=1562077421
136 | DRONE_STAGE_KIND=pipeline
137 | DRONE_STAGE_MACHINE=8df7bf6c9c01
138 | DRONE_STAGE_NAME=cypress-e2e-testing
139 | DRONE_STAGE_NUMBER=2
140 | DRONE_STAGE_OS=linux
141 | DRONE_STAGE_STARTED=1562077415
142 | DRONE_STAGE_STATUS=success
143 | DRONE_STAGE_VARIANT=
144 | DRONE_STEP_NAME=build
145 | DRONE_STEP_NUMBER=3
146 | DRONE_SYSTEM_HOST=cloud.drone.io
147 | DRONE_SYSTEM_HOSTNAME=cloud.drone.io
148 | DRONE_SYSTEM_PROTO=https
149 | DRONE_SYSTEM_VERSION=1.2.0
150 | DRONE_TARGET_BRANCH=master
151 | DRONE_WORKSPACE=/drone/src
152 | DRONE_WORKSPACE_BASE=/drone/src
153 | DRONE_WORKSPACE_PATH=
```

**Comment by bahmutov** [comment]
ok, let's see - first here is a trick - you are installing Cypress using `npm ci` command - you should immediately call `npx cypress verify` after that - otherwise, every build tries to verify it again when you call `cypress run` in each of the 4 containers

Second, there is something funky going on with the build. So the current build is 253 `DRONE_BUILD_NUMBER=253` great. The existing old Dashboard run has url https://dashboard.cypress.io/#/projects/xysa6x/runs/76/specs

When I look at that run it shows

![Screen Shot 2019-07-02 at 11 28 23 AM](https://user-images.githubusercontent.com/2212006/60525542-8aebba80-9cbc-11e9-95e8-2993246061d7.png)

hmm, it thinks that PR 82 https://github.com/nextcloud/viewer/pull/82 has been built using Drone build number 253 (that's why the clashing). I am looking at the PR on GitHub and the only link I see is https://drone.nextcloud.com/nextcloud/viewer/332/2/1

![Screen Shot 2019-07-02 at 11 29 47 AM](https://user-images.githubusercontent.com/2212006/60525625-bec6e000-9cbc-11e9-8bdc-d6babc42d072.png)

This url does not open. Are there 2 drone services?

**Comment by skjnldsv** [comment]
Yes, there is definitely something weird.
It sounds like it's matching an old build by mistake.

We were using our own drone.nextcloud.com service for this repo, but I moved on to drone.io. :)

> otherwise, every build tries to verify it again when you call `cypress run` in each of the 4 containers

I'm not sure I get this right.
you mean this? 
```
[14:22:48] Verifying Cypress can run /root/.cache/Cypress/3.3.1/Cypress [started]
[14:22:50] Verifying Cypress can run /root/.cache/Cypress/3.3.1/Cypress [completed]
```
I have 4 drone workers for the parallelization, where shall I run the `npx cypress verify`? On my [drone build step](https://github.com/nextcloud/viewer/blob/5dfa80383b958cd7bf9cb3a81c85ce4371786ed9/.drone.yml#L41)?

**Comment by skjnldsv** [comment]
> I have 4 drone workers for the parallelization, where shall I run the `npx cypress verify`? On my [drone build step](https://github.com/nextcloud/viewer/blob/5dfa80383b958cd7bf9cb3a81c85ce4371786ed9/.drone.yml#L41)?

I I do that, I get `Your system is missing the dependency: Xvfb`

**Comment by bahmutov** [comment]
So verification step - yes run it on your build box, because you have
1 machine runs "build step": "npm ci", "npx cypress verify"
4 machines run "cypress run". Cypress binary is already verified and the machines go right to specs

But if the build image runs without all OS dependencies, then never mind, I kind of thought all build steps use the same docker image `cypress/...`

<hr>

As far as the run id - seems you were using one Drone service and when you moved, the build numbers started again causing the clashes! Fortunately it is simple to overcome. Instead of relying on the automatic environment variables to pick up `DRONE_BUILD_NUMBER` pass it yourself like this

```
cypress run --record --parallel --ci-build-id my-drone-$DRONE_BUILD_NUMBER
```

This will avoid clashes with previous build numbers because it will use things like "drone-my-drone-253" from now on 

Also, I recommend setting `CYPRESS_RECORD_KEY` environment variable rather than passing it via CLI, I think it is a little bit safer and would avoid accidental printing

**Comment by skjnldsv** [comment]
> I have 4 drone workers for the parallelization, where shall I run the `npx cypress verify`? On my [drone build step](https://github.com/nextcloud/viewer/blob/5dfa80383b958cd7bf9cb3a81c85ce4371786ed9/.drone.yml#L41)?

if I do that, I get `Your system is missing the dependency: Xvfb`
WHich make sense since I'm guessing `cypress/browsers` have it built-in?
Since all my 4 workers starts at the same time automatically, how can I make only one run this?

**Comment by bahmutov** [comment]
don't worry about `cypress verify` in this case, try the `ci-build-id` I suggested

**Comment by skjnldsv** [comment]
Works great! Thanks for the help! :)
