### ISSUE TITLE
parent() can't find element

### ISSUE THREAD

**Issue by Postavshik** [cypress-io/cypress#4658]
### Current behavior:
Trying to find parent DOM element and click it but it doesn't work.
Here is my DOM
![image](https://user-images.githubusercontent.com/21285622/60735599-b61f1580-9f19-11e9-9146-4f02c849aea0.png)

my code:
```js
cy.contains('Place of Exam').parent('mat-card').type('{enter}')
```

also tried
```js
cy.contains('Place of Exam').parent('.question-answer').type('{enter}')
```

![image](https://user-images.githubusercontent.com/21285622/60735857-802e6100-9f1a-11e9-94dd-dc60666dd1bf.png)

If I do hacky like this it works:
```js
cy.contains('Place of Exam').parent().parent().parent().parent().type('{enter}')
```

### Desired behavior:

`parent()` method should find the element in the DOM for the child element

### Versions
Cypress: 3.3.2
MacOS Mojave
Electron 61

**Comment by jennifer-shehane** [comment]
You may want to try passing a second argument to `.contains()` to specify the topmost selector you want it to find as shown here: https://on.cypress.io/contains#Selector

```js
cy.contains('mat-card', 'Place of Exam')

cy.contains('.question-answer', 'Place of Exam')
```

**Comment by Postavshik** [comment]
@jennifer-shehane this is looks like a workaround. The problem here with a parent() method which should find a patent element based on the locator provided

**Comment by jennifer-shehane** [comment]
`.parent()` only travels a single level up the DOM tree, you can use `.parents()` to go traverse up several levels up the DOM tree. https://on.cypress.io/parents

**Comment by Postavshik** [comment]
@jennifer-shehane `.parents()` return a list of elements. I need one, the very first element on the DOM which `parent()` with selector should return. BUT the selector for the `parent()` method does not work. As you see from the error on the screenshot: element never fuond

**Comment by jennifer-shehane** [comment]
`.parents()` returns a list of matching elements, yes, but you can pass a selector to `.parents()` to narrow down the array to one element and then get the first index element of the array. 

`.parent()` will ALWAYS only travel one single level up the DOM tree. It is using the exact implementation as jQuery, so you can read their docs. 

- https://api.jquery.com/parent/
- https://api.jquery.com/parents/

I can see how the docs weren't the best in explaining this, since the accompanying HTML was missing from the test examples, so I updated both the `.parent()` and `.parents()` docs to reflect this here https://github.com/cypress-io/cypress-documentation/pull/1859

**Comment by mrmowji** [comment]
Based on the meaning of **parent**, I think @Postavshik needs something like `ancestor()`, which is not implemented, rather than `parent()`. Try using [`closest()`](https://docs.cypress.io/api/commands/closest.html).
