### ISSUE TITLE
Gmail API request

### ISSUE THREAD

**Issue by shaninadav** [cypress-io/cypress#4660]
Hi,
I tried to login to gmail account, via UI with username and password.
Where can I see example for checking gmail inbox via API call?

Thanks,
Shani

**Comment by gabbersepp** [comment]
Not sure what your problem is. ;-)
Do you want to know how to use the google API? -> https://developers.google.com/gmail/api/

**Comment by jennifer-shehane** [comment]
@shaninadav We have some recipes testing logging in here: https://on.cypress.io/recipes#Logging-In

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our [premium support options](https://www.cypress.io/support/).
