### ISSUE TITLE
How can I use any variable/element of a describe block in different describe block?

### ISSUE THREAD

**Issue by smruti2907** [cypress-io/cypress#4664]
**Details:**

```js
//Enter data and add the customer profiles
   describe('Enter data to New profiles', function() {
	it('Enter cuatomer details and add the customer profile', function() {
//Dynamic Customer profile Name
	const todaysDateTime = Cypress.moment().format('MMMDDYYYYSS')
	const profileName ='ProfileName-' +todaysDateTime
//Entering the profile Name
	cy.get('input[id="fileDataSubform-profile_name"]').type(**profileName**)
	cy.get('textarea[name="fileDataSubform[customer_list]"]').type('Smith002')
??clicking the submit button
	cy.get('button[id="pvwButton1"]').click()
		 })
	  })
```

_**I want to use the above 'profileName' const value in different describe block as below.**_
```js
describe('Customer details page Navigation', function() {
  it('Click on created customer profile name', function() {
	cy.get('html > body > div:nth-of-type(1)').then(($elem) => {
   const x =  $elem.text()
   cy.log(x)
   if (x.includes(**_profileName_**)) {
	 cy.log("found")
	 cy.get($elem).click()
})
})
```

I have used cypress hook method to solve this but is there anyway, I could able to use the 1 dynamic/constant value of a describe block in other describe block apart from cypress hook concept

**Comment by gabbersepp** [comment]
We enhance cypress with an own `describe` and `it`. 
First you will need to register a context object within a `beforeEach` (should be called within the support file):

```js
beforeEach(() => {
    const ctx: Context = {
         tags: {} // this is our way to simulate the tags from our old cucumber/selenium project
    };
    cy.wrap((<any>window)._context || ctx).as("context");
});
```

then you can do following:

```js
export function _describe(name: string, tags: Tag[], fn: (ctx?: Context) => void): void {
    describe(name, () => {
        // merge available context with additional information from tags
        const ctx: Context = mergeTagsIntoContext((<any>window)._context, tags);
        (<any>window)._context = ctx;
        fn(ctx);
    });
}
```

the same is possible for `it`.

Example:

```js
import { _beforeEach, _describe, _it } from "../../support/EnhanceCypress";

_describe("Context set from this describe", [], (ctx: any) => {
    it("set context", () => {
        ctx.someText = "some text";
        assert.isTrue(true);
    });
});

_describe("Context set from other describe", [], (ctx: any) => {
    it("read context", () => {
        assert.equal(ctx.someText, "some text");
    });
});
```

**Comment by jennifer-shehane** [comment]
@smruti2907 Please read through this doc in our documentation: https://on.cypress.io/variables-and-aliases

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email. If you would like something higher touch, we also offer screen sharing and workshops with our [premium support options](https://www.cypress.io/support/).
