### ISSUE TITLE
Issue load fixture

### ISSUE THREAD

**Issue by santiagoholguing** [cypress-io/cypress#4697]
I can't load a fixture from this way:

```js
describe("Knowledge Base Application", () => {
  beforeEach(() => {
    cy.fixture("users/admin").**as("admin");**
  });
  it("Should be able to login: admin", function() {
    cy.visit("/login");
    
    cy
      .get('input[name="email"]')
      .type(this.admin.email)
      .should("have.value", this.admin.email);
});
});
```

before I could load the fixtures with this way, now i get this error:
![image](https://user-images.githubusercontent.com/30031287/61066962-27544200-a3cc-11e9-8f2d-916411e08f1c.png)

**Comment by brayansuarezm** [comment]
I have same issue

**Comment by jennifer-shehane** [comment]
@santiagoholguing When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like the version of Cypress you are using. 

I cannot recreate this error from the information provided on Cypress 3.4.0. 

My test

```js
describe("Knowledge Base Application", () => {
  beforeEach(() => {
    cy.fixture("admin").as("admin");
  });
  it("Should be able to login: admin", function () {
    cy.visit("https://example.cypress.io/commands/actions");

    cy
      .get('input[type="email"]')
      .type(this.admin.email)
      .should("have.value", this.admin.email);
  });
});
```

My fixture:

```json
{
  "email": "foo@email.com"
}
```

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by santiagoholguing** [comment]
I saw that he was using the arrow function, that was the problem ...

As soon as I switched to a normal function, started to work

Thanks <3
