### ISSUE TITLE
Update lodash to > 4.17.12

### ISSUE THREAD

**Issue by Lavioli** [cypress-io/cypress#4730]
running npm audit shows a Prototype Pollution vulnerability, please update the lodash library to  verions highter than 4.17.12

https://www.npmjs.com/advisories/1065

### Current behavior:

![Screen Shot 2019-07-16 at 9 08 44 AM](https://user-images.githubusercontent.com/17465323/61297059-6bb75780-a7a9-11e9-90b5-eff2b0c97ef1.png)

### Versions
cypress 3.4.0

cypress 3.4.0
Mac OSX
Chrome

**Comment by Evanht** [comment]
fix already merged in develop, but not released yet :( https://github.com/cypress-io/cypress/pull/4684

**Comment by flotwig** [comment]
Duplicate of #4699

**Comment by jennifer-shehane** [comment]
The code for this is done in https://github.com/cypress-io/cypress/pull/4709, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

You can run `npm audit fix` to fix the 'vulnerable' dependencies.

But also Cypress is immune to most if not all security vulnerabilities because its locally run software - not a web server hosted in the cloud, so this security issue doesn't even apply and is low priority for us.

**Comment by Lavioli** [comment]
Thanks for the prompt response :)
