### ISSUE TITLE
[Bug] Fails to install on Termux/Android/Busybox

### ISSUE THREAD

**Issue by rayfoss** [cypress-io/cypress#4733]
#3984 # Current behavior: Does not install

![Screenshot_20190716-104910](https://user-images.githubusercontent.com/876076/61309868-b096ba80-a7b8-11e9-97a4-0e25f83521fe.jpg)

### Desired behavior:

Install with reduced functionalty. A full npm install failure  is undesireable, it's not gracefully degrading.

### Steps to reproduce: (app code and test code)

On Termux for Android, no root required:
`pkg install nodejs; npm install cypress`

### Versions
Latest

**Comment by flotwig** [comment]
Since Cypress runs in Electron, and Android can't run Electron, there's no "graceful degradation" possible. Failing the install is the correct behavior - there's nothing else that can be done.

Splitting Electron from Cypress (issue: #3900) would make running Cypress on Android possible, though I'm still not sure what benefit this would bring. Could you share your use case for this?

**Comment by rayfoss** [comment]
My use case is installing a server with media on a high capacity android phone for offline access. I can also see installing it on a  DDWRT router may be useful. I can get around cypress by using --prod with npm.

**Comment by flotwig** [comment]
Well, `package.json` supports mandatory and optional production dependencies - `dependencies` and `optionalDependencies`, respectively. It also supports development dependencies - `devDependencies`. `npm install` installs both by default, `npm install --prod` skips `devDependencies` (and hence, skips Cypress). Sadly, there is no `optionalDevDependencies` ([discussion here](https://github.com/npm/npm/issues/3870)), so there's no easy way to make `cypress` skippable. Normally this is not a problem because typically, end-user products don't ask the user to clone the repo and do `npm install`.

`chokidar` makes use of `optionalDependencies` to make `fsevents` not break the build: https://github.com/paulmillr/chokidar/blob/master/package.json#L23

There is a package called `optional-dev-dependencies` that simulates this behavior for dev dependencies, maybe you can make use of this if doing `npm install` is part of the normal installation for your project: https://github.com/bcoe/optional-dev-dependency

If `cypress` silently failed on unsupported systems, we'd be doing users a disservice by not running and not notifying the user of this, like if it happened in CI somehow. So that's not really an option.

Going to close this since it's working as it should.
