### ISSUE TITLE
How to get values of the browser properties in Cypress?

### ISSUE THREAD

**Issue by Postavshik** [cypress-io/cypress#4740]
### Current behavior:
I need to assert the value of the "value" property in the browser properties. This value is not presented in the DOM. I have Googled everything but can't find how to do that with Cypress

<img width="1441" alt="2019-07-16_1654" src="https://user-images.githubusercontent.com/21285622/61332977-3f242f80-a7eb-11e9-943a-5e4d64a09ac8.png">

Cypress its() method do not work for this scenario.... :(

**Comment by jennifer-shehane** [comment]
https://docs.cypress.io/faq/questions/using-cypress-faq.html#How-do-I-get-an-input%E2%80%99s-value

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

In the future we recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
