### ISSUE TITLE
cy.within does not yield as documented

### ISSUE THREAD

**Issue by chrisbreiding** [cypress-io/cypress#4757]
### Current behavior:

The [`cy.within` doc states that](https://docs.cypress.io/api/commands/within.html#Yields) it "yields the same subject it was given from the previous command". However, it seems to yield the last subject in the `within` function. Only an empty `within` function will yield the subject from the previous command.

### Desired behavior:

Not sure if the documentation or the implementation is wrong. Depending on that, the documentation or the implementation should be fixed.

### Steps to reproduce: (app code and test code)

```html
<article class='post'>
  <h1>My Blog Post</h1>
</article>
```

```javascript
cy
.get('article')
.within(() => {
  cy.get('h1')
})
.should('have.class', 'post')
```

This fails because the `within` yields the `h1` instead of the `article`.

### Versions

Cypress: 3.4.0
OS: MacOS Mojave 10.14.5
Browser: Electron

**Comment by Superkunair** [comment]
**_Pass a function that takes the current yielded subject as its first argument._**
i think this means that it takes in your case the father element `article` as the parameter of your callback, if you want to yield `article` i think it should be redundant because you're getting the father element in a command that search inside of a element
**i think this is what you want to yield**
```javascript
cy.get('article').within(() => {
  cy.get('h1').parent()}).should('have.class', 'post')

**Comment by jennifer-shehane** [comment]
This is not the expected behavior. The documentation is the correct intent.
