### ISSUE TITLE
Assertion failure does not trigger test failure

### ISSUE THREAD

**Issue by skywinston** [cypress-io/cypress#4868]
### Current behavior:

A failed assertion made in my test does not cause the test to fail.
![CleanShot 2019-07-29 at 16 46 14](https://user-images.githubusercontent.com/700803/62087924-b95ba780-b220-11e9-84bd-bcf333b85b95.png)

### Desired behavior:

I would expect that the failure of the assertion would lead to the failure of the entire test.

### Steps to reproduce: (app code and test code)

1. Clone [this repo](https://github.com/skywinston/cypress-assertion-failures)
2. `yarn start`
3. `npx cypress open`
4. Run the `mocking.spec.js` test

### Versions

Cypress Version `3.4.1`
MacOS `10.14.6`
Chrome 75

**Comment by jennifer-shehane** [comment]
Usually this is caused by some async behavior not matching up - where the test will evaluate as complete before the assertion is done evaluating.

So, this is happening because the test is evaluating as complete when it reaches the `.click()`, when in actuality the assertions within your `mockGraphQL` method still haven't run. ehhh, it's a bit tricky, but yeah, you'll want to call the `done()` after everything has run - since you are opting to handle calling when the test ends yourself.
