### ISSUE TITLE
API call is getting blocked and message shown is "net::ERR_BLOCKED_BY_CLIENT"

### ISSUE THREAD

**Issue by rangrasjay** [cypress-io/cypress#4873]
```js
describe('My First Test', function() {
  it('finds the content "type"', function() {
    cy.visit('https://dev01-bmw-pp.urgent.ly')

    cy.get('[ng-model="login.username"]').type('bmwspecialist1@urgent.ly') 
	cy.get('[ng-model="login.password"]').type('demo123')
	cy.get('.btn').click()
  })
})
```

![Screenshot (105)](https://user-images.githubusercontent.com/35130479/62117253-364a5800-b2d9-11e9-81b7-9a6c67d4c9da.png)

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue if no reproducible example is provided. Can anyone provide a way to reproduce this?

**Comment by rangrasjay** [comment]
@jennifer-shehane , Just run the script mentioned above

**Comment by jennifer-shehane** [comment]
Hey @rangrasjay, I'm not experiencing the same issue as you when I run the script above. I also don't know what version of Cypress you are using, could you make sure to update to the latest version and try again.

If the issue is still occurring, please mention any other configuration you have, including PROXYs and run the script on your side  [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and print the logs here.

**My run in Cypress 3.4.1 & Chrome 75 & Electron**

<img width="1562" alt="Screen Shot 2019-07-31 at 10 10 10 AM" src="https://user-images.githubusercontent.com/1271364/62182182-af9a8700-b37b-11e9-8a2f-65a01854ec72.png">

**Comment by rangrasjay** [comment]
[cypress_logs.txt](https://github.com/cypress-io/cypress/files/3450187/cypress_logs.txt)

@jennifer-shehane,

Here I am attaching my log file. cypress.json file is empty. I haven't configured any file manually.

Cypress version: 3.4.1  
Chrome version: 75

**Comment by mcantonbul** [comment]
any solution for this problem? I got same. It is working in electron but not in chrome.

**Comment by rangrasjay** [comment]
@mcantonbul , It is due to firewall. My firewall was blocking this somehow
