### ISSUE TITLE
Tests are not aborted after abort CI/Jenkins job

### ISSUE THREAD

**Issue by Abel0916** [cypress-io/cypress#4911]
### Current behavior:

The tests are not abort in Cypress dashboard after i abort the test build in Jenkins.

### Desired behavior:

I would expect the tests are abort as well if the build is abort from jenkins/CI tool.

### Steps to reproduce: (app code and test code)
1. Config one test job in jenkins
2. Run the test in the job by below command
Cypress run "--record" "--key" "***" "--parallel" "--spec" "cypress/integration/login/*"'
3. Tests are run correctly.
4. Abort the build in jenkins, then check the test in Jenkins
--> Test is still shown running in Cypress dashboard.

### Versions

Mac OS, Browser: Chrome 75, Cypress version - 3.4.0

**Comment by jennifer-shehane** [comment]
When a build is aborted/cancelled from CI, Cypress will no longer receive an exit code. This means that Cypress essentially never hears back from CI. In this situation, we wait 90 minutes for a lack of signal and then kill the run. 

In this situation, we recommend cancelling the run from within the Cypress Dashboard manually following these instructions: https://on.cypress.io/runs#Cancel-run

**Comment by gandadil** [comment]
I have the same problem but I am not using Cypress Dashboard. How can I kill all the processes that the job started on server? After some days I have too many chrome and cypress processes opened because someone abort the jobs. Is there anything I can do on my pipeline script to send a signal to cypress end all process? I running cypress with a npm run command.
