### ISSUE TITLE
--spec requires no spaces between spec files

### ISSUE THREAD

**Issue by jm2242** [cypress-io/cypress#4915]
## Current behavior:
Cypress ignores specs if they are passed in with a space between the comma, and only finds 1 spec:
![image](https://user-images.githubusercontent.com/8572502/62378376-b60f3700-b512-11e9-8739-6980c1ea1037.png)

But finds two specs if I remove the space between the comma and the next spec
![image](https://user-images.githubusercontent.com/8572502/62378450-d8a15000-b512-11e9-9f76-4bfd5577f75d.png)

### Desired behavior:

Spaces should be ignored if listing out specs. Additionally, it would be nice to pass multiple specs via separate `--spec` flags

### Steps to reproduce: (app code and test code)

pass in specs via `--spec` with a space after the comma

### Versions

3.4.1 on Mac

**Comment by flotwig** [comment]
Hey @jm2242, `--spec` does not trim whitespace from filenames, so when you do `--spec "a.js, b.js"`, it's trying to load `a.js` and `<space>b.js`. 

If Cypress stripped spaces from the filenames, Cypress would have to decide whether you intentionally wanted to load `<space>b.js` or if you wanted `b.js` instead. 

Since it can't reasonably do that, stripping spaces from the filename would mean that Cypress wouldn't support any filename that begins with spaces, which sounds like a bug.

I recommend passing `--spec` without spaces between the filenames to fix this issue.

**Comment by jm2242** [comment]
Okay, that makes sense!
