### ISSUE TITLE
CORS issue is happening even after setting chromeWebSecurity to false in cypress.json file.

### ISSUE THREAD

**Issue by bharadwaj-pendyala** [cypress-io/cypress#4943]
### Current behavior:

```
CypressError: Cypress detected a cross origin error happened on page load:

  > Blocked a frame with origin "https://web-client.xyz.com" from accessing a cross-origin frame.

Before the page load, you were bound to the origin policy:
  > https://xyz.com

A cross origin error happens when your application navigates to a new superdomain which does not match the origin policy above.

This typically happens in one of three ways:

1. You clicked an <a> that routed you outside of your application
2. You submitted a form and your server redirected you outside of your application
3. You used a javascript redirect to a page outside of your application

Cypress does not allow you to change superdomains within a single test.

You may need to restructure some of your test code to avoid this problem.

Alternatively you can also disable Chrome Web Security which will turn off this restriction by setting { chromeWebSecurity: false } in your 'cypress.json' file.

https://on.cypress.io/cross-origin-violation

```
### Desired behavior:

User should be able to navigate to google sso without any issues

### Versions

Chrome version being used 76

**Comment by RiZKiT** [comment]
For us it works, so did you tried it with `chrome` and/or `electron`? How does your config look like, any typos?

**Comment by bharadwaj-pendyala** [comment]
@RiZKiT Thank you for commenting over the issue. I am currently using Chrome and issues seems to be happening in both chrome and electron. Sharing configuration snapshots below for reference for chromeWebSecutiry feature.

![image](https://user-images.githubusercontent.com/4959529/64248493-d88bda00-cf2e-11e9-88bf-2c0283eb064d.png)

Cypress.json config is pasted below for reference:

```
{
  "video": false,
  "projectId": "zjfq56",
  "chromeWebSecurity": false,
  "integrationFolder": "Huddl.ai/integration",
  "fixturesFolder": "Huddl.ai/fixtures",
  "pluginsFile": "Huddl.ai/plugins",
  "screenshotsFolder": "Huddl.ai/screenshots",
  "supportFile": "Huddl.ai/support",
  "videosFolder": "Huddl.ai/videos"
}
```

**Comment by bharadwaj-pendyala** [comment]
Please let me know if you need more details if required.

**Comment by amarth1982** [comment]
+1 

I too face a similar issue, I needed to disable it for SSO to do its magic so that my application could be tested.

my **config** looks like 
{
    "integrationFolder": "e2e/tests",
    "fixturesFolder": "e2e/fixtures",
    "chromeWebSecurity": false
}

**Browser info**
{ displayName: 'Chrome',
  family: 'chrome',
  isChosen: true,
  majorVersion: 78,
  name: 'chrome',
  path:
   'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
  version: '78.0.3904.108',
  isHeaded: true,
  isHeadless: false }

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

This may be related to #3994 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
