### ISSUE TITLE
Custom Commands that return void are still chainable.

### ISSUE THREAD

**Issue by AmazingJaze** [cypress-io/cypress#4968]
When I have a custom command defined as:
```js
myCommand = () => { 
  return void;
}
```
And I use it like so:
```js
Cy.myCommand().pause(). 
```

I would expect to hit a run time error since my custom command `myCommand` doesn't return a `Cypress.Chainable<T>`,

But instead the `pause()` command executes after I chain if off of my void method, and I am able to continue chaining even further.

**Comment by AmazingJaze** [comment]
**Update**
I searched the docs to see if this behavior was called out anywhere as by design, but did not find any such examples.

**Comment by Lakitna** [comment]
A command will always return a `Cypress.Chainable<T>`. If I'm not mistaken your example returns `Cypress.Chainable<void>`

**Comment by AmazingJaze** [comment]
Does that mean there is an implicit cy.wrap happening on the return type then?

**Comment by Lakitna** [comment]
Kind of, yes.

A `Cypress.Chainable<T>` will always return a `Cypress.Chainable<T>`, the difference is in what `T` represents. `T` can be extracted using another `Cypress.Chainable`. This pattern is a lot like the one you'll find in promises.

An example:

```javascript
// Create a new `Cypress.Chainable<T>` where T = undefined
// Return `Cypress.Chainable<undefined>`
cy

  // Unpack `Cypress.Chainable<undefined>` and grab the subject of type `undefined`
  // Pick up the value of type `string`. This is the value we'll yield.
  // Return `Cypress.Chainable<string>`
  .wrap('foo')

  // Unpack `Cypress.Chainable<string>` and grab the subject of type `string`
  // Pass the value of type `string` to the callback function and execute the callback
  // Pick up the returned value of the callback function. This is the value we'll yield
  // Return `Cypress.Chainable<number>`
  .then((val) => {
    return 123;
  });
```

Hope this makes it a bit clearer :)

**Comment by erickwilder** [comment]
I respect the design decision but it kinda twists a language construct and makes it even worse for novice developers to fully grasp the concepts behind a `then`able object (like promises).

JavaScript already has many quirks and adding _implicit returns_ to be can have its benefits, but can mislead developers (both novice and experienced) if they don't know the internals of the framework. All in all, my expectations when writing any code is that the _language restrictions and rules_ to be respected, and this is not the case.

**Comment by jennifer-shehane** [comment]
If you want to discuss the Promise decisions made in the API - there's at least some discussion on using `await` or making thenables more apparent here: https://github.com/cypress-io/cypress/issues/1417

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
