### ISSUE TITLE
Sporadic disconnection between test runner and Cypress UI

### ISSUE THREAD

**Issue by karevn** [cypress-io/cypress#4970]
### Current behavior:
After working with an UI test runner for some time, the test list gets empty sporadically, and you can see the next in the UI:
![image](https://user-images.githubusercontent.com/7992040/62849460-224f1f00-bcf9-11e9-962b-31bca09ef487.png)

### Desired behavior:

Just having the Cypress UI in a working condition.

### Steps to reproduce: (app code and test code)

No special steps to reproduce - I see it sporadically, sometimes rarely, sometimes in 2 minutes after launching Cypress.

### Versions

Cypress 3.4.1, macOS Mojave 10.14.6, Electron browser 61

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.
