### ISSUE TITLE
Replace `cypress open`, `cypress run` references with appropriate command

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#5019]
### Current behavior:

Cypress recommends users to run `cypress open` or `cypress run` in different ways. For example:

https://github.com/cypress-io/cypress/blob/ad70513912340248a7b6ec22e526d2a994eee62f/packages/desktop-gui/src/update/update-banner.jsx#L82-L95

https://github.com/cypress-io/cypress/blob/ad70513912340248a7b6ec22e526d2a994eee62f/packages/server/lib/errors.coffee#L127-L132

https://github.com/cypress-io/cypress/blob/ad70513912340248a7b6ec22e526d2a994eee62f/packages/desktop-gui/src/runs/runs-list.jsx#L353-L355

https://github.com/cypress-io/cypress/blob/ad70513912340248a7b6ec22e526d2a994eee62f/packages/desktop-gui/src/settings/record-key.jsx#L126-L131

https://github.com/cypress-io/cypress/blob/ad70513912340248a7b6ec22e526d2a994eee62f/packages/server/lib/errors.coffee#L336-L347

https://github.com/cypress-io/cypress/blob/ad70513912340248a7b6ec22e526d2a994eee62f/packages/server/lib/errors.coffee#L362-L381

https://github.com/cypress-io/cypress/blob/ad70513912340248a7b6ec22e526d2a994eee62f/packages/server/lib/errors.coffee#L382-L401

### Desired behavior:

* If the user has `node_modules/.bin` in their `$PATH`, recommend `cypress [command]`
* If the user is using `yarn`, recommend `yarn cypress [command]` (this works?)
* If the user has `npx`, recommend `npx cypress [command]`
* Else, recommend `./node_modules/.bin/cypress [command]`

**Comment by sarthakkundra** [comment]
Hi. I would like to work on this issue. Can you please confirm if the commands mentioned in the desired behavior are correct? This will be my first open source contribution so I'd appreciate it if you can tell me if I'm doing anything wrong. Thanks.

**Comment by sainthkh** [comment]
`yarn cypress` doesn't work when `package.json` doesn't have the "script" whose name is `"cypress"`. 

In yarn 2, there is a [`yarn dlx` command](https://yarnpkg.com/cli/dlx). You can use it for this purpose. And the issue was debated over 2 years at [here](https://github.com/yarnpkg/yarn/issues/3937). And [it is not backported](https://github.com/yarnpkg/yarn/issues/3937#issuecomment-499155481) and it seems that it will be.

**Comment by merceyz** [comment]
> yarn cypress doesn't work when package.json doesn't have the "script" whose name is "cypress".

That's not true, it will execute the package with that binary name in the project

**Comment by Celinarabe** [comment]
Is this issue still open? If yes, I can work on it! :)

**Comment by sainthkh** [comment]
@Celinarabe PRs are always welcome!

**Comment by devtayls** [comment]
## Update: 

- Some of the files listed in the original issue have been replaced or are no longer extant
- The commands listed in the source have been changed since the issue was posted

 ### File Changes:

> cypress/packages/desktop-gui/src/update/update-banner.jsx  is now ../update/update-instructions.

https://github.com/cypress-io/cypress/blob/04e854eaa652a4c654b12e3d27b07b9905f7618f/packages/desktop-gui/src/update/update-instructions.jsx#L89-L90

The command is now passed to the `<UpgradeCommand command={} />`  prop.  
For npm: `npm install --save-dev cypress@`
For yarn: `yarn upgrade cypress@`

>  cypress/packages/server/lib/errors.coffee is now ../lib/errors.js
>  The command text remains the same here as in the OP issue.

https://github.com/cypress-io/cypress/blob/04e854eaa652a4c654b12e3d27b07b9905f7618f/packages/server/lib/errors.js#L371-L381
