### ISSUE TITLE
Failed in after each hook that I don't have

### ISSUE THREAD

**Issue by myuzhang** [cypress-io/cypress#5026]
### Current behavior:
Found if cypress command failed, some failures sometimes fail in `afterEach` or `beforeEach`, and I don't have these `afterEach` in code though, wondering why this happens.

I have three cases:

1. when a new test start, seems cypress is still waiting for an api which belongs to previous test, and if the api failed, it shows in `beforeEach` of the new test (sorry forgot to take the screenshot)
2. when `cy.readFile()` failed (sorry forgot to take the screenshot)
3. when `cy.visit()` failed as picture below:

![image](https://user-images.githubusercontent.com/6210892/63562458-096c2680-c5a1-11e9-8d93-457cf675a73d.png)

### Desired behavior:

Don't fail in either `afterEach` or `beforeEach`, which skips the remaining tests.

Also wondering how https://github.com/cypress-io/cypress/issues/2744 goes, I think it is also good to continue with testing even if they fail in before or after each

### Versions

Cypress: 3.2.0
Chrome: 59
Windows: 10

**Comment by mpahuja** [comment]
The main reason why tests are skipped when an afterEach or beforeEach call fails is because we want the tests to be deterministic, predictable and reliable. So if an afterEach blocks failed once it might leave the account, test, browser or something else in an unexpected state. To avoid subsequent failures its better to fail after a failure is encountered in any of those hooks. Hope it makes sense

**Comment by jennifer-shehane** [comment]
In the situation you pasted the photo of - we do not arbitrarily add `afterEach` to your tests.

Your project likely has an `afterEach` somewhere running in Cypress - check all files in the `cypress/support` folder and the `cypress/plugins` folder because anything included in those files will run on each test run.
