### ISSUE TITLE
Cypress test runner crashes when detecting a test modified in Visual Studio Professional - Windows OS

### ISSUE THREAD

**Issue by luis-m-gonzalez** [cypress-io/cypress#5039]
### Current behavior:

- Open Test Runner
- Test runner Launches
- Double Click test File
- Chrome window launches
- Test runs successfully
- Open test file on Visual Studio Professional
- Add empty space
- Save file

Expected: The tests run again automatically

Actual: About half of the time, I get the expected result. The other Half Test Runner and Chrome window crash with this message:

```
{ Error: EPERM: operation not permitted, stat 'XXX\cypress\integration\CypressCucumberPrototype.cyfeature~RFfcae6e9.TMP'


  errno: -4048,
  code: 'EPERM',
  syscall: 'stat',
  path: 'C:\\XXX\\cypress\\integration\\CypressCucumberPrototype.cyfeature~RFfcae6e9.TMP' }
Error: EPERM: operation not permitted, stat 'C:\XXX\cypress\integration\CypressCucumberPrototype.cyfeature~RFfcae6e9.TMP'
```

### Desired behavior:

Expected: The tests run again automatically

### Versions

Cypress 3.4.1, Windows 10, Chrome 75

**Comment by bahmutov** [comment]
Nice! We still should not crash the test runner though

**Comment by luis-m-gonzalez** [comment]
@jennifer-shehane do you need anything else from me to remove the needs information tag? 

I understand that this issue may be a low priority for your team, however it would be great to have it fixed at some point.

Thanks!

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by SohumB** [comment]
I can't speak to Visual Studio, but I believe I can trigger the same bug while using Emacs to edit cypress test suites while the runner is running. "We stopped running your tests because a plugin crashed.", with no plugins installed.

![image](https://user-images.githubusercontent.com/66472/151904149-d5f8c2b0-3b0d-41e1-966c-a0509c82f310.png)

Emacs creates and deletes short-lived `.#FILENAME` symlinks (that don't point anywhere valid) as [lock files](https://www.gnu.org/software/emacs/manual/html_node/emacs/Interlocking.html#Interlocking); it appears to be intended to signal on multi-user systems that this file is being edited. Turning off `create-lockfiles` no longer triggers the cypress crash. 

I can replicate this crash on Cypress 9.4.1.
