### ISSUE TITLE
reuse login.spec doesn't work

### ISSUE THREAD

**Issue by thian4** [cypress-io/cypress#5041]
I want to reuse my login.spec.js which is a UI login, then I have another spec I did this

```js
context('Waiting', () => {
  beforeEach(() => {
    require('./login.spec.js')
  })
  it('get a list of rate limits', async () => {
    cy.visit('somewhere')
    
  })
})
```

I got forever loading and I have no problem running login.spec.js alone. Here's the login.spec.js file
```js
context('Login', () => {
  const loginCredential = {
    user: 'someone@gmail.com',
    password: 'xxx'
  }
  beforeEach(() => {
    cy.visit('signin')
  })
  it('has a form with ', () => {
    cy.get('#username').should('have.length', 1)
    cy.get('#password').should('have.length', 1)
    cy.get('#organization').type(loginCredential.org)
    cy.get('#username').type(loginCredential.user)
    cy.get('#password').type(loginCredential.password)
    cy.get('[type=submit]').click()
    cy.wait(500)
    cy.location('href').should('match', /home$/)
  })
})
```

**Comment by mpahuja** [comment]
what you are trying to do is a good use case for using and creating a custom command for the login function and then use it in both the test cases. Please read about custom commands here: 
https://docs.cypress.io/api/cypress-api/custom-commands.html#Syntax

I would also suggest to look into ways of not needing to log in through the UI in multiple tests. You can also look into using one of the methods described at the link below:
https://docs.cypress.io/examples/examples/recipes.html#Logging-In

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
