### ISSUE TITLE
File export, or access to confirm window

### ISSUE THREAD

**Issue by Ahmad-Alahrashi** [cypress-io/cypress#5057]
Hello
How can I file exporting?
for example, when clicked button, there confirm window to save the file...
How can access for this confirm window, then click on save button?

thnx

**Comment by mpahuja** [comment]
@Ahmad-Alahrashi please read FAQ available on this topic here: https://docs.cypress.io/faq/questions/using-cypress-faq.html#Is-there-a-way-to-test-that-a-file-got-downloaded-I-want-to-test-that-a-button-click-triggers-a-download

**Comment by Ahmad-Alahrashi** [comment]
not yet :(

**Comment by jennifer-shehane** [comment]
@Ahmad-Alahrashi There are some examples here https://github.com/cypress-io/cypress-example-recipes/issues/339

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
