### ISSUE TITLE
Possible to ignore entire folders with ignoreTestFiles?

### ISSUE THREAD

**Issue by awitherow** [cypress-io/cypress#5064]
I like the idea of keeping the `integrations/examples` in my project so I can have a little doc reference.

I tried in `plugins/index.js` to ignore 

```javascript
module.exports = (on, config) => {
  config.ignoreTestFiles = "examples/*.spec.js";
  return config;
};
```

doesn't seem to work though :) any ideas or do I have to do it manually for or loop over contents of a folder using `fs`?

**Comment by mpahuja** [comment]
try this ```module.exports = (on, config) => {
  config.ignoreTestFiles = "**/examples/*.spec.js";
  return config;
};```

**Comment by jennifer-shehane** [comment]
Yes. `ignoreTestFiles` accepts a glob as explained here: https://on.cypress.io/configuration#Global

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).

**Comment by awitherow** [comment]
Thank you @mpahuja!
