### ISSUE TITLE
Cannot connect to API server

### ISSUE THREAD

**Issue by tarponjargon** [cypress-io/cypress#5071]
### Current behavior:

When opening the "Runs" tab of the test runner this message appears:

```
Cannot connect to API server
Viewing runs requires connecting to an external API server.
We tried but failed to connect to the API server at http://localhost:1234/
 Try again
The following error was encountered:
connect EHOSTUNREACH fe80::1:1234 - Local (:::59225)
Learn more
```

I am not using a corporate proxy, just trying to connect from my mac at home.  Not sure where the 'localhost:1234' is coming from - I think it's supposed to connect to api.cypress.io?

<img width="816" alt="Screen Shot 2019-09-01 at 10 22 25 PM" src="https://user-images.githubusercontent.com/12751386/64092039-e6abe180-cd07-11e9-98a2-70f93376a71e.png">

<img width="802" alt="Screen Shot 2019-09-01 at 10 22 43 PM" src="https://user-images.githubusercontent.com/12751386/64092052-f3c8d080-cd07-11e9-957a-89163087b76b.png">

### Desired behavior:

Connect to api.cypress.io so I can use the dashboard.

Mac OSX 10.14.6

**Comment by jennifer-shehane** [comment]
@tarponjargon Can I verify that you are running Cypress after downloading it via npm? You are not forking the Cypress repo and running it in develop in order to contribute to the code?

This is definitely a bug if installed Cypress via npm and are seeing this message. It should attempt to connect to the `api.cypress.io`.

Can I have you try one more thing? Can you run this command below in your terminal and verify that you do not have an env var on your machine called `CYPRESS_ENV`?

```
env | grep -E "(CYPRESS_ENV|CYPRESS_KONFIG_ENV)"
```

**Comment by tarponjargon** [comment]
Ah - that was in fact the problem.  I was using CYPRESS_ENV in my .bash_profile.  I changed it to something else and everything works now.  Thanks!
