### ISSUE TITLE
When I run the tests together ("Run all specs"), it crashes. But when I run each one individually, they all work. any solution?

### ISSUE THREAD

**Issue by Rohit1990Sharma** [cypress-io/cypress#5075]

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
