### ISSUE TITLE
Whoops there is no test to run.

### ISSUE THREAD

**Issue by uc-any** [cypress-io/cypress#5088]
I find this issue when I am running my test code.
It comes when my site redirects me from https://www.ucertify.com to https://www.ucertify.com/[xyz].
Please solve it or provide some ideas.

**Comment by jennifer-shehane** [comment]
The code below runs fine in Cypress version 3.4.1

```js
it('visits', () => {
  cy.visit('https://www.ucertify.com/')
})
```

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
