### ISSUE TITLE
cy.visit() page with baseUrl and two dots doesn't work

### ISSUE THREAD

**Issue by amrtn** [cypress-io/cypress#5090]
### Current behavior:
`cy.visit('?q=..')` will not honor the `baseUrl` defined in `cypress.json` and will load `http:///?q=..` instead.

### Desired behavior:

Given `cypress.json` as

```json
{
  "baseUrl": "https://google.com"
}
```
`cy.visit('?q=..')` should load `https://google.com?q=..`

### Steps to reproduce: (app code and test code)

See <https://github.com/amrtn/cypress-test-tiny/tree/double-dot-visit>

### Workaround

`cy.visit('/?q=..')` will get translated to `http://www.google.com/?q=..` 

This behavior can be acceptable in some cases.

### Versions

Tested on cypress@3.4.1 in windows 10

**Comment by jennifer-shehane** [comment]
Yeah, this is weird and also not fixed in our upcoming pre-release. There is one issue that is being highlighted here which is that it is visiting `http:///` with an extra `/` which is described here: https://github.com/cypress-io/cypress/issues/2101 

It's weird that the dots seem to specifically make things worse.

**Comment by mratoms** [comment]
We appear to be encountering this as well, in our case with query parameters which _contain_ two dots
