### ISSUE TITLE
Can't to stop loop

### ISSUE THREAD

**Issue by narinepoghosyan** [cypress-io/cypress#5093]
Hello. I can't to stop my loop in my code. 
I have a loop checking 40 items. I want to stop my loop, when I am finding the first element, which > 0 

I am trying like this 

```js
var genArr = Array.from({ length: 40 }, (v, k) => k + 1);
  cy.wrap(genArr).each((index) => {
    cy.get('.list-item').eq(index - 1).find('.number')
        .invoke('text')
        .then(text => {
            const pendingCount = text;
            cy.get('.list-item').eq(index - 1).click();
            cy.get('.list-table').find('.list-table-list-item')
                .should('have.length', pendingCount);
            if (text > 0) return false
         });
    });
});
```

But have a selected error. 

![Screenshot from 2019-09-05 21-18-01](https://user-images.githubusercontent.com/40800905/64363878-b4112a00-d022-11e9-8e38-bea4176e90f3.png)

Pls help me!

**Comment by jennifer-shehane** [comment]
Please read this section of our docs: https://on.cypress.io/introduction-to-cypress#Commands-Are-Asynchronous

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).
