### ISSUE TITLE
error in cypress

### ISSUE THREAD

**Issue by ARPITA1409** [cypress-io/cypress#5100]
```
CypressError: Timed out retrying: expected '<div.sub-categories-list>' to be 'visible'

This element '<div.sub-categories-list>' is not visible because it has CSS property: 'position: fixed' and its being covered by another element:

undefined
```

```js
 it("Category1", function() {
    cy.get(".col-md-3.d-none.d-sm-block")
      .get(".subscribe-details")
      .should("be.visible")
      .eq(1)
      .should("be.visible")
      .get(".categories-header")
      .should("be.visible")
      .get(".categories-list.OpenSansBold")
      .should("be.visible")
      .get("div.sub-categories-list")
      .eq(0)
      .should("be.visible")
      .contains("Alternative medicine")
      .click();
})
```

**Comment by jennifer-shehane** [comment]
See this existing issues: https://github.com/cypress-io/cypress/issues/1379 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by swathisham** [comment]
i still see this issue

**Comment by jennifer-shehane** [comment]
@swathisham If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
