### ISSUE TITLE
cy.wait() with @alias.all @alias.last @alias.n

### ISSUE THREAD

**Issue by aesfer** [cypress-io/cypress#5112]
### Current behavior:

When multiple requests happen with the same alias, there is not a convenient way (at least that I know of) to use `cy.wait()`.

### Desired behavior:

Given a request alias `@alias`, it would be nice if we could:
1. `cy.wait('@alias.all')` to wait for all the requests that have been requested up to this point with this alias.
2. `cy.wait('@alias.last')` to wait for the last request sent up to this point with this alias.
3. `cy.wait('@alias.n')` to wait for the nth request sent up to this point with this alias.

**Comment by ryan-snyder** [comment]
May I ask why you don't just have different alias and wait on the ones you want with
```js
cy.wait(['@alias1', '@alias2'])
```

Besides that there's https://docs.cypress.io/api/commands/wait.html#Wait-automatically-increments-responses

**Comment by jennifer-shehane** [comment]
There's an undocumented feature that does this: https://github.com/cypress-io/cypress-documentation/issues/1573

But, as with anything undocumented, this API is subject to change.

**Comment by mfrieling** [comment]
Even if this issue is closed a while now, I would like to point you to a use case @ryan-snyder.

My Angular app needs to load a couple of configuration files from its server during app initialization and before the first UI can be shown to the user. These are `/assets/config.json` with API server base url, API token and similar settings and multiple JSON files which control parts of the UI (which must be customizable per production installation).

As those files must be intercepted to provide different fixtures per test case/suite, I wrote a custom command `cy.setupApplication` which I call in `beforeEach` of all tests with different arguments. To keep my test code clean I have multiple setup commands, one is needed for all tests and others only for specific parts of the applications (I don't need to configure things like payment UI & handling for searching products for example):

```
beforeEach(() => {
  cy.setupApplication(/* parameters */)
  cy.setupPayments(/* parameters */)

  cy.visit('/')

  // And here I have to wait for all interceptors defined by `setup*()` commands.
})
```

Either I know all aliases to wait for (by returning them from the commands, but didn't manage to do that) or I just wait for them via `cy.wait('@alias.all')`. The point is that the HTTP requests are triggered by the `cy.visit('/')` and as I have multiple setup commands I can't put the visit into any of them.
