### ISSUE TITLE
Can you see Cypress Github App status checks for tests in dependency repos?

### ISSUE THREAD

**Issue by westhomas** [cypress-io/cypress#5157]
Is it possible to connect the Cypress Github App to a repo without cypress tests and see Github Status Checks for commits outside of where the E2E tests are located?

Example:

1) We have a frontend app in its own repo.
2) We have multiple micro-services which together with the front end make up our "app"; each micro-service has its own repo.
3) We have all our E2E tests in another repo.

When a commit happens to (1) or (2), we want to launch the E2E tests in (3) with CI and get reporting on that commit/PR just like if we had committed it to (3).

I've been able to get (3) working and see it report in github status checks, etc. It's awesome. I'm just trying to figure out if (1) or (2) are supported currently and how to go about doing it.

**Comment by jennifer-shehane** [comment]
Hey @westhomas, this is not something that is built into the current GitHub integration. There's no way for Cypress to detect commits made to a separate repo to then trigger a build or the status checks on a separate repo. 

Cypress will only watch and detect commits made in a PR on a single connected repo - in order to trigger status checks or PR comments.

This definitely *seems* possible to do using some outside service though. Maybe using a utility to listen to commits from one repo to trigger a PR in the separate repo with Cypress tests - Cypress is looking for a commit SHA to trigger it, so this process would have to involve making a commit to trigger the build. Maybe GitHub actions can somehow help with this? I don't have an example of a full solution.

Issues in this GitHub repo are reserved for potential bugs or feature requests, so this issue will be closed since it appears to be neither a bug nor a feature request.
