### ISSUE TITLE
cypress running forever for getting an alias from XHR body

### ISSUE THREAD

**Issue by pranav700** [cypress-io/cypress#5162]
### Current behavior:
Whenever you alias a XHR response body and then try to access it later as shown in example, the 'cy.get' command runs forever.
![cypress_waiting](https://user-images.githubusercontent.com/38900373/65134661-8ea9f600-d9fc-11e9-9185-69e69dd09a6b.jpg)

### Desired behavior:
It should get the value from Alias.

### Steps to reproduce: (app code and test code)
```js
cy.wait('@save').then((xhr) => {
  cy.get(xhr.responseBody).as('audienceid')
})
 cy.log(cy.get('@audienceid')) // The 'get' here is running forever. I should be getting the value back 
```

### Versions

3.4.1

**Comment by jennifer-shehane** [comment]
Hey @pranav700, there are a few things I notice from the provided example that aren't quite the intended use of the Cypress API. I would suggest reviewing our docs, especially:

- the arguments accepted into [cy.get()](https://on.cypress.io/get) - this accepts a css style selector or an alias, not an object like `xhr.responseBody` 
- our Introduction to Cypress guide particularly the sections on [how Cypress is async and commands run serially](https://on.cypress.io/introduction-to-cypress#Commands-Are-Asynchronous), you cannot execute a cypress command within a cypress command like you are trying to do `cy.log(cy.get())` will not work. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

Also check out our [community chat](https://gitter.im/cypress-io/cypress) for questions about how to use Cypress. 

I'll be closing this since this does not appear to be a bug with the intended use of Cypress at the time. Comment if you have any updates on identifying this as a bug.
