### ISSUE TITLE
Application not loading through cypress

### ISSUE THREAD

**Issue by sensuraj92** [cypress-io/cypress#5171]
Our application is build on iFrames, application is not at all loading through cypress
when i check with development team, they gave below explanation

-Through normal browser in console,
when we type `this.id` it is giving some id like `ext-gen1` , when we type `this.parent.id` it is giving same id in our application

Through cypress browser in console
when we type `this.id` it is giving some id like `ext-gen1` , when we type `this.parent.id` it gives `undefined`

Is there any way to automate our application through cypress ?
can we do some configuration to correct this ?

attached screenshots for reference
![cypress_browser](https://user-images.githubusercontent.com/41458305/65306039-209f3380-dba2-11e9-958e-a8d07a6904fe.PNG)

![normal_browser](https://user-images.githubusercontent.com/41458305/65306051-272dab00-dba2-11e9-9cc5-79feb9990c99.PNG)

**Comment by ryan-snyder** [comment]
See https://github.com/cypress-io/cypress/issues/136 on how to access iframes. If you have any other questions, you can ask over on gitter or add on to this ticket

**Comment by jennifer-shehane** [comment]
@sensuraj92 Cypress runs all applciations under test in an iframe, so testing iframes in your application isn't fully supported without some workarounds as ryan mentioned above from https://github.com/cypress-io/cypress/issues/136

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.
