### ISSUE TITLE
How to test application running in Docker?

### ISSUE THREAD

**Issue by nitingupta220** [cypress-io/cypress#5172]
I have a React application running in Docker container. I want to test that app with Cypress.
Can you please help me in letting me know the steps to run the tests in docker written in Cypress?

@brian-mann @jennifer-shehane

**Comment by ryan-snyder** [comment]
Are you trying to run tests on a CI? Or just test it locally? I'm assuming whatever port the application is running on isn't exposed outside the docker container? Or is it?

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email.
