### ISSUE TITLE
Tests won't run within CI pipeline

### ISSUE THREAD

**Issue by Jakegillingham5** [cypress-io/cypress#5182]
Hey, really stuck trying to get my test suites running on our GitLab CI pipeline although they run locally with no issues. 

I'm using the start-server-and-test package to serve my laravel application but Cypress is exiting prior to running any tests which results in a Gitlab Job succeeded. I've attached an image of the GitLab output and my configuration file for the E2E test job.

I'm using Cypress v3.4.1

<img width="1081" alt="gitlab-console" src="https://user-images.githubusercontent.com/11712293/65407446-b399d100-de21-11e9-88db-895f82486177.png">

<img width="1081" alt="ci-config" src="https://user-images.githubusercontent.com/11712293/65407976-46873b00-de23-11e9-80bd-01b29f4637d6.png">

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email.

**Comment by robsontenorio** [comment]
@Jakegillingham5 

For now, this is my current approach. If there is another option, please, let me know.

https://github.com/robsontenorio/laravel-docker-cypress
