### ISSUE TITLE
Xvfb default cursor position interacts with AUT

### ISSUE THREAD

**Issue by kuceb** [cypress-io/cypress#5186]
By default Xvfb seems to place a cursor at `{x: 640, y: 512}`, which can interact with the AUT by triggering `mouseover` events, and even activating css :hover styles.

This isn't a huge issue but it can cause small inconsistencies

issues caused by this:
- random mouseover trigger #4936

**Comment by flotwig** [comment]
So this is kinda weird, @Bkucera and I spent some time looking into this today...

* There does not appear to be a way to start Xvfb without a pointer device.
	* `-nocursor` is a supported argument, but in actuality, it only removes the icon of the cursor, not the actual pointer device.
* We can check if a pointer device exists by doing either:
	* `xinput`, which comes with X, lists all input devices
	* `xdotool getmouselocation` (3rd party tool) will show the cursor's current location
* Chrome will sometimes fire a `mouseover` event if a page is rendered/scrolled underneath the cursor
	* Sometimes it does, sometimes it doesn't; could be related to Chrome's security efforts
	* This probably causes all kinds of strange flake

Potential solutions:

* Use `xdotool` to move the mouse to 0x0 at the start of the test (hacky, requires dependencies)
* Create two displays at Xvfb startup and abandon one to hold the cursor (hacky)
* Create native dependency that uses `XTEST` to move mouse to 0x0 (hacky, hard to maintain)

Probably the best solution is @Bkucera's idea to just check if `xdotool` is available, and if so, use it to move the mouse to 0x0. Then we could start adding xdotool to our Docker images to fix this.

This could also be implemented easily as a Cypress plugin that does one of the above.

Since only one person is reporting an issue, and the path forward is not clear, going to wait for more feedback here before proceeding.

**Comment by brian-mann** [comment]
Maybe `robotjs`

**Comment by flotwig** [comment]
Yeah, that could work. We'd still have to compile the native deps for Electron ourselves: https://robotjs.io/docs/electron
