### ISSUE TITLE
I can't get my fixture response when click event trigger a request

### ISSUE THREAD

**Issue by lucascravero** [cypress-io/cypress#5195]
Hi! I newer in Cypress. I'm trying to use fixtures to "mock" my own API responses.
This is my test code:

![image](https://user-images.githubusercontent.com/30657141/65543773-41d88a80-dee8-11e9-9083-616de333fb3b.png)

When I click onto confirm button from a modal, this event fires the request. I don't wanna hit my backend, I wanna "mock" this response using fixtures, but I can't. The request is executed hit to my database, creating new records.
When I use cy.wait(), I've this error into the Cypress Log:

![image](https://user-images.githubusercontent.com/30657141/65544374-7862d500-dee9-11e9-92e9-b4dc7f8dc607.png)

### Desired behavior:
I desire understand if is possible get the fixture content as my own API response when the request is executed.

![image](https://user-images.githubusercontent.com/30657141/65544061-dba03780-dee8-11e9-8df4-d4e88def9ebf.png)

this fragment of code is from my frontend code. Ajax success segment trigger the method that have another Ajax request. I wanna "mock" his response.

![image](https://user-images.githubusercontent.com/30657141/65544175-16a26b00-dee9-11e9-8ce2-1ea511578abc.png)

Cypress version: 3.4.1
Chrome version: 77

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
