### ISSUE TITLE
Mouse hover does not work with tippy.js

### ISSUE THREAD

**Issue by prashantabellad** [cypress-io/cypress#5227]
### Current behavior:
We are using tippy.js for tool tips in our application. This is very important functionality for our application as we perform few actions through actionable buttons on the tool tips.
Cypress does not recognize these tool tips
### Desired behavior:
Cypress to come up with a solution

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by theNomik** [comment]
For anyone with same problem, check
https://stackoverflow.com/a/65888012/14655526 

From answer (for me 'mouseenter' worked):
> cy.get('#gh-Alerts-i').trigger('onmouseover')
> cy.get('#gh-Alerts-i').trigger('mouseenter')
> cy.get('#gh-Alerts-i').invoke('trigger', 'contextmenu')
> cy.get('#gh-Alerts-i').rightclick();
