### ISSUE TITLE
wait after upload is done (fixture)

### ISSUE THREAD

**Issue by thian4** [cypress-io/cypress#5259]
How to wait when a image upload is finished? below is my code, the uploading is working, but I can't  do ```cy.wait('@lastCoverPhotoUpload')```.

I'm using this plugin
https://www.npmjs.com/package/cypress-file-upload

```js
cy.fixture('cat4.jpg').as('lastCoverPhotoUpload').then(fileContent => {
      cy.get('[data-cy="cover_photo"]')
        .eq(3)
        .upload({
          fileContent,
          fileName: 'cat4.jpg',
          mimeType: 'image/jpg'
        })
    })

    cy.wait('@lastCoverPhotoUpload').then(() => { //stuck here
      cy.get('.ant-btn').click()
      cy.wait(1000)
      cy.reload()
    })
```

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

In this case you may want to ask in the https://www.npmjs.com/package/cypress-file-upload repo or comment in our general file upload issue https://github.com/cypress-io/cypress/issues/170 (which is not fully supported).

You can also ask questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
