### ISSUE TITLE
Replace x.top, x.parent accessors with correct reference (at runtime)

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#5271]
PR: #5273

### Current behavior:

window.top and window.parent references are naively corrected like so:

https://github.com/cypress-io/cypress/blob/4ec77e3d589983b19d448d9c8cc2aed9d9068d05/packages/server/lib/util/security.js#L7-L38

### Desired behavior:

* Replace `/(.*)\.(top|parent)/` with `(window.top.Cypress.resolveWindowReference($1, "$2"))` using AST parser or regexes
* `window.top.Cypress.resolveWindowReference(maybeWindow, prop)` is a function that checks if `maybeWindow` is a `Window` and, if so, corrects the property access to be 1 level deeper than it would've been (to skip `window.top`). 
* If `maybeWindow` is not a `Window`, and if `maybeWindow[prop]` is a `Function`, it will bind `maybeWindow[prop]` to `maybeWindow` and return it. 
* Else, it will return `maybeWindow[prop]`.

**Comment by flotwig** [comment]
This fix is available starting in [`4.6.0`](https://docs-staging.cypress.io/guides/references/changelog.html#4-6-0) as an [experiment](https://on.cypress.io/experiments) which you can access by setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

Please use a new issue if you are still running into issues that are not solved by this change.

**Comment by fderraz** [comment]
Hello,

My Cypress test fails because the home page is not loaded:
**(uncaught exception)TypeError: top.getTabFrom is not a function 
(uncaught exception)TypeError: top.getParamWindow is not a function**

 The following error originated from your application code, not from Cypress. > top.getTabFrom is not a function

 I addedto the cypress.json file, the following params: “**experimentalSourceRewriting**”: true 
Except that it doesn't fix my problem

**Version Cypress: "13.15.0"**

Any suggestions you may have to solve this problem, will be appreciated :)

<img width="859" alt="Error" src="https://github.com/user-attachments/assets/7d0639d7-8d6a-4c0f-b865-b9ac0be66c84">



Please find enclosed my code: Test.cy.js
The following code snippet corrects the loading problem, except that it's not a relevant solution because the win.top is used everywhere in the application under Test ==> it's not possible to include it after each click.

 
  **cy.window().then((win) => {
        win.top.getTabFrom = win.top[0].getTabFrom; 
        win.top.getParamWindow = win.top[0].getParamWindow; 
    });**

<img width="409" alt="Test" src="https://github.com/user-attachments/assets/04c09993-3a60-411e-b55a-9e41711f2fd0">

**Comment by jennifer-shehane** [comment]
@fderraz Please open a new issue filling out the issue template if you have a new bug, this older bug was already addressed.
