### ISSUE TITLE
integrate with passport.js

### ISSUE THREAD

**Issue by TomYang1993** [cypress-io/cypress#5276]
### Current behavior:

testing a ui button, which after `click()`, it should fire a post action(basically a form submit), post action returns 403 forbidden, it is intended by my apis, because it's checking if `req.user` exists. I am using **passport** **OAuth**, it will save user session or info on `req.user`. It seems because cypress is natively reacting, it fires the post request **without** req.user.

### Desired behavior:

any workaround? or is this a new feature? or just misunderstandings(I am new to cypress)

### Versions

mac os
chrome
all is stable version up to date 10/02/2019

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example (test code that can run against an application exhibiting the failure) and we will reopen the issue.
