### ISSUE TITLE
run cypress in staging frontend

### ISSUE THREAD

**Issue by thian4** [cypress-io/cypress#5278]
How difficult is it to allow cypress to be trigger in a webapp? 

We have this development flow: 
1. developer write and run cypress for e2e, deploy feature to staging
2. tester and manager test manually in staging
3. release feature to production

Is it possible to let tester and manager to run cypress in staging?

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
