### ISSUE TITLE
Using subfolder __tests__

### ISSUE THREAD

**Issue by xereda** [cypress-io/cypress#5284]
Can I leave the test files inside the implementation folders, as we already do with unit tests, using __tests__ subfolder?

I believe the flow of TDD can be further optimized by getting testing close to implementation. I understand that we would have to differentiate the unit test files from the e2e tests. We would solve with two files patterns: `*.unit.js` and `*.e2e.js`.

Would it be possible?

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email.
