### ISSUE TITLE
Find a way to run test jobs on forked pull requests

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#5312]
We have switched to using CircleCI contexts to inject environment variable per job. This is good, since it only exposes specific environment variables to the jobs that truly need them. Unfortunately, we have 3 jobs in our pipeline that inject Cypress record key to record integration tests to the dashboard.

For example https://github.com/cypress-io/cypress/pull/5254

The original forked pull request from an outside user did NOT run 3 jobs in the workflow

![Screen Shot 2019-10-08 at 5 44 20 PM](https://user-images.githubusercontent.com/2212006/66435765-99e8b400-e9f3-11e9-9bc9-ae6967297bf3.png)

since I am a member of Cypress GitHub organization I could simply execute "Rerun from failed" and those jobs now execute

![Screen Shot 2019-10-08 at 5 45 01 PM](https://user-images.githubusercontent.com/2212006/66435858-c6043500-e9f3-11e9-9794-9a34dd9df7a7.png)

The sensitive variables WERE NOT injected (since this is outside pull request), which is the same behavior as before (when we used plain environment variables across all jobs of the project). Our `cypress run --record` handles missing `CYPRESS_RECORD_KEY` in forked pull requests, so it is fine.

## Dilemma

This is only for `CYPRESS_RECORD_KEY` env variable used to record our internal test runs to the dashboards in a few test jobs. Should we:

- switch back to injecting this variable across ALL our test jobs?!
- add manual trigger job between test jobs that do not need security context. Once the workflow is passing these jobs, then someone from the team can trigger manual job, which will trigger these recording jobs (which still won't record)

I don't see any other way - either we share record key across of our jobs (forked pull requests don't get it in any job), or require manual trigger to run the jobs for external pull requests

**Comment by NicholasBoll** [comment]
I won't pretend to understand CircleCI and security contexts because I lack experience with them, but it seems like an Approval could be used to trust a context. This requires a manual step from a trusted pool of people: https://circleci.com/docs/2.0/contexts/#approving-jobs-that-use-restricted-contexts

Trust and security are tricky. We're using Github Actions, but I've been finding a lot of information on how CircleCI does things. They seem to be the most innovative and security conscious and Github Actions documentation even uses them as examples.

More info from the CircleCI blog: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/

We may experiment with the concept of promoting a PR from a forked repo to a trusted branch by running a process to copy the forked branch to the main repository. Since Github Status/Checks are based on commit hashes, the CI would run against the local branch's head commit which is the same as the forked PRs head commit.

It is possible for us to create automation that checks files changed to determine auto-promotion of a PR to a local branch if PR doesn't change any files that the CI system runs.

**Comment by bahmutov** [comment]
`reporter-integration-tests`, `desktop-gui-integration-tests-2x` and `driver-integration-tests-chrome` require `PACKAGES_RECORD_KEY`

**Comment by jennifer-shehane** [comment]
Released in [3.5.0](https://on.cypress.io/changelog#3-5-0)
