### ISSUE TITLE
Zero tests passing (and no failing) should have an error exit code

### ISSUE THREAD

**Issue by zakhenry** [cypress-io/cypress#5314]
### Current behavior:

If something goes wrong in picking up tests, the reporter exits with a successful result, despite no tests having actually been run.

### Desired behavior:

When there are no failures AND no passes, exit with non-zero code

### Steps to reproduce: (app code and test code)

Run cypress against js file that contains no tests

### Versions

`cypress@3.4.1`

**Comment by jennifer-shehane** [comment]
Cypress issues a 0 exit code when a file contains no tests because we consider this a non-failure event. This would be a breaking changes that we don't intend to change. 

There are several ways that you could access the data to determine there were no tests run yourself. I'm not exactly sure of your use case but you could use our [Module API](https://docs.cypress.io/guides/guides/module-api.html#cypress-run) to detect that there were zero tests in a single spec file and issue your own different non-zero exit code. 

We also detect when a specfile had 0 tests and display this as a different status in our Dashboard when reviewing recorded results.

**Comment by theKashey** [comment]
Cypress can think that you have "zero tests" if there is a compilation problem. For example using `dynamic import` with `webpack preprocessor` might lead to webpack bundle actually not executed (due to multiple chunks produced), timing out as "no tests found".

It would be pretty nice to have an option to consider such situation as failure.

**Comment by bahmutov** [comment]
I agree that this could be a source of false confidence in the tests - the CI build is green, but no tests are running. We have written a tool that is a wrapper around Cypress just to prevent this scenario, see https://github.com/bahmutov/cypress-expect. You can add it to your CI and set the exact or minimum number of passing tests

```
npx cypress-expect run --min-passing 5 ... rest of Cypress run arguments
```

Read [Wrap Cypress Using NPM Module API](https://glebbahmutov.com/blog/wrap-cypress-using-npm/) and [Cypress Metaprogramming](https://glebbahmutov.com/blog/cy-metaprogramming/)
