### ISSUE TITLE
Cypress 3.4.1 + Chrome 77 -> adds __/ to baseUrl 

### ISSUE THREAD

**Issue by erikferencz** [cypress-io/cypress#5315]
### Current behavior:
In our test under Chrome browser, in case our APP calls relative Path url, base url is changed to `baseUrl/__/`

Example : http://127.0.0.1/__/Training/Courses/5/Quizzes/5/Results/24
But should be : http://127.0.0.1/Training/Courses/5/Quizzes/5/Results/24

This is happening only in test run under Chrome.

Thast run under Electron are not affected

### Desired behavior:

No change in baseUrl in any case.

### Steps to reproduce: (app code and test code)

Call any relative path from your App

### Versions
Cypres 3.4.1
Chrome 77
Win 10

**Comment by jennifer-shehane** [comment]
Unfortunately we will have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please include the tests that we can run to reproduce this issue - we don't know if you are calling cy.visit, cy.request, or doing nothing for example to recreate this.
