### ISSUE TITLE
How to input text into textfield in chrome alert?

### ISSUE THREAD

**Issue by sangmai350** [cypress-io/cypress#5316]
In my test, it require to input to chrome popup text field. You can see the popup in screenshot http://prntscr.com/pgvazb.
How to input text into the textfield in chrome alert and click Ok?
Very thankful if anyone could help

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email.

**Comment by jennifer-shehane** [comment]
Hey @sangmai350, I found a solution for writing in a prompt that I wanted to share on the issue. 

`index.html` of my test application, but essentially when a button is clicked, a window prompt appears.

```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Stubbing Window Prompt</title>
</head>
<body>
    <ul>
        <li>
            <h1>My Application</h1>
            <button id="prompt">Prompt</button>
        </li>
    </ul>

    <script>
        var btn = document.getElementById('prompt')
        btn.addEventListener('click', function (event) {
            let sign = prompt("What's your sign?");

            if (sign === "scorpio") {
                alert("Wow! I'm a Scorpio too!");
            }
        })
    </script>
</body>
</html>
```

My Cypress test file. 

1. We are stubbing the text that is entered into the prompt, this will be 'faking' as if a real user typed this. 
2. We are spying on the 'alert' - which is the 'success' message that displays after the text is entered. Then we are asserting that the correct message is displayed - which would test whether they wrote 'scorpio' in my case.

```js
it('window prompt test', function () {
  cy.visit('/index.html', {
    onBeforeLoad(win) {
      cy.stub(win, 'prompt').returns('scorpio')
      cy.stub(win, 'alert').as('windowAlert')
    }
  })
  
  cy.get('#prompt').click().then(function () {
    expect(this.windowAlert).to.be.calledWith('Wow! I\'m a Scorpio too!')
  })
})
```

This is the result in the Cypress Test Runner after, notice that you can click within the Command Log to see more details about Spies/Stubs.

<img width="1072" alt="Screen Shot 2019-10-11 at 2 24 45 PM" src="https://user-images.githubusercontent.com/1271364/66675231-e837c600-ec32-11e9-9eae-41d7c8105789.png">

You will no longer see the 'prompt' window pop up and stop execution of the tests since we're handling the type and confirm in Cypress tests.
