### ISSUE TITLE
Test passes in headed browser but fails headlessly

### ISSUE THREAD

**Issue by hsaab** [cypress-io/cypress#5328]
### Current behavior:

Here is the test in question:

<img width="760" alt="test" src="https://user-images.githubusercontent.com/30737735/66528505-f8c23200-eab4-11e9-857c-2aff9148caaf.png">

For added context, this is what `initBag()` does

<img width="762" alt="initBag" src="https://user-images.githubusercontent.com/30737735/66528511-fbbd2280-eab4-11e9-9a26-447de0007e91.png">

Here is the result in the headed browser with the `cypress open` command: 

<img width="1434" alt="browser passed" src="https://user-images.githubusercontent.com/30737735/66528562-2effb180-eab5-11e9-9c70-66d7115569d5.png">

Here is the result headlessly using `cypress run` command: 

<img width="1176" alt="terminal failed" src="https://user-images.githubusercontent.com/30737735/66526794-ae3db700-eaae-11e9-923e-de1dba86f9c2.png">

### Desired behavior:

- I was reading a lot of the documentation on chaining command and assertion together for retry-ability, which is the format I tried to follow in the test
-  I understand that there is a 4 second timeout when assertions are run headlessly, but am confused as to why in the headed browser the test passes within milliseconds then headlessly it times out (although rarely will pass)
- Desired behavior is for the test to pass in the headed browser and headlessly without any flakiness

### Steps to reproduce: (app code and test code)

- Attached code snippets above
- Curious if the way I am structuring the tests is prone to flakiness headlessly and why

### Versions

- Cypress 3.4.1
- macOS Mojave 10.14.5
- Chrome

**Comment by HareemManzoor** [comment]
@hsaab Can you please share the commands that you are using for executing your tests in headless mode? Thanks :)

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

I would suggest updating to our latest version of Cypress - as many variables between headless and headed have disappeared with our updates of Electron. 

Also try running headlessly with `--browser chrome` to match running tests headed in Chrome.

Please comment in this issue with a fully reproducible example (test code and application code we can run) and we will reopen the issue.
