### ISSUE TITLE
modifyObstructiveCode incorrectly matches the word 'stop'

### ISSUE THREAD

**Issue by mikey0000** [cypress-io/cypress#5330]
### Current behavior:

During test run, code fails with sself not defined.

### Desired behavior:

functionality of code should not be replaced
isChildTrainPlatform = stop => stop.route_type === STOP_TYPE.TRAINSTOP && stop.location_type === 0;
should not turn into 
isChildTrainPlatform = stop => stop.route_type === STOP_TYPE.TRAINSTOP && sself.location_type === 0;

### Steps to reproduce: (app code and test code)
code specifically with this line

return stop.route_type===__WEBPACK_IMPORTED_MODULE_10__types_stop_types__["a" /* default */].TRAINSTOP&&stop.location_type===0;

### Versions

Cypress 3.4.1, Chrome 77

**Comment by Bkucera** [comment]
paging @flotwig, he's working with our app isolation logic

**Comment by flotwig** [comment]
Your code is getting mangled by these regexes in the proxy which blindly replacing `top` with `self`:

https://github.com/cypress-io/cypress/blob/5654680fcdcd7181223b75849ae3e059e3d6da96/packages/server/lib/util/security.js#L7-L10

I am working on a PR that parses and rewrites the Javascript instead of using regexes, which I'll make sure fixes this problem: #5273

**Comment by mikey0000** [comment]
Yeah, I managed to work that out, awesome! Look forward to the fix!

**Comment by brian-mann** [comment]
`s` + `top` === `stop` ;-P

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
