### ISSUE TITLE
data-cy should be unique or not ?

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#5333]
Data-cy should unique or not in cypress. If data-cy is not unique, can i select two items simultaneous and can i the first item with first() command or not ?

last question, which one is the best suit ?

thanks for helping.

**Comment by HareemManzoor** [comment]
Please share the purpose of using both commands as your question is not clear. However, if you want to access the first DOM element on the entire page then **.first(options)** a good option.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
