### ISSUE TITLE
App inside an iframe redirect to login page who needs a certificate failed

### ISSUE THREAD

**Issue by delphineli** [cypress-io/cypress#5349]
### Current behavior:

So my application is inject in one site by iframe. To login (SSO), page will redirect a login page who need a certificate. Then I got 
`xxxx.xxx.com refused to connect.` showing on the page.
I checked in security: 

My certificate becomes issued by Issued by: CypressProxyCA and is not trusted.
So i can't access to login page.

### Desired behavior:

I can accept the certificate in test. Or no proxy on certificate.

### Steps to reproduce: (app code and test code)
```js
    cy.visit(Cypress.env('EXPERIENCE_URL'));
 
    cy.wait(Cypress.env('TEST_WAIT_FOR_REDIRECT_MILLIS') || 5000);
    cy.url()
      .then((url) => {
        cy.get('.login-sign-in-button').click();  // this should redirect to login page but chrome error page instead
      })
```

### Versions

newest version cypress (3.3.1) / OS / Chrome

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example that we can run and we will reopen the issue.
