### ISSUE TITLE
Vsts builds are failing due to a memory leak error. 

### ISSUE THREAD

**Issue by Swati-activeops** [cypress-io/cypress#5364]
I have been running these builds regularly but recently they have started failing.

"(node:3837) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exitEarlyWithErr listeners added. Use emitter.setMaxListeners() to increase limit"

We’re just using standard out of the box agents.
![image](https://user-images.githubusercontent.com/50127497/66737008-6a6cf800-ee88-11e9-853f-91510251e49b.png)

Could you please help?

**Comment by blumk** [comment]
@Swati-activeops can you provide a repository containing the tests that cause the memory leak error to occur?
How many tests are you running? What's the total duration of the test run?
I'm using Azure DevOps as well and I've not experienced this issue before.

**Comment by jennifer-shehane** [comment]
This warning message is not related to the cancellation of CI. See this issue for that warning: https://github.com/cypress-io/cypress/issues/1305

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
