### ISSUE TITLE
Cypress Eror handling

### ISSUE THREAD

**Issue by jrtest400** [cypress-io/cypress#5371]
Hi

I'm testing a lot of things but some of them are not too important(like caption text fail)I want to add optional parameter (if its wrong thats okay continue testing) I used to work with Katalon Studio, it has Change failure options(stop,fail,continue) Can I make it with Cypress for my test cases

**Comment by jennifer-shehane** [comment]
See this doc: https://on.cypress.io/catalog-of-events#Catching-Test-Failures

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email.
