### ISSUE TITLE
¿ How to keep without reload the page when the url change on a single page application ? 

### ISSUE THREAD

**Issue by jdramirezr** [cypress-io/cypress#5389]
¿ How to keep without reload the page when the url change on a single page application ? 

### Current behavior:
when Cypress finishes writing in the form and clicks on "continue", it loads the page and continuous  in the second form, but when loads the page, the data of the previous form is missing

![image](https://user-images.githubusercontent.com/45051181/67040147-79ea7c00-f0e8-11e9-84e4-05de0c868eb2.png)

### Desired behavior:
I hope that the page don't need to reload to keep the data

### Versions
cypress 3.4.1

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email.
