### ISSUE TITLE
Can i spy fetch request

### ISSUE THREAD

**Issue by tarikcarli** [cypress-io/cypress#5390]
I read the issue #95 but i couldn't find what i was looking for. I have fetch api request and i want to control the request header and request body. Are there any example for that and is this possible with cypress ?

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email.
