### ISSUE TITLE
Add option to avoid automatic parsing of JSON files in cy.fixture() and cy.readFile()

### ISSUE THREAD

**Issue by checketts** [cypress-io/cypress#5395]
### Current behavior:

Fixtures with comments  throw an error as not being 'valid json'
![image](https://user-images.githubusercontent.com/416063/67033071-210fe900-f0d2-11e9-8d44-ddc92a51349b.png)

### Desired behavior:

Please allow json5 (json with comments) for fixtures. Some fixtures are huge and having comments to point out the critical part would be helpful

### Steps to reproduce: (app code and test code)

https://github.com/checketts/cypress-test-tiny.git see https://github.com/checketts/cypress-test-tiny/blob/master/cypress/fixtures/example.json

### Versions

Mac OSX using Cypress 3.4.1

**Comment by jennifer-shehane** [comment]
Hey @checketts, we do not propose supporting JSON5, as this is not valid JSON and do not intend to support every form of reading in files - and think this is a concern of the user. 

ALTHOUGH, there is no way to get around our current JSON validation to read this file. So we do think there should be a way to get around the validation. 

### Proposal

We propose passing an option to the `cy.fixture()` (or at the least the `cy.readFile()` to enable reading of invalid JSON files. 

The  simplest name I can think of for the option is `parse` with it's default being `true` and you could pass in `false`. Someone else may have a better suggestion though.

### Code

The code for `cy.fixture()` starts here, attempting to lint and parse any files with a `.json` extension. This is the point where you would say `if (options.parse === false)` then skip any of the specific calls to `parseJson`, `parseJs`, `parseCoffee`, or `parseHtml`.

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/fixture.coffee#L106

Here is the code for `cy.readFile()` that does the same thing and should be given the same options - `parse: false` to skip the parsing of files with `.json` extensions.

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/files.coffee#L8

### Workaround

You could rename your file that is passed to `cy.readFile()` or `cy.fixture()` so that it does not have a `.json` extension (adding a `.txt` extension) and it will read in the file just fine in our current version of Cypress.

**Comment by checketts** [comment]
Thanks for the excellent write up and included work around! I've incorporated them and they work (almost) perfectly! See https://github.com/checketts/cypress-test-tiny/commit/0229f7543c66b84e013b04efd5a5d7e1ddec3ef6#diff-d344d2966988ae770a3305445156ac3e

By changing my file to `.json5` my IDE (WebStorm) still parses it as JSON and allows comments, so I don't lose that functionality and Cypress serves up the files without any error.

However, it appears that my frontend code (Angular) can't parse it, because, as you noted it isn't valid JSON. So I would need to create a command that uses `cy.readFile` and strip out comments before passing them on. (It also broke Cypress' ability to assert `have.property` on the response.

So my final work around is to use a JS object directly: https://github.com/checketts/cypress-test-tiny/commit/e2da55e79437d4a7abf7fc1b2c7716c131cfda71

Thanks for this great framework!

**Comment by fr0** [comment]
Duplicate of https://github.com/cypress-io/cypress/issues/3138 which was closed but never implemented.

**Comment by jennifer-shehane** [comment]
Yah, this isn't exactly a duplicate of https://github.com/cypress-io/cypress/issues/3138 because the parsing of the JSON actually causes errors / could change the original data that can't be reread in with the `JSON.stringify()` workaround.

**Comment by jprealini** [comment]
Comment requested by @jennifer-shehane (comming from closed #8110) ... 

I use the mentioned fixture to mock an api call, and populate a grid. One of the columns is a transaction amount, which is expected to have two decimal places. In this case, cy.fixture removes any trailing zeros, so 170.40 reaches the grid as a 170.4, or 170.00 is shown as 170 (the frontend doesn't do any formatting, just dumps to the grid whatever comes from the db through the api request). 

I managed to solve this by removing the .json extension from my fixture files... only problem is that in VS Code you lose the json formatting and color scheme which is visually helpful sometimes... 
So, I think your proposal is just what I was thinking about (passing an option to tell it to parse or not)

BTW... I came to know Cypress last December, and I became the biggest fan.... It's the most amazing tool I know for test automation... Keep up the great work!!!

**Comment by dinhvinhloc** [comment]
Hi @jennifer-shehane Can you please advice a bit more detail how to make cy.request() to NOT parse the response automatically? Please note that this is the direct response which I can't work-around by changing the file extension to a non-JSON file.
Appreciate much for your response on my issue https://github.com/cypress-io/cypress/issues/8154

**Comment by Brestachan** [comment]
Is there any update regarding this issue?

**Comment by cjcrandall** [comment]
Can you do _something_ about this rogue bot? Bugs don't fix themselves, and features don't add themselves.

**Comment by mike-plummer** [comment]
@cjcrandall Unfortunately, we're a small team and if an issue lies dormant for almost three years we have to assume it's either not affecting our users anymore or isn't a priority since it hasn't received an OSS contribution to resolve it.

This particular issue has since been fixed elsewhere - you can pass a `null` encoding argument to [`cy.fixture`](https://docs.cypress.io/api/commands/fixture#Arguments) and [`cy.readFile`](https://docs.cypress.io/api/commands/readfile#Arguments) which causes Cypress to load the file in as a [Buffer](https://docs.cypress.io/api/utilities/buffer) instance, bypassing the default parsing. The user can then parse/process it however they like.

```js
// In this example there is a fixture `json-5.json` that contains JSON5 content

it('fails to load JSON5 without `encoding` param', () => {
  cy.fixture('json-5')
})

it('successfully loads JSON5 with `encoding` of `null`', () => {
  cy.fixture('json-5', null).then((result) => {
    cy.log(result.toString()) // Convert buffer to string, do whatever you want with it
  })
})
```
