### ISSUE TITLE
Soft assert or failure handling

### ISSUE THREAD

**Issue by nishant-sngl** [cypress-io/cypress#5400]
### Current behavior:
Scenario: To crawl through the whole website and check if all the pages are working fine. In case one page is out-of-order, then it should not stop the execution right-away on one failed assertion. We need to continue the execution even if any assertion fails. All assertions should fail at the end.

### Desired behavior:
Requirement is to keep a track of the failures, and continue the tests till end. At the end the test should give the summary of failures.

### Steps to reproduce: (app code and test code)

This can be done via any kind of soft-assert, where the failed assertions will be handled and throws error at the end of the test case.

This can also be done via try-cath. we can apply some login inside catch and then report it at the end of the test.

For every failure of cy.get().should() , the test fails. If we put the test steps in try-catch, still it fails the test.

Right now i am not able to get any of the above two functionality support in cypress.
Please help me, if any of these functionalities are currently supported in Cypress

### Versions

working on cypress 3.3 & macOS

**Comment by jennifer-shehane** [comment]
This should be possible by hooking into the `fail` event in Cypress - doing whatever logic you want there and then not `throwing` in order to continue to the next test. This would require you to split up your assertions into separate tests. 

We do not intend to change the behavior of a `.should()` to pass if it fails, as this is an extremely unusual test case. 

We intend to add more events to listen into as Cypress runs, so you can write whatever logic you want after hooking into those.

**Comment by Elzebub** [comment]
Jennifer could you post an example of how to do this without swallowing legitimate errors? Won't this approach mark my test as passing when it actually failed?

I have a github action that runs all of my suites against Chrome & should then run them all in Electron. If one test fails in Chrome then the Electron tests do not run at all. This was not the case with 6.8.0 but is now the case with 9.2.0
