### ISSUE TITLE
Provide documentation for setting up VSCode for contribution

### ISSUE THREAD

**Issue by gabbersepp** [cypress-io/cypress#5405]
I tried to understand the code in the driver and server package in order to fix this issue correctly: https://github.com/cypress-io/cypress/issues/5367

So I started by searching for the definition of cy.visit to understand what's going on there. After finding navigation.coffee, I wanted to navigate through the code. Unfortunatelly there is no "jump to symbol" support for those files in VSCode.

It would be nice, if one can provide a documentation that shows how to setup VSCode or that suggests an alternative IDE (but as there is a .vscode folder in the root folder, I think it is recommended to use VSCode :-) ).

**Comment by gabbersepp** [comment]
btw not sure if this is possible in coffeescript^^

**Comment by jennifer-shehane** [comment]
VSCode does not support 'Go to Symbol' for CoffeeScript: https://github.com/Microsoft/vscode/issues/12378#issuecomment-340183383 Supposedly that extension will give you that feature. 

I consider this personal to contributor and IDE however, since it's an extension, so I wouldn't consider this necessary for our contributing documentation. 

We're working to convert our coffee docs to js also https://github.com/cypress-io/cypress/issues/2690
