### ISSUE TITLE
Add organization name to invitation e-mail

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#542]
> < username > has requested to become a member of your Cypress.io organization.

I have multiple organisations. Please put the organization name in the e-mail template so I can see which organization the user want access to.

**Comment by jennifer-shehane** [comment]
@trydionel Can you open an issue for this on our Services board - or make sure there is an existing issue for this?

**Comment by trydionel** [comment]
Done! Thanks for the heads up.

**Comment by jennifer-shehane** [comment]
The best place to express interest and see progress for Dashboard features is on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard and we want to make sure any feedback gets seen and addressed by the right team. 

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thanks!
