### ISSUE TITLE
How to stub a getter props？

### ISSUE THREAD

**Issue by lihroff** [cypress-io/cypress#5420]
Current API shows:
```js
cy.stub()
cy.stub(object, method)
cy.stub(object, method, replacerFn)
```
### Current behavior:
Suppose I want to go to Stub a getter like the below:
```js
it('stub getter?', () => {
    let count = 0;

    const obj = {
      get count() {
        return ++count;
      }
    };

    cy.stub(obj, 'count', () => {
      // always assign to 10
      count = 10;
      return count;
    });
    
    expect(obj.count).eq(10);
  });
``` 
>  It assert failed: expected 1 to equal 10

### Desired behavior:
 expected 10 to equal 10

### Versions
- cypress: 3.4.1

### Question
I don't know the implementation behind stub, whether it can be done?

**Comment by bahmutov** [comment]
@lihroff take a look at https://github.com/cypress-io/cypress-fiddle/pull/26

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email.
