### ISSUE TITLE
insensitive assertion using should and contain?

### ISSUE THREAD

**Issue by thian4** [cypress-io/cypress#5462]
I tried this
```
cy.get('@textInput')
      .invoke('val')
      .should('contain', `/${searchTerm}/i`)
```
but it doesn't work. I know .contain support regex but how about using ```should``` and ```contain``` with invoke like above case?

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email.
