### ISSUE TITLE
Length property along find method is not working for me 

### ISSUE THREAD

**Issue by vinod236** [cypress-io/cypress#5463]
Requirement : to find the length of table rows 
Problem statement : When we dont have rows inside the `tbody` , we get error for "Find" statement where we use length property
Code : 

```js
cy.get('tbody').then(el =>{
   let tempvar = 0
   if(!el.find('tr').length){
   tempvar = el.find('tr').length;
   }
   cy.log(tempvar);
});
```

Here in UI, we can clearly see that Table will be existed with empty rows. Please help me to understand why its not giving Zero as its length, why its throwing find element error

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
