### ISSUE TITLE
Hook alike a "final" statement

### ISSUE THREAD

**Issue by MacGyver27** [cypress-io/cypress#5468]
I wanted to confirm if there is a way to implement something like "final" block in exceptions..

Problem is that I have couple tests, some are just pure rest calls to prepare the environment and while testing I multiple times hit X button on giu or kill it (forgot sth etc..) and this way my DB is getting populated with data which I need to clear manually...

Solution would be something like a final hook which would be executed asynchronously before test is killed - so I would pass all ids of elements for deletion..

Test block is running -> Tester kills it -> cypress execute final hook (async) -> cypress will kill the test
 That hook would also execute once all tests are finished..

Thanks, Michal

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Alternatively, signing up for any of our [paid plans](https://www.cypress.io/pricing/) gives you access to our team for support via email.

**Comment by MacGyver27** [comment]
What is it other than feature request then?..

**Comment by jennifer-shehane** [comment]
>I wanted to confirm if there is a way to implement something like "final" block in exceptions..

This is phrased as a question not a feature request. 

When opening an issue, please fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) provided - it requires necessary information we need to help you, like desired behavior, which would be necessary for a feature request.
