### ISSUE TITLE
Upgrade banner covers up project setup button

### ISSUE THREAD

**Issue by IanVS** [cypress-io/cypress#5483]
### Current behavior:

In the default size that the test runner window opens in, this is what I see:

![image](https://user-images.githubusercontent.com/4616705/67628432-89ca3480-f83b-11e9-9a47-9b6a31cf84e2.png)

### Desired behavior:

I should be able to see the button to set up a new project, without resizing the window.

![image](https://user-images.githubusercontent.com/4616705/67628457-12e16b80-f83c-11e9-8368-adf419a31def.png)

I think the banner should sit under the button, either by giving the page a bit more room under the button, or by moving the banner outside of the scroll container, allowing the user to scroll all the way down.

### Steps to reproduce: (app code and test code)

Install a non-current version of the test runner, go to the runs tab, see that you can't find a button to click.

### Versions

3.4.1, currently.

**Comment by jennifer-shehane** [comment]
This issue is not present in 3.5.0. The default size (which is 800 x 550) does not cover it and you can scroll to see the button - see the scrollbar. 

<img width="802" alt="Screen Shot 2019-10-28 at 12 20 51 PM" src="https://user-images.githubusercontent.com/1271364/67696548-78894100-f97d-11e9-9528-2bcfc4fc34cd.png">
