### ISSUE TITLE
Can't break each loop early by returning false

### ISSUE THREAD

**Issue by dugajean** [cypress-io/cypress#5485]
### Current behavior:

When running an `.each` loop and attempting to break the loop by doing `return false;`, Cypress doesn't stop the loop, but instead explodes with:

> CypressError: cy.then() failed because you are mixing up async and sync code.
> 
> In your callback function you invoked 1 or more cy commands but then returned a synchronous value.
> 
> Cypress commands are asynchronous and it doesn't make sense to queue cy commands and yet return a synchronous value.
> 
> You likely forgot to properly chain the cy commands using another cy.then().
> 
> The value you synchronously returned was: 'false'

![image](https://user-images.githubusercontent.com/2448254/67636235-e88cbe00-f8ce-11e9-9ce2-4f60ddbc4fcc.png)

### Desired behavior:

Cypress should break the loop when returning `false` from an `.each` loop.

### Steps to reproduce: (app code and test code)

1. Do a `get` + `find`, then loop through each of them with `.each`
2. `return false` at some arbitrary location, preferably inside an `if` statement to properly copy my situation
3. Get the error above

### Versions

- Cypress: 3.5.0
- Node: 12.13.0
- Chrome

**Comment by jennifer-shehane** [comment]
`.each()` does exit when passed `false` as documented. The below example exits the each loop on the 1 index.

```js
  it('.each() - iterate over an array of elements', () => {
    cy.visit('https://example.cypress.io/commands/connectors')
    cy.get('.connectors-each-ul>li')
      .each(($el, index, $list) => {
        console.log(index)
        if (index === 1) {
          return false
        }
      })
  })
```

The error you are receiving is because you are mixing async and sync code, as explained in the error message with the `cy.wait()` inside of an if statement. We discourage conditional testing in this way due to the way which you can read more about here. https://on.cypress.io/conditional-testing

**Comment by chkashif167** [comment]
cy.get('div.author-name')
    .each(($el, index, $list) => {
      var $name = $el.text();
      // cy.log($name);
       if ($name !== ' KashifN4') {
        cy.get($el).closest('partie-feed-item').find('button.btn.btn-menu > img').click() 
        return false;
      }

it shows this error
CypressError: cy.then() failed because you are mixing up async and sync code.

In your callback function you invoked 1 or more cy commands but then returned a synchronous value.

Cypress commands are asynchronous and it doesn't make sense to queue cy commands and yet return a synchronous value.

You likely forgot to properly chain the cy commands using another cy.then().

The value you synchronously returned was: 'false'

**Comment by jennifer-shehane** [comment]
@chkashif167 The issue with your code is mixing the below 2 lines of code together. The `return false` (syncronous) will run before the cypress lines (asynchronous) run, since Cypress is async. The warning is correct in that the code you wrote will not run as expected. 

```
cy.get($el).closest('partie-feed-item').find('button.btn.btn-menu > img').click() 
return false;
```

Please read the full introduction guide: https://on.cypress.io/introduction-to-cypress#Commands-Are-Asynchronous

**Comment by chkashif167** [comment]
@jennifer-shehane you mean i dont need to user each and only below code will fulfill my requirements?
`cy.get($el).closest('partie-feed-item').find('button.btn.btn-menu > img').click() 
return false;`

**Comment by anthonychernenko** [comment]
@jennifer-shehane what should we do if need to run some async code inside .each and immediately break (like here https://github.com/cypress-io/cypress/issues/5485#issuecomment-562545976)?

**Comment by jennifer-shehane** [comment]
@chkashif167 @anthonychernenko Issues in our GitHub repo are reserved for potential bugs or feature requests.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by begli80** [comment]
@jennifer-shehane What is the point of this : 
it('.each() - iterate over an array of elements', () => {
    cy.visit('https://example.cypress.io/commands/connectors')
    cy.get('.connectors-each-ul>li')
      .each(($el, index, $list) => {
        console.log(index)
        if (index === 1) {
          return false
        }
      })
  })

if I am not able to perform any operations in my if block and only then break out loop of based on the condition.

I have got the similar situation like chkashif167 below , where Im trying to break out of the each loop only after some operation based on the condition.But getting message :'cy.then() failed because you are mixing up async and sync code.

cy.get('.checkbox').each(($el, index, $list)=>{
        let checkBox=$el.prop('checked')
        if(checkBox&&index===0)
        {
            email.getPharmacyHealthOptionsPhone().eq(index).uncheck()
            email.getPharmacyHealthOptionsPhone().eq(1).check()  
            return false  
        }
})

So what is the workaround ?

**Comment by Frauxt** [comment]
For some reason, returning false like this doesn't work. It executes the command and it doesn't throw an error. But unfortunately the loop does not break

     var category = 'abc'
     cy.get('a[class="category-list"]')
        .each(($el) => {
            cy.get($el).invoke('text')
                .then((text)=>{
                    if(text === category){
                        cy.wrap($el).click()
                        return false
                    }
                })
        })

**Comment by bahmutov** [comment]
@begli80 the `cy.each` requires a "normal" synchronous function to work. Just like you cannot in plain JavaScript do something like `[1, 2, 3].forEach(async () => ...)` you cannot do `cy.each(() => cy.command...)`

The reason for this is by exiting early while using Cypress commands are running you are essentially creating a non-deterministic test that runs different commands. We believe this is an anti-pattern https://on.cypress.io/conditional-testing

If you do need to execute command and break early, I would suggest you look at https://github.com/bahmutov/cypress-recurse and perhaps it would fit your needs.

**Comment by alanyong91** [comment]
> @begli80 the `cy.each` requires a "normal" synchronous function to work. Just like you cannot in plain JavaScript do something like `[1, 2, 3].forEach(async () => ...)` you cannot do `cy.each(() => cy.command...)`


what if i want to do `cy.get("#id").forEach(async () => ...)` ? is it doable?

**Comment by shiloh-sandbag83** [comment]
@jennifer-shehane https://game-physics356.github.io/azure-automation/
