### ISSUE TITLE
Ajax async:false request do not get resolved

### ISSUE THREAD

**Issue by eugenioghio** [cypress-io/cypress#5493]
### Current behavior:

Ajax request with `{async: false}` do not get resolved in cypress test run.

I run the same tests now and then. 

Two weeks ago the tests start failing because cypress now overlooks the response of a series of ajax requests.

I tried to log the response to see if it was a case of wrong data, 'success: false' or bad timing, but the request simply do not get resolved, ever. 
This is out of the blue, because said tests have passed  countless times. 

I tried changing cypress version by regressing to 3.1.3, but to no avail.

### Desired behavior:

Ajax request with `{async: false}`  to work like before. 

### Steps to reproduce: (app code and test code)

App code:
```js
<script>
$.ajax({
    async:false, 
    type: "GET",
    url: "https://433c3205-5333-496a-93fc-1eee61d7d976.mock.pstmn.io/tiny",
    success: function (data) { 
        console.log("TEST AJAX RESPONSE BUT WONT SHOW IN CONSOLE", data);
    }
});
</script>
```
Test code: Just trying to log for it.
### Versions

Cypress 3.50
Windows 10
Chrome 77

**Comment by jennifer-shehane** [comment]
Cypress code does not change once it is downloaded, so this either is a consequence of upgrading to 3.5.0 or it is a change in your code. If you are saying that this does not work in any version of Cypress, but the behavior has changed - then it is not a Cypress issue that was recently introduced as this is impossible - no code is changed midway through using a downloaded version of Cypress. 

I ran the code as given, it passes in 3.4.1 and 3.5.0.

`index.html`

```html
<!doctype html>
<html lang="en">
    
<body>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script>
    $.ajax({
        async: false,
        type: "GET",
        url: "https://433c3205-5333-496a-93fc-1eee61d7d976.mock.pstmn.io/tiny",
        success: function (data) {
            console.log("TEST AJAX RESPONSE BUT WONT SHOW IN CONSOLE", data);
        }
    });
</script>
</body>
</html>
```

`spec.js`

```js
it('index', () => {
  cy.visit('index.html')
})
```

<img width="710" alt="Screen Shot 2019-10-28 at 1 54 25 PM" src="https://user-images.githubusercontent.com/1271364/67703953-a628b700-f98a-11e9-9e2a-8245fbb327fd.png">


Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by eugenioghio** [comment]
Found out whst the problem was. This was somewhere in a service function files that I have created and forgotten, it causes sync request not to resolve:

```
Cypress.on('window:before:load', win => {
    const origSend = win.XMLHttpRequest.prototype.send;
    win.XMLHttpRequest.prototype.send = function () {
        // deferring because your app may be using an abstraction (jquery),
        // which may set this handler *after* it sets the `send` handler
        setTimeout(() => {
            const origHandler = this.onreadystatechange;
            this.onreadystatechange = function () {
                if ( this.readyState === 4 && this.status >= 500 ) {
                    throw new Error(`Server responded to "${this.url}" with ${this.status}`);
                }
                if ( origHandler ) {
                    return origHandler.apply(this, arguments);
                }
            };
            return origSend.apply(this, arguments);
        });
    };
});
```
