### ISSUE TITLE
add tests for {moveToStart} / {moveToEnd} special sequences

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#5502]
add better tests for {moveToStart} / {moveToEnd} special char sequences

they were added in #4870 but not called out in changelog / documented / or tested, making it one of those "undocumented features")

* after this is fixed, we can open PR for adding to docs

**Comment by jennifer-shehane** [comment]
@w0wka91 Unfortunately [this PR](https://github.com/cypress-io/cypress/pull/6203) was merged in prematurely - without the tests passing after being merged in from develop. We had to revert this PR in https://github.com/cypress-io/cypress/pull/6469 in order to get our latest release out.

Please feel free to open a new PR for the work contained in this PR.
