### ISSUE TITLE
Relative paths showing for XHRs that are not actually relative

### ISSUE THREAD

**Issue by carpedalan** [cypress-io/cypress#5505]
### Current behavior:

![Example](https://cl.ly/11c689d0745b/%255B19860fde149b4a60e9886758c54614a1%255D_Image%2525202019-10-28%252520at%2525203.59.19%252520PM.png "Example")

XHRs displayed in the cypress UI sidebar display relative URLs even when the host doesn't match. In the above example after much painful debugging, I was able to reveal that the request being pointed at was an XHR to `https://localhost/api/login` when visually one would assume it was `https://alb/api/login`, based on the `window.location.host`.

### Desired behavior:

Only show relative paths when the hostname matches the baseUrl in XHR logging.

### Steps to reproduce: (app code and test code)

1. Setup a webapp that makes requests to itself (a relative path) that _is not `localhost`_. This can be done with a docker/docker-compose -based setup, or a baseUrl of a webapp that is deployed.
2. In the webapp application code, make an XHR to `http://localhost/any/path`
3. Observe that both requests display a relative path in the cypress logs.

If I had to guess, this seems like paths are displayed as relative if the host contains localhost, which makes the wrong assumption.

### Versions

* Cypress v3.5.0
(not platform specific)

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
