### ISSUE TITLE
How can I run the following command? cypress run --record --key e472d3e1-ad6a-4a18-884c-c08e12531f92

### ISSUE THREAD

**Issue by robdewGitHub** [cypress-io/cypress#5514]

**Comment by natkrish** [comment]
@robdewGitHub Are you missing something to add to this open issue? If you want to run the above command - you can use any command line tool to execute it. I use ConEmu for example and then navigate to the root of the project and then execute this command. Let me know how it goes

**Comment by jennifer-shehane** [comment]
Hi @robdewGitHub, pasting your record key in a public place is not advisable. There are reasons why this key should be kept secret as mentioned here: https://on.cypress.io/projects#Record-key

**We strongly advise that you regenerate a new key since you have exposed your private record key.** Instructions here: https://on.cypress.io/projects#Create-new-record-key

You need to run this command in a terminal or a CI environment. There are instructions about how to run this command here, including a video showing where to run the command: https://on.cypress.io/projects#Set-up-a-project-to-record

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).

**Comment by robdewGitHub** [comment]
> @robdewGitHub Are you missing something to add to this open issue? If you want to run the above command - you can use any command line tool to execute it. I use ConEmu for example and then navigate to the root of the project and then execute this command. Let me know how it goes

Hi Natkrish, I can't run the command from command prompt (CMD). Can you help me out?

**Comment by natkrish** [comment]
@robdewGitHub okay. can you try running the same command from this folder instead of the parent project root. So try running it like this: parentdirectory/node_modules/.bin/cypress run......
