### ISSUE TITLE
How can I pass a clientInfo that has many values by setCookie method?

### ISSUE THREAD

**Issue by TANCANJIE** [cypress-io/cypress#5535]
### Current behavior:

![Uploading Snipaste_2019-10-30_20-08-27.png…]()
After I executed the test, I got this hint.

> CypressError: cy.setCookie() must be passed an RFC-6265-compliant cookie value. You passed:

### Desired behavior:

I trid to pass a `clientInfo` by `setCookie` method but the `clientInfo` has many value so I got this error. I want to know if there any way for me to pass multi value?

### Steps to reproduce: (app code and test code)

```js
describe("start App", () => {
  before(() => {
    cy.visit("http://localhost:3000");
    cy.setCookie(
      "clientInfo",
      '"clientid":"xxxx-xxxx-xxxx-xxxx-xxxxxxxx","uid":"xxxxxx","utdid":"xxxxxxx","ticket":"xxxxxxxxxxx","android_id":"xxxxxxxx"'
    );
  });

  describe("The default UI", () => {
    it("get Daily Deal", () => {
      cy.get("h2").contains("Daily Deal");
    });
  });
});
```

From the code, we can see the value of param 'clentInfo' more than 1, so what can I do?

### Versions

"cypress": "^3.5.0"
"operating system" : Mac OS
"browser": Chrome

**Comment by jennifer-shehane** [comment]
The value you passed to `cy.setCookie()` is invalid for a cookie value. I can't tell you why because you have removed many parts of it. 

We use [strict-cookie-parser](https://www.npmjs.com/package/strict-cookie-parser) to parse the value you sent - this library is throwing an error saying your value does not meet the [RFC-6265](https://tools.ietf.org/html/rfc6265) guidelines for cookie values.

Please recheck the requirements and your cookie value again before sending.

**Comment by filiphric** [comment]
I’m bumping into this issue too after upgrading from 3.4.1 to 3.6.0. Command looks like this:

`cy
    .setCookie('Slido.Privacy', '{"categories":["Nonessential","Essential","Analytical","Advertising"],"isBannerClosed":true}', {
      domain: // my domain
    });`

**Comment by jennifer-shehane** [comment]
@filiphric If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

Also please update to the [current version of Cypress](https://on.cypress.io/changelog) as we've fixed a lot of cookie bugs since them.
