### ISSUE TITLE
Multiple elements cannot be chosen anymore since update to Cypress 3.5.0

### ISSUE THREAD

**Issue by Gamerdachs** [cypress-io/cypress#5537]
### Current behavior:

Multiple elements cannot be chosen anymore by `.first()`, `.last()`, or `eq(x)`. It worked fine for months, but broke with the update to Cypress 3.5.0. The error Cypress gives me is "CypressError: Timed out retrying: obj.indexOf is not a function".

### Desired behavior:

It should select the corresponding item.

### Steps to reproduce: (app code and test code)

App code:
```html
<div data-test="text">Test 1</div>
<div data-test="text">Test 2</div>
```

Test code:
```js
cy.get('[data-test=text]').first().should('contain', 'Test 1');
cy.get('[data-test=text]').eq(1).should('contain', 'Test 2');
```

### Versions
Cypress: 3.5.0
OS: MacOS 10.15
Chrome: 78.0.3904.70

**Comment by gabbersepp** [comment]
I tested it with following spec:

```js
  it("test", () => {
    cy.visit("/cypress/fixtures/index.html");
    cy.get('[data-test=text]').first().should('contain', 'Test 1');
    cy.get('[data-test=text]').eq(1).should('contain', 'Test 2');
  })
```

and following fixture:

```html
<div data-test="text">Test 1</div>
<div data-test="text">Test 2</div>
```

Result:
![image](https://user-images.githubusercontent.com/3234900/67874694-94374780-fb35-11e9-9df9-815726dcc0b6.png)

System:
Windows 10, Cypress 3.5.0

**Comment by jennifer-shehane** [comment]
As @gabbersepp mentioned - the test code provided passes in 3.5.0. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
