### ISSUE TITLE
window === window.parent resolving to true despite different location objects

### ISSUE THREAD

**Issue by PodgeHn** [cypress-io/cypress#5538]
### Current behavior:

Evaluating `window === window.parent` returns `true` within the webpage when it should be `false`. Inspecting the code from the debugger i can see both `window.location` object have different hrefs. These object seem to be different but return `true` when running cypress.

Our webpage uses `window.parent.postMessage()` to posts to a parent webpage to retrieve a oAuth token.

For testing i need to simulate this process but this cant be done due to the above error i am seeing

### Desired behavior:
`window !== window.parent` should evaluate to `true`

### Steps to reproduce: (app code and test code)

create webpage with statement `console.log(window !== window.parent)`
visit webpage within cypress.
Observe Console output.

### Versions
cypress: 3.4.1
MacOS
chrome

**Comment by jennifer-shehane** [comment]
Cypress runs your application within an iframe, so `window` will not equal `window.parent` when running within Cypress - `window.parent` will evaluate to the Cypress Test Runner window. 

Can you please detail the piece of code that is breaking within Cypress? What is happening during the `window.parent.postMessage()`? 

Essentially to fix this, Cypress would need to rewrite instances of `window.parent` to just be `window`. 

As a workaround today, you would need to rewrite the application code to call `window` instead of `window.parent` - you can do this specifically only when running within Cypress tests by following these instructions: https://on.cypress.io/using-cypress-faq#Is-there-any-way-to-detect-if-my-app-is-running-under-Cypress

**Comment by PodgeHn** [comment]
>Cypress runs your application within an iframe, so window will not equal window.parent when running within Cypress - window.parent will evaluate to the Cypress Test Runner window.

This is what i am expect to happen. Sorry i wrote the question wrong. See edits above.

I would expect window and window.parent not to be equal but they are evaluating as equal.

```TypeScript
        const parentWindow = window !== window.parent ? window.parent : window.opener;
        if (parentWindow) {
            parentWindow.postMessage(this.createRequest(forceFreshToken), this.parentOrigin);
             if (this.reject) {
                 this.reject(new Error('Timeout retrieving oAuth token for request'));
             }
         } else {
           this.reject(new Error('No parent window to post to'));
         }
```

**Comment by jennifer-shehane** [comment]
@PodgeHn Sorry, I should have read your issue more carefully. Can you try setting `modifyObstructiveCode` to `false` in your `cypress.json` configuration? Cypress makes modifications to some of the code - to try to prevent situations of framejacking that would cause the application to not load within Cypress - so we may be already editing this line of code. Setting `modifyObstructiveCode` to `false` will turn off any editing of Cypress. https://on.cypress.io/configuration#modifyObstructiveCode

**Comment by PodgeHn** [comment]
Yes that did the trick 👍. Thanks for your help. Appreciate it.
