### ISSUE TITLE
User name is not updated when changed in GitHub

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#558]
There are some users without name in the User's list on the Organizations page. I requested them to fill in a user name in Github since it is not possible to override the user name in the Cypress Dashboard.

The user name is still "_No Name_" in the list.

**Comment by jennifer-shehane** [comment]
@trydionel Another Dashboard issue to keep track of.

**Comment by jennifer-shehane** [comment]
The best place to express interest and see progress for Dashboard features is on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard and we want to make sure any feedback gets seen and addressed by the right team. 

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thanks!
