### ISSUE TITLE
Sitemap on Dashboard not intuitive

### ISSUE THREAD

**Issue by fvanwijk** [cypress-io/cypress#560]
For several times I was lost on the Dashboard pages because the sitemap felt a bit unintuitive to me.

The main menu contains two items: *Runs* and *Organizations*.

On the *Runs* page, there are child pages for every project, containing a Runs tab and a Settings tab.

The *Organizations* page contains large tiles with a link to Runs > _org_/_project_ > Settings.
The cog icon links to Organizations > _org_ > Users.

These things are confusing to me:
* Project settings can be found on the Runs page. I expect them to be under Organizations > _org_ > _project_ > Settings.
* The main action on the Organization page is clicking the super large project tile, which navigates away from the Organizations page (related to previous bullet)
* Users have access to projects via their Organization, so it is not possible to manage permissions per project. It would be better to remove the "Users with Access" list. The indenting is messed up anyway ;) Also the "Access" tooltip link is broken.
This might be a separate GH issue.

In general I think you should separate Organizations, Projects and Runs clearly, or just merge them together because these entities are closely related.

**Comment by jennifer-shehane** [comment]
Thanks so much for opening all of these issues for the [Dashboard](https://on.cypress.io/dashboard). We are definitely planning to take a second look at the design of the Dashboard and optimize it to better fit our user's needs, so user feedback is crucial! Thank you!

**Comment by jennifer-shehane** [comment]
cc @trydionel

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.
