### ISSUE TITLE
Headless + Typescript

### ISSUE THREAD

**Issue by mspoulsen** [cypress-io/cypress#5607]
Is Cypress capable of running headless if typescript is in the mix? I have tried hard to set it up but with no luck. Do you have a sample repo?

**Comment by jennifer-shehane** [comment]
Please check our docs: https://on.cypress.io/typescript-support

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
