### ISSUE TITLE
404 error: https://docs.cypress.io/dashboard/overview/projects.html#Set-up-a-Project-to-Record

### ISSUE THREAD

**Issue by jelling** [cypress-io/cypress#561]
Running `cypress run --record` returns:

```
You passed the --record flag but did not provide us your Record Key.

You can pass us your Record Key like this:

  cypress run --record --key <record_key>

You can also set the key as an environment variable with the name CYPRESS_RECORD_KEY.

https://on.cypress.io/how-do-i-record-runs
```

Clicking URL redirects to https://docs.cypress.io/dashboard/overview/projects.html#Set-up-a-Project-to-Record

However, that page returns a 404.
![screen shot 2017-07-12 at 1 25 53 pm](https://user-images.githubusercontent.com/1887486/28130718-af2b9bac-6705-11e7-85eb-cfcdd13f793d.png)

**Comment by jennifer-shehane** [comment]
This has been fixed. Thank you for reporting!

**Comment by jelling** [comment]
Workaround using   cypress-cli@0.13.1":

Enabled video record in cypress.json via:

```
{
    "chromeWebSecurity": false,
    "videoRecording": true
}
```

And run cypress without the record flag via:

```
cypress run
```

Tests will now run AND videos will record. @jennifer-shehane perhaps that's not as intended?

**Comment by brian-mann** [comment]
The `--record` flag records runs on our dashboard.

The `videoRecording` option simply means to "capture a video" of the run. We should probably rename this option since its two different things.

Unless you set the `--record` flag, it will not send runs to our Dashboard.

**Comment by jelling** [comment]
@brian-mann yeah, maybe, a --premium flag would make sense as I'm sure you'll be adding more features that fall in that category.

FYI page is 404'ing even after a cache clear. Perhaps just a CDN roll-out issue.

**Comment by brian-mann** [comment]
If you visit: https://on.cypress.io/how-do-i-record-runs it works now.

I think we'll likely keep the `--record` flag since all of the verbiage says to "Record on our Dashboard". Plus it's not like you can "accidentally" send us any data - you have to opt into the service and setup your project.

Worse case if you hit a road block as you did, where we need you to provide us additional information before *actually* recording your run.

Had that link redirected you to the correct doc you probably would have figured it out.

I've opened an issue with our team internally to think about renaming the `videoRecording` option to something thats clearer its really just about capturing a video of the run. That will hopefully clear up the verbiage around **recording** since that's only applicable on our Dashboard service.
