### ISSUE TITLE
False positives: Cypress passes tests that use the same timeout option object in specific sequence.

### ISSUE THREAD

**Issue by beatrichartz** [cypress-io/cypress#5641]
### Current behavior:

Cypress produces false positives if one test contains a long timeout which is fed in via a variable. Below is a test to reproduce, which fails to produce a failure for the second test on `https://google.com`.

### Desired behavior:

Fail the last `contains` test.

### Steps to reproduce: (app code and test code)

```javascript
describe('Cypress bug', () => {
  const LONG_TIMEOUT_OPTION = {
    timeout: 10000,
  }

  beforeEach(() => {
    cy.viewport('macbook-15')
  })

  it('should visit Google', () => {
    cy.visit('/')
    cy.contains('About').click()
    cy.contains(
      'Our mission is to organise the world’s information and make it universally accessible and useful.', LONG_TIMEOUT_OPTION)
    cy.contains('See what we build').scrollIntoView().click({ force: true })
    cy.contains(
      'Learn more', LONG_TIMEOUT_OPTION)
  })

  it('should visit Google', () => {
    cy.visit('/')
    cy.contains('About').click()
    cy.contains('Something that the page does not contain', LONG_TIMEOUT_OPTION)
  })
})
```

![image](https://user-images.githubusercontent.com/305847/68448628-38a54200-0238-11ea-8d77-da1d5b33650c.png)
![image](https://user-images.githubusercontent.com/305847/68448677-5ffc0f00-0238-11ea-8e80-c309ac9f1e7f.png)

### Versions
`uname -a`
`Darwin angel 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

Cypress version `3.6.0`
Electron version `73`
Chrome version `Version 74.0.3729.157 (Official Build) (64-bit)`

**Comment by jennifer-shehane** [comment]
I'm not able to recreate this behavior exactly. Although, this does highlight that the options Object is being mutated as it is passed along. 

My example below demonstrates logging of the `LONG_TIMEOUT_OPTION`.

```js
describe('Cypress bug', () => {
  const LONG_TIMEOUT_OPTION = {
    timeout: 10000,
  }

  it('should visit Google', () => {
    cy.visit('http://www.google.com')
    cy.contains('About').click().then(() => {
      cy.log(LONG_TIMEOUT_OPTION)
    })
    cy.contains(
      'Our mission', LONG_TIMEOUT_OPTION)
  })

  it('should visit Google too', () => {
    cy.visit('https://www.google.com')
    cy.contains('About').click().then(() => {
      cy.log(LONG_TIMEOUT_OPTION)
    })
    cy.contains('Something that the page does not contain', LONG_TIMEOUT_OPTION)
  })
})
```

In the first log, it logs:

<img width="167" alt="Screen Shot 2020-01-06 at 12 16 49 PM" src="https://user-images.githubusercontent.com/1271364/71797911-7549ba00-307e-11ea-9db9-7e9b2a1fa76e.png">

In the second log, it logs:

<img width="440" alt="Screen Shot 2020-01-06 at 12 17 10 PM" src="https://user-images.githubusercontent.com/1271364/71797922-81357c00-307e-11ea-91b3-0ad7f6140c80.png">

This looks to be this issue: https://github.com/cypress-io/cypress/issues/3171

---

I can't recreate the original issue however, so I will need more information or a reproducible example. Perhaps the fact that Google's website has changed has some effect on it because I couldn't run the original example exactly. 

Please comment with a reproducible example and we will consider reopening.

**Comment by beatrichartz** [comment]
Thanks for having a look - I've created a repo here: https://github.com/beatrichartz/cypress-false-positive

I've been able to reproduce this with the latest version of Cypress - let me know if you have trouble reproducing it using the repo.

**Comment by jennifer-shehane** [comment]
Yeah, I wasn't able to reproduce this in either `cypress run` or `cypress open`. Followed the instructions in the repo when running. In my example, the first test always failed to find the content you were trying to find. 

I VPN'd to Atlanta because initially google was not even displayed in English for me, but there is no text on the page for 'See what we build' in the about page. I then tried VPN'ing into Sydney since that seems to be where you are from and now the correct content is showing since Google's website is largely generated based off of locale.

So, this finally recreates the issue although I would prefer a simple `index.html` file to test against since at any time Google could change their site and we're left with no reproducible example again. 

Something is very oddly specific about this example. I tried to remove several different steps and can't reduce the example any further.

```js
// You must VPN into Sydney, Australia
describe('Cypress bug', () => {
  const LONG_TIMEOUT_OPTION = {
    timeout: 10000,
  }

  it('should visit Google', () => {
    cy.visit('https://www.google.com')
    cy.contains('About').click()
    cy.contains(
      'Our mission', LONG_TIMEOUT_OPTION)
    cy.contains('See what we build', LONG_TIMEOUT_OPTION).scrollIntoView().click({ force: true })
    cy.contains(
      'Learn more', LONG_TIMEOUT_OPTION)
  })

  it('should visit Google 2', () => {
    cy.visit('https://www.google.com')
    cy.contains('About').click()
    cy.contains('Something that the page does not contain', LONG_TIMEOUT_OPTION)
  })
})
```

![Screen Shot 2020-01-14 at 12 38 46 PM](https://user-images.githubusercontent.com/1271364/72318509-d8fd6400-36ca-11ea-8cec-a6730baa7f49.png)

I haven't been able to reproduce outside of Google from my easy example. 

```html
<!DOCTYPE html>
<html>
<body>
  <button>About</button>
  <p>Our mission</p>
  <div>Learn more</div>
  <p>See what we build</p>
</body>
</html>
```

```js
describe('Cypress bug', () => {
  const LONG_TIMEOUT_OPTION = {
    timeout: 10000,
  }

  beforeEach(() => {
    cy.viewport('macbook-15')
  })

  it('should visit Google', () => {
    cy.visit('index.html')
    cy.contains('About').click()
    cy.contains(
      'Our mission', LONG_TIMEOUT_OPTION)
    cy.contains('See what we build').scrollIntoView().click({ force: true })
    cy.contains(
      'Learn more', LONG_TIMEOUT_OPTION)
  })

  it('should visit Google', () => {
    cy.visit('index.html')
    cy.contains('About').click()
    cy.contains('Something that the page does not contain', LONG_TIMEOUT_OPTION)
  })
})
```

![Screen Shot 2020-01-14 at 12 46 01 PM](https://user-images.githubusercontent.com/1271364/72318886-eff08600-36cb-11ea-83c4-fcd5d5db061e.png)
