### ISSUE TITLE
how can i open new tab ? it doesn't have any  anchor <a>

### ISSUE THREAD

**Issue by nikhilesh009** [cypress-io/cypress#5646]
```
<button class="md-button md-ink-ripple" type="button" ng-transclude="" ng-if="$ctrl.showMenu" ng-disabled="$ctrl.offerNewForm.$invalid" ng-click="$ctrl.onSaveHandler()" style="">
      Save
    <div class="md-ripple-container" style=""></div></button>
```
when i click this button it open in new tab, is there any posiblity to visit new tab in same tab ?
i had some more button ,but that consist with anchor link. but this doesn't 

```
  cy.get('iframe', { timeout: 5000 }).then(function($element) {
      const $body1 = $element.contents().find('body');
      const cyElement1 = cy.wrap($body1);
      cyElement1
        .find('[ng-click="$ctrl.onBasicNext()"]', { timeout: 40000 })
        .click();
      const $body2 = $element.contents().find('body');
      const cyElement2 = cy.wrap($body2);
      cyElement2
        .find('[ng-click="$ctrl.onSaveHandler()"]', { timeout: 40000 })
        .click();
    });
```
i wrote this but its open in new tab and i lose control over it

**Comment by gabbersepp** [comment]
Can you provide a minimal runnable example? I think there are more than one posibilities to open a new window so the solution may depend on how you implemented it in your app code

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
