### ISSUE TITLE
Execute multiple environment in one command 

### ISSUE THREAD

**Issue by AdnanAlakwarit** [cypress-io/cypress#5648]
Hi!
I have test code in cypress and I need to run it in three environments:
configuration for each one implemented in a file.json 
prod.json, stag.json, and test.json

I can do that by plugins solution the do like this > npx cypress run --env configFile=prod

but I need to run all three commands in one line 
Is this possible?
Thanks

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
