### ISSUE TITLE
Cypress crashes and aborts XHR get request this morning

### ISSUE THREAD

**Issue by prudhvidandamudi** [cypress-io/cypress#5659]
The cypress is crashing in the middle of the test with the following error which is shown in the screenshot. The test is running successfully on Friday and all of a sudden today it's crashing this way and was not able to understand the reason behind the crash. This is happening at a step where it will click a button and application loads a new page and all of a sudden it crashes. Need urgent help 
I see the XHR get requests are getting aborted and canceled.

![image](https://user-images.githubusercontent.com/46937269/68598671-38da5300-046d-11ea-8bdc-5e587a5f408c.png)

**Error On Console**
![image](https://user-images.githubusercontent.com/46937269/68598860-91a9eb80-046d-11ea-8679-d5dc1aff5260.png)

![image](https://user-images.githubusercontent.com/46937269/68600781-19ddc000-0471-11ea-9a5a-d87830b6013a.png)

Gif Image of execution
![Cypress crashes](https://user-images.githubusercontent.com/46937269/68599332-6a9fe980-046e-11ea-9a8a-128463951ee8.gif)

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by karem63** [comment]
![Screen Shot 2020-01-12 at 16 41 31](https://user-images.githubusercontent.com/56069690/72220580-a2a0d700-355a-11ea-8114-f9050bccc675.png)

facing the same problem! Cypress sometimes aborts XHR.
it's /token url which is responsible for login to the site i'm testing.

**Comment by jennifer-shehane** [comment]
Hi, @karem63 please provide a reproducible example otherwise we cannot begin debugging your issue. 

Cypress does sometimes *report* XHRs as being aborting when the page navigates away or moves to the next test - this is expected behavior however so we would need a reproduction of an actual bug case where this is being handled incorrectly.

**Comment by karem63** [comment]
Hello @jennifer-shehane, what does it mean it's an expected behavior ? it's causing to crash the tests when Cypress aborts XHRs.
which example to provide ?

**Comment by jennifer-shehane** [comment]
@karem63 We need a failing test case that we can run on our machines in order to identify the exact issue you are seeing. 

Cypress *reports* aborted XHRs when they are aborted, so to see an XHR as aborted by itself in a screenshot is not an indication of an actual bug. We need a failing test case provided. Thanks.
