### ISSUE TITLE
Request: expose BrowserWindow instance

### ISSUE THREAD

**Issue by dwelle** [cypress-io/cypress#5670]
### Desired behavior:

Would be great if the Electron's BrowserWindow would be exposed to us in the plugins file. Is there some technical limitation preventing it?

```js
module.exports = ( on, config ) => {
  on('before:browser:launch', (browser, args, /* --> */ browserWindow) => {
    if ( browser.name === 'electron' ) {
      // browserWindow supplied here
    }
  });
});
```

### Why?

- Ability to customize behavior, such as changing how the browser should behave when downloading files (to auto-accept download prompt), etc.

**Comment by flotwig** [comment]
Since your plugins file runs in Node, not Electron, there's not a way to pass the actual `BrowserWindow` *instance*.

Some alternatives:

* Could create a proxy object for BrowserWindow that gets/sets/callsback over IPC, and expose this in a new `on:browser:window` event or something
* Could accept more options for BrowserWindow in `before:browser:launch` - right now, I believe only `webPreferences` can be modified
* Proper support for interacting directly w Chrome DevTools Protocol in the browser or pluginsfile could be added - then you could use the setDownloadBehavior command: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDownloadBehavior

I'm kind of leaning towards option #3 - it would work in Electron and in Chrome; plus, I'd love to see what users do in Cypress with direct access to CDP from their tests. Thoughts?

**Comment by dwelle** [comment]
I didn't realize that Cypress is actually spawning a node process for the plugins file (but makes sense since users can use their system node by setting `nodeVersion`).

Mhm --- yea, I'd go with **(3)**, too. Since Cypress is moving to CDP for all the things (well, lots of them), skipping the middle man (Electron) and exposing CDP sounds good.

**Comment by avallete** [comment]
> I didn't realize that Cypress is actually spawning a node process for the plugins file (but makes sense since users can use their system's node by setting `nodeVersion`).
> 
> Mhm --- yea, I'd go with **(3)**, too. Since Cypress is moving to CDP for all the things (well, lots of them), skipping the middle man (Electron) and exposing CDP sounds good. It'll also allow (as you mentioned) to instrument all the browsers (kinda -- dunno how much is FF's devTools protocol compatible with CDP).

About your questioning on Firefox CDP:

**Does FF use CDP ? How will that evolve in future ?**:  FF use kind of CDP, the FF implementation is called [Remote](https://wiki.mozilla.org/Remote) and according to the docs, it's based on CDP. I did ask a question about the development of Remote and the goal of it to the FF dev team, here is a quote:

> Eventually the plan is for remote to implement the WebDriver BiDi standard, but that doesn't exist yet, so implementing CDP is a step along the way

PS: Remote team know about Cypress existence, there is actually [an open ticket about Cypress support with Remote](https://bugzilla.mozilla.org/show_bug.cgi?id=1604723).

**Comment by jennifer-shehane** [comment]
Since this hasn’t gotten a lot of interest over the years, we’ll close this issue.
