### ISSUE TITLE
cypress browser cache the cookie while running the tests

### ISSUE THREAD

**Issue by dennismail4u** [cypress-io/cypress#5675]
### Current behavior: 

When I open the test runner and run my test, it directly lands on the home page instead of login page since it has the cookie info. And if I rerun the test from runner, it goes to login page by clearing the cookie. 

### Desired behavior: 

I want every test should be started on a new session without having any cookie. And that was the way it was working before. I am using 3.4.0 version now.

### Steps to reproduce: (app code and test code): 

I have a login steps on beforeEach and if I run, it lands on home page directly all the time I run the new test. 
steps: 
```
beforeEach: 
cy.visit(url);
login()
```

test: do some actions on home page

### Versions

 3.4.0, electron 61. Same issue with head less browser too.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem - there is no code we were given that we can run on our machine.. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

Overall this is part of this larger issue though https://github.com/cypress-io/cypress/issues/686
