### ISSUE TITLE
Cypress swallows requests with pipe, returns 400 error

### ISSUE THREAD

**Issue by jylertones** [cypress-io/cypress#5695]
### Current behavior:

When submitting an XHR from the page in Cypress, any unescaped pipe character will cause Cypress to not submit the request to the backend, but will result in an automatic `400` response.

i.e. `GET /api?param=1|2` does not work, but `GET /api?param=12` does work

### Desired behavior:

The request should be submitted to the backend/server with the same URL as entered, even if escaping is incorrect.

### Steps to reproduce: (app code and test code)

Project with reproducible scenario: https://github.com/jylertones/cypress-400-pipe

To run server: `npm run server`
To run tests: `npm run cypress`

### Versions
OS: Linux (tested in various)
Browser: both bundled Electron and Chrome 78
Last working: 3.4.1
Broken in 3.5.0 to present (3.6.1 at the moment)

**Comment by moconnord360** [comment]
I noticed this issue, too. Although it only happens on my production and staging environments, not on my local...

**Comment by orayya-esters** [comment]
I noticed that if encode the url (meaning the pipe turns into %7C) it works correctly.
After I [researched a little](https://perishablepress.com/stop-using-unsafe-characters-in-urls/) I found out is a good practice.

**Comment by jennifer-shehane** [comment]
This was fixed in Cypress 3.8.0.

This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
