### ISSUE TITLE
Uncaught exception not thrown in DevTools

### ISSUE THREAD

**Issue by ben-x-dev** [cypress-io/cypress#5698]
### Current behavior:

The rightclick method is throwing an error unlike `trigger('contextmenu')`. As you can see from the screenshot below, the right click works because the context menu opens up but cypress' test fails. Can't see any js error doing the right click on the page being tested.
![image](https://user-images.githubusercontent.com/11013464/68830585-03d93500-06e7-11ea-840e-51ad464e05fe.png)

### Desired behavior:

It should work just like `trigger('contextmenu')`. Using that is the current workaround to allow tests like this to pass.

### Steps to reproduce: (app code and test code)

Try this simple test:
```js
context('App Tests', () => {
  beforeEach(() => {
    cy.visit('https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-contextmenu-firstclick.html');
  })

  it('test right click', () => {
    cy.get('[aria-rowindex="1"] > [aria-colindex="1"] > .datagrid-cell-wrapper').rightclick();
  });
});
```

### Versions

latest

**Comment by jennifer-shehane** [comment]
`.rightclick()` by design does not behave exactly like `.trigger('contextmenu')`, it takes into account several over things that occurs when a user would normally rightclick and triggers other events accordingly (like `mouseover` for example).

If you solely want to trigger the event, then using `.trigger()` is the correct workaround. 

When you see Cypress mentioning an uncaught exception thrown from a cross origin script. So this error could be triggered during other events outside of `contextmenu` (like `mouseover`). 

This situation is strange the error is no longer printing to the console when Cypress catches it. This is a bug and we should have someone look into this.

You can ignore uncaught:exceptions by adding the code below:

```js
Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false
})

context('App Tests', () => {
  beforeEach(() => {
    cy.visit('https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-contextmenu-firstclick.html')
  })

  it('test right click', () => {
    cy.get('[aria-rowindex="1"] > [aria-colindex="1"] > .datagrid-cell-wrapper').rightclick()
  })
})
```

When adding this code, then rerunning the Cypress test - we now see an error in the devTools console. It appears that an error is being thrown through the popup menu widget during `keydown` events - where `this` is `undefined`.

I'm not sure why `keydown` events would be fired during `.rightclick()` and will have to check with @Bkucera, but I would think this is not intended.

<img width="472" alt="Screen Shot 2019-11-14 at 11 29 32 AM" src="https://user-images.githubusercontent.com/1271364/68876594-ba7eea80-06d2-11ea-88e3-1bcdefc57aa8.png">

<img width="748" alt="Screen Shot 2019-11-14 at 11 30 36 AM" src="https://user-images.githubusercontent.com/1271364/68876608-c074cb80-06d2-11ea-8fe7-03e9a58838e0.png">

**Comment by nbcp** [comment]
Thanks! Looks like you figured out the root of the problem already.
Btw it would really help to include something like this in the [docs](https://docs.cypress.io/guides/references/error-messages.html#Uncaught-exceptions-from-your-application):

> Add this to print your application's error stack trace on the devTools console:
> `Cypress.on('uncaught:exception', () =>  false);`

**Comment by jennifer-shehane** [comment]
@nbcp This is not the designed behavior - this is a bug. The uncaught exception should be thrown to the DevTools. 

We found the root of the issue though, which is a bit confusing how this is related, but the popup's third party code was at some point evaluating `window` as `undefined`, which is why the error was being thrown in the first place. 

The code for this is done in [cypress-io/cypress#5709](https://github.com/cypress-io/cypress/pull/5709), but has yet to be released.
We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by jennifer-shehane** [comment]
Actually, I am going to reopen this to track the issue of the uncaught exception not being thrown to DevTools.

**Comment by nbcp** [comment]
Sweet! Thanks @jennifer-shehane
