### ISSUE TITLE
How to store and use DOM element ?

### ISSUE THREAD

**Issue by liamoar** [cypress-io/cypress#5716]
hi everyone , can any one help me solve this.

  cy.get('.col-prf-left > :nth-child(3) > .col-lg-8 > p').then(($data)=>{
            const userid = $data.text()
            cy.log(userid)
        })
i cannot access this "userid" outside this cy.get, so i tried using aliases as down below as in the documentation but it shows  Type error: cannot read  property 'a' of undefined .  
        //using aliases
        cy.get('.col-prf-left > :nth-child(3) > .col-lg-8 > p').invoke('text').as('a')
        const checkid = this.a

Also can i save this element value in the cypress.json file or fixture json file . if yes, how to do it ?

**Comment by syn-zeta** [comment]
@liamoar Your issue is more related to JS than Cypress.

Declaring `userid` inside the closure scopes it to that function and is thus inaccessible outside.

The aliasing looks okay, but accessing `a` when the async commands haven't yet executed will result in `undefined`. Refer to the docs at https://docs.cypress.io/api/commands/as.html#as-is-asynchronous.

For writing to files, refer https://docs.cypress.io/api/commands/writefile.html#Syntax.

---

@jennifer-shehane Has something like Gitter been considered to redirect users with general usage questions to? The issues section could then prolly be restricted to bug reports, feature requests, and such.
