### ISSUE TITLE
Custom command loses it's right chainable attribute (Typescript)

### ISSUE THREAD

**Issue by masaanli** [cypress-io/cypress#5724]
### Current behavior:
I'm using Typescript with a declaration file but then my should is linking to the wrong chainable from chai instead of Cypress....

### Desired behavior:

That chainable gives the right thing back. Because now 

### Steps to reproduce: (app code and test code)
Add custom command:
```ts
Cypress.Commands.add('getMatCheckbox', (selector, _options) => {
    return cy.get(selector).find("[type=\"checkbox\"]");
});
```

Add index.d.ts to cypress support folder:
```ts
declare namespace Cypress {
    interface Chainable<Subject> {
        getMatCheckbox<K extends keyof HTMLElementTagNameMap>(selector: K, options?: Partial<Cypress.Loggable & Cypress.Timeoutable & Cypress.Withinable>): Cypress.Chainable<JQuery<HTMLElementTagNameMap[K]>>;
        getMatCheckbox<E extends Node = HTMLElement>(selector: string, options?: Partial<Cypress.Loggable & Cypress.Timeoutable & Cypress.Withinable>): Cypress.Chainable<JQuery<E>>;
        getMatCheckbox<S = any>(alias: string, options?: Partial<Cypress.Loggable & Cypress.Timeoutable & Cypress.Withinable>): Cypress.Chainable<S>;
    }
}
```

Write this line in the spec (test):
```js
cy.getMatCheckbox("[formcontrolname=fieldName]").should("be.checked");
```

Should is now not typed anymore...
Error: Should expects 0 arguments
When navigating to 'should' im getting into chai/index.d.ts instead of Cypress/index.d.ts

### Versions
MacOS 10.15.1, Cypress 3.6.0

**Comment by jennifer-shehane** [comment]
Our types are defined here: https://github.com/cypress-io/cypress/blob/develop/cli/types/index.d.ts

We would love an open PR - even one that is a work in progress is fine. Check out our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) and ask us if you get stuck.

**Comment by masaanli** [comment]
@jennifer-shehane i've added a custom command and trying to external the Cypress types. Already using the Cypress types.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
