### ISSUE TITLE
Chrome failing to load web page - Cypress 3.6.1, Chrome  78.0.3904.108

### ISSUE THREAD

**Issue by pipesmoke120** [cypress-io/cypress#5744]
### Current behavior:

When selecting a spec file from the Cypress Test Runner, a Chrome browser window opens with the correct URL but just displays the 'Aw snap!' message.  Cannot pull information from chrome dev tools as Chrome states it is disconnected from the web page.
Same problem occurs for Cypress example spec files as our own.

Tests all work fine in Electron through the test runner, and all work through console commands.

Some other issues have been created that seem similar but reference older versions of Cypress from what I can see.

### Desired behavior:
Tests to open and run in Chrome.

### Steps to reproduce: (app code and test code)

Open Cypress test runner.
Select a spec file to run using Chrome 78.

### Versions
Cypress 3.6.1
Chrome  78.0.3904.108
Windows 10 with all current updates

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

>Open Cypress test runner.
>Select a spec file to run using Chrome 78.

We will need more information on reproducing this - we have many many tests opening the runner in Chrome 78 and it working, so it is likely isolated to your configuration or the url you are visiting, the test code you are running. Also posting screenshots of the exact errors you are seeing. Please comment in this issue with a reproducible example and we will reopen the issue.
