### ISSUE TITLE
Cypress Dashboard Date Filter

### ISSUE THREAD

**Issue by BrettWalker05** [cypress-io/cypress#5749]
### Current behavior:

The new Date filter on cypress dashboard does not include today. When selecting any of the date options (last 7 days, last 30 days, last 3 months, last 12 months, All Time) todays date or current week is not included see print screen.

![Screenshot 2019-11-20 at 10 12 53](https://user-images.githubusercontent.com/46792277/69230128-9dd52d80-0b7e-11ea-878f-8e282c41d4bc.png)

### Desired behavior:

The most critical information in cypress dashboard is the current runs, by default I expect all options to include today.

### Steps to reproduce: (app code and test code)

Open dashboard
Use one of the predefined date filters
See today not included or current week

### Versions

Latest Cypress Dashboard

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.

**Comment by jennifer-shehane** [comment]
There is a now a ‘Today’ filter. 

![](https://user-images.githubusercontent.com/3586758/71745053-b3e93580-2e2e-11ea-9ad6-981eb802f67e.png)
