### ISSUE TITLE
It isn't it possible to use .find() with a .wrap() element.

### ISSUE THREAD

**Issue by ryan-mulrooney** [cypress-io/cypress#5758]
### Current behavior:

It isn't it possible to use `.find()` with a wrapped element.

**For example:**

```js
cy
  .get('#SOME_ELEMENTS')
  .eq(0)
  .then(
     $element => {
     cy.wrap($element).find('.button').click()
})
```

**When I do that, the error in the test runner is:**

```
CypressError: cy.find() failed because it requires a DOM element. The subject received was: > null
```

But... this isn't true, because `cy.wrap($element).should('contain', 'SOME_TEXT')` works fine.

**When not using .wrap() the .find() is successful. E.g:**

```js
cy
  .get('#SOME_ELEMENTS')
  .eq(0)
  .find('.button')
  .click()
})
```

### Desired behavior:

`.find()` should work for a `.wrap()` element

### Versions

3.1.5

**Comment by ryan-mulrooney** [comment]
Not even a comment after two weeks :(

**Comment by bahmutov** [comment]
Don't take it personally - we have a lot of open issues due to the project's popularity. 

- Please try latest version 3.7.0
- Please give us reproducible example (maybe clone https://github.com/cypress-io/cypress-test-tiny and add HTML + spec there?) so we can see the failing test

I suspect the elements there appear dynamically. `eq(0).find('.button')` retries while `.then ... wrap` does not retry, read our guide here https://on.cypress.io/retry-ability to understand the difference

**Comment by jennifer-shehane** [comment]
This code does work. Working example below. Double check that there is an element being passed into `cy.wrap()`. 

```js
it('.find after .wrap', () => {
  cy.visit('https://example.cypress.io/commands/network-requests')

  cy.get('#network-requests')
    .eq(0)
    .then(
      $element => {
        cy.wrap($element).find('.network-btn').click()
      })
})
```

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by ryan-mulrooney** [comment]
Weird. Clearly something isn't working correctly here though.. since I have examples that pass (proving there is a DOM element) and very similar ones using .wrap that fail.

**Comment by jennifer-shehane** [comment]
@ryan-mulrooney The DOM element may be detaching from the DOM before moving to the next command? I'm not sure since I do not have your exact example.
