### ISSUE TITLE
Side menu disappears after test run.

### ISSUE THREAD

**Issue by seanlawrenz** [cypress-io/cypress#5766]
### Current behavior:

When I run a test everything works as expected. If I change or rerun the test for any reason, the side menu disappears. I have to delete the app data after every run. 
<img width="1280" alt="Screen Shot 2019-11-21 at 3 35 02 PM" src="https://user-images.githubusercontent.com/18721340/69374825-ecfd8a00-0c74-11ea-86b9-502810c55936.png">
<img width="1448" alt="Screen Shot 2019-11-21 at 3 35 22 PM" src="https://user-images.githubusercontent.com/18721340/69374830-ef5fe400-0c74-11ea-89ff-96031e6fdcd2.png">

### Desired behavior:

The side menu should stay open after every test.

### Steps to reproduce: (app code and test code)

Make any test. Run `cypress open`. After the test hit stop or run another test and the side menu is gone.

### Versions

cypress: 3.41

**Comment by seanlawrenz** [comment]
Y'all just going to ignore this?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example that we can run on our machines and we will reopen the issue. We need html + test code to run, otherwise we have no idea what mechanism your application is using that may be causing this issue in Cypress.
