### ISSUE TITLE
Slack/Email Notifications

### ISSUE THREAD

**Issue by amcdnl** [cypress-io/cypress#578]
### Is this a Feature or Bug?
Feature

### Desired behavior:
One of the most important things about automated testing is to know when a change actually caused the tests to fail. It would be nice if there was a out-of-the-box solution to send a message to slack notifying you of the failure. 

Taking it a step further it would be really nice to have a email sent to the git commiter that caused the breaking test.

**Comment by willischu** [comment]
These would be amazing!
Slack notifications to a desired channel and/or @user.

**Comment by jennifer-shehane** [comment]
Related full proposal for integrations: https://github.com/cypress-io/cypress/issues/981

**Comment by aequasi** [comment]
This is now possible with the cypress Github integration, with the github slack integration, but it doesn't look the greatest ([bunch of image links](https://github.com/cypress-io/cypress/issues/981#issuecomment-517445672))

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.

**Comment by jennifer-shehane** [comment]
Slack integration is now available within our Cypress Dashboard. It allows you to see your Cypress test results directly in your teams’ Slack channels. Please read our [Slack Integration](https://on.cypress.io/slack-integration#Install-the-Cypress-Slack-app) docs to get started.
