### ISSUE TITLE
Test isolation when depending on server state

### ISSUE THREAD

**Issue by yagudaev** [cypress-io/cypress#5782]
### Current behavior:

There is no real E2E testing without a server. A server maintains state and needs to be properly reset. Consider the following code:

```javascript 
describe('Counter App', () => {
  describe('Counting', () => {
    beforeEach(() => {
      resetServerData()
      cy.visit('/')
    })

    it('increments the counter', () => {
      cy.contains('Increment').click()
      cy.get('[data-cy="counter"]').contains('1')
      cy.contains('Increment').click() // "accidently" click increment to show flakiness
    })

    it('resets the count', () => {
      cy.contains('Increment').click()
      cy.get('[data-cy="counter"]').contains('1')
      cy.contains('Reset').click()
      cy.get('[data-cy="counter"]').contains('0')
    })
  })
})

function resetServerData() {
  cy.request('POST', 'http://localhost:4000/counter', { counter: 0 })
}
```

Every time we click increment we update the server state. Because we do not explicitly wait for the last request to increment to finish, it will affect the results of our second test. It will occasionally make it fail. 

The simple workaround is to add

```javascript
it('increments the counter', () => {
  cy.contains('Increment').click()
  cy.get('[data-cy="counter"]').contains('1')

  cy.server()
  cy.route('POST', 'http://localhost:4000/counter').as('increment')
  cy.contains('Increment').click() // "accidental" call to show flakiness
  cy.wait('@increment')
})
```

### Desired behavior:

Cypress should know about any pending requests that have not yet been resolved. Therefore it should NOT move on to the next test before all requests of the previous tests have been finished.

While the above example is simple, we had a lot of issues with this exact behaviour. When you have hundreds of tests in dozens of files that rely on server state this becomes a big deal. 

Furthermore, CI services typically run in a headless mode, while locally developing we run in a full-fledge browser window. In headless mode, each test file is loaded independently in a different process. In development mode, all the tests are loaded at once and the state is never reset between test files. This is a recipe for disaster. Our team had many instances where everything passed on the CI, but running it locally would not work.

Needless to say, it is frustrating for us as users and goes against the promise of Cypress of providing a deterministic test environment.

### Steps to reproduce: (app code and test code)

Github repo: https://github.com/yagudaev/cypress-flakey-server-state

### Versions

3.6.1

### Related

https://github.com/cypress-io/cypress/issues/1773

**Comment by jennifer-shehane** [comment]
>Cypress should know about any pending requests that have not yet been resolved. Therefore it should NOT move on to the next test before all requests of the previous tests have been finished.

Cypress could know about pending requests, but we wouldn't know which pending requests you *care* about. This is the exact functionality of `cy.wait()` and why it is there. The example you showed to fix this is what we recommend. You should assert the exact requests you care about and assert agains their request and response. 

This also adds another layer of tests that we find valuable. You wouldn't get an indiscriminate test result like 'data-counter does not contain 1', you would get a more descriptive error if the bug was isolated to the request/server saying 'response.body does not contain 1' - making it one layer closer to where the issue is and one step faster in debugging.

Many projects I have seen have 100s of XHR requests go out in a single test, so us waiting for every pending request that is in route would slow down a lot of people's use cases. 

The case of changing state in one test while another is running (say while running in parallel) is something that should be handled in your test setup/teardown. If you know there is a possibility of data being touched while another test is running, you need to set up isolated instances of that data for testing.
