### ISSUE TITLE
Getting SecurityError

### ISSUE THREAD

**Issue by hemanthaSN** [cypress-io/cypress#5784]
Getting **SecurityError: Blocked a frame with origin “https://login.microsoftonline.com” from accessing a cross-origin frame.**
I am not able to launch the URL itself. it keeps on loading and giving security error.
And please find the attachment for the error.  Could you please let me know asap

**Comment by hemanthaSN** [comment]
![Screen Shot 2019-11-25 at 11 27 12 AM (1)](https://user-images.githubusercontent.com/3306428/69517434-bd06fd00-0f7a-11ea-8db5-f0795191a63b.png)

**Comment by jennifer-shehane** [comment]
Try setting `chromeWebSecurity: false`. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
