### ISSUE TITLE
Pass additional arguments to child process when loading plugin file

### ISSUE THREAD

**Issue by boyanio** [cypress-io/cypress#5802]
### Current behavior:

When writing a custom plugin and trying to debug it (e.g., from VSCode), we cannot do this, because the plugin is loaded with `fork` without initial Node.js arguments.

### Desired behavior:

The following Node.js arguments are passed to the child process:

- `--inspect-brk`
- `--inspect-port`
- `--inspect`
- `--require`

**Comment by flotwig** [comment]
Great idea!

In the meantime, have you tried running with `NODE_OPTIONS=--inspect-brk`?

**Comment by boyanio** [comment]
Good point, thanks, I will try it out!

**Comment by flotwig** [comment]
@brian-mann and I discussed this a little bit, with the goal of getting an argument that is capable of selecting the plugin, the CLI, the Electron app, or all processes for debugging.

Here's kinda what we came up with:

* `cypress open --inspect-brk` - inspect the plugins process
* `cypress open --inspect-brk=1234` - inspect the plugins process on port 1234
* `cypress open --inspect-processes=cli,main,plugin --inspect-brk=1234` - inspect all 3 processes, on port 1234, 1235, 1236, respectively - since this is the order they are launched
* `cypress open --inspect-processes=main` - inspect just main Electron app

`--inspect` , `--inspect-port`, and `--require` will also be passable in this way.

Open to thoughts on this design.

**Comment by boyanio** [comment]
I personally like the proposition (y)

**Comment by brian-mann** [comment]
`--inspect-process` is a little less verbose than `--inspect-processes`, and since the default will only be `plugins` it kind of acts as a power feature to pass a comma separated list of the others

**Comment by jennifer-shehane** [comment]
Since this has not had a lot of interest over the years, we’ll close this as not planned.
