### ISSUE TITLE
cy.click() doesn’t select element in custom dropdown component

### ISSUE THREAD

**Issue by Sharan-ram** [cypress-io/cypress#5805]
### Current behavior:
With the update to 3.5.0, Cypress doesnt seem to select the right MenuItem from the Material ui Popper. The cy.click() is applied to the right element but the actual element clicked is wrong. I have made a sample demo app reproducing the issue and a screenshot has been attached below:

![Screenshot from 2019-11-27 18-57-04](https://user-images.githubusercontent.com/18206489/69727983-90eda680-1149-11ea-8dbf-fbbfaf9e01cd.png)

### Desired Behaviour:
cy.click() should be applied to the right element

### Steps to reproduce:
[Here is a sample repo](https://github.com/Sharan-ram/cypress-bug-demo) which reproduces the issue. Run npm run cypress:open, select app.test.js file, you can see on the console that applied to is different from actual element clicked.

### Versions
Cypress 3.5.0, reproducible even in v3.6.1
Browser Chrome

**Comment by sepehr500** [comment]
I have the same issue.

**Comment by jennifer-shehane** [comment]
The actual assertion should be checking the `value`, as this will fail whether the component selects properly or not, so change your last assertion to: 

```js
cy.get("[name=foods]").should("have.value", "Beef");
```

Regardless, this is a regression that was introduced in 3.5.0 and has not been fixed as of 3.8.1. 

## Repro

Run this repo: https://github.com/Sharan-ram/cypress-bug-demo and change last assertion to 

```js
cy.get("[name=foods]").should("have.value", "Beef");
```

## 3.4.1

<img width="921" alt="Screen Shot 2020-01-02 at 2 49 06 PM" src="https://user-images.githubusercontent.com/1271364/71657616-0e22c180-2d6f-11ea-9bfb-f1ee3f6b6155.png">

## 3.5.0

![](http://g.recordit.co/BIjV9zF2zT.gif)

# Workaround

Downgrade to 3.4.1 of Cypress.

**Comment by vramana** [comment]
@jennifer-shehane I did some digging into this issue yesterday.  

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/actions/click.js#L157

`mousemove` event on the targetElement causes it to recompute it's position and it looks something like this.

![img](https://cdn.discordapp.com/attachments/453514326058336257/661871446435561492/unknown.png) So for the rest of the command the popover just stays towards the left we click on html element.

**Comment by jennifer-shehane** [comment]
Ran across this other issue with material-ui today, thought I would comment in case it sheds some light. https://github.com/cypress-io/cypress/issues/5826#issuecomment-560035193

**Comment by stevenvachon** [comment]
Even with a `should('contain', 'text')`, it doesn't throw, so it must have the correct element selected, but continues to click the wrong one. What's worse is that it alternates; the first run through, it works as expected while the second has this issue. The results continue to alernately repeat through the third, fourth, etc runs.

**Comment by jennifer-shehane** [comment]
This issue still exists in Cypress 4.10.0.

**Comment by sainthkh** [comment]
I confirmed that the behavior @vramana said is true. 'mousemove' event does move autocomplete window to the left.

This behavior didn't happen before 3.5.0 because `mousemove` event wasn't supported. (It's added with #3030.)

When you comment out the line below:

https://github.com/cypress-io/cypress/blob/497745037fb0b80601f7f937d04b3aa61ecb620b/packages/driver/src/cy/mouse.js#L362

The test works correctly.

And the 'mousemove' event is sent at:

https://github.com/cypress-io/cypress/blob/497745037fb0b80601f7f937d04b3aa61ecb620b/packages/driver/src/cy/mouse.js#L726


----

This 'mousemove' event changes the style of popper. It removes the transform:

**Before mousemove:**

![Screenshot from 2020-08-03 11-28-48](https://user-images.githubusercontent.com/8130013/89141109-8f993700-d57e-11ea-92eb-a03f79689a17.png)


**After mousemove:**

![Screenshot from 2020-08-03 11-30-00](https://user-images.githubusercontent.com/8130013/89141113-92942780-d57e-11ea-9e63-45d51131d1ca.png)

**Comment by sainthkh** [comment]
I found the cause. It's because of the click event simulation.

In native settings, the code flow after clicking menu is like this: 

```
destroy
Popper constructor
update() with isDestroyed false
pointerdown event
mousedown event
update() with isDestroyed false
pointerup event
mouseup event
click event
destroy
update() with isDestroyed true => update is ignored
```

In Cypress settings, the code flow is like this:

```
destroy
Popper constructor
pointerdown event
mousedown event
pointerup event
mouseup event
click event
destroy
update() with isDestroyed true => update is ignored
```

As you can see, update() is not called. That's why the element is not relocated below the text field. 

Although we know what the problem is, the solution is a bit hard. We need to give time for browsers to execute event handlers after an event is fired. To do so, we might need to restructure `actionability`.

**Comment by binary-koan** [comment]
In case this helps anyone else, my workaround for Material UI Autocomplete is to use keyboard controls to select the item. For example, to select the first item:

```js
cy.get('.my-material-autocomplete input').type('{downarrow}{enter}')
```

**Comment by ashetty-womply** [comment]
@binary-koan 's solution worked for me. 
I have an autocomplete field for state. I clear it and type

`cy.get("#state").clear().type('New {downarrow}{downarrow}{enter}');
`

**Comment by wanderleydrumond** [comment]
I also have the same issue with version 8.2.0.

**Comment by GarrisonD** [comment]
Also for Cypress 10.3.1

**Comment by GarrisonD** [comment]
Passing `force: true` to `.click()` solves the issue.

According to the docs the `force` option controls waiting for actionability.
Why doesn't Cypress throw an error about an un-actionable element then?

**Comment by thanh90** [comment]
> Passing `force: true` to `.click()` solves the issue.
> 
> According to the docs the `force` option controls waiting for actionability. Why doesn't Cypress throw an error about an un-actionable element then?

this works with my popper
