### ISSUE TITLE
Cypress 3.6.1 asks for at least Chrome 64 while Chrome 65 is detected

### ISSUE THREAD

**Issue by mariotsi** [cypress-io/cypress#5817]
### Current behavior:

```
 (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.6.1                                                                              │
  │ Browser:    Chrome 65                                                                          │
  │ Specs:      7 found (*****)              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  00_generic_spec.js                                                              (1 of 7)
Cypress requires at least Chrome 64.

Details:
A minimum CDP version of v1.3 is required, but the current browser has v1.2.
Error: Cypress requires at least Chrome 64.

Details:
A minimum CDP version of v1.3 is required, but the current browser has v1.2.
    at /tmp/CypressBinaries/3.6.1/Cypress/resources/app/packages/server/lib/browsers/chrome.js:225:23
```

### Desired behavior:

Chrome 65 is accepted.

### Steps to reproduce: (app code and test code)
Run any test with cypress 3.6.1 vs Chrome bundled in this tag of [cypress/browser](https://hub.docker.com/layers/cypress/browsers/chrome65-ff57/images/sha256-96995f2ad79e76018f9da614d7c29c401cea847df8d516970305aefbdd4f2090) docker image

### Versions

Cypress 3.6.1
Chrome 65

**Comment by brian-themaven** [comment]
Any updates on this?

**Comment by Benyamin-Rafaeli** [comment]
Hi, Someone can publish the fix or workaround please ?
Cypress 4.12.1
A minimum CDP version of v1.3 is required, but the current browser has v1.2.

**Comment by jennifer-shehane** [comment]
I'm seeking clarification on this. I apologize because this is not documented and if we are not supporting Chrome prior to 64 then our docker image should also not be made available as if it is working. 

This error is being thrown from here in the code: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/browsers/chrome.ts#L461:L461

I'm not sure why this would be throwing for Chrome 65 or how we determined that the v1.3 CDP version matched up to Chrome 64. 

You'll likely need to update the Chrome browser you are using to get around this though. This is a very old Chrome version, any reason you need to be testing on it?

**Comment by Benyamin-Rafaeli** [comment]
yes you're absolutely right, need to update docker image

**Comment by mariotsi** [comment]
Update and it worked. Was using it as a legacy setup we inherited. Thansk.
