### ISSUE TITLE
While loading Oracle db within Cypress, getting error - NJS-069: node-oracledb 4.1.0 requires Node.js 8.16 or later (x64)

### ISSUE THREAD

**Issue by petermartin2002** [cypress-io/cypress#5818]
**Current behaviour:**
I am trying to connect to and query an oracledb using: 
```js
const oracledb = require('oracledb');
const dbConfig = require('./dbconfig.ts');

export class DbConnection {

  constructor() {
    try {
      // Create a connection pool which will later be accessed via the
      // pool cache as the 'default' pool.
    oracledb.createPool({
        user: dbConfig.user,
        password: dbConfig.password,
        connectString: dbConfig.connectString
        
      });
      console.log('Connection pool started');
    } catch (err) {
      console.error('init() error: ' + err.message);
    }
  }
  

    public static async dostuff(sql :string) : Promise < any[] > {
    let connection;
    let result
    try {
      // Get a connection from the default pool
      connection = await oracledb.getConnection();
      result = await connection.execute(sql);
      console.log(result);
    } catch (err) {
      console.error(err);
    } finally {
      if (connection) {
        try {
          // Put the connection back in the pool
          await connection.close();
        } catch (err) {
          console.error(err);
        }
      }
    }
    return result
  }
}

```
Which I then call from my test spec like:
```js
import { SetupTest } from '../utils/setup';
import { DbConnection } from '../utils/DbConnection';

describe('DB Test', function() {

    SetupTest();

    it('Connect and query', async ()=> {


      await DbConnection.dostuff('SELECT COUNT(ID) FROM <table> WHERE ID = <id number>');
      })
    })
```
I get the following error returned:

> Uncaught Error: NJS-069: node-oracledb 4.1.0 requires Node.js 8.16 or later

![image](https://user-images.githubusercontent.com/13946993/69824865-108c7b80-1205-11ea-9e2f-6b6f6feaf9cc.png)

**Desired behaviour:**
I would like to load the oracle db using node processor (nodejs)

Steps to reproduce: (app code and test code)
Complete all the prerequisite as per https://oracle.github.io/node-oracledb/INSTALL.html#prerequisites
a) Install Python 2.7.14
b) Install Visual Studio 2019
c) Download Oracle Instant Client on local machine & give that to PATH
Install oracledb on node using 
- npm install github:oracle/node-oracledb#v4.1.0
and also tried
- npm install oracledb

**Versions**
    "cypress": "^3.7.0",
    "cypress":"^3.6.1",
    "nodeVersion": "system"
nodejs - v8.16.2
nodejs - v12.13.1
nodejs - v9.11.2

Os - Windows 7 or Windows 8.1
oracledb - "github:oracle/node-oracledb#v3.0.1",

**Comment by jennifer-shehane** [comment]
Hey @petejohansonxo, the test files (anything defined within the `cypress/integration` directory) will execute within the context of the browser, so this error is displaying because this code is not being run within Node at all. 

Code placed within the `cypress/integration/support` files will be run within the context of Node. Cypress ships with Node.js 12.0.0 version by default, so should be sufficient for your needs (so you should not need to set the `nodeVersion: "system"` unless you wanted something explicitly different from Node.js 12.0.0).

I would suggest moving the `DbConnection.dostuff('SELECT COUNT(ID) FROM <table> WHERE ID = <id number>');` code to be within a file within `cypress/integration/support`, like placing it within a [custom command](https://on.cypress.io/custom-commands). Then you can call this custom command from within your test file. 

For future questions relating to how to use Cypress ask in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by bahunov** [comment]
@petermartin2002 did it work for you? I'm trying to do the same but not working..

**Comment by imarchuang** [comment]
it didn't work for me either

**Comment by ice1080** [comment]
I'm also seeing this not working @jennifer-shehane. I've tried with oracledb v5.1.0 and v4.1.0.
Also the problem is coming from code that is not in the cypress directory. I'm trying to test files at the top level using cypress, and the cypress directory is next to that. So it's not like I can move my code into cypress/integration/support. Anybody have suggestions?

**Comment by Shnrqpdr** [comment]
I'm trying to do the same stuff but not working either. Looks like even in recent versions these errors appears

**Comment by Shnrqpdr** [comment]
@imarchuang did you find a solution?

**Comment by sharadraju** [comment]
@Shnrqpdr @imarchuang Not sure how late I am to the party, but you can find a potential solution [here](https://github.com/oracle/node-oracledb/issues/1261#issuecomment-1693310818)
