### ISSUE TITLE
Spec reporter still outputs results with any other reporter configured

### ISSUE THREAD

**Issue by seyfer** [cypress-io/cypress#5833]
### Current behavior:

I have even more weird issue but I think might be connected with this one https://github.com/cypress-io/cypress/issues/5083.

I have cypress installed globally. Then I want to use mocha `dot` or `nyan` reporter.

So I set a reporter in the config.

And then I have mixed output from default `spec` reporter with the reporter I have set-up.

For some reason `spec `still outputs and my specified reporter adds **dots** or **cats** in between.

```
Running:  backend/settings/my.spec.js                   (4 of 5)


  ․․

  2 passing (11s)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     11 seconds                                                                       │
  │ Spec Ran:     backend/settings/my.spec.js                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

```

### Desired behavior:

Only reporter specified in `reporter` config option outputs to console. I should see only dots in case of dot reporter specified.

```
..
```

### Steps to reproduce: (app code and test code)

Set
`"reporter": "dot"`
or
`"reporter": "nyan"`

in cypress.json. do `cypress run`, see the mixed output.

### Versions

Latest Cypress (3.7.0), latest Chrome from deb repositories, Debian.

**Comment by jennifer-shehane** [comment]
@seyfer This is the expected behavior or cypress. The portion printed from mocha is the portion that will use the specified mocha reporter. I've pasted an example for the 'nyan' reporter below. Before the mocha specs - Cypress will print a description of the upcoming run and after it will print the Cypress test results as well as any asset processing and finally a summary of the test run. 

This is not the same as https://github.com/cypress-io/cypress/issues/5083 since the reporter is being displayed and is not throwing an error.

![Screen Shot 2019-12-03 at 3 09 52 PM](https://user-images.githubusercontent.com/1271364/70034169-2623eb80-15df-11ea-921c-84c8047c65f8.png)

**Comment by seyfer** [comment]
@jennifer-shehane but how the default output can be disabled? 
I want to see only my custom or mocha reporter output.
