### ISSUE TITLE
Improve unzip time on Windows

### ISSUE THREAD

**Issue by flotwig** [cypress-io/cypress#5861]
### Current behavior:

Windows uses a Node.js-based method to unzip the Cypress binary during `cypress install`, which is fairly slow.

### Desired behavior:

Windows uses some faster method, like the native win32 zip APIs, to unzip the Cypress binary during `cypress install`, only falling back to the Node.js unzip method if the faster method fails.

Related:
- #5851

**Comment by flotwig** [comment]
The approach used in #5851 may work for Windows as well, since I believe that CircleCI and AppVeyor both install `unzip`.

**Comment by devsh4** [comment]
@flotwig Unzipping cypress takes about 5-6 minutes on a windows machine (Windows Server 2019 with Visual Studio 2019) on Azure DevOps.

![image](https://user-images.githubusercontent.com/23476848/77682765-d42c1a80-6f6d-11ea-895b-5a7e7948cf3c.png)

**Comment by flotwig** [comment]
@devsh4 indeed, it would be nice to have a native unzipping method on Windows to help speed it up. Node unzipping is too slow.

**Comment by devsh4** [comment]
@flotwig Yeah +1, in the interim caching the cypress binary should speed things up.

**Comment by kapil-sinha** [comment]
this issue is still there. no caching helps - node modules are cached ($(Pipeline.Workspace)\s\e2e\node_modules), cypress binaries are cached from the cypress cache folder (C:\Users\VssAdministrator\AppData\Local\Cypress\Cache). But npm ci still tries to install cypress which is nothing but cypress for me and it takes long - 
25l[19:57:59]  Downloading Cypress     [started]
[19:58:02]  Downloading Cypress     [completed]
[19:58:02]  Unzipping Cypress       [started]
[20:02:27]  Unzipping Cypress       [completed]
[20:02:27]  Finishing Installation  [started]
[20:02:27]  Finishing Installation  [completed]
25h 

Is there another faster way to install cypress on my build agent (.NET fwk app on windows and azuredevops for CI) and run tests?
