### ISSUE TITLE
Use cypress on application bigger that 4000px wide

### ISSUE THREAD

**Issue by digiink** [cypress-io/cypress#5871]
### Current behavior:
I have a application which is displayed across multiple screens which is bigger that the max screen size of 400px wide

```js
cy.viewport(7680, 1601);
```

```
Error:
CypressError: cy.viewport() width and height must be between 20px and 4000px.
```

### Desired behavior:

The max `cy.viewport()` width  and height increased to `8000px`. 

### Steps to reproduce: (app code and test code)

```js
cy.viewport(7680, 1601);
```

https://github.com/digiink/cypress-test-tiny

### Versions

Cypress package version: 3.6.1
Cypress binary version: 3.6.1
Mac OS 10.14
Chrome 78

**Comment by jennifer-shehane** [comment]
Here is the previous PR that upped the max value: https://github.com/cypress-io/cypress/pull/5189

**Comment by gabbersepp** [comment]
Is there a valid reason for the limits?

**Comment by digiink** [comment]
No valid reason, I feel that the max should be set in the config with a default lower limit set in the code but this is outside my ability in this codebase at the moment.

**Comment by flotwig** [comment]
> Is there a valid reason for the limits?

I think the *intention* is to prevent users from accidentally setting something unreasonably huge and crashing/freezing the browser. I do not think there is a practical reason outside of that.

Instead of adding more config options, I'm in favor of just removing the limitation. In the year 2022, people are probably gonna be using Cypress with 16k res screens, so I think we should just save the time now and remove the restriction, or set it to something that is clearly infeasible (like 100k or 1 million).

**Comment by flotwig** [comment]
As a workaround, you can suppress this error by using [`cy.stub`](https://on.cypress.io/stub) to stub out the Cypress error function.

Add the following to your specs or to your support file:

```js
beforeEach(() => {
  cy.stub(Cypress.utils, "throwErrByPath")
  .callThrough() // still throw other types of errors
  .withArgs("viewport.dimensions_out_of_range").returns() // suppress invalid value errors
})
```

**Comment by flotwig** [comment]
Created an issue to remove/vastly increase the limits: https://github.com/cypress-io/cypress/issues/5892
