### ISSUE TITLE
the class is visible but error for click

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#5873]
### Current behavior:
CypressError: Timed out retrying: cy.click() failed because this element is not visible:

<a class="sc-dnqmqq dTBffB sc-htpNat gTEYvI" data-spm-click="gostr=/aliyun;locaid=denterprise-0" href="//resourcemanager.console.aliyun.com/resource-groups" target="_blank">资源管理</a>

This element '<a.sc-dnqmqq.dTBffB.sc-htpNat.gTEYvI>' is not visible because its parent '<li>' has CSS property: 'visibility: hidden'

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example that we can run locally and we will reopen the issue. 🙏
