### ISSUE TITLE
How can I route the request based on the POST parameter?

### ISSUE THREAD

**Issue by pmbaldha** [cypress-io/cypress#5880]
In WordPress, All Ajax requests go to the URL wp.com/wp-admin/admin-ajax.php. Each AJAX request differentiates by the action named POST param.

I would like to give a different route name based on this POST param's value. How can I do it?

Thank you

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
