### ISSUE TITLE
Cypress getting into infinite XHR when the API call is made in web components.

### ISSUE THREAD

**Issue by PrashanthSuriyanarayanan** [cypress-io/cypress#5898]
- Operating System: Windows 10
- Cypress Version: 3.7.1
- Browser Version: Chrome 78, Canary 80, Electron 59

### Is this a Feature or Bug?
A bug

### Current behavior:
cypress open

I have a web component in a page where an api call is triggered to get some data on init.  When I load a page through cypress the api calls are called infinitely. I assume the webcomponent is being rendered more than one time.

Reproducible in all browser.

### Desired behavior:
Should not trigger infinite xhr calls when called from web component.

### Steps to reproduce: (app code and test code)
1. create a web component and have an api call on load.
2. use the component in a page.
3. load the page through cypress open.

There is already a open [bug 1068](https://github.com/cypress-io/cypress/issues/1068), but my case is different than that.

**Comment by pvijayamirtharaj** [comment]
Please resolve this issue ASAP. I too facing this kind of the same issue. Please treat this as an Urgent priority.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a **fully reproducible example** - including app code and test code and we will consider reopening the issue.
