### ISSUE TITLE
cy.route does not always work

### ISSUE THREAD

**Issue by GavinPalmer1984** [cypress-io/cypress#5900]
## Current behavior: 
The following test fails.  I uncomment the second test and it passes.

```js
/// <reference types="Cypress" />
$ = require('jquery');
describe('Route Testing', () => {
	before(() => {
		cy.server({ force404: true });
		cy.route('api/test\\?*', { status: 'ok' });
	});
	const url = 'api/test?123';
	var promise = new Promise(function(resolve, reject) {
		$.get(url, (response) => {
			resolve(response);
		});
	});
	it(`should handle this`, () => {
		promise.then((data) => {
			expect(data.status).to.eq('ok');
		});
	});
	// it(`should handle this too`, () => {
	// 	promise.then((data) => {
	// 		expect(data.status).to.eq('ok');
	// 	});
	// });
});
```

### Desired behavior:
I desire the test to pass because I am stubbing most of my endpoints.

### Steps to reproduce: (app code and test code)
Try to run the test above.  Uncomment the commented test and see that it will then pass.  Magic...

### Versions
3.7.0

**Comment by dwelle** [comment]
In your case, the test(s) pass irrespective if you issue just one, or two. It's the nested assertion that fails.

There are several things you're doing wrong.

1. `cy.route` is for instrumenting your app's XHR requests. You, on the other hand, are making the request from your test code, not from your app. Thus, it'll not be intercepted and handled by Cypress.
    
2. You can't make assertions in asynchronous callbacks that are not part of the Cypress command queue. By the time you're making the assertion in your example, Cypress has already finished the test. That's why the test isn't failing, just the assertion --- it being reported as failing in the Command log doesn't necessarily mean it's part of the test.
    
Instead, you'll want to do something like:

```js
cy.server();
cy.route('api/test?*', { status: 'ok' }).as('test');

// instead of the following (which is shown only for demonstration purposes),
//  make some action that will make your app issue the request
cy.window().then( win => {
    const xhr = new win.XMLHttpRequest();
    xhr.open('GET', '/api/test?2');
    xhr.send();
});

cy.wait('@test').its('response.body.status').should('eq', 'ok');
```

Btw, next time, you should ask this on StackOverflow or on https://gitter.im/cypress-io/cypress

**Comment by jennifer-shehane** [comment]
Closing as resolved. See @dwelle comment https://github.com/cypress-io/cypress/issues/5900#issuecomment-562849827

**Comment by GavinPalmer1984** [comment]
Thank you for your response @jennifer-shehane - I am going to try and post a better example.

The example above was my attempt to reduce the real app down and be helpful - so much for that.  I will try again :)

It turns out that the reason my "real" test is failing is because my request has something like `since=11/12/2018` in the GET query params and my cypress route logic is probably doing something strange because of the forward slashes in the date (maybe decoding the url prematurely).

I have a route like:
cy.route('api/account/*/generate_csv\\?*', { status: 'cool' }).as('coolTest');

And my app is hitting an endpoint like api/account/1/generate_csv?since=11/12/2018 and cypress isn't matching them correctly.

test app:
```
<script>
	const xhr = new XMLHttpRequest();
	const url = '/api/account/1/generate_csv?' + encodeURIComponent('good=11/19');
	console.log(url);
	xhr.open('GET', url);
	xhr.send();
</script>
```

and the test:
```
/// <reference types="Cypress" />
$ = require('jquery');
describe('Route Testing', () => {
	before(() => {
		cy.server({ force404: true });
		cy.route('api/account/*/generate_csv\\?*', { status: 'cool' }).as('coolTest');
	});
	it(`should handle this`, () => {
		cy.visit('tests/gavin.html');
		cy.wait('@coolTest').its('response.body.status').should('eq', 'cool');
	});

});
```

**Comment by jennifer-shehane** [comment]
@GavinPalmer1984 Please experiment with our `minimatch` utility to ensure the glob you are writing is correctly matching the url you specify. https://on.cypress.io/minimatch#Examples

**Comment by GavinPalmer1984** [comment]
@jennifer-shehane - here is my experiment with minimatch.

![Screen Shot 2020-01-07 at 1 15 05 PM](https://user-images.githubusercontent.com/5564129/71922031-be1d7380-314f-11ea-94c0-b581b6998f63.png)

**Comment by jennifer-shehane** [comment]
@GavinPalmer1984 The glob does not match for many of the urls you are expecting, so you will need to write a better glob to match. We cannot spend time writing a correct glob for your project.

**Comment by GavinPalmer1984** [comment]
For those who may end up here looking for an answer - glob may not always work for your pattern and you will need to use a RegExp instead.

```
/// <reference types="Cypress" />
$ = require('jquery');
describe('Route Testing', () => {
	before(() => {
		cy.server({ force404: true });
		// cy.route('api/account/*/generate_csv\\?*', { status: 'cool' }).as('coolTest');
		cy.route(/((api\/account\/).(\/generate_csv\?).*)/, { status: 'cool' }).as('coolTest');
	});
	it(`should handle this`, () => {
		cy.visit('tests/gavin.html');
		cy.wait('@coolTest').its('response.body.status').should('eq', 'cool');
	});

});
```

**Comment by SnehithaN** [comment]
@jennifer-shehane , @dwelle , All,
Can anyone help me with the below issue?

I am using cypress for testing my API of type multipart/form-data. Since cypress doesn't support multipart/form-data I am using XMHTTPRequest to achieve it.  My scenario is I need to upload a JSON file using POST method. Below is the code I use and I am getting back 200 for status code and { success: false } in response which means something is wrong with the payload. The same endpoint is working in postman and all other API tools. I expect something is not working when it is encoding to blob format. Can anyone help me with the this issue?

describe("upload a file", () => {
    it("XHR Way", () => {
      function form_request(method, url, formData, done) {
        
        const xhr = new XMLHttpRequest();
        
        xhr.open(method, url);
     
    
        xhr.onload = function() {
            done(xhr);
        };

        xhr.onerror = function() {
        done(xhr);
        };
        xhr.send(formData);
      }
      const fileName = "report.cucumber.json";
      const method = "POST";
      const url = "Endpoint\URL";
      
      cy.fixture(fileName, "binary")
      .then((txtBin) => Cypress.Blob.binaryStringToBlob(txtBin))
      .then((blob) => {
          const formData = new FormData();
          formData.append("file", blob, fileName);
          
          form_request(method, url, formData, function(response) {
                        expect(response.status).to.eq(200);
              expect(JSON.parse(response.response).success).to.eq(true);
          });

      });

    })
})
