### ISSUE TITLE
 To get the background color code of a selected element

### ISSUE THREAD

**Issue by shamilyn** [cypress-io/cypress#5924]
I need to get the background color code of a selected element and to bind that color code to another element

**Comment by nwiatrek** [comment]
would something like this work for you?
```
it('Assigning css color', () => {
        cy.visit('/');
        cy.get('.App-header')
            .invoke('css', 'background-color')
            .then(background => {
                cy.get('[data-cy=new-element]')
                    .invoke('attr', 'style', `background-color: ${background}`)
                    .then(new_element => {
                        expect(new_element).to.have.css('background-color', background);
                    });
            });
    });
```
In this test i get the background color of an element with class name `App-header`, get the background color of it and then set a different div background color with it.

Here is the div with the color that will be changed:
```
<div data-cy='new-element' style={{ backgroundColor: 'red' }}>
    is red
</div>
```
which renders as this:
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/31594144/70588954-fa32d800-1b93-11ea-8c5f-aa220ac54d3c.png">

After the code above (binding) it comes out as this in cypress
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/31594144/70588935-eedfac80-1b93-11ea-9ac0-92e19a6d6fb1.png">

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
