### ISSUE TITLE
Feature Request: Save an artefact in Cypress Dashboard that would allow time-travel / replaying on localhost

### ISSUE THREAD

**Issue by voboshi** [cypress-io/cypress#5925]
### Current behavior:

If the application under test doesn't surface errors properly, recordings / screenshots from the Cypress Dashboard are not enough to debug.

### Desired behavior:

When running in CI and recording to the Dashboard service, upon completion dump some kind of artefact that users could fetch on their local to time travel through steps and inspect the DOM / network calls.

### Steps to reproduce: (app code and test code)

Not applicable.

### Versions

Cypress: 3.7.0

**Comment by samtsai** [comment]
This would be amazing and I'm wondering if anyone has been able to make any progress on this or have any thoughts on approaches.

**Comment by jennifer-shehane** [comment]
You can express interest for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. Any subsequent work required by the Test Runner team will be opened when that feature is decided for work. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.
