### ISSUE TITLE
Adding assertion that the subject is a very large array hangs the test runner

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#5929]
Cypress v3.7.0 on Windows
Reproduction https://github.com/cypress-io/cypress-test-tiny/tree/test-wrap-large-array

This test passes after about a second

```js
it('works', () => {
  const arr = new Uint8ClampedArray(2560000)
  cy.wrap(arr)
})
```

<img width="1280" alt="Screen Shot 2019-12-10 at 5 15 50 PM" src="https://user-images.githubusercontent.com/2212006/70573944-ef1a8080-1b70-11ea-8aa0-72f8cff1ba7b.png">

but if we add any assertion like

```js
it('works', () => {
  const arr = new Uint8ClampedArray(2560000)
  cy.wrap(arr)
    .should('have.length', 2)
})
```
then the Test Runner starts hanging. Breaking the debugger to see what is going on shows the Chai assertion trying to format the values in the array

<img width="1280" alt="Screen Shot 2019-12-10 at 5 13 58 PM" src="https://user-images.githubusercontent.com/2212006/70574023-15d8b700-1b71-11ea-8134-992a87915c02.png">

<img width="1280" alt="Screen Shot 2019-12-10 at 5 14 13 PM" src="https://user-images.githubusercontent.com/2212006/70574031-1a9d6b00-1b71-11ea-9fcc-09de1709762d.png">

Our code in the stack
<img width="1282" alt="Screen Shot 2019-12-10 at 5 14 55 PM" src="https://user-images.githubusercontent.com/2212006/70574053-24bf6980-1b71-11ea-93ec-f1bd85e23dbd.png">

This showed up in the user's project https://github.com/ericblade/quagga2-reader-qr/blob/8e1665bda9832fb31e32f4eb8eea2364c5d1c37d/e2e/cypress/integration/test_spec.ts#L50

Expected: not freezing and maybe formatting the value differently.

**Comment by avallete** [comment]
Interesting issue here,

I've looking into that bug, and I think I've nailed down the root cause of it.

At first glance, I've suspected that it has to do with logging of Cypress, since the issue wasn't seem to be related to memory usage (very large array memory allocation without assertion work without error) and that the simple test with a 'little' array of `new Uint8ClampedArray(1000)`  was already producing a huge amount of logs.

To test this hypothesis I've started by reducing the size of the Array to tests multiples larges array scenarios, and find what was causing the increase of execution time, so, here is the tests I wrote based on OP example. I split theses tests into two sections, first one will tests a valid assertion on the array (which produce less output), the second one will tests an invalid assertion on the large array (like in the OP issue):

Here the code I used:
```js
describe('issue #5929 with valid assertions', () => {
  it('test memory allocation of very large array', () => {
    const arr = new Uint8ClampedArray(2560000);
    cy.wrap(arr);
  })
  it('test 5000', () => {
    const arr = new Uint8ClampedArray(5000);
    cy.wrap(arr)
      .should('have.length', 5000);
  })
  it('test 10000', () => {
    const arr = new Uint8ClampedArray(10000);
    cy.wrap(arr)
      .should('have.length', 10000);
  })
  it('test 25000', () => {
    const arr = new Uint8ClampedArray(25000);
    cy.wrap(arr)
      .should('have.length', 25000);
  })
  it('test 50000', () => {
    const arr = new Uint8ClampedArray(50000);
    cy.wrap(arr)
      .should('have.length', 50000);
  })
});

describe('issue #5929 with invalid assertions', () => {
  it('test memory allocation of very large array', () => {
    const arr = new Uint8ClampedArray(2560000);
    cy.wrap(arr);
  })
  it('test 5000', () => {
    const arr = new Uint8ClampedArray(5000);
    cy.wrap(arr)
      .should('have.length', 5000 - 1);
  })
  it('test 10000', () => {
    const arr = new Uint8ClampedArray(10000);
    cy.wrap(arr)
      .should('have.length', 10000 - 1);
  })
  it('test 25000', () => {
    const arr = new Uint8ClampedArray(25000);
    cy.wrap(arr)
      .should('have.length', 25000 - 1);
  })
  it('test 50000', () => {
    const arr = new Uint8ClampedArray(50000);
    cy.wrap(arr)
      .should('have.length', 50000 - 1);
  })
});
```

The results was pretty clear:

|                           | Time to execute |
|---------------------------|-----------------|
| Assertion result is True  | ~19.25 sec      |
| Assertion result is False | ~57 sec         |


My insight started to confirm, but to be sure it was really related to the way cypress log content, I've done a little experiment with cypress code by changing the logging style. Since I didn't know where the log was exactly done, I did it the brutal way replacing every log messages matching: `expected '${node} .*` or `expected #{this} .*` by `expected  .*`.

The result, was as I expected, without the logging of the "stringified" object of my assertion, I ran the same tests:

|                           | Time to execute                                                     |
|---------------------------|---------------------------------------------------------------------|
| Assertion result is True  | ~0.83 sec                                                           |
| Assertion result is False | ~17.4 sec (mainly due to retry time before cypress command timeout) |

My fix isn't really one doe, since I'm only dogging the issue the brutal way.

I would propose to handle the logging of larges values into assertions results the same way we it is done by the `cy.wrap` command (ex: `Object{5000}`).

PS: The issue also occurs with `cypress run command on cli`.
