### ISSUE TITLE
"Tests" button fails to take user back to specs list

### ISSUE THREAD

**Issue by wojciech-sygier** [cypress-io/cypress#5948]
### Current behavior:

Clicking "< Tests" button does nothing, only plays animation showing that the button was clicked.

### Desired behavior:

User is taken back to the tests/specs list in the Cypress UI.

### Steps to reproduce: (app code and test code)

App and test code not included, you can test it with basically anything you want.
1. Start Cypress.
2. Run any spec.
3. Stop the test's execution.
4. Click "< Tests" button".

### Additional information

 Console doesn't seem to be returning any error or anything. Typical regression for me.

### Media

https://streamable.com/ocfhs

### Versions

Introduced in Cypress 3.8.0. I'm using macOS Catalina 10.15.1. Worked fine on Cypress 3.7.0.

**Comment by jennifer-shehane** [comment]
@ThisIsJesus I have confirmed the `< Tests` button does not bring the 'tests' window into focus in 3.8.0 when run in Chrome 78 (which is weird, I thought for sure it would be in Electron). This does work in 3.7.0. 

## 3.7.0 Chrome 

![](http://g.recordit.co/1stH2J2Cg9.gif)

## 3.8.0 Chrome

![](http://g.recordit.co/fUyUD1J5Iv.gif)

**Comment by ThisIsJesus** [comment]
@jennifer-shehane Ah shoot, I completely forgot to mention what browser I was using. Silly me. :( Well then, Chrome 79 is also affected (this is the one I am using), can't really say how it looks on older versions though.

**Comment by oleksiydubovykTR** [comment]
Same in Firefox 75

**Comment by jennifer-shehane** [comment]
I traced through the code to find that clicking on the button eventually goes to call `win.focus()` of the Browser Window. 

https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/modes/interactive.js#L105:L105

I think this is likely due to the Electron upgrade that was done in 3.8.0, but would have to dig deeper on why us calling the focus on the Electron Desktop-GUI window is not focusing the window. https://github.com/cypress-io/cypress/pull/5849
