### ISSUE TITLE
What is the diff between these string matchers?

### ISSUE THREAD

**Issue by dialex** [cypress-io/cypress#5996]
What's the difference between:

- `.should("have.text", "expected text goes here")`
- `.should("include.text", "expected text goes here")`
- `.should("contains.text", "expected text goes here")`

Do they all accept text? Some accept regex? Are they literal or substring?
I was not able to find clear documentation about this (I searched on [Cypress](https://docs.cypress.io/guides/references/assertions.html#Chai-jQuery) and [Chai](https://www.chaijs.com/api/bdd/))

**Comment by ThisIsJesus** [comment]
Not exactly the place you should be asking these questions, but to keep it short and simple:
`"have.text" `- text is EXACTLY what you passed as an argument ("expected text goes here" in your example)
`"include.text"` and `"contains.text"` are both the same thing, but just aliases (`include`/`includes`/`contain`/`contains`) and they check if text from the element, well, contains what you passed as an argument.

Example:
You have a `<h3>` element that has `"I am an example"` text in it.
If you write `cy.get('h3).should('have.text', 'I am an example')` - it will pass
If you write `cy.get('h3).should('have.text', 'example')` - it will fail (`expected "I am an example" to have text "example"` or something similar)
If you write `cy.get('h3).should('include.text', 'I am an example')` - it will pass (though it doesn't check it the same way `"have.text"` does)
If you write `cy.get('h3).should('contains.text', 'example')` - it will pass (because `"example"` is a part of that string).

Not sure if it answers your question but, as I said before, this isn't the right place to ask it.

**Comment by dialex** [comment]
Thanks a lot @ThisIsJesus , that's exactly what I was looking for 👌 
From my experiments, I also discovered that neither of these matchers accept a regex. For that we need to use `.should("match", regex)`

P.S: What would be the right place to ask a doubt like this? I would like to know for the next time :)

**Comment by ThisIsJesus** [comment]
I'd say their chat would be your best bet. This is what the suggest when you create an issue by the way. Here's the link: https://on.cypress.io/chat.

There is also StackOverflow. ;)

**Comment by avirajBoxture** [comment]
cy.get('h3').should('include.text', 'I am an example') -PASS
cy.get('h3').should('includes.text', 'I am an example') -PASS

what is the difference here....?

**Comment by ALapaque** [comment]
> cy.get('h3').should('include.text', 'I am an example') -PASS cy.get('h3').should('includes.text', 'I am an example') -PASS
> 
> what is the difference here....?

As the first answer from @wojciech-sygier  `include/includes/contain/contains` those are aliases so it's exactly the same behavior
