### ISSUE TITLE
Replace dep @types/blob-util (it's deprecated)

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6001]
### Current behavior:

We include `@types/blob-util` as a dep in the cli here: https://github.com/cypress-io/cypress/blob/v4.0-release/cli/package.json#L64:L64

As mentioned in this PR https://github.com/cypress-io/cypress/pull/5684#pullrequestreview-316174984, this dep has been deprecated since blob-util provides it's own types in their package as mentioned here: https://www.npmjs.com/package/%40types/blob-util

### Desired behavior:

Replace use of `@types/blob-util` to include the types correctly.

### Versions

3.8.0

**Comment by vanya829** [comment]
Hi. I'd like to work on this issue

**Comment by sainthkh** [comment]
After some research, I learned that updating `blob-util` is a breaking change. 

In `1.3.3`, the return type of `blob-util` functions are `Promise`. But from `2.0.0`, they're `Blob` object. That's why attempting to fix them in #5780 [failed](https://circleci.com/gh/cypress-io/cypress/232201?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). 

`1.3.0` of `blob-util` doesn't use TypeScript and [`@types/blob-util@1.3.3` is not deprecated](https://www.npmjs.com/package/@types/blob-util/v/1.3.3). 

For now, we should use `@types/blob-util@1.3.3` and update it to `2.0.2` and remove `@types/blob-util` at Cypress 4.0.
