### ISSUE TITLE
check if parentNode is null in all recursive functions

### ISSUE THREAD

**Issue by gabbersepp** [cypress-io/cypress#6002]
### Current behavior:

There are many recursive functions, that traverse up to the root html element to find a specific node. See the issue in #4373 and the fix in pr #5528 where two places were fixed.

According to the comment of @Bkucera  there are many other similar places, too, that have to be fixed.
He mentioned a few places where Cypress may potential have such problems, too. A first full text search revealed much more places that may be affected.

Would be nice if all those places use the same shared function to avoid duplicate code.

### Desired behavior:

N/A

### Steps to reproduce: (app code and test code)

For the original issue, see #4373 

### Versions

all versions

**Comment by JasonFairchild** [comment]
Does this happen because of how SF LWC uses a DOM Polyfill as described here? https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.testing_dom_api 

Particularly the part at the end. It seems that basically ALL lightning web components are abstracted into document-fragments on purpose. On a different note, what if a component you want to test is inside a document-fragment? Is there a way to use cypress to interact with the component? I doubt its impossible, but I wouldn't be surprised if involved making another library to first get inside of the fragment and then do cypress like commands to find the elements you want..?

**Comment by gabbersepp** [comment]
@JasonFairchild Thanks for the documentation. I will try to create a small example with the information provided. Hopefully without including a salesforce lib :-)

If you have a closed shadow root, you can not access it by calling `document.querySelector` and so on. This is disabled by design. I have not tested a app that makes use of DocFragment/ShadowDom, yet. So no experience here. But the company I am working for has one application that is injected into a host page by shadow dom. maybe I should start creating tests for it to to acquire new knowledge ;-P

**Comment by jennifer-shehane** [comment]
This is actually handled in https://github.com/cypress-io/cypress/pull/6708 which was released in [4.1.0](https://on.cypress.io/changelog#4-1-0)

Although I would still love better ways to test this in the future that replicates closer to what LWC is doing.
