### ISSUE TITLE
chore: switch to commander.js API

### ISSUE THREAD

**Issue by jamesgeorge007** [cypress-io/cypress#6005]
It seems that you guys aren't leveraging the API as provided by `commander.js` in order to get things done.

For instance

1. `commander.js` warns by default on firing in unknown options. 
https://github.com/cypress-io/cypress/blob/720bc470e9c7a42fff0d98d2b649ef11ee338239/cli/lib/cli.js#L13
I can see a manual implementation here which is kinda weird IMO.

2. Make use of the `version()` API in order to print version information.
https://github.com/cypress-io/cypress/blob/720bc470e9c7a42fff0d98d2b649ef11ee338239/cli/lib/cli.js#L193

3. There is a regex matcher to catch unknown commands:- 

```js
// error on unknown commands
program.on('command:*', function () {
  console.error('Invalid command: %s\nSee --help for a list of available commands.', program.args.join(' '));
  process.exit(1);
});
```

https://github.com/cypress-io/cypress/blob/720bc470e9c7a42fff0d98d2b649ef11ee338239/cli/lib/cli.js#L311

IMO all these manual workarounds can be dropped and it makes a lot more sense using the `commander.js` API for the purpose.

**Comment by jamesgeorge007** [comment]
@jennifer-shehane thoughts :thinking:

**Comment by jennifer-shehane** [comment]
This sounds good to me. Just note that we are currently on commander version `2.15.1` https://github.com/cypress-io/cypress/blob/develop/cli/package.json#L37 

We're updating to commander `4.0.1` in our v4.0 release, since it includes breaking changes (as I recall dropping support for Node versions) https://github.com/cypress-io/cypress/pull/4226/files#diff-06024e5e8a3ed051810f077e14ec9bafR37

So, you'd need to double check to see if these features commander will give were possible in 2.15.1 or not, otherwise open a PR against [4.0 branch](https://github.com/cypress-io/cypress/tree/v4.0-release).

**Comment by sainthkh** [comment]
I checked the cases and concluded that those manual workarounds are necessary.

1. `unknownOption` function: When we remove it, `cypress cache` commands doesn't show help message when an unknown command is given. 
2. version command: You can use other version of Cypress when you use `CYPRESS_RUN_BINARY` environment variable. `.version` function cannot handle this case. 
3. regex catcher: Without this, `cypress asdf` doesn't show any warning. 

I'm closing this issue now because of the reasons above. If I missed something, please leave me some comments.
