### ISSUE TITLE
How to hijack http 302 requests through `cy.server`

### ISSUE THREAD

**Issue by jarone** [cypress-io/cypress#6042]
### Current behavior:

options of `cy.server` can not support mock http 302

### Desired behavior:

```javascript
cy.server({
  method: 'GET',
  status: 302,
  responseHeaders: {
    'location': myUri,
    'content-type': 'text/html'
  }
})

cy.route(someUriWillRespod302ToMyUri)
cy.visit(myUri)
cy.url().should('eq', myUri)
```

### Versions

newest

### Purpose

My goal is to test all logic that follows the Oauth 2.0 specification through Cypress.

Does anyone have a success story?

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
