### ISSUE TITLE
load test enviroment long time when start test 

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#6046]
From the test result video, about 35 second on loading enviroment finished， cypress spend too much time on loading, can you reduce the loading time？ or has another method to reduce?

### Versions
Cypress:    3.8.0                                                                              │
Browser:    Electron 78 (headless)

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
