### ISSUE TITLE
visiting `https` then `http` of same subdomain fails saying you can only visit a single unique domain per test

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#6048]
what_it_does:

```
CypressError: cy.visit() failed because you are attempting to visit a second unique domain.

You may only visit a single unique domain per test.

Different subdomains are okay, but unique domains are not.

The previous domain you visited was: 'https://www.sina.com.cn'

You're attempting to visit this new domain: 'http://sports.sina.com.cn'
```

http://sports.sina.com.cn is subdomain , but error.
https://sports.sina.com.cn is ok.

### Versions
Cypress:    3.8.0                                                                              │
Browser:    Electron 78 (headless)

**Comment by hieutrandn9889** [comment]
That is the same my problem

**Comment by jennifer-shehane** [comment]
Visiting an `http` subdomain after visiting a `https` subdomain fails. This should not fail.

I thought this may be a regression, but this happens all the way back to Cypress version 2 even.

```js
it('visit https after http subdomain', () => {
  cy.visit('https://www.cypress.io')
  cy.visit('http://docs.cypress.io') // fails
})

it('visit http after https subdomain', () => {
  cy.visit('http://www.cypress.io')
  cy.visit('https://docs.cypress.io') // passes
})
```

## `https` then visit `http` subdomain

<img width="1365" alt="Screen Shot 2019-12-30 at 5 01 09 PM" src="https://user-images.githubusercontent.com/1271364/71590269-32578600-2b56-11ea-8a46-d6a646f82535.png">

## `http` then visit `https` subdomain

![Screen Shot 2019-12-30 at 5 11 28 PM](https://user-images.githubusercontent.com/1271364/71590289-44d1bf80-2b56-11ea-8cb3-5f8cf2a56756.png)

**Comment by jennifer-shehane** [comment]
## Why

Ok, so, after discussing this with the team, this is actually expected behavior. 

The rules for what we have been calling a 'single unique domain per test' are technically following the rules of Same Origin Policy as outlined here: https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

>Two URLs have the same origin if the `protocol`, `port` (if specified), and `host` are the same for both.

So visiting a different protocol (`http` to `https`) is not considered the same protocol.

The reason the `http` to `https` often works is because of the websites rerouting rules.

## Next steps

1. The error message we are throwing in the Test Runner is completely confusing in this regard. We only mention a 'single domain' policy and should be more specific to call out `same origin policy`. This error message should be updated.
2. The documentation is just wrong. We talk about superdomain and then even mention `http` and `https` specifically being the same and following the rules. https://on.cypress.io/trade-offs#Same-origin I've created an issue to update this here: https://github.com/cypress-io/cypress-documentation/issues/2364

**Comment by jennifer-shehane** [comment]
There's a pull request to update the messaging of this error. The behavior is not in error nor a bug. This is expected behavior, but the messaging needs updating. https://github.com/cypress-io/cypress/pull/6118
