### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR with cypress open migrating from 3.7.0 -> 3.8.x

### ISSUE THREAD

**Issue by jarretmoses** [cypress-io/cypress#6057]
### Current behavior:
I recently just upgraded from `3.7.0` -> `3.8.x` and started noticing the issue that with my current setup running a test suite through the dev gui (cypress open) results in an error`ERR_SSL_PROTOCOL_ERROR (-107) loading 'https://localhost:56186/__/#/tests/integration/create-listing.test.ts'`. I've tested reverting back to 3.7.0 and my tests run fine.

Output from `cypress open` on 3.7.0 - https://gist.github.com/jarretmoses/00ab0853e017eaf7b5774808cdd446f4

Output from `cypress open` on 3.8.x - https://gist.github.com/jarretmoses/c1a1978869e92288bc0096c631aed64c

Output running a test suite on 3.7.0 - https://gist.github.com/jarretmoses/7b73bc53afad6fb56bca1670aafbfb83

Output running a test suite on 3.8.x - https://gist.github.com/jarretmoses/59510fc4e2d6c23910bdd2e9fb861ac5

### Desired behavior:

My tests to run as they were in 3.7.0 with HTTPS enabled locally.
### Steps to reproduce: (app code and test code)

I've recreated a repo with a very similar setup to my actual codebase https://github.com/jarretmoses/cypress-regression-3.8.x. The readme will instruct how to reproduce.

### Versions

3.8.1, macOS Catalina 10.15.2, Electron 78

**Comment by jarretmoses** [comment]
Just noticed...potentially related to https://github.com/cypress-io/cypress/pull/6043. Will keep an eye out for it and close this if that indeed is the issue.

**Comment by jennifer-shehane** [comment]
@jarretmoses Can you explain why you think this is related to the `https-proxy-agent` update specifically? Thanks.

**Comment by jennifer-shehane** [comment]
Hey @jarretmoses, I followed the instructions in the repo and unfortunately do not get the error you are seeing during `cypress open` or `cypress run` on version 3.8.0 of Cypress in Electron or Chrome. 

Is there some other configuration that could possibly be affecting it on your system that you're not sharing?

![Screen Shot 2019-12-30 at 4 01 03 PM](https://user-images.githubusercontent.com/1271364/71576061-aa558a00-2b1d-11ea-9b0c-7b6f02e78ce6.png)

The logs are a bit confusing. 

This output of `cypress open` (which actually is a log output from `cypress run`) is erroring because you are not logged into Cypress when attempted to record. https://gist.github.com/jarretmoses/c1a1978869e92288bc0096c631aed64c

```
cypress: server: events send error: Error:
  You 're not logged in. Run `cypress open` to open the Desktop App and log in. at Object.get ...
cypress: server: events sending ipc data {
  type: 'get:project:status',
  data: {
    id: 0.22404597418277938,
    __error: {
      type: 'NOT_LOGGED_IN',
      name: 'Error',
      stack: "Error: You're not logged in.\n" + '\n' + 'Run `cypress open` to open the Desktop App and log in.\n' +
        '    at Object.get 
...
} + 2 ms
```


I do however see the error in this output you pasted https://gist.github.com/jarretmoses/59510fc4e2d6c23910bdd2e9fb861ac5

This output shows it occurred on Electron 78 (not 73 as mentioned). I don't see any evidence of this happening during `cypress open`, so please provide information otherwise if this is not correct. And also provide any other configuration to recreate this issue on our end.

**Comment by jarretmoses** [comment]
@jennifer-shehane Firstly thanks for following up!
1) I don't entirely know it would be that package (https-proxy-agent) but because it seemed to be the means of handling https within the cypress server, but it seems I misunderstood its purpose so could be disregarded.

2) You are correct and I had a typo it is in fact Electron 78 not 73

3) Looking at your screenshot it seems perhaps your cert had not taken effect as it is still  says `Not Secure` which means your cert is not actually being read. It would be hard to tell why unless perhaps you started the webpack server before running the mkcert commands as theres  a `prestart` script that injects the `.cert/server.pem` file into webpack. Does that definitely exist (may be worth quitting chrome and hitting the url manually first) I could update the repo to potentially run the shell scripts from `create-local-cet.js` manually. But perhaps running the cert command manually restarting the app and verifying a secure connection with just going to `localhost:7777` in chrome before trying cypress.
The manual setup would be (in the shell within the test repo)
a) `rm -rf .cert`
b) `mkdir .cert`
c) `mkcert -install` (One note I realize I left out is if you use firefox and wanted to go to https://localhost:7777 there you need `brew install nss`) - comes from https://github.com/FiloSottile/mkcert
d) `mkcert localhost`
e) `touch ./.cert/server.pem`
f) `cat localhost.pem localhost-key.pem > ./.cert/server.pem`
(then start the app server)

4) I didnt think not being logged in should matter for this issue you can see it is was run with the  command `open` `cypress: cli: cli cli starts with arguments["/usr/local/bin/node",
  "/Users/jarretmoses/Dev/web/node_modules/.bin/cypress", "open"] + 0 ms`

I will dig around and see if I am missing a step but this is exactly how we setup our current dev environment. If it weren't the fact that going from 3.7->3.8 and back verified a change in cypress working I wouldn't feel it was a cypress update that changed some configuration.

**Comment by jarretmoses** [comment]
@jennifer-shehane I am noticing from my error that it doesn't seem to be hitting the correct url. As you can see from your screen shot you go to `'https://localhost:7777/__/#/tests/integration/example.test.ts'` which is the correct port but my error throws from port `62145` with the full url being `''https://localhost:62145/__/#/tests/integration/example.test.ts'` Is this expected behavior?

**Comment by jennifer-shehane** [comment]
When I ran the example project, it visited `https://localhost:7777/` which is passed into the Cypress.config as the `baseURL` as is defined in the `support/index.js` file. 

Do you have this config value being overwritten somewhere in your system env vars or something? I dont' see why it would just visit a completely different url from the project provided.

Can you open the Test Runner and click on Configuration to see where the `baseUrl` value is being read from? 

The panel looks something like shown below. 

![](https://docs.cypress.io/img/guides/configuration/see-resolved-configuration.0357cd82.jpg)

**Comment by jarretmoses** [comment]
Here is a screenshot. https://share.getcloudapp.com/04ug2jzj. Im confident I am not overriding the `baseUrl` anywhere outside of my setup. I think this is confirmed since 1) the baseUrl works fine for 3.7 and also every time I start cypress with 3.8.x the port is randomized.

**Comment by jarretmoses** [comment]
@jennifer-shehane apologies. It seems that between 3.7 -> 3.8 the way to set config changed and I did not notice that through the change log. I see now at https://docs.cypress.io/api/plugins/configuration-api.html#Usage my setup seems to now be incorrect. I am going to make some changes and confirm that my system is running correctly locally and through ci still and I will close this issue.

**Comment by jarretmoses** [comment]
@jennifer-shehane Going to mark this as resolved. Seems with an updated config override it works as expected again. Did `Cypress.config` get removed? Curious why it works for you and not me.

**Comment by jennifer-shehane** [comment]
@jarretmoses There should not have been a breaking change from 3.7 to 3.8, since this was not a major version release. 

Can you paste the previous config and the new config that was required? I'd like to track down if there was some sort of regression.

`Cypress.config` did not get removed - again, there should be zero breaking changes on non-major version releases.

**Comment by jarretmoses** [comment]
@jennifer-shehane sure thing. Here is the old setup that seems to have stpped working for me 
```
// support/index.js

import './commands'

export const CLIENT_BASE_URL = 'https://localhost:7777/';

Cypress.config('baseUrl', CLIENT_BASE_URL); // eslint-disable-line
```

and here is the change that started working for me. (specifically the return object)

```
// plugins/index.js
const cypressTypeScriptPreprocessor = require('./cy-ts-preprocessor')

module.exports = (on, config) => {
  on('file:preprocessor', cypressTypeScriptPreprocessor)

  return {
    ...config,
    baseUrl: 'https://localhost:7777/'
  }
}

```


Would you like me to reopen this issue too?

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce the `Cypress.config('baseUrl')` not being set from the `support/index.js` file in Cypress 3.8.1.

`support/index.js`

```js
export const CLIENT_BASE_URL = 'https://localhost:7777/'

Cypress.config('baseUrl', CLIENT_BASE_URL)
```

`spec.js`

```js
it('sets baseurl', () => {
  cy.log(Cypress.config('baseUrl'))
  cy.visit('/')
})
```

Failure due to my not having anything running on `localhost:7777`

<img width="594" alt="Screen Shot 2020-01-07 at 2 01 05 PM" src="https://user-images.githubusercontent.com/1271364/71876865-2e2ef800-3156-11ea-903d-228a86e2ba8c.png">

Any other configuration that may be relevant to why this is not setting for you?

**Comment by jarretmoses** [comment]
@jennifer-shehane Honestly everything in that repo is really my setup. If it were isolated to my machine Id think it was just something wrong with it but this occurs for my other devs as well. When I have some more free time I'll poke around and if anything springs up  I'll let you know.
