### ISSUE TITLE
Custom 'Should' error messages are not dynamic

### ISSUE THREAD

**Issue by dizhar** [cypress-io/cypress#6060]
### Current behavior:
```js
it('fails with custom message via overwrite of should', () => {
    cy.wrap(1).should('eq', 1, { message: 'custom error message 1'})
    cy.wrap(1).should('eq', 2, { message: 'custom error message 2'})
  })
```

Actual error message:
```
CustomError:  custom error message 1
```

Expected error  Message:
```
CustomError:  custom error message 2
```

### Desired behavior:

Custom error messages should be dynamic and not static.

If a 'should' fails, then the custom message of where a 'should'  failed is expected to  be displayed and not the first custom error message on the test run. 

### Steps to reproduce: (app code and test code)
```js
  /*
    Ref: https://docs.cypress.io/api/cypress-api/custom-commands.html#Overwrite-Existing-Commands
    Add this to /cypress/support/commands.js
  */
  Cypress.Commands.overwrite('should', (originalFn, actual, assertion, expected, options) => {
    if (options && options.message) {
      cy.on('fail', (error, runnable) => {
        error.name = 'CustomError'
        error.message = options.message
        throw error // throw error to have test still fail
      })
    }
    return originalFn(actual, assertion, expected, options)
  })

it('fails with custom message via overwrite of should', () => {
    cy.wrap(1).should('eq', 1, { message: 'custom error message 1'})
    cy.wrap(1).should('eq', 2, { message: 'custom error message 2'})
  })
```

### Versions
v3.8.0

OS Windows 10, browser chrome

**Comment by jennifer-shehane** [comment]
I think this is related to https://github.com/cypress-io/cypress/issues/3171 which will be fixed in https://github.com/cypress-io/cypress/pull/5762 

@sainthkh is this correct?

**Comment by sainthkh** [comment]
@jennifer-shehane It has nothing to do with #3171. Reason below:

@dizhar According to Node.js EventEmitter documentation, [on() function](https://nodejs.org/api/events.html#events_emitter_on_eventname_listener) calls all event listeners in the ordered of registration. (Internally, `cy` object inherits methods in node.js `EventEmitter`).

In your case, you registered your first listener with `{message: 'custom error message 1'}` with the first `should` command. And the second `should` fails a lot of times and it adds a lot of listeners. 

Then, when the test fails, it tries to run all the listeners. Then, when it runs the first listener registered by the first `should`. It throws the first error object (with `"custom error message 1"`. 

That's why it threw the first error message. 

Then, how should we solve this problem? 

The simplest method is to remove `'fail'` listeners before registering new ones like below: 

```js
Cypress.Commands.overwrite('should', (originalFn, actual, assertion, expected, options) => {
  if (options && options.message) {
    cy.removeAllListeners('fail') // remove all 'fail' listeners
    // And we're starting from fresh!
    cy.on('fail', (error, runnable) => {
      error.name = 'CustomError'
      error.message = options.message
      throw error // throw error to have test still fail
    })
  }

  return originalFn(actual, assertion, expected, options)
})
```

But if you created multiple custom commands and they use `'fail'` event, they can cause flaky tests. In that case, you need to remove listeners when the `should` ran successfully like below: 

```js
Cypress.Commands.overwrite('should', (originalFn, actual, assertion, expected, options) => {
  if (options && options.message) {
    const listener = (error, runnable) => {
      error.name = 'CustomError'
      error.message = options.message
      throw error // throw error to have test still fail
    }

    const removeListener = () => {
      cy.removeListener('fail', listener)
      cy.removeListener('command:end', removeListener)
    }

    cy.on('fail', listener)
    cy.on('command:end', removeListener)
  }

  return originalFn(actual, assertion, expected, options)
})
```

Note: `"command:end"` event is fired when command is ended. For more information, [please check here](https://docs.cypress.io/api/events/catalog-of-events.html#Cypress-Events).

I hope this solved your problem.

**Comment by dizhar** [comment]
Hi sainthkh and jennifer-shehane,
I am using typescript,  Property ' cy.removeAllListeners  and  '  cy.removeListener' does not exist.

Any suggestions?

**Comment by sainthkh** [comment]
Current workaround is to write code like `(cy as any).removeAllListeners('fail')`. 

It's an issue in #5228 that should be fixed soon.

**Comment by sainthkh** [comment]
@dizhar #6066 is merged and everything will be fixed in the next version of Cypress.

**Comment by sainthkh** [comment]
@jennifer-shehane Everything solved. This can be closed now.

**Comment by dizhar** [comment]
That's great news! I am looking forward to it.

Also thank you for the quick response.

Best Regards'
Daniel Izhar
