### ISSUE TITLE
[Bug] Infinite loop caused because of inadequate null check

### ISSUE THREAD

**Issue by DesignByOnyx** [cypress-io/cypress#6061]
### Current behavior:

A "Maximum call stack" error occurs in the `getFirstFixedOrStickyPositionParent` method when `$el` has a zero length. The method iteratively crawls up the DOM tree using `$el.parent()` - however the method only checks for `$el` and not `$el.length`. If `$el.length` is zero, the method should exit.

https://github.com/cypress-io/cypress/blob/74006acf66597eac84ceff31eb3af90152315fd4/packages/driver/src/dom/elements.ts#L858

### Desired behavior:

The code should not cause a stack overflow. 

### Steps to reproduce: (app code and test code)

Call getFirstFixedOrStickyPositionParent with an empty collection:

```
getFirstFixedOrStickyPositionParent( $([]) )
```

### Versions

cypress@3.8.1
OSX 10.14.6 / Ubuntu 19.04
Chrome 79

**Comment by jennifer-shehane** [comment]
@DesignByOnyx We'll need a test example in order to fix the issue. A failing test versus a passing test after we fix the check. We have been trying to fix this issue in ttps://github.com/cypress-io/cypress/issues/4373 but need a simple test in order to merge the fix in.

Closing as a duplicate of https://github.com/cypress-io/cypress/issues/4373, please comment in that issue with an example.
