### ISSUE TITLE
Is there any way to close the antd drawer?

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress#6063]
https://ant.design/components/drawer/

<img width="1435" alt="截屏2019-12-30下午4 55 36" src="https://user-images.githubusercontent.com/22906174/71574836-74b49f00-2b25-11ea-813d-c0c747da2cd9.png">

### Versions
Cypress 3.8.0

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
