### ISSUE TITLE
Amplify + Cypress: Deployment test phase hangs indefinitely once all the tests are completed

### ISSUE THREAD

**Issue by jeececab** [cypress-io/cypress#6065]
### Current behavior:

When I try to deploy, the tests run as usual, but the test step hangs indefinitely once the tests are over (At the "All specs passed" line), therefore the deployment never happens. Had no similar problem before. I did a deployment last week with no problem whatsoever. I didn't change the build settings.

![bb](https://user-images.githubusercontent.com/33330556/71591881-ff80a400-2afb-11ea-8aea-2e723dc957c6.png)

Build settings:

![fddfd](https://user-images.githubusercontent.com/33330556/71591884-04455800-2afc-11ea-913e-35f7ea5cc35d.png)

### Desired behavior:

The deploying step should happen after the tests, OR the tests results should show (artefacts, etc) after failure.

### Steps to reproduce: (app code and test code)

Deploy on Amplify and add the Cypress tests step in the build

### Versions

Cypress 3.8.1 and also tried 3.7.0 (which was working fine before)

**Comment by neilbts** [comment]
I am currently struggling with an identical problem. I have a single very simple test which is passing. When I download the artifacts I can see the test executing successfully.

I've seen a few variations throughout the day and with various tweaks (eg. calling executables with `yarn` rather than `npx`, not doing mochawesome reports, skipping merge, etc...) and saw a variety of results which were not consistently reproducible. For example, sometimes it gets past the cypress run and hangs on the `postTest` phase.

Also, I don't think Cypress is reporting your tests as failing. The headers are just not aligned with the results.

**Comment by jeececab** [comment]
@neilbts Oh you're right about the last point, thanks. I removed it from the description. 

Interesting points. I tried a few variations too with no success :( Never had problems in the past weeks. It may be a regression on their side (Amplify or Cypress). I also opened an issue with amplify-console:

https://github.com/aws-amplify/amplify-console/issues/347

**Comment by c32hedge** [comment]
What browser and OS? Could be similar to https://github.com/cypress-io/cypress/issues/6023?

**Comment by neilbts** [comment]
I am running the following...
Browser:    Electron 78 (headless)
OS: Amazon Linux 2 Docker container image (137112412989.dkr.ecr.us-west-2.amazonaws.com/amazonlinux:2)

**Comment by danieletieghi** [comment]
Same problem here, tests were running correctly *last year*, now they hang at the end of the test phase (all test passed). 

[venting mode on] Actually it's a bit frustrating, I'm new with amplify, but as of now it seems to be complicating my life instead of easing it. I've read "production ready" but it's like everything I'm trying has a bug. [/venting mode off]

**Comment by neilbts** [comment]
For the record I tried with video disabled (`--config video=false`) thinking it may be an issue with video processing, however, problem persists.

@danieletieghi same feelings about Amplify. It has been overpromised and underdelivered.

**Comment by jeececab** [comment]
Closing (issue resolved): see https://github.com/aws-amplify/amplify-console/issues/347
