### ISSUE TITLE
How to Install Cypress older version 3.4.1

### ISSUE THREAD

**Issue by Sourajeet01** [cypress-io/cypress#6069]
How to Install Cypress older version 3.4.1

**Comment by jennifer-shehane** [comment]
Please see npm or yarn documentation on how to install specific versions of packages. https://docs.npmjs.com/cli/install `npm install cypress@3.4.1`

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by Sourajeet01** [comment]
Thanks Jennifer ! It works successfully..

**Comment by reymarte07** [comment]
Thanks, It works.
