### ISSUE TITLE
Need a sample code to test WebSockets in any webpage using Cypress JS

### ISSUE THREAD

**Issue by Sourajeet01** [cypress-io/cypress#6079]
Need a sample code to test WebSockets in any webpage using Cypress JS.
1. Verify Web Socket is used behind any UI/Webpage (like google homepage, etc.)
2. Check connection time/ data response time.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress).

I would also suggest asking for 'recipes' of this sort in our `cypress-example-recipes' repo as a new issue. https://github.com/cypress-io/cypress-example-recipes
