### ISSUE TITLE
possible bug in cy.exec() -  command not found: npm

### ISSUE THREAD

**Issue by zsolt-dev** [cypress-io/cypress#6081]
### Current behavior:

```
CypressError: cy.exec('npm run db:reset') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 127

Stderr:
zsh:1: command not found: npm

Because this error occurred during a 'before each' hook we are skipping the remaining tests in the current suite: 'deleteUser'
```

After clicking on "Run all tests" (reload button) it works fine. It just does not work on the first time.

When I tried to provide PATH as an env option to cy.exec() it was doing the same thing.

### Desired behavior:

Running cy.exec even on the first time, not just every time after the first time

### Steps to reproduce: (app code and test code)

1. npm run cy:open
2. click on the test that is using cy.exec()
3. it fails
4. click on "Run all tests" (reload button)
5. the same test now works fine

### Versions

"cypress": "^3.8.1" in package json as a dev dependency
macOS catalina

**Comment by jennifer-shehane** [comment]
@zsolt-dev I'm not able to reproduce this error. Please provide the exact test code. 

`package.json` script

```json
  "scripts": {
    "foo": "echo foo"
  },
```

```js
it('exec npm', () => {
  cy.exec('npm run foo').then((obj) => {
    cy.log(obj.code)
    cy.log(obj.stdout)
    cy.log(obj.stderr)
  })
})
```

<img width="719" alt="Screen Shot 2020-01-03 at 12 59 36 AM" src="https://user-images.githubusercontent.com/1271364/71684596-57e9c700-2dc4-11ea-96ee-fd39ffd7beb7.png">

**Comment by amkoehler** [comment]
I saw this issue and noticed OP is using zsh as their shell (which is the new default on macOS catalina). I'm also using zsh on ubuntu and had the same issue. I don't have the issue when switching my default shell back to bash.

**Comment by jennifer-shehane** [comment]
I also use zsh as my shell (on Catalina) and am unable to reproduce the issue from the code I pasted above. 

Unfortunately we'll have to close this issue if no reproducible example is provided. Please provide the test code to run to reproduce this error.

**Comment by racedale** [comment]
This is an issue I am also running into with Catalina, zsh, and executing npm commands through Cypress. I am also using `nvm` which I think _might_ be part of it? Haven't yet been able to find a way to reproduce it since it seems dependent on how Catalina is setup. 

If I personally run `npx cypress run` then my `cy.exec('npx serverless invoke local ...')` command works.  But if Cypress isn't executed directly from the commandline but instead through a script, it can't find `npm` or `npx` like OP's thread.

Basic script I am using: 
```
import { spawn, exec } from 'child_process'

const serverlessProcess = spawn('npx', ['serverless', 'offline', 'start'], { shell: '/bin/zsh' })
serverlessProcess.stdout.on('data', message => {
  if (
    message.toString().includes('Serverless: Offline [HTTP] listening on http://localhost:3000')
  ) {
    exec('npx cypress run', { shell: '/bin/zsh' }, (error, stdout) => {
      console.log(stdout)
      serverlessProcess.kill()
    })
  }
})
serverlessProcess.on('error', error => {
  console.error(error)
})
```
Cypress test:
```
it('should map fields', () => {
    cy.exec('npx serverless invoke local --function mapFields --path cypress/fixtures/s3-event.json')
      .its('stdout')
      .then(consoleOutput => {
        expect(consoleOutput).match(/"gender": "M"/)
        expect(consoleOutput).match(/"age": 60/)
      })
  })
```

**Comment by racedale** [comment]
@jennifer-shehane updated my description with minimal code to reproduce as best I can.

**Comment by dylnclrk** [comment]
Just chiming in to say we were debugging something similar today…

Context: 

We have a command (`prep`), frequently run in a `beforeAll`, that looked something like this:

```
Cypress.Commands.add("prep", () => {
  cy.exec("npm run prep");
});
```

The first time `cy.prep()` was run, it would fail with the error described in this issue (`Code: 127`, `command not found: npm`). But when run before subsequent tests in the suite, it would pass.

In debugging, we saw that adding another exec command (pwd, sleep, whatever) seemed to prevent it from breaking. For example,

```
Cypress.Commands.add("prep", () => {
  cy.exec("sleep 1");
  cy.exec("npm run prep");
});
```

-----------------------------

I can't reproduce it on my machine, only on another developer's laptop. 

She's using Bash as her default shell with High Sierra.

Could this be an issue with nvm (perhaps login scripts/shimming is not yet complete)? I have no idea how `cy.exec` works.

**Comment by jennifer-shehane** [comment]
We use `nvm` at Cypress ourselves, and haven't encountered this error before. 

This is essentially the exec code: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/exec.js#L18:L18

**Comment by michalvankodev** [comment]
Funny as it sounds. I get this error as well when the failing tests runs for the first time only.
I was able to get around this with setting a `retries` option on the test. But it still doesn't make sense as I need to run my custom command in `beforeAll` or `beforeEach` hook.

and yes I also use `nvm` and `zsh` and I tried both: 
1. running test via Module API
2. running tests via `cypress open`

In both environments the problem is the same: It only works on second try.

Hopefully my little hack will work by executing the command before all tests, let it retry and pass. and then it shouldn't require setting retries anymore.

**Comment by mlewando90** [comment]
I have this same issue too.
I'm using Ubuntu, ZSH and nvm.

**Comment by dlcoffee** [comment]
i had the same issue as well. i was on nvm 0.33.11. i upgraded to the latest version (0.37.2 as of writing) and that seems to have solved my problem.

**Comment by jennifer-shehane** [comment]
Are any of you setting `nodeVersion` in your Cypress configuration, like `cypress.json`? Let us know if you are or are not setting this and still experiencing the issue.

**Comment by dlcoffee** [comment]
@jennifer-shehane i don't have `nodeVersion` set in my `cypress.json`. it's bare bones:

```json
{
  "baseUrl": "http://localhost:3000/"
}
```

**Comment by GradedJestRisk** [comment]
@michalvankodev, I come against a similar behaviour as [yours](https://github.com/cypress-io/cypress/issues/6081#issuecomment-717330501). Mine was a [dependency issue](https://github.com/jorgebucaran/colorette/issues/49), solved on Node 14

What I found that may interest you:
- when runinng a script for the first time throught `npm`, like  `cy.exec('npm run db:empty');` [here](https://github.com/1024pix/pix/blob/dev/high-level-tests/e2e/package.json#L27)
- cypress used Ubuntu `sh` (dash) shell, not the default login shell (for me, `zsh`), the one you set with `chsh` (you can check this by inserting `ps -p $$` in your npm script)

I quick-fixed it by installing Node on OS level, as I haven't been able to install `nvm` on `dash`

So why cypress use `sh` instead of `zsh` ?
The shell is picked [here](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/exec.js#L45) using $SHELL environment variables, themselves provided by [shell-env](https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/exec.js#L4) dependency. 

So I can't figure why:
- if you launch cypress using `zsh` ($SHELL is `zsh`)
- cypress ends up reading `sh`  in $SHELL

The answer may lay in `shell-env` dependency, [default-shell](https://github.com/sindresorhus/shell-env/blob/main/index.js)

**Comment by joe1248** [comment]
I had a similar issue, a solution was:
Doing `which npm` on your system may give you `user/local/bin/npm`.
Then, in cypress, before calling npm, just do `export PATH=/usr/local/bin/:$PATH`

**Comment by hvaandres** [comment]
I'm having the same issue, and maybe this is a good reference. [Github Repo](https://github.com/ddawson235/salesforce-cypress-demo/blob/master/cypress/integration/accounts/CreateAccounts.ts)

**Comment by zsolt-dev** [comment]
updating the nvm to the version solved the issue for me.

Thanks to @dlcoffee for providing the fix in the comment.

**Comment by AlienLifeForm-UMA** [comment]
I have the same issue and have to add "source ~/.zshrc" to all exec commands for nvm/Node to work. So it seems that Cypress doesn't actually run the zshrc file even when using zsh? I checked using echo $0 and it is using zsh.

**Comment by alexsegura** [comment]
I think I have almost the same problem under Mac OSX, using Cypress standalone / direct download. 

I'm using `cy.exec()` to run a Docker Compose command (i.e `cy.exec('docker compose exec -T ...')`). 

Depending on how Cypress is launched, the `$PATH` is not the same. 
- When it's launched via Spotlight or double-click, it does not contain `/usr/local/bin` (that's where the `docker` binary is located). 
- When it's launched via command line `open -a /Applications/Cypress.app`, it contains `/usr/local/bin`.

**Comment by wojciechbialasek** [comment]
@alexsegura I also facing the same issue, have you solved it?

**Comment by gbutt-tr** [comment]
I am using this npm script to open cypress: 
`"cypress:open": "dotenv -v TZ=Etc/UTC -- cypress open"`

Thanks to the comments above, I was able to fix this issue by adding SHELL=/bin/bash to the script: 
`"cypress:open": "dotenv -v TZ=Etc/UTC -v SHELL=/bin/bash -- cypress open"`
