### ISSUE TITLE
Possible to let the test fail if a console.error occurred during the test?

### ISSUE THREAD

**Issue by masaanli** [cypress-io/cypress#6094]
### Current behavior:
.

### Desired behavior:
Some generic stuff somewhere where I can say, that if a console error happens during a test then that test will fail.

### Steps to reproduce: (app code and test code)
Just run a test. If the test succeeds

### Versions
Cypress 3.8.1
MacOS Catalina 10.15.2
Chrome / Electron

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by kicktipp** [comment]
Just for reference I add a link to the solution here
https://stackoverflow.com/questions/61362670/
