### ISSUE TITLE
svg element is visible but cypress detects it as not visible

### ISSUE THREAD

**Issue by knagarajan1984** [cypress-io/cypress#6097]
Cypress detects an svg element in my application as invisible even though it is visible

In `version 3.8.0 and 3.8.1`  => see the visibility hidden icon

![image](https://user-images.githubusercontent.com/15121799/71810507-d370a000-3072-11ea-99f5-2dcda2bd90b5.png)

on checking the element properties in the chrome console, i see below
![image](https://user-images.githubusercontent.com/15121799/71810524-dc617180-3072-11ea-9733-35f6b35fb365.png)

In `version 3.7.0` 

![image](https://user-images.githubusercontent.com/15121799/71815682-8a274d00-3080-11ea-9986-202ffcda67e2.png)

![image](https://user-images.githubusercontent.com/15121799/71815747-bd69dc00-3080-11ea-8049-d02dc3dc835a.png)

As you can see from the logs in versions >3.7.0 cypress has automatically added a tag entry for `<rect>` and detected it as not visible.

**Comment by knagarajan1984** [comment]
Any help please?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. We need a failing test and the HTML to run the test code against. 

My example below does not show this invisible icon in 3.8.1.

```html
<html>
<body>
<svg viewBox="0 0 220 100" xmlns="http://www.w3.org/2000/svg">
  <rect width="100" height="100" />
  <rect x="120" width="100" height="100" rx="15" />
</svg>
</body>
</html>
```

```js
it('see svg', () => {
  cy.visit('index.html')
  cy.get('svg').should('exist')
})
```

![Screen Shot 2020-01-08 at 4 41 34 PM](https://user-images.githubusercontent.com/1271364/71969803-d23ba080-3235-11ea-9020-b47517a1d589.png)

**Comment by MherPolo** [comment]
zfddfg
