### ISSUE TITLE
Cypress on Chrome Extensions

### ISSUE THREAD

**Issue by hamzachd4** [cypress-io/cypress#6102]
Hello,
I am facing an issue related to e2e testing on a chrome extension. Currently, I'm able to install the extension using `on('before:browser:launch')`. The problem I'm facing is how to trigger the chrome extension in cypress.

Well, my use case is 
- Open a URL (any website)
- Trigger the chrome extension
- Run api calls to the server using Cypress

Here, is the code

```js
module.exports = (on, config) => {
  on('before:browser:launch', extensionLoader.load({
    source: '/path/to/extension',
    alias: 'Feed',
    skipHooks: false,
    watch: true,
    validBrowser: ['chrome'],
    quiet: false,
    destDir: '/dir',
    cypressMatches: ['*://*/*/integration/*']
  }));
```

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by esharmony** [comment]
> Hello, I am facing an issue related to e2e testing on a chrome extension. Currently, I'm able to install the extension using `on('before:browser:launch')`. The problem I'm facing is how to trigger the chrome extension in cypress.
> 
> Well, my use case is
> 
> * Open a URL (any website)
> * Trigger the chrome extension
> * Run api calls to the server using Cypress
> 
> Here, is the code
> 
> ```js
> module.exports = (on, config) => {
>   on('before:browser:launch', extensionLoader.load({
>     source: '/path/to/extension',
>     alias: 'Feed',
>     skipHooks: false,
>     watch: true,
>     validBrowser: ['chrome'],
>     quiet: false,
>     destDir: '/dir',
>     cypressMatches: ['*://*/*/integration/*']
>   }));
> ```

Did you find a resolution to this question?
