### ISSUE TITLE
Getting Cannot GET /__/ error while running headless 

### ISSUE THREAD

**Issue by nikhiletc** [cypress-io/cypress#6104]
<img width="934" alt="Screenshot 2020-01-07 at 11 58 05" src="https://user-images.githubusercontent.com/4526422/71891225-6f1f1080-3146-11ea-8c58-91db542c25db.png">

i have 2 spec file in one folder first spec works fine and when 2nd spec starts it throw an error message and test hanged.
the same spec works fine while running on chrome
Cypress version: 3.8.1
Electron: 78
![Screenshot 2020-01-07 at 12 12 05](https://user-images.githubusercontent.com/4526422/71891796-a641f180-3147-11ea-9f5e-05e48ef75faf.png)
<img width="1438" alt="Screenshot 2020-01-07 at 13 23 05" src="https://user-images.githubusercontent.com/4526422/71895273-e8236580-3150-11ea-961c-e43c6fa7133e.png">

mac Os

**Comment by jennifer-shehane** [comment]
Could be related to this bug: https://github.com/cypress-io/cypress/issues/3975

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example that we can run and we will reopen the issue.

**Comment by jennifer-shehane** [comment]
This fix is available starting in [`4.6.0`](https://docs-staging.cypress.io/guides/references/changelog.html#4-6-0) as an [experiment](https://on.cypress.io/experiments) which you can access by setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

The fix is experimental, so there may be some situations where the this is not fixed. 

If you're still this issue while setting the `experimentalSourceRewriting` to true in 4.6.0 - [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a reproducible example + screenshots, etc - filling out our issue template.
