### ISSUE TITLE
How to catch duplicate text inside a page with cy.get/cy.contains functions

### ISSUE THREAD

**Issue by Slamster7** [cypress-io/cypress#6108]
### Current behavior:

I need to make a test which captures duplicated text if it exists. 

My idea is to pass the text to a string parameter and then see if this parameter is found more than once in the page. It should be present only once, if more the test should fail.

```js
cy.get(`:contains(${textParameter})`).should('have.length', 1)
```

But the `.should()` function is applying to the element that contains `textParameter` and it catches every outer element that it contains it. 

Output : `Expected <> to have length of 1 but got 11`

### Desired behavior:

I need to know if there is a way that the `.should` function could be applied to `textParameter` to count how many times it exists in the page.

### Test code to reproduce

```js
var textParameter = 'some text'
cy.get(`:contains(${textParameter})`).should('have.length', 1)
```

### Versions

Cypress 3.0.2
macOS 10
Chrome

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
