### ISSUE TITLE
Run my first test file but not the rest

### ISSUE THREAD

**Issue by jboucly** [cypress-io/cypress#6114]
When I run my tests on my dev (heroku) server the tests do not work fully, it stops on the end of the first test file and does not continue with the other test files.
It reloads the page but no longer displays anything on chrome or electron.
The weird thing is that when I do it with my local server (http://localhost: 4200) everything works perfectly ...

A response to this bug?

### Current behavior:

The first test file is executed but the others do not...

### Desired behavior:

All my test runs.

### Versions
3.8.1

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. There is likely something specific in your first test file that is stopping execution somehow. 

Also some more direction on what `does not continue` would be nice. I would suggest 
running Cypress in [debug mode](https://on.cypress.io/debugging#Debug-the-Command-Line) mode and printing the entire set of logs here.

**Comment by jboucly** [comment]
![NG-ZORRO_Universal_Starter_et__Users_difi_Documents_Projets_socle-test](https://user-images.githubusercontent.com/33218155/71962461-c205d000-31f9-11ea-924d-0b375894ac48.png)

@jennifer-shehane I can't actually show you anything since the bug displays a blank page and in the console nothing

**Comment by jennifer-shehane** [comment]
Your application may be using "frame busting". By default Cypress modifies code it detects as frame busting so the application under test runs properly in the Cypress Test Runner (which runs your app inside an iframe itself). Can you try disabling this by setting `modifyObstructiveCode=false` in your configuration? Further explanation can be found here: https://on.cypress.io/configuration#modifyObstructiveCode

**Comment by jboucly** [comment]
No change in the behavior of the app..
