### ISSUE TITLE
how to use command:retry to run cy command

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#6119]
I want to use retry command to check selector when test failure, and on retry to find actual selector when run test, so how to run cy command on support files, or how to do this?

### Current behavior:
```js
Cypress.on('command:retry', (e) => {
  console.log(e)
  var elements = document.querySelector('#q');
  console.log(elements);
})
```

### Versions
cypress： 3.8.1
Chrome： 79

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
