### ISSUE TITLE
Unable to call custom command in test spec file

### ISSUE THREAD

**Issue by Amrkamel1** [cypress-io/cypress#6122]
### Unable to call custom command :
i have add a new command in `commands.js` and trying to call it inside spec test
but its not defined 
```js
Cypress.Commands.add('login',(username,password) => {
    cy.visit('https://example.com/')
    cy.get('input[name="username"]').clear().type('username');
    cy.get('input[name="password"]').type('password');
    cy.get('button[type="submit"]', { timeout: 20000 }).last().click();
    cy.url().should('eq','https://example.com/home/');
});
```

**then call it in beforeEach**

```js
import helper from '../../Libs/helper/helper.js';
import AccountPage from '../../Libs/accountPage.js';
import Menu from '../../Libs/menu';
import LoginPage from '../../Libs/loginPage.js';


const page = new AccountPage();
const menu = new Menu();
const login = new LoginPage();

describe('MC_TC_02 Account Overview test', function () {

    beforeEach(function () {
       **cy.login();**
        cy.fixture('testdata').as('testData');
        cy.get('@testData').then((testData) => {
            helper.testData = testData;
        });
    });

    it('2.1.Verify account is loaded properly after loging', function () {
        page.navigateToAccoun()
    });

});
```

**Comment by pravynandas** [comment]
Hi @Amrkamel1, not 100% sure, but because the username and password parameters defined as mandatory and not supplied in your command could be the root cause?

Try supplying cy.log('some_username', 'some_password'); and see what happens.

If you, however do not want to supply custom credentials on every call (which is mostly the case), you can simply remove the parameters in command definition and add them as local constants assigning the actual value.

**Comment by Amrkamel1** [comment]
> Hi @Amrkamel1, not 100% sure, but because the username and password parameters defined as mandatory and not supplied in your command could be the root cause?
> 
> Try supplying cy.log('some_username', 'some_password'); and see what happens.
> 
> If you, however do not want to supply custom credentials on every call (which is mostly the case), you can simply remove the parameters in command definition and add them as local constants assigning the actual value.

Thanks its working

Just one more question can i make this login to be run once per spec not in beforeEach func as it will login with each single block with beforeEach

**Comment by pravynandas** [comment]
Great, it works.

And to run once per spec add it in a before() function in support/index.js file.

**Comment by Amrkamel1** [comment]
> Great, it works.
> 
> And to run once per spec add it in a before() function in support/index.js file.

Thanks for fast reply can u justb provide a sample how it will look since i start using cypress recently 

Not how how i will dedicate thia specific before() to specific spec

**Comment by pravynandas** [comment]
Sure. Here how it would look like.

// Import commands.js using ES2015 syntax:
import './commands';
// Alternatively you can use CommonJS syntax:
// require('./commands')

before(function () {
    cy.login();
});


If this resolves your issues. You may want to close the issue. Thanks.

**Comment by Amrkamel1** [comment]
but how i will apply this to particular spec 
 lets say i have 5 specs i want this login method to be run once upon specific  spec not before each it block within the spec

**Comment by pravynandas** [comment]
Since this before() is in index.js which is the entry point for cypress, it indeed runs (by default) before any spec file in the project. Give a try.

**Comment by Amrkamel1** [comment]
sorry for asking alot im just curious about this tool

let say i have loginTest.spec im testing alot of login scenario

so if i add before() in index it mean that when i start loginTestSpec cypress will be already logged in so how i will verify the test cases i believe im missing something

**Comment by pravynandas** [comment]
No worries, that's how we learn.

Based on your earlier request, "lets say i have 5 specs i want this login method to be run once upon specific spec" it is certain that you wanted to login before starting each spec file, which means, you have to logout at the end of each test to make it work (otherwise your before() test fails on next spec file, because you already logged in and cannot file login form). 

Also, if you have some scenarios to test on the login feature itself, you can achieve that within the spec file (while logging out one last time at the end).

To put it in simple terms.

# 01.login.spec.js
1. You are already logged in before()
2. logout
3. login with invalid credentails (using your cy.login('','') command)
4. login with invalid password only
5. login successfully & logout
6. reset password
7.login one last time
8. **logout** (<--- important)

# 02.nagivation.spec.js
1. You are already logged in before()
2. navigate to page 1
3. navigate to page 2
4. **logout** (<-- important)


I think, if logout is obvious, you can put it in after() command of index.js (which, ofcourse I haven't tried myself yet :) )

**Comment by Amrkamel1** [comment]
@pravynandas
 
awesome!
thanks for the details explanation

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
