### ISSUE TITLE
404 after redirect on login test

### ISSUE THREAD

**Issue by Ugedas** [cypress-io/cypress#6123]
Hi, I have a problem in which, after doing an AJAX POST, the page redirects to some JSP, but in cypress, it just changes the url from the page and it goes to a 404 error in the test. The problem seems to be that Cypress changes the context by changing the first one with "/__/"
Before redirect:

![bfore](https://user-images.githubusercontent.com/8956095/71976243-2040ac00-3216-11ea-93b4-5ddeaacb8e50.png)

After redirect:
![after](https://user-images.githubusercontent.com/8956095/71976255-25056000-3216-11ea-9d20-afe4f89b8404.png)
![after2](https://user-images.githubusercontent.com/8956095/71976579-ee7c1500-3216-11ea-98e1-bdcd5ec5c1c4.png)

**Comment by Ugedas** [comment]
#3975

**Comment by jennifer-shehane** [comment]
This fix is available starting in [`4.6.0`](https://docs-staging.cypress.io/guides/references/changelog.html#4-6-0) as an [experiment](https://on.cypress.io/experiments) which you can access by setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

The fix is experimental, so there may be some situations where the this is not fixed. 

If you're still this issue while setting the `experimentalSourceRewriting` to true in 4.6.0 - [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a reproducible example + screenshots, etc - filling out our issue template.
