### ISSUE TITLE
.type() does not enter a - or + after a valid number in an input of type number

### ISSUE THREAD

**Issue by pkell** [cypress-io/cypress#6150]
### Current behavior:

Similar to to now closed [6055](https://github.com/cypress-io/cypress/issues/6055), if I try to type `123-` into an input of type number, the field only contains 123. This is a bit of an edge case, we use these valid characters to make an invalid number to test field validation messages for our NumberTextField component.

This behavior is a discrepancy between Cypress and manual in Chrome as strings like 123- and 1+1 can be entered manually. Our tests are passing in 3.7 but failing in 3.8.2

### Desired behavior:

`.type()` allows valid characters to be added to an input of type number even if the positioning of the characters makes the end value invalid.

### Steps to reproduce:

use `.type('123-')` on an input of type number.
use `.type('1+1')` on an input of type number.

### Versions

Chrome 79, Windows 10, Cypress 8.3.2

**Comment by jennifer-shehane** [comment]
I was actually never really able to get the assertion to pass in any version, but the behavior of typing is definitely different from 3.7.0.

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
<body>
  <input type='number'>
</body>
</html>
```

`spec.js`

```js
it('type 123-', () => {
  cy.visit('index.html')
  cy.get('input').type('123-').should('have.value', '123-')
})

it('type 1+1', () => {
  cy.visit('index.html')
  cy.get('input').type('1+1').should('have.value', '1+1')
})
```

# 3.4.1

![](http://g.recordit.co/Gbk0EF4437.gif)

# 3.7.0

![](http://g.recordit.co/feHkIXeVDN.gif)


# 3.8.2

![](http://g.recordit.co/iX7HIjAgxl.gif)

# Manual typing

![](http://g.recordit.co/7Xznx2qVl8.gif)

**Comment by avallete** [comment]
Yeah, into my fix #6055 I've already thought of some corner cases like this one.

Since I didn't found a satisfying solution, I've only resolved the actual issue and didn't pushed fix futher more.

I would like to share here some of my though:

First, some code lines to look at:
https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/keyboard.ts#L65
https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/keyboard.ts#L262

Basically, Cypress do validation on the typed data regarding of the input type.
Why do they do that ? Well, to set the value, Cypess `.type` change the javascript `.value` property of the element. So let's try it with the chrome console.

Here is what happen with your examples:

![Screenshot from 2020-01-16 01-24-37](https://user-images.githubusercontent.com/8771783/72441717-43afbc00-37ff-11ea-9c93-585f5dd5f9ca.png)

We see two things:

1. The browser throw us a warning.
2. The value isn't set inside the input html element (see: [HTML Standard <input=number>](https://html.spec.whatwg.org/multipage/input.html#number-state-(type%3Dnumber)))

Also, if you manually enter the value "123-" or "1+1" and then try to get the `.value` property of your `<input>` element, you'll will get an empty string as a result.

So, we are kind of stuck between the rock and a hard place here.

And I don't see any "really" satisfying solution. Because:

1. Using the actual way Cypress `.type` set the value inside the element will not allow us to set this kind of value (even if no filter was applied on cypress side).
2. The tests cases that @jennifer-shehane provided will fail anyway. Because even if the 'real' input is typed, according to the [HTML Standard <input=number>](https://html.spec.whatwg.org/multipage/input.html#number-state-(type%3Dnumber)) there is no way for the rest of the javascript test to get this value out of the field (the only retrievable value is the sanitized one and must be a valid number).

I would really like to hear any suggestion about that topic.

**Comment by jennifer-shehane** [comment]
This is still an issue in 4.10.0.

**Comment by devtayls** [comment]
@jennifer-shehane, Has the community decided on this? I'd be happy to make the behavior match the OP. That is, allowing .type() to set the value on <input value={} /> to things that are prohibited by standard. 

This of course would break what @Bkucera wrote regarding the standards and will throw browser console errors. 

My vote would weigh in on allowing the behavior, if there isn't an overriding design value of the project. My reasoning is that since the behavior is available when manipulating the DOM (programmatically or manually) it may actually be a state that end users need to test. The fact that the state can exist and someone is asking to test it is pretty solid to me.

**Comment by jennifer-shehane** [comment]
Probably the real-events plugin does this correctly. I haven't tried though. https://github.com/dmtrKovalenko/cypress-real-events But in the end we need to implement something closer to that plugin instead of simulating the type.

**Comment by rammohankini** [comment]
I used realType() to add invalid value to number field, but should have.value assertion not considering the added value and test is getting passed .
![image](https://user-images.githubusercontent.com/72487913/165682546-89b361e3-6a4d-49c6-899e-6af103f67f88.png)

**Comment by Hellsfoul** [comment]
Sorry to bring that up again.
Same here. I have to automate testcases, with invalid inputs.
