### ISSUE TITLE
`.select()` on option list having duplicate value and / or text

### ISSUE THREAD

**Issue by ryan-m-williams** [cypress-io/cypress#6155]
This issue will be closed to further comment as the exact issue here was resolved and tested.  in [`0.19.1`](https://github.com/cypress-io/cypress/wiki/Changelog#0191-03092017).

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

_Originally posted by @jennifer-shehane in https://github.com/cypress-io/cypress/issues/554#issuecomment-570519857_

**Comment by ryan-m-williams** [comment]
It looks like the issue that @jennifer-shehane referred to is:

https://github.com/cypress-io/cypress/issues/441

In this case it's correct that the issue mentioned is resolved however a new issue was brought up here.

https://github.com/cypress-io/cypress/issues/554#issuecomment-434475750

> Are there any updates on this or workaround for selecting desired option when the text/value is duplicate?

> I have following case and cy.get('[data-cy=test_select]').select('tester') is returning
CypressError: Timed out retrying: cy.select() matched more than one option by value or text: Tester OrgAdmin


The new select() related issue is a case where there are duplicate entries in an option list and you want to select the first() one.

Since select() is an action and doesn't render a DOM element first() can't be applied afterwards. What's the correct way to handle this as far as select the first option that contains some value?

**Comment by jennifer-shehane** [comment]
@ryan-m-williams Please provide the test code to run as well as the HTML to run the tests against that demonstrates **a bug or feature request in Cypress**. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. Issue will be closed since it appears to be neither a bug nor a feature request (aka questions on use in Cypress).

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by ryan-m-williams** [comment]
Feature request may be that a .select() that returns multiple elements would render a DOM? I'll ask the question in the forums. Thank you for your quick response.
