### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vinod236** [cypress-io/cypress#6185]
When we open the mocha test case from test runner we get this error message .
![Cypress_3 8 2](https://user-images.githubusercontent.com/7825972/72610336-15d88d80-394d-11ea-9a8a-ddce6312a663.GIF)

Expected result:
   test cases should run 
Actual result:
   At of the start test case execution itself , we get error "RangeError: Maximum call stack size exceeded"

Versions :
Cypress 3.8.2
Os : win 10 Enterprise (64 bit)
Chrome : 79.0.3945.117 (64 bit)

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
