### ISSUE TITLE
Route Regex matching

### ISSUE THREAD

**Issue by Gurubg1** [cypress-io/cypress#6194]
Hi,
My App uses following url to download a json file:
/Modules/Common/config.json?1579344447406
the last number is dynamically generated. I want to stub this and load a json in my fixtures folder. I have not been able to come up with a regex for this. Any ideas?

**Comment by jennifer-shehane** [comment]
Try playing with https://regex101.com/ and testing glob patterns again Cypress.mimimatch https://docs.cypress.io/api/utilities/minimatch.html#Syntax

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
