### ISSUE TITLE
Still got "uncaught exception" after turning it off in support file

### ISSUE THREAD

**Issue by LienLotus** [cypress-io/cypress#6196]
### Current behavior:

Visit a website then click on "Play" button to play video, but got many uncaught exception:

![Screenshot from 2020-01-20 13-22-24](https://user-images.githubusercontent.com/51039899/72703440-27f24000-3b88-11ea-9939-55b04b301f31.png)

### Desired behavior:
Video can be rendered

### Test code to reproduce

1. Visit https://demo.keyos.com/customers/anevia/9972/index.dash.anevia.html
2. Play Dash manifest file to get video

![Screenshot from 2020-01-20 13-46-16](https://user-images.githubusercontent.com/51039899/72704373-3e4dcb00-3b8b-11ea-8c4c-fc75790e547e.png)

3. After click on "Play" button => no video can be rendered, see many errors in console:
![Screenshot from 2020-01-20 13-22-24](https://user-images.githubusercontent.com/51039899/72703440-27f24000-3b88-11ea-9939-55b04b301f31.png)

![Screenshot from 2020-01-20 13-25-30](https://user-images.githubusercontent.com/51039899/72703518-612ab000-3b88-11ea-91dd-29cbc0cd3f0b.png)

4. Modify /support/index.js:

![Screenshot from 2020-01-20 13-28-41](https://user-images.githubusercontent.com/51039899/72703696-ced6dc00-3b88-11ea-9295-d0db25ff6f52.png)

5. Still got the same issue 

### Versions
Cypress package version: 3.8.1
Cypress binary version: 3.8.1
Google chrome: Version 79.0.3945.88 (Official Build) (64-bit)
No issues on same Chrome version but running on my local PC (Ubuntu 18.04)

**Comment by jennifer-shehane** [comment]
Please provide all test code next time in text format so that it can be easily copy/pasted to run. 

The error is being thrown from within your application code. 

I am however able to ignore this error and continue with the tests by adding the `uncaught:exception` handler - this does not remove the fact that this uncaught exception occurs, it simply ignores it from failing the tests. 

Click on the yellow error with DevTools open to see where the error is originating from in your code and why the uncaught exception is being thrown in your application. 

<img width="647" alt="Screen Shot 2020-01-21 at 2 50 16 PM" src="https://user-images.githubusercontent.com/1271364/72787487-6c500f80-3c5e-11ea-9dba-cbefd8132175.png">


```js
Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false
})

it('plays video', () => {
  cy.visit('http://demo.keyos.com/customers/anevia/9972/index.dash.anevia.html')
  cy.get('#stream-url').clear()
  cy.get('#stream-url').type('https://irtdashreference-i.akamaihd.net/dash/live/901161/bfs/manifestBR.mpf')
  cy.get('.btn.btn-primary.js-reinit-player').click()
})
```

<img width="1164" alt="Screen Shot 2020-01-21 at 2 54 47 PM" src="https://user-images.githubusercontent.com/1271364/72787364-2c892800-3c5e-11ea-8738-0bbe8496e98f.png">

**Comment by LienLotus** [comment]
Hi  jennifer-shehane,
Did you see the video after running all test code ?
For me, after doing `cy.get('.btn.btn-primary.js-reinit-player').click()` the video still unavailable, and will get this error:
![72703518-612ab000-3b88-11ea-91dd-29cbc0cd3f0b](https://user-images.githubusercontent.com/51039899/72821673-6a5c6f80-3ca3-11ea-9034-6c30b1415adc.png)

This issue only happened if we run this script in Cypress/Chrome/Electron , for Chrome and Firefox  in my local Ubuntu, there're no problems.
Do you have any workaround for this issue?

**Comment by LienLotus** [comment]
Can not reproduce now because of license issue, change to use a new player, so don't see this error, close as the error from player source code
