### ISSUE TITLE
Refocus the main Cypress window after running all tests

### ISSUE THREAD

**Issue by UyQTran** [cypress-io/cypress#6218]
### Current behavior: 
After running the set of tests in the Cypress window in Chrome, it does not focus the window again. Therefore we have to click on the Cypress window again to be able to use hotkeys like R (rerun tests). It seems like Cypress focuses on the test page rather than the Cypress window after tests are ran.

### Desired behavior:
After running all the tests, Cypress should focus on the Cypress window instead, making hotkeys more useful.

### Test code to reproduce
Any test code. The example code provided when setting up Cypress with "cypress open" also works to reproduce.

### Versions
Cypress 3.8.2
Google Chrome 79.0.3945.117
Mac OSX Catalina 10.15.2

**Comment by UyQTran** [comment]
Here is one of the examples provided when setting up Cypress
`
context('Actions', () => {
  beforeEach(() => {
    cy.visit('https://example.cypress.io/commands/actions')
  })

  // https://on.cypress.io/interacting-with-elements

  it('.type() - type into a DOM element', () => {
    // https://on.cypress.io/type
    cy.get('.action-email')
      .type('fake@email.com').should('have.value', 'fake@email.com')

      // .type() with special character sequences
      .type('{leftarrow}{rightarrow}{uparrow}{downarrow}')
      .type('{del}{selectall}{backspace}')

      // .type() with key modifiers
      .type('{alt}{option}') //these are equivalent
      .type('{ctrl}{control}') //these are equivalent
      .type('{meta}{command}{cmd}') //these are equivalent
      .type('{shift}')

      // Delay each keypress by 0.1 sec
      .type('slow.typing@email.com', { delay: 100 })
      .should('have.value', 'slow.typing@email.com')

    cy.get('.action-disabled')
      // Ignore error checking prior to type
      // like whether the input is visible or disabled
      .type('disabled error checking', { force: true })
      .should('have.value', 'disabled error checking')
  })
})`

**Comment by jennifer-shehane** [comment]
In this case, this is due to the focus being directed to the input that was just being typed into in the test. 

It's a bit more difficult to tell in this case because the focus is on a disabled element, but if you run the test below, you can see that the focus is maintained in the currently typed input or DOM element being interacted with. 

```js
it('.type() - type into a DOM element', () => {
  cy.visit('https://example.cypress.io/commands/actions')
  cy.get('.action-email')
    .type('fake@email.com').should('have.value', 'fake@email.com')
})
```

![](http://g.recordit.co/hoKnByejEY.gif)

This is the expected behavior of Cypress. 

We cannot remove focus after every DOM element interaction and force it back to the main window because this would not mimic actual user behavior and cause a lot of broken tests if we changed this behavior. 

Refocusing the main window back after *all* of the tests are done running? I suppose this may be possible, but this would be pretty low priority.

**Comment by UyQTran** [comment]
Ah I see, and I can understand the priority. I just find that if you have to click and refocus on the main window every time you want to use a hotkey, then it is faster to just click on the buttons instead of the hotkeys. Rendering the hotkeys almost useless in most cases. Almost since I guess for people that have motor issues with aiming the computer cursor, will still have use for it.
