### ISSUE TITLE
CypressError: Timed out retrying: Expected to find element: 'ls-table-body > :nth-child(1) > :nth-child(2)', but never found it.

### ISSUE THREAD

**Issue by manabshy** [cypress-io/cypress#6224]
I get the Error  executing cypress tests in the gitlab pipeline. Locally, they all pass. What is the reason ?

```
CypressError: Timed out retrying: Expected to find element: 'ls-table-body > :nth-child(1) > :nth-child(2)', but never found it.
```

I am doing AS below
```js
  And('I load the forecast page', () => {
  if (newCampaign) {
    cy.get('ls-button.ng-star-inserted > .btn-full').click({ force: true });
  }
});

Then('The forecast page should load', () => {
  cy.wait('@forecast')
    .its('status')
    .should('be', 200);
  cy.url().should('include', '/forecast');
  cy.wait(1000);
  cy.get('ls-table-body > :nth-child(1) > :nth-child(2)')
  .as('costMarket')
  cy.get('@costMarket').then(($td) => {
    expect($td).to.contain('GBP');
    expect(extractNumericalValue($td.text())).to.be.greaterThan(0);
  });
});
```

- What I already tried
1.
```js
  cy.get('ls-table-body > :nth-child(1) > :nth-child(2)')
  .as('costMarket')
  cy.get('@costMarket').then(($td) => {
    expect($td).to.contain('GBP');
    expect(extractNumericalValue($td.text())).to.be.greaterThan(0);
  });
```

2. use `cy.wait`

Thank you

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

There is no provided application to run the test code against, so there's no way to assess why this error is throwing or if this is a bug in Cypress.

Please comment in this issue with a reproducible example and we will consider reopening the issue.

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
