### ISSUE TITLE
cypress connectivity with google maps

### ISSUE THREAD

**Issue by ranaec21** [cypress-io/cypress#6248]
### Current behavior:

my application using google maps in one of the screens and when we invoke application this page gets loaded However to cover BDD when We invoke that page using Cypress script then page itself is not loaded and we get error like "unable to load google maps API".
We initially thought it could be proxy issue and tried enabling proxy also However still issue persists. Any help on this would be appreciated,

### Desired behavior:

When we invoke application then that screen along with google map should be loaded. 

### Test code to reproduce

Since issue is on client code We can'tpost here However any reference on similar issue should be good. Does Cypress work with google maps ?

### Versions

windows 10

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.
