### ISSUE TITLE
wrap(JQuery) does not retry for assertions

### ISSUE THREAD

**Issue by mbolotov** [cypress-io/cypress#6252]
### Current behavior:

`cy.wrap` of a JQuery element does not retry for chained assertions, e.g. for 'have.length'

![image](https://user-images.githubusercontent.com/19785715/73190199-a9bd0d00-4136-11ea-9fcd-1ade991390c7.png)

### Desired behavior:

`cy.wrap` of a JQuery element retries for chained assertions as stated in the docs

### Test code to reproduce
```js
 cy.visit('https://example.cypress.io/utilities').then(() => {
      cy.get('.list-group li').first().click()
 })
 cy.get(".list-group .active").then(() => {
   cy.get('.list-group li').last().click()
   cy.get('.list-group .active').should('have.length', 2) // cy.get retries
   cy.wrap(Cypress.$('.list-group .active')).should('have.length', 2) // cy.wrap does not retry
 })
```
### Versions

Operating System: Win10 Pro 1909
Cypress Version: 3.8.1
Browser Version:  Chrome 79.0.3945.130

**Comment by jennifer-shehane** [comment]
The error message states `Timed out retrying`, so the `cy.wrap()` is indeed retrying, but not reaching the conditions of the assertion within the retry time, which by default is the `defaultCommandTimeout` of 4000. Try increasing the `timeout` option to a higher number to retry for a longer length of time. 

You also never need to use a `.then()` as you have after the `visit` or the `cy.get()`. The next command will only run after the previous commands has resolved because [commands run serially](https://on.cypress.io/introduction-to-cypress#Commands-Run-Serially) Below works exactly the same. 

I'm not sure why you're using jQuery wrap instead of just `cy.get()`, but the code above cdoes not work because of [Cypress being asynchronous](https://on.cypress.io/introduction-to-cypress#Commands-Are-Asynchronous). So the `Cypress.$('.list-group .active')` returns `undefined` because it is evaluated literally before the `cy.visit()` even executes, so you need to put this within a `.then()` to ensure it is evaluated when the DOM is ready. 

```
it('runs', () => {
  cy.visit('https://example.cypress.io/utilities')
  cy.get('.list-group li').first().click()
  cy.get(".list-group .active")
  cy.get('.list-group li').last().click()
  cy.get('.list-group .active').should('have.length', 2).then(() => {
    cy.wrap(Cypress.$('.list-group .active')).should('have.length', 2)
  })
})
```

I would strongly suggest fully reading our [Intro to Cypress](https://on.cypress.io/ntroduction-to-cypress) guide before moving forward.

**Comment by mbolotov** [comment]
> Try increasing the `timeout` option to a higher number to retry for a longer length of time.

It does not make sense. Test selects the both element in less than a second, so the default timeout must be enough.
 
>  So the Cypress.$('.list-group .active') returns undefined

That is not true. I would suggest you to look at the screenshot one more time:
![image](https://user-images.githubusercontent.com/19785715/73282313-6fb93d00-4202-11ea-9eb3-7bec595802fb.png)

>  so you need to put this within a .then() to ensure it is evaluated when the DOM is ready.

This is actually in place:
![image](https://user-images.githubusercontent.com/19785715/73282457-bb6be680-4202-11ea-95a9-9779f8fdb202.png)

Having said this, I found that it seems the only 'have.length' assertion fails in conjunction with cy.wrap. All others are able to reflect the changes in dom while retrying.
