### ISSUE TITLE
Show list of top failing tests in dashboard

### ISSUE THREAD

**Issue by infi-pc** [cypress-io/cypress#626]
### Is this a Feature or Bug?
feature

### Current behavior:
Didn't find anything like that

### Desired behavior:
Add a list of failing tests ordered by number how often they are failing. 

### Additional Info (images, stack traces, etc)
The problem what we are trying to solve is that we have a lot of false-alerting tests and we would like to identify which tests are failing most often so we can prioritize which tests we need to fix.
Right now we just randomly report it to the author of the test if our CI fails too often with the same test.

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.
