### ISSUE TITLE
Empty parameter sent to API

### ISSUE THREAD

**Issue by innamalyar** [cypress-io/cypress#6266]
### Current behavior:
I have a page with some fields, input text field which is not mandatory and submit button that triggers the API POST request. The problem is that when i am typing the string in the input field, it appears as expected, but when i am clicking at the submit button, the value of the text field is not a part of the request, and instead of something like that: 
![image](https://user-images.githubusercontent.com/45535777/73274103-aafd4100-41ed-11ea-8e57-e1114edeb532.png)
it sent like:
![image](https://user-images.githubusercontent.com/45535777/73274722-b3a24700-41ee-11ea-98c9-2e7f3ecfb60e.png)

### Desired behavior:

On submit button, if the input field has value it should be a part of the request
When i am repeating the same manually not via cypress tool, the request sent correctly with all parameters

### Versions
cypress: 3.8.3
Browser: Chrome Version 79.0.3945.130 (Official Build) (64-bit)
OS: Windows 10, 64-bit
Node.js: v11.6.0

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. There could be a lot of variables involved here, so we need some HTML to visit against with the test code to reproduce. 

This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Comment by innamalyar** [comment]
Actually I found the problem. When cypress is typing in this text input field, the onChange angular methos was not triggered. I had to add the following code:
`export function enterPlayerName(playerName) {
    it ('Type the player name in the input field: ' + playerName, () => {
        cy.get(inputPlayerLocator).type(playerName);
        cy.get(inputPlayerLocator).trigger('change');  //new line
    });
    checkPlayerValue(playerName);
}`
