### ISSUE TITLE
Searching for a solution to replace DOM elements

### ISSUE THREAD

**Issue by Skhoshhal** [cypress-io/cypress#6289]
### Current behavior:

As we know cypress doesn't support  browser tab changes and for link we can change the target to `_self`, my Problem is with button, because button has no `target` attribute.

### Desired behavior:

 I am searching for a method to change button to link. I write the code below as command and I am using it but it say ```Cannot read property 'replaceChild' of undefined ```

### Test code to reproduce

`command.js`

```js
Cypress.Commands.add('changeButton', (element) => {
  cy.get(`.${element}`).then(($el) => {
    const aEl = document.getElementsByClassName('offer-tile__button offer-tile__button--success');
    const newEl = document.createElement('a');
    newEl.setAttribute('data-cy', 'offer-tile-to-booking');
    newEl.setAttribute('class', 'offer-tile__button--success');
    newEl.setAttribute('href', 'https://travel-test.lan/1522568');
    newEl.setAttribute('target', '_self');
    newEl.innerHTML = 'Zur Buchung';
    aEl.parentNode.replaceChild(newEl, aEl);
  });
```
`test.ts`

```ts
Then('change the button to link', () => {
    cy.changeButton('offer-tile__button--success')
});
```

### Versions
"cypress": "3.8.1"

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
