### ISSUE TITLE
scrollIntoView resets the scroll position before running next command/assertion

### ISSUE THREAD

**Issue by nishants** [cypress-io/cypress#6301]
### Current behavior:

`scrollIntoView` resets the scroll position before running next command/assertion.

### Desired behavior:

After invoking `scrollIntoView`, the scroll position should be retained so that element is visible for next command.

### Test code to reproduce

To reproduce this, create a webpage larger than viewport size, make sure the .some-element is at the bottom of the page and run :
```javascript
cy.get(".some-element").scrollIntoView();
cy.screenshot();  // Element is not visible in screenshot
```

### Versions
Checked in version 3.8.2 and 3.4.1. This behaviour is observed with both chrome and electron runners on on Windows 10 and OSX Mojave .

**Comment by jennifer-shehane** [comment]
I'm unable to recreate without the HTML and test code provided to test against.

My attempt to repro. 

`index.html`

```html
<html>
<body>
  <p style="background-color: red; height: 1000px">Donec ullamcorper nulla non metus auctor fringilla.</p>
  <div class="some-element" style="background-color: blue;">Lorem ullamcorper nulla non metus auctor fringilla.</div>
</body>
</html>
```

`spec.js`

```js
it('screenshot after scroll', () => {
  cy.viewport(1000, 500)
  cy.visit('index.html')
  cy.get('.some-element').scrollIntoView()
  cy.screenshot()  // Element is not visible in screenshot
})
```

Screenshot taken includes the element at bottom of page. 

![screenshot after scroll (1)](https://user-images.githubusercontent.com/1271364/73714530-73d3e600-473f-11ea-8dfc-e01a9abcf6c9.png)


Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue.

**Comment by nishants** [comment]
I tried to reproduce this in  an isolated setup without success:
An html page with non scrollable body
html
```html
<html>
  <body style="height: 100vh">
  <div id="container">
    <h1 style="padding-bottom: 200vh">This is head</h1>
    <div id="footer">This is feet</div>
  </div>
  </body>
</html>
```
Scroll to element and trigger click :
javascript

```javascript
describe('Selectors and assertions', () => {
  it('should scroll to element and take screenshot', () => {
    cy.visit('http://127.0.0.1:8080');
    cy.get('#footer').scrollIntoView();
    cy.screenshot({capture: 'viewport'})
  })
});
```
Code here : https://github.com/nishants/cypres-scoll-bug
This works just as expected. This is not a cypress bug.

Thanks !
