### ISSUE TITLE
Make it possible to support no_proxy environment variable for download

### ISSUE THREAD

**Issue by lee-thurston** [cypress-io/cypress#6304]
### Current behavior:

When downloading Cypress, the no_proxy environment variable is not taken into account.

![image](https://user-images.githubusercontent.com/9371059/73665135-86471480-4698-11ea-94cc-011e58c21275.png)

### Desired behavior:

When downloading, I want Cypress to be able to use the no_proxy environment so that it doesn't go through the company proxy. Using CYPRESS_INSTALL_BINARY and downloading manually isn't really a solution as we don't want CI/CD build agents to download cypress every time. Installing cypress on every build agents doesn't seem like the best solution either.

### Versions
Cypress: 3.8.3

**Comment by flotwig** [comment]
@lee-thurston There is currently no `NO_PROXY` support in the CLI, as you've noted.

You can try unsetting your proxy environment variables, so Cypress doesn't use them. Here are the variables that are considered:

https://github.com/cypress-io/cypress/blob/3fdc965655abd3a185f6d190568b407d970ff744/cli/lib/tasks/download.js#L19-L27

So, on macOS/Linux, this should work:

```
HTTPS_PROXY= HTTP_PROXY= https_proxy= http_proxy= npm_config_https_proxy= npm_config_proxy= cypress ...
```

**Comment by lee-thurston** [comment]
Ahh yeah, I tried doing that but only supplied the lower case version. Using that has made it work, thanks.

**Comment by konradtoenz** [comment]
@flotwig, do we need this at all?

> https://github.com/cypress-io/cypress/blob/3fdc965655abd3a185f6d190568b407d970ff744/cli/lib/tasks/download.js#L19-L27

When I set my environment variables like this:
```
HTTP_PROXY="http://wont.work"
NO_PROXY="download.cypress.io"
```
`node index.js --exec install` doesn't work.

After I replace the above code with
```
const getProxyUrl = () => {
  return undefined;
};
```
it works.

It looks as if the the `request` module figures out the proxy configuration by itself, also being aware of `NO_PROXY`. See the [README](https://github.com/cypress-io/request/blob/74c2136945928ef0ed7545273176fc154c34233d/README.md) and

https://github.com/cypress-io/request/blob/74c2136945928ef0ed7545273176fc154c34233d/lib/getProxyFromURI.js#L40-L77

**Comment by jennifer-shehane** [comment]
@konradtoenz If you are behind a corporate proxy, this code reading the HTTP_PROXY variables would be required to download Cypress. Did you test behind a properly configured corporate proxy?

**Comment by konradtoenz** [comment]
@jennifer-shehane I dont't argue that the `HTTP_PROXY` environment variable has to be read somewhere. But to me it looks like the `request` module does that already:

https://github.com/cypress-io/request/blob/74c2136945928ef0ed7545273176fc154c34233d/lib/getProxyFromURI.js#L40-L77

The code in question seems to override this without reading the `NO_PROXY` variable.

Case in point, when I have this:
```
HTTP_PROXY="http://wont.work"
NO_PROXY="download.cypress.io"
```

```
const getProxyUrl = () => {
  return undefined;
};
```

`node index.js --exec install` downloads properly as the invalid proxy configuration is ignored by `NO_PROXY` (by the `request` module). When I remove the `NO_PROXY` variable, it doesn't download,  because the `request` module also reads `HTTP_PROXY`. So I think the extra code is not needed and might even make things worse by not reading `NO_PROXY`.

**Comment by westarne** [comment]
I've encountered the same problem when installing cypress. The problem is that we don't have a corporate proxy but need to load some dependencies via proxy from a separate registry. So our current process to install npm dependencies is

```sh
HTTP_PROXY=http://localhost:7001 HTTPS_PROXY=http://localhost:7001 NO_PROXY=localhost,.com,.io npm install
```
(We pretty much have everything required in the NO_PROXY except for the registry needing to be proxied)

This usually works fine, but with this issue in the download script we were not able to install the dependencies correctly as either the dependencies needing to be proxied fail or cypress.

So I've added a PR tackling the issue. Also I've added a reason why I've still overwritten the proxy which would have been detected in the request module, as mentioned by @konradtoenz.
