### ISSUE TITLE
How to verify/validate the value against api Response Array

### ISSUE THREAD

**Issue by Kishorekumar2789** [cypress-io/cypress#6308]
Hi @jennifer-shehane, How can I verify an email id in api response which(email-id) is created from UI.

Response return as an array but how to compare the created email id with response data?

Sample Code:
```js
  cy.server();
  cy.route('GET', 'ENDPOINT').as('userlist');
  /*email id created in UI/
  cy.wait('@userlist').then(function(res) {
    cy.log('Response: ' + res.responseBody);
  });
```
Sample Response:
```
[
  {
    "id":"id1",
    "emailid":"emailid1"
  },
  {
    "id":"id2",
    "emailid":"emailid2"
  }
]
```

![image](https://user-images.githubusercontent.com/42167657/73685893-43e8fc00-46c7-11ea-9303-26e6487116b7.png)

**Comment by GregLahaye** [comment]
You just want to find if an email id is in the response data? You could do something like this:

`cy.wrap(response.responseBody.filter((user) => user.emailId === myEmailId)).should("have.length", 1);`

This will filter out all of the users that don't have the emailId you are looking, returning an array of matching users. It then wraps the resulting array and asserts that it's length is one.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
