### ISSUE TITLE
Test case fails if verifying that element is no longer is visible if webSecurity is turned off

### ISSUE THREAD

**Issue by testquantilope** [cypress-io/cypress#6332]
### Current behavior:
If you are verifying that an element that doesn't exist (or no longer exists) is not visible, the test case will fail if you have webSecurity enabled and pass if webSecurity is turned off.

![image](https://user-images.githubusercontent.com/35334883/73871709-53c62480-481c-11ea-8ae1-3a07ee1997de.png)

### Desired behavior:
The webSecurity settings should not impact in this case if the test passes or fails. It should either always fail or always pass.

### Test code to reproduce

```js
describe('Repro', function() {
  it('repro', function() {
    cy.visit('https://www.cypress.io')
    cy.get('.some-random-class').should('not.be.visible')
  })
})
```

cypress.json:
```json
{
  "chromeWebSecurity": false
}
```

### Versions
3.8.2

**Comment by testquantilope** [comment]
Workaround is to check that the element doesn't exist rather than that it is not visible.

Which one of the 2 behaviors is the correct one I don't really mind, as long as it is consistent ;)

**Comment by jennifer-shehane** [comment]
This is very weird. I can confirm this is the case, I also ran the test randomly over 50 times for each just to make sure this wasn't some weird case where it randomly fails / passes. 

I tried to reproduce this on a very simple `index.html` file and was unable to reproduce, so something about the public website is important here. 

`spec.js`

```js
it('repro', () => {
  cy.visit('https://www.cypress.io')
  // test below fails with chromeWebSecurity true
  // passes with chromeWebSecurity false
  cy.get('.some-random-class').should('not.be.visible')
})
```

## `chromeWebSecurity: true`

<img width="440" alt="Screen Shot 2020-02-10 at 11 16 34 AM" src="https://user-images.githubusercontent.com/1271364/74121658-d5d89380-4bf6-11ea-9fa0-b93cc8acac86.png">


## `chromeWebSecurity: false`

<img width="439" alt="Screen Shot 2020-02-10 at 11 17 22 AM" src="https://user-images.githubusercontent.com/1271364/74121685-f0127180-4bf6-11ea-9791-3bff097c55d3.png">

## What is expected behavior

In this case, the test should fail. The `cy.get()` should do a check that the element exists before moving on to the assertion. However, there is a bug involving this currently where this is not the case, detailed here: https://github.com/cypress-io/cypress/issues/205

We really wanted to get in https://github.com/cypress-io/cypress/pull/3268 for 4.0, but it was a bridge too far unfortunately. 

**This issue**, however, is very weird. That the introduction of the `chromeWebSecurity` flag would have any influence over this is not intended behavior.

**Comment by BlueWinds** [comment]
I *believe* this will be resolved in Cypress 12 by some of our upcoming changes. Since this issue is fairly old and innactive, I'm going to close this as 'resolved in Cypress 12' - if it isn't, I'd appreciate a comment here and I'll repoen, or a new issue tested against the latest version.
