### ISSUE TITLE
Plugins need to know the Cypress version running

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#6352]
Cypress v4

We don't include the Cypress version in the config passed to the plugins, but it would be really nice, especially to handle breaking changes.

┆Issue is synchronized with this [Jira Features](https://cypress-io.atlassian.net/browse/TR-135) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Oh, right, can’t use Cypress.version here 🤔

**Comment by sainthkh** [comment]
@jennifer-shehane 

It's because they're loaded differently.

Runner is loaded here.

https://github.com/cypress-io/cypress/blob/4618650118bb392e314016c6045e627e7947160a/packages/server/lib/project.js#L135

And version is added here:

https://github.com/cypress-io/cypress/blob/4618650118bb392e314016c6045e627e7947160a/packages/server/lib/controllers/runner.js#L33

But the plugin is loaded here:

https://github.com/cypress-io/cypress/blob/4618650118bb392e314016c6045e627e7947160a/packages/server/lib/project.js#L124

Because of that, `version` is not added to the `config` object.

Fixed the issue at #7925
