### ISSUE TITLE
cy.wait(50000) goes on.... infinitely

### ISSUE THREAD

**Issue by poojyasankar** [cypress-io/cypress#6362]
### Current behavior:

I am trying to run this test that will run after the sign-in button is pressed. It takes about 50 seconds for the homepage to initialize.

So I put a `cy.wait(50000)` and it seems to go on forever. When I tried `cy.wait(40000)`, it works just fine but the component I want to test isn't loaded by then, although the page is in a loaded state, so I couldn't use the aliases way of waiting.

Could it be related to the XHR looping? But then it happens only when the wait time is 50s or more. I didn't test any other mid region between 40s and 50s
![image](https://user-images.githubusercontent.com/60782196/74031943-70e52980-49bb-11ea-8edf-a85f53edda79.png)

### Desired behavior:

Desired behavior is, it should wait only 50 secs. 

### Test code to reproduce

```js
describe('ConnectTest1',()=>{
    beforeEach(()=>{
        cy.visit('3d.connect.trimble.com');
        cy.get('#user').type(user.email);
        cy.get('#password').type(user.password);
        cy.get('#chkRemember').click();
        cy.get('#signin').click();
        cy.wait(50000);
    })
    it('Test1', () => {      
        //cy.get('#view-inner-container > div.row > div > div').click(10, 10);
        //cy.contains('[title=trimble-tabs-selector-button]').click();    
    })
})
```

### Versions

Chrome 79, Cypress 3.8.3

**Comment by jary91** [comment]
Hi, i have similar or maybe the same issue and i'm sure there is something wrong in cypress.
I faced this timeout on big request response (over 15 mb) in my current project. I spent several ours to find the solution... without success. 
Now i'm sure this is the cypress issue because the same occurs on completely different environment. We already created test environment with similar big response: https://github.com/sterenczak-marek/go-long-request. It will help you to re-create the issue.
E.g. try to send easy GET in POSTMAN and do the same in Cypress. Postman will complete the request in ~30 seconds, cypress will fail with timeout (even after 10 minutes of waiting). responseTimeout will solve this problem.

the code: 

`describe('test', () => {
it('ds', () => {
		cy
		.request({
			url: 'https://warm-atoll-78694.herokuapp.com/',
		})
	});	
});`

**Comment by jennifer-shehane** [comment]
I cannot recreate the issue of `cy.wait(50000)` not completing. It runs to completion within 50 seconds. 

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
  <input />
</body>
</html>
```

`spec.js`

```js
it('repro', () => {
  cy.visit('index.html')
  cy.get('input').click()
  cy.wait(50000)
})
```

<img width="444" alt="Screen Shot 2020-02-10 at 1 16 21 PM" src="https://user-images.githubusercontent.com/1271364/74126917-8d75a180-4c07-11ea-9751-f4839567ee71.png">

@poojyasankar Likely this is not related to `cy.wait()` and something else. Please provide a fully reproducible example so that we can continue investigating and we will consider reopening.

@jary91 You're issue is likely unrelated to this, but we need a fully reproducible example including Cypress tests that we can run on our machine to reproduce.

**Comment by poojyasankar** [comment]
@jennifer-shehane What I wrote was the fully reproducible example, and I see that you tried on a static html. It's probably something else in the page I'm visiting that triggered the infinite waiting.
I can investigate a bit more on the URL I'm testing, if you would be able to tell me what to look for.

Thanks.
