### ISSUE TITLE
Cypress  considering typeof null as string instead of object - resulting in failing of test cases

### ISSUE THREAD

**Issue by AB1519** [cypress-io/cypress#6366]
I am trying to load a component if the service response is null, but cypress is failing the test because it is considering the response as a string.

eg: My response 
```js
{
   value1: true,
   value2 : null
}
```

CODE: 
```js
if (value2 === null) {
  //do something
} else {
  //do something
}
```

RESULT:  Able to load when checking if the value2 is equal to `null`

Cypress RESULTS:  Unable to load the page because cypress is considering the value2 as a string. i.e value2 === null , it is considering `null` as a string.

Can anyone help me with this 
using cypress version : 3.5.0

Thanks!

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

I do not know where the `response` code is within your tests (or is it in fixtures) and I do not know where the if statements are written (is this in tests or application code)? Please provide a fully reproducible example with the cypress test to run.

I will say that the response is a JSON response, so you likely need to use `JSON.parse()` to convert the values to non-strings before your check. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
