### ISSUE TITLE
Calling window function with RegExp argument results in wrong instance type

### ISSUE THREAD

**Issue by Zharktas** [cypress-io/cypress#6382]
### Current behavior:

Calling browser side javascript function in Cypress with RegExp argument results the argument in browser javascript to be wrong instance type.

### Desired behavior:

The argument should be instance of RegExp.

### Test code to reproduce

Test page, calling foo(/asd/) in console prints true to the page.
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="fixture"></div>
<script type="application/javascript">
    function foo(arg) {
        if (arg instanceof RegExp) {
            let content = document.createTextNode("true");
            document.getElementById('fixture').appendChild(content)
        } else {
            let content = document.createTextNode("false");
            document.getElementById('fixture').appendChild(content)

        }
    }
</script>
</body>
</html>
```

Cypress test which fails as false is printed to page.
```javascript
context('Window', () => {
    it('Should print true to page', () => {
        cy.visit('./index.html')
        cy.window().then(win => {
            win.foo(/asd/);
            cy.get('#fixture').should('contain', 'true');
        })
    })
})
```

### Versions

Tested with Cypress 3.8.3 - 4.0.1 on Windows and Linux, with electron, chrome and firefox.

**Comment by jennifer-shehane** [comment]
I can recreate this behavior with the given example.

**Comment by jennifer-shehane** [comment]
This is happening because you're constructing the RegExp in the Test Runner window (which is a different window than your application under test window) - `instanceof` will only look at the host object that created it, since they’re 2 different windows it will be false. It’s the exact same behavior that would happen when having an iframe within another window frame - `instanceof` won’t work for this check. 

This is why instanceof is not the best way to do type detection. I'd recommend using lodash or a method similar to what they use to detect the type of the value. http://tobyho.com/2011/01/28/checking-types-in-javascript/ (across windows behavior is explained in `Cross-window Issues of instanceof` section)

**Comment by Zharktas** [comment]
Ah, thanks. I assumed it was cypress issue as I was porting old tests which were run in the same window context, but apparently I was wrong. Sorry about this.
