### ISSUE TITLE
Cypress 4.0.1 - Electron is 1.5x slower in a test spec

### ISSUE THREAD

**Issue by sandrina-p** [cypress-io/cypress#6388]
# Current behavior:

In our project, we are updating Cypress from 3.5 to 4.0.1. See PR https://github.com/okTurtles/group-income-simple/pull/829

The same test spec "Large Group" takes 2:29m to run instead of 1:36m. The other specs take the same time. See [run 284 - @3.5](https://dashboard.cypress.io/projects/q6whky/runs/284/specs) vs [run 285 - @4.01](https://dashboard.cypress.io/projects/q6whky/runs/285/specs). 

### Desired behavior:

All specs should take the same time.

### Test code to reproduce

1. Clone our project and [checkout the PR](https://github.com/okTurtles/group-income-simple/pull/829) (or master to see v 3.5.0)
2. Install dependencies `npm install`
3. Run the project `grunt dev`
4. In another terminal run cypress `npm run cy:open`
5. Run the test step "Group Large" on Electron.

The test in the spec taking too long is located at `test/cypress/integration/group-large.spec.js`. See [file here](https://github.com/okTurtles/group-income-simple/blob/820cdb2511a4c2c0016426a23cc1b7ce05c64d66/test/cypress/integration/group-large.spec.js#L22)

```js
  it(`A group with ${groupLength} members shows correctly the pledging month overview widget`, () => {
    for (let i = 2; i <= groupLength; i++) {
      // The member joins the group through an invitation...
      cy.giAcceptGroupInvite(invitationLinks.anyone, {
        username: `user${i}-${userId}`,
        groupName,
        bypassUI: true,
        actionBeforeLogout: () => {
          if (i > 3) {
            cy.getByDT('contributionsLink').click()
          }
          cy.giAddRandomIncome()
        }
      })
    }

    cy.giLogin(`user1-${userId}`)
    cy.giAddRandomIncome()
    cy.get('.graph-bar')
      .should('have.length', groupLength)
    cy.giLogout()
  })
```

If anything else is missing, please let me know.

### Versions

- Cypress 3.5 and 4.0.1
- Browser Electron 72 and 78 (maybe that's the reason?)
- OS Ubuntu 14.04

**Comment by Olgagr** [comment]
We have the same issue. However, we noticed the speed tests degradation from version 3.8.2 to 3.8.3 (15 minutes slower). We thought that maybe the speed improves in version 4 but it is not.

**Versions**
* Cypress 3.8.2 to 4.0.1
* Electron 78 (headless)
* Doker image: cypress/base:10

**Comment by slava-44** [comment]
I have the same problem on Chrome: my tests takes 12 min on Cypress 3.8.3 and 19 min on Cypress 4.0.1

**Comment by oneumyvakin** [comment]
In compare with 3.6.1 we have the same issue with slowing down 15 tests from 1 min 50 sec to 2 min 50 sec - which is very significant for us.

**Comment by samar-77** [comment]
Same here:

cypress run --headless --browser chrome

Cypress 3.8.3 with Headless chrome 80 --> specs run in 2:30
Cypress 4.0.1 with Headless chrome 80 --> specs run in 7:35

**Comment by jasoncastro2215** [comment]
current version has lots of bugs

**Comment by Thundix** [comment]
Hello,

For information, I have the same issues as Olgagr, performance drastically slowdown when upgrading above 3.8.2 (3.8.3 + 4.0.2 tested)

I see network calls for static resources are very slow (css, png,...)

I'm running on Windows

Now, on CI, which is running on Linux, no degradation with 4.0.2 nor 3.8.3

But I cannot migrate the test to fit 4.0.2 as it's really too slow in local :(

(a bit like before this update https://www.cypress.io/blog/2019/05/22/how-we-improved-network-speed-by-300-in-cypress-3-3-0/)

I'm for the moment downgrading to 3.8.2, would be glad to have an update on this

**Comment by Thundix** [comment]
For info, it's actually working on my personal PC

We are using px software to bypass the proxy in local, I'm suspecting an issue with this

Will keep posted here if I find a workaround

**Comment by kriegster108** [comment]
Tried upgrading to 4.1.0 today after coming from 3.8.0 and got horrendus performance problems on both GUI and headless mode. Went from 10min runtime to 30Min+. Had to downgrade back to 3.8.0

**Comment by samar-77** [comment]
Just updated Cypress to 4.3.0 on my Windows 10 machine.

Running with Chrome 80 headless and Cypress 3.8.3 => 3.47 minutes
Running with Chrome 80 headless and Cypress 4.3.0 => 16.10 minutes

**Is there any update on this, Cypress team?**
Can't really benefit from any Cypress updates from now on...

B.t.w. Going to a Linux machine is not an option at the moment ;-)

**Comment by vjau** [comment]
> B.t.w. Going to a Linux machine is not an option at the moment ;-)

Don't bother, it's the same thing.

**Comment by kriegster108** [comment]
tried with Cypress 4.5 today, and the performance is still extremely slow. each XHR request my client is trying to make takes FOREVER to resolve and the entire runner is just frozen up. Our organization is still on 3.8.0 because of this. I dont know if i can get a working example to use but i'll see.

**Comment by flipace** [comment]
Same here - we've been waiting with the update for quite some time, but it seems there is no insight on this from the cypress team still?

**Comment by yizha** [comment]
3.1.3 --> 4.5.0
155 passing (7m) --> 155 passing (14m)

**Comment by MoRTDooM** [comment]
Is there any future plan to fix the timing issue?... 
In our organisation we have not updated since 3.4.1 as now it would not make much sense to move to 3.7 which seems to have still a good performance, but cypress 4.7 has just been released and there's no sign of the timing issue being addressed.

**Comment by fsnopek** [comment]
Same in our organisation. We're still running on `3.7.0` because of the performance drop.

We've ran same 5 jobs in TeamCity on the same agent for `3.7.0` and `4.7.0` (following [Migration Guide](https://docs.cypress.io/guides/references/migration-guide.html#Migrating-to-Cypress-4-0)) and had following results:
![comparison](https://user-images.githubusercontent.com/36360797/83386308-1f89fb80-a3eb-11ea-9416-8d1bdcb58563.png)

**Comment by simologos** [comment]
Same here. Since we are using Cypress to test an application which controls phone calls, we unfortunately rely on timing (calls only ring for 10 seconds for example). Upgrading to 4+ (even 4.7) brakes half of our existing test.

Our dev machine + CI is also windows based, and tests are running at least 3-5 times slower.
On our end it does not matter if we run the tests with Chrome, Firefox or Electron. Tests which took previously 8s to complete, now take ~30s.

Happy to share a debug log or other information.

**Comment by fsteinbauer** [comment]
Hi @jennifer-shehane,
do you know if there are any updates from the Cypress Developers?
We are currently executing more than 6000 tests nightly and this would quite significantly slow down our execution.

We would be happy to provide more info information or help fix this topic.

**Comment by samar-77** [comment]
Hi @jennifer-shehane or any other Cypress developer.
Is there any news about this?
Seems that more than a few organisations are impacted by this performance issue.

Is there something you can say about when you going to look into this?

**Comment by jennifer-shehane** [comment]
### The issue

From the comments, there have been various mentions of performance hits:

- 3.5.0 to 4.0.1 (52 secs slower) https://github.com/cypress-io/cypress/issues/6388#issue-562431428
- 3.8.2 to 3.8.3 (15 mins slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-584060837
- 3.8.3 to 4.0.1 (7 mins slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-584316549
- 3.6.1 to 4.0.1 (1 min slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-584510564
- 3.8.3 to 4.0.1 (5 mins slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-585285858
- 3.8.2 to 3.8.3 Window only on px software as proxy in local (slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-587579383
- 3.8.0 to 4.1.0 (14 mins slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-595044452 - this sounds identical to this issue https://github.com/cypress-io/cypress/issues/6783
- 3.8.3 to 4.3.0 (12.5 mins slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-607184208
- 3.8.0 to 4.5.0 (slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-622580449
- 3.1.3 to 4.5.0 (7 mins slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-629594823
- 3.7.0 to ?.?.? (slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-634628677
- 3.7.0 to 4.7.0 (4 mins slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-636671318
- ?.?.? to 4+ (slower) https://github.com/cypress-io/cypress/issues/6388#issuecomment-637055543

Some people mention 3.8.3 being the breaking version, while others mention a version greater than 3.8.3 being the introduction of the performance issue. 

Additionally there is variation in mentioning which browsers and environments this happens on among the comments although the majority to mention Electron. 

From this, there can't be any real determination on which version, environment, or test code to focus on to narrow down the issue. 

### Related issues

Your issue may have already been identified elsewhere, please refer to those issue if your issue looks similar. 

- Tests slow down over time when performing several XHR requests calls in single test https://github.com/cypress-io/cypress/issues/6783
- Running large amount of DOM related Cypress commands will freeze/slow up the Test Runner, likely due to visibility checks https://github.com/cypress-io/cypress/issues/6967
- Performance issues when iterating over large object. https://github.com/cypress-io/cypress/issues/6944
- 3.8.0 Regression: Tests slow down after failing tests when accessing request body https://github.com/cypress-io/cypress/issues/6881
- 3.8.0 Regression due to Electron upgrade: Several commands in a single test slow down over time, likely due to visibility checks. https://github.com/cypress-io/cypress/issues/5987

### We need a reproducible example

The original provided example is not runnable (the `grunt dev` task fails on the `rollup:watch` task).

I don't doubt that there is some performance regressions, but **we can't identify it without a reproducible example**.

Please comment in this issue with a reproducible example - one that shows marked performance issues in on specific version of Cypress versus an older version so that we can investigate.

**Comment by sandrina-p** [comment]
@jennifer-shehane , what error exactly do you have when running `grunt dev`?

**Comment by MoRTDooM** [comment]
I have now been testing v5.0.0. and I do not see any significant improvement in performance to what has been discussed in this thread... 
Has anyone have any clue to how could it be possible to have the same performance in all these new versions matching the performance in the old versions that we have been talking about... I would very much like to be able to update to recent version but I cannot compromise the overall performance doing it...

**Comment by denisLoncaric** [comment]
Tried with cypress 5.0.0 on macOS Catalina 10.15.2.

Running with Electron 78 headless and Cypress 3.8.3 takes 05:23 minutes
Running with Electron 83 headless and Cypress 5.0.0 takes 12:04 minutes

We would like to update the package for quite some time now, any updates here?

**Comment by andrewmtam** [comment]
Building off of this thread: https://github.com/cypress-io/cypress/issues/2970#issuecomment-589082328

we tried setting `overflow:hidden` to the command log only when the test is run in CI (via checking environment variables), and this has yielded large performance benefits when running tests through CI.

```javascript
const sidebar = window.parent.document.querySelector('.reporter-wrap .container');
if (sidebar) {
    sidebar.setAttribute('style', 'overflow: hidden;');
}
```

On cypress@3.4.1, our test suite took about 1.75hrs.
On cypress@5.1.0 without these changes, the test suite timed out at 3hrs+
On cypress@5.1.0 with these changes, we were back down to 1.5hrs

Of course this isn't entirely robust as the UI can change in future versions, and it doesn't necessarily fix the underlying issue, but it enabled us to upgrade cypress from 3.4.1 to 5.1.0 without inheriting the large performance hits described in this thread.  One caveat is that in some recordings, it looked like the runner did not continually keep scrolling the command log, but in most instances it did.

For local development, we did something similar, where we added a button to the UI that toggles the command log.  Here's an incomplete snippet, but it should convey the general approach:

```javascript
        const icon = document.createElement('i');
        icon.setAttribute('class', 'fas fa-list');

        const button = document.createElement('button');
        button.setAttribute('class', 'toggle-command-log');
        button.appendChild(icon);


        button.onclick = toggleCommandLog;
        button.setAttribute('aria-label', 'Toggle Command Log');

        const newCommandLogExpandButton = document.createElement('span');
        newCommandLogExpandButton.appendChild(button);

        commandLogButtons.appendChild(newCommandLogExpandButton);
```

We tossed both of these snippets into a `before` hook (in hindsight, adding it to the global `support/index.js` file so that it only gets run once might be sufficient).  Hopefully others find this work-around handy!

**Comment by emilio-notable** [comment]
we just tested @andrewmtam 's workaround and we got pretty good results as well.

We've been trying to upgrade from 4.3.0, and every version was much slower, except 5.1.0 (which includes this [PR](https://github.com/cypress-io/cypress/pull/8351)) which was not as slow as the other, but still slower than our baseline with 4.3.0.

Setting `overflow: hidden ` the test duration is pretty much the same as 4.3.0, and sometimes even faster

**Comment by peruukki** [comment]
I quickly tested using a windowed list in the command log in https://github.com/cypress-io/cypress/issues/6783#issuecomment-636303038 and saw similarly good results. Probably some kind of large list efficient technique would be needed in the command log to solve the performance issues.

**Comment by jennifer-shehane** [comment]
We're investigating some performance issues related to the rendering of the Command Log such as https://github.com/cypress-io/cypress/issues/6783 where I think the solution to that may also solve this issue.

Since there was never a reproducible example provided in this thread - we will have no way of actually testing if any solution we provide solves these however. But we'll followup in here when a PR is open for that.

There are some cases where hiding the Command Log does improve performance, and this is what we're investigating - what in the rendering of the component is causing the slowdown and how we can improve that.

**Comment by jennifer-shehane** [comment]
Closing this issue as we have resolved SEVERAL performance issues over the year, especially in the last few months. Please upgrade to the latest version and open a new issue with a repro if you're experiencing performance issues.
