### ISSUE TITLE
Cypress `--browser` option not working on Windows when given a `path` argument

### ISSUE THREAD

**Issue by Amrkamel1** [cypress-io/cypress#6389]
### Current behavior:

im running the following command after updating cyrpess to 4.0.1 
npm run cypress --browser c:\Users\amrka\appData\local\Mozilla Fireforx\firefox.exe
but still unable to see firefix among the list of browser in cypress

part of the log 

C:\Users\amrka\Desktop\ATT MNC\mc-testing-framework>npm run cypress --browser c:\Users\amrka\appData\local\Mozilla Fireforx\firefox.exe

> mc-testing-framework@1.0.0 cypress C:\Users\amrka\Desktop\ATT MNC\mc-testing-framework
> cypress open "Fireforx\firefox.exe"

![image](https://user-images.githubusercontent.com/32042806/74137614-6cee1d00-4bf0-11ea-9e7d-b2fed45e17cd.png)

### Desired behavior:

I should be able to see firefox among browser list in cypress

### Versions

Firefox

**Comment by flotwig** [comment]
@Amrkamel1 how did you install Firefox? I haven't seen it at this path before. Currently, Cypress will only look for Firefox installed in Program Files, which is why you are running into this.

**Comment by flotwig** [comment]
Actually, it seems like `--browser` is broken on Windows, so passing a path will not work here.

**Comment by flotwig** [comment]
I spent some time looking in to why `--browser` doesn't work on Windows.

This logic in the `launcher` is used to filter browsers:

https://github.com/cypress-io/cypress/blob/9103292f2cf2a493a43f8ec006a4a9feacf3c0e3/packages/launcher/lib/detect.ts#L163-L170

This works for Linux and macOS, because `stdout` is something like 'Mozilla Firefox 72.0a1'. But on Windows, `stdout` will be `Version=72.0.0001` or similar, since it comes from `wmic`.

Since `google-chrome --version` and `firefox --version` don't work on Windows, we have to keep using WMIC.

There needs to be some way for the launcher to determine what browser is passed. There could be a naive check, like if the path contains "firefox", assume it's firefox.

Or there could be a convention like `--browser firefox:C:\Program Files\Mozilla Firefox\firefox.exe`.

Open to ideas on how to detect the browser type, so `--browser` on Windows can be fixed.

**Comment by Amrkamel1** [comment]
> 
> 
> @Amrkamel1 how did you install Firefox? I haven't seen it at this path before. Currently, Cypress will only look for Firefox installed in Program Files, which is why you are running into this.

Nothing regular flow i have downloaded firefox installer then install it by default it went to that path stating above and its not in programeFiles but anyway will try again install it in program files

**Comment by arvinder06** [comment]
For me it hangs after below and nothing happen. Windows 10
using --browser firefox --headless
(without headless it is working fine)
```

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    4.0.1                                                                              │
  │ Browser:    Firefox 73 (headless)                                                              │
  │ Specs:      1 found (login.spec.js)                                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  login.spec.js                                                                   (1 of 1)
undefined
Your project has set the configuration option: `chromeWebSecurity: false`

This option will not have an effect in Firefox. Tests that rely on web security being disabled will not run as expected.
undefined
```

**Comment by AaronRohrbacher** [comment]
> > @Amrkamel1 how did you install Firefox? I haven't seen it at this path before. Currently, Cypress will only look for Firefox installed in Program Files, which is why you are running into this.
> 
> Nothing regular flow i have downloaded firefox installer then install it by default it went to that path stating above and its not in programeFiles but anyway will try again install it in program files
> 
> update :
> 
> its working fine when i have changed the path to C:\Program Files\Mozilla Firefox\firefox.exe

Users on (annoying) Windows GPOs, such as myself, will often have Firefox installed in their user-local AppData folders (C:\Users\[windows user name]\AppData\Local\Mozilla Firefox). Would be great if a fix came available for us!

**Comment by flotwig** [comment]
@AaronRohrbacher I haven't tried it, but I believe this should work in the meantime if you add it to your plugins file:

```js
module.exports = (on, config) => {
  // ...

  config.browsers.push({
    name: 'firefox',
    family: 'firefox',
    channel: 'stable',
    displayName: 'Firefox',
    version: '73.0.1',
    path: 'C:\Users[windows user name]\AppData\Local\Mozilla Firefox',
    majorVersion: '73'
  })

  return config
}
```

https://docs.cypress.io/guides/guides/launching-browsers.html#Customize-available-browsers

**Comment by kyle-mcknight** [comment]
Will this work for cypress run? The docs only mention it for cypress open. I would need it to work with run for CI

**Comment by kyle-mcknight** [comment]
> Will this work for cypress run? The docs only mention it for cypress open. I would need it to work with run for CI. And does it have to be an absolute path? This isn't much of a workaround for actual projects if so :/

I've answered my own question, it does not have to be an absolute path and it does work with cypress run

**Comment by flotwig** [comment]
After discussing with the team a bit, I think the way we can go about fixing this issue on Windows is using the `.exe` name to determine the expected browser type.

For example, for these paths:

* `C:\...\firefox.exe` would launch it as Firefox
* `C:\...\chrome.exe` would launch it as Chrome

**Comment by EmmanuelDemey** [comment]
We are facing the same problem. When trying to use chromium, it looks like the `wmic` command do not return the version on Windows, but launch the browser itself.

**Comment by stevejefferies** [comment]
Ran into this earlier today and started to look into this. @flotwig would your suggested fix of using the executable name work in the case of chrome vs chromium given both would be detected as chrome? (both are chrome.exe by default).

From a WMIC perspective both Chrome and Chromium appear identical so is hard to detect between the two. The only difference in the two is the author field ("The Chromium Authors" vs "Google LLC") which feels a little hacky, but would provide enough of a basis to differentiate.

**Comment by flotwig** [comment]
> Ran into this earlier today and started to look into this. @flotwig would your suggested fix of using the executable name work in the case of chrome vs chromium given both would be detected as chrome? (both are chrome.exe by default).

Good point, though it would only be a cosmetic issue, Chrome and Chromium are treated identically in Cypress.

> From a WMIC perspective both Chrome and Chromium appear identical so is hard to detect between the two. The only difference in the two is the author field ("The Chromium Authors" vs "Google LLC") which feels a little hacky, but would provide enough of a basis to differentiate.

We could use the filename matching in addition to an extra WMIC column to determine if it's Chromium or Chrome based on the author field... 

...this is starting to feel kinda hacky, I think we just need a way for users to specify the browser's `name` straight up, instead of adding more things to try and autodetect it. I think a convention like this could work:

* `--browser=C:\foo\firefox.exe` -> launches as Firefox
* `--browser=C:\foo\chrome.exe` -> launches as Chrome
* `--browser=C:\foo\chrome.exe:chromium` -> launches as Chromium
* `--browser=C:\foo\bar.exe` -> errors and complains about not being able to tell what kind of browser it is, shows examples of correct usage
* `--browser=C:\foo\bar.exe:chrome` -> launches as Chrome

**Comment by codenamics** [comment]
Hey,

Any update on that? workarounds are not working for me?

**Comment by flotwig** [comment]
@codenamics Nobody from the team is currently working on this, but we would welcome a PR that implements the fix described in https://github.com/cypress-io/cypress/issues/6389#issuecomment-632706124

**Comment by Nashati** [comment]
Hi,
Any update on this? 
does the latest version have the same issue?

**Comment by Zacharias3690** [comment]
I'd like to give this a shot.

**Comment by flotwig** [comment]
@Zacharias3690 feel free to go ahead and open a PR. Tag me if you have any questions about the repo that are not answered by the `CONTRIBUTING.md`.
