### ISSUE TITLE
require() not working after upgrade

### ISSUE THREAD

**Issue by nisargjoshi95** [cypress-io/cypress#6403]
### Current behavior:

On 3.8.3, I have tests that require() either other specs directly or functions that return a spec, and it works great. After updating to 4.0, all my specs with require() calls break with the following error:

![2020-02-10-113001_5360x1440_scrot](https://user-images.githubusercontent.com/4529746/74174501-ad9e6400-4bf9-11ea-8718-959a79744024.png)

Reverting to 3.8.3 restores desired behavior.

### Desired behavior:

Specs can `require()` other specs or functions

### Test code to reproduce

Create a file that exports a function that returns a `describe()`:

```js
export default (config) => {
  return describe(config.title, () => {
    // does stuff here
  }
}
```
require() the function in another spec:

```js
describe('a different spec', () => {
  require('path/to/first/spec.spec.js')({ config: 'object', that: 'is', passed: 'in' });
});
```

### Versions

Cypress 4.0.1, chrome and firefox, Manjaro Linux 18.1.5 (5.5.0-1 kernel)

**Comment by jennifer-shehane** [comment]
This is a regression in 4.0.0. This is likely due to the `@cypress/browserify-preprocessor` update from `1.1.2` to `2.1.1`

My working example:

`spec.js`

```js
describe('a different spec', () => {
  const num = require('./spec2.js')(4)

  it('foo', () => {
    expect(num).to.eq(64)
  })
})
```

`spec2.js`

```js
export default function cube(x) {
  return x * x * x
}
```

## 3.8.3

<img width="496" alt="Screen Shot 2020-02-11 at 2 39 40 PM" src="https://user-images.githubusercontent.com/1271364/74219919-866c9300-4cdc-11ea-8f51-ebe8bacc6f7c.png">

## 4.0.0

<img width="705" alt="Screen Shot 2020-02-11 at 2 41 55 PM" src="https://user-images.githubusercontent.com/1271364/74219980-aef48d00-4cdc-11ea-8037-f5c1217787b3.png">
