### ISSUE TITLE
test runner never stops on log method

### ISSUE THREAD

**Issue by jpita** [cypress-io/cypress#6457]
### Current behavior:

running this code the test runner never stops on the log method

### Desired behavior:

put the src of the image on the log

### Test code to reproduce
```js
/// <reference types="Cypress" />
describe('experiments', () => {
     
    it('experiment cy log', () => {
      cy.visit('https://docs.cypress.io/api/commands/log.html#Syntax')
      cy.log(cy.get('#logo > img'))
      cy.log(cy.get('#logo > img').invoke('attr', 'src'))

    })    
  })
```  
The timeout error only appears when I click the stop button.
![image](https://user-images.githubusercontent.com/5482105/74500300-6f6ab280-4f21-11ea-8c35-f70d09f93d80.png)

I tried https://github.com/cypress-io/cypress/issues/2107#issuecomment-579165591 this but didn't work

### Versions

```
Electron 78
Platform: darwin (19.3.0)
Cypress Version: 4.0.1```

**Comment by jpita** [comment]
never stops, meaning, the test never stops until I stop it manually

**Comment by jennifer-shehane** [comment]
You can't pass cypress commands as arguments to other commands due to the async nature of how tests run. In this particular case, let's look at the arguments and yield of each command you used.

- `cy.log()` accepts a String as an argument as indicated in the docs: https://on.cypress.io/log
- `cy.get()` yields the DOM element found https://on.cypress.io/get#Yields

Regardless, this still wouldn't run as expected even if it yielded a string. Please read our Intro to Cypress docs, especially this *entire* section: https://on.cypress.io/introduction-to-cypress#Chains-of-Commands

I don't know what you're trying to achieve with this code, but `cy.get()` and every command already logs within the Command Log.

**Comment by jpita** [comment]
I'm trying to get the src attribute from the image.
The idea is to put into a variable and then compare it with another one.
How can I achieve that @jennifer-shehane ?

**Comment by jennifer-shehane** [comment]
@jpita Check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by jpita** [comment]
Will do, thank you
