### ISSUE TITLE
Chrome 80 - crashes after ~10 minutes of running all specs || "Aw, snap!" screen.

### ISSUE THREAD

**Issue by Jacek-fstack** [cypress-io/cypress#6461]
I know it was a common issue with crashing and Chrome running out of memory, however for me the issue does not occur on Chrome 79 but does occur on Chrome 80. 

We used to have this issue with Chrome 79, but I fixed it with this code:

```js    
on('before:browser:launch', (browser = {}, launchOptions) => {
  if (browser.name === 'chrome') {
    launchOptions.args.push('--disable-dev-shm-usage')
  }
});
```

However, it doesn't seem to work with Chrome 80.

And for Chrome 80 the only fix is to add:
```js
"numTestsKeptInMemory": 1
```

But we want to have this data.

I tried switching to `browser.family` in case the 'chrome' name is not recognized, but it didn't help.

I've seen several topics on the "Aw, snap!" issue, but like I said - we handled our crashes with a code that doesn't seem to do its job anymore.

Does anyone know what may be causing this?

4.0.1 Cypress
80 Chrome

**Comment by Jacek-fstack** [comment]
Update: I found someone with a similar issue:
https://travis-ci.community/t/cypress-chrome-all-build-broken-at-same-time/7166/3

**Comment by CJ-Lab7** [comment]
I've been having the same problem.  The test runner has been useless for more than a few test cases.  This never happens though when running chrome headless though.

**Comment by Jacek-fstack** [comment]
It SEEMS like it was fixed in the newest 80 update for us. However, in general non-headless gets pretty slow after some time. But I know it's not meant to run a lot of tests.

**Comment by jennifer-shehane** [comment]
We don't recommend running 10 minutes of tests during `cypress open` and do recommend the given workaround of lowering the `numTestsKeptInMemory`, so that Cypress is not keeping multiple snapshots of the DOM over several tests. 

Chrome 79 previously had a bug introduced by Chrome that would cause performance issues like freezing in Chrome. https://github.com/cypress-io/cypress/issues/6023#issuecomment-574031655 

I'm not sure if there is a new issue in Chrome 80 as of yet. 

These types of issues where Chrome potentially introduces memory leaks or performance issues tend to exhibit themselves a lot more often within Cypress because of the amount of actions that can be performed very quickly over one session running 10 minutes of specs. 

---

As for the `launchOptions`, the `name='chrome'` should be fine if that is the name of the browser you are launching (not chromium, canary). You need to make sure you are returning the `launchOptions`, otherwise the new option will not be pushed in. 

You can always `console.log()` anything in here and it will print to your terminal whenever you launch Cypress within a browser. 

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser, launchOptions) => {
    // this will apply to any Chromium browser other than electron
    if (browser.name === 'chrome') {
      launchOptions.args.push('--disable-dev-shm-usage')

	  console.log(launchOptions) // can see the options take effect!

      return launchOptions // important to return here!!!
    }
  })
}
```

**console log of launchOptions.args**

<img width="534" alt="Screen Shot 2020-02-18 at 11 07 55 AM" src="https://user-images.githubusercontent.com/1271364/74704482-f5973980-523e-11ea-82fe-e35e26419ef9.png">

**Comment by lencioni** [comment]
@jennifer-shehane since it is important to return `launchOptions` here, what do you think about updating the examples in the v4 migration guide to include this? https://docs.cypress.io/guides/references/migration-guide.html#Plugin-Event-before-browser-launch

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
