### ISSUE TITLE
Group runs across multiple projects/repositories in the Dashboard

### ISSUE THREAD

**Issue by drewbrend** [cypress-io/cypress#6466]
I'm hoping this is already possible and I just haven't been able to figure this out.

### Our scenario:

We have specs spread across many repos, each repo represents a feature of our application.  We run a subset of these tests as a "smoke" run, we run the smoke tests from each repo in parallel, triggered by a "dispatcher" job that waits for them all to complete.

We want to aggregate the results to show the health of our application.  We can sort of view the results in Jenkins, but it's less than ideal and requires clicking around a whole bunch.  We'd much prefer to give them a group tag and view them all in the dashboard together.

### Current behavior:

You can currently group runs in the **same project** and view the results together, for example - different runs on browsers like the docs say:  https://docs.cypress.io/guides/guides/parallelization.html#Grouping-to-label-parallelization

### Desired behavior:

View results for **multiple projects/repos** with the same group tag together.

### Test code to reproduce

N/A

### Versions

Cypress 4.0.0

**Comment by jennifer-shehane** [comment]
@drewbrend By 'same project', we mean a 'project' in Cypress. So, they would need to have and pass the same `projectId` which is present in the `cypress.json` file. Otherwise, there's no way to group into a single run, which is owned by a single project. 

You could set the same `projectId` over multiple repos by just copy/pasting the `projectId` you already have set up in an existing Cypress project into all the other `cypress.json` files. **This will mix all the future recordings that share the same `projectId` together into the same runs list in the Dashboard**. 

You may want to further utilize the `--tag` flag if you're going to be running multiple 'repos' in a single Cypress project to better distinguish what you're running. https://on.cypress.io/command-line#cypress-run-tag-lt-tag-gt

Another point to note is the [run completion delay](https://on.cypress.io/parallelization#Run-completion-delay) which you may need to configure depending on how far apart your `cypress run` commands run that you want grouped into a single run.

**Comment by drewbrend** [comment]
That is a less than ideal solution for us - instead of closing this could it be a feature request then?

I imagine we aren't the only company that has multiple repos/projects and would benefit from this.

**Comment by jennifer-shehane** [comment]
@drewbrend Grouping across projects how we have 'groups' designed in our database is currently impossible. Realistically, I would not expect this feature work to be done anytime soon, 

Maybe there is some way other than the concept of 'groups' that you could achieve what you want. This really boils down to you wanting a way to associate and review multiple runs across multiple Cypress projects in one view.

This would actually all be work required by our Dashboard team. For feature requests in the Dashboard, they're not tracked in this repo, but in our [productboard](https://portal.productboard.com/cypress-io/1-cypress-dashboard) in order to get the right set of eyes on it.

I've already added your feedback to our productboard. You can express interest in this feature and see it's progress on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard
