### ISSUE TITLE
Cypress run gives error, when hovering over an element.

### ISSUE THREAD

**Issue by dizhar** [cypress-io/cypress#6472]
### Current behavior:
Getting an error message, when hovering over elements.  

**For Example:**

```js
cy.get("#elementID").trigger('mouseover');
```

**Note:** This bug only happens when doing a `cypress run` command . This bug does not happen when running the test via the `cypress open`.

Screen shot of the error.
![image](https://user-images.githubusercontent.com/6719491/74590114-2f382c80-5014-11ea-9fdd-9c98b4c234dd.png)

### Desired behavior:

1) The `cypress open` or the `cypress run` command should give the same test results.   
2) Hovering over an element in Cypress run should work.

### Test code to reproduce
```js
cy.get("#elementID").trigger('mouseover');
```

command:
```
npx cypress run --headed --spec  "xxxxxx"
```

### Versions
Cypress v4.0.1
OS Windows 10
Electron and Chrome

**Comment by clarmso** [comment]
Do you have a sample repo that shows the behaviour?

**Comment by dizhar** [comment]
Cypress.Commands.add("hover",  {prevSubject: 'element'}, subject => {
        cy.wrap(subject[0]).trigger('mouseover', {timeout: 6000});
});

use case:
cy.get('element').hover()

Also return the same error

**Comment by clarmso** [comment]
We need a website that exhibit the behaviour together with the Cypress command.  There are multiple known ways that a hover is achieved.

**Comment by dizhar** [comment]
I can only do it on a private repository.

Do you want to continue this conversation in private via email or WhatsApp?

**Comment by clarmso** [comment]
If you have a (public) repo that we can reproduce the bug, other people could help you, too.
https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md#reproducibility

**Comment by jennifer-shehane** [comment]
I can't recreate this with the given code. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide the HTML to run the code against to reproduce or the other pieces of configuration required to reproduce and we will reopen the issue.

---

The code I ran is below:

`index.html`

```html
<!DOCTYPE html>
<html lang="en">
<body>
  <div>action</div>
</body>
</html>
```

`spec.js`

```js
Cypress.Commands.add('hover', { prevSubject: 'element' }, subject => {
  cy.wrap(subject[0]).trigger('mouseover', { timeout: 6000 })
})

it('repro', () => {
  cy.visit('index.html')
  cy.get('div').hover()
})
```

Screenshot from `cypress run --headed --no-exit` - tried Electron and Chrome 80.

<img width="983" alt="Screen Shot 2020-02-18 at 12 13 58 PM" src="https://user-images.githubusercontent.com/1271364/74707504-6c850000-5248-11ea-8299-b085b77f9a00.png">
