### ISSUE TITLE
Cant select elements..

### ISSUE THREAD

**Issue by lcherone** [cypress-io/cypress#6473]
### Current behaviour:

The selector does not align with elements and/or mouse, so cannot select anything and when does just sees `body`.

![Peek 2020-02-15 19-04](https://user-images.githubusercontent.com/3892806/74593738-5bf53f80-5026-11ea-9f45-fec871811f07.gif)

### Desired behavior:

It work.

### Versions

 - Cypress: Version 4.0.2
 - OS: Linux
 - Runner/Browsers: all

**Comment by thundree** [comment]
Hi, I can confirm this. Just got this issue. In my case Cypress.$ won't find any element that was hidden or created after a few seconds the navigation happened.

**Comment by lcherone** [comment]
@thundree - me not cy.$ etc though, prob diff issue.. issue is about the selector on the app, not any tests, they work fine on older version.

**Comment by jennifer-shehane** [comment]
I can't recreate this just visiting our example.cypress.io website. 

Likely this is specific to something in your web application that we're not taking into account. Like, there's some css or javascript or something set that is making us read everything as 20 vertical pixels off or something.

![](http://g.recordit.co/RA46dt9nk6.gif)

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue and provide a website to test against that shows this behavior - or some hint on what css maybe your website has that may be unusual in this case and we will reopen the issue.
