### ISSUE TITLE
On Form Submit in case of download file on the same page/location, cypress waits for page load even when the file is downloaded..

### ISSUE THREAD

**Issue by testerncoder** [cypress-io/cypress#6476]
Hi Team,
Can anyone help me here how should I deal with download when it is implemented using <form> tag and not in <a> tag with XHR request?

it works fine when the file is being downloaded by XHR, but in the form submission, it expects page load.

### Current behavior:

On Form Submit in case of download file on the same page/location, cypress waits for page load when there is no page refresh or page load needed file is simply downloaded when the form is submitted or download button is clicked. Cypress unessesarly waits for the page load event for 6 sec and the test case fails.

### Desired behavior:

Cypress should be mature enough to understand when the file is downloaded after form submission. It should not be waiting for page load every time when the form is submitted, not in all form submission there is need for a page refresh.

### Test code to reproduce

Can't share the code because it can't be run without credentials. (Can't create test cred)

### Versions

Windows 10, Chrome -Version 79.0.3945.130 

![image](https://user-images.githubusercontent.com/30372207/74616398-9de3ca00-517b-11ea-8e9b-cc98a7f4d00f.png)

**Comment by jennifer-shehane** [comment]
Does your code rely on setting the url's href to the new document as described in https://github.com/cypress-io/cypress/issues/1551#issuecomment-558543003? 

There is also an existing issue about in-browser file download support here: https://github.com/cypress-io/cypress/issues/949

**Comment by testerncoder** [comment]
Hi Jen,

No, it is not setting any url href to the new document. It is simply submitting a form with post method to the server directly. even though the download is completed once the download button is clicked or by directly submitting the form, Cypress waits for a page to the event to occur. here is code screenshot:
![image](https://user-images.githubusercontent.com/30372207/74889846-5ad16300-53d6-11ea-9445-e6f554572f98.png)

and test script:

    it('download report', () => {
      cy.get('form[action="/formactionvalue"]').submit()
    })

**Comment by testerncoder** [comment]
Hi Jen,

I think it is the same case you explained above related to content-type, it's not 'text/html' but 'text/csv' instead. And I tried using cy.spy() as you mention in as workaround but it is also not going to the next line. I am not sure if I am using it correctly or not. can someone please help me out how can I write test for below form/ download functionality.
![image](https://user-images.githubusercontent.com/30372207/74896418-5615aa80-53e8-11ea-9ff2-caddb04ae1dc.png)

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by ranjit2827** [comment]
Hi, Jennifer
I am facing same issue in cyprase. On Button click File download scuccessfully but cyprase test case failed.Please provide some solution.I am facing this issue from last 2-3 days.I am nt using harcoded URL I am clicking on button [ INPUT BUTTON ].After button click test getting failed.

**Comment by jennifer-shehane** [comment]
@ranjit2827 If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run.

**Comment by tuly12** [comment]
Hi, Jennifer
I am facing same issue in Cypress.
On Button click File download successfully.
the file is created on server side ,no hard coded URL.
on issue #949 there is no solution for this case.
getting error :

Timed out after waiting 60000ms for your remote page to load.

Your page did not fire its load event within 60000ms.

You can try increasing the pageLoadTimeout value in cypress.json to wait longer.

Browsers will not fire the load event until all stylesheets and scripts are done downloading.

When this load event occurs, Cypress will continue running commands.

this occur due to waiting to load new page timeout
how can i stop waiting for new page? 
it is realy blocking me from continue the test

**Comment by jennifer-shehane** [comment]
@tuly12 You can't currently stop waiting for page load event. See https://github.com/cypress-io/cypress/issues/788

**Comment by thumatiraja** [comment]
@jennifer-shehane , 
**Hi, Jennifer,
Hope you are doing good.
I am facing same issue in Cypress.
On Button click File download successfully, but script does not continue with next steps due to below error.
I am Stuck and I want to get out of it, could you please help me.
See attached screenshot for reference.**

CypressError: Timed out after waiting '60000ms' for your remote page to load.
Your page did not fire its 'load' event within '60000ms'.
You can try increasing the 'pageLoadTimeout' value in 'cypress.json' to wait longer.
Browsers will not fire the 'load' event until all stylesheets and scripts are done downloading.
When this 'load' event occurs, Cypress will continue running commands.

Thanks in advance.
![Git hub](https://user-images.githubusercontent.com/60852563/86625051-12f85480-bfe2-11ea-8a8a-68e3595aedc8.jpg)

**Comment by alkuzad** [comment]
@jennifer-shehane I got this issue too, probably corelated with usage of `content-disposition: attachment` ([MDN][1]). Cypress does not detect it and waits for real page reload, which never actually happens.

[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

**Comment by KimWooHyun** [comment]
@jennifer-shehane 

Hi,
The same issue occurs after I added content-disposition.

> @jennifer-shehane I got this issue too, probably corelated with usage of `content-disposition: attachment` ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)). Cypress does not detect it and waits for real page reload, which never actually happens.

Are there any further solutions or discussions added later?

**Comment by ranjit2827** [comment]
Not yet

**Comment by norvinino** [comment]
I have the same problem. Do you have an answer to this please
![image](https://user-images.githubusercontent.com/71896864/94308970-f6165200-ff3c-11ea-9733-c983ddebf87f.png)

**Comment by psteixeira23** [comment]
> @jennifer-shehane ,
> **Hi, Jennifer, Hope you are doing good. I am facing same issue in Cypress. On Button click File download successfully, but script does not continue with next steps due to below error. I am Stuck and I want to get out of it, could you please help me. See attached screenshot for reference.**
> 
> ```
> CypressError: Timed out after waiting '60000ms' for your remote page to load.
> Your page did not fire its 'load' event within '60000ms'.
> You can try increasing the 'pageLoadTimeout' value in 'cypress.json' to wait longer.
> Browsers will not fire the 'load' event until all stylesheets and scripts are done downloading.
> When this 'load' event occurs, Cypress will continue running commands.
> ```
> 
> Thanks in advance.
> ![Git hub](https://user-images.githubusercontent.com/60852563/86625051-12f85480-bfe2-11ea-8a8a-68e3595aedc8.jpg)

I have the same problem.
Anyone have a suggestion?

**Comment by jennifer-shehane** [comment]
There is not workaround currently, as previously mentioned. Please follow https://github.com/cypress-io/cypress/issues/949 for update on file download support.

**Comment by jennifer-shehane** [comment]
File download is now supported in Cypress 6.3.0. 

You can now test file downloads in Cypress without the download prompt displaying. Any files downloaded while testing file downloads will be stored in the [`downloadsFolder`](https://on.cypress.io/configuration#Downloads) which is set to `cypress/downloads` by default. The `downloadsFolder` will be deleted before each run unless [`trashAssetsBeforeRuns`](https://on.cypress.io/configuration#Downloads) is set to `false`.

This means that if you had any code written to prevent the download prompt or to configure the download location (like in a `before:browser:launch` event handler), you can **remove all of these workarounds**. 

Our [file download recipe](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/testing-dom__download) has been updated, so you can see some ways to test different types of files after they've been downloaded there.

If you're encountering any bugs while testing file downloads, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose).
