### ISSUE TITLE
Can't log/intercept/mock requests when document-domain is disabled by Feature Policy

### ISSUE THREAD

**Issue by AkA84** [cypress-io/cypress#6480]
### Current behavior:

I have a site running on https, its server serving resources with the `Feature Policy` header `document-domain` directive set to `none`

```
Feature Policy: document-domain 'none'
```

As expected, not setting 

```json
"chromeWebSecurity": false
```
in cypress.json will result in Cypress failing to even reaching the site

<img width="917" alt="1" src="https://user-images.githubusercontent.com/6400898/74632943-d2965800-5160-11ea-89ae-4ccfc1c9e742.png">

If I set `chromeWebSecurity` to `true`, Cypress will be able to reach and perform actions on the site (in this case, logging in), but

1. In the console I can still see an error being thrown about `document.domain` being disabled by the `Feature Policy`
2. no XHR requests are being logged on the test runner
3. most importantly, no XHR requests get intercepted by `cy.route()`, meaning that it's impossible to wait for them, or inspect their response, or mock their response

<img width="913" alt="3" src="https://user-images.githubusercontent.com/6400898/74633060-1b4e1100-5161-11ea-813b-dbdf09c7a743.png">

If I get rid of the `document-domain` directive, then the error is gone and the XHR requests are getting logged and intercepted as expected

<img width="910" alt="4" src="https://user-images.githubusercontent.com/6400898/74633676-703e5700-5162-11ea-92f2-5c95e2284b35.png">

### Desired behavior:

The desired behaviour would be that setting

```
"chromeWebSecurity": false
```

would bypass the `document-domain: none` directive

### Versions

cypress: 4.0.2
OS: macOS Catalina 10.15.3
browser: Chrome 80

**Comment by jennifer-shehane** [comment]
In order for Cypress to function, we have to set `document.domain` since we run your application in an iframe. Larger explanation here: https://on.cypress.io/web-security

The Feature Policy header is new and still experimental, which is why we have not considered it: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy

In particular the one featured in this issue concerns the `document-domain` Feature-Policy described here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/document-domain

>The HTTP Feature-Policy header document-domain directive controls whether the current document is allowed to set document.domain. When this policy is enabled, attempting to set document.domain will fail and cause a SecurityError DOMException to be be thrown.

We will likely need to strip this specific Feature-Policy when running within Cypress.

## Workaround

I would suggest removing this specific feature policy header when running within Cypress. [Instructions on how to detect your app is running within Cypress.](https://on.cypress.io/using-cypress-faq#Is-there-any-way-to-detect-if-my-app-is-running-under-Cypress)

**Comment by AkA84** [comment]
thanks @jennifer-shehane ! Are you guys planning on solving this issue on one of the future releases? Also, am I correct in thinking that the workaround would only work on node-based apps (ours runs on PHP)?

**Comment by jennifer-shehane** [comment]
@AkA84 Removing the feature policy header would be specific to your application code - independent of what it's written in, you should be able to write this workaround in any language. 

This issue is still in the 'needs investigating' stage, which means no work has been done on this issue as of today, so we do not have an estimate on when this will be delivered.
