### ISSUE TITLE
[4.0.2] FireFox - ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by you1anna** [cypress-io/cypress#6481]
### Current behavior:

![Screen Shot 2020-02-17 at 12 25 42](https://user-images.githubusercontent.com/7108767/74655967-33378c00-5185-11ea-81cb-bff5ff955145.png)

### Desired behavior:

Test runs correctly in Chrome and Edge

### Test code to reproduce

The console mentions the top level test but the error is within the runner code, I think:

ReferenceError: $ is not defined__:169:5
    <anonymous> https://xxx.dev/__#/tests/integration/Rarebreed/signup.spec.js:169

ReferenceError: $ is not defined__:340:5
    <anonymous> https://xxx.dev/__#/tests/integration/Rarebreed/signup.spec.js:340

### Versions

MacOS Mojave 10.14.6
Yarn 1.22.0
Cypress 4.0.2

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

We need some code to be able to run to reproduce this. Can you provide a simple `index.html` to visit that would show this issue?

Also provide the Cypress test code you are running please (removing sensitive info)

Please comment in this issue with a reproducible example and we will reopen the issue.
