### ISSUE TITLE
Running Cypress with the Docker image - any way to get code completion?

### ISSUE THREAD

**Issue by kevinquillen** [cypress-io/cypress#6486]
Loving this so far. Using Cypress to run tests for local dev and CI. One thing though, how can I get code completion when writing tests? Cypress is in a container with all its dependencies, I don't see a way to get this going without installing the full thing on the host.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
