### ISSUE TITLE
Test suite execution headless mode electron

### ISSUE THREAD

**Issue by flname** [cypress-io/cypress#6487]
Hi ,

 We are unable to run multiple feature spec in headless mode. First spec execution is successful passed , from 2nd spec onwards time out message is displayed . unable to access electron browser , test been aborted. I tried with cypress 3.4.1.Same feature specs are run via cypress test runner on Windows . 
Could you please provide the solution to resolve this issue. 

### Current behavior:
Unable to run bundle feature files via command line in both headed/headless mode on electron.

**Comment by jennifer-shehane** [comment]
I see that you are using an older version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog)? Your issue may have already been fixed. 

Closing since the current version of Cypress is not being used. Please comment with the results of updating and we will consider reopening.
