### ISSUE TITLE
Hi everyone, Could you please help me to solve my problem with Auth0? I can not login with any of emails I use.

### ISSUE THREAD

**Issue by lilitpoghosyandc** [cypress-io/cypress#6488]

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by dandv** [comment]
@jennifer-shehane: can we please change the title of this issue to something like "INVALID"? It pollutes the search results for "Auth0".

**Comment by jennifer-shehane** [comment]
@dandv Hmm, we don't really have a process around that, but I can see polluted search results may be an issue.

**Comment by MuckT** [comment]
Hey I ran into this similar issue with trying to get a programmatic login working with Auth0 in to a react app and was using [End-to-End Testing with Cypress and Auth0](https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/); however, I ran into some issues. Below is the code I used to my `commands.js` solve it along with following the listed guide: 
```JavaScript
// From auth0 Cypress integration https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/ - modified
Cypress.Commands.add('login', (overrides = {}) => {
  Cypress.log({
    name: 'loginViaAuth0',
  });

  const options = {
    method: 'POST',
    url: Cypress.env('auth_url'),
    body: {
      grant_type: 'password',
      username: Cypress.env('auth_username'),
      password: Cypress.env('auth_password'),
      audience: Cypress.env('auth_audience'),
      scope: 'openid profile email',
      client_id: Cypress.env('auth_client_id'),
      client_secret: Cypress.env('auth_client_secret'),
    },
  };
  cy.request(options)
    .then((resp) => {
      return resp.body;
    })
    .then((body) => {
      const { access_token } = body;
      cy.visit('/', {
        Headers: {
          Authorization: `Bearer ${access_token}`,
        }
      });
    })
    .then(() => {
      cy.setCookie('auth0.is.authenticated', 'true');
      cy.setCookie('_legacy_auth0.is.authenticated', 'true');
    });
});
```
