### ISSUE TITLE
API does not respond in chrome launched by cypress locally

### ISSUE THREAD

**Issue by mindaugasnakrosis** [cypress-io/cypress#6489]
### Current behavior:

Test fails in Chrome browser launched by cypress.
API responds with an error: "**err empty response**".

![image](https://user-images.githubusercontent.com/14983636/74715580-5883d300-5235-11ea-805c-e5e650f7b3eb.png)

If I reproduce the same test manually (chrome opened by me), API responds just fine (screenshots included).

![image](https://user-images.githubusercontent.com/14983636/74715485-2a05f800-5235-11ea-9b87-fbe26bd67a86.png)

If I launch backend code on `127.0.0.1:9090` rather than on `localhost:9090` everything seems to work.
### Desired behavior:

API responds correctly.

**Comment by jennifer-shehane** [comment]
Are you behind a corporate proxy? Have you followed the instructions for Proxy Configuration? https://on.cypress.io/proxy-configuration

What version of Cypress are you using?

**Comment by mindaugasnakrosis** [comment]
I am not behind a proxy. 
I am using 4.0.2 version.

**Comment by dancornilov** [comment]
Hey, I also have some trouble with local API testing. When I try to execute tests. All my XHR requests **canceled & aborted**.
<img width="440" alt="Screen Shot 2020-02-22 at 12 36 55 AM" src="https://user-images.githubusercontent.com/24212761/75077712-41cace00-550c-11ea-8f44-11fd85f85a2a.png">
<img width="382" alt="Screen Shot 2020-02-22 at 12 37 05 AM" src="https://user-images.githubusercontent.com/24212761/75077714-442d2800-550c-11ea-871e-d8564e433b2f.png">
<img width="583" alt="Screen Shot 2020-02-22 at 12 37 08 AM" src="https://user-images.githubusercontent.com/24212761/75077716-44c5be80-550c-11ea-8b42-8e47bd598eee.png">

I don't understand why it aborted in cypress's browser?

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
