### ISSUE TITLE
cypress redirects to 404

### ISSUE THREAD

**Issue by Ruifeng-Wu** [cypress-io/cypress#6500]
### Current behavior:
when repeat cy.visit(url), cyprees inner  browser and tools bar disappear.

### Desired behavior:
Normal redirects to Authentication server.

### Versions
3.8.1

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏
