### ISSUE TITLE
Uncaught TypeError: r is not a function when i use .type for an input type=text

### ISSUE THREAD

**Issue by MaximePouessel** [cypress-io/cypress#6507]
### Current behavior:

_Hi all,_ 

I have an input `type=text` 
<kbd>![image](https://user-images.githubusercontent.com/58938595/74845275-0e7f1800-532f-11ea-9c79-df9f105951e3.png)</kbd>

```html
 input aria-describedby="questions[0].title-error " aria-invalid="true" 
name="questions[0].title" type="text" id="questions[0].title" class="form-control" 
value="" 
```

When i want to enter a text in the text field via `.type`, 
<kbd>![image](https://user-images.githubusercontent.com/58938595/74845388-3a9a9900-532f-11ea-860b-e20f06660763.png)</kbd>

```js
cy.xpath('//*[@id="questions[0].title"]')
  .type('Section 1')
```

(i try with a `cy.get('#questions[0].title')` and with class, same issue for both)

I have an error : 
<kbd>![image](https://user-images.githubusercontent.com/58938595/74845562-7df50780-532f-11ea-9f21-b1f6d79dcfe0.png)</kbd>

And i dont know why i have this error

### Desired behavior:

Insert "Section 1" in `<input type=text` when i get the id or xpath (i try xpath just to try, i know it's not a good practice)

### Versions

Cypress version : 4.0.2
Chrome version : Version 79.0.3945.130
OS : Windows 10.0.18362

**Comment by jennifer-shehane** [comment]
Hey @MaximePouessel, the error is being thrown from within your application code - not Cypress. 

Open the DevTools console and click the big yellow error message from the UI, this will log the stack trace of where this error if throwing within your application. That will help you narrow down where and why this error is throwing when you type into the field. 

Closing as I can't recreate this with an input and the given Cypress code because the error is being thrown from your application code which we don't have.

**Comment by MaximePouessel** [comment]
Bug fixed,
Error is js code, forgot the onBlur

Add the follow line : 

- if(onBlur) { onBlur()}
