### ISSUE TITLE
Unable to detect Proxy configuration settings

### ISSUE THREAD

**Issue by satgalley** [cypress-io/cypress#6510]
# Current behavior:
 I have a test which is just to take me to google.com. When I do that, I get an error in both chrome 80 and Electron 78
![image](https://user-images.githubusercontent.com/22899547/74879266-61a49b00-532e-11ea-8a0d-65d8f3ef5b2d.png)
I don't find anything under proxy settings in the test runner
![image](https://user-images.githubusercontent.com/22899547/74879375-9c0e3800-532e-11ea-9d9a-27988fa87677.png)

I already followed the procedure in this link  
https://on.cypress.io/proxy-configuration#Proxy-environment-variables 
and set `HTTP_PROXY` and `HTTPS_PROXY` in the Env variables. I am not sure about the no proxy part.

 Also when I launch through chrome, I see the URL generated is
HTTP://localhost:41655/__/#/tests/integration\examples\Test1.js

### Desired behavior:

I am under a company proxy, Got stuck at this step itself. I guess something related to my proxy setting is wrong. 

I am a beginner in Cypress, so expecting detailed steps to fix the issue.

### Test code to reproduce

```js
describe('First Test', function()
  {
    it('Test Case',function(){
        cy.visit("http://www.google.com/");
    })
  })
```

### Versions
Node.JS version: v12.16.1
Cypress version: 4.0.2
Machine OS : Windows 10
Office Network : Yes Under proxy
Added Proxy: Yes Added both HTTP_PROXY and HTTPS_ PROXY in Env Variables

**Comment by JasonFairchild** [comment]
So, it sounds like this issue chain may be related to your issue: https://github.com/cypress-io/cypress/issues/672 (long thread, I'd search more toward the end for specific current steps that may tell you what you need)

Maybe part of the problem is that cypress did not automatically detect your company proxy settings? Or maybe that is how it works now, and you need to set something up in the cypress.json to make it work with with a company VPN/proxy. That seems to be where the 672 issue ended up. 

Also, it may help to understand that Cypress itself uses a proxy under the hood. You can learn more about that here, along with its recent improvements https://www.cypress.io/blog/2019/05/22/how-we-improved-network-speed-by-300-in-cypress-3-3-0/ (and probably elsewhere for a more general overview). Point is, just because your cypress runner doesn't list a proxy in those settings doesn't mean a proxy is not at play as part of the problem. It could be that your company proxy and cypress' just needs stitching together, so to say. And hopefully that is what a simple cypress,json entry can solve. Someone may have to correct me if that isn't entirely correct, but I think its in the right direction at least.

**Comment by jennifer-shehane** [comment]
If the Proxy Settings tab in the Test Runner is showing 'no proxy settings configured', then the env variables are not set on your system correctly for the `HTTP_PROXY` and `HTTPS_ PROXY` correctly. All we do is read in `process.env.HTTP_PROXY`. 

Please check again that you are setting your system environment variables correctly in your Windows environment - this is different depending on your command prompt or powershell. Instructions here: https://on.cypress.io/proxy-configuration#Windows

What is the result of printing all environment variables in Windows like described here? https://docs.cypress.io/guides/references/proxy-configuration.html#See-all-currently-set-environment-variables

If this does not print the `HTTP_PROXY` or `HTTPS_PROXY` env variable then they are not set correctly.

**Comment by satgalley** [comment]
Thanks @jennifer-shehane @JasonFairchild .

Few pointers on what I did
=> Uninstalled everything and started from scratch
=>My company proxy was set to detect an automatic proxy, there were multiple proxies. Removed that option and manually set a proxy and used it in Env variables.
=>I also ran this command in PowerShell - Set-ExecutionPolicy RemoteSigned

The only question I have now is, the company now has multiple proxy EX: sdfg1, sdfg2, sdfg3  and when I do netstat -b Chrome takes different proxy at a different instance. Is there a way to handle any proxy in that list. Can I add all those in the env variables? Will that solve it. BTW, yet to get the complete proxy list from admin.

Will keep you posted

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by manjunath1818** [comment]
Hi Team,

How to get rid off this?


Proxy Server | http://my-company-proxy.com
-- | --
127.0.0.1, ::1, localhost

Basically i dont want any proxy settings.

PS F:\Cypress\> npm config rm proxy
PS F:\Cypress\> npm config rm https-proxy
PS F:\Cypress\> npm config rm http-proxy 

i still see below proxy settings.

![image](https://user-images.githubusercontent.com/57515636/113606141-3893b680-9665-11eb-93d5-7c741851af75.png)
