### ISSUE TITLE
Getting an error message, when hovering over an element and a popup is supposed to be displayed.

### ISSUE THREAD

**Issue by dizhar** [cypress-io/cypress#6521]
### Current behavior:
Getting an error message, when hovering over an element and a popup is supposed to be displayed.

### Desired behavior:
cy.get("#elementID").trigger('mouseover');

Note: This bug happens when doing a cypress run  --browser chrome . This bug does not happen when running  the test on Chrome via the cypress open GUI.  Also this bug happens when running on FireFox or electron

Screen shot of the error.
![image](https://user-images.githubusercontent.com/6719491/74952809-76099600-5409-11ea-8090-9f3655fb61a2.png)

### Test code to reproduce

**I have attached the Repo to reproduce:**
https://github.com/dizhar/cypress-hover

**Steps:** 
1) git clone https://github.com/dizhar/cypress-hover
2) cd cypress-hover
3) npx cypress run --browser chrome --spec "C:\cypress-hover\cypress\integration\e2e-tests\all-pages\popups.spec.ts"

### Versions
Cypress v4.0.2
OS Windows 10
Electron, Chrome and FireFox

**Comment by jennifer-shehane** [comment]
Mac path to run specs: `npx cypress run --browser chrome --spec "cypress/integration/e2e-tests/all-pages/popups.spec.ts"`

I am not getting the same error as you when running the command above. I am getting:

```
  CypressError: Timed out retrying: cy.trigger() failed because this element:

  <a link-theme="base" entity="[object Object]" data-test="link" class="Link-er0b4x-0 boUiFV" href="/securities/orgfs_1581839832204SEM907683852f9546d7b44a4e242b5d32d6" style="border: 5px solid red;">000996AA6</a>

  is being covered by another element:

  <div data-test="popup-body" class="styled-components__StyledTableData-sc-17sxyhe-2 cflnio">...</div>

  Fix this problem, or use {force: true} to disable error checking.

  https://on.cypress.io/element-cannot-be-interacted-with
```

My guess from your error is that you are wrapping a Cypress command somewhere and returning your own Promise, which you should never need to do since this is exactly what this error means and detects. 

The example given is way too complex for me to dive into exactly where this is though. If you can simplify the example to only Cypress commands and show this is a bug, we will consider reopening.
