### ISSUE TITLE
When including zepto library, zepto object is passed as remote jQuery instead of expected Cypress jQuery to use for chaining.

### ISSUE THREAD

**Issue by luokuning** [cypress-io/cypress#6529]
I'm using cypress v4.0.2, and here is a snip of my test code:
```javascript
cy.get('div[data-component-data-id=301602] h2:first')
  .should(($el) => {
    expect($el).to.have.text('dress')
  })
```

and cypress complains about the assertion:
```
CypressError: Timed out retrying: You attempted to make a chai-jQuery assertion on an object that is neither a DOM object or a jQuery object.

The chai-jQuery assertion you used was:

  > text

The invalid subject you asserted on was:

  > Object{3}

To use chai-jQuery assertions your subject must be valid.

This can sometimes happen if a previous assertion changed the subject.
```

So I have to change `expect($el).to.have.text('dress')` to `expect($el[0]).to.have.text('dress')`, then the complain dismissed and test passed.

I debug the assertion a bit, turns out `$el[0]` is also a jquery element.

I also print `$el` and `$el[0]` to the console:

<img width="785" alt="image" src="https://user-images.githubusercontent.com/12708534/75036433-c9084980-54ec-11ea-9924-c33cdf12d671.png">

**Isn't `cy.get` equivalent to jquery $? Why should I have to get the first element from $el?**

**Comment by jennifer-shehane** [comment]
I can't recreate this. Please provide a full example of the HTML you are testing against. My test code below:

```html
<!DOCTYPE html>
<html>
<body>
  <h2>dress</h2>
</body>
</html>
```

```js
it('have text not exist', () => {
  // h2 doesn't even exist
  cy.get('h2')
    .should(($el) => {
      expect($el).to.have.text('dress')
    })
})

it('have text', () => {
  cy.visit('index.html')
  cy.get('h2')
    .should(($el) => {
      // assertion passes
      expect($el).to.have.text('dress')
    })
  cy.get('h2')
    .should(($el) => {
      // assertion fails
      expect($el).to.have.text('foo')
    })
})
```

<img width="594" alt="Screen Shot 2020-02-24 at 3 06 31 PM" src="https://user-images.githubusercontent.com/1271364/75137910-431c1680-5717-11ea-98fc-5a71b31970b6.png">

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will reopen the issue. 🙏

**Comment by luokuning** [comment]
Thanks for the reply. Here is my complete test code in `cypress/integration/image.spec.js`:

```javascript
describe('image component', () => {
  beforeEach(() => {
    cy.viewport('iphone-x')

    cy.visit('http://159.65.226.122', {
      onBeforeLoad(win) {
        Object.defineProperty(win.navigator, 'userAgent', {
          value:
            'Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1',
        })
      },
    })
  })

  it.only('title display', () => {
    cy.get('div[data-component-data-id=302749] h2:first')
      .should($el => {
        expect($el).to.have.text('dress')
      })
  })
})
```

And some settings in `cypress/support/index.js`:
```javascript
Cypress.on('uncaught:exception', () => {
  // returning false here prevents Cypress from
  // failing the test
  return false
})
```

I can confirm that the html in `http://159.65.226.122` would cause CypressError:

<img width="416" alt="image" src="https://user-images.githubusercontent.com/12708534/75144735-8c2d9400-5732-11ea-875c-f612c52a555f.png">

**Comment by jennifer-shehane** [comment]
@luokuning Please provide the fully HTML/CSS/JavaScript or a hosted application since we cannot visit `http://159.65.226.122` to run your tests.

**Comment by luokuning** [comment]
@jennifer-shehane Sorry for the inconvenient. Here is the minimize HTML:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>test</title>
</head>
<body>

<div data-component-data-id="302749">
    <h2 class="mshe-text-left">dress</h2>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js"></script>
</body>
</html>
```

And it turns out that when I comment the script tag which load `zepto`, everything works fine. How is this error related to the application script?

**Comment by jennifer-shehane** [comment]
Another failing use case brought up in https://github.com/cypress-io/cypress/issues/7917

@Ayase-252 mentioned:

>After digging into the code, I find that the problem may arise in [there](https://github.com/cypress-io/cypress/blob/993302757cc9871c8a1a7da9e54bcf191e93d0e1/packages/driver/src/cy/jquery.js#L17). The `remoteJQuery` is actually a `Zepto`. therefore, the `remoteSubject` is a zepto object with a jquery passing in.

Yes, this is how Cypress currently works. If cypress finds that the application under test (AUT) has a global jQuery instance, rather than wrap elements in cypress’s own jQuery, it will use the jQuery instance in the AUT which can have some surprising implications such as when the remote jQuery has been overwritten.

The reason this was originally designed this way was so that 3rd party jQuery plugins you’ve installed in your AUT would automatically be “accessible” and queryable from cypress’s API. So taking this behavior away would negate your ability to do this: `cy.get('element').invoke('somePlugin', args)`.

But this is likely not a strong argument for keeping this behavior. 

`spec.js`

```js
it('test', () => {
  cy.visit('index.html')
  cy.get('body').then(($el) => {
    // `$el` is a zepto object now, the following will 
    // fail because $el is not a valid jQuery object
    cy.wrap($el).screenshot();
  });
})
```

`index.html`

```html
<body>
  hello world
  <script src="https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js"></script>
</body>
```

<img width="645" alt="Screen Shot 2020-07-09 at 10 57 30 AM" src="https://user-images.githubusercontent.com/1271364/86996970-0129d380-c1d3-11ea-94b7-1a5d50f04b28.png">
