### ISSUE TITLE
cypress need cy wrapper for information using variables in different  methods

### ISSUE THREAD

**Issue by Bheemaanil** [cypress-io/cypress#6558]
In below example, `_jwt variable` is `null` in the beginning when I trigger the `tokenexcute` method, jwt variable is assigned with a value which can be use in different place with out any issue

```js 
private _jwt = '';
  private _accessToken = '';
  async tokenExecute(brandCode: BrandCode) {
    const response = await http.get(
      Caller.getCallerByBrandCode(brandCode).TOKEN_HOST, {
        headers: {
          'Content-Type': 'application/json',
          'brand': brandCode
        }
      }
    );
    this._jwt = response.response.headers.token;
  }
```

```js
async loginExecute(username: string, password: string, brandCode: BrandCode) {
    const response = await chakram.post(
      Caller.getCallerByBrandCode(brandCode).LOGIN_HOST,
      {
        "email": username,
        "password": password
      },
      {
        headers: {
          'Content-Type': 'application/json',
          'brand': brandCode,
          'authorization': 'Bearer ' + this._jwt,
        },
      }
```

where as in Cypress we need a wrapper with cy as below. 

```js
this.getQuotePrice()
      .stripPrice()
      .as('initialPrice');
    cy.get('@initialPrice').then(initialPrice => {
        .getDrawerQuoteTotal()
        .should(drawerQuoteTotal => {
          expect(getPriceFromEl(drawerQuoteTotal)).to.eq(initialPrice);
        });
    });
```

is there any simple process for this please

**Comment by jennifer-shehane** [comment]
This seems like the simplest way to do it, without actually seeing the code in your custom commands.

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
