### ISSUE TITLE
Tests against cypress-test-node-versions not properly failing in repo?

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6559]
### Current behavior:

I’m a bit confused by this ‘test-node-versions’ process.

- I see in develop that this status check is pending 
	<img width="768" alt="Screen Shot 2020-02-26 at 11 47 16 AM" src="https://user-images.githubusercontent.com/1271364/75314514-57ceea80-588e-11ea-9277-474cacd4a946.png">
- The details link goes to this url: https://github.com/cypress-io/cypress-test-node-versions/commit/063793dd1f5845cc677baeb67cf702c9480e6834
- The status check on this page shows it as failed: 
	<img width="422" alt="Screen Shot 2020-02-26 at 11 48 29 AM" src="https://user-images.githubusercontent.com/1271364/75314532-66b59d00-588e-11ea-9827-22173f7ea598.png">
- But the CircleCI job that actually ran in develop branch shows as passing: https://circleci.com/gh/cypress-io/cypress/263937

### Desired behavior:

Well, I am starting to realize that rolling back execa to 2.0.0 is not actually going to fix our Node 8.0.0 dep problem because we actually have to go back to 1.0.0. 

The `test-node-version` should be failing in `develop`. But then I was like, wait? I saw our node-versions tests passing in develop. 😕 

`develop` should fail if the `cypress-test-node-version` fails with the new binary.

### Versions

`develop` branch

**Comment by bahmutov** [comment]
There are several things:
- when we build the commit on `develop` we run `test-binary-and-npm-against-other-projects` job - all it does it kicks off OTHER repos by making a commit there with JSON message. So that job successfully made a commit, thus it is green
- `cypress-test-node-versions` gets a commit with JSON object describing how to install Cypress beta and commit SHA and starts its jobs, for example, https://github.com/cypress-io/cypress-test-node-versions/commit/063793dd1f5845cc677baeb67cf702c9480e6834 kicks off Circle jobs https://circleci.com/workflow-run/a3d795bd-9dfa-4860-bbc6-325ae21535ff

Node 8.0.0 test job fails to install at all https://circleci.com/gh/cypress-io/cypress-test-node-versions/10407 and thus it fails - then it runs its own commit step that is supposed to set the failing status on `cypress-io/cypress` repo _original_ SHA. But here is a problem: because the install has failed, our status check module also failed to install 😁

<img width="683" alt="Screen Shot 2020-02-26 at 9 14 22 AM" src="https://user-images.githubusercontent.com/2212006/75352874-71fdce00-5878-11ea-8133-8716f123c21c.png">

Let me see if I can fix this

**Comment by bahmutov** [comment]
Second problem - it installs Cypress v4.0.2 by default which we should skip or install dynamically

**Comment by bahmutov** [comment]
Ok, I reworked the install, so it does not try to install Cypress v4.0.2 first, which is bound to fail on Node v8.0.0. So now it still fails https://circleci.com/workflow-run/1dbcbec7-84b5-425e-9cea-b156982d2aa4
and I am not sure where the execa is coming from

```
> cypress@4.0.3 postinstall /home/node/app/node_modules/cypress
> node index.js --exec install

/home/node/app/node_modules/cypress/node_modules/execa/index.js:36
		...options,
		^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/node/app/node_modules/cypress/lib/util.js:20:13)
```

**Comment by bahmutov** [comment]
but the jobs do report back correctly the commit status on failure

**Comment by bahmutov** [comment]
Ok, now seems to work as expected, let's see if all is good. Also https://github.com/cypress-io/cypress/pull/6569 adds Node 8.0.0 NPM install for the freshly built NPM package, so this repo is one extra check
