### ISSUE TITLE
Not able to visit stored value in second cy.visit() to different cross origin URL

### ISSUE THREAD

**Issue by sushantlokhande** [cypress-io/cypress#6562]
### Current behavior:
1. Opens yopmail page and enters text as `activeproduser` in `textbox` and clicks `button`
2. In first `cy.log`, it prints `hrefvalue` of link 'Reset Your Password'.
3. In second `cy.log` it not prints `hrefvalue` of link 'Reset Your Password'
4. Not opens link URL in 2nd `it()` method

### Desired behavior:

I want to visit Links `href` value stored inside `iframe` to submit form
I cannot use `cy.request` here.

### Test code to reproduce
```js
describe("***** Verify Reset Password Token Tests", function() {   
let hrefValue;
  it("* Get Reset password Token page ", function() {    
    cy.log("***** Inside verifyResetPasswordEmail ");
    cy.server();
    cy.visit("http://www.yopmail.com/en/")
    cy.get('input#login').click({force: true}).clear() 
    cy.get('input#login').type('activeproduser') 
    cy.get('input[type=submit]').click({force: true})
    cy.wait(4000)    
    cy.get('#ifmail').then($iframe => {
      const $body = $iframe.contents().find('body')         
      cy.wrap($body).find("table tr:nth-of-type(3) a").invoke('attr','href')
      .then(href => {
        hrefValue = href;
        //It logs hrefvalue
        cy.log(hrefValue)
      })
      //Its not logging anything 
      cy.log(hrefValue)
   })
  })

  it("* Open Reset password Token page ", function() {    
    cy.log("***** Inside Reset password token page");
    cy.visit(hrefValue)
  })
})
```
### Versions
Cypress: 3.8.3│Browser: Chrome 80 │OS: Windows10

**Comment by sushantlokhande** [comment]
Note: 
1. If I click on link it opens in new tab. Cypress dont support Multitab
2. Used removeattr to stop #1 but its not doing the job

**Comment by jennifer-shehane** [comment]
#### Why is the second `cy.log()` not logging anything.

The second `cy.log()` is logging `hrefValue` as undefined because the `hrefValue` evaluates as soon as the commands are read in - which at that point is undefined. Please read our [Intro to Cypress guide on how commands are async](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html#Commands-Are-Asynchronous)

```js
it("sets href", function () {
  let hrefValue;
  
  cy.visit("index.html").then(() => {
    hrefValue = 'foo'
    cy.log(hrefValue) // evaluates to 'foo'
  })
  // evaluates to 'undefined', the code above has not 
  // set the hrefValue when this hrefValue is evaluated.
  cy.log(hrefValue) 
})
```

### Why is the `cy.visit()` not going to the right URL

So, above is not the issue. What *is* happening here though is that when you call the second `cy.visit()` to a cross origin URL (different superdomain, host, or port) - Cypress reloads the page so that the main window is now navigated to the new domain. When it does this - it loses the previous value of `hrefValue`, so that when it goes to `cy.visit()` the `hrefValue` again - it is undefined. 

This is a unexpected behavior.

#### Code to reproduce

```js
describe('Href visit', function () {
  let hrefValue;

  it('captures href', function () {
    cy.visit('https://www.google.com').then(() => {
      hrefValue = 'https://www.cypress.io'
    })
  })

  it('visit href', function () {
    cy.visit(hrefValue)
  })
})
```

![](http://g.recordit.co/nJ5czuGVC9.gif)

<img width="499" alt="Screen Shot 2020-02-27 at 3 47 58 PM" src="https://user-images.githubusercontent.com/1271364/75429665-8cb76c00-5978-11ea-8ec8-a313f32cbf96.png">

**Comment by sushantlokhande** [comment]
@jennifer-shehane Thanks for looking into it, changing title and adding labels to it. Waiting for some workaround solution.

**Comment by sushantlokhande** [comment]
@jennifer-shehane - Any update on this issue? I am also trying with different approaches.. but no luck yet.. Can your team spend some time on this one and help me in getting workaround..
Thanks,
Sushant

**Comment by jennifer-shehane** [comment]
## Current Workaround

Ok, I have a workaround for this. So, since we're wiping the entire state on each browser refresh, the value of the `href` needs to be saved outside of this - and this can be done in our plugins file, which will retain its state through browser state refreshes. 

So, you could achieve this by using `cy.task()`, creating a couple of tasks to set and then later get the href value. An example is shown below. 

`plugins/index.js`

```js
let href

module.exports = on => {
  on('task', {
    setHref: (val) => {
      return href = val
    },
    getHref: () => {
      return href
    }
  })
}
```

`spec.js` using `cy.task()`

```js
describe('Href visit', () => {
  it('captures href', () => {
    cy.visit('https://www.google.com').then(() => {
      cy.task('setHref', 'https://www.cypress.io')
    })
  })

  it('visit href', () => {
    cy.task('getHref').then((href) => {
      cy.visit(href)
    })
  })
})
```

**Comment by rishabhjn321** [comment]
How can we destructure url from hrefValue that we have stored and use it to visit a new site

**Comment by rishabhjn321** [comment]
> ### Current behavior:
> 1. Opens yopmail page and enters text as `activeproduser` in `textbox` and clicks `button`
> 2. In first `cy.log`, it prints `hrefvalue` of link 'Reset Your Password'.
> 3. In second `cy.log` it not prints `hrefvalue` of link 'Reset Your Password'
> 4. Not opens link URL in 2nd `it()` method
> 
> ### Desired behavior:
> I want to visit Links `href` value stored inside `iframe` to submit form I cannot use `cy.request` here.
> 
> ### Test code to reproduce
> ```js
> describe("***** Verify Reset Password Token Tests", function() {   
> let hrefValue;
>   it("* Get Reset password Token page ", function() {    
>     cy.log("***** Inside verifyResetPasswordEmail ");
>     cy.server();
>     cy.visit("http://www.yopmail.com/en/")
>     cy.get('input#login').click({force: true}).clear() 
>     cy.get('input#login').type('activeproduser') 
>     cy.get('input[type=submit]').click({force: true})
>     cy.wait(4000)    
>     cy.get('#ifmail').then($iframe => {
>       const $body = $iframe.contents().find('body')         
>       cy.wrap($body).find("table tr:nth-of-type(3) a").invoke('attr','href')
>       .then(href => {
>         hrefValue = href;
>         //It logs hrefvalue
>         cy.log(hrefValue)
>       })
>       //Its not logging anything 
>       cy.log(hrefValue)
>    })
>   })
> 
>   it("* Open Reset password Token page ", function() {    
>     cy.log("***** Inside Reset password token page");
>     cy.visit(hrefValue)
>   })
> })
> ```
> 
How can we destructure url from hrefValue that we have stored and use it to visit a new site
