### ISSUE TITLE
cy.contains() should be case-insensitive by default

### ISSUE THREAD

**Issue by artemisclyde** [cypress-io/cypress#6564]
### Current behavior:
`cy.contains()` argument `matchCase` defaults to true.

### Desired behavior:
`cy.contains()` argument `matchCase` defaults to false and can be set to true for case-sensitive matching.

As already stated by @jennifer-shehane [in this issue]( https://github.com/cypress-io/cypress/issues/2785#issuecomment-440014819), I find it quite annoying to have to change my tests `cy.contains()`s whenever I change capitalization and would generally prefer case-insensitive matching as for me, that would be closer to the easy way of creating tests Cypress is always promoting.

### Versions

Cypress 4.0.2
Chromium, Manjaro Linux

**Comment by jennifer-shehane** [comment]
I would recommend just overwriting the `.contains` command, so that every time you use it it has `matchCase` set to `false`. 

```js
Cypress.Commands.overwrite('contains', (originalFn, subject, filter, text, options = {}) => {
  // determine if a filter argument was passed
  if (typeof text === "object") {
    options = text
    text = filter
    filter = undefined
  }

  options.matchCase = false

  return originalFn(subject, filter, text, options)
})
```

We didn't want to make a massive breaking change for everyone (which this would have been) in 4.0 when we released this. 

Adding this feature is not something we see as within our scope of feature work, so we will be closing this issue. We will reconsider and reopen if we see this issue gains more 👍 or comments in support.

**Comment by FredrikRosenqvist** [comment]
How about adding a global configuration for this, would not be a breaking change then?

**Comment by dmsidrake** [comment]
New to cypress and had this same question, glad to find a work around, but doesn't their need to be an else statement?

`Cypress.Commands.overwrite('contains', (originalFn, subject, filter, text, options = {}) => {
  // determine if a filter argument was passed
  if (typeof text === 'object') {
    options = text
    text = filter
    filter = undefined
  }
  else options.matchCase = false

  return originalFn(subject, filter, text, options)
})`

**Comment by Mekacher-Anis** [comment]
so the code snippet provided by @jennifer-shehane didn't work as it uses `overwrite` instead of `overwriteQuery`  see this
https://stackoverflow.com/a/75670962
and for completeness' sake, here's the answer mentioned in the Stackoverflow question (all Thanks goes to the original poster)

```JS
Cypress.Commands.overwriteQuery(
  "contains",
  function (contains, filter, text, userOptions = {}) {

    // This is parameter resolution from Cypress v12.7.0 source
    if (Cypress._.isRegExp(text)) {
      // .contains(filter, text)
      // Do nothing
    } else if (Cypress._.isObject(text)) {
      // .contains(text, userOptions)
      userOptions = text
      text = filter
      filter = ''
    } else if (Cypress._.isUndefined(text)) {
      // .contains(text)
      text = filter
      filter = ''
    }

    userOptions.matchCase = false;

    let contains0 = contains.bind(this)    // this line fixes the error

    return contains0(filter, text, userOptions)
  }
)
```

and I do agree with @ciriousjoker this should probably be a config.
