### ISSUE TITLE
Promise error with chrome 80

### ISSUE THREAD

**Issue by amitguptagwl** [cypress-io/cypress#6576]
### Current behavior:
When I open a page with chrome 80 browser selected on the dashboard, I see following error

![cypress-error](https://user-images.githubusercontent.com/7692328/75430143-eb78e780-5970-11ea-90d7-2745a1e7095b.png)

It works fine with Electron browser or <= Chrome v71. I don't know about Chrome versions after v71.
It was causing issue for particular URLs only. But as they are internal I can't share them.

### Desired behavior:
It should open the page without any error.

### Test code to reproduce

```js
cy.visit("url")
```

### Versions
Cypress: 3.4.1,
Ubuntu 18.04
node js: 11.15
Chrome: 80

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide the full set of tests and configuration that is causing the error. I ran the code below in Chrome 80 - and it works fine. Likely there is something else in your project that you think is unrelated but is related causing an edge case. 

```js
it('visit', () => {
  cy.visit('https://www.cypress.io')
})
```

<img width="496" alt="Screen Shot 2020-02-27 at 4 14 58 PM" src="https://user-images.githubusercontent.com/1271364/75432183-71e6f680-597c-11ea-9c32-0a206fd531c4.png">

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by amitguptagwl** [comment]
We're using cypress cucumber plugin.

**Comment by jennifer-shehane** [comment]
@amitguptagwl PRovide the reproducible tests with the cucumber plugin and all commands that we can run on our machine and see the error and we will consider reopening.
