### ISSUE TITLE
How to stub cy.request with fixtures?

### ISSUE THREAD

**Issue by jmaicaaan** [cypress-io/cypress#6586]
### Current behavior:
I've watched this video for best practices on Cypress https://www.youtube.com/watch?v=5XQOK0v_YRE
The video mentioned along was to create a custom command for "login" / "signup" . And so I wonder how can I mock or use fixtures for my custom commands that uses `cy.request` inside?

### Desired behavior:
Can be mocked by fixtures

### Test code to reproduce
```js
export const signup = () => {
  Cypress.Commands.add('signup', () => {
    cy.request({
      url: 'localhost:8000/api/signup',
      method: 'POST',
      body: {
        email: TestingFactory.fake.email(),
        password: TestingFactory.fake.hash({
          length: 15,
        }),
        firstName: TestingFactory.fake.first(),
        lastName: TestingFactory.fake.last(),
      },,
    }).then(({
      body: {
        session: {
          token: ownerToken,
        },
        user: {
          roleId: ownerID,
        },
      },
    }) => {
      cy.window().its('store').invoke('dispatch', {
        type: 'sign_up_success',
        payload: {
          ownerID,
          ownerToken,
        },
      });
    });
  });
};
```

### Versions
4.0 
macOS 
Google Chrome

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
