### ISSUE TITLE
If-else: control always goes to else loop

### ISSUE THREAD

**Issue by renukaalurkar** [cypress-io/cypress#6601]
### Current behavior:

Control  always enters Else loop. The length of the `$el` always evaluates to `0` even though I see that the element is present on the webpage. 

I already also asked in the gitter chat group but since I didnt get any replies as to how I can correct my code i decided to post it here. Thanks for your help!

### Desired behavior:

When the `$el` is present on the webpage/I can see it, control should be in if block and then exit. 
When the `$el` is not present on the webpage, then the control should be in else block.

### Test code to reproduce
```js
it("User can set certification for multiple users at once",()=>{
      cy.get(':nth-child(4) > .RadioButton__StyledRadioButton-sc-1j2qp2u-1').click(); //clicking Non-certified button
      const $el=Cypress.$('[class="Typography__StyledTypography-sc-153d8g4-0.jhYDmS.TrainingQueueListstyles__EmptyListMessage-sc-19yfim3-1.ihRiqU"]');
      cy.get("body").then($body =>{
       if ($body.find($el).length) {
        cy.log('if block');
        cy.log($body.find($el).length);
        cy.get('.hZDZBR').should('not.exist');
        cy.get('input[id="selectAll"]').should('not.exist');
       } else {
       cy.log('else block');
       cy.log($body.find($el).length);
       cy.get('input[id="selectAll"]').click();
       cy.get('.hZDZBR').click();
     }
  })
})
```

**Comment by brycehanscomb** [comment]
Your check for `if ($body.find($el)` may happen an indeterminate amount of time _after_ the `const $el=Cypress.$(...)` happens. 

There might be a chance that the timing difference between these two statements is causing one of the variables to be flushed or otherwise unavailable later in time. Can you try defining `$el` inside the `.then()` scope and see if that changes anything?

**Comment by jennifer-shehane** [comment]
The `const $el=Cypress.$('[class="Typography__StyledTypography-sc-153d8g4-0.jhYDmS.TrainingQueueListstyles__EmptyListMessage-sc-19yfim3-1.ihRiqU"]');` code will evaluate immediately, once - so this is evaluating before the cy.get() above it even evaluates. 

We really advise staying within the cypress commands since they are async. Please read this guide: https://on.cypress.io/introduction-to-cypress#Commands-Are-Asynchronous

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
