### ISSUE TITLE
How to test an API which calls other APIs while mocking the other APIs

### ISSUE THREAD

**Issue by ravitoait** [cypress-io/cypress#6616]
### Current behavior:
How do I test an API (`/extensions/external/apps`) which in turn call other APIs internally (like, `/kappnav/namespaces`), while mocking the data for other APIs?

### Test code to reproduce
```js
it('testing the success condition when we got the list of all WAS Traditional Apps and Liberty Apps', function () {
  //starting
  cy.server()
  // mocking the other APIs
  cy.route('GET', '/kappnav/namespaces', '@allNamespacesJSON').as('fetchAllNamespaces')
  // visiting this page calls /extensions/external/apps, which in turn calls other apis
  cy.visit('/kappnav-ui/applications/stock-trader/addComponents?namespace=ravikumarsingh123', {
  })
  cy.wait('@fetchAllNamespaces').then(console.log)
})
```

The above mentioned `cy.visit`, in turn, calls the API (`/extensions/external/apps`), which in turn internally calls other APIs, like `/kappnav/namespaces`.

But I can't see other APIs (`/kappnav/namespaces`) being hit and the `cy.wait()` getting timedout as its not getting hit.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/9142577/75716239-68b79b80-5c94-11ea-8485-51e1f39d51bb.png">

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
