### ISSUE TITLE
can we use multiple reporter in cypress.json

### ISSUE THREAD

**Issue by MehranShafqat** [cypress-io/cypress#6622]
### Current behavior:

In current scenario Im using html reporter in cypress.json file, but now I have another reporter like "cypress-testrail-reporter" how can I define both in reporter ? 

Html Reporter

"reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "configFile": "reporter.json"

TestRail reporter
 "reporter": "cypress-testrail-reporter",
  "reporterOptions": {
    "domain": "test.testrail.io",
    "username": "qa.apps@test.com",
    "password": "test123",
    "projectId": 1,
    "suiteId": 4
  }

**Comment by CypressCecelia** [comment]
Please refer to our [documentation here](https://docs.cypress.io/guides/tooling/reporters.html#Multiple-reporters) about multiple reporters.

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io/), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
