### ISSUE TITLE
Question abut the use of Jquery and CoffeeScript in your code

### ISSUE THREAD

**Issue by 11ume** [cypress-io/cypress#6631]
Hi,

I want to ask you two questions:

* Why did you decide to use CoffeeScript?

* Why do you use Jquery in low level modules like the driver or the browser modules?
> This does not have a significant impact on your perfmance, load times and code coverage?

**Comment by bahmutov** [comment]
- Cypress was started 6 years ago where CoffeeScript was much better for larger scale app development. It gets transpiled to JavaScript during our build step, so ultimately it is all JS. Nowadays we have moved a lot of code, probably the majority of CoffeeScript code to modern JavaScript and even to TypeScript
- we jQuery because it is convenient

We don't think the choice of language above affects the performance in any way.
