### ISSUE TITLE
Aims to work out of the box, config free

### ISSUE THREAD

**Issue by qkreltms** [cypress-io/cypress#6638]
### Current behavior:
So much to config like test-coverage, typescript, reactjs, etc...
These are bring me headache... and to some others too and even don't works.

### Desired behavior:

Wish Cypress aims to work out of the box, config free It's good tool though.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

If you can define a more specific feature request that is within scope of Cypress as a product, we will consider reopening, but this is just a very broad statement about Cypress and its customized tooling.
