### ISSUE TITLE
Not able to use cypress image snapshot plugin and rename image at a time

### ISSUE THREAD

**Issue by nani554** [cypress-io/cypress#6648]
### Current behavior:
I have renamed images by following the logic give by you
https://on.cypress.io/after-screenshot-api#Usage

but when i use renaming code with cypress-image-snapshot plugin, its not working properly
Eg: 

### `plugins/index.js`

```js
const fs = require('fs');
const path = require('path');
const { addMatchImageSnapshotPlugin } = require('cypress-image-snapshot/plugin');
const _ = require('lodash');
const getImageName = require('../fixtures/common-functions').getImageName;

module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  on('after:screenshot', (details) => {
    if (details.testFailure) {
      let folders = details.specName.split('\\');
      let pathArray = details.path.split('\\');
      let imageName = getImageName(true, pathArray[pathArray.length - 1])
      const newPath = path.resolve(__dirname, `../reports/mochawesome-report/reporter-assets/${folders[0]}/${folders[1]}/${imageName}`)
      fs.renameSync(details.path, newPath)
      return { path: newPath }
    }
  })
  addMatchImageSnapshotPlugin(on, config);
}
```

### note: 

Here `addMatchImageSnapshotPlugin(on,config)` is related to cypress image snapshot plugin

### case 1) 

If i keep cypress image snapshot plugin above renaming code then facing 

```
Error: Image was NaN% different from saved snapshot with undefined different pixels. See diff for details: undefined issue
```

### case 2) 

If i keep cypress image snapshot plugin below renaming code then renaming is not working

### Desired behavior:

Both should work simultaneously without any issue

### Versions
```js
  "dependencies": {
    "cypress": "^3.8.3",
    "cypress-image-snapshot": "^3.1.1"
  }
```

**Comment by jennifer-shehane** [comment]
Yeah, I'm not able to get this to work in general from the docs instructions even without the `cypress-image-snapshot` plugin. 

Docs say:

>You can return an object or a promise that resolves an object from the callback function

`spec.js`

```js
it('fails', () => {
  expect(true).to.be.false // failing so we get a screenshot
})
```

```js
const path = require('path');

module.exports = (on, config) => {
  on('after:screenshot', (details) => {
    console.log('DETAILS', details)
    const newPath = path.resolve(__dirname, '../new/path/to/screenshot.png')
    console.log('NEW PATH', newPath)
    return { path:  newPath }
  })
}
```

The `console.log()` from my plugins results in the following printed to stdout. 

```
DETAILS {
  size: 40833,
  takenAt: '2020-03-06T09:30:16.762Z',
  dimensions: { width: 1280, height: 720 },
  multipart: false,
  specName: 'spec.js',
  testFailure: true,
  path: '/Users/jennifer/Dev/cypress-transform-test/cypress/screenshots/spec.js/fails (failed).png',
  scaled: true,
  blackout: [],
  duration: 337
}
NEW PATH /Users/jennifer/Dev/cypress-transform-test/cypress/new/path/to/screenshot.png
```

**Prints to stdout as if it is saving screenshot to new path**

<img width="829" alt="Screen Shot 2020-03-06 at 4 01 07 PM copy" src="https://user-images.githubusercontent.com/1271364/76072538-894e6100-5fc6-11ea-9a10-580b6a8878c0.png">

However, there is absolutely no path or file at `cypress/new/path/to/screenshot.png`, the `cypress/screenshots/spec.js/fails (failed).png` however does exist. 

![Screen Shot 2020-03-06 at 4 01 48 PM](https://user-images.githubusercontent.com/1271364/76071040-fc0a0d00-5fc3-11ea-8007-19e12299adf9.png)

This *seems* to be a fault in the functionality of the `after:screenshot` handler and not a mistake in the docs, just from looking through the code. I see *some* tests for overwriting `after:screenshot` in this way, but not really a one to one of what I'm doing.

**Comment by nani554** [comment]
Yup what you have said is true, its not considering new path at all. checked it without cypress-image-snapshot plugin as well, new path is not considered.

**Comment by jennifer-shehane** [comment]
Ok, so actually my understanding of how setting the `path` and other properties work was mistaken and I'm going to update the docs after this experience. 

The `path` and other properties are meant to be set to the new *existing* properties of the screenshot. So, setting `path` does not *move* the screenshot, it simply is saying 'the screenshot now exists here'. The user is responsible for physically moving the screenshot first, then telling Cypress where the correct new path of the screenshot exists. 

@nani554 Does the screenshot actually exist at `../reports/mochawesome-report/reporter-assets/${folders[0]}/${folders[1]}/${imageName}`, like, you have moved it there? Or were you expecting Cypress to move the screenshot to that new location? Because Cypress is not intended to move the actual screenshot.

**Comment by jennifer-shehane** [comment]
I was able to get this to work with Cypress along with the below example. @nani554 You may want to use the `fs.rename` (not sync) function so that you can catch any errors that may be throwing. The directory where you are moving the screenshot to has to exist before placing the file there. 

```js
const path = require('path');
const fs = require('fs')

module.exports = (on, config) => {
  on('after:screenshot', (details) => {
    const newPath = path.resolve(__dirname, '../new-path/screenshot.png')
    fs.renameSync(details.path, newPath)
    return { path: newPath }
  })
}
```

--- 

Now, we know Cypress functionally works without the plugin, lets add in the plugin. [`cypress-image-snapshot`](https://github.com/palmerhq/cypress-image-snapshot)

This plugin is also overwriting the `after:screenshot` handler as part of their `addMatchImageSnapshotPlugin` command as can be seen here: https://github.com/palmerhq/cypress-image-snapshot/blob/master/src/plugin.js#L137

What are they doing here? Well, the same as you are - moving the screenshot and overwriting the path of where the screenshot exists. 

### The problem

If you have 2 event handlers for `after:screenshot`, the second one wins and the first handler actually *never runs* as can be seen below:

```js
const path = require('path');
const fs = require('fs')

module.exports = (on, config) => {
  on('after:screenshot', (details) => {
    // THIS CODE NEVER RUNS
    const newPath = path.resolve(__dirname, '../new-path/screenshot.png')
    fs.renameSync(details.path, newPath)
    console.log('NEWPATH', newPath) // THIS NEVER LOGS
    return { path: newPath }
  })

  on('after:screenshot', (details) => {
    const newPath = path.resolve(__dirname, '../new-second-path/screenshot.png')
    fs.renameSync(details.path, newPath)
    console.log('NEWPATH', newPath) // THIS LOGS
    return { path: newPath } // sets to new-second-path
  })
}
```

So, as it currently stands, you cannot get the benefit of `cypress-image-snapshot` actually working as intended and also overwrite the `after:screenshot` handler yourself. 

## The solution?

We could say this is an issue with [`cypress-image-snapshot`](https://github.com/palmerhq/cypress-image-snapshot), that they can essentially expose a way for their users of the plugin to pass their own directory path to override their default. (I would suggest opening an issue with them since this is what you want).  

But, this is likely a pretty common pattern of people adding a plugin, not even knowing what event handlers that plugin has already written to, but wanting to expand on the event handler yourself. So, we could maybe handle this better. At the least, maybe warning that there is some code within an event handler that is effectively never being read?? I'd like @chrisbreiding opinion on this.

**Comment by chrisbreiding** [comment]
We have seen this sort of issue before, and it's unfortunately common for a plugin to take the `on` function in and register events with it. I'd say this is poor behavior on the plugin's part and a bad pattern, since it takes control away from the user and doesn't allow them to do anything else with the events the plugin registers. I prefer to see plugins take a callback function for an individual event, so it looks something more like:

```javascript
const { afterScreenshotPlugin } = require('some-screenshot-plugin')

module.exports = (on, config) => {
  on('after:screenshot', (details) => {
    // ... do what I need with the screenshot details ...
    return afterScreenshotPlugin(details)
  })
}
``

That said, the current API is clearly not ideal and it's something we'll consider if and when we develop a new API for plugins. That would likely mean a breaking change, so it would be something for a future major release.

In the meantime, I agree that we should print a warning if the same event is registered twice, so it's clear that the previous handler has been overwritten and will not get called.

**Comment by nani554** [comment]
> shot actually exist at `../reports/mochawesome-report/reporter-assets/${folders[0]}/${folders[1]}/${imageName}`

Yes it exists in that location, as iam just renaming image name and not relocating the image it will be in the same location as it was there previously.
the point is either renaming not working or CIS is not working when used both.
and coming to my second comment which is not true, as i tested again now & Renaming 
 is working fine when not used with CIS plugin.

my goal is to rename images before generating reporter (mochawesome html file).
**The problem:** 
if image name length is more than 100 then it is not visible in reporter. so i have to reduce its length

**Solution:**
Tried on after:screenshot event but as there are few problems mentioned by @jennifer-shehane and @chrisbreiding  ,using this event doesnt work with CIS plugin.

So i have created a node js file and used glob and fs to rename it successfully. now things are working fine. I thought of following this approach as my last resort but have to use it anyway.

**Thank you @jennifer-shehane for spending time on this bug and providing information, iam very greatfull for that. thank you @chrisbreiding**  and closing this issue is upto you as my issue is resolved.

**Comment by jscontreras** [comment]
### Here is a solution
If you print the ImageSnapshotPlugin here is what it does
```js

function addMatchImageSnapshotPlugin(on, config) {
  on('task', {
    [_constants.MATCH]: matchImageSnapshotOptions(config),
    [_constants.RECORD]: matchImageSnapshotResult(config)
  });
  on('after:screenshot', matchImageSnapshotPlugin);
```
So override your on `after:screenshot` but don't forget to call that one too
```js
const {
  addMatchImageSnapshotPlugin,
  matchImageSnapshotPlugin
} = require('cypress-image-snapshot/plugin');

module.exports = (on, config) => {
 // after:screenshott via ImageSnapshot
  addMatchImageSnapshotPlugin(on, config);
  // Override
  on('after:screenshot', (details) => {
    console.log(details)
    const newPath = path.resolve(__dirname, '../new-path/screenshot.png')
    fs.renameSync(details.path, newPath)
    console.log('NEWPATH', newPath)
    // Get it ready for the matchImagSnapshot plugin
    details.path = newPath
    matchImageSnapshotPlugin(details)
  })
}
```

**Comment by yazlai** [comment]
how i can use this function in cypress (how to implement it)

var fs = require ('fs');
fs.rename ('/ path / to / title.pdf', '/path/to/title_01.pdf', function (err) {
    if (err) console.log ('ERROR:' + err);
});

to rename PDFs after each download

thank you in advance

**Comment by badeball** [comment]
I recently [implemented options](https://github.com/badeball/cypress-cucumber-preprocessor/commit/15ae6d0ae3b30fe3034804a2826ba5411a5de102) to opt out of auto-attaching handlers because of this. It's rather moot though, because every other plugin still doesn't have similar options. Furthermore, it requires the user to be familiar with all the handlers a plugin is requesting. This leads to 1) more ceremony and 2) changes to a plugin's handlers would always have to be considered a breaking change.

Why can't this behave similar to any other event emitter?
