### ISSUE TITLE
How to apply find for custom elements, received without get ?

### ISSUE THREAD

**Issue by golubvladimir** [cypress-io/cypress#6651]
How to apply find for custom elements, received without get ?

```
    it('open new tab', () => {
      cy.window().then(win => {
        //const usersTable = win.document.getElementsByClassName('users-table');
        //console.log(usersTable.find('tbody'));
        //console.log($(win).find('.users-table'))
      });
    });
```

**Comment by golubvladimir** [comment]
It is not working.

```
      cy.window()
        .find('.users-table')
        .find('tbody')
        .find('tr')
        .first()
        .find('.users-table__delete-btn')
        .click()
```

**Comment by Yayuro** [comment]
.find() is not chainable and you can't use it in the way you want.
https://docs.cypress.io/api/commands/find.html#Rules

What is wrong with .get()? Any reason why you can't use it?
This should do the job:
```
cy.get(".user-table tbody tr:nth-child(1) .user-table__delete-btn")
  .click();
```

BTW I don't think this is an issue with cypress itself.

**Comment by CypressCecelia** [comment]
> .find() is not chainable and you can't use it in the way you want.
> https://docs.cypress.io/api/commands/find.html#Rules
> 
> What is wrong with .get()? Any reason why you can't use it?
> This should do the job:
> 
> ```
> cy.get(".user-table tbody tr:nth-child(1) .user-table__delete-btn")
>   .click();
> ```
> 
> BTW I don't think this is an issue with cypress itself.

Thanks @Yayuro for providing that documentation link.

**Comment by CypressCecelia** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

Thank you!
