### ISSUE TITLE
How to setup the pipeline and env var for aws linux agent?

### ISSUE THREAD

**Issue by karlhan628** [cypress-io/cypress#6656]

**Comment by CypressCecelia** [comment]
We do have [recipe for a BuildKite `pipeline.yml` file](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.buildkite/pipeline.yml) in our [Continuous Integration guide](https://docs.cypress.io/guides/guides/continuous-integration.html#Examples). As for setting up Node in your AWS agent, I'd recommend taking a look at the [AWS documentation](https://docs.aws.amazon.com/index.html) specifically, as that would not be a Cypress issue.

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
