### ISSUE TITLE
cy.exec timing out every linux command.

### ISSUE THREAD

**Issue by brunodev09-iheart** [cypress-io/cypress#6693]
### Current behavior:

Every `cy.exec` command I call returns me the timeout callback. 

![JOSpCUA](https://user-images.githubusercontent.com/1271364/76398226-e83b1e00-63aa-11ea-8083-70d6014ffc1e.png)

### Desired behavior:

Expected `cy.exec` to work properly.

### Test code to reproduce

I'm not sure how to setup a reproducible code as it seems to be some kind of enviromental conflict or something related, I just don't know where else to open this. Anyone ever experienced this can give me some kind of hint on how to fix this?

### Versions

OS: Ubuntu 16.04 LTS
Python 3.7.6
Cypress 4.1.0
Node v10.14.2

**Comment by jennifer-shehane** [comment]
Just want to point out that the commands you are running must exit: https://on.cypress.io/exec#Commands-Must-Exit

Unfortunately we have to close this issue as there is not enough information to reproduce the problem.

Please comment in this issue with code that can be run from the `index.js` file, to execute via `cy.exec('node index.js')` so that we can reproduce. We can run this on Linux to check.
