### ISSUE TITLE
how to use if condition when different env

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#6698]
```js
if (cy.contains('users')) {
} else {
}
```

I will find a text on web as a condition, has a different web.
but `cy.contains` not return boolean or number, failuer when not find text.
so how to code ?

**Comment by jennifer-shehane** [comment]
Please see our doc on [conditional testing](https://on.cypress.io/conditional-testing)

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
