### ISSUE TITLE
Cy.write into an existing json file

### ISSUE THREAD

**Issue by Jagsingh-coder** [cypress-io/cypress#6710]
### Current behavior:
Hi,

It's possible the feature already exists but I don't know how to use it.

Let's say I have a json file like this >

```json
[
	{
		"Salutation": "1",
		"Firstname": "2",
		"Lastname": "3",
		"Email": "4",
		"number5": "5",
		"number6": "6"
	}
]
```

### Desired behavior:

And I want to replace the value of "email" to "test@test.com"
Is there a way to do this ?

When I use the `cy.writeFile` function, it always erases the all content and only writes the new email

### Test code to reproduce
```js
const getLTDApprovedApplicationFileName = () =>
    path.join(__dirname, '..', 'fixtures', 'LTD-Approved-Application.json')

  on('task', {
    updateEmail(email) {
      const cy = require('fs')
      let updateEmail
      cy.readFile(getLTDApprovedApplicationFileName(), (err, data) => {
        if (err) throw err
        updateEmail = JSON.parse(data)
      })
      debug('updateEmail')
      console.log(email)
      let data = JSON.stringify({
        ...updateEmail,
        EmailAddress: email
      })
      cy.writeFileSync(getLTDApprovedApplicationFileName(), data)
      return null
    }
  })
```

**Comment by jennifer-shehane** [comment]
You like what to use the `flag` option of `cy.writeFile()`. https://on.cypress.io/writefile#Arguments It accepts flags same as Node fs: https://nodejs.org/api/fs.html#fs_file_system_flags

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
