### ISSUE TITLE
Unable to launch Application application using cy.visit(). Cypress is throwing 500 response code

### ISSUE THREAD

**Issue by kumarshiva1** [cypress-io/cypress#6714]
### Current behavior:

I am getting 500 error code while launching application using cy.visit() command. It happen with WebDriver IO as well but when i refresh the page with webdriver IO, it works. When i am refreshing the page using Cypress by using cy.reload(), command, it does not work. it gives the same 500 response code.

### Desired behavior:

Cypress should launch app using cy.visit() command.

### Versions

3.7.0 & 4.1.0 - With both the version

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by kumarshiva1** [comment]
Steps to Reproduce -
cy.visit('app url')
cy.reload()

I am doing cy.reload() as with selenium I need to refresh the page to launch the application. When I am doing the same with Cypress, I am still getting 500 error code.

Complete Error Message - 

CypressError : cy.visit() failed trying to load;
The response received from your web server was:
>500:Server Error
This was considered a failure because the status code was not '2XX'.

**Comment by jennifer-shehane** [comment]
Can you explain why your webpage initially gets a 500 response? (Is this expected behavior?) and what about your application is 'fixed' due to reloading the webpage exactly? That would probably hint at why this is working/not working.

`cy.visit('app url')` is not something we can run on our side to reproduce, so this it not something we can move forward with investigating.

**Comment by mariiakhairi** [comment]
Hi @jennifer-shehane 
I have the same issue 
please do cy.visit("https://app.experiment-oa.zendy.io/")
I am not sure why this is is happening

**Comment by mariiakhairi** [comment]
@jennifer-shehane I get this error in console - DevTools failed to load source map: Could not load content for http://localhost:57605/__cypress/runner/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by nagash77** [comment]
HI @mariiakhairi as Jennifer [mentioned here](https://github.com/cypress-io/cypress/issues/6714#issuecomment-599901010) sinply providing a `cy.visit()` is not something we can use to replicate your issues.  In order to give our engineers the best chance at recreating your problem, please create a reproducible example using a fork of [Cypress Test Tiny](https://github.com/cypress-io/cypress-test-tiny).  This gives us the best chance of seeing exactly what you are seeing and being able to investigate effectively.

If you are new to using Cypress I would also suggest you check out the Cypress Discord Community [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by mariiakhairi** [comment]
Hi @nagash77 

Upgrading the cypress version from 12.5.1 to 12.17.2 fixed the issue.
Thank you for the clue. Once I have installed the cypress from scratch to provide the repository URL the issue wasn't there :)

**Comment by Shirinhashemii** [comment]
> Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.
> 
> Please comment in this issue with a reproducible example and we will consider reopening the issue.

miaw
