### ISSUE TITLE
connection problem

### ISSUE THREAD

**Issue by NoorAlazab** [cypress-io/cypress#6717]
i did all steps u wrote down , but i got this error 

```
CypressError: cy.task('queryDb') failed with the following error:

The task 'queryDb' was not handled in the plugins file. The following tasks are registered: logRetry

Fix this in your plugins file here:
C:\Users\idk\Documents\qarepo\cypress\plugins\index.js

https://on.cypress.io/api/task
```

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with your entire `plugins/index.js` file so we can reproduce and we will consider reopening the issue.

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
