### ISSUE TITLE
RangeError for screenshot only on default viewportWidth

### ISSUE THREAD

**Issue by nitzanashi** [cypress-io/cypress#6719]
### Current behavior:
* Taking screenshot for elements that contain **css grid layout** with default (1000) configuration for `viewportWidth` is throwing error.
```
RangeError: The value of "offset" is out of range. It must be >= 0 and <= 3686396. Received -4192
  RangeError [ERR_OUT_OF_RANGE] [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 3686396. Received -4192
      at boundsError (internal/buffer.js:72:9)
      at Buffer.readUInt32BE (internal/buffer.js:295:5)
```

![image](https://user-images.githubusercontent.com/13871150/76640394-24f44a00-6550-11ea-96a3-ef10ac880bdf.png)

* This is not happening when changing the `viewportWidth` to other values (`1001`, `999` both works fine)

### Desired behavior:
* screenshot should be taken without any error been thrown

### Test code to reproduce
find some grid css layout my code looks like that:
```js
it('test', () => {
  cy.get('[data-soul=SANDBOX_TEASER_SECTION_GRID')
    .first().screenshot('test')
})
```

### Versions
from Cypress v4, on chrome

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with the HTML code to run the above test code against in order to reproducible and we will consider reopening the issue.

**Comment by nitzanashi** [comment]
duplicate of #2034
