### ISSUE TITLE
Can't use some npm mail-listener diretly from a test case

### ISSUE THREAD

**Issue by idanRiski** [cypress-io/cypress#6728]
I'm trying to code some testing in **cypress 4.1.0** for some ongoing emails and verify their content when they received by some **nodejs mail-listener** 
(https://www.npmjs.com/package/mail-listener5), 
but I've managed to run it and to use his features only inside the *plugin index.js* and it's running before the tests.

When I'm trying to run it through the test case it returns the error below:

      1) An uncaught error was detected outside of a test:
         Uncaught TypeError: Invalid Version: 
    
    This error originated from your test code, not from Cypress.
    
    When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
    
    Cypress could not associate this error to any specific test.
    
    We dynamically generated a new test to display this failure.

I've also tried to use googleAPIs for gmail but it doesn't generate the gmail token and a redirect to some uri is required, also the token is limited for 30 days and I prefer something with a minimum maintenance.

Any idea?

**Comment by jennifer-shehane** [comment]
The code from your spec files in Cypress are executed in the browser, so you can import or require JS modules, but **only those that work in a browser**. 

The `pluginsFile` and `supportFile` however execute within Node, which is why it works there.

You can read a more detailed explanation here: https://on.cypress.io/using-cypress-faq#How-do-I-require-or-import-node-modules-in-Cypress
