### ISSUE TITLE
Open url in new window workaround doesn't work with multiple test blocks

### ISSUE THREAD

**Issue by tiennguyen-ftu-k52** [cypress-io/cypress#6760]
I’ve faced an issue with `cypress` about workaround to open url in new window
I registered a global event like this:

```js
Cypress.on('window:before:load', win => {
  // Replace window.open(url, target)-function with our own arrow function
  cy.stub(win, 'open', url => {
    // change window location to be same as the popup url
    cy.visit(url);
  }).as('popup'); // alias it with popup, so we can wait refer it with @popup
});
```

### Current behavior:
This works:

```js
it('test case 1', () => {
 cy.openPopup1()
 ...
 cy.openPopup2() -> work fine, open url in current window
});
```

However, if using multiple test blocks, it doesn’t work:

```js
it('test case 1', () => {
 cy.openPopup1();
 ...
});
it('test case 2, () => {
 cy.openPopup2(); -> doesn't work, open a new window
 ...
});
```

### Desired behavior:

Should work with multiple test blocks, it really affects to code structure & readability.

### Versions

`cypress` 4.1.0

**Comment by jennifer-shehane** [comment]
Can you include the code for your `onPopup1` and `onPopup2` test code? Ideally providing full HTML + Cypress test code we can run to reproduce - as this is provided, I cannot run your example. The issue will be closed without a reproducible example.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
