### ISSUE TITLE
Launching my application using cy.visit() ends up with the error "refused to connect"

### ISSUE THREAD

**Issue by jaiprksh17** [cypress-io/cypress#6761]
### Current behavior:

Launched the application using - `cy.visit('https://***.com') `

The given url has few following redirection url. I am facing an error that "refused to connect" when application tries to connect to the redirection url

Note: Redirection url reach to the SSO application 

### Desired behavior:

`cy.visit()` should take care of redirection url or any other way to achieve it

### Versions

Chrom = 80
Cypress = 3.8.3
Operation system = Windows

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

- Can you explain the redirection mechanism? - What is expected to happen?
- Can you paste a screenshot of the error you are seeing or the full text of the error?
- Can you open your DevTools and see if there are any errors/warning printed there and share those?

Please comment in this issue with a reproducible example and questions answered above and we will consider reopening the issue.
