### ISSUE TITLE
After failed tests new commands are not executing 

### ISSUE THREAD

**Issue by sushantlokhande** [cypress-io/cypress#6766]
Hi @bahmutov ,

I am facing the same issue in case of failed tests mentioned on page https://github.com/cypress-io/cypress/issues/5143

Can you please help me for this issue..

```
npm ERR! code ELIFECYCLE
npm ERR! errno 10
npm ERR! @splunk/splunk-login-react-component@0.0.63 e2e_mochawesome: `npm run cleanup && cypress run --browser chrome --env configFile=production --spec 'cypress/integration/first-tests.js,cypress/integration/second-tests.js' && npm run merge_reports && npm run generate_mochawesome_report && npm run move_report && npm run open_report`
npm ERR! Exit status 10
```

I am running this on windows machine and performing following actions:

1. - Delete existing json and html files inside mochawesome folder
2. - Run specs file
3. - Merge all json file into one `output.json`
4. - Generate `output.html` from `output.json`
5. - Open `output.html` in browser

My scripts are mentioned below:

```json
"scripts": {
"cleanup": "del /S /Q mochawesome-report\\*.*",
    "merge_reports": "mochawesome-merge --reportDir mochawesome-report > mochawesome-report/output.json",
    "generate_mochawesome_report": "marge mochawesome-report/output.json",
    "move_report": "move mochawesome-report\\mochawesome-report\\output.html mochawesome-report && rmdir mochawesome-report\\mochawesome-report",
    "open_report": "start mochawesome-report\\output.html",
    "e2e_mochawesome": "npm run cleanup && cypress run --browser chrome --env configFile=production --spec 'cypress/integration/first-tests.js,cypress/integration/second-tests.js' && npm run merge_reports && npm run generate_mochawesome_report && npm run move_report && npm run open_report"
  }

"devDependencies": {
    "mocha": "^5.2.0",
    "mochawesome": "^4.1.0",
    "mochawesome-merge": "^2.1.0",
    "mochawesome-report-generator": "^4.1.0"
  }
```

**Comment by jennifer-shehane** [comment]
I believe this was already answered in the previous issue here: https://github.com/cypress-io/cypress/issues/5143#issuecomment-533879420 

If a test fails in `cypress run`, we issue an exit code - the process will exit. To get around this, you should look into using our [Module API](https://on.cypress.io/module-api) and handling what you want to do after the run yourself (instead of exiting).

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
