### ISSUE TITLE
Legacy HTTPS configurations can cause requests to hang forever.

### ISSUE THREAD

**Issue by maximkoshelenko** [cypress-io/cypress#6771]
### Current behavior:
On 4.2.0 Version tests with functionality are crashed because XHR requests breaking the interaction with elements on the page.

![image](https://user-images.githubusercontent.com/35900275/76955376-b67e0600-691a-11ea-8001-cc91eac13a6c.png)
### Desired behavior:
If downgrade with the same project to 4.1.0 everything is working fine.
![image](https://user-images.githubusercontent.com/35900275/76954588-415e0100-6919-11ea-9146-98a31babde59.png)
The project will be added
[cypressSolution.zip](https://github.com/cypress-io/cypress/files/4348640/cypressSolution.zip)
Some elements are not rendered (popups which are visible on 4.1.0 just doest shown on 4.2.0), some events are breaking functionality of Cypress.
### Test code to reproduce
[cypressSolution.zip](https://github.com/cypress-io/cypress/files/4348640/cypressSolution.zip)
### Versions
4.2.0, Win and MacOS, Chrome, Firefox, Electron

**Comment by jennifer-shehane** [comment]
Thank you for providing a reproducible example! 

First things first, I do see the behavior you are describing with failures in 4.2.0 and all passing in 4.1.0.

Now to narrow down the example to the simplest example.

```js
Cypress.on('uncaught:exception', (err, runnable) => false)

it('tests', () => {
  cy.setCookie('OptanonAlertBoxClosed', 'value', { domain: '.www.pgeveryday.com' })
  cy.visit('https://www.pgeveryday.com/offers/printable-offers')
  cy.get('.logout-link:visible').should('not.be.visible')
  cy.get('.js-basket-status')
  cy.get('.pg-coupons__t-ic:first').click()
  cy.get('.modal-dialog button.close:visible')
})
```

## 4.1.0

<img width="1290" alt="Screen Shot 2020-03-19 at 5 25 06 PM" src="https://user-images.githubusercontent.com/1271364/77060222-9d528380-6a06-11ea-8c61-2363c9dbf05e.png">

## 4.2.0

<img width="1305" alt="Screen Shot 2020-03-19 at 5 27 06 PM" src="https://user-images.githubusercontent.com/1271364/77060384-e30f4c00-6a06-11ea-952c-9cf3121f6d5a.png">

The command logs look nearly identical. I initially thought this may be caused by changes in https://github.com/cypress-io/cypress/pull/6708, but stepping through the debugger on those changes, I'm not sure about that anymore.

**Comment by jennifer-shehane** [comment]
Alright, so the only other actual big change in 4.2.0 was https://github.com/cypress-io/cypress/pull/6705. I reverted the changes made in https://github.com/cypress-io/cypress/pull/6705 and it is now passing every time in `develop`, so looks like the changes there are the culprit. 😬

**Comment by maximkoshelenko** [comment]
> nd it is

Thanks, reply, for now, I downgrade all our tets to 4.1.0. Will be waiting for FIX

**Comment by maximkoshelenko** [comment]
Hello. @jennifer-shehane any updates regarding this one?

**Comment by jennifer-shehane** [comment]
Upon further investigation, there was some disagreement on whether https://github.com/cypress-io/cypress/pull/6708 or https://github.com/cypress-io/cypress/pull/6705 was the cause of this change of behavior. There is *some* flake involved, so that complicated the isolation. 

I'm running the test 10 times with no DevTools open - removing each PRs implementation. 

```js
describe("Testing", () => {
  Array(10).fill(0).forEach((val, i) => {
    it('tests', () => {
      cy.setCookie('OptanonAlertBoxClosed', 'value', { domain: '.www.pgeveryday.com' })
      cy.visit('https://www.pgeveryday.com/offers/printable-offers')
      cy.get('.logout-link:visible').should('not.be.visible')
      cy.get('.js-basket-status')
      cy.get('.pg-coupons__t-ic:first').click()
      cy.get('.modal-dialog button.close:visible')
    })
  })
})
```

## Develop 

10/10 failed

Rerun: 5/5 failed

<img width="438" alt="Screen Shot 2020-04-01 at 12 06 40 PM" src="https://user-images.githubusercontent.com/1271364/78105776-f57e8200-7417-11ea-867a-2b3367151251.png">

## Remove #6708 

8/10 failed

Rerun: 9/10 failed

<img width="440" alt="Screen Shot 2020-04-01 at 12 34 38 PM" src="https://user-images.githubusercontent.com/1271364/78105745-e4357580-7417-11ea-84f8-d23b8a596162.png">


## Remove #6705 

0/10 failed

Rerun: 0/10 failed

<img width="455" alt="Screen Shot 2020-04-01 at 12 53 13 PM" src="https://user-images.githubusercontent.com/1271364/78105700-c7993d80-7417-11ea-912b-864e9a21b450.png">


I don't understand how https://github.com/cypress-io/cypress/pull/6705 could be involved here either, but I find it very improbably that my results are something other than it being the source of the regression.

**Comment by maximkoshelenko** [comment]
I have tried to update my CY version into 4.3.0 half of tests just falling. And rendering not working correctly (on 4.1.0 some elements are visible after actions (clicking, or XHRs) on 4.2.0 and 4.3.0 nope). So hope you will continue the investigation. If I can help somehow let me know.

**Comment by flotwig** [comment]
I think there is something strange about `www.pgeveryday.com`'s SSL configuration. The HTTPS connection hangs about 50% of the time for me unless "legacy renegotiation" is enabled for the connection made from Cypress's HTTP agent.

#6130 was released in Cypress 3.8.3 and set Cypress's minimum TLS version to 1.0, which I guess also set "legacy renegotiation" as the default. Before this version, the spec @jennifer-shehane shared will fail about 50% of the time:

```
docker run -it -v `pwd`:/app -w /app cypress/included:3.8.2 --spec "cypress/integration/spec.js"

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  spec.js                                  06:38       10        4        6        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     06:38       10        4        6        -        -  
```

And from 3.8.3 until 4.2.0, it will pass 100% of the time:

```
docker run -it -v `pwd`/repro:/app -w /app cypress/included:3.8.3 --spec "cypress/integration/spec.js"

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  spec.js                                  01:11       10       10        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        01:11       10       10        -        -        -  
```

Then, #6705 was released in Cypress 4.2.0 due to the performance regression caused by #6130. #6705 caused the TLS minimum version to only be set to 1.0 after the connection errored out, but would not detect the strange hanging behavior found when "legacy renegotiation" is needed.

**Comment by maximkoshelenko** [comment]
@flotwig any updates regarding this one? Because we cannot update our solution to latest versions :)

**Comment by jennifer-shehane** [comment]
The fix for this was causing some performance regressions for all other users as noted in https://github.com/cypress-io/cypress/pull/6912 so was not fully implemented yet.
