### ISSUE TITLE
cy commands with options object should not display as Object{N} in the Command Log

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#678]
### Current behavior:

Prints visit "Object{4}" ? this is confusing because I only passed single timeout option and I cannot see the fields in that object. Devtools does not show anything on click

### Desired behavior:

- print `...`?
- print only non-default options?
- serialize the object to print VISIT {timeout: 20000} for example in this case

### How to reproduce:

Do `cy.visit` with extra options, like below

#### Test code:

```js
cy.visit("/", {timeout: 20000})
```

### Additional Info (images, stack traces, etc)

<img width="371" alt="screen shot 2017-09-21 at 8 49 52 am" src="https://user-images.githubusercontent.com/2212006/30696630-46a691fe-9eaa-11e7-91f9-ef13ba043119.png">

<img width="386" alt="screen shot 2017-09-21 at 8 50 32 am" src="https://user-images.githubusercontent.com/2212006/30696636-5014dfa2-9eaa-11e7-834d-9a13dbf95e57.png">

- Operating System: mac
- Cypress Version: 0.20.0
- Browser Version: electron

**Comment by sainthkh** [comment]
It's hard to know if it's intended or not, but this issue was somewhat fixed in #3489. It removes entire user option in that PR. 

But I found out that `Object{N}` problem isn't solved entirely. It's because 'Object{N}' part is generated in each command, not in reporter. 

But { force: false } in #2847 isn't still solved and trigger in #1045, too. 

To fix this problem, we need to check the entire list of driver api options and create a util function for message generation. 

Note: This bug isn't related with `pkg/server` or `pkg/reporter`. It's a `pkg/driver` bug.

**Comment by Manuel-Suarez-Abascal** [comment]
I would like to attempt to resolve this issue. Can you please provide me with some guidance on which files are involved? We should update the labels. Instead of using `pkg/server` or `pkg/reporter` labels, we should use the `pkg/driver` label instead as stated in [this comment](https://github.com/cypress-io/cypress/issues/678#issuecomment-554907714). @sainthkh

**Comment by dr-rockso** [comment]
test
