### ISSUE TITLE
Cypress can not auto accept `confirm` in iframe

### ISSUE THREAD

**Issue by ddddhhz** [cypress-io/cypress#6781]
As it stands Cypress's current behavior is to auto accept alert and confirm.  

I read https://github.com/cypress-io/cypress/issues/376 and https://github.com/cypress-io/cypress/issues/621 ,but I can't resolve my situation.

Because of some reason,I have to auto accept confirm which pop up in iframe.
 How can I fix this?

**Comment by ddddhhz** [comment]
@brian-mann  In view of your previous answer, could you help me find a way to solve it

**Comment by jennifer-shehane** [comment]
Examples here: https://github.com/cypress-io/cypress-example-recipes/issues/410

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
