### ISSUE TITLE
it.only runs all the tests

### ISSUE THREAD

**Issue by piotr-s-brainhub** [cypress-io/cypress#6803]
### Current behavior:

All the tests are run though I wrote `it.only`
https://circleci.com/gh/brainhubeu/react-carousel/2920

### Desired behavior:

Only the test marked with `it.only` should be run.

### Test code to reproduce

https://github.com/brainhubeu/react-carousel/pull/369

### Versions

cypress: 4.2.0
`cypress/included:4.2.0` Docker image
default browser, probably Chrome

**Comment by jennifer-shehane** [comment]
`it.only` only applies to the currently running specfile - since the specs are run completely separately within `cypress run`. While the `ClickToChange.test.js` spec file contains 2 tests, it only ran the test with `it.only`. 

If you want the run to also only run a single spec file, you can pass the [`--spec` flag](https://on.cypress.io/command-line#cypress-run-spec-lt-spec-gt) to run that single spec file.

**Comment by piotr-s-brainhub** [comment]
@jennifer-shehane 
thanks,
unfortunately `--spec` param isn't allowed for the `cypress verify` command and `cypress run` doesn't work at all for me because there's no connection with the server
