### ISSUE TITLE
Timeout not triggering fail event

### ISSUE THREAD

**Issue by averri** [cypress-io/cypress#6829]
### Current behavior:
The `fail` event is not being captured when a test fails due to timeout.

### Desired behavior:
The `fail` event should be captured when a test fails due to timeout.

### Test code to reproduce
```javascript
  cy.on('fail', () => {
    // This code will never be reached.
    cy.log('Ignoring this fail.')
    return false
  })

cy.get('div#submit').click({timeout: 1000})  // This should timeout. Make the button disabled to reproduce the timeout.
```

### Versions
cypress 4.2.0, Windows 10.

**Comment by jennifer-shehane** [comment]
Ok, so this is likely due to the difference between `cy.on` and `Cypress.on` explained here: https://on.cypress.io/catalog-of-events#Cypress (It's hard to be certain because you did not specify where your `cy.get()` is being called in an `it`.

*As a side note, you cannot call `cy` commands within the event listeners. https://github.com/cypress-io/cypress/issues/6316*

`cy.on` will only listen to events within the specific test whereas `Cypress.on` will listen to all events across tests. 

```js
Cypress.on('fail', () => {
  // This code will run for any failure in any test
  console.log('Cypress.on: Fail event')
  return false
})

it('test', () => {
  cy.on('fail', () => {
    // This code will run for this test failure
    console.log('cy.on: Fail event')
    return false
  })

  cy.visit('index.html')
  cy.get('#btn').click({ timeout: 1000 })
})
```

<img width="351" alt="Screen Shot 2020-03-25 at 4 36 23 PM" src="https://user-images.githubusercontent.com/1271364/77525046-ccf60580-6eb6-11ea-9604-4b86a1e1a550.png">

Please comment if you have an example outside of this where it is not working and we will consider reopening.

**Comment by averri** [comment]
Hi @jennifer-shehane, this could be caused by a 3rd party plugin. I have added more examples here: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/348

**Comment by jennifer-shehane** [comment]
Yeah, that may be.
