### ISSUE TITLE
How can I select an element duplicated in a list ? 

### ISSUE THREAD

**Issue by eGoudi** [cypress-io/cypress#6830]
Hi,

I present the HTML list below:

<img width="802" alt="Capture d’écran 2020-03-24 à 18 52 21" src="https://user-images.githubusercontent.com/58534476/77461419-ce65f600-6e02-11ea-8314-9117672bc461.png">

Now I want to select the first one using just the following command which I call via Gherkin in my test file (.feature):

```js
When(`I select {string} in {string} list`, (string, field) => {
  cy.get(`select[name="${field}"]`).select(string, { force: true });
});
```

But I got this following result:

<img width="620" alt="Capture d’écran 2020-03-24 à 19 00 18" src="https://user-images.githubusercontent.com/58534476/77461716-446a5d00-6e03-11ea-971e-c52466d72649.png">

I really need your help.

cordially

`

**Comment by jennifer-shehane** [comment]
You have to include the full text for `.select()`, it does not partially match text - it has to be an exact match. You test is missing the end text of ` Maturity Date`.

```
cy.get('select').select('Following Business Day convention, unadjusted up to and including the Maturity Date, and up to and including the Extended', { force: true });
```

should be:

```
cy.get('select').select('Following Business Day convention, unadjusted up to and including the Maturity Date, and up to and including the Extended Maturity Date', { force: true });
```

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by eGoudi** [comment]
Thank you
