### ISSUE TITLE
unable to proceed SAML sso

### ISSUE THREAD

**Issue by NilukaSripalim** [cypress-io/cypress#6837]
Description:
I already create node.js sample app for SAML sso using passport.js, then I try to sso with Identity provider WSO2 (https://wso2.com/identity-and-access-management/) but when i try to sso in manually with out any issue i could, when automate the process via cypress, i couldn't proceed, 

```js
import LandingPage from '../rest-api/scim-api-user.js'
describe('landing page tests', function () {
   const landingPage = new LandingPage();
   before(function() {
   cy.visit('http://localhost:3000/app');
  cy.visit('/');
    cy.fixture('new-user').as("user");
       
        cy.fixture('new-scim-user-create').as("data");
    });

    
      it('checks user menu content and actions', function () {
        // Check user email in profile drop down
        
        cy.get('@user')
        .then(user => {
            let base64Encode = cy.base64encode(user.adminuser, user.adminupword);
            const userName = user.adminuser;
            const password = user.adminupword;
            cy.log("@@@@@@@@"+userName+"******"+password)
            //landingPage.createSCIMUser(userName, password, base64Encode, this.data);
            
        })
        cy.wait(3000);
        cy.login();
    })
```

![image](https://user-images.githubusercontent.com/39120228/77507008-555fb080-6e8d-11ea-8172-d94e3c7a350d.png)

**Comment by jennifer-shehane** [comment]
The redirect is what happens in your application. I'm not sure what is triggering the page load, but it is not Cypress loading a new page. Cypress imply logs that there has been a new page load (somehow triggered from your application). 

I would recommend checking out our recipes on logging in: https://on.cypress.io/recipes#Logging-In

Also, the screenshot you posted has your username and password information exposed, so I would suggest resetting your username and password for your test application.

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by NilukaSripalim** [comment]
Thanks, but  @jennifer-shehane, if the issue with app, so why the issue is not occurring when try with manually, do you have any idea to avoid page reload, It is great if you can give me any clue .

**Comment by jennifer-shehane** [comment]
It looks like your app reroutes to some outside authentication URL in order to retrieve a sessionDataKey or other authentication keys during login. I can't say for sure without knowing your application.

**Comment by jennifer-shehane** [comment]
Please provide a reproducible example. Some other things that may be helpful:

- Provide comparible videos of run in Cypress versus outside of Cypress. 

You cannot *stop* a page reload that is initiated by your application. Likely there is some difference between your application when run under Cypress and outside of Cypress - it could be any number of things that is not reproduced completely in your Cypress environment.
