### ISSUE TITLE
cy.visit() by invoke('text') from an element have URL text

### ISSUE THREAD

**Issue by HussamAlHunaiti** [cypress-io/cypress#6846]
### Current behavior:
According to the documentation, cy.visit() should visit a page by URL as a string. I wanted to capture a URL text into an element and save the value in POM variable 'ex: Url: string' then try to visit a page by cy.visit(POM.Url), but no XHR and do not visit the page.

Note: invoke('text') work correctly and save a URL text in POM variable and the cy.visit() take a correct URL from POM variable but it does not visit the page. 

### Desired behavior:
```
cy.get('.url-link').invoke('text').then((urlText: JQuery) => {
pom.url = urlText.toString();
});
cy.visit(pom.url);
```

- Expected cy.visit() can visit an page by invoke('text')

### Test code to reproduce
```
cy.get('.url-link').invoke('text').then((urlText: JQuery) => {
pom.url = urlText.toString();
});
cy.visit(pom.url);
```
### Versions
3.8.3

#Chrome

**Comment by jennifer-shehane** [comment]
`pom.url` evaluates immediately within the `cy.visit()` before it is set above. Please read https://on.cypress.io/introduction-to-cypress#Commands-Are-Asynchronous

## Works

```js
const pom = {}

it('test', () => {
  cy.visit('index.html')
  cy.get('.url-link').invoke('text').then((urlText) => {
    pom.url = urlText.toString();
    // works
    cy.visit(pom.url);
  });
})
```

## Works

```js
const pom = {}

it('test', () => {
  cy.visit('index.html')
  cy.get('.url-link').invoke('text').then((urlText) => {
    pom.url = urlText.toString();
    // works
    cy.visit(pom.url);
  });
})
```

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
