### ISSUE TITLE
Is it possible to fetch the entire json data from the json file, placed in the fixtures folder and paste it's content in the textarea?

### ISSUE THREAD

**Issue by Jeev1510** [cypress-io/cypress#6849]
### Current behavior:

```js
cy.readFile('cypress/fixtures/swagger-sample.json').its('openapi').should('eq', '3.0.0') 
```

This reads the respective variables value for comparing

### Desired behavior:

If either `cy.readFile` / `cy.fixtures` should fetch the entire data of the json file as such.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by Jeev1510** [comment]
Thanks for letting me know. I have raised the same in the chat. Can you please get back on that?
