### ISSUE TITLE
Log in through external provider (different super domain)

### ISSUE THREAD

**Issue by ilianabe** [cypress-io/cypress#6866]
I have an application with a login button. When the login button is clicked, it redirects to another page (second superdomain) with a login form. The user types the email and password and clicks the login button (in the second superdomain). My app takes the user's data and redirects back to my app in a form page with the user's data (name, date of birth, etc) fulfilled. 
### Current behavior:

- 1st Attempt: with the use of cypress-social-logins. 
I tried to customize the plugin by changing the selectors and paths, but I didn't manage to make it work

- 2nd Attempt: with the use of request().
I tried to request the external page without clicking the first login button but I haven't found a way to type data.

- 3rd Attempt: by disable chrome-security.
I added   "chromeWebSecurity": false, on my cypress.json and tried to click the first login button as normally. I get this error: chrome-error://chromewebdata/

### Desired behavior:

My App:
User clicks the login button. 
It redirects him to login page of external app.

External App:
The user types username and password.
The user clicks the login button.
It redirects him back to My App with some data which are being displayed in UI.

### Versions

Cypress: 3.8.2

Is there any way to test my app with cypress?

**Comment by jennifer-shehane** [comment]
chrome-error://chromewebdata/ is this issue: https://github.com/cypress-io/cypress/issues/4220

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
