### ISSUE TITLE
 Unable to click on tag "<a href> " link NetworkError: Failed to execute 'send' on 'XMLHttpRequest':

### ISSUE THREAD

**Issue by Vikas1712** [cypress-io/cypress#6870]
### Current behavior:
NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load

### Desired behavior:

Should able to click and navigate to link successfully

### Test code to reproduce
I have uploaded solution code to github: https://github.com/Vikas1712/Assignment

I have uploaded solution code to github: https://github.com/Vikas1712/Assignment

**Comment by jennifer-shehane** [comment]
There is a warning in the DevTools console clicking the `[data-testid=btn-telefoons]` button, inside and outside of Cypress:

```
Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://gcpsmapi.vodafone.com/sec/submit-events': Synchronous XHR in page dismissal. See https://www.chromestatus.com/feature/4664843055398912 for more details.
```

<img width="1054" alt="Screen Shot 2020-03-30 at 3 52 05 PM" src="https://user-images.githubusercontent.com/1271364/77896581-83cef880-729e-11ea-9f3b-96bf31d88008.png">

### Also throwing outside of Cypress

![](http://g.recordit.co/tkIkaZZMW4.gif)

Clicking into this error explains where this error is coming from and how to fix it (introduced in Chrome 80): https://www.chromestatus.com/feature/4664843055398912 explaining:

>Chrome now disallows synchronous XHR during page dismissal when the page is being navigated away from or closed by the user. This involves the following events (when fired on the path of page dismissal): beforeunload, unload, pagehide, and visibilitychange.

You error is throwing due to your application code when run in Chrome 80 and you need to address it - Cypress is catching this error for you and showing it in your test to highlight the need for you to address it. 

You can ignore failing the test on these exceptions by [turning off uncaught excpetion handling](https://on.cypress.io/catalog-of-events#Uncaught-Exceptions)

Test Code I ran:

```js
///<reference types="cypress"/>

it('Assignment', function () {
    cy.server();
    cy.visit("https://www.vodafone.nl/").then(function () {
        cy.url().should('include', 'vodafone');
    })
    cy.get('.cookiewall__cookiewall')
    cy.get('.lgi_btn_3').should('contain', 'Accepteren')
    cy.get('.lgi_btn_3').click()
    cy.wait(6000);
    cy.route('GET', 'gcpsmapi.vodafone.com*').as('getMapi')
    cy.request('https://gcpsmapi.vodafone.com')
    cy.get('`[data-testid=btn-telefoons]`').should('contain', 'Telefoons');
    cy.get('[data-testid=btn-telefoons]').click();
})
```
