### ISSUE TITLE
2 waits to the same endpoint return timeout for the longest

### ISSUE THREAD

**Issue by KarmaCop213** [cypress-io/cypress#6874]
### Current behavior:

I have 2 endpoints being called in my page with the same URL. The first one is waited but the second isn't

```javascript
    cy.server()
    cy.route({
      url: "/graphql",
      method: "POST"
    }).as("graphql")
    cy.login(Cypress.env("loginUser"), Cypress.env("loginPassword"), "login-option-system")
    cy.wait(["@graphql", "@graphql"], { timeout: 60000 })
```

I get the following error after 60s although the 1st request finished in 1s and the 2nd in 30s

`
CypressError: Timed out retrying: cy.wait() timed out waiting 60000ms for the 2nd response to the route: 'graphql'. No response ever occurred.
` 
 
### Desired behavior:

The second request should be awaited correctly and cypress should detect that it already finished instead of throwing a timeout error.

**Comment by jennifer-shehane** [comment]
Cypress will wait for both routes requests and responses to finish within a combined 60 seconds when passing an array of routes to `.wait()`. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

I can't recreate this behavior of waiting for the same endpoint - not waiting for second input. 

My example:

`index.html`

```html
<html>
<body>
  <input />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script>
    $(() => {
      $('input').on('keyup', (e) => {
        $.ajax({
          url: 'https://jsonplaceholder.cypress.io/comments',
          method: 'POST',
          data: {
            name: 'Using POST in cy.route()',
            email: 'hello@cypress.io',
            body: 'You can change the method used for cy.route() to be GET, POST, PUT, PATCH, or DELETE',
          },
        })
      })
    });
  </script>
</body>
</html>
```

```js
it('2 routes', () => {
  cy.server()
  cy.route('POST', 'https://jsonplaceholder.cypress.io/comments').as('postComment')
  cy.visit('index.html')
  cy.get('input').type('fi')
  cy.wait(['@postComment', '@postComment'], { timeout: 60000 })
})
```

<img width="617" alt="Screen Shot 2020-03-30 at 4 11 18 PM" src="https://user-images.githubusercontent.com/1271364/77898429-1ec8d200-72a1-11ea-9a6f-342fa4442366.png">


Please comment in this issue with a fully reproducible example and we will consider reopening the issue.

**Comment by KarmaCop213** [comment]
No worries, I solved this issue  by waiting for the `get` of the element that is populated with the data that comes from the response of those calls:

```javascript
cy.get(`my-id`, { timeout: 60000 })
```

Not sure if this is the correct way to do this, but it works.
