### ISSUE TITLE
Chainable interface doesnt work after import 'cypress-file-upload'

### ISSUE THREAD

**Issue by dbuchar** [cypress-io/cypress#6879]
Hello, 

after import 'cypress-file-upload' in commands.ts doesnt work any more interface Chainable. 

### Current behavior:

![image](https://user-images.githubusercontent.com/62888283/77915128-3602c200-7297-11ea-8570-13f9bc138fe0.png)

### Desired behavior:

When I delete row 2 with import everything work fine again. 

### Versions

cypress 4.1.0

**Comment by karol-majewski** [comment]
`cypress-file-upload` has a bug in their typings. A type parameter called `Subject` is [used, but never declared](https://github.com/abramenal/cypress-file-upload/blob/31c925cdcedb58be91d83ffaac09ed5a0f992f8a/types/index.d.ts#L26-L33).

The fix is pretty easy, but it needs to be introduced in that repository. Either change the name of the type parameter to `Subject` or remove the second overload altogether.

```diff
-  interface Chainable<JQuery = any> {
+  interface Chainable<Subject = any> {
```

For the time being, you may want to use [`patch-package`](https://www.npmjs.com/package/patch-package) to make that change locally in your project.

**Comment by jennifer-shehane** [comment]
Closing as not an issue with the Cypress product itself. Please open an issue in the [`cypress-file-upload` repo](https://github.com/abramenal/cypress-file-upload).
