### ISSUE TITLE
Can't pass hash values containing exponential operators to --env command line option.

### ISSUE THREAD

**Issue by tzolnai** [cypress-io/cypress#6891]
### Current behavior:
We use `--env` variable to pass some environment variables to cypress, when it's running both in headless and headed mode. 

One of the parameters is a hash (mix of numbers and characters). Surprisingly some specific hash values make cypress to fail reading this value from the command line (e.g. `769e98018`). The corresponding environment variable is not set and the `Cypress.env()` function returns with `null`.

### Desired behavior:
It should not be a problem to read a hash from the command line and put into an environment variable.

### Test code to reproduce
A simplified command line call:

```
node_modules/cypress/bin/cypress open --env WSD_VERSION_HASH=769e98018
```

Test code showing the issue:

```js
describe('Hash test.', function() {
    it('Test 1.', function() {
        expect(Cypress.env('WSD_VERSION_HASH')).to.equal('769e98018');
    });
});
```

This test fails with: 'expected null to equal 769e98018'

If I remove the 'e' character for example, then the value is read correctly.

### Versions
Cypress 4.1.0
OpenSUSE 15.1 and Ubuntu 18.04

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-159) by [Unito](https://www.unito.io/learn-more)

**Comment by CypressCecelia** [comment]
I was able to confirm this behavior running locally on 4.1 and 4.3. Passing a string OR a number is fine, but a hash comes through as null.

**Comment by jennifer-shehane** [comment]
Logged in plugins file configuration, the value is showing as `null`:

Logged in Settings - Configuration panel, the value is showing as Infinity 😅 

Basically this value is being converted to a Number - due to the `e`, if you change the value to say '769d98018' - with a `d`, it is now read correctly as a string. 

For example, lodash considers this a number. 

<img width="366" alt="Screen Shot 2020-04-01 at 2 04 30 PM" src="https://user-images.githubusercontent.com/1271364/78110900-cec54900-7421-11ea-80e4-0414a7159ea4.png">

The transformation from the actual value to a Number (specifically Infinity) happens through this method:

https://github.com/cypress-io/cypress/blob/test-retries/packages/server/lib/util/args.js#L234

You can see if you log the value before and after that function that it's transformed to this value.

<img width="408" alt="Screen Shot 2020-04-01 at 2 13 48 PM" src="https://user-images.githubusercontent.com/1271364/78111779-2e702400-7423-11ea-9fd0-11b68d1e3a95.png">

The root culprit is actually this call here where it's calling `JSON.parse('769e98018')` 

https://github.com/cypress-io/cypress/blob/test-retries/packages/server/lib/util/args.js#L85:L85

<img width="213" alt="Screen Shot 2020-04-01 at 2 47 40 PM" src="https://user-images.githubusercontent.com/1271364/78114779-cc65ed80-7427-11ea-9405-8159de477692.png">

It seems like the code has always been this way - I traced this code being here at least 2 years, so this is likely a very rare edge case.

**Comment by jennifer-shehane** [comment]
I'm not really sure that I'll have time to address this, but the thought on how to handle this was to do a regex check for exponential operators and transform them to a string.

**Comment by nimish-gupta** [comment]
Hey @jennifer-shehane, I can start working on this issue.

For this, I can check for infinity (Both negative and positive) after the value is parsed

**Comment by jennifer-shehane** [comment]
The code for this is done in [cypress-io/cypress#8051](https://github.com/cypress-io/cypress/pull/8051), but has yet to be released.

We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.
