### ISSUE TITLE
Peer dependency warning when installing cypress 4.3.0

### ISSUE THREAD

**Issue by crfrolik** [cypress-io/cypress#6896]
### Current behavior:

```
warning cypress > extract-zip > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
```

### Desired behavior:

No warnings. It looks like `extract-zip` 2.0.0 has addressed this, so cypress should upgrade to use it.

### Versions

Cypress 4.3.0

**Comment by jennifer-shehane** [comment]
Duplicate of #6730

**Comment by jennifer-shehane** [comment]
Actually, I'm going to reopen this specifically. If we bumped `extract-zip` to `2.0.0`, this would be a breaking change in Cypress because their update requires Node.js 10.12. Cypress currently only requires Node.js 8+. https://github.com/cypress-io/cypress/pull/6905

You can safely ignore deprecation warnings though. They should not effect your run.

**Comment by jennifer-shehane** [comment]
Still can't bump this because Cypress only requires Node.js 10+

**Comment by sainthkh** [comment]
[Node 10 ends of life at April 30th, 2021](https://nodejs.org/en/about/releases/). Maybe we can safely update extract-zip to 2.0.0 after the date.

**Comment by jennifer-shehane** [comment]
Our next major release (7.0) is scheduled for Feb 16 - the one after would be scheduled for May 10, so...could probably aim for the later release.

**Comment by jennifer-shehane** [comment]
Opened an issue for dropping Node.js 10 support https://github.com/cypress-io/cypress/issues/9545

**Comment by jimmywarting** [comment]
Time to update extract-zip now?
