### ISSUE TITLE
Run on AWS Lambda

### ISSUE THREAD

**Issue by newtack** [cypress-io/cypress#690]
I would like to run each cypress test as a separate lambda function to 
a) Consume (and pay) resources only when I need them
b) Scale horizontally and execute tests parallely.

Can I run a Cypress test on AWS Lambda (node js runtime) and if so, what is needed to do so?

**Comment by brian-mann** [comment]
I will likely never be possible to parallelize by individual test. However, It is possible to parallelize by individual spec files (the files that contain the various tests).

The bigger problem here is that Lambda is probably not a great choice for browser based tests for these reasons:

- Tests would have to finish in under 300 seconds (including things like installing Cypress, uploading results, etc)
- There is a 1.5gb memory limit which is very low for browsers. 
- There is also only 512mb disk space which is also very tight due to needing to install your app code, the Cypress binary itself, individual browsers, and then unique browser profiles.
- Cypress requires certain system dependencies be installed. Our docs / docker containers go into all those details.
