### ISSUE TITLE
Second drop down list does not get filled

### ISSUE THREAD

**Issue by gcostafinkel** [cypress-io/cypress#6910]
Hello guys, I ran into a problem. Can anyone help me ?

So, I have two drop down lists and the second is dependent on the option I choose on the first. 

Say, for example: The first drop down list has the options 'numbers' and 'letters', while the second drop down list is empty by default. However, when I choose the option 'letters' on the first drop down list, the second is filled with the options 'A', 'B' and 'C'. Manually, it is working fine, but when I select the first drop down list with Cypress, the second doesnt get filled. It remains empty, so I cant choose anything on it.

HTML:
```html
<select id="list" class="selectpicker form-control" onchange="">
  <option value="0">select your preference</option>
  <option value="2">numbers</option>
  <option value="3">letters</option>
</select>
```

CYPRESS:
```js
cy.get('#list').select('letters')
```

it does select the option letters, I can see the option letters selected on the first drop down list, but nothing happens on the second.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
