### ISSUE TITLE
CypressError: cy.visit() failed trying to load:

### ISSUE THREAD

**Issue by sari555** [cypress-io/cypress#6915]
Hi,
I'm getting following error when accessing `.gov` url from cypress code. I have cypress installed and running within the gov network. When executing `cy.visit` I get following error:

```
'https://.......gov'
The response we received from your web server was:
 401: Unauthorized
This was considered a failure because the status code was not '2xx'.
If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'
```

I have also tried following but still not working:

```js
describe('MyTestSuite', function() {
    it('Verify title of the page', function() {
        cy.request({
            method:'POST',
            url:'https://....gov
            body:{userName: "******", password: "******"},
            failOnStatusCode: false
          })
          cy.visit('https://....gov') })
```

Any idea how to resolve this issue? Please help

**Comment by jennifer-shehane** [comment]
The web server when issuing the `.visit()` is responding `401: Unauthorized`, so you'll need to make sure to validate that authorization is valid before continuing to your website in your test. Maybe you need `auth` headers in the [`cy.visit()`](https://on.cypress.io/visit#Arguments)? I can't say without knowing your application. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
