### ISSUE TITLE
File watching does not execute actual code changes when site under test utilizes Service Workers.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#6919]
### Current behavior:

There is a situation where making code changes will cause the test to reload (as if there are recognized changes in the file), yet the actual code changes in the test file are not executed. 

![](http://g.recordit.co/aRPeqM7fRx.gif)

Furthermore, I can even kill Cypress and reopen - Cypress flashes the new code while it visits the random port `localhost:12830` and then switches to the url under test and restores the ORIGINAL test file code when it stopped 'watching'. This isn't noticeable at all though if you have a `baseUrl` set. 

![](http://g.recordit.co/q55UxDypSE.gif)

### Test code to reproduce

Well, I can't provide the url since it was privately provided to me, but I think there's something about the url that is involved because I can't recreate it when visiting some other sites Cypress owns. 

```js
describe('Bug reproducing test', function () {
  it('case 1', function () {
    cy.visit('/') // url not provided for privacy
  })
})
```

### Versions

4.3.0

**Comment by chrisbreiding** [comment]
The reason is that the site is using a Service Worker and it's caching the test file locally. The 'reload' message makes it through, but when the browser goes to fetch the spec, the Service Worker returns the one it has cached. You can see this in the DevTools Network tab:

![Screen Shot 2020-04-02 at 9 44 42 AM](https://user-images.githubusercontent.com/1157043/78256741-f0c4d700-74c6-11ea-8e26-2a5b34d131b1.png)

Clearly, we need to take this into account in Cypress somehow. 

The only workaround for now I can think of is to disable Service Workers when running Cypress tests. I'm not really familiar with the Service Worker API at all, so I'm not sure if it's possible, but another option would be to blacklist the test files somehow so only they don't get cached.

**Comment by bahmutov** [comment]
@chrisbreiding we could just delete it from the browser API like this https://glebbahmutov.com/blog/cypress-tips-and-tricks/#disable-serviceworker
```js
it('disables it', function () {
  cy.visit('index.html', {
    onBeforeLoad (win) {
      delete win.navigator.__proto__.serviceWorker
    }
  })
})
```

**Comment by chrisbreiding** [comment]
Thanks, @bahmutov! Should have assumed you would have a blog post about it 😄

Note that I had to go into `DevTools > Application > Service Workers` and click `Unregister` first, so that it would allow the new spec file through.

**Comment by bahmutov** [comment]
Yeah cleaning unwanted service worker is a major pain

**Comment by jennifer-shehane** [comment]
## Current workaround

1. Within Chrome, go into `DevTools > Application > Service Workers` and click `Unregister`.
2. Add the code below for every visit to the site utilizing Service Workers:

```js
cy.visit('https://my.website.com', {
  onBeforeLoad (win) {
    delete win.navigator.__proto__.serviceWorker
  }
})
```

**Comment by EtienneBruines** [comment]
Despite having service-workers active, I do not encounter this issue. 

Tested with `Cypress: 4.3.0` and `Chrome 80, Chrome 83 and Firefox 74`

Perhaps it is an issue with the particular service-worker code?

**Comment by jennifer-shehane** [comment]
This is actually of duplicate of https://github.com/cypress-io/cypress/issues/702 which has a fuller proposal for work and a better workaround. 

Duplicate of #702
