### ISSUE TITLE
Not able to execute scripts using integrationFolder from cypress.json?

### ISSUE THREAD

**Issue by senthkum** [cypress-io/cypress#6927]
### Current behavior:
I have created multiple projects and I have multiple scenario folder created and want to execute the spec files inside the folder and execute an individual spec under any specific folder. I am not able to achieve it.

I tried executing the scripts with the below command both did not work, It is executing all the spec under the integration folder.

```
"runSingleSpec": "npm run runDemowebshop --spec \"Categories-Modules/*\""   
"runSingleSpec": "npm run runDemowebshop -- --spec \"Categories-Modules/*\""   

"runSingleSpec": "npm run runDemowebshop --spec \"Categories-Modules/Books.js\""   
"runSingleSpec": "npm run runDemowebshop -- --spec \"Categories-Modules/Books.js\""   
```

**cypress.json:**
```json
{
  "defaultCommandTimeout": 4000,
  "pageLoadTimeout": 60000,  
  "Environments": {
    "L-Env": "http://demowebshop.tricentis.com/"
  },
  "projectId": "p7n7io",
  "integrationFolder": "Demowebshop/cypress/integration/",
  "reporter": "mochawesome",
  "reporterOptions": {
  "reportDir": "./mochawesome-report",
  "overwrite": false,
  "html": true,
  "json": true
  }
}
```

**package.json:**
```json
  "scripts": {
    "runDemowebshop": "cypress run --config-file=Demowebshop/cypress.json",
    "runAllSpec": "npm run runDemowebshop --spec \"Categories-Modules/*\""
     "runSingleSpec": "npm run runDemowebshop --spec \"Categories-Modules/Books.js\""    
     "runSingleSpec": "npm run runDemowebshop -- --spec \"Categories-Modules/Books.js\""   
  },
```

![specExecution](https://user-images.githubusercontent.com/46837197/78310791-b298e780-759a-11ea-9e78-c8980fd11a55.jpg)

![running all spec](https://user-images.githubusercontent.com/46837197/78310799-b6c50500-759a-11ea-9ab5-99af8bd7816f.jpg)

Thanks
Senthil.M

**Comment by jennifer-shehane** [comment]
To pass arguments to npm scripts, you need to append `--`, so `npm run runDemowebshop -- --spec` would be the correct signature, the other will not read the argument correctly. See [`npm run` docs](https://docs.npmjs.com/cli/run-script). You will see the resolved arguments printed before it runs. 

The following scripts work, for example:

```js
"scripts": {
  "cypress:run": "cypress run --browser=chrome",
  "cypress:run:demo": "npm run cypress:run -- --spec=cypress/integration/categories/spec.js"
}
```

<img width="822" alt="Screen Shot 2020-04-07 at 2 32 34 PM" src="https://user-images.githubusercontent.com/1271364/78644919-aedbcc80-78dc-11ea-99a4-3e262c6c0e99.png">

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by senthkum** [comment]
Hi Jennifer,

Thanks for your response. I have my node_modules and package.json in common for multiple projects created. I have the cypress.json for each project. Know I am trying to execute an individual spec from a folder. I am not able to achieve this. Sorry I did not mention in the previous post. I tried the below command to execute, but it did not work. Please help me here, I am stuck with this for a few days.

![image](https://user-images.githubusercontent.com/46837197/78739242-2f5f0380-7997-11ea-8aa2-41f4981f5725.png)

"SingleScript": "npm run runDemowebshop -- --spec \"/Categories-Modules/Books.js\""
"SingleScript": "npm run runDemowebshop -- --spec=/Categories-Modules/Books.js"
D:\cypress-multiple-project>npm run SingleScript

![image](https://user-images.githubusercontent.com/46837197/78738953-8c0dee80-7996-11ea-8043-4ea23ee76b5c.png)


**cypress.json:**
{
  "defaultCommandTimeout": 4000,
  "pageLoadTimeout": 60000,  
  "Environments": {
    "L-Env": "http://demowebshop.tricentis.com/"
  },

  "projectId": "p7n7io",

  "integrationFolder": "Demowebshop/cypress/integration",
  "reporter": "mochawesome",
  "reporterOptions": {
  "reportDir": "./mochawesome-report",
  "overwrite": false,
  "html": true,
  "json": true
  }

}

**package.json**
"scripts": {
"runDemowebshop": "cypress run --config-file=Demowebshop/cypress.json",
"SingleScript": "npm run runDemowebshop -- --spec \"/Categories-Modules/Books.js\""
},


![current folder](https://user-images.githubusercontent.com/46837197/78736648-0471b100-7991-11ea-9965-8ec7f96999e6.jpg)

![image](https://user-images.githubusercontent.com/46837197/78737882-ee192480-7993-11ea-8fb1-96868ad412f5.png)

![image](https://user-images.githubusercontent.com/46837197/78737905-fd986d80-7993-11ea-887b-2794aaeb1e3d.png)

![image](https://user-images.githubusercontent.com/46837197/78739088-de4f0f80-7996-11ea-8fc6-93569df75aa5.png)



Thanks
Senthil.M

**Comment by jennifer-shehane** [comment]
As stated previously https://github.com/cypress-io/cypress/issues/6927#issuecomment-610240174:

>The `--spec` argument should take a path that is relative to the current path where the command is executing from - not the `integrationFolder`. 

Since you are within the `cypress-multiple-project` directory when you run `cypress run` - the `--spec` path needs to be relative to this directory. 

```
---spec Demowebshop/cypress/integration/Categories-Modules
```

Please check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
