### ISSUE TITLE
Capturing the assertion message from TestRunner window.

### ISSUE THREAD

**Issue by ranjankale** [cypress-io/cypress#6928]
After a test runs successful and clicking on "assert" from the command log, the assertion message is logged into the browser console.
Is there a way I can capture the assertion message into my test/hooks to log it into a file for reporting purpose ? 
@brian-mann

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
