### ISSUE TITLE
Cypress typing  one one character instead of whole string in window poup

### ISSUE THREAD

**Issue by rikisudhir** [cypress-io/cypress#6937]
### Current behavior:

Hello, In my application there is a popup window , in which there are some text areas.  I need to enter string in all those text areas. But when I pass any value its typing character by character instead of whole string .
example:
I am trying to type a string "serverCert1"  in the text area but cypress typing it character by character i.e s  e  r v  e  r .... makes my execution very slow
Its waiting for 2 secs before typing next character. So taking around 22 secs
But in normal page like login page its typing the full string (username and password) in one go. 

### Desired behavior:

it should type it as whole string or should type fast 

### Test code to reproduce

```js
cy.get('#addId_label').click({force: true})//popup window opens 
cy.get('#ks_alias_id').type('serverCert1',{force:true}).should('have.value', 'servercert1')   type serverCert1  
cy.get('#cn_id').type('serverCert2',{force:true}).should('have.value', 'servercert2') // type   serverCert2
```

### Versions

4.3.0

**Comment by jennifer-shehane** [comment]
Cypress mimics typing as a user would - a user cannot type a full line of text without typing it character by character. You can change the `delay` options of type to be lower to have it a bit faster `cy.type('foo', {delay: 0})`. 

Each character **should** take 10ms to type, which is very fast. 

But, your real issue is a performance issue - where likely you are doing XHR requests on every key event which is detailed here: https://github.com/cypress-io/cypress/issues/6783

You can get around typing by just inserting the value (as you would in JavaScript)

```js
cy.get('textarea').invoke('val', 'all my text here')
```

**Comment by adamgilg** [comment]
@jennifer-shehane A related question - Cypress is typing very slowly in a textarea in my app, which is not in itself a huge issue as I can just invoke the text value and essentially 'paste' into the textarea. However, `invoke` seems to refuse to work with multiline text no matter how I try to convince it to. It will only take the content up to the first `\n`. Any suggestions?
