### ISSUE TITLE
Cypress.exe recognized as malicious code by VirusTotal

### ISSUE THREAD

**Issue by dkwolek** [cypress-io/cypress#6942]
### Current behavior:
Cypress.exe which is part of 4.3.0 ver. and taken from official source: https://download.cypress.io/desktop/4.3.0?platform=win32&arch=x64

is being recognized as malicious by VirusTotal:

https://www.virustotal.com/gui/file/fc87c2c0120b86409eb00e3dbe87521d868c115c699f899e565d2e2b4c3b447d/detection

### Desired behavior:

Exe files should be clean from viruses and malicious code but **it might be problem with TotalVirus as well**

### Test code to reproduce

Download Cypress.exe from https://download.cypress.io/desktop/4.3.0?platform=win32&arch=x64
and verify on VirusTotal

### Versions

4.3.0

**Comment by jennifer-shehane** [comment]
Our application undergoes notarization from Apple (starting in 4.3.0), which scans our software for malicious content. https://github.com/cypress-io/cypress/pull/6013

Seems like Trapmine specifically is labeling this as `Malicious.moderate.ml.score`, yet all other detectors show 'undetected'. 

Also mentions the `File is not signed` which also doesn't seem accurate because we are signing the app. 

I would say this is something to do with VirusTotal.
