### ISSUE TITLE
Assertions for color/background-color fail on CI pipeline and pass locally

### ISSUE THREAD

**Issue by tachojelev** [cypress-io/cypress#6947]
I would like to start by saying that cypress is awesome, my team and I love how everything is configured and executed with ease!

We are currently working on integrating Cypress into our CI pipeline at Atlassian Bamboo for our Angular 8.x.x project.

### Current behavior:

**(Reproduced on both electron and chrome headless in CI).**

Locally, everything is working okay and as expected.

On the build agent in Bamboo, around 90% of the actual values we are receiving for **background-color** and **color** assertions are either **rgb(0, 0, 0)** or **rgba(0, 0, 0, 0)** (or in **very** rare cases, they are simply incorrect). This is quite strange since locally, these assertions are passing.

```js
cy.get(`my-element`).should('have.css', 'background-color', rgba(0, 0, 0, 0.12))
```

```
 CypressError: Timed out retrying: expected '<div...>' to have CSS property 'background-color' with the value 'rgba(0, 0, 0, 0.12)', but the value was 'rgba(0, 0, 0, 0)'
```

```
CypressError: Timed out retrying: expected '<div...>' to have CSS property 'background-color' with the value 'rgba(51, 191, 197, 0.54)', but the value was 'rgba(0, 0, 0, 0)'
```

Similar inconsistencies occur for some other assertions:

```
CypressError: Timed out retrying: expected '<div...>' to have CSS property 'font-family' with the value '"Source Sans Pro"', but the value was '"Times New Roman"'
```

```
CypressError: Timed out retrying: expected '<div...>' to have CSS property 'top' with the value '151.5px', but the value was '-6748.5px'
```

**NOTE: Most other tests are passing with no issues.**

### Desired behavior:

The assertions should be consistent for local and CI test run.

### Test code to reproduce

**Used scripts:**

```
"e2e:cypress:run:chrome": "cypress run --headless --browser=chrome".
"e2e:cypress:verify": "cypress verify",
"ci:start-server": "angular-http-server --silent --path ./dist/lib-demo -p 4200",
"ci:e2e": "start-server-and-test ci:start-server http://localhost:4200 e2e:cypress:run:chrome",
```

**Relevant CI test steps:**

1. ng build lib-demo --prod
2. npm run e2e:cypress:verify
3. npm run ci:e2e

I cannot provide a failing test or an example, where the issue is reproduced, since it occurs only in our CI pipeline.

### Versions

"cypress": "4.2.0"
**(Issue is reproduced on both electron and chrome headless in CI).**

**Comment by jennifer-shehane** [comment]
Are you able to review a video/screenshots of the run from CI? 

We have debugging tips for finding discrepancies between CI and local runs, which I'd advise walking through: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

Maybe there's some variability in the color animation/transitions for some reason, so it takes more time to reach the correct value in CI?

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Honestly it's impossible to say without a reproducible example. If you can provide an HTML/CSS/JS example we can run and reproduce, please comment in this issue and we will consider reopening the issue.
