### ISSUE TITLE
Unable to connect to server in different environment

### ISSUE THREAD

**Issue by AB1519** [cypress-io/cypress#6950]
I am trying to run a cypress test pointing to different environment.

1. When I run my local server and then run cypress, i.e cypress is now pointing `http://localhost:xxxx`.  It is working fine.

Problem:

I need to run the cypress command without running my local server. Since I have multiple application that needs to run these commands.

local url: `http://localhost:xxxx/app1/`  & `http://localhost:xxxx/app2/`

staging url: 
application 1: http://test.test.com/app1/
application 2: https://test.test.com/app2

both application 1 and application 2 are different but have the same domain and need to have cypress tests running.

I have tried switching the baseurl as shown in https://docs.cypress.io/api/plugins/configuration-api.html#Switch-between-multiple-configuration-files

It did not work. When I do cypress run --env configFile=staging, it shows me below error

<img width="512" alt="Screen Shot 2020-04-06 at 3 12 35 PM" src="https://user-images.githubusercontent.com/32438432/78596054-1fb9b080-7819-11ea-8ec5-32ffdcaa4981.png">

Please let me know what can be the potential issue.

I assume if i move BDD into CI job it will give me the same error. 

Thanks in Advance

**Comment by jennifer-shehane** [comment]
The server defined in your `baseUrl` is not running - so if you visit the `baseUrl` itself outside of Cypress - it will not open. You need to have your server defined as the `baseUrl` up and running before cypress runs. 

I can't be sure which server it's trying to run since it's not specified in the error message. And I can't be sure if you've defined the baseUrl switching correctly since you didn't include that code. 

Make sure your server is running - we recommend using these npm modules to help wait for the server.

- wait-on https://www.npmjs.com/package/wait-on
- start-server-and-test https://github.com/bahmutov/start-server-and-test

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
