### ISSUE TITLE
Is there any way to make a report when cypress opening the same as cypress running?

### ISSUE THREAD

**Issue by pmbaldha** [cypress-io/cypress#6956]
I would like to generate a report when running the command cypress open. I can generate report when running the command cypress run. I am generating the report by mochawesome when running cypress test.

Can you please tell me how can we generate a report if test specs ran from cypress opened panel?

**Comment by jennifer-shehane** [comment]
No, `cypress open` does not exit, so wouldn't have a point of report generation, it's meant to be used interactively by the developer, can rerun in real time, etc. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
