### ISSUE TITLE
Can't run cypress programmatically by Install cypress globally `npm install -g "cypress@4.3.0`

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress#6963]
### Current behavior:

case1: 

1. run command `npm install -g cypress@4.3.0`
2. check folder `/usr/local/lib/node_modules/cypress/node_modules`, in this folder, can't found folder `cypress`
3. run cypress programmatically `node ./ foo.js`

`foo.js`:

```js
const cypress = require('cypress')
// cypress.run() some code todo
```
Get error ```Error: Cannot find module 'cypress'```

case2: 

1. mkdir `tmp` on desktop, in this folder, run command `npm install cypress@4.3.0`
2. check folder `tmp/node_modules`,  folder `cypress` can be found
3. run cypress programmatically `node ./ foo.js`, no error happened

---

If install cypress globally, user can't run cypress programmatically
Such as [cypress-docker-images](https://github.com/cypress-io/cypress-docker-images/blob/master/included/4.3.0/Dockerfile)

### Versions
Cypress: 4.3.0
System: MacOS

**Comment by jennifer-shehane** [comment]
In Node.js, require doesn't look in the folder where global modules are installed. See this SO for workarounds: https://stackoverflow.com/questions/15636367/nodejs-require-a-global-module-package 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
