### ISSUE TITLE
Can I execute 'node abcd.js' inside cypress test

### ISSUE THREAD

**Issue by NilukaSripalim** [cypress-io/cypress#6980]
Can I execute 'node abcd.js' inside cypress test

**Comment by NilukaSripalim** [comment]
I tied with 
1. package json
"scripts": {
    "vumper": "node ./sample/user-portsl/gmail.js",
    
  },

but my test class is located in /cypress/integration/user-portal
in there when I execute 
cy.exec('  npm run vumper').then((obj) => {
    cy.log(obj)
    
  })
I didnt get output as I xpexted, but when try whre in package,json availabe and execute,
npm run vumper,
it will work, but within test I am unable,
Please help me

**Comment by jennifer-shehane** [comment]
https://on.cypress.io/using-cypress-faq#How-do-I-require-or-import-node-modules-in-Cypress

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
