### ISSUE TITLE
Finding the time taken to load a page

### ISSUE THREAD

**Issue by sumairaali** [cypress-io/cypress#6981]
Is there any functionality built into Cypress that will help find the  time taken to load a page ?

For example , Cypress documentation says that `cy.visit(...)` resolves once the page visited is loaded. Is there a way to find the time taken to resolve a cy.visit(..) command ? T

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
