### ISSUE TITLE
Unable to identify elements on Cesium 3D map in Cypress

### ISSUE THREAD

**Issue by chaitanyac-git** [cypress-io/cypress#6983]
Current Behavior :

I am new to Cypress and cesium . Our application has HTML elements and 3D maps shown using Cesium viewer. I am able to locate HTML elements using CSS selectors , but having issue with the 3D map shown in Cesium viewer .

It is identified as Canvas with no other identification .

Please help if any option to locate elements on Cesium 3D maps using cypress .

Desired behavior:
To show the CSS selector details for the elements on the 3D map ( currently treated as Canvas)
Please help if any option to locate elements on Cesium 3D maps using cypress .

 Versions
Cypress :4.3.0
Chrome : 80.0.3987.163
Cesium : Cesium ion 1.50

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example - some Cypress tests that visit a Cesium app, or a comparible 3D map within HTML/CSS and we will consider reopening the issue.
