### ISSUE TITLE
How can I connect to postgresql db  from cypress?

### ISSUE THREAD

**Issue by konicasarker** [cypress-io/cypress#6990]
Hello!,
I want to connect to postgresql db from Cypress. Can someone help me giving any example?
I use typescript and my webpack.config.js looks like following. Thanks in advance!

**webpack.config.js**
```js
const path = require('path')

module.exports = {
  entry: './src/index.ts',
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      }
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts', '.js']
  },
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  node: {
    fs: 'empty',
    dns: 'empty',
    net: 'empty',
    readline: 'empty',
    tls: 'empty'
  },
}
```
BR,

Konica

**Comment by Sumedh-k** [comment]
Please ask this question on Stack Overflow or in the Cypress chat room.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
