### ISSUE TITLE
Auto-waits not waiting for element to be visible on Firefox

### ISSUE THREAD

**Issue by saki2rules** [cypress-io/cypress#6992]
### Current behavior: 

The test on Firefox doesn't perform auto wait for a drop-down box to be clickable. The tests runs seamlessly on chrome, edge and electron browsers but when the test are executed on Firefox, it just perform click and goes for next step, although the click action was not in effect still. 

![console](https://user-images.githubusercontent.com/19150340/79056111-c500ca00-7c07-11ea-877a-93290f8713b1.png)

### Desired behavior:
The Firefox should also auto wait for the elements to be clickable like other browsers.

The page needs to wait for a drop-down box to complete loading but the test doesn't wait for the element in Firefox browser only. 
I have tried should('be.visible') also but it makes no difference. It works only hen i add cy.wait(), the test execute seamlessly on Firefox

The auto-wait feature on cypress should be working across all browsers equally.

### Versions - 4.3.0, MacOS 10.14.6, Firefox 74

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

We have lots of tests that run through both Chrome and Firefox, so likely this is an edge case we're unaware of.

Please comment in this issue with a complete reproducible example (including the HTML/CSS/JS for the dropbox that is being tested against with the Cypress test code) and we will consider reopening the issue.

**Comment by saki2rules** [comment]
![DOM](https://user-images.githubusercontent.com/19150340/79140173-699c1c80-7d6c-11ea-8739-53ae88febfca.png)

Attached the DOM which is relevant for the above issue.

**Comment by jennifer-shehane** [comment]
We will need the HTML / CSS / JS, as this is likely relevant to the issue. An HTML structure like this with visibility checks will not recreate the error. 

Please provide a fully reproducible example - the Cypress test code as well as the application to visit to reproduce.

**Comment by saki2rules** [comment]
I'm sorry, i can't share the application due to company policies.

In terms of code : cy.get(#id).click() which auto waits in all the other browsers to load and become visible, but in firefox directly goes on and clicks before being visibile
