### ISSUE TITLE
Simulate DOM input event on .type()

### ISSUE THREAD

**Issue by jennifer-mann** [cypress-io/cypress#7]
The DOM input event should be fired when the value of an `<input>` or `<textarea>` element is changed through `cy.type()`.

For IE9 < support, the `propertychange ` event should be fired when value of an `<input>` or `<textarea>` element is changed through `cy.type()`.

**Comment by brian-mann** [comment]
Typing implements the spec and behavior of `Chrome`. 

When cross browsers are used we don't simulate anything, real OS events are used so there is no need to add support for multiple browser.

Input event is now fired. Fixed in [`0.8.0`](https://github.com/cypress-io/cypress/wiki/Changelog#080-06262015)
