### ISSUE TITLE
Cypress stops/freezes, running a conditional .click() action

### ISSUE THREAD

**Issue by Strg-Alt-Anja** [cypress-io/cypress#7009]
### Current behavior:

Cypress stopst/freezes on Electorn and Chrome, but not on Firefox.
I am running the following code:

![2020-04-14 14_17_46-devicelist-web  C__Users_eichhorn_Desktop_Janitza_devicelist-web  -  _cypress_](https://user-images.githubusercontent.com/52451963/79225415-f1615400-7e5c-11ea-8dec-bd48cba3f65c.png)

and the `.click()` option seems to be the problem. Because if I remove this `.click()` then it works just fine. But with the `.click()`, the test sops and it looks like this:

![2020-04-14 14_18_30-devicelist-web](https://user-images.githubusercontent.com/52451963/79225518-1e156b80-7e5d-11ea-969b-7c058a7f60af.png)

But that only happens in Crome and Electron, not in Firefox! It runs perfect on Firefox Browser.

There is nothing interesting in the console. The test is only stoping without an error.

### Desired behavior:

Test should run the same way as it does on Firefox.

### Versions

Cypress Version 4.2.0 and also on v4.4.0 with Windows10

**Comment by jennifer-shehane** [comment]
You shouldn't need to chain `is.visible` check off of the get if you plan to click it, `.click()` does a default check for visibility. 

Aside from this, we'll need a reproducible example that we can run in order to investigate. We can't tell why the test would 'stop' without this. Which btw, what does 'stop' mean, does the timer at the top stop updating?

Please provide a full Cypress tests against an HTML/CSS/JS code that we can run and recreate the error - otherwise we will need to close this issue as there is no path forward for us to investigate.

**Comment by Strg-Alt-Anja** [comment]
@jennifer-shehane also if i dont chain the is.visible, the problem stays the same.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
