### ISSUE TITLE
npx cypress open installs cypress again ?

### ISSUE THREAD

**Issue by keerthifission** [cypress-io/cypress#7016]
### Current behavior:

So whenever I need to run my tests , I use `npx cypress open` which creates a new folder into my existing `cypress` floder

![image](https://user-images.githubusercontent.com/28805200/79339986-54c7b080-7f47-11ea-8eeb-40729298496c.png)
![image](https://user-images.githubusercontent.com/28805200/79340046-65782680-7f47-11ea-84b4-9560cd684db7.png)

### Desired behavior:

What command should I use to execute my tests in cypress??

**Comment by keerthifission** [comment]
@all ,please give your solution asap

**Comment by jennifer-shehane** [comment]
You'll need to run `npx cypress open` from the root of your project. Please check the [docs](https://on.cypress.io) on getting started. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
