### ISSUE TITLE
Flaky UI assertion that depends on a number of finished XHR responses

### ISSUE THREAD

**Issue by gkatsanos** [cypress-io/cypress#7018]
### Current behavior:
locally, this passes 100% of times

```js
beforeEach(() => {
    cy.login();
    cy.server();
    cy.route('**/real-estates/*').as('getRealEstateDetails');
    cy.route('**/estate-units**').as('getEstateUnits');
    cy.visit('/real-estates/1/estate-units-table?viewMode=installation-mode');
    cy.wait('@getRealEstateDetails');
    cy.wait('@getEstateUnits');
  });

  context('when they are sortable', () => {
    it('should properly sort elements by name', () => {
      cy.get('.table-filter__header.real-properties__name-header .v-btn').click();
      cy.wait('@getEstateUnits');
      cy.get('.v-data-table.sub-properties tbody').within(() => {
        cy.get('tr')
          .first()
          .contains('B Canonical Stairway 2');
      });
      cy.get('.table-filter__header.real-properties__name-header .v-btn').click();
      cy.wait('@getEstateUnits');
      cy.get('.v-data-table.sub-properties tbody').within(() => {
        cy.get('tr')
          .first()
          .contains('A Canonical Stairway 1');
      });
    });
```

![image](https://user-images.githubusercontent.com/1768834/79374085-66b14f80-7f57-11ea-8e13-de0ed7694bf2.png)

On our CI, it fails consistently.
```

1) Table column headers when they are sortable should properly sort elements by name:
--
287 | AssertionError: Timed out retrying: Expected to find content: 'B Canonical Stairway 2' within the element: <tr> but never did.
288 | AssertionError: Expected to find element: `:not(script,style):cy-contains('B Canonical Stairway 2'), [type='submit'][value~='B Canonical Stairway 2']`, but never found it.


```
### Desired behavior:
Test should pass consistently.

### Versions

Cypress : 4.4.0

Is there anything we're doing wrong in how we're asserting? would using the callback function be a more solid solution?

**Comment by jennifer-shehane** [comment]
Please run through our guide on debugging test failures in CI versus locally: https://docs.cypress.io/faq/questions/using-cypress-faq.html#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

Outside of this we will have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
