### ISSUE TITLE
cy.wait() for multiple XHR request can not work

### ISSUE THREAD

**Issue by biigpongsatorn** [cypress-io/cypress#7034]
### Current behavior:

I want to test XHR requests that run as parallel (4 requests) but cy.wait([]) can't work.

![Screen Shot 2563-04-16 at 20 38 01](https://user-images.githubusercontent.com/10693658/79463362-f3750f80-8022-11ea-9804-3f063d18042c.png)

I think the problem happens because has 2 requests called (line 1) before `cy.wait` work (line 2).

### Test code to reproduce
My XHR requests code:
```js
docs.forEach(value => {
  const task = new Promise(async (resolve) => {
    await this.service.postUploadKycDocs(value)
    resolve(true)
  })
  promiseTasks.push(task)
})
await Promise.all(promiseTasks)
```

Cypress test code:
```js
cy.get('[data-test="submit-btn"]').click()
cy.wait(['@uploadDocs', '@uploadDocs', '@uploadDocs', '@uploadDocs'])
cy.wait('@submit').its('status').should('eq', 200)
```

### Versions
Cypress version: 3.8.2

**Comment by jennifer-shehane** [comment]
The `cy.wait()` is timing out before the 3rd request is made though. You can see the wait timesout and then the 3rd response is listed in the commands. 

`wait` will match previously made commands, regardless of them being logged before. You may want to click the lefthand arrow on line 1 and 3 to have a clearer view of the matchers. 

Waiting for an array like this will wait for *all* items in the array to finish within the defined request and response timeouts. You may find more benefit with splitting them up so that they each get their own request/response timeout. 

```js
cy.wait('@uploadDocs')
cy.wait('@uploadDocs')
cy.wait('@uploadDocs')
cy.wait('@uploadDocs')
```

**Comment by biigpongsatorn** [comment]
@jennifer-shehane 
I just try 
```js
cy.wait('@uploadDocs')
cy.wait('@uploadDocs')
cy.wait('@uploadDocs')
cy.wait('@uploadDocs')
```
but it does still not work.
![image](https://user-images.githubusercontent.com/10693658/79571419-5d55ed80-80e5-11ea-98fa-f5aa6529b083.png)

**Comment by a-onkar** [comment]
@biigpongsatorn 
Add assertions to each step. Cypress commands are asynchronous.
I had the same problem, adding assertions helped me.
Assertions include waits by default in cypress.

**Comment by biigpongsatorn** [comment]
@a-onkar  Do you have an example?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.
