### ISSUE TITLE
Share tests beetwen projects

### ISSUE THREAD

**Issue by myskamil** [cypress-io/cypress#7049]
Hello :) I've got two projects in React. One of them is basic project with standard Cypress tests. Second project is more advanced and this project extends first, basic project. In second project I'd like to run standards cypress tests which are in basic project without copying them and add more advanced tests. Is that possible? If yes, how can I do it?

**Comment by Sumedh-k** [comment]
Can you ask this question on Stack Overflow or the Cypress Chat?

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
