### ISSUE TITLE
Firefox websecurity error (cross-origin object)

### ISSUE THREAD

**Issue by MihailPertsev** [cypress-io/cypress#7061]
### Current behavior:
When testing old web sites with firefox, this thing happens.

![изображение](https://user-images.githubusercontent.com/48799733/79636189-97270280-817e-11ea-8ec6-505f4bcaf608.png)

![error](https://user-images.githubusercontent.com/48799733/79636447-5cbe6500-8180-11ea-8861-c15754a295b6.png)

### Desired behavior:

To have the same config feature as chromeWebSecurity: false. For example,
fireFoxWebSecurity:false.

### Test code to reproduce

This happens RANDOMLY, I do not know how you can reproduce it. But if you try to test some old websites that were written for example in 2011 using Cypress + Firefox, you will probably have this error atleast once.

### Versions
cypress 4.3.0, windows 10, FireFox76

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide an example of an 'old website' we can test and we will consider reopening the issue.. This is not specific enough for us to move forward.
