### ISSUE TITLE
Upgrading Cypress from 4.0.1 to 4.3.0 results in conflicting jquery typedefs

### ISSUE THREAD

**Issue by dnaverdo** [cypress-io/cypress#7063]
### Current behavior:

Upgrading Cypress from 4.01 to 4.3.0 results in conflicting jquery typedefs since jquery puts a bunch of stuff on the global scope. 

### Desired behavior:

No conflicting typedefs

### Test code to reproduce

Have a product using jquery 2
Upgrade from cypress 4.0.1 to 4.3
Observe `yarn.lock`:

```
cypress@4.3.0:
  version "4.3.0"
  resolved "https://registry.yarnpkg.com/cypress/-/cypress-4.3.0.tgz#74694c2407846119368a6aecc456b3ee1a8ee32b"
  integrity sha512-xO1oef4ns4koDAkQROGJIhKKhGHDOKfOmlirwP1QAk9w/no+YJpN7HZ6IUPiXwWw3C7xVLjScoI8Dad0z5uTTg==
  dependencies:
    "@cypress/listr-verbose-renderer" "0.4.1"
    "@cypress/request" "2.88.5"
    "@cypress/xvfb" "1.2.4"
    "@types/blob-util" "1.3.3"
    "@types/bluebird" "3.5.29"
    "@types/chai" "4.2.7"
    "@types/chai-jquery" "1.1.40"
    "@types/jquery" "3.3.31"

"@types/jquery@*", "@types/jquery@2":
  version "2.0.49"
  resolved "https://registry.yarnpkg.com/@types/jquery/-/jquery-2.0.49.tgz#95bd7064caebf65bde10429dff491a1aea05b67d"

"@types/jquery@3.3.31":
  version "3.3.31"
  resolved "https://registry.yarnpkg.com/@types/jquery/-/jquery-3.3.31.tgz#27c706e4bf488474e1cb54a71d8303f37c93451b"
  integrity sha512-Lz4BAJihoFw5nRzKvg4nawXPzutkv7wmfQ5121avptaSIXlDNJCUuxZxX/G+9EVidZGuO0UBlk+YjKbwRKJigg==
  dependencies:
    "@types/sizzle" "*"
```

### Versions

4.0.1, 4.3.0

**Comment by jennifer-shehane** [comment]
Maybe related to https://github.com/cypress-io/cypress/pull/5780? cc @sainthkh

**Comment by sainthkh** [comment]
I'll also check this out.

**Comment by sainthkh** [comment]
I've investigated the problem and concluded that I need more information. With my current setting, the type clash happen even when Cypress is 1.2.0. 

Because from the beginning (#1044, #1048), `index.d.ts` started with jQuery 3.x types.  

[This repo](https://github.com/sainthkh/cypress-jquery) is the test repo I used. I tested types with `./node_modules/.bin/tsc --noEmit --esModuleInterop --lib dom,es5,es6  cypress/integration/examples/action.spec.ts`.


Can you provide me a repo with codes that works before 4.3.0 but fails after it and how to test it?

**Comment by sainthkh** [comment]
@dnaverdo In #7352, `@type`s are removed. I guess your project might work with 4.6.0 and above.

**Comment by dnaverdo** [comment]
it does work again... thanks for the note!
