### ISSUE TITLE
Cypress freezes when opening app

### ISSUE THREAD

**Issue by haoyangnz** [cypress-io/cypress#7064]
### Current behavior:

1. My app and tests work fine before.
2. I `yarn add react-sketch` and app and tests still work fine.
3. I add `import { SketchField } from "react-sketch"` to my code. App still works fine but the test `cy.visit("http://localhost:3000")` now freezes the browser, the timer stops ticking.

### Desired behavior:

It shouldn't freeze.

### Test code to reproduce

`cy.visit("http://localhost:3000")`
for a react app that has
`import { SketchField } from "react-sketch"`.

### Versions

Both cypress 4.0.1 and 4.4.0
MacOS Catalina 10.15.1
Chrome 80.0.3987.163

**Comment by jennifer-shehane** [comment]
Can you provide a repo with a reproducible example?

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
