### ISSUE TITLE
Cypress : Unable to see the dashboard even after cy.request command passes

### ISSUE THREAD

**Issue by shradha1101** [cypress-io/cypress#7067]
I am basically new to Cypress and wanted to implement the login page using `cy.request` command inorder to bypass the UI. My `cy.request()` passes with 200 response code. However i am not able to visit the dashboard page after successful login. Kindly guide me through this

Below is the code

```js
Cypress.Commands.add('loginByJSON', (username, password) => {
  return cy.request({
    method: 'POST',
    url: 'My website login url',
    body: {
      "username": username,
      "password": password,
    }
  }).then((resp) => {
    expect(resp.status).to.eq(200)
  })
})

describe('Sign In Page', function () {
  it('OnSuccessful Login', function () {
    cy.loginByJSON("test@gmail.com", "test@1234");
    cy.visit('http://test-apac.appspot.com/#/dashboard')
    cy.title().should("eq", "Dashboard")
  })
})
```

The Assert statement passes successfully.Further while visiting the dashboard page it again open the login page, even after successful login Any help would be appreciated

Thanks in Advance!

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
