### ISSUE TITLE
Cypress ca I   ignore new page load 

### ISSUE THREAD

**Issue by MehranShafqat** [cypress-io/cypress#7074]
Hi, Can i ignore the  the new page load in cypress ? 

Reason is why I need we have a api call around 5 second and cypress stuck on that and try to wait to load it again and again my tests completed and everything done but I just want to ignore this load.

![Screenshot_51](https://user-images.githubusercontent.com/50338287/79754312-c41b1700-8330-11ea-95ff-578f604a554f.png)

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
