### ISSUE TITLE
Step excuted  display in the browser  code

### ISSUE THREAD

**Issue by Wesly-Yu** [cypress-io/cypress#7086]
I want to know where is the code that shows the execution steps on the left side of the browse
I mean like this
![WeChat Screenshot_20200421150509](https://user-images.githubusercontent.com/43123294/79836275-870f5d00-83e2-11ea-9809-bd7c425161ec.png)

**Comment by jennifer-shehane** [comment]
It depends on if you're talking about the generation of the messages or the front-end view - also likely depends on what you're trying to do. I would suggest familiarizing yourself with our [contributing doc](https://github.com/cypress-io/cypress/blob/develop/CONTRIBUTING.md) if you want to dive into the code that creates Cypress. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
