### ISSUE TITLE
How to change the contents of the element

### ISSUE THREAD

**Issue by xiaoxinhis** [cypress-io/cypress#7093]
### Current behavior:
![image](https://user-images.githubusercontent.com/64055065/79858991-dfeeed80-8402-11ea-8bcb-e5e19819b40e.png)
this is Emailinput，but the code：

```js
.get('.input-wrapper',{timeout:30000}).first().type('123456@qq.com',{force:true})
```
dose not work,

### Desired behavior:
i want change the contents of the element directly. Is there any other API works？

### Versions
chrome 81.0.4044.113，cypress 4.4.0

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with the HTML/CSS/JS required to reproducible the example with the Cypress tests you've already provided and we will consider reopening the issue. We need to be able to run the test ourselves to help you.
