### ISSUE TITLE
Check all emails accosted with a Github account when attempting to login.

### ISSUE THREAD

**Issue by scottdavis** [cypress-io/cypress#71]
If you have multiple emails associated with a Github login cypress will just test against the first one even if it is not marked as your primary and deny you access.

**Comment by brian-mann** [comment]
This is a temporary problem due to being in private beta. Once Cypress is publicly available these restrictions will be lifted. 

Right now Github only sends back one email address (which should be the primary one) in their `oAuth` API, but I can probably request all of them and validate against any of them. This is a good suggestion.

**Comment by brian-mann** [comment]
This is finally in :P
