### ISSUE TITLE
Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by sidcyrus** [cypress-io/cypress#7107]
Hello, 

I get this error while npm install.

URL: https://download.cypress.io/desktop/4.4.1?platform=win32&arch=x64
Error: `unable to get local issuer certificate`

There were suggestions on this page,

https://github.com/cypress-io/cypress/issues/1401

        1. Download the binary manually here: https://download.cypress.io/desktop
        2. npm isntall: CYPRESS_INSTALL_BINARY=/path/to/zipfile/cypress.zip npm install cypress --save-dev

    For windows:
    SET CYPRESS_INSTALL_BINARY=/path/to/zipfile/cypress.zip npm install cypress

	
can someone please give more details on how to set this ? Is it env variable ? full detailed step by step guide please. I am new to this. thank you

**Comment by sidcyrus** [comment]
Hello,

Please can someone help me to install cypress urgently.

I use the info given on the site,
https://docs.cypress.io/guides/getting-started/installing-cypress.html#Environment-variables


*** 1) When i run**
npm install cypress --save-dev

I get,
Error: unable to get local issuer certificate

*** 2) When I try** 
CYPRESS_INSTALL_BINARY=C:\Temp\cypress.zip npm install cypress

I get below error,

PS C:\Users\ONE\CypressAutomation> CYPRESS_INSTALL_BINARY=C:\Temp\cypress.zip npm install cypress
CYPRESS_INSTALL_BINARY=C:\Temp\cypress.zip : The term 'CYPRESS_INSTALL_BINARY=C:\Temp\cypress.zip' is not 
recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, 
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ CYPRESS_INSTALL_BINARY=C:\Temp\cypress.zip npm install cypress
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CYPRESS_INSTALL...emp\cypress.zip:String) [], CommandNotFoundExce 
   ption
    + FullyQualifiedErrorId : CommandNotFoundException
 
***3) When I try** 
SET CYPRESS_INSTALL_BINARY=C:\Temp\cypress.zip npm install cypress

I get below error,

Set-Variable : A positional parameter cannot be found that accepts argument 'install'.
At line:1 char:2
+  SET CYPRESS_INSTALL_BINARY=C:\Temp\cypress.zip npm install cypress
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Variable], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetVariableCommand

**Comment by jennifer-shehane** [comment]
Setting environment variables in Windows is different See this for full instructions: https://on.cypress.io/proxy-configuration#Windows (replace the env vars with your `CYPRESS_INSTALL_BINARY` environment variable.)

Likely you are behind a corporate proxy and need to follow the full instructions to configure the proxy to work with Cypress: https://on.cypress.io/proxy-configuration

**Comment by angmas** [comment]
I'm behind a corporate proxy. What's interesting is that when I install version 4.3.0 I don't run into this error. I've been running into it when trying to install 4.8.0.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue due to inactivity. Please comment if there is new information to provide concerning the original issue and we can reopen.

**Comment by kadamagithub** [comment]
hi , i am getting same error while installing 4.11

**Comment by jennifer-shehane** [comment]
@kadamagithub If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.

**Comment by adjenks** [comment]
Okay, so I think I figured it out. I too am behind a corporate firewall and need to set custom ca certificates.

Based on [this function](https://github.com/cypress-io/cypress/blob/7489561fbfb676a8948eff89730b99bf4d4fc63e/cli/lib/tasks/download.js#L41) when cypress downloads itself it attempts to use the npm ca or cafile settings from `process.env`, however, on my system and apparently other people's `process.env` is not populated by the `.npmrc` that is configured with `npm config set`. `process.env` is only the result of the environment variables, which npm also uses but doesn't use alone.

To address the issue I had to run these two lines:

```bash
export npm_config_cafile=/etc/pki/tls/certs/ca-bundle.crt
export CYPRESS_DOWNLOAD_USE_CA=1
```
This sets the bash environment variables which will be read correctly by cypress' postInstall. So even if you run `npm config get cafile` and it returns an answer, if you do not set these environment variables as well, cypress will fail. You can check this before setting the variables by running. `node -e "console.log(process.env)"` and looking for settings prefixed with `npm_config_`. When I tried this, I could not find the relevant variables until setting them using `export`.

node doesn't provide a builtin package to get the settings inside of itself by default, but a user named [kevva](https://github.com/kevva) seems to have created a package to get settings the [same way npm does](https://docs.npmjs.com/cli/v8/using-npm/config). It was forked and is now more recently maintained by the pnpm project [here ](https://www.npmjs.com/package/@pnpm/npm-conf)though. As a side note, they seem to have [removed](https://github.com/pnpm/npm-conf/commit/ed7b6390c3bc1e4f841e066712b4a3da57226597#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15R47) Kevin's copyright notice though and MIT requires "preservation of copyright and license notices", so I think that was a bit rude.

If cypress would like to use it, it works like this after you install it:
`node -e "require('@pnpm/npm-conf')().config.get('cafile')"`



It seems like this problem comes up a lot:
https://github.com/cypress-io/cypress/issues/17238
https://github.com/cypress-io/cypress/issues/1401

Good luck everyone.
