### ISSUE TITLE
Cypress 4.4.1: Variables created with `this` is not working, its working in Cypress 4.4.0

### ISSUE THREAD

**Issue by rohitshrivastva** [cypress-io/cypress#7108]
I have a fixture file in JSON format. Previously, when i was using Cypress@4.4.0, it was working fine. I have updated the Cypress to version 4.4.1 and it stops working

Data in fixture file:

account.json:
```json
{
	"accountId":123412341234
}
```

Code that gives error:

```js
cy.fixture('account')
  .then((account) => {
    this.accountId = account.accountId;
    console.log(this.accountId)
  })
```

Current behavior:

```
TypeError
Cannot set property 'accountId' of undefined

Because this error occurred during a before all hook we are skipping the remaining tests in the current suite: s3 configuration
View stack trace
```

![Screenshot from 2020-04-22 20-36-02](https://user-images.githubusercontent.com/9219248/79998950-f6677880-84d8-11ea-8391-4a73830253b7.png)

Cypress: 4.4.1
OS: Ubuntu 18.04
Browser: Chrome 81

**Comment by jennifer-shehane** [comment]
Hey @rohitshrivastva, I'm not able to recreate this issue as described. Likely there is some other configuration involved that is causing the error. Can you provide any information regarding your setup? Where is the `before` hook defined? Are you using typscript? Preprocessors? Do you have anything in your plugins or support files? Are you using any cypress plugins?

Ideally providing a complete repo we can run and see the failure would be ideal. Thanks!

My `spec.js` file:

```js

describe('describe', () => {
  before(() => {
    cy.fixture('account')
      .then((account) => {
        this.accountId = account.accountId;
        console.log(this.accountId)
      })
  })

  it('test', () => {
    expect(true).to.be.true
  })
})
```

<img width="333" alt="Screen Shot 2020-04-28 at 2 02 40 PM" src="https://user-images.githubusercontent.com/1271364/80459808-f217e100-8958-11ea-8402-e4c26b7252c6.png">

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
