### ISSUE TITLE
Regression about displaying device resolution

### ISSUE THREAD

**Issue by Tay08** [cypress-io/cypress#7114]
### Current behavior:

Implement responsible visual regression testing with device supported into cypress viewport parameters. 

When I run the test, the website doesn't responsive in `iphone-x`, `ipad-2` ...etc

### Desired behavior:

Have the same behaviour with toogle device toolbar into Chrome developer tools. Website is really responsive about the device associated.

### Test code to reproduce

```js
const pages = ['https://www.amazon.fr/']
const sizes = ['iphone-x', 'ipad-2', [1200, 800]]

//** Responsive visual regression test **/
describe('Integration test with visual testing : case n°2 ', function () {
	sizes.forEach((size) => {
		pages.forEach((page) => {
			it('Should match ${page} in resolution ${size}', () => {
				// Display datetime
				let currentTime = new Date(Date.UTC(2020, 1, 1)).getDate()
				cy.clock(currentTime)
				// Set size resolution
				cy.setResolution(size)
			// Load the page or perform any other interactions with the app.
				cy.visit(page)
				// Take a snapshot for visual testing diff
				cy.matchImageSnapshot()
			})
		})
	})
})
```

### Versions

MacOSX Catalina 10.15.2
Cypress 4.4.0

**Comment by jennifer-shehane** [comment]
Hey @Tay08 could you include the code for your `setResolution` custom command? This test code is not runnable without that definition. 

Cypress solely changes the viewport size of the browser window. We do not simulate other things like [`devicePixelRatio`](https://on.cypress.io/viewport#Notes) or the [`User-Agent`](https://on.cypress.io/configuration#Browser) as part of `cy.viewport()`. 

You would need to emulate what your application is looking for to decide how the site is laid out, which will require knowledge on how the site makes decisions on how to render its layout.

We strongly discourage testing sites that are not under your control for reasons you can read here: https://on.cypress.io/best-practices#Visiting-external-sites

If you track down what is required to emulate the iphone/ipad layout that Cypress is not able to do, please comment in this issue so that we can address specifically what Cypress is not emulating and we will reopen the issue.
