### ISSUE TITLE
Cypress initially very slow / failing tests and timeouts when running via cypress open locally

### ISSUE THREAD

**Issue by Nasicus** [cypress-io/cypress#7116]
First of all:
I ❤️  cypress. On our CI we run currently 2200 tests (around 1000 of them are UI tests, the others purely test API routes) within a docker-compose and it works very good. So thanks for this great product! 👍 👍 👍 

-----------------

But now to the problem which we've basically always had. However it's not that bad since it's only happening **locally**, but it's still very annoying and frustrating.

Cypress version: `4.4.1` => but this happened always (we're using cypress since over 2.5 years)

We have the following setup:
- Frontend (Web App) created & served (locally) with create-react-app
- Backend (C#, Web API, REST)
- Database (Mongo, run in docker)

When we run tests locally via the cypress UI (`cypress open`) we almost always have a very "rusty start" if we run any tests which includes the UI / WebApp. This basically means we need to rerun the tests multiple times until they stop failing due to timeouts. However usually once you've hit that "rerun" button multiple times (but mind you, this sometimes need a lot of retries and multiple minutes of trying), it looks like everything has been "warmed up" and is suddenly good to go and then the tests work "forever" (until you close them and maybe switch over to the normal webapp development and come back later for writing new tests). I hope you get what I'm describing here.

Anyway, here's a screenshot of when it's slow, you can see that loading some chunks takes 8 seconds, sometimes even longer - no wonder you get those timeouts:
![image](https://user-images.githubusercontent.com/1086065/80063365-111c0a80-8536-11ea-90dc-f9ebe7f9650a.png)

Once it's running "smooth" the same link looks like this => 20ms loading times etc.:
![image](https://user-images.githubusercontent.com/1086065/80063417-2d1fac00-8536-11ea-87fb-d09efb998b41.png)

What we also noticed is that this mainly happens to the devs which are using windows, for mac users this doesn't appear to be a big problem.

I'm not even sure if it's cypress related, maybe it's also related to create-react-app. However we do not have these problems if we access the web app locally in the normal browser.

Does anyone else also have that problem? Is there a solution for it?

Any help is greatly appreciated.

**Comment by jennifer-shehane** [comment]
We'll really need a reproducible example in order to investigate where this is stemming from. There could be a lot of things involved around your setup, plugins, support files, configuration or the tests themselves. 

You may want to run Cypress with [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) locally and share those here, this may show what processes are running and taking up resources.

**Comment by ericvera** [comment]
I don't have a repro for this issue or understand the internal of Cypress enough, but just spend about 6 hours troubleshooting and trying things.

Removing the following directory did not work...
/Users/<username>/Library/Application Support/Google/Chrome

...but right **after removing this directory everything started to work.**
`/Users/<username>/Library/Application Support/Cypress`

Hope it helps someone else.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
