### ISSUE TITLE
chaining cy.request().then()

### ISSUE THREAD

**Issue by VajraFate** [cypress-io/cypress#7121]
### Description
I cannot find a way to resolve data in `cy.request().then()`, using a `Cypress.Promise`:

### Code
```javascript
 it('get inst state', () => {
    getInstState().then(res => {
      console.log('res: ', res);
    });

function getInstState() {
  return cy.request({
    url: 'instances/state',
    headers,
  }).then(res => {
    expect(res.status).equal(200);
   // do something
    return new Cypress.Promise(resolve => {
      resolve(res);
    });
  });
}
```

### result

I return a `Cypress.Promise` instance in `.then() `, but  this code always logs `res:  null`

I want to chaining `cy.request()` like this: 

```javascript
 it('get inst state', () => {
    getInstState().then(res => {
      console.log('res: ', res);
      instAction(res).then(actionResult => {
         console.log(actionResult)
        // next request;
      })
    });

function getInstState() {
  return cy.request({
    url: 'instances/batch/state',
    headers,
  }).then(res => {
    expect(res.status).equal(200);
   // do something
    return new Cypress.Promise(resolve => {
      resolve(res);
    });
  });
}

function instAction(res) {
  expect(res.status).equal(200);
  const items = res.body.items;
  return cy.request({
    url: '/instances/action',
    method: 'POST',
    body: {
      instances: items.map(item => item.inst_id),
      action: 'server_off',
    },
  }).then(res => {
    cy.log('server_off inst', res);
    expect(res.status).equal(200);
    return res;
  });
}
```
how to make `cy.request().then()` can chaining the next `.then()`?

### Versions
Cypress@4.4.0

**Comment by jennifer-shehane** [comment]
I don't understand why the Cypress.Promise is necessary in this instance. The code within the `.then()` will only run once the request has resolved. Please read about how commands are async: https://on.cypress.io/introduction-to-cypress#Commands-Are-Asynchronous You can't queue cy commands and yet return a synchronous value.

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
