### ISSUE TITLE
Getting an Error: Cannot find module '../PageObjects/LoginPage'.

### ISSUE THREAD

**Issue by PavanBisaralli** [cypress-io/cypress#7135]
### Current behavior: 

Getting an Error: `Cannot find module '../PageObjects/LoginPage'`.

![image](https://user-images.githubusercontent.com/26905121/80231374-eb475080-8670-11ea-8882-6d45cf51b0e3.png)

### Desired behavior: 
![image](https://user-images.githubusercontent.com/26905121/80231069-7c69f780-8670-11ea-92ca-779edecbc8ca.png)

### Test code to reproduce
```js
import { LoginPage } from '../PageObjects/LoginPage';

describe('test suite', function() {

    it('valid login test', function() {

        const lp = new LoginPage()
        lp.visit()
        lp.fillEmail('admin@yourstore.com')
        lp.fillPassword('admin')
        lp.submit()
        cy.title.should('be.equal', 'Dashboard / nopCommerce administration')

    })

})
```

**Comment by zac11** [comment]
The error says Cannot find the module. Are you sure you have imported the module correctly?

**Comment by jennifer-shehane** [comment]
@PavanBisaralli What version of Cypress are you using? This information is critical to debugging and why we ask this in the template. 

Ensure the module you are importing is at the correct path and it being exported as expected. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example we can run (including the LoginPage export) and the version of Cypress you are using and we will consider reopening the issue.
