### ISSUE TITLE
The JS file that cypress got is little different with JS file gotten in chrome

### ISSUE THREAD

**Issue by Rey-Wang** [cypress-io/cypress#7138]
### Current behavior:
visit the same page, In cypress will get an error caused by one parameter not defined
![image](https://user-images.githubusercontent.com/45580554/80302521-1babfd80-87dd-11ea-8c98-2c6dd354455d.png)

### Desired behavior:
Expect the cypress can visit normally

### Test code to reproduce

I can not reproduce because I'm not sure this is caused by cypress or webpack or my project

### Versions

OS: Windows 10 1909 18363.778
Cypress: 4.3.0
Chrome: Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
This is a bug in Cypress. We replace instances of `top.location` within code to `self.location` in order to prevent the application under test from not working within Cypress (which we run in an iframe). 

You should be able to fix this by passing `modifyObstructiveCode: false`, which will turn off our code modification. 

Full explanation here: https://on.cypress.io/configuration#modifyObstructiveCode
