### ISSUE TITLE
Change default icon

### ISSUE THREAD

**Issue by nachocab** [cypress-io/cypress#714]
Would it be possible to change the icon of the Chrome Browser? Right now I always get confused as to which of the two Chromes Cypress is in:

![image](https://user-images.githubusercontent.com/27538/31316512-0965dbc8-abfd-11e7-833c-7029313d5517.png)

**Comment by brian-mann** [comment]
You could launch Canary or Chromium or Electron instead so you'll see a different icon.

I remember looking at this over a year ago, but to date we have not found a way to change the icon.

The reason is that Cypress is launching your system Chrome, but only in a separate profile. The icon itself is tied to the app not the profile. Changing it in one place would change it in the other.

**Comment by nachocab** [comment]
Got it. Thanks!
