### ISSUE TITLE
Not loading stuff in the test, but it does in another tab

### ISSUE THREAD

**Issue by julianmendonca** [cypress-io/cypress#7141]
### Current behavior:

Loads a carousel in one computer but dont load it in another one

### Desired behavior:

Load the carousel in all computers

### Test code to reproduce

i already set it to save localStorage and Cokkies just in case... this is saving the data correctly.
But if i open https://www.sodimac.com.ar/sodimac-ar/ in another tab it load a carousel of products with title 'Los más vendidos' but when i open it with cypress test it doesent appear... why is that?

THIS IS THE CAROUSEL

![image](https://user-images.githubusercontent.com/31936866/80325589-292cac00-880c-11ea-8052-26af726daf14.png)

```js
cy.visit(https://www.sodimac.com.ar/sodimac-ar/)
```

### Versions

last one

**Comment by jennifer-shehane** [comment]
This is due to the screen size that Cypress is running your tests by default (1000pixel width). You likely have your website open in a bigger screen size outside of Cypress. Since your website is dynamic based on viewport width, the carousel displays different number of items based on width.

You can change the size of the viewport by default by setting `viewportHeight` and `viewportWidth` in your configuration: https://on.cypress.io/configuration#Viewport or within each test by using [`cy.viewport()`](https://on.cypress.io/viewport)

**Comment by julianmendonca** [comment]
> This is due to the screen size that Cypress is running your tests by default (1000pixel width). You likely have your website open in a bigger screen size outside of Cypress. Since your website is dynamic based on viewport width, the carousel displays different number of items based on width.
> 
> You can change the size of the viewport by default by setting `viewportHeight` and `viewportWidth` in your configuration: https://on.cypress.io/configuration#Viewport or within each test by using [`cy.viewport()`](https://on.cypress.io/viewport)

Thank you for your reply, but this is not the problem, i run this script in one pc with the same viewport set and it loads, but in another pc it doesent load... That caroussel load from a third party script and i cant find why it loads on another tab but no on cypress test tab.

**Comment by jennifer-shehane** [comment]
Please detail the exact situation that is unexpected within Cypress. I'm not familiar with the application, so can not notice subtle differences. 

- Share screenshots of inside / outside and what it unexpected. 
- Please provide a failing tests of the situation exactly. If cookies should be present, write a failing test showing cookies are not present, etc.

**Comment by jennifer-shehane** [comment]
Details from duplicate issue https://github.com/cypress-io/cypress/issues/7155



### Current behavior:

Test browser tab not behaving the same way as a normal tab.

My company inject stuff to already developed sites and i use cypress to check if the content loaded.

The problem is when i do `cy.visit("https://www.sodimac.com.ar/sodimac-ar/")` the carousel that we inject doesent appear, but when i open another tab in the same browser the carousel appear...

I used the same exact code in 4 computers with windows, it worked in my desktop one and the one we use from aws, but didnt work in the other 2 windows notebooks we used

I dont know why it appear in others tab but no in the running test tab.

This is the carousel that should appear

![image](https://user-images.githubusercontent.com/31936866/80404890-3db68600-8898-11ea-90be-658b567b6cae.png)

There should be cookies from `s.braindw.com` that dont appear, maybe that is a hint?


### Desired behavior:

Apper the same carousel in test tab

### Test code to reproduce

Cypress.json

```json
{
    "chromeWebSecurity": false,
    "viewportWidth": 1300,
    "viewportHeight": 660
}
```

index.js

```js
Cypress.Cookies.defaults({
    whitelist: ['cd_user_id',
        '__utmb',
        '__cfduid',
        'keepalive',
        '_fbp',
        '_sdsat_login_clienteID',
        '__utmt',
        'guid',
        '_hjIncludedInSample',
        'DYNAMIC_DATA_COOKIE',
        'kampyleUserPercentile',
        'kampyleUserSessionsCount',
        'kampyleUserSession',
        'kampyle_userid',
        'TS016f6d42',
        'JSESSIONID',
        'kampyleSessionPageCounter',
        '_pk_ses.655.44e8',
        'TS01660a12',
        'ADRUM',
        '_sdsat_hash-id',
        '_pk_id.655.44e8',
        '_pk_ref.655.44e8',
        'AWSALB',
        'BVBRANDSID',
        'TS01c00e35',
        '__utmz',
        'BVBRANDID',
        'AWSALBCORS',
        '__utmc',
        '__utma',
        '_hjid',
        'mbox',
        'guid',
        'DYNAMIC_DATA_COOKIE',
        '_hjIncludedInSample',
        'keepalive',
        '_fbp',
        '__cfduid',
        '_sdsat_login_clienteID',
        '__utmt',
        '__utmb',
        'cd_user_id'
    ]
})

beforeEach(() => {
    Cypress.on('uncaught:exception', (err, runnable) => {
        return false
    })
})
```

commands.js

```js
Cypress.Commands.add('getIframeDocument', (id) => {
    return cy
        .get('#' + id)
        .its('0.contentDocument').should('exist')
})
Cypress.Commands.add('getIframeBody', (id) => {
    return cy.getIframeDocument(id)
        .its('body').should('not.be.undefined')
        .then(cy.wrap)
})

let LOCAL_STORAGE_MEMORY = {};

Cypress.Commands.add("saveLocalStorageCache", () => {
    if (Object.keys(localStorage)) {
        Object.keys(localStorage).forEach(key => {
            LOCAL_STORAGE_MEMORY[key] = localStorage[key];
        });
    }

});

Cypress.Commands.add("restoreLocalStorageCache", () => {
    if (Object.keys(LOCAL_STORAGE_MEMORY)) {
        Object.keys(LOCAL_STORAGE_MEMORY).forEach(key => {
            localStorage.setItem(key, LOCAL_STORAGE_MEMORY[key]);
        });
    }

});

Cypress.Commands.add('clearLocalAndCookies', () => {
    Cypress.Cookies.defaults({
        whitelist: []
    });

    //Clear localStrage
    cy.clearLocalStorage()

    //Clear Cookies
    cy.clearCookies()

    // Set defaults
    Cypress.Cookies.defaults({
        whitelist: /cd_user_id.*|kampyleSessionPageCounter.*|guid.*/
    })
})
```


theTest.js

```js
beforeEach(() => {
    cy.restoreLocalStorageCache();
});

afterEach(() => {
    cy.saveLocalStorageCache();
});
describe("Sodimac Gondola Los Mas Vendidos", () => {


    it('Cargo la gondola "Los Mas Vendidos"', function () {
        cy.visit("https://www.sodimac.com.ar/sodimac-ar/");
        cy.wait(10000);
        cy.getIframeBody('Braindw6').find('.owl-item:not(.cloned)').should('exist')
    })
})
```

### Versions

There actualy is more code, but since the carousel doesent appear in any part of the site i only put the home page only.

Thank you in advance :)



Latest Chrome

**Comment by jennifer-shehane** [comment]
@julianmendonca The tests provided are passing. Can you provide a failing test case of the exact issue? If there should be content in the carousel - write a failing test for the missing content. Thanks. 

<img width="560" alt="Screen Shot 2020-04-29 at 12 50 41 PM" src="https://user-images.githubusercontent.com/1271364/80566098-2a322900-8a18-11ea-8d18-569e925e8e07.png">

**Comment by julianmendonca** [comment]
@jennifer-shehane The problem is that this exact code that worked, in some computers dont work.
The reason for that is that there should be an initial request to https://www.s.braindw.com/ that is not happening... and therefore there is no cookies with the domain s.braindw.com.
That request is from a third party script, but i don´t understand the reason the request is made in some computers and in others isn´t.
