### ISSUE TITLE
not record videos when visit a new url

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#7143]
### Current behavior:

when visit text2, record video failure, only part of visiting text1.

```js
cy.visit('text1')

cy.wait(1000)
cy.get('li:nth-child(3) > span.t').trigger('mouseenter', {force: true})

cy.wait(1000)
cy.xpath('//a[text()="aaa"]').click()

cy.visit('text2')
```
### Versions

cypress : 3.6.1
system: ubutun
browser: chrome 80

**Comment by jennifer-shehane** [comment]
I see that you are using a very old version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog). Your issue may have already been fixed.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example that we can run on our machine - screenshots would also be helpful and we will consider reopening the issue. Thanks!

**Comment by mingyixu** [comment]
@jennifer-shehane : The same question on 4.0.1 .

**Comment by jennifer-shehane** [comment]
@mingyixu See this section in our docs: https://on.cypress.io/trade-offs#Multiple-tabs
