### ISSUE TITLE
How to click on the mouseover an element and click on the child element from the TopMenu?

### ISSUE THREAD

**Issue by senthkum** [cypress-io/cypress#7163]
Hi Team,

I want to select the product from the menu and click on the child product, Could you please help me here. I am not able to achieve this. I am trying my best. But if we get multiple elements, we need to pass the values and click on it. I am able to get the count as 7 correctly, but not able to print the values of it.

```
BOOKS, COMPUTERS, ELECTRONICS, APPAREL & SHOES, DIGITAL DOWNLOADS, JEWELRY, GIFTCARDS
```

Code:
```js
cy.get('.top-menu').find('.top-menu-triangle').each((menuItem, index, $list) => {
  const menuName = menuItem.eq(index).text()
  cy.log(menuName)
})
```

![mousecount](https://user-images.githubusercontent.com/46837197/80484061-73439800-899a-11ea-94ba-0e0a9f92748e.jpg)

![Mouseover](https://user-images.githubusercontent.com/46837197/80484110-85bdd180-899a-11ea-943d-9800de579b97.jpg)

Thanks
Senthil.M

**Comment by njevdjo** [comment]
Try with this code
```javascript
cy.get(".top-menu").find("li").eq(1).then((ele) => {
    ele.trigger('mouseenter')
    cy.wrap(ele).contains("Desktops")
})
```

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
