### ISSUE TITLE
Feature: make it easier to override core config variables

### ISSUE THREAD

**Issue by csvan** [cypress-io/cypress#7164]
### Current behavior:

Currently, overriding core Cypress config variables, such as the ones found in [`app/packages/server/config/app.yml`](https://github.com/cypress-io/cypress/blob/develop/packages/server/config/app.yml) is usually not possible without tampering directly with the config files themselves. Apart from being overwritten on updates and new installs, this is difficult to do in a consistent, cross-platform manner since the location where the files are installed vary between operating systems, etc.

### Desired behavior:

It should be simple to override core config via, for example, environment variables:

`CYPRESS_SERVER_API_URL=myurl.com cypress run`

The core config could ideally also be overridden via the standard config files (`cypress.json` etc), for example:

https://github.com/cypress-io/cypress/blob/develop/packages/server/config/app.yml#L9

```
{
    "server": {
        "api_url": "myurl.com"
    }
}
```
### Versions
Any

**Comment by mirobo** [comment]
@lmiller1990 Sorry, to bother you.. don't know how to address like a "cypress team" account or some kind of "cypress dispatcher" :-D

This ticket is quite old but it came up once again. I am blocked with upgrading to Cypress 12.0.2+ and so are all other users of sorry-cypress because of this issue from your "partial competitor" sorry-cypress: https://github.com/sorry-cypress/cy2/issues/38

As you might know there are a couple of companies which just cannot legally use a remotely hosted dashboard. So sorry-cypress is our only alternative. I'd happily pay something for an on-premise solution, but Cypress doesn't offer it (at least publicly).. so there's is just no alternative. Or I could pay a monthly fee for the parameter to be exposed via opencollective.. deal? :D

**Comment by lmiller1990** [comment]
Hello, I hadn't seen this issue. I see three issues here:

1. What are my options for an on-prem Cypress?
2. What about currents.dev?
3. What is the status of the feature request?

For 1) If you need on-prem, you can reach out at support@cypress.io. @mirobo (or anyone else) if you can share your email, we will reach out to you. Every use case for on-prem is different, let's find out what the gap is and see if we can bridge it. In the email, you could link to this GH issue for context in the email. In general, that's probably the best way to reach the team. 

For 2) You will need to post in their issue in the repo to find out what their recommendation is.

For 3) As for this feature request, it's not something I can speak to - my main focus is only triaging and bug fixes on the OSS offering, not high level decisions about the product and integrations. Right now this looks like it's tagged with `"stage: proposal". I'll try to find out more information. Right now, my understanding is no work is been done on this particular feature at this point in time.

**Comment by jennifer-shehane** [comment]
Closing as we will not be providing this as a feature.
