### ISSUE TITLE
Checking for existence of attribute without giving an error

### ISSUE THREAD

**Issue by nagamalleshavenkategowda** [cypress-io/cypress#7169]
### Current behavior:

We can use `should('have.attr', 'spaced')`  to check for existence and value of `attribute`. But if the attribute is not exists then it gives error 

### Desired behavior:

Is there any way to check that with out getting an error, that returns `true` or `false` based on existence of attribute.

Something `hasClass` function. 

![image](https://user-images.githubusercontent.com/49677363/80582732-d716a100-8a2c-11ea-9354-c2fe18915a02.png)

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
