### ISSUE TITLE
Unable to get element count using Cypress.$ 

### ISSUE THREAD

**Issue by spsingham1902** [cypress-io/cypress#7172]
I am trying to get the element count using below method :

```js
cy.log(Cypress.$('tr.dx-row-lines').length)
```

but it always print 0

```js
while If I use code like below :
 cy.get("body").then(($el) =>{
    cy.log ($el.find("tr.dx-row-lines").length) 
}
```

it print 4

Because I need to break a for loop if rows found so I can not use 2nd way,

Please guide me

**Comment by jennifer-shehane** [comment]
`Cypress.$('tr.dx-row-lines').length` is evaluated immediately because it is a sync method. so it's evaluating before other Cypress code is ran. 

I suggest reading the entirety of our [Introduction to Cypress](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code).
