### ISSUE TITLE
Global variable seems broken in Cypress

### ISSUE THREAD

**Issue by rajivbhati12** [cypress-io/cypress#7173]
### Current behavior: 
- JavaScript Global variable seems broken in Cypress.
- `cy.log` inside `beforeEach` block print nothing
- tried `this.fName` and at global level `let fName`, `var fName` nothing worked

### Desired behavior: 
- A variable declared outside a function, becomes GLOBAL.
- A global variable has global scope: All scripts and functions on a web page can access it. 
- `cy.log` inside `beforeEach` block should print `apple`

### Test code to reproduce

Please checkout: https://github.com/rajivbhati12/cypress-test-tiny and run cypress_*.js from integration

I have also attached video recording: https://github.com/rajivbhati12/cypress-test-tiny/blob/master/Cypress_global_variable_issue.mov

### Versions
Cypress package version: 4.4.0
Cypress binary version: 4.4.0
OS: macMojave 10.14.6 (18G4032)
browser: n/a

**Comment by jennifer-shehane** [comment]
This is due to `this.fName` and `fName` being evaluated immediately - before the async Cypress commands have run.

I suggest reading the entirety of our [Introduction to Cypress](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code).
