### ISSUE TITLE
I am unable to send GET api call with authorization bearer accessToken is added in it. 

### ISSUE THREAD

**Issue by shahmed-nisum-com** [cypress-io/cypress#7195]
Hi All,

Currently i have two request one is POST request and other is get, in first i get user access token by post and in other i used this `accessToken` to get login. Every my code does not work. Kindly help me out in this regards;

I am using window 7
cypress 3.3.5

I have added my code below:

```js
var value;
describe("Login operation", () => {
  it("Login Request with post method", () => {
    cy.request({
      method:'POST', 
      url:'https://odms.baitussalam.org:8445/api/v1/auth/login',
      body: {
        "userName": "faizanj",
        "password": "abc"
      }
    })
    .then(function(response){
      this.value=response.body.accessToken;
      console.log("Value "+this.value);   
          expect(response.body.name).to.equal('Faizan');
        expect(response.status).to.equal(200);

    });
  });

  it('Second test case', function() {
    var authHeader='bearer ${'+this.value+'}';
    const options = {
      method: 'GET',
      url: `https://odms.baitussalam.org:8445/api/v1/qurbani-representative`,
      headers:{
        authorization:authHeader,
      }};

      cy.request(options)
      .then((response)=>{
        expect(response.status).to.equal(200);
      });
  });
});
```

**Comment by njevdjo** [comment]
Try to replace code
```javascript
var authHeader='bearer ${'+this.value+'}';
```
with
```javascript
var authHeader = `Bearer ${ this.value }`;
```

**Comment by jennifer-shehane** [comment]
`cy.request` accepts `auth` as the options key as documented, not `authorization`. https://on.cypress.io/request

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
