### ISSUE TITLE
unable to break loop with async and sync commands combination-Cypress

### ISSUE THREAD

**Issue by khalid8899** [cypress-io/cypress#7206]
I have 10 div elements and i want to check if it has anchor tags.Once it finds the first anchor tag it should break.

Cypress code:
```js
var isLinkFound = false
var Dom_Path
cy.get('.show-card')
  .each(($el, index, $list) => {
    cy.log("$el", $el)
    cy.log("$list", $list)
    cy.wrap($el).click()
    if (!isLinkFound) {
      cy.get(".show-detail-card").eq(0).then($body => {
        if ($body.find(".show-detail-card__title>a").length > 0) {
          cy.get(".show-detail-card__title>a").click().then(() => {
            isLinkFound = true;
            return false
          })
        }
      })
    }
  })  
```

Error i am getting :

```
cy.click() failed because this element is detached from the DOM.

<div title="1st Look" class="show-card" style="width: 16.6667%; display: inline-block;">...</div>

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > cy.wrap()

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element
```

**Comment by jennifer-shehane** [comment]
The command is failing as described. One of the elements is detached from the DOM by the time it attempts to click. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
