### ISSUE TITLE
i cant run  .\node_modules\.bin\cypress open in visual code studio

### ISSUE THREAD

**Issue by andin2019** [cypress-io/cypress#7208]
hi all im new using cypress Version 4.0.1 and i can't open cypress in visual studio code  with 

```
.\node_modules\.bin\cypress open
```

and i get error in terminal visual  studio code

```
.\node_modules\.bin\cypress : File C:\Users\Lenovo\cobacypress\node_modules\.bin\cypress.ps1 cannot be loaded because 
running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\node_modules\.bin\cypress open
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Comment by jennifer-shehane** [comment]
See this SO question: https://stackoverflow.com/questions/56199111/visual-studio-code-cmd-error-cannot-be-loaded-because-running-scripts-is-disabl

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by SumanSaurabh44** [comment]
I also had same issue when I tried to open cypress in visual studio code. This issue got resolved when I used below command to open cypress for first time:

![image](https://user-images.githubusercontent.com/22400373/108103994-54f57880-7050-11eb-8f8b-8ac8506cc1ca.png)

**Comment by ShStudyTech** [comment]
On using the 'npx cypress open' resolves the issue. if your the first time using the cypress.

**Comment by juanduarte1927** [comment]
Did you try to execute before with sorry-cypress? Because I was executing with Cypress Dashboard, after I install sorry-cypress and set up that dashboard changing the parameter cypress_api_url = localhost.... I believe that this affect it the cypress Dashboard.

**Comment by vshanthipriya** [comment]
Thanks . npx cypress open works.
