### ISSUE TITLE
Windows Handles

### ISSUE THREAD

**Issue by PriyabrataBeheraTR** [cypress-io/cypress#7214]
How to handle windows/new tab in cypress , Could you please help me 

I have written in Query to handles 
cy.Settings().invoke('removeAttr','target').click() its not working

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
