### ISSUE TITLE
Issue :How to handles child windows/new tab ? is this cypress Limitation ?

### ISSUE THREAD

**Issue by PriyabrataBeheraTR** [cypress-io/cypress#7215]
Hi all,
I need help from anyone how to handles Child windows/new tab , Could you please suggest to me how to handles these scenarios

**Comment by jennifer-shehane** [comment]
Yes, see our docs on multi-tabs and workarounds: https://on.cypress.io/trade-offs#Multiple-tabs

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by PriyabrataBeheraTR** [comment]
Even I have tried this code cy.get('a[href="/foo"]').should('have.attr', 'target', '_blank') not woring for my application
