### ISSUE TITLE
Configuring different URL's with the same base domain URL via the cypress.json file

### ISSUE THREAD

**Issue by Asprao78** [cypress-io/cypress#7221]
I am a newbie to Cypress.

I want to create a simple login test to an app which has different tenants and the same base URL.

Ex: Base URL **https://www.xyz.com**

URL's to be tested:

1. **https://www.xyz.com**/**subdomain1**
2. **https://www.xyz.com**/**subdomain2**

Now, I can configure the baseURL property in my cypress.json file to **https://www.xyz.com**

The problem arises when I want to configure the subdomain with the base URL only via the `cypress.json` file. I do not want to hard code the complete URL along with username and password in the spec files.

I want to design my tests in such a way that all URL's and username and passwords are configured via the `cypress.json` file only. All URL's and values should be taken from the cypress.json value without the need for me to hard code them into the spec files.

Here is what my cypress.json looks like:

```js
{
    "baseUrl":"https://xyz.com/",
    "video":"false",
    "reporter": "mochawesome",
        "reporterOptions": {
            "reportDir": "cypress/reports",
            "overwrite": false,
            "html": false,
            "json": true
        },
    "env":{
          "tenant":"subDomain1",
          }
        {
          "tenant":"subdomain2"
          
        }
        
    }
} 
```

When I execute the cypress file, I see a syntax error. env object does not accept multiple values of the same field. 

Also, the env field only takes object values and not arrays. 

Can you help me out?

**Comment by jennifer-shehane** [comment]
`env` accepts an Object. You're passing it not an object. 

```json
{
    "baseUrl":"https://xyz.com/",
    "env":{
          "tenant1":"subDomain1",
          "tenant2":"subdomain2"
        } 
    }
} 
```

test

```js
cy.visit(`${Cypress.config('baseUrl')}**/**${Cypress.env('tenant1')}`)
```

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
