### ISSUE TITLE
Lodash (Capitalize) does not work as expected on Cypress

### ISSUE THREAD

**Issue by victorFSL** [cypress-io/cypress#7222]
### Current behavior:

_On Cypress:_
```js
 _.capitalize("FOO BAR") => "FOO BAR"
```

### Desired behavior:
_On the lodash website:_
```js
 _.capitalize("FOO BAR") => "Foo bar"
```

### Test code to reproduce

```js
const { _ } = Cypress

console.log(_.capitalize("FOO BAR")) => "FOO BAR"
```

### Versions

**Cypress version:** 4.4.0
**Browser:** Chrome 83

When I look at the documentation cypress is on lodash `4.17.15` since version `3.4.1`. Which is the lastest version of lodash and the one used in the website.

**Comment by jennifer-shehane** [comment]
Yeah, I can confirm this behavior.

### Why

So, what I've discovered is happening here is that we seem to have patched *one* of the lodash methods with [underscore.string](https://gabceb.github.io/underscore.string.site) methods. 

I can't find the exact git blame, since it spans across old repos, but I'm 95% sure that this comment is from @brian-mann about the use of overriding lodash capitalize with `underscore.capitalize`:

```
// its mo' better the lodash version
```

https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/config/lodash.js#L11:L11

This appears to be the **only** lodash method we are overriding (although we added some new methods from underscore.string).

I think this is completely unexpected behavior, especially since this is not documented anywhere. I'll have to discuss with the team how to handle this - if this would be considered a breaking change or a 'fix' to change. 

### To Reproduce

`package.json`

```json
{
  "devDependencies": {
    "cypress": "4.5.0",
    "lodash": "^4.17.15",
    "underscore.string": "^3.3.5"
  }
}
```

`spec.js`

```js
const lodash_ = require('lodash')
const underscoreString_ = require('underscore.string')

it('works', () => {
  expect(lodash_.capitalize('FOO BAR')).to.eq('Foo bar')           // passes
  expect(underscoreString_.capitalize('FOO BAR')).to.eq('FOO BAR') // passes
  expect(Cypress._.capitalize('FOO BAR')).to.eq('FOO BAR')         // passes
})
```
