### ISSUE TITLE
Problem with finding elements on page by CSS selectors - "there is no tests"

### ISSUE THREAD

**Issue by klaudynaz** [cypress-io/cypress#7228]
### Current behavior:

Hello everyone,
I ve got problem with my first scrypt :)
I decided to make small scrypt to login in on e-mail.
After launch the browser, the page is loading.
I am not able to see its preview.
And any elements on page (CSS selectors) are not found.

### Desired behavior:

The elements should be find by ids

### Test code to reproduce
```js
describe('Login',function()
{
    it('Verify logging in', function()

    {
        cy.request("https://profil.wp.pl/login.html?zaloguj=poczta")
        
        cy.wait(3000)

        cy.get("#login").type("name@name.pl")

        cy.wait(3000)

        cy.get("#password").type("password")

        cy.wait(3000)

        cy.get("#btnSubmit").click()

        cy.wait(3000)

        cy.get(".Button topuser__logout").click()

        cy.wait(3000)
        //.Button topuser__logou

    }
)    }

   
    )
```

### Versions

MacOs Catalina
Chrome 81.0.4044.129

**Comment by jennifer-shehane** [comment]
You want to use [`cy.visit()`](https://on.cypress.io/visit) to visit the url, not `cy.request()`. 

Please fully read our [documentation](https://on.cypress.io) before getting started. It walks you through a first test in our [Getting Started](https://on.cypress.io/writing-your-first-test) guide. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
