### ISSUE TITLE
using styled-components or custom component with cypress

### ISSUE THREAD

**Issue by thian4** [cypress-io/cypress#7237]
Cypress selector is easy, just do `cy.get('.myComp')` and `<input className="myComp" />` will be selected but with styled-component

maybe we need to use custom attribute like cy-data, cy-testid etc. I guess there's no other shortcut than flood our component with those custom attribute right?

The other hassle using cypress is when you use css module, where the class is generated differently every build, and imagine your component is , then you need to pass your the custom attribute all the way down
```
<Custom cy-data="btn1" />

const Custom = ({cy-data}) => <button cy-data={cy-data} />
```
any workaround to avoid this pain?

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
