### ISSUE TITLE
Can't overwrite multiple overloads of contains() command correctly

### ISSUE THREAD

**Issue by TomaszG** [cypress-io/cypress#7257]
### Current behavior:
When I tried to overwrite two overloads of `.contains()` function only one of them works, another one seems to have misaligned arguments, thus it doesn't work properly.

Contains can work in two modes:
```js
cy.get('.foo').contains('bar', options)
```
and
```js
cy.contains('.foo', 'bar', options)
```

When I defined overwrite for one mode then everything worked fine, however, with override defined for both modes, only the second one is overridden.

### Test code to reproduce

1. Create two overrides:
```js
// overwrites cy.get('.foo').contains('bar', options)
Cypress.Commands.overwrite('contains', (originalFn, subject, chars, options) => {
  return cy.log(options).then(() => originalFn(subject, chars, options));
});

// overwrites cy.contains('.foo', 'bar', options)
Cypress.Commands.overwrite('contains', (originalFn, subject, selector, chars, options) => {
  return cy.log(options).then(() => originalFn(subject, selector, chars, options));
});
```
2. Try to use both overrides in the test:
```js
cy.get('.foo').contains('bar', { some: 'option' });
cy.contains('bar', { some: 'option' });
```
3. Check Cypress log whether `{ some: 'option' }` has been logged for both usages

For such setup, only second .contains() usage will have options correctly logged, however, if we comment out second overwrite then the first one works correctly.

What I'm trying to achieve is to add support for one new option, `strict` (or `fullMatch`), which uses RegExp instead of partial match:

```js
Cypress.Commands.overwrite('contains', (originalFn, subject, chars, options) => {
  if (options && options.strict) {
    chars = new RegExp(`^${chars}$`);
  }

  return originalFn(subject, chars, options);
});
```

### Versions

Cypress 4.5.0
Chromium 81

**Comment by jennifer-shehane** [comment]
You can't overwrite the command twice. The second overwrite will just completely overwrite the first. You need to write the overwrite command to handle all cases of possible args that you intend to use. So, handling that the 3rd arg could be either the `chars` or the `selector`. You can see an example of this here: https://on.cypress.io/custom-commands#Overwrite-contains-command

So if the 3rd arg is of type x, then we know it's this arg and handle it accordingly, etc. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
