### ISSUE TITLE
Request: text assertions that normalize whitespace

### ISSUE THREAD

**Issue by eppsilon** [cypress-io/cypress#7265]
### Current behavior:

DOM elements created via templates often have extra whitespace in their text content:

```html
<div id="whatever">Hello
World</div>
```

In a Cypress test, I usually want to check that the text as seen by the end user matches a particular string. The kind of whitespace within the string isn't important since browsers collapse it into single spaces.

```js
cy.get('#whatever').should('contain.text', 'Hello World') // fails
```

### Desired behavior:

If changing the behavior of the current text assertions is too big a change, maybe a modifier could be added?

```js
cy.get('#whatever').should('contain.normalized.text', 'Hello World') // works?
```

### Versions

Cypress 4.4.1

**Comment by jennifer-shehane** [comment]
Cypress's `.contains()` command already accounts for this since Cypress 4.0.0. https://github.com/cypress-io/cypress/issues/92

```js
cy.get('#whatever').contains('Hello World') // passes
```

There's been some discussion about how the whitespaces don't match across other usecases of `.contains()` (like the `.should()` command you have) in here: https://github.com/cypress-io/cypress/pull/6411

Does switching to use `.contains()` solve your issue?

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
