### ISSUE TITLE
Hidden Assertion is not working properly 

### ISSUE THREAD

**Issue by juanjoserendon13** [cypress-io/cypress#7270]
### Current behavior: 
When I run the "should" assertion in order to test the visibility of an element after a click, using the "be.hidden chainer"
![image](https://user-images.githubusercontent.com/17439129/81351341-b7fdbc00-9089-11ea-8a11-91fbfe051b97.png)
If this gets executed through *cypress open* script and then tested on browser, the assertion will throw true, even when the element is actually visible.
![image](https://user-images.githubusercontent.com/17439129/81351382-d06dd680-9089-11ea-939e-12e59458561d.png) 
And if I run this through *cypress run* the chainer performs sometimes as expected failing the test because the element is visible and sometimes just doing the same like above.
![image](https://user-images.githubusercontent.com/17439129/81352007-18412d80-908b-11ea-907b-506640f6438b.png)

### Desired behavior:
The "be.hidden" chainer should throw false in any case if the css visibility is visible.

### Test code to reproduce
Not sure if this happens in other scenarios than my project, but what I could see is if I add a *cy.wait()* the issue gets fixed.
![image](https://user-images.githubusercontent.com/17439129/81352805-0e202e80-908d-11ea-8029-686e99dc94ab.png)
Seems like the assertion watch the element before the css changes, and maybe thats why throw a wrong result. Maybe I'm approaching the issue in a wrong way and misunderstanding the tools and how they behave.

Thanks for any help or thought.

### Versions
Cypress 4.5.0
Electron 80
Firefox 75
Chrome 81 (Just headless mode)
macOS Catalina 10.15.3

**Comment by jennifer-shehane** [comment]
The assertion will pass if at any time the element was queried that it was hidden. If the element is not hidden within the [defaultCommandTimeout](https://on.cypress.io/configuration#Timeouts) of 4 seconds, then the error will throw. This is how it should work, if there is a bug outside of this behavior we will need a completely reproducible example provided to track it down. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
