### ISSUE TITLE
     AssertionError: Timed out retrying: Expected to find element: `undefined`, but never found it.

### ISSUE THREAD

**Issue by mssachin** [cypress-io/cypress#7273]
### Current behavior:
I am new to cypress
Says undefined element not sure why

### Desired behavior:
should give me the locator at least

### Test code to reproduce
```js
Cypress.Commands.add("ClickX",(locator) =>{
  cy.xpath(locator).click({force: true});
})

cy.ClickX(QuestHullHomepage.CreatePolicyButton)

static CreatePolicyButton: string = "img[title='Add an account']";
```

this is in conjunction with typescript

### Versions
4.5.0 Cypress
Windows 10
Chrome

**Comment by mssachin** [comment]
I keep getting this issue for all objects. Please advise as I cannot proceed. Thanks.

**Comment by jennifer-shehane** [comment]
It seems as if your `QuestHullHomepage.CreatePolicyButton` is returning `undefined`, but I can't be sure without a fully reproducible example.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example (the full test code as well as the HTML to run the test code against) and we will consider reopening the issue.
