### ISSUE TITLE
Surprising behavior with native promises

### ISSUE THREAD

**Issue by badeball** [cypress-io/cypress#7275]
### Current behavior:

The following piece of code fails with `AssertionError: undefined == 'baz'`. It does however succeed when using `cy.wrap` to venture into the asynchronous domain, instead of `Promise.resolve` (bear in mind: while doing such replacement is easy - my actual issue was more complex and contained native async functions, which returns native promises).

```js
const assert = require("assert");

cy.wrap("foo").then(() => {
  return Promise.resolve("bar")
    .then(() => {
      return cy.wrap("baz");
    })
    .then(value => {
      assert.equal(value, "baz");
    });
});
```

### Desired behavior:

I'm not entirely sure what is most desirable here. I realize that there's a lot of things going on behind the scenes with chainers, etc. Maybe this is just one of the things that can't be supported due to reasons and if so that's fine. But it definitely caught me by surprise and I spent a lot of time narrowing the issue down before I could solve it.

This was surprising to me due to how Cypress is described as [promise aware](https://docs.cypress.io/api/utilities/promise.html#Examples).

### Test code to reproduce

A repository reproducing the issue can be found [here](https://github.com/badeball/reproducible-issues/tree/master/cypress/promise-surprise).

### Versions

Cypress v4.5.0, Arch Linux, Chrome 80.

**Comment by badeball** [comment]
It also makes no difference if I use native `Promise.resolve` or `Cypress.Promise.resolve`.

**Comment by sainthkh** [comment]
Sorry for the late reply. 

It seems that it's the intended behavior of Cypress. Please check [this FAQ](https://on.cypress.io/returning-promise-and-commands-in-another-command). 

It's not allowed to return Cypress-command-calling `Promise` inside a Cypress command. The provided example is the case: `cy.wrap()` calls `Promise` calles `cy.wrap()`. 

I guess the real problem here is that this error message isn't thrown.
