### ISSUE TITLE
Is it possible to bypass a login for token authentication web applications?

### ISSUE THREAD

**Issue by kalavathijeeru** [cypress-io/cypress#7278]
### Current behavior:
I tried so many times but I did not get to bypass login through cypress

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by AtofStryker** [comment]
@kalavathijeeru you can try authentication flows now with  the `cy.origin` command. Please give it a try and let us know what you think!
