### ISSUE TITLE
How to add all test run inside a test plan in test rail triggered from cypress

### ISSUE THREAD

**Issue by rikisudhir** [cypress-io/cypress#7279]
We are using Cypress to automate UI test cases. We have recently integrated the cypress framework with test rail. It is able to create test run in test rail.

### Current behavior:

Issue: We want all test run should go inside a test plan or any suite or any folder. Currently all test run are created independently(can be seen in screenshot below) in the test rail "Test Run and Results Tab" which pollutes the test rail dashboard.

### Desired behavior:

Is there any way to put all test run inside a test plan or any folder ? By clicking on the test plan or the folder i should see all test run. 

### Test code to reproduce

```json
"reporterEnabled": "cypress-testrail-accumulative-reporter"
 "reporterOptions": {
 "domain":"xxxxx.testrail.io",
      "username":"email",
      "password":"pass",
      "projectId":1,
      "suiteId":1,
      "runName":"Cypress Automated Test Run"
}
```

![image](https://user-images.githubusercontent.com/8281695/81406951-27da7800-9158-11ea-9f44-dbfea80825f5.png)

### Versions

cypress: "4.4.0
cypress-testrail-accumulative-reporter: "^1.1.4",

**Comment by jennifer-shehane** [comment]
I would refer to the (cypress-testrail-accumulative-reporter)[https://github.com/Vivify-Ideas/cypress-testrail-reporter] plugin, which is not maintained by Cypress. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
