### ISSUE TITLE
Cypress.json shape should match cypress.run options shape

### ISSUE THREAD

**Issue by shcallaway** [cypress-io/cypress#729]
- Operating System: MacOS Sierra
- Cypress Version: 0.20.1
- Browser Version: not relevant

### Is this a Feature or Bug?

Feature.

### Current behavior:

`cypress.json` shape is different from the shape expected by the module API `cypress.run`. In `cypress.json`, the configuration options are top-level but the environment options are nested:

```
{
  "projectId": "12345",
  "baseUrl": "http://localhost",
  "integrationFolder": "cypress/spec",
  "env": {
    "stubs": false
  },
  "videoRecording": false
}
```

But the module API expects an object where both configuration and environment are nested:

```
{
  config: {
    baseUrl: 'http://localhost',
  },
  env: {
    stubs: false
  }
}
```

### Desired behavior:

The shape should be the same so that I can do the following:

```
const options = require('cypress.json');
cypress.run(options);
```

This would also allow me to easily override "default" options in `cypress.json` when I use the module API.

**Comment by brian-mann** [comment]
You're technically right - the shapes due differ, but this is because there are *other* things you can pass via CLI flags or via `cypress.run()` which affect the run itself, but are not necessarily configuration - nor do they exist in `cypress.json`.

For instance most of these other keys are not `config` or in `cypress.json` but they do affect things.

https://github.com/cypress-io/cypress/blob/develop/cli/lib/cli.js#L14

I don't want to flatten the other objects on `cypress.run)_` nor do I want to flatten them on the CLI because there would be a chance of conflicts, and I believe its even more confusing in that way.

In your specific use case, I can see why you'd like this changed - but it's not actually necessary to pass in the `cypress.json` options to `cypress.run()` to begin with. They will *automatically* be picked up later.

In fact whatever you pass to `cypress.run()` or whatever you pass to the CLI just act as **overrides** to whatever is in `cypress.json`.

**Comment by shcallaway** [comment]
Thanks for the explanation!
