### ISSUE TITLE
stub request with wildcard on dynamic url params?

### ISSUE THREAD

**Issue by thian4** [cypress-io/cypress#7304]
Was trying to stub my network request but I still can see the actual api been called in cypress. I did this cypress what went wrong?

```js
describe("Test", () => {
    it("componentDidMount call", () => {
      cy.fixture("priceCheck").as("priceCheckData");
      cy.server();
      cy.route(
        "GET",
        "https://staging.gobear.co/price?rate_id=*&gobear_item_id=123",
        "@priceCheckData"
      );

      cy.visit(
        "http://localhost:6006"
      );

    });
  });
```

I think something  iswrong with the wildcard in the route url above, because it worked when I tried an exact match url like this
```js
 cy.route(
      "GET",
      " http://www.mocky.io/v2/5eba1e742f000066953c3520",
      "@priceCheckData"
    );
```
So any clue how can I match my url with params? it can be dynamic params like 
```
https://staging.gobear.co/price?rate_id=*
https://staging.gobear.co/price?some_other_id=*
```
hence I can't simply use 
```
https://staging.gobear.co/price*
```

Thanks!

**Comment by jennifer-shehane** [comment]
We use minimatch to test glob pattern matching. So I suggest ensuring that your glob matches through out `Cypress.minimatch()` utility first. https://on.cypress.io/minimatch

You didn't provide the full URL you wanted matched, so I can't tell you which glob would match.

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by thian4** [comment]
this is the full url
```
https://staging.gobear.co/price?rate_id=123456&gobear_item_id=123
```

why is it not matching with
```
https://staging.gobear.co/price?rate_id=*&gobear_item_id=123
```
?

**Comment by jennifer-shehane** [comment]
I'm not sure. It seems like the minimatch does evaluate those other globs as matching. 

Can you provide a full example of the stubbing not working/matching so that we can investigate?

**Comment by thian4** [comment]
My code above is my actual code. When I replace
```https://staging.gobear.co/price?rate_id=*&gobear_item_id=123```
with 
```https://staging.gobear.co/*```
it just worked

**Comment by jennifer-shehane** [comment]
Yes, I understand, but the application is hosted at `http://localhost:6006`, which we don't have access to, so we can't run the test code provided in order to investigate.

**Comment by thian4** [comment]
forget about the `http://localhost:6006`, it's not relevant with this issue.

With this url pattern
`https://staging.gobear.co/price?rate_id=*&gobear_item_id=123`
or this 
`https://staging.gobear.co/price?rate_id=*`, 

you can see on the left sidebar of cypress it won't do the stubbing.

But it will work if you do 
https://staging.gobear.co/*
