### ISSUE TITLE
Not able to see data from locally run API 

### ISSUE THREAD

**Issue by thiggins826** [cypress-io/cypress#7317]
### Current behavior:

Cypress is not able to see any data from locally run API. and the locally run frontend is able to load but no data is populated. This application was tested and working with external API provider however since switching to a locally run proxy this no longer works with cypress

### Desired behavior:

Cypress is able to see the traffic and provide to frontend from API running on localhost. I believe the issue lies with the internal proxy cypress runs, in most cases when proxying these kind of requests a direct value of '<-loopback>' needs to be specified.

### Test code to reproduce

requires locally run API
`cy.visit({url}) `

### Versions

Cypress 4.5.0
Chrome 81.0.4044.138

To clarify I am able to run this application under test normally in chrome browser outside of cypress

**Comment by jennifer-shehane** [comment]
We are providing the `--proxy-bypass-list=<-loopback>` flag to Chrome when run. 

You can see all flags passed by adding thie to your `plugins/index.js` file:

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser = {}, launchOptions) => {
    console.log(launchOptions.args) // print all current args
  })
}
```

Make sure you have the correct configuration if you are behind a corporate proxy: https://on.cypress.io/proxy-configuration#Set-a-proxy-on-Linux-or-macOS

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
