### ISSUE TITLE
Cypress - Need assistance in merging multiple plugins in the Index.JS file

### ISSUE THREAD

**Issue by vij27101982** [cypress-io/cypress#7321]
### Current behavior:

I wanted to merge the **NTLM** plugin with the existing plugin**("webpack-preprocessor")** in the `index.js`. Below are the details 

```js
/** 
 * Used to setup TypeScript support in cypress 
 */
const wp = require('@cypress/webpack-preprocessor')
module.exports = (on) => {
  const options = {
    webpackOptions: {
      resolve: {
        extensions: [".ts", ".tsx", ".js"]
      },
      module: {
        rules: [
          {
            test: /\.tsx?$/,
            loader: "ts-loader",
            options: { transpileOnly: true }
          }
        ]
      }
    },
  }
  on('file:preprocessor', wp(options))
}

/* Used to supprt nltm authentication in Cypress */
const ntlmAuth = require("cypress-ntlm-auth/dist/plugin");
module.exports = (on, config) => {
  config = ntlmAuth.initNtlmAuth(config);
  return config;
};
```

![image](https://user-images.githubusercontent.com/65231062/81778154-9588fa00-94f2-11ea-9a54-d991c55678f4.png)
**Error Details:**

While selecting Run All Specs" in the test runner

```
 Oops...we found an error preparing this test file:
__all
This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

A missing file or dependency
A syntax error in the file or one of its dependencies
Fix the error in your code and re-run your tests.
```
### Desired behavior:

I should be able to compile all the files successfully. Please note, If I run test cases individually then it is running correctly. However, If I run the entire suite then the error in the screen-shot is displayed
### Versions

```
  "dependencies": {
    "@cypress/webpack-preprocessor": "^4.1.3",
    "cypress": "^4.3.0",
    "cypress-localstorage-commands": "^1.1.7",
    "cypress-multi-reporters": "^1.2.4",
    "mocha": "^7.1.1",
    "mocha-junit-reporter": "1.23.3",
    "mocha-xunit-reporter": "2.0.0",
    "mochawesome": "4.1.0",
    "mochawesome-merge": "4.0.0",
    "mochawesome-report-generator": "4.1.0",
    "ts-loader": "^6.2.2",
    "typescript": "^3.8.3",
    "webpack": "^4.42.1"
```

**Comment by jennifer-shehane** [comment]
The plugins file should have a **single export** function, so you'll want to include all of the code necessary within the single export. 

As a side note, we built in native TypeScript support into 4.4.0, so you should be able to remove the TypeScript support setup when you upgrade.

Try the code below which puts all of the code necessary within the single export.

```js
const wp = require('@cypress/webpack-preprocessor')
const ntlmAuth = require("cypress-ntlm-auth/dist/plugin");

module.exports = (on, config) => {
  const options = {
    webpackOptions: {
      resolve: {
        extensions: [".ts", ".tsx", ".js"]
      },
      module: {
        rules: [
          {
            test: /\.tsx?$/,
            loader: "ts-loader",
            options: { transpileOnly: true }
          }
        ]
      }
    },
  }

  on('file:preprocessor', wp(options))

  config = ntlmAuth.initNtlmAuth(config);
  
  return config;
};
```

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
