### ISSUE TITLE
Tests run successfully using Cypress Open command but not using Cypress run command

### ISSUE THREAD

**Issue by mssachin** [cypress-io/cypress#7328]
I have a test which runs successfully using the below command
```
node_modules/.bin/cypress open --config-file cypress.staging.json
```

When the run the same test using the below command it times out looking for an object and the run is extremely slow.
```
node_modules/.bin/cypress run --config-file cypress.staging.json --reporter mochawesome --browser chrome
```

### Desired behavior:
Tests should be successful in both instances.

### Test code to reproduce
Success: `node_modules/.bin/cypress open --config-file cypress.staging.json`

Fail: `node_modules/.bin/cypress run --config-file cypress.staging.json --reporter mochawesome --browser chrome`
 contents of cypress.staging.json file below
```json
{
    "baseUrl": "",
    "testFiles": "**/*.{feature,features}",
    "pageLoadTimeout":1200000,
    "defaultCommandTimeout":30000,
    "responseTimeout":60000,
    "viewportWidth":2000,
    "viewportHeight":1320,
    "reporter": "mochawesome",
    "chromeWebSecurity": false,
    "blacklistHosts": [
        "www.googletagmanager.com"
      ]
}
```

### Versions

4.5.0 Cypress
Windows 10
Chrome

**Comment by jennifer-shehane** [comment]
I would suggest following on recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example, including test code and we will consider reopening the issue.
