### ISSUE TITLE
npm install not working behind corporate firewall

### ISSUE THREAD

**Issue by BasieP** [cypress-io/cypress#733]
I have troubles installing the npm package behind a corporate firewall due to the download of an executeable included in the post-install of the npm package.

Right now this is how my output looks like:
```
d:\Workspace\myproj>npm install cypress --save-dev

> cypress@1.0.1 postinstall d:\Workspace\myproj\node_modules\cypress
> node index.js --exec install

Installing Cypress (version: 1.0.1)

 V  Downloaded Cypress
 ×  Unzipping Cypress
   → Cypress Version: 1.0.1
    Finishing Installation
The Cypress App could not be unzipped.

Search for an existing issue or open a GitHub issue at

https://github.com/cypress-io/cypress/issues
----------

Error: end of central directory record signature not found
----------
```

Probably the downloaded file (zip i guess) gets replaced by a html page of my proxy.
therefore the download is successfull, but the unzip fails

I'm hoping for some way to resolve this for all our big banks, goverments and other companies where we don't blindly trust executables download off the internet.

I don't know much about the logic behind Cypress, but i noticed the CLI is binary, so if that is the problem, please split the package into 2 different NPM packages.
I won't be needing the CLI anyway.

**Comment by RandallKent** [comment]
@BasieP - Have you tried the [Direct Download](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Direct-Download)? That should hopefully get you up and running while the community looks into this issue further.

**Comment by tgelu** [comment]
+1 :( the link to direct download is blocked behind my organisation's firewall

**Comment by MarcLoupias** [comment]
@tgelu is your organization using something like [JFrog Artifactory](https://www.jfrog.com/artifactory/) or do they allow direct download from the npm registry ?

When sysadmins blocks downloads from the outside world the solution is to use something like artifactory to act like a proxy with an appropriate network config for that "proxy". That way they can control what it is goin on on their network instead of letting anybody doing everything.

For example when you run `npm install cypress` the artifactory will download from the internet and when it will be available your npm client will download it from your local network and not from the internet.

I am pretty sure it is possible to configure artifactory to act the same way with external downloads fired from npm installation scripts. 

So `npm install cypress` will download cypress package from your artifactory and when cypress will try to download from https://download.cypress.io/xxxxx it will download from artifactory also.

I will have to fix this issue also but later. For now the direct download is available to me so i have what i need to convince my hierarchy to heavily use cypress :-)

I don't think the bug label is appropriate here. At best you (cypress.io) could embark everything in the cypress package (every platform and arch available) but the direct download package is a 500mo stuff which seems too heavy for the npm registry.

**Comment by IcodeNet** [comment]
Guys this seems the same problem that people are having with chromedriver behind corporate networks.
In particular the issue has to do with the usage of **https:** in the download link
The solution for chrome driver is to be able to specify and alternate location for the download through the npm config.
So if cypress while installing was checking npm connfig for a **_"cypress-cdnurl_"** and that url was local to the network then there woud not be an issue.
For completness what I do with Chromedriver is set in my **_npm config file_** 
...`
chromedriver_cdnurl=http://someServer/chromedriver
..
`

**Comment by bahmutov** [comment]
You could do this already via (undocumented) CYPRESS_BINARY_VERSION environment variable that can be any URL

**Comment by IcodeNet** [comment]
For completeness based on @bahmutov very helpful hint what you need to do 
(if your network blocks downloads or mess with certificates so that you cannot download from https://)
is the following:
Download and store somewhere on your network the cypress.zip file.
Then expose this file through a URL under **https://** 
Thenset either in your environment variables a 
**`CYPRESS_BINARY_VERSION=https://someserver/cypress.zip`**

**_This is very important as the code that installs cypress has a function that checks if the alternative location for the binary starts with `/^https:/`_**

You can also pass at the command prompt the same
**`>set CYPRESS_BINARY_VERSION=https://someserver/cypress.zip&& npm i cypress -D`**

Ideally this should not be the case as the ceremony is greater than it should.
_IMHO I think any local path could do such as `C:\dev\cypress.zip`_ 
this way it would be _easier to install behind proxies or networks that block zip downloads_ and point to a local folder. Especially useful for _CI servers_

**Comment by paulpruteanu** [comment]
+1
Same as for @IcodeNet , I need to use the library under a corporate firewall which blocks downloading outside a nexus resource:

`Installing Cypress (version: 1.0.2)

 ✖  Downloading Cypress
   → Cypress Version: 1.0.2
    Unzipping Cypress
    Finishing Installation
The Cypress App could not be downloaded.

Please check network connectivity and try again:
----------

URL: https://download.cypress.io/desktop/1.0.2?platform=linux&arch=x64
Error: tunneling socket could not be established, cause=connect EINVAL 0.0.12.56:80 - Local (0.0.0.0:0)
----------

Platform: linux (Centos - 6.7)
Cypress Version: 1.0.2`

**Comment by bahmutov** [comment]
Good suggestion @IcodeNet and `set CYPRESS_BINARY_VERSION=/some/path/to/cypress.zip` environment variable already supports file path. So if your proxy does not allow whitelisting ` https://download.cypress.io` domain you could download `cypress.zip` for your platform and provide direct filepath on the test worker machine.

**Comment by bahmutov** [comment]
Please watch https://github.com/cypress-io/cypress-documentation/issues/121 where I will document `CYPRESS_BINARY_VERSION` variable

**Comment by BasieP** [comment]
it works nice with the CYPRESS_BINARY_VERSION variable, but there is still the bug of it only working with https
we have an internal nexus on http (not secure) and the CYPRESS_BINARY_VERSION variable doesn't work on http sites....
can that be fixed? i can make a PR if needed

**Comment by RandallKent** [comment]
@BasieP - PRs are always welcome! 😄

**Comment by simonatorw** [comment]
This is the only thing preventing me from using this really nice software.  For the time being, I'm stuck with the crappy alternatives :(

**Comment by brian-mann** [comment]
@simonatorw @BasieP is this still the case? There's a problem with `http` ? We fixed that in `1.1.4` https://docs.cypress.io/guides/references/changelog.html#1-1-4

**Comment by BasieP** [comment]
Gonne test it in new year.. Should work i've seen the fix :)

**Comment by simonatorw** [comment]
Hello, thx for your reply. I was able to overcome the problem with the env var solution.  Thx.  Is it possible to have npm just fetch the zip by default?  Wouldn't that solve the problem with setting the env var?  As you say, the custom path won't be saved in package.json so someone else cannot do a new npm i and be able to install cleanly.

**Comment by TimoPot** [comment]
why not place the cypress.zip file in the GitHub project?
My company does not block zip file downloads from GitHub.
CYPRESS_BINARY_VERSION can then point to the zip file on GitHub.

**Comment by chris-kobrzak** [comment]
In Cypress version 3+ you will need to unset `CYPRESS_BINARY_VERSION` and use `CYPRESS_INSTALL_BINARY` instead.

**Comment by TimoPot** [comment]
Thank you @chris-kobrzak. True but that does not solve my issue

**Comment by brian-mann** [comment]
@TimoPot you can download the binary and host yourself if you'd like. That would be the easiest way to get it inside your network.

**Comment by Kokipa** [comment]
Any indication when it will be released?
We'd really like to include it for our new project :)

**Comment by jennifer-shehane** [comment]
Soon. We have been working on the release - had to pause to fix some potential regressions in the release. 🤞

**Comment by tomasbjerre** [comment]
I made a tool to help deal with these platform specific binaries, and not being able to download behind firewall, se comment here: https://github.com/cypress-io/cypress/issues/5141#issuecomment-622774084

**Comment by zwfang** [comment]
CYPRESS_INSTALL_BINARY=3.8.2 npm install cypress@3.8.2

Fix my issue.

**Comment by mobsean** [comment]
Under Windows and behind corp. proxy I downloaded the zip manually and saved it to C:\dev\.
Then I did this:
`npm config set CYPRESS_INSTALL_BINARY "C:\dev\cypress.zip"`
and then
`npm install -D cypress`

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
