### ISSUE TITLE
 TypeError: EPO1.menuButton.should is not a function

### ISSUE THREAD

**Issue by wasiqkhan786** [cypress-io/cypress#7330]
I just made a object and funtions in it but when i call  them in my test its showing this error.
any idea
this is object

```js
export class EPO {
  showMenu() {
    return this.menuButton().click().then(function () {
      return (function () {
        return that.screenshotButton.isVisible()
      })
    })
  }

  menuButton() {
    return cy.get('[id=exportButton]')
  }
  screenshotButton() {
    return cy.get('[id=screenshotButton]')
  }
  csvExportButton() {
    return cy.get('[id=csvButton]')
  }
}
```
these are tesst
```js
describe("test menu", function () {
  it("expands menu", function () {
    EPO1.showMenu()
  });
  
  it("should show menu button", function () {
    expect(EPO1.menuButton.should('be.visible')).to.be(true);
  });
})
```

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
