### ISSUE TITLE
Provide manner to access long command log message without opening devtools

### ISSUE THREAD

**Issue by verheyenkoen** [cypress-io/cypress#734]
### Is this a Feature or Bug?
Feature

### Current behavior:
When you have a long command log message, it is truncated in the command log (displaying ellipsis). Currently the only way to read the whole log message is opening the devtools console.

### Desired behavior:
It would be good if there was a manner to display the whole log message without opening devtools.

I can think of 2 ways:

* Either display this text in a tooltip on click/hover (there is already a very short tooltip though about the console props).
* When clicked/activated: expand the log entry to multiple lines and lift the truncation so the log message is wrapped over multiple lines.

### How to reproduce:
```
cy.log('This is a very long command log message. I know being brief is good but yeah, you know.');
```

**Comment by jennifer-shehane** [comment]
You can drag the leftside of the Test Runner so that it is wider and read the message that is truncated (in real time). I know this isn't completely apparent. We need a little drag icon there.

<img width="1792" alt="screen shot 2017-10-12 at 9 57 24 am" src="https://user-images.githubusercontent.com/1271364/31499806-d7df9ec4-af33-11e7-883f-36c879b5b42f.png">

The only area where this may be problematic is when run in CI, reviewing a video you would not be able to read the entire log, but even then you should have the full output in the Stdout.
