### ISSUE TITLE
Cannot overwrite click command with subject different then DOM element

### ISSUE THREAD

**Issue by vitmalina** [cypress-io/cypress#7341]
I have a custom control that I want to click on. It is not a DOM element. I can create a custom cypress command `clickGrid` and it works. However, to have cleaner code I want to overwrite `click` command and check if it's my control, then do my custom click, if not then pass it to original function.

### Current behavior:

I can overwrite click command, but before it gets to implementation, it does validation and stops with this error

```js
cy.click() failed because it requires a DOM element.
```

### Desired behavior:

I want to be able to overwrite validation and/or only validate before original click is executed

### Test code to reproduce

```js
Cypress.Commands.overwrite('click', (originalFn, subj, param) => {
    if (subj && subj.name) {
        // my widget click, but for now just wait will suffice
        cy.wait(10000)
    } else {
        let args = Array.from(arguments).splice(1)
        originalFn(...args)
    }
})
```

### Versions
Cypress: Version 4.4.0 (4.4.0.300671)
MacOS Catalina
Chrome: Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
If you're calling the original function of click, then it's going to go through all of the normal checks that click does, including ensuring that the subject is an element, ensuring it's visible, ensuring it's attached to the window, etc. It's probably best to just use a custom command in this case. 

*maybe* passing `force = true` options to the `originalFn` will override the checks you want to ignore? But I haven't tried this. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by vitmalina** [comment]
@jennifer-shehane, thank you for your feedback and comments. I tried { force: true } approach, but it does not help. However, I believe it is a bug. The bug is that it does not allow overwrite click command if the subject is not DOM element. Let me explain one more time.

1. I overwrite click with my customFn, (I will refer to original as originalFn)
2. I use click in `cy.wrap(myWidget).click()`
3. it should call
- customFn()
- validate previous subject as DOM Element, and do other validations
- originalFn() - if it is called from customFn
4. It does it this way now
- validate previous subject as DOM Element, and do other validations
- customFn()
- originalFn() - if it is called from customFn

And because validation does not pass, `customFn` is never called.

Therefore, I argue it is a bug. If you do not consider this a bug, please keep the issue closed, I will do use "clickGrid" command approach. Thank you.
