### ISSUE TITLE
test a form redirect with cypress assert?

### ISSUE THREAD

**Issue by thian4** [cypress-io/cypress#7363]
```html
<form
    id="payment"
    method="post"
    action="http://somewhere-external.com"
    >
</form>


//after some user actions
$('#payment').submit()
```
How do I test with cypress when I have a form when submitted the entire page will be redirected to external url? I can test with cy.visit or cy.request if it's within the app, but when redirection to other url (for example payment gateway), the entire cypress session is gone.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
