### ISSUE TITLE
Error message"Your current browser version is not supported , please downlod an updated version"

### ISSUE THREAD

**Issue by yuriV7** [cypress-io/cypress#7364]
### Current behavior:

![image](https://user-images.githubusercontent.com/61054677/82054843-40064600-96c8-11ea-9ac4-ee066968efee.png)

### Test code to reproduce
I have about 70 tests and it could **Fail** randomly

### Versions
**OS**: UBUNTU & Windows
**Cypress version**
"cypress": "^4.5.0"

**Browsers**:
Chrome 81
Firefox :  72 & 76 
Firefox: 60
Electron 80

**Comment by jennifer-shehane** [comment]
This message is not being shown by Cypress itself, but by the application under test. 

Without knowing the application under test, I can't say what the logic is of the application that determines whether to show the browser message. The code is minified, so I can't tell what the logic is. 

![Screen Shot 2020-05-18 at 3 20 30 PM](https://user-images.githubusercontent.com/1271364/82193254-27da3500-991b-11ea-9f4f-82627f5d30fb.png)

Please provide a completely reproducible example or the application code showing where this is failing within Cypress.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
