### ISSUE TITLE
Make Cypress even faster: use MutationObserver for retry-ability

### ISSUE THREAD

**Issue by aaronshaf** [cypress-io/cypress#737]
Instead of (or in addition to?) using a setTimeout to retry the next assertion, a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) on the page could trigger the next queued assertion. 

Relevant code (I think): [packages/driver/src/cy/retries.coffee](https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/retries.coffee)

**Comment by aaronshaf** [comment]
Also relevant: packages/driver/src/cypress/cy.coffee#L107

**Comment by aaronshaf** [comment]
Is there a `Cypress.action` string to represent that the DOM has changed and is ready for assertion checks? Something like `Cypress.action("app:dom:changed", e)`

**Comment by brian-mann** [comment]
So this is something I experimented with awhile ago.

My thoughts:

I first began experimenting by placing mutation observers on the thing that I wanted to wait for to change. 

```js
cy.get('button').should('have.text', 'download now')
```

In that circumstance we could just wait to get notified with the text has changed.

```js
cy.get('button').should('have.class', 'active')
```

In this circumstance we just wait until the attribute modification is changed.

However this fails if there is a piece of DOM higher than the element that re-renders and blows away a chunk of the children where the mutation observer is on. I guess we could detect that too, but then it just became too complex.

Likely what is simpler is just placing a mutation observer on the body and then retrying where there is a change **to any piece of the DOM**. That logic is simplest although retries would happen more frequently than a more targeted approach.

There are two caveats to this approach:

- MutationObservers are not really *that* much faster than using the setTimeout as we are doing.
- This only works on DOM based assertions

MutationObservers are microtasks and thats why they are internally used by bluebird, and they fire faster than the 4ms limit on regular timer tasks, which is a win. However, there is performance tradeoff here. Running Cypress DOM based commands more frequently causes more load on the CPU and these retries will often queue faster than your applications own timers. That can mean that by retrying Cypress **more often** will actually result in your application updating less frequently.

More performance experimentation needs to be done here, and I haven't done this in awhile - and it could be more beneficial to use MutationObservers now.

The second thing as I mentioned is that this only works on a DOM based assertion. As it stands, the current retry logic works irrespective of what the subject is. We could maybe use one strategy or another based on the subject (whether its DOM or something else), because there is no way to figuring it out on the assertion level.

Another strategy might be to combine both as you suggested, but even then we have situations where it may be less performant because microtask retries will be running more frequently on subjects which wouldn't even be affected by DOM updates.

**Comment by brian-mann** [comment]
To your other comment, there is not an `app:dom:changed` event. We certainly could add it and attach to the body like we do on other things. But what is the point? 

It would likely be useful for debugging purposes, but then again you can already use the built in dev tools to add debuggers around mutation observers. I'm not against adding it, but it will fire a ton of events and i'd like to understand the specific use case.

**Comment by brian-mann** [comment]
Also wanted to clarify that I think this is a potentially huge win for Cypress and will continue to separate us from other testing tools by being even *more* precise with retrying. I'm very excited about this idea, it just needs some experimentation / performance testing to verify it will be a better strategy.

**Comment by aaronshaf** [comment]
Thanks for the wonderful responses. Would be nice to run this on a large diverse test suite.

**Comment by Phillipe-Bojorquez** [comment]
I was speaking about this with a coworker and then found this issue on a search.  A year ago this was in the stage: needs investigating.  I am curious if any headway has been made in that investigation?

**Comment by jennifer-shehane** [comment]
@Phillipe-Bojorquez No progress has been made on this issue.

**Comment by lucksp** [comment]
this probably different, but I only see this current related issue to Mutation Observer.

I am curious about using MutationObserver during `cy.visit({ onBeforeLoad: runObserverFunction()})` because we have an `async` script injection to get our product loaded.  So, when that script is done loading, I want to be able to spyOn my methods.  

```
(function() {
  var se = document.createElement('script'); se.type = 'text/javascript'; se.async = true;
  se.src = '//urlgoes.here/inject-script-file.js';
  var done = false;
  se.onload = se.onreadystatechange = function() {
    if (!done&&(!this.readyState\|\|this.readyState==='loaded'\|\|this.readyState==='complete')) {
      done = true;
    }
  };
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(se, s);
  })();
```

Our network requests (legacy type code) are made with [YAHOO's Util Library ](https://yuilibrary.com/) which makes "RPC" requests.  These are considered a "script" in the network, so we cannot use the Cypress "server" options to return different results.  No plans to update all our requests at this point.

The issue I have seen with mutation observer with `onBeforeLoad` is that the DOM cannot be queried (it's null), i think because of issues with the context of the browser?

If i wait until option `onLoad` then the network requests have already begun and it's too late.

**Comment by jennifer-shehane** [comment]
Closing since this hasn’t had a lot of activity over the years. We are looking at ways to improve performance of Cypress currently and we have investigated Mutation Observers more in depth. If something comes out of it we’ll create a new issue to document.
