### ISSUE TITLE
Call unlayer.exportHtml and verify the output. 

### ISSUE THREAD

**Issue by bilal-bin-zafar** [cypress-io/cypress#7371]
I need some help regarding this one as I'm newbie to cypress. What exactly I've to do ? Please guide
Web Link for automation: https://react-email-editor-demo.netlify.com/

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
