### ISSUE TITLE
Do you have a minimal set of production dependencies for cypress?

### ISSUE THREAD

**Issue by WinstonN** [cypress-io/cypress#7377]
Hello 

Looking at https://github.com/cypress-io/cypress/blob/develop/package.json#L79
I only see `devDependencies` 
As I understand it, these include dependencies used for contributing to the project, but might not be needed to just simply run cypress

Can you point me to documentation, or a file, where I can see a minimal set of dependencies needed to run cypress via cli

I tried, `npm install --production` but this failed with quite a few errors

Thanks!

**Comment by jennifer-shehane** [comment]
The cypress repo is a monorepo of several packages that are later built into a deployed cypress npm package. You should be able to see the dependencies of the actual `cypress` CLI package here: https://www.npmjs.com/package/cypress

It would help knowing what you're trying to do with this information though, because I'm not sure how exactly what you're looking for.

**Comment by WinstonN** [comment]
heya @jennifer-shehane 

Thanks for the response
I'm trying to run cypress in a lambda, and essentially boil it down to a place where it will fit inside 512MB  as you can see here https://github.com/cypress-io/cypress/issues/1232

It is a wonderful piece of software but it is also disheartening not having any buy-in from someone at cypress - I am not sure why this is the case

**Comment by WinstonN** [comment]
Closing this issue - not needed anymore
