### ISSUE TITLE
Invalid attempt to spread non-iterable instance. non-array objects must have a [Symbol.iterator]() method.

### ISSUE THREAD

**Issue by vladL2C** [cypress-io/cypress#7383]
### Current behavior:

![weird](https://user-images.githubusercontent.com/26981847/82162597-d3728d80-98f9-11ea-91b5-96522adfed80.JPG)

![stackTrace](https://user-images.githubusercontent.com/26981847/82165893-e772bb00-990a-11ea-96a6-2147b8123354.JPG)

### Desired behavior:

Tests should run

### Test code to reproduce

I don't have reproducible steps it started happening randomly (locally)
Test's run perfectly fine in the ci environment

I have tried clearing cypress cache / re installing cypress / re installing node modules / selecting electron browser to run tests/
upgrading to v4.5.0 but this still happens.

not sure what else to try that could be causing this issue.

### Versions
4.3.0 | windows 10 64bit | chrome

**Comment by jennifer-shehane** [comment]
This error is being thrown from you application code, not Cypress. You'll need to locate where this is being thrown from within your application and fix the issue or ignore uncaught exceptions in Cypress by following these directions: https://on.cypress.io/catalog-of-events#Uncaught-Exceptions

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by RoySegall** [comment]
I've got the same issue but the same issue. Let me explain:

On my CI I run:
```bash
npm i --also dev
npm run build:e2e
```
I have a docker container that serves my compiled app via an Nginx to simulate my real-world application as much as I can (while in real-world scenario a CDN serves it but eventually a CDN is just a simple HTTP server that serves static files).

But, my cypress tests are running via Github actions from the directory of my react app. I got the error when I run the tests without the interactive mode on my local machine and found that a stub that waited for a window to be open (a window for authorizing my use to my app, just like connect with Facebook).

I solved it locally wy adding a `cy.sleep(3000)` but the CI still fails and I don't know why   🤔
