### ISSUE TITLE
keyboard event using cypress type('{downarrrow}')

### ISSUE THREAD

**Issue by tejasdandekar** [cypress-io/cypress#7396]
```js
///<reference types="Cypress"/>

describe("date",function(){
    it("date testing",function(){
        cy.visit("https://www.cheapoair.com/en-in/")
        cy.get("label[id='owFlight']").click()
        cy.get("input[id='from-01-0']").type("lon").trigger("keypress","bottom")
```
       
I'm trying to handle dynamic dropdown by using keyboard event. Tried by using each function but not able to do it
Able to handle keyboard event protractor, java, python. So please can  you help me in overcome this problem. Thankyou.

**Comment by jennifer-shehane** [comment]
Hey @tejasbubane, I can't tell from the test code provided what your intention is to test. The test passes and the dropdown pops down. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
