### ISSUE TITLE
cy.contains() reruns previous commands when re-querying an alias 

### ISSUE THREAD

**Issue by kokovtsev** [cypress-io/cypress#7413]
### Current behavior:

Preconditions:
* an element is located using `cy.contains()` invoked off the `cy` object and saved as `@alias`
* the element is recreated by the application under test

If the test tries to retrieve the element using `cy.get('@alias')`, the whole chain is executed again as expected (starting with `cy.contains()`). The `cy.contains()` works fine and finds the element in the whole document.

However, if there were some querying commands before `cy.contains()`, they seem to interfere with the alias querying procedure. For instance, the alias query fails if the query command _preceding to `contains`_ does not succeed. Please see the reproduction example for more clarity

### Desired behavior:

When invoked off the `cy` object, the `contains` command should not depend in any way on the precedent command.

### Test code to reproduce

Reproduction repo:
https://github.com/kokovtsev/cypress-repro-cy.contains/blob/master/cypress/integration/examples/contains.spec.js

Application under test:
https://codesandbox.io/s/gracious-newton-q4913?file=/src/App.js

### Versions

Windows 10 x64, Cypress 4.5.0, Electron 80/Chrome 81/Firefox 76

### See also
Might be related to:
* `.each` changes scope for next dual-command (like `cy.contains()`) #4921

**Comment by jennifer-shehane** [comment]
I can recreate this with the code below. It seems it's just not recognizing the `.contains()` as a parent command and always attempting to travel up to the previous command when trying to retrieve the alias. This results in some weird behavior. 

`spec.js`

```js
it('cy.contains()', () => {
  cy.visit('index.html');
  
  // removing this line changes the behavior of the test
  cy.get('h1')
  cy.contains('Current').as('counter')
  cy.get('@counter').should('match', 'div')

  // this causes the <div> to be recreated and also removes H1
  cy.contains('button', 'Update DOM').click()

  // fails trying to get 'h1'
  cy.get('@counter').should('contain', 'Current 1')
})
```

`index.html`

```html
<html>
<body>
  <h1 id="h1">Hello</h1>
  <div id="div">Current</div>
  <button id="button">Update DOM</button>
</body>
<script>
  document.getElementById('button').onclick = () => {
    const newText = document.createTextNode('Current')
    const newDiv = document.createElement('div').appendChild(newText)
    
    document.getElementById('div').remove()
    document.body.appendChild(newDiv)
    document.getElementById('h1').remove()
  }
</script>
</html>
```

### With `cy.get('h1')` command

The alias tries to retrieve the `h1` element (the previous command to the defined alias), so the test fails because it's been removed. 

<img width="679" alt="Screen Shot 2020-05-20 at 1 46 41 PM" src="https://user-images.githubusercontent.com/1271364/82416630-5b929780-9aa0-11ea-977d-913a5900076b.png">

### Without `cy.get('h1')` command

It reruns the `cy.visit()` command (the previous command) - wow. 

<img width="679" alt="Screen Shot 2020-05-20 at 1 46 41 PM" src="https://user-images.githubusercontent.com/1271364/82416793-a90f0480-9aa0-11ea-8ebb-caa64c454314.png">

**Comment by Gibstick** [comment]
We ran into the same issue and our test is structurally identical to the one in https://github.com/cypress-io/cypress/issues/7413#issuecomment-631287674. This might be obvious to others but a quick workaround is to do `cy.root().contains(...)`, which should be functionally equivalent (I hope).

**Comment by BlueWinds** [comment]
> We ran into the same issue and our test is structurally identical to the one in [#7413 (comment)](https://github.com/cypress-io/cypress/issues/7413#issuecomment-631287674). This might be obvious to others but a quick workaround is to do `cy.root().contains(...)`, which should be functionally equivalent (I hope).

Good workaround, yeah.

I'm going to close this issue, since the resolution to #7306 (coming out in Cypress 12) is basically redoing how commands chain together, and the internal logic around re-querying the DOM is pretty different. See my comments in that issue for a more complete explanation of the changes coming in Cypress 12 in this regard.
