### ISSUE TITLE
cy.request() doesn't mock all requests

### ISSUE THREAD

**Issue by sergeyKhristenko** [cypress-io/cypress#7478]
### Current behavior:
Sometimes requests don't mocked. My guess is that `cy.server` getting reset between `it`s. So if `cy.server` declared in `beforeEach` requests could occur before `cy.server` properly set up.
Like on the screenshot you can see that request to `/translator` mocked and listed in `ROUTES` but sometimes real request could happen:
![cypress-mock](https://user-images.githubusercontent.com/18219232/82891482-7bb9cf00-9f56-11ea-8f55-d4cc9b419a3d.png)

### Desired behavior:
Setup `cy.server` somehow that it doesn't getting reset between `it`s

### Test code to reproduce
This is not really a `test` it just can demonstrate the behaviour. To check if it does you need to manually click on each step and check if request to `translator` was stubbed or not. It doesn't happens every time so it does 10 repetitions. Though I choose 10 just because it's kind of round number, don't have any scientific proof than 10 should be enough.

```js
describe('Test', function () {
  before(function () {
    cy.visit('https://www.theguardian.com/international');
  });

  beforeEach(function () {
    cy.server();
    cy.route('POST', '**translator**', {});
  });

  for (let i = 0; i < 10; i++) {
    it('load page', function () {
      // reload the page
      cy.get('.inline-the-guardian-logo')
        .should('exist')
        .click({ force: true });
    });
    it('dummy', function () {
      // split page loading to multiple `it`s so "translator" request can occur in 'beforeEach'
      cy.wait(500);
    });
    it('dummy', function () {
      cy.wait(500);
    });
  }
});
```

### Versions
Cypress 4.3.0, operating system: any, browser: any

**Comment by sergeyKhristenko** [comment]
Currently my workaround is to explicitly wait for the last request. Something like:
```
it('load page', function () {
      // reload the page
      cy.get('.inline-the-guardian-logo')
        .should('exist')
        .click({ force: true });
      cy.wait('@ translator')
    });
```

**Comment by jennifer-shehane** [comment]
The way you've written the tests makes is non-deterministic when the translator request will go out, so if they go out before the cy.route() is run in the `beforeEach`, then they won't be stubbed - as you've explained. You'll need to write your tests in a more deterministic way. 

- Writing explicit waits as you've seen is a great example of determinism - you want to make sure your test steps don't continue until this request has responded. 
- We would also not recommend visiting the site once, but visiting `beforeEach` test so that state from the previous test doesn't leak into the next test and affect it in unexpected ways.
- There's no determination on when the 'dummy' test should run also, so it's a matter of timing where you're app loading will be by the time it is run, normally  you would define some sort of state for 'my app is loaded', so that the next test doesn't run before then. 
- We also wouldn't recommend [relying on the state of previous tests for next tests](https://docs.cypress.io/guides/references/best-practices.html#Having-tests-rely-on-the-state-of-previous-tests).

**Comment by sergeyKhristenko** [comment]
@jennifer-shehane thanks for the reply! I see what you're saying.
I guess that the case here(or how it could be used) is something similar to why `Cypress.Cookies.preserveOnce('session');` exists - to keep the state through the all `it's`.

It seems to be not a bug but just how `cypress` works be design. My request would be to add a possibility to make `cy.server();` persistent and don't reset after each `it`.

How do you think would it be possible to add it to roadmap at some point?

**Comment by jennifer-shehane** [comment]
That's part of the larger work planned here, which is on our roadmap https://github.com/cypress-io/cypress/issues/686
