### ISSUE TITLE
Fixture json data will not populate properly for a select value

### ISSUE THREAD

**Issue by rolu315** [cypress-io/cypress#7480]
### Current behavior:

Using fixture data variable from a `fixture.json` file, Cypress is unable to locate a select even though it located the exact same value when it was hard coded.

Example: 
Without Fixture:
```js
cy.get('#expire_month_display').select('11')  <---value is actually 11 not the label or name.
 With fixture data var:
cy.get('#expire_month_display').select(data.oeMonth)
```

Here is the json: 
```json
"oeMonth": 11,
```

### Desired behavior:

Fixture data should populate properly the value for selects

### Test code to reproduce

See above, i am running tests on a payment gateway and prefer not to disclose our credentials in th test code. 

### Versions

Chrome

**Comment by jennifer-shehane** [comment]
What is the error you are seeing? What is `date.oeMonth` evaluating to?


Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide the code defining the fixture and a full fixture file so we can run the tests and also the HTML of the select you are testing against. 


Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by rolu315** [comment]
I actually wired this up better last night with your documentation. Thank you for your response.

**Comment by amitkalyan** [comment]
Hi,@rolu315 will you please help me out in this..i am facing the same issue.

**Comment by amitkalyan** [comment]
Hi,@theTestingApproach please help me out resolving this issue
