### ISSUE TITLE
CypressError: `cy.visit()` failed because you are attempting to visit a URL that is of a different origin.

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#7490]
how to disable same-origin , i set `chromeWebSecrity` to `false`, but also the same error. 

I want to test http://diamond.aaaa.com, first to redirect login, but had this question.

```
CypressError: `cy.visit()` failed because you are attempting to visit a URL that is of a different origin.
The new URL is considered a different origin because the following parts of the URL are different:

  > protocol

You may only `cy.visit()` same-origin URLs within a single test.

The previous URL you visited was:

  > 'https://login.aaaa.com'

You're attempting to visit this URL:

  > 'http://diamond.aaaa.com'

You may need to restructure some of your test code to avoid this problem.

https://on.cypress.io/cannot-visit-different-origin-domain
```

### Versions

cypress: 4.6.0
browser: 83

**Comment by jennifer-shehane** [comment]
This link in the error message should lead to https://on.cypress.io/error-messages#cy-visit-failed-because-you-are-attempting-to-visit-a-different-origin-domain

See our [Web Security](https://on.cypress.io/web-security#Limitations) document for workarounds as visiting 2 domains with different protocols in a single test is not currently supported.  https://github.com/cypress-io/cypress/issues/944
