### ISSUE TITLE
Headless tests with chrome pops up chrome UI.

### ISSUE THREAD

**Issue by poojyasankar** [cypress-io/cypress#7496]
### Current behavior:

![headlesstest](https://user-images.githubusercontent.com/60782196/82994485-ea586480-a00a-11ea-988d-0feced293306.gif)

### Desired behavior:

It previously used to be possible to run the headless test for chrome browsers. 
I also tried doing a clean install but it still does this. And I wouldn't normally have a problem with this behavior but I noticed that only if I run the test headlessly can I avoid XHR looping. 

### Versions

Cypress 4.7.0
Chrome 81
Win 10

**Comment by jennifer-shehane** [comment]
The default for `cypress run` is to run `headed` for Chrome and Firefox. This has always been the case since the behavior was introduced. https://on.cypress.io/command-line#cypress-run-headless

The default for `cypress run` is to run `headless` for Electron. This has also always been the case. https://on.cypress.io/command-line#cypress-run-headed

To run Chrome `headless`, pass the `--headless` flag.
