### ISSUE TITLE
Errors show code frame to preview with garbage characters.

### ISSUE THREAD

**Issue by JFRabbit** [cypress-io/cypress#7507]
<img width="422" alt="截屏2020-05-28下午3 54 00" src="https://user-images.githubusercontent.com/22906174/83115286-bc534d00-a0fc-11ea-9257-8736bc943240.png">

<img width="332" alt="截屏2020-05-28下午3 54 23" src="https://user-images.githubusercontent.com/22906174/83115293-be1d1080-a0fc-11ea-992d-73dcaccd3a24.png">

file encoding=utf-8

### Versions
Cypress 4.7.0
MacOS 10.15.2
Chrome 83.0.4103.61

**Comment by jennifer-shehane** [comment]
I can recreate this with the following code. This issue occurs in 4.6.0 onward, since that is when we first introduced the code frames. It's probably something with the renderer we're using, it's transforming these characters to `'å­¦ã¶ãã¨'`

```js
it('test', () => {
  cy.contains('学ぶこと')
})
```

<img width="633" alt="Screen Shot 2020-05-29 at 4 39 01 PM" src="https://user-images.githubusercontent.com/1271364/83248360-f68b2000-a1ca-11ea-9d2b-671c9117df4d.png">
