### ISSUE TITLE
how i can visit link with a copy at the label

### ISSUE THREAD

**Issue by bukutamu** [cypress-io/cypress#7528]
### Test code to reproduce

this is my current code:
```js
    cy.get('.copy-link__text').click({force:true}) //this is i selected this label to copy
     .then((link) => { //and i want to get this link
        cy.url().should('eq', 'http://stg.paper.id/')
        cy.visit(link) //open link
     })
```

**Comment by jennifer-shehane** [comment]
The `.click()` command will return the DOM element found, so you'll need to traverse into the DOM element to access the `href` `attr`. 

```js
it('href value', () => {
  cy.visit('https://example.cypress.io')
  cy.contains('a', 'get').then(($el) => {
    const link = $el.attr('href')
  })
})
```

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by bukutamu** [comment]
Thank you jennifer
