### ISSUE TITLE
The array of aliases is waited without finish

### ISSUE THREAD

**Issue by MikePopov** [cypress-io/cypress#7530]
I have a code

```js
logInUI (login: string, password: string) {
        this.open();

        cy.server();
        cy.route('GET', '/api/translations').as('request1');
        cy.route('GET', '/api/beds?wardId=*').as('request2');
        
        cy.get(this.usernameInput).clear().type(login);
        cy.get(this.passwordInput).clear().type(password);
        cy.contains('Log in').click();

        cy.wait(['@request1', '@request2']);
}
```

But aliases in `cy.wait` is waited without the finish 

![image](https://user-images.githubusercontent.com/23239997/83265213-d9098680-a1c9-11ea-978c-819f9df0e402.png)

**Comment by jennifer-shehane** [comment]
If you're using GraphQL, this may be related to https://github.com/cypress-io/cypress/issues/5999

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
