### ISSUE TITLE
Have long file paths to screenshots and video that return be 'copy-able' as a single link

### ISSUE THREAD

**Issue by JobLeonard** [cypress-io/cypress#7533]
# Current behavior:

As is, paths to screenshots and videos generated when a test fails are displayed in such a way that I cannot use the hyperlink capabilities of my terminal emulator. Similarly, a straightforward copy/paste is not possible.

![image](https://user-images.githubusercontent.com/259840/83269104-e2452400-a1c6-11ea-8478-35e477376293.png)

### Desired behavior:

Displaying the file paths in such a way that clicking on them does not break, and so that copying them is straightforward.

### Test code to reproduce

Any failed test that produces screenshots or videos will do, I think?

### Versions

Cypress version: 4.2.0
OS/Browser: not relevant, as this is about the terminal UI

**Comment by jennifer-shehane** [comment]
We display the filepath that the screenshot/video is located relative to your home directory and do not promise any utility outside of this display. 

The link is likely not working because of how we handle the display of longer filenames - returning to a newline instead of printing the entire link to console regardless of size: https://github.com/cypress-io/cypress/pull/5120

I seriously doubt we will change this display anytime soon as the original PR to show the entire link was a pretty big undertaking itself with this offering pretty minimal value.

**Comment by JobLeonard** [comment]
> The link is likely not working because of how we handle the display of longer filenames - returning to a newline instead of printing the entire link to console regardless of size

In the linked PR I see that the latter used to be the case. What design decision motivated the change?

**Comment by jennifer-shehane** [comment]
Most of the filepaths were truncated previously so not fully viewable. We were also wanting to keep the tables looking nice and readable, not extending way beyond the set width of our reporter. https://github.com/cypress-io/cypress/issues/4977

**Comment by tchiaspko** [comment]
I also face this very same issue very frequently.  You can find this issue while using a simple VT100 or xterm. Is the width of the reporter adjustable? I think that is the better solution(i.e. let the user decide what the width is)

**Comment by jennifer-shehane** [comment]
Since this issue hasn’t gotten a lot of interest over the years, we’ll close this as not planned.
