### ISSUE TITLE
Elements invisible since Cypress 4.6.0

### ISSUE THREAD

**Issue by SevanAMPS** [cypress-io/cypress#7557]
### Current behavior:
Since version 4.6.0, I use the new fix `experimentalSourceRewriting` to `true` because I want to avoid __ in url. 

However Cypress seems to not now display all my web page Elements. 

### Desired behavior:

Resolve and let my elements appears. 

### Test code to reproduce
```js
describe('Impression', () => {
    beforeEach(() => {
        cy.visit(XMLC_BaseHRef)
        cy.get('#in_user').type(userName)
        cy.get('#in_passw').type(password + '{enter}') //Connexion a Mainta
    })


    it('Se connecte a Mainta', () => {
        cy.log("La connexion s'effectue correctement ")
    })


    it('Test de la fonction impression', () => {
        cy.wait(5000)
        cy.visit("GrilleE39")
        cy.get(':nth-child(2) > [style="background-color: rgb(222, 222, 222);"] > .icon-12x12-blue').click() //clique sur le premier BT

        cy.get('a[onclick="MOSDefaultPrint(event,false,\'E39\');return false;"').eq(1).click() //clique sur le bouton imprimer

        cy.get('#ID_NUMITEM312').click()
        cy.get('#BtnMOSSavePrintDialog').click()

//deconnexion
    })
})
```
<img width="372" alt="Invisible Zone Elements" src="https://user-images.githubusercontent.com/31892506/83434153-399efa80-a43a-11ea-975a-3db882a0d4f8.png">

==> Here, you can see, nothing is loaded in this div. 

<img width="499" alt="Error Code" src="https://user-images.githubusercontent.com/31892506/83434161-3b68be00-a43a-11ea-9a7e-a7a09386c8b4.png">
==> Obviously, Cypress can't find any Elements here. 

I Have no more informations usefull here, don't hesitate If I Can Add Something more. 

### Versions
Cypress 4.7.0 
Chrome 83
Electron 80

**Comment by jennifer-shehane** [comment]
Is there any way you can provide a reproducible example? There's not much we can do without that. You're welcome to send private info to support@cypress.io. 

The `experimentalSourceRewriting` flag is experimental and we're hoping to work through all the issues with it before general release. Thanks!

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
