### ISSUE TITLE
Error message filename should truncate instead of wrap

### ISSUE THREAD

**Issue by Bkucera** [cypress-io/cypress#7560]
### Current behavior:
![image](https://user-images.githubusercontent.com/14625260/83464324-8c7ab100-a43e-11ea-9730-cdcdf73f91b3.png)

### Desired behavior:
![image](https://user-images.githubusercontent.com/14625260/83464373-b3d17e00-a43e-11ea-8d4e-e03026c1b00e.png)
![image](https://user-images.githubusercontent.com/14625260/83464384-bdf37c80-a43e-11ea-81f4-71341188dd64.png)

### Test code to reproduce

- should add a test for the width and height of the element to ensure it's truncated

**Comment by panzarino** [comment]
Should I update #7515 as well? That PR was just modified specifically to wrap per: https://github.com/cypress-io/cypress/pull/7515#pullrequestreview-421886974

**Comment by jennifer-shehane** [comment]
I would probably check with the design channel to get consensus on this decision. I'm not sure truncating is the best decision here. Some people have pretty long files and the most important part is the filename which would be lost.

**Comment by Bkucera** [comment]
good point @jennifer-shehane

**Comment by panzarino** [comment]
@Bkucera it seems like the consensus was to leave it wrapped, because mot displaying all info usually results in complaints and most importantly during screenshots/videos it's important to be able to see the full file name. Perhaps an intelligent wrapping system with line breaks only on `/` or something along those lines might work better than what we have now.

**Comment by Bkucera** [comment]
@brian-mann had an opinion

**Comment by jennifer-shehane** [comment]
Yeah, we came to a consensus including @brian-mann to leave the wrapping as is for now. Going to close for now.
