### ISSUE TITLE
Common step implementation for multiple feature files

### ISSUE THREAD

**Issue by khushbooabhi** [cypress-io/cypress#7568]
### Background:
I am working on cypress with cucumber. I have multiple feature files in my project and in each feature file have lot of common step definitions. 

### Current behavior:
At this moment, every feature file should have separate .js implementation  file, due to this i have to repeat common step defs in every .js implementation file.

### Desired behavior:
 I am looking for common .js implementation file which can be utilized in multiple feature files.

Could you please help or guide me to achieve this behavior. Please let me know for any input.

**Comment by msmps** [comment]
I think this is better suited over at this repo:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor

**Comment by jennifer-shehane** [comment]
@khushbooabhi Yes, I recommend seeking advise from https://github.com/TheBrainFamily/cypress-cucumber-preprocessor plugin, since Cucumber is not natively supported in our product.

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.
