### ISSUE TITLE
Security Error : The operation is insecure 

### ISSUE THREAD

**Issue by SonaliAvaya** [cypress-io/cypress#7571]
![Error while typing desc on firefox browser ](https://user-images.githubusercontent.com/62263280/83551724-b8e20c00-a4d6-11ea-86e6-a08676485345.png)

![HTML DOM](https://user-images.githubusercontent.com/62263280/83551996-18401c00-a4d7-11ea-9be1-c4276862fe54.png)

Firefox version : Firefox 67 beta version 
Cypress version  : 4.7.0 

## Actual Behaviour: 

At first time it will give above error and at second and third time that error gone. 

## Expected Behaviour : 

Work as chrome browser

I have tried : 

Going to firefox's `about:config `and toggling `network.websocket.allowInsecureFromHTTPS`, 
Remove `serviceWorker.js` file

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide the test code, HTML, css, js all necessary that we can run on our machines to reproduce the error. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by SonaliAvaya** [comment]
Well actually i can understand your point and i have uninstall ff and install again on my laptop then it does working good on while running script on cypress UI but unfortunately i can not run my script on firefox headless browser and script does working good without any error on ff browser on cypress Test Runner UI 

Error on ff headless 
![image](https://user-images.githubusercontent.com/62263280/83681229-1b5b0b00-a5b0-11ea-953d-7dbd80735a47.png)

**Comment by SonaliAvaya** [comment]
Ohk no problem anyways i dont get issue anymore on cypress UI but i got issue on ff headless mode which is open issue in cypress :  https://github.com/cypress-io/cypress/issues/6813
