### ISSUE TITLE
Simulating long click with hammer.js in cypress

### ISSUE THREAD

**Issue by WillianaLeite** [cypress-io/cypress#7586]
**Current behavior:**

I'm trying to simulate a long click, on an element manipulated by [Hammer.js](https://hammerjs.github.io/). I have a square and when I make the long click it increases its dimensions, when the long click is done natively everything happens correctly, however when I try to simulate with cypress the square element is not expanded. Apparently the problem is found in cypress that is unable to simulate native clicks, as presented in this question: [https://github.com/cypress-io/cypress/issues/2521](#2521).  Any solution to this problem? 

Here is my code:

```js
cy.visit('./src/index.html')    
cy.get('.square').trigger('mousedown')
cy.wait(5000)
cy.get('.square').trigger('mouseleave')

// After the long click occurs I make the statement to check if the square element has changed its dimensions
cy.get('.square').should('have.css', 'width', '90px')
```

Cypress doesn't return an error, it just doesn't execute the long click.

**Desired behavior:**

Simulate the long click on an element handled by Hammer.js

**Versions**

Cypress: 3.6.0 on Windows 10

**Comment by jennifer-shehane** [comment]
Without a way to run the code and reproduce on our end, we wouldn't be able to offer assistance on the exact way to test this in Cypress. We have no idea what events your code is listening to.

I would also recommend updating to our latest version of Cypress, as 3.6.0 is quite old now.

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
