### ISSUE TITLE
cy.request doesn't allowing me to go to next UI test cases

### ISSUE THREAD

**Issue by makwanaparth94** [cypress-io/cypress#7596]
Created two files:

API test --> DO Login and writing token & saving it to fixture file

Spec test -->Do REAL Login by using username and password and once test case pass then in next test first get the response by using `cy.request` using token which saved by step1. Based on response keys search the data in search bar

API Test File:
```js
it("Login Request API", function () {
  cy.request({
    method: "POST",
    url: POST URL,
    headers: {
      "content-type": "application/json"
    },
    body: {
      "email": USER NAME,
      "password": PASSWORD
    },
    log: true
  }).then((response) => {
    // Parse JSON the body.
    expect(response.status).to.equal(200)
    let resbody = JSON.parse(JSON.stringify(response.body));
    cy.writeFile("File Path to store response", resbody)
  })
});
```
Once above test is executed then it redirect to first test . Not going to further tests

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Can you provide a video of this behavior? I'm having a hard time understanding where the unexpected behavior is. Or can you provide the full test code to reproduce the issue on our end?

Please comment in this issue with a reproducible example and we will consider reopening the issue.
