### ISSUE TITLE
Large XHR response objects can exceed the maximum header size.

### ISSUE THREAD

**Issue by zachgibb** [cypress-io/cypress#76]
If I respond to `route` with a very large object, tests waiting for that response will fail with `ERR_EMPTY_RESPONSE`

``` coffeescript
cy
  .server()
  .route("POST", /route/, reallyLargeObject).as("willFail")
  .get(".submit").click()
  .wait("@willFail")
```

**Comment by brian-mann** [comment]
Okay this is not a quick or easy fix.

Node sets a constant maximum total header size at `80kb` for all headers. There is no easy way to split this up. We can't toss the data in the request body either, since that would be altering the entire request.

Probably the only way to do this is transfer the data over websockets while the server begins handling the request.

That means managing all kinds of state, but this would work. There are some other features of the XHR refactor that would also introduce websockets, so I'll hold off on implementing this until it can go in with some new architecture.

In the mean time you'll have to reduce the response sizes to less than 80kb, or just use a fixture and not an alias.

**Comment by acthp** [comment]
Trying to find a workaround for this, e.g. manipulating the request, or the response, or the server object. The available hooks fire after the request is sent, and after the response is delivered to the app, so there's no opportunity to influence it. Also haven't found any way to access the server object, e.g. to override a method. Any suggestions? Using a fixture doesn't help, because it's fixed. ;)

**Comment by brian-mann** [comment]
If your fixture exceeds the maximum headers you'll need to modify your app code, such as using a conditional if `window.Cypress` exists, and if so, to use a property on that (on the XHR response callback)

Then ahead of time in your test code, you can use a fixture and set that property on the Cypress object so your app code can pick it up.

**Comment by brian-mann** [comment]
The key takeaway here is that Cypress **is just javascript** and it has native access to everything. You can share properties and data. You can collaborate between Cypress and your application code. 

If your application code is "hardwired" to take a specific path, you can just modify it to open a seam to which you can use Cypress to modify that behavior.

**Comment by acthp** [comment]
Just realized I could wrap onreadstatechange during onRequest, to flow the data into the app.

```js

cy.route({
	url: '/api/bookmarks/bookmark*',
	method: 'GET',
	onRequest: xhr => {
		var orsc = xhr.xhr.onreadystatechange;
		xhr.xhr.onreadystatechange = function() {
			if (this.readyState === 4) {
				Object.defineProperty(this, 'response', {
					writable: true
				});
				this.response = content;
			}
			orsc.apply(this, arguments);
		};
	},
	response: 'placeholder',
});
```

The Cypress console shows response 'placeholder', but otherwise this functions as a workaround.

**Comment by brian-mann** [comment]
Yup that would work.

You could also bind to `onload` instead of `onreadystatechange`. Would avoid the `readyState` conditional

**Comment by ankri** [comment]
Thank you for your suggestions.

For guys coming from google. Here is our workaround:

put this in e.g. `ingegration/utils/loadLargeFixture.js`
```javascript
export default function loadLargeFixture(url, response, method = 'GET') {
  return cy.route({
    url,
    method,
    onRequest: xhr => {
      const originalOnLoad = xhr.xhr.onload;
      xhr.xhr.onload = function() {
        Object.defineProperty(this, 'response', {
          writable: true
        });
        this.response = response;
        originalOnLoad.apply(this, xhr);
      };
    }
  });
}
```

Import the json and the `loadLargeFixture` function in your test:

```javascript
import largeFixture from '../fixtures/veryLargeJson.json';
import loadLargeFixture from '../utils/loadLargeFixture';

describe('demo', () => {
  it('should work with large fixture', () => {
    cy.server();
    loadLargeFixture('/api/large', largeFixture).as('data');
    // do stuff
    cy.wait('@data')
    // do stuff
  });
});
```

**Comment by Kebie** [comment]
This error mixed with the [no support for fetch()](https://github.com/cypress-io/cypress/issues/95) ruined my afternoon, and made me think I was crazy. Please add note in docs where it is suggested to use cy.fixture aliases when it seems to not be great for large jsons. 

Just not using aliases like @tolicodes suggested fixed everything.

**Comment by saimonmoore** [comment]
I just ran into this today! @tolicodes method worked perfectly for me with a 1Mb fixture!

**Comment by cookiescrumbs** [comment]
@jennifer-shehane i'm getting the same ```CypressError: The network request for this XHR could not be made. Check your console for the reason.``` 

Looking at the solution from @brian-mann at the top; I'm confused about the solution and why what I'm doing won't work... 

```
options = {
    method: 'POST',
    status: 200,
    url: '/playlist/search'
}

cy.fixture('playlist/search/playlist-search.dto.mock.json').then((data) => {
    options['response'] = data;
    cy.route(options);
});
```

**Comment by AllanPinheiroDeLima** [comment]
@jennifer-shehane @brian-mann 
I'm using an nedb implementation for simulate database inside my tests, so I have many custom functions running in and out all the time.

I've found something interesting, as the response sent through the server is meant to be in the body, why the response is sitting in the headers? Is there any reason to do that ? Because of this, the header gets much, much bigger than it needs

Is this a behavior or something else ?

i've attached a print. 
![Captura de tela de 2019-04-05 14-51-47](https://user-images.githubusercontent.com/20716785/55646960-d8868300-57b2-11e9-9aa4-9480e741e6c0.png)


If it is not a behavior, can I try to fix it ? I really need this to work in order to continue testing well here

**Comment by nitzansan** [comment]
So I unfortunately and traumatically ran into this bug as well.
I was writing some new tests with new fixtures (programmatic fixtures and not static ones) and the cy.route + cy.wait failed with the `ERR_EMPTY_RESPONSE` error.

Unfortunately, I thought it was an issue on my side so I started to debug it and after rigorous testing found that the issue relates to big response size passed to `cy.route`.

As I mentioned before - Our fixtures are programmatic, which means that we don't have static json files holding fixtures and rather we have functions that we call and return as customizable fixtures. Therefore, @tolicodes solution doesn't seem to be relevant for us (unless I missed something about how to use cypress `fixtures`.
Additionally, I've tried using the `loadLargeFixture` function suggested by @ankri but it failed with XHR AssertionError.

1. Is there any way to workaround this issue with my functional fixtures?
2. I really think there should be an assertion internal in the `cy.route` implementation that throws a descriptive error when called with above-threshold size response.

**Comment by mgurov** [comment]
Similarly to @nitzansan none of the workarounds with xhr events worked for my programmatic data. 

What did work is a nasty hack of pre-creating a fixture programmatically: 

```
cy.writeFile('cypress/fixtures/my_test_response.json', bigReponseObject);
cy.route('/whatever', `fixture:my_test_response.json`);
```

Can work as long as unique file names used and the fixtures saved this way are `.gitignore`'ed.
