### ISSUE TITLE
Clicking on submit button doesn't open a new page - keeps loading forever

### ISSUE THREAD

**Issue by phoshing** [cypress-io/cypress#7641]
### Current behavior: 

I navigate to my login page and enter right credentials and click Submit button.

### Desired behavior: 

I should be navigated to the Home Page of my app. But it forever says 'loading' and my test constantly fails.

### Test code to reproduce

```js
cy.visit(Cypress.config("baseUrl"))
    .get('[id="username"]')
    .type(Cypress.config("username"))
    .get('[id="password"]')
    .type(Cypress.config("password"))
    .get('[id="submit"]')
    .click()
```

### Versions

Cypress = 3.1.0
OS = macOS Catalina version 10.15.4
Browser = Electron 59

**Comment by jennifer-shehane** [comment]
I see that you are using a **much older** version of Cypress. Please update to the [current version of Cypress](https://on.cypress.io/changelog). Your issue may have already been fixed.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example that we can run on our machines and we will consider reopening the issue.

**Comment by phoshing** [comment]
Ok, I will try updating to latest version of Cypress and check out.. The code that I gave above is all I am doing... nothing else... so clicking on 'Submit' button should ideally take me to HomePage..

Simple workflow:
On a login screen, enter credentials and click Submit... It should launch HomePage... That's it..

Instead it says 'loading' forever..

**Comment by jennifer-shehane** [comment]
@phoshing Yeah, it likely dependent on some things within the actual application under test. It's impossible to say why this would happen without a reproducible example including the application under test.
