### ISSUE TITLE
Cypress.environment variables / Login and Environment.

### ISSUE THREAD

**Issue by Ahmad-Baker** [cypress-io/cypress#7695]
Dears,

I have more than 3 environments to check my cypress test : (Production, Staging, Test, Dev) and I want to call a variable in the CI to get the variables for each environment.

So what is the perfect way to add these variables ?  In the `cypress.json` or in the `cypress.env.json` ? 

and where to add the cases ? 

Example : 

I need to define a variable to insert the variables dependence on parameter 

- if i insert a parameter "Production" , Insert the URL : "www.test.com"", Email :"test" , Passowrd: "123"
- if i insert a parameter "Dev" , Insert the URL : "staging.test.com", Email :"test2" , Passowrd: "321"
... and so on.

So where to put these cases, and how.

**Comment by jyotsana-khaparde** [comment]
Hi @Ahmad-Baker
You can create env.sh file and define the variables eg:
(export CYPRESS_LOGIN_EMAIL=test
export CYPRESS_LOGIN_PASSWORD=123)
And then can use these variables eg:
Cypress.env('LOGIN_EMAIL')
Cypress.env('LOGIN_PASSWORD')

**Comment by Ahmad-Baker** [comment]
hi @jyotsana-khaparde 
ok great, but i need more deep in this becuase i want to call the staging env as an example with the email and password, so i need just to define the URL,email,password as null, then call them in another function like this : 

  if (browser.params.Env == "prod") {
            browser.params.Link = "https://test.test.com";
            browser.params.Login.Email = "test@test.com";
            browser.params.Login.Password = "123";

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
