### ISSUE TITLE
Cypress loses control after switching baseUrl

### ISSUE THREAD

**Issue by dandv** [cypress-io/cypress#7697]
### Current behavior:

1. Run the test below. It should succeed
```js
context('navigation', () => {
  it('💥', () => {
    Cypress.config('baseUrl', 'https://cypress.io');
    cy.visit('/');
    cy.contains('test');
  });
});
```

2. Edit the Cypress.config line to `Cypress.config('baseUrl', 'https://cypress.io');`
3. Cypress should automatically detect the file change and re-run the test.

The problem is that the sidebar disappears and the test is in an undefined state. It should pass, because google.com does contain the word 'test' somewhere.

![image](https://user-images.githubusercontent.com/33569/84586343-a072cb00-adcd-11ea-96c9-7d2f15a11764.png)

### Desired behavior:

The google.com test run should pass as it does if it's run for the first time.

### Versions

Cypress 4.8.0, Chromium 83, Ubuntu 20.04.

**Comment by jennifer-shehane** [comment]
I'm not able to recreate the situation you're describing. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide **all** required configuration to recreate the issue including any values in `cypress.json`, plugin/support code, or env variables and we will consider reopening the issue.
