### ISSUE TITLE
Not able to see API calls on browser 

### ISSUE THREAD

**Issue by kalpanakapoor11** [cypress-io/cypress#7699]
### Desired behavior:
API calls tab should be there on left panel in browser

I clicked somewhere on the browser window while running a test and API call tab was gone, No I am not able to get it back

**Comment by jennifer-shehane** [comment]
You may be experiencing this issue https://github.com/cypress-io/cypress/issues/2132

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
