### ISSUE TITLE
WebSockets which hosted on AWS don't work

### ISSUE THREAD

**Issue by Alados** [cypress-io/cypress#7720]
### Current behavior:

I'm trying to mock WebSockets which hosted on AWS (AppSync). And for some reason, it doesn't work. I'm getting the error: **WebSocket connection to {url} failed**. Could you help? The same code work with a custom implementation of WebSockets. Is it some specific case for AppSync?

### Desired behavior:

WebSockets should be mocked and return message: "Hello, world!"

### Test code to reproduce

```js
let mockServer;

const fakeURL = 'wss://aws-ws-url.com';
cy.server();
class WebSocketMock extends WebSocket {
  constructor(url, protocols) {
    const urlWithoutToken = url.split('?')[0];
    super(urlWithoutToken, protocols);
  }
}

cy.on('window:before:load', (win) => {
  (cy.stub(win, 'WebSocket'))
    .as('WebSocket')
    .callsFake((url, protocols) => new WebSocketMock(url, protocols));

  if (mockServer) {
    mockServer.stop();
  }

  mockServer = new Server(fakeURL);

  mockServer.on('connection', (socket) => {
    console.log(socket);
    socket.send("Hello, world!");
  });
});

navigateToPage(`/`);
```

### Versions
"cypress": "3.6.0"
"mock-socket": "9.0.2"

**Comment by jennifer-shehane** [comment]
Please see this thread https://github.com/cypress-io/cypress/issues/2492 - also make sure you are using the latest version of Cypress. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
