### ISSUE TITLE
"command timeout exceeded" from visit()

### ISSUE THREAD

**Issue by stevenvachon** [cypress-io/cypress#7728]
### Current behavior:
In only `cypress run` mode, calling `visit()` for the _fifth_ time consistently yields:
```
Cypress command timeout of 4000ms exceeded.

Because this error occurred during a `after each hook we are skipping the remaining tests in the current suite: `E2E Tests`
```
There're two things that're odd about this message:
* it appears to be using `defaultCommandTimeout` instead of `pageLoadTimeout`; although, watching the video recording shows that it did wait the full 60000ms.
* this `visit()` is not within an `afterEach()`

### Desired behavior:
Please visit the damn page 😄 

### Test code to reproduce
Still trying to achieve this.

### Versions
Cypress 4.8.0
Node.js 12.18.0

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
