### ISSUE TITLE
Cypress / Upload files 

### ISSUE THREAD

**Issue by Ahmad-Baker** [cypress-io/cypress#7767]
Dears,

When i try to upload a pdf/png/jpg file via cypress, the file uploaded successfully,
But when i open the file from my project, i found that the file looks like damaged or cann't opened 
for pdf, when open the file it always required a password 
for pictures, error message shown : "It looks like we doesn't support this file format.

Please help me with this : 

This is what i use 
![cypress1](https://user-images.githubusercontent.com/42723661/85222809-bdf3f600-b3c6-11ea-9d24-5b4c8f9e09c1.PNG)
![image](https://user-images.githubusercontent.com/42723661/85222817-cc421200-b3c6-11ea-88c4-9c0b6bd9688d.png)

**Comment by jennifer-shehane** [comment]
Please provide all code required to run the example given. We do not have access in this case to the `.attachFile()` command.

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
