### ISSUE TITLE
Cypress seems not able to do cy.request during chaining

### ISSUE THREAD

**Issue by moonformeli** [cypress-io/cypress#7781]
### Current behavior:
`cy.request()` doesn't work if it's in the chaining.
But it works if it's run at the very beginning of the test.

### Desired behavior:
I want to check API results after clicking buttons

### Test code to reproduce
```ts
// This doesn't work
// Cypress throws a timeout error
cy
  .get('button[data-test=myBtn]')
  .click()
  .request({
    method: 'get',
    headers: { ... },
    url: '...'  
  });
```

However,
```ts
// This works
cy.request({
    method: 'get',
    headers: { ... },
    url: '...'  
  });

cy
  .get('button[data-test=myBtn]')
  .click();
```

### Versions
`^4.8.0`

I want `request` to work after clicking the button without giving me any errors. How can I do this?

**Comment by jennifer-shehane** [comment]
>cy.request() doesn't work if it's in the chaining.

Can you be more specific about what 'doesn't work' means here? Are you seeing an error? Can you provide that?

Did you try the below. `request` is meant to be chained off of `cy` generally, but this shouldn't break `cy.request()`

```js
cy
  .get('button[data-test=myBtn]')
  .click()
 cy.request({
    method: 'get',
    headers: { ... },
    url: '...'  
  });
```

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
