### ISSUE TITLE
PDF reports are not getting opened in Cypress Test Runner

### ISSUE THREAD

**Issue by automationJatinder** [cypress-io/cypress#7797]
My Web application generates some PDF reports on demand and when I try to open the report using the URL in cypress test runner using visit method, then Cypress generates the attached error.

![image](https://user-images.githubusercontent.com/44338967/85550768-e84fe880-b63e-11ea-90bc-27e19d1b7a54.png)

I tried to open the link by changing attribute of existing anchor tag (which open webpage in existing window) but the report is getting opened in a pop up. Then I added the attribute of target="_self" but still the report is getting opened in a pop up.

Is there a way to open PDF report in Cypress Test runner?

**Comment by jennifer-shehane** [comment]
Cypress is not currently able to visit pages that are not of type `html/text` as explained in this issue: https://github.com/cypress-io/cypress/issues/1551

If you believe this issue is outside of the issue described above, we'll need a reproducible example in order to investigate. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
