### ISSUE TITLE
Constant variable not working

### ISSUE THREAD

**Issue by trips11** [cypress-io/cypress#7804]
I have declared `myAppName` as constant to be used in multiple it blocks. But the value changes in it blocks.
Is there a way to declare a constant? 

```js
const myAppName = "Cypress"+Cypress.moment().format('MMDDYYYY_HHMMSS')

describe('Temp test cases',function()
{
    it('TC01',function(){
        cy.log(myAppName)
    })
    it('TC02',function(){
        cy.log(myAppName)
    })
})
```

**Comment by trips11** [comment]
Just realized it is happening only if you have beforeEach in your script. If you remove that then it works fine

**Comment by jennifer-shehane** [comment]
@trips11 Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

The code I'm running passes:

```js
const myAppName = "Cypress" + Cypress.moment().format('MMDDYYYY_HHMMSS')

describe('Temp test cases', function () {
  beforeEach(() => {
    
  })
  it('TC01', function () {
    expect(myAppName).to.not.be.undefined
  })
  it('TC02', function () {
    expect(myAppName).to.not.be.undefined
  })
})
``` 

<img width="543" alt="Screen Shot 2020-06-26 at 3 47 34 PM" src="https://user-images.githubusercontent.com/1271364/85841620-5f62b980-b7c4-11ea-8dbb-deafb74830df.png">


Please comment in this issue with a reproducible example and we will consider reopening the issue.
