### ISSUE TITLE
Unexpected token '<'

### ISSUE THREAD

**Issue by Berkmann18** [cypress-io/cypress#7837]
### Current behaviour:

![cypress-4 8-hsdn](https://user-images.githubusercontent.com/8260834/85955757-cd4fe200-b978-11ea-9fb3-5aecc4e2319e.png)

### Desired behaviour:

The test suites runs like it used to be.

### Test code to reproduce

Please see: https://github.com/misterpeddy/hands-down/tree/ghci-up

### Versions

Cypress: 4.8.0
OS: ArchLinux 5.7.4-arch1-1
Browser (on Cypress): Chrome 83

**Comment by jennifer-shehane** [comment]
>The test suites runs like it used to be.

You mention the test used to pass? What has changed since the test was passing? The Cypress version? Your application code? This will be the key to narrowing down why your test is now failing. 

This error is being thrown from your application. I see there is an application console.warn being logged, perhaps it is related.

<img width="467" alt="Screen Shot 2020-06-29 at 3 13 48 PM" src="https://user-images.githubusercontent.com/1271364/85992618-2708e880-ba1b-11ea-9000-1b043698dd94.png">


You can ignore the error by putting the following in your code:

```js
Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false;
});
```

**Comment by Berkmann18** [comment]
> You mention the test used to pass? [...] Your application code? This will be the key to narrowing down why your test is now failing.

Yes, they used to (except for the video stream which seems to never work, possibly due to the inconsistent WebGL support, cf. https://github.com/cypress-io/cypress/issues/2704#issuecomment-610020455).

> What has changed since the test was passing?

Updating the `script` sources to [use the WebGL backend of TFjs](https://github.com/misterpeddy/hands-down/pull/67/files) (that was taken out of the core library) using `cypress@4.3.0` and again after [upgrading to `cypress@4.8.0`](https://github.com/misterpeddy/hands-down/pull/70/files) with no changes in the test suite.

> The Cypress version?

This occurs on both Cypress 4.3.0 and 4.8.0.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
