### ISSUE TITLE
Fetch through webworker are not handled by cypress resulting in wait() timeout

### ISSUE THREAD

**Issue by gamegee** [cypress-io/cypress#7840]
### Current behavior:
The `wait()` command will not be triggered if a fetch is done through webworkers.
Because the request is never handled, the test will fail because of timeout.

### Desired behavior:
Trigger `wait` when a fetch is done through webworkers, indeed in an other thread.

### Test code to reproduce
If the browser support webworkers I use specific function `fetchResourceWithWorker`

```tsx
import { fetchResource } from './api.fetch'
import { fetchResourceWithWorker } from './api.worker'

const fetchFn = window.Worker ? fetchResourceWithWorker : fetchResource

/**
 * Calls the given URL and returns the json object
 */
export const call = (...args) => {
  const [path, options] = args
  return fetchFn(path, { ...options })
}
```

My only alternative for now is to do something like this:
```tsx
const fetchFn = window.Worker || process.env.CI === 'true' ? fetchResourceWithWorker : fetchResource
```

It is not really useful to provide cypress specs code sample, because all my specs using `wait()` are failing since webworkers are used in the codebase. 

### Versions
Chrome: Version 83.0.4103.116
MacOS: 10.15.5
Cypress: 4.3.0

**Comment by kamranayub** [comment]
I am pretty certain this isn't possible yet, because Service Workers and Web Workers use different scopes. Cypress can indeed stub/spy on `fetch` with `experimentalFetchPolyfill: true` in `4.9.0` but it only works on the Window scope, where it will force the use of XHR. Worker scopes will continue to use `fetch`, so you can't wait/spy/stub those calls.

In my app, I also workaround it by disabling service worker fetching using routing (e.g. `/path?sw_ignore`). I think you'll have to workaround it like you're doing until stubbing/spying on fetch is enabled for worker scopes.

Related to #687 I think.

**Comment by nicholaschiang** [comment]
I'm experiencing the same thing using the new `cy.intercept` command. I have a service worker that intercepts all requests and adds authentication headers; Cypress seems unable to detect them with the new `cy.intercept` command when they worked fine with `cy.route`. I'm not sure why.

**Comment by cwirz** [comment]
I have the same issue as @nicholaschiang. For me the `cy.route` function can actually intercept these service worker handled requests.
<img width="517" alt="Screenshot 2022-03-07 at 21 02 06" src="https://user-images.githubusercontent.com/1812094/157109061-ec574344-3a60-4a8e-8f7c-6b2cc9eb174e.png">
 
 I can also see that if you use a `cy.intercept('*')` to intercept all requests they are also not captured but everything else is.
