### ISSUE TITLE
Failed to execute ‘open’ on ‘Document’ : Can only call open() on same-origin documents

### ISSUE THREAD

**Issue by SuryaBansode** [cypress-io/cypress#7854]
This is question:

### Current behavior:
I am trying to login to our application website. I am going through 3 screens(customer, password, token) and on token page I am doing final click. Once I click, I go to dashboard of our page and if I try to click on any object of the page, it gives me above mentioned error.
What I see is, once I click on final page and before going to dashboard, it changes navigating url. 

### Desired behavior:
I should be able to click on objects on the dashboard.

**Comment by SuryaBansode** [comment]
Url changes from
https://login-and-registration.xxx.yyy.z/
To
https://Internet-banking.ddd.yyyy.aaaa.ee
One more thing, I am not changing these URLs through Cy.visit, it’s automatically getting changed by application. May be redirect URLs.. please help me this issue. It’s blocking my testing. Appreciate your response. Thanks, Surya

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by SuryaBansode** [comment]
Thanks for your reply. Could you please confirm me cause for this? And if any workaround to resolve this issue?
