### ISSUE TITLE
Cypress fails to log an error due to an exception in cypress_runner splitStack function (Cannot read property 'split' of undefined)

### ISSUE THREAD

**Issue by ajewers** [cypress-io/cypress#7870]
### Current behavior:
Cypress encounters an error or failure whilst running the test, but is unable to log this error in the run log due to an exception occurring in the `cypress_runner.js` code whilst the stack trace of the original error is being prepared.

The exception is `TypeError: Cannot read property 'split' of undefined`, and occurs on the first line of the `splitStack(stack)` function in `cypress_runner.js`.

Screenshot:
![cypress!UNITO-UNDERSCORE!splitStack!UNITO-UNDERSCORE!exception](https://user-images.githubusercontent.com/6303092/86342057-ff01cb00-bc4e-11ea-9eb0-1e7b8e2811f9.png)

This is happening whilst attempting to screenshot a QR code and then parse the screenshot through a QR library.

This seems to involve a race condition in some way, as the issue occurs ~50% of the time in my original code. In the minimal example linked below it seems to happen every time.

### Desired behavior:
Cypress correctly logs the original error in the run log so that it can be debugged.

### Test code to reproduce
Here is a fork of cypress-tiny-test with a minimal example which reliably reproduces the issue: https://github.com/ajewers/cypress-test-tiny

* Run `npm run cypress:open`
* Select the 'spec.js' file
* Observe the error in the run log as in the screenshot above

Edit: Adding the key section of code for clarity:

```javascript
describe('Screenshotting and parsing a QR code', () => {
    it('works', () => {
      // Wikipedia page on QR codes
      cy.visit('https://en.wikipedia.org/wiki/QR_code');

      // Screenshot one of the larger QR codes and attempt to parse
      cy.get(':nth-child(5) > [style="width: 255px"] > .thumb')
        .screenshot('qr-screenshot', {
          onAfterScreenshot($el, props) {
            qrImagePath = props.path;
          }
        })
        .then(() => cy.readFile(qrImagePath, 'base64'))
        .then(qrBase64 => Buffer.from(qrBase64, 'base64'))
        .then(imageBuffer => Jimp.read(imageBuffer))
        .then(qrImg => decodeQR(qrImg))
        .then(value => cy.log(value.result));
    });
});
```

### Versions
Observed on both Cypress 4.8.0 and 4.9.0, running on Linux for Chrome 83.

┆Issue is synchronized with this [Jira Bug](https://cypress-io.atlassian.net/browse/TR-91) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
This is happening because the error being thrown is not a proper Error object, but a string. Can reproduce with the following code:

```js
it('Cannot read "split" of undefined', () => {
  cy.then(() => {
    throw 'Error'
  })
})
```

<img width="553" alt="Screen Shot 2020-07-06 at 11 44 33 AM" src="https://user-images.githubusercontent.com/1271364/86558375-2b835300-bf7f-11ea-862a-149c585e79ad.png">


Prior to 4.6, this error used to show indicating you should throw an Error, not a string. The 'cannot read split of undefined' is definitely not what we should be doing here. 

<img width="553" alt="Screen Shot 2020-07-06 at 11 44 33 AM" src="https://user-images.githubusercontent.com/1271364/86558464-62f1ff80-bf7f-11ea-82fb-86e5b25d198e.png">


@ajewers You can fix this in your code for now by changing your `decodeQR` function to throw an Error. This would throw the actual error you are expecting and fail the test. 

```js
function decodeQR(img) {
  return new Promise((resolve, reject) => {
    qr.callback = (err, v) => err != null ? reject(new Error(err)) : resolve(v);
    qr.decode(img.bitmap);
  });
}
```

<img width="550" alt="Screen Shot 2020-07-06 at 11 55 41 AM" src="https://user-images.githubusercontent.com/1271364/86558544-ab112200-bf7f-11ea-843d-7901f6232c41.png">

**Comment by jrr** [comment]
To anyone else looking to purge their code bases of errors that can provoke this issue, check out the ESLint's `no-throw-literal`: https://eslint.org/docs/rules/no-throw-literal
