### ISSUE TITLE
4.8.0 -> 4.9.0: Windows based tests no longer working, linux working fine

### ISSUE THREAD

**Issue by mduft** [cypress-io/cypress#7876]
### Current behavior:

In 4.8.0 Windows, Linux and Mac UI tests are working fine. After the update to 4.9.0 only the Windows test reproducibly fail, seemingly because of timeouts, slowness, etc.

When run locally on my desktop windows, headless or headed, things do work (with 4.9.0), but slower than usual, and I have hell of a machine, much more powerfull than the cloud VMs...

### Desired behavior:

4.9.0 cypress should be able to run the Windows based tests successfully.

### Test code to reproduce

Example of run with 4.9.0: https://dashboard.cypress.io/projects/k88zyw/runs/2074/specs
Example of run with 4.8.0 (after downgrade): https://dashboard.cypress.io/projects/k88zyw/runs/2080/specs

As i said: Linux and Mac seem to work normally, although Mac runs are currently ignored for our project as we do not have official support yet...

### Versions

4.9.0, Electron, Windows (Github Actions).

**Comment by jennifer-shehane** [comment]
In both of the runs (4.8 and 4.9), I can see that the video recording is 'freezing' pretty frequently. In 4.8, the tests passed more frequently, but the freezing is still there. 

In previous cases of frozen frames in video recordings, we've often found that this is due to an insufficient amount of CPU provided to the machine during cypress runs. When running Cypress on a machine, it has to use resources to load Cypress, the Chrome browser, and also do video recording. This can use a fair amount of CPU and if there is not enough on the machine recording, it can result in these types of locked up frames. There's a longer thread of investigation here if you're interested: https://github.com/cypress-io/cypress/issues/4722, but I would suggest trying to increase the CPU available on the machine to see if this clears up the issue.

You'll likely want to [log your memory and CPU usage](https://docs.cypress.io/guides/references/troubleshooting.html#Log-memory-and-CPU-usage), this will show some more information on the CPU usage.

**Comment by mduft** [comment]
Thanks for the info. Unfortunately we're on the free GitHub plan, using GitHub Actions - so we cannot allocate more resources, even if we want to :( I'm pretty sure you're correct and CPU is at least one of the bottlenecks here. I guess I'll have to find a way to run the tests successfully *even though* CPU is a rare resource... And it does work pretty reliably with 4.8.0 xD
