### ISSUE TITLE
Cypress - Chrome dev tools profiling stats.

### ISSUE THREAD

**Issue by rsudarson** [cypress-io/cypress#7894]
Is there a way to get chrome dev tools performance profiling stats from cypress tests?

**Comment by jennifer-shehane** [comment]
By default Chrome quantizes the `window.performance.memory` and updates the value only every 20 seconds for scripts served from a different origin as the webpage. This is a security protection.

You'll need to pass a `--enable-precise-memory-info` flag to disable this behavior and values will be pulled more frequently.

You can pass this flag through your `plugins/index.js` file like shown below:

```js
module.exports = (on, config) => {
  on('before:browser:launch', (browser, launchOptions) => {
    launchOptions.args.push('--enable-precise-memory-info')

    return launchOptions
  });
}
```

And then log these performance values in your spec file like shown below.

```js
it("works", () => {
  cy.visit("https://www.cypress.io")
  cy.window().then((window) => {
    console.log(window.performance.memory.totalJSHeapSize)
    console.log(window.performance.memory.usedJSHeapSize)
    console.log(window.performance.memory.jsHeapSizeLimit)
  })
})
```

The `window.performance.memory` will display memory used from the Cypress application as well as the application under test. 

---

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by rsudarson** [comment]
@jennifer-shehane - How do we get the chrome performance profiler flame chart for a set of actions from cypress tests.

**Comment by jennifer-shehane** [comment]
Could you explain exactly the information you're trying to gather? 

You can access the Chrome DevTools Protocol like below if you need something more specific. 

```js
Cypress.automation("remote:debugger:protocol", {

})
```

**Comment by rsudarson** [comment]
I like to generate the flame chart during cypress tests execution for client side js profiling.

![image](https://user-images.githubusercontent.com/10207067/87158807-f27c1300-c2dd-11ea-8196-a0a178dd3e03.png)

**Comment by jennifer-shehane** [comment]
@rsudarson If this is available through the Chrome DevTools Protocol, then it may be possible. You'll have to see how to get this flame chart out of Chrome in general.
