### ISSUE TITLE
how to write case by ts

### ISSUE THREAD

**Issue by ycwdaaaa** [cypress-io/cypress#7895]
I have install some cypress plugin,  but I have to write some code in `index.d.ts`. like blow:

```ts
declare namespace Cypress {
    interface Chainable<Subject> {
        /**
         * Get one or more DOM elements by an XPath selector.
         * **Note:** you can test XPath expressions from DevTools console using $x(...) function, for example $x('//div') to find all divs.
         * @see https://github.com/cypress-io/cypress-xpath
         * @example
         * cy.xpath(`//ul[@class="todo-list"]//li`)
         *   .should('have.length', 3)
         */
        xpath<E extends Node = HTMLElement>(selector: string, options?: Partial<Loggable & Timeoutable>): Chainable<JQuery<E>>
    }
}
```

or in webstorm will thow errors.   the `tsconfig.json` is below.

```json
{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": ["es5", "dom"]
//    "types": ["cypress"]
  },
  "include": [
    "**/*.ts"
  ]
}
```

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
