### ISSUE TITLE
previous visited page is used for `cy.*` commands

### ISSUE THREAD

**Issue by ismail-codinglab** [cypress-io/cypress#7896]
### Current behavior:

It assumes it's on the previous `visit()`ed page `login/` instead of `jobs/`
![image](https://user-images.githubusercontent.com/48755937/86645186-77b1b000-bfde-11ea-9de2-6b8d37006f2e.png)
![image](https://user-images.githubusercontent.com/48755937/86645061-5b157800-bfde-11ea-8aae-521e162f69db.png)

The code I use to get the exposed angular services through `visit`ing `login/`:
![image](https://user-images.githubusercontent.com/48755937/86645394-a760b800-bfde-11ea-90db-944bd0cb96ad.png)

### Desired behavior:

I want every `cy.*` to do assertions on the last visited page, meaning, working sequentially.

### Versions

v4.9.0

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example that we can run and we will consider reopening the issue.
