### ISSUE TITLE
how to break for in cy.command

### ISSUE THREAD

**Issue by ycwdaaaa** [cypress-io/cypress#7922]
as blow: when the status changed to 1 or 2 ,I want to end the for

![image](https://user-images.githubusercontent.com/18463029/86939669-70240f80-c174-11ea-9a4d-69484e41350c.png)

**Comment by jennifer-shehane** [comment]
You can't break out of a for loop within a Promise (with is what the Cypress `.then()` is). You'll likely want to rewrite your code to recursively call a function and not call the function when your condition is met. 

```js
const queryDb = (i) => {
  if (i>= 100) {
    return
  }

  cy.log(i)
  cy.task('log', i)
    .then(() => {
      if (i === 3) {
        return i
      } else {
        queryDb(i + 1)
      }
    })
}

it('test', () => {
  queryDb(0)
})
```

<img width="649" alt="Screen Shot 2020-07-09 at 10 49 58 AM" src="https://user-images.githubusercontent.com/1271364/86996541-f4f14680-c1d1-11ea-8e01-fd88ec3c02a1.png">

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
