### ISSUE TITLE
Missing class names in multi select

### ISSUE THREAD

**Issue by clmz** [cypress-io/cypress#7944]
Hello!
If I set a custom classname for the react-select component like this:
```html
<ReactSelect 
...
className='react-select'>
```
the rendered component has divs with classnames like `react-select__menu` etc.

The element tree of a normal react-select:
![image](https://user-images.githubusercontent.com/47241471/87147609-3145a500-c2ad-11ea-9130-0d3a8aad051f.png)

if I use the MultiSelect via prop `isMulti`, all these class names are missing. Only the parent div has a class named `react-select`, but there is for example no `react-select__menu` class for one of the child divs - there's a whitespace in the classname prop where this name should be.
The element tree of a multi react-select:
![image](https://user-images.githubusercontent.com/47241471/87147684-56d2ae80-c2ad-11ea-9326-1bc308c0e8f9.png)

For me, the class names are very important for cypress tests, because I have no other way to access the correct div for testing.

**Comment by jennifer-shehane** [comment]
I don't see how this is an issue with Cypress, but rather an issue with your react components + your strategy on testing. Regardless of the testing you use, you will need to target elements in a unique way. If you cannot rely on the class names being consistent, I would suggest using some other means to target elements in Cypress (such as `data-test` or `data-cy` attributes. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
