### ISSUE TITLE
Vue data： how can I chang the vue data in cypress test

### ISSUE THREAD

**Issue by regnoh** [cypress-io/cypress#7969]
### Current behavior:

Change vuex store in integration/xxx.js or  change  xx.vue directly when testing

### Desired behavior:

I need to change vue data (not vuex store) when testing in integration/xxx.js

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
