### ISSUE TITLE
Conditional when test is run alone

### ISSUE THREAD

**Issue by Hendrikson** [cypress-io/cypress#7973]
Is there any way to identify whether the current test is being run individually or in a group?

I have some tests that would normally be run in order, but I'd also like to be able to run them individually and implement some logic in the before() and after() statements to cope for this.

**Comment by Hendrikson** [comment]
To clarify, by test I mean separate spec files, not tests in a file.

**Comment by jennifer-shehane** [comment]
I'm not sure exactly what you're asking for here, but you can get the name of the currently running spec with `Cypress.spec` https://on.cypress.io/spec

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
