### ISSUE TITLE
Cypress Set HTTP request headers

### ISSUE THREAD

**Issue by rsudarson** [cypress-io/cypress#7993]
When a url is visited through cy.visit(url), application makes REST API requests. I need to send a custom header to the service url, otherwise service will fail and application wont show the data.

Can you please suggest how to set the header for all the REST API requests invoked from the application? 

cc @bahmutov @jennifer-shehane

**Comment by jennifer-shehane** [comment]
You can set headers for stubbed routes through [`cy.route()` options](https://on.cypress.io/route#Arguments). You'll need to stub all of the routes, since without stubbing - the requests will go through as is. We're working on improvements to this, so that you can 'partially' stub routes for instance. https://github.com/cypress-io/cypress/pull/4176

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
