### ISSUE TITLE
remote-debugging-port cannot be set using ELECTRON_EXTRA_LAUNCH_ARGS

### ISSUE THREAD

**Issue by dg-nvm** [cypress-io/cypress#7994]
### Current behavior:
When `set ELECTRON_EXTRA_LAUNCH_ARGS=--remote-debugging-port 40500` is used then nothing happens

**BUT**

When I change environment.js to use `appendSwitch` instead, it works:

`app.commandLine.appendSwitch('remote-debugging-port', '40500')`

### Desired behavior:
I can set option via environment variable

### Test code to reproduce
```
set ELECTRON_EXTRA_LAUNCH_ARGS=--remote-debugging-port 40500
cypress open
```

Cypress should output:
`DevTools listening on ws://127.0.0.1:40500/devtools/browser/<UUID>`

### Versions
Windows 10, Cypress 4.10.0, using builtin Electron in Headed mode

┆Issue is synchronized with this [Jira Story](https://cypress-io.atlassian.net/browse/TR-116) by [Unito](https://www.unito.io/learn-more)

**Comment by jennifer-shehane** [comment]
Yeah, I don't think we are handling key value pairs correctly in our `ELECTRON_EXTRA_LAUNCH_ARGS` here. Electron says we need to call the argument like `app.commandLine.appendSwitch('remote-debugging-port', '8315')`, but I don't see us actually pulling out the value from the key in order to pass these as 2 arguments to appendSwitch. https://www.electronjs.org/docs/api/command-line-switches

The code that handles this is here: https://github.com/cypress-io/cypress/blob/develop/packages/server/lib/environment.js#L71:L71

The test shows it's being called as `--remote-debugging-port=40500`.

I don't think that `appendArgument` actually supports key value pairs, the Electron docs even suggest using `appendSwitch` here instead. https://www.electronjs.org/docs/api/command-line#commandlineappendargumentvalue

**Comment by jennifer-shehane** [comment]
Opened a PR here https://github.com/cypress-io/cypress/pull/8001

**Comment by dg-nvm** [comment]
@jennifer-shehane thank you Jennifer for fast reaction. These two differs greatly internally and also they mention added cmdline will be added before switches.
