### ISSUE TITLE
My page lost CSS design after logging.

### ISSUE THREAD

**Issue by dpecimuth** [cypress-io/cypress#8004]
Hello, 
I try to running some tests for webpage which looks like
<img width="486" alt="Screenshot_1" src="https://user-images.githubusercontent.com/67587678/87669622-9d714e80-c76e-11ea-913c-d48c03f109df.png">
but in cypress looks like page lost the CSS design.
<img width="245" alt="Screenshot_4" src="https://user-images.githubusercontent.com/67587678/87669630-a104d580-c76e-11ea-862b-aff19e36613e.png">

Could you help me with this issue?
Thanks for your advice.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

I can't say why the css is not loading without being able to run an example. Can you open the DevTools? Is there a request for a resource in the network tab that's not being completed in Cypress? 

Please comment in this issue with a reproducible example and more info and we will consider reopening the issue.
