### ISSUE TITLE
How to rerun specific API till API status modify

### ISSUE THREAD

**Issue by Gyetukuri** [cypress-io/cypress#8014]
How to run a spcific API in a loop specific object convert from  A to B

Ex: specific order in pending state i need to run that specific api to till to change into Completed status

some times it will take 2 min some times it will take 5 min

Max time i need to for 5min, till 5 min every 5sec i  need to call status API and need to check whether status got updated to pending to completed

If it once change to completed or 5min over then i need to come out from the loop and make test case fail

**Comment by jennifer-shehane** [comment]
This is a gist I made before, involving 'retrying' a request until some condition is met. You could likely modify this idea to meet the condition you're wanting. But the idea is to call a recursive function to request until the conditions are met. https://gist.github.com/jennifer-shehane/35847772128616ff477e10de19299040

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by Gyetukuri** [comment]
Hi Jennifer, thanks for the reply. I need to break the loop after sentence gets true or else after 5min i need to end the looping but in your code no where have break the loop could you please help me on this

**Comment by jennifer-shehane** [comment]
You can check out our [community chat](https://on.cypress.io/chat) for help on writing tests. Our team does not have the resources to dedicate one on one support for this unfortunately.
