### ISSUE TITLE
Testing font-face

### ISSUE THREAD

**Issue by Hamidrezana** [cypress-io/cypress#8020]
I want to test font face added to css.

How can I do that?

For now I can't test with snapshot.

Is there any solution for this?

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
