### ISSUE TITLE
Cypress doesn't work with "While loop"

### ISSUE THREAD

**Issue by truyenkv** [cypress-io/cypress#8022]
Hello, This is my TC:
```js
it('Verify number of item on a Page', () => {
  const home = new HomePage()
  cy.searchwithcondition('Books', 'apple')
  home.englishCheckBox('yes') //input yes for check condion
  home.checkProductInList(16) //have 16 item on a page
  // cy.get('.a-last').prev().invoke('text')
  while (cy.get('.a-selected').invoke('text').should('not.equal', cy.get('.a-last').prev().invoke('text'))) {
    cy.get('.a-last').click()
  }
})
```
When I open the Cypress and run with this test case, The Cypress can't connect with any browser. It looks like sleep well 
But when I remove the while loop. That mean my code :
```js
it('Verify number of item on a Page', () => {
  const home = new HomePage()
  cy.searchwithcondition('Books', 'apple')
  home.englishCheckBox('yes') //input yes for check condion
  home.checkProductInList(16) //have 16 item on a page
})
```
And open Cypress again, The test case run normally.
Can you give me some solutions for resolve it? 
Thank alot!

**Comment by jennifer-shehane** [comment]
I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [Commands Are Promises](https://on.cypress.io/introduction-to-cypress#Commands-Are-Promises). 

You are expecting a single return value from the cypress chain, but Cypress chains return a Promise. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
