### ISSUE TITLE
Tests failed without UI tests runner

### ISSUE THREAD

**Issue by danimin7** [cypress-io/cypress#8024]
### Current behavior:

When using Dashboard and run tests without UI tests runner - tests with downloading and parsing files or uploading files are failed, but when running them with the UI tests runner the tests are succeeding.
Seems like it's failed to download the files, I couldn't even find the downloaded files in the downloads directory after the tests failed.

### Desired behavior:

Running tests without the UI tests runner will succeed as it's succeed when it runs with the UI tests runner

### Test code to reproduce

The error is:
> Error: ENOENT: no such file or directory, stat '/Users/userName/Downloads/fileName.tsv'

### Versions

Using macOS Catalina Version 10.15.5.
Cypress Version 4.5.0
Chrome Version 83.0.4103.97

**Comment by jennifer-shehane** [comment]
I would suggest following on recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
