### ISSUE TITLE
How can I push item to array list

### ISSUE THREAD

**Issue by truyenkv** [cypress-io/cypress#8034]
Sorry if it is a basic case
I can't push the item to array list
This is code to get the DateTime of list production to sorting
```js
 dateTimeProduct () {
  var date = []
  cy.get('.a-size-base.a-color-secondary.a-text-normal')
  .each(($el) => {
    date.push($el.text()) 
    cy.log($el.text())
  })
  cy.log(date)
}
```
I can see the exactly date-time with "cy.log($el.text())". But I can't store them date. With  "cy.log(date)" I just see Array[16].
So how can I store/explore the date to sorting. Please help!!!!

**Comment by jennifer-shehane** [comment]
The code listed works as I would expect it, with the array of items printing to `cy.log()`. 

`spec.js`

```js
 it('test', () => {
   cy.visit('index.html')
    var date = []
    cy.get('div')
    .each(($el) => {
      date.push($el.text()) 
      cy.log($el.text())
    })
    cy.log(date)
 })
```

```html
<html>
<body>
  <div>Foo</div>
  <div>Bar</div>
  <div>Baz</div>
</body>
</html>
```

<img width="322" alt="Screen Shot 2020-07-21 at 11 27 06 AM" src="https://user-images.githubusercontent.com/1271364/88014567-3fb17d80-cb45-11ea-9198-40b564926bae.png">


<img width="322" alt="Screen Shot 2020-07-21 at 11 27 06 AM" src="https://user-images.githubusercontent.com/1271364/88014517-214b8200-cb45-11ea-8969-00e2ece2cb54.png">


Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by vivekbachu** [comment]
Hi @jennifer-shehane ,

I am facing the same issue mentioned by @truyenkv .

It seems like my elements text is pushed to array but never printed to log, below is the code snippet i used. 

I still see cy.log for my array prints ```Array[4]```, here 4 is my total elements count in the tbody. Can someone help me to solve this. Thank you !

```
it('My Test Case', function()
    { 
      var tableelements = []
      cy.iframe().xpath("//tbody[@id='table-body']").find("tr").find("td").each(($elm)=>{
       tableelements.push($elm.text())
        })
      cy.log(tableelements)

})
```

**Comment by nameetjambla** [comment]
Hi @jennifer-shehane 

I am also Facing the same issue  output should be [1,2,3,4,5,6,3,94,6,65]

Please help 

        let idArray = []
        var bounce= cy.get('tr td:nth-child(3)').each(($el,list,$array)=>{
            idArray.push($el.text())
            cy.log($el.text())
              
            })
            cy.log('----',idArray)



![image_2023_01_12T08_06_51_843Z](https://user-images.githubusercontent.com/79189939/212011959-d8bd7a69-90a3-4639-bb54-b9ceacc66f78.png)

**Comment by kankush213** [comment]
I am also facing same issue.. Can you pls help .. 

@jennifer-shehane

**Comment by nagash77** [comment]
@kankush213 Please open a new issue with a reproducible example and we will be happy to investigate.
