### ISSUE TITLE
Month date and year (date picker doubt)

### ISSUE THREAD

**Issue by suriyabambeeq** [cypress-io/cypress#8036]
[https://gooru.org/sig-up](https://gooru.org/sig-up)

Hii,

I have doubt in cypress in date of birth code in dropdown value .i have mentioned above link .please give me solution .

@jennifer-shehane 

![DoubT](https://user-images.githubusercontent.com/67900566/87940828-d6cff400-cab7-11ea-8862-5460da6c3ca5.png)

**Comment by jennifer-shehane** [comment]
@suriyabambeeq Unfortunately our team does not have the resources to give one on one support through GitHub issues, writing tests for your specific situation. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by suriyabambeeq** [comment]
hi Cypress-Io/Cypress,

cypress google login in cypress not working as mentioned documentation ,
can you send me video tutorial


Thanks & Regards
M.SURIYA
