### ISSUE TITLE
The way to wait for graphql response.

### ISSUE THREAD

**Issue by baeharam** [cypress-io/cypress#8059]
According to docs, there is no way to wait for `fetch` request. And I'm using Apollo client for the graphql implementation which uses `fetch` internal. Then, is there no way to wait for this response? Do I have to set timeout enough? How can I manage this? This is question, but there was no answer when I asked to gitter channel. Thanks

**Comment by jennifer-shehane** [comment]
You may find this thread helpful: https://github.com/cypress-io/cypress-documentation/issues/122

Also there is an experimental config to polyfill fetch explained here: https://github.com/cypress-io/cypress/issues/687#issuecomment-651006308

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.
