### ISSUE TITLE
exception: Whoops, there is no test to run when setting `window.top.location`

### ISSUE THREAD

**Issue by mingyixu** [cypress-io/cypress#8063]
when run visit https://weex.kaola.com/activity/pages/cosmetic.html?spm=a2v0d.b27995055.icon.1, it's crash, Whoops, there is no test to run.

case: 

```js      
cy.viewport(1024, 768);
cy.visit('https://m.kaola.com/');

cy.wait(1000);
cy.get('div.closeBtn').click();

cy.wait(1000);
cy.get('a:nth-child(1) > img.icon').click();

cy.visit('https://weex.kaola.com/activity/pages/cosmetic.html?spm=a2v0d.b27995055.icon.1');
```

### Versions

cypress: 4.10.0
system: mac
browser: chrome 83

**Comment by jennifer-shehane** [comment]
I can recreate this with the following code:

```js
it('test', () => {
  cy.visit('https://m.kaola.com/')
  cy.get('div.closeBtn', { timeout: 5000 }).click()
  cy.get('a:nth-child(1) > img.icon', { timeout: 5000 }).click()
})
```

<img width="1139" alt="Screen Shot 2020-07-23 at 2 11 26 PM" src="https://user-images.githubusercontent.com/1271364/88262554-6d85f600-ccee-11ea-8986-06a37cdd07ae.png">

This issue is occurring because you're setting `window.top.location.href` to the new location. Since Cypress runs within an iframe, this will set the main Cypress url to reroute to the new url, so that we can no longer execute the tests. 

<img width="803" alt="Screen Shot 2020-07-23 at 2 15 01 PM" src="https://user-images.githubusercontent.com/1271364/88263475-1c770180-ccf0-11ea-835c-2dd06cb67d69.png">


Setting `experimentalSourceRewriting: true` causes the page to no longer load.

The only way to work around this today is to update the application code to call `window` instead of `window.top` when [run inside Cypress](https://docs.cypress.io/faq/questions/using-cypress-faq.html#Is-there-any-way-to-detect-if-my-app-is-running-under-Cypress).

**Comment by mylearning1005** [comment]
@jennifer-shehane  Is there any work around untill it is fixed

**Comment by jennifer-shehane** [comment]
@mylearning1005 You'd have to change the application code so that it no longer references `window.top`, so that it can be correctly run within an iframe.

**Comment by rangabarath** [comment]
@jennifer-shehane any update on this issue? 

This is the blocker issue for us.

**Comment by rsov** [comment]
Experiencing same issue

**Comment by lasithdilshan20** [comment]
@jennifer-shehane  any update on this issue?

**Comment by TarlanCollector** [comment]
@jennifer-shehane I still getting the same error. Is there an update on this issue? 
I tried different solutions that were named earlier for this issue but that do not work for me

**Comment by Raghav-Ramanathan** [comment]
@jennifer-shehane : Any updates on this issue? This is a real blocker for us as asking an application code change for it to run on a certain tool isnt the best possible practice. Any updates on when this might become available would be great.

**Comment by mingyixu** [comment]
@jennifer-shehane : It is very easy to appear this problem, how to avoid？If the service wants to use window.top.location.
[15963](https://github.com/cypress-io/cypress/issues/15963)
