### ISSUE TITLE
Feature Request: Run recently-failed tests at the beginning in cicd

### ISSUE THREAD

**Issue by craig-dae** [cypress-io/cypress#8066]
Feature Request

### Current behavior:

In cicd, tests are run in a random order, with new tests run first instead of at random. 

### Desired behavior:

Run recently-failing tests first, after new tests. 

Why? Sometimes we have test failures that occur in cicd, but not locally, due to race conditions. It would be nice to run these as quickly as possible to see if changes succeed in fixing those race conditions. 

### Test code to reproduce

This ticket does not require reproduction. It is not a bug. 

### Versions

4.11.0

**Comment by zoechi** [comment]
Somewhat similar to #6261

**Comment by jennifer-shehane** [comment]
As part of Cypress’s [new pricing](https://www.cypress.io/blog/2021/03/16/new-pricing-that-scales-seamlessly/), we’ve included the ability to [run failed tests first](https://on.cypress.io/smart-orchestration#Run-failed-specs-first). This setting is accessible from the Dashboard for organizations starting at the [Business Plan](https://www.cypress.io/pricing/).

This offers a solution for those running tests using the Cypress Dashboard since the feature itself requires a history of runs (that have been recorded).

**To get this feature, you will need to update to Cypress 6.8.0+ and also be a member of an organization subscribed to a [Business Plan](https://www.cypress.io/pricing/).**
