### ISSUE TITLE
Mock a Response with the binary of a pdf file

### ISSUE THREAD

**Issue by fabu1985** [cypress-io/cypress#8081]
Hello guys, I need help. Happened to me, that I want to mock the response, but my response is retrieving the binary of a pdf and your information, too. Ussually, I don´t have this problem because all the tests that I had expect a response like as Json for example. So

### Current behavior:
Actual Response:
![image](https://user-images.githubusercontent.com/20380386/88336059-b9469880-cd0a-11ea-8cfe-e2419aa5e8c8.png)

### Desired behavior:
Mock the response, when this is a binary with a pdf file and information associatted to it.

### Versions
Operatin System: Windows Server 8
Cypress: 4.9.0
Chrome: Version 84.0.4147.89

**Comment by jennifer-shehane** [comment]
Mocking the response through fixtures, you can pass the encoding you need for the response https://on.cypress.io/fixture

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
