### ISSUE TITLE
Unable to see test runner after running npx cypress open cmd

### ISSUE THREAD

**Issue by a-onkar** [cypress-io/cypress#8092]
### Current behavior:
I run the cmd to open cypress test runner, the test runner is opened in the background but can't see it.

### Desired behavior:

Able to see the test runner.

### Test code to reproduce

![cy-test runner](https://user-images.githubusercontent.com/25897622/88553650-6aa44180-d01d-11ea-9d0a-dbce83e591b4.gif)

### Versions

Windows 10
Cypress 4.11.0
Cypress 4.8.0

Tried with 2 diff repos, with 2 diff versions.

**Comment by jennifer-shehane** [comment]
This seems like an OS specific issue, as if it thinks you have another monitor. Other apps open find from the preview?

You could try following [these instructions](https://on.cypress.io/troubleshooting#Clear-App-Data) to Clear App Data - because this is where we store the information on where on the screen the app should display.

**Comment by a-onkar** [comment]
@jennifer-shehane Thanks for the solution. Clearing App Data woked.

**Comment by amancodify** [comment]
I faced similar issue. Here is the Fix:

I think you might have used Extended Display and probably have dragged the Cypress Runner on another screen, so if you have removed the extended screen and trying to open in you Laptop now, it will not open. Its a very weird issue on Cypress.
To Fix this, you have to connect you Screen(HDMI) again and then you might see the popup on that display. Drag again to you Laptop screen and then disconnect. It will work.
