### ISSUE TITLE
While loop doesn't work in Cypress

### ISSUE THREAD

**Issue by prnab** [cypress-io/cypress#8100]
```js
 while (true) {
  cy.get(".picker__nav--prev").click({ force: true }).then(function () {
    systemYear = $el.text();
    cy.log("After cick the value is " + systemYear);
    if (systemYear == date.getFullYear())
        break;
  })
}
```
### Current behavior:

Cypress runner gets hanged for the while loop

### Desired behavior:

While loop is not working in Cypress.

### Test code to reproduce

```js
while (true) {
  cy.get(".picker__nav--prev").click({ force: true }).then(function () {
    systemYear = $el.text();
    cy.log("After cick the value is " + systemYear);
    if (systemYear == date.getFullYear())
      break;
  })
}
```
Version = Latest
![image](https://user-images.githubusercontent.com/29373375/88641054-507d6880-d0dc-11ea-88b5-4e3ed75545bf.png)

**Comment by estefafdez** [comment]
I think those loops are not going to work on Cypress as they are using async functions. I also tried to use a do/while loop with the same result. 

Any workaround on this? I couldn't find a good async function to do something like: 

- Log in with a user with cards saved on his profile. 
- Check the list of cards and delete the first one. 
- Is there another card added? yes? delete the next one. 
- ...
- Repeat these steps until the card list is empty and you can see the message "There isn't any payment method added". 

Thanks!

**Comment by jennifer-shehane** [comment]
As suggested, this won't quite work as expected with Cypress commands being asynchronous. I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code). It's hard to suggest how to rewrite this since this is not a real-world example of what you're trying to accomplish with the 'while true'. 

@estefafdez The [conditional testing](https://on.cypress.io/conditional-testing) guide may be helpful here. If you have to do some action over and over again, generally just creating a recursive function and calling it until the condition is met will work fine. But, you need to ensure the state of the DOM is immutable at the point that you run the checks. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by estefafdez** [comment]
@jennifer-shehane is there any possibility to have an example of this types of loops with the RWA? thanks!

**Comment by yangislet** [comment]
> As suggested, this won't quite work as expected with Cypress commands being asynchronous. I suggest reading the entirety of our [Introduction to Cypress](https://on.cypress.io/introduction-to-cypress) guide. Specifically the section on [mixing async and sync code](https://on.cypress.io/introduction-to-cypress#Mixing-Async-and-Sync-code). It's hard to suggest how to rewrite this since this is not a real-world example of what you're trying to accomplish with the 'while true'.
> 
> @estefafdez The [conditional testing](https://on.cypress.io/conditional-testing) guide may be helpful here. If you have to do some action over and over again, generally just creating a recursive function and calling it until the condition is met will work fine. But, you need to ensure the state of the DOM is immutable at the point that you run the checks.
> 
> Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.
> 
> We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

This is a problem. We often use a test mode. Python builds a server that is only responsible for sending JSON test cases. Cypress is responsible for receiving JSON test cases, translating them into test cases for execution, and returning the direct results of the current test cases to the server. If Cypress does not support While (TRUE) mode, how can I dynamically add test cases to the Cypress execution thread? In the Python Asyncio library, they provide asyncio.run_ coroutine_ The threadsafe function allows users to dynamically add tasks to the loop thread, but we
