### ISSUE TITLE
question about Cypress.Promise

### ISSUE THREAD

**Issue by 534519560** [cypress-io/cypress#8115]
why the last code can not run?
### Current behavior:
![image](https://user-images.githubusercontent.com/33799740/88760077-d2ce6100-d19e-11ea-9932-7b0e353c4a37.png)

### Test code to reproduce
```js
it.only("test", function () {
  new Cypress.Promise((res) => {
    let obj = {
      onStart: () => {
        setTimeout(() => {
          res();
        }, 2000);
      },
    };
    obj.onStart();
  })
    .then(() => {
      return cy.request({ url: "http://localhost" });
    })
    .then(() => {
      console.info("success1");
    })
    .then(() => {
      return new Cypress.Promise((res) => {
        let obj = {
          onStart: () => {
            setTimeout(() => {
              res();
            }, 2000);
          },
        };
        obj.onStart();
      });
    })
    .then(() => {
      console.info("success2");
      return cy.request({ url: "http://localhost" });
    })
    .then(() => {
      console.info("should be executed");
    });
});
```

### Versions
4.9.0

**Comment by jennifer-shehane** [comment]
We don't advise running Cypress commands within a Promise, as the result is often unexpected. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
