### ISSUE TITLE
Tests are displayed duplicated on the logs when you run Cypress on CLI mode. 

### ISSUE THREAD

**Issue by estefafdez** [cypress-io/cypress#8117]
### Current behavior:

If I execute Cypress on CLI mode with cypress run... the tests I wrote and the specs are displayed duplicated on the logs but the tests are executed only once (as it should). 

### Desired behavior:

You can see on the logs the specs and tests executed without being duplicated. 

### Test code to reproduce

Run any project with Cypress 4.11.0 and with the command cypress run on CLI mode. It's happening to me locally (on a Macbook with MacOSX Catalina version 10.15.6) and on Linux when I run the tests on AWS on a Docker container. 

### Versions

Cypress 4.11.0 
All browsers: firefox, chrome, electron or edge. 

## Logs example:

![image](https://user-images.githubusercontent.com/6990209/88770659-70656880-d17e-11ea-9824-b59f971a5771.png)

**Comment by jennifer-shehane** [comment]
The results are not typically displayed twice for every case, so there is something specific to your project that is causing this. 

I see you are using the TestRail Reporter. Could you try turning off all plugins/reporters until you narrow down where the issue is happening? Or provide a reproducible repo of the issue - there may be something in your `plugins` or `support` file causing this. 

`cypress run` in 4.11.0 in a new project

<img width="816" alt="Screen Shot 2020-07-29 at 5 47 15 PM" src="https://user-images.githubusercontent.com/1271364/88793916-9e20d080-d1c3-11ea-87c4-ad56302d6390.png">

**Comment by estefafdez** [comment]
You're right, it's the TestRail accumulative reporter plugin the one that is causing the duplication. Thanks for the investigation @jennifer-shehane, I will open an issue on the proper repo! thanks! :)

**Comment by trprincebautista** [comment]
I have the same problem but with mochawesome reporter. How were you able ot fix it?

**Comment by prasadkotamsettiCS** [comment]
> I have the same problem but with mochawesome reporter. How were you able ot fix it?

Please check if you have two multiple reporting options enabled in **_cypress.config.js_** [or /.ts] .
See how having multiple reporting options, generate multiple logs on left side and removing one reporting option on right side config file would fix the issues. Let me know if it works. 

<img width="1620" alt="Screenshot 2024-03-21 at 09 24 10" src="https://github.com/cypress-io/cypress/assets/141259183/3bc283cf-1159-4fad-be1f-02461ee05a6a">
