### ISSUE TITLE
Change experimentalSourceRewriting  value

### ISSUE THREAD

**Issue by shevara84** [cypress-io/cypress#8128]
Can I change experimentalSourceRewriting value from cypress.json in single test file?
I tried with Cypress.config() but it doesn't work.

**Comment by jennifer-shehane** [comment]
You'll need to restart the browser in between resetting `experimentalSourceRewriting` so `Cypress.config()` setting with not work here. You'd have to run separate configuration or configuration file when running the specific file where this fix is needed. Some info here also on strategies: https://www.cypress.io/blog/2020/06/18/extending-the-cypress-config-file/#plugins-file 

```
cypress run --spec post-resource.spec.js --config-file source-rewrite.json
```

or 

```
cypress run --spec post-resource.spec.js --config experimentalSourceRewriting=true
```

Then run your other specs without this config. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
