### ISSUE TITLE
The final interacting element is checkbox but cypress throws exception when using check.

### ISSUE THREAD

**Issue by TestLeafInc** [cypress-io/cypress#8134]
### Current behavior:

Cypress throwing exception when interacting with Checkbox with check method. The 'get' command finds a div element and using div, I am looking for the input checkbox using sibilings. And then am interacting with checkbox but cypress throws exception stating that it is not a chekbox.

### Desired behavior:

Cypress should the final interacting element' type before invoking check or click.

### Test code to reproduce

```js
cy.visit('https://www.flipkart.com/')
cy.contains('Electronics').trigger('mouseover')
cy.wait(1000)
cy.contains('Vivo').click()
cy.scrollTo("bottom").contains('Number of Cores').click()
cy.get('div[title="Octa Core"]').siblings().first().click()
```

### Versions
4.11

**Comment by jennifer-shehane** [comment]
@TestLeafInc Please provide a failing test case - something showing the thrown exception. Running the test code provided passes and I see no errors. 

```js
it('visit', () => {
  cy.visit('https://www.flipkart.com/')
  cy.contains('Electronics').trigger('mouseover')
  cy.wait(1000)
  cy.contains('Vivo').click()
  cy.scrollTo("bottom").contains('Number of Cores').click()
  cy.get('div[title="Octa Core"]').siblings().first().click()
})
```

<img width="701" alt="Screen Shot 2020-08-03 at 3 52 39 PM" src="https://user-images.githubusercontent.com/1271364/89167389-61791e80-d5a1-11ea-8414-82a5bf3bf46a.png">

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
