### ISSUE TITLE
Testing on jira cloud website hangs trying to load page

### ISSUE THREAD

**Issue by galczo5** [cypress-io/cypress#8146]
### Current behavior:

Trying to test any addon for jira cloud. 
A lot of errors visible in console, check screenshots below.
Errors may be connected to @jennifer-shehane issue: https://github.com/cypress-io/cypress/issues/1436, I found the same `fn of undefined` visible in logs.

Jira Cloud is using iframes to display addons, so there may be the source of errors. I had to disable web security and use ignore x headers plugin for log in.
In sources I found potential fixes https://github.com/cypress-io/cypress/blob/6960f7cd78c9d730ed2d595faf5dc0a06d524270/packages/proxy/lib/http/util/regex-rewriter.ts#L8. 
![result](https://user-images.githubusercontent.com/6080725/89050691-6ea0ce00-d353-11ea-9e9a-427d280d4a32.png)
![console](https://user-images.githubusercontent.com/6080725/89050747-80827100-d353-11ea-98d6-8c4df0176302.png)

### Desired behavior:
Jira cloud renders addons.

### Test code to reproduce

Ready to use example in https://github.com/galczo5/cypress-jira-cloud

### Versions

Cypress: 4.11.0
Chromium: 83
Tested on Pop OS and MacOS, same result

**Comment by jennifer-shehane** [comment]
I can recreate this from the provided repo https://github.com/galczo5/cypress-jira-cloud Basically after logging in, the page gets stuck on a loading spinner and has a lot of errors displayed in the console.

**Comment by erezvish** [comment]
I have an issue that appears similar, trying to test a jira cloud addon.
Disbaled web security to try to bypass cross origin redirect and ended up with errors.
I'm not using an ignore headers plugin

Watching :)

**Comment by tomasz-kucharski** [comment]
Highly interested in having it fixed!

**Comment by fipciu1996** [comment]
I'm looking forward for fix that

**Comment by galczo5** [comment]
@jennifer-shehane do you need more details from me?

**Comment by galczo5** [comment]
Any news? I really need this to be fixed

**Comment by becciwatson** [comment]
We have the same issue and would like a resolution promptly.  
This defect renders Cypress inoperable for the Jira stack.

**Comment by jennifer-shehane** [comment]
I am able to get the example provided in the original comment working, with a few extra steps. 

1. Visiting the Jira website encounters this bug: https://github.com/cypress-io/cypress/issues/8679. You will need to downgrade Cypress to version 4.11.0 until this is fixed (this should be prioritized soon). 
1. Visiting the Jira website encounters this bug: https://github.com/cypress-io/cypress/issues/4220. You will need to include the [current workaround](https://github.com/cypress-io/cypress/issues/4220#issuecomment-649264985) to ignore xframe headers in Jira. You can see an example of linking to a locally installed version of the plugin here: https://github.com/galczo5/cypress-jira-cloud/blob/master/cypress/plugins/index.js
1. You'll need to pass `--browser chrome` during `cypress run` - as the ignore-xframe-headers plugin workaround will not apply in Electron.
1. You'll need to add an `uncaught:exception` handler to avoid failing tests - since there are some errors being thrown from the application under test. 
1. You'll need to pass `"chromeWebSecurity": false` to your `cypress.json`

The previous example had a `userAgent` defined in its `cypress.json`. This would cause an error in Jira saying third party cookies need to be accepted. Removing the `userAgent` configuration fixed this. May be related to [this](https://community.atlassian.com/t5/Jira-questions/how-to-resolve-Please-make-sure-your-browser-has-third-party/qaq-p/591612).

- There is still a remaining issue after all of this with reloading the tests during `cypress open` - where it will go to a dead link. 

<img width="1050" alt="Screen Shot 2020-10-22 at 11 27 32 AM" src="https://user-images.githubusercontent.com/1271364/96826568-9b97e500-1459-11eb-8317-68da4514c5a7.png">

**Notice:** At the end of the day, their website is doing a lot of things that prevent it from running well within the Cypress Test Runner. This is big reason that we advise you to not test websites that are not under your direct control. Atlassian could change their site tomorrow and none of our workarounds above will work anymore, so there's no guarantee. 

**Working example**

`spec.js`

```js
Cypress.on('uncaught:exception', (err, runnable) => {
    return false // this is required!
})

it('Jira cloud', () => {
    cy.visit('https://cypress-testing.atlassian.net/')
    cy.get('#username').type('qxo88804@bcaoo.com')
    cy.get('#login-submit').click()
    cy.get('#password').type('sdAA3@sd!@;')
    cy.get('#login-submit').click()
    // the code below here is outdated, 
    // so I'm not sure what was meant to be tested after login
})
```

`cypress/plugins/index.js`

```js
const path = require('path');
// this should point to a local version of the ignore-x-frame-headers plugin
// https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe
const extensionUnZipped = path.join(__dirname, '../../IgnoreXFramesPlugin');

module.exports = (on, config) => {
    on('before:browser:launch', (browser = {}, launchOptions) => {
        // this only works in Chrome, not Electron.
        // pass '--browser chrome' during 'cypress run'
        launchOptions.extensions.push(extensionUnZipped);
        return launchOptions;
    });
}
```

`cypress.json`

```json
{
  "chromeWebSecurity": false,
  "defaultCommandTimeout": 30000
}
```

![](http://g.recordit.co/LEeGwTYQM9.gif)

**Comment by becciwatson** [comment]
Hi Jennifer:

Thank you for responding.
We cannot ignore xframe headers – It is a security requirement and part of the Jira authentication that we must have them.
No xframe headers = no app.  They shut down the app for non-compliance within 24 hours.
Atlassian makes the rules and they do not compromise on this.

Milan – please will you provide some examples of the snippets of code for Jennifer ASAP.

Regards,
Becci
________________________________
Becci Watson
m:  0412 029 903
Int:  +61-412 029 903
email:  becci@becciwatson.com.au<mailto:becci@becciwatson.com.au>
blog: BecciWatson.com.au
linkedIn: www.linkedin.com/in/becciwatson<http://www.linkedin.com/in/becciwatson>

**Comment by becciwatson** [comment]
Milan:

Please provide details of this bug to Jennifer directly.
Do not put any details of our code on public websites.

Cypress should know better than this to make all bugs public.

Regards,
Becci
________________________________
Becci Watson
m:  0412 029 903
Int:  +61-412 029 903
email:  becci@becciwatson.com.au<mailto:becci@becciwatson.com.au>
blog: BecciWatson.com.au
linkedIn: www.linkedin.com/in/becciwatson<http://www.linkedin.com/in/becciwatson>

**Comment by galczo5** [comment]
@becciwatson try to set `window.name` to `@atlassian/spa-iframe` before you load Jira page. Somehow it works, but there is no information what is it and how long it will be supported.

**Comment by milan-easykad** [comment]
Hi Jenifer,

 

As we agreed, here is the bug for Jira add-on loading:

https://github.com/cypress-io/cypress/issues/8958

 

I hope it will be fixed soon. 

 

Kind Regards, 

Milan Suka

**Comment by becciwatson** [comment]
Hi Jennifer:  this workaround has not resolved the problem.  Please can we have an update on this.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.
