### ISSUE TITLE
Cypress captured Text not recognized

### ISSUE THREAD

**Issue by PrasadNunna** [cypress-io/cypress#8147]
### Current behavior:
Using cypress i am able to capture text on form inputs,but when submitting form my application says all fields required.I am not sure what to do with this.I tried {downarrow}{Enter} type of key storks

### Desired behavior:

Need to sub,it form using the entered text.

### Test code to reproduce
```js
describe('Search', () => {
    it('testing', () => {
        cy.viewport(1920, 1080)
        cy.visit('http://localhost:8001/')
        cy.get('#userNameBox').type('xyz')
        cy.get('#Password').type('ABC')
        cy.xpath("//button[@type='submit']").click()
        cy.get('#Name').click().focus().then(($input) => { $input.val('DCode') }).type('{enter}')
        /*
        below code is not working
        */
        cy.get('#Name').click().focus().then(($input) => { $input.val('DCode') }).type('{enter}')
    })
})
```

![image](https://user-images.githubusercontent.com/19566394/89057547-22a75680-d35e-11ea-8d9c-1ce58120812d.png)

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide the application code or some sample HTML code to run the provided tests against - where we can recreate and see the issue. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

Also, check out our [community chat](https://on.cypress.io/chat), it can be helpful for debugging or answering questions on how to use Cypress.

**Comment by nunnaveeraprasad** [comment]
[code.txt](https://github.com/cypress-io/cypress/files/5039177/code.txt)
Please find the HTML Code of my Application window

**Comment by jennifer-shehane** [comment]
Can you provide the test code to go with this exact HTML? The test code targets `#userNameBox`, `'#Password'`, a submit button and `'#Name'`, but none of this is found in the HTML you provided. 

We need a full example we can run - all test code + application code to run against it.

**Comment by nunnaveeraprasad** [comment]
[codeOne.txt](https://github.com/cypress-io/cypress/files/5039578/codeOne.txt)
Please find the code for the above scenario 
/* 
First block belongs to page inputs
*/

/* 
Second block belongs to test
*/

**Comment by jennifer-shehane** [comment]
There is code missing from this test code - like definitions to `cy.Login` and the `import { depotPage } from "../PageObjects/Depots"`. Please provide a full example - perhaps a repo would be best.
