### ISSUE TITLE
before() from support/index.js called twice

### ISSUE THREAD

**Issue by ttomaszewski** [cypress-io/cypress#8167]
### Current behavior:

before() used in support/index.js being called twice.

<img width="739" alt="Screenshot 2020-08-03 18 44 55" src="https://user-images.githubusercontent.com/37166713/89234509-2505ec80-d5ba-11ea-8066-a61fb2db32b0.png">

### Test code to reproduce

support/index.js
```js
// Import commands.js using ES2015 syntax:
import './commands';
import faker from 'faker';

export const nameSeed = faker.random.words(3);

before('define nameSeed', () => {
  cy.log(`Name seed for this run is: ${nameSeed}`);
});

after('log out', () => {
  cy.log(nameSeed);
});
````

### Versions

4.11.0, MacOS, Chrome

**Comment by jennifer-shehane** [comment]
I cannot recreate the issue as described in Cypress 4.11.0. Likely, the test code or the structure of the actual spec file is important to recreating the issue. Please provide the test code (in the spec file) required to run with this to recreate the issue. Thanks!

<img width="429" alt="Screen Shot 2020-08-05 at 11 41 45 AM" src="https://user-images.githubusercontent.com/1271364/89374232-c901ac00-d710-11ea-842b-34ffbd74d886.png">

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by ashutoshns** [comment]
I'm facing the same issue. I didn't face it earlier but when I moved my tests to a folder structure inside `integration` folder, it started running twice. 
![image](https://user-images.githubusercontent.com/18315924/89861915-73237d00-dbc4-11ea-8752-2c0283672371.png)

**Comment by jennifer-shehane** [comment]
@ashutoshns It's likely that this is a visual bug - that it's only in the display and not actually making 2 requests. 

Please provide the test code that produces the duplicate logs so that we can track down and fix the bug. Thanks!

**Comment by ashutoshns** [comment]
I confirmed that it is indeed making two requests by adding a global counter which was set to 0 and also having it print a random number. From the look of it, I'd say the `index.js` is being called twice for some reason.(Adding the hook and logs) I also tried to reproduce this issue on a new dummy app but the hook was called just once and was working as per expectation. I think this could be something related to my configuration and not a cypress bug. What forum can I reach for support?

![image](https://user-images.githubusercontent.com/18315924/89888174-2738fe00-dbed-11ea-85c1-0f3298a8a8bc.png)
```javascript
var counter = 0
before(() => {
  cy.pingMaster();

  var _counter = Cypress.env('counter');
  Cypress.env('counter', ++_counter);

  cy.log('global counter =' + Cypress.env('counter'));

  cy.log('local counter =' + ++counter);
  
  cy.log(Math.random());
})
```

**Comment by jennifer-shehane** [comment]
Yeah, maybe you are requiring the index file twice somehow?

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by sagenicky** [comment]
Found out that in supportFile, when I define a function, export it and import it in some test file, then that particular test file executes all other functions/modules inside support/index.js for a second time, resulting in before and after hooks called twice.

Is that an expected behavior? Why does import execute the whole file? Any way to stop it?

**Comment by jennifer-shehane** [comment]
@sagenicky Please provide a full reproducible example so we can see if the behavior is expected or not for ourselves.

**Comment by steveatkoan** [comment]
@sagenicky thanks for the clue that helped.
When I define some test utility functions in e2e.ts and import those in my tests, after() gets run twice. Seems like e2e.ts is magical somehow: 
- it is included once by cypress in one execution context, which calls after()
- it is included again in another context when the file is imported to use the utility functions, which also calls after()

The contexts are separate somehow, because 
```
let alreadyIncluded=false; 
if (!alreadyIncluded) {
   alreadyIncluded = true;
   after(() => console.log('foo'))
}
```
logs foo twice

The solution was to move my testing utility functions to a separate file and only have cypress configuration (and after()) in e2e.ts
