### ISSUE TITLE
Urgent - Issue with XHR call using Cypress

### ISSUE THREAD

**Issue by gitsaquib** [cypress-io/cypress#8168]
```js
cy.form_request(
  'POST',
  `${apiBaseUrl}/attachment?entityId=${executionId}&entityType=EXECUTION`,
  'sample.jpg',
  'image/jpeg',
  function (response) {
    console.log(response);
  }
);
```
command.js:
```js
Cypress.Commands.add('form_request', (method, url, fileName, fileType, done) => {
  cy.fixture(fileName, 'binary').then(binary => {
    return Cypress.Blob.binaryStringToBlob(binary, fileType).then(blob => {
      const formData = new FormData();
      formData.set('data', blob, fileName);
      const xhr = new XMLHttpRequest();
      xhr.open(method, url);
      xhr.setRequestHeader('Authorization', 'Basic xxxxxxxxxxxxxxxxxxxxxxxxxx');
      xhr.setRequestHeader('Cache-Control', 'no-cache');
      xhr.setRequestHeader('X-Atlassian-Token', 'nocheck');
      xhr.setRequestHeader('User-Agent', 'test-agent');
      xhr.onload = function () {
        done(xhr);
      };
      xhr.onerror = function () {
        done(xhr);
      };
      xhr.send(formData);
    });
  });
})
```

Getting `net::ERR_BLOCKED_BY_CLIENT` error. Because cypress is setting `Referer` to `localhost` and overriding `User-Agent` to `User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36`

Also, gives error `Refused to set unsafe header "User-Agent" on xhr.setRequestHeader('User-Agent', 'test-agent');	`

**Comment by jennifer-shehane** [comment]
Can you provide a fully reproducible example? That we can run completely to see the error?

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
