### ISSUE TITLE
ERR_CONNECTION_ABORTED (-103) loading 'http://localhost Any browser

### ISSUE THREAD

**Issue by christoud** [cypress-io/cypress#8169]
### Current behavior:

Running any of the `feuture/exampl`e on my work laptop gives
``` 
ERR_CONNECTION_ABORTED
```
I tried most of the suggestions offered by search engines to no avail.

Windows 10 2004 64bit
Cypress 4.12.0
No local/PAC proxy, we do use Blue Coat as a cloud proxy 
Symantec EP 14 AV
![image](https://user-images.githubusercontent.com/61222341/89267932-3662fd80-d67b-11ea-9a06-370373059cb8.png)

### Desired behavior:
Run the example/file:
```
cross-env DEBUG=cypress:* cypress open
```

### Versions

Windows 10 2004 64bit
Cypress 4.12.0
No local/PAC proxy, we do use Blue Coat as a cloud proxy 
Symantec EP 14 AV
Electron, Firefox, Chrome

Logs:
[cy_logs.log](https://github.com/cypress-io/cypress/files/5020821/cy_logs.log)

Code:
[Cypress_BDD.zip](https://github.com/cypress-io/cypress/files/5020835/Cypress_BDD.zip)

**Comment by jennifer-shehane** [comment]
I'm not able to reproduce the issue as given from the provided repo, so it is likely isolated to something with your environment/OS or proxy. 

<img width="843" alt="Screen Shot 2020-08-07 at 4 22 13 PM" src="https://user-images.githubusercontent.com/1271364/89633747-4f152280-d8ca-11ea-8b19-7b41a3780797.png">

**Comment by christoud** [comment]
Any ideas how i can debug this more? Our QA team wants to use Cypress and this is blocking us.

**Comment by jennifer-shehane** [comment]
We'd need a way to see and reproduce the error in order to give some guidance on how to fix it.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by CialUnity** [comment]
turns out our security team was blocking connections to localhost, we are just running it on aws instances at the moment.

Thanks for the help.
