### ISSUE TITLE
cypress "or "

### ISSUE THREAD

**Issue by Ahm3d-A** [cypress-io/cypress#8170]
Is there any possible way of telling cypress that the url should equal someting OR  something else?

For example 
  
           url should equal https://www.google.com/ or https://www.bing.com/

**Comment by Ahm3d-A** [comment]
doing it like this throws an error 
![image](https://user-images.githubusercontent.com/64726246/89281040-c5572200-d649-11ea-9d63-99abff4790f6.png)

**Comment by Ahm3d-A** [comment]
![image](https://user-images.githubusercontent.com/64726246/89281199-051e0980-d64a-11ea-9982-6b0eb58d2ffe.png)

**Comment by Ahm3d-A** [comment]
![image](https://user-images.githubusercontent.com/64726246/89281297-2979e600-d64a-11ea-943d-6cf6b768a6db.png)

**Comment by jennifer-shehane** [comment]
`expect` is not chainable off of Cypress commands. Please read our docs, particularly the portion on [Writing assertions](https://on.cypress.io/introduction-to-cypress#Writing-Assertions)

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
