### ISSUE TITLE
drag select problem

### ISSUE THREAD

**Issue by wasiqkhan786** [cypress-io/cypress#8172]
### Current behavior:
```js
public dragSelect(selectionRect: any) {
  debugger
  let that = this;
  let top = selectionRect.top;
  let left = selectionRect.left;
  let right = selectionRect.right;
  let bottom = selectionRect.bottom;
  return this.waitForSelectionHandling().then(() => {

    cy.wait(1500)
    cy.get("#map").first().trigger('mousemove', left, top, { which: 1, force: true })
      .trigger('keydown', { keycode: 16, release: false, force: true })
      .trigger("mousedown", { button: 0, force: true })
      .trigger("mousemove", right, bottom, { force: true })
      .trigger("mouseup", { force: true })
      .trigger("keyup", { force: true });
  }
}
```
![TestrubberBandSelectionspects](https://user-images.githubusercontent.com/44477404/89291912-a6fa2200-d65b-11ea-803e-9a812c25997d.gif)

### Desired behavior:

I am facing the problem in selecting the vehicles on map using coordinates my case mouse is moving but from source to destination but not selecting any vehicles on map.after pressing shift key and mouse left button it should move to desired position but getting no sucsses. please help in this case

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by wasiqkhan786** [comment]
its feature request how can i use shift with non typeable elements

**Comment by jennifer-shehane** [comment]
@wasiqkhan786 You can type `{shift}` on the body and pass `release: false` to hold down the key throughout other commands. https://on.cypress.io/type#Key-Combinations

But also, issuing keyCodes through events should trigger those events with the options you've passed.
