### ISSUE TITLE
SQL Server connectivity will cypress .Encountering Task not defined in Cypress\Plugins\index.js even after describing Task 

### ISSUE THREAD

**Issue by Harikagrandhi** [cypress-io/cypress#8173]
Error--
![image](https://user-images.githubusercontent.com/40540573/89316334-9177fe80-d641-11ea-8bf1-f5a390022fc6.png)

Cypress.json
```json
 "db": {
    "userName": "****",
    "password": "****",
    "server": "****",
    "options": {
      "database": "",
      "encrypt": true,
      "rowCollectionOnRequestCompletion": true
    }
```

support\index.js
```js
import sqlServer from 'cypress-sql-server';
sqlServer.loadDBCommands();
```
plugins\index.js
```js
const sqlServer = require('cypress-sql-server');
module.exports = (on, config) => {
    tasks = sqlServer.loadDBPlugin(config.db);
    on('task', tasks);
}
```

spec.js
```js
 cy.sqlServer('SELECT TOP (10) * FROM TableX');
```

Please guide me where the issue is ?

**Comment by jennifer-shehane** [comment]
I am not encountering this same error. Please make sure you only have one `module.exports` defined in your `plugins/index.js` - if you have more than one, they will overwrite each other and your task will not be defined. 

<img width="542" alt="Screen Shot 2020-08-18 at 1 43 39 PM" src="https://user-images.githubusercontent.com/1271364/90482216-e85cf800-e158-11ea-866e-27881fbea7e9.png">

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by ashokkumarg** [comment]
@jennifer-shehane I use Cypress with Typescript. Will it be possible to call cy.sqlserver in a typescript class file. Could you provide the guidance?

**Comment by sindhuakn** [comment]
I use Cypress with Typescript. Will it be possible to call cy.sqlserver in a typescript class file. Could you provide the guidance?
