### ISSUE TITLE
cy.click() working inconsistently.  

### ISSUE THREAD

**Issue by ShamiliArj** [cypress-io/cypress#8185]
cy.click() working inconsistently. 

on clicking the Add to basket button should see view basket button.

![image](https://user-images.githubusercontent.com/38881563/89389058-d319af80-d6fc-11ea-8f36-6328cc295cc9.png)

Steps:
1.https://raceforlifeshop.cancerresearchuk.org/ 
2.Add any product the basket.
3. again add another product to the basket 

 windows and chrome

**Comment by jennifer-shehane** [comment]
@ShamiliPrabu Please provide the test code you run - the JavaScript file in your `cypress/integration` to reproduce the error so that we can just run the code. Thanks!

**Comment by ShamiliPrabu** [comment]
@jennifer-shehane thanks for getting back. though its not the good practice I have used cy. wait to resolve this error. 

Below is the code is used
cy.visit(https://raceforlifeshop.cancerresearchuk.org/'
    cy.get('main-menu__link_anchor main-menu__link_anchor--level0).each((output) =>{
      cy.contains(outputData).click();
      cy.get('figure a img').then((selprod) => {
        selprod.first().click();
        cy.wait(300);
  cy.get('[id*=edit-submit]').click({ force: true }, { release: true });
      });

Thanks.

**Comment by jennifer-shehane** [comment]
@ShamiliPrabu Please provide a fully running test suite. As provided, the test does not find the first element and the `outputData` is undefined. 

```js
it('test', () => {
  cy.visit('https://raceforlifeshop.cancerresearchuk.org/')
  cy.get('main-menu__link_anchor main-menu__link_anchor--level0').each((output) =>{
    cy.contains(outputData).click();
  })
  cy.get('figure a img').then((selprod) => {
    selprod.first().click();
    cy.wait(300);
    cy.get('[id*=edit-submit]').click({ force: true }, { release: true });
  });
})
```

<img width="1328" alt="Screen Shot 2020-08-18 at 1 38 47 PM" src="https://user-images.githubusercontent.com/1271364/90481672-29a0d800-e158-11ea-862b-a2cacab5d1d7.png">

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
