### ISSUE TITLE
Search Input is not refreshing search results starting from cypress 4.9.0

### ISSUE THREAD

**Issue by chandrasekhar174717** [cypress-io/cypress#8187]
### Current behavior:
I have a table containing details of multiple users, and search input on top of that table. When I enter user details in search input table should be updated with the search results.  This was working fine till version 4.8.0
![image](https://user-images.githubusercontent.com/48081804/89410610-ab990600-d741-11ea-97ec-04473ee5e64d.png)

### Desired behavior:
When Input is entered table is not updating with search results starting from cypress 4.9.0 when tests are running.

### Versions

Cypress: 4.9.0
browser: Chrome 84

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment with a full example - test code and application code to run against and we will consider reopening the issue.
