### ISSUE TITLE
Why i am facing crashing issue in headless mode mean while test case running perfectly on electron or other browser.

### ISSUE THREAD

**Issue by Rana-Shabbir** [cypress-io/cypress#8188]
On cypress i had wrote big test-case when i run that test-case on desktop mode on electron then its working smoothly but when i runned that same test-case on headless mode its crashed

This is desktop mode when i am running my test case on electron ...
![Screenshot from 2020-08-05 17-06-23](https://user-images.githubusercontent.com/55960875/89411965-b6eb3200-d73f-11ea-8ff3-bfe95150f965.png)

This is headless mode when i am running my test case on terminal
![Screenshot from 2020-08-05 17-07-28](https://user-images.githubusercontent.com/55960875/89412047-d7b38780-d73f-11ea-8010-e65937d04754.png)

How to solve it is it my code issue or some thing else?

**Comment by jennifer-shehane** [comment]
I suggest reviewing the video of the test run - it can help isolate why this may have failed. Also try following recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by Rana-Shabbir** [comment]
**Attached is the video reference for test in Headed Mode which is running our test case smothly** 
[Places_Headed-Mode.zip](https://github.com/cypress-io/cypress/files/5183241/Places_Headed-Mode.zip)

----------------------------------------------------------------------------------------------------------------------------------------------

**Attached is the video reference for test in Headless Mode which is failing our test case**
[Places_Headless-Mode.zip](https://github.com/cypress-io/cypress/files/5183243/Places_Headless-Mode.zip)

**Comment by jennifer-shehane** [comment]
Did you go through some of the suggestions in the guide? https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI Could you share any insight from that?

Specifically have you run the tests in Electron locally with devtools open, are there any errors being thrown at the time the page goes blank?
