### ISSUE TITLE
Using If/else condition in code but not working properly

### ISSUE THREAD

**Issue by Ayushrjt** [cypress-io/cypress#8208]
I am using If/else condition on my code but i guess the the condition i am using for if/else is not proper.Need help for getting proper condition that i can implement correctly in the cypress.io.

**Explanation-** i need a condition to implement,like-->when i will search any text(ex-july) on my filter searchbox then if that text is present, it should be visible but when the searched text(ex-july) is not present then it will display the text as "No data".
So for this i am trying to implement If/else statement. 

If condition used below--> it will get element in which text is present, it should be visible, if that happens then verify whether text(july) is present
else--> will display the text as "No data"

_**Code written for if/else:-**_

```js
namefilteredvalue(): this {

  if (cy.get('.ant-table-row > .NameStyling').should('be.visible')) {
    cy.contains("july")
  }

  else {
    cy.contains('No Data')
  }
  return this;
}
```

_Element for first row in which july(text) is displayed_-->  '.ant-table-row > .NameStyling'

Problem facing:- only validating if statement if  they will find text it will display the text but when not getting desired text not moving to else statement (which can show other text(no data))

using cypress.io.

**Comment by jennifer-shehane** [comment]
Please read our guide on [Conditional Testing](https://on.cypress.io/conditional-testing) - you will need to have absolute gaurantee that the page is don't loading - that all elements are present before using conditional statements or else you don't know if your test will meet the condition because the page isn't done loading or because it legitimately does not exist. 

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by geetha409** [comment]
Hi Jennifer,

I am trying to use if-else block to verify data from fixture file and if that matches I am trying to perform some actions. but that's not working. 

Eg: 
         if(bussinessProfileDetails_standard.doesTheEntityOperateUnderDBA == 'No'){
            cy.get('#abc').click();
         } else {
            cy.get('#xyz').click();
            cy.get('#sdf').type(bussinessProfileDetails_standard.ifYes_enterTheDBANames)
           
         }

Here bussinessProfileDetails_standard is the fixture object. 
It's always going to else block without considering the if condition. please help

**Comment by madhuriaarth** [comment]
In my code it runs only else condition if condition is not working
cy.get('body').then((body) => {
            if (body.find('[data-test-id="startImportProjectBtn"]').length > 0) {
cy.get('[data-test-id="startImportProjectBtn"]').click()
                
            }
            else {
                cy.get('[data-test-id="replaceExistingProjectCheckBox"]').click()  
            }
            
        })
