### ISSUE TITLE
Cypress with AEM: Can not open path browser in author dialog

### ISSUE THREAD

**Issue by anubajaj23** [cypress-io/cypress#8216]
### Current behaviour:
I am trying to replace AEM hobbes test cases to cypress test cases but facing lots of issues related to AEM dialog. One of them is explained below:

It will open insert dialog but popup the same dialog multiple times and my browser hangs for some time.

### Desired behavior:

Popup should display only one time on click.

### Test code to reproduce

```js
it('Open the Cookie dialog and verifies elements and values', () => {
  cy.server()
    .visit(homePageUrl)
    .route('/libs/wcm/core/content/components*').as('components')
    .wait('@components').then(() => {
      cy.get('div[data-text="Drag components here"]').should('be.visible').click()
        .then(() => {
          cy.get('#EditableToolbar').then(($EditableToolbar) => {
            if ($EditableToolbar.length <= 2) {
              cy.get('[title="Insert component"]').click({ force: true });
            }
          })
        })
    })
})
```

<img width="697" alt="Screen Shot 2020-08-07 at 2 10 39 PM" src="https://user-images.githubusercontent.com/51432815/89627008-dd33dd80-d8b7-11ea-9055-73dde8efce40.png">

### Versions
Cypress : 4.11.0
Browser: chrome
MacBook

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide the application code, or an example HTML page to run the test code against to see the issue.

Please comment in this issue with a reproducible example and we will consider reopening the issue.
