### ISSUE TITLE
Take into account the search pattern when running all specs in the interactive mode (RegEx)

### ISSUE THREAD

**Issue by CScharerCorteva** [cypress-io/cypress#8220]
### Current behavior:

Currently the search pattern does not allow the use of Regular Expressions.

### Desired behavior:

Since I have spec files created for individual brand tests in separate files within separate folders it would be very useful to be able to filter using a regular expression (using the folder separator and maybe include a dropdown to specify .spec.ts, .spec.js, etc.) so I can include the folder(s) and/or sub folder(s) that the spec files exist in.

### Test code to reproduce

Simply include a regular expression in the search pattern (include a back slack or forward slash or asterisks).

### Versions

4.12.1

**Comment by sinharaksh1t** [comment]
@CScharerCorteva did you mean provide a regex for Search here on this search bar?
![Screen Shot 2020-09-17 at 1 56 24 AM](https://user-images.githubusercontent.com/28585848/93449500-ad4e0180-f889-11ea-8557-0acf69b3a544.png)

**Comment by CScharerCorteva** [comment]
Yes.  😉

**Comment by sinharaksh1t** [comment]
I see! I would love to take a stab at it if I could get some guidance around it (cc @jennifer-shehane)
Hopefully, I wouldn't need too much hand-holding.. 😅 
Let me do some home work to see how this can be accomplished. If you have any pointers for me as a starting point @jennifer-shehane , I would truly appreciate it!! Thank you!! 🙏 😁

**Comment by sinharaksh1t** [comment]
I read through the contributing docs and I also dug deeper into the `packages/desktop-gui` code. I have been able to identify [the file](https://github.com/cypress-io/cypress/blob/develop/packages/desktop-gui/src/specs/specs-list.jsx#L78) where the code change needs to happen.
My only concern is that the [Desktop GUI document](https://github.com/cypress-io/cypress/tree/develop/packages/desktop-gui) itself has a note saying:
```
NOTE: Currently, if you want to work on the code around logging in, viewing runs, or setting up new projects to record,
this requires connecting to a locally running API server.
```
And since this local API server is only accessible to Cypress employees and not to outside collaborators, I have been having some challenges in getting the local version of the Desktop GUI app to load a mocked project structure. I tried using the existing mocks. However, I have a hard time understanding if there is a way by which I could mock `specStore` object in that file. This object, in my understanding, is what is responsible to keep the most up to date filtered list of projects to be rendered in the list.
Is `packages\desktop-gui\cypress\fixtures\specs.json` an accurate depiction of the mock that I can use for `specStore` object?

Thanks for the help in advance!

**Comment by samueloakley** [comment]
Hi I've done a straightforward drop in of regex matching alongside the current string matching in #8819
Still need to add some tests.

@jennifer-shehane @CScharerCorteva In terms of implementation, does it make sense to have regex vs standard filtering as a toggle? It's not obvious otherwise that you can even do it.

**Comment by CScharer** [comment]
@jennifer-shehane I don't think it could hurt, but I think it would become very clear once a person types in a regular expression and the filter starts to show folders/files that match that RegEx.

**Comment by jennifer-shehane** [comment]
After re-looking at the original issue, our team is wondering if the real need here is some checkboxes in the GUI, to filter to "run all" matching specfiles as explained in this issue. https://github.com/cypress-io/cypress/issues/3607

Right now our team is thinking the Regex search is not something we'd like to support.

**Comment by CScharer** [comment]
That would work as a substitute.  Might also be nice to always be able to see a count of the number of specs that were selected or would run if clicking the **_Run all specs_** button too.

**Comment by jennifer-shehane** [comment]
Since this has not gotten a lot of interest over the years, we’ll close this as not planned.
