### ISSUE TITLE
No stack traces in `cypress run` and inconsistent from `cypress open`

### ISSUE THREAD

**Issue by samtgarson** [cypress-io/cypress#823]
- Operating System: OSX
- Cypress Version: 0.20.1
- Browser Version: 61.0.3163.100 (Official Build) (64-bit)

### Is this a Feature or Bug?

Bug

### Current behavior:

Using a Nuxt app and `cypress run` from the command line, the tests linked below show an `Uncaught SyntaxError: Unexpected identifier` with **no** stack trace, but work perfectly when using `cypress open`

Commenting out `cy.visit` seems to fix the error, but obviously the tests still fail which suggest to me it's an error when processing the page however I don't know how to find out any further than that without any clues.

### Desired behavior:

The behaviour in `open` and `run` should be the same, but also primarily there should be stack traces to debug syntax errors.

### How to reproduce:

Basic versions of the tests and results shown here: https://gist.github.com/samtgarson/dadd2d760c7701c8ab0c2ee8e89bd9a4

I can't share the entire repo but if you have no idea where to begin I can try to recreate with a basic example.

#### Test code:

Above

### Additional Info (images, stack traces, etc)

Above

**Comment by jennifer-shehane** [comment]
Have you tried running the tests with `cypress open` and selecting the Electron browser? We use Electron to run headlessly in `cypress run`. I'm wondering if there error would show up there.

**Comment by samtgarson** [comment]
Thanks for the quick reply! It does show a stack trace there but seems to be internal?

![image](https://user-images.githubusercontent.com/6242344/32065267-2921a412-ba74-11e7-9b3a-6d80c1334d05.png)

**Comment by samtgarson** [comment]
(Incidentally—just upgraded to v1.0.2, to keep this issue accurate...)

**Comment by brian-mann** [comment]
Cypress does not print a stack trace when the error originated from itself (since it throws hundreds of different error messages).

There's no way there's an unexpected identifier in Cypress itself so I'd be curious why its thinking the error came from itself...

I believe this is actually an uncaught exception **from your application**. I'd have to investigate why Cypress is not immediately printing the stack trace which would point you to your application.

We probably should upgrade the error message to also be much clearer that its from **your app** as opposed to something else.

Lastly, if my assumptions are correct you can use the `uncaught:exception` event to capture this error instance directly (by using a debugger).

The docs for that are here: https://docs.cypress.io/api/cypress-api/custom-commands.html#Syntax

**Comment by samtgarson** [comment]
Yeah I did assume the error was from my app and that that was the cause—I was more filing this as the error is quite vague (and not super helpful—although the other errors I've encountered in Cypress have been very helpful!)

Do you know any easy way to boot up the electron browser myself to see if I can find the error that way? The payload from that `uncaught:exception` is not giving me much...

**Comment by samtgarson** [comment]
aha... I've got it. Thanks for your help. Shall I close this issue?

**Comment by brian-mann** [comment]
You can use the Electron browser by switching to it in the GUI (which you already did)

It runs headlessly by default from `cypress run` but you can just pass `--headed` and it will display like the GUI.

- https://docs.cypress.io/guides/guides/command-line.html#cypress-run
- https://docs.cypress.io/guides/core-concepts/launching-browsers.html#Electron-Browser

**Comment by brian-mann** [comment]
Released in [`2.0.0`](https://docs.cypress.io/guides/references/changelog.html#2-0-0).
