### ISSUE TITLE
creating random id for elemens but not changing when reload

### ISSUE THREAD

**Issue by Ahm3d-A** [cypress-io/cypress#8234]
Is there any way I can give elemnts on a webpage random id that will afterwards be fixed even if the page reloads? (javascript, vue, ... ) I want to test the webpage using cypress and I have added datacy attributes but when this specific element gets added it has same data cy attribute so I want to give it a random number like index but this index should not change even if e.g. first element with index 1 gets removed second element has still index 2 and if i use just random string for data cy i want if page gets reloaded not to change.

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
