### ISSUE TITLE
cy.click() because it requires a Dom element in after each

### ISSUE THREAD

**Issue by khaledjawhar** [cypress-io/cypress#8245]
I have specified multiple tests in a fixture with a before each and after each as follows:
```js
describe('My First Test', () => {
  before each() {
    cy.login
  }
  after each()  {
    cy.reload();
    cy.logout;
  }
  it('test1', () => {
    expect(true).to.equal(true)
  })
  it('test2', () => {
    expect(true).to.equal(true)
  })
})
```

### Current behavior:

in the `cy.logout` method defined, `cy.click()` failed because it requires a Dom element. I increased the timeout from its default of 4 seconds to 30 seconds in order to give it some time in case it requires some time to find the Dom element but still the after each block fails from time to time and I am not sure why.

### Desired behavior:

I expect that the after each should always pass since all what it does is just reload then logout after each test.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please provide the code that is used to define your `cy.login()` method and `cy.logout()` method so that we can run the test and see the error - also any application code required.

Please comment in this issue with a reproducible example and we will consider reopening the issue.
