### ISSUE TITLE
Add ability to split long spec to multiple videos

### ISSUE THREAD

**Issue by mikila85** [cypress-io/cypress#8248]
### Current behavior:

Video starts recording on beginning of the spec.
Video stops recording on the end of the spec.

### Desired behavior:

Add ability inside the spec at a specific point to tell cypress to split video for example:
`cy.splitVideoRecording("step2")`

resulting in:
File 1: 
`login.spec.ts.mp4`
File 2:
` login.spec.ts_step2.mp4`

**Comment by jennifer-shehane** [comment]
Our Dashboard allows you to jump to the exact point in the video of any specific test within your suite.

<img width="1334" alt="Screen Shot 2020-08-12 at 1 31 01 PM" src="https://user-images.githubusercontent.com/1271364/89984899-2614d900-dca0-11ea-94d8-9e5d7896929c.png">

Additionally, we provide the videoTimestamp of each test in the [`cypress.run`](https://on.cypress.io/module-api#cypress-run) results, so you could take this info and splice up the video after the run however you like. 

Can you explain more about why you want this feature? 

As it stands I don't see this as being something we would pursue implementing since you can already jump to any failure or test in the Dashboard and the ability to splice up the video to your own configuration exists.

**Comment by jennifer-shehane** [comment]
Adding this feature is not something we see as within our scope of feature work, so we will be closing this issue. We will reconsider and reopen if we see this issue gains more 👍 or comments in support.
