### ISSUE TITLE
Visibility of mocha hook titles in the runner

### ISSUE THREAD

**Issue by mccataldo** [cypress-io/cypress#8252]
### Behavior (Current and Desired)

Mocha hook titles aren't visible in the runner and I believe it would be a valuable addition.

Example:
`support/index.js`
```js
// global pre-hook
beforeEach('auth/login, setup initial app state', () => {
  ...
})
```
`integration/some-test.spec.js`
```js
...
beforeEach('setup some data for the test', () => {
...
})
```
The hook title should fit nicely directly to the right of the hook name in the header:
![Screen Shot 2020-08-11 at 10 16 22 AM](https://user-images.githubusercontent.com/14354013/89922556-6ef36180-dbbc-11ea-8fed-01838cb6bdda.png)

### Versions

Displaying Cypress info...

1. Chrome
  - Name: chrome
  - Channel: stable
  - Version: 84.0.4147.105
  - Executable: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

Proxy Settings: none detected
Environment Variables: none detected

Cypress Version: 4.12.1
System Platform: darwin (19.6.0)

**Comment by jennifer-shehane** [comment]
Interesting. I can see this being helpful, especially since we now split up all of the hooks so that they individually show in the UI instead of being all grouped together. It would make it easier to tell which hook the code came from. 

If you hover over the hook (BEFORE EACH) - there will be a button to 'Open in IDE', this is a great way to jump to the definition currently if your in `cypress open`.

<img width="510" alt="Screen Shot 2020-08-12 at 12 43 26 PM" src="https://user-images.githubusercontent.com/1271364/89981192-7b99b780-dc99-11ea-8b23-864c644f22c6.png">

**Comment by Manuel-Suarez-Abascal** [comment]
@jennifer-shehane is there any progress on this issue? It would be helpful for debugging purposes. If this is not a priority for the team, I would love to tackle this issue. I got two questions:

- Can you point me to the relevant sections in the codebase to accomplish this?
- Do you UI design for it?
