### ISSUE TITLE
Stubbing window.location.reload() doesn't seem to work

### ISSUE THREAD

**Issue by spacewaffle** [cypress-io/cypress#8266]
### Current behavior:

I have a button that fires an ajax request when clicked, then when it receives the response, it reloads the page using `window.location.reload()`. I'm attempting to stub the function `window.location.reload()` to prevent a page reload during the test like so
```js
    cy.window().then(win => {
      //neither of these variations work
      cy.stub(win.location, 'reload').as("locationReload");
      cy.stub(win, 'location.reload').as("locationReload");
    })
```

The issue is this will cause an error and the test will fail causing the following error messages:

Error message for stubbing (win.location, "reload")
![Screen Shot 2020-08-12 at 6 38 16 PM](https://user-images.githubusercontent.com/1930218/90075355-27a7c680-dccb-11ea-87ab-67bfc3249985.png)
Error message for stubbing (win, "location.reload")
![Screen Shot 2020-08-12 at 6 41 44 PM](https://user-images.githubusercontent.com/1930218/90075491-82d9b900-dccb-11ea-9914-b8b6492a5a83.png)

### Desired behavior:

page does not reload during test, `window.location.reload()` is properly stubbed without errors.

### Test code to reproduce

Here's a fork with an example that shows stubbing `window.open` works fine but `window.location.reload()` errors.
https://github.com/spacewaffle/cypress-test-tiny

### Versions

cypress: 4.10.0
os: osx 10.14.5
browser: chrome 84

**Comment by jennifer-shehane** [comment]
This seems to be due to `window.location.reload` being non-writable and non-configurable. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Description

You could in your app define and call a function, like `winReload` which calls `window.location.reload()` inside of it - and then in your test, test that the call to your function was made. This would test that the call is being made.
