### ISSUE TITLE
Uploading results on Dashboard: The run started, but never completed.

### ISSUE THREAD

**Issue by mgavrila** [cypress-io/cypress#8278]
### Current behavior:
Running tests by using record option generates Timed Out even though tests are running.

### Desired behavior:
Should upload results to dashboard
![image](https://user-images.githubusercontent.com/23659869/90232678-b3ce0100-de25-11ea-9c57-f1d6313ea84c.png)
![image](https://user-images.githubusercontent.com/23659869/90232929-03acc800-de26-11ea-9e2a-ae1a08a0482e.png)
![image](https://user-images.githubusercontent.com/23659869/90233076-3951b100-de26-11ea-968b-557819caa1b6.png)

Upload to dashboard should be done

### Test code to reproduce
From what i've observed, all my tests were Timed Outed when a test ran more than 1 hour and 30 minutes. The Timed Out in dashboard appeared in the test runtime. Dashboard received Timed Out but my tests continued to run. Screenshots were taken and video continued to be compressed so this eliminates the scenarios in which test didn't started / test crashed.

### Versions

4.10.0

**Comment by jennifer-shehane** [comment]
@mgavrila 

- Is it normal for your specfile to run more than 1.5 hours? Why is it taking 2 hours to run?
- Was there something changed in your run where this just began happening?
- Does this happen on all of your runs?
- Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by mgavrila** [comment]
> Is it normal for your specfile to run more than 1.5 hours? Why is it taking 2 hours to run?
Yes it is normal due to numerous steps being done in each test. 

> Was there something changed in your run where this just began happening?
There was nothing changed in the run

> Does this happen on all of your runs?
Yes, it happened on all my run which had a run time more than 1 hour and 30 minutes as seen in the following picture. All these tests were run with the same spec file. The difference between the timed out ones versus the ones that failed is the number of tests. In the timed out one it ran 16 tests while in the failed ones ran 10 tests.
![image](https://user-images.githubusercontent.com/23659869/90237354-d31c5c80-de2c-11ea-9bfd-2498da13674a.png)

> Could you run Cypress in debug mode mode and print the entire set of logs here?
For this i'll have to run a new test. It will take some time to get you this information

**Comment by mgavrila** [comment]
@jennifer-shehane 
Update with more screenshots:
![image](https://user-images.githubusercontent.com/23659869/90259995-92840980-de53-11ea-86ff-3a131dcf17f4.png)
![image](https://user-images.githubusercontent.com/23659869/90260156-ca8b4c80-de53-11ea-96e8-7cbd51945efd.png)
![image](https://user-images.githubusercontent.com/23659869/90260259-ea227500-de53-11ea-99bc-ec51a6e272c2.png)
![image](https://user-images.githubusercontent.com/23659869/90260417-20f88b00-de54-11ea-9f6c-c99474ef5423.png)

I've attached debug using https://github.com/bahmutov/cypress-failed-log .
There is nothing in logs which may reflect the cause of this issue.

I've done several tests from which:
- created a test run and aborted the test from VSCode terminal in which will force the dashboard to display the test as running. I did this to see how long the dashboard will get Timed Out. The answer to this was the same, 1 hour and 30 minutes  (between 30 and 37 it's pretty random).
- all tests that i ran never got passed this amount of time
- in the screenshots above as we can see dashboard timed out at test 12/16. I've looked into it on chrome and the test was still running. After some time i've stopped the test and they were put as skipped.

**Comment by jennifer-shehane** [comment]
If a run does not issue it's exit code or signal back that a new spec file is running within 90 minutes - the run will time out. This is expected behavior. 

Cypress requires some sort of signal within these 90 minutes or we assume something has gone wrong and will close the run. 

We strongly recommend that you do not run any single specfile longer than 90 minutes. Although I will forward this feedback to our API team to see if they have any plans to change this behavior.

**Comment by jennifer-shehane** [comment]
I've spoken with the team. There are no plans currently to support recording specs longer than 90 minutes. I have added your feedback to our [Dashboard Product Board](https://portal.productboard.com/cypress-io/1-cypress-dashboard) for consideration for our engineering team there.

You can express interest in this feature and see it's progress on our Roadmap from our Dashboard's new product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

This issue will be closed since issues regarding our Dashboard are tracked separately as linked above.
