### ISSUE TITLE
Can cypress output Puppeteer code?

### ISSUE THREAD

**Issue by WinstonN** [cypress-io/cypress#8291]
I love writing code using cypress
Unfortunately for load testing I have to use puppeteer - see https://github.com/cypress-io/cypress/issues/1232
My question is, is it possible for Cypress to output a whole test in puppeteer code, using a plugin, or otherwise?

**Comment by jennifer-shehane** [comment]
See https://github.com/cypress-io/cypress/issues/2427

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.

**Comment by jennifer-shehane** [comment]
We've released an official Puppeteer plugin, to make puppeteer calls from within Cypress: https://github.com/cypress-io/cypress/tree/develop/npm/puppeteer

Please leave any feedback here: https://github.com/cypress-io/cypress/discussions/28410
