### ISSUE TITLE
Implementation responsively

### ISSUE THREAD

**Issue by enieber** [cypress-io/cypress#8304]
This project is very nice and much useful and I wanna use this project together [responsively browser](https://github.com/responsively-org/responsively-app)

This is possible?

**Comment by jennifer-shehane** [comment]
We only guarantee Cypress to work in the browsers listed here: https://on.cypress.io/launching-browsers#Browsers

That being said you can add browsers by following these instructions: https://on.cypress.io/launching-browsers#Customize-available-browsers It may work for other chromium-based browsers. It likely won't work for others out of the box though.

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
