### ISSUE TITLE
webpage not loading with cy.visit() for the URL having /#/login

### ISSUE THREAD

**Issue by leelavathi2592** [cypress-io/cypress#8306]
<img width="501" alt="git" src="https://user-images.githubusercontent.com/69853562/90515390-32a59f80-e180-11ea-92b6-7b2b8714dd69.PNG">

### Current behavior:

Web page not loading

### Desired behavior:

it should load the page and login page should be visible

### Test code to reproduce
```js
describe('My First Test',() => {
  it('logs in',() => {
    cy.visit('url')
    cy.wait(32000)
    cy.get('input[name=username]').type('test1234')
    cy.get('input[name=password]').type('Test1234{enter}')
    cy.get('[type=Submit]').click()
  })
})
```

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example and we will consider reopening the issue.

**Comment by leelavathi2592** [comment]
Am trying to Load a page with URL having hash(#) .But am getting Auto Focusing Error.

In lower version of Chrome Its working fine(78).In latest version its not supporting 
Any Solution or work around this in latest version of Chrome
