### ISSUE TITLE
Microsoft Single Sign On with "chromeWebSecurity": false not working

### ISSUE THREAD

**Issue by steenstn** [cypress-io/cypress#834]
- Operating System: Windows
- Cypress Version: 1.0.2
- Browser Version:  61.0.3163.100

### Is this a Feature or Bug?
Maybe bug?

### Current behavior:
In our project we're using SSO and Azure AD so the flow is
- Goto web page
- Get directed to login.microsoftonline.com (here another redirect happens to login.<ourdomain>.net)
- Enter username. Since you're logged in with your account on the computer you don't have to enter your password.
- Get logged in to the web page. Your browser now has a couple of cookies with tokens.

This of course doesn't work due to the limit on staying in one domain. But I thought that putting `"chromeWebSecurity": false` would allow jumping around inbetween different domains but the test starts and when the redirect happens the test window disappears and I'm left with a browser window with the url `https://login.microsoftonline.com/__/` and the text `Whoops, there is no test to run.`

So is it the case that disabling chromeWebSecurity doesn't mean "Get redirected as much as you want"? I tried it with a simple html page that redirects to another domain and that worked.

I've tried going the cy.request()-route and tried reproducing the requests made in the login flow but so far I've been unsuccessful. I also tried "hardcoding" the cookies by logging in manually, looking at the cookies and writing a cypress test that sets the same cookies before goin to the page. But when I then do cy.visit('<our-web-page>') I'm still redirected to login.microsoft.com and the test window disappears.

Doing a cy.visit directly on the login.microsoft.com-url also gives me the `Whoops, there is no test to run` screen

### Expected behavior
I would expect the test window to not disappear so that I would be able to get some debugging information.
I would also expect "chromeWebSecurity": false to enable redirecting to be able to do the SSO. Or is that not the way it's designed?

Or if someone has struggled with the same problem I'd be happy to get some help how to complete the SSO using cy.request().

**Comment by brian-mann** [comment]
The problem is most definitely that the Windows site is not under your control and has employed security restrictions that prevent Cypress from working.

Visiting or interacting with 3rd party content is a common anti-pattern and the workaround is to always use `cy.request` for interacting with the party in order to isolate getting just the token part.

I think you are on the right track that you should just set the cookie / session stuff directly (and that will work). If you're being redirected by the client or server it's likely due to it **not** having the right session information to work. Perhaps the cookies are domain based cookies instead of host-only.

Check to see if Windows has a published SSO API that you can use directly with `cy.request`. I am sure they do. Use those API's and you'll avoid ever needing your UI to utilize their services - which insulates you from changes on their end. It'll also make testing much much faster.

Here's the anti pattern for reference.

https://docs.cypress.io/guides/references/best-practices.html#Visiting-External-Sites

Also please check out our SSO recipes that show this in action.

https://docs.cypress.io/examples/recipes/logging-in-recipe.html#Single-Sign-On

I'm going to close this issue as there is nothing that can be done on our part. We could deploy strategies to remove the javascript code causing Cypress to be redirected but even if we did there is a better approach and you shouldn't ever use the UI to accomplish this.
