### ISSUE TITLE
Feature request: tag-based posting of slack messages

### ISSUE THREAD

**Issue by SanderMeesterIndepender** [cypress-io/cypress#8345]
### Current behavior:

You now only have the option to send either All runs or Failed runs only to a certain slack channel.

### Desired behavior:

I want to be able to send failed runs to a certain channel ONLY when a certain tag is available.

e.g.: when tag is "Apple" or "Pear", send message to #Fruit (and on top of this te current option to have All runs or Failed only)

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comments from this issue there. Please refer all future comments there. Thank you.
