### ISSUE TITLE
How to install Cypress for CI/CD pipeline

### ISSUE THREAD

**Issue by Jhonatangiraldo** [cypress-io/cypress#8348]
### Current behavior:
In Jenkins, every time I install the dependencies it tries to download the huge cypress binaries

### Desired behavior:
Have a way to cache the cypress binaries and use it, so **npm i** or **yarn** only would install other packages not taking up so much time

### Versions
12.1.0

### Note
Sorry, I know this is a question, but not in the documentation neither in any blog or channel is an appropriate standard to solve this problem. Waiting for 20 minutes to download cypress every time I run the pipeline is not an option for the team

**Comment by jennifer-shehane** [comment]
See our advanced instructions for installing cypress https://on.cypress.io/installing-cypress#Advanced and caching in CI: https://on.cypress.io/continuous-integration#Caching

Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
