### ISSUE TITLE
cypress run with firefox browser is toooooooooooo slow for page loading!!!!!

### ISSUE THREAD

**Issue by mehrabadi1366** [cypress-io/cypress#8355]

**Comment by mehrabadi1366** [comment]
i want to test a web page with cypress. this page is ok with electorn Test but with firefix page loading is tooo slow, do you know why?

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
