### ISSUE TITLE
Migrating to 5.0.0 : Can't resolve 'async_hooks'

### ISSUE THREAD

**Issue by CodeTroopers** [cypress-io/cypress#8375]
I'm just migrating from 4.12.1 where all works to 5.0.0

### Current behavior:
The test doesn't start and an error message is displayed

> Error: Webpack Compilation Error
> ./node_modules/bluebird/js/release/promise.js
> Module not found: Error: Can't resolve 'async_hooks' in '/e2e/node_modules/bluebird/js/release'
> resolve 'async_hooks' in '/e2e/node_modules/bluebird/js/release'
>   Parsed request is a module
>   using description file: /e2e/node_modules/bluebird/package.json (relative path: ./js/release)
>     Field 'browser' doesn't contain a valid alias configuration
>     Looked for and couldn't find the file at the following paths:
> [/e2e/node_modules/bluebird/js/release/node_modules]
> [/e2e/node_modules/bluebird/js/node_modules]
> [/e2e/node_modules/bluebird/node_modules]
> [/e2e/node_modules/node_modules]
> [/e2e/node_modules]
> [/node_modules]
> [/e2e/node_modules/async_hooks]
> [/e2e/node_modules/async_hooks.js]
> [/e2e/node_modules/async_hooks.json]
> [/e2e/node_modules/async_hooks.jsx]
> [/e2e/node_modules/async_hooks.coffee]
> [/e2e/node_modules/async_hooks.ts]
> [/e2e/node_modules/async_hooks.tsx]
>  @ ./node_modules/bluebird/js/release/promise.js 34:4-26
>  @ ./node_modules/bluebird/js/release/bluebird.js
>  @ ./node_modules/auth0/src/utils.js
>  @ ./node_modules/auth0/src/auth/index.js
>  @ ./node_modules/auth0/src/index.js
>  @ ./cypress/support/LoginCredentials.ts
>  @ ./cypress/support/commands.ts
>  @ ./cypress/support/index.ts

### Test code to reproduce
We use auth0 api, if i comment this lines the test works:

```js
import { ManagementClient } from 'auth0';

export class Auth0Service extends RequestService {
	private auth0!: ManagementClient;

	public constructor() {
		super();
		this.getToken();
	}

	private getToken() {
		this.auth0 = new ManagementClient(AUTH);
	}
}
```
### Versions

Cypress: 5.0.0
OS: macOS Catalina 10.15.6
Chrome: 84.0.4147.135
Node: 12.16.2

**Comment by jennifer-shehane** [comment]
I'm not able to recreate the issue as described. Please provide all code necessary to recreate the issue. 

**Code I ran**

The code below runs fine without any webpack errors during `cypress open`.

`cypress/support/index.ts` (assumed this is where that code is since you didn't say

```ts
import { ManagementClient } from 'auth0';

export class Auth0Service extends RequestService {
  private auth0!: ManagementClient;

  public constructor() {
    super();
    this.getToken();
  }

  private getToken() {
    this.auth0 = new ManagementClient(AUTH);
  }
}
```

`package.json`

```json
{
  "devDependencies": {
    "auth0": "^2.27.1",
    "cypress": "5.0.0",
    "typescript": "^4.0.2"
  }
}

```

**Comment by CodeTroopers** [comment]
I reproduce with this tsconfig.json in the cypress directory
```
{
	"compilerOptions": {
		"baseUrl": "../node_modules"
	},
	"include": ["**/*.ts"]
}
```

Not sure why I have this baseUrl option but it works with cypress 4.12.1

**Comment by jennifer-shehane** [comment]
Yeah, I'm not exactly sure what I changed since I last ran this, but I am able to recreate this now. Maybe I was running in the older version accidentally.

`cypress/support/index.ts` (assumed this is where that code is since you didn't say

```ts
import { ManagementClient } from 'auth0';

export class Auth0Service extends RequestService {
  private auth0!: ManagementClient;

  public constructor() {
    super();
    this.getToken();
  }

  private getToken() {
    this.auth0 = new ManagementClient(AUTH);
  }
}
```

`package.json`

```json
{
  "devDependencies": {
    "auth0": "^2.27.1",
    "cypress": "5.0.0",
    "typescript": "^4.0.2"
  }
}
```

<img width="1490" alt="Screen Shot 2020-08-26 at 5 47 31 PM" src="https://user-images.githubusercontent.com/1271364/91297382-3e1e4980-e7c4-11ea-92ba-656850cfcd5e.png">

This specific error actually appears to be fixed in our next release already, but when running in our next release, there's this error thrown with the code above, which seems legitimate since this is not defined.

<img width="829" alt="Screen Shot 2020-08-26 at 5 49 24 PM" src="https://user-images.githubusercontent.com/1271364/91297594-95241e80-e7c4-11ea-99ae-7e24a0da34da.png">

Closing as this is pending release.
