### ISSUE TITLE
Cypress 5: CypressError not displaying

### ISSUE THREAD

**Issue by rwinsphoto** [cypress-io/cypress#8383]
### Current behavior:

Running tests in Chrome 70 in Cypress Open after upgrading to Cypress 5 will not show any details of the error.

![test](https://user-images.githubusercontent.com/49311093/90956738-4179a400-e457-11ea-9e6d-956f5270eaa3.png)

### Desired behavior:

A description of Cypress error messages (ex. timeout, element not found, etc.)

### Test code to reproduce

```js
cy.visit('', { retryOnStatusCodeFailure: true, log: true })
cy.get('input#inpUsername', { timeout: 2000 }).type(username)
cy.get('input#inpPassword').type(password)
cy.get('button#btnLogin').click()
cy.wait(500)
cy.get('#lblTitle', { timeout: 14000 }).should('contain', 'Home')
```

### Versions

Cypress 5, Windows 10, Chrome 70

**Comment by jennifer-shehane** [comment]
Unfortunately we'll have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example. As this is now, there is no application to run the test code against, so we can't recreate it. Please also provide any cypress.json, support, or plugins code required to recreate.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
