### ISSUE TITLE
Flaky percy snapshot in internal tests

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#8390]
### Current behavior:
One of our internal percy snapshots is flaky. Seems to fail a lot in PRs.

Percy: https://percy.io/cypress-io/cypress/builds/6620394

![](https://user-images.githubusercontent.com/1271364/91033140-ea2b2d80-e628-11ea-8acd-b697e4bc749e.png)

### Versions
5.0.0

**Comment by brian-mann** [comment]
@Bkucera the DOM is not ready when we're taking the percy snapshot. Remember me talking about this? You're guarding against the number of passes in the HEADER (so you can see they're both 2)... but react has not rendered the DOM for the 2nd test because you're not adding a guard there.

If you add the guard it will consistently pass.

**Comment by jennifer-shehane** [comment]
Closing as resolved.
