### ISSUE TITLE
Timed out retrying: Expected to find element, but never found it, While the element does exist

### ISSUE THREAD

**Issue by flora8984461** [cypress-io/cypress#8393]
### Current behavior:

Cypress keeps throwing error saying `Timed out retrying: Expected to find element: [data-testid=publishActivitiesBtn], but never found it`  while the element is there, and the recommendation also recognizes it.

![image](https://user-images.githubusercontent.com/39588094/91071303-036eb280-e606-11ea-939d-618a154565c6.png)

### Desired behavior:

This does not make sense, its recommendation is also suggesting me to use this data-testid. I also tried with cy.get('[data-testid="publishActivitiesBtn"]'). 

But I have tried with a simple sample with material UI Modal testing, it can recognize the button on the modal. 

I really do not understand what could be the possible reasons causing this? 

### Versions

Cypress 5.0.0
OP: windows 10
browser: chrome
The modal is material UI 4.11.0

Thanks a lot for your help!

**Comment by jennifer-shehane** [comment]
Generally this will happen when there is some asynchronous behavior - the button doesn't exist while it's loading, so you generally want to write an assertion to ensure the popup is completely shown. But the element exists after the test runs, which is why it is found in the selector playground.

Writing cy.wait() is not a recommended way of handling this. 

You may want to review our blog post on ['When can the test click'](https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/), it walks through some best practices on waiting to assert things exist in the DOM. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by flora8984461** [comment]
> Generally this will happen when there is some asynchronous behavior - the button doesn't exist while it's loading, so you generally want to write an assertion to ensure the popup is completely shown. But the element exists after the test runs, which is why it is found in the selector playground.
> 
> Writing cy.wait() is not a recommended way of handling this.
> 
> You may want to review our blog post on ['When can the test click'](https://www.cypress.io/blog/2019/01/22/when-can-the-test-click/), it walks through some best practices on waiting to assert things exist in the DOM.
> 
> Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.
> 
> Please comment in this issue with a reproducible example and we will consider reopening the issue.

Thank you so much for your help, I will try the way you suggested.
