### ISSUE TITLE
Not generate test result for all file test

### ISSUE THREAD

**Issue by nam-np** [cypress-io/cypress#8427]
### Current behavior:

- Generate only lastest test result

### Desired behavior:

- I have multiple file test (.spec.js).
- I want to have multiple test result but have only lastest test result. (results-0c1b99ef352beae5502e2e3163f89eda.xml)

### Test code to reproduce
cypress.json
```json
{
  "reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "configFile": "reporter-config.json"
  }
}
```

`reporter-config.json`

```json
{
  "reporterEnabled": "spec, mocha-junit-reporter",
  "mochaJunitReporterReporterOptions": {
    "mochaFile": "cypress/results/results-[hash].xml"
  }
}
```

package.json
```json
{
  "scripts": {
    "delete:reports": "rm cypress/results/* || true",
    "prereport": "npm run delete:reports",
    "report": "cypress run --reporter cypress-multi-reporters --reporter-options configFile=reporter-config.json"
  }
}
```

And run
```
npm run report
```
### Versions
4.7.0

**Comment by jennifer-shehane** [comment]
Issues in our GitHub repo are reserved for potential bugs or feature requests. This issue will be closed since it appears to be neither a bug nor a feature request.

We recommend questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers.
