### ISSUE TITLE
Cannot install Cypress 5.0 with Node v11

### ISSUE THREAD

**Issue by danmaftei** [cypress-io/cypress#8429]
#8407 # Current behavior:

```
(foo) yarn install
yarn install v1.22.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error cli-table3@0.6.0: The engine "node" is incompatible with this module. Expected version "10.* || >= 12.*". Got "11.15.0"
error Found incompatible module.
```

### Desired behavior:

Successful install. Migration docs state that Cypress 5.0 can be installed with Node versions >= 10.

### Versions

Cypress 5.0
Node 11.15.0
OS X 10.15.6

**Comment by jennifer-shehane** [comment]
Node.js's odd number releases reach their end of life after 6 months with Node.js 11's being end of life on June 1, 2019. I suppose we do technically say that we support 10+, I guess it's an assumption in the community that older odd numbered versions are not supported within that. 

Our goal is to not support Node.js versions that have reached end of life essentially. I think we'll update the docs to reflect this instead of changing the behavior of Node.js support in the product.

**Comment by jennifer-shehane** [comment]
Opened a PR in our docs to be more specific about this https://github.com/cypress-io/cypress-documentation/pull/3108
