### ISSUE TITLE
Cypress fails in open mode but not in run mode

### ISSUE THREAD

**Issue by carlos-salgado** [cypress-io/cypress#8456]
### Current behavior:

Cypress fails when I execute in Open mode by a console error, that is good, but in "run" mode (CLI) cypress does not fail, leading me to false positives because at this moment we have an error in the test system that we want to be found with the tests.

**Open Mode** - fails with console error it's ok...

![image](https://user-images.githubusercontent.com/66172416/91788057-e1120180-ebd0-11ea-8e5a-6beb023c108c.png)

**Run Mode (CLI)** : Cypress dont fail :( it's bad

![image](https://user-images.githubusercontent.com/66172416/91788149-11f23680-ebd1-11ea-8aec-d9067582500f.png)

### Desired behavior:

should fail if there is an error in console in "run" mode

### Versions

Cypress 5.0
Linux Manjaro -- Manjaro 20.1 Mikah
Chrome : Chrome 85 (headless)

**Comment by Bkucera** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example and we will consider reopening the issue.
