### ISSUE TITLE
suggestion - esbuild preprocessor

### ISSUE THREAD

**Issue by sod** [cypress-io/cypress#8492]
### Current behavior:

cypress supports and suggest webpack preprocessor

### Desired behavior:

cypress may suggest using esbuild as a preprocessor instead https://github.com/evanw/esbuild. esbuild is a bundler written in go and thus 50 to 100 times faster as webpack. We reduced the cypress startup from 50s to 7s in our test suite with it.

### Test code to reproduce

Here is a sample that uses esbuild as a preprocessor. So it's actually pretty easy to use it right now:

```sh
git clone git@github.com:sod/cypress-test-tiny.git
cd cypress-test-tiny
npm ci
npm start
```

And see how ridiculously fast it crunshes through the files

![image](https://user-images.githubusercontent.com/905328/92126768-dc339480-ee00-11ea-8091-968902a16e2a.png)

All what was needed to make it work was this commit: https://github.com/sod/cypress-test-tiny/commit/b49abe3873422f7f03ec2de46814c10dcb14a80e

It even understands typescript. If you give the plugin a tsconfig like

```typescript
    on('file:preprocessor', esbuildPreprocessor({
        tsconfig: path.resolve(__dirname, '../../../../tsconfig.json'),
    }));
```

it even automatically understands the path mappings configured in there.

We use it in our project with typescript, and when you press "start" in the gui to run all tests, the webpack preprocessor took 50 seconds from "click" to "tests start running"

With this esbuild preprocessor, thats down to 7 seconds - where most of that time left is actually spent starting chrome.

### Versions

5.0

**Comment by sod** [comment]
Moved the thing into a package https://www.npmjs.com/package/cypress-esbuild-preprocessor

I guess there is no need to support it native in cypress :)

**Comment by ncknuna** [comment]
I left a comment on `cypress-esbuild-preprocessor`, but just in case folks are more likely to see comments here, or if there's some additional work needed on the cypress side:

This preprocessor is really awesome, thanks for building it! My build times went from 90s -> ~1s!

However, because of the way that esbuild handles CSS files, when I try to write component unit tests with Cypress using the @cypress/react (https://www.npmjs.com/package/@cypress/react , aka cypress-react-unit-test) package, the components I'm testing don't end up with their associated CSS files, so everything is unstyled. As someone who hasn't written a cypress plugin and is new to esbuild, I'm a bit lost as to how to make it work. Would you be open to adding CSS support in this preprocessor for @cypress/react, or point me in the right direction so I can add it? Thanks!!

Minimal repro repo here: https://github.com/ncknuna/cypress-react-esbuild

**Comment by ncknuna** [comment]
@bahmutov , @sod got back to me on the issue I filed on the preprocessor package: https://github.com/sod/cypress-esbuild-preprocessor/issues/1 . Do you think you could give me some guidance on if there are any gotchas on the @cypress/react side before I dig into this? 

Seems like this could be a way to increase adoption of the @cypress/react project, which I really want to thrive :)

**Comment by sod** [comment]
https://blog.checklyhq.com/cypress-vs-selenium-vs-playwright-vs-puppeteer-speed-comparison/

I wonder how this perception on this viral blog post now burns in peoples head. The startup time is just as good as the other tools if you use esbuild instead of webpack.
