### ISSUE TITLE
Chrome hangs on application open intent with --waiting for new page to load--

### ISSUE THREAD

**Issue by kohakukun** [cypress-io/cypress#8496]
### Current behavior:

Cypress waits indefinitely for window prompt

![image](https://user-images.githubusercontent.com/4264247/92146063-6f78c400-ee19-11ea-9a17-ebf171cc5949.png)

### Desired behavior:

Testing commands should continue to execute regardless of the opened window

### Test code to reproduce

Given we have an html defined using react (not using jsx to make it easier to run in a generic environment)

```html
ReactDOM.render(React.createElement(
  'a',  {href:"vscode://someurl", 'data-cy':"testing-app"},
  "TESTING CYPRESS"
  ), document.getElementById('main-container'));
```
or in HTML
```html
<a href="vscode://someurl" data-cy="testing-app">TESTING CYPRESS</a>
```

The follow test fails to pass
```javascript
       it('does not work', () => {
          cy.visit('/')
          cy.get('[data-cy="testing-app"]').click();
          cy.get('[data-cy="testing-app"]').should('exist');
        });
```

### Versions

Cypress: 5.10.0, 4.10.0
MacOS: Catalina 10.15.6
Browsers: Chrome 84

**Comment by Bkucera** [comment]
Do you have a baseUrl set in cypress.json?

**Comment by falgun2411** [comment]
![image](https://user-images.githubusercontent.com/39234337/93003591-473b4480-f540-11ea-8f2b-8e0b92304275.png)

I am working on cucumber 
    "cypress": "^4.12.1",
    "cypress-cucumber-preprocessor": "^2.5.0",

Case:
Click on show more results button --> new results gets loaded .
But once you click on show more results ( Just within cypress - Cypress is completely stuck and does not timeout ) , so my automation case gets failed.

Actual web-application works fine.

Versions
Cypress: 5.10.0, ^4.12.1,
Windows 10 
Browsers: Chrome 85 , All browsers + headless mode

**Comment by Bkucera** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment in this issue with a fully reproducible example and we will consider reopening the issue.

**Comment by kohakukun** [comment]
@Bkucera I do have a base url. I also modified the example to be reproducible

**Comment by Bkucera** [comment]
thanks for the reproducible, reopened. What is the expected behavior? I assume you're asking Cypress to auto-accept the prompt

**Comment by kohakukun** [comment]
Well, regardless of the prompt, I'm more interestetd cypress asserting the next command. In this case, the test never finishes

**Comment by Bkucera** [comment]
I recommend asserting that the link has the proper url instead of clicking it if you'd like to test this scenario. Although we should handle this in a clearer way, there's no added test coverage by clicking the link vs asserting on the DOM, so this is low priority.

**Comment by kohakukun** [comment]
The issue is that we do other operations after that, so I'm interested in the test continuing beyond that

**Comment by Bkucera** [comment]
@kohakukun What do you mean "after that"? My recommendation was to simply replace the `.click()` with a `.its('href').should('include', 'vscode://')`, and the rest of the test can remain as normal.

**Comment by kohakukun** [comment]
The assertion after the click `cy.get('[data-cy="testing-app"]').should('exist');` is never executed. In the provided example, it is a trivial assertion but, in my use case, I need to continue interacting with the app after the button for opening the application is clicked. I understand that we cannot control the prompt window but, I would expect cypress to continue with the following commands

**Comment by jepetko** [comment]
I'm referring to this as it is a real blocker for testing business applications. Let's consider a typical scenario:

**A** (base url for Cypress tests) -> **B** (OAuth login form) -> **A** (redirect uri for OAuth). A and B don't share the same site.

* A = https://app.mydomain.com
* B = https://login.provider.com

Note that:
* I cannot use Chrome out of security reasons (despite `disableWebSecurity = true` I have to hack `X-frame-options` using a Chrome extension for fixing "Refused to display 'https://login.provider.com' in a frame because it set 'X-Frame-Options' to 'deny'." This happens because Cypress loads the application into an iframe. Unfortunately, I'm not allowed to load the according Chrome extension due to a corporate policy.)
* In Firefox I'm able to bypass the security measures (X-frame-options, Same-Site policy etc.). Now, I'm looking for the proper preferences to bypass also the cross origin check (see below).
* manual OAuth flow behind the scenes (described in https://docs.cypress.io/guides/guides/web-security.html#Form-Submission-Redirects) is not really possible due to additional security measures such as XSRF token etc.

With the following test, I can navigate to the OAuth login form hosted on domain B (meaning: I can see the rendered page):

```
  cy.server();
  cy.route('https://login.provider.com/**').as('oauth');

  getLoginButton().click(); // this navigates to https://login.provider.com/login

  cy.wait('@oauth');
```

however, then I also see this warning 

```
(page load)--waiting for new page to load--
```

If I manually finish the OAuth flow using valid credentials (of course I have to do it within the timeout) then the state of that line turns to 

```
"(page load)--page loaded--".
```

The state of the application is correct, I successfully finished the OAuth flow and the application has a correct state.

But Cypress shows this error:

```
Cypress detected a cross origin error happened on page load:

  > Permission denied to access property "document" on cross-origin object

Before the page load, you were bound to the origin policy:

  > https://mydomain.com

A cross origin error happens when your application navigates to a new URL which does not match the origin policy above.

A new URL does not match the origin policy if the 'protocol', 'port' (if specified), and/or 'host' (unless of the same superdomain) are different.

Cypress does not allow you to navigate to a different origin URL within a single test.

You may need to restructure some of your test code to avoid this problem.

Alternatively you can also disable Chrome Web Security in Chromium-based browsers which will turn off this restriction by setting { chromeWebSecurity: false } in cypress.json.Learn more

The stacktrace is:

```
    at onPageLoadErr (https://app.mydomain.com/__cypress/runner/cypress_runner.js:156215:18)
    at initialize (https://app.mydomain.com/__cypress/runner/cypress_runner.js:168094:18)
    at dispatch (https://app.mydomain.com/__cypress/runner/cypress_runner.js:90364:28)
    at add/elemData.handle (https://app.mydomain.com/__cypress/runner/cypress_runner.js:90172:29)
From previous event:
    at run (https://app.mydomain.com/__cypress/runner/cypress_runner.js:167762:20)
    at addCommand/cy[name] (https://app.mydomain.com/__cypress/runner/cypress_runner.js:168214:12)
    at runTest (../../node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js:47:1)
	...
```

I think some of the Firefox preferences could fix it. Do you know what is the counterpart of `disableWebSecurity` when running Firefox? I found https://bugzilla.mozilla.org/show_bug.cgi?id=1039678 which is still open but I assume that some combination of FF preferences could provide the same behavior.

**Comment by RadwaSaleh** [comment]
I have the same issue and it totally blocks feature e2e testing

**Comment by benjaminpinto** [comment]
Same bug here.

**Comment by venu2589** [comment]
As an alternate try using the mouse event here.

For instance, 
cy.get('[data-cy="testing-app"]').trigger("click")

**Comment by vertocode** [comment]
Same bug here, can someone help us, please? 

Cypress version: 9.3.1

I get the 'waiting for the page loading' error when I run GitHub actions visiting 2 different domains, but locally it works... do we have a problem when using GitHub actions and 2 different domains that can cause this? it seems that everything is ok when we try it locally, but when we see the video that the cypress dashboard shows us, we have an infinite loading that only happens there.

**Comment by benjaminpinto** [comment]
@vertocode take a look on this: https://medium.com/@benjaminpinto/cypress-waiting-for-a-page-to-load-after-downloading-a-file-quick-fix-210d89a02e1a

Hope it helps.

**Comment by vertocode** [comment]
> @vertocode take a look on this: https://medium.com/@benjaminpinto/cypress-waiting-for-a-page-to-load-after-downloading-a-file-quick-fix-210d89a02e1a
> 
> Hope it helps.

Thanks, but It not helps.

I want enter with contact with you! You can take a look in your LinkedIn?please

**Comment by idannyou** [comment]
I also have this issue. Did anyone resolve this?

**Comment by nagash77** [comment]
Hi @idannyou please open a new issue with a [reproducible example](https://github.com/cypress-io/cypress-test-tiny) and the Cypress team will be happy to investigate.
