### ISSUE TITLE
Cypress taking more than 2 min to launch the browser instance | Cypress is very slow | Tried with old and latest versions

### ISSUE THREAD

**Issue by ratnakarbellary** [cypress-io/cypress#8502]
Using:
Window: 10
Chrome: 84

**Comment by Bkucera** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example and we will consider reopening the issue.
