### ISSUE TITLE
Application is not loading in Cypress

### ISSUE THREAD

**Issue by anjaneyuludesu** [cypress-io/cypress#8503]
Getting error window.parent.$ is not a function. When I change this to window.$ in the application its loading successfully. But this needs an application code change.

I  tried modifyObstructiveCode=False in cypress.json file but still application is not loading in cypress. 

Any Help on this issue.

![Error](https://user-images.githubusercontent.com/6862513/92228998-698cec80-eec6-11ea-95fe-8b194ef7598d.PNG)

**Comment by Bkucera** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a fully reproducible example and we will consider reopening the issue.
