### ISSUE TITLE
Fails to load webpage with content-type "text/html;"

### ISSUE THREAD

**Issue by swernerx** [cypress-io/cypress#8506]
### Current behavior:
When loading a web page from our CDN (Azure) we do not have any issues in standard web browsers but when using Cypress. We receive the following error message:

![](https://user-images.githubusercontent.com/145201/92250962-6dbc0880-eecc-11ea-92d9-781b6593647f.png)

Seems like it does the like the appended semicolon. I can't imagine that this additional semicolon used for adding e.g. a charset information is really that problematic.

### Desired behavior:
I guess Cypress should tolerate all content-types starting with "text/html" instead of doing a strict string check here.

### Test code to reproduce
Try running cypress again one of our CDN urls e.g.:

```CYPRESS_BASE_URL=https://hconnectmanage-qa.azureedge.net/ yarn cypress run```

The actual test is not relevant. It fails even before starting.

I modified your tiny repo to show it quickly:
https://github.com/swernerx/cypress-test-tiny/tree/content-type-issue

### Versions
Cypress: v5.1
MacOS 10.15.6
Electron as bundled by Cypress

**Comment by flotwig** [comment]
Technically, the header `text/html;` is invalid: https://tools.ietf.org/html/rfc7231#section-3.1.1.1 You need to supply a `parameter` after the `;` for it to be valid.

However, it looks like Cypress wouldn't even recognize a valid parameter like `text/html;charset=utf-8`, or a valid uppercase content-type like `Text/HTML`:

https://github.com/cypress-io/cypress/blob/dd979eb696514dedf94b1b0aba2a8054b7c28ae8/packages/server/lib/server.js#L70-L84

This section of code should probably be updated to case-insensitively check that the content-type starts with `text/html`, since that is all that we really care about here.

Cypress also tries to check for valid HTML tags as a fallback, I'm not sure why this isn't working for your application, does it present valid HTML?

**Comment by lbesson-della** [comment]
@swernerx FYI I don't know if you need a workaround for your specific case until this fix is available, but using the console or more easily via Microsoft Azure Storage Explorer, you can edit the Content-Type served by azure storage.
