### ISSUE TITLE
Cypress doesn't fail the test and move on in case of an error, hangs up instead

### ISSUE THREAD

**Issue by sai-tej** [cypress-io/cypress#8511]
### Current behavior:

When I run my tests in cypress test runner and intermittently I see an unhandled exception coming at get method and cypress just hangs on indefinitely without erroring the test out.

```
Unhandled rejection [Exception... "Component not initialized"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: https://myserver.com/__cypress/tests?p=cypress/support/index.js :: [3]</Cypress.mocha._mocha.Mocha.Test.prototype.clone :: line 122"  data: no]
    [3]</Cypress.mocha._mocha.Mocha.Test.prototype.clone@https://myserver.com/__cypress/tests?p=cypress/support/index.js:122:3
    [3]</Cypress.mocha._mocha.Mocha.Test.prototype.clone@https://myserver.com/__cypress/tests?p=cypress/support/index.js:104:22
```

All I have in support/index.js is this
```
import './commands';
require('cypress-plugin-retries');
```
### Desired behavior:
Cypress should error the test out in case of an unhandled rejection and move on

### Test code to reproduce

This is just a simple test where I load a page and check for different elements and if the data grid is loaded on the page. If in case it matters, there are around 20 get methods in this test and it fails on the 14. There are no page loads (even the async ones) once the initial visit is done.

### Versions
cypress 4.8
FF Version 68.12.0esr (64-bit)

**Comment by jennifer-shehane** [comment]
We have test retries built into Cypress now. 
Try updating to the [current version of Cypress](https://on.cypress.io/changelog).

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
