### ISSUE TITLE
TypeError Cannot read property 'isLoaded' of undefined

### ISSUE THREAD

**Issue by sleknizi** [cypress-io/cypress#8516]
### Current behavior:
My tests are broken after cypress browsers update (Chrome 84 to Chrome 85, Firefox 79 to 80, ...)
Here is the error log : 
TypeError
The following error originated from your application code, not from Cypress.
> Cannot read property 'isLoaded' of undefined

![CypressError](https://user-images.githubusercontent.com/48132821/92456542-5a0dec00-f1c3-11ea-9419-d6e5ac4dd7d4.JPG)

### Test code to reproduce

cy.visit(url)

### Versions
Cypress version : 5.1.0
Chrome version : 85
Firefox version : 
Electron version :

**Comment by jennifer-shehane** [comment]
This error is coming from your application. Open DevTools to see the full error. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
