### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by amitguptagwl** [cypress-io/cypress#8539]
# Current behavior:
I'm trying to write a pre-processor where I pass the file name at run time as environment variable. But I get an error

```js
const someVar= require(Cypress.env('someEnvVar'));
```
It is printing the correct value of environment variable in Error. If I hard code the value then it works fine.

### Desired behavior:

I'm expecting it to load the module.

### Versions
Cypress: 4.12.1

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
