### ISSUE TITLE
Cypress - on running test getting white screen after some time

### ISSUE THREAD

**Issue by nitsaw09** [cypress-io/cypress#8571]
I am getting complete white screen after some time in cypress. I am running test 37 in cypress it gets white screen after some time. I want to ask if there is any test limit in cypress for running test.

**Comment by jennifer-shehane** [comment]
There is not a limit on the number of tests or specs that can be run in Cypress. It’s likely some other issue. 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by uplRahulC** [comment]
I am facing similar issue. This issue is not happening for all the test suites. Only happening for a specified one.
