### ISSUE TITLE
hooks are running twice

### ISSUE THREAD

**Issue by amitguptagwl** [cypress-io/cypress#8572]
### Current behavior:

I'm writing a file preprocessor. and observed that
1. In case if a test skips, cypress reload the tests. `before` method inside `describe` gets called 2 times. However, `it()` and `after()` gets called only once. 
Code sample
```js
describe("Suit", () => {
    before(() => {
        clilog("Running suit: ");
    });
    after(() => {
        clilog("Completing suit: ");
    });
    describe("Test: Some Test", () => {
        before(() => {
            clilog("Before Test: ");
        });
        after(() => {
            clilog("After Test: ");
        });
        xit( "This is the test to skip", ()=>{
            //test code
            clilog("Running Test: ");
        });
        it( "This is the sample test", ()=>{
            //test code
            clilog("Running Test: ");
        });
    });
});

logs
```
  Suit
DEBUG:: Running suit: 
    Test: Some Test
DEBUG:: Before Test: 
      - This is the test to skip
DEBUG:: Running suit: 
DEBUG:: Before Test: 
      ✓ This is the sample test (1818ms)
DEBUG:: After Test: 
DEBUG:: Completing suit: 
```
2. If I create a wrapper and run tests using `cypress.run()` then it runs the tests 2 times. However, on second run only `before` and `after` gets called.

### Desired behavior:

Hooks should run only once

### Test code to reproduce

Attached above

### Versions

Cypress: 4.12.1
OS: Ubuntu 18.04

**Comment by bahmutov** [comment]
Here is my code in https://github.com/cypress-io/cypress-test-tiny/tree/twice-before

To me it seems to run as expected - the skipped test _does not need_ its hooks to run

<img width="570" alt="Screen Shot 2020-09-15 at 3 28 22 PM" src="https://user-images.githubusercontent.com/2212006/93255730-4e449b80-f768-11ea-8eae-58e2a514185c.png">

Here is what Mocha does for the same test

<img width="418" alt="Screen Shot 2020-09-15 at 3 32 38 PM" src="https://user-images.githubusercontent.com/2212006/93256000-b09d9c00-f768-11ea-868f-3951c713019d.png">

Since we stick to Mocha's behavior, I think this is the expected result

**Comment by amitguptagwl** [comment]
Thanks @bahmutov to spend your time to create the sample. Yes, I also tried to extend your example by creating a sample preprocessor. But I'm not able to reproduce the issue. However, it is happening in my main project where I'm generating the tests dynamically. But I have found a workaround so I can move ahead.

Thanks for your time.
