### ISSUE TITLE
Seen "Cannot read property 'defaultView' of null" error on latest version 5.1.0 but same code not on 3.4.1 version

### ISSUE THREAD

**Issue by OzgurEvrenK** [cypress-io/cypress#8577]
Seen "Cannot read property 'defaultView' of null" error on latest version 5.1.0 but with same code not on 3.4.1 version

cy.get('button[name="newpatient"]').click();

![image](https://user-images.githubusercontent.com/60222240/93210021-39afd580-f75f-11ea-97d7-5567765d4e6d.png)

please inform me with possible sollutions... thank you

**Comment by bahmutov** [comment]
Please provide a reproducible example for us to investigate. There is something about this page that Cypress "chokes" on. Is it possible that there is a shadow dom element?

**Comment by OzgurEvrenK** [comment]
> Please provide a reproducible example for us to investigate. There is something about this page that Cypress "chokes" on. Is it possible that there is a shadow dom element?

- i am not sure what kind of reproducible example you are asking. if you give me your email address i can sent you DOM html 
- we dont have shadow element

**Comment by bahmutov** [comment]
You could make a tiny web app that has a similar structure to your application that gives an error, and make it into a public repo on GitHub, including the test that runs into the error. Then we can investigate and fix the problem. Otherwise, we have nothing to go on.

You could also open the browser DevTools console and look at the stack at the moment of the error to see if there is any information to help locate the error.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
