### ISSUE TITLE
Support of older versions of currently supported browsers

### ISSUE THREAD

**Issue by jradom** [cypress-io/cypress#8579]
I still haven't gotten an answer to this question
"Edge, FF, Chome for Windows and Mac OS Safari, FF, Chome including all versions of each 6 months back."
For example, is Edge "legacy" (not based on Chromium supported), older versions of FF(72, 73, 74, etc), older version of Chrome (75, 76, 77, 78, etc). Like I said we have a requirement to support all current browser and 6 months back
Please, let me know

Thanks

Jeff

**Comment by bahmutov** [comment]
- We do not have any plans to support the legacy Edge browser
- We do try to run lots of end-to-end tests and example applications in evergreen browsers (FF, Chrome) and because we use Docker images with the browsers baked in https://github.com/cypress-io/cypress-docker-images we usually are pretty good at catching bugs from the last couple of browser versions.

By the way, 6 months is not that long for evergreen browsers, so you should probably be ok. At least you could stay with a version of Cypress that supports it.
