### ISSUE TITLE
Config from cypress.json is considered as cli config in the app

### ISSUE THREAD

**Issue by pawelgalazka** [cypress-io/cypress#858]
- Cypress Version: `1.0.3`

### Is this a Feature or Bug?

Bug

### Current behavior:

Environment variables from `cypress.json` are treated as cli config, thus settings from `cypress.json` have higher priority than those from `cypress.env.json`:

<img width="408" alt="screen shot 2017-10-31 at 10 51 39 am" src="https://user-images.githubusercontent.com/829242/32201161-825354aa-be29-11e7-9894-708abecb68dd.png">

`domain` env variable config (cypress.json.host), was provided by `cypress.json` not cli.

### Desired behavior:

Configs from `cypress.json` should appear as configs from `cypress.json` file, not cli, so `cypress.env.json` config should overwrite `cypress.json` one.

**Comment by jennifer-shehane** [comment]
Is it possible for you to paste the contents of your `cypress.json` and `cypress.env.json` files?

**Comment by pawelgalazka** [comment]
cypress.json
```json
{
  "videoRecording": false,
  "videoUploadOnPasses": false,
  "screenshotOnHeadlessFailure": true,
  "viewportHeight": 800,
  "viewportWidth": 1280,
  "environmentVariables": {
    "protocol": "http",
    "domain": "shopfront.envato.dev"
  },
  "projectId": "zjrnco"
}
```

cypress.env.json
```json
{
  "environmentVariables": {
    "domain": "shopfront.envato.dev:8080"
  }
}
```

From the app
<img width="526" alt="screen shot 2017-11-01 at 8 20 21 am" src="https://user-images.githubusercontent.com/829242/32249561-94c0c6fe-bedd-11e7-833e-10fccb1a26d7.png">

**Comment by brian-mann** [comment]
This is not a bug, the problem is that you're not using the `cypress.env.json` file correctly.

You do not nest `environmentVariables` in there. That's generating a nested object.

https://docs.cypress.io/guides/guides/environment-variables.html#Option-2-cypress-env-json

**Comment by pawelgalazka** [comment]
@brian-mann if I do not nest, so for example my `cypress.env.json` is 
```
{
  "domain": "shopfront.envato.dev:8080"
}
```

then this is not read at all. Cypress don't see that, I need to nest it under `environmentVariables` to make Cypress to see it.

**Comment by brian-mann** [comment]
That's because you're also not using the property for the `cypress.json` - which is what is obliterating the other values.

https://docs.cypress.io/guides/guides/environment-variables.html#Option-1-cypress-json

The key is `env` and not `environmentVariables`. Internally we use the later which is why you're seeing confusing results.

**Comment by pawelgalazka** [comment]
Ahh.. cool, ok so I do not nest in `cypress.env.json` now, and I changed `environmentVariables` key to `env` in cypress.json and it seems to work:

<img width="447" alt="screen shot 2017-11-01 at 8 32 42 am" src="https://user-images.githubusercontent.com/829242/32250082-45c06b8e-bedf-11e7-92fe-736462dc20aa.png">

But why app interface keeps `environmentVariables` name ? Shouldn't display `env` ? That's a bit confusing.

**Comment by brian-mann** [comment]
I agree its a bit confusing - but the reason is that because there are 4 areas that can set environment variables it's not really a direct 1:1 comparison of `cypress.json`. It's more like saying - these are all the environment variables that have been set from all 4 different sources.

It's a visual thing only so we could just update it. We've actually had this question / confusing at least 1 other time.

If you want submit a PR - this is just the react front end for the `packages/desktop-gui`. @jennifer-shehane  or @chrisbreiding could also do it too.
