### ISSUE TITLE
Chainer typescript definitions should use an enum

### ISSUE THREAD

**Issue by JamesYeoman** [cypress-io/cypress#8614]
### Current behavior:
Currently, we have to use 'magic strings' in order to use chainers. This is prone to typos and incorrect ordering (because there's no intellisense to help you).

### Desired behavior:
The typings provided by Cypress should provide either an enum, or a callback-based assertion like the underlying chai library offers. This would result in compile-time checking, and remove the need for us users to rely on self-defined constants or enums. Not only will that satisfy those of us who hate using magic strings, but it'll also satisfy linters. It even enables documentation to be added to each assertion, and lets the users see all the available assertions from their completion dropdown, rather than trawling through a typescript definition file.

### Test code to reproduce

https://github.com/JamesYeoman/cypress-test-tiny/tree/issue-example

### Versions

Cypress: 5.2.0
OS: Ubuntu 20.04
Browser: Chrome

**Comment by sod** [comment]
Actually the issue is, that these two fallback typings exist

https://github.com/cypress-io/cypress/blob/10b9a5b172f7f702b804c4cb359348a446a48c9a/cli/types/cypress.d.ts#L4912-L4919

If those didn't exist, typescript would error if your "magic string" wasn't defined in [cypress.d.ts](https://github.com/cypress-io/cypress/blob/10b9a5b172f7f702b804c4cb359348a446a48c9a/cli/types/cypress.d.ts#L2944-L4910).

**Comment by Brookke** [comment]
Are there any blockers to removing the fallback typings? I initially assumed there were there for custom assertions, but since the [type definitions can be extended](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/extending-cypress__chai-assertions), it seems like they could be removed without issue in a future version?

**Comment by Brookke** [comment]
https://app.circleci.com/pipelines/github/cypress-io/cypress/15708/workflows/c016ad5e-9a35-4df8-a334-eaddfd1a1646/jobs/556531 

https://app.circleci.com/pipelines/github/cypress-io/cypress/15708/workflows/c016ad5e-9a35-4df8-a334-eaddfd1a1646/jobs/556562
