### ISSUE TITLE
Tests started to fail when we disable video option

### ISSUE THREAD

**Issue by onurgultekin** [cypress-io/cypress#8631]
We have 12 integration test with video option is true, but when we changed to video option to false, tests started to fail. If option is true, tests are being succeeded else tests are being failed. Do you have an idea about this?

**Comment by bahmutov** [comment]
No idea why this would be the case, is there any more information?

**Comment by jennifer-shehane** [comment]
When opening a pull request, please fill out the [pull request template](https://github.com/cypress-io/cypress/blob/develop/PULL_REQUEST_TEMPLATE.md) provided - it requires necessary information we need to move forward with reviewing pull requests. 

If you can, please edit the initial comment of this PR filling out the pull request template including an explanation for why this PR is necessary. Otherwise, we will be closing this PR.
