### ISSUE TITLE
Request for a native API recording feature for Cypress

### ISSUE THREAD

**Issue by abryant710** [cypress-io/cypress#8633]
### Current behavior:

I am currently using the following package to record API requests from our app, so they can be played back offline during test runs using Cypress:

https://github.com/scottschafer/cypressautomocker

The author has expressed that he does not plan to maintain this project going forward, although this is a very valuable package for us. It allows us to run our testing scripts while the API responses get recorded from our backend. Once they are recorded, we can run the tests while disconnected to our backend altogether, making it easier to run our scripts in CI/CD.

### Desired behavior:

It would be nice to have similar functionality natively within the Cypress testing framework.

### Test code to reproduce

Please refer to the package to see how it works.

### Versions

I am using "cypress": "4.8.0"

**Comment by OmriSama** [comment]
Hey guys, I wanted to necro this because I was looking for a plugin that does the same thing.

https://medium.com/ax2-inc/dynamic-xhr-responses-recording-stubbing-with-cypress-9257d4f730cd

This is a good post that explains how to do Request Recording with relatively little code. He mentions the plugin API, and I wanted to see if there was a plugin in development for this :) thanks in advance

**Comment by jennifer-shehane** [comment]
Due to the lack of interest in this feature over the years, we’ll close this as not currently planned.
