### ISSUE TITLE
Text editor module won't appear in case I use Cypress editor 

### ISSUE THREAD

**Issue by SamehElNabawy** [cypress-io/cypress#8635]
### Current behavior:

Text editor module won't appear in case I use Cypress editor 

### Desired behavior:

Text editor should appear on cypress browser as it happens on my personal browser
### Test code to reproduce

Install Cypress 5 
Login to any website which has text editor module 
Try to find the editor

**Comment by bahmutov** [comment]
Please provide an actual reproduction: spec file (a link to a repo is preferred), screenshots, videos. Otherwise we have nothing to go on.

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
