### ISSUE TITLE
Chromium Renderer process crashes with Electron browser

### ISSUE THREAD

**Issue by storrestw** [cypress-io/cypress#8642]
### Current behavior:

When running cypress tests on Jenkins build agent, Chromium render process crashes with the following error:
`[792:0922/144449.942519:FATAL:memory.cc(38)] Out of memory. size=54118400`

These tests run every 30 min, and they have been running successfully but since 21/09 at 8 AM they started to fail.

btw, tests are passing when running locally.

### Desired behavior:

Tests should pass without any error.

### Test code to reproduce

I can't add the steps to reproduce since the repository is internal to the company.

### Versions

cypress: 5.2.0
browser: Electron 83
operating system: CentOS
node: 10

**Comment by storrestw** [comment]
### Fix
Using headless chrome as browser fixed this issue

**Comment by jennifer-shehane** [comment]
I would suggest following on recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
