### ISSUE TITLE
Best way to debug EPIPE errors

### ISSUE THREAD

**Issue by weyert** [cypress-io/cypress#8647]
### Current behavior
I am getting a lot of EPIPE errors when using Cypress v5.0 or v5.2. I was wondering if Cypress has any tips to find out the potential reason for these issues? Mostly happening when using Electron but also occasionally happen when using Chromium.

### Desired behavior
No suddenly crashes due to EPIPE error which closes the Cypress application.

### Test code to reproduce
It's intermittent still working on trying to make a reproducible case, hence my query for tips how to more information about the potential cause, any 

### Versions
macOS 10.15.6, Cypress 5.2.0
macOS 10.15.6, fork of Cypress 5.2.0 to include Kungfu browser support

**Comment by bahmutov** [comment]
I can suggest reading the https://on.cypress.io/debugging guide and trying maybe using https://github.com/bahmutov/cypress-repeat to run the same project again and again.

**Comment by weyert** [comment]
Thank you for your response, I don't have problems reproducing the issue, I am only struggling to come up with good starting points within the Cypress codebase to find the cause of the EPIPE issue. Looks like I could use `DEBUG=cypress:*` to see what's going on before Cypress crashes.

**Comment by jennifer-shehane** [comment]
@weyert I’d suggest checking our troubleshooting for tools for debugging actual bugs in Cypress. https://on.cypress.io/troubleshooting 

Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by weyert** [comment]
Found the cause of the problem the Cypress Interop agent for my webkit browser had a memory leak and caused the web process to be killed which dragged Cypress down. All good now :)
