### ISSUE TITLE
cypress writing texts very slowly

### ISSUE THREAD

**Issue by mpHenriqueMelo** [cypress-io/cypress#8667]
### Current behavior

The ".type" method of the "cy" object is writing texts very slowly in versions above 4.8.0

I've tried to change the TypedOptions options by reducing the delay and setting the Force option but nothing worked

### Desired behavior

The ".type" method should write texts quickly

### Test code to reproduce

cy.get(".textarea.element").type("long text with line breaks")

### Versions

Any version between 4.8.0 and 4.12.x

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

The example provided alone does not reproduce the error. It’s likely dependent on typing into the specific application you are testing - something in the application under test exhibits the bug. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
