### ISSUE TITLE
cypress 5.2.0 can not install using npm

### ISSUE THREAD

**Issue by sakiburrahman** [cypress-io/cypress#8681]
I tried to install cypress using **npm install cypress --save-dev** command but after installing the following things do not execute.

I waited for two hours to complete the process but it's getting stuck in downloading cypress step

![cypress_error](https://user-images.githubusercontent.com/4531044/94374491-689a5400-012e-11eb-980d-00dde57e03e7.png)

**Comment by bahmutov** [comment]
Could you try installing while the environment variable `DEBUG` is set to `cypress:cli` please? That would print debug log messages.

https://docs.cypress.io/guides/references/troubleshooting.html#Print-DEBUG-logs

**Comment by sakiburrahman** [comment]
Found it using debug
![cypress_error_1](https://user-images.githubusercontent.com/4531044/94375197-b9f91200-0133-11eb-8027-38c55fac4581.png)

**Comment by bahmutov** [comment]
You would need to run install again since it did not finish

**Comment by sakiburrahman** [comment]
I ran the command and waited for 2 hours to finish but it did not finish

**Comment by bahmutov** [comment]
But could you try running it npm install again with debug variable set to see Cypress log messages?

**Comment by sakiburrahman** [comment]
getting it. it does not download to the project directory 
![cypress_error_2](https://user-images.githubusercontent.com/4531044/94376343-d6994800-013b-11eb-8376-3ffc99e84ea6.png)

**Comment by sakiburrahman** [comment]
not only that the zip file does not exist in ..\\local\\temp folder

**Comment by bahmutov** [comment]
Seems like something breaks there during the end of the download stream, and just never finishes.

**Comment by sakiburrahman** [comment]
Similar issue found in 5.3.0

![image](https://user-images.githubusercontent.com/4531044/94990427-d6ff6c00-059d-11eb-802f-370877bd8942.png)

**Comment by joszo** [comment]
I have simmilar problem on 5.3.0 and 5.2.0 on gitlab.

`The Cypress App could not be downloaded.
Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
Otherwise, please check network connectivity and try again:
----------
URL: https://download.cypress.io/desktop/5.2.0?platform=linux&arch=x64
Error: unable to get local issuer certificate`

Is it related? Or should I configure somehow proxy on gitlab...
