### ISSUE TITLE
`cy.wait` types for yielded object are incorrect when awaiting `cy.route2` routes

### ISSUE THREAD

**Issue by bhgsbatista** [cypress-io/cypress#8731]
### Current behavior
In the following code, VSCode underlines statusCode with red squiggles indicating a missing type:

```js
cy.wait('@create').should(({ response }) => expect(response.statusCode).be.equal(200))
```

![image](https://user-images.githubusercontent.com/47303296/94872135-d0e08280-0419-11eb-9b66-e218e3f35d67.png)

### Desired behavior
`statusCode` and other properties are properly typed in the response object.

### Test code to reproduce
https://github.com/bhgsbatista/cypress-test-tiny/tree/route2_method_fail

Just opening [spec.js](https://github.com/bhgsbatista/cypress-test-tiny/blob/route2_method_fail/cypress/integration/spec.js) with VSCode should be sufficient to reproduce the issue.

### Versions
Cypress v5.3.0

**Comment by flotwig** [comment]
@bhgsbatista unfortunately, the `cy.wait` type does not yet yield the correct type for an aliased `cy.route2`, because it would break the existing yielded type for `cy.route`. The type for `cy.wait` will probably only be updated once cy.route2 replaces cy.route.

The type you are looking for is `Request`: https://github.com/cypress-io/cypress/blob/80569861a77d6aeaa1a9c69207a601bc27c8025e/packages/net-stubbing/lib/external-types.ts#L105-L128

You can import it from `cypress/types/net-stubbing` and override the global type for `cy.wait` like this:

```ts
import { Request } from 'cypress/types/net-stubbing'

declare global {
  namespace Cypress {
    interface Chainable<Subject = any> {
      wait(alias: string): Chainable<Request>
    }
  }
}
```

You can override the other `.wait` method signatures as needed.

**Comment by bhgsbatista** [comment]
@flotwig I see, I think it makes sense to close this issue since this is a known issue that will be fixed in due time.

**Comment by flotwig** [comment]
I'll keep it open so users can find this workaround, then close it once the workaround is no longer needed
