### ISSUE TITLE
Page redirect issue

### ISSUE THREAD

**Issue by kasarlas** [cypress-io/cypress#8738]
Hi All, I am facing one issue in Cypress.

I am successfully opening the application, in that page, I have different links, So when I click one of the links on the page it is loading fully, it shows spinner for a long time. So maybe when I click the link it is redirecting to a different URL, so not sure how to code that..could someone help me with this?

Thanks 
Ram

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
