### ISSUE TITLE
3rd party login form is failing in chrome 85 and chromium 88 but works in electron 83 or edge 85

### ISSUE THREAD

**Issue by vranky** [cypress-io/cypress#8760]
### Current behavior
Few weeks ago we started facing the problem (probably after cypress or chrome update)

Simply login form(3rd party) returns failed credentials error after submit with correct credentials even when we tried to log in manually in cypress test-runner (chrome/chromium), but it worked when we opened next tab in cypress test-runner. 

The same scenario worked correctly in cypress test-runner edge/electron. It also worked correctly with selenium-webdriver.

ChromeWebSecurity is set to false, credentials was filled correctly and submit was pressed.

![image](https://user-images.githubusercontent.com/10365694/95211250-9fd2ca00-07ec-11eb-84ae-da7d99169876.png)

![image](https://user-images.githubusercontent.com/10365694/95211009-5aae9800-07ec-11eb-8296-ff1a67ea3a31.png)

### Versions
Cypress 5.3.0
Chrome 85
Chromium 88

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Is the error fixed when you roll back to a previous version of Cypress? That would narrow down whether it’s a Cypress issue itself. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.

**Comment by vranky** [comment]
After downgrade cypress to 3.3.1 I was able to run this test case on chrome 75.
