### ISSUE TITLE
#8764 should be re-written.

### ISSUE THREAD

**Issue by sainthkh** [cypress-io/cypress#8768]
### Current behavior

#8764 broke CI and some test suites like `packages/server/test/e2e/6_video_compression_spec.js` are not executed. 

### Desired behavior

* CI works correctly
* Test suites like `packages/server/test/e2e/6_video_compression_spec.js` are executed.
* Flaky tests are fixed.

### Test code to reproduce

According to [the CI results](https://app.circleci.com/pipelines/github/cypress-io/cypress?branch=retries-for-flaky-failing-specs) of #8764, it's merged hastily. There are non-flaky failures in server-6 tests, but they're ignored.

### Versions

Current develop branch.

**Comment by jennifer-shehane** [comment]
Thanks for the notice. We’ll definitely look into this.

**Comment by JessicaSachs** [comment]
The specs that were falling when merged were related to network stubbing and were fixed by a PR earlier this week. Let me know if you’re seeing a failure outside of the net stubbing ones.

The PR was coauthored by @Bkucera  and I so we feel comfortable retrying these specs as the solution for reducing flake.  How does retrying the spec prevent it from running?

**Comment by JessicaSachs** [comment]
I see, I didn’t understand that the snapshots were required to be updated. I think we’ll roll forward with a fix rather than revert. https://app.circleci.com/pipelines/github/cypress-io/cypress/13838/workflows/eeb0dec9-e5c0-40e5-9163-8f0125936404/jobs/471112

I’ll do this in the morning (5-6 hours). Thanks 🙏🏻

**Comment by sainthkh** [comment]
As for not running a test, I also felt it's really weird. But when you open a [test result log page of the branch of #8764](https://app.circleci.com/pipelines/github/cypress-io/cypress/13830/workflows/fafd20f7-cb2b-4ac5-bc8d-4ab993800b5a/jobs/470819/steps) and search `e2e video compression / passes` with Ctrl + F, it doesn't exist. But in [the logs before that](https://app.circleci.com/pipelines/github/cypress-io/cypress/13854/workflows/676b33eb-353a-4c45-b417-ccdb1ccbf9b4/jobs/471922)(I intentionally ignored #8764 in this PR), it does exist. 

I found it because I was fixing something related. Maybe it needs some investigation. It has something to do with `{ retries: 1 }`. When we add it, the test isn't executed.

**Comment by jennifer-shehane** [comment]
Does this close this issue? https://github.com/cypress-io/cypress/pull/8775

**Comment by sainthkh** [comment]
Fixed. Close it.
