### ISSUE TITLE
viewport rounding error with cy.viewport()

### ISSUE THREAD

**Issue by AnderssonChristian** [cypress-io/cypress#8770]
### Current behavior
I'm getting incorrect viewport set when using `cy.viewport()`. It is off by 1 px and thus failing my tests.

### Desired behavior
Viewport settings should work as expected.

### Test code to reproduce
This is my test. My app has its navigation at the top on desktop mode. For mobiles the navigation is shown on a sidebar that is toggleable from a hamburger-button.

I do the test for 5 viewports (1440x1080, 1024x768, 768x576, 480x768, 320x768). All pass except the 3rd one. As seen in the screenshot below, the viewport width is less than 768 pixels in width. When entering `window.innerWidth` in the console, it returns `767`. The other viewports in the test do not appear to have this issue.

![screenshot](https://i.imgur.com/cnbDQNN.jpg)

Here's the complete test:

```js
const viewports = [
  {width: 1440, height: 1080, isMobile: false},
  {width: 1024, height: 768, isMobile: false},
  {width: 768, height: 576, isMobile: false},
  {width: 480, height: 768, isMobile: true},
  {width: 320, height: 768, isMobile: true}
];

context('Navigation', () => {
  let idx = 0;

  // Before starting any of the tests, visit the page.
  before(() => {
    cy.visit();
  });

  // Unless viewport is specified during each test, it will reset to default.
  // It does not keep viewport settings from previous tests.
  beforeEach(() => {
    cy.viewport(viewports[idx].width, viewports[idx].height);
    cy.wait(500); // Allow app to adjust
  });

  viewports.forEach(({width, height, isMobile}) => {
    describe(`(${isMobile ? 'Mobile' : 'Desktop'}) ${width}x${height}`, () => {
      // When all tests for this viewport are done, increment the index.
      after(() => {
        idx++;
      });

      it('Shows all page links', () => {
        if (isMobile) {
          cy.get('[data-cy="sidebar"]').should('exist');
          cy.get('[data-cy="sidebar"]').find('a').should('have.length', 3);
        } else {
          cy.get('[data-cy="sidebar"]').should('not.exist');
          cy.get('[data-cy="header"] nav').find('a').should('have.length', 3);
        }
      });

      if (width < 480) {
        it('Hides the branding in the header', () => {
          cy.wait(200);
          cy.get('[data-cy="header"] div > span').should('not.exist');
        });
      } else {
        it('Shows the branding in the header', () => {
          cy.wait(200);
          cy.get('[data-cy="header"] div').eq('-2').find('span').should('have.length', 2);
        });
      }

      if (isMobile) {
        it('Can show/hide the sidebar', () => {
          cy.get('[data-cy="sidebar"]').then(el => {
            const {left} = el[0].getBoundingClientRect();
            expect(left).to.be.below(0);
            cy.get('[data-cy="header"] button').click();
          });
          cy.wait(500); // Allow animation to finish
          cy.get('[data-cy="sidebar"]').then(el => {
            const {left} = el[0].getBoundingClientRect();
            expect(left).to.be.equal(0);
            cy.get('[data-cy="header"] button').click();
          });
        });
      }
    });
  });
});

```

### Versions
Cypress 5.3.0, Linux, Chrome 78

**Comment by jennifer-shehane** [comment]
I'm not able to recreate this issue with the information provided. Likely, there is something specific to the application under test (like some css property) that is affecting when this error occurs. Please provide a fully reproducible example - including the app code to test against - so that we can investigate further. 

**The example I tried**

`index.html` - I thought maybe the vertical scrollbar was affecting it, but no.

```html
<!DOCTYPE html>
<html>
<body>
<p style="height: 5000px;">Foo</p>
<script>
</script>
</body>
</html>
```

`spec.js`

```js
it('test', () => {
  cy.viewport(768, 576)
  cy.visit('index.html')
  cy.window().then((win) => {
    expect(win.innerWidth).to.eq(768)
  })
})
```

<img width="643" alt="Screen Shot 2020-10-08 at 2 14 01 PM" src="https://user-images.githubusercontent.com/1271364/95429713-c4f04580-0970-11eb-9c36-836984669202.png">

**Comment by AnderssonChristian** [comment]
@jennifer-shehane I cannot share the app code, unfortunately.

That said, I cannot imagine any case where a css property changes the output of window.innerWidth.
I'll investigate further and come back when I've found more details.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
