### ISSUE TITLE
cy.intercept routes being matched with external URLs, but does not return mocked fixture during cypress run

### ISSUE THREAD

**Issue by m1ky91** [cypress-io/cypress#8789]
### Current behavior

First of all many thanks on the work done for the new ```route2```. Working on it I have noticed that mocking external URLs with ```route2``` there was a [bug](https://github.com/cypress-io/cypress/issues/8487) resolved with the ```5.3.0``` version, but now even after this upgrade I can see the ```route2``` is working fine when I run the test from the visual dashboard but not when I run the tests from the command line with:

```
npx cypress run --config-file cypress/config/all.json
```

With this line of code I am mocking an external URL (```tokenizer``` is a const defined with the external URL):

```js
cy.route2('POST', tokenizer, { fixture: 'edgeToken.json' }).as('edgeTokens');
```

and when I run the test from the visual dashboard with ```cypress open --config-file cypress/config/all.json``` the visual stack trace is the following one:

![dashboard](https://user-images.githubusercontent.com/12275263/95461369-0c290700-096e-11eb-8331-973290664d23.gif)

whereas when I run the tests from the command line ```cypress run --config-file cypress/config/all.json``` which is the one we run in our jenkins job it fails:

![cmd](https://user-images.githubusercontent.com/12275263/95461621-59a57400-096e-11eb-9088-411a2ca57163.gif)

Just to give a context ```createPaymentSession``` is not called if ```edgeTokens``` fails, and for that reason the test fail during the command line run

### Desired behavior

The same behavior between the dashboard and the command line run. Old ```route``` command is working fine as work around.

### Test code to reproduce

Described in the  Current behavior section

### Versions

Cypress 5.3.0, Mac OS, Chrome

**Comment by jennifer-shehane** [comment]
I would suggest following the recommendations on troubleshooting why tests are fail in CI but pass locally: https://on.cypress.io/using-cypress-faq#Why-do-my-Cypress-tests-pass-locally-but-not-in-CI

From that guide, you may want to specifically run Electron locally instead of Chrome and see if the difference is isolated to the specific browser. 

Please comment here with any findings from that troubleshooting. 

Outside of that we’ll need some way to reproduce this behavior in order to investigate.

**Comment by m1ky91** [comment]
Hi yes just tried running the test from the dashboard using Electron 83 and I can see it fails like in the CI.

**Comment by jennifer-shehane** [comment]
Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
