### ISSUE TITLE
Strange error thrown when filling a form

### ISSUE THREAD

**Issue by borecz** [cypress-io/cypress#8792]
### Current behavior
When trying to fill a form at a certain step I get this error:

```
Cypress command timeout of 15000ms exceeded. (and Mocha's done() called multiple times)

Because this error occurred during a before all hook we are skipping the remaining tests in the current suite: Guest checkout
```

As you can see from the screenshot provided, the error message is anyway wrong as the error happens during the test body but it's being recognised as happened in a before all hook 

![image](https://user-images.githubusercontent.com/57007154/95477907-26241300-0989-11eb-9b87-a1812d6608fb.png)

### Versions
Cypress 5.3.0, MacOs

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
