### ISSUE TITLE
Spy is failing to assert that a call was made, despite confirming the call was made

### ISSUE THREAD

**Issue by egucciar** [cypress-io/cypress#880]
- Operating System: Windows 7
- Cypress Version: 1.0.3
- Browser Version: 62

### Is this a Feature or Bug?
Bug

### Current behavior:
Expectation is failing despite confirming the call was made

### Desired behavior:
The expectation should succeed

### How to reproduce:
Not sure why the issue is happening and I cannot expose the repository as it is not public. Screenshots:
![image](https://user-images.githubusercontent.com/2848185/32453747-220801d8-c2eb-11e7-8f0e-4e925b6b0f6a.png)
![image](https://user-images.githubusercontent.com/2848185/32453803-44c74bfc-c2eb-11e7-9751-9ce0ee466097.png)
![image](https://user-images.githubusercontent.com/2848185/32453839-5f6fb2b4-c2eb-11e7-8189-58434d6f8484.png)

![image](https://user-images.githubusercontent.com/2848185/32453907-9c5f0b66-c2eb-11e7-9ad2-9d652546a5da.png)

#### Test code:

```js

```

**Comment by brian-mann** [comment]
I don't believe this is a bug.

You are spying on the function after it's been invoked.

You have to insert your spy when the function exists, but **before** its called else how could the spy know it's been called?

You might want to insert the spy during the `onLoad` event handler of the `cy.visit`. However if this function is called immediately when your page is initialized - it can be difficult to insert the spy at the right moment. It's going to depend on your application code.

In these cases you have to introduce a "seam" somewhere. Your app code could do something conditionally when it detects its running in Cypress. Another option is to just test the side effect of what this function does. Does it matter that its been called? Since you're using a `spy` and not a `stub` it looks like you're only verifying its been called as opposed to changing its behavior. In that case just test the behavior.

**Comment by egucciar** [comment]
@brian-mann  youre correct, idk why i didnt notice that detail. Thanks a bunch. the function is not called immediately. However theres no way for me to solve this issue. I dont really need to watch this function. I actually just want to assert a Network call is only made once. Currently in the application we're making so many redundant data calls so i want to write a failing test that asserts that the network call is only called once, but see no tools to do this. Since I'm unable to write this test it makes me question if Cypress is the right tool.

**Comment by brian-mann** [comment]
If the network call is an XHR you could test that in Cypress.

**Comment by brian-mann** [comment]
You could also expose something in your application that holds an array of the network calls (or attempts) and then assert on that in Cypress

**Comment by egucciar** [comment]
@brian-mann  thanks, I'll try to second option unless you have an example on how to get the # of times a network XHR request is made as i looked through the assertion possibilities for XHR and saw how to asset a request, but not on how to assert a particular request with particular parameters is only called X times

**Comment by brian-mann** [comment]
We provide you `onRequest` function callback so you could increment a counter there and then assert the counter is a specific number.

**Comment by egucciar** [comment]
@brian-mann  the solution works wonderfully! thank you so much!
