### ISSUE TITLE
My website reload the whole page and even the cypress UI disappear

### ISSUE THREAD

**Issue by heitrix** [cypress-io/cypress#8801]
### Current behavior

When I run cy visit command, the website reload the whole thing and even the Cypress UI doesn't appear or appear briefly and then disappear

Test site: https://orders.stg.redrooster.com.au
Video: https://photos.app.goo.gl/Y1Uf1favtnc6y3dq6
Screenshot: https://photos.app.goo.gl/gfTj6iJ4bsM5Ek5r7

### Desired behavior

The Cypress UI should still appear so the automated script runs.

### Test code to reproduce

`
/// <reference types="cypress" />

describe("Sign in", function () {
  before(() => {
    cy.clearCookies();
  });

  beforeEach(() => {});

  it("Sign in with wrong detail", () => {
    cy.visit("/");
    cy.title().should("have.text", "Red Rooster");
  });
});

`

**Comment by bahmutov** [comment]
Ok, so it loads for me, but seems this is a problem with command log disappearing because it has width of 0

<img width="1440" alt="Screen Shot 2020-10-09 at 9 35 56 AM" src="https://user-images.githubusercontent.com/2212006/95589589-f4578e80-0a12-11eb-8767-cc843cf55552.png">

Can you try clearing the Cypress data to get it back as shown here https://github.com/cypress-io/cypress/issues/2132

PS: Ughh I cannot believe we have not set min-width on this yet...

**Comment by heitrix** [comment]
Hi @bahmutov ,

Clearing the data fixes the problem!

But, when I edit the spec file, it will hot reload right? But, it just keep spinning and when I stop the script,  re-run the script again, the same problem **happens again**, the site opened without Cypress UI.

Here's a video: https://photos.app.goo.gl/ThJStnjdEUrifW6W7

Thank you,

**Comment by bahmutov** [comment]
Can you open devtools console to see if there are any errors there

**Comment by heitrix** [comment]
Hi @bahmutov ,

There are errors when the hot reload happen.

Video: https://photos.app.goo.gl/ZLDJCTp6LQTyeXveA
Screenshot: https://photos.app.goo.gl/UBh1wnhStDDt3fQQ7

Thank you,

**Comment by bahmutov** [comment]
I can recreate your problem in https://github.com/cypress-io/cypress-test-tiny/tree/8801 and see the website taking over the entire browser page on reload. This is due to the ServiceWorker - you can clear the cache in the browser to see the spec "back to normal" (but then it takes over the entire page again)

<img width="1278" alt="Screen Shot 2020-10-09 at 10 44 56 AM" src="https://user-images.githubusercontent.com/2212006/95597515-bc554900-0a1c-11eb-8e8c-3bfa57f18ee8.png">

Try visit the site but disable the service worker as I show here https://glebbahmutov.com/blog/cypress-tips-and-tricks/#disable-serviceworker

**Comment by heitrix** [comment]
Thank you @bahmutov , I'll try.

**Comment by heitrix** [comment]
Hello @bahmutov ,

It's working! The website no longer take over! Very cool!

Thank you very much!

https://photos.app.goo.gl/Jm4sMedoxZatvMoFA

**Comment by NoumanYns** [comment]
Hi @bahmutov I am facing quite a similar issue, I have followed the instruction that you explained regarding "disabled service workers" but my issue is not getting resolved, please refer to this video

**website Link:** 
https://prodtest.demosphere-secure.com/_/_officials-mgmt
 **OR**
https://prodtest.demosphere-secure.com/_dashboard

My Code:

it('Successful Signin',()=>{
        cy.visit('https://prodtest.demosphere-secure.com/_/_officials-mgmt', {
            onBeforeLoad (win) {
                delete win.navigator.__proto__.ServiceWorker
            }
          })
        
        cy.get('#user_login').type('alidem2')
        cy.get('#user_password').type('Alidem2')
        cy.get('[type="submit"]').click()
    } ) 

[screen-capture (21).webm](https://user-images.githubusercontent.com/103923598/184245076-5bea4063-7c1f-41eb-9549-a5f196e405a1.webm)

**Looking forward to hear from you**
