### ISSUE TITLE
cy.route2: Stubbing response with {}

### ISSUE THREAD

**Issue by camden-brown** [cypress-io/cypress#8810]
### Current behavior
I switched to using route2 because of the ease of use and improved syntax. Occasionally, I run across weird errors like this one. When I try to mock a response for this call it fails with the following error but when I provide an empty string or an array the error disappears. However, the [docs](https://docs.cypress.io/api/commands/route2.html#Stubbing-a-response) suggest that `body` should accept `string | object | object[]`. 

```js
cy.route2('**/appointments**', { body: { combined: [], dependents: [], patient: [] } }).as('getAppointments');
```

```
Uncaught SyntaxError: The following error originated from your application code, not from Cypress.

  > Unexpected token ':'

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `No Predictions/Answer No`
SyntaxError: The following error originated from your application code, not from Cypress.

  > Unexpected token ':'

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
From previous event:
    at run (http://localhost:4200/__cypress/runner/cypress_runner.js:169256:21)
    at $Cy.cy.<computed> [as mockHealthHistoryStepThrough] (http://localhost:4200/__cypress/runner/cypress_runner.js:169713:11)
    at Context.runnable.fn (http://localhost:4200/__cypress/runner/cypress_runner.js:169937:21)
    at callFn (http://localhost:4200/__cypress/runner/cypress_runner.js:104304:21)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:4200/__cypress/runner/cypress_runner.js:104291:7)
    at http://localhost:4200/__cypress/runner/cypress_runner.js:175515:28
From previous event:
    at Object.onRunnableRun (http://localhost:4200/__cypress/runner/cypress_runner.js:175503:17)
    at $Cypress.action (http://localhost:4200/__cypress/runner/cypress_runner.js:166073:28)
    at Hook.Runnable.run (http://localhost:4200/__cypress/runner/cypress_runner.js:173900:13)
    at next (http://localhost:4200/__cypress/runner/cypress_runner.js:104806:10)
    at http://localhost:4200/__cypress/runner/cypress_runner.js:104850:5
    at timeslice (http://localhost:4200/__cypress/runner/cypress_runner.js:98776:27)
```

I do use `sy.server()` as well after this `stub` because I have issues with using`route2` to stub responses from 3rd party domains and therefore am forced to use `cy.route`. Not sure if this would affect anything but thought it would be worth mentioning.

### Desired behavior
Consistent and reliable behavior when needing to stub a response of a request that need to return an `{}`.

### Versions

Tested in all recent versions of Electron/Firefox/Chrome
Cypress 5.3.0

**Comment by camden-brown** [comment]
Switching back to:
`  cy.route('**/appointments**', { combined: [], dependents: [], patient: [] }).as('getAppointments');`
fixes the error as well.

**Comment by jennifer-shehane** [comment]
We will need more information to reproduce the problem. This error is being thrown from your application, so we’ll need a way to run the code and reproduce the error. 

We’ll have to close the issue otherwise. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.

Please comment in this issue with a reproducible example.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
