### ISSUE TITLE
ScrollTo is not working after viewport is set

### ISSUE THREAD

**Issue by VictorPapuc** [cypress-io/cypress#8816]
ScrollTo is not working after viewport is set

If viewport is less then (995 X any value) it will not work . If I decrease the firs value to be less than 995 it won't work . 

```js
 cy.viewport('ipad-2'); 
 cy.scrollTo('bottom'); - it will fail
``` 

```
Timed out retrying: cy.scrollTo() failed because this element is not scrollable:
  
<window>
  
Make sure you're targeting the correct element or use {ensureScrollable: false} to disable the scrollable check
```

If I put `ensureScrollable: false`,  the test will not fail but the behavior it will not happen.

**Comment by jennifer-shehane** [comment]
I can't recreate the issue as described. Please provide an application to visit where this issue fails or a repo of a reproducible example. The code below passes for me which means the bug is likely dependent on the structure of the application being tested.

```js
it('passes', () => {
  cy.visit('https://example.cypress.io')
  cy.viewport('ipad-2')
  cy.scrollTo('bottom')
})
```

We'll have to close this issue is a reproducible example can't be provided.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
