### ISSUE TITLE
Paused before potential out-of-memory crash

### ISSUE THREAD

**Issue by tnhu** [cypress-io/cypress#882]
- Operating System: Mac OS Sierra 10.12.6
- Cypress Version: 1.0.3
- Browser Version: Version 62.0.3202.89 (Official Build) (64-bit)

### Is this a Feature or Bug?

Bug

### Current behavior:

I have about 40 tests running locally. JavaScript bundle is quite large (40M, yes, sorry) due to sourcemap and other stuffs. After 12 tests, Chrome notified me that it paused because of potential out-of-memory crash when I had DevTools opened. If I don't have DevTools opened, the whole testing screen just became blank.

### Desired behavior:

Tests should be run without Chrome pausing/or crashing.

#### Test code:

N/A

### Additional Info (images, stack traces, etc)

<img width="1695" alt="screen shot 2017-11-06 at 7 13 09 pm" src="https://user-images.githubusercontent.com/30633/32475442-93b4db54-c326-11e7-8385-a3e1bdf6bdce.png">

**Comment by brian-mann** [comment]
Closing because this is a well known and documented problem.

If you're curious as to the full details it is explained at length in these other issues:

- https://github.com/cypress-io/cypress/issues/681
- https://github.com/cypress-io/cypress/issues/416#issuecomment-310485344
- https://github.com/cypress-io/cypress/issues/349
- https://github.com/cypress-io/cypress/issues/431
