### ISSUE TITLE
cy.get() querying behavior does not match jQuery's :visible and :hidden

### ISSUE THREAD

**Issue by JessefSpecialisterren** [cypress-io/cypress#8824]
### Current behavior
[The documentation on cy.get()](https://docs.cypress.io/api/commands/get.html) states:

>The querying behavior of this command matches exactly how $(…) works in jQuery.

This is not true for the `:visible` and `:hidden` selectors.

### Desired behavior
The documentation and the actual behavior should match.

### Test code to reproduce
Consider this html:

```html
<div style="visibility:hidden">Hello</div>
```

And this Cypress code:

```JavaScript
cy.get('div:hidden')
```

Using the selector `'div:hidden'` in `cy.get()` finds the div. Using that same selector with the actual jQuery `$()` [does not find it](https://jsfiddle.net/cxrtbho6/). The reverse goes for `'div:visible'`: `cy.get()` finds nothing, actual jQuery finds the element.

Note that jQuery is acting according to its own documentation here: https://api.jquery.com/visible-selector/ states 

>Elements with visibility: hidden (...) are considered visible. 

So `cy.get()` is deviating from an explicit statement in the jQuery documentation here.

### Versions
Cypress: 5.3.0
OS: Windows 10 Pro
Browser: Chrome 86
jQuery: 3.5.1

### Additional notes
When I report my first bug on a project, I like to say thanks. So, thank you for making an awesome testing tool, for making it available for free, for reading and responding to so many bug reports, for keeping on maintaining and extending and improving Cypress. Much appreciated 😊!

**Comment by jennifer-shehane** [comment]
Yeah, the behavior is different from jQuery in this case, so the documentation is probably too strict in saying it matches exactly. I would say it more or less is modeled off of or inspired by jQuery. I opened an issue in the docs to update this wording, so will close this issue here: https://github.com/cypress-io/cypress-documentation/issues/3238 

I would argue that Cypress query is more accurate in this case. Why would jQuery return this element as visible? 

`index.html`

```html
<html>
<body>
  <div style="visibility:hidden">Hello</div>  
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</body>
</html>
```

`spec.js`

```js
it('cypress selectors', () => {
  cy.visit('index.html')
  cy.get('div:hidden').should('have.length', 1)
  cy.get('div:visible').should('have.length', 0)
})

it('jquery selectors', () => {
  cy.visit('index.html')
  expect(Cypress.$('div:hidden')).to.have.length(1)
  expect(Cypress.$('div:visible')).to.have.length(0)
})
```


### Inside Cypress

<img width="531" alt="Screen Shot 2020-10-14 at 12 24 04 PM" src="https://user-images.githubusercontent.com/1271364/95949197-2b191480-0e18-11eb-8ecb-3c3fde0bc804.png">


### Outside Cypress

Querying using jQuery 3.5.1 does the opposite of within Cypress

<img width="362" alt="Screen Shot 2020-10-14 at 12 23 04 PM" src="https://user-images.githubusercontent.com/1271364/95949155-16d51780-0e18-11eb-874d-0f71bc8325ba.png">
