### ISSUE TITLE
The browser goes blank at the middle.

### ISSUE THREAD

**Issue by PrakashDahal** [cypress-io/cypress#8840]
### Current behavior

The test is running and at the middle the browser gets blank. The terminal gets pause too.
![image](https://user-images.githubusercontent.com/39849793/95969459-79391280-0e2e-11eb-9804-e52eb8725fe2.png)

----------------------------------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/39849793/95968590-56f2c500-0e2d-11eb-9a32-9268ab872183.png)

It has to be terminated and run again.

### Desired behavior

I would like to request to prevent browser from getting blank

### Test code to reproduce

I have encountered this issue multiple times in a long test case scenario. (if this is helpful)

### Versions

Cypress: 5.1.0
Chrome: 86.0.4240.75 (Official Build) (64-bit)

**Comment by jennifer-shehane** [comment]
Unfortunately we have to close this issue as there is not enough information to reproduce the problem. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue.
