### ISSUE TITLE
test:after:run - cy.request won't send out http request on test case fail

### ISSUE THREAD

**Issue by Jibbedi** [cypress-io/cypress#885]
- Operating System: Mac OS 10.13 (17A405)
- Cypress Version: 1.0.3
- Browser Version: Chrome 62.0.3202.89

### Is this a Feature or Bug?
Bug, probably

### Current behavior:
I am trying to send a request to report the outcome of the test to another service via http.
This works great by listening to the **test:after:run** event and using **cy.request** to send out the http call.

However, this only works if the test case succeeds. If the test case fails, it won't send out a request.

### Desired behavior:
Send out a request if the test case fails, too.

### How to reproduce:
Set up a **test:after:run** event listener and try to send out a http request.

#### Test code:

```js
describe('Test case', function () {
  it('will not send out request', function () {
    expect(true).to.eq(false);
  });

  it('will send out request', function () {
    expect(true).to.eq(true);
  });
});
```

```js

Cypress.on('test:after:run', function(test, runnable) {
  cy.request({
    method: 'POST',
    url : 'url',
    body : {
      data : 'test data'
    },
    auth : {
      user : 'username',
      pass : 'password'
    },
    headers : {
      'Content-Type': 'application/json'
    }
  }).then(function (response) {
    console.log(response);
  });

});


```

**Comment by brian-mann** [comment]
We don't / didn't consider the use case of using `cy` commands outside of a running test. This won't work because on a test failure we halt command execution and don't run anything after this.

There is a myriad of ways for us to implement this and you might have to use lower level API's than `cy.*` commands since those are really specific and come with very strict use case.

Can you answer what you are sending and why? It would help to better understand this use case. You want to send a network request on **every single test** whether its passing or failing? What information are you including with the request body? Curious.

**Comment by brian-mann** [comment]
It sounds like what you actually want and need is just a reporter.

Most of the time people do this in CI. They run Cypress - it generates a report, and then you send it to wherever you like.

You might want to read this: https://docs.cypress.io/guides/guides/reporters.html

Typically people use `junit` reporters which is XML that most CI systems and testing systems understand. That will include everything you're trying to send + more.
