### ISSUE TITLE
Not able to launch URLs which need proxy

### ISSUE THREAD

**Issue by Garimaja** [cypress-io/cypress#8886]
### Versions
 Cypress 5.3.0   , Chrome 86

**Comment by jennifer-shehane** [comment]
When opening a pull request, please fill out the [pull request template](https://github.com/cypress-io/cypress/blob/develop/PULL_REQUEST_TEMPLATE.md) provided - it requires necessary information we need to move forward with reviewing pull requests. 

If you can, please edit the initial comment of this PR filling out the pull request template including an explanation for why this PR is necessary. Otherwise, we will be closing this PR.
