### ISSUE TITLE
Cypress failing on Ubuntu with error "Syntax error: Unterminated quoted string"

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#8893]
I am installing cypress using npm, and working with version 4.8.0

My system is Ubuntu Xenial, ARMv8, 64 bit.

Cypress gets installed successfully, but fails to run with below error
~~~
It looks like this is your first time using Cypress: 4.8.0

Verifying Cypress can run /home/.cache/Cypress/4.8.0/Cypress [started]
Verifying Cypress can run /home/.cache/Cypress/4.8.0/Cypress [failed]

Cypress failed to start.

This is usually caused by a missing library or dependency.
The error below should indicate which dependency is missing.
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies installed.
----------
/home/.cache/Cypress/4.8.0/Cypress/Cypress: 3: /home/.cache/Cypress/4.8.0/Cypress/Cypress: Syntax error: Unterminated quoted string
----------
~~~
I have installed all the dependencies mentioned here <https://docs.cypress.io/guides/getting-started/installing-cypress.html#Ubuntu-Debian>, but nothing happened.

I also tried with latest version 5.4.0, but got the same syntax error as below
~~~
----------
/home/.cache/Cypress/5.4.0/Cypress/Cypress: 3: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected
----------
~~~

Can you please help me out, as I found some similar syntax issues, but those were because of 32 bit system. Mine is already 64 bit. Does cypress support ARM 64 bit platform? If yes, Can you please guide me on this? Thanks!!!

**Comment by wichpatricke** [comment]
@jennifer-shehane Thank you for the reponse!!!
Here are the logs
~~~
$ DEBUG=cypress:* cypress run

2020-10-20T15:31:50.352Z cypress:cli:cli cli starts with arguments ["/home/.nvm/versions/node/v10.22.1/bin/node","/home/build/reactive-interaction-gateway/examples/tests/node_modules/.bin/cypress","run"]
2020-10-20T15:31:50.361Z cypress:cli NODE_OPTIONS is not set
2020-10-20T15:31:50.363Z cypress:cli:cli program parsing arguments
2020-10-20T15:31:50.379Z cypress:cli:cli running Cypress with args [ Command { commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _noHelp: false, _exitCallback: undefined, _executableFile: undefined, parent: Command { commands: [Array], options: [Array], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _usage: '<command> [options]', _events: [Object], _eventsCount: 9, rawArgs: [Array], args: [] }, _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, _events: [Object: null prototype] { 'option:browser': [Function], 'option:ci-build-id': [Function], 'option:config': [Function], 'option:config-file': [Function], 'option:env': [Function], 'option:group': [Function], 'option:key': [Function], 'option:headed': [Function], 'option:headless': [Function], 'option:no-exit': [Function], 'option:parallel': [Function], 'option:port': [Function], 'option:project': [Function], 'option:quiet': [Function], 'option:record': [Function], 'option:reporter': [Function], 'option:reporter-options': [Function], 'option:spec': [Function], 'option:tag': [Function], 'option:dev': [Function] }, _eventsCount: 20, exit: true } ]
2020-10-20T15:31:50.767Z cypress:cli:cli variable-length opts parsed { args: [ '/home/.nvm/versions/node/v10.22.1/bin/node', '/home/build/reactive-interaction-gateway/examples/tests/node_modules/.bin/cypress', 'run' ], opts: Command { commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _noHelp: false, _exitCallback: undefined, _executableFile: undefined, parent: Command { commands: [Array], options: [Array], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _usage: '<command> [options]', _events: [Object], _eventsCount: 9, rawArgs: [Array], args: [] }, _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, _events: [Object: null prototype] { 'option:browser': [Function], 'option:ci-build-id': [Function], 'option:config': [Function], 'option:config-file': [Function], 'option:env': [Function], 'option:group': [Function], 'option:key': [Function], 'option:headed': [Function], 'option:headless': [Function], 'option:no-exit': [Function], 'option:parallel': [Function], 'option:port': [Function], 'option:project': [Function], 'option:quiet': [Function], 'option:record': [Function], 'option:reporter': [Function], 'option:reporter-options': [Function], 'option:spec': [Function], 'option:tag': [Function], 'option:dev': [Function] }, _eventsCount: 20, exit: true } }
2020-10-20T15:31:50.775Z cypress:cli parsed cli options {}
2020-10-20T15:31:50.776Z cypress:cli verifying Cypress app
2020-10-20T15:31:50.779Z cypress:cli checking environment variables
2020-10-20T15:31:50.789Z cypress:cli checking if executable exists /home/.cache/Cypress/5.4.0/Cypress/Cypress
2020-10-20T15:31:50.795Z cypress:cli Binary is executable? : true
2020-10-20T15:31:50.797Z cypress:cli binaryDir is  /home/.cache/Cypress/5.4.0/Cypress
2020-10-20T15:31:50.797Z cypress:cli Reading binary package.json from: /home/.cache/Cypress/5.4.0/Cypress/resources/app/package.json
2020-10-20T15:31:50.807Z cypress:cli Found binary version 5.4.0 installed in: /home/.cache/Cypress/5.4.0/Cypress
2020-10-20T15:31:50.811Z cypress:cli could not read binary_state.json file at "/home/.cache/Cypress/5.4.0/binary_state.json"
2020-10-20T15:31:50.812Z cypress:cli {}
2020-10-20T15:31:50.813Z cypress:cli is Verified ? undefined
2020-10-20T15:31:50.813Z cypress:cli running binary verification check 5.4.0
It looks like this is your first time using Cypress: 5.4.0
[15:31:50]  Verifying Cypress can run /home/.cache/Cypress/5.4.0/Cypress [started]
2020-10-20T15:31:50.841Z cypress:cli clearing out the verified version
2020-10-20T15:31:50.853Z cypress:cli undefined DISPLAY environment variable
2020-10-20T15:31:50.853Z cypress:cli Cypress will spawn its own Xvfb
2020-10-20T15:31:50.853Z cypress:cli needs Xvfb? true
2020-10-20T15:31:50.853Z cypress:cli Starting Xvfb
2020-10-20T15:31:50.918Z cypress:cli disabling Electron sandbox
2020-10-20T15:31:50.919Z cypress:cli running smoke test
2020-10-20T15:31:50.919Z cypress:cli using Cypress executable /home/.cache/Cypress/5.4.0/Cypress/Cypress
2020-10-20T15:31:50.919Z cypress:cli smoke test command: /home/.cache/Cypress/5.4.0/Cypress/Cypress --no-sandbox --smoke-test --ping=714
2020-10-20T15:31:50.919Z cypress:cli smoke test timeout 30000 ms
2020-10-20T15:31:50.992Z cypress:cli Smoke test failed: { Error: Command failed: /home/.cache/Cypress/5.4.0/Cypress/Cypress --no-sandbox --smoke-test --ping=714
/home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected
    at makeError (/home/build/reactive-interaction-gateway/examples/tests/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/build/reactive-interaction-gateway/examples/tests/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 2,
  stdout: '',
  stderr:
   '/home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected\n',
  failed: true,
  signal: null,
  cmd:
   '/home/.cache/Cypress/5.4.0/Cypress/Cypress --no-sandbox --smoke-test --ping=714',
  timedOut: false,
  killed: false }
2020-10-20T15:31:50.993Z cypress:cli error message: /home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected
2020-10-20T15:31:51.021Z cypress:cli Stopping Xvfb
[15:31:51]  Verifying Cypress can run /home/.cache/Cypress/5.4.0/Cypress [failed]
Cypress failed to start.
This is usually caused by a missing library or dependency.
The error below should indicate which dependency is missing.
https://on.cypress.io/required-dependencies
If you are using Docker, we provide containers with all required dependencies installed.
----------
/home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected
----------
Platform: linux (Ubuntu Linux - 16.04)
Cypress Version: 5.4.0
~~~

**Comment by ilaizra** [comment]
hey @jennifer-shehane any useful tips on resolving this? I am getting the same error and am not sure where in my code I am making this synthax error

TIA

**Comment by ilaizra** [comment]
> @jennifer-shehane Thank you for the reponse!!!
> Here are the logs
> 
> ```
> $ DEBUG=cypress:* cypress run
> 
> 2020-10-20T15:31:50.352Z cypress:cli:cli cli starts with arguments ["/home/.nvm/versions/node/v10.22.1/bin/node","/home/build/reactive-interaction-gateway/examples/tests/node_modules/.bin/cypress","run"]
> 2020-10-20T15:31:50.361Z cypress:cli NODE_OPTIONS is not set
> 2020-10-20T15:31:50.363Z cypress:cli:cli program parsing arguments
> 2020-10-20T15:31:50.379Z cypress:cli:cli running Cypress with args [ Command { commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _noHelp: false, _exitCallback: undefined, _executableFile: undefined, parent: Command { commands: [Array], options: [Array], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _usage: '<command> [options]', _events: [Object], _eventsCount: 9, rawArgs: [Array], args: [] }, _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, _events: [Object: null prototype] { 'option:browser': [Function], 'option:ci-build-id': [Function], 'option:config': [Function], 'option:config-file': [Function], 'option:env': [Function], 'option:group': [Function], 'option:key': [Function], 'option:headed': [Function], 'option:headless': [Function], 'option:no-exit': [Function], 'option:parallel': [Function], 'option:port': [Function], 'option:project': [Function], 'option:quiet': [Function], 'option:record': [Function], 'option:reporter': [Function], 'option:reporter-options': [Function], 'option:spec': [Function], 'option:tag': [Function], 'option:dev': [Function] }, _eventsCount: 20, exit: true } ]
> 2020-10-20T15:31:50.767Z cypress:cli:cli variable-length opts parsed { args: [ '/home/.nvm/versions/node/v10.22.1/bin/node', '/home/build/reactive-interaction-gateway/examples/tests/node_modules/.bin/cypress', 'run' ], opts: Command { commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _noHelp: false, _exitCallback: undefined, _executableFile: undefined, parent: Command { commands: [Array], options: [Array], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _usage: '<command> [options]', _events: [Object], _eventsCount: 9, rawArgs: [Array], args: [] }, _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, _events: [Object: null prototype] { 'option:browser': [Function], 'option:ci-build-id': [Function], 'option:config': [Function], 'option:config-file': [Function], 'option:env': [Function], 'option:group': [Function], 'option:key': [Function], 'option:headed': [Function], 'option:headless': [Function], 'option:no-exit': [Function], 'option:parallel': [Function], 'option:port': [Function], 'option:project': [Function], 'option:quiet': [Function], 'option:record': [Function], 'option:reporter': [Function], 'option:reporter-options': [Function], 'option:spec': [Function], 'option:tag': [Function], 'option:dev': [Function] }, _eventsCount: 20, exit: true } }
> 2020-10-20T15:31:50.775Z cypress:cli parsed cli options {}
> 2020-10-20T15:31:50.776Z cypress:cli verifying Cypress app
> 2020-10-20T15:31:50.779Z cypress:cli checking environment variables
> 2020-10-20T15:31:50.789Z cypress:cli checking if executable exists /home/.cache/Cypress/5.4.0/Cypress/Cypress
> 2020-10-20T15:31:50.795Z cypress:cli Binary is executable? : true
> 2020-10-20T15:31:50.797Z cypress:cli binaryDir is  /home/.cache/Cypress/5.4.0/Cypress
> 2020-10-20T15:31:50.797Z cypress:cli Reading binary package.json from: /home/.cache/Cypress/5.4.0/Cypress/resources/app/package.json
> 2020-10-20T15:31:50.807Z cypress:cli Found binary version 5.4.0 installed in: /home/.cache/Cypress/5.4.0/Cypress
> 2020-10-20T15:31:50.811Z cypress:cli could not read binary_state.json file at "/home/.cache/Cypress/5.4.0/binary_state.json"
> 2020-10-20T15:31:50.812Z cypress:cli {}
> 2020-10-20T15:31:50.813Z cypress:cli is Verified ? undefined
> 2020-10-20T15:31:50.813Z cypress:cli running binary verification check 5.4.0
> It looks like this is your first time using Cypress: 5.4.0
> [15:31:50]  Verifying Cypress can run /home/.cache/Cypress/5.4.0/Cypress [started]
> 2020-10-20T15:31:50.841Z cypress:cli clearing out the verified version
> 2020-10-20T15:31:50.853Z cypress:cli undefined DISPLAY environment variable
> 2020-10-20T15:31:50.853Z cypress:cli Cypress will spawn its own Xvfb
> 2020-10-20T15:31:50.853Z cypress:cli needs Xvfb? true
> 2020-10-20T15:31:50.853Z cypress:cli Starting Xvfb
> 2020-10-20T15:31:50.918Z cypress:cli disabling Electron sandbox
> 2020-10-20T15:31:50.919Z cypress:cli running smoke test
> 2020-10-20T15:31:50.919Z cypress:cli using Cypress executable /home/.cache/Cypress/5.4.0/Cypress/Cypress
> 2020-10-20T15:31:50.919Z cypress:cli smoke test command: /home/.cache/Cypress/5.4.0/Cypress/Cypress --no-sandbox --smoke-test --ping=714
> 2020-10-20T15:31:50.919Z cypress:cli smoke test timeout 30000 ms
> 2020-10-20T15:31:50.992Z cypress:cli Smoke test failed: { Error: Command failed: /home/.cache/Cypress/5.4.0/Cypress/Cypress --no-sandbox --smoke-test --ping=714
> /home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected
>     at makeError (/home/build/reactive-interaction-gateway/examples/tests/node_modules/execa/index.js:174:9)
>     at Promise.all.then.arr (/home/build/reactive-interaction-gateway/examples/tests/node_modules/execa/index.js:278:16)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   code: 2,
>   stdout: '',
>   stderr:
>    '/home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected\n',
>   failed: true,
>   signal: null,
>   cmd:
>    '/home/.cache/Cypress/5.4.0/Cypress/Cypress --no-sandbox --smoke-test --ping=714',
>   timedOut: false,
>   killed: false }
> 2020-10-20T15:31:50.993Z cypress:cli error message: /home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected
> 2020-10-20T15:31:51.021Z cypress:cli Stopping Xvfb
> [15:31:51]  Verifying Cypress can run /home/.cache/Cypress/5.4.0/Cypress [failed]
> Cypress failed to start.
> This is usually caused by a missing library or dependency.
> The error below should indicate which dependency is missing.
> https://on.cypress.io/required-dependencies
> If you are using Docker, we provide containers with all required dependencies installed.
> ----------
> /home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected
> ----------
> Platform: linux (Ubuntu Linux - 16.04)
> Cypress Version: 5.4.0
> ```



> @jennifer-shehane Thank you for the reponse!!!
> Here are the logs
> 
> ```
> $ DEBUG=cypress:* cypress run
> 
> 2020-10-20T15:31:50.352Z cypress:cli:cli cli starts with arguments ["/home/.nvm/versions/node/v10.22.1/bin/node","/home/build/reactive-interaction-gateway/examples/tests/node_modules/.bin/cypress","run"]
> 2020-10-20T15:31:50.361Z cypress:cli NODE_OPTIONS is not set
> 2020-10-20T15:31:50.363Z cypress:cli:cli program parsing arguments
> 2020-10-20T15:31:50.379Z cypress:cli:cli running Cypress with args [ Command { commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _noHelp: false, _exitCallback: undefined, _executableFile: undefined, parent: Command { commands: [Array], options: [Array], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _usage: '<command> [options]', _events: [Object], _eventsCount: 9, rawArgs: [Array], args: [] }, _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, _events: [Object: null prototype] { 'option:browser': [Function], 'option:ci-build-id': [Function], 'option:config': [Function], 'option:config-file': [Function], 'option:env': [Function], 'option:group': [Function], 'option:key': [Function], 'option:headed': [Function], 'option:headless': [Function], 'option:no-exit': [Function], 'option:parallel': [Function], 'option:port': [Function], 'option:project': [Function], 'option:quiet': [Function], 'option:record': [Function], 'option:reporter': [Function], 'option:reporter-options': [Function], 'option:spec': [Function], 'option:tag': [Function], 'option:dev': [Function] }, _eventsCount: 20, exit: true } ]
> 2020-10-20T15:31:50.767Z cypress:cli:cli variable-length opts parsed { args: [ '/home/.nvm/versions/node/v10.22.1/bin/node', '/home/build/reactive-interaction-gateway/examples/tests/node_modules/.bin/cypress', 'run' ], opts: Command { commands: [], options: [ [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option], [Option] ], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'run', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _noHelp: false, _exitCallback: undefined, _executableFile: undefined, parent: Command { commands: [Array], options: [Array], _execs: Set {}, _allowUnknownOption: false, _args: [], _name: 'cypress', _optionValues: {}, _storeOptionsAsProperties: true, _passCommandToAction: true, _actionResults: [], _helpFlags: '-h, --help', _helpDescription: 'output usage information', _helpShortFlag: '-h', _helpLongFlag: '--help', _usage: '<command> [options]', _events: [Object], _eventsCount: 9, rawArgs: [Array], args: [] }, _usage: '[options]', _description: 'Runs Cypress tests from the CLI without the GUI', _argsDescription: undefined, _events: [Object: null prototype] { 'option:browser': [Function], 'option:ci-build-id': [Function], 'option:config': [Function], 'option:config-file': [Function], 'option:env': [Function], 'option:group': [Function], 'option:key': [Function], 'option:headed': [Function], 'option:headless': [Function], 'option:no-exit': [Function], 'option:parallel': [Function], 'option:port': [Function], 'option:project': [Function], 'option:quiet': [Function], 'option:record': [Function], 'option:reporter': [Function], 'option:reporter-options': [Function], 'option:spec': [Function], 'option:tag': [Function], 'option:dev': [Function] }, _eventsCount: 20, exit: true } }
> 2020-10-20T15:31:50.775Z cypress:cli parsed cli options {}
> 2020-10-20T15:31:50.776Z cypress:cli verifying Cypress app
> 2020-10-20T15:31:50.779Z cypress:cli checking environment variables
> 2020-10-20T15:31:50.789Z cypress:cli checking if executable exists /home/.cache/Cypress/5.4.0/Cypress/Cypress
> 2020-10-20T15:31:50.795Z cypress:cli Binary is executable? : true
> 2020-10-20T15:31:50.797Z cypress:cli binaryDir is  /home/.cache/Cypress/5.4.0/Cypress
> 2020-10-20T15:31:50.797Z cypress:cli Reading binary package.json from: /home/.cache/Cypress/5.4.0/Cypress/resources/app/package.json
> 2020-10-20T15:31:50.807Z cypress:cli Found binary version 5.4.0 installed in: /home/.cache/Cypress/5.4.0/Cypress
> 2020-10-20T15:31:50.811Z cypress:cli could not read binary_state.json file at "/home/.cache/Cypress/5.4.0/binary_state.json"
> 2020-10-20T15:31:50.812Z cypress:cli {}
> 2020-10-20T15:31:50.813Z cypress:cli is Verified ? undefined
> 2020-10-20T15:31:50.813Z cypress:cli running binary verification check 5.4.0
> It looks like this is your first time using Cypress: 5.4.0
> [15:31:50]  Verifying Cypress can run /home/.cache/Cypress/5.4.0/Cypress [started]
> 2020-10-20T15:31:50.841Z cypress:cli clearing out the verified version
> 2020-10-20T15:31:50.853Z cypress:cli undefined DISPLAY environment variable
> 2020-10-20T15:31:50.853Z cypress:cli Cypress will spawn its own Xvfb
> 2020-10-20T15:31:50.853Z cypress:cli needs Xvfb? true
> 2020-10-20T15:31:50.853Z cypress:cli Starting Xvfb
> 2020-10-20T15:31:50.918Z cypress:cli disabling Electron sandbox
> 2020-10-20T15:31:50.919Z cypress:cli running smoke test
> 2020-10-20T15:31:50.919Z cypress:cli using Cypress executable /home/.cache/Cypress/5.4.0/Cypress/Cypress
> 2020-10-20T15:31:50.919Z cypress:cli smoke test command: /home/.cache/Cypress/5.4.0/Cypress/Cypress --no-sandbox --smoke-test --ping=714
> 2020-10-20T15:31:50.919Z cypress:cli smoke test timeout 30000 ms
> 2020-10-20T15:31:50.992Z cypress:cli Smoke test failed: { Error: Command failed: /home/.cache/Cypress/5.4.0/Cypress/Cypress --no-sandbox --smoke-test --ping=714
> /home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected
>     at makeError (/home/build/reactive-interaction-gateway/examples/tests/node_modules/execa/index.js:174:9)
>     at Promise.all.then.arr (/home/build/reactive-interaction-gateway/examples/tests/node_modules/execa/index.js:278:16)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   code: 2,
>   stdout: '',
>   stderr:
>    '/home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected\n',
>   failed: true,
>   signal: null,
>   cmd:
>    '/home/.cache/Cypress/5.4.0/Cypress/Cypress --no-sandbox --smoke-test --ping=714',
>   timedOut: false,
>   killed: false }
> 2020-10-20T15:31:50.993Z cypress:cli error message: /home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected
> 2020-10-20T15:31:51.021Z cypress:cli Stopping Xvfb
> [15:31:51]  Verifying Cypress can run /home/.cache/Cypress/5.4.0/Cypress [failed]
> Cypress failed to start.
> This is usually caused by a missing library or dependency.
> The error below should indicate which dependency is missing.
> https://on.cypress.io/required-dependencies
> If you are using Docker, we provide containers with all required dependencies installed.
> ----------
> /home/.cache/Cypress/5.4.0/Cypress/Cypress: 4: /home/.cache/Cypress/5.4.0/Cypress/Cypress: Syntax error: "(" unexpected
> ----------
> Platform: linux (Ubuntu Linux - 16.04)
> Cypress Version: 5.4.0
> ```

Hi!
Were you able to get this resolved? 
I'm having the same error and am stumped at the moment

**Comment by ACregan** [comment]
I'd just like to throw my hat in the ring to say I've attempted this and given up too. All required dependencies are installed on my jenkins server but it still gives the missing depenency message and follow up with this:

/home/USERNAME/.cache/Cypress/6.9.1/Cypress/Cypress: 17: Syntax error: Unterminated quoted string

I hope somebody can help pinpoint and resolve this issue, unfortunately that error message tells me very little I can work with.

**Comment by lukebelliveau** [comment]
I'm having a similar issue on Ubuntu 20.04. Here's my output with debug logs:

```
$ DEBUG=cypress:* npm run cypress run

> iris-console@0.1.0 cypress
> cypress open "run"

  cypress:cli:cli cli starts with arguments ["/home/ubuntu/.nvm/versions/node/v14.16.0/bin/node","/home/ubuntu/ROBOT/nuwave/iris-console/node_modules/.bin/cypress","open","run"] +0ms
  cypress:cli NODE_OPTIONS is not set +0ms
  cypress:cli:cli program parsing arguments +2ms
  cypress:cli:cli opening Cypress +1ms
  cypress:cli parsed cli options {} +80ms
  cypress:cli opening from options {"project":"/home/ubuntu/ROBOT/nuwave/iris-console"} +0ms
  cypress:cli command line arguments ["--project","/home/ubuntu/ROBOT/nuwave/iris-console"] +0ms
  cypress:cli verifying Cypress app +0ms
  cypress:cli checking environment variables +1ms
  cypress:cli checking if executable exists /home/ubuntu/.cache/Cypress/7.2.0/Cypress/Cypress +4ms
  cypress:cli Binary is executable? : true +5ms
  cypress:cli binaryDir is  /home/ubuntu/.cache/Cypress/7.2.0/Cypress +0ms
  cypress:cli Reading binary package.json from: /home/ubuntu/.cache/Cypress/7.2.0/Cypress/resources/app/package.json +0ms
  cypress:cli Found binary version 7.2.0 installed in: /home/ubuntu/.cache/Cypress/7.2.0/Cypress +5ms
  cypress:cli could not read binary_state.json file at "/home/ubuntu/.cache/Cypress/7.2.0/binary_state.json" +6ms
  cypress:cli {} +0ms
  cypress:cli is Verified ? undefined +2ms
  cypress:cli running binary verification check 7.2.0 +0ms
It looks like this is your first time using Cypress: 7.2.0

  cypress:cli clearing out the verified version +3ms
  cypress:cli undefined DISPLAY environment variable +0ms
  cypress:cli Cypress will spawn its own Xvfb +0ms
  cypress:cli needs Xvfb? true +2ms
  cypress:cli Starting Xvfb +0ms
  cypress:cli disabling Electron sandbox +16ms
  cypress:cli running smoke test +0ms
  cypress:cli using Cypress executable /home/ubuntu/.cache/Cypress/7.2.0/Cypress/Cypress +1ms
  cypress:cli smoke test command: /home/ubuntu/.cache/Cypress/7.2.0/Cypress/Cypress --no-sandbox --smoke-test --ping=478 +0ms
  cypress:cli smoke test timeout 30000 ms +0ms
  cypress:cli Smoke test failed: Error: Command failed with exit code 2: /home/ubuntu/.cache/Cypress/7.2.0/Cypress/Cypress --no-sandbox --smoke-test --ping=478
/home/ubuntu/.cache/Cypress/7.2.0/Cypress/Cypress: 1: Syntax error: word unexpected (expecting ")")
    at makeError (/home/ubuntu/ROBOT/nuwave/iris-console/node_modules/cypress/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/ubuntu/ROBOT/nuwave/iris-console/node_modules/cypress/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  shortMessage: 'Command failed with exit code 2: /home/ubuntu/.cache/Cypress/7.2.0/Cypress/Cypress --no-sandbox --smoke-test --ping=478',
  command: '/home/ubuntu/.cache/Cypress/7.2.0/Cypress/Cypress --no-sandbox --smoke-test --ping=478',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '/home/ubuntu/.cache/Cypress/7.2.0/Cypress/Cypress: 1: Syntax error: word unexpected (expecting ")")',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
} +12ms
  cypress:cli error message: /home/ubuntu/.cache/Cypress/7.2.0/Cypress/Cypress: 1: Syntax error: word unexpected (expecting ")") +2ms
  cypress:cli Stopping Xvfb +34ms
  ✖  Verifying Cypress can run /home/ubuntu/.cache/Cypress/7.2.0/Cypress
    → Cypress Version: 7.2.0
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

/home/ubuntu/.cache/Cypress/7.2.0/Cypress/Cypress: 1: Syntax error: word unexpected (expecting ")")

----------

Platform: linux (Ubuntu - 20.04)
Cypress Version: 7.2.0
```

**Comment by mdellabitta** [comment]
Just ended up here from a search. Looks like Cypress doesn't support ARM OOTB yet?

https://github.com/cypress-io/cypress/issues/4478
