### ISSUE TITLE
Property 'app' does not exist on type 'cy & EventEmitter'

### ISSUE THREAD

**Issue by stoplion** [cypress-io/cypress#8899]
Hi.

Source code from [Cypress on Rails](https://www.google.com/search?q=cypress+on+rails&oq=cypress+on+rails&aqs=chrome..69i57j0i22i30l3j69i60l3.2263j0j1&sourceid=chrome&ie=UTF-8)

```ts
// spec/cypress/support/on-rails.ts

Cypress.Commands.add('app', function (name, command_options) {
  return cy
    .appCommands({ name: name, options: command_options })
    .then((body) => {
      return body[0];
    });
});

```

`spec/cypress/tsconfig.json`

```json
{
  "compilerOptions": {
    "strict": true,
    "target": "es5",
    "lib": ["es6", "dom"],
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": false,
    "types": ["cypress"],
    "downlevelIteration": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": ["**/*.ts"]
}

```

Results in 
```
 Property 'app' does not exist on type 'cy & EventEmitter'.
```

**Comment by jennifer-shehane** [comment]
When opening an issue, please take the time to fill out the [issue template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE.md) - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using. 

Since you've added your own custom command, you will want to specify types for the command also - see instructions here: https://on.cypress.io/typescript-support#Types-for-custom-commands

**Comment by mspoulsen** [comment]
But the instructions don't work!

**Comment by IceMaD** [comment]
Managed to fix my project by inspecting source code of plugins.

Instead of doing as the doc suggest [here](https://docs.cypress.io/guides/tooling/typescript-support#Types-for-Custom-Commands) 
```javascript
declare global {
  namespace Cypress {
    interface Chainable {
      login: typeof login
    }
  }
}
```
I did
```javascript
declare namespace Cypress {
  interface Chainable {
    login: typeof login
  }
}
```

**Comment by nagash77** [comment]
@jaffrepaul Is [this](https://github.com/cypress-io/cypress/issues/8899#issuecomment-1631524301) something that needs to be looked at in the docs?
