### ISSUE TITLE
cy.visit('/') loads blank page.

### ISSUE THREAD

**Issue by kavitha24** [cypress-io/cypress#8904]
Hi 

I am experiencing a problem with cypress that it don't launch my test env url, it loads the blank page for `cy.visit('/')`.

Steps:
1. `$export HTTP_PROXY=http://my-company-proxy.com`
2. Added the following code to `plugin>index.js`

```js
on('before:browser:launch', (browser,args) => {
    if (browser.name === 'chrome') { 
      // ^ make sure this is your browser name, you may 
      // be using 'canary' or 'chromium' for example, so change it to match!
      args.push('--proxy-bypass-list=<-loopback>')
      return args
    }
  })
```
3. This is my test case
```js
describe("Verify login", function () {
    before(function () {
        cy.visit('https://----TestEnv ur--------') 
    })
```

Issue:
**Chrome:**
Without the Proxy setting it loads blank page
**After the proxy set it shows

```
HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE**
```

**Electron:**

```
DevTools failed to load SourceMap: Could not load content for https://********/__cypress/runner/popper.js.map: Unknown error
```

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
