### ISSUE TITLE
Parallel tests all running on all Docker containers

### ISSUE THREAD

**Issue by CScharer** [cypress-io/cypress#8912]
### Current behavior
When running tests in parallel using image: `cypress/included:5.4.0` every test is run on every container.  This multiplies the number of tests run by the number of replicas and therefore increase the time to complete by that much and reduces the number of tests available to run against the Cypress Dashboard.

### Desired behavior
When I run the tests in parallel they should be managed and passed to each container and only run once.

### Test code to reproduce
```
    entrypoint: ["/e2e/cypress-entrypoint.sh"]
    command: [ "run",
               "--browser", "${BROWSER}",
               "--ci-build-id", "${CI_BUILD_ID}",
               "--group", "${ENVIRONMENT}",
               "--headless",
               "--key", "${CYPRESS_PROJECT_KEY}",
               "--record",
               "--parallel",
               "--spec", "${SPEC_FILTER}",
               "--tag", "${CI_COMMIT_SHA},${CI_BUILD_ID},${BROWSER},${ENVIRONMENT},${AUTH_TYPE}" ]
```

### cypress-entrypoint.sh
#we exit 0 because we use the mochawesome reports to fail the build and not the exit code of a Cypress test
cypress "$@"
exit 0

### Versions
Cypress: 5.4.0 (Was working with 5.3.0)
Browser: Chrome
OS: Mac
CI: Gitlab

**Comment by CScharer** [comment]
We are starting 3 instances of Cypress using docker-compose that share this same command and environment and these runs would all have started within 10-15 seconds of each other, so they shouldn't be seen as different builds.

cypress_1   | + cypress run --browser chrome --ci-build-id 643247 --group encappdevelopment --headless --key 972db02a-12d8-4ff7-b29c-361b199967ea --record --parallel --spec 'cypress/integration/SmokeTests/**/*.spec.ts' --tag 475a5618a5c77abbf3af9922d28d6d1ce387ca1c,643247,chrome,encappdevelopment,AzureAD
cypress_2   | + cypress run --browser chrome --ci-build-id 643247 --group encappdevelopment --headless --key 972db02a-12d8-4ff7-b29c-361b199967ea --record --parallel --spec 'cypress/integration/SmokeTests/**/*.spec.ts' --tag 475a5618a5c77abbf3af9922d28d6d1ce387ca1c,643247,chrome,encappdevelopment,AzureAD
cypress_3   | + cypress run --browser chrome --ci-build-id 643247 --group encappdevelopment --headless --key 972db02a-12d8-4ff7-b29c-361b199967ea --record --parallel --spec 'cypress/integration/SmokeTests/**/*.spec.ts' --tag 475a5618a5c77abbf3af9922d28d6d1ce387ca1c,643247,chrome,encappdevelopment,AzureAD

![image](https://user-images.githubusercontent.com/3430747/96752863-ad638480-1394-11eb-96d6-ad5ce0d1be8a.png)

**Comment by CScharer** [comment]
It also appends a number to the CI Build Id and was happening with Cypress 5.3.0 too.

![image](https://user-images.githubusercontent.com/3430747/96755768-be15f980-1398-11eb-8455-29a027f3ef12.png)
![image](https://user-images.githubusercontent.com/3430747/96755785-c2daad80-1398-11eb-8c4e-0a7f9ed45bc5.png)
![image](https://user-images.githubusercontent.com/3430747/96755793-c66e3480-1398-11eb-94ed-f5ebcdf30b56.png)

**Comment by jennifer-shehane** [comment]
You should not share your record key in a public place. There are reasons why this key should be kept secret as explained here: https://on.cypress.io/projects#Record-key

**We strongly advise that you regenerate a new key since you have exposed your private record key.** Instructions here: https://on.cypress.io/projects#Create-new-record-key

---

Is this a recent issue that you're encountering? Was this previously working correctly and now has started creating multiple runs? That will help us narrow down the issue. 

Also, is there a reason you're passing the ciBuildId? What was happening before when you didn't pass this - because generally Cypress finds this ID on its own, but there are some circumstances where it's required.

**Comment by CScharer** [comment]
Oops, thanks for pointing that out.  Done!

**Comment by CScharer** [comment]
Anything else I can provide or any luck reproducing this?

**Comment by jennifer-shehane** [comment]
Is this a recent issue that you're encountering? Was this previously working correctly and now has started creating multiple runs? That will help us narrow down the issue.

Also, is there a reason you're passing the ciBuildId? What was happening before when you didn't pass this - because generally Cypress finds this ID on its own, but there are some circumstances where it's required.

**Comment by CScharer** [comment]
This has been happening since Cypress 6.3.0 and so I'm still on 6.2.1.  I don't believe removing the ciBuildId helped and I think that actually caused it to to not show the build in the dashboard (although we're not using the dashboard now because of the issue).

**Comment by BHunter2889** [comment]
@CScharer I came here looking for answers to a different issue, but I'll chime in here and hopefully it helps... I just set ours up recently using GitLab CI and it coordinates all the tests according to your expectation. The big thing I noticed was you're using GitLab CI but also using a docker-compose to spin up multiple containers. Just use the one image, built from a single dockerfile, use the `parallel:` gitlab job param to set the number of containers to spin up with this image to coordinate parallel tests with the Dashboard Service. Try this in your .gitlab_ci.yml and set your CYPRESS_RECORD_KEY in your project level Env Variables in your CI settings:

```
cypress_parallel:
  image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${PROJECT_VERSION} 
  stage: test
  parallel: 6  ### NOTE: This is the important part. Use this instead of spinning up multiple containers with docker-compose.
  variables: 
    GROUP_ID: ${PROJECT_NAME}/${CI_COMMIT_BRANCH}/cypress_e2e_runners-${CI_PIPELINE_ID}
    CYPRESS_RECORD_KEY: ${K8S_SECRET_CYPRESS_RECORD_KEY}
  script:
    - npx cypress cache path
    - npx cypress cache list
    - tsc --version 
    - npm run e2e-ci-demo:record
```
With that `e2e-ci-demo:record` being:
```
cypress run --record --spec cypress/integration/demo/**/*.spec.ts --parallel --group $GROUP_ID
```

Apologies if I'm off base with what your problem is, brain is a bit scattered trying to resolve my own issue haha but thought this might be helpful.

**Comment by CScharer** [comment]
> @CScharer I came here looking for answers to a different issue, but I'll chime in here and hopefully it helps... I just set ours up recently using GitLab CI and it coordinates all the tests according to your expectation. The big thing I noticed was you're using GitLab CI but also using a docker-compose to spin up multiple containers. Just use the one image, built from a single dockerfile, use the `parallel:` gitlab job param to set the number of containers to spin up with this image to coordinate parallel tests with the Dashboard Service. Try this in your .gitlab_ci.yml and set your CYPRESS_RECORD_KEY in your project level Env Variables in your CI settings:
> 
> ```
> cypress_parallel:
>   image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${PROJECT_VERSION} 
>   stage: test
>   parallel: 6  ### NOTE: This is the important part. Use this instead of spinning up multiple containers with docker-compose.
>   variables: 
>     GROUP_ID: ${PROJECT_NAME}/${CI_COMMIT_BRANCH}/cypress_e2e_runners-${CI_PIPELINE_ID}
>     CYPRESS_RECORD_KEY: ${K8S_SECRET_CYPRESS_RECORD_KEY}
>   script:
>     - npx cypress cache path
>     - npx cypress cache list
>     - tsc --version 
>     - npm run e2e-ci-demo:record
> ```
> 
> With that `e2e-ci-demo:record` being:
> 
> ```
> cypress run --record --spec cypress/integration/demo/**/*.spec.ts --parallel --group $GROUP_ID
> ```
> 
> Apologies if I'm off base with what your problem is, brain is a bit scattered trying to resolve my own issue haha but thought this might be helpful.

**Comment by CScharer** [comment]
@BHunter2889 I appreciate the suggestion, but we didn't do it that way for the following reasons:

- We only have 1 or 2 runners, but they have lots of resources so we can run as many containers as we have cores.
- Doing this, when running locally also allows us to use the 8-12-16 or more cores in our machine to cut the runtime WAY WAY down.

**Comment by BHunter2889** [comment]
> @BHunter2889 I appreciate the suggestion, but we didn't do it that way for the following reasons:
> 
> * We only have 1 or 2 runners, but they have lots of resources so we can run as many containers as we have cores.
> * Doing this, when running locally also allows us to use the 8-12-16 or more cores in our machine to cut the runtime WAY WAY down.

I suppose that makes sense. Ours is running in a the self-hosted GitLab instance for the massive enterprise I work for so good chance we're comparing apples to oranges in terms of environments and resources we have to work with. 

Prior to setting up the parallel runners, our project was taking as long as 2+ hours to run ~52 e2e tests alone.  After some tinkering, setting up parallel, and bugging the team managing the GitLab instance to increase the resources (they doubled to start after seeing what I was doing, seems they added more since haha) and as of an hour ago, I ran 185 tests on the same project across 6 parallel GitLab runners in under 10 minutes total. 

I was originally trying to run `docker-compose up` locally myself but even on my 2020 MBP it took over an hour with over half my system resources shared with the container. Our situation is tricky though because we're testing against our components hosted in a Storybook instances so it can be a bit of a tangled mess trying to manually manage containers and so 185 tests in <10 minutes feels like a massive win for us, or at least me lol.  😅
