### ISSUE TITLE
Chrome (and Electron) is breaking before beginning the tests

### ISSUE THREAD

**Issue by caugbr** [cypress-io/cypress#8950]
There is an error that happens before the test is loaded and points to runner.js at function setup() > enable(). It seems that the sent namespace is just '?' and the monted RegExp results in /^?$/ ... and it generates the error: "Nothing to repeat".
How can I fix this? ..Thanks!

![image](https://user-images.githubusercontent.com/2520477/96998925-c0986080-150a-11eb-9731-780b6a25dbbc.png)

![image](https://user-images.githubusercontent.com/2520477/96998974-d148d680-150a-11eb-98c6-e26ffef9ccec.png)

**Comment by jennifer-shehane** [comment]
Did you happen to open Cypress in debug mode? Passing `DEBUG` as an environment variable?

Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
