### ISSUE TITLE
Jira Cloud addon is not loading after addon implement getting token from Jira context

### ISSUE THREAD

**Issue by milan-easykad** [cypress-io/cypress#8958]
### Current behavior

I am testing the Jira cloud add-on. To be able to load the Jira add-on in Cypress I am using a trick:   
```js 
cy.visit(config.JIRA_WELCOME_URL, {   
        onBeforeLoad: (win) => {   
            win["parent"] = win;   
        }   
    });
```

And the application was successfully loaded.   
But Jira add-on recently implements getting JWT token from Jira context and forwarding token to all add-on API.  

```js
return new Promise((resolve, reject) =>  
        AP.context.getToken((token) => {  
            return resolve(request.call({  
                baseURL: baseURL || config.ROOT_SERVRE_URL,  
                headers: { 'Authorization': "JWT " + token },  
                ...params  
            }))  
        })  
        );  
```
After this change, the Jira add-on is not loaded anymore.    

### Desired behavior
Jira should render addon. 
Even without the trick that I have using to archive that. 

### Versions

Cypress: 4.12.1 / 5.4.0
Chrome: 86
Win OS

**Comment by jennifer-shehane** [comment]
Without a reproducible example, I'm not exactly sure where this JWT token is meant to be inserted in your test code. We do accept `headers` options for both `cy.visit()` and `cy.request()`, where you could sent the JWT token header if needed. 

Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
