### ISSUE TITLE
Allow to specify Minimatch options

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [cypress-io/cypress#8980]
### What would you like?

Cypress automatically includes minimatch and exposes it as Cypress.minimatch.
However I am not able to choose options of minimatch https://github.com/isaacs/minimatch/tree/master#options as they are hardcoded:
```
MINIMATCH_OPTIONS = { dot: true, matchBase: true }
```
### Why is this needed?
I want to be able to set globally, within spec file or on individual  `cy.route()` command `minimatch.options {}`  
In particular I wish to specify nocase https://github.com/isaacs/minimatch/tree/master#nocase for glob matches.
However I think that other minimatch options will be useful as well

**Comment by jennifer-shehane** [comment]
`Cypress.minimatch()` accepts options as its third argument. Currently this is just a utility to test globs and would have no effect on how `cy.route()` glob matching is performed. 

We would have to have somewhere to surface the glob matching options. We will be moving to `cy.route2()` behavior soon, so it may be worthwhile trying that out since we're moving there, but I don't think this option is available in there either.

**Comment by flotwig** [comment]
Hey @michael-freidgeim-webjet,

You can use `minimatch`'s `makeRe` function to compile your custom pattern and options into a RegExp, which you can then use with `cy.route` and `cy.route2`.

Example:

```js
const regExp = Cypress.minimatch.makeRe('*something*', { nobrace: true, /** whatever options you want **/ })
cy.route(regExp, /* ... */)
```

You can even create a helper function or custom Cypress command around `makeRe` if you want to reuse the same options elsewhere.

Closing this issue since we do not want to add this to core at this time.

**Comment by bahmutov** [comment]
It would be a good example to add to the docs and to the recipe
