### ISSUE TITLE
Microsoft Teams (MSTeams) Integration

### ISSUE THREAD

**Issue by jimpriest** [cypress-io/cypress#8989]
### What would you like?
Currently there is Slack integration (https://docs.cypress.io/guides/dashboard/slack-integration.html#Install-the-Cypress-Slack-app)  Would be nice to see similar integration for MSTeams.   

### Why is this needed?
According to Microsoft and other sources - MSTeams is outpacing Slack in growth:   https://gopractice.io/blog/slack-vs-teams-vs-workplace/

**Comment by jennifer-shehane** [comment]
You can express interest and see progress for this feature on our Roadmap from our Dashboard's product board here: https://portal.productboard.com/cypress-io/1-cypress-dashboard

I will be closing this issue and closing it to all comments since this is related to our Dashboard.

All related work for Dashboard features is handled in that ProductBoard and will be addressed by the Dashboard team directly when you comment there. We have already noted the initial comment from this issue there. Please refer all future comments there. Thank you.
