### ISSUE TITLE
4.12.0 Regression: Cypress.dom.isVisible change in behaviour

### ISSUE THREAD

**Issue by ElisaDellaC** [cypress-io/cypress#8998]
We have a scrollable dropdown list and our test wants to verify how many elements are visible when opening the list: to do so we use `Cypress.dom.isVisible`

Until Cypress version 4.11.0 our test were working as expected: `Cypress.dom.isVisible` was only detecting as visible the elements of the list that were visible on screen when opening the list and as not visible the ones present in the list but for which you need to scroll down in order to see them displayed on screen.

As from Cypress version 4.12.0, when opening the dropdown list all elements in the list are detected as visible.

If this is a wanted change in behaviour, could you please advise on a workaround to have our test working? 

Here a reproduction scenario: 
https://github.com/rosahealth/cypress-tiny-test-fork

Many thanks!

**Comment by jennifer-shehane** [comment]
I can recreate this behavior using the example in https://github.com/rosahealth/cypress-tiny-test-fork This is a regression in 4.12.0

This was introduced in this PR: https://github.com/cypress-io/cypress/pull/8095 I git bisected and saw the issue was introduced in this commit https://github.com/cypress-io/cypress/commit/298612bc684e76d7338e54d8e6b9c0781662b9e7

### 4.11.0

<img width="661" alt="Screen Shot 2020-10-28 at 5 29 40 PM" src="https://user-images.githubusercontent.com/1271364/97427600-305f7e80-1943-11eb-8d9e-a514354bd3f8.png">


### 4.12.0

<img width="655" alt="Screen Shot 2020-10-28 at 5 28 37 PM" src="https://user-images.githubusercontent.com/1271364/97427545-1a51be00-1943-11eb-9b5b-9d3ace9af63e.png">

**Comment by bahmutov** [comment]
released in v6.1.0
