### ISSUE TITLE
When you unfocus Cypress tab in Chrome, JS stops executing & fails the tests.

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress#9]
When you unfocus the Cypress tab in the middle of running tests, the JavaScript stops executing and the current test fails due to timeout.

![screen shot 2015-03-31 at 10 01 31 am](https://cloud.githubusercontent.com/assets/1271364/6920596/606cf66e-d78d-11e4-86c6-f85d1dcda1e9.png)

Instead of failing, maybe cy could 
- pause the tests
- display a message about being unfocused
- ???

**Comment by brian-mann** [comment]
This is due to modern browsers throttling `setTimeout` on inactive tabs from `0.04s` to `1s`. There is no flag to turn this off, it is a constant.

The only way around this is to use `setImmediate` or `requestAnimationFrame`. The problem is `mocha`  as Cypress does not use `setTimeouts` for async.

But an even bigger problem is given we update everything on our end not to use `setTimeout`, the users application will still be throttled if they use `setTimeout`, which would still cause the tests to fail / be flakey.

**Comment by brian-mann** [comment]
There are some potential work arounds work investigating - such as playing silent audio, which prevents Chrome from backgrounding a tab.

Also listed here as a known issue: https://docs.cypress.io/docs/known-issues

**Comment by jennifer-mann** [comment]
As of [`0.16.0`](https://github.com/cypress-io/cypress/wiki/Changelog#0160-05172016), when running a project in the new Cypress browser environment, if a new tab is opened, a message now displays discouraging the use of multiple tabs while testing.
