### ISSUE TITLE
Nested describes cause the very last it to pass even if it fails

### ISSUE THREAD

**Issue by duttkin** [cypress-io/cypress#9004]
I have a spec that has two describes nested under a top level subscribe.  When the final it fails, cypress still passes the test.  When I removed the nested describes, cypress works as expected.  This should not be the case.  We should be able to have as many nested describes as we want to clearly report what is being tested

```js
describe('Assignment Page', () => {
  before(() => {
    ...
  });

  describe('First', () => {
     it('should do something', () => {
     ...
     });
  });
  describe('Second', () => {
     it('passes no matter what', () => {
     cy.visit(...);
     ...
     });
  });
});
```

I tested the issue in both Cypress 5.4 and 5.5

**Comment by jennifer-shehane** [comment]
I ran the code provided and it fails. Please provide a **full** example we can copy and paste to see the bug, likely something else in your test or Cypress configuration is important to reproduce.

```js
describe('Assignment Page', () => {
  before(() => {
  })

describe('First', () => {
  it('should do something', () => {
  });
});

describe('Second', () => {
  it('passes no matter what', () => {
    expect(true).to.be.false
     });
  });
});
```

<img width="438" alt="Screen Shot 2020-10-29 at 5 45 13 PM" src="https://user-images.githubusercontent.com/1271364/97561412-83523800-1a0e-11eb-87e0-8f82c8d427ba.png">


Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by duttkin** [comment]
It is sad that you won’t even give a few minutes to a problem in your code. We are in the process of evaluating and switching to Cypress. Looks like that decision needs to be rethought
