### ISSUE TITLE
Trying to drag and drop on a canvas heavy page 

### ISSUE THREAD

**Issue by ashajoy** [cypress-io/cypress#9005]
Trying to automate a drag and drop for a heavily canvassed page 

```js
it('Click and drag fraction to the center of the page', () => {
    cy.showQuestionById(skillIds.fractionSkill);
    cy.get('[class*="side-panel"]')
      .trigger('mousedown',100, 25, { force:true })
    cy.get('.manipulatives')
      .trigger('mousemove', 100 ,50, { force:true })
      .trigger('mouseup', { force:true });
  });
```

We used trigger and moving the mouse after selecting  the element 

If we didn't write `{ force:true }` both .manipulatives and side-panel has this error https://github.com/cypress-io/cypress/issues/7306

```
CypressError: cy.click() failed because this element is detached from the DOM.

<element>

Cypress requires elements be attached in the DOM to interact with them.
```

If we do `force:true` it clicks the locations we set without dragging the fraction

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

Right now there doesn't seem to be enough information to reproduce the problem on our end - there is no application to run the tests against and some of the custom command code is not provided. 

We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
