### ISSUE TITLE
I want to save an element text/value in a variable to use in assertions later.

### ISSUE THREAD

**Issue by RadwaSaleh** [cypress-io/cypress#9010]
Hi,

I want to be able to save an element text before closing popup modal to use it in assertions in later steps.
using alias in the beforeEach block doesn't work because the element is not visible/accessible yet.
Also using invoke('text') or .text() or set the value as env value leave the variable undefined because of the async behavior.

here's my code
```js
    let formatText; 
    cy.get(projectsPage.projectFormatList).eq(projectFormatIndex).find('span').then(($formatElement) => {
            formatText = $formatElement.text();
OR
            formatText = $formatElement.invoke('text');
            cy.get($formatElement).click();
        })

//After modal close and doing some required steps
    cy.get(projectsPage.projectFormat).should('have.text', formatText);
```

Is there anything that I miss? if not then I think this is a must have feature really.

**Comment by jennifer-shehane** [comment]
Issues in this repo are reserved for potential bugs or feature requests so that our team can fully focus on improving the product. This issue will be closed since it appears to be neither a bug nor a feature request.

We suggest asking questions relating to how to use Cypress be asked in our [community chat](https://gitter.im/cypress-io/cypress). Also try searching our [existing GitHub issues](https://gitter.im/cypress-io/cypress/issues), reading through our [documentation](https://docs.cypress.io), or searching [Stack Overflow](https://stackoverflow.com/questions/tagged/cypress) for relevant answers. 

You can also create [new issue](https://github.com/cypress-io/cypress-documentation/issues/new) or pull request in our [docs](https://github.com/cypress-io/cypress-documentation) if you think our documentation could be clearer regarding your question.
