### ISSUE TITLE
4.8.0 Regression: Nested describes with before hook does not run final test

### ISSUE THREAD

**Issue by duttkin** [cypress-io/cypress#9026]
I am running into an issue with nested describes and cy.visit that causes the final test to either not actually execute or just return as successful.  I tested this issue with 5.4 and 5.5 and it occurs in both versions.  Below is a test that I used to reproduce the issue.

I would expect this test to fail on the last it block.  I noticed a couple things when running this test in the GUI (running the open command).  First the final test never gets a successful green check mark or red x for failure.  The box is just there like it never ran but it will pass if run outside the gui which it should not pass.  Second, if you watch the dev tools console in the GUI, the whole GUI will flash and the before which should have run just once will run again.

```js
describe('Top level describe ', () => {
  before(() => {
    cy.request('https://www.cypress.io');
  });

  describe('Nested Describte 1', () => {
    beforeEach(() => {
      cy.visit('https://www.google.com');
    });

    it('should pass', () => {
      cy.location().should(loc => {
        expect(loc.origin).to.eq('https://www.google.com');
      });
      cy.get("#hplogo").should('be.visible');
    });

    it('should pass', () => {
      cy.location().should(loc => {
        expect(loc.origin).to.eq('https://www.google.com');
      });
      cy.get("#hplogo").should('be.visible');
    });

    it('should pass', () => {
      cy.location().should(loc => {
        expect(loc.origin).to.eq('https://www.google.com');
      });
      cy.get("#hplogo").should('be.visible');
    });
  });

  describe('Nested Describe 2', () => {
    beforeEach(() => {
      cy.visit('https://www.yahoo.com');
    });

    it('should fail', () => {
      cy.location().should(loc => {
        expect(loc.origin).to.eq('https://www.google.com');
      });
    });
  });
});
```

**Comment by jennifer-shehane** [comment]
Please next time comment in the original issue opened, instead of opening a new issue. We like to keep all of the original context together.

Original issue for reference: https://github.com/cypress-io/cypress/issues/9004

I can reproduce the issue with the below code. This is a regression introduced in 4.8.0 in this PR: https://github.com/cypress-io/cypress/pull/7154

You can downgrade to 4.7.0 or restructure your tests as a workaround.

### Reproducible example

```js
describe('Top level describe ', () => {
  before(() => {
    cy.request('https://www.cypress.io')
  })

  describe('Nested Describe 1', () => {
    it('should pass', () => {
      expect(true).to.be.true
    })
  })

  describe('Nested Describe 2', () => {
    it('should fail', () => {
      cy.visit('https://example.cypress.io').then(() => {
        expect(true).to.be.false
      })
    })
  })
})
```

### 4.7.0

<img width="556" alt="Screen Shot 2020-10-30 at 2 26 53 PM" src="https://user-images.githubusercontent.com/1271364/97674481-ffef2000-1abb-11eb-9f44-971f36d2fb36.png">

### 4.8.0

<img width="524" alt="Screen Shot 2020-10-30 at 3 20 04 PM" src="https://user-images.githubusercontent.com/1271364/97679234-688dcb00-1ac3-11eb-8471-78402df8909c.png">

**Comment by jennifer-shehane** [comment]
Another example of this bug (I believe), when visiting multiple domains from https://github.com/cypress-io/cypress/issues/14179

### Reproducible example

`spec.js`

```js
describe('page', () => {
  before('before 1', () => {})

  describe('inner describe 1', () => {
    it('runs describe 1 test 1', () => {
      cy.visit('docs.cypress.io')
    })
  })

  describe('inner describe 2', () => {
    it('runs describe 2 test 1', () => {
      cy.visit('example.cypress.io')
    })
  })
})
```

### 4.7.0

<img width="474" alt="Screen Shot 2020-12-15 at 1 21 46 PM" src="https://user-images.githubusercontent.com/1271364/102181187-816a0880-3ed8-11eb-8696-5dde8d42ed72.png">


### 4.8.0

<img width="472" alt="Screen Shot 2020-12-15 at 1 20 22 PM" src="https://user-images.githubusercontent.com/1271364/102181080-567fb480-3ed8-11eb-8058-fe5d088ddb5d.png">

**Comment by c32hedge** [comment]
@jennifer-shehane thanks for identifying the introduced version and duplicate issue. It’s important to note that not only does the second test not execute, but the top-level `before` block executes twice instead of just once—the modified example has an empty `before` block so it doesn’t capture that part.

**Comment by c32hedge** [comment]
@jennifer-shehane I'm curious whether the `internal-priority` label means this is near the top of the Cypress team's list to address? In my case it's quite a blocker since we have two different systems with different superdomains (mix of cloud and locally-hosted pages) that are closely integrated. Currently the only workaround I can think of is to create multiple spec files, use a naming convention so that they're executed in the order I want, and share state between them by writing to and reading from a file or something. But that's a lot of work so I'm anxious to hear if this is slated to be fixed soon or if there might be a cheaper workaround.

**Comment by jennifer-shehane** [comment]
@c32hedge We used to use the internal-priority label to add issues to our external board. We don't use it anymore. I'll add this to our new board, but I can't gaurantee it will be prioritized.
