### ISSUE TITLE
Are we have any way to prevent cypress clear memory between each test and log in again when I do "cypress run"? 

### ISSUE THREAD

**Issue by viengiang** [cypress-io/cypress#9038]
### Current behavior
Hi guys, first thing, I want to thanks for your work.

I having a problem: My project has multiple test cases that need to test, so I don't want to log in again and again between each test case when I do "cypress run". Every time my test log in that will waste 20 seconds just for nothing. Are we have any way to prevent cypress clear memory between each test and log in again when I do "cypress run"? 

![image](https://user-images.githubusercontent.com/61610632/97671887-aab30e80-1abb-11eb-9b3f-70682f386654.png)

### Desired behavior
Keep login between each test when do "cypress run". Thanks a lot.

### Versions

Cypress 5.5

**Comment by csvan** [comment]
No, runs are isolated by design and you always get a clean session.

**Comment by jennifer-shehane** [comment]
Each test file will relaunch the browser and start from a clean state, so that each file can be run isolated, especially when run in parallel. This is by design.

If you wanted to stay logged in within a singular test file across several 'it' definitions, you can preserve cookies or localStorage. Options for saving cookies: https://on.cypress.io/cookies. Options for saving localStorage here: https://github.com/cypress-io/cypress/issues/461
