### ISSUE TITLE
Get is not retrying itself

### ISSUE THREAD

**Issue by AyWa** [cypress-io/cypress#904]
- Operating System: Mac OS Sierra `10.12.6`
- Cypress Version: `1.0.3`
- Browser Version: chrome `62.0.3202.89 64 bits`

### Is this a Feature or Bug?

It is a bug. Or I didn't get the documentation 
`get will automatically retry itself until assertions you've chained all pass.`

### Current behavior:

```
  cy.wait(['@getRoles'])
  cy.get(".myClass1 .myClass2") // time out was just to test
    .contains("Something")
```
Little tricky but when my apps mount the 'get' will target 3 element and after the request that I wait (and the rerender of react) the number of element will be 5.
Maybe my app rerender is too slow but it seems like the get will always target those 3 elements. (if i put a wait of 100ms before it the get it will target the 5)

`will automatically retry itself until assertions you've chained all pass.` seems to not working

### Desired behavior:

Check if the selector change state when its direct chainer is not successfull

### How to reproduce:

add an element after a timeout.

#### Test code:

```
  cy.wait(['@getRoles'])
  cy.get(".myClass1 .myClass2") // time out was just to test
    .contains("Something")
```

**Comment by jennifer-shehane** [comment]
The state of your application that Cypress is looking for if the example you provided is that there are *any* elements that exist on the page matching `.myClass1 .myClass2` with the content `Something` within those elements. The `get` will no longer retry if it finds this situation on the page.

If you want the tests to not continue until 5 elements are found in the `get`, you will need to write an assertion to that effect (so that the `get` will retry until that assertion is true). 

Something like:

```js
  cy.wait(['@getRoles'])
  cy.get(".myClass1 .myClass2").should("have.length", 5)
    .contains("Something")
```

Let me know if I understood your question correctly and if this solves it.

**Comment by AyWa** [comment]
Thx for your answer. Yeah I understand. I thought 'contains' was an assertion and so it will work like a have length

**Comment by brian-mann** [comment]
Contains has a default assertion that it will retry until it finds an element with the matching content.

However it is independently run from the `get`. Once the `get` resolves the `contains` begins to run, scoped to whatever elements the `get` returned.

That's different than an assertion - an assertion acts as a "guard" on whatever it is chained to, preventing it from resolving until all of the associated assertions pass.

Have you read our guides? Specifically this one: https://docs.cypress.io/guides/core-concepts/introduction-to-cypress.html
