### ISSUE TITLE
Uncaught syntax error in selector expression

### ISSUE THREAD

**Issue by tzolnai** [cypress-io/cypress#9089]
I experienced an issue with syntax error detection. I managed to use a wrong selector accidentally in one of my tests which were not recognized as a syntax error. It just passed and then sometimes it just failed in a different context.

### Current behavior
A syntax error is not caught in a specific selector string and the test goes on.

### Desired behavior
The syntax error should be caught and the test should fail.

### Test code to reproduce
```js
describe('Syntax error.', function() {

	it('Uncaught syntax error 1.', function() {
		cy.visit('https://googlechrome.github.io/samples/picture-in-picture/');

		cy.get('a[href=\'http://www.blender.org')
			.should('be.visible');

		// Passes without a problem
	});

	it('Uncaught syntax error 2.', function() {
		cy.visit('https://googlechrome.github.io/samples/picture-in-picture/');

		cy.get('a[href=\'http://www.blender.or')
			.should('be.visible');

		// Fails on should('be.visible'), because of the missing 'g' in the end.
	});
	
	it('Find catches the same syntax error.', function() {
		cy.visit('https://googlechrome.github.io/samples/picture-in-picture/');

		cy.get('body').find('a[href=\'http://www.blender.org')
			.should('be.visible');

		// Syntax error, unrecognized expression: a['href=http://www.blender.org
	});

	it('Contains catches the same syntax error.', function() {
		cy.visit('https://googlechrome.github.io/samples/picture-in-picture/');

		cy.contains('a[href=\'http://www.blender.org', 'www.blender.org')
			.should('be.visible');

		// Syntax error, unrecognized expression: a[href='http://www.blender.org:not(script,style):cy-contains('www.blender.org'),
		// a[href='http://www.blender.org[type='submit'][value~='www.blender.org']
	});

	it('No syntax error.', function() {
		cy.visit('https://googlechrome.github.io/samples/picture-in-picture/');

		cy.get('a[href=\'http://www.blender.org\']')
			.should('be.visible');

		// Passes correctly.
	});
});
```

The closing `\']` characters are missing from the selector, which causes this weird behavior. In the different test cases, it's visible, that contains() and find() method catches the same syntax error. My expectation is to catch the same syntax error with get() method too. get() behaves in this case like it understands what I tried to write down and it passes and fails, just like that syntax error would be not there at all. The problem here, that the same selector won't work in a different context, so this syntax error will fail eventually, but it would be better if it can fail with get() too, so we can find these typos faster.

### Versions

cypress version: 5.3.0
browser: chromium 78.0.3904.108
OS: openSUSE Leap 15.0

**Comment by jennifer-shehane** [comment]
In the future, please comment in the original issue instead of opening a new issue so that we can maintain the context of the conversation in one place.

We use sizzle (jQuery) for our selector engine. 

- 1st example: Sizzle does not recognize this as having a syntax error and returns a valid element. 

<img width="560" alt="Screen Shot 2020-11-05 at 11 20 08 AM" src="https://user-images.githubusercontent.com/1271364/98199167-fe5ca680-1f58-11eb-8f1e-c245e42d5518.png">

- 2nd example, this is also not recognized by Sizzle as a syntax error and searches for an a element matching `http://www.blender.or` which does not exist.

- 3rd example, this throws an error because Cypress actually mutates the selector under the scene when used in a `.contains()` to exclude things like script and style tags and to create priority of elements over other elements, so the actual selector gets constructed to `$("a[href='http://www.blender.org:not(script,style),a[href='http://www.blender.org[type='submit'][value~='www.blender.org']")` which throws as this is not recognized as a valid selector by Sizzle.

Overall, this is a situation where we would not be able to determine whether this is the selector you intended and want us to match on, or if this is an incorrect selector for your use case - because they are both valid, albeit what you didn't intend to match on. 

If you think this should show a syntax error, you can open an issue with jQuery's sizzle engine to change their logic. https://github.com/jquery/sizzle

**Comment by tzolnai** [comment]
> If you think this should show a syntax error, you can open an issue with jQuery's sizzle engine to change their logic. https://github.com/jquery/sizzle

Thanks! I'll check sizzle.
