### ISSUE TITLE
Vaadin Combobox input field type action not working properly

### ISSUE THREAD

**Issue by kutlaykural** [cypress-io/cypress#9114]
### Current behavior
Could not able use search functionality of Vaadin Lazy Loading Combobox 

it is useful manually;
![image](https://user-images.githubusercontent.com/38225108/98359451-5074f900-2039-11eb-8258-aab8daf4c083.png)

automation code cannot continue;
![image](https://user-images.githubusercontent.com/38225108/98359392-34715780-2039-11eb-9f81-30d02d84df18.png)

### Desired behavior
fill into combobox with given text and filter matched values

### Test code to reproduce

```js
/// <reference types="cypress" />

context('Vaadin Components', () => {
  beforeEach(() => {
    cy.visit('https://vaadin.com/components/vaadin-combo-box/java-examples')
  })

  it('.type() - type into Vaadin Combobox', () => {
    cy.contains('Lazy loading with callbacks',{timeout:20000}).click()
    cy.get('#callback-box',{timeout:20000}).should('be.visible')
    cy.get('#callback-box').shadow().find('vaadin-text-field#input').type('Oliver',{force:true})
      
  })
})
```
### Versions

cypress 5.5

**Comment by jennifer-shehane** [comment]
Thanks for providing a reproducible example.

I think this likely has to do with how Cypress interacts with how this input is coded. It looks like there's an XHR request performed on focus and each subsequent key event. And I believe that the input may be rerendering underneath on each key event, so that the target ends up being `null` for some reason. 

This may be related to this issue. https://github.com/cypress-io/cypress/issues/5480

### Reproducible

```js
it('.type() - type into Vaadin Combobox', () => {
  cy.visit('https://vaadin.com/components/vaadin-combo-box/java-examples')
  cy.contains('Lazy loading with callbacks', { timeout: 20000 }).click()
  cy.get('#callback-box', { timeout: 20000 })
  .should('be.visible')
  .shadow()
  .find('vaadin-text-field#input')
  .type('Oliver')
})
```

<img width="1057" alt="Screen Shot 2020-11-09 at 12 16 31 PM" src="https://user-images.githubusercontent.com/1271364/98504476-72fb5200-2285-11eb-9010-3f434b52d915.png">


### Type Events

<img width="923" alt="Screen Shot 2020-11-09 at 12 13 53 PM" src="https://user-images.githubusercontent.com/1271364/98504507-83133180-2285-11eb-8c2f-7541c6f1f11c.png">
