### ISSUE TITLE
cy.screenshot() contain number of attempts

### ISSUE THREAD

**Issue by SlavikDMI** [cypress-io/cypress#9126]
Hello.

When I use retry-ability of cypress (not plugin), and make screenshot (cy.screenshot()) and if cypress try it do one more times, filename with screenshot contrain number of attempts - "about - 375x820 (attempt 2)". Can I turn of it?
I'd like that file name will be the same as cy.screenshot('about')

### Test code to reproduce

cy.screenshot('about')

### Versions
5.5.0

**Comment by jennifer-shehane** [comment]
You cannot turn off the screenshot during retries to not having the appended `(attempt #)` with any single configuration within Cypress. 

The purpose is to maintain all screenshots during all attempts, instead of overwriting them. If we did not append the attempt #, then we would overwrite all attempt screenshots so that they would no longer be available for review, which is not ideal for everyone wanting to review why their test is flaky. 

Can I ask why you don't want to maintain all screenshots of all attempts?

We suggest that any post-processing of screenshots (such as changing the name of the screenshot to remove the `(attempt #)` from the title) be done in the `after:screenshot` event documented here: https://on.cypress.io/after-screenshot-api

**Comment by dominics** [comment]
> Can I ask why you don't want to maintain all screenshots of all attempts?

Because, for visual regression testing, the name of the screenshot tends to be a stable key, so that you can drive comparisons between builds. The after:screenshot plugin API is a sufficient workaround, as long as you know what filename rewrites you'll have to undo (see docs).

> The purpose is to maintain all screenshots during all attempts, instead of overwriting them [or] they would no longer be available for review, which is not ideal

But, I am passing `{ overwrite: true }` to `cy.screenshot()` - I'd like for this to signal that I accept this risk, as the docs imply.  Would probably break BC though, so might be a non-starter.

### docs

I think there's also [some missing documentation: the naming conventions section](https://docs.cypress.io/api/commands/screenshot#Naming-conventions) doesn't mention the "(attempt n)" convention at all; it only mentions the addition of `(failed)`, and the `ensureSafePath()` deduplication (which adds `(n)` rather than `(attempt n)`)

The documentation says the "they will be appended with a number" behavior can be changed by passing the `overwrite` flag, but it's referring to skipping `ensureSafePath()`, **not** that it will also skip this logic (which I think can be a source of confusion, because both involve adding a number):
https://github.com/cypress-io/cypress/blob/98bdc39effe5033bbb9236a83812db4a1f62c6c9/packages/server/lib/screenshots.js#L368-L370
