### ISSUE TITLE
5.2.0 Regression: "TypeError: webpack is not a function" when baseUrl present in tsconfig.json

### ISSUE THREAD

**Issue by jwalton** [cypress-io/cypress#9145]
### Current behavior
```
Oops...we found an error preparing this test file:

  cypress/integration/myTest.js

The error was:

TypeError: webpack is not a function

```

### Desired behavior
Cypress should run tests.

### Test code to reproduce
https://github.com/jwalton/cypress-test-tiny

```
git clone git@github.com:jwalton/cypress-test-tiny.git
cd cypress-test-tiny
npm install
npm cypress run
```

### Versions
This works fine in Cypress 4.x, 5.0.0, and 5.1.0, but 5.2.0 and higher, it breaks.

I did a little digging at the line it's failing on is [here](https://github.com/cypress-io/cypress/blob/36a4289a98d65eb16ec5714a9e246dfc5fc56922/npm/webpack-preprocessor/index.ts#L226):

```js
    const compiler = webpack(webpackOptions)
```

Again, I couldn't figure out how to set a breakpoint here and hit this, so I added a `console.log(webpack)` to see what webpack actually was.  What's interesting here is that in our project, in the root folder we have a folder called "webpack" with some configuration files in it, and the contents of the `webpack` variable here are clearly from our `/webpack/index.js`, not from the real webpack.  (Perhaps this is related to https://github.com/cypress-io/cypress/issues/8555?)

**Comment by jwalton** [comment]
Updated with test case.

**Comment by echenley** [comment]
What happens if you remove the `paths` property from the root `.tsconfig`? I was having a similar issue and found that our .tsconfig had something to the effect of:

```json
{
  "paths": {
    "*": ["src/*", "node_modules/*"]
  }
}
```

Because of #8555, that configuration was causing all `require()` calls to look in the root `node_modules` before looking in local `node_modules` (i.e. the normal node resolution algorithm), which caused all sorts of issues with mismatched versions of dependencies.

I added a little more info in [this comment](https://github.com/cypress-io/cypress/issues/8948#issuecomment-726932743).

**Comment by jennifer-shehane** [comment]
I can recreate this with the provided repo: https://github.com/jwalton/cypress-test-tiny This is breaking in version 5.4.0+ for me though. 

@echenley Removing the `paths` from the provided reproducible doesn't resolve the issue. 

<img width="838" alt="Screen Shot 2020-11-16 at 12 02 04 PM" src="https://user-images.githubusercontent.com/1271364/99216241-93865780-2803-11eb-98bf-6b5abbadd59c.png">

Smallest repo involves this in the base `tsconfig.json`

```json
{
  "compilerOptions": {
    "baseUrl": "."
  }
}
```

With the following dependencies:

`package.json`

```json
{
  "devDependencies": {
    "cypress": "5.6.0",
    "typescript": "^4.0.5"
  }
}
```

**Comment by jwalton** [comment]
This might actually be correct behavior.  According to the [typescript docs](https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url):

> Setting baseUrl informs the compiler where to find modules. All module imports with non-relative names are assumed to be relative to the baseUrl.

And, in Typescript 4.1, we now have [the ability to set paths without setting baseUrl](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#paths-without-baseurl) (although tsconfig-paths-webpack-plugin will complain if you try to actually do this).

**Comment by chrisbreiding** [comment]
As you noted, this is the correct behavior. Setting `baseUrl` to `.` causes TypeScript to resolve imports starting with `.` instead of `./node_modules`, so since `./webpack/index.js` exists, it will load that instead of the actual webpack package since it finds it first. It's the same as [this issue](https://github.com/cypress-io/cypress/issues/9326#issuecomment-775209958) where the conflict was `tsconfig-paths.json`. 

Unfortunately there's nothing we can do to prevent the conflict. Using TS 4.1 and not setting baseUrl seems to be a promising workaround. Otherwise, using a name different than `webpack` for the directory would also work.
