### ISSUE TITLE
cannot re-run same tests with dashboard

### ISSUE THREAD

**Issue by lughino** [cypress-io/cypress#9157]
Hi all, I got a weird behavior with cypress dashboard triggered with github actions...
The workflow ran triggered by a commit and a couple of tests were failing due to network communication on our server.
I tried to re-run the e2e test workflow and it succeeded almost immediately, but none of the tests were executed.
The cypress dashboard didn't even receive the new run...
Is there some weird logic that prevents to re-run the same workflow?

**Comment by jennifer-shehane** [comment]
As described in the GitHub Actions example repo [here](https://github.com/cypress-io/github-action#parallel) (see the Warning section), the Cypress Dashboard API connects parallel jobs into a single logical run using GitHub commit SHA plus workflow name. If you attempt to re-run GitHub checks, the Dashboard thinks the run has already ended.

In order to truly rerun parallel jobs, push an empty commit with `git commit --allow-empty -m "re-run checks" && git push`. As another work around you can generate and cache a custom build id. Read [Adding a unique build number to GitHub Actions](https://medium.com/attest-engineering/adding-a-unique-github-build-identifier-7aa2e83cadca) for more info on that option.

**Comment by paschalidi** [comment]
@jennifer-shehane I am wondering if there is a simpler workaround for this one these days. Anything you might seen that works?

**Comment by mellis481** [comment]
Also, the steps listed in the article linked above don't even work.  Much easier instructions that actually work are in the Cypress documentation [here](https://github.com/cypress-io/github-action#robust-custom-build-id).
