### ISSUE TITLE
4.12.1 Regression: after() block causes errors in before() to be hidden

### ISSUE THREAD

**Issue by kpittman-securus** [cypress-io/cypress#9162]
### Current behavior
If I have a `before()` that threw an error, and anything (or even nothing) inside an `after()` block, the test runner gets hung up and will not display the error from the `before()`.

This behavior only occurs on tests with multiple `it` blocks.

### Desired behavior
Should behave the same as when I remove the `after()`

* display the error and exit cleanly.

### Test code to reproduce
```js
describe("A spec with an after() block has an error in a before() block", () => {
  before(() => {
    cy.request("https://httpstat.us/404");
  });
  after(() => {
    cy.log("after"); // if you remove these 3 lines - the entire after() block, not just the cy.log - the stack trace is shown correctly
  });
  it("has a test", () => {
    expect(true).to.be.true;
  });
  it("has another test", () => {
    expect(true).to.be.true;
  });
});
```

![image](https://user-images.githubusercontent.com/62567227/98723322-d35ac400-2357-11eb-82ba-20abc6253a0b.png)

### Versions
At least 4.12.1 through 5.6.0

**Comment by jennifer-shehane** [comment]
This is a regression introduced in 4.12.1. This must have been introduced in https://github.com/cypress-io/cypress/pull/8113, since there were very few commits in this release and that one involves test hooks.

```js
describe('hangs when error in a before() block', () => {
  before(() => {
    expect(true).to.be.false
  })
  after(() => {})
  it('has a test')
  it('has another test')
})
```

### 4.12.0

<img width="562" alt="Screen Shot 2020-11-16 at 11 35 24 AM" src="https://user-images.githubusercontent.com/1271364/99215009-1ad1cc00-2800-11eb-97d2-7c3072fd741b.png">



### 4.12.1

<img width="563" alt="Screen Shot 2020-11-16 at 11 37 04 AM" src="https://user-images.githubusercontent.com/1271364/99215000-15748180-2800-11eb-8b75-8fd5d15f38e7.png">
