### ISSUE TITLE
Webpack Compilation Error getting thrown while trying to upgrade cypress to anything above 5.1.0

### ISSUE THREAD

**Issue by adityagautam** [cypress-io/cypress#9172]
I am having an issue where if I try to upgrade cypress to anything above version 5.1.0 its throwing Webpack Compilation Error.

As soon as I revert back the cypress version to 5.1.0. Everything starts working.

**Error:**
```
Error: Webpack Compilation Error
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: Cannot read property 'close' of undefined
```

Here is my `package.json` file 
```json
{
  "name": "automation-appsec-ui",
  "version": "1.0.0",
  "description": "cypress test",
  "main": "index.js",
  "scripts": {
    "lint": "./node_modules/.bin/tslint ./cypress/**/*.ts ",
    "runTests": "cypress run",
    "runCypress": "npm run runTests"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/node": "14.14.7",
    "log4js": "^0.6.38",
    "speakeasy": "^2.0.0",
    "sync-request": "^4.1.0",
    "tslint": "6.1.3",
    "allure-commandline": "^2.13.0",
    "mocha": "^7.0.1",
    "mocha-allure-reporter": "^1.4.0",
    "webpack": "5.4.0"
  },
  "devDependencies": {
    "@babel/core": "7.12.3",
    "@babel/preset-env": "7.12.1",
    "@bahmutov/add-typescript-to-cypress": "^2.1.2",
    "@cypress/webpack-preprocessor": "5.4.11",
    "ansi-styles": "^4.3.0",
    "babel-loader": "8.2.1",
    "chalk": "^4.1.0",
    "cypress": "5.2.0",
    "mocha-junit-reporter": "^1.23.3",
    "ts-loader": "8.0.11",
    "tslint": "5.20.1",
    "typescript": "^4.0.5"
  }
}
```

Node version: v14.15.0

Pleaes let me know if anyother info is needed to debug this issue.

**Comment by Narretz** [comment]
Is the error thrown we you compile your own app? This could mean that you are not setting a dependency explicitly, but it's a dp used by Cypress, and after you update Cypress, the dependency is now different and doesn't work with your app anymore.

**Comment by adityagautam** [comment]
Yes the error is being thrown while the test is being compiled by cypress. what dependency needs to be set explicitly apart from the one I have mentioned in package.json?

**Comment by Narretz** [comment]
I didn't mean "while Cypress compiles the tests", so you can disregard my comment.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Provide the code from your plugins file or any preprocessor code, plus test code needed to run to show issue. Also, I'm not sure what version you are updating from, providing that would also be helpful.

Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
