### ISSUE TITLE
Github Apps - Cypress not commenting on PR for all test suites

### ISSUE THREAD

**Issue by mihaic195** [cypress-io/cypress#9184]
### Current behavior

I have multiple test suites, but the Cypress bot only adds 1 comment to the PR (the first one that finishes).
![Screenshot 2020-11-12 at 18 58 33](https://user-images.githubusercontent.com/34626017/98971026-4eb7a380-2519-11eb-9622-b7b450ea3856.png)
![Screenshot 2020-11-12 at 19 00 58](https://user-images.githubusercontent.com/34626017/98971113-6b53db80-2519-11eb-8950-76892a393fa2.png)

### Desired behavior

For each test suite, there should a separate comment in the associated PR.

### Test code to reproduce

Create multiple test suites in a single repository. Each test suite has an associated GitHub workflow.

### Versions

Cypress v5.5.0

**Comment by jennifer-shehane** [comment]
Yeah, it doesn't look like our GitHub integration is commenting on a single PR associated with the information from several Dashboard runs, although the GitHub status checks appear to be showing both of the runs. 

We typically recommend using groups to separate 'jobs' within a single PR, so that they show up in the same Dashboard run (single url like https://dashboard.cypress.io/projects/ypt4pf/runs/13460/specs) instead of separate runs. This will make a single comment for a single run, showing all test results. https://docs.cypress.io/guides/guides/parallelization.html#Grouping-test-runs This should give the desired comments you're looking for.

**Comment by mihaic195** [comment]
@jennifer-shehane 
thank you for your response. Indeed, the status checks appear to be showing both of the runs. I did group my tests. One has the group `E2E` and another has the group `Smoke`. I've also added different tags to both of them using the `tag` key. The Cypress bot is commenting still only for the first group of tests that finishes.
For now, I've disabled commenting and only follow the check statuses, as the Cypress comments are not really a deal-breaker for us.
I think it's still worth a look to fix this for upcoming versions.

**Comment by jennifer-shehane** [comment]
Is this still an issue? Our Dashboard has made several changes since this issue was opened, want to see if this has been addressed.

**Comment by mihaic195** [comment]
@jennifer-shehane I don't think it's valid anymore. You can close it. Thanks.

**Comment by ghost** [comment]
I'll make a comment here and maybe open another issue later but for now I wanted to comment that grouping is not always possible so it would make sense if it was possible to have multiple separate runs on the same PR and display them all in a single comment (or multiple?). 

For example, we are using Vercel integration on a monorepo which triggers multiple deployments on each PR. Each deployment will trigger a different Cypress test run but grouping them is not possible due to the randomness of each trigger. So one may finish much later than the others. Yes one solution is to allow grouping with increasing the configurable delay but that makes things more unpredictable.

Thank you

**Comment by jennifer-shehane** [comment]
@kostas-pblworks Thanks for the feedback, I've forwarded it to the team responsible for the GitHub PR comments.
