### ISSUE TITLE
I recently did the latest update now my automated test runs throw errors.

### ISSUE THREAD

**Issue by kalebmccaw** [cypress-io/cypress#9187]
I recently did the latest update now my automated test runs throw errors.

![Cypress error](https://user-images.githubusercontent.com/60949168/98992333-eac5b880-24e1-11eb-84e4-af57c13fd23e.PNG)

Kalebmccaw@aviamedia.com

Thank You,

Kaleb Mccaw

**Comment by Narretz** [comment]
You should at least write which version you used before.

**Comment by kalebmccaw** [comment]
I was using 5.5.0 and upgraded to 5.6.0.

**Comment by jennifer-shehane** [comment]
@kalebmccaw Can you provide a reproducible example? Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
