### ISSUE TITLE
StorageEvents does not work in tests

### ISSUE THREAD

**Issue by CSchulz** [cypress-io/cypress#9189]
### Current behavior
Storage events does not work in app iframe. Normal custom events works.

```js
$0.contentWindow.addEventListener('storage', (e) => console.log(e))
undefined
$0.contentWindow.dispatchEvent(
      new StorageEvent({
        detail: {
          key: 'key',
          newValue: null,
          oldValue: null,
        }
      })
)
true

$0.contentWindow.addEventListener('asd', () => console.log('Asd'))
undefined
$0.contentWindow.dispatchEvent(
      new CustomEvent('asd', {
        detail: {
          key: 'key',
          newValue: null,
          oldValue: null,
        }
      })
)
VM288:1 Asd
true
```

![image](https://user-images.githubusercontent.com/1520593/99058125-0b067d80-259d-11eb-9fa4-71c2eca870ad.png)

### Desired behavior
Storageevents should also be propagated in iframes.

### Test code to reproduce
Use the sample lines from above.

### Versions
4.12.1
5.6.0

**Comment by jennifer-shehane** [comment]
Can you provide code that we can run that would show this failing in the context of your Cypress tests? What tests are you running that are failing in the context of how your application code is running.  Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
