### ISSUE TITLE
eq() does not seem to be honouring the default timeout when running against Electron.

### ISSUE THREAD

**Issue by joetidee** [cypress-io/cypress#9199]
### Current behavior

I am running a test that uses `eq(1)` and it randomly fails. When changed to `eq(1,  { timeout: 4000 })` the test consistently passes. The occurs with running in headless mode (Electron). When running against local Chrome the test always passes.

### Desired behavior

For the `eq()` command to honour the default timeout of 4000ms.

### Test code to reproduce

This is the command used to run the tests:
`cypress run --config-file cypress-config.dev.json`

This is the test:
```js
it('archives an item immediately', function() {
  cy.get('[data-test="insert-item"]').eq(1).click();
  cy.get('[data-test="chooser-text-item"]').click();
  cy.get('[data-test="text-item-textarea"]').eq(1).type(mockData.textItems[1].title).type('{enter}');
})
```

### Versions

Cypress: 5.3.0
Browser: Electron
OS: MacOS High Sierra

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
