### ISSUE TITLE
UX improvement, highlight the current test running (and maybe the line?)

### ISSUE THREAD

**Issue by SimoneGianniHNP** [cypress-io/cypress#9238]
### What would you like?
The name of the current test running should always be clearly visible somewhere on top of the side panel.

### Why is this needed?
When watching the video of a test is extremely tedious to find the place where a given test is being executed, and scanning a video of 15/20 minutes searching for a single frame is not easy at all. 

Reporting at least the name of the test being run at that moment, big on top, would help.

The current line of the test would be incredibly good, but that's probably asking too much, even if you have it cause it's then reported in errors. 

The current workaround is to:
- Search on the source which one is the NEXT test from the one I need to watch
- Check here and there until the NEXT one is the first of the list of stuff to execute
- Then try to go back until I don't find the start of the test I'm looking for

**Comment by jennifer-shehane** [comment]
@SimoneGianniHNP Thanks for opening an feature reuqest. I have a question just to clarify the use case. 

- Is your request needed for failing tests or for all tests (regardless of status)? Just wondering if you have a use case for watching the video for passing tests and needing to track those down or if it's just failing. 

For failing tests, when recording to the Cypress Dashboard you'd be able to see and filter by all failed tests and also see the test code of each one. There's a video alongside that will jump to the exact point of failure in the video also. This may save you some time, rather than searching through a 20 min video.

<img width="1057" alt="Screen Shot 2020-11-19 at 12 19 37 PM" src="https://user-images.githubusercontent.com/1271364/99626904-9a120a80-2a61-11eb-9d69-640de1e299f3.png">

**Comment by SimoneGianniHNP** [comment]
Hi Jennifer,
no, not necessarily failed test.

While the runner is running, it should report the name of the test currently running, so that it’s visible in the recorded video.

**Comment by jennifer-shehane** [comment]
Closing this issue as highlighting the currently running test is available as part of Cypress [Test Replay](https://docs.cypress.io/guides/cloud/debugging/test-replay). Test Replay allows you to see and click on any test that ran to see how your application under test ran at that time including DOM changes, console logs, and network requests.
