### ISSUE TITLE
Browser Hangs while retrying test

### ISSUE THREAD

**Issue by yusufJinadu** [cypress-io/cypress#9335]
![retry-error](https://user-images.githubusercontent.com/39502587/100263463-d5bf3f80-2f4d-11eb-8f81-04dcb6d69454.JPG)

**Comment by bahmutov** [comment]
When opening an issue, please fill out the [bug report template](https://raw.githubusercontent.com/cypress-io/cypress/develop/.github/ISSUE_TEMPLATE/1-bug-report.md) provided - it requires the necessary information we need to help you.

- please provide a reproducible code example we can run to investigate

Please make sure to update to the [current version of Cypress](https://on.cypress.io/changelog).

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.
