### ISSUE TITLE
Assertion should('not.be.visible') doesn't work as expected

### ISSUE THREAD

**Issue by Karnikel** [cypress-io/cypress#9348]
### Current behavior
Assertion `cy.get('[data-cy=an_invisible_button').should('not.be.visible');` fails with `Timed out retrying: Expected to find element: [data-cy=an_invisible_button], but never found it.`

### Desired behavior
The assertion should be pass, because the invisible button is really not visible.

### Test code to reproduce
cy.get('[data-cy=an_invisible_button').should('not.be.visible');

### Versions
Bug was visible in Cypress version 6.0.0
Last known working Cypress Verion: 5.1.0 (Only tested because I updated to 6.0.0 from that version)

**Comment by jaroslav-kubicek** [comment]
Does the element exist on the page? There is a breaking change in `not.be.visible` assertion - it now checks whether the element _is_ in the DOM AND is not visible whereas before it passed when the element wasn't on the page OR was invisible.

You can check the release notes: https://docs.cypress.io/guides/references/changelog.html#6-0-0 Believe me, we also have many errors like this now 😄

**Comment by jennifer-shehane** [comment]
Yes, this is expected behavior as of 6.0. Please see our Migration Guide for a detailed explanation. https://on.cypress.io/migration-guide

You’ll want to change your assert to .should(‘not.exist’) if you want to ensure it’s not in the DOM. 

We understand this may be cumbersome to change but we think it’s better than having tests potentially falsely pass. We found a misspelled selector query in our own tests when updating even where it wasn’t testing what we thought.

**Comment by KhizerRehan** [comment]
@jennifer-shehane 
cy.get('[data-cy=element').should('not.exists).should('not.be.visible'); // doesn't work
cy.get('[data-cy=element').should('not.exists); // does work => `expected null to not exist`
cy.get('[data-cy=element').should('not.be.visible'); // does work => `expected undefined not to be visible`

what should be the right way?

**Comment by stacypetrova** [comment]
> > cy.get('[data-cy=an_invisible_button').should('not.be.visible');

Just add the ], so you'll have: 
`cy.get('[data-cy=an_invisible_button]').should('not.be.visible');`

**Comment by abhidp** [comment]
> > > cy.get('[data-cy=an_invisible_button').should('not.be.visible');
> 
> Just add the ], so you'll have:
> `cy.get('[data-cy=an_invisible_button]').should('not.be.visible');`

as Jennifer said above, `should('not.be.visible')` is deprecated from `6.0.0` onwards. It wont work no matter what.

**Comment by gweaths** [comment]
> > > > cy.get('[data-cy=an_invisible_button').should('not.be.visible');
> > 
> > 
> > Just add the ], so you'll have:
> > `cy.get('[data-cy=an_invisible_button]').should('not.be.visible');`
> 
> as Jennifer said above, `should('not.be.visible')` is deprecated from `6.0.0` onwards. It wont work no matter what.

Is this true, as i'm using it on 6.4.0 and it works for me.  How would you test the scenarios where you know the element in the DOM is there, but not displayed. How do you test the DOM element is there and not visible / displayed, if you can no longer use `not.be.visible` ? What alternatives are there , as `not.exist` is not a viable option here surely, due to the fact the element **is** in the DOM, its just hidden / or display:none;

**Comment by bahmutov** [comment]
Nothing was deprecated, the assertions are still there, we just separated existence from visibility assertions to make it a lot more clearer

**Comment by stacypetrova** [comment]
> > > > cy.get('[data-cy=an_invisible_button').should('not.be.visible');
> > 
> > 
> > Just add the ], so you'll have:
> > `cy.get('[data-cy=an_invisible_button]').should('not.be.visible');`
> 
> as Jennifer said above, `should('not.be.visible')` is deprecated from `6.0.0` onwards. It wont work no matter what.

For me this construct works) I have 7.0.0 version.

**Comment by spbond** [comment]
> Yes, this is expected behavior as of 6.0. Please see our Migration Guide for a detailed explanation. https://on.cypress.io/migration-guide
> 
> You’ll want to change your assert to .should(‘not.exist’) if you want to ensure it’s not in the DOM.
> 
> We understand this may be cumbersome to change but we think it’s better than having tests potentially falsely pass. We found a misspelled selector query in our own tests when updating even where it wasn’t testing what we thought.

I have to respectfully disagree with your design choice for the following reasons:

- Automated testing should not be dependent on implementation choices.  If an element does not exist then it is not visible. This is the intuitive behavior of  checking for non-visibility and what most users will expect.
- If you want to ensure that an element exists and cannot be seen to protect against spelling errors, or for any other reason, this can be accomplished with `.should('exist').and('not.be.visible')`.  However, you cannot currently test for non existence OR non-visibility, because OR is not a supported operation.
- Separating the two doesn't really solve the problem you separated them for, because in the case of testing for non-existence, spelling errors will still pass.  This is simply a bug in the code, and not a flaw in the design of the library from my perspective.

Separating existence from visibility in my opinion does not solve any problem that could not already have been solved through better written tests, but it does make a class of tests now impossible to do, forcing developers writing the tests to know exactly how non-visibility of the element is going to be implemented and necessitating changes to the tests if the implementation details ever change.
