### ISSUE TITLE
With v6.0 - Permission error appears

### ISSUE THREAD

**Issue by melibe23** [cypress-io/cypress#9352]
### Current behavior

When updating to v6.0 I get this error when I `npm run cypress:open`

```
`Cypress cannot run because this binary file does not have executable permissions here:

/Users/megarcia/Library/Caches/Cypress/6.0.0/Cypress.app/Contents/MacOS/Cypress

Reasons this may happen:

- node was installed as 'root' or with 'sudo'
- the cypress npm package as 'root' or with 'sudo'

Please check that you have the appropriate user permissions.

You can also try clearing the cache with 'cypress cache clear' and reinstalling.`
```
Mac Catalina

**Comment by miloszatko** [comment]
I've deleted node_modules directory and re-downloaded all depedencies using _npm install_ command.

**Comment by jennifer-shehane** [comment]
@melibe23 Were you able to try the suggestion above?

**Comment by melibe23** [comment]
@jennifer-shehane @miloszatko Thank you for your replies. It didn't work, what it actually worked was to ERASE CYPRESS CACHE. I will close this ticket but leave this comment for other users, if this helps them :)

**Comment by Nazmin1982** [comment]
I am in a similar situation I have no idea what to do; nothing is working 

Nazminaras-MacBook-Pro:Cypress_Automation-main nazminaraali$  npm install cypress --save-dev

up to date, audited 255 packages in 2s

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Nazminaras-MacBook-Pro:Cypress_Automation-main nazminaraali$ npm i

up to date, audited 255 packages in 948ms

40 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Nazminaras-MacBook-Pro:Cypress_Automation-main nazminaraali$ npx cypress open 
Cypress cannot run because this binary file does not have executable permissions here:

/Users/nazminaraali/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/MacOS/Cypress

Reasons this may happen:

- node was installed as 'root' or with 'sudo'
- the cypress npm package as 'root' or with 'sudo'

Please check that you have the appropriate user permissions.

You can also try clearing the cache with 'cypress cache clear' and reinstalling.

----------

Platform: darwin-x64 (19.6.0)
Cypress Version: 9.7.0
Nazminaras-MacBook-Pro:Cypress_Automation-main nazminaraali$
