### ISSUE TITLE
cy.intercept() breaks uploaded image

### ISSUE THREAD

**Issue by AlexCSR** [cypress-io/cypress#9359]
### Current behavior
When using cy.intercept(), an image uploaded has incorrect size and doesn't recognized as image. It's almost 2x more in size than original image.

### Desired behavior
An image uploaded should be the same as the original image.

### Test code to reproduce
Please clone and try: https://github.com/AlexCSR/cypress-intercept-buffer-bug

### Versions
Cypress: 6.0.0

- - -
This issue looks similar to #9166 and only faced with cy.route2() / cy.intercept(), but not with cy.route().

**Comment by jennifer-shehane** [comment]
I am able to recreate the issue from the repo provided.

**Comment by bahmutov** [comment]
Tried Cypress v6.0.1 and the latest `develop` branch, still breaks

Even breaks when simply spying using `cy.intercept`

```js
it.only('spy only', () => {
  cy.intercept('PUT', 'http://localhost:3000/upload'); // only spy on the upload

  cy.visit('http://localhost:3000/');
  cy.get('input').attachFile('image.jpeg');
  cy.get('button').click();
  cy.get('span').should(function ($span) {
    expect($span).to.have.text('SUCCESS')
  });
})
```

The command log shows

<img width="765" alt="Screen Shot 2020-12-03 at 2 41 34 PM" src="https://user-images.githubusercontent.com/2212006/101079595-b049bb80-3575-11eb-80ef-233ff578dc07.png">



Note: the image upload code
```js
var formData = new FormData();
formData.append('image', input.files[0]);
axios.put('http://localhost:3000/upload', formData)
```

**Comment by nickpalmer** [comment]
I just discovered this is ALSO an issue with blob downloads as I was attempting to test a PDF download by parsing the intercepted body, but the PDF parser pukes.

It turns out the intercepted body has way more bytes than the actual API provided, so the bug exists in intercept on both send and receive.

**Comment by nickpalmer** [comment]
I suspect the toString() is incorrect here:
https://github.com/cypress-io/cypress/blob/1c2a17560b704304bef4940aa924b2ad5373c50e/packages/net-stubbing/lib/server/intercept-request.ts#L203

**Comment by pedrojpj** [comment]
Same issue here and continues in version 6.1.0. 

Any progress on fixing it? This prevents the use of intercept in requests with formData.

**Comment by Threnos** [comment]
Me and colleague just spent 4 hours on figuring out why file download request was failing not even getting to back-end. It was cy.intercept that broke request somewhere in the middle (or, maybe, the very moment it was detected).

**Comment by maxbause** [comment]
Hey everyone :wave:, 
I run into the same problem this week, and I found a possible solution/hack.

:warning: Disclaimer: I'm new to cypress source code that's why I have only assumptions and no proof for some statements. if I have assumed something wrong, please correct me.

### The problem
As @nickpalmer mentioned, the issue lies in:  
https://github.com/cypress-io/cypress/blob/f47d5c05749c3ab9c2252f4377b561effb72c42b/packages/net-stubbing/lib/server/intercept-request.ts#L103

The parameter `reqBody` is the original request body represented by a [Buffer](https://nodejs.org/api/buffer.html#buffer_buffer). If this buffer gets encoded with `.toString()` it will be encoded to utf8, since it is the [default](https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end) encoding.

That results in a change of the actual byte length of the request body. 
```js
  request.req.pipe(network_1.concatStream(function (reqBody) {
       request.req.body = frame.req.body = reqBody.toString() 
       console.log("Original content length: ", request.req.headers["content-length"], " Bytes")
       console.log("Binary content length: ", reqBody.byteLength, " Bytes")
       console.log("UTF-8 content length: ", Buffer.byteLength(reqBody.toString(), 'utf8'), " Bytes")
       cb();
  }));
```

```
Original content length: 18135  Bytes
Binary content length: 18135  Bytes
UTF-8 content length: 29223  Bytes
```

Now the `content-length` header is no longer correct, thus resulting in an error on the backend. You might get something like `[ExceptionsHandler] Unexpected end of multipart data`. (NestJS in my case).

### A possible solution
After some manual testing I came across this working solution: 
```ts
  request.req.pipe(network_1.concatStream(function (reqBody) {
      request.req.body = frame.req.body || reqBody.byteLength ? reqBody : undefined
      cb();
  }));
```
It is key to omit `toString()` because trying to encode into a different encoding may work but can/will result in broken files attached to the multipart/form-data form. 

Can anyone give me feedback on this solution? I would be more than willing to make a pull request for it.

Cheers,
Max

**Comment by flotwig** [comment]
@maxbause it sounds like you're on the right track, feel free to open a PR and I can help if you run into any issues
