### ISSUE TITLE
.contains() and .should('not.be.visible') isn't working on and off

### ISSUE THREAD

**Issue by codinghedgehog-python** [cypress-io/cypress#9361]
I've encountered problem where even though HTML elements are shown during the test (I can clearly see them)
Cypress throws:

```
AssertionError: Timed out retrying: Expected to find content: 'User Status' within the element: [ <a.navbar-item>, 3 more... ] but never did.
```

and the element is there.

Also the `('not.be.visible')` works on and off as I've had elements that I couldn't see during test which is expected but this line shouldn't be in red as error.

Using latest stable Cypress release.
Let me know if you need any details.

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Can you provide the HTML and test code to run to see that Cypress is incorrectly not finding the content that is in the DOM?

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by codinghedgehog-python** [comment]
Hi @jennifer-shehane the easiest way to see this problem in action is to download the repo and have GitLab CI runner to build it and run it. Please download the zipped repo here https://www.dropbox.com/s/gguhmjdzu4604cq/flaskondocker-master.zip?dl=1

**Comment by codinghedgehog-python** [comment]
> Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward.
> 
> Can you provide the HTML and test code to run to see that Cypress is incorrectly not finding the content that is in the DOM?
> 
> Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

@jennifer-shehane  I updated my original issue with more details.
