### ISSUE TITLE
Cypress Behind Bluecoat Proxy

### ISSUE THREAD

**Issue by charch** [cypress-io/cypress#939]
- Operating System: Windows 7 Enterprise SP1
- Cypress Version: Beta Version 1.0.3
- Browser Version: Chrome Canary 64.0.3247.0 and Chrome 62.0.3202.94

### Is this a Feature or Bug?
Feature

### Current behavior:
Our application pulls from CDNs for additional CSS libraries. (semantic, react-md, font-awesome), but when running the tests, it cannot connect through the corporate (BlueCoat) proxy leading to missing styles, functionality and slow page loads (it waits for the connections to timeout). 

### Desired behavior:
Add the ability to enter proxy credentials in some way. Perhaps add proxy credentials to the configuration options?

**Comment by MarcLoupias** [comment]
If cypress can't connect to CDN to lazy download some source code, how it works for you in dev mode ?

There is something i cannot get here. If cypress can't reach `cdn.domain.tld` you can't reach it either when running your app locally.

So the issue is in your build not in cypress. You should have a build where everything is local.

You should define more accuratly which test type you want to achieve. What is your context ? Is it local dev test ? CI test ? Something else ?

**Comment by charch** [comment]
It works fine locally because chrome, Firefox and IE all ask for proxy
credentials when we access the internet.

What I would like to see in Cypress is support for corporate proxies so
that we can use Cypress to test our application as it would work in
deployment. Our application is going to be public facing, and proxies will
not affect CDNs if those people can reach our page in the first place.

Just a note, I can use http_proxy and https_proxy environment variables for
my proxy and credentials. When those variables are set though, Cypress
fails to connect to localhost. I tried setting the variable NO_PROXY, but
Cypress still couldn't connect to localhost.

**Comment by bahmutov** [comment]
Hmm if using Chrome browser works by itself, try running Cypress not in its built electron browser, but using chrome ?

**Comment by charch** [comment]
I have. In Chrome + Cypress, I can get the app to load (only if http_proxy
and https_proxy are unset), but the CDNs won't load. I do not get a
credentials popup like I normally do. I assume this because this instance
of chrome is set to use Cypress as the proxy instead of the corporate
proxy, and Cypress does not request credentials.

**Comment by MarcLoupias** [comment]
You should definitely have a purely local build version to run the tests against. 

Relying on external service makes your tests unstables (the cypress team loves the term "flaky"). 

Anytime a problem will occur at your cdn provider or at a network level your tests will fail. They should not.

IMHO your best bet is to try mocking your CDN provider with `cy.server`, `cy.route` and `cy.fixture`.

Check the part named *"Change the default whitelisting"* from the [`cy.server` API doc](https://docs.cypress.io/api/commands/server.html#Options) to remove the source code assets whitelisting.

You will be able to remove : 
- the proxy settings needs
- the "flakyness" from your tests

And you can try this right now.

**Comment by thejones** [comment]
I am using Cypress to test against another product called Web AppBuilder from Esri (It generates web mapping applications). Because of this dependency it wants/needs to download assets from a CDN to get the ArcGIS JavaScript API. Behind a corporate proxy I am unable to load the application as it fails trying to request the resources. On an outside network it is fine. So, the idea that e2e testing could not use CDN code in unrealistic. If I cannot connect to the ArcGIS API the application wont work anyway. Clearly if everything is local it is better and I am not arguing that, I am just saying that sometimes you need to connect to CDN resources. 

Anyway, I have the same issues. If we go to Esri's web site: https://developers.arcgis.com/web-appbuilder/

We can grab a public facing sample: 
http://gis.calhouncounty.org/ParcelViewer3.1/

My test file
```js
describe('My First Test', function() {
    //Works
    it('Visits the Kitchen Sink', function() {
      cy.visit('https://example.cypress.io')
    })
    //fails
    it('Visits the jsapi site', function() {
      cy.visit('http://gis.calhouncounty.org/ParcelViewer3.1/')
    })
  })
````

I am not 100% if that site *should* work but I get the same behavior with my local apps running on localhost. Hopefully this is somewhat helpful...

This is on Windows 7, latest (LTS) version of Node.

**Comment by BasieP** [comment]
+many on the NO_PROXY setting... it should work, but cypress ignores it  :(

**Comment by jennifer-shehane** [comment]
Can ya'll try to set `HTTP_PROXY` and/or `HTTPS_PROXY` to your corporate proxy as system/shell environment variables? I detailed some of this fix here: https://github.com/cypress-io/cypress/issues/1469#issue-305961859

**Comment by NickStees** [comment]
I have been looking around the various proxy related issues, and experimented alot. I want to report I am also behind a BlueCoat proxy, I have `HTTP_PROXY` and `HTTPS_PROXY` set to our bluecoat proxy. To make it more complicated we use a [PAC file](https://help.zscaler.com/zia/what-pac-file) but this is a pretty common setup for Governments.  Basically we have proxy problems with just about every piece of software, especially if its trying to get `https` resources. We usually have to set our software to `verify_ssl=FALSE` in order to get things to work. Is that something Cypress can work in?
