### ISSUE TITLE
Cypress-Cant execute calculation

### ISSUE THREAD

**Issue by stick710** [cypress-io/cypress#9420]
I have problem testing some WebApp with cypress. App has button "RUN", and when it is clicked it pops out alert "put some variables in rows and columns". When I put some variables into fields and then again click "RUN" it should execute calculations and put result in "grid". But in tests when I click on "RUN" button it starts the calculations, and shows -(xhr) POST 500 /crosstab/execute- and he never finishes calculations and put it in grid view.

I dont have source code for app, im using inspect to finds selectors. Button works and shows alert when fields for row and column are empty, but when it needs to start calculating something in going wrong. And that problem show only when Cypress is doing that, on the actual WebApp all functions are working fine.
![Screenshot_2](https://user-images.githubusercontent.com/48359709/100881325-1408b180-34ae-11eb-98b4-45566511c817.png)
![Screenshot_3](https://user-images.githubusercontent.com/48359709/100881327-14a14800-34ae-11eb-96af-8f86cabec3d8.png)
![Screenshot_4](https://user-images.githubusercontent.com/48359709/100881329-1539de80-34ae-11eb-8172-b33b051b325d.png)

Alert "No message available" is never popping out in real app, only in cypress.
Results of calculation should be in Grid after clicking on button "RUN"

**Comment by jennifer-shehane** [comment]
From the information given, I would suggest:

- Make sure you update to the [current version of Cypress](https://on.cypress.io/changelog). Your issue may have already been fixed.
- Check the Developer Tools for any errors in the console, this may give a clue as to the issue within Cypress.

Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by stick710** [comment]
@jennifer-shehane Well, I can provide you my code, but I would love if it could be private. Is it possible somehow ? Thank you for your time!

**Comment by stick710** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/48359709/100991689-94cdb900-3553-11eb-9d20-5f994b5fb930.png)

**Comment by stick710** [comment]
That first ERROR is happening on the actual cite too. This second one "Internal Server Error" is happening only in Cypress. And I think that is reason why calculations cant be finished in Cypress, but I don't know how to fix that.

**Comment by stick710** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/48359709/101013535-bf743d80-3564-11eb-99c4-43594513d61e.png)
There are requests of both

**Comment by stick710** [comment]
@jennifer-shehane I found something out so if you could contact me so i could explain to you my problem in details. sevarikamilan97@gmail.com im stuck 3 days at this, so it would be nice if we could sort something up! Thank you on your time!

**Comment by stick710** [comment]
@jennifer-shehane I realized what was the problem! Every single task that I wanted to check I wrote on new ' it() ' and site couldn't work like that, so I merged all that under on ' it() ' and now tests and site are work fine under Cypress
