### ISSUE TITLE
Trigger hover to check a tooltip with Angular (v5) and Material

### ISSUE THREAD

**Issue by maxime1992** [cypress-io/cypress#953]
- Operating System: Ubuntu 17.10 - 64 bits
- Cypress Version: 1.1.1
- Browser Version: Chrome 62.0.3202.89

### Is this a Feature or Bug?
Not sure :)

### Current behavior:
I cannot display a tooltip built with Angular Material

### Desired behavior:
Trigger hover to show the tooltip

### How to reproduce:
Here's a stackblitz repro with the editor:  
https://stackblitz.com/edit/angular-material2-issue-iyyert

And the same but just the app running into the browser:  
https://angular-material2-issue-iyyert.stackblitz.io

#### Test code:

```js
  cy.get('span').invoke('trigger', 'mouseover');
  cy.get('mat-tooltip-component').contains('Tooltip!');
```

### Additional Info (images, stack traces, etc)
Related to #10

**Comment by brian-mann** [comment]
Using `invoke('trigger')` is simply calling the "trigger" method on the jquery wrapped DOM element. Since angular isn't bound to jquery events, that's why its not triggering.

You never have to do this anymore, because our own (and very real) `cy.trigger()` now exists and works in every situation you would have otherwise used `invoke('trigger')`.

Change to that and it will work.

I have updated my comments on that old issue, and we have lots of docs in many places explaining this.

https://github.com/cypress-io/cypress/issues/10#issuecomment-346436968

**Comment by azollai** [comment]
It was only working to me with .trigger('mouseenter'). None of 'mouseover' and 'hover' was working. 

Also: be sure that you are getting the right element with the tooltip directive before your .trigger call :)

**Comment by ganeshkadam111** [comment]
cy.get('span').invoke('trigger', 'mouseover'); 
working for me

**Comment by palakdua27** [comment]
@azollai , still not working for me :-
cy.get('[data-testid="SortByTitle"]').trigger('mouseenter')

**Comment by maxime1992** [comment]
@brian-mann you said:

> You never have to do this anymore, because our own (and very real) cy.trigger() now exists and works in every situation you would have otherwise used invoke('trigger').

But [Cypress doc](https://docs.cypress.io/api/commands/hover.html#Workarounds) seems to have a different opinion on that:

![image](https://user-images.githubusercontent.com/4950209/97689459-e5a54a00-1a9b-11eb-8212-643b8bef42b4.png)

And it still isn't working for me. Could we reopen this issue please?
