### ISSUE TITLE
Build failing for firefox when run for cypress using command line

### ISSUE THREAD

**Issue by alokverma75** [cypress-io/cypress#9532]
Hi,

I am trying to run testcases from run command to upload results to dashboard but build is failing:
```
SecurityError: Permission denied to access property "addEventListener" on cross-origin object  on accessing the URL
```
but the test run well when run using open command for cypress version 6.0.1

```
 .\node_modules\.bin\cypress run --browser firefox --headless --spec \"cypress/integration/OnlineWeb/* \" 
```

**Comment by jennifer-shehane** [comment]
In the future, when opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

The issue is likely relevant to the test you're running in Firefox. Please provide a reproducible example that we can run to see this error in 6.0.1. (What version was this previously working in also?)

**Comment by jennifer-shehane** [comment]
Right now there doesn't seem to be enough information to reproduce the problem on our end. We'll have to close this issue until we can reproduce it. This does not mean that your issue is not happening - it just means that we do not have a path to move forward. 

Please comment in this issue with a reproducible example and we will consider reopening the issue. Here are some tips for providing a [Short, Self Contained, Correct, Example](http://sscce.org/) and our own [Troubleshooting Cypress](https://on.cypress.io/troubleshooting) guide.

**Comment by shirshendu30** [comment]
I am using Cypress 7.4.0 and seeing the same issue. Is there any work around to bypass this error?

**Comment by shirshGit** [comment]
I am using 7.4.0 for Cypress. Is there any workaround or settings in Firefox so that it can be bypassed.

**Comment by shirshGit** [comment]
@alokverma75 Thanks Alok. It worked. But funny thing is that , after that when I changed it back to Standard also its working fine.
Thanks anyway.
