### ISSUE TITLE
Apex page not fully loading

### ISSUE THREAD

**Issue by trip-S** [cypress-io/cypress#9550]
Cypress test runner loads the application page but dropdown data and calendar on the page are not loaded/displayed.

I have checked this manually and it works fine outside cypress.
I have checked this on Electron which also has the same issue.
I have downgarded chrome from 87 to 83 but without any luck.

There are JavaScript error and here are the console log extract,
```
-----------------------------------------
desktop_all.min.js?v=19.2.0.00.18:sourcemap:2 Uncaught TypeError: The following error originated from your application code, not from Cypress.
  > apex.da.initDaEventList is not a function

HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
-----------------------------------------
```

I have searched the full directory and there is no such function used anywhere.

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

We'll need a reproducible example in order to see why this error is occuring.

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.
