### ISSUE TITLE
Video recording not working on dashboards anymore

### ISSUE THREAD

**Issue by neilmatillano** [cypress-io/cypress#9585]
When running tests connected to the dashboards, the video doesn't seem to record properly the tests
https://dashboard.cypress.io/projects/f9z6ef/runs/293/specs

**Comment by jennifer-shehane** [comment]
@neilmatillano There was an issue with Cypress due to Chrome 87 update where the videos would freeze/be blank detailed here: https://github.com/cypress-io/cypress/issues/9265

This issue was resolved in Cypress 6.0.1. You will need to update Cypress to 6.0.1+. If for some reason you cannot update to the latest Cypress version, the other alternative would be to downgrade Chrome to 86 until you can upgrade Cypress.
