### ISSUE TITLE
Incorrect evaluations for contain when using `should('not.exist')`

### ISSUE THREAD

**Issue by calendee** [cypress-io/cypress#960]
Sample Test Case : https://github.com/calendee/cypress-contains-should-not-exist

- Operating System: macOS 10.12.6
- Cypress Version: 1.1.1
- Browser Version: Chrome 62.0.3202.94 

### Is this a Feature or Bug?
Bug

### Current behavior:
When testing for content that should not exist using `contains`, Cypress evaluates the test incorrectly and always passes.

Asserting `cy.get('div').contains('Test Paragraph').should('not.exist');` incorrectly tests `div :not(script):contains('Test Paragraph'), [type='submit'][value~='Test Paragraph']`

### Desired behavior:
Cypress should evaluate the assertion as written.

### How to reproduce:
See sample test case.  When it is run, review the tests and assertions

#### Test code:
See sample test case

### Additional Info (images, stack traces, etc)
<img width="1909" alt="cy-test-contains-issue" src="https://user-images.githubusercontent.com/57374/33242833-70c576ce-d2a0-11e7-865f-7d72afb78619.png">

**Comment by brian-mann** [comment]
I'm not seeing how this is actually incorrect. I looked at your repo as well but I can't tell exactly what you're saying is wrong.

Are you saying that the visual expectation reads incorrectly? Are you saying it should be passing and its not?

To me - the test asserts that given the div, it should not contain the text 'Test Paragraph'. After you've removed it, this is true and the test passes.

The assertion gives you that long selector string because under the hood **that is exactly what contains is doing**. That's why it displays that way.

There isn't another way to display it because there's no way to stringify an element in the case where it does not exist. So we fallback to displaying the selector used so you get a context of what the underlying query was.

**Comment by calendee** [comment]
Why would it use a selector that appears to use an `input` element of type `submit` when there is no such element on the page?

If this is not a real issue, what is the correct way to assert that the paragraph should not exist?

**Comment by brian-mann** [comment]
The query is actually saying this:

- within any `<div>`
  - find any element that contains the text content `Test Paragraph` excluding `<script>` elements
  - OR find any `input` with the value containing `Test Paragraph`

It's an "or" not an "and". `cy.contains()` finds inputs because those do not have `textContent` they have `value`.

**Comment by brian-mann** [comment]
I believe you *have* correctly written the assertion - and it is passing because there is nothing on the page that has that content.

**Comment by calendee** [comment]
I think I understand what you're saying now.  It's looking for any div that contains "Test Paragraph" and/or any input/submit that contains it.  

Thanks for clarifying.
