### ISSUE TITLE
Video & Screenshot artifacts not recorded properly

### ISSUE THREAD

**Issue by remjx** [cypress-io/cypress#9652]
There is a video artifact in my Cypress Dashboard that says the test ran for 5 seconds and that the video is 5 seconds long, but when I play it, the video lasts for under 1 second.

Also, there are no screenshots captured for the successful test run.

https://dashboard.cypress.io/projects/gjafub/runs/1/test-results/9dd89182-aea0-4bef-8ac7-9e43eb0d2837

**Comment by jennifer-shehane** [comment]
Please make sure to update to the [current version of Cypress](https://on.cypress.io/changelog). There was an issue https://github.com/cypress-io/cypress/issues/9265 with video recordings in Chrome 87 (and Electron 87) with frozen videos that was fixed in 6.0.1. I think this is likely the issue you're seeing.

**Comment by remjx** [comment]
Yes upgrading fixed it. Thanks!
