### ISSUE TITLE
Support React Dev Tools

### ISSUE THREAD

**Issue by pedroteixeira** [cypress-io/cypress#9656]
Hello,

Adding the following in the _mount_ function allows the React Dev Tools to work inside the iframe:
```
     <script>
      if (window.parent !== window) {
          window['__REACT_DEVTOOLS_GLOBAL_HOOK__'] = window.parent['__REACT_DEVTOOLS_GLOBAL_HOOK__'];
      }
     </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/16.2.0/umd/react.development.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.2.0/umd/react-dom.development.js"></script>
```

Perhaps it's useful for more people to have it by default.

**Comment by lmiller1990** [comment]
Hi all.

We just released Cypress 7.0, which comes with a completely revamped Component Testing experience. Component testing is no longer experimental (but still in alpha, with lots of updates and improvements coming in the next few weeks). Please let us know if you find any more issues.

Updated Component Testing intro: https://docs.cypress.io/guides/component-testing/introduction
Changelog: https://docs.cypress.io/guides/references/changelog
Migration guide: https://docs.cypress.io/guides/references/migration-guide#Component-Testing

Main updates:

- things are now (much) faster, since we use  dev-server and hot reload architecture, not file:preprocessor
- no need to launch into the electron shell. It opens straight to the browser (select your spec from the inline spec selector)
- dedicated, component specific runner (build on top of the existing runner, so you get all the good stuff you are used to)

Upgrading should not be too difficult, see the [migration guide](https://docs.cypress.io/guides/references/migration-guide#Component-Testing).

To make sure Webpack 5 is working, I made a minimal example with [Babel + Webpack 5 + React + Cypress 7.x + 

One of the many improvements is the react devtools are now embedded *in* the runner.

![image](https://user-images.githubusercontent.com/19196536/113673266-1bf68d80-96fc-11eb-9518-49986b44e562.png)

Note that they don't play super nicely with hot reload, sometimes you will need to cmd+R to force them to update, but it's still a big improvement over the existing solutions. Things will get better as we iterate. 

Anyone interested in this, please update to Cypress 7.0 using the migration guide and give it a try. Devtools support is getting better and will continue to do so 🎉

**Comment by jennifer-shehane** [comment]
Closing as resolved.

**Comment by piotrpalek** [comment]
@jennifer-shehane sorry to comment on this old issue, but with the newest (10.x) versions of Cypress, are react devtools also included / supported? I'm having trouble using them.

**Comment by lmiller1990** [comment]
@piotrpalek It's not built in like the 9.x alpha had - those were quite buggy and had some known usability problems.

In he future, I hope we can 1) support it in a more first class way and 2) expose some kind of API for people to build Cypress UI plugins (which could include some kind of bridge to communicate w/ the iframe and connect to things like React/Redux dev tools) at some point.

As of 10.x the React dev tools are not shipped, but you should be able to still set it up (I definitely remember people working with Cypress + React Devtools as far back as 7.x).
