### ISSUE TITLE
Speed up a preparation phase of the following test

### ISSUE THREAD

**Issue by daedalius** [cypress-io/cypress#9663]
Hi Gleb!
Yesterday I've already experimented with the v4 version and noticed that tests run slow enough.

For example: git@github.com:daedalius/cypress-react-test.git
Here are 10 copies of the same test. I run them in a row:
```
npm run test:ci
```

On the timeline it takes:
* ~12 seconds for the Cypress start (it is ok. But for the cold start after Windows restarting it takes ~34 seconds)
* ~3 seconds for the first test preparation 🤔
* less than a second to run it (it is ok too)

and so on:
* ~3 seconds for next test preparation 🤔
* less than a second to run it

Total times:
Windows:
>1:08 for the cold start after Windows restart
>0:42 for the next run

mac os:
>0:38 for the cold start after a system reboot
>0:34 for the next run

The output says that clean test time is 3 seconds (around ~0.3 per test).
**Is there any way to speed up the test preparation phase?**

You know, I am in love with Cypress and this repo in particular. But it's hard to debate with colleagues who argue that Jest does 500 tests in 20 seconds. 

This is maybe important:
* I've noticed in the Windows Task Manager that Antimalware Service Executable activates during the test run (especially for the cold one after restart).
* Specs: 
	Windows: Ryzen 2600x, NVME, Windows 10 build 1809
	Mac: MacBook Pro 2019, i7 6-cores 2.6 - 4.5 GHz, SSD

**Comment by taninnazar** [comment]
Hello @bahmutov , could you, please, update us how thing are going with fixing this issue ?

**Comment by bahmutov** [comment]
Things are going great and soon it will be faster than lightning

**Comment by AndrewSouthpaw** [comment]
This brings me much excitement. Thanks for all your hard work!

**Comment by denis-domanskii** [comment]
@bahmutov did you experiment with concurrent run? I mean not cypress dashboard, but native mocha --parallel, on a single machine? I understand why Dashboard-like parallelization exists for e2e tests, but since Cypress trying to cover component and unit tests - probably you need to revise parallelization politic and allow it for non e2e? It's a default for Jest/Mocha/Ava and other unit-test frameworks. I have seen [cypress-parallel](https://github.com/tnicola/cypress-parallel) project, but native solutions are always better :)

**Comment by denieler** [comment]
@bahmutov do you maybe have some rough estimations regarding those improvements? maybe we can help somehow?

**Comment by JessicaSachs** [comment]
Hey folks, this was fixed in the major rewrite we did to use your webpack dev server instead of rebuilding with the preprocessor from scratch every time. You’ll need to read the migration guide here: https://docs.cypress.io/guides/references/migration-guide#Component-Testing

**Comment by Thaval** [comment]
Could you make this work for vue too?
I started component testing today and the preparation to test one component takes more than 5 minutes. Gotta admit, it's a big projects with lots of dependencies and stuff, but component/unit testing should be fast.
There needs to be some kind of caching I guess.

**Comment by JessicaSachs** [comment]
> Could you make this work for vue too?
> I started component testing today and the preparation to test one component takes more than 5 minutes. Gotta admit, it's a big projects with lots of dependencies and stuff, but component/unit testing should be fast.
> There needs to be some kind of caching I guess.

Hey @Thaval, can you tell me what you mean by "the preparation to test one component"? Is this before the browser launches or during the loading spinner within Chrome?

In normal usage, we heavily cache the webpack builds + babel dependency graph across multiple launches. The performance of Cypress CT should be equal to that of your normal dev server setup. If you're stuck on the loading spinner in the browser while the component compiles and it's taking longer than your normal dev server, then your webpack setup is probably building for production, or is otherwise unoptimized.

If the browser hasn't launched yet and you're just waiting for your terminal to boot, it's probably due to an issue on Big Sur. To check if you have this issue, run the command `DEBUG=cypress:* yarn cypress open-ct` and see how long it takes before any logs print out. Another way to check if it's your OS or your build step is to [try one of our boilerplates](https://github.com/cypress-io/cypress-component-examples) The Vite ones should start up within 1.5 seconds. The webpack ones will take a little longer (~2-5 seconds).

**Comment by Thaval** [comment]
Hi, 
with "preparation to test one component" I meant the build time and the startup of the browser. I just see the loading dots but nothing happens. You're absolutely right, my production build setup is not optimized and I'm not able to do so as it's not my responsibility, officially. 
So I will try and optimize the build. 
But isn't there an option to skip the build and simply call "yarn serve" or something like that? When I think about the minifying steps and such, I would not be able to debug (maybe I would need some kind of SourceMaps?).

**Comment by Thaval** [comment]
Is it possible to tell cypress which command within package.json it should use to build?

**Comment by JessicaSachs** [comment]
Which command... what do you mean? For questions, chat on [Discord](https://on.cypress.io/discord)
