### ISSUE TITLE
Specs preparing time is too long

### ISSUE THREAD

**Issue by taninnazar** [cypress-io/cypress#9673]
Currently I've added 16 specs with tests (61 test) in my project. I'm running them in headless Chrome. As a result if believe cypress - tests running time is up to 50sec  (45sec usually) what is very cool result, as for me, because it's taking and comparing screenshot in most of the tests. But whole time starting from "npx cypress run" command and till all pass takes more than 7 mins (up to 8 min sometimes). I see that after spec finishes it takes 20-25 sec to start another one. We will have approximately 4 times more tests in nearest future and waiting for about 30-35 minutes to run 250 component tests is not nice and hardly comparable to jest+enzyme where 250 tests are running up to 60 sec all together. 
![specs_running_time](https://user-images.githubusercontent.com/11903748/87314379-c9e95880-c52b-11ea-92f6-f2a472d6cdbc.png)

P.S. sometimes while tests are running I'm getting node errors like this - 
![node_error](https://user-images.githubusercontent.com/11903748/87313900-39127d00-c52b-11ea-8df2-466742f67272.png)

@bahmutov  Please, take a look to this

OS: Windows
Cypress Version 4.10.0
cypress-react-unit-test 4.9.0

**Comment by lmiller1990** [comment]
Hi all! I have some updates.

We just released Cypress 7.0, which comes with a completely revamped Component Testing experience. Component testing is no longer experimental (but still in alpha, with lots of updates and improvements coming in the next few weeks). Please let us know if you find any more issues. 

[Updated Component Testing intro](https://docs.cypress.io/guides/component-testing/introduction). [Changelog](https://docs.cypress.io/guides/references/changelog). [Migration guide](https://docs.cypress.io/guides/references/migration-guide#Component-Testing) <- this is probably most important for anyone wanting to upgrade.

The main difference is we moved from a `file:preprocessor` architecture to a dev-server architecture. Component testing is no longer experimental, and has a dedicated runner (which is build on top of an extends the existing cypress runner). Open mode, once initially started and bundled, is VERY fast. It will only rebuild the component + spec file relevant, not the rest of the bundle.
 
Upgrading should not be too difficult, see the [migration guide](https://docs.cypress.io/guides/references/migration-guide#Component-Testing).

Regarding speed improvements, the initial bundle will always take some amount of time, since... all the files need to be bundled to execute all the tests. 25s second per spec just seems crazy though, this is definitely not expected. I am guessing with Enzyme + Jest you are not using webpack at all, but some kind of Jest transformer, so it sounds like Webpack is the problem here. 

Is either of your projects open source? I'll do my best to help you upgrade if you run into any problems. This should give you a speed improvement, by how much , I can't say without been able to debut your setup. I am sure we can do better than 30s / spec. I am currently running around 100 specs files, each with varying amounts of tests, in around 3 minutes: https://app.circleci.com/pipelines/github/cypress-io/cypress/18667/workflows/e79205fa-735e-46b1-9297-cc28fc9e7122/jobs/675896/parallel-runs/0/steps/0-104. Source for those [is found here](https://github.com/cypress-io/cypress/tree/develop/npm/react/cypress/component).

Now we finally finished moving from experimental component testing to a proper public alpha with a dedicated component testing runner, I really want to start aggressively improving performance.

**Comment by jennifer-shehane** [comment]
Closing as resolved. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new/choose) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
