### ISSUE TITLE
Loading custom webpack config expects an object, not just an environment name

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress#9678]
According to Webpack 4.x docs https://webpack.js.org/configuration/configuration-types/#exporting-a-function the webpack.config.js file can export a function. That function takes `env` object as first argument

For some reason our current implementation passes `development` string as `env`, but the `env` config should be an object

```
module.exports = function(env, argv) {
  env.production //
}
```

`env` should have properties from https://webpack.js.org/api/cli/#environment-options

**Comment by lmiller1990** [comment]
I may be misunderstanding or missing some context here - do we need to fix/change something? Seem this is probably not relevant anymore, since now you pass your entire webpack config as of 7.x and the implementation is completely different:

https://github.com/cypress-io/cypress/blob/df8cb0345f7b09f393b442ac9b9cbc549eee0f23/npm/react/cypress/plugins/index.js#L69

as the argument `webpackConfig` in the `startDevServer` function.

If I am missing something please re-open.
