### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by alvarosaburido** [cypress-io/cypress#9682]
Hi guys, awesome library, wanted to ask which branch has the code for using this library with vue3? (there is `feature/bundled-support-vue-3` and `feature/vue-3-dist`).

Also, something that can help your users, is having a `next` branch with an npm `next` channel with the support for  Vue3 until is stable enough to merge it into main.

Thanks in advance

**Comment by lmiller1990** [comment]
Hello @alvarosaburido,

We have Vue 3 support with the newly release component testing runner! [See this blog post for more information](https://www.cypress.io/blog/2021/04/06/getting-start-with-cypress-component-testing-vue-2-3/). The example provided uses Vue 2, but Vue 3 works just fine as well - only difference is you do `yarn add @cypress/vue@next`. 

Let me know if you run into any troubles, so far I'm working on a little design system with Vue + Cypress 7 + component testing and it's working really well.

**Comment by alvarosaburido** [comment]
Hello @lmiller1990  Awesome stuff, I'm just checking it looks amazing, great job! 

I do have a minor issue, using Typescript. 
<img width="1671" alt="Screenshot 2021-04-08 at 10 50 50" src="https://user-images.githubusercontent.com/4699008/113997317-4f4e2f00-9858-11eb-8a38-8042aa7e2d41.png">

In the example we need to register the `dev-server:start` event and tell Cypress to use the same Webpack configuration as the Vue CLI project uses.

```
const { startDevServer } = require('@cypress/webpack-dev-server')
const webpackConfig = require('@vue/cli-service/webpack.config.js')

module.exports = (on, config) => {
  on('dev-server:start', options =>
    startDevServer({
      options,
      webpackConfig
    })
  )

  return config
}
```

I guess that Vue CLI  webpack config is not  using typescript loaders

My question would be, how you can add `aliases`, `vue.config.js`  options o the webpack used by  the  test  runner, for example using  a  third party lib like Quasar

Thanks, and again, awesome  stuff

**Comment by lmiller1990** [comment]
That doesn't seem like a minor issue, it seems like a huge problem! Let's fix it.

As long as your webpack config has TS support, it should "just work".

Can you share your config or project? I don't have enough information to guide you. What do you think the problem is? Seems like some file is not getting found during the resolution of modules. The `@` alias is working for me, even with a lazy loaded component: https://github.com/lmiller1990/vue-cypress-template/blob/4cf5fee31e6ed5d8197b28bd8b4cf6d1688355a9/src/components/ClickToLazyLoad.vue#L18

**Comment by alvarosaburido** [comment]
Hey there @lmiller1990 thanks for the quick response. I manage to use the Cypress Component Test Runner in a very simple `vue-cli` project (similar to the example repo you posted [here](https://github.com/lmiller1990/vue-cypress-template)). 

> As long as your webpack config has TS support, it should "just work".

For the code that I was asking for (is private so I can't share it) ---> The solution was to install `@vue/cli-plugin-typescript`, since the project is actually using `Vite` instead of `vue-cli` I just added the `vue-cli` dependencies for the `@cypress/webpack-dev-server`  to work. 

However, I'm going through the [docs](https://docs.cypress.io/guides/component-testing/introduction#Install) to use a custom WebpackConfig similar to the one I'm using for Storybook to stop depending on `vue-cli` deps. 

Is there an example similar to the repo you shared using webpack directly instead of `vue-cli`. That would be helpful.

Thanks again and congrats, I really love it.

**Comment by lmiller1990** [comment]
Ohhhh damn, if you are using Vite boy do I have some news for you @alvarosaburido!

We haven't advertised or made this public yet because we are still getting it stable, but we have a [vite-dev-server](https://github.com/cypress-io/cypress/tree/develop/npm/vite-dev-server) implementation. [This repo on the cypressify branch](https://github.com/lmiller1990/vue-30/tree/cypressify) has a working example.

It's still a work in progress but you are welcome to give it a try - if you do and find any bugs, shoot me or @elevatebart a message or make an issue. Again this isn't something we are making public since it's still needs some polish but you are welcome to try it out!

**Comment by alvarosaburido** [comment]
Omg, Chritsmas came earlier 🤩.
