### ISSUE TITLE
webpack 5 assets don't play nicley with cypress-react-unit-test

### ISSUE THREAD

**Issue by glomotion** [cypress-io/cypress#9697]
For some reason, even inlined assets don't get rendered. 

![Screen Shot 2020-11-12 at 12 35 26 pm](https://user-images.githubusercontent.com/1452237/98884195-a20eff00-24e3-11eb-877f-89152ec93834.png)

```
// ./webpack.config.js

...
{
    test: /\.(png|jpe?g|gif|svg|eot|ttf|woff|woff2)$/i,
    type: 'asset', // sets assets to be automatically resourced. cypress fails when i make this 'asset/resource'. Some error about automatic public path. :(
},

```

deps: 
```
"cypress": "^5.5.0",
    "cypress-react-unit-test": "^4.16.0",
    "typescript": "^4.0.5",
    "webpack": "^5.1.3",
    "webpack-cli": "4.2.0",
    "webpack-dev-server": "^3.11.0"
```

**Comment by lmiller1990** [comment]
This should be fixed in Cypress 7.0. I posted about that [in your other issue](https://github.com/cypress-io/cypress/issues/15569#issuecomment-813813742). 

I was able to get it working in my test project:

- [Image.jsx](https://github.com/lmiller1990/cypress-react-webpack-5-example/blob/master/src/Image.jsx)
- [Image.spec.jsx](https://github.com/lmiller1990/cypress-react-webpack-5-example/blob/master/src/Image.spec.jsx)
- [webpack.config.js](https://github.com/lmiller1990/cypress-react-webpack-5-example/blob/c798bdcf4d5ec410786a286b4e17963963161c42/webpack.config.js#L31). I used the exact line you provided with `type: 'asset'`, thanks for that.

Let me know if it isn't working for you.
