### ISSUE TITLE
Parcel support?

### ISSUE THREAD

**Issue by mekhami** [cypress-io/cypress#9699]
Any interest or plan for supporting parcel as a plugin for building components instead of webpack?

**Comment by midanosi** [comment]
For when this issue is worked on, it's worth mentioning that the bahmutov's old parcel-preprocessor library is for parcel v1.
Parcel v2 is out now (though technically still in beta, and I don't know how usage compares to v1), and I think it would require a rewrite to support.

I did briefly try using that old repo for preprocessing for @cypress/react, but I couldn't get it to work. Haven't got any extra information worth adding on top of that, but I thought I should share that at least one attempt with it has been made.

**Comment by jennifer-shehane** [comment]
Closing for CT team to re-evaluate is they want to support parcel.
