### ISSUE TITLE
support integration and component tests colocation

### ISSUE THREAD

**Issue by tannera** [cypress-io/cypress#9705]
Hello, thanks for your great work on this plugin for Cypress.
Is there any plans to support integration & component tests being colocated in the same root folder, with some sort of glob matcher for integration & components tests in `cypress.json`?

```
{
  "integrationFiles": "**/__e2e__/*cy.ts",
  "componentFiles": "**/__tests__/*.cy.tsx",
}
```

```
src
│
└───searchbar
│   │   Searchbar.tsx
│   └───__e2e__
│   |   │   Searchbar.cy.ts // using cypress 
│   └───__tests__
│       │   Searchbar.cy.tsx // using cypress-react-unit-test

```

**Comment by midanosi** [comment]
It's worth mentioning that you could already achieve this with cli --spec flag to use globs.
I've done this in my current codebase where we've put all unit tests in a new folder 'cypress/unit', so the opposite of yourself!

But I support your request to define test location by globs in config file rather than cli.



Off-topic: I would say it's a bit strange to have an e2e test living in a component folder by default. I can see how you could center an e2e test around the idea of component, but by definition an e2e test is run against a whole deployed app. This isn't a criticism, it's just what comes to my mind.

**Comment by lmiller1990** [comment]
Hi @tannera,

I have some updates on this request.

Firstly, we just released Cypress 7.0, which comes with a completely revamped Component Testing experience. Component testing is no longer experimental (but still in alpha, with lots of updates and improvements coming in the next few weeks).

- Updated Component Testing intro: https://docs.cypress.io/guides/component-testing/introduction
- Changelog: https://docs.cypress.io/guides/references/changelog
- Migration guide: https://docs.cypress.io/guides/references/migration-guide#Component-Testing

We now have a dedicated component testing runner (which builds on top of the existing runner, but has some changes like not needing to launch the electron app to select a spec, and using a dev-server architecture instead of file:preprocessor, making it a (lot) faster.

As your your request, since we now have a component testing specific runner, we support [runner specific config](https://docs.cypress.io/guides/references/configuration#Runner-Specific-Overrides). You can specify `component` in `cypress.json` for component testing specific overrides. eg:

```json
{
  "testFiles": "cypress/integration/**/*.spec.js",
  "component": {
    "componentFolder": "src",
    "testFiles": "**/*.spec.ts"
  }
}
```

This will apply a different test glob for component tests (when launching component testing via `yarn cypress open-ct`. There is no way to actually *know* if a spec file is meant to be executed as a component testing or an e2e test, though, so you'll need to find some way to differentiate the two. You could do:

```json
```

**Comment by tannera** [comment]
thanks a lot, looks great!

**Comment by lmiller1990** [comment]
I'll close this since we have a solution. Let me know if run into any problems or have any ideas to make it better.
