### ISSUE TITLE
cypress-vue-unit-test, does support components that use vue-property-decorator and TS?

### ISSUE THREAD

**Issue by warheartvik** [cypress-io/cypress#9719]
Hello,

My components are writen using typescript and vue-property-decorator and I'm getting this error trying to write unit testing with cypress on my project. 

>./pages/persona/frmPersona.vue?vue&type=script&lang=ts& (./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/persona/frmPersona.vue?vue&type=script&lang=ts&) 262:0
>Module parse failed: Unexpected character '@' (262:0)
>You may need an appropriate loader to handle this file type.
>| import { ApiPersona } from '~/servicios/persona/ApiPersona';
| 
> @Component({
|     components:{
|         comSexoSeleccionar,
 @ ./pages/persona/frmPersona.vue?vue&type=script&lang=ts& 1:0-179 1:195-198 1:200-376 1:200-376
 @ ./pages/persona/frmPersona.vue
 @ ./cypress/integration/frmPersona.spec.js
 @ multi ./cypress/integration/frmPersona.spec.js

Any idea, anyone?

If the solution is a loader, what would be?

Please advise!

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by Emrald-TA** [comment]
I am facing the same issue as shown above. Since the plugins folder is deprecated since Cypress >= 10.0.0, I am not sure how exactly to add this in component testing. I did find the webpack config file generated by vue-cli and used that in the component section of the `cypress.config.ts`. But that did not resolve the issue. Kindly advise on how to proceed.
