### ISSUE TITLE
Parallel tests have started failing with we do not parallelize tests across different environments

### ISSUE THREAD

**Issue by Risen-Solutions** [cypress-io/cypress#9744]
This is coming out of a Gitlab CI/CD job that ran perfectly ~6 days ago, and the job hasn't be altered in any way since that time. There are 3 machines in job each of which is passing in the same parameters (see below). There is no data in the dashboard related to this job.

This machine sent the following parameters:
```js
{
  "osName": "linux",
  "osVersion": "Debian - 10.2",
  "browserName": "Firefox",
  "browserVersion": "81.0",
  "specs": [
    .... 13 specs are listed here.
  ]
}
```

Interestingly, an earlier job that also runs in parallel across 3 machines completed perfectly. In this case it is running in electron 87 (headless) rather than Firefox (see below).

```
  │ Cypress:      6.0.0                                                                            │
  │ Browser:      Electron 87 (headless)                                                           │
  │ Specs:        13 found (...)                                                            │
  │ Params:       Tag: false, Group: false, Parallel: true                                         │
  │ Run URL:      https://dashboard.cypress.io/.......                        │
  │ Experiments:  experimentalComponentTesting=true       
```

Given that the CI/CD file hasn't changed, and that these runs have worked flawlessly when last run in full (as well as an earlier parallel run), something must have changed on the Cypress side that is blocking the running in Firefox over last few days. Has there been an update on the backend that I am not taking account of?

Phoenix

**Comment by jennifer-shehane** [comment]
The browser that Cypress is run within is not decided by a backend, but it only decided by the `--browser` flag (or lack of) passed to `cypress run`. 

If the `--browser` flag was not recognized for some reason, maybe the args are malformed or not being read in one machin, this would cause Cypress to run in the default browser of Electron. 

Cypress will not regard a run as a 'single' run across environments, ie - different browsers, different browser major versions, different specs arrays. Every `cypress run` that you want to be considered as a single run parallelized needs to be run on the same browser, running the same `specs`, same OS.

I would suggest rechecking the `cypress run` command in those runs, seeing that the flags were parsed correctly and also checking if anything else may have changed in the commit when this started happening.

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by malt-man** [comment]
I'm also seeing this issue - sometimes with the above mentioned error and sometimes without any error showing in the GitHub action logs at all. It just looks like tests are not executing at all and no test run shows up on Cypress Dashboard.

The issue appears to be happening when running the same workflow in succession. The first run is ok but if a second run is triggered later then the issue occurs.

Please let me know what info would help with investigating this.

**Comment by itorres-github** [comment]
At the moment ,  same issue is occurring when running 2 jobs with same configuration under same workflow.

The first job always thrown the  message: "You passed the --parallel flag, but we do not parallelize tests across different environments." and fails.

The second job is running perfectly fine.

Is there any known workaround  ?

**Comment by muratkeremozcan** [comment]
Sporadic issue, has been hard to reproduce internally, yet alone get an external repro so that the Cypress team can help. But, I tell you, you will not get help until it is reproduced in an open repo.

**Comment by malt-man** [comment]
> same. any known workaround? @itorres-github @malt-man ?

@choonkeat 
This was a while ago but I seem to remember that there may have been an issue with how our GitHub action workflows were configured. What exactly that was I can't seem to recall.

Sorry I know this doesn't really help you 🙂

**Comment by choonkeat** [comment]
My solution was https://github.com/cypress-io/cypress/issues/7199#issuecomment-1143628102

**Comment by tiagodread** [comment]
We've seen this too and I could identify why:

1. Our environment is exactly the same since we run the tests in self-hosted runners at GitHub actions
2. We use `cypress-grep` plugin to organize our runs in 3 groups: `smoke`, `sanity` and `regression`. 
  - smoke: small set of tests just to make sure the application under test is not on 🔥, **we have a single test in this group**.
  - sanity: all important/critical test cases 
  - regression: everything else + corner cases
3. We split our specs in 8 machines using the matrix strategy

I noticed that by the time that the machine `#1` is up and get the first spec (from smoke group) to run and others machines to be provisioned and get the remaining specs (starting from sanity group this time) the array of "specs" is now different, since the spec in matter was previously executed by machine `#1` 😵‍💫

**Comment by ArturMiszkowicz** [comment]
@tiagodread did you got it to work with `cypress-grep`?

**Comment by marc-niclas** [comment]
Just started running into this issue this morning. Here's what I'm seeing in ci/cd:

`"browserVersion": "132.0.6834.83.... (Expected: 131)",`

However, I don't see a way to specify the browser version in the GH action config. It looks like 2/6 machines picked 131, whereas the rest picked 132. 

This is a big problem for us because not only does it now take forever to complete on just a few machines but it also breaks our visual testing tool, which is waiting for the status of 6 parallel machines to be reported before running visual regression analysis.

**Comment by jennifer-shehane** [comment]
@marc-at-brightnight Cypress will not parallelize a single run across multiple major browser versions. GH Actions updates the browser at a specific time, so this timing could mean some of your tests run in 131 and some run in 132. We error in this case because the environement is so different. We ourselves can have the same thousands of tests run in 131 and then those tests fail in 132. So this is an intentionaly decision that Cypress has made to fail in this case. 

You would have to reference a docker container with an explicit browser version to ensure a consistent environment in GH actions.

**Comment by justAdevTV** [comment]
@marc-at-brightnight I had the same issue as you. The Cypress docs suggest that:

> If you specify a browser in parallel mode, we recommend using a [Cypress Docker image](https://docs.cypress.io/app/continuous-integration/github-actions#Testing-with-Cypress-Docker-Images) to pin the browser version used.
Source - https://docs.cypress.io/app/continuous-integration/github-actions#Specifying-Browsers-in-Parallel-Builds

Cypress Browser Container docs - https://github.com/cypress-io/cypress-docker-images/tree/master/browsers

I ended up adding this to to the workflow job:
```
container:
      image: cypress/browsers:node-22.13.1-chrome-132.0.6834.83-1-ff-134.0.2-edge-132.0.2957.115-1
```

You can find the tags to use here - https://hub.docker.com/r/cypress/browsers/tags

I hope this helps!

**Comment by marc-niclas** [comment]
Those images lack some of the packages installed on the default GitHub runners so we ended using the following to install latest Chrome. This step only takes 17s to install:
```
      - name: setup latest stable version of chrome browser
        run: |
          wget -q -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
            && sudo apt install -y --allow-downgrades /tmp/chrome.deb \
            && rm /tmp/chrome.deb
```
